RIOT-OS/RIOT

- examples/default/Makefile
The nrf52840dongle was not in the default example as having a radio. But it does.
So I added it to the list.
When the default example is compiled for board nrf52840dongle.  
Then the network stack is included.
And the board shows its radio information using `ifconfig`.
> example/default: add nrf52840dongle to BOARD_PROVIDE_NETIF

- boards/same54-xpro/Makefile.dep
- boards/same54-xpro/board.c
- boards/same54-xpro/include/board.h
- drivers/at24cxxx/mtd/mtd.c
- drivers/at25xxx/mtd/mtd.c
- drivers/include/mtd.h
- drivers/mtd/mtd.c
- drivers/mtd_mapper/mtd_mapper.c
- drivers/mtd_mci/mtd_mci.c
- drivers/mtd_sdcard/mtd_sdcard.c
- makefiles/pseudomodules.inc.mk
- pkg/fatfs/fatfs_diskio/mtd/mtd_diskio.c
- pkg/littlefs/fs/littlefs_fs.c
- pkg/littlefs2/fs/littlefs2_fs.c
- tests/mtd_raw/Makefile
- tests/mtd_raw/main.c
The `mtd_write_page()` function will do a 'raw write' to the underlying memory device.
That means for flash based  storage, it will only do 1 -> 0 bit writes while 0 -> 1 writes are ignored.
This is the behavior that e.g. SPIFFS expects (used there for 'blind writes').
For some applications a more high level view is required where any bit write pattern should result in the requested data being written to the storage device.
For flash based storage, this means a read - modify - write cycle is necessary where a whole flash sector is copied to RAM, modified, erased and re-written.
This PR introduces a `mtd_write_page()` function that will do just that (or fall back to `mtd_write_page_raw()` if the storage supports direct writes, e.g. in the case of EEPROM).
The work area is allocated …
> mtd: rename mtd_write_page() -> mtd_write_page_raw(), add high-level mtd_write_page()

- cpu/nrf52/radio/nrf802154/nrf802154.c
- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
- cpu/nrf5x_common/clock.c
- cpu/nrf5x_common/include/nrf_clock.h
- cpu/nrf5x_common/radio/nrfble/nrfble.c
- cpu/nrf5x_common/radio/nrfmin/nrfmin.c
Currently, we enable the external high frequency crystal (`HFXO`) as clock source for the nRFs high frequency clock (`HFCLK`) during CPU initialization per default. With the `HFXO` constantly enabled the CPU is however prevented to to into proper power saving states when idle. Further this external clock source is only needed for some selected peripherals (e.g. `radio`) or some specific peripheral configurations (e.g. `UART` with baudrate >> 500kbps). So the better solution is to not enable this clock source by default, but let the peripherals/drivers request that clock source on demand.
This PR introduces 2 changes:
- add two functions to request/release the `HFXO`
- disable the `HFXO` by default, however, keeping the option to enable it during boot setting the `CLOCK_HFXO_ONBOOT` define …
> cpu/nrf5x: enhance external HF clock source handling to allow for substantial energy savings

- tests/ieee802154_submac/main.c
Adds a check for the return value of the `recv` function, since it may return an error, and the code could read past the end of the buffer. Noticed it on IEEE 802.15.4g frames when sending a frame of a size higher than expected.
- `make -C tests/ieee802154_submac flash` on two boards, and send frames with `txtsnd`, should work as before.
> tests/ieee802154_submac: check netdev_driver_t::recv return value

- boards/qn9080dk/Kconfig
- boards/qn9080dk/Makefile.features
- boards/qn9080dk/include/periph_conf.h
- cpu/qn908x/doc.txt
- cpu/qn908x/include/periph_cpu.h
- cpu/qn908x/periph/adc.c
The ADC in the QN908x cpu offers multiple options for ADC conversion using up to 8 external pins, one external reference pin and some internal signals like a 1.2V reference, Vss, Vcc and an internal temperature monitor.
This patch implements support for sampling ADC values from the ADC lines defined in the board configuration. Some configurations are really always present and don't require a board configuration, like the Vcc or internal temperature monitor but to coexist with other board ADC line options they are only set as part of the board configuration.
There are some limitations in what's implemented in this ADC module as outlined in the adc.c documentation. Namely the ADC block support a whole lot of more settings, but this patch implements enough to make it work for the common use …
> cpu/qn908x: ADC support

- cpu/qn908x/periph/adc.c
The macro was moved from Kconfig to the periph_cpu.h which means that
the macro name needed to be updated to BOARD_HAS_ADC_PA06_CAP instead
of CONFIG_BOARD_HAS_ADC_PA06_CAP.
Built `tests/periph_adc` with `BOARD_HAS_ADC_PA06_CAP` defined.
> cpu/qn908x: Fix BOARD_HAS_ADC_PA06_CAP usage.

- boards/qn9080dk/Kconfig
- boards/qn9080dk/Makefile.dep
- boards/qn9080dk/Makefile.features
- boards/qn9080dk/board.c
- boards/qn9080dk/include/board.h
- boards/qn9080dk/include/periph_conf.h
- cpu/qn908x/Kconfig
- cpu/qn908x/Makefile.features
- cpu/qn908x/doc.txt
- cpu/qn908x/include/gpio_mux.h
- cpu/qn908x/include/periph_cpu.h
- cpu/qn908x/periph/spi.c
- drivers/lis2dh12/lis2dh12.c
This patch implements the basic support the last of the FLEXCOMM modes,
Serial Peripheral Interface, in a simple blocking mode with busy wait,
which is enough to test all the SPI functionality end-to-end.
Tested reading and writing registers on a SPI peripheral, and checked
with the oscilloscope that the frequencies were as expected.
Results from `tests/periph_spi`:
```
> init 0 0 2 -1 0
SPI_DEV(0) initialized: mode: 0, clk: 2, cs_port: -1, cs_pin: 0
> bench
1 - write 1000 times 1 byte:			16002	16009
2 - write 1000 times 2 byte:			18001	18008
3 - write 1000 times 100 byte:		802000	802007
4 - write 1000 times 1 byte to register:	24003	24010
5 - write 1000 times 2 byte to register:	26001	26008
6 - write 1000 times 100 byte to register:	810001	810008
7 - read 1000 times 2 byte:			23003	23009 …
```
> cpu/qn908x: Implement blocking SPI support

- tests/pkg_libcose/tests/01-run.py
- tests/pkg_wolfcrypt-ed25519-verify/tests/01-run.py
- tests/pkg_wolfssl/tests/01-run.py
- tests/suit_manifest/tests/01-run.py
This PR increases the timeout value of some of the test scripts: `tests/pkg_libcose`, `tests/pkg_wolfcrypt-ed25519-verify`, `tests/pkg_wolfssl` and `tests/suit_manifest`. They all succeed but require quite some time on nrf51dk which is quite slow.
These applications are failing in the [test-on-iotlab action](https://github.com/RIOT-OS/RIOT/runs/1759015809?check_suite_focus=true) because of a timeout. There are other tests failing in test-on-iot-lab but some should now be fixed and other are working when run manually., let's wait for the next run (next sunday).
~~I'm not sure if I should set the `CI: Ready for CI build` label, since there shouldn't be any build failures with this PR and I could run the tests locally without issues. I let the reviewer decide :)~~
Verify that the test target …
> tests: increase timeout for nrf51dk

- cpu/stm32/Makefile.include
The ram size is exposed as macro value (`CPU_RAM_SIZE`) and available for use in code.
For the stm32 it has a value in kilobytes suffixed with 'k'. This is
less than optimal for usage in arithmetic. This commit modifies the
value to bytes so that it can be used in preprocessor magic
`CPU_RAM_SIZE` is only used by `sys/include/riotboot/usb_dfu.h` so far.
This should not affect the current builds.
Remotely required for #15420
> stm32: Resolve RAM size to bytes

- cpu/kinetis/Kconfig
- cpu/kinetis/kinetis-info.mk
I think this CPU was added before RIOT had support for the FPU on Cortex-M4F, this should now have been long fixed.
Advertise the FPU on these CPUs.
I don't have a board with this CPU to test.
`tests/thread_float` should still work on affected boards (`frdm-k22f`).
> cpu/kinetis: enable floating point support

- drivers/ina3221/ina3221.c
- drivers/ina3221/ina3221_saul.c
- drivers/include/ina3221.h
- drivers/saul/init_devs/auto_init_ina3221.c
This fixes some compatibility issues with C++. C++ is more strict about enum conversions. I've added some type casts and removed enums as parameters where non-enum values are allowed.
This also adds the INA3221 to the SAUL docs (there was the group entry missing) and fixes a typo in the auto-init header.
The return values and parameter values keep all the same. The public interface does not change nor any internal method behavior. Even the binary should stay the same.
@fabian18
@maribu
> drivers/ina3221: Fix compatibility with C++

- drivers/include/periph/flashpage.h
- drivers/periph_common/flashpage.c
- sys/riotboot/flashwrite.c
As the title says, this removes the last references to `FLASHPAGE_SIZE` from the riotboot code.
Use either the `tests/riotboot_flashwrite` test or the `examples/suit_update` application to test this.
required for #15420
> riotboot/flashwrite: Remove last dependencies on flashpage size

- cpu/stm32/periph/gpio_all.c
In case a non-gpio EXTI (>= 16) is pending, the isr_exti() used to clear
the flag and try to call a callback, which was out-of-bouds, thus
generating a hard fault.
This fixes it by masking the pending_isr variables with 0xFFFF.
#14564
> cpu/stm32/gpio: fix EXTI flag clearing

- cpu/stm32/Makefile.features
- cpu/stm32/include/cpu_conf.h
- cpu/stm32/kconfigs/f2/Kconfig
- cpu/stm32/kconfigs/f4/Kconfig
- cpu/stm32/kconfigs/f7/Kconfig
- cpu/stm32/periph/flash_common.c
- cpu/stm32/periph/flashpage.c
- tests/periph_flashpage/main.c
- tests/unittests/tests-flashpage/tests-flashpage.c
This adds periph_flashpage support to the stm32f2, f4 and f7 families. Due to the non-uniform flashpage sizes some magic has to be applied to erase and write the correct sectors.
`tests/periph_flashpage` should succeed. stm32f4 devices with 1MB and 2MB flash use a dual bank architecture. This should be tested as well.
~~Depends on #15412~~
> stm32f{2,4,7}: Initial flashpage support

- cpu/stm32/periph/gpio_all.c
In case a non-gpio EXTI (>= 16) is pending, the isr_exti() used to clear
the flag and try to call a callback, which was out-of-bouds, thus
generating a hard fault.
This fixes it by masking the pending_isr variables with 0xFFFF.
#14564
> cpu/stm32/gpio: fix EXTI flag clearing [backport 2021.01]

- cpu/mips32r2_common/include/cpu.h
- cpu/mips_pic32_common/periph/gpio.c
If no `clz` instruction is available in hardware, the operation will be implemented in software by a series of shifts.
When iterating over all bits in a word, this is sub-optimal as in will create O(n²) shift operations instead of O(n).
Instead of implementing the logic in the platform driver, use a common helper function to simplify the code.
In the case where `clz` is available, the generated code should not differ from the one in `master`.
GPIO interrupts should still work
To verify, connect two GPIOs and run the `auto_test` command (from `tests/periph_gpio`) on them.
depends on #14556
> cpu/mips_pic32_common: GPIO: use bitarithm_test_and_clear()

- pkg/fatfs/Makefile
- pkg/fatfs/patches/0001-remove-ffconf.h.patch
- pkg/fatfs/patches/0002-remove-diskio.c.patch
- pkg/fatfs/vendor/include/ffconf.h
A new version has been [released](http://elm-chan.org/fsw/ff/updates.txt).
Update our pkg accordingly.
`tests/pkg_fatfs_vfs` should still pass.
> pkg/fatfs: bump version to r0.14a

- boards/arduino-duemilanove/Makefile.include
- boards/arduino-leonardo/Makefile.include
- boards/arduino-mega2560/Makefile.include
- boards/arduino-nano/Makefile.include
- boards/arduino-nano/doc.txt
- boards/arduino-uno/Makefile.include
- boards/avr-rss2/Makefile.include
- boards/common/atmega/Makefile.include
- boards/derfmega128/Makefile.include
- boards/derfmega256/Makefile.include
- boards/mega-xplained/Makefile.include
- boards/waspmote-pro/Makefile.include
This PR is a cleanup of the BOOTLOADER/BOOTLOADER_SIZE/BOOTLOADER_BAUD variable used on some atmega platform.
It remove the IMHO useless pattern:
```mk
BOOTLOADER_<board name> ?= bootloader
BOOTLOADER ?= $(BOOTLOADER_<board name>)
```
And add an `ATMEGA_` to all these atmega specific variables (only used in boards/common/atmega).
Try to flash the affected boards (but should be harmless).
Noticed that while reviewing #15884
> boards/atmega: cleanup BOOTLOADER variables definitions

- sys/include/ztimer.h
- sys/ztimer/util.c
- tests/ztimer_rmutex_lock_timeout/Makefile
- tests/ztimer_rmutex_lock_timeout/Makefile.ci
- tests/ztimer_rmutex_lock_timeout/app.config.test
- tests/ztimer_rmutex_lock_timeout/main.c
- tests/ztimer_rmutex_lock_timeout/tests/01-run.py
Similar to xtimer_rmutex_lock_timeout().
The test app is essentially a copy of xtimer_rmutex_lock_timeout test app.
> ztimer: add ztimer_rmutex_lock_timeout()

- sys/arduino/SPI.cpp
- set `is_transaction` before releasing the SPI bus (and the mutex) to avoid data races
- adapt switch indent to coding convention
This is trivial enough that IMO code review and CI should be sufficient.
None
> sys/arduino: Bug and style fixes in SPI

- Makefile.dep
- boards/common/e104-bt50xxa-tb/Makefile.dep
- bootloaders/riotboot/Makefile
- cpu/cc2538/Makefile.default
- cpu/cc2538/Makefile.dep
- cpu/efm32/Makefile.default
- cpu/efm32/Makefile.dep
- cpu/esp32/Makefile.default
- cpu/esp32/Makefile.dep
- cpu/kinetis/Makefile.default
- cpu/kinetis/Makefile.dep
- cpu/lpc1768/Makefile.default
- cpu/lpc1768/Makefile.dep
- cpu/lpc23xx/Makefile.default
- cpu/lpc23xx/Makefile.dep
- cpu/sam0_common/Makefile.default
- cpu/sam0_common/Makefile.dep
- cpu/samd21/Makefile.default
- cpu/samd5x/Makefile.default
- cpu/saml1x/Makefile.default
- cpu/saml21/Makefile.default
- cpu/stm32/Makefile.default
- cpu/stm32/Makefile.dep
- cpu/stm32/include/periph_cpu.h
- cpu/stm32/periph/pm.c
- sys/Makefile.dep
- sys/include/pm_layered.h
This makes `pm_layered` a `DEFAULT_MODULE` so it can be disabled.
This is useful to squeeze down the size of riotboot, which does not need pm functionality.
`riotboot` should still work.
In fact, also normal applications should still work. I tested this with `examples/default` and it will operate just normal, albeit consuming more power as it's now busy looping instead of idling when no thread is scheduled.
split off #15493
> cpu: make pm_layered a DEFAULT_MODULE

- cpu/stm32/periph/flashpage.c
#15420 removes the setting where the PER bit is reset (switched to programming) after an erase, this puts it back in for CPU's with no PNB.
- ` BOARD=iotlab-m3 make -C examples/suit_update/ flash test-with-config -j3`
passes again.
> cpu/stm32/flashpage: reset PER after erase

- pkg/nimble/netif/nimble_netif.c
Minor fix: the internal _send_pkt() function now returns a distinct return value in the case that an internal NimBLE error occurred while sending. This makes debugging a little bit simpler...
Build test should be enough, as the return value is not explicitly used in any upstreamed code...
none
> pkg/nimble/netif: improve _send_pkt() error return value

- sys/include/shell.h
- sys/shell/Kconfig
- sys/shell/shell.c
- tests/gnrc_tcp/Makefile
- tests/test_tools/Makefile
- tests/test_tools/main.c
This documents the compile time configurations of the shell interpreter module, and models them in Kconfig. Although the previous macros were not documented I marked them now as deprecated, favoring the `CONFIG_` version of them.
- `tests/test_tool`, `tests/shell` should work as usual
- The changed applications should work
- You should be able to configure via menuconfig or `CFLAGS`
- The deprecated macros should still work
Part of #12888
> sys/shell: document configs and add them to Kconfig

- sys/include/shell.h
- sys/shell/Kconfig
- tests/gnrc_tcp/Makefile
- tests/test_tools/Makefile
This modifies the `menuconfig` symbol of shell to adhere to the naming convention. Also, in tests that use CFLAGS to change shell parameters a check for Kconfig is added.
- When using Kconfig and enabling `KCONFIG_USEMODULE_SHELL` CFLAGS in the changed tests should not conflict
- Check that the symbol name now follows [the convention](http://doc.riot-os.org/kconfig-in-riot.html#kconfig-transition-phase) on prefixes.
#15918
> sys/shell: rename Kconfig symbol to adhere to convention

- pkg/nimble/Makefile.dep
Minor fix: the `nimble_autoconn` module uses the `random` module, but this dependency was missing in `pkg/nimble/Makefile.dep`. Now its fixed :-)
Build test should do.
none
> pkg/nimble/autoconn: add missing 'random' dep

- sys/uri_parser/uri_parser.c
- tests/unittests/tests-uri_parser/tests-uri_parser.c
Before attempting to access the `://` part of the URI it is necessary to check that the URI is long enough to actually contain this string and data following it. Otherwise, a read outside the bounds of the provided buffer is performed if the buffer is too small.
Application code:
```C
#include <stdlib.h>
#include <stdint.h>
#include <uri_parser.h>
#define BUFFER_SIZE 5
static char buf[] = { 112, 80, 58, 47, 47, };
int main(void)
{
size_t len = sizeof(buf);
uri_parser_result_t result;
uri_parser_process(&result, buf, len);
return 0;
}
```
Makefile:
```Makefile
APPLICATION = uri
DEVELHELP = 1
BOARD = native
USEMODULE += uri_parser
```
Run:
```
$ make -C examples/uri all-asan
$ make -C examples/uri term …
```
> uri_parser: check if uri is long enough to even contain a ://

- sys/include/net/ieee802154/radio.h
- sys/include/net/ieee802154_security.h
- sys/net/link_layer/ieee802154/security.c
This PR does two things:
1. **Removes duplicated definitions that were added to the radio HAL, which are already defined in `ieee802154_security.h`**
The shortcut functions are removed from the radio HAL. After a discussion with @jia200x, a `ieee802154_sec_context_t` will likely find a place on the newly introduced submac later on. For now, as radios that use the radio HAL are still accessed via the `netdev_ieee802154_submac`, the current status will still work. This allows to remove an avoidable dependency and reduce code duplication.
2. **Makes the default implementations of the cipher operations of ieee802154_security private**
This makes the API of the module simpler, as the fallback implementations are kept private. Now the default cipher operations driver holds `NULL` pointers, …
> net/ieee802154_security: remove radio hal dependency and cleanup

- pkg/wakaama/patches/0021-core-registration-cast-to-time.patch
There seems to be some issue on native (which may involve certain versions of toolchains, see #15870 and #15878), that leads to floating point exceptions when using some packages. This adds a patch to the wakaama package to cast a float macro to `time_t`, which seems to fix the issue.
- Follow the instructions in `examples/wakaama`. Check that with current master the node raises an exception when the registration is triggered. With this PR it should work normally.
Maybe related to #15870 and #15878
> pkg/wakaama: add patch to cast macro to time_t

- cpu/riscv_common/include/thread_arch.h
This should resolve the issues mentioned [here](https://github.com/RIOT-OS/RIOT/pull/15718#issuecomment-774248134). The thread_yield_higher function now checks if it is executed from interrupt context and just set the `sched_context_switch_request` flag if it is in interrupt context.
These tests should work again:
- tests/event_wait_timeout
- tests/thread_flags 
- tests/thread_flags_xtimer.
Fixes regressions mentioned [here](https://github.com/RIOT-OS/RIOT/pull/15718#issuecomment-774248134)
> riscv_common: make thread_yield_higher IRQ compatible

- sys/Makefile.dep
- sys/include/net/gnrc/nettype.h
- sys/include/net/gnrc/tx_sync.h
- sys/net/gnrc/Makefile
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/network_layer/sixlowpan/frag/gnrc_sixlowpan_frag.c
- sys/net/gnrc/pktbuf/gnrc_pktbuf.c
- sys/net/gnrc/sock/gnrc_sock.c
- sys/net/gnrc/tx_sync/Makefile
- sys/net/gnrc/tx_sync/gnrc_tx_sync.c
- tests/gnrc_tx_sync/Makefile
- tests/gnrc_tx_sync/Makefile.ci
- tests/gnrc_tx_sync/main.c
- tests/gnrc_tx_sync/tests/01-run.py
The new `gnrc_tx_sync` module allows users of the GNRC network stack to synchronize with the actual transmission of outgoing packets. This is directly integrated into gnrc_sock. Hence, if `gnrc_tx_sync` is used, calls to e.g. sock_udp_send() will block until the network stack has processed the message.
Use cases:
1. Prevent packet drop when sending at high rate
- If the application is sending faster than the stack can handle, the message queues will overflow and outgoing packets are lost
2. Passing auxiliary data about the transmission back the stack
- When e.g. the number of required retransmissions, the transmission time stamp, etc. should be made available to a user of an UDP sock, a synchronization mechanism is needed
3. Simpler error reporting without footguns
- The current approach …
> sys/net/gnrc/tx_sync: new module

- cpu/stm32/include/cpu_conf.h
- drivers/include/periph/flashpage.h
- sys/riotboot/flashwrite.c
This PR addresses two issues with `riotboot_flashwrite_invalidate`:
- writing `0XAA` to invalidate will no always work, e.g. for stm32f1:
> In this mode the CPU programs the main Flash memory by performing standard half-word
write operations. The PG bit in the FLASH_CR register must be set. FPEC preliminarily
reads the value at the addressed main Flash memory location and checks that it has been
erased. If not, the program operation is skipped and a warning is issued by the PGERR bit in
FLASH_SR register (the only exception to this is when 0x0000 is programmed. In this case,
the location is correctly programmed to 0x0000 and the PGERR bit is not set). If the
addressed main Flash memory location is write-protected by the FLASH_WRPR register,
the program operation is skipped and a warning …
> sys/riotboot/flashwrite: when invalidating erase checksum as well 

- tests/cpp11_condition_variable/Makefile
- tests/cpp11_condition_variable/main.cpp
On small platforms the test is hard-faulting because of RAM, using one less thread makes it fit on more platforms and IMO does not impact the test coverage.
Otherwise I can add the `BOARD` (`nucleo-f334r8`) to `Makefile.ci`
Test now passes
`BOARD=nucleo-f334r8 make -C tests/cpp11_condition_variable/ flash test -j3`
```
main(): This is RIOT! (Version: 2021.04-devel-67-g6d9af0b-pr_cpp11_condition_variable_test)
************ C++ condition_variable test ***********
Wait with predicate and notify one ...
Done
Wait and notify all ...
Done
Wait for ...
Done
Wait until ...
Done
Bye, bye.
******************************************************
```
>  tests/cpp11_condition_variable: reduce thread number

- cpu/native/Kconfig
- cpu/native/Makefile.features
- cpu/native/include/cpu.h
- cpu/native/include/cpu_conf.h
- cpu/native/periph/flashpage.c
Add a simple RAM-backed flashpage implementation for native, to allow for easier testing of flashpage based applications / features.
`tests/periph_flashpage` can now be tested with `native`
> cpu/native: add periph/flashpage implementation

- makefiles/features_check.inc.mk
Previously, FEATURES_REQUIRED_ANY didn't honor the order of the alternatives
provided, if none of the features were already in used and multiple options
are provided. This fixes this.
See https://github.com/RIOT-OS/RIOT/pull/15855#issuecomment-773471032
Found in https://github.com/RIOT-OS/RIOT/pull/15855
> build system: fix FEATURES_REQUIRED_ANY

- boards/adafruit-itsybitsy-m4/Kconfig
- boards/adafruit-itsybitsy-m4/Makefile
- boards/adafruit-itsybitsy-m4/Makefile.dep
- boards/adafruit-itsybitsy-m4/Makefile.features
- boards/adafruit-itsybitsy-m4/Makefile.include
- boards/adafruit-itsybitsy-m4/board.c
- boards/adafruit-itsybitsy-m4/doc.txt
- boards/adafruit-itsybitsy-m4/include/board.h
- boards/adafruit-itsybitsy-m4/include/gpio_params.h
- boards/adafruit-itsybitsy-m4/include/periph_conf.h
- boards/common/samd21-arduino-bootloader/Makefile.include
- boards/same54-xpro/Kconfig
- cpu/samd5x/Kconfig
- pkg/wolfssl/include/user_settings.h
This adds support for the [Adafruit ItsyBitsy M4 Express](https://learn.adafruit.com/introducing-adafruit-itsybitsy-m4?view=all), a small board based on the SAM D51G19A MCU.
It uses Adafruit's UF2 bootloader and comes with a 2 MiB QSPI Flash, a single DotStar (APA102) RGB LED and not much else.
I tested all the peripherals:
- `tests/periph_uart`
- `tests/periph_i2c`
- `tests/periph_spi` - this one requires a patch to always enable MOSI mux on `spi_aquire()`, will be provided as a separate PR
- `tests/periph_adc`
- `tests/periph_pwm`
- `tests/mtd_raw`
- `tests/pkg_littlefs2`
- `tests/driver_apa102`
#15846 is needed for SPI to work
> boards: add adafruit-itsybitsy-m4

- dist/tools/pyterm/pyterm
- tests/shell/main.c
Currently, when the prompt is read in `pyterm` the space after it is ignored for the prompt and the output command just adds its own prompt. This leads to the next output always having a leading space, see e.g. this output from `tests/shell` using `RIOT_TERMINAL=pyterm`:
```
make: Entering directory '/home/mlenders/Repositories/RIOT-OS/RIOT2/tests/shell'
/home/mlenders/Repositories/RIOT-OS/RIOT2/dist/tools/pyterm/pyterm -p "/dev/ttyUSB1" -b "500000"
2021-02-09 14:47:15,071 # Connect to serial port /dev/ttyUSB1
bufsize
2021-02-09 14:47:19,712 # bufsize
2021-02-09 14:47:19,712 # 128
> bufsize
2021-02-09 14:47:21,535 #  bufsize
2021-02-09 14:47:21,536 # 128
>
``` …
> pyterm: read space after prompt into prompt

- tests/driver_hih6130/main.c
This PR fixes a minor issues with a couple of calls of `abs` in `tests/driver_hih6130`. This function expect an int as input but a float is given. This leads to an error with gcc 10 (on riscv).
The proposed fix is to cast it to an int. It's untested but now it builds fine.
- If someone has the sensor, it would nice to have this PR tested on it
- The build succeeds on gcc 10 riscv:
<details><summary>this PR:</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=atmega256rfr2-xpro -C tests/driver_hih6130/ --no-print-directory Launching build container using image "riot/riotbuild:latest".
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT-review:/data/riotbuild/riotbase:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e …
```
> tests/driver_hih6130: fix 'absolute-value' error

- dist/tools/uncrustify/whitelist.txt
- sys/include/riotboot/flashwrite.h
- sys/include/riotboot/slot.h
- sys/riotboot/flashwrite.c
- sys/riotboot/flashwrite_verify_sha256.c
- sys/riotboot/hdr.c
- sys/riotboot/slot.c
- sys/riotboot/usb_dfu.c
While looking at #15912 I realized riotboot files were full of uncrustify issues. To ease reviewing I prefered to split uncrustify changes out and add it to the whitelist.
- green Murdock
- binaries should not have changed
Waiting for #15912
> sys/riotboot: uncrustify

- boards/cc1350-launchpad/Kconfig
- boards/cc1350-launchpad/Makefile
- boards/cc1350-launchpad/Makefile.dep
- boards/cc1350-launchpad/Makefile.features
- boards/cc1350-launchpad/Makefile.include
- boards/cc1350-launchpad/board.c
- boards/cc1350-launchpad/dist/cc13x0f128_XDS110.ccxml
- boards/cc1350-launchpad/dist/cc13x0f128_XDS110.dat
- boards/cc1350-launchpad/dist/cc13x0f128_gdb.conf
- boards/cc1350-launchpad/dist/openocd.cfg
- boards/cc1350-launchpad/doc.txt
- boards/cc1350-launchpad/include/board.h
- boards/cc1350-launchpad/include/gpio_params.h
- boards/cc1350-launchpad/include/periph_conf.h
- cpu/cc26xx_cc13xx/include/periph_cpu_common.h
- examples/dtls-sock/Makefile.ci
- examples/gnrc_border_router/Makefile.ci
- examples/javascript/Makefile.ci
- examples/lua_REPL/Makefile.ci
- examples/lua_basic/Makefile.ci
- tests/bench_xtimer/Makefile
- tests/gnrc_dhcpv6_client_6lbr/Makefile.ci
- tests/gnrc_netif/Makefile.ci
- tests/pkg_tinydtls_sock_async/Makefile.ci
- tests/pkg_utensor/Makefile.ci
- tests/unittests/Makefile.ci
Adds the definitions for the TI CC1350 LAUNCHXL board, including the SAUL gpio params (verified with `examples/saul` and `tests/saul`).
~~By the way, `add_insufficient_memory_board` is still running so this is expecting a rebase :-)~~. Done
- Run `./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py` for `cc1350-launchpad`.
Depends on #15944
> boards: add cc1350 launchpad

- makefiles/features_check.inc.mk
Fix `FEATURES_REQUIRED_ANY` using more features than needed.
Test provided in https://github.com/RIOT-OS/RIOT/pull/15973 should now pass.
Bug introduced in https://github.com/RIOT-OS/RIOT/pull/15957, fix suggested in https://github.com/RIOT-OS/RIOT/pull/15957#discussion_r573128263
> build system: fix feature resolution

- pkg/openwsn/sock/openwsn_sock_udp.c
- tests/pkg_openwsn_sock_udp/main.c
There where two problems related to the implementation of `sock_udp_close`:
1. messages where not removed from the mailbox and therefore not removed from `openqueue` after closing a `sock`
2. possible race conditions if a `sock` was closed while iterating through its linked 
Added a unittest for 1 and add check to make sure the mbox is empty before closing.
Addressed 2 by wrapping linked list access with a mutex. I'm unsure if there is still a race condition if `sock_udp_close()` is called in an ISR or by a thread with higher priority just before the asynchronous callback happens.
- `make -C tests/pkg_openwsn_sock_udp/ flash test -j3`
- take a close look at the possible race condition
> pkg/openwsn/sock: fix sock_udp_close handling

- sys/clif/clif.c
- tests/unittests/tests-clif/tests-clif.c
While the for-loop condition does contain a bounds check, the pointer is independently increment in the for-loop body. This increment therefore requires a separate bounds check. Otherwise, the parsing loop may access data outside the given buffer boundaries.
Sample application code:
```C
#include <stdlib.h>
#include <stdint.h>
#include <clif.h>
static uint8_t buf[] = { 59, 196, 198, 196, 196, 196, 196, 196, 196, 61 };
int main(void)
{
char *input = (char *)&buf[0];
clif_attr_t attr;
clif_get_attr(input, sizeof(buf), &attr);
return 0;
}
```
Minimal `Makefile`:
```Makefile
APPLICATION = clif
BOARD = native
USEMODULE += clif
```
Invoke as:
```
$ make -C examples/clif all-asan
$ make -C examples/clif term …
```
> clif: After incrementing pos, make sure it is still in bounds

- tests/driver_bq2429x/_util.h
This PR fixes a small enum conversion bug in `tests/driver_bq2429x`. The fix is quite obvious, the parameter of one of the helper function expects a bq2429x_chrg_fault_t but it is declared as bq2429x_chrg_stat_t.
This raises a build failure when building with gcc 10 on risc-v.
A green Murdock.
The build doesn't fail when building with gcc 10 on risc-v:
```
$ BUILD_IN_DOCKER=1 make BOARD=hifive1b -C tests/driver_bq2429x --no-print-directory 
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT-review:/data/riotbuild/riotbase:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' -e …
```
> tests/driver_bq2429x: fix implicit conversion in helper function

- sys/include/ztimer.h
Read the docs, check the output of the static tests.
Should avoid similar misunderstandigs as in https://github.com/RIOT-OS/RIOT/pull/15960
> sys/ztimer: clearify doc on clock ops

- sys/include/fmt.h
- tests/fmt_print/main.c
- tests/fmt_print/tests/01-run.py
- tests/periph_ptp_clock/main.c
It seems that `print_s64_dec` is implemented but not exposed in the header.
This PR exposes it and improves coverage of the `fmt` module. 
`make all test -C tests/fmt_print/`
CI should pass too.
Split from #15950
> sys/fmt: Add print_s64_dec to header

- cpu/nrf52/include/periph_cpu.h
- cpu/nrf52/periph/adc.c
The nrf52840 has the awesome option to be powered by an external voltage source from ~3V to over 5V, making it possible to attach the CPU directly to e.g. an USB bus or an li-ion battery. In that case the supply voltage is connected to the CPUs VDDH input pin. This is done e.g. on the `nrf52840dongle` board.
The ADC module for the nrf52 family of CPUs does allow to select their internal VDDH line as input for the ADC, allowing for example to directly sample the volage of an attached li-ion battery without the need of any external components. This PR enables support for this ADC input.
Build test and a good review (easy for this 3 line change :-) ) should do. I did test and verify it on a `nrf52840dongle`.
none
> cpu/nrf52: add VDDHDIV5 as ADC input

- cpu/stm32/periph/ptp.c
- drivers/include/periph/ptp.h
- tests/periph_ptp_clock/main.c
The clock adjustment API only used a 16 bit integer for speed correction. This
is to course grained to allow compensating clock drifts at high accuracy.
Using a 32 bit integer instead would allow to fix for a drift of up to
about 1 nanosecond drift per each 5 seconds.
The test application was updated to the new API, the test should still pass.
none
> drivers/periph_ptp: fix clock adjustment API

- makefiles/toolchain/llvm.inc.mk
clang/LLVM is a bit more finicky with what target triples it accepts compared
to GCC. However, the GCC target triple is needed to properly locate the C
libraries. In case a locally installed GCC toolchain uses a technically not
fully correct target triple, it might be impossible to build with LLVM.
The solution here is to allow specifying a TARGET_ARCH_LLVM target triple
(which defaults to TARGET_ARCH), which is passed to clang. For locating the
C lib, still TARGET_ARCH is used.
Murdock will do.
https://github.com/RIOT-OS/RIOT/pull/15176
> build system: support wrong target triples with LLVM

- cpu/fe310/Makefile.dep
This PR fixes a regression introduced by the combination of #15859 and #15957. Initially newlib was used as default libc on fe310 and the regression forces the use of picolibc.
For users with local toolchains providing newlib by default, this regression is a breaking change. Note that in recent Ubuntu versions, riscv64-unknown-elf is available in the package manager but it doesn't come with newlib and the package manager only provides picolibc. So it's not possible to use the riscv toolchain in the package manager of Ubuntu unless FEATURES_REQUIRED=picolibc is added to the build command. So this is not optimal but there's no good solution for all setup at the moment (until we have a way to automatically detect and use the available libc).
- A green Murdock (Murdock provides both newlib …
> cpu/fe310: set back newlib as default libc

- cpu/fe310/thread_arch.c
This commit is a handcrafted backport for
0b2810a856ee1b23315bdbbb8dc074108c87170a, see #15942
This should resolve the issues mentioned [here](https://github.com/RIOT-OS/RIOT/pull/15718#issuecomment-774248134). The thread_yield_higher function now checks if it is executed from interrupt context and just set the `sched_context_switch_request` flag if it is in interrupt context.
These tests should work again:
- tests/event_wait_timeout
- tests/thread_flags 
- tests/thread_flags_xtimer.
Fixes regressions mentioned [here](https://github.com/RIOT-OS/RIOT/pull/15718#issuecomment-774248134)
> fe310: make thread_yield_higher IRQ compatible [backport 2021.01]

- cpu/riscv_common/Makefile.include
- cpu/riscv_common/irq_arch.c
- makefiles/arch/riscv.inc.mk
Not sure if there is any interested in this but I am personally currently working on using the HiFive1 with the clang compiler. The changes below enabled me to do so, currently doing some more manual testing but haven't found any issues so far. 91707a60e858b7501505e3ecc2e510a51ef931b9 might be useful even if you are not interested in supporting the clang/llvm toolchain on the hifive1.
Compile some example applications with `BOARD=hifive1` and run them.
None.
> fe310: Support compilation with clang

- cpu/nrf5x_common/include/nrfx.h
When using VDDH (high level volatge source) as power supply for an `nrf52840` CPU, it internally uses a two stage voltage regulator. So far, we only enabled the DC/DC mode for the second stage. This PR also enables the DC/DC mode for the first stage in case it is in use.
To my knowledge the `nrf52840dongle` is the only board that uses the VDDH voltage source per default, powering the CPU directly from the 5V USB voltage. To test this PR, best apply the change from  #15990 and verify that any application of your choosing is still running as expected on that board.
-  #15990 enables to test this
- either this PR or #15989 will need a rebase though, who ever comes first...
> cpu/nrf5x: enable DC/DC also for REG0 if VDDH is used

- boards/nrf52840dongle/include/periph_conf.h
Straight forward: this PR enables the DC/DC converters for the `nrf52840dongle` board. In most common use cases, this proves to be the more power efficient mode. If wanted, one can always disable it for ones application... (see #15989)
Any test application should still run fine for this board...
Depends on #15989 to work fully, but the effect should also show without #15989 being merged...
> boards/nrf52840dongle: enable DCDC converters

- cpu/nrf5x_common/include/nrfx.h
nRF52833 has `POWER_MAINREGSTATUS_MAINREGSTATUS_High`, but no `POWER->DCDCEN0` register.
This breaks all builds on this MCU.
Check for the proper define in the `#ifdef` to fix the build.
Murdock should stop failing on `microbit-v2`
#15991  and #15955 where build independent from each other on CI.
Now that both are merged, the error becomes apparent.
> cpu/nrf5x: only enable DCDC for REG0 if REG0 exists

- boards/common/particle-mesh/Kconfig
- boards/common/particle-mesh/Makefile.dep
- boards/common/particle-mesh/Makefile.features
- boards/common/particle-mesh/Makefile.include
- boards/common/particle-mesh/doc.txt
The particle boards have their on-board USB connector wired into the CPU; since CDC-ACM stdio is now readily available, and because while there is a pair of RX/TX pins but no shipped hardware that connects them to the host, it makes the better default.
* Connect to USB
* Ready bootloader (when using PARTICLE_MONOFIRMWARE=1: by keeping mode pressed at powerup until things blink yelllow)
* Flash a regular example, eg. `make BOARD=particle-xenon PARTICLE_MONOFIRMWARE=1 -C examples/saul all flash term`
* Observe that RIOT's CDC-ACM comes up on USB, manifests itself in a /dev/ttyACM0 and the board connects there.
* When using monofirmware, observe that a different example can now be flashed on withouot any physical interaction.
Some of this PRs usefulness is from the bootloader entering work …
> b/c/particle-mesh: Switch default stdio to USB

- core/mutex.c
- doc/doxygen/src/porting-boards.md
I recently (obligatory "this happened a few weeks ago") got bitten by doing I2C (which is blocking) inside board_init (which happens way before threads are around). In retrospect the error is obvious, but before, it heisenbugged me -- for while I2C is set to debug, the mutices don't block for stdio takes longer, and once you start building without I2C debug, Weird Things happen.
This adds an assert into the mutex locking path that checks whether the about-to-be-used thread struct pointer is actually non-null, ie. whether it's actually being executed from a thread (and not before threads are around).
Some warning words about the board_init implementation are added to catch the mistake before it is made.
* This triggers only when there are no threads *yet*, not when in an IRQ. Would it make …
> core/mutex: Check against mutex use outside of threads

- CODING_CONVENTIONS.md
- boards/native/Makefile.include
- makefiles/cflags.inc.mk
- pkg/relic/Makefile
The standard is 9 years old now, it is well supported in all major compilers.
In fact, features of the 'new' standard are already used in RIOT (std_atomic).
Let's make it the default and adapt the Makefiles accordingly.
Murdock will ensure everything compiles with the new flags.
> CODING_CONVENTIONS.md: default to C11

- sys/clif/clif.c
- tests/unittests/tests-clif/tests-clif.c
This is relevant as `clif_decode_link` may invoke `clif_get_attr` with `input_len == 0`.
Example application:
```C
#include <stdlib.h>
#include <stdint.h>
#include <clif.h>
#define MAX_EXPECTED_ATTRS (6)
static uint8_t buf[] = { 60, 193, 62, 59, 0, 0, 0, 0, 0, 0, };
int main(void)
{
char *input = (char *)&buf[0];
clif_t lookif;
clif_attr_t attrs[MAX_EXPECTED_ATTRS];
clif_decode_link(&lookif, attrs, MAX_EXPECTED_ATTRS, input, sizeof(buf));
return 0;
}
```
Minimal `Makefile`:
```Makefile
APPLICATION = clif
BOARD = native
USEMODULE += clif
```
Invoke using:
```
$ make -C examples/clif all-asan
$ make -C examples/clif term
main(): This is RIOT! (Version: 2021.04-devel-461-g50cf93) …
```
> clif: Don't access any data if input is empty

- drivers/include/bmx280.h
Hi RIOT-OS Team,
I removed spi3w_en parameter in drivers/include/bmx280.h since it is never used.
compile bmx280 tests by including bmx280.h header.
Fixes #15954 .
Have a nice day,
Memiks.
> remove unused parameter spi3w_en to solve issue #15954

- boards/cc1312-launchpad/Makefile.dep
- boards/cc1312-launchpad/include/gpio_params.h
- boards/cc2650-launchpad/Makefile.dep
- boards/cc2650-launchpad/include/gpio_params.h
Adds the `gpio_params.h` and default dependency to `saul_gpio` when `saul_default` is present. These were the only in-tree boards that missed these definitions of this CPU family.
- `make -C examples/saul BOARD=cc1312-launchpad`
- `make -C examples/saul BOARD=cc2650-launchpad`
And the buttons/leds defined in the quick start guide for the boards should work as expected:
- [LAUNCHXL-CC2650 Quick Start Guide](https://www.ti.com/lit/ml/swru451/swru451.pdf).
- [LAUNCHXL-CC1312R1 Quick Start Guide](https://www.ti.com/lit/ml/swru535c/swru535c.pdf)
N/A.
> boards/[cc2650, cc1312]-launchpad: add saul_gpio definitions

- makefiles/tools/cc2538-bsl.inc.mk
- makefiles/tools/jlink.inc.mk
This PR fixes a couple of bugs in the build system when using EMULATE=1 and flash in the same command and the emulated boards are using jlink or cc2538-bsl as default programmer.
In the first case, hifive1b are affected and the command just fails. In the second case, cc2538dk and firefly are affected and a weird error message is printed, but the emulation can start still.
The problem comes from the fact that when using EMULATE=1, the FLASHER and FFLAGS variables are set to an empty value by the emulator logic:
https://github.com/RIOT-OS/RIOT/blob/b25c63757e22bde35056e3c83ecc8d70a42fbbff/makefiles/tools/renode.inc.mk#L60-L62
But in jlink.inc.mk, FLASHER is set regardless if it was already set before:
https://github.com/RIOT-OS/RIOT/blob/b25c63757e22bde35056e3c83ecc8d70a42fbbff/makefiles/too …
> make/emulate: fix bugs when using flash target

- pkg/cn-cbor/Makefile
- tests/ssp/Makefile
This PR silences 2 warning raised when building with gcc 10 on riscv:
- upstream code of pkg/cn-cbor raises the return-local-address error. The latest version of the upstream code doesn't provide a fix for this
- `tests/ssp` allocates on purpose a buffer too small but this is catched by the compiler as array-bound warning. Similar to the stringop-overflow warning, the array-bound warning is silenced if it's available in the compiler.
- Both applications build with gcc 10 for riscv and works on hifive1b:
<details><summary>tests/pkg_cn-cbor</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=hifive1b -C tests/pkg_cn-cbor --no-print-directory flash test
docker run --rm --tty --user $(id -u) -v …
```
> make: silence a couple of warnings raised with gcc 10 on riscv

- sys/net/gnrc/pktbuf/include/pktbuf_internal.h
- sys/net/gnrc/pktbuf_malloc/gnrc_pktbuf_malloc.c
Otherwise the local mallocs variable is not decremented correctly (if `TEST_SUITES` is defined) and the fuzzing setup (i.e. when `MODULE_FUZZING` is defined) does not terminate. This regression was introduced in 3970b667aade062ab9dc4e2afe7914f7cd081f80.
See:
https://github.com/RIOT-OS/RIOT/blob/3970b667aade062ab9dc4e2afe7914f7cd081f80/sys/net/gnrc/pktbuf_malloc/gnrc_pktbuf_malloc.c#L54-L69
CC: @maribu
> gnrc_pktbuf: always use _free function with gnrc_pktbuf_malloc

- bootloaders/riotboot_dfu/Makefile
The IDs are not advertised to dfu-util to allow a smooth transition into
having a VID/PID-identifiable riotboot_dfu.
As allocated on https://pid.codes/1209/7D02/. (Don't mind the license stated there, it's a copy-paste error and to be fixed in https://github.com/pidcodes/pidcodes.github.com/pull/619).
---
* Flash riotboot_dfu applying test procedure from https://github.com/RIOT-OS/RIOT/pull/16011 up to "Notice how it comes up in the bootloader".
* Observe in `lsusb` that the "Generic USB device" is now shown as 1209:7d02 when the bootloader is entered.
* No warnings of test PIDs show up.
With the allocated code, devices in bootloader mode will be more clearly visible in `lsusb`. This is especially important when bootloader mode can be entered manually (as of #16011) to tell which state …
> riotboot_dfu: Use allocated USB IDs

- cpu/nrf51/include/cpu_conf.h
- cpu/nrf5x_common/include/periph_cpu_common.h
- cpu/nrf5x_common/periph/gpio.c
We can use the `GPIO_COUNT` vendor macro to check if there is more than one GPIO port on nRF52.
This is the case for nRF52840 and nRF52833.
Pins on the second GPIO block should still work, no additional code should be generated on MCUs without that block.
> cpu/nrf5x_common: make GPIO_PIN macro model independent

- drivers/nrf24l01p_ng/include/nrf24l01p_ng_types.h
Bugfix of conversion between `nrf24l01p_ng_etoval_ard()` and  `nrf24l01p_ng_valtoe_ard()`.
```C
for (uint16_t ard = 250; ard <= 4000; ard += 250) {
assert(ard == nrf24l01p_ng_etoval_ard(nrf24l01p_ng_valtoe_ard(ard)));
}
```
fixes: #16027
> drivers/nrf24l01p_ng: auto retransmission delay conversion bugfix

- boards/yarm/Kconfig
- boards/yarm/Makefile.features
The board uses USB CDC ACM as stdio by default, so select the highlevel_stdio feature.
`yarm` should build on CI again.
discovered by #16034
> boards/yarm: add Highlevel STDIO feature

- cpu/cc2538/radio/cc2538_rf_radio_ops.c
- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
- sys/include/net/ieee802154/radio.h
Modifies the `ieee802154_radio_ops_t` structure to use an integer to store capabilities instead of a function call. Uses an `uint16_t` for this purpose, in the future, if needed could be extended to an `uint32_t` if more capabilities are needed.
The `caps` field was put on the top of the structure just for aesthetics reasons (to not mix actual operations with the capabilities).
The motivation is to (on another PR) add the PHY capabilities, see https://github.com/RIOT-OS/RIOT/pull/15932#discussion_r570904375 and previous comment on the HAL RDM (https://github.com/RIOT-OS/RIOT/pull/13943#discussion_r414769629).
<details>
<summary>Binary size changes</summary>
Tested with `make -C examples/gnrc_networking BOARD=<....>`
**cc2538dk**
```
91512 …
```
> net/ieee802154/radio: use bitflags for capabilities

- pkg/wakaama/include/lwm2m_client.h
Drop included of unused header file that caused conflict with the new toolchain
Murdock should turn green again.
None
> pkg/wakaama: fix compilation with 6lowpan-clicker

- drivers/at86rf2xx/at86rf2xx_netdev.c
Missing ISR's added to at86rf2xx_netdev.c for ATmegaRFA1/RFR2:
- TRX24_PLL_LOCK
- TRX24_PLL_UNLOCK
- TRX24_RX_START
- TRX24_CCA_ED_DONE
- TRX24_AWAKE
Add one of ATMegaRFR2-based boards to BOARD_WHITELIST in tests\gnrc_gomach\Makefile or in examples\gnrc_networking_mac:
`BOARD_WHITELIST := samr21-xpro iotlab-m3 derfmega256`
Run the test on 2 boards. Check that board with ATMegaRFR2 shows received packets
Fixes #12857
> drivers/at86rf2xx: add missing handler for TRX24_RX_START interrupt

- bootloaders/riotboot_dfu/Makefile
While looking at  #16044 I realized there was an issue with USEMODULE declaration in `bootloader/dfu`. Because of this `stdio_uart` was actually pulled in.
- flashing with the bootloader should still work
- stdio_null is now used
```
make -C bootloaders/riotboot_dfu/ info-modules | grep stdio_null
stdio_null
```
> bootloader/dfu: fix USEMODULE=

- drivers/at86rf2xx/at86rf2xx.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
There was mispring in module name MODULE_AT86RF2XX_AES_SPI
There are no tests that checks AES encryption key settings by NETOPT_ENCRYPTION_KEY.
> drivers/at86rfr2xx: usage of module at86rf2xx_aes_spi fixed

- boards/cc1312-launchpad/doc.txt
- boards/cc1350-launchpad/doc.txt
- boards/cc1352-launchpad/doc.txt
- boards/cc1352p-launchpad/doc.txt
- boards/cc2650-launchpad/doc.txt
- cpu/cc26xx_cc13xx/doc.txt
- Adds documentation for LaunchPad boards.
- Moves the flashing section of existing boards to a central place (on CC26xx/CC13xx common).
- Fixes the number of UARTs for cc1350-launchpad, has only 1 :-(.
- Adds a Table of Contents for each board and CPU, slightly copied from the great esp32 documentation.
- `make docs`
- Take a cup of coffee, read it, point out errors 😉 . 
None
> cpu/cc26xx_cc13xx: add CPU documentation

- bootloaders/doc.txt
- bootloaders/riotboot/doc.txt
- bootloaders/riotboot/main.c
- doc/doxygen/riot.doxyfile
Currently, documentation about the bootloaders is only accessible through the source tree and not through the API documentation.
This adds the `bootloaders/` directory to the list of starting points for doxygen, and moves the riotboot documentation into a place where doxygen can pick it up. Some metadata is added to make it fit nicely.
* Open the documentation search for "bootloader".
* Since this change, a section shows up (also in the modules list) that currently contains only riotboot
* The current form of #16011 adds board defines that influence how the bootloader is used; until this is merged, they are not visibly documented.
* Further work seems indicated to document the DFU based bootloader (currently blank), and to make the riotboot docs more newcomer friendly in general. (They …
> doc: Make bootloaders visible in modules

- sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
This PR corrects the packet length checks in the validation procedures for `DAO` and `DAO-ACK` messages by guarding them appropriately.
Thanks @nmeum for this hint!
1. As specified in #16018.
2. Also, check if a basic RPL topology forms (native is fine) and try to ping the root node.
fixes #16018
> rpl: strengthen length checks for DAO and DAO-ACK

- boards/native/Makefile.include
This PR is split-out from #15970. Native doesn't have a flasher so the FLASHER variable can simply be empty to skip this step transparently.
make -C examples/hello-world flash term should still work but `true` is not printed by this PR:
```
$ BUILD_IN_DOCKER=1 make -C examples/hello-world flash term
make: Entering directory '/work/riot/RIOT/examples/hello-world'
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' -e 'BUILD_DIR=/data/riotbuild/riotbase/build' -e 'RIOTPROJECT=/data/riotbuild/riotbase' -e …
```
> boards/native: set FLASHER as empty

- makefiles/boot/riotboot.mk
When working on #15970, I noticed that when setting a custom PROGRAMMER (for example openocd instead of edbg with samr21-xpro), and flashing with `riotboot/flash%` targets, I realized that the riot slot is flashed with the custom programmer (openocd) but riotboot is flashed using the default programmer.
This PR is fixing this small inconsistency by passing the PROGRAMMER variable to the riotboot/flash% targets.
- Default `tests/riotboot%` flashing behaviour is still working
- Test the flashing of `tests/riotboot` on samr21-xpro by setting `PROGRAMMER=openocd` and verify that openocd is used to flash both the slots and riotboot:
```
$ PROGRAMMER=openocd make BOARD=samr21-xpro -C tests/riotboot all riotboot/flash term
make: Entering directory …
```
> makefiles/boot: use same PROGRAMMER to flash riotboot

- sys/Makefile.include
- sys/net/gnrc/pktbuf_static/Makefile.include
- sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
- sys/net/gnrc/pktbuf_static/include/pktbuf_static.h
- tests/gnrc_ndp/Makefile
- tests/gnrc_ndp/main.c
From https://github.com/RIOT-OS/RIOT/issues/12651
> &#x2610; tests/gnrc_ndp: no idea of the problems
The problem is that the tests makes some assumptions that do not hold true for every platform: For testing the "packet buffer is full" error case, it fills the packet buffer with just enough data to be able to progress the function under test to a certain point and then fail. For this it assumes the size of a `gnrc_pktsnip_t` to be 24 bytes. However, 24 bytes is only the right size for `gnrc_pktsnip_t` on 32-bit systems (and only if the struct does not change), on AVR e.g. it 9 bytes. By using the internal alignment function of `pktbuf` we are able to precisely tell the internal size of `gnrc_pktsnip_t` using the `sizeof` operator.
Run
```sh
make -C tests/gnrc_ndp -j flash test
```
on an …
> tests/gnrc_ndp: don't guess size of `gnrc_pktsnip_t` in `pktbuf`

- sys/shell/commands/Kconfig
- tests/periph_i2c/Makefile
- tests/periph_i2c/Makefile.ci
- tests/periph_i2c/app.config.test
This PR adds a small little tool to scan a given I2C bus for all connected devices and simply list them to STDIO. This is quite useful when trying to find out I2C the active address of freely configurable slaves or some strange modules with unknown documentation.
Not sure if we have something like this in the code base already, at least I could not find anything...
Simply run this example on any board that has 1 or more I2C devices connected to it. You should see the addresses of all connected devices listed to STDIO.
none
> examples: add I2C scanner

- examples/gnrc_networking_mac/Makefile
The example now works successfully on these AVR based boards.
`avr-rss2` can ping `samr21-xpro`
```
2021-02-20 00:41:33,491 # ping fe80::204:2519:1801:c905
2021-02-20 00:41:33,656 # 12 bytes from fe80::204:2519:1801:c905%7: icmp_seq=0 ttl=64 rssi=-33 dBm time=156.032 ms
2021-02-20 00:41:35,162 # 12 bytes from fe80::204:2519:1801:c905%7: icmp_seq=1 ttl=64 rssi=-38 dBm time=661.936 ms
2021-02-20 00:41:35,887 # 12 bytes from fe80::204:2519:1801:c905%7: icmp_seq=2 ttl=64 rssi=-37 dBm time=388.336 ms
2021-02-20 00:41:35,887 # 
2021-02-20 00:41:35,893 # --- fe80::204:2519:1801:c905 PING statistics ---
2021-02-20 00:41:35,898 # 3 packets transmitted, 3 packets received, 0% packet loss
```
#16038
> examples/gnrc_networking_mac: whitelist ATmega256RFR2 based boards

- boards/native/include/eui_provider_params.h
- cpu/native/Makefile
- cpu/native/Makefile.dep
- cpu/native/cli_eui_provider/Makefile
- cpu/native/cli_eui_provider/eui_provider.c
- cpu/native/include/native_cli_eui_provider.h
- cpu/native/include/native_internal.h
- cpu/native/include/socket_zep.h
- cpu/native/socket_zep/socket_zep.c
- cpu/native/startup.c
- drivers/include/net/netdev.h
- pkg/lwip/contrib/lwip.c
- sys/net/gnrc/netif/init_devs/auto_init_socket_zep.c
- tests/socket_zep/main.c
This registers `socket_zep` with netdev to use eui_provider to generate a L2 address for the ZEP device.
Consequently an EUI provider for the `native` board is added that is sourced from command-line supplied addresses.
This contains an API change in which an additional `index` parameter is supplied to the eui provider callback function.
I can move this to a separate PR.
Add `TERMFLAGS += -U 00:AA:BB:CC:DD:EE:FF:11` to the `Makefile` of `examples/gnrc_networking`, then run
make -C examples/gnrc_networking USE_ZEP=1 all term
```
Iface  7  HWaddr: 7F:11  Channel: 26  NID: 0x23 
Long HWaddr: 00:AA:BB:CC:DD:EE:FF:11 
L2-PDU:102  MTU:1280  HL:64  RTR  
6LO  IPHC  
inet6 addr: fe80::2aa:bbcc:ddee:ff11  scope: link  VAL
inet6 …
```
> socket_zep: register with netdev, provide EUI-64 as command line parameter

- dist/tools/edbg/edbg.sh
- makefiles/tools/edbg.inc.mk
As requested in #15970, this PR splits out the changes related to edbg in its own PR.
While working on #15970, I noticed that support for edbg was not consistent with the other flashers, using a custom command with a dual call to edbg.
Similar to openocd/jlink/pyocd, this PR adds an edbg.sh script that wrap the flash and reset calls to edbg. As a result, edbg.inc.mk needs some refactoring as well.
The good thing is that there's no need to define a custom `flash-recipe = $(edbg-flash-recipe)`.
Flashing and resetting with edbg still works. Also verify that flashing using DEBUG_ADAPTER_ID still works.
Results on samr21-xpro:
<details><summary>flash</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=samr21-xpro -C examples/hello-world flash --no-print-directory 
Launching build container using …
```
> tools/edbg: add and use wrapper shell script

- dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
A [new version of Pylint was released today](https://pypi.org/project/pylint/#history) and [this breaks the tools-test github action](https://github.com/RIOT-OS/RIOT/runs/1947401308?check_suite_focus=true) because of a small inconsistency in the compile_and_test_for_board script.
The raised issue is perfectly valid and this PR is fixing it by cleaning up a bit the `make_with_outfile` function. The return value of this function is never used so a bare return or no return is ok.
https://github.com/RIOT-OS/RIOT/blob/e0211f4574d08f2dac978a91a34a5842a7378491/dist/tools/compile_and_test_for_board/compile_and_test_for_board.py#L410
https://github.com/RIOT-OS/RIOT/blob/e0211f4574d08f2dac978a91a34a5842a7378491/dist/tools/compile_and_test_for_board/compile_and_test_for_board.py#L418-L419 …
> tools/compile_and_test_for_board: fix lint

- drivers/mtd_spi_nor/mtd_spi_nor.c
The while condition for polling the chip ID is broken, it will always poll for the max amount of retries.
Change the condition from `or` to `and` to fix the logic.
A spi nor device is still detected by `tests/mtd_raw`
```
2021-02-11 22:52:00,752 # test 0
2021-02-11 22:52:00,752 # [START]
2021-02-11 22:52:00,980 # [SUCCESS]
2021-02-11 22:52:11,040 # info 0
2021-02-11 22:52:11,040 # sectors: 128
2021-02-11 22:52:11,041 # pages per sector: 16
2021-02-11 22:52:11,041 # page size: 256
2021-02-11 22:52:11,042 # total: 512 kiB
```
fixes #15894
> drivers/mtd_spi_nor: fix poll on init

- dist/tools/boards_supported/check.sh
- dist/tools/ci/static_tests.sh
- makefiles/tests/boards_supported/Makefile
- makefiles/tests/boards_supported/README.md
This adds a unit test for `make info-boards-supported` to `make static-tests` which will enforce that at least applications that do not use any modules (other than the default modules) are build for *all* boards supported by RIOT. It can detect some issues of the following class:
- Something with `make info-boards-supported` is broken and too few boards are printed
- The set of default modules gets extended to render boards unusable
- Boards are added to RIOT that are missing some mandatory features, so that not even `examples/hello-world` can be build on them
This should expose an issue with current `master` within the static tests that should look like this:
```
Running "./dist/tools/boards_supported/check.sh" x
Command output:
BOARDS_FEATURES_MISSING="yarm highlevel_stdio"
Makefile:23: …
```
> makefiles/tests: add unit test for info-boards-supported

- cpu/esp32/Makefile.include
- makefiles/tools/esptool.inc.mk
This PR fixes the inclusion order of FFLAGS with the esptool when using the `esp_qemu` module. In master, this is currently broken (probably because of #15475).
The fix proposed by this PR is to move the logic from esp32 to esptool.inc.mk, which is now included after the cpu Makefile.include is included.
This PR is a quick fix and IMHO a more proper fix is to reuse the EMULATE=1 variable and integrate the esp emulator into the qemu.inc.mk mechanism, instead of relying on the module mechanism. I leave this as a follow-up.
Another cleanup that is worth is to get rid of all this commands configured in the FFLAGS variable, this is an abuse of this variable that should only contain parameters of the flasher tool (configured in FLASHER). I'm also leaving this as a follow-up.
- Try to flash an …
> make/esptool: fix FFLAGS inclusion order for qemu

- sys/include/usb/cdc.h
- sys/usb/usbus/cdc/acm/cdc_acm.c
Found a small typo when studying USB CDC ACM code: _capabalities_ - renamed as it should.
> USB CDC: fix typo in definitions

- cpu/sam0_common/periph/adc.c
The ADC SYNCBUSY.SWTRIG gets stuck to '1' after wake-up from Standby Sleep mode.
Ignore the ADC `SYNCBUSY.SWTRIG` status bit, this functionality is not used by the driver anyway.
> sam0/adc: work around ADC errata on SAM D5x/E5x

- pkg/emlearn/Makefile
`tests/pkg_emlearn` still works on `same54-xpro` and `native`.
> pkg/emlearn: bump version to 0.11.6

- cpu/stm32/include/can_params.h
- cpu/stm32/include/candev_stm32.h
- cpu/stm32/periph/can.c
Deep-sleep was based on using rx pin as external interrupt to be able to
wake up from stop mode. If rx pin cannot be used as interrupt or user
does not need to wake up from stop from the CAN, an option is now
present. If en_deep_sleep_wake_up is set to false, setting the device to
sleep simply unblocks stop mode. Otherwise the behavior is unchanged.
> stm32/can: add option to enable deep-sleep per device

- pkg/nanopb/Makefile
Update to the [latest release](https://github.com/nanopb/nanopb/commit/2b48a361786dfb1f63d229840217a93aae064667).
`tests/pkg_nanopb` still works.
> pkg/nanopb: bump version to 0.4.4

- cpu/native/Kconfig
- cpu/native/Makefile.features
- cpu/native/periph/timer.c
The native timer is not free running, so we can't honor it's flags.
But `setitimer()` already provides an interval option, we only have to enable it.
`tests/periph_timer_periodic` should now also work on `native`.
> cpu/native: timer: implement timer_set_periodic()

- tests/xfa/Makefile
This PR fixes the `tests/xfa` build when using `BUILD_IN_DOCKER=1` on the command line and a parallel make (using --jobs=x). The proposed fix is to append the `static-test` target to the `BUILDDEPS` variable after Makefile.include is parsed. With the `BUILDDEPS` variable, order is apparently kept with parallel make.
This problem triggers a build failure in the test-on-iotlab action (for example [on nrf52dk](https://github.com/RIOT-OS/RIOT/runs/1948186596?check_suite_focus=true#step:10:2258)), because this action uses `BUILD_IN_DOCKER=1` and `--jobs=2`.
Try `BUILD_IN_DOCKER=1 make RIOT_CI_BUILD=1 --no-print-directory -C tests/xfa clean al --jobs=2`, with this PR is works, on master it fails:
<details><summary>this PR:</summary>
```
$ BUILD_IN_DOCKER=1 make RIOT_CI_BUILD=1 …
```
> tests/xfa: use BUILDDEPS instead of overriding the all target

- cpu/native/periph/flashpage.c
- cpu/stm32/include/cpu_conf.h
- drivers/mtd_flashpage/mtd_flashpage.c
- tests/mtd_flashpage/Makefile
- tests/mtd_flashpage/main.c
`native` uses the same 'unusual' flashpage properties as stm32l0, also the flash does not start at address 0 this uncovered some issues:
- when calculating alignment, we have to do so in regards to the start of the flash, not it's absolute address
- `FLASHPAGE_WRITE_BLOCK_ALIGNMENT` is a requirement for the *target* block alignment for *writing*, it shouldn't say enforce about the *source* alignment or *read* alignment
`tests/mtd_flashpage` now works on `native`.
fixes issue brought to light by #16026
> drivers/mtd_flashpage: fixes for native (and stm32l0, stm32l4)

- makefiles/tools/esptool.inc.mk
The build system integration of esptool abuses FFLAGS/PREFFLAGS variables with extra commands (as described in #16059). This PR introduces 2 internal targets and adds them to the FLASHDEPS variable instead.
- ESP boards can still be flashed:
<details><summary>esp32-wroom-32</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=esp32-wroom-32 -C examples/default/ flash term --no-print-directory
ESP32_SDK_DIR should be defined as /path/to/esp-idf directory
ESP32_SDK_DIR is set by default to /opt/esp/esp-idf
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' …
```
> tools/esptool: cleanup preflash and qemu integration in build system

- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/lwip/include/arch/cc.h
- pkg/lwip/include/lwipopts.h
- pkg/lwip/patches/0002-lowpan6-Use-arch-independent-printf-formatters.patch
- sys/shell/commands/Makefile
- sys/shell/commands/sc_lwip_netif.c
- sys/shell/commands/shell_commands.c
- tests/lwip/main.c
- tests/lwip/tests/01-run.py
This PR adds ifconfig shell command when lwIP is included as IP stack,
plus some minor tweaks (allowing both ESP netifs to be used, and setting
name for 6lowpan netifs).
This is the result when running on an ESP board with wifi & ethernet:
```
> ifconfig
Iface ET0 HWaddr: 24:0a:c4:e6:0e:9f Link: up State: up
inet addr: 10.4.4.81 mask: 255.255.254.0 gw: 10.4.4.1
inet6 addr: fe80:0:0:0:260a:c4ff:fee6:e9f scope: link
inet6 addr: 2001:db8:1000:0:260a:c4ff:fee6:e9f scope: global
Iface ET1 HWaddr: 24:0a:c4:e6:0e:9c Link: up State: up
inet addr: 10.4.4.82 mask: 255.255.254.0 gw: 10.4.4.1
inet6 addr: fe80:0:0:0:260a:c4ff:fee6:e9c scope: link
inet6 addr: 2001:db8:1000:0:260a:c4ff:fee6:e9c scope: global
>
```
I have used the lwIP internal methods for printing ip …
> Add lwIP ifconfig shell command

- boards/arduino-leonardo/Makefile.include
- boards/common/cc2538/Makefile.include
- boards/mega-xplained/Makefile.include
This was scheduled for removal a while ago:
```
- makefiles/vars.inc.mk: PORT_BSL & AVRDUDE_PORT will be removed after release
2020.04
```
```
→ git grep AVRDUDE_PORT
release-notes.txt:- makefiles/vars.inc.mk: PORT_BSL & AVRDUDE_PORT will be removed after release
```
```
→ git it grep PORT_BSL
release-notes.txt:- makefiles/vars.inc.mk: PORT_BSL & AVRDUDE_PORT will be removed after release
```
> boards: remove AVRDUDE_PORT and PORT_BSL

- core/include/xfa.h
xfa previously used `typeof`, which arm-none-eabi-gcc (at least 10.2) doesn't accept in c11 mode.
This changes `typeof` to `__typeof__`, which both gcc and llvm are ok with.
No user, so nothing to see. Take a good look at the reasoning.
Split from #16061.
> core/xfa: typeof() -> __typeof__()

- makefiles/kconfig.mk
This modifies the Kconfig makefile to only source the `out.config` file into the build system when Kconfig has to run. There is no need to include it otherwise.
We need to make sure this change keeps Kconfig working across different workflows. I tested the following:
1. `make menuconfig` > `make all` should load `out.config`
2. `env TEST_KCONFIG=1 make` should load `out.config`, using dependency modelling
3. `make` (on an application without Kconfig files) should not load `out.config`
4. `make menuconfig` > `make clean all` should not load `out.config` (because of the clean)
5. Successive configurations via `.config` files or menuconfig should always load `out.config` until clean is executed
To check if there are Kconfig symbols loaded to the build system, one can add something like the …
> makefiles/kconfig: include out.config only when running Kconfig

- .github/workflows/test-on-iotlab.yml
- tests/periph_timer_periodic/tests/01-run.py
The python test script seems to have timing issues when launched from the github actions environment. Most of the boards are failing reliably([example on nrf52dk](https://github.com/RIOT-OS/RIOT/runs/1948186596?check_suite_focus=true)) every week.
I tried locally, or on IoT-LAB, with compile_and_test_for_board used on my computer and I'm not able to reproduce at all.
My guess is that the github actions are running in a virtualized environment and time measured by Python is very imprecise in this context.
The test application is skipped when launched via the test-on-iotlab action.
None
> gh_action: exclude tests/periph_timer_periodic from test-on-iotlab

- makefiles/libc/picolibc.mk
missing picolibc auto adaptation needs changes in make-system and is therefor on hold this PR make the build fail early and loud and needs basically no modification of unrelated make-system parts.
Build something that prefers or requires picolibc on a system that does not have it (installed) (e.g.: current Ubuntu LTS 20.04)
e.g.: RIOT/examples/gnrc_minimal for a cortex-m Board
before u get a failure somthing like:
```
"make" -C <Riot>/sys/picolibc_syscalls_default
<Riot>/sys/picolibc_syscalls_default/syscalls.c:236:5: error: implicit declaration of function 'FDEV_SETUP_STREAM' [-Werror=implicit-function-declaration]
236 |     FDEV_SETUP_STREAM(picolibc_put, picolibc_get, picolibc_flush, _FDEV_SETUP_RW);
|     ^~~~~~~~~~~~~~~~~
<Riot>/sys/picolibc_syscalls_default/syscalls.c:236:67: error: …
```
> makefile/..picolibc: make missing picolibc fail louder

- dist/tools/coccinelle/check.sh
- dist/tools/headerguards/check.sh
- dist/tools/uncrustify/uncrustify.sh
In https://github.com/RIOT-OS/RIOT/pull/15739 I noticed, that the annotated diffs are a bit broken in their format.
This should fix that.
I provided a test commit. The annotated patches should now be correct.
None, but discovered in #15739
> static_tests: fix diff output

- Kconfig
- makefiles/kconfig.mk
- tests/kconfig/Makefile
- tests/kconfig/app.config
- tests/kconfig/external_module_1/Kconfig
- tests/kconfig/external_module_1/Makefile
- tests/kconfig/external_module_1/Makefile.include
- tests/kconfig/external_module_1/include/external_module_1.h
- tests/kconfig/external_module_2/Kconfig
- tests/kconfig/external_module_2/Makefile
- tests/kconfig/external_module_2/Makefile.include
- tests/kconfig/external_module_2/include/external_module_2.h
- tests/kconfig/main.c
- tests/kconfig/tests/01-run.py
This PR enables handling external module configurations via Kconfig. They are all included under the same `external modules` menu.
To be able to source them easily as a blob all EXTERNAL_MODULE_DIRS that hold a configuration file are written as `osource <dir_path>/Kconfig` to a Kconfig.external_modules file.
- Test cases added to extend `tests/kconfig`.
> Kconfig: source EXTERNAL_MODULES configurations

- drivers/saul/init_devs/auto_init_saul_pwm.c
This fixes a small missed PRIu32 (had "%u" for printing a uint32_t) that makes LLVM trip.
```
$ make BOARD=nrf52840dongle TOOLCHAIN=llvm -C examples/saul
```
should build (currently doesn't)
> drivers/saul: Fix "%u" print formatter

- sys/include/net/nanocoap.h
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/suit/transport/coap.c
- tests/unittests/tests-nanocoap/tests-nanocoap.c
The URI is passed as a string to `suit_coap_get_blockwise()`.
It may contain query parameters (`/path/to/resource?foo=bar&baz=blub`), those will not be translated properly to CoAP options if `coap_opt_put_uri_path()` is used.
To fix this, add a function `coap_opt_put_uri_pathquery()` that handles both path and query parameters.
A test for the new function has been added to `tests/unittests/tests-nanocoap`.
> nanocoap: add coap_opt_put_uri_pathquery()

- sys/net/gnrc/routing/rpl/gnrc_rpl_validation.c
Hardens the validation of `option` lengths.
Thanks @nmeum for reporting this!
1. as specified in #16062
2. run a small RPL network (`native` will suffice) and verify that ping between nodes (use the global IPv6 address) still works.  `nib route` should show the correct routing entries.
fixes #16062
> gnrc_rpl: harden validation routine for options

- Makefile.include
- dist/tools/cosy/Makefile
- dist/tools/cosy/patches/0001-cosy.py-set-working-directory-to-location-of-cosy.py.patch
- dist/tools/cosy/patches/0002-frontend_server.py-make-URL-clickable.patch
- makefiles/tools/targets.inc.mk
`cosy` is a graphical memory usage analyzer.
It is a great tool, but pretty hidden.
Add it as a build target so it can be easiely summoned for any application and board.
Run e.g. 
make -C examples/hello-world cosy
and open the link (http://localhost:12345) in your browser.
You should see a graphical break down of every symbol and it's memory usage.
You can do this for every app or board.
upstream PRs:
https://github.com/haukepetersen/cosy/pull/9
https://github.com/haukepetersen/cosy/pull/10
> make: add cosy as a build target

- sys/net/gnrc/network_layer/sixlowpan/frag/gnrc_sixlowpan_frag.c
In case of an error, the tx sync packet snip could previously have been
released twice. This moves re-attaching the tx sync snip down after the
last `goto error` to avoid this.
The test in `tests/gnrc_tx_sync` should still pass.
None
> sys/net/gnrc: fix logic bug in gnrc_tx_sync implementation

- tests/pkg_littlefs/main.c
- tests/pkg_littlefs/tests/01-run.py
- tests/pkg_littlefs2/main.c
- tests/pkg_littlefs2/tests/01-run.py
- tests/pkg_spiffs/main.c
This PR fixes #14579.
The MTD configuration of the nrf52840dk was added in #14052 but it never worked when using the littlefs/spiffs automated tests because of a timeout. Indeed, to complete the littlefs tests take more than 2 minutes and it's even 10 minutes for spiffs.
Those tests [break in the test-on-iotlab github action](https://github.com/RIOT-OS/RIOT/runs/1964404209?check_suite_focus=true) (and are now the only ones there).
So this PR fixes the problem by 2 means:
- set a long enough timeout for the littlefs test, since waiting 2 minutes is reasonable (but maybe not for everyone :) )
- don't test on MTD_0 the spiffs, and just use the mtd in RAM. This is much faster (of course) and the MTD configured for a board is already tested by other tests anyway. If this is not acceptable for …
> tests/pkg_littlefs:  tests/pkg_spiffs: fix test timeouts on nrf52840dk

- tests/periph_spi/main.c
https://github.com/RIOT-OS/RIOT/pull/16061 exposed that on 16kb flash ARM boards (e.g., samd10-xmini), `tests/periph_spi_dma` is borderline not fitting, with maybe 50b left.
This PR just compacts the bootup message slightly:
PR:
```
text    data     bss     dec     hex filename
16244      44    3860   20148    4eb4 /data/riotbuild/riotbase/tests/periph_spi_dma/bin/samd10-xmini/tests_periph_spi_dma.elf
```
master:
```
text    data     bss     dec     hex filename
16284      44    3860   20188    4edc /data/riotbuild/riotbase/tests/periph_spi_dma/bin/samd10-xmini/tests_periph_spi_dma.elf
```
CI should be fine.
> tests/periph_spi: compact help messages a bit to shave off some bytes

- makefiles/arch/riscv.inc.mk
This PR adds a CFLAGS option to riscv compiler to use a natural alignment of data instead of xlen (the default). This change fixes the sys_architecture test application on riscv but needs a version of gcc >= 8.3 and the version in riot/riotbuild is 8.2.
<details><summary>`tests/sys_architecture` now works on hifive1b:</summary>
```
$ make BOARD=hifive1b -C tests/sys_architecture/ flash test
make: Entering directory '/work/riot/RIOT/tests/sys_architecture'
Building application "tests_sys_architecture" for "hifive1b" with MCU "fe310".
"make" -C /work/riot/RIOT/boards/hifive1b
"make" -C /work/riot/RIOT/cpu/fe310
"make" -C /work/riot/RIOT/cpu/fe310/periph
"make" -C /work/riot/RIOT/cpu/fe310/vendor
"make" -C /work/riot/RIOT/cpu/riscv_common
"make" -C …
```
> arch/riscv: use natural align data type

- Makefile.include
- dist/testbed-support/makefile.iotlab.single.inc.mk
- dist/tools/programmer/programmer.py
- makefiles/boot/riotboot.mk
- makefiles/tools/programmer.inc.mk
- makefiles/vars.inc.mk
This is an RFC PR that introduces 2 variables to control the output of the flasher. Most of the time it's just noise, especially when pasting them as test output in a PR. The build system also provides the QUIET variable to silent the compiler output and replace it with a nice output. The idea of this PR is to something similar for the flasher and by default, only display the flasher command.
FLASHERLOG and FLASHER_OUTPUT variables are introduced to give a way to control the flasher output.
The proposed behavior is as follows:
- by default, when QUIET=1, nothing is printed to stdout and all output goes to a log file defined by FLASHERLOG
- if FLASHERLOG is empty, the output goes to stdout
- if QUIET=0 and FLASHERLOG is defined, the output goes to stdout and to the log file.
- by default, …
> make: print spinning icon while flashing/resetting

- drivers/at86rf2xx/at86rf2xx.c
- drivers/atwinc15x0/Makefile.dep
- drivers/mrf24j40/Makefile.dep
Those drivers don't rely on luid directly anymore, we can drop the dependency.
Everything should still compile.
> drivers: remove unused luid dependencies

- .murdock
Currently the loop that cycles through the applications to test Kconfig on does not break when t finds it. This adds a break when the application is found. Also, `appdir` is used for the error message instead.
- Green CI
- Locally one could force an issue in the Kconfig test (e.g. by adding/removing some module) and running the compile function in the script. For instance: `/bin/bash -c "source .murdock; JOBS=4 compile tests/driver_ad7746 samr21-xpro:gnu"` The error message should return the correct application name.
None
> murdock: break loop when app found and fix error message

- makefiles/kconfig.mk
When an application contains an `app.config` for configuration using Kconfig without dependency resolution and an `app.config.test` for configuration using Kconfig with dependency resolution, the `app.config` file is still loaded, setting legacy symbols, and this is causing errors with Kconfig (see e.g. https://github.com/RIOT-OS/RIOT/pull/15951#issuecomment-785760426). This makes `app.config` and `app.config.test` mutually exclusive and their selection as application base configuration based on the setting of `TEST_KCONFIG=1`.
I cherry-picked this PR on top of #15951 and try to build the test there with and without `TEST_KCONFIG=1` (currently causing an easy to solve merge conflict
```console
$ git remote add miri64 git@github.com:miri64/RIOT.git
$ git fetch miri64
$ git checkout …
```
> Kconfig: make app.config and app.config.test mutually exclusive

- pkg/lwip/contrib/lwip.c
`lwip` requires a separate init.
Hook up `sam0_eth` init here so lwip can be used with this driver.
flash `examples/paho-mqtt` on `same54-xpro`, `ifconfig` should work:
```
2021-02-26 12:55:37,020 # Iface ET0 HWaddr: fc:c2:3d:0d:2d:1f Link: up State: up
2021-02-26 12:55:37,022 #         Link type: wired
2021-02-26 12:55:37,028 #         inet6 addr: fe80:0:0:0:fec2:3dff:fe0d:2d1f scope: link
2021-02-26 12:55:37,043 #         inet6 addr: 2001:16b8:456e:6900:fec2:3dff:fe0d:2d1f scope: global
```
> lwip: hook up sam0_eth support

- pkg/openthread/Makefile
- pkg/openthread/contrib/openthread.c
- pkg/openthread/contrib/platform_random.c
- pkg/openthread/contrib/platform_uart.c
- pkg/openthread/patches/0001-RIOT-use-assert.h.patch
- pkg/openthread/patches/0001-xxx-define-UINT16_MAX.patch
I noticed the OpenThread package is quite old, so I bumped it to the latest tagged upstream release.
Only minor API changes.
Somehow it would not find `UINT16_MAX` (and `<cstdint>` would call for C++11) so I added a hacky patch.
Compile tested only (and flashed onto `nrf52840dk`).
I don't know how to properly test this.
I only tried `ping` between two nodes, this worked.
> pkg/openthread: bump version to 20191113

- examples/cord_ep/README.md
- examples/cord_epsim/Makefile
- examples/cord_epsim/README.md
- examples/cord_lc/README.md
- sys/include/net/cord/ep.h
- sys/include/net/cord/lc.h
- sys/net/application_layer/cord/doc.txt
- sys/net/application_layer/cord/epsim/cord_epsim.c
This enacts the one actual change since this was written (which is, simple registrations go to /.well-known/rd rather than /.well-known/core).
The remaining changes are just updating the references to -27 (updating sections and comments as needed). Unless the RFC editor changes anything about sections, the updated numbers can stay.
* [Install latest aiocoap from git](https://aiocoap.readthedocs.io/en/latest/installation.html)
* Run `./aiocoap-rd`
* Run the `examples/cord_epsim` example
* Watch aiocoap-rd's output: It does not warn about a client registering with the old .well-known/core name any more.
(but the code change is really minimal, so looking at the code change might be good enough.)
> sys/net/app/cord: Update to RD draft -27

- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
This PR adds a missing NULL check when allocating a `gnrc_pktsnip_t` on reception. If the pktbuf is full, GNRC netif doesn't return immediately.
Configure the Network Server to send a downlink to the node and try this patch:
```
diff --git a/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c b/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
index c30519220f..a6fb79cb72 100644
--- a/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
+++ b/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
@@ -26,7 +26,7 @@
#include "net/loramac.h"
#include "net/gnrc/netreg.h"
-#define ENABLE_DEBUG 0
+#define ENABLE_DEBUG 1
#include "debug.h"
static uint8_t _nwkskey[LORAMAC_NWKSKEY_LEN];
@@ -91,7 +91,7 @@ void gnrc_lorawan_mcps_indication(gnrc_lorawan_t *mac, mcps_indication_t *ind)
{
(void)mac; …
```
> gnrc_netif_lorawan: add missing NULL check

- makefiles/libc/picolibc.mk
With #16008 an error is outputted whenever a build is attempted with missing `picolibc`. Issue is this check runs always and does when querying build_system variables,eg:
```
BOARD=iotlab-m3 RIOT_CI_BUILD=1 make -C examples/gnrc_minimal info-debug-variable-BOARD_INSUFFICIENT_MEMORY 
/home/francisco/workspace/RIOT/makefiles/libc/picolibc.mk:10: picolibc was selected to be build but no picolibc.spec could be found
/home/francisco/workspace/RIOT/makefiles/libc/picolibc.mk:11: you might want to install "picolibc" for "arm-none-eabi"
/home/francisco/workspace/RIOT/makefiles/libc/picolibc.mk:12: or add "FEATURES_BLACKLIST += picolibc" to Makefile
/home/francisco/workspace/RIOT/makefiles/libc/picolibc.mk:13: *** check your installation or build configuration..  Stop.
```
This is not desirable …
> makefiles/libc/picolibc.mk: only fail when building

- .github/workflows/test-on-iotlab.yml
For actually running the test, the docker container is not used. As such, `riotctrl` needs to be installed for the tests to succeed.
I started a test run [over at my fork](https://github.com/miri64/RIOT/actions/runs/613389460). `tests/congure_test` should now pass (or at least not fail on import due to a missing `riotctrl` ;-)).
None
> gh-actions/test-on-iotlab: install riotctrl

- dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
It seems this needs to be backported, in order to continue backporting other PRs to the latest release (see https://github.com/RIOT-OS/RIOT/pull/16120#issuecomment-788789395).
A [new version of Pylint was released today](https://pypi.org/project/pylint/#history) and [this breaks the tools-test github action](https://github.com/RIOT-OS/RIOT/runs/1947401308?check_suite_focus=true) because of a small inconsistency in the compile_and_test_for_board script.
The raised issue is perfectly valid and this PR is fixing it by cleaning up a bit the `make_with_outfile` function. The return value of this function is never used so a bare return or no return is ok.
https://github.com/RIOT-OS/RIOT/blob/e0211f4574d08f2dac978a91a34a5842a7378491/dist/tools/compile_and_test_for_board/compile_and_test_for_board …
> tools/compile_and_test_for_board: fix lint [backport 2021.01]

- makefiles/tools/programmer.inc.mk
As reported in https://github.com/RIOT-OS/RIOT/pull/15970#issuecomment-787498973, #15970 introduces a regression for the very specific case where pyocd is used with multiple debuggers. Since pyocd output is not verbose, the Python wrapper is
disabled with pyocd.
Similar functionality could be added to the wrapper script later on and this change reverted.
```
BOARD=nrf52840-mdk make -C examples/hello-world/ flash-only
/home/francisco/workspace/RIOT2/dist/tools/pyocd/pyocd.sh flash /home/francisco/workspace/RIOT2/examples/hello-world/bin/nrf52840-mdk/hello-world.hex
[====================] 100%
0002854:INFO:loader:Erased 0 bytes (0 sectors), programmed 0 bytes (0 pages), skipped 12288 bytes (3 pages) at 8.39 kB/s
Done flashing
```
> makefiles/tools/programmer: do not use wrapper with pyocd

- core/include/thread.h
- core/include/thread_config.h
This PR moves some thread configuration defines from thread.h into thread_config.h.
As is, this only moves code around, but it is the first step to untangle the thread.h API from cpu specific stuff (see e.g., [here](https://github.com/RIOT-OS/RIOT/pull/15595#issuecomment-762094819)).
It is also a necessary step for providing alternative scheduler / core implementations.
This only moves code around, so a CI success should be fine.
Suggested in #15595.
> core/thread: move thread configuration into seperate header

- sys/include/net/gnrc/gomach/gomach.h
- sys/include/net/gnrc/lwmac/lwmac.h
- sys/net/gnrc/link_layer/gomach/gomach.c
- sys/net/gnrc/link_layer/lwmac/lwmac.c
The name of the thread running the MAC can be stored in ROM. Hence, add the missing `const` qualifier.
With it, `examples/gnrc_networking_mac` should compile with the `at86rf215` driver.
Code review should be sufficient IMO.
None
> sys/net/{lwmac,gomach}: add missing const qualifier

- dist/tools/programmer/programmer.py
If the help is only printed on failure, if the script does not detect failure
and programming still fails, the user has no idea how to get the full information.
Always print help on how to disable this feature.
The help text is now always printed.
```
For full programmer output add PROGRAMMER_QUIET=0 or QUIET=0 to the make command line.
✓ Flashing done! (programmer: 'edbg' - duration: 3.01s)
make BOARD=same54-xpro APP_VER=1612217220  -j flash  39,90s user 4,24s system 441% cpu 9,992 total
```
> dist/tools/programmer: always print how to disable programmer wrapper

- dist/pythonlibs/riotctrl_shell/tests/common.py
There was an [update to `riotctrl`](https://github.com/RIOT-OS/riotctrl/commit/c039b21e81cc015139ce7035c59c08688e769579) which introduced the usage of another method of `pexpect`'s `spawn` class: `read_nonblocking` to flush the read output by `pexpect`. The mock we currently use in the tests for `riotctrl_shell` does not support that method which makes the CI action `test-tools` fail. This fixes that.
`test-tools` should pass again.
Follow up on RIOT-OS/riotctrl#21
> riotctrl_shell.tests: add missing method to MockSpawn

- boards/stm32f3discovery/Makefile.dep
- boards/stm32f3discovery/include/board.h
This PR adds a default configuration for the lsm303dlhc available on the stm32f3discovery board (see dm00063382).
<details><summary>tests/driver_lslm303dlhc prints data</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=stm32f3discovery -C tests/driver_lsm303dlhc/ flash term --no-print-directory  …
```
> boards/stm32f3discovery: add lsm303dlhc configuration

- sys/congure/test/congure_test.c
- sys/include/congure/test.h
- sys/shell/commands/shell_commands.c
- tests/congure_test/main.c
- tests/congure_test/tests/01-run.py
The current version of `congure_tests` uses quite a lot of arguments which can be problematic, if e.g. the UART-USB-converter on a board does not support such long inputs. This splits up of those commands, by filling a central argument list. Since this framework is meant to be used with a test script only anyways, I don't think this extra step would make a problem.
```console
$ make -C tests/congure_test -j flash test
```
should still succeed for any board.
https://github.com/RIOT-OS/RIOT/pull/15953#issuecomment-786857059
Required for #15952 and #15953.
> congure_test: make shell commands shorter

- tests/mtd_raw/Makefile
See #16130. Disabling on CI to reduce false positives.
> tests/mtd_raw: disable for esp32-wroom-32

- drivers/include/usbdev_mock.h
While working on https://github.com/RIOT-OS/riot-os.org/pull/39, I noticed that the usbdev_mock driver documentation was directly linked to the main `drivers` category. As a result it shows up in the driver categories page (at the bottom):
This PR is fixing that by linking it to the `misc` category.
Related questions:
- should we maybe also link the radio hardware abstraction layer to the `drivers_netdev` category ?
- Same question with saul: should it go to the misc category (or maybe move it to sys) ?
Look at the documentation preview, the usbdev_mock module should show up in the Miscellaneous category.
None
> drivers/usbdev_mock: add to drivers_misc category

- dist/pythonlibs/riotctrl_shell/tests/common.py
There was an [update to `riotctrl`](https://github.com/RIOT-OS/riotctrl/commit/c039b21e81cc015139ce7035c59c08688e769579) which introduced the usage of another method of `pexpect`'s `spawn` class: `read_nonblocking` to flush the read output by `pexpect`. The mock we currently use in the tests for `riotctrl_shell` does not support that method which makes the CI action `test-tools` fail. This fixes that.
`test-tools` should pass again.
Follow up on RIOT-OS/riotctrl#21
> riotctrl_shell.tests: add missing method to MockSpawn [backport 2021.01]

- sys/event/event.c
Fixes this warning:
```
event.c: In function â€˜event_wait_multiâ€™:
event.c:96:12: error: â€˜resultâ€™ may be used uninitialized in this function [-Werror=maybe-uninitialized]
return result;
^~~~~~
```
The warning is valid if `n_queues` is zero, which it shouldn't be and which is checked by assert. alas, asserts are not always compiled in.
Found in #16143
> sys/event: fix possibly uninitialized return warning

- pkg/cn-cbor/Makefile
- pkg/wakaama/include/lwm2m_client.h
- tests/driver_hih6130/main.c
- tests/ssp/Makefile
This PR silences 2 warning raised when building with gcc 10 on riscv:
- upstream code of pkg/cn-cbor raises the return-local-address error. The latest version of the upstream code doesn't provide a fix for this
- `tests/ssp` allocates on purpose a buffer too small but this is catched by the compiler as array-bound warning. Similar to the stringop-overflow warning, the array-bound warning is silenced if it's available in the compiler.
- Both applications build with gcc 10 for riscv and works on hifive1b:
<details><summary>tests/pkg_cn-cbor</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=hifive1b -C tests/pkg_cn-cbor --no-print-directory flash test
docker run --rm --tty --user $(id -u) -v …
```
> tests / pkg: fixes for toolchain changes in docker container [backport 2021.01]

- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
This PR adds a missing NULL check when allocating a `gnrc_pktsnip_t` on reception. If the pktbuf is full, GNRC netif doesn't return immediately.
Configure the Network Server to send a downlink to the node and try this patch:
```
diff --git a/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c b/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
index c30519220f..a6fb79cb72 100644
--- a/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
+++ b/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
@@ -26,7 +26,7 @@
#include "net/loramac.h"
#include "net/gnrc/netreg.h"
-#define ENABLE_DEBUG 0
+#define ENABLE_DEBUG 1
#include "debug.h"
static uint8_t _nwkskey[LORAMAC_NWKSKEY_LEN];
@@ -91,7 +91,7 @@ void gnrc_lorawan_mcps_indication(gnrc_lorawan_t *mac, mcps_indication_t *ind)
{
(void)mac; …
```
> gnrc_netif_lorawan: add missing NULL check [backport 2021.01]

- uncrustify-riot.cfg
This doesn't change the config, it only beautifies it. Some comments are
shortened to keep the 100 char limit.
Verify that only there are no changes but white-space and comment changes.
None
> uncrustify-riot.cfg: align uncrustify config

- cpu/nrf52/Kconfig
- cpu/nrf52/Makefile.dep
- cpu/nrf52/Makefile.features
- cpu/nrf52/include/periph_cpu.h
- cpu/nrf5x_common/periph/uart.c
This PR adds `FEATURES_PROVIDED += periph_uart_nonblocking` for `nrf52840` devices. UARTE is not used to its full potential, since I could instead of writing single bytes use the tsrb buffer as the RAM buffer. But I found the logic much more complicated in this case since it required either:
- duplicated tx_buffers
- if using the tsrb buffer as the RAM buffer then it needs to keep track of where in the buffer we are
- but then sent bytes from the tsrb buffer need to be poped once they are sent out so either:
- at the END of transmission using `EVENT_ENDTX` and `TX.MAXCNT`
- every time a byte is sent out using ` EVENT_TXDRDY`
- but ` EVENT_TXDRDY` can overlap or be missed so at the end of transmission still need to POP the remaining ones
- so required keeping track of the ones that were …
> cpu/nrf52: add periph_uart_non_blocking to nrf52840

- boards/yarm/doc.txt
While reviewing https://github.com/RIOT-OS/riot-os.org/pull/39 I noticed there that the Doxygen link for YARM didn't work.
It turns out there was a missing comment ending in `doc.txt`.
Without this PR, there's no "Acmesystems YARM board" under boards. With this PR, you should see it under Boards
https://github.com/RIOT-OS/riot-os.org/pull/39
> boards/yarm: add missing comment ending in doc.txt

- drivers/bmx280/bmx280_saul.c
The SAUL implementation of the BMx280 currently returns the pressure in hPa.
The sensor, however, actually reads the pressure in Pa, leading to a
significant loss of precision.
Because the operation range of the BME280 and BMP280 is 300 hPa to 1100 hPa,
we can safely increase the precision by a factor of 10 without risk of overflow.
The only downside is that readings are now presented as `e1 Pa` (eg 10206e1 Pa).
Run SAUL example with a BME280 sensor. Read value:
```
2021-03-03 16:03:18,382 # saul read 2
2021-03-03 16:03:18,385 # Reading from #2 (bme280|SENSE_PRESS)
2021-03-03 16:03:18,387 # Data:	        10206e1 Pa
```
None.
> driver/bmx280: increase accuracy of SAUL pressure readings

- sys/clif/clif.c
- tests/unittests/tests-clif/tests-clif.c
This adds some test cases of attribute parsing for the CoRE Link Format parser module, and fixes the module to comply with them.
Specifically
- single-quoted values are not valid
- empty quoted values are not valid
- empty values when separator is present are not valid 
Check that the tests cases in 73cb813 make the test application fail. This should be fixed with 43dcee4.
Related to #15945
> sys/clif: fix attribute parsing

- uncrustify-riot.cfg
The coding convention was changed to suggest breaking lines with with
more than 100 chars. This brings the uncrustify configuration back in
sync.
I don't think this needs testing.
Change of coding convention was done in https://github.com/RIOT-OS/RIOT/pull/15793
> uncrustify-riot.cfg: update to coding convention

- pkg/qDSA/Makefile.dep
- pkg/qDSA/Makefile.include
qDSA as optimized implementations for AVR. The logic to select the optimized
backend predates the architecture features and uses some hand crafted logic.
This updates the logic to select the backend based on the boards architecture
using the feature system instead.
No changes in generated binaries.
Fixes compilation with ATXmega boards introduced in https://github.com/RIOT-OS/RIOT/pull/15758
> pkg/qDSA: fix backend selection log

- boards/nucleo-f722ze/Kconfig
- boards/nucleo-f722ze/Makefile.features
- cpu/stm32/include/can_params.h
- cpu/stm32/include/candev_stm32.h
- cpu/stm32/periph/can.c
- sys/include/can/common.h
- tests/candev/main.c
boards/nucleo-f722ze: Add periph_can support
cpu/stm32: Add CAN support for f722ze board
f722ze board has ONLY 1 CAN interface, fix compiling error which
treats f722xx has more than 1 CAN.
- stm32f722ze MCU contains CAN 2.0B interface. Makefile.features for board nucleo-f722ze is missing this periph_can. (1st commit)
- Fix a bug in cpu/stm32/include/can_params.h which treats f722ze with more than 1 CAN interfaces. (1st commit)
- For test purpose, add loopback. Due to hardware limitation, I have to use loopback mode to test my changes. (2nd commit)
First, pin CAN_TX(PD1) and CAN_RX(PD0) shall be connected with 120 ohm. For me, i short the pins for loopback test is good enough
Second, compile candev application to test. in RIOT/ folder, run
CFLAGS=-DCAN_LOOPBACK_MODE make …
> boards/nucleo-f722ze: Add periph_can

- sys/riotboot/flashwrite.c
There is still a missing `FLASHPAGE_SIZE` dependency that is not triggered unless `DEVELHELP` is set:
- with this PR:
```
DEVELHELP=1 BOARD=nucleo-f446re make -C tests/riotboot_flashwrite/ all -j3
Building application "tests_riotboot_flashwrite" for "nucleo-f446re" with MCU "stm32".
compiling /home/francisco/workspace/RIOT/dist/tools/riotboot_gen_hdr/bin/genhdr...
make: Nothing to be done for 'all'.
"make" -C /home/francisco/workspace/RIOT/boards/nucleo-f446re
"make" -C /home/francisco/workspace/RIOT/boards/common/nucleo
"make" -C /home/francisco/workspace/RIOT/cpu/stm32
"make" -C /home/francisco/workspace/RIOT/cpu/cortexm_common
"make" -C /home/francisco/workspace/RIOT/cpu/cortexm_common/periph …
```
> sys/riotboot: remove remaining FLASHPAGE_SIZE dep

- cpu/atmega_common/Kconfig
- cpu/atmega_common/Makefile.features
- cpu/avr8_common/startup.c
- cpu/cortexm_common/Kconfig
- cpu/cortexm_common/Makefile.features
- cpu/cortexm_common/vectors_cortexm.c
- cpu/kinetis/include/cpu_conf.h
- cpu/kinetis/vectors.c
- cpu/msp430_common/Kconfig
- cpu/msp430_common/Makefile.features
- cpu/msp430_common/startup.c
- kconfigs/Kconfig.features
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/dbgpin.h
- tests/dbgpin/Makefile
- tests/dbgpin/main.c
- tests/dbgpin/tests/01-run.py
Successor of #14304
This PR contains a slightly reworked version of the code PRed in #14304:
- this module is now a header file + some Makefile entries only. Thanks @maribu for the pointers!
- the usage of this module now depends on the `dbgpin` feature to be provided
- This PR only contains the feature and initialization hook for `cortexm` platforms
- all other platforms can/should be added on demand step by step, this way we don't end up in this huge loop once more...
With these changes the PR is much slimmer now.
Run the `tests/dbgpin` example on any cortexm board. Either check the output of the default pin (`GPIO_PIN(0,0)`) or define alternative pin(s). The output is best observed with a scope o logic analyzer...
successor of #14304
> sys: add `dbgpin` module for debugging and profiling (take 2)

- dist/tools/avarice/debug.sh
There are some Linux distributions like DEBIAN 10 that gdb-multiarch doesn't work as expected and debug section not start.  Since AVARICE is dedicated to AVR architecture, let's check first by the default tool then multiarch version.
`make BOARD=<board name> all flash debug`
detected at #15758
CC: @maribu
> dist/tools/avarice/debug.sh: Change gdb check order

- sys/include/shell.h
- sys/shell/shell.c
- tests/periph_spi_dma/Makefile.ci
- tests/shell/main.c
- tests/shell/tests/01-run.py
This PR adds a macro that allows adding shell commands using a cross file array.
It basically allows this to be put in *any* file:
```
#include "shell.h"
static int _my_command(int argc, char **argv) {
// ...
}
SHELL_COMMAND(my_command, "my command help text", _my_command);
```
This PR extends the tests/shell test scripts. Running this on some more platforms (AVR, RISC-V, ...) would be helpful!
Otherwise, please give feedback on the integration / usage.
First user of  [XFA](https://github.com/RIOT-OS/RIOT/pull/15002).
> sys/shell: add XFA support

- dist/tools/coccinelle/check.sh
- dist/tools/headerguards/check.sh
- dist/tools/uncrustify/uncrustify.sh
I am always a bit irritated when the diffs are _above_ the lines they are commenting on. This should fix that.
I provided changes to trigger annotations. See Files tab.
Depends on #15795
> static_tests: move diff annotations by offset.

- boards/native/Makefile.include
- examples/filesystem/main.c
- pkg/qcbor/Makefile
- pkg/wakaama/Makefile
- pkg/wolfssl/Makefile
- tests/unittests/tests-ieee802154/tests-ieee802154.c
adds `-Og` to board/native `CFLAGS`
There is information out there suggesting that `-Og` is actually better for debugging than `-O0`
it is added in the board include since all `CFLAGS` for native are set there 
(it does not have a makefile/arch it also has no arch but that is an other PR)
compile with native and see how basic optimization is working (e.g.: actually inline static inlines or reduce unused (static) code)
not today
> board/native: add basic debugging compatible optimization

- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/netif/netif.c
If we call `netif_register()` before we can be sure that the interface can be configured, a 'zombie' interface remains in the list, causing all kinds of trouble down the line.
Only call `netif_register()` if `init()` was successful.
Build `examples/gnrc_networking` with e.g `USEMODULE += at86rf215` for a board that does not have a `at86rf215` radio. (Any other network driver will do, as long as the board doesn't have the hardware.)
If you call `ifconfig` an assert will trigger, if you remove the `assert()`, you'll get something like
```
2021-02-01 19:03:16,720 # Iface  6  HWaddr: FC:C2:3D:0D:2D:1F 
2021-02-01 19:03:16,726 #           L2-PDU:1500  MTU:1500  HL:64  Source address length: 6
2021-02-01 19:03:16,729 #           Link type: wired
2021-02-01 19:03:16,732 #           inet6 group: …
```
> sys/net/gnrc/netif: only register netif after init was successful

- drivers/soft_spi/soft_spi.c
fix:fix drivers/soft_spi transfer one byte without read back bug
test:test read w25q64 id success
> drivers/soft_spi: fix soft spi transfer bug

- boards/calliope-mini/board.c
- boards/microbit-v2/board.c
- boards/microbit/board.c
This PR makes use of BTNx_MODE for some boards which were not using them in their board.c file. This is purely cosmetic as the right configuration was already set but change it anyway for consistency.
A green CI should be enough.
None
> boards: use BTNx_MODE when defined

- cpu/stm32/include/candev_stm32.h
We can deduce the number of available CAN interfaces from the vendor headers so no need to hard-code this number for individual part numbers.
The binaries should not change.
https://github.com/RIOT-OS/RIOT/pull/16161#discussion_r589645304
> cpu/stm32: candev: derive number of CAN interfaces from vendor header

- pkg/lwip/contrib/sock/ip/lwip_sock_ip.c
- pkg/lwip/contrib/sock/lwip_sock.c
Use lwIP macro to iterate netifs instead of doing it manually. This reduces
dependency on lwIP internals (for instance it will not break if `LWIP_SINGLE_NETIF` is used)
All lwip tests still pass.
None
> pkg/lwip: Use NETIF_FOREACH macro in sock implementation

- drivers/sx127x/sx127x_netdev.c
- examples/lorawan/main.c
- pkg/semtech-loramac/contrib/semtech_loramac.c
- pkg/semtech-loramac/contrib/semtech_loramac_radio.c
- pkg/semtech-loramac/include/semtech_loramac.h
- sys/auto_init/loramac/auto_init_loramac.c
- sys/include/net/loramac.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
The current Loramac-node port (that we called semtech-loramac for historical reasons) is tightly coupled with the sx127x radio driver although it should be possible to use other radio devices (such as sx126x or llcc68 see #16177 and I have a branch for sx126x).
This PR is adapting the package to only control the radio via the netdev interface. The radio is either initialized in auto_init (for the `tests/pkg_semtech-loramac` application) or in the application itself (for `examples/lorawan`): this should be considered as an API change, since the user has to take care of this part now.
Some stuff were removed from the loramac radio layer:
- "is channel free" is always true. I don't think this is used by our loramac package port
- "time on air" computation return 0. I could think of a generic …
> pkg/semtech-loramac: refactor to use netdev API only

- sys/net/sock/sock_util.c
Otherwise, the following strncpy() leaves strtol() with a non-terminated
buffer.
This caused random errors based on the stack state, so it is hard to reproduce.
Found in https://github.com/RIOT-OS/RIOT/pull/16193.
> sys/net/sock_util: zero out temporary buffer

- drivers/include/periph/spi.h
use `@retval` to document individual return values rather than `@return`
`make doc`
none
> drivers/periph_spi: fix Doxygen commands

- sys/include/net/gnrc/netif/pktq.h
- sys/net/gnrc/netif/pktq/gnrc_netif_pktq.c
- tests/unittests/tests-gnrc_netif_pktq/tests-gnrc_netif_pktq.c
This adds a new function to the API of `gnrc_netif_pktq` to check how much resources (i.e. number of entries in the pool) are currently in use.
I extended the unittests, so they should still pass.
gnrc_netif_pktq: add function to check usage
None
> gnrc_netif_pktq: add function to check usage

- release-notes.txt
Release notes mentioned QN808x instead of NQ908x.
> Fix typo in release notes.

- sys/include/net/gnrc/lorawan.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mlme.c
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_region.c
- sys/net/gnrc/link_layer/lorawan/include/gnrc_lorawan_internal.h
This PR implements channel mask for GNRC LoRaWAN. The channel mask is used to enable/disable LoRaWAN channels (e.g when the network server sends an ADR-Req command or if requested by the user).
Since there's no support for adding/removing channels yet, I'm not exposing this to the user of the interface.
This is required in order to implement ADR (already handled by @akshaim)
There's a test commit. Check that GNRC LoRaWAN doesn't assert and that it only transmit in a single channel (868.1 MHz).
None so far
> net/gnrc_lorawan: implement channel mask support

- tests/periph_ptp_clock/main.c
The API doc of ptp_clock_adjust_speed says regarding the correction
parameter:
1. A call with @p correction set to `0` restores the nominal clock speed.
2. A call with a positive value for @p correction speeds the clock up
by `correction / (1 << 32)` (so up to ~50% for `INT32_MAX`).
3. A call with a negative value for @p correction slows the clock down by
`-correction / (1 << 32)` (so up to 50% for `INT32_MIN`).
So we need to divide by 2^32, not 2^32 - 1 (or `UINT32_MAX`).
Output of the test on a Nucleo-F767ZI:
```
READY
s
START
main(): This is RIOT! (Version: 2021.04-devel-1036-g42df5-tests/periph_ptp_clock)
Testing clock at speed 0 (~100.000 % of nominal speed): SUCCEEDED
Testing clock at speed 2147483647 (~149.999 % of nominal speed): SUCCEEDED
Testing clock at speed -2147483648 …
```
> tests/periph_ptp_clock: fix bug in debug print

- bootloaders/riotboot_dfu/bootloader_selection.h
- bootloaders/riotboot_dfu/main.c
For USB bootloaders, it is common to have a way of entering the bootloader even when the application is not cooperating. A typical way is to poll a button on startup. (For example, the bootloaders shipped with nrf52840dongle and the particle xenon boards to that; the latter in a more elaborate fashion that includes blink patterns).
It doesn't help with remote bricking, and it doesn't help against flash writes to the bootloader (both of which might be mitigated by additional means), but solves the common case of "I forgot to give my application the right USEMODULES to get back into DFU" or "crash at board_init". 
* Flash the bootloader using `make -C bootloaders/riotboot_dfu BOARD=particle-xenon PROGRAMMER=openocd DEBUG_ADAPTER=stlink all flash`
* Dismantle your programmer. (Well, at least …
> riotboot: Mode selection for boards

- bootloaders/riotboot_dfu/doc.txt
This adds usage documentation to riotboot_dfu; it explains riotboot_dfu's relation to riotboot, and primarily how it is used (both to install in the first place, and later to flash applications).
* Read the built documentation.
This builds on <del>#16025</del> (to be visible in the first place), and on #16011 (because I don't want to change the text later). It's best merged only after thoes (and can then be rebased onto master to get rid of the fixup / merge commits).
> riotboot_dfu: Add documentation

- drivers/include/saul.h
SAUL drivers habitually do things like mutex locking that are forbidden in interrupt contexts. This change makes that explicit in the documentation, and puts the reposnsibility on the SAUL callers (and not the drivers) to check that no calls come from an interrupt context.
The note is placed with the driver documentation, as that's where general SAUL text resides; the SAUL registry documentation page primarily contains a link there, and it's not repeated for the individual functions.
Read the documentation.
> doc/SAUL: State expectations on blocking and interrupts

- tests/driver_ccs811/main.c
- tests/driver_ccs811_full/main.c
I was trying to run the test, but was puzzled why it was failing on reading when everything else seemed fine. Seems the error code check is wrong. This PR fixes it.
The test now works...
```
2021-03-21 20:41:33,607 # main(): This is RIOT! (Version: 2021.04-devel-1038-g488d7-riotfp-demo)
2021-03-21 20:41:33,609 # CCS811 test application
2021-03-21 20:41:33,610 #
2021-03-21 20:41:33,613 # +------------Initializing------------+
2021-03-21 20:41:33,821 #
2021-03-21 20:41:33,824 # +--------Starting Measurements--------+
2021-03-21 20:41:37,808 # TVOC [ppb]: 0
2021-03-21 20:41:37,809 # eCO2 [ppm]: 400
2021-03-21 20:41:37,813 # +-------------------------------------+
2021-03-21 20:41:38,803 # TVOC [ppb]: 0
2021-03-21 20:41:38,804 # eCO2 [ppm]: 400
2021-03-21 20:41:38,808 # …
```
> tests/driver_ccs811%: fix read return code check

- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
The PR is a minor fix that adds a check for `NETOPT_LORAWAN_DR` to avoid out of bound values
Tested using `b-l072z-lrwan1` target.
```
ifconfig 3 set dr 16
error: unable to set datarate
```
NA
> gnrc_netif_lorawan: Validate DR

- drivers/at86rf215/at86rf215.c
- drivers/at86rf215/at86rf215_getset.c
- drivers/at86rf215/at86rf215_netdev.c
- drivers/at86rf2xx/at86rf2xx.c
- drivers/at86rf2xx/at86rf2xx_getset.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
- drivers/cc2420/cc2420.c
- drivers/cc2420/cc2420_getset.c
- drivers/cc2420/cc2420_netdev.c
- drivers/cc2420/include/cc2420_registers.h
- drivers/include/at86rf215.h
- drivers/include/at86rf2xx.h
- drivers/include/kw2xrf.h
- drivers/include/mrf24j40.h
- drivers/kw2xrf/kw2xrf.c
- drivers/kw2xrf/kw2xrf_getset.c
- drivers/kw2xrf/kw2xrf_netdev.c
- drivers/kw41zrf/include/kw41zrf_getset.h
- drivers/kw41zrf/kw41zrf.c
- drivers/kw41zrf/kw41zrf_getset.c
- drivers/kw41zrf/kw41zrf_netdev.c
- drivers/mrf24j40/mrf24j40.c
- drivers/mrf24j40/mrf24j40_netdev.c
- sys/include/net/netopt.h
- sys/net/gnrc/link_layer/gomach/gomach.c
- sys/net/gnrc/link_layer/lwmac/lwmac.c
- sys/net/gnrc/netif/gnrc_netif.c
- tests/driver_xbee/Makefile.ci
Update the API contract to make `NETOPT_TX_END_IRQ`, `NETOPT_TX_START_IRQ`, `NETOPT_RX_END_IRQ`, and `NETOPT_RX_START_IRQ` read-only. That is, the corresponding events are not expected to be always send, and the netopts can only be used to test if a netdev supports them.
Additionally, the handful of drivers actually having support for configuring at run time were adapted.
- The event on RX completion is already mandatory, as no network stack can operate without it. The event on TX completion recently became mandatory with the new confirm_send API. There is not reason to ever turn them off.
- Configuring the other events at run time increases complexity, ROM size, and maintenance burden
- There really seems to be no use case to configure them at runt time.
For of the following list of …
> sys/net/netopt: make NETOPT_TX_END_IRQ and friends read-only

- boards/microbit-v2/doc.txt
For the microbit v2, schematics and pinout were just published a few days ago. This adds the relevant links.
Look at the documentation output.
> boards/microbit-v2: Add links to schematics etc.

- sys/shell/commands/sc_saul_reg.c
SAUL devices can legitimately be unnamed; catching all attempts to read
their names with a generic "(no name)" name.
* Create a SAUL device with a NULL name (whichever board you have, run the saul example and search where the available device's name comes from).
* Replace that with NULL
* Run the saul example, observe the memory dump produced by any `saul` command on that device.
(Some libc may catch this; the ones used with both LLVM and GCC by default with my particle-xenon does not)
* After applying the patch, try again: it prints (no name) there.
> sys/shell/saul: Don't print from NULL

- core/msg.c
Fix for some mismatched format specifiers which triggers compiler warnings with some extra flags.
Should be minimal impact since this is in the debug print code.
N/A
> core/msg: Fix mismatched printf formats

- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/lwip/include/lwipopts.h
Set link state correctly in lwIP for interfaces that support
the `NETOPT_LINK` option. Interfaces that do not support it
(like tap for native arch) remain up all the time.
Netdevs that support `NETOPT_LINK` but do not send `NETDEV_EVENT_LINK_UP`/`DOWN`
events will end up with a mismatched link state - but DHCP would
already not start for them either.
tests/lwip still passes on native board
Flash a board with an app using lwIP and try plugging/unplugging ethernet cable and verify link state with ifconfig shell command, and that DHCP still gets an address when starting with cable unplugged (if using IPv4).
> pkg/lwip: Set netif link state properly when supported

- pkg/lwip/contrib/lwip.c
Makes 6lowpan netifs work even if dual stack is enabled,
and one less static method needed.
* `tests/lwip` still passes
* Pinging board still works with `example/paho-mqtt` app which uses lwip
None
> pkg/lwip: Add netifs with netif_add_noaddr

- cpu/stm32/periph/eth_common.c
- cpu/stm32/periph/ptp.c
- Clear the PTP timer interrupt *after* the user callback is executed
- Otherwise it would be possible that the ISR sets another super
short timeout that triggers during ISR, which also gets cleared
- This is a pretty nasty race condition :-/
- The debug output was a bit too verbose to be generally useful. Some
noise is now silenced unless `DEBUG_VERBOSE` is `#define`d to 1
Should be simple enough to go in by code review only. But one could use https://github.com/RIOT-OS/RIOT/pull/15960#pullrequestreview-619074700 which triggers the race condition for me without the fix.
Found while testing https://github.com/RIOT-OS/RIOT/pull/15960
> cpu/stm32/periph_ptp: bugfix & better debug output

- boards/bastwan/Kconfig
- boards/bastwan/Makefile
- boards/bastwan/Makefile.dep
- boards/bastwan/Makefile.features
- boards/bastwan/Makefile.include
- boards/bastwan/board.c
- boards/bastwan/include/board.h
- boards/bastwan/include/gpio_params.h
- boards/bastwan/include/periph_conf.h
- examples/lua_REPL/Makefile.ci
- tests/bench_xtimer/Makefile
Add RIOT OS support for [BastWAN Board](https://github.com/ElectronicCats/BastWAN).
Board uses on rak4260 which itself uses on samr34 with integrated Lora.
Based on samr34 xplained pro board (`boards/samr34-xpro`) and adopted to RAK specific pin mappings. 
Fieldtested with SX127X module and semtech stack from `examples/lorawan`.
Tested all ADC channels.
UART, USB and GPIOS/LEDs are working as defined.
not known
> boards/bastwan: Support BastWAN Board

- sys/include/ztimer/periph_ptp.h
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
- sys/ztimer/periph_ptp.c
This PR adds support for PTP-Clock in ztimer. 
I did some basic tests on `nucleo-f767zi` of clock and timer and compared the time values printed with the shell timestamps. It requires to use `ztimer_usec`.  
None
> sys/ztimer: add periph_ptp backend

- cpu/stm32/periph/ptp.c
Scientific rounding is a very uncommon term (not found in the Wikipedia article about rounding) and no good DDG results.
The edge case *.5  has different resolution methods (none is more scientific than the other one):
- The macro implements what in Germany is called "Kaufmänisches Runden" the English Wikipedia calls it "round half up" 
- An other common tie-breaking rule is "Round half to even", which has the blessing of the IEEE and has many other names assigned to it like in contrast to the german one "bankers rounding".
Both rules may skew further scientific test applied to the data and therefor have to be used with caution.
(the second rule will have a little more even values (that might skew numeral tests e.g. for data validity), the first has a little higher average)
change the …
> stm32/ptp: avoid creating a new rounding rule

- boards/nucleo-f767zi/Kconfig
- boards/nucleo-f767zi/Makefile.features
stm32f767zi MCU contains CAN 2.0B interface. Makefile.features for board nucleo-f767zi is missing this periph_can.
similar to nucleo-722ze https://github.com/RIOT-OS/RIOT/pull/16161
Connect pin CAN_TX(PD1) and CAN_RX(PD0) a jumper for loop-back test only, due to hardware limitation.
Compile candev application to test. in RIOT/ folder, run
`CFLAGS=-DCONFIG_USE_LOOPBACK_MODE make BOARD=nucleo-f767zi CAN_DRIVER=PERIPH_CAN -C tests/candev flash term`
In pyterm, type send to send bytes, and check data is looping back to receive FIFO with command receive
My test as following i.e.
```
2021-03-18 20:55:07,652 # help
2021-03-18 20:55:07,655 # Command              Description
2021-03-18 20:55:07,658 # ---------------------------------------
2021-03-18 20:55:07,662 # send                 send some …
```
> boards/nucleo-f767zi: Add periph_can support

- makefiles/boot/riotboot.mk
The build target for RIOTBOOT fails to depend on ${ARCHIVES}.
With this patch, like in /Makefile.include, it now pulls in ARCHIVES before ELFFILES.
How it fails:
* Build anything that uses ARCHIVES (in my case, Rust applications) with `FEATURES_REQUIRED+=riotboot make all riotboot/flash-slot0` and see how it fails with `arm-none-eabi-gcc: error: target/thumbv7em-none-eabihf/debug/libshell.a: No such file or directory`.
* Build without riotboot and see how it gets pulled in
* Build with riotboot and see everything just work
How it works:
* Apply patch and clear bin
* Works the first time
> riotboot: Build ARCHIVES

- boards/microbit-v2/doc.txt
- boards/microbit/doc.txt
This adds links from the two micro:bit boards to the microbit module that provides display drivers.
The link is relevant because a) for lack of a general display support a user would not expect anything to be there, and b) may not find it due to the different styling of "micro:bit". (OK, I didn't).
Look at the built documentation.
> boards/microbit*/doc: Link to matrix display driver

- Makefile.base
- Makefile.include
I realized that actually `SECONDEXPANSION` was not enabled for applications but only for modules since it was in `Makefile.base`, so this PR also enables that.
Test build times?
Split out from #16197.
> Makefile: enable SECONDEXPANSION globally for modules and applications

- tests/bench_msg_pingpong/main.c
Drop the global volatile variable, clean up the code.
`tests/bench_msg_pingpong` should still work. 
Not using a global variable is slightly slower, but less error prone.
{ "result" : 86486, "ticks" : 555 }
{ "result" : 86799, "ticks" : 553 }
> tests/bench_msg_pingpong: cleanup

- pkg/nimble/Makefile.dep
- pkg/nimble/statconn/include/nimble_statconn.h
- pkg/nimble/statconn/nimble_statconn.c
When keeping multiple connections in parallel on a node, it has proven to be beneficial when each connection uses a slightly differing connection interval, as this prevents the connections losses due to connection event shadowing caused by clock drift.
This PR adds the possibility to configure the `nimble_statconn` module to use a random connection interval for each new connection from a defined range. Simply configure `NIMBLE_STATCONN_CONN_ITVL_MIN_MS` and `NIMBLE_STATCONN_CONN_ITVL_MAX_MS` to different values.
This PR changes the modules API slightly, but as it is marked as ` @experimental` this should be ok.
- build `tests/nimble_statconn_gnrc` with e.g. `CFLAGS=-DNIMBLE_STATCONN_CONN_ITVL_MAX_MS=100` for an `nrf52(840)dk` or similar
- flash it to 2 boards in radio range
- connect the …
> pkg/nimble/statconn: allow random connection interval

- cpu/atxmega/atxmega_cpu.c
The current ATxmega clock_init enable DFLL to improve the accuracy of the 2MHz and 32MHz internal oscillators.  In some ATxmega revisions, after started DFLL the clock become unstable.  Add another sync point for 32MHz internal oscilator.
This avoid a BUG when clock is is not ready and clock_init try switch from 2MHz to 32MHz as main clock.
Detected when try run RIOT-OS an ATxmega128A1 and ATxmega192A3.
CC: @benpicco @maribu
> cpu/atxmega/atxmega_cpu: Fix clk sel after dfll en

- sys/pm_layered/pm.c
Using atomic_utils for atomically accessing the state of `pm_layered` rather than disabling IRQs. For 32 bit platforms the 32 bit load is implemented lock free, so there should be minor gain in CPU cycles and ROM.
Theoretically, `pm_block()` and `pm_unblock` could use `atomic_fetch_add_u8()` and `atomic_fetch_sub_u8()`. But this increases ROM size when GCC is used, which doesn't optimize out the unused return value.
1. `tests/periph_pm` should still behave as before
2. There should be ~8 bytes less ROM for 32 bit Archs
None
> sys/pm_layered: use atomic_utils

- pkg/lwip/contrib/lwip.c
- pkg/lwip/contrib/netdev/lwip_netdev.c
Change the special case hack for native tap interfaces into a general start
of DHCP for all Ethernet interfaces. 
Netifs without link status support will keep sending discover
messages with increasing time between.
Netifs that support link status will wait for the link to be up,
and then start sending.
Netifs that support link status but send no link status events
will continue to not work (unless link status is up from the
first check when setting it up).
Test for native board in `tests/lwip` still passes (in dualstack & v6 only)
Boards without link status support will now have DHCP starting properly (there can be a delay from inserting cable until DHCP sends next discover message).
Boards with link status event support will send DHCP discover right away after link comes up.
Depends on …
> pkg/lwip: Start DHCP early for all Ethernet interfaces

- sys/fs/devfs/Makefile
- sys/fs/devfs/hwrng.c
- sys/fs/devfs/random.c
`devfs-random` and `devfs-hwrng` are already declared as pseudo modules so it makes little sense to have one file which contains two conditionally compiled implementations.
- Check that devfs random works both with and without hwrng present
None
> devfs: Split devfs-random into two files using submodules

- boards/common/arduino-due/include/periph_conf.h
- cpu/sam3/include/periph_cpu.h
This PR allows overriding the default value for the rtt frequency, it's one I missed in #14303.
Sadly I do not have a BOARD to test, but this should be the testing procedure:
- `tests/periph_rtt` should still pass on `sam3` boards with different frequencies
- `BOARD=arduino-due make -C tests/periph_rtt flash test --no-print-directory -j3`
- `CFLAGS+=-DRTT_FREQUENCY=1024 BOARD=arduino-due make -C tests/periph_rtt clean flash test --no-print-directory -j3`
Although IMO a green Murdock should be enough.
Realized I missed this `sam*` family while looking at  #16254
> boards/arduino-due: allow changing frequency

- cpu/sam3/periph/rtt.c
- tests/periph_rtt/main.c
- Previously, the return value was off by one. The second commit fixes this
- The first commit sneaks in some enhancement of `tests/periph_rtt` to ease debugging, as this might be useful in the future as well
`make BOARD=arduino-due -C tests/periph_rtt` should now pass
Noticed in https://github.com/RIOT-OS/RIOT/pull/16257
> cpu/sam3/periph_rtt: fix rtt_get_alarm()

- boards/common/microbit/microbit.c
- boards/common/nrf52/include/cfg_timer_default.h
- cpu/nrf5x_common/periph/timer.c
Up to now, nrf52 only exposes its timers NRF1 and NRF2 (as TIMER_0 and TIMER_1).
This adds the remaining two NRF3 and NRF4 (as TIMER_2 and TIMER_3).
As a result, the microbit-v2 LED matrix display can be moved to one of the higher timers; until that is done, it breaks the 802.15.4 stack whose NRF802154_TIMER also uses TIMER_1 (and ztimer uses TIMER_0 so we're in a pinch already).
* Run the periph_timer test, it still succeeds.
* Run the board_microbit test, it stil shows a running text. (This can also double as a test for timer 2; for timer 3 you can change TIMER_DEV_NUM in the microbit-v2 section of b/c/microbit/microbit.c).
* Why is NRF0 not exposed?
* Is the channel number right? ([The manual](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52833%2Ftimer.html&cp=4_1_0_5_27_4& …
> cpu/nrf52: Expose more timers

- examples/lorawan/main.c
- sys/auto_init/loramac/auto_init_loramac.c
- sys/net/gnrc/netif/init_devs/init.c
This PR adds the missing logic to be able to use the semtech-loramac package with sx126x and llcc68 radios.
One can test this PR out-of-the-box using an sx1261/sx1262/llcc68 mbed shield and a nucleo 64 board (I tested with nucleo-l476rg and nucleo-g431rb): just flash the `tests/pkg_semtech-loramac` application and verify that OTAA join procedures are successful and data can be sent to a LoRaWAN backend:
<details><summary>some basic tests with TTN</summary>
```
$ LORA_DRIVER=sx1261 make BOARD=nucleo-g431rb -C tests/pkg_semtech-loramac/ flash term
make: Entering directory '/work/riot/RIOT/tests/pkg_semtech-loramac'
Building application "tests_pkg_semtech-loramac" for "nucleo-g431rb" with MCU "stm32".
[INFO] updating driver_sx126x /work/riot/RIOT/build/pkg/driver_sx126x/.pkg-state.git-downloa …
```
> pkg/semtech-loramac: add support for sx126x/llcc68 radios

- pkg/nimble/netif/include/nimble_netif.h
- pkg/nimble/netif/nimble_netif.c
- sys/shell/commands/sc_nimble_netif.c
This PR extends the `ble` shell command with the `ble chanmap` subcommand, allowing to list the used channel map for each open connection. This is e.g. useful to check which data channels are currently used in each connection so see if any adaptive channel selection is being used.
- flash the `gnrc_networking` with `USEMODULE=nimble_netif` on any two nrf52(840) nodes that are in radio range of each other
- open a BLE connection, e.g. node A: `ble adv foo`, node B: `ble connect foo`
- list the used channel map on each node: `ble chanmap`
-> the output should be `1f ff ff ff ff` on both nodes, as NimBLE is per default always using all 37 data channels.
none
> pkg/nimble/netif: allow to read used channel map

- sys/event/event.c
- sys/include/event.h
- tests/event_wait_timeout_ztimer/Makefile
- tests/event_wait_timeout_ztimer/Makefile.ci
- tests/event_wait_timeout_ztimer/main.c
- tests/event_wait_timeout_ztimer/tests/01-run.py
If one wants to use the timeout functionality with the `event` module, it is so far tied to `xtimer`. This PR also adds support to use `ztimer` for the same purpose, by introducing a new function called `event_wait_timeout_ztimer()`. This function allows to specify the used ztimer clock, and hence it can be used for any fitting time scale and no 64-bit version of that function is needed.
I'd like to have this function merged to proceed on my path to remove any `xtimer` and `periph_timer` dependencies from NimBLE...
Run the `tests/event_wait_timeout` test on any platform of your choosing. It should still succeed.
none
> sys/event: add event_wait_timeout_ztimer()

- tests/driver_sx126x/Makefile.ci
- tests/event_wait_timeout_ztimer/Makefile.ci
Add `atmega328p-xplained-mini` to `BOARD_INSUFFICIENT_MEMORY` in `tests/driver_sx126x` and `tests/event_wait_timeout_ztimer`.
Green CI
#16239
> tests: add atmega328p-xplained-mini to insufficient memory list

- cpu/native/periph/rtc.c
- sys/include/ztimer.h
- sys/include/ztimer/config.h
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
- sys/ztimer/auto_init.c
- sys/ztimer/periph_rtc.c
- tests/ztimer_msg/Makefile
- tests/ztimer_msg/main.c
- tests/ztimer_underflow/Makefile
- tests/ztimer_xsec/Makefile
- tests/ztimer_xsec/Makefile.ci
- tests/ztimer_xsec/README.md
- tests/ztimer_xsec/app.config.test
- tests/ztimer_xsec/main.c
- tests/ztimer_xsec/tests/01-run.py
I adopted #15715 @maribu wired up some ZTIMER_SEC support supporting ztimer_periph_rtc and ztimer_periph_rtt
- add `ZTIMER_SEC` support which is currently documented but missing.
- restructure the auto init. for readability an flexibility.
- avoid the use of RTT for MSEC if its Frequency less than 1kHz.
- puts the power mangement association to the base clk (basic timer / rtt / rtc) 
by @maribu:
- tests/ztimer_msg has been updated to allow testing `ZTIMER_SEC`. Note: Uncomment a line in the Makefile as documented there
- tests/ztimer_underflow has been updated to allow testing `ZTIMER_SEC`
-Run `make TEST_ZTIMER_CLOCK=ZTIMER_SEC -C tests/ztimer_underflow flash test`
-This fails for me, which proves two things: a) wiring up the RTC worked, and b) there is a preexisting bug in master …
> sys/ztimer: add ZTIMER_SEC, improve auto_init

- cpu/stm32/periph/gpio_all.c
I've found a race condition in the GPIO IRQ handling. Without this patch, there is a small probability to get caught in an endless loop since the related *Pending Request* bit is never cleared.
What happend:
1. The GPIO's related `IMR` bit is enabled
2. The condition of the interrupt is met (like the GPIO went from HIGH to LOW) and the corresponding `PR` bit is set
3. The `IMR` bit is cleared by the program
4. The program gets interrupted and `isr_exti()` is called
5. `isr_exti()` reads the `PR` bits and masks out the bit that caused its execution. Thus, the `PR` bit is never cleared and `isr_exti()` is called again after `cortexm_isr_end()`.
The [DOSE driver](http://api.riot-os.org/group__drivers__dose.html) uses the GPIO IRQ to detect start bits of Ethernet frames. This IRQ is then …
> cpu/stm32/gpio: fix IRQ handler

- tests/sema/Makefile
- tests/sema/Makefile.ci
- tests/sema/main.c
- tests/sema/tests/01-run.py
This is a simple test for sema.
`BOARD=native make  -C tests/sema flash test`
> tests/sema/: added simple sema test

- sys/crypto/aes.c
- sys/crypto/ciphers.c
- sys/include/crypto/ciphers.h
This PR removes the [max_key_size](https://github.com/RIOT-OS/RIOT/blob/3e32d55c33645c7de2107b144f4a712a5eca0997/sys/include/crypto/ciphers.h#L80) member of the `cipher_interface_st`. The only place I found where this struct member is used is [this](https://github.com/RIOT-OS/RIOT/blob/3e32d55c33645c7de2107b144f4a712a5eca0997/sys/crypto/ciphers.c#L25) check. To me this check seems unnecessary. In my opinion it should be the job of the specific cipher modules,  e.g. [aes.c](https://github.com/RIOT-OS/RIOT/blob/master/sys/crypto/aes.c), to have checks related to key size.
This change does not alter the behavior of any cipher. All tests under [/tests/sys_crypto](https://github.com/RIOT-OS/RIOT/tree/master/tests/sys_crypto) should still pass.
#16183
> crypto/ciphers: remove unneeded max_key_size in cipher_interface_st

- sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp_eventloop.c
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c
- sys/net/gnrc/transport_layer/tcp/include/gnrc_tcp_fsm.h
This PR fixes a race condition within gnrc_tcp. The multiple threads within gnrc_tcp read the connections
state of the TCB processing FSM to base decisions on. This state variable is only changed within the FSM function
that is protected by a mutex. The current readout of the state is not protected.
This PR adds a function to get the current state of the FSM. Calling the function locks/unlocks the FSM and returns
the current state. This adds a dedicated synchronization point to resolve the issue.
This fix should not change the behavior of gnrc_tcp. To test the changes, run the gnrc_tcp test suite.
None. I came across this, implementing something else.
> gnrc_tcp: fix data race on fsm status

- bootloaders/riotboot_dfu/doc.txt
- makefiles/boot/riotboot.mk
This PR adds an automatic selection for DFU_ALT when invoking `make flash-slotX`. This way, we don't have to manually set it (as I forget it every single time). Update the documentation accordingly.
`PROGRAMMER_QUIET=0 PROGRAMMER=dfu-util USEMODULE="usbus_dfu"  make BOARD=saml21-xpro -C tests/buttons riotboot/flash-slot1` and checks DFU_ALT variable in your terminal log.
`PROGRAMMER_QUIET=0 PROGRAMMER=dfu-util USEMODULE="usbus_dfu"  make BOARD=saml21-xpro -C tests/buttons riotboot/flash-slot0` and checks again your DFU_ALT variable.
Everytime, the flash-slotX should match DFU_ALT=X.
None
> riotboot_dfu: select DFU_ALT automatically when invoking make flash-slotX

- cpu/stm32/periph/eth.c
In a `DEBUG()` statement in `cpu/stm32/periph_eth`: Use `PRIu32` instead of `lu` to make LLVM happy.
Not needed. `unsigned long` and `uint32_t` have the same size on STM32. This doesn't change anything.
Split out of https://github.com/RIOT-OS/RIOT/pull/15821
> cpu/stm32/periph_eth: fix format specifier in DEBUG()

- sys/include/ztimer.h
- sys/ztimer/auto_init.c
- sys/ztimer/core.c
the mode that is stored in required_pm_mode would not keep clock running
but one mode higher therefor the timer needs to block that mode, the logic does it this way.
The define keeps it's name for compatiblity but its use should fade, when #15715 is merged,
and should be deprecated in the release after that.
this PR is backward compatible to previous name waiting for it to be deprecated and removed.
build and test things that use pm_layerd and ztimer
the name was introduced with #13722  maybe  https://github.com/RIOT-OS/RIOT/pull/13722#discussion_r400694298_ creted the name != function mismatch
this is in conflict with an other PR I am writing on: #15715 i will happily rebase either when the other is merged
> sys/ztimer: rename required_pm_mode to block_pm_mode

- boards/atxmega-a1u-xpro/include/periph_conf.h
- cpu/atxmega/atxmega_cpu.c
- cpu/atxmega/include/cpu_pm.h
- cpu/atxmega/include/periph_cpu.h
- cpu/atxmega/periph/pm.c
- cpu/atxmega/periph/timer.c
- cpu/atxmega/periph/uart.c
The current xmega don't have a way to disable peripherals that are not in used.  Add peripheral management to allow enable only the mcu blocks that will be used by application.  This saves power on active and sleep modes.  By default, at clock initialization, all peripherals are now disabled and each drive must activate at initialization phase.
The periph_timer and periph_uart were updated with this new feature.
Tests were conducted with atxmega128-a1u-xpro board in:
- tests/periph_pm
- tests/periph_timer_short_relative_set
This is part of #15703.
CC: @maribu @benpicco
> cpu/atxmega: Add periph power management

- pkg/lwip/contrib/sock/tcp/lwip_sock_tcp.c
lwip receives network buffers that are made available to lwip_sock_tcp
calling `netconn_recv_tcp_pbuf`. The size of these buffers depends on
the size of the network packets. An application calling `sock_tcp_read`
can pass any arbitrary buffer size to read (copy) from these internal
network buffers, which may be smaller. lwip_sock_tcp keeps around the
last network buffer (`struct pbuf last_buf`) and the offset into this
buffer already consumed by the application (`last_offset`).
However, when multiple application reads from the same `pbuf` buffer
occur, the `last_offset` must be updated incrementing it. The code had
a bug that would work only when `last_offset` was either 0 (no previous
partial read) or when the current read was consuming all the remaining
data (when `buf_len == copylen`). …
> lwip_sock: Fix computation of last_offset on partial reads.

- boards/msbiot/include/board.h
When the driver for the mpu9150 has been renamed to mpu9x50, the
corresponding macro in the MSB-IoT board was forgotten to be renamed
as well. This fixes the issue.
With `master`:
```
> [auto_init_saul] error initializing mpu9x50 #0
main(): This is RIOT! (Version: 2021.04-devel-1223-g9eac73-sys/Makefile.dep)
```
This PR:
```
main(): This is RIOT! (Version: 2021.04-devel-1223-g9eac73-sys/Makefile.dep)
Welcome to RIOT!
> saul
ID	Class		Name
#0	ACT_SWITCH	red LED
#1	ACT_SWITCH	yellow LED
#2	ACT_SWITCH	green LED
#3	SENSE_BTN	left button
#4	SENSE_BTN	right button
#5	SENSE_ACCEL	mpu9x50
#6	SENSE_GYRO	mpu9x50
#7	SENSE_MAG	mpu9x50
> saul read 5
Reading from #5 (mpu9x50|SENSE_ACCEL)
Data:	[0]         203 mg
[1]         -12 mg
[2]         968 mg
> saul read 6
Reading from #6 (mpu9x50|SENSE_GYRO) …
```
> boards/msbiot: fix param for MPU9150

- drivers/cc110x/cc110x_netdev.c
- drivers/cc110x/include/cc110x_netdev.h
- drivers/cc110x/include/cc110x_params.h
- drivers/cc1xxx_common/gnrc_netif_cc1xxx.c
- drivers/include/cc110x.h
- drivers/include/cc1xxx_common.h
This PR  adds  a hook for the cc110x driver to facilitate address configuration, e.g. if your board has an EUI provider.
Add the function:
```C
#include "net/netdev.h"
bool  cc110x_eui_get(const netdev_t *netdev, void *eui)
{
(void)netdev;
*((uint8_t *)eui) = 0x11;
return true;
}
```
for example in `board.c` and check the address with `ifconfig`.
> drivers/cc110x: add hook cc1xxx_eui_get()

- examples/suit_update/README.md
In documentation use the release version of aiocoap instead of master, this should be done in Murdock as well, can you make the change @kaspar030? I could do it as well (but I rather go by you).
- pip3 install aiocoap==0.4.1
- make -C examples/suit_update flash test
```
> ifconfig
current-slot
Running from slot 0
> ifconfig
Iface  4  HWaddr: AA:04:26:28:64:38
L2-PDU:1500  MTU:1500  HL:64  RTR
inet6 addr: fe80::a804:26ff:fe28:6438  scope: link  VAL
pinging node...
PING fe80::a804:26ff:fe28:6438%riot0(fe80::a804:26ff:fe28:6438%riot0) 56 data bytes
--- fe80::a804:26ff:fe28:6438%riot0 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 40.626/40.626/40.626/0.000 ms
pinging node succeeded.
TEST PASSED …
```
> examples/suit_update: use aiocoap 0.4.1

- core/include/clist.h
- tests/unittests/tests-core/tests-core-clist.c
This adds proper API, docs, test case for determining whether a clist is empty.
The actual logic is a oneliner, so a good look and CI should be sufficient.
> core: add clist_is_empty()

- makefiles/boot/riotboot.mk
When riotboot depends on a package for building that the main
application also depends on (e.g., gecko_sdk for efm32), previously,
that package would be checked out twice in parallel, which fails.
This commit adds pkg-prepare as dependency to the bootloader target,
ensuring any packages are already up-to-date before calling the
bootloader submake.
<details>
<summary>example error output</summary>
```
make: Entering directory '/tmp/dwq.0.5577578061595997/ee195ef839279feec1409411fe57b39e/tests/riotboot'
rm -rf /tmp/dwq.0.5577578061595997/ee195ef839279feec1409411fe57b39e/build/pkg-build/gecko_sdk
Building application "tests_riotboot" for "sltb001a" with MCU "efm32".
compiling /tmp/dwq.0.5577578061595997/ee195ef839279feec1409411fe57b39e/dist/tools/riotboot_gen_hdr/bin/genhdr...
make: Nothing …
```
> make: make riotboot target depend on pkg-prepare

- .github/workflows/test-on-ryot.yml
This PR adds a github action workflow that launch `compile_and_test_for_board` on all boards currently connected to a [RYOT](https://github.com/fjmolinas/riot-ryot) machine.
For each board compile_and_test script starts. And the end result are archived.
For each board, jobs are run in parallel, I limited it at 7 for this particular configuration (since I have 7 cores), it takes quite some time to run all tests since about 30 boards are connected, the time to execute each test varies depending on the supported applications.
Since it takes a lot of time to complete, it's not ~possible~ acceptable to perform this check on PR basis, so the action is configured to be run on a weekly basis on master and for each RC tag pushed. I have a [similar …
> .github/workflows: add riot-ryot.yml

- examples/gnrc_border_router/Makefile
Boards with an ethernet interface already have this as their `netdev_default` so we don't have to enable anything here.
`same54-xpro` with ATREB215-XPRO:
USEMODULE=at86rf215 BOARD=same54-xpro UPLINK=ethernet make -C examples/gnrc_border_router flash
```
2021-03-21 17:49:24,354 # Iface  7  HWaddr: FC:C2:3D:0D:2D:1F 
2021-03-21 17:49:24,359 #           L2-PDU:1500  MTU:1492  HL:255  RTR  
2021-03-21 17:49:24,362 #           Source address length: 6
2021-03-21 17:49:24,364 #           Link type: wired
2021-03-21 17:49:24,370 #           inet6 addr: fe80::fec2:3dff:fe0d:2d1f  scope: link  VAL
2021-03-21 17:49:24,377 #           inet6 addr: 2001:16b8:4531:2300:fec2:3dff:fe0d:2d1f  scope: global  VAL
2021-03-21 17:49:24,380 #           inet6 group: ff02::2
2021-03-21 17:49:24,383 # …
```
> examples/gnrc_border_router: enable ethernet uplink

- drivers/sgp30/sgp30.c
There is an unused var if no assert.
```
DEVELHELP=0 make -C tests/driver_sgp30/
Building application "tests_driver_sgp30" for "samr21-xpro" with MCU "samd21".
"make" -C /home/francisco/workspace/RIOT/boards/samr21-xpro
"make" -C /home/francisco/workspace/RIOT/cpu/samd21
"make" -C /home/francisco/workspace/RIOT/cpu/cortexm_common
"make" -C /home/francisco/workspace/RIOT/cpu/cortexm_common/periph
"make" -C /home/francisco/workspace/RIOT/cpu/sam0_common
"make" -C /home/francisco/workspace/RIOT/cpu/sam0_common/periph
"make" -C /home/francisco/workspace/RIOT/cpu/samd21/periph
"make" -C /home/francisco/workspace/RIOT/cpu/samd21/vectors
"make" -C /home/francisco/workspace/RIOT/drivers/periph_common …
```
> drivers/sgp30: unused variable when DEVELHELP=0

- cpu/nrf5x_common/radio/nrfble/nrfble.c
This is a continuation of #15804 and enables the `nrfble` radio driver to request the external high frequency crystal as clock source only on demand, hence allowing for the CPU to save significant power. 
When combined with #15804 and #15805 this PR will reduce the average current drawn by the `examples/skald_ibeacon` application from ~400µA down to 13µA!!! Thus it makes the difference from running ~3 months to running >5 years on a 1000mAh battery :-)
Simply run `examples/skald_ibeacon` on any Nordic board and verify that the node is broadcasting
EDIT:
Best build without STDIO (`USEMODULE=stdio_null`), otherwise the UART will prevent the HFXO from being disabled...
EDIT
~~Depends on/rebased on  #15804~~
> cpu/nrf/radio/nrfble: request HFXO only on demand

- pkg/lwip/contrib/sock/tcp/lwip_sock_tcp.c
- tests/lwip/tests/01-run.py
`sock_tcp_read` reads (copies) from the internal lwip connection buffer to the data buffer passed by the app. If any data is available, the function would copy as much as possible to the app buffer but only from a single internal connection buffer. For example, if multiple small network packets are received but app passes a large enough buffer, `sock_tcp_read` would only copy at most one internal buffer to the output. This patch makes `sock_tcp_read` copy as much as possible from all the available buffers at the time of the call.
This also adds a test for this case and the recently fixed issue #16124.
`RIOT_CI_BUILD=1 make -C tests/lwip flash test`
This is related to issue #16124 which was fixed in #16278.
> lwip_sock: Make sock_tcp_read return more data if available and test it

- pkg/semtech-loramac/Makefile.dep
- pkg/semtech-loramac/Makefile.loramac_crypto
- pkg/semtech-loramac/patches/0004-switch-to-riot-aes.patch
This PR is a take over from https://github.com/RIOT-OS/RIOT/pull/10124:
> 
> Patch to adapt LoRaMAC 4.4.1 to RIOT AES implementation.
> 
> 1) Code size: RIOT AES significantly bigger without #10037, ~1KB bigger with #10037, about the same size as LoRaMAC AES with #10037 and aes_decrypt disabled (LoRaWAN doesn't need it)
> 
> 2) Performance: generally, RIOT AES is significantly (over 2 times) faster, especially on Cortex-M3 and above. On Cortex-M0, decryption is about the same speed, encryption is almost 2 times faster with RIOT AES.
> 
> Such difference is to be expected, as RIOT uses faster T-tables implementation while LoRaMAC uses S-boxes.
> 
> 3) Compatibility: LoRaMAC AES and RIOT AES can't be used simultaneously because of the same function names aes_encrypt() and aes_decrypt(). So, …
> [TAKEOVER]: pkg/semtech-loramac: switch to RIOT AES

- tests/periph_rtt_min/Makefile
- tests/periph_rtt_min/main.c
- tests/periph_rtt_min/tests/01-run.py
This fixes a test that regularly fails in the nightlies due to a timeout in catching its flashed dots:
- Better self-containment: read number of expected samples from output
rather than the environment
- Less reliance on `stdout` timing: Count samples in application and
output it rather then counting flushed dots.
```console
$ make -C tests/periph_rtt_min -j flash test
```
should still succeed
None
> tests/periph_rtt_min: harden test

- sys/Makefile.dep
- sys/include/sema.h
- sys/sema/sema.c
- tests/sema/Makefile
- tests/sema/main.c
On the winding road to get NimBLE running without including `xtimer` or `periph_timer` in the build, the `sema` and `event` modules are the last ones that pull in these dependencies currently. So I am desperately looking for way to free these modules of `xtimer` deps.
The code in this PR, still very prototypic, illustrates one possible solution to decouple the `sema` module from `xtimer` and at the same time adding `ztimer` support. However, this might not be the most elegant solution, so I am happy to hear any alternative ideas on this task!
Regarding what IMO should be possible:
- per default, build with an untouched API, so no existing code ever breaks
- allow to enable the `ztimer` API in parallel to the existing API -> allows for mixing legacy code with new ztimer code
- allow to …
> sys/sema: allow to use ztimer and/or xtimer

- pkg/nimble/netif/nimble_netif.c
In my initial implementation of `nimble_netif` I decided for using a local memory pool for buffering IP packets when transferring them from GNRC `pktbuf` to NimBLEs own (`mbuf`) memory pool. Now after more understanding and a lot of more experience using NimBLE, I come to the conclusion that it is far sufficient to use NimBLE global memory pool for this step as well. 
This saves quite a bit of otherwise over provisioned memory. Example - building `gnrc_networking` for `nrf52dk`:
without this PR:
```
text    data     bss     dec 
155788     288   46620  202696
```
with this PR:
```
text    data     bss     dec 
155796     288   38180  194264  
```
--> So for the default configuration (max connections := 3, mbuf-pool size := 35) **we save >8kb RAM!**
To further justify this change, the …
> pkg/nimble/netif: use global MSYS memory pool

- tests/malloc_thread_safety/Makefile
- tests/malloc_thread_safety/main.c
- fix false test failure on picolibc
- For picolibc, the result of mallinfo().uordblks doesn't go back
to zero after the first allocation. By adding `free(malloc(4))`
before recording the pre-test mallinfo() value, this issues is
worked arround
- increase test coverage to also cover realloc()
- ease testing with picolibc by allowing `make PICOLIBC=1 flash test`
Test application should still pass. After applzing
```diff
diff --git a/cpu/cortexm_common/Makefile.dep b/cpu/cortexm_common/Makefile.dep
index 856befb6c1..309d8c9a9a 100644
--- a/cpu/cortexm_common/Makefile.dep
+++ b/cpu/cortexm_common/Makefile.dep
@@ -25,4 +25,4 @@ ifeq (1, $(DEVELHELP))
endif
-USEMODULE += malloc_thread_safe
+#USEMODULE += malloc_thread_safe
```
the test should crash.
Came up in …
> tests/malloc_thread_safety: improve test

- drivers/ds3231/Makefile.dep
- drivers/ds3231/ds3231.c
- drivers/ds3231/include/ds3231_params.h
- drivers/include/ds3231.h
- makefiles/pseudomodules.inc.mk
- tests/driver_ds3231/Makefile
- tests/driver_ds3231/main.c
See also issue #16155. 
This PR adds support for alarms within the DS3231 drivers. 
I have corrected some alarm registers which were not used before and seemed to be incorrect. 
This is still a work in progress:
- As mentioned in issue #16155 it might be better to hide the alarm functions behind a pseudo module even though, as I mentioned earlier, I do not completely agree with this. You can absolutely use RTC alarms without any kind of callback. Sometimes the alarms are not even intended to the MCU. Meaning in those cases there is no need for a callback.
- I used typedefs for the alarm configuration, it seemed way easier/cleaner to me, but others might disagree/have a better idea. 
- The ITCN bit is for now set during the initialization of the RTC, therefore disabling the square wave …
> drivers/ds3231: add alarm support

- cpu/sam0_common/include/periph_cpu_common.h
- cpu/sam0_common/periph/rtc_rtt.c
- tests/periph_gpio/main.c
On SAM D5x/E5x only the 5 RTC tamper pins can wake the CPU from Deep Sleep.
Since this triggers a full reset, no callback can be executed. We have to read the `TAMPID` register to find out which event woke us from hibernation.
The new function was added to `tests/periph_gpio`
```
2021-03-11 22:28:03,257 # GPIO peripheral driver test
2021-03-11 22:28:03,257 # 
2021-03-11 22:28:03,262 # In this test, pins are specified by integer port and pin numbers.
2021-03-11 22:28:03,268 # So if your platform has a pin PA01, it will be port=0 and pin=1,
2021-03-11 22:28:03,271 # PC14 would be port=2 and pin=14 etc.
2021-03-11 22:28:03,271 # 
2021-03-11 22:28:03,276 # NOTE: make sure the values you use exist on your platform! The
2021-03-11 22:28:03,283 #       behavior for not existing ports/pins is not …
```
> cpu/sam0_common: add rtc_get_tamper_event() 

- tests/driver_dac_dds/main.c
The previous sine wave cast signed integers into the PCM range, causing
jumps at zero transitions. This shifts everything up by the respective
maximum signed integer, so that the signed idle zero becomes the
unsigned PCM signal's idle half-point and can continuously cover the
whole unsigned range.
(I could be completely wrong and this is all just an artifact of how I convert in the PWM-DAC of #15618 -- but I don't think so because if I flip the bit there, the do sound better but the PCM recording is garbled. Thus, I came to conclude that the intended buffer semantics are the PCM ones of 0=minimum, 255=maximum and 128=DC-free idle).
Acoustic test: the sound produced by sine should have fewer overtones; it is quieter over-all (as it only has energy in one frequency rather than jumping …
> tests/dac_dds: Fix sine wave to fit in PCM range

- boards/microbit-v2/doc.txt
- boards/microbit-v2/include/board.h
- boards/microbit-v2/include/gpio_params.h
The microbit v2's logo and rings are touch sensitive, with a resistive (vs. 1MOhm) and a capacitive mode.
This enables them by implementing the resistive mode (which is really trivial button reading, as long as you don't expect debouncing) and documents them.
Run the SAUL example, `saul read all` repeatedly, while touching any of the rings, button and GND with at least not completely dry fingers.
> boards/microbit-v2: Add buttons

- tests/unittests/tests-rtc/tests-rtc.c
`rtc_tm_normalize` does not use it, so `mktime` should not either.
This fixes https://github.com/RIOT-OS/RIOT/issues/16184. Something about the timezone configuration in the newest `ubuntu-latest` runners makes `mktime` confused, when using with DST timestamps. See https://github.com/RIOT-OS/RIOT/issues/16184#issuecomment-818719898.
I ran the test isolated and [it succeeded](https://github.com/miri64/RIOT/actions/runs/744752759). I also started a [full run in the main repo](https://github.com/RIOT-OS/RIOT/actions/runs/744849529) to check it still works in total.
Fixes https://github.com/RIOT-OS/RIOT/issues/16184
> tests/unittests/tests-rtc: do not use DST info for normalization

- core/include/sched.h
- core/thread.c
- tests/malloc_thread_safety/main.c
While developing #16126 i got the request to split out this Part of the PR.
- this adds sched_runq_advance(prio)
- used it in core/thread and 
- in the test malloc_thread_safety
this also enables (dumb and simple) schedulers like #14810 that need no information about the runqueue(s) they are working on
test
malloc_thread_safety
```
tests/malloc_thread_safety$ make flash; make test
```
> this tests its own modification
and
sched_testing
```
tests/sched_testing$ make flash; make test
```
> this test modifications made to thread_yield()
hopefully makes the review process of #16126 smoother
> core/sched: keep scheduler clist internal to sched

- drivers/ds18/include/ds18_params.h
I wondered why my DS18 parameters were not picked up. It turned out the DS18 driver was missing the include for "board.h".
> drivers/ds18: missing "board.h" include

- pkg/nimble/Makefile
- pkg/nimble/Makefile.dep
- pkg/nimble/scanlist/nimble_scanlist.c
- pkg/nimble/scanlist/nimble_scanlist_print.c
- sys/shell/commands/sc_nimble_netif.c
- tests/nimble_l2cap/main.c
With #15782 merged all prerequisites for migrating NimBLE from `xtimer` to `ztimer` are in. For a next step, I PRed the required NimBLE NPL changes to NimBLE (https://github.com/apache/mynewt-nimble/pull/967). These are needed in conjunction with the changes of this PR and finally allow for `xtimer`-free RIOT/NimBLE builds :-)
As stated in https://github.com/apache/mynewt-nimble/pull/967, appart from simplifying the NPL code in NImBLE, this change allows for significant energy savings. E.g. when running the `examples/nimble_gatt` application without STDIO (`USEMODULE+=stdio_null`) and the node is in connected state with a peer, the average current consumption drops from ~420µA to 72µA.
Verify that NimBLE is behaving as before. I suggest to run at least the following on any nrf52x board of …
> pkg/nimble: migrate to ztimer

- core/include/clist.h
- tests/unittests/tests-core/tests-core-clist.c
maybe #16126 is a little big #16292 added clist_is_empty() this ads the other two that #16126 needs
adds clist_exactly_one() and clist_more_than_one()
and a unittest that tests them
a good look
and 
```
RIOT/tests/unittests$ make tests-core; make term;
```
#16126 << needs to be rebased
#16292 << similar addition
> core/clist: add special cardinality tests and matching unittest

- pkg/nimble/Makefile
https://github.com/apache/mynewt-nimble/pull/967 was merged, so we can switch the upstream branch for the NimBLE package back to NimBLEs upstream master, as discussed in #16317.
Nothing should change by this PR, but verifying `gnrc_networking`, `nimble_gatt` and `tests/nimble_l2cap` would certainly not hurt.
redo the temporary upstream repo change introduced with #16317.
> pkg/nimble: switch back to upstream master

- sys/shell/commands/sc_nimble_netif.c
When merging #16317 one minor detail slipped through: the scan duration for `_cmd_connect_name()` was not adjusted and still applying us instead of ms -> leading to the shell seeming to be stuck when using the `ble connect SOMENAME` shell command.
This PR fixes this.
- run `examples/gnrc_networking` with `nimble_netif` on two nodes
- advertise some name with node A -> `ble adv FOOBAR`
- connect to that node from node B, using that name -> `ble connect FOOBAR`
without this PR, the shell only returns after a loong time, with this PR everything works as expected...
follow up on #16317
> shell/sc_nimble_netif: fix _connect_name scan dur

- pkg/nimble/contrib/nimble_riot.c
As discovered in  #16317 the `nimble_scanner` and other NimBLE applications are currently buggy in RIOT due to a issue with the late initialization/seed of the PRNG module in NimBLEs controller. A proper fix is already proposed to NimBLE upstream: https://github.com/apache/mynewt-nimble/pull/970. But until that fix is merged, I would like to merge this work-around into RIOT temporarily so we at least have the NimBLE port in a working state right away...
Run `examples/nimble_scanner` on some fitting board. Currently the board hard-faults every ~2nd time or so the `scan` shell command is triggered after the node is freshly rebootet. With this fix that should not happen anymore.
Work-around until https://github.com/apache/mynewt-nimble/pull/970 is merged and the NimBLE package is updated to …
> pkg/nimble: temporary fix to NimBLE PRNG seed issue

- sys/Makefile.dep
- sys/net/gnrc/network_layer/sixlowpan/ctx/gnrc_sixlowpan_ctx.c
- sys/shell/commands/sc_gnrc_6ctx.c
This PR makes `gnrc_sixlowpan_ctx` use `ztimer_msec` as time module whenever `ztimer_msec` is included in the build. This is one more step in running a `xtimer`-free network application :-)
Run `gnrc_networking` example build with `USEMODULE="ztimer_msec ztimer_periph_rtt" make ...` and verify, that nodes still communicate as expected...
none
> net/grnc/sixlowpan/ctx: use ztimer_msec if available

- tests/periph_rtt_min/main.c
- tests/periph_rtt_min/tests/01-run.py
The test still occasionally fails in the nightlies which points to a too short timeout.
We maybe should give Murdock a few spins with that to see if the error reoccurs there.
None
> tests/periph_rtt_min: adapt for slower RTTs

- boards/arduino-nano-33-iot/Kconfig
- boards/arduino-nano-33-iot/Makefile.features
- boards/arduino-nano-33-iot/include/periph_conf.h
Added missing configuration for ADC / PWM / SPI
Tested with:
tests/periph_adc
tests/periph_spi
tests/periph_pwm
Discussed in #16247 and #16267
Closes #16267
> Configuration extension for arduino-nano-33-iot

- .github/workflows/release-test.yml
Another follow-up on https://github.com/RIOT-OS/RIOT/pull/15637. `pytest` reads the token from the `HOME` directory, which with `sudo` is `root`, so there is none (since it is in the login user's `HOME`), so it can't comment in the tracking issue for `sudo` the tasks.
I started a run in https://github.com/miri64/RIOT/actions/runs/766574330. Murdock should comment from there.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/15637
> gh-actions: release-tests: properly configure GH token for sudo

- tests/pkg_tensorflow-lite/Makefile.ci
Explicitly list BOARD_INSUFFICIENT_MEMORY so
dist/tools/compile_and_test_for_board can filter out BOARDs.
> tests/pkg_tensorflow-lite/Makefile.ci: explicit list

- .github/workflows/release-test.yml
Another follow-up on https://github.com/RIOT-OS/RIOT/pull/15637. `pytest` reads the token from the `HOME` directory, which with `sudo` is `root`, so there is none (since it is in the login user's `HOME`), so it can't comment in the tracking issue for `sudo` the tasks.
I started a run in https://github.com/miri64/RIOT/actions/runs/766574330. Murdock should comment from there.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/15637
> gh-actions: release-tests: properly configure GH token for sudo [backport 2021.04]

- boards/common/slwstk6000b/include/periph_conf.h
- boards/e180-zg120b-tb/include/periph_conf.h
- boards/ikea-tradfri/include/periph_conf.h
- boards/slstk3400a/include/periph_conf.h
- boards/slstk3401a/include/periph_conf.h
- boards/slstk3402a/include/periph_conf.h
- boards/sltb001a/include/periph_conf.h
- boards/slwstk6220a/include/periph_conf.h
- boards/stk3200/include/periph_conf.h
- boards/stk3600/include/periph_conf.h
- boards/stk3700/include/periph_conf.h
- cpu/efm32/include/periph_cpu.h
- cpu/efm32/periph/rtt_series0.c
- cpu/efm32/periph/rtt_series1.c
make efm32 rtt frequency configurable by setting RTT_FREQUENCY
**I can not test that, I don't have such a BOARD**  see **Test results** :arrow_down:
```
tests/ztimer_xsec$ BOARD=<some efm32> USEMODULE=ztimer_periph_rtt CFLAGS=-DRTT_FREQEUNCY=32768 make flash test
```
expected to print SUCCESS and some time information 
(start Time; SEC ~1*10^^6 later; MSEC ~200*10^^3 later; USEC ~100*10^^3 later)
```
tests/periph_rtt$ BOARD=<some efm32> USEMODULE=ztimer_periph_rtt CFLAGS=-DRTT_FREQUENCY=32768 make flash term
```
expected to print Hello every 5 seconds 
RTT_FREQUENCY may be chosen from 2^^0 to 2^^15  other values should fail at precompile-time 
please test with 
```
1024 (2^^10)  
periph_rtt should print the line "Setting initial alarm to now + 5 s (5ddd) (d any decimal)"
4096 (2^^12) …
```
> cpu/efm32: add RTT_FREQUENCY support to efm32

- drivers/include/nrf24l01p_ng.h
- drivers/nrf24l01p_ng/gnrc_netif_nrf24l01p_ng.c
- drivers/nrf24l01p_ng/nrf24l01p_ng_netdev.c
This PR adds a hook for the nrf24l01p_ng driver to facilitate address configuration, e.g. if your board has an EUI provider.
For example add:
```C
#include "nrf24l01p_ng.h"
void nrf24l01p_ng_eui_get(const netdev_t *netdev, uint8_t *eui)
{
const uint8_t seed[] = {"abcde"};
memcpy(eui, seed, NRF24L01P_NG_ADDR_WIDTH);
eui[NRF24L01P_NG_ADDR_WIDTH - 1] = 0x11; /* EUI */
eui[NRF24L01P_NG_ADDR_WIDTH - 2] ^= netdev->index;
}
```
to your `board.c` and check the address with `ifconfig`
is related to #16286
> drivers/nrf24l01p_ng: add hook nrf24l01p_ng_eui_get()

- cpu/esp32/include/sdk_conf.h
- cpu/esp8266/include/cpu_conf.h
All other cpu define this variable so added without replacing the defines that come from upstream as stated in https://github.com/RIOT-OS/RIOT/pull/16341#issuecomment-821041343
- green murdock.
Split from #16341
> cpu/esp*: add CLOCK_CORECLOCK

- sys/shell/commands/sc_gnrc_rpl.c
When RPL was not started, don't show an empty state -- rather, show it was not started.
```
$ make BOARD=microbit-v2 -C examples/gnrc_networking all flash term
> rpl
RPL not initializied
> rpl init 6
> rpl
instance table: [ ]
parent table:   [ ]     [ ]     [ ]
```
or run with `USEMODULE+=gnrc_netif_single` and never see the new "RPL not initialized" unless there's something wrong with autoinit.
The more important (not so much testing, but general review) question is: Does this hide any possibly valuable output that could be there even when RPL was not started? My impression is that nothing touches the state before the thread gets started, and that the PID is never removed (even if the RPL thread happened to crash), but never having worked with the RPL implementation this is just gossip, …
> sys/shell/sc_gnrc_rpl: Err out early if RPL not even started

- sys/ztimer/core.c
- tests/unittests/tests-ztimer/tests-ztimer-mock.c
ztimer's machinery depends on figuring out if a timer is currently set
or not. It does that using _is_set(), which is also exposed as
ztimer_is_set().
Now when a timer expired and got taken of the timer queue using
_now_next(), the `next` pointer wasn't unset. This caused _is_set() to
wrongly return `true` for that timer.
Internally in ztimer, this didn't cause breakage, just an unnecessary
iteration of the timer queue by _delete_timer_from_list().
But this also broke the public ztimer_is_set().
This PR fixes the issue by correctly NULLing the timer's `next`
pointer when the timer triggers.
There's also an added regression test to ztimer's unittests.
The regression test now ensures correct behaviour. To see it fail, uncomment the new lines in sys/ztimer/core.c and run ztimer's unittests.
> ztimer: fix `ztimer_is_set()`

- sys/ztimer/core.c
- tests/unittests/tests-ztimer/tests-ztimer-mock.c
ztimer's machinery depends on figuring out if a timer is currently set
or not. It does that using _is_set(), which is also exposed as
ztimer_is_set().
Now when a timer expired and got taken of the timer queue using
_now_next(), the `next` pointer wasn't unset. This caused _is_set() to
wrongly return `true` for that timer.
Internally in ztimer, this didn't cause breakage, just an unnecessary
iteration of the timer queue by _delete_timer_from_list().
But this also broke the public ztimer_is_set().
This PR fixes the issue by correctly NULLing the timer's `next`
pointer when the timer triggers.
There's also an added regression test to ztimer's unittests.
The regression test now ensures correct behaviour. To see it fail, uncomment the new lines in sys/ztimer/core.c and run ztimer's unittests.
> ztimer: fix `ztimer_is_set()` [backport 2021.04]

- dist/tools/avarice/debug.sh
Redirect also stderr to /dev/null when trying to detect the correct binary name for GDB for AVR.
`make debug` for an AVR board should still work.
None
> dist/tools/avarice/debug.sh: less noise

- sys/xtimer/xtimer.c
This PR fixes a rare race-condition in `xtimer_msg_receive_timeout` which can lead to corruption of the timer list and subsequent hard faults.
The race condition is triggered when:
1) A message is sent to a thread using `msg_send`.
2) The `xtimer` which sents the timeout message expires and executes before `xtimer_remove(t)` is called. This will cause the message queue for the thread to contain first a real message and second the timeout message. The timer will not be queued anymore, but the timeout message will still be in the queue.
3) The `xtimer_msg_receive_timeout` function is called again. This will queue a new xtimer while the timeout message of the previous timer is still in the buffer. `_msg_wait` will see the old timeout message, think that the current xtimer has already expired …
> xtimer: Fix race condition in xtimer_msg_receive_timeout

- .github/workflows/release-test.yml
The release tests are marked as failing currenty since there is a bug in `pylint` (or one of its libraries). There is not much sense to run the linter for the release tests on the test scripts, as this is already done in the [CI of the release tests](https://github.com/RIOT-OS/Release-Specs/blob/master/.github/workflows/self-test.yml#L46). As such, we only need to run the test environment of `tox`, which executes the release tests.
I'll run the workflow in my fork, just to see if everything works (to shorten the runtime a REMOVE ME commit is included).
See https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823210031
> gh-actions: release-tests: do not run linters for release tests

- .github/workflows/release-test.yml
The release tests are marked as failing currenty since there is a bug in `pylint` (or one of its libraries). There is not much sense to run the linter for the release tests on the test scripts, as this is already done in the [CI of the release tests](https://github.com/RIOT-OS/Release-Specs/blob/master/.github/workflows/self-test.yml#L46). As such, we only need to run the test environment of `tox`, which executes the release tests.
I'll run the workflow in my fork, just to see if everything works (to shorten the runtime a REMOVE ME commit is included).
See https://github.com/RIOT-OS/Release-Specs/issues/213#issuecomment-823210031
> gh-actions: release-tests: do not run linters for release tests [backport 2021.04]

- release-notes.txt
Release notes mentioned QN808x instead of NQ908x.
> Fix typo in release notes. [backport 2021.01]

- sys/Makefile.dep
- sys/net/gnrc/Makefile.dep
- cleaned two low hanging fruits in `sys/Makefile.dep`
- split out all GNRC handling to `sys/net/gnrc/Makefile.dep`
Tests and applications using GNRC should still generate the same binaries.
> sys/Makefile.dep: Some cleanup

- cpu/sam0_common/sam0_eth/eth-netdev.c
Detect RX of frame also when other bits of RSR are set.
see https://github.com/RIOT-OS/RIOT/issues/16298#issuecomment-825743257
fixes #16298
> cpu/sam0_common: ethernet: fix RX detection

- tests/periph_flashpage_unittest/main.c
Reduce the fake memory size to avoid an overflow on `AVR_8`. Found while looking at release tests.
The test now passes on `arduino-uno`
```
r
READY
s
START
main(): This is RIOT! (Version: 2021.07-devel-5-g94329-pr_avr_flashpage_unittest)
..
OK (2 tests)
```
> tests/periph_flashpage_unittest: lower FLASHPAGE_SIZE for 8bit overflow

- makefiles/tools/programmer.inc.mk
While nice at first, this causes more issues than it's worth for a slightly more pretty output.
Hiding information from developers is not a good idea, especially when it comes to an often finicky programming step.
While in theory error output should be caught, there are enough cases where the programmer will get stuck in a loop or require user input that hiding programmer output by default is a bad idea.
alternative to #16370 and #16360
> tools/programmer: do not use programmer wrapper

- sys/xtimer/xtimer.c
This PR fixes a rare race-condition in `xtimer_msg_receive_timeout` which can lead to corruption of the timer list and subsequent hard faults.
The race condition is triggered when:
1) A message is sent to a thread using `msg_send`.
2) The `xtimer` which sents the timeout message expires and executes before `xtimer_remove(t)` is called. This will cause the message queue for the thread to contain first a real message and second the timeout message. The timer will not be queued anymore, but the timeout message will still be in the queue.
3) The `xtimer_msg_receive_timeout` function is called again. This will queue a new xtimer while the timeout message of the previous timer is still in the buffer. `_msg_wait` will see the old timeout message, think that the current xtimer has already expired …
> xtimer: Fix race condition in xtimer_msg_receive_timeout [backport 2021.04]

- tests/dbgpin/Makefile
The test fails because the default pin is connected to the jtag, with this PR it does not.
See `test-ryot` for a failed flash, with this pr:
```
READY
s
START
main(): This is RIOT! (Version: 2021.07-devel-1-gd10f9-pr_test_dbgpin_frdm-k64f)
Found 1 configured debug pin(s)
Testing pin 0
Test successful.
```
> tests/dbgpin: user port 1 for frdm-k64f

- tests/dbgpin/Makefile
The test fails because the default pin is connected to the jtag, with this PR it does not.
See `test-ryot` for a failed flash, with this pr:
```
READY
s
START
main(): This is RIOT! (Version: 2021.07-devel-1-gd10f9-pr_test_dbgpin_frdm-k64f)
Found 1 configured debug pin(s)
Testing pin 0
Test successful.
```
> tests/dbgpin: user port 1 for frdm-k64f [backport 2021.04]

- examples/nanocoap_server/coap_handler.c
This branch fixes buffer overflow bug in the nanocoap_server. In the file **coap_handler.c** in function **_riot_value_handler** there was **memcpy** call, which copy user data to the buffer without checking if provided data fits into the buffer. Provided code checks length of received data, and in a case when they are bigger than buffer, copying is denied. Moreover, function returns client error code 4.13 (**COAP_CODE_REQUEST_ENTITY_TOO_LARGE**) and sends response to the user "Max 15 chars".
Testing procedure requires connection beetwen RIOT OS for native BOARD and Linux machine. In the provided example, RIOT OS has configured only link-local addres (which is presented in the example console) and connected to the Linux using tap0 interface.  
Before fix, execution of command:  
``` …
```
> examples/nanocoap_server: fix a buffer overflow bug

- boards/atxmega-a1u-xpro/Kconfig
- boards/atxmega-a1u-xpro/include/periph_conf.h
- boards/atxmega-a3bu-xplained/Kconfig
- boards/atxmega-a3bu-xplained/include/periph_conf.h
- cpu/atxmega/Makefile.features
- cpu/atxmega/include/periph_cpu.h
- cpu/atxmega/periph/i2c.c
- tests/pkg_cryptoauthlib_internal-tests/Makefile.ci
Add ATxmega i2c master driver. The atxmega-a1u-xpro and atxmega-a3bu-xplained boards received default EXT-1/J1 header config.
The test was conducted using tests/periph_i2c using a at24mac device.
This is part of #15703
CC: @benpicco @maribu
> cpu/atxmega/periph: Add i2c driver

- drivers/nrf24l01p_ng/nrf24l01p_ng_netdev.c
The `NETOPT_ADDRESS` option of the `nrf24l01p_ng` driver modified the address of pipe 0 but the main listening
address was designed to be the address of pipe 1.
```
> ifconfig
[...]
2021-04-26 12:10:49,444 # Iface  8  HWaddr: 4D:49:6F:54:33  Channel: 4 
```
```
> ifconfig 8 set addr 01:02:03:04:05
```
```
> ifconfig
[...]
2021-04-26 12:15:04,901 # Iface  8  HWaddr: 01:02:03:04:05  Channel: 4
```
The printed address did not change in master.
> drivers/nrf24l01p_ng: bugfix netdev::set NETOPT_ADDRESS

- tests/periph_flashpage_unittest/main.c
Reduce the fake memory size to avoid an overflow on `AVR_8`. Found while looking at release tests.
The test now passes on `arduino-uno`
```
r
READY
s
START
main(): This is RIOT! (Version: 2021.07-devel-5-g94329-pr_avr_flashpage_unittest)
..
OK (2 tests)
```
> tests/periph_flashpage_unittest: lower FLASHPAGE_SIZE for 8bit overflow [backport 2021.04]

- makefiles/tools/programmer.inc.mk
While nice at first, this causes more issues than it's worth for a slightly more pretty output.
Hiding information from developers is not a good idea, especially when it comes to an often finicky programming step.
While in theory error output should be caught, there are enough cases where the programmer will get stuck in a loop or require user input that hiding programmer output by default is a bad idea.
alternative to #16370 and #16360
> tools/programmer: do not use programmer wrapper [backport 2021.04]

- examples/nanocoap_server/coap_handler.c
This branch fixes buffer overflow bug in the nanocoap_server. In the file **coap_handler.c** in function **_riot_value_handler** there was **memcpy** call, which copy user data to the buffer without checking if provided data fits into the buffer. Provided code checks length of received data, and in a case when they are bigger than buffer, copying is denied. Moreover, function returns client error code 4.13 (**COAP_CODE_REQUEST_ENTITY_TOO_LARGE**) and sends response to the user "Max 15 chars".
Testing procedure requires connection beetwen RIOT OS for native BOARD and Linux machine. In the provided example, RIOT OS has configured only link-local addres (which is presented in the example console) and connected to the Linux using tap0 interface.  
Before fix, execution of command:  
``` …
```
> examples/nanocoap_server: fix a buffer overflow bug [backport 2021.04]

- drivers/bmx280/Kconfig
- drivers/bmx280/Makefile.dep
- drivers/bmx280/bmx280.c
- tests/driver_bmx280/Makefile
- tests/driver_bmx280/app.config.test
For some reason the `bmx280` driver does require `xtimer`, although xtimer is never used in the driver code... So this PR removes the xtimer dependency from the driver.
Also, the test application for the driver is using `xtimer`, but not setting this dependency. This is also fixed in this PR.
Build test should be sufficient. Also a `git grep xtimer` on the driver code shows that there are not xtimer occurrences in the driver.
none
> driver/bmx280: remove unused xtimer dependency

- drivers/cc2420/Makefile.dep
- drivers/cc2420/cc2420.c
- drivers/include/cc2420.h
- drivers/include/net/netdev.h
- sys/net/gnrc/netif/init_devs/auto_init_cc2420.c
Register `cc2420` with netdev so we don't have to generate a EUI inside the driver but can make use of an EUI provider if available.
Run e.g. `examples/gnrc_networking` on `telosb` or `z1`.
> drivers/cc2420: register with netdev

- boards/nrf52840dongle/Kconfig
- boards/nrf52840dongle/Makefile.features
- boards/nrf52840dongle/include/periph_conf.h
This PR adds a small collection of fixes/enhancements for the default pin configuration of the `nrf52840dongle` board:
- fixes line length issue in PWM configuration
- fixes SPI pin configuration (see below)
- adds I2C pin conifuration and `periph_i2c` feature to the board.
Regarding the SPI pin configuration: currently the board uses the nrf52 default pin config of P0.15, P0.14, and P0.13 (-> `cfg_spi_default.h`). This is problematic for two reasons:
1. pins P0.13 and P0.15 are also used for `UART_DEV(0)`
2. pin P0.14 is not even accessible on the board (see pin mapping below)
Code review should be fine.
none
> board/nrf52840dongle: fix and enhance pin mapping for I2C and SPI

- drivers/nrf24l01p_ng/nrf24l01p_ng_netdev.c
The `NETOPT_ADDRESS` option of the `nrf24l01p_ng` driver modified the address of pipe 0 but the main listening
address was designed to be the address of pipe 1.
```
> ifconfig
[...]
2021-04-26 12:10:49,444 # Iface  8  HWaddr: 4D:49:6F:54:33  Channel: 4 
```
```
> ifconfig 8 set addr 01:02:03:04:05
```
```
> ifconfig
[...]
2021-04-26 12:15:04,901 # Iface  8  HWaddr: 01:02:03:04:05  Channel: 4
```
The printed address did not change in master.
> drivers/nrf24l01p_ng: bugfix netdev::set NETOPT_ADDRESS [backport 2021.04]

- pkg/nanopb/Makefile
Update to nanopb 0.4.5: [Changelog](https://github.com/nanopb/nanopb/blob/master/CHANGELOG.txt)
`tests/pkg_nanopb` still works.
> pkg/nanopb: bump version to 0.4.5 [backport 2021.04]

- examples/nanocoap_server/coap_handler.c
cosmetic
#16389 made the block unnecessary this removes it 
(improve readability, avoids wrong assumptions about switch cases)
read 
build and run nanocoap_server
#16389 #16394 Backport of that
> examples/nanocoap_server: remove unneed case block

- cpu/cortexm_common/cortexm_init.c
- cpu/cortexm_common/vectors_cortexm.c
When building a Cortex-M application and optimisation level `-O3` or `-Ofast`, a hard fault occurs at start up.
The reason that this happens is because the reset handler will copy data stored in flash to their respective locations in RAM.
In order to speed this up, GCC makes use of 64-bit floating point registers and the `vldmia` and `vstmia` instructions.
However, the FPU has not yet been initialised at this point. This causes these instructions to throw hard faults when used.
When building with `-O2` or lower it will use 32 bit data accesses instead.
The body of the following `for`-loop from the `reset_handler_default` function in `vectors_cortmex.c`:
```c
/* load data section from flash to ram */
for (dst = &_srelocate; dst < &_erelocate; ) {
(dst++) = *(src++);
}
```
Compiles to …
> Fix Cortex-M hard faults when building with -O3 or -Ofast

- cpu/lpc23xx/Kconfig
- cpu/lpc23xx/Makefile.features
- cpu/lpc23xx/include/cpu_conf.h
- cpu/lpc23xx/periph/flashpage.c
- drivers/periph_common/flashpage.c
- tests/periph_flashpage/main.c
This converts the old flashrom driver to the new flashpage API.
I've had this lying around for a while and now all dependencies are merged, but unfortunately I can't test it.
Not sure if this works yet, but better PR it, maybe it's useful for someone. 
`tests/periph_flashpage` should now work on lpc23xx boards (untested)
follow-up to #16280
#15936 could come in handy here.
> cpu/lpc23xx: implement periph/flashpage

- cpu/stm32/periph/spi.c
As mentioned in #16308, there an inversion in parameter placement in the DMA function parameters. I don't have any BOARD to test sadly, maybe @bergzand can?
- some application that uses spi + dma: `FEATURES_REQUIRED=periph_dma BOARD=nucleo-l476rg make -C tests/periph_spi`
Ticks one point in #16308
> cpu/stm32/periph/spi: fix wrong parameter order 

- boards/common/esp8266/include/periph_conf_common.h
- cpu/esp8266/include/periph_cpu.h
- cpu/esp8266/periph/gpio.c
- cpu/esp_common/periph/uart.c
The esp8266 CPU has actually two hardware UART peripherals. UART0 is
used by the boot ROM for flashing and serial output during boot,
typically at a baudrate of 74880 bps until the bootloader or application
sets the more standard 115200 baudrate. This UART0 device has two
possible pins for TXD, GPIO1 and GPIO2, which are both set to TXD by the
boot ROM. esp8266 modules will typically have GPIO1 labeled as the TX
pin, but it is possible to use GPIO2 for that purpose even while
flashing the device with esptool.py.
The second device, UART1, also has two options for TXD, GPIO2 and GPIO7,
and only one option for RXD, GPIO8. However, GPIO7 and GPIO8 are used
by the flash internally so those options are not very useful unless
maybe while running from IRAM with the flash disabled, for example for …
> esp8266: Support UART1 and other UART0 pins.

- drivers/at86rf2xx/at86rf2xx.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
- drivers/include/net/netdev/ieee802154.h
- drivers/netdev/ieee802154.c
- sys/include/net/ieee802154_security.h
- sys/net/gnrc/netif/ieee802154/gnrc_netif_ieee802154.c
- sys/net/link_layer/ieee802154/security.c
While working on replay protection I found 3 things that I want to fix. 
This PR does three things:
1. Remove `NETOPT_ENCRYPTION_KEY` from the `at86rf2xx` driver.
It was redundant because the IEEE 802.15.4 `netdev` driver also sets the key and
the IEEE 802.15.4 security implementation transfers the key to the hardware if required. 
2.  Fix a small copy paste bug.
Luckily the code segment was not executed because we only use the implicit key mode so far.
3. Stricter prefixing of types and constants with `ieee802154_sec_`
No change of functionality.
works as before
```
2021-02-28 10:23:12,699 # ifconfig 6 set key 00112233445566778899aabbccddeeff
2021-02-28 10:23:12,699 # 
2021-02-28 10:23:12,705 # Notice: setting 128 bit key.success: set encryption key on interface 6 to 
2021-02-28 …
```
> net/ieee802154_security: small bugfix and stricter names

- cpu/stm32/dist/kconfig/Kconfig.lines.j2
- cpu/stm32/dist/kconfig/Kconfig.models.j2
- cpu/stm32/dist/kconfig/gen_kconfig.py
- cpu/stm32/dist/kconfig/requirements.txt
When the kconfig generator for STM32 script was written the [xlrd package](https://pypi.org/project/xlrd/) was still able to read xls**x** files and this is no longer the case starting from version 2.0 (end of 2020).
This PR is replacing the xlrd package with [openpyxl](https://pypi.org/project/openpyxl/) which seems to be the preferred solution.
There's also an small improvement regarding dynamic copyright date (otherwise, newly generated files still have 2020) with the kconfig template.
The script still works. Tested with G0, only the year is changed but not the rest of the content:
```
$ rm -f cpu/stm32/kconfig/g0/{Kconfig.lines,Kconfig.models}
$ ./cpu/stm32/dist/kconfig/gen_kconfig.py g0 --sheets ~/Downloads/G0ProductsList.xlsx
$ git diff
diff --git …
```
> cpu/stm32/dist: fix and improve genkconfig script

- dist/tools/dhcpv6-pd_ia/pkg/__init__.py
When running `Mint` LInux, the `dhcpv6-pd_ia` tool fails to trigger the kea installation process, as it does not recognize Mint as Debian/Ubuntu family member. This PR fixes this by adding "Linux Mint" to the list of known OSes.
For reference:
```
hauke@schelm:~$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="20.1 (Ulyssa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.1"
VERSION_ID="20.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyssa
UBUNTU_CODENAME=focal
```
where `NAME` is the field we are comparing with
Optimal: do a fresh install of `Linux Mint` and run the `gnrc_border_router` in DHCP6 …
> tools/dhcpv6-pd_ia: add Linux Mint to installer

- cpu/sam0_common/periph/rtc_rtt.c
This allows to use the sam0 RTT together with the rtt_rtc module.
The idea is to use RTT as a monotonic counter, but still keep track of the time with the virtual RTC module.
Only re-orders / guards code.
Compile testing should be enough. 
split off #15763
> cpu/sam0_common: only include RTC/RTT symbols if module is used

- tests/malloc/main.c
- tests/malloc/tests/01-run.py
Matching on every free leads to flimsy test results where all memory
is freed but one line fails to be matched by pexpect, instead, match
the final count.
- `test/malloc` still passes:
```
Free 128 Bytes at 0x0x20001c90, total 2048
Free 128 Bytes at 0x0x20001bf8, total 1912
Free 128 Bytes at 0x0x20001b60, total 1776
Free 128 Bytes at 0x0x20001ac8, total 1640
Free 128 Bytes at 0x0x20001a30, total 1504
Free 128 Bytes at 0x0x20001998, total 1368
Free 128 Bytes at 0x0x20001900, total 1232
Free 128 Bytes at 0x0x20001868, total 1096
Free 128 Bytes at 0x0x200017d0, total 960
Free 128 Bytes at 0x0x20001738, total 824
Free 128 Bytes at 0x0x200016a0, total 688
Free 128 Bytes at 0x0x20001608, total 552
Free 128 Bytes at 0x0x20001570, total 416
Free 128 Bytes at 0x0x200014d8, total 280
Free 128 Bytes …
```
> tests/malloc: refactor test

- boards/nucleo-f303k8/Kconfig
- boards/nucleo-f303k8/Makefile.features
- tests/pkg_tensorflow-lite/Makefile.ci
- tests/pthread_cooperation/Makefile
Some tests in https://github.com/RIOT-OS/RIOT/runs/2480009583?check_suite_focus=true are failing do to some setup issues:
- `tests/pkg_tensorflowlite` should not be ran on `nucleo-g071rb`
- stack size should be reduced for `nucleo-f334r8` on `tests/pthread_cooperation/`
- `periph_rtc` should not be provided for  `nucleo-f303k8`
- `BOARD=nucleo-f334r8 make -C tests/pthread_cooperation/ flash test`
```
main(): This is RIOT! (Version: 2021.07-devel-95-gd8287-pr_small_test_fixes)
START
Creating thread with arg 1
Creating thread with arg 2
Creating thread with arg 3
Creating thread with arg 4
Creating thread with arg 5
Creating thread with arg 6
Creating thread with arg 7
Creating thread with arg 8
Creating thread with arg 9
Creating thread with arg 10
Creating thread with arg 11
Creating …
```
> tests: small fixes

- sys/congure/mock/congure_mock.c
- sys/include/congure/mock.h
- tests/congure_test/congure_impl.c
This extends the `congure_mock` so that actual `congure` method drivers can be added, in case the test needs some actual functionality.
No tests are provided for the new functionality (it will be used in a later PR). `tests/congure_test` should still compile and pass.
```console
$ BOARD=iotlab-m3 make -C tests/congure_test/ --no-print-directory -j flash test
Building application "tests_congure_test" for "iotlab-m3" with MCU "stm32".
[…]
18300	    132	   2536	  20968	   51e8	/home/mlenders/Repositories/RIOT-OS/RIOT/tests/congure_test/bin/iotlab-m3/tests_congure_test.elf
For full programmer output add PROGRAMMER_QUIET=0 or QUIET=0 to the make command line.
✓ Flashing done! (programmer: 'openocd' - duration: 2.01s) …
```
> congure_mock: add capability to provide actual methods

- .github/workflows/release-test.yml
This way, the tests that shall be run can be determined using [`pytest -k` expressions][k]. E.g. `spec04 and task04` would only run task 4.4.
[k]: https://docs.pytest.org/en/stable/usage.html#specifying-tests-selecting-tests
See https://github.com/miri64/RIOT/actions/runs/807124859 for a run with the filter and https://github.com/miri64/RIOT/actions/runs/807138408 for a run without.
Unrelated, but had this idea for testing https://github.com/RIOT-OS/RIOT/pull/16430.
> gh-actions: release-tests: add filter input

- makefiles/info-global.inc.mk
Since we are using `eval` for `board_unsatisfied_features` we are currently using the previous iteration of `DEFAULT_MODULE` for the next one, which leads to the bug exposed in https://github.com/RIOT-OS/RIOT/pull/16397 , this PR fixes it.
Rebase on #16397 and see that `make -C examples/hello-world/ info-boards-supported  | grep arduino-uno` is not empty.
Also print every iteration `DEFAULT_MODULE` and the `BOARD` name and you would see it's off by one.
> makefiles/info-global.inc.mk: fix DEFAULT_MODULE inclusion

- .github/workflows/tools-test.yml
- dist/pythonlibs/riotctrl_ctrl/native.py
- dist/pythonlibs/riotctrl_ctrl/requirements.txt
- dist/pythonlibs/riotctrl_ctrl/tests/test_native.py
- dist/pythonlibs/riotctrl_ctrl/tox.ini
This provides two helper classes for tests with `riotctrl`:
1. A `NativeRIOTCtrl` for native specifically, so the nodes can be resetable with the workflow provided in https://github.com/RIOT-OS/RIOT/pull/12517.
2. ~~A factory class `RIOTCtrlFactory` that allows for automatic generation of a RIOTCtrl object. In a first step, the `NativeRIOTCtrl` is selected, when `BOARD` is set to `native` in the environment variables (or a provided `env` dictionary)~~ ([migrated to `riotctrl`](https://github.com/RIOT-OS/riotctrl/pull/18))
Tests are provided and hooked into the `test-tools` Github Action. For manual testing call
```
cd dist/pythonlibs/riotctrl_ctrl
tox
```
None
> riotctrl_ctrl: A reset helper class for `native`

- cpu/arm7_common/Makefile.dep
- cpu/cortexm_common/Makefile.dep
- cpu/esp32/Makefile.dep
- cpu/fe310/Makefile.dep
- cpu/msp430_common/Makefile.dep
This allows to disable nanospecs with
DISABLE_MODULE += newlib_nano
if a full-features version of newlib is desired.
```
43144	    144	  18040	  61328	   ef90	/home/benpicco/dev/RIOT/examples/default/bin/same54-xpro/default.elf
```
```
70748	   2520	  18084	  91352	  164d8	/home/benpicco/dev/RIOT/examples/default/bin/same54-xpro/default.elf
```
> cpu: make newlib_nano a DEFAULT_MODULE

- Makefile.include
- makefiles/color.inc.mk
- makefiles/utils/ansi.mk
- makefiles/utils/ansi_special.mk
This PR split out the color functions from #12156 without attempting to replace all usage but allowing to use built-ini make functions instead of shell calls.
```
diff --git a/Makefile.include b/Makefile.include
index 5ddce7f8dd..1c50e6881d 100644
--- a/Makefile.include
+++ b/Makefile.include
@@ -583,7 +583,8 @@ flashfile: $(FLASHFILE)
ifeq (,$(FLASHFILE))
$(error FLASHFILE is not defined for this board: $(FLASHFILE))
endif
-
+$(info $(call c_green,Color function test))
+$(info no color)
ifeq ($(RIOT_CI_BUILD),1)
```
Compile any application.
Split out from #12156
> TAKEOVER: makefiles/color: Add color functions, new attempt. #12156

- sys/include/net/gnrc/tx_sync.h
I'd like to add an explicit cast to the module `gnrc/tx-sync` for it to build with default setting on C++ compilers.
cc @maribu
> gnrc tx-sync: add cast for c++ compatibility

- dist/pythonlibs/riotctrl_shell/loramac.py
- dist/pythonlibs/riotctrl_shell/tests/test_loramac.py
This PR adds a loramac shell, to be used in the Release tests.
- green ci
- used in https://github.com/RIOT-OS/Release-Specs/pull/218
> dist/pythonlibs/riotctrl_shell: add loramac shell [backport 2021.04]

- cpu/esp_common/syscalls.c
- pkg/tlsf/contrib/newlib.c
The documentation of `void *calloc(size_t nmemb, size_t size)` says it should detect overflows in `nmemb * size`, but the two implementation failed to comply. This fixes the issues.
[Some people might consider this a security fix](https://msrc-blog.microsoft.com/2021/04/29/badalloc-memory-allocation-vulnerabilities-could-affect-wide-range-of-iot-and-ot-devices-in-industrial-medical-and-enterprise-networks/). (But honestly, there are few legitimate use cases of dynamic memory management on MCUs in general. And using unchecked user input (including data received via network) to compute allocation sizes is something that will still allow resource exhaustion attacks even after the fix. So an application previously vulnerable is still vulnerable, only with one attack vector fewer.)
The …
> pkg/tlsf,cpu/esp_common: fix possible overflow in calloc implementations

- cpu/atmega_common/periph/rtc.c
`tests/periph_rtc` is now setting an alarm to a full minute (second 0).
This brought a off-by-one error in the RTC driver to light, here the minute counter is only incremented if the second reaches 60.
However, the second in `struct tm` goes from 0 - 59, the normalization is triggered a second too late, yielding second 1.
So the 0 second is never reached and the alarm on that second is never triggered.
Besides that small fix, there is also a small optimization where we can get rid of a global variable by comparing the counter register directly to tell if an overflow occurred. 
`tests/periph_rtc` should work again
```
2021-05-04 17:55:01,812 # RIOT RTC low-level driver test
2021-05-04 17:55:01,816 # This test will display 'Alarm!' every 2 seconds for 4 times
2021-05-04 17:55:01,821 # …
```
> cpu/atmega_common: RTC: fix off-by-one second normalization & simplify rtc_get_time()

- doc/doxygen/src/mainpage.md
- doc/memos/rdm0001.md
With the new website some links in our documentation are not working anymore. This updates them.
- Build the docs and check the link
- Open RDM1 and check the reference link
https://github.com/RIOT-OS/riot-os.org/pull/82
> doc: fix URLs to the new website

- cpu/esp_common/syscalls.c
- pkg/tlsf/contrib/newlib.c
The documentation of `void *calloc(size_t nmemb, size_t size)` says it should detect overflows in `nmemb * size`, but the two implementation failed to comply. This fixes the issues.
[Some people might consider this a security fix](https://msrc-blog.microsoft.com/2021/04/29/badalloc-memory-allocation-vulnerabilities-could-affect-wide-range-of-iot-and-ot-devices-in-industrial-medical-and-enterprise-networks/). (But honestly, there are few legitimate use cases of dynamic memory management on MCUs in general. And using unchecked user input (including data received via network) to compute allocation sizes is something that will still allow resource exhaustion attacks even after the fix. So an application previously vulnerable is still vulnerable, only with one attack vector fewer.)
The …
> pkg/tlsf,cpu/esp_common: fix possible overflow in calloc implementations [backport 2021.04]

- cpu/riscv_common/irq_arch.c
The handle_trap function is used internally by the trap_entry implementation from the same file. However, the trap_entry implementation calls handle_trap from inline assembly. This makes it difficult for the compiler to infer that the handle_trap function is used at all. This causes issues when LTO is enabled.
Without this patch compiling any RISC-V RIOT code with `LTO=1` causes the following linker error:
RIOT/cpu/riscv_common/irq_arch.c:134: undefined reference to `handle_trap'
/tmp/hello-world.elf.Nngidp.ltrans0.ltrans.o:cpu/riscv_common/irq_arch.c:134:(.text.trap_entry+0x34):relocation truncated to fit: R_RISCV_GPREL_I against undefined symbol `handle_trap'
This commit fixes LTO support for RISC-V.
Try compiling `examples/hello-world` with and without this patch as follows:
```
$ …
```
> riscv_common: mark handle_trap as used (fixes LTO on RISC-V)

- cpu/atmega_common/Kconfig
- cpu/atmega_common/Makefile.features
- cpu/atmega_common/periph/rtc.c
- cpu/lpc23xx/Kconfig
- cpu/lpc23xx/Makefile.features
- cpu/lpc23xx/periph/rtc.c
- drivers/include/periph/rtc.h
- drivers/rtt_rtc/Makefile.features
- drivers/rtt_rtc/rtt_rtc.c
- kconfigs/Kconfig.features
- tests/periph_rtc/Makefile
- tests/periph_rtc/main.c
RTC on RTT usually runs at a frequency greater than 1 Hz, so sub-second precision is available.
Add a function to get the current RTC timestamp together with it's sub-second component.
To run `tests/periph_rtc` with `rtt_rtc` instead of the hardware RTC, do
```patch
--- a/tests/periph_rtc/Makefile
+++ b/tests/periph_rtc/Makefile
@@ -1,6 +1,7 @@
include ../Makefile.tests_common
-FEATURES_REQUIRED += periph_rtc
+USEMODULE += rtt_rtc
+# FEATURES_REQUIRED += periph_rtc
FEATURES_OPTIONAL += periph_rtc_ms
DISABLE_MODULE += periph_init_rtc
```
```
2021-04-19 14:32:06,802 # RIOT RTC low-level driver test
2021-04-19 14:32:06,808 # This test will display 'Alarm!' every 2 seconds for 4 times
2021-04-19 14:32:06,811 #   Setting clock to   2020-02-28 23:59:57
2021-04-19 14:32:06,815 # Clock value is …
```
> drivers/rtt_rtc: implement rtc_get_time_ms()

- drivers/ccs811/include/ccs811_params.h
Using the ccs811_full module, with default configuration, results in a compilation error:
RIOT/drivers/ccs811/include/ccs811_params.h:84:1: error: missing initializer for member 'ccs811_params_t::int_pin' [-Werror=missing-field-initializers]
This commit fixes this bug.
> drivers/ccs811: fix default config for ccs811_full

- boards/arduino-nano-33-iot/include/periph_conf.h
The configuration for I2C and SPI use the same serial communication interface (SERCOM4). This makes it impossible to use them at the same time. This commit switches the configuration of one of the SPIs from SERCOM4 to SERCOM2 
The modified SPI configuration is responsible for communicating with the NINA W102 device. I tested that after making the changes, interaction with this device works as before (custom driver, missing in RIOT)
> boards/arduino-nano-33-iot: resolved SPI and I2C configuration conflict

- boards/bastwan/include/periph_conf.h
- boards/saml21-xpro/include/periph_conf.h
- boards/samr30-xpro/include/periph_conf.h
- boards/samr34-xpro/include/periph_conf.h
- boards/yarm/include/periph_conf.h
- cpu/saml21/cpu.c
- cpu/saml21/include/periph_cpu.h
My recently merged PR #16433 introduces a bug: when OSC16M is not running at 16MHz, the timer clock SAM0_GCLK_8MHZ is no longer correct.
I've renamed SAM0_GCLK_8MHZ as SAM0_GCLK_TIMER, and compute it as 4MHz or 8MHz depending on the frequency of the core clock - CLOCK_CORECLOCK at 4MHz or at 12MHz result in SAM0_GCLK_TIMER at 4MHz, all other available core clocks still produce the original 8MHz one.
> CPU SAML21: fix timers frequency when using slow clocks

- cpu/native/include/cpu_conf.h
This PR is a simple improvement of the thread size defines for the native CPU. The idea is to allow the user (at build time via CFLAGS for example) to specify custom values.
This PR also fixes an issue on Mac OSX where one value is defined twice (so it doesn't build but native is not supported anymore on Mac).
- A green Murdock should be enough
Required to set a default stack size greater than the 8192 default value for the memory needs of an application.
> cpu/native: make thread stacksize defines overridable

- pkg/libcose/Makefile
- pkg/libcose/Makefile.dep
- pkg/libcose/Makefile.include
- pkg/libcose/patches/0001-RIOT-Use-RIOT-random_bytes-function-instead-of-rando.patch
- pkg/tinycrypt/Makefile
- pkg/tinycrypt/Makefile.tinycrypt
The latest libcose master adds support for AES-CCM through the added tinycrypt backend.
A tinycrypt opportunistic POSIX RNG dependency is patched out to allow the interaction -- as described in the commit, that would only have worked on native anyway, and it's better to consistently not pull in that function than give people surprise behavior when going away from native. (Also, the native function would have conflicted with the more generic implementation provided by libcose, which needs a RNG linked in there for key generation).
* `make -C tests/pkg_libcose all flash test`
* Same but with
```patch
diff --git a/tests/pkg_libcose/Makefile b/tests/pkg_libcose/Makefile
index 8206fe43b0..105b5a9aac 100644
--- a/tests/pkg_libcose/Makefile
+++ b/tests/pkg_libcose/Makefile
@@ -5,8 +5,9 @@ …
```
> pkg/libcose: Update to latest master

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- Makefile
- README.md
- doc/doxygen/src/mainpage.md
The users@ list doesn't exist anymore (is in autoreply mode to notify users). The devel@ address points to the forum category and should not be advertised as mailing list.
Read the changes maybe :sweat_smile: 
See [here](https://forum.riot-os.org/t/start-a-topic-via-email-which-email-addresses/3082/6)
> Documentation: Remove mentions of the users@ and devel@ mailing lists.

- drivers/at86rf215/Makefile.dep
- drivers/at86rf215/at86rf215.c
- drivers/at86rf215/at86rf215_netdev.c
- drivers/include/net/netdev/ieee802154.h
- makefiles/pseudomodules.inc.mk
- sys/net/gnrc/netif/ieee802154/gnrc_netif_ieee802154.c
- tests/driver_at86rf215/Makefile
This PR adds support for recording RX timestamps on at86rf215. It also extends `netdev_ieee802154_rx_info_t` to allow recording timestamps.
The captured timestamps are actually counter values but are converted to ns (given a clock rate of 32MHz). The timestamps can be useful for time synchronization to compensate delays.
`tests/sock_udp_aux` can be used to show the reception timestamps.
> drivers/at86rf215: add RX timestamps

- cpu/esp32/vendor/esp-idf/heap/heap_trace.c
- cpu/esp_common/Makefile.include
- cpu/esp_common/syscalls.c
- sys/malloc_thread_safe/malloc_wrappers.c
- tests/malloc/main.c
The already in place wrapper for calloc (that is used to ensure thread-safety for concurrent calls to *alloc() and free) has been re-written on top of malloc to manually include an check for a potential overflow in the multiplication. Likely, this will be a bit more efficient in terms of ROM, so it won't hurt to be done this way even if the underlying calloc implementation would be correct.
In addition, the test in `tests/malloc` was extended to ensure correct behavior.
Some might consider this a security fix.
The extended test in `tests/malloc` should fail with older newlibs (before 4.0.0 release) when build against `master`, but work in this PR.
Partially split out of https://github.com/RIOT-OS/RIOT/pull/16438
> sys/malloc_thread_safety: fix potential overflow in multiplication

- examples/gcoap/Makefile
To simulate gcoap on a 802.15.4 node we can use the `socket_zep` network interface for `native`.
This adds a convenient make variable to enable this with a single command line option.
- create tap interface
- start ZEP border router
make -C examples/gnrc_border_router BOARD=native all term
- run gcoap example with a simulated 802.15.4 interface with custom MAC address
make -C examples/gcoap BOARD=native USE_ZEP=1 ZEP_MAC=\"E6:CB:21:BF:9B:F8:72:62\" all term
```
main(): This is RIOT! (Version: 2021.07-devel-225-gc21097)
gcoap example app
> ifconfig
ifconfig
Iface  7  HWaddr: 72:62  Channel: 26  NID: 0x23 
Long HWaddr: E6:CB:21:BF:9B:F8:72:62 
L2-PDU:102  MTU:1280  HL:64  6LO  
IPHC  
Link type: …
```
> examples/gcoap: add support for socket ZEP

- boards/atxmega-a1u-xpro/Kconfig
- boards/atxmega-a1u-xpro/include/board.h
- boards/atxmega-a1u-xpro/include/periph_conf.h
- boards/atxmega-a3bu-xplained/Kconfig
- boards/atxmega-a3bu-xplained/include/periph_conf.h
- cpu/atxmega/Makefile.features
- cpu/atxmega/include/periph_cpu.h
- cpu/atxmega/periph/spi.c
- examples/gnrc_lorawan/Makefile.ci
- tests/disp_dev/Makefile.ci
- tests/driver_at86rf215/Makefile.ci
- tests/driver_atwinc15x0/Makefile
- tests/driver_cc110x/Makefile.ci
- tests/driver_enc28j60/Makefile.ci
- tests/driver_encx24j600/Makefile.ci
- tests/driver_kw2xrf/Makefile.ci
- tests/driver_mrf24j40/Makefile.ci
- tests/driver_nrf24l01p_ng/Makefile.ci
- tests/driver_w5100/Makefile.ci
Add ATxmega spi driver. ~The atxmega-a1u-xpro board received the RZ-600 at86rf231 adapter config.~
Add atxmega-a1u-xpro EXT-1 config.
Add atxmega-a3bu-xplained J1 config.
The test was conducted using ~Tutorials/task-06 application.~ tests/periph_spi.
This is part of #15703 ~and depends on #16288~.
CC: @benpicco @maribu
> cpu/atxmega/periph: Add spi driver

- README.md
- doc/doxygen/riot.doxyfile
- doc/doxygen/src/release-cycle.md
This offers an alternative to https://github.com/RIOT-OS/RIOT/pull/16087 for the documentation of our release cycle. The README is amended with a short section how to download RIOT and the doxygen documentation receives a page about our release cycle in detail
Read, doxygen should build properly and all the links should work (except the `[release cycle]` link; for that `https://doc.riot-os.org` needs to be updated with this PR first).
Alternative to https://github.com/RIOT-OS/RIOT/pull/16087.
> doc: README: Add documentation on downloads and release cycle

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR adds a new github action to automatically assign `Area: *` labels to newly opened PRs. This is based on the [labeler action](https://github.com/actions/labeler).
Some rules are predefined for setting the most common `Area: *` labels but we can probably finely tune them, later.
There are 3 `REMOVEME` commits that should automatically add `Area: boards`, `Area: cpu` and `Area: build system` labels.
Useful with https://github.com/RIOT-OS/RIOT-release-manager/pull/20 which relies on those labels being set to automatically and correctly generate the release notes.
> .github: add automatic PR labeler action

- cpu/stm32/periph/gpio_f1.c
This is a follow-up for #16272 for the STM32F1 family. The same description applies. I was able to reproduce the described problem with a STM32F103RC. Compared to #16272 it's pretty hard to trigger that race. It took me hours of patience. Reducing the system clock to 8MHz seems to raise the probability of running into the described race condition
To verify the described race condition you can checkout the [Reference Manual](https://www.st.com/resource/en/reference_manual/cd00171190-stm32f101xx-stm32f102xx-stm32f103xx-stm32f105xx-and-stm32f107xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf) page 207 Figure 20.
I wrote a poor-man's frequency counter, measuring a NE555 multi-vibrator running at 33kHz (i.e. 33.000 IRQs per second) I had laying around:
```c
#include …
```
> cpu/stm32/gpio_f1: fix IRQ handler

- tests/disp_dev/Makefile
- tests/disp_dev/main.c
This PR improves the `tests/disp_dev` test application in order to remove the explicit dependency to the ili9341 module by using `auto_init_screen` and the related API.
There's also a small optimization of the screen refresh: apply the null pixel by lines instead of pixel by pixel. This is much faster but needs a buffer (so increase memory usage).
I'm also wondering if `auto_init_screen` shouldn't be made a default module when disp_dev is used. This would simplify the application Makefile again but would enforce all display device with a `disp_dev` adaption layer to provide an `auto_init` function. Thoughts ?
- Tested on adafruit-clue and the RIOT logo is displayed as expected (but faster)
Thought of it after reviewing #12509
> tests/disp_dev: improve genericity of application + optimize screen refresh

- tests/touch_dev/Makefile
- tests/touch_dev/main.c
This PR is similar to #16479 but applied to the `tests/touch_dev` application.
- The test application is still functional. Tested on stm32f429i-disc1:
<details>
```
$ USE_PROGRAMMER_WRAPPER_SCRIPT=1 BUILD_IN_DOCKER=1 make -C tests/touch_dev flash term --no-print-directory  …
```
> tests/touch_dev: improve genericity by using auto_init_screen module

- boards/esp32-wrover-kit/Makefile.dep
When `disp_dev` is present, pull the ili9341 driver to allow auto-initialization. Previously initialization of LVGL failed because no display was found.
- `make -C tests/pkg_lvgl BOARD=esp32-wrover-kit flash`. See the system monitor test 😉 
Fixes #16471
> boards/esp32-wrover-kit: add dependency to ILI9341

- dist/tools/uncrustify/whitelist.txt
- drivers/include/sx127x.h
- drivers/sx127x/sx127x.c
- drivers/sx127x/sx127x_getset.c
- drivers/sx127x/sx127x_internal.c
- drivers/sx127x/sx127x_netdev.c
- tests/driver_sx127x/main.c
When working on #16177, I took some "inspiration" from the sx127x driver and where I found lots of style issues. This PR is fixing them by running uncrustify on related files:
```
$ docker run --rm -ti -u $(id -u) -v $(pwd):/data/riotbuild riot/static-test-tools uncrustify -c uncrustify-riot.cfg --replace drivers/sx127x/*.c
$ docker run --rm -ti -u $(id -u) -v $(pwd):/data/riotbuild riot/static-test-tools uncrustify -c uncrustify-riot.cfg --replace drivers/include/sx127x.h
$ docker run --rm -ti -u $(id -u) -v $(pwd):/data/riotbuild riot/static-test-tools uncrustify -c uncrustify-riot.cfg --replace tests/driver_sx127x/main.c
```
All files are whitelisted in the uncrustify check.
A green CI
None
> drivers/sx127x: uncrustify code

- sys/include/byteorder.h
`byteorder.h` already includes functions that are able to read/write integers from/to buffers with big endian byte order as target. Functions for doing the same with a little endian target are however so far missing, so this PR is adding them. These are however useful when writing hardware independent code e.g. for network protocols that use little endian byteorder as for example the advertising data in BLE advertising packets.
The 6 added functions are pretty much a copy/paste from the existing `byteorder_bebuftohX()` and `byteorder_htobebufX()` functions, except that of course the #if/#else  blocks are switched around.
Code review and successful build test should do the trick.
none
> sys/byteorder: add little endian to/from buf functions

- pkg/lvgl/contrib/lvgl.c
- pkg/lvgl/include/lvgl_riot.h
- tests/pkg_lvgl/main.c
- tests/pkg_lvgl_touch/main.c
This PR is a small refactoring of the lvgl integration into RIOT: the internal thread used to trigger the lvgl task handler is removed and `lvgl_start` is renamed `lvgl_run`. It's still possible to run lvgl in its own thread, but this becomes the responsibility of the user  to do that.
There's one call to `lv_task_handler();` that is moved from `lvgl_init` to the beginning of `lvgl_run`. I'm suspecting that this change might fix the issue reported in #16471.
Since there's one thread less in `tests/pkg_lvgl` and `tests/pkg_lvgl_touch`, this PR frees up 2K of RAM on both.
- `tests/pkg_lvgl` and `tests/pkg_lvgl_touch` are still functional
Might help with #16471
> pkg/lvgl: remove internal thread

- dist/tools/edbg/Makefile
- adds pic32 & saml11 devices
- Nuvoton M480 series support
The sam*-xpro boards should still be flashable.
> tools/edbg: bump version

- cpu/stm32/periph/gpio_all.c
This is a follow-up for #16272 for the STM32G0, STM32L5 and STM32MP1 families. The same description applies.
The reference manuals I based this PR on:
- [STM32G0x1 RM](https://www.st.com/resource/en/reference_manual/dm00371828-stm32g0x1-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf): Page 320, Figure 27
- [STM32L552xx and STM32L562xx RM](https://www.st.com/resource/en/reference_manual/dm00346336-stm32l552xx-and-stm32l562xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf): Page 539, Figure 48
- [STM32MP151 RM](https://www.st.com/resource/en/reference_manual/dm00366349-stm32mp151-advanced-armbased-32bit-mpus-stmicroelectronics.pdf): Page 1304, Figure 138
I don't own a board with a CPU of the mentioned families. If you do: please verify that GPIO IRQs are still working. …
> cpu/stm32/gpio_all: fix IRQ handler for G0/L5/MP1 families

- cpu/sam0_common/include/periph_cpu_common.h
- cpu/sam0_common/periph/uart.c
I did misunderstand this feature: This only inverts the data bits (instead of `c` uart will transmit `~c`), not the whole line level.
This is not very useful on it's own, so revert it.
This reverts #14300
> cpu/sam0_common: UART: Revert "implement inverted RX & TX"

- drivers/disp_dev/Kconfig
- drivers/disp_dev/Makefile.dep
- drivers/touch_dev/Kconfig
- drivers/touch_dev/Makefile.dep
- pkg/lvgl/Makefile.dep
- tests/disp_dev/Makefile
- tests/pkg_qr-code-generator/Kconfig
- tests/pkg_qr-code-generator/Makefile.board.dep
- tests/touch_dev/Makefile
This PR simplifies a bit the dependency resolution around the disp_dev and touch_dev modules. Now that #16479 and #16480 are merged it's possible to automatically set auto_init_screen as a default module when disp_dev and touch_dev modules are used.
As a result, by default,  it enforces any device providing a disp_dev/touch_dev interface to provide an auto_init function (since auto_init is used by default as well). But one can disable this using `DISABLE_MODULE += auto_init_screen` from an application that manually initialize the specific device driver.
- `tests/disp_dev`, `tests/touch_dev`, `tests/pkg_qr-code-generator`, `tests/pkg_lvgl` and `tests/pkg_lvgl_touch` are still working
Follow-up of #16479 and #16480
> drivers/{disp_dev,touch_dev}: add auto_init_screen as default module when used

- .github/workflows/test-on-iotlab.yml
- dist/testbed-support/makefile.iotlab.single.inc.mk
- examples/lorawan/README.md
- tests/pkg_semtech-loramac/README.md
This PR ticks the item in #9694 which is about merging auto and auto-ssh possible values for IOTLAB_NODE. As said by @cladmi, since there's an IOT_LAB_FRONTEND_FQDN env variable on the frontend there's no need to distinguish between auto and auto-ssh.
This makes the usage of IOTLAB_NODE more simple as well as cleaning up the internal implementation.
This PR also adds a deprecation message when auto-ssh is uses.
- Start an experiment on IoT-LAB with several iotlab-m3 and a8-m3:
```
$ iotlab-experiment submit -d 120 -l saclay,a8,110 -l grenoble,m3,20-31 -l saclay,m3,1-2
```
- Build and flash an application for the M3, use auto to select one automatically (the first one in grenoble is used):
<details>
```
$ BUILD_IN_DOCKER=1 make -C examples/default BOARD=iotlab-m3 IOTLAB_NODE=auto flash …
```
> tools/testbed: use IOTLAB_NODE=auto instead of auto-ssh

- cpu/stm32/dist/irqs/gen_irqs.py
Sort the output of `sort_cpu_lines` which relies on the output of `os.listdir` whose order is not deterministic.
> cpu/stm32: Generate the irqs in a reproducible manner

- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/event/timeout.c
- sys/include/event/timeout.h
- tests/events/main.c
This PR adds an option to use ztimer as the backend for an `event/timeout`. To keep the API compatible I added a `ztimer_clock_t` field to the `event_timeout_t` type. But this could also be passed in the function signature and maybe have static inlines to implement the current API.
- `USEMODULE+=event_timeout_ztimer make -C flash teset`
TODO: add a individual test.
> sys/event/timeout: add option to use ztimer as backend

- .github/labeler.yml
The labeler seems to be missing changes on `Kconfig` files that occur in subdirectories of the tree (e.g. #16515). This tries to match those.
Not really sure if the labeler can be triggered before merging this. The glob pattern should match now all Kconfig files in the tree.
Example of issue in #16515
> .github/labeler: match Kconfig files in subfolders

- pkg/pkg.mk
This PR is a take over of #11491 adapted to the new pkg.mk structure. This allows to build an application using a package even without network and if the package was already downloaded once (except for openthread and micropython).
I'm wondering if this will work on Murdock with tags given as package version. If this is problematic, failing package version will have to be updated to the commit hash.
- Check that git fetch is not called if not needed (no message printed):
<details>
- first call: no fetch
```
$ make -C tests/pkg_cayenne-lpp/
make: Entering directory '/work/riot/RIOT/tests/pkg_cayenne-lpp'
Building application "tests_pkg_cayenne-lpp" for "native" with MCU "native".
[INFO] updating cayenne-lpp /work/riot/RIOT/build/pkg/cayenne-lpp/.pkg-state.git-downloaded …
```
> pkg/pkg.mk: avoid git fetch if commit is already there

- .github/labeler.yml
This PR fixes the Kconfig minimatch pattern added in #16518 otherwise the automatic labeler action is failing in master ATM.
Needs to be merged in master first unfortunately
Fixes an issue introduced by #16518
> .github/labeler: quote rules

- dist/testbed-support/iotlab-debug.sh
- dist/testbed-support/makefile.iotlab.single.inc.mk
This PR extends the IoT-LAB tooling support with the remote debugging facility provided by the testbed. The tools are wrapped inside the `debug` and `debug-server` make targets when the IOTLAB_NODE variable is used.
To start/stop the GDB server the nodes of an experiment, IoT-LAB cli-tools provide the `iotlab-node --debug-start` and `iotlab-node --debug-stop` commands and the GDB server can be reached on port 3333, either directly from the SSH frontend or via an SSH tunnel from the local computer.
This PR supports both use case.
All boards exceptt firefly, zigduino and iotlab-a8-m3 can use this feature.
- Start an experiment on IoT-LAB:
```
$ iotlab-experiment submit -d 120 -l saclay,m3,2 -l saclay,nrf52dk,1 -l saclay,st-lrwan1,2
$ iotlab-experiment wait
```
- Start a debug session from …
> tools/iotlab-testbed: add support for remote debugger

- sys/include/bit.h
There are functions to set and clear bits in a bit map, but no functions to check if a bit in a bit map is set.
Add those trivial functions for consistency. 
Read.
> sys/bit: add bit_checkXX() functions

- Makefile.include
Makes the functionality of being more quiet on build (setting `QQ` to `@`) independently configurable from `RIOT_CI_BUILD`.
For the release tests I mostly want a binary as a normal user would if they do `make all`, so I do not want to use `RIOT_CI_BUILD=1` as it changes some build behavior. However, I do want to reduce the output, as most of the time the interesting part is the output of the binary not the build output there.
Try building any application with ~~`MORE_QUIET=1`~~ `QUIETER=1`. Compared to ~~`MORE_QUIET=0`~~ `QUIETER=0` (the default) only the size output should be shown and no `"make" -C <dir>` commands
```console
$ MORE_QUIET=1 make -C examples/hello-world/ -j --no-print-directory all
Building application "hello-world" for "native" with MCU "native".
text	   data	    bss …
```
> make: introduce QUIETER

- boards/samr21-xpro/board.c
If the radio module is not used, there is no need to configure the antenna switch.
Antenna should still be configured with `at86rf233` in use.
> boards/samr21-xpro: only configure antenna switch if radio is used

- sys/include/net/gcoap.h
- sys/net/application_layer/gcoap/gcoap.c
`gcoap_req_send()` does not allow returning negative values to indicate errors. For the support of DTLS in gcoap it is useful to return error codes here to specify what went wrong (e.g. authentication failed) and not only return that 0 bytes were sent. 
This PR only changes the return type from `size_t` to `ssize_t` to allow this. The cast to `size_t` at the end is not necessary anymore, since `res` is already the right type now.
Reading and compiling examples/gcoap should be enough. It works the same as before.
> net/gcoap: change return type from gcoap_req_send() to ssize_t

- sys/auto_init/auto_init.c
(tinydtls context)
When DTLS is initialized after an application creates a DTLS socket, the memory access on the internal DTLS memory leads to a segfault. This PR moves the DTLS auto initialization right after the network stack initialization.
Happened for gcoap.
Tests should pass.
> sys/auto_init: move sock_dtls after network stack initialization

- boards/i-nucleo-lrwan1/Makefile.dep
- boards/nucleo-g431rb/Makefile.dep
- boards/nucleo-g474re/Makefile.dep
- boards/nucleo-l433rc/Makefile.dep
- boards/nucleo-l496zg/Makefile.dep
- boards/nucleo-l4r5zi/Makefile.dep
- boards/nucleo-l552ze-q/Makefile.dep
- boards/nucleo-wl55jc/Makefile.dep
- boards/p-nucleo-wb55/Makefile.dep
- makefiles/stdio.inc.mk
Currently, BOARDs are requiring `lpuart` even when it's not used or needed. This PR fixes this by requiring it only if `stdio_uart` is used.
It also makes `stdio_uart` depend on either `uart` or `lpuart` being selected. Because of inclusion order, both might be required, but currently, there is not much that can be done about that, worst case both get selected, but as long as a BOARD defaulting to `lpuart` requires it (as it is now), then there will be no issues.
- pr
```
BOARD=p-nucleo-wb55 make -C tests/minimal/ info-modules | grep uart
```
- master;
```
BOARD=p-nucleo-wb55 make -C tests/minimal/ info-modules | grep uart
periph_init_lpuart
periph_lpuart
```
> makefiles/stdio.inc.mk: stdio_uart require uart or lpuart

- pkg/nanocbor/Makefile
- add support for decimal fractions
- fix underflow in nanocbor_leave_container()
- make return values consistent with documentation
`tests/pkg_nanocbor` and `tests/suit_manifest` should still work. (tested by Murdock)
> pkg/nanocbor: bump version

- boards/seeeduino_xiao/Kconfig
- boards/seeeduino_xiao/Makefile
- boards/seeeduino_xiao/Makefile.dep
- boards/seeeduino_xiao/Makefile.features
- boards/seeeduino_xiao/Makefile.include
- boards/seeeduino_xiao/board.c
- boards/seeeduino_xiao/doc.txt
- boards/seeeduino_xiao/include/board.h
- boards/seeeduino_xiao/include/gpio_params.h
- boards/seeeduino_xiao/include/periph_conf.h
- examples/lua_REPL/Makefile.ci
- tests/bench_xtimer/Makefile
This pull request adds support for the Seeeduino XIAO board for RIOT OS. 
This implementation is based of the Serpente R2 board.
The feature PWM is not available in the current pull request.
The implementation passed all standard periphery tests. (UART, I2C, SPI etc.)
> boards: Adding board support for the Seeeduino XIAO

- tests/riotboot_flashwrite/Makefile
- tests/riotboot_flashwrite/README.md
- tests/riotboot_flashwrite/main.c
- tests/riotboot_flashwrite/tests-with-config/01-run.py
I brought back to life an old PR I had to add a test for #15511, so this PR is based on top of that one. I'm not enabling it in the CI, but I still think having the script is useful for testing `riotboot_flashwrite`.
-  libcoap `coap-client` must be in the path
- setup network
`sudo dist/tools/ethos/setup_network.sh riot0 2001:db8::/64`
- run test
`make -C tests/riotboot_flashwrite/ flash test -j3`
> tests/riotboot/flashwrite: add automatic test

- sys/Makefile.dep
- sys/event/periodic.c
- sys/include/event/periodic.h
- sys/include/event/timeout.h
- tests/event_ztimer/Makefile
- tests/event_ztimer/Makefile.ci
- tests/event_ztimer/main.c
- tests/event_ztimer/tests/01-run.py
This PR adds a periodic timeout event using `ztimer`. Useful to scheduler a task that should be periodically executed, e.g.: reading some sensor.
`make -C tests/event_timeout_ztimer`
depend on #16505
> sys/event: add periodic timeout event 

- pkg/nimble/Makefile.include
- tests/nimble_l2cap_server/nimble.inc.mk
The current buffer size configuration for `nimble_netif` is broken: if the L2CAP COC MPS size (`MYNEWT_VAL_BLE_L2CAP_COC_MPS`) is set to a value larger than the maximum link layer packet size (`MYNEWT_VAL_BLE_LL_MAX_PKT_SIZE`), it triggers faulty behavior where the link layer will simply cut off bytes at the end of the payload, leading to the receiving node being stuck waiting for those missing bytes.
Currently, nodes will run out of nimble buffers and get stuck when receiving IP packets larger than 251 bytes...
This PR cleans up and optimizes the NimBLE buffer sizes for the use with `nimble_netif`: 
- the faulty behavior as described above is fixed by setting `COC_MPS` equal to `LL_MAX_PKT_SIZE`
- the `MSYS_1_BLOCK_SIZE` is adapted, so that a full COC payload of 251 bytes fits into a …
> pkg/nimble/netif: fix and optimize NimBLE buffer sizes

- examples/gnrc_networking/udp.c
This PR makes the `gnrc_networking` example use `ZTIMER_MSEC` whenever `ztimer_msec` is included in the build. Although this PR is not really useful w.r.t. power consumption, as the example includes the shell, which on most platforms blocks low power modes similar to xtimer, it is still helpful in terms of code size and modularity as this prevents xtimer to be pulled into otherwise ztimer only builds...
Compile and run the example with `USEMODULE="ztimer_msec ztimer_periph_rtt" make ..` for you favorite platform...
Similar to e.g. #16339, #16322, #16340
> examples/gnrc_networking: use ztimer_msec if available

- sys/Makefile.dep
- sys/include/trickle.h
- sys/shell/commands/sc_gnrc_rpl.c
- sys/trickle/trickle.c
- tests/trickle/main.c
This PR migrates `trickle` from xtimer to `ZTIMER_MSEC`. This allows for a) slightly simpler code, and b) for potential energy savings as `xtimer` can (at one point) be left out of a GNRC build.
The acutal changes are pretty straight forward, no surprises here :-) 
Running the `test/trickle` test should suffice.
none
> sys/trickle: migrate from xtimer to ZTIMER_MSEC

- examples/openthread/main.c
- pkg/openthread/include/ot.h
Since #15038 saw the light, the current "ot_command" wrapper is only limiting OpenThread usage. The Event Queue makes it possible now to call OpenThread API functions directly when posting an event to the OpenThread queue.
This PR removes the `ot_command` calls from `examples/openthread`, improve Doxygen documentation and deprecate the "ot_command" related functions
Test if `examples/openthread` still works ok. Note that it's possible to run OpenThread with any board that supports the Radio HAL if using `netdev_ieee802154_submac`.
None so far
> pkg/openthread: deprecate ot_command related functions

- boards/common/kw41z/Makefile.features
- boards/frdm-kl43z/include/board.h
- boards/frdm-kw41z/include/board.h
- boards/openlabs-kw41z-mini/include/board.h
- boards/pba-d-01-kw2x/Kconfig
- boards/pba-d-01-kw2x/Makefile.features
- boards/phynode-kw41z/include/board.h
- boards/usb-kw41z/include/board.h
- cpu/kinetis/Kconfig
- cpu/kinetis/Makefile.dep
- cpu/kinetis/Makefile.features
- cpu/kinetis/include/periph_cpu.h
- cpu/kinetis/periph/rtc.c
- cpu/kinetis/periph/rtt.c
- tests/periph_rtt/Makefile
This pr makes `rtc` use the RTC peripheral and `rtt` use the `RTT` peripheral. This wants to remove the remaining od-ball that is `kinetis`, with this we can simply do:
```
ifneq (,$(filter ztimer_msec,$(USEMODULE))
FEATURES_OPTIONAL += periph_rtt
ifneq (,$(filter periph_rtt,$(FEATURES_USED)))
USEMODULE += ztimer_periph_rtt
endif
endif
ifneq (,$(filter stm32 nrf52 sam%,$(CPU)))
RTT_FREQUENCY ?= RTT_MAX_FREQUENCY
CFLAGS += -DRTT_FREQUENCY=$(RTT_FREQUENCY)
endif
```
And have `rtt` always pulled as the `ztimer_msec` backend if available.
On all kinetis as possible run
- `tests/periph_rtt`
```
2021-06-11 17:59:01,668 # main(): This is RIOT! (Version: 2021.07-devel-322-g92924-HEAD)
2021-06-11 17:59:01,668 # 
2021-06-11 17:59:01,671 # RIOT RTT low-level driver test
2021-06-11 17:59:01,673 # RTT …
```
> cpu/kinetis: use LPTMR as rtt backend 

- makefiles/boot/riotboot.mk
When using `riotboot` conveniently the extended binary is used. But if `clean` is also used then the bootloader binary is not cleaned, this can lead to unexpected behavior where a previous bootloader (eg: different start addresses) is used.
- `make -C tests/riotboot flash`
- `make -C tests/riotboot clean flash -j3` you should see that that the bootloader and application are compiled while in master only the application is:
```
"make" -C /home/francisco/workspace/RIOT2/boards/stm32f429i-disc1
"make" -C /home/francisco/workspace/RIOT2/core
"make" -C /home/francisco/workspace/RIOT2/cpu/stm32
"make" -C /home/francisco/workspace/RIOT2/cpu/cortexm_common
"make" -C /home/francisco/workspace/RIOT2/cpu/cortexm_common/periph
"make" -C /home/francisco/workspace/RIOT2/cpu/stm32/periph
"make" -C …
```
> makefiles/boot/riotboot: clean bootloader when cleaning application

- sys/include/net/ieee802154_security.h
- sys/net/link_layer/ieee802154/Kconfig
- sys/net/link_layer/ieee802154/security.c
Makes IEEE 802.15.4 security module configurable with Kconfig.
`USEMODULE="ieee802154 ieee802154_security" BOARD=nucleo-f767zi make -C examples/gnrc_networking menuconfig`
> Kconfig: expose IEEE 802.15.4 Security to Kconfig

- boards/feather-nrf52840/Kconfig
- boards/feather-nrf52840/Makefile.dep
- boards/feather-nrf52840/Makefile.features
- boards/feather-nrf52840/Makefile.include
- boards/feather-nrf52840/doc.txt
- boards/feather-nrf52840/reset.c
Add the uf2 bootloader for the BOARD as its the default bootloader on the BOARD when shipped from adafruit.
Flash anything it should work...
```
BOARD=feather-nrf52840 make -C tests/bloom_bytes/ flash test
Building application "tests_bloom_bytes" for "feather-nrf52840" with MCU "nrf52".
"make" -C /home/francisco/workspace/RIOT/boards/feather-nrf52840
"make" -C /home/francisco/workspace/RIOT/cpu/nrf52
"make" -C /home/francisco/workspace/RIOT/cpu/cortexm_common
"make" -C /home/francisco/workspace/RIOT/cpu/cortexm_common/periph
"make" -C /home/francisco/workspace/RIOT/cpu/nrf52/periph
"make" -C /home/francisco/workspace/RIOT/cpu/nrf52/vectors
"make" -C /home/francisco/workspace/RIOT/cpu/nrf5x_common
"make" -C …
```
> board/feather-nrf52840: add uf2 boot loader

- sys/net/gnrc/network_layer/ipv6/nib/nib.c
If we switch the interface in `gnrc_ipv6_nib_get_next_hop_l2addr()` we must also re-get the nib entry from the 'proper' interface.
Otherwise we will always find the host unreachable on the 'wrong' interface.
You need a node with two interfaces of type `Ethernet` with both of them having a global address configured.
Now send a ping request to the global address of the second interface by a host connected to the first interface.
On `master` only the first request is answered and any subsequent communication to that host fails from the downstream interface address. Instead, the node will send a neighbor solicitation even though the host is already in the neighbor cache.
With this patch, the pings are answered as expected. 
fixes #16547
> gnrc_ipv6_nib: get node from proper interface

- drivers/sm_pwm_01c/Kconfig
Removes a `checksum` module from the kconfig for the sm_pwm_01c.  It doesn't show up in the binary but the info-modules show a difference
Run this on master vs this pr.
```
cd tests/driver_sm_pwm_01c
make clean && make info-modules > /tmp/no-kconfig && make clean && TEST_KCONFIG=1 make info-modules > /tmp/kconfig && diff /tmp/no-kconfig /tmp/kconfig
```
> drivers/sm_pwm_01c: remove checksum in Kconfig

- boards/native/include/eui_provider_params.h
- boards/same54-xpro/include/eui_provider_params.h
- sys/include/net/eui_provider.h
- sys/net/link_layer/eui_provider/eui_provider.c
Otherwise the provider can be used for multiple interfaces but only return a single MAC address for all of them.
Add `USEMODULE += dose` to `examples/gnrc_networking` when building for `same54-xpro`.
Both DOSE and Ethernet interface use the same MAC address from the at24mac chip.
```
2021-06-02 13:54:52,130 # Iface  6  HWaddr: FC:C2:3D:0D:2D:1F 
2021-06-02 13:54:52,134 #           L2-PDU:1500  MTU:1500  HL:64  RTR  
2021-06-02 13:54:52,136 #           RTR_ADV  
2021-06-02 13:54:52,139 #           Source address length: 6
2021-06-02 13:54:52,141 #           Link type: wired
2021-06-02 13:54:52,147 #           inet6 addr: fe80::fec2:3dff:fe0d:2d1f  scope: link  VAL
2021-06-02 13:54:52,150 #           inet6 group: ff02::2
2021-06-02 13:54:52,152 #           inet6 group: ff02::1
2021-06-02 …
```
> boards: lock EUI provider to interface type

- cpu/stm32/periph/rtt_all.c
- cpu/stm32/stmclk/stmclk_common.c
cpu/stm32/periph/rtt_all: 
When testing peripherals on a CPU_FAM_STM32L5 based BOARD, tests/periph_rtt didn't work as expected. Implemented a case for CPU_FAM_STM32L5 for correct LPTIM1 register setup. 
Ran `tests/periph_rtt` on a STM32L5 CPU based BOARD, output as expected (bunch of Hellos). Wasn't working before since the registers for LPTIM1 setup weren't correct. 
Addition of periph_rtt to CPU_FAM_STM32L5
> cpu/stm32/periph/rtt_all: RTT peripheral support for CPU_FAM_STM32L5

- boards/z1/include/board.h
Without tunning most BOARD's behave OK, but some behave very bad as shown by https://github.com/RIOT-OS/RIOT/pull/16254. This PR adds the configuration adjust values for the spotted BOARDS.
- rebase on #16254 and run ` make -C tests/ztimer_periodic/ flash test`
- z1
```
2021-06-15 16:35:05,351 # main(): This is RIOT! (Version: 2021.07-devel-382-g391315-pr-16254)
2021-06-15 16:35:05,354 # Testing clock: ZTIMER_MSEC
2021-06-15 16:35:05,857 # i: 0 time: 3834 offset: 0
2021-06-15 16:35:05,859 # i: 1 time: 3934 offset: 0
2021-06-15 16:35:05,862 # i: 2 time: 4035 offset: 1
2021-06-15 16:35:05,864 # i: 3 time: 4134 offset: 1
2021-06-15 16:35:05,866 # i: 4 time: 4235 offset: 1
2021-06-15 16:35:05,869 # Testing clock: ZTIMER_USEC
2021-06-15 16:35:05,922 # i: 0 time: 4259368 offset: 28
2021-06-15 …
```
> boards/z1: add CONFIG_ZTIMER_USEC_ADJUST_% values

- drivers/sx127x/Makefile.dep
- pkg/nimble/Makefile.dep
- pkg/openwsn/Makefile.dep
- pkg/openwsn/Makefile.include
- sys/Makefile.dep
- sys/Makefile.include
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
- sys/ztimer/Makefile.include
- tests/pkg_umorse/Makefile.ci
- tests/ztimer_periodic/Makefile.ci
With #16546 `ztimer_periph_rtt` can always be included since all rtt are capable of supplying a msec timer, so this PR includes it by default.
I'm not sure how the Kconfig dependency should be adapted, I gave it a go but maybe @leandrolanzieri could take a second look.
Included modules should be the same for the affected pkgs, `rtt` is included when possible otherwise `ztimer_msec` fallbacks to `periph_timer`,
Takeover of #16334
> ztimer: pull ztimer_periph_rtt for ZTIMER_MSEC if available

- makefiles/boot/riotboot.mk
If flashing a riotboot application on iotlab, then `FLASHFILE` is not set on the submake since the `PROGRAMMER=iotlab`.  By passing IOTLAB_NODE this is fixed:
The following fails in master:
```
IOTLAB_NODE=auto BOARD=iotlab-m3 make -C tests/riotboot riotboot/flash-combined-slot0
Warning! EXTERNAL_MODULE_DIRS is a search folder since 2021.07-branch, see https://doc.riot-os.org/creating-modules.html#modules-outside-of-riotbase
3.2.1
/home/francisco/workspace/RIOT/bootloaders/riotboot/../..//Makefile.include:614: *** FLASHFILE is not defined for this board: .  Stop.
make: *** [/home/francisco/workspace/RIOT/makefiles/boot/riotboot.mk:81: riotboot/bootloader/binfile] Error 2
```
is fixed with this PR.
Exposed by #16047
> makefiles/boot/riotboot.mk: pass IOTLAB_NODE

- dist/tools/kconfiglib/riot_kconfig.py
This commit fixes the generation of autoconf headers.
The `write_autoconf` function in the RIOT wrapper was overriding
the default value of the `header` arg to None in Kconfiglib's `write_autoconf`.
It's now set to the default header.
I was not able to reproduce it in other environments, but at least it should be possible to see that Kconfig's `write_autoconf` will never receive `header=None`.
None so far
> dist/Kconfiglib: fix autoconf header

- sys/include/net/gnrc/rpl.h
- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/routing/rpl/gnrc_rpl.c
- sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
With this PR RPL will use `ztimer_msec` as timer whenever  `ztimer_msec` is included in the build. This is needed for `xtimer`-free GNRC builds for getting to lower power consumption.
One small quirk: when building with ztimer, the RPL shell commands does not show the remaining seconds until the trickle timer triggers next anymore. This is due to missing functionality in the `ztimer`, and IMO it would be overkill to add this functionality into ztimer (or any other workaround in the trickle timer) just to get this debug information...
The default builds (e.g. `examples/gnrc_networking`) should not change, as per default RPL will still use xtimer. But when building with `ztimer_msec` included in the build, RPL should switch to use `ztimer_msec`.
This can be tested e.g. with two samr21-xpro …
> net/gnrc/rpl: use ztimer_msec if available

- examples/gnrc_lorawan/main.c
- sys/include/net/gnrc/lorawan.h
- sys/include/net/gnrc/netif/lorawan.h
- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/link_layer/lorawan/Kconfig
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mcps.c
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mlme.c
- sys/net/gnrc/link_layer/lorawan/include/gnrc_lorawan_internal.h
- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
This PR adds support for using RTT in GNRC LoRaWAN. This is required for the following reasons:
- Standard xtimer cannot go to very low power modes.
- For class B support precise timers are required.
The RTT support is provided vía `ztimer` (`ztimer_periph_rtt` backend).
EDIT: This add an explicit requirement to `periph_rtt`.
Test with `examples/gnrc_lorawan`. Try to Join a LoRaWAN network and send/receive data. It should work with all possible DR.
E.g
```
ifconfig 4 set deveui aaaaaaaaaaaaaaaa
ifconfig 4 set deveui bbbbbbbbbbbbbbbb
ifconfig 4 set appkey cccccccccccccccccccccccccccccccc
/* Set highest DR */
ifconfig 4 set dr 5
ifconfig 4 up
/* Wait approx 7 seconds and interface should e up*/
ifconfig
2020-07-20 13:36:18,496 # Iface  4  HWaddr: 01:19:86:07  Frequency: 868299987Hz  BW: …
```
> gnrc_lorawan: add support for RTT (ztimer)

- tests/ztimer_periodic/Makefile.ci
- tests/ztimer_periodic/main.c
Instead of only testing for `ZTIMER_MSEC`, iterate over a list of
clocks and run the test for each. The reasoning is that this test
does not only test `ztimer_periodic`, but also that the used clock
backend operates correctly in a typical use case.
The test should still pass.
Useful for #16172
> tests/ztimer_periodic: iterate over clocks

- sys/auto_init/auto_init.c
- sys/include/net/gnrc/dhcpv6/client/simple_pd.h
- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/application_layer/dhcpv6/client.c
- sys/net/gnrc/application_layer/dhcpv6/client_simple_pd.c
The `gnrc_dhcpv6_client_6lbr` code only considers 6LoWPAN interfaces possible downstream interface candidates.
This needlessly excludes the use of DHCPv6 for non-6lo downstream networks.
Chose all non-upstream interfaces as downstream interfaces for DHCPv6 to allow using it together with e.g. SLIP, DOSE or ethos.
I tested this on `same54-xpro` which has an Ethernet interface that is used as uplink and which has a downlink device connected via SLIP.
For this to work with SLIP a second patch is needed to simulate a L2 address that is then used as an IPv6 IID.
I ran this with `examples/gnrc_networking` with the following modules added:
```Makefile
USEMODULE += ethos
USEMODULE += gnrc_dhcpv6_client_6lbr
CFLAGS += -DETHOS_UART=UART_DEV\(1\)
CFLAGS += -DETHOS_BAUDRATE=115200
CFLAGS += …
```
> gnrc_dhcpv6_client_6lbr: choose downstream if as !upstream

- cpu/avr8_common/avr_libc_extra/include/errno.h
https://www.nongnu.org/avr-libc/user-manual/group__avr__errno.html only defines two errno, at least make sure those match.
`tests/turo` and other code relying on the MACRO now pass:
```
✓ Flashing done! (programmer: 'avrdude' - duration: 3.01s)
.............
----------------------------------------------------------------------
Ran 13 tests in 8.378s
```
> cpu/avr8_common: fix errno

- tests/congure_test/tests/01-run.py
- tests/turo/tests/01-run.py
Some BOARD terminal is slow to start so if the BOARD is reset after
opening the terminal this can lead to off-by-one error when parsing
the output.
So instead do as testrunner and reset before opening the terminal.
Note that no interactive_sync is needed since a similar mechanism
happens in ShellInteraction.
- Murdock should now be green
- Ran the tests on a list of [BOARD's](https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/271/artifact/), (atmega based boards failures are unrelated to this PR, and `ek-lm4f120xl` failed to flash, and `z1` fails to boot the firmware on master as well)
fixes  #16415
> tests/congure-turo: reset before opening terminal

- pkg/nimble/Makefile.dep
- pkg/nimble/autoconn/include/nimble_autoconn.h
- pkg/nimble/autoconn/include/nimble_autoconn_params.h
- pkg/nimble/autoconn/nimble_autoconn.c
- pkg/nimble/netif/include/nimble_netif.h
- pkg/nimble/netif/include/nimble_netif_conn.h
- pkg/nimble/netif/nimble_netif.c
- pkg/nimble/netif/nimble_netif_conn.c
- pkg/nimble/statconn/nimble_statconn.c
As we were able to show in our research, using the same connection interval for multiple connections of a node can decrease network performance significantly. To prevent this, one solution is to use random connection intervals chosen from a configured range. This is already in the RIOT code base specifically for the `nimble_statconn` module. This PR generalizes this approach to be applicable for all modules using `nimble_netif`.
On top, this PR adds the option to enforce different connection intervals for each of a nodes connection. If a nodes opens a new connection as master, it will generate random intervals and check them against the interval of each existing connections, until it finds a connection interval that is spaced at least `NIMBLE_NETIF_CONN_ITVL_SPACING_MS` ticks apart from …
> pkg/nimble/netif: allow to apply and enforce random and unique connection intervals

- sys/Makefile.dep
- sys/arduino/base.cpp
- tests/sys_arduino/Makefile.ci
This PR replaces xtimer by ztimer as high-level background timer for delay/delayMicroseconds/millis/micros functions.
- `tests/sys_arduino` should still work:
<details><summary>nucleo-l412kb</summary>
```
$ BUILD_IN_DOCKER=1 RIOT_VERSION=test make BOARD=nucleo-l412kb -C tests/sys_arduino --no-print-directory flash test
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' -e 'BUILD_DIR=/data/riotbuild/riotbase/build' -e 'RIOTPROJECT=/data/riotbuild/riotbase' -e 'RIOTCPU=/data/riotbuild/riotbase/cpu' -e …
```
> sys/arduino: replace xtimer by ztimer as high-level background timer

- cpu/cc2538/include/cc2538_rf.h
- cpu/cc2538/radio/cc2538_rf.c
- cpu/cc2538/radio/cc2538_rf_radio_ops.c
- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
- pkg/openwsn/Makefile.include
- pkg/openwsn/contrib/radio_hal.c
- sys/include/net/ieee802154.h
- sys/include/net/ieee802154/radio.h
- sys/include/net/ieee802154/submac.h
- sys/net/link_layer/ieee802154/Kconfig
- sys/net/link_layer/ieee802154/submac.c
- tests/ieee802154_hal/main.c
This PR implements the proposal from https://github.com/RIOT-OS/RIOT/pull/13943#issuecomment-724699696 (in a slightly different way, as described above).
This removes the `set_rx_mode` and `set_hw_addr_filter` and replace them with 3 functions:
- `config_addr_filter`
- `set_frame_filter_mode`
- `config_src_addr_match`
The original proposal didn't include the `set_frame_filter_mode`, but it turns out to be much better IMO to split the original proposal of `config_addr_filter` because there's indeed a mode for the frame filter (promisc, sniffer, accept only ACK frames, etc). This also adds a "reject all frames" mode, that might be useful for certain stacks (e.g OpenWSN).
Also, a `CONFIG_IEEE802154_AUTO_ACK_DISABLE macro was added in order to disable Auto ACK in radios (required for OpenWSN) …
> ieee802154/hal: adapt frame filter and source address matching changes

- pkg/semtech-loramac/Makefile.dep
- tests/pkg_semtech-loramac/Makefile.ci
This PR removes the hard dependency of ztimer RTT backend used by semtech-loramac package. AFAIU, with #16553, the RTT backend is only used when the periph_rtt is provided by the board.
- Semtech-loramac package based applications are still functional
- Check that ztimer RTT backend is used with b-l072z-lrwan1 board (which is the default for semtech-loramac applications)
- Check that examples/lorawan and tests/pkg_semtech-loramac can be built with im880b (no RTT provided so cannot be used in current master)
Follow-up of #16553
> pkg/semtech-loramac: don't force ztimer rtt backend

- makefiles/boot/riotboot.mk
If flashing a riotboot application on iotlab, then `FLASHFILE` is not set on the submake since the `PROGRAMMER=iotlab`.  By passing IOTLAB_NODE this is fixed:
The following fails in master:
```
IOTLAB_NODE=auto BOARD=iotlab-m3 make -C tests/riotboot riotboot/flash-combined-slot0
Warning! EXTERNAL_MODULE_DIRS is a search folder since 2021.07-branch, see https://doc.riot-os.org/creating-modules.html#modules-outside-of-riotbase
3.2.1
/home/francisco/workspace/RIOT/bootloaders/riotboot/../..//Makefile.include:614: *** FLASHFILE is not defined for this board: .  Stop.
make: *** [/home/francisco/workspace/RIOT/makefiles/boot/riotboot.mk:81: riotboot/bootloader/binfile] Error 2
```
is fixed with this PR.
Exposed by #16047
> makefiles/boot/riotboot.mk: pass IOTLAB_NODE [backport 2021.04]

- cpu/native/Kconfig
- cpu/native/mtd/Kconfig
Implement the mtd module for native in Kconfig.
apply a patch to .murdock
```patch
diff --git a/.murdock b/.murdock
index e692d0eeb3..db34f895b9 100755
--- a/.murdock
+++ b/.murdock
@@ -29,6 +29,7 @@ tests/cb_mux*
tests/congure_*
tests/driver_ws281x
tests/eepreg
+tests/mtd_flashpage
tests/periph_*
tests/pkg_c25519
tests/pkg_cayenne-lpp
```
run:
```
/bin/bash -c "source .murdock; JOBS=4 compile tests/mtd_flashpage native:gnu"
```
in both master and this PR.
> cpu/native: Add native mtd kconfig dep

- sys/net/gnrc/network_layer/ipv6/nib/_nib-6lr.h
- sys/net/gnrc/network_layer/ipv6/nib/_nib-router.h
Set the `CFLAGS += -DCONFIG_GNRC_IPV6_NIB_ADV_ROUTER=0` option to start RIOT with router advertisements disabled.
Then selectively enable router advertisements by running `ifconfig <if> rtr_adv`.
The first step was not possible on master as the config option was ignored.
The second step was not possible on a non-6lo node as `_nib-6lr.h` turned it into a no-op.
> gnrc/nib: fix starting with router advertisements disabled, enabling them at run-time

- CONTRIBUTING.md
- README.md
- doc/doxygen/src/mainpage.md
Freenode migrated to a different IRC network and we lost control of the #riot-os room there. As we no longer own this room the references to this room should be removed from the documentation and be replaced with a reference to the matrix room where applicable.
- Check that the IRC shield is gone from the README.
- The main page of doxygen now refers to the Matrix room for live chat and support
- There are no remaining references to IRC in the source (except for previous release notes)
See the forum [here](https://forum.riot-os.org/t/riot-irc-channel-and-the-freenode-turmoil) and [here](https://forum.riot-os.org/t/riot-irc-and-even-more-freenode-turmoil)
> docs: Remove references to Freenode from the documentation

- sys/ztimer/Makefile.include
In #16553 nrf51 was neglected by mistake in frequency configuration, this adds it for cases where the default frequency might be insufficient.
`IOTLAB_NODE=auto BOARD=nrf51dk make -C tests/ztimer_periodic/ flash test -j3`
```
main(): This is RIOT! (Version: 2021.07-devel-441-gbeee6f-pr_ztimer_rtt_nrf51)
Testing clock: ZTIMER_MSEC
i: 0 time: 3123 offset: 0
i: 1 time: 3223 offset: 0
i: 2 time: 3323 offset: 0
i: 3 time: 3423 offset: 0
i: 4 time: 3524 offset: 1
Testing clock: ZTIMER_USEC
i: 0 time: 3522502 offset: 50
i: 1 time: 3532510 offset: 8
i: 2 time: 3542510 offset: 0
i: 3 time: 3552510 offset: 0
i: 4 time: 3562510 offset: 0
Test successful.
```
> sys/ztimer: use highest frequency for nrf51 as well

- sys/net/gnrc/netif/gnrc_netif.c
- tests/gnrc_sixlowpan_frag_minfwd/Makefile.ci
Make `gnrc_netif_create()` block until the interface is created and registered.
This avoids a race condition where after calling `gnrc_netif_init_devs()` not all interfaces are available yet when iterating through the list of interfaces with `gnrc_netif_iter()`.
Replace the `auto_init_gnrc_netif` module with `gnrc_netif_init_devs` to manually initialize the network interfaces.
Then iterate all interfaces after having called `gnrc_netif_init_devs()`:
```C
/* enable network interfaces */
gnrc_netif_init_devs();
/* iterate all interfaces */
gnrc_netif_t *netif = NULL;
while (netif = gnrc_netif_iter(netif)) {
puts("network interface found");
}
```
Without this patch, this will 'find' no network interfaces (if the driver uses sleep inside it's init path), but after a delay all interfaces will …
> sys/net/gnrc/netif: make gnrc_netif_create() blocking to avoid race condition

- .murdock
Use a matrix for kconfig board/tests
As support grows we need a cleaner way of enforcing kconfig testing.
This checks an app contains an `app.config.test` for a supported board or if a test group must be tested.
This removes the need to list individual tests.
Groups can still be enforced with the `TEST_KCONFIG_ENFORCE_APP_GROUPS`.
If a board is in TEST_KCONFIG_BOARDS_AVAILABLE, all supported apps should be built.
Murdock passes, verify tests actually run on kconfig boards by checking murdock results of applicable tests (ie, samr21-xpro pkg_umorse, native xtimer_drift, etc.)
Depends on  ~~#16551~~, ~~#16558~~, and ~~#16550~~ to pass CI
> Simplify kconfig murdock testing

- sys/net/gnrc/network_layer/ipv6/nib/nib.c
- sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
If a node has two interfaces A with `2001:16b8:45b5:9af8:5884:3bff:fe4f:a903` and B with `2001:16b8:45b5:9afa:5884:3bff:fe4f:a902` and receives a neighbor solicitation on A for an address configured on interface B, answer the neighbor solicitation instead of bailing out with
> Target address `2001:16b8:45b5:9afa:5884:3bff:fe4f:a902` is not assigned to the local interface
see https://github.com/RIOT-OS/RIOT/pull/8823#discussion_r651768593
> gnrc_ipv6_nib: consider all local interfaces when looking for address

- pkg/wakaama/contrib/lwm2m_client.c
- pkg/wakaama/contrib/lwm2m_client_connection.c
This PR removes the only dependency to GNRC that was present in the Wakaama example, since https://github.com/RIOT-OS/RIOT/pull/12738 was already merged some time ago.
With this change it should be possible to run Wakaama with other network stacks (e.g LWIP ~and soon OpenThread~)
Run `examples/wakaama`
https://github.com/RIOT-OS/RIOT/pull/12738
> pkg/wakaama: remove gnrc dependency

- drivers/include/net/netdev.h
- drivers/include/slipdev.h
- drivers/slipdev/Makefile.dep
- drivers/slipdev/slipdev.c
- makefiles/pseudomodules.inc.mk
- sys/include/net/gnrc/netif/conf.h
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/netif/gnrc_netif_device_type.c
- sys/net/gnrc/netif/init_devs/auto_init_slipdev.c
- sys/net/link_layer/l2util/l2util.c
A lot of things break if `GNRC_NETIF_FLAGS_HAS_L2ADDR` is not set (failed asserts, no IPv6 IID).
In order to handle router advertisements and auto-configuration, generate a faux l2 address based on the netdev ID.
In combination with #16530 SLIP can now be used as a downstream interface for board to board communication:
I ran this on `same54-xpro` with examples/gnrc_networking with the following modules added:
```Make
USEMODULE += slipdev_l2addr
USEMODULE += gnrc_dhcpv6_client_6lbr
CFLAGS += -DSLIPDEV_PARAM_UART=UART_DEV\(1\)
CFLAGS += -DCONFIG_GNRC_DHCPV6_CLIENT_6LBR_UPSTREAM=5
```
The SLIP interface now has a hardware address, which gives it a link-local address and the possibility to get a prefix via DHCPv6:
```
2021-06-07 00:13:08,232 # ifconfig
2021-06-07 00:13:08,233 # Iface  6 …
```
> drivers/slipdev: report NETOPT_ADDRESS to simulate l2 address

- pkg/nanocbor/Makefile
Upstream fixed a nasty bug when decoding an indefinite container inside a fixed
length container.
The test should work as before.
None
> NanoCBOR: Bump version

- .github/workflows/release-test.yml
Tasks 4.5 and 4.6 use the firefly nodes at the lille site, so we need to verify the host key for that side as well (not sure why it worked so far without).
`release-test` for task 4.5 and 4.6 should succeed now.
> release-test: fetch host key for lille site

- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/net/dhcpv6.h
- sys/net/application_layer/dhcpv6/_dhcpv6.h
- sys/net/application_layer/dhcpv6/client.c
- sys/net/application_layer/dhcpv6/client_dns.c
Now that I finally have IPv6 at home, I started playing around with configuring my OpenWRT as a 6LoWPAN border router, using an nrf52840dongle with `cdc-ecm` as the actual border router.
It took me a while to remember that I also can get the DNS server information from the WRT's router advertisements using the `gnrc_ipv6_nib_dns`, so I added this optional feature to the DHCPv6 client.
Compile the border router example with DHCPv6 with `dhcpv6_client_dns` and `sock_dns`, flash it, and wait until the DHCPv6 initialization is completed (you can check by looking at the 6LoWPAN interface; when it has a global address the procedure is complete). Given that you have your DHCPv6 server and firewall configured properly, you should now be able to ping a host name from the border router (did not …
> dhcpv6_client: add DNS recursive name server option handling

- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
This PR fixes a memory leak introduced by #16080. The netif hdr was not being released on send.
On current master:
```
ifconfig 3 up
2021-06-24 15:24:51,325 # ifconfig 3 up
> ifconfig
2021-06-24 15:25:06,809 # ifconfig
2021-06-24 15:25:06,820 # Iface  3  HWaddr: 26:01:44:AF  Frequency: 869524963Hz  RSSI: 99  BW: 125kHz  SF: 12  CR: 4/5  Link: up 
2021-06-24 15:25:06,827 #            TX-Power: 14dBm  State: SLEEP  Demod margin.: 0  Num gateways.: 0 
2021-06-24 15:25:06,829 #           IQ_INVERT  
2021-06-24 15:25:06,833 #           RX_SINGLE  OTAA  L2-PDU:767  
2021-06-24 15:25:06,834 #           
txtsnd 3 01 "THIS IS RIOT!"
2021-06-24 15:26:25,320 # txtsnd 3 01 "THIS IS RIOT!"
> txtsnd 3 01 "THIS IS RIOT!"
2021-06-24 15:26:29,540 # txtsnd 3 01 "THIS IS RIOT!"
> pktbuf
2021-06-24 …
```
> gnrc_netif/lorawan: drop netif header on send

- sys/include/net/gnrc/lorawan.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
This PR fixes and undefined state when the PSDU is NULL (because `dev->driver->recv(...) return 0 or an error).
On current master, the MAC layer misses an event if `gnrc_lorawan_radio_rx_done_cb` is called with NULL. This either hangs the MAC layer or gets it stuck in a loop.
Since receiving a wrong packet is equivalent to an rx_timeout, I added a `gnrc_lorawan_radio_rx_error_cb` wrapper that maps to `gnrc_lorawan_radio_rx_timeout_cb`.
Without this PR, if this patch is applied:
```diff
diff --git a/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c b/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
index 51b06f2ac3..c9aa3f5cb4 100644
--- a/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
+++ b/sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
@@ -183,7 +183,8 @@ static void …
```
> gnrc_lorawan: fix undefined state when PSDU is NULL

- sys/ztimer/convert.c
- sys/ztimer/convert_frac.c
avoid blocking and unblocking of power mode 0 for convert clocks
@vincent-d identified in #15911 that pm should be done in base clock which was implemented in the huge ztimer auto init overhaul, but it was lacking the not blocking and not unblocking of #15911 for convert clocks which by default are set to 0 (un)blocking that pm
this removes that flaw
in contrast to my comment in #15911 `ztimer/convert_muldiv64.c` and `ztimer/convert_shift.c` do not need modification since they call the init of `ztimer/convert.c` 
this add setting convert clocks to require no pm (the base clock should have the pm blocking setup correctly)
have hardware that operates with pm_mode 0 active, check the power consumption while you expect it sleeping, check if it wakes up when required. 
i don't have such a …
> sys/ztimer: convert clock do not require pm

- sys/net/application_layer/emcute/emcute.c
- tests/emcute/README.md
- tests/emcute/tests-as-root/01-run.py
This is a bug fix for emcute. Without it, emcute rejects incoming PUBLISH messages that have the RETAIN flag set (when the client subscribes to a topic for which a retained message is present). I don't see any reason to do this.
I added some test cases to the existing test suite that send PUBLISH messages with the RETAIN flag set to the RIOT node, and ran them with:
`BOARD=native make -C tests/emcute flash test-as-root`
Without my change in emcute, they fail:
```
Run test case
{'data_len_end': 503,
'data_len_start': 0,
'data_len_step': 50,
'mode': 'sub',
'qos_level': 0,
'retain': True,
'topic_name': '/test'}
Timeout in expect script at "self.spawn.expect_exact(" (tests/emcute/tests-as-root/01-run.py:246)
```
(Side note: tests/emcute/README.md says to run the tests with `make test`, which …
> net/emcute: Allow RETAIN flag to be set on incoming PUBLISHs

- examples/lorawan/main.c
If `sx126x` is used the device descriptor is missing.
A compile test should be enough (didn't test more myself since I have other issues with the hardware).
> examples/lorawan: add missing sx126x descriptor

- cpu/nrf52/radio/nrf802154/nrf802154.c
- drivers/include/net/netdev/ieee802154.h
- sys/include/net/ieee802154.h
- sys/net/link_layer/ieee802154/ieee802154.c
- tests/unittests/tests-ieee802154/tests-ieee802154.c
This PR migrates `netdev_ieee802154_dst_filter` to `ieee802154_dst_filter`.
This not only makes it not dependent to netdev, but will help with Kconfig modelling since now `netdev_ieee802154` can be represented as a pure netdev layer. I will add a follow up PR that shows this in action.
`netdev_ieee802154_dst_filter` is marked as deprecated and will be removed after 2022.01.
Check that `examples/gnrc_networking` compiles for e.g `nrf52840dk` (with `USEMODULE=`nrf802154_netdev_legacy`) and confirm that pinging still works.
None so far
> ieee802154: migrate `netdev_ieee802154_dst_filter` to a common ieee802154

- sys/include/net/gnrc/netif/flags.h
- sys/include/net/gnrc/netif/ipv6.h
- sys/net/gnrc/network_layer/ipv6/nib/_nib-slaac.c
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
- sys/net/gnrc/network_layer/ipv6/nib/nib_pl.c
- sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
- tests/gnrc_sixlowpan_frag_minfwd/Makefile.ci
This PR is another spin-off from #16228. Its changes let the the `aac_mode` field of `gnrc_netif_ipv6_t` be treated as flag field.
The members of the `net_gnrc_netif_aac` enum are updated accordingly. This way, it is possible for a net interface to use (for instance) both SLAAC and DHCPv6 for auto-adress configuration.
As this is curently more or less a refactoring, you can use the existing `gnrc` and unit tests should which should still be passing.
> sys/net/gnrc/netif: Make aac_mode a flag field

- cpu/sam0_common/periph/i2c.c
When using the I2C_NOSTOP flag the bus should remain in control.
The current check assumes it must go to idle when reading.
This adds a condition checks if the nostop flag is active
and expects the bus status to be the owner of the bus.
Connect a driver to a sam* based i2c bus and run `tests/periph_i2c`
```
i2c_acquire 0
i2c_read_byte 0 <my_device_address> 4
```
On master this will lockup, with this PR it should give one byte back.  Please note that other reads that don't contain a `I2C_NOSTART` (0x08) may cause errors.
... or I can just post the result outputs.
This was an error on the [PHiLIP based HiL CI](https://hil.riot-os.org/results/nightly/latest/saml10-xpro/tests_periph_i2c/log#s1-s4-t1) for a long time, I finally have time to check it.
> cpu/sam0/i2c: Handle read with I2C_NOSTOP flag

- pkg/nimble/netif/include/nimble_netif_conn.h
- pkg/nimble/netif/nimble_netif.c
- pkg/nimble/netif/nimble_netif_conn.c
This is a bug fix for the changes introduced in #16372.
It turns out, that once a node maintains multiple connections, its state can break after a GAP-slave node rejects a new incoming connection by closing it in the `GAP` event callback: 
- the master node opens a GAP connection
- the slave node triggers the `_on_gap_slave_evt` callback, Here it did check the connection interval and initiated a connection teardown if the iinterval was not spaced sufficiently
- in the mean time, the master node did not know about the connection teardown, yet, and creates the L2CAP channel
- this leads to the `_on_l2cap_server_evt()` event callback being triggered on the slave, despite the fact that it already triggered the connection to be closed
--> the slave node ends up with broken state and hangs
This …
> pkg/nimble/netif: fix randomized conn intervals

- sys/shell/commands/sc_gnrc_icmpv6_echo.c
The `gnrc_icmpv6_echo` implementation directly used a thread_t field where it could use public API.
Previously, it was calling `cib_avail(thread_get_active()->msg_queue)`. `msg_avail()` adds an extra check, which is always true when there actually is a msg_queue, which the previous code assumes. Under that assumption, `msg_avail()` casted to unsigned is equivalent to the previous call.
> sys/shell/commands: gnrc_icmpv6_echo: use msg_avail()

- sys/include/net/netstats.h
`netstats.h` is using cib_t in (now) line 108 without including the header.
> netstats: add missing cib.h include

- tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c
- tests/unittests/tests-ipv6_addr/tests-ipv6_addr.c
prevents gcc-11 error:
```
In file included from /home/kaspar/src/riot/sys/include/embUnit/embUnit.h:47,
from /home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:17:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c: In function ‘test_ipv4_addr_to_str__result_NULL’:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:59:22: error: ‘a’ may be used uninitialized [-Werror=maybe-uninitialized]
59 |     TEST_ASSERT_NULL(ipv4_addr_to_str(NULL, &a, IPV4_ADDR_MAX_STR_LEN));
/home/kaspar/src/riot/sys/include/embUnit/AssertImpl.h:70:47: note: in definition of macro ‘TEST_ASSERT_NULL’
70 |         __typeof__(pointer_) ____pointer__ = (pointer_); \
|                                               ^~~~~~~~
In file included from …
```
> unittests/tests-ipv?_addr: fix some uninitialized variable bugs

- tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c
- tests/unittests/tests-ipv6_addr/tests-ipv6_addr.c
prevents gcc-11 error:
```
In file included from /home/kaspar/src/riot/sys/include/embUnit/embUnit.h:47,
from /home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:17:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c: In function ‘test_ipv4_addr_to_str__result_NULL’:
/home/kaspar/src/riot/tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c:59:22: error: ‘a’ may be used uninitialized [-Werror=maybe-uninitialized]
59 |     TEST_ASSERT_NULL(ipv4_addr_to_str(NULL, &a, IPV4_ADDR_MAX_STR_LEN));
/home/kaspar/src/riot/sys/include/embUnit/AssertImpl.h:70:47: note: in definition of macro ‘TEST_ASSERT_NULL’
70 |         __typeof__(pointer_) ____pointer__ = (pointer_); \
|                                               ^~~~~~~~
In file included from …
```
> unittests/tests-ipv?_addr: fix some uninitialized variable bugs [backport 2021.07]

- examples/blinky/Makefile
- examples/blinky/Makefile.board.dep
- examples/blinky/README.md
- examples/blinky/main.c
This adds a dedicated `blinky` application that blinks and LED with a 2 second period. If no LED is configured (no `LED0_TOGGLE` macro defined in `board.h`), it will print `Blink!` instead via stdio.
For delay, `ztimer` is used when `periph_timer` is provided by the board. If this is not the case, a simple delay loop is used instead. `ztimer` is used over `xtimer` here as it is more widely applicable (e.g. xtimer has strict frequency requirements) and the fallback loop is provided in case no hardware timer is supported yet.
```
make BOARD=SOME_BOARD_WITH_AT_LEAST_ONE_LED -C examples/hello_world flash term
```
Above you can see this example running on a work-in-progress port of RIOT to the Raspberry Pi Pico.
None
> examples/blinky: new application

- pkg/tinydtls/contrib/sock_dtls.c
- sys/include/net/sock/dtls.h
Right now `sock_dtls_session_destroy()` does not do all the time what the API states.
https://github.com/RIOT-OS/RIOT/blob/08f1f9768d23bd934d4707a37d19744e7279a598/sys/include/net/sock/dtls.h#L699
The sock implementation for tinyDTLS only initiates closing of a session, which results in sending a `close_notify`. But when the remote peer never ACK's the closing (e.g. not receiving or not answering), the session slot is blocked until device reboot. TinyDTLS endlessly stays in a `STATE_CLOSING` session state for that peer and there is no way of resetting a peer with the current DTLS sock API. 
The main problem is that `sock_dtls_session_destroy()` does not allow a return value for feedback. This is easily fixable...but currently it is not possible to get the success of the session closing …
> pkg/tinydtls: handling of close_notify

- tests/unittests/tests-ipv6_hdr/tests-ipv6_hdr.c
Fixes some array bounds warnings:
```
In file included from tests/unittests/tests-ipv6_hdr/tests-ipv6_hdr.c:21:                                                                          
tests/unittests/tests-ipv6_hdr/tests-ipv6_hdr.c: In function ‘test_ipv6_hdr_set_version’:                                                          
./sys/include/net/ipv6/hdr.h:104:24: error: array subscript ‘ipv6_hdr_t[0]’ is partly outside array bounds of ‘uint8_t[1]’ {aka ‘unsigned char[1]’}
[-Werror=array-bounds]                                                  
104 |     hdr->v_tc_fl.u8[0] |= 0x60;                                                                                                            
|     ~~~~~~~~~~~~~~~~~~~^~~~~~~ …
```
> tests/unittests/tests-ipv6_hdr: fix too short ipv6_hdr_t allocations

- drivers/sx126x/sx126x_netdev.c
This commit fixes the send function of sx126x. The loop that reads the
iolist was not considering the offset. Therefore each iolist snippet was
being written into the first position.
The loop was also setting the payload length to the size of the iolist
snippet. Then the payload was also wrong.
With this commit an iolist is copied sequentially into the framebuffer
and the payload length is set to `iolist_size`.
EDIT: This PR also fixes the return value of `_recv`. According to the `netdev_driver_t` API, the `recv` function must return the number of read bytes. The current version in master was returning 0. This was causing issues in GNRC LoRaWAN.
- Trigger a Join Request using GNRC LoRaWAN. Neither `tests/driver_sx126x` nor Semtech LoRaMAC use an iolist with more than one snippet, so they …
> drivers/sx126x: fix netdev send and recv function

- drivers/include/sx127x.h
- drivers/sx127x/sx127x_getset.c
- drivers/sx127x/sx127x_netdev.c
- pkg/semtech-loramac/contrib/semtech_loramac_radio.c
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
- tests/driver_sx127x/main.c
The definition of NETOPT_RX_SYMBOL_TIMEOUT [states](https://doc.riot-os.org/group__net__netopt.html#gga19e30424c1ab107c9c84dc0cb29d9906aadd8dd23500923fd80a3f5e4c452fdfa) that the size should be `uint8_t` instead of `uint16_t`.
The documentation makes sense IMO:
- The rx symbol timeout register is 1 byte in SX127x
- Larger values are not suitable for common applications such as LoRaWAN.
It's guaranteed that GNRC LoRaWAN won't pick a value greater than UINT8_MAX. Although it's defined as `uint16_t` in semtech loramac, in practice this value won't be bigger than UINT8_MAX neither because it depends on the configuration values. A proof of that is the fact sx127x runs with semtech-loramac.
I just added an assertion to the pkg just in the rare case this changes in future semtech-loramac …
> netdev/lora: fix size of NETOPT_RX_SYMBOL_TIMEOUT

- drivers/cc110x/cc110x.c
- drivers/cc110x/cc110x_communication.c
- drivers/cc110x/cc110x_netdev.c
- drivers/cc110x/include/cc110x_communication.h
- drivers/cc110x/include/cc110x_constants.h
- drivers/include/cc110x.h
- tests/driver_cc110x/main.c
- tests/driver_cc110x/sc_cc110x.c
Add `cc110x_sleep()` and `cc110x_wakeup()` to allow low power operation for the CC110x transceivers.
The test in `tests/driver_cc110x` has been extended to also contain the `sleep` and `wakeup` shell commands.
I used a MIoT-Lab Testbed Node (a Nucleo-F767ZI which contains among others a CC1101 transceiver and a 6 channel power monitoring solution, of which one channel is monitoring the CC1101) for testing.
```
2021-03-25 12:50:51,778 # main(): This is RIOT! (Version: 2021.04-devel-1144gNETOPT_RX_END_IRQ not implemented by driver
2021-03-25 12:50:51,782 # NETOPT_TX_END_IRQ not implemented by driver
2021-03-25 12:50:51,784 # ec756-drivers/cc110x)
2021-03-25 12:50:51,786 # cc110x driver test application
2021-03-25 12:50:51,789 # ==============================
2021-03-25 12:50:51,789 # …
```
> drivers/cc110x: add power off (sleep) functions

- drivers/include/sx126x.h
- drivers/sx126x/Kconfig
- drivers/sx126x/include/sx126x_internal.h
- drivers/sx126x/include/sx126x_params.h
- drivers/sx126x/sx126x.c
- drivers/sx126x/sx126x_netdev.c
- tests/driver_sx126x/app.config.test
This PR adds support for multiple simultaneous sx126x variants running in the same binary, while at the same time keeping all compile time optimizations.
This idea can be used as a base for #16579, in which a periph version of the driver and an external might be used at the same time.
This PR reduces already ~12 bytes for sx1261 because the compile is not always able to put the pa_cfg structure in ROM (see https://github.com/RIOT-OS/RIOT/commit/f635a102f62cec0408cfb0b579b4e7414dad6fec). After the last commit, this remains unchanged.
The easiest way to test it is to select the corresponding driver version in periph_conf.h and compile it with an extra module. E.g
```
USEMODULE="sx1261 llcc68" make flash term
```
And make sure everything works.
#16579
> sx126x: add support for multiple simultaneous variants

- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
This PR fixes an issue introduced by #16080, in which the wrong pktsnip is released on TX errors.
I removed the `head` variable and asserted "payload" just to avoid this kind of mistakes in the future.
It's quite hard to test LoRAWAN right now if we don't have working setups with TTN, but I have a running instance of Chirpstack. I will post results ASAP.
If the transmissions fails (e.g the node didn't join), there's an assertion on master:
```
2021-07-06 13:59:26,331 # txtsnd 3 02 test
2021-07-06 13:59:26,338 # sys/net/gnrc/pktbuf/gnrc_pktbuf.c:94 => 0x8000165
2021-07-06 13:59:26,340 # *** RIOT kernel panic:
2021-07-06 13:59:26,341 # FAILED ASSERTION.
```
With this PR:
```
2021-07-06 14:28:20,569 # reboot
2021-07-06 14:28:20,613 # NETOPT_RX_END_IRQ not implemented by driver
2021-07-06 …
```
> gnrc_lorawan: fix gnrc_pktbuf_release_error (introduced by #16080)

- drivers/include/sx127x.h
- drivers/sx127x/sx127x_getset.c
- drivers/sx127x/sx127x_netdev.c
- pkg/semtech-loramac/contrib/semtech_loramac_radio.c
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
- tests/driver_sx127x/main.c
Backport of #16604
From #16604
> netdev/lora: fix size of NETOPT_RX_SYMBOL_TIMEOUT [backport 2021.07]

- drivers/at24cxxx/include/at24cxxx_params.h
Hello everyone. 
This PR is related to issue #16589 (sorry it took so long). It fixes the compilation error in C++ of drivers/include/at24cxxx_params.h 
Members of at24cxxx_params were not initialized in the right order. 
Compile the driver.
> drivers/at24cxxx: rearrange AT24CXXX_PARAMS

- drivers/dose/dose.c
If there was a collision, return -EBUSY so the frame can be put into the packet queue and we can attempt to send it again.
Add `USEMODULE += gnrc_netif_pktq` to your project and see if the packet loss goes down if you are sending lots of packets on a busy link.
> drivers/dose: return -EBUSY if medium is busy

- pkg/nimble/Makefile.include
NimBLE offers the option to configure a minimum slotsize that is used when scheduling connection events. I means that a minimum of `SLOT_SIZE * 1,25ms` slot will be reserved for every connection event in the controller, even if the event itself will take less time. The default value for NimBLE is `4`, making the controller block a 5ms for every connection event. Now when running multiple connections in parallel, the connection events will more likely overloap and be skipped, the larger this slot size is. Setting this value to its minimum value of `1` does greatly improve link layer performance for multi-hop (multiple connections per node) scenarios:
The impacts on the link layer are quite drastic, below plotted is the link layer packet delivery radio (PDR) for two runs of the same …
> pkg/nimble: configure BLE_LL_INIT_SLOT_SIZE to 1

- fuzzing/gnrc_tcp/main.c
- sys/include/net/gnrc/tcp.h
- sys/include/net/gnrc/tcp/tcb.h
- sys/include/net/tcp.h
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp_eventloop.c
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c
- sys/net/gnrc/transport_layer/tcp/include/gnrc_tcp_common.h
- tests/gnrc_tcp/README.md
- tests/gnrc_tcp/main.c
- tests/gnrc_tcp/tests-as-root/01-conn_lifecycle_as_client.py
- tests/gnrc_tcp/tests-as-root/02-conn_lifecycle_as_server.py
- tests/gnrc_tcp/tests-as-root/03-send_data.py
- tests/gnrc_tcp/tests-as-root/04-receive_data.py
- tests/gnrc_tcp/tests-as-root/05-garbage-pkts.py
- tests/gnrc_tcp/tests-as-root/06-receive_data_closed_conn.py
- tests/gnrc_tcp/tests-as-root/07-endpoint_construction.py
- tests/gnrc_tcp/tests-as-root/08-return_codes.py
- tests/gnrc_tcp/tests-as-root/09-listen_accept_cycle.py
- tests/gnrc_tcp/tests-as-root/shared_func.py
This PR rewrites the passive connection establishment mechanism of GNRC_TCP.
The new version aligns the GNRC_TCP interface with the SOCK_TCP interface with the goal to make a upcoming SOCK integration straight forward and trivial.
Since this is a large change, I've split the PR into three commits (api, implementation and tests) to help reviewing this.
The new tests are written in different style than existing tests, please ignore the difference in style for now, I plan to align the existing  test structure in a dedicated PR on after merging this. 
This PR is covered by the GNRC_TCP test suite.
To test this PR follow the instructions under tests/gnrc_tcp/Readme.md
Fixes #10664 - TCP Sockets can not be used / built
> gnrc_tcp: rewrite passive open

- cpu/stm32/periph/spi.c
This PR address issue first discovered in #16579 .  STM32WL55JC use a memory mapped SPI interface instead of a GPIO. The change would init the `pins` only if it's not `GPIO_UNDEF`
Tested using #16579. Works!
#16579
> stm32/spi : Add check for GPIO_UNDEF

- drivers/include/sx126x.h
- drivers/sx126x/sx126x.c
- drivers/sx126x/sx126x_netdev.c
This PR  adds `NETOPT_RX_SYMBOL_TIMEOUT` which is required by the sx126x radio and also removes `NETOPT_RX_TIMEOUT` which is no longer required. The PR has been made as per discussions in thread #16579 , which  would integrate a `periph` version of `sx1261` radio driver used in STMWL55JC SoC.
Forced Radio Rx timeout timer to stop on preamble detection, else it breaks the current stack.
The changes were already tested in #16579 using `Nucleo-WL55JC` and logs can be found in its description.
#16579
Depends on #16604
> drivers/sx126x : r/NETOPT_RX_TIMEOUT/NETOPT_RX_SYMBOL_TIMEOUT

- drivers/sx127x/Makefile.dep
- sys/Makefile.dep
This commit fixes the dependency resolution of `gnrc_netif_cmd_lora`.
As it was, this module was pulled by the driver if `gnrc` was used.
Besides pulling an extra dependency in applications that don't use
`shell_commands` or `gnrc_lorawan`, this hardcodes the module
resolution in the drivers.
This commit pulls `gnrc_netif_cmd_lora` if `shell_commands` and
`gnrc_lorawan` are present.
Check that `gnrc_netif_cmd_lora` is pulled when using `examples/gnrc_lorawan`. (`make info-modules`)
None so far
> shell_commands/gnrc_netif: fix gnrc_netif_cmd_lora dependency

- sys/auto_init/auto_init.c
While looking at `fortuna` I realized it makes a call to `xtimer_now64` before the module is initialized, and I started wondering if it did not make more sense to initialize timers before `random`, unless someone is aware of a dependency between in the other direction.
- Murdock, run tests on multiple BOARDS to be safe
> sys/auto_init: init ztimer/xtimer before random

- examples/wakaama/Makefile
- pkg/wakaama/Makefile.dep
- pkg/wakaama/contrib/lwm2m_client_connection.c
- pkg/wakaama/contrib/lwm2m_client_objects.c
- pkg/wakaama/contrib/objects/Makefile
- pkg/wakaama/contrib/objects/common.c
- pkg/wakaama/include/lwm2m_client.h
- pkg/wakaama/include/lwm2m_client_config.h
- pkg/wakaama/include/objects/common.h
This adds generic get/set functions to interact with resources of the LwM2M client. Also, the client connection code is refactored to use these functions and the URI parser module.
The `examples/wakaama` application should work as usual.
None
> pkg/wakaama: add get set functions and cleanup client connection

- pkg/lwip/contrib/lwip.c
- pkg/lwip/patches/0003-netif_is_flag_set-fix.patch
Fix spelling error (nefif -> netif) in `netif_is_flag_set` macro. This did not cause compilation failures
as long as there is a variable called netif in scope - but in that case it did not check the flags on the correct interface. This fix comes from [lwIP upstream](https://git.savannah.nongnu.org/cgit/lwip.git/commit/?id=7a2923020f3686b030d38c3e604b1f3801ca2e43).
Also start DHCP on the interface that was checked, not the first one in the array.
Compilation of application using lwIP and IPv4 still works. \
DHCP now starts properly on all interfaces and not only the first one:
Before:
```
> ifconfig
Iface ET0 HWaddr: 24:0a:c4:e6:0e:9f Link: up State: up
inet addr: 10.4.4.81 mask: 255.255.254.0 gw: 10.4.4.1
Iface ET1 HWaddr: 24:0a:c4:e6:0e:9c Link: up State: up
Link type: …
```
> pkg/lwip: Fix DHCP autostart

- sys/include/net/gnrc/tcp.h
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c
- tests/gnrc_tcp/main.c
- tests/gnrc_tcp/tests-as-root/01-run.py
- tests/gnrc_tcp/tests-as-root/helpers.py
This PR implements all missing functions and API changes for SOCK_TCP integration to GNRC_TCP. 
All new functions and return codes are tested within the GNRC_TCP suite.
Just execute the tests under tests/gnrc_tcp
Depends on PR #16459
Depends on PR #16461
Fixes #10664 - TCP Sockets can not be used / built
> gnrc_tcp: align with sock tcp

- cpu/esp_common/Makefile.include
- cpu/esp_common/syscalls.c
This fixes an issue that prevents ESP8266 from booting.
```
make BOARD=esp8266-esp-12x flash test BUILD_IN_DOCKER=1 -C tests/malloc_thread_safety
[...]
READY
s
START
main(): This is RIOT! (Version: 2021.10-devel-139-ga53e1)
Test Application for multithreaded use of malloc()
==================================================
This test will run duelling threads allocating and freeing memory.
The running thread is interrupted every millisecond and the other
threads gets scheduled. Eventually, this should yield to memory
corruption unless proper guards are in place preventing them. After
ca. two seconds without crash, the test is considered as passing.
Testing: malloc()/free()
Testing: realloc()/free()
TEST PASSED
```
Bug introduced in …
> cpu/esp_common: fix boot issue on ESP8266

- cpu/esp_common/Makefile.include
- cpu/esp_common/syscalls.c
This fixes an issue that prevents ESP8266 from booting.
For both an ESP32 and an ESP8266 run:
```
make BOARD=esp8266-esp-12x flash test BUILD_IN_DOCKER=1 -C tests/malloc_thread_safety
[...]
READY
s
START
main(): This is RIOT! (Version: 2021.10-devel-139-ga53e1)
Test Application for multithreaded use of malloc()
==================================================
This test will run duelling threads allocating and freeing memory.
The running thread is interrupted every millisecond and the other
threads gets scheduled. Eventually, this should yield to memory
corruption unless proper guards are in place preventing them. After
ca. two seconds without crash, the test is considered as passing.
Testing: malloc()/free()
Testing: realloc()/free()
TEST PASSED
```
and (more …
> cpu/esp_common: fix boot issue on ESP8266 [backport 2021.07]

- sys/net/gnrc/sock/include/gnrc_sock_internal.h
Found this while testing https://github.com/RIOT-OS/RIOT/pull/16606: When using the `gnrc_netif_single` optimization module `gnrc_sock` basically accepts any `netif` value in the `gnrc_sock*_ep_t` structs, as it is just overwritten with the ID only existing network interface. While this seems like a nice extra from a shell user perspective, I wouldn't call this behavior valid and it also might cause some faulty behavior if e.g. invalid interface IDs are received from the network (as might be the case with DHCPv6's [Interface ID option]() https://github.com/RIOT-OS/RIOT/pull/16606).
The following tests should still pass:
- `tests/gnrc_sock_udp`
- `tests/gnrc_sock_ip`
None
> gnrc_sock: imply end-point netif only if unset

- sys/net/gnrc/sock/include/gnrc_sock_internal.h
Found this while testing https://github.com/RIOT-OS/RIOT/pull/16606: When using the `gnrc_netif_single` optimization module `gnrc_sock` basically accepts any `netif` value in the `gnrc_sock*_ep_t` structs, as it is just overwritten with the ID only existing network interface. While this seems like a nice extra from a shell user perspective, I wouldn't call this behavior valid and it also might cause some faulty behavior if e.g. invalid interface IDs are received from the network (as might be the case with DHCPv6's [Interface ID option]() https://github.com/RIOT-OS/RIOT/pull/16606).
The following tests should still pass:
- `tests/gnrc_sock_udp`
- `tests/gnrc_sock_ip`
None
> gnrc_sock: imply end-point netif only if unset [backport 2021.07]

- drivers/include/sx126x.h
- drivers/include/sx127x.h
- drivers/sx126x/sx126x_netdev.c
- drivers/sx127x/sx127x_getset.c
- drivers/sx127x/sx127x_netdev.c
- pkg/semtech-loramac/contrib/semtech_loramac_radio.c
- sys/include/net/netopt.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
- tests/driver_sx127x/main.c
It turns out the SX127x DOES support 2 bytes symbol timeout. Therefore, #16604 makes no sense at all and the correct solution would be to change the NETOPT_RX_SYMBOL_TIMEOUT documentation to use `uint16_t` instead of `uint8_t`.
The worst thing is, #16604 also introduced a bug because the MSB was being written as the LSB. I guess I owe some beers...
This PR reverts such a disgrace and fixes the NETOPT documentation.
The Release tests are not enough to catch this bug. We should work on that.
The proper way to detect this bug is to follow a similar approach to https://github.com/RIOT-OS/RIOT/pull/16599#issuecomment-876300546.
I can provide a patch and test results.
#16604
> net/lorawan: Revert #16604 and fix NETOPT_RX_SYMBOL_TIMEOUT documentation

- tests/periph_uart_mode/Makefile
- tests/periph_uart_mode/Makefile.board.dep
- tests/periph_uart_mode/main.c
Use `xtimer` only optionally (when `periph_timer`is available) for the test. This makes this test applicable to freshly ported boards that do not yet have a peripheral timer driver.
1. Binaries shouldn't change for any upstream board (they all have a timer available)
2. It should still compile when the `periph_timer` feature is disabled via `export FEATURES_BLACKLIST=periph_timer` and work with an approximate timeout between test data from the UART instead of the precise one.
Used to test https://github.com/RIOT-OS/RIOT/pull/16609
> tests/periph_uart_mode: Drop dep to periph_timer

- drivers/include/sx127x.h
- drivers/sx127x/sx127x_getset.c
- drivers/sx127x/sx127x_netdev.c
- pkg/semtech-loramac/contrib/semtech_loramac_radio.c
- sys/include/net/netopt.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
- tests/driver_sx127x/main.c
Backport of #16640 .
This backport is not a copy of #16640:
- There's no support for NETOPT_RX_SYMBOL_TIMEOUT for the sx126x in the 2021.07 release branch. That feature was merged after feature freeze.
- #16577 was merged after HFF. Therefore https://github.com/RIOT-OS/RIOT/commit/50c0002540aa9f65aef812d38ddb4004322a80c8 was adapted accordingly.
Same as #16640 .
#16640 .
> net/lorawan: Revert #16604 and fix NETOPT_RX_SYMBOL_TIMEOUT documentation [backport 2021.07]

- boards/nucleo-wl55jc/include/board.h
This PR set the SX126X_PARAM_TYPE in `boards/nucleo-wl55jc` to `SX126X_TYPE_STM32WL`, in order to reflect the correct board when more than one SX126x is being used (see #16597).
As is it, it compiles with the default value (`SX126X_TYPE_SX1261`). This makes LoRaWAN applications running on `nucleo-wl55jc` crash if the default settings are used.
Pull more `sx126x` variants and make sure `nucleo-wl55jc` runs as expected.
Test results for `examples/gnrc_lorawan/> BOARD=nucleo-wl55jc USEMODULE="sx1262 sx1262 llcc68" PORT=/dev/ttyACM2 SHOULD_RUN_KCONFIG=y make flash term`:
```
help
2021-07-14 14:06:31,262 # help
2021-07-14 14:06:31,265 # Command              Description
2021-07-14 14:06:31,268 # ---------------------------------------
2021-07-14 14:06:31,272 # reboot               Reboot the …
```
> boards/nucleo-wl55jc: add SX126X_PARAM_TYPE to board.h

- pkg/lwip/contrib/sock/ip/lwip_sock_ip.c
- pkg/lwip/contrib/sock/lwip_sock.c
- pkg/lwip/contrib/sys_arch.c
- pkg/lwip/include/arch/sys_arch.h
- pkg/lwip/include/lwipopts.h
When `DEVELHELP` is enabled, add checks that unprotected lwip functions are called correctly:
* Not be called from interrupts.
* If called from outside the tcpip thread, the lock must be held
The check is a macro to preserve the file/line of where it fired, to simplify debugging.
Adds locking to some calls in sock implementation to make it safe. \
Having this enabled will make it harder to add new unsafe code.
Netif handling has already been made safe in the switch to `netifapi` functions for dhcp and netif link up/down.
All lwip tests still work.
When calling `dhcp_start` instead of netifapi version in pkg/lwip/contrib/lwip.c, the following failure occurs (when IPv4 enabled) on native: \
`Assertion "Core lock held" failed at [...]/RIOT/build/pkg/lwip/src/core/ipv4/dhcp.c:742`
Sending …
> pkg/lwip: Add thread safety check when using DEVELHELP

- sys/include/net/gnrc/dhcpv6/client/simple_pd.h
- sys/net/gnrc/application_layer/dhcpv6/client_simple_pd.c
In https://github.com/RIOT-OS/RIOT/pull/16530 the module to bootstrap prefix delegation on border routers was renamed, but some of the rename is not reflected in the documentation and some of the function names, making both code and documentation somewhat confusing to read, if you do not know the history.
Everything should still compile and the doc should now show `simple_pd` instead of `6lbr` wherever it applies.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/16530
> gnrc_dhcpv6_client_simple_pd: fix old doc and names

- drivers/dfplayer/include/dfplayer_constants.h
- drivers/dfplayer/include/dfplayer_params.h
- Fix unbalanced groups
- Add missing doc
- Fix C++ `extern "C" { ... }` boilerplate
- `make doc` should no longer complain about the DFPlayer code
- the issue with C++ shouldn't trigger anyway, as the header is internal to the C-only implementation. But it won't hurt to fix it anyway.
None
> drivers/dfplayer: fix doc & C++ boilerplate

- makefiles/pseudomodules.inc.mk
- sys/include/net/dhcpv6/client.h
- sys/net/application_layer/dhcpv6/client.c
- sys/net/gnrc/Makefile.dep
- tests/gnrc_dhcpv6_client/Makefile
Prefix delegation used to be the only supported feature of our DHCPv6 client, but by now it also supports MUD, DNS recursive name servers and IA_NA is on the horizon. So it makes sense to make IA_PD an optional module like all those other features are as well.
Binary sizes of the `tests/gnrc_dhcpv6_*` test applications as well as the border router with `USE_DHCPV6=1` should stay the same with and without this fix (build with `RIOT_CI_BUILD=1`).
When removing the line
https://github.com/RIOT-OS/RIOT/blob/233249eae0e96c36ad6d34e1806a0679d6393ced/tests/gnrc_dhcpv6_client/Makefile#L11
the build size should decrease drastically. The test will fail (since it checks for working prefix delegation), but it should not crash during the run. Additionally, one may check if the proper DHCPv6 handshake …
> dhcpv6_client: make IA_PD an optional module

- boards/lora-e5-dev/Kconfig
- boards/lora-e5-dev/Makefile
- boards/lora-e5-dev/Makefile.dep
- boards/lora-e5-dev/Makefile.features
- boards/lora-e5-dev/Makefile.include
- boards/lora-e5-dev/board.c
- boards/lora-e5-dev/dist/openocd.cfg
- boards/lora-e5-dev/doc.txt
- boards/lora-e5-dev/include/board.h
- boards/lora-e5-dev/include/gpio_params.h
- boards/lora-e5-dev/include/periph_conf.h
- boards/nucleo-wl55jc/include/periph_conf.h
- cpu/stm32/Makefile.include
- cpu/stm32/cpu_init.c
- cpu/stm32/include/periph/wl/periph_cpu.h
- cpu/stm32/periph/flashpage.c
- cpu/stm32/stm32_info.mk
- cpu/stm32/stm32_mem_lengths.mk
- drivers/periph_common/flashpage.c
- tests/unittests/Makefile.ci
This PR adds support for [LoRa-E5 Development Board](https://www.google.com/search?channel=fs&client=ubuntu&q=seedstudio+lora-e5). 
Missing form this PR:
There seems to be an issue with I2C but I experienced the same issue with `nucleo-wl55jc`, so I think its unrelated to this PR and I'm confident on the pin mapping, so I kept the support. Maybe @MrKevinWeiss can use HIL to verify that `stm32wl` i2c is not broken?
Tested main functionalities:
- spi ( bme280_spi)
```
2021-07-20 13:46:27,385 # main(): This is RIOT! (Version: 2021.10-devel-170-g05efb-wip/lora_e5)
2021-07-20 13:46:27,386 # BMX280 test application
2021-07-20 13:46:27,386 #
2021-07-20 13:46:27,393 # +------------Initializing------------+
2021-07-20 13:46:27,393 # Initialization successful
2021-07-20 13:46:27,394 #
2021-07-20 …
```
> boards/lora-e5-dev: initial support

- examples/nimble_gatt/Makefile
- examples/nimble_gatt/main.c
- examples/nimble_heart_rate_sensor/Makefile
- examples/nimble_heart_rate_sensor/main.c
This PR modifies the example applications `nimble_gatt` and `nimble_heart_rate_sensor` such that they use the new automated advertising module, provided by PR #13425
This PR is rebased on top of PR #13425, so you only have to build and test the applications mentioned above.
> examples/nimble_*: use nimble_autoadv module

- sys/event/timeout.c
- tests/event_ztimer/main.c
Currently, `event_timeout_clear()` crashes when used with `ztimer` and when the timeout is uninitialized. This isn't the same behavior as with `xtimer`. As such, check the clock variable (which when set to `NULL` causes the crash) before clearing the timer.
`tests/event` should pass. When the fix is reverted, it crashes.
None.
> event_timeout: check clock before removing ztimer on clear 

- sys/Makefile.dep
- sys/include/net/dhcpv6/client.h
- sys/include/timex.h
- sys/net/application_layer/dhcpv6/client.c
Not sure, why I did not do that in the first place (maybe `event_timeout` did not exist back then, I seemed to basically have mirrored its behavior). As an added bonus, this makes the migration to `ztimer` really easy, which I also did in this PR.
`make -C tests/gnrc_dhcpv6_client flash -j test` still passes, with and without `USEMODULE=ztimer`
~~Requires https://github.com/RIOT-OS/RIOT/pull/16667 for the test to pass with `ztimer`.~~ (merged)
#16661 conflicts with this PR, but IMHO #16661 should be merged first, to have the issue fixed in master.
> dhcpv6_client: refactor to use `event_timeout` for non-sock timeouts

- sys/net/netutils/util.c
The zone ID part in a host part is the name of the network interface (which by chance is the string representation of the ID with GNRC), not the ID.
`tests/netutils` should still pass.
Somehow slipped through the initial review. See https://github.com/RIOT-OS/RIOT/pull/16634#issuecomment-878475883.
> netutils: get interface by name rather than ID

- sys/include/net/nanocoap.h
This provides a convenience function to add an [Accept option](https://www.rfc-editor.org/rfc/rfc7252#section-5.10.4) to a CoAP message.
There are no specific tests for these type of functions, so I did not bother to add one either. The semantics are the same as for `coap_opt_add_format()`, which looks basically the same apart from the option type. So the procedure: read ;-).
None
> nanocoap: provide Accept option convenience function

- sys/net/application_layer/dhcpv6/client.c
- sys/net/gnrc/application_layer/dhcpv6/client.c
mrd calculation for dhcp-rebind and renew was wrong this fixes it
see issue  #16677
fixes mrd calculation
run the "tests/gnrc_dhcpv6_client" but to see the effect you have to put some extra prints too
```
--- a/sys/net/application_layer/dhcpv6/client.c
+++ b/sys/net/application_layer/dhcpv6/client.c
@@ -854,6 +854,7 @@ static void _request_renew_rebind(uint8_t type)
lease->parent.ia_id.info.netif,
&lease->pfx, lease->pfx_len
);
+                printf("valid_until %"PRIu32"\n",valid_until);
if (valid_until > mrd) {
mrd = valid_until;
}
@@ -887,6 +888,7 @@ static void _request_renew_rebind(uint8_t type)
msg_len += _add_ia_pd_from_config(&send_buf[msg_len], sizeof(send_buf) - msg_len);
_flush_stale_replies(&sock);
while (sock_udp_send(&sock, send_buf, msg_len, &remote) <= 0) {}
+ …
```
> dhcpv6_client: mrd calculation fixed

- cpu/rpx0xx/include/periph_cpu.h
The PR fixes some minor warnings which Murdock discovered in #16627
The tests which failed to compile now work as expected.
`tests/pkg_flatbuffers`
```
2021-07-27 15:21:33,626 # Connect to serial port /dev/ttyUSB0
s
2021-07-27 15:21:36,117 # START
2021-07-27 15:21:36,127 # main(): This is RIOT! (Version: 2021.10-devel-165-g0d740-cpu_rp2040_periph_timer)
2021-07-27 15:21:36,132 # The FlatBuffer was successfully created and verified!
```
`tests/periph_gpio`
```
2021-07-27 15:27:24,475 # auto_test 0 14 0 15
2021-07-27 15:27:24,475 # [START]
2021-07-27 15:27:24,482 # [SUCCESS]
```
#16627
> cpu/rpx0xx: fix minor gpio warnings

- sys/include/net/gcoap.h
- sys/net/application_layer/gcoap/gcoap.c
The `coap_socket_t` and `coap_socket_type_t` types are used by gCoAP only and the `coap_` prefix is usually used to namespace the `nanocoap` module's API. This makes it confusing to locate the types in question.
As these types were introduced in the current release cycle and those types are mostly used internally to `gcoap`, I do not think the usual deprecation process is required here.
`examples/gcoap` and `example/gcoap_dtls` should still compile and work.
```
$ git grep "\<coap_socket"
```
should yield no results.
None
> gcoap: fix socket type naming

- drivers/include/rtt_rtc.h
- drivers/rtt_rtc/rtt_rtc.c
- tests/unittests/Makefile.ci
- tests/unittests/tests-rtt_rtc/tests-rtt_rtc.c
The `rtt_rtc` module provided a RTC based on a RTT.
For some applications (e.g. NTP) it can be handy to set / get the epoch timestamp directly while still retaining the calendar alarm functionality.
This PR adds two functions `rtc_settimeofday()` and `rtc_gettimeofday()` to set/get the RTT timestamp with µs precision (rounded to the closest multiple of `1 /  RTT_FREQUENCY`).
The unit test in `unittests/tests-rtt_rtc` was extended to cover the new functionality.
> rtt_rtc: add rtt_rtc_settimeofday() & rtt_rtc_gettimeofday()

- sys/net/gnrc/network_layer/ipv6/nib/nib.c
When the default router was removed as it did send it's 'last RA' or could not be added, `dr` will be NULL.
In this case, don't cease sending router solicitations - we still don't have a default router.
> gnrc_ipv6_nib: don't stop sending router solicitations when receiving last router advertisement from router

- sys/include/net/gnrc/netif/internal.h
- sys/include/net/gnrc/rpl.h
- sys/include/net/gnrc/rpl/dodag.h
- sys/include/net/gnrc/sixlowpan/ctx.h
- sys/net/gnrc/application_layer/dhcpv6/client.c
- sys/net/gnrc/application_layer/uhcpc/gnrc_uhcpc.c
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/routing/rpl/gnrc_rpl.c
- sys/net/gnrc/routing/rpl/gnrc_rpl_dodag.c
Code from `dhcpv6_client_conf_prefix()` can be useful in other situations where we want to configure a prefix on an interface.
Move it to a common place and also use it for  uhcp.
`examples/gnrc_border_router` still gets a valid prefix
```
Iface  6  HWaddr: AE:8D:C2:75:23:DE 
L2-PDU:1500  MTU:1500  HL:64  RTR  
inet6 addr: fe80::ac8d:c2ff:fe75:23de  scope: link  VAL
inet6 addr: fe80::2  scope: link  VAL
inet6 group: ff02::1:ff75:23de
inet6 group: ff02::1:ff00:2
Iface  5  HWaddr: 49:05  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
Long HWaddr: 00:04:25:19:18:01:C9:05 
TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
AUTOACK  ACK_REQ  CSMA  L2-PDU:102  MTU:1280  HL:64  RTR  
RTR_ADV  6LO …
```
> gnrc_netif: add gnrc_netif_ipv6_add_prefix() & helper functions

- cpu/sam0_common/periph/uart.c
SERCOM5 on SAM L21 does not support fractional baud rate mode.
Instead of special-casing it, just use arithmetic baud rate mode in general on this CPU, as I'm not sure what the advantages of fractional baud rate mode are.
- configure SERCOM5 as UART on a board where the appropriate pins are exposed
- connect the uart to a different UART capable device
- run `tests/periph_uart`and try to communicate with different baud rates
fixes #16692
> cpu/saml21: uart: use arithmetic baud rate mode

- boards/saml21-xpro/include/periph_conf.h
This adds the missing configuration for I2C and UART on EXT2/3
connect RX to TX and MISO to MOSI and run `tests/periph_uart` and `tests/periph_spi` for the new instances.
> boards/saml21-xpro: configure UART & SPI on EXT2, 3

- pkg/wakaama/contrib/lwm2m_client_connection.c
- pkg/wakaama/contrib/objects/common.c
- pkg/wakaama/include/objects/common.h
#16203 introduced multiple convenience functions to access resources of different types. While string resources are `NULL` terminated, that's not the case for opaque ones. As the length is not always known beforehand, this fixes the API to return the amount of read bytes. As the APIs were not part of the last release, no need to deprecate the old ones.
Also `lwm2m_set_objlink_by_path` is fixed.
- `examples/wakaama` should work as usual
- The get/set functions should still work (can be tested by checking the resources in the application above)
> pkg/wakaama: fix object common `get` functions

- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/link_layer/lorawan/include/gnrc_lorawan_internal.h
- tests/gnrc_lorawan/Makefile
- tests/gnrc_lorawan/Makefile.ci
- tests/gnrc_lorawan/main.c
- tests/gnrc_lorawan/tests/01-run.py
This PR adds some initial ~unit~test for GNRC LoRaWAN  (EDIT: as suggested by @miri64 , they are now regular tests instead of unittests) . I plan to keep extending these tests in order to improve the overall coverage.
I also piggyback a dependency resolution fix that was discovered while working on the tests.
- `netdev_layered` is not used anymore
- `gnrc_lorawan` actually doesn't depend on any GNRC core module. This is important, because the tests needs to implement some callback functions that are already implemented in `gnrc_netif_lorawan`).
`make -C tests/gnrc_lorawan all test` should pass.
None so far.
> tests/gnrc_lorawan: add initial tests

- sys/include/uri_parser.h
- sys/uri_parser/uri_parser.c
- tests/unittests/tests-uri_parser/tests-uri_parser.c
This provides a function to `uri_parser` to split the query part of a given URI parsing result into its components.
`tests/unittests` were amended for the new function, so
```sh
make -C tests/unittests/ tests-uri_parser test
```
should succeed for a board of choice.
None.
> uri_parser: provide function to split query

- sys/include/usb/hid.h
- sys/include/usb/usbus/hid.h
- sys/include/usb/usbus/hid_io.h
- sys/usb/usbus/hid/hid.c
- sys/usb/usbus/hid/hid_io.c
- tests/usbus_hid/main.c
This PR adds a header file for `sys/usb/usbus/hid/hid.io.c` which was missing before. Furthermore it adds the possibility to add a RX callback function which will be called whenever data has been received from the USB HID endpoint. This is supposed to enable the usage of the `hid_io` interface in an async context (e.g. trigger an event when data has been received).
I have extended `test/usbus_hid` to also test the functionality of the RX callback function.
> usbus/hid_io: add missing header file, add RX callback function

- drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c
- sys/net/link_layer/ieee802154/submac.c
This PR does essentially 3 things:
- Move some of the initialization code of netdev_ieee802154_submac from `netdev_submac_ieee802154_init` to the actual `_init` function of `netdev_driver_t`. This is required in order to make sure the device is initialized before setting netdev stuff.
- Fix the default SubGHz page
- Call `confirm_set_trx_state` after setting the state to RX_ON during initialization. In some cases, the radio was not ready to do a state transition because `request_set_trx_state` didn't finish.
- Ensure hal dependent radios (cc2538, nrf52840) still work with `gnrc_networking` and `tests/ieee802154_hal`
None so far
> ieee802154/submac: fix initialization code

- sys/include/net/netif.h
- sys/net/netif/netif.c
- tests/gnrc_netif/main.c
This adds a function to `netif` that allows to search an interface by name, using a buffer and length (like the one provided by the [URI parser](http://doc.riot-os.org/group__sys__uri__parser.html)), instead a null-terminated string. `tests/gnrc_netif` has been extended accordingly.
`tests/gnrc_netif` should pass.
Split from #16233
> net/netif: add function to get interface by name from a buffer

- makefiles/libc/picolibc.mk
This is a regression which was introduced in #16114 (CC: @fjmolinas), without resetting
the color the red color will be used for all following text written to
the terminal and will also cause the shell prompt etc. pp. to be colored
in red which is undesirable. This commit fixes this regression by using
the ANSI escape sequences to reset the color after the error message has
been written.
> picolibc: Reset color in error message if picolibc is not available

- pkg/wakaama/contrib/lwm2m_client_connection.c
- sys/include/uri_parser.h
- sys/uri_parser/uri_parser.c
`uri_parser_process()` takes a `const char *` as input parameter but the result is a struct of `char *` to the original string.
This may lead a user to modifying the strings in `uri_parser_result_t` which will cause a crash if the original string resides in read-only memory (and violates the no-modifications promise of the const parameter in `uri_parser_process()`).
To fix this, make the resulting strings `const` as well, so nobody dares to touch them in a writing way.
make -C tests/unittests tests-uri_parser term
https://github.com/RIOT-OS/RIOT/pull/16695#discussion_r681820654
> uri_parser: constify result

- sys/include/net/gcoap.h
- sys/include/net/nanocoap.h
- sys/net/application_layer/gcoap/gcoap.c
When working with modules such as `uri_parser`, where the path is not necessarily `\0`-terminated, this change greatly simplifies working with these modules.
`examples/gcoap` should still be able to exchange messages, same for `tests/nanocoap_cli`.
None.
> nanocoap & gcoap: allow path to be non-`\0`-terminated.

- sys/include/net/gnrc/ipv6/nib/abr.h
- sys/include/net/gnrc/ipv6/nib/pl.h
`gnrc_ipv6_nib` provides for some of its view a time stamp until which an entry is valid. Since we now have multiple clocks that provide timestamps, getting the offset of the current time to said timestamp can be tricky, since it is not immediately clear what the timestamp was generated from. This aims to solve that by providing helper functions to the affected NIB views to calculate that offset for external use.
Did not bother to provide tests. The functions are simple enough so just read ;-).
Might be needed for #16536.
> gnrc_ipv6_nib: provide functions to get offset of public timestamps

- cpu/avr8_common/avr_libc_extra/posix_unistd.c
Add a minimal implementation of `strerror()`.
All other targets use either newlib or picolibc and provide this function, add it to AVR so we can rely on it in common code.
https://github.com/RIOT-OS/RIOT/pull/16494#discussion_r684194520
> avr_libc_extra: implement strerror()

- sys/net/gnrc/netif/gnrc_netif.c
Initialize `addr` with 0 first.
Otherwise if prefix is < 64 there will be random bits of stack memory in the bits of the address that are neither touched by `ipv6_addr_set_aiid()` nor `ipv6_addr_init_prefix()`.
I was wondering why I was randomly getting addresses like
inet6 addr: 2001:db8:0:e:dcdb:4fff:fe0c:523d  scope: global  VAL
with
2001:db8:0:c::/62 dev #7
This fixes it and the address configured with this prefix is now
inet6 addr: 2001:db8:0:c:dcdb:4fff:fe0c:523d  scope: global  VAL
as expected.
> gnrc_netif: properly initialize address in gnrc_netif_ipv6_add_prefix()

- README.md
After the HiL Link was removed from the Murdock CI it is probably good to expose it somewhere, thus the readme badge.
As there is still no clear result we have a static badge, it may change in the future to show passed vs failed tests (once we get the passed tests up.
I guess just read it and try the links...
> README.md: Expose HiL CI overview link

- cpu/cc2538/include/cc2538_rf.h
- cpu/cc2538/radio/cc2538_rf_radio_ops.c
This PR fixes a deadlock in `cc2538_rf` caused by frames being received too fast.
The reasons for this deadlock are:
1. While sending with CCA the RX chain should be disabled, which was not the case. When frames were received during CCA, there was a wrong state transition in the `submac` that ended with `submac->tx`  being not released. Therefore, the `submac` would always return `-EBUSY`.
2. The driver logic was always following the internal FSM states, although the Reference Manual (Section 23.11) explicitly says to not do that:
> Although it is possible to read the state of the FSM, do not use this information to control the program flow
in the application software
I was able to trigger cases were the FSM state was not defined but the radio was still fully functional. Therefore, I …
> drivers/cc2538_rf: fix deadlock when receiving too fast.

- sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.c
- sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
Consider the following: A node tries to forward a packet to another host for which it does not know the route yet. It assumes it to be on-link and starts a neighbor solicitation, putting the node address in the destination cache.
Later the route is known (via a second hop) but the host is still in the NIB.
The result is that `gnrc_ipv6_nib_get_next_hop_l2addr()` ends up in the [`"nib: %s is in NC or on-link, start address resolution"`](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L223) case and does not attempt to resolve the route.
This results in the host remaining unreachable even though now a route is present.
The fix should make sense since only neighbor cache entries are guaranteed to be on-link.
> gnrc/nib: gnrc_ipv6_nib_get_next_hop_l2addr(): only assume neighbor cache entries to always be on-link

- dist/pythonlibs/riotctrl_shell/gnrc.py
- sys/shell/commands/sc_gnrc_icmpv6_echo.c
The Linux ping utility has the nice feature that fills the ICMPv6 request payload with a pattern `payload_index & 0xFF`.
Then the ICMPv6 response payload is checked to verify that the pattern is still intact.
This way corrupted messages can be detected.
In the past that revealed some 6lo-fragmentation bugs in Linux when corrupted replies arrived.
This feature is also useful for RIOT, so implement it in RIOTs `ping` command.
`ping` should still work with varying lengths.
If packet corruption happened on the data path, this should now be reported.
> sys/shell/commands/gnrc_icmpv6_echo: test for ICMPv6 reply corruption

- makefiles/pseudomodules.inc.mk
- sys/include/net/dhcpv6.h
- sys/include/net/dhcpv6/client.h
- sys/include/net/gnrc/netif/conf.h
- sys/net/application_layer/dhcpv6/Kconfig
- sys/net/application_layer/dhcpv6/_dhcpv6.h
- sys/net/application_layer/dhcpv6/client.c
- sys/net/gnrc/application_layer/dhcpv6/client.c
- sys/net/gnrc/netif/Kconfig
- sys/net/gnrc/network_layer/ipv6/nib/_nib-slaac.c
- tests/gnrc_dhcpv6_client/Makefile
- tests/gnrc_dhcpv6_client/kea-dhcp6.conf
- tests/gnrc_dhcpv6_client/main.c
- tests/gnrc_dhcpv6_client/tests-as-root/01-run.py
This PR adds identity association for non-temporary addresses (IA_NA) to the DHCPv6  client and makes it possible to use the `auto_init_dhcpv6_client` module for auto configuring it.
While requesting a non-temporary address already works (see below), the implementation is probably not finished yet as I wasn't entirely sure how to correctly add the obtained address to the respective net interface and where to remove them if their lifetime passes. There also some other aspects which I wasn't quite sure about (the relevant lines on `IA_NA` in `_nib-slaac.c` for example) and code passages that probably need refactoring.
I would be very grateful to receive some feedback on this and hope that this PR is not too far away from a mergeable state.
You can use the provided test under …
> sys/net/dhcpv6: Add IA_NA support to the DHCPv6 client

- sys/include/net/dhcpv6/client.h
- sys/net/application_layer/dhcpv6/client.c
- sys/net/gnrc/application_layer/dhcpv6/client.c
- tests/gnrc_dhcpv6_client/tests-as-root/01-run.py
This PR is a follow-up to #16228 and removes introduced redundancy by re-using the already existing DHCPv6 prefix configuration functions.
You can use the existing test under `tests/gnrc_dhcpv6_client` to assert that the implementation is still working.
Depends on #16228
> sys/net/dhcpv6: Refactor IA_NA implementation

- sys/include/net/nanocoap.h
- sys/net/application_layer/nanocoap/nanocoap.c
From a client-side when performing a POST it can be useful to know when the complete message has been transmitted. Since when using BLOCK payloads are relatively large if the resource is dynamic then upon sending out the last block then the resource can be freed checking the return status of `coap_block%_finish` can be a way of getting this information, so this PR has `coap_block_finish` return the value of the `more` field.
- Murdock: Everything should still be green
- Release tests regarding block transactions still pass
```
tox -- -k "spec09 and (task03 or task04)" --non-RC
test installed: aiocoap==0.4.1,attrs==21.2.0,beautifulsoup4==4.9.3,certifi==2021.5.30,cffi==1.14.6,charset-normalizer==2.0.4,coverage==5.5,Deprecated==1.2.12,idna==3.2,iniconfig==1.1.1,iotlabcli==3.2.1,jmespath==0.10 …
```
> sys/net/nanocoap: block_finish returns if more are expected

- drivers/nrf24l01p_ng/gnrc_netif_nrf24l01p_ng.c
- drivers/nrf24l01p_ng/nrf24l01p_ng.c
- drivers/nrf24l01p_ng/nrf24l01p_ng_communication.c
- drivers/nrf24l01p_ng/nrf24l01p_ng_netdev.c
- drivers/nrf24l01p_ng/nrf24l01p_ng_states.c
- sys/arduino/wireport.cpp
- sys/net/gnrc/netif/init_devs/auto_init_nrf24l01p_ng.c
- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
- sys/usb/usbus/hid/hid.c
- sys/usb/usbus/hid/hid_io.c
This PR makes a couple of trivial changes to `ENABLE_DEBUG` statements across the code base to fix the warnings that are currently raised by coccinelle in the CI.
All CI tests should pass with no warnings raised by coccinelle.
> ci: fix coccinelle warnings

- dist/tools/pyterm/pyterm
Trying to connect to telnet server module with pyterm:
```
$ ./dist/tools/pyterm/pyterm -ts [fe80::a413:5bff:feac:60b0%enp0s25]:23
2021-08-12 22:31:02,270 # Connect to [fe80:
2021-08-12 22:31:02,274 # [Errno -2] Name or service not known
2021-08-12 22:31:02,275 # Something went wrong connecting to localhost:[fe80::a413:5bff:feac:60b0%enp0s25]:23
```
```
$ ./dist/tools/pyterm/pyterm -ts [fe80::a413:5bff:feac:60b0%enp0s25]:23
2021-08-12 22:38:26,894 # Connect to fe80::a413:5bff:feac:60b0%enp0s25:23
version
2021-08-12 22:38:32,398 # version
2021-08-12 22:38:32,449 # …
```
> dist/tools/pyterm: ipv6 address support for tcp_serial option

- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_region.c
~This PR fixes the upper bound of `random_uint32_range` during channel selection. Since this function is defined as `a <= x < b`, the current implementation picks N-1 channels (instead of N).~
The function was actually right, but the for loop was not taking into consideration that the random number was the channel position in the bitmask.
If the channel mask is e.g `0x5` (`101`), this function should pick the either the first or the third channel (with indexes `0` and `2`).
Join a NS with ABP using `examples/gnrc_lorawan`. Send many unconfirmable uplinks. Make sure 3 channels are used.
@akshaim, coud you give it a look, since you have all the hardware?
Discovered while reading the SDR results in https://github.com/RIOT-OS/RIOT/pull/15946#issuecomment-883370407
> net/gnrc_lorawan: fix pick channel

- sys/include/net/gnrc/tcp.h
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c
- tests/gnrc_tcp/Makefile
- tests/gnrc_tcp/tests-as-root/01-run.py
This PR adds the constant GNRC_TCP_NO_TIMEOUT to disable user specified timeouts on the functions gnrc_tcp_accept, gnrc_tcp_send, gnrc_tcp_recv. 
This PR can be partially tested by executing the tests under tests/gnrc_tcp. Tests exist for gnrc_tcp_accept and gnrc_tcp_recv.
The function gnrc_tcp_send can't be tested because as soon as a connection was established the host system stores received data, therefore gnrc_tcp_send would be unblocked.
Adds missing functionality required by #16494
> gnrc_tcp: Add GNRC_TCP_NO_TIMEOUT

- sys/net/gnrc/transport_layer/tcp/include/gnrc_tcp_common.h
This PR adds minimal documentation to remove gnrc_tcp related warnings from the doxygen static test.
This PR is tested by running 
```
make static-test | grep gnrc_tcp
``` 
If there is no output, the test is successful.
None
> gnrc_tcp: Document internal defines

- sys/include/net/gnrc/tcp.h
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c
- tests/gnrc_tcp/main.c
- tests/gnrc_tcp/tests-as-root/01-run.py
- tests/gnrc_tcp/tests-as-root/helpers.py
This PR enables gnrc_tcp_send and gnrc_tcp_recv to handle zero as buffer size parameter correctly.
To verify this test, run the gnrc_tcp test suite located under: tests/gnrc_tcp.
A dedicated test for each function was added.
Adds missing functionality required by #16494
> gnrc_tcp: handle zero size buffers

- pkg/lwip/contrib/sys_arch.c
- pkg/lwip/include/arch/sys_arch.h
If DEVELHELP is not set `LOCK_TCPIP_CORE()`/`UNLOCK_TCPIP_CORE()` are not defined, leading to a build failure.
Defining them to no-op leads to a run-time segmentation fault, so better always use those functions.
Compile the TCP echo examples from #16739 with `LWIP=1 DEVELHELP=0`
> lwip_tcp: fix build with DEVELHELP=0

- drivers/at86rf215/at86rf215_netdev.c
- drivers/include/at86rf215.h
This PR removes a hardcoded dependency to the GNRC msg queue in `at86rf215`.
The driver needs to do ISR offloading (Bottom Half processing) in order to execute ACK timer and CSMA-CA logic. However, it assumes the upper layer is running GNRC (it posts `NETDEV_MSG_TYPE_EVENT`).
This PR makes it generic using `netdev->event_callback(netdev, NETDEV_EVENT_ISR)`. This way, the driver can be still used with not only msg queues, but also event loops or even thread flags.
Make sure `at87rf215` still works as expected. I unfortunately don't have the hardware to test.
None so far
> drivers/at86rf215: remove msg queue dependency

- pkg/mynewt-core/contrib/task.c
The logging should be not enabled with the default `LOG_LEVEL`, this was a leftover from debugging.
- Green Murdock suffices
> pkg/mynewt-core: change task start log level

- boards/atxmega-a1u-xpro/Kconfig
- boards/atxmega-a1u-xpro/Makefile.features
- boards/atxmega-a3bu-xplained/Kconfig
- boards/atxmega-a3bu-xplained/Makefile.features
- cpu/atxmega/Kconfig
- cpu/atxmega/Makefile.features
Update features definitions and configurations.  Now atxmega define features that only are full available on all variations and do not require any definition at periph_conf.h file.
The test was conducted using `tests/kconfig_features` .
This is a split from #16288
CC: @maribu
> cpu/atxmega: Fix features config

- cpu/cortexm_common/ldscripts/cortexm_base.ld
Fixes this error with binutils 2.37 (the current one on Arch Linux):
```
/usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/bin/ld:cortexm_base.ld:217: warning: memory region `bkup' not declared
/usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/bin/ld:cortexm_base.ld:217: syntax error
```
Seems like newer binutils trip over the minus in the region name. This PR renames the memory region to "bkup_ram" (underline),
which is also more in line with the related variable names.
I'm not aware of any in-tree user. With my binutils, this broke every compilation for affected boards.
IMO, successful CI should be fine!
`bkup-ram` was introduced in #11486.
> cpu/cortexm: ldscripts: bkup-ram -> bkup_ram

- cpu/nrf52/include/nrf802154.h
- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
This PR fixes 2 things:
1. The return value is not compliant with the radio HAL API. It should return either 0 or a negative errno, not the frame length
2. There was a missing:
```c
#ifdef __cplusplus
}
#endif
```
This was not detected because we usually don't include this header from C++ files.
I guess not so much. Just make sure it compiles and the fact including the header from a C++ files works.
Discovered while porting OpenDSME
> drivers/nrf802154: fix write return value and `__cplusplus` closing bracket.

- pkg/lwip/Makefile.dep
- pkg/lwip/Makefile.include
- pkg/lwip/contrib/lwip.c
- pkg/lwip/include/lwip_init_devs.h
- pkg/lwip/init_devs/Makefile
- pkg/lwip/init_devs/auto_init_at86rf2xx.c
- pkg/lwip/init_devs/auto_init_atwinc15x0.c
- pkg/lwip/init_devs/auto_init_enc28j60.c
- pkg/lwip/init_devs/auto_init_esp_eth.c
- pkg/lwip/init_devs/auto_init_esp_wifi.c
- pkg/lwip/init_devs/auto_init_ethos.c
- pkg/lwip/init_devs/auto_init_mrf24j40.c
- pkg/lwip/init_devs/auto_init_netdev_tap.c
- pkg/lwip/init_devs/auto_init_nrf802154.c
- pkg/lwip/init_devs/auto_init_sam0_eth.c
- pkg/lwip/init_devs/auto_init_socket_zep.c
- pkg/lwip/init_devs/auto_init_stm32_eth.c
- pkg/lwip/init_devs/init.c
- sys/include/auto_init.h
Split lwip netif setup into auto_init files, same as gnrc does.
To simplify init.c XFA can be used to group the init functions,
and then call them in a for loop. 
* `tests/lwip` still passes
*  Flash apps using lwIP (such as `examples/paho-mqtt`) and see that the expected interfaces show up in `ifconfig` and work
Depends on and includes #16153, same goal as #14382
> pkg/lwip: Allow initializing different types of netifs

- pkg/lwip/include/lwip_init_devs.h
- pkg/lwip/init_devs/init.c
Fixes build failure without IPv6:
```
RIOT/pkg/lwip/init_devs/init.c:65:61: error: 'tcpip_6lowpan_input' undeclared (first use in this function)
return netif_add_noaddr(netif, state, lwip_netdev_init, tcpip_6lowpan_input);
^
```
Build `examples/paho-mqtt` with `LWIP_IPV4=1 LWIP_IPV6=0`
Build failure existed since #16162
> pkg/lwip: Fix compilation without IPv6

- pkg/nimble/autoconn/nimble_autoconn.c
When a connection is aborted and the node in question is a slave
then it can be advertising/scanning at the time. The incoming
event triggers the state to be changed to IDLE but ongoing adv/scan
which will cause 'nimble_netif_conn_start_adv' to fail to allocate
a handle as the netif will still be busy. Therefore when
stop scan/stop before switching the state.
Use `nimble_autoconn` on two nimble capable devices, either on slave or master close the connection (can also be done by rebooting the master node), an assertion will blow on `pkg/nimble/autoconn/nimble_autoconn.c:81 => 0x611`:
`CFLAGS=-DDEBUG_ASSERT_VERBOSE USEMODULE=nimble_autoconn_ipsp BOARD=nrf52840-mdk make -C examples/gnrc_networking flash term`
```
> 2021-08-03 09:15:00,783 # ble info
2021-08-03 09:15:00,788 # Own Address: …
```
> pkg/nimble/autoconn: stop scan/adv on NETIF_ABORT_SLAVE

- examples/nimble_scanner/Makefile
- examples/nimble_scanner/main.c
- pkg/nimble/scanner/include/nimble_scanner.h
- pkg/nimble/scanner/nimble_scanner.c
This PR adds a function to enable setting the scan duration, similar to what is done for the autoadv module. By default it will run forever. The `nimble_scanner` example has been adapted accordingly.
`make -C examples/nimble_scanner/ flash term`
```
2021-08-03 12:00:47,058 # main(): This is RIOT! (Version: 2021.10-devel-270-g0202e2-pr_nimble_scanner_set_duration)
2021-08-03 12:00:47,059 # NimBLE Scanner Example Application
2021-08-03 12:00:47,059 # Type `scan help` for more information
> scan 1000
2021-08-03 12:01:21,922 # scan 1000
2021-08-03 12:01:22,925 # Scanning for 1000 ms now ... done
2021-08-03 12:01:22,926 # 
2021-08-03 12:01:22,926 # Results:
2021-08-03 12:01:22,935 # [ 0] e4:dd:e0:8f:73:65 (RANDOM) [IND] "RIOT-autoconn", adv_msg_cnt: 19, adv_int: 49093us, last_rssi: -55 …
```
> pkg/nimble/scanner: add function to set scan duration 

- dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
Should fix the warning making static-checks fail.
> dist/toles/compile_and_test_for_board: fix W1514

- pkg/nimble/autoadv/README.md
- pkg/nimble/autoadv/include/nimble_autoadv.h
- pkg/nimble/autoadv/nimble_autoadv.c
These fields can be omitted if all other FLAGS are 0 and the advertising
packets are not connectable, allowing for 3 extra bytes for advertisement
payload.
In an application I need every byte I can get out of the advertisement packet so It's useful/required to gain these 3 extra bytes.
Flash with and without the flag set the FLAGS are then omitted from the payload:
`CFLAGS=-DNIMBLE_AUTOADV_FLAG_FIELD=0 BOARD=nrf52840-mdk make -C examples/nimble_heart_rate_sensor/ flash term -j7`
> pkg/nimble/autoadv: make AD flag optionnal

- sys/net/gnrc/network_layer/ipv6/nib/nib.c
A handle route information option with ltime == 0 means the option is no longer valid and must be removed. 
I forgot to handle that case in the original implementation.
follow-up to #16568
> gnrc_ipv6_nib: handle route information option with ltime = 0

- pkg/lwip/init_devs/auto_init_at86rf215.c
- pkg/lwip/init_devs/auto_init_cc2538_rf.c
- pkg/lwip/init_devs/auto_init_dose.c
Adding new devices to LWIP is easy now, so add some more drivers.
```
2021-08-20 16:18:00,692 # ifconfig
2021-08-20 16:18:00,697 # Iface ET0 HWaddr: a6:ed:29:ec:c3:f3 Link: up State: up
2021-08-20 16:18:00,700 #         Link type: wired
2021-08-20 16:18:00,704 #         inet addr: 0.0.0.0 mask: 0.0.0.0 gw: 0.0.0.0
2021-08-20 16:18:00,719 #         inet6 addr: fe80:0:0:0:a4ed:29ff:feec:c3f3 scope: link
2021-08-20 16:18:00,724 # Iface ET1 HWaddr: a6:ed:29:ec:cb:f3 Link: up State: up
2021-08-20 16:18:00,726 #         Link type: wired
2021-08-20 16:18:00,730 #         inet addr: 0.0.0.0 mask: 0.0.0.0 gw: 0.0.0.0
2021-08-20 16:18:00,736 #         inet6 addr: fe80:0:0:0:a4ed:29ff:feec:cbf3 scope: link
2021-08-20 16:18:00,742 #         inet6 addr: 2001:16b8:45f3:100:a4ed:29ff:feec:cbf3 scope: …
```
> pkg/lwip: add auto-init for DOSE & at86rf215, cc2538_rf

- pkg/nimble/Makefile
- pkg/nimble/Makefile.dep
- pkg/nimble/Makefile.include
- pkg/nimble/contrib/nimble_riot.c
- pkg/nimble/rpble/Makefile
- pkg/nimble/rpble/include/nimble_rpble.h
- pkg/nimble/rpble/include/nimble_rpble_params.h
- pkg/nimble/rpble/nimble_rpble.c
- sys/include/net/gnrc/rpl/rpble.h
- sys/net/gnrc/routing/rpl/gnrc_rpl.c
- sys/net/gnrc/routing/rpl/gnrc_rpl_dodag.c
- tests/nimble_rpble_gnrc/Makefile
- tests/nimble_rpble_gnrc/Makefile.ci
- tests/nimble_rpble_gnrc/main.c
This PR adds support for a BLE connection manager that can be used to automatically let nodes join RPL-based IP over BLE networks. For this nodes start to advertise themselves once they have joined the RPL network, including RPL context information into their BLE advertising data. Other BLE nodes that want to join the network scan for this data and use it to select (and connect) to the best fitting parent node.
The implementation PRed here is tested and works stable. However, the concept itself is still in a prototype phase and there are quite some things that will be improved in the future...
Flash the included `test/nimble_rpble_gnrc` example to at least two supported BLE nodes (basically an board featuring a `nrf52xxx` cpu).
After flashing, configure one of the nodes as RPL root, e.g. …
> net/BLE: add support for RPL-over-BLE

- boards/atxmega-a1-xplained/Kconfig
- boards/atxmega-a1-xplained/Makefile
- boards/atxmega-a1-xplained/Makefile.dep
- boards/atxmega-a1-xplained/Makefile.features
- boards/atxmega-a1-xplained/Makefile.include
- boards/atxmega-a1-xplained/doc.txt
- boards/atxmega-a1-xplained/include/board.h
- boards/atxmega-a1-xplained/include/gpio_params.h
- boards/atxmega-a1-xplained/include/periph_conf.h
- tests/cpu_avr8_xmega_drivers/Makefile
- tests/cpu_avr8_xmega_drivers/test_ebi.c
- tests/periph_timer/Makefile
- tests/pkg_cryptoauthlib_internal-tests/Makefile.ci
Add initial version of [atxmega-a1-xplained](https://www.microchip.com/DevelopmentTools/ProductDetails/PartNO/ATAVRXPLAIN) board. This is another ATxmega development board based on the A1 version. This board shows how to use external SDRAM memory interface.
The test was conducted using Tutorials/task-06 application.
This is part of #15703 and depends on #16288.
CC: @benpicco @maribu
> boards: Introduce atxmega-a1-xplained board

- boards/feather-nrf52840/doc.txt
This fixes several issues with the documentation of the `feather-nrf52840` documentation:
- malformed formatting of the shell commands
- typo in requirements and missing info where to find them
- missing commands in shell commands to let them run out of the box
- out-dated doc on terminal
Compile documentation with `make doc`. The output should now look much nicer and contain much more information compared to the current doc.riot-os.org. Also try out the instructions. The `feather-nrf52840` should mount as a disk drive afterwards (for Arch and Fedora I needed to patch `dist/tools/uf2/uf2conv.py` to be able to flash:
```diff
--- build/pkg/UF2/utils/uf2conv.py	2021-08-24 16:37:10.613961049 +0200
+++ dist/tools/uf2/uf2conv.py	2021-08-24 17:57:43.061182395 +0200
@@ -200,9 +200,13 @@
if …
```
> feather-nrf52840: several fixes to documentation

- README.md
I noticed the doc link badge is broken, this should fix it. 
Test the link in master, follow the link in this PR (or open the file in markdown and click on the badge).
> README.md: fix doc link

- cpu/stm32/periph/flashpage.c
- drivers/include/periph/flashpage.h
- drivers/periph_common/flashpage.c
All addresses to flashpage_page() must be in flash. Flash memory is `const`, therefore this function must also take `const` pointers.
Code should still compile.
> drivers/flashpage: flashpage_page() takes a const argument

- .gitignore
As the title says. I use this to locally to fine-tune what clangd warns me about.
Create a `.clang-tidy` file. In `master` that file will show up in `git status`, with this PR it won't.
None
> .gitignore: add .clang-tidy

- dist/tools/suit/suit-manifest-generator/suit_tool/create.py
- makefiles/suit.base.inc.mk
- makefiles/suit.inc.mk
No change other than using `$(Q)` instead of `@` for silencing output. Some extra things are silenced now.
Run the suit workflow and look at the output from `MAKE`, main changes in `suit/publish`
` make suit/publish`
PR:
```
creating /home/francisco/workspace/RIOT/examples/suit_update/bin/samr21-xpro/suit_update-slot0.1629727397.riot.bin...
creating /home/francisco/workspace/RIOT/examples/suit_update/bin/samr21-xpro/suit_update-slot1.1629727397.riot.bin...
published "/home/francisco/workspace/RIOT/examples/suit_update/bin/samr21-xpro/suit_update-riot.suit.1629727397.bin"
as "coap://localhost/fw/samr21-xpro/suit_update-riot.suit.1629727397.bin"
published "/home/francisco/workspace/RIOT/examples/suit_update/bin/samr21-xpro/suit_update-riot.suit.latest.bin"
as …
```
> makefiles/suit*: use $(Q) to silence output

- sys/net/application_layer/dhcpv6/client.c
This PR makes a couple of changes to the DHCPv6 client implementation to increase maintainability and the possibility to add new features.
It mostly moves existing code to separate functions but also refactors the composition of messages by adding a new `_compose_message` function which eliminates some code duplication and makes it easier to see which options are used (or requested) with each message type. This should also make it easier to add additional features like information-requests to the client.
You can use the existing tests under `tests/gnrc_dhcpv6_client` and `tests/gnrc_dhcpv6_client_6lbr`. Despite the changes, these should still work.
> sys/net/dhcpv6: Refactor DHCPv6 client

- core/include/msg.h
When I worked through messages, I got once more confused by how msg_send_receive / msg_reply work -- what if I receive another message while waiting? Do I have to make sure that doesn't happen? Would the other message get dropped? What if there's already a message waiting in the queue?
This clarifies the behavior, which (from reading the code) I understand to be that the thread, for all other messages, behaves like it's not waiting for a message, and that only the msg_respond function understands that state and puts the message in -- responses never enter the queue.
* Read updated documentation and compare to your expectations.
> core/msg doc: Clarify; elaborating on interaction with queue

- boards/arduino-leonardo/board.c
- boards/common/atmega/board.c
- cpu/atmega_common/atmega_cpu.c
- cpu/atxmega/include/cpu_conf.h
- cpu/avr8_common/avr8_cpu.c
This code should not be in the realm of the board config, but in common arch code.
No change in functionality is expeted on ATMega boards.
split off #16055
> cpu/atmega_common: move clock init to common code

- pkg/mynewt-core/contrib/core.c
- pkg/nimble/contrib/nimble_riot.c
- pkg/nimble/patches/0001-porting-nimble-src-nimble_port-riot-initializes-time.patch
- pkg/nimble/patches/0002-porting-npl-riot-add-namespaced-syscfg-symlink.patch
This PR implements suggestions in https://github.com/RIOT-OS/RIOT/pull/16348#discussion_r665160617, the upstream PR has been adapted accordingly https://github.com/apache/mynewt-nimble/pull/996. The patch can be removed once that Pr is merged and upstream commit updated.
It can be tested with a simple compile test verifying that its not called when using `uwb-core` and that it is when not (e.g.: adding a #error)
- note called ` CFLAGS=-fms-extensions USEPKG="uwb-dw1000 uwb-core" make -C examples/nimble_gatt/ all -j3`
- called ` make -C examples/nimble_gatt/ all -j3`
```
/home/francisco/workspace/RIOT/pkg/nimble/contrib/nimble_riot.c: In function 'nimble_riot_init':
/home/francisco/workspace/RIOT/pkg/nimble/contrib/nimble_riot.c:109:6: error: #error
109 |     #11852 
```
> pkg/nimble: have RIOT always initialize nimble timers

- boards/hifive1b/include/periph_conf.h
This fixes the tx and rx pins for the HiFive1 Rev B01 for uart device 1. These pins were in the wrong order.
See the FE310-G002 manual at page 81.
https://sifive.cdn.prismic.io/sifive/e36c0a2f-413f-49d4-85c1-51ee1ed243e5_fe310-g002-manual-v1p1.pdf
This change will be tested with RobotFW https://github.com/RIOT-OS/RobotFW-tests/pull/117
> boards/hifive1b: Fix uart dev1 pins

- Makefile.include
Currently `Makefile.include` errors if these tools are absent, but they are actually rarely used, so as all other tools used by only some packages don't error, but keep the warning.
```
$ git grep \$\(CURL\)
Makefile.include:  ifeq (,$(CURL))
Makefile.include:  ifeq (,$(WGET)$(CURL))
Makefile.include:    DOWNLOAD_TO_STDOUT ?= $(if $(CURL),$(CURL) -s,$(WGET) -q -O-)
Makefile.include:    DOWNLOAD_TO_FILE ?= $(if $(WGET),$(WGET) -nv -c -O,$(CURL) -s -o)
$ git grep \$\(WGET\)
Makefile.include:  ifeq (,$(WGET))
Makefile.include:  ifeq (,$(WGET)$(CURL))
Makefile.include:    DOWNLOAD_TO_STDOUT ?= $(if $(CURL),$(CURL) -s,$(WGET) -q -O-)
Makefile.include:    DOWNLOAD_TO_FILE ?= $(if $(WGET),$(WGET) -nv -c -O,$(CURL) -s -o)
$ git grep \$\(DOWNLOAD_TO_STDOUT\)
Makefile.include:ifeq (,$(and …
```
> Makefile.include: only warn if not curl, wget, unzip, 7z

- tests/gnrc_dhcpv6_client/Makefile
- tests/gnrc_dhcpv6_client/README.md
- tests/gnrc_dhcpv6_client/dhcpv6_server.sh
- tests/gnrc_dhcpv6_client/kea-dhcp6.conf
Currently, Kea will only start in `tests/gnrc_dhcpv6_client` properly, when `IFACE` is set to `tapbr0`. With this change, the Kea config honors the value of the `IFACE` variable.
Create a bridge typically not used with RIOT e.g.
```sh
dist/tools/tapsetup/tapsetup -b tapbr1
```
and start the test with that interface
```sh
IFACE=tapbr1 make -C tests/gnrc_dhcpv6_client flash -j test-with-config
```
without this change the test will fail and Kea will complain, that `tapbr0` does not exist. With this change the test should pass.
Follow-up on #16792.
> tests/gnrc_dhcpv6_client: honor configured $IFACE in Kea config

- .github/workflows/release-test.yml
- Makefile.include
- dist/testbed-support/makefile.iotlab.single.inc.mk
- dist/tools/buildsystem_sanity_check/check.sh
- dist/tools/openvisualizer/makefile.openvisualizer.inc.mk
- makefiles/arch/riscv.inc.mk
- makefiles/boards/sam0.inc.mk
- pkg/flatbuffers/Makefile.include
The `which` command is being deprecated in Debian (see references below).
This moves all invocations in the build system from `which` to the successor `command -v`.
Try building anything on a recent Debian sid system. While it'll fail on master, after #16775 you'll get several lines of
```
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
```
that are gone after this patch sequence.
Any attempt to reintroduce `$(shell which ...)` in the Makefiles should also trigger the sanity checks of dist/tools/buildsystem_sanity_check/check.sh.
This is a follow-up of (and based on) #16775. It was split out after [some build process](https://github.com/RIOT-OS/RIOT/runs/3411537020?check_suite_focus=true) spew errors for not knowing `command`. As #16775 is …
> Remove `which` from shell invocations

- Makefile.include
- dist/testbed-support/makefile.iotlab.single.inc.mk
- dist/tools/buildsystem_sanity_check/check.sh
- dist/tools/openvisualizer/makefile.openvisualizer.inc.mk
- makefiles/arch/riscv.inc.mk
- makefiles/boards/sam0.inc.mk
- pkg/flatbuffers/Makefile.include
Reverts RIOT-OS/RIOT#16776
Builds [are failing](https://ci.riot-os.org/RIOT-OS/RIOT/16020/9cae200ab1a51fa3a9a540ca48f182102db2b58d/output/compile/examples/lorawan/hifive1b:gnu.txt) due to this PR having been merged.
> Revert "Remove `which` from shell invocations"

- boards/common/nrf52/Makefile.nimble.dep
- boards/common/nrf52/Makefile.nrfmin.dep
Only nimble depends on GNRC, but we want to replace gnrc_netdev_default with netdev_default, so check for gnrc instead.
`gnrc_netdev_default` selects `netdev_default` so binaries will stay the same.
> boards/nrf52: replace gnrc_netdev_default with netdev_default

- cpu/sam0_common/periph/rtc_rtt.c
- cpu/samd5x/Kconfig
- cpu/samd5x/Makefile.features
- cpu/saml21/Kconfig
- cpu/saml21/Makefile.features
- drivers/include/periph/rtc_mem.h
- kconfigs/Kconfig.features
- tests/periph_rtc/Makefile
- tests/periph_rtc/main.c
- tests/periph_rtt/Makefile
- tests/periph_rtt/main.c
The RTC often provides some memory that can be used to store data across reset / deep sleep.
Expose this memory with a proper API.
On SAM D5x/E5x general purpose registers are shared with the alarm registers.
Since the RTC/RTT interface only exposes a single alarm, we can only use the second pair of General Purpose Registers.
The data sheet for SAM L1x and SAM L2x do not mention such limitations, but according to the data sheet SAM L21 only has 2 General Purpose registers whereas the vendor files have definitions for 4. I didn't yet test if they do indeed all work. 
So far this only has been tested on `same54-xpro`. Both `tests/periph_rtc` and `tests/periph_rtt` have been adapted to make use of the feature and to ensure it does not interfere with normal RTC/RTT alarms.
alternative to …
> drivers/periph: define rtc_mem and implement it for sam0_common

- cpu/cc2538/radio/cc2538_rf_radio_ops.c
- drivers/include/net/netdev/ieee802154_submac.h
- drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c
- sys/include/net/ieee802154/radio.h
- sys/include/net/ieee802154/submac.h
- sys/net/link_layer/ieee802154/submac.c
This PR re-implements the IEEE802.15.4 SubMAC using a Mealy FSM. There are many advantages of using this method:
1. The SubMAC is more robust to hicups such as race condition or slow Bottom Half Processor (e.g SPI radios that process their internal events using the same thread as the SubMAC)
2. It's way easier to debug the SubMAC since the transitions are well known.
3. It's also easier to expand the functionalities of the SubMAC.
4. Automated testing should be way easier as well.
5. Last but not least, this helps to point out implementation issues in radios (this PR piggyback a fix for the CC2538)
Given this PR, the SubMAC seems to be way more stable and tolerant to radio quirks:
E.g:
```
2021-08-13 13:40:24,533 # 
2021-08-13 13:40:24,536 # --- fe80::204:2519:1801:bddb PING statistics …
```
> ieee802154/submac: reimplement using FSM

- doc/doxygen/src/advanced-build-system-tricks.md
This fixed the link in doxygen.
Check the doc... (waiting for circle ci)
> doc/doxygen/src/advanced-build-system-tricks: fix no udev link

- makefiles/tests/tests.inc.mk
This adds another dependency for `test-with-config` that uses (optional) `check-config` scripts within the `tests-with-config` directory to check if the config required for the test is available. If the config is not available, the `make test-with-config` target will fail with an appropriate error message.
I will provide a config checker for `tests/gnrc_dhcpv6_client` as a follow-up (https://github.com/RIOT-OS/RIOT/pull/16797). With that, this PR will be testable.
None
> make: add capability to check config for `test-with-config`

- sys/include/net/cord/config.h
- sys/net/application_layer/cord/common/cord_common.c
Registations at a Resouirce Directory can have extra arguments; this is useful for example to ask an RD to reverse-proxy you.
With a board that gets a route to the Internet, add the following config to one of `examples/cord_ep` or `examples/cord_epsim`, and run it.
```patch
+CFLAGS += '-DCONFIG_CORD_EXTRAARGS="proxy=on","et=tag:riot-os.org,2020:board"'
+CFLAGS += '-DCONFIG_CORD_EP="myhost"'
```
The `epsim` version also needs
```patch
-RD_ADDR ?= \"[affe::1]\"
+RD_ADDR ?= \"[2a01:4f8:190:3064::5]\"
```
whereas the non-simple version needs the command
```
> cord_ep register [2a01:4f8:190:3064::5]
```
executed.
Then, you should see your device registering with a synthetic proxy URI (courtesy of the `proxy=on` argument) in the public RD indicated by the addresses:
```shell
$ ./aiocoap-client …
```
> sys/net/app/cord: Support the addition of extra registration arguments

- cpu/cc2538/periph/spi.c
Fixes a copy-paste error introduced in https://github.com/RIOT-OS/RIOT/pull/15902
Green Murdock and code review should be sufficient for this.
See https://github.com/RIOT-OS/RIOT/pull/15902#discussion_r702210076
> cpu/cc2538/periph/spi: move assert to spi_acquire

- pkg/nimble/Makefile
- pkg/nimble/Makefile.dep
- pkg/nimble/Makefile.include
Nimble has in-tree copy of tinycrypt for stand-alone nimble builds, this is not needed when building in RIOT and can lead to conflicts with other pkg/modules using `tinycrypy`
Build results seem the same...
- PR:
```
RIOT_VERSION=0 RIOT_CI_BUILD=1 make -C examples/nimble_gatt/ clean all -j3
Building application "nimble_gatt" for "nrf52dk" with MCU "nrf52".
rm -rf /home/francisco/workspace/RIOT2/examples/nimble_gatt/bin/nrf52dk/pkg-build/nimble
rm -rf /home/francisco/workspace/RIOT2/examples/nimble_gatt/bin/nrf52dk/pkg-build/tinycrypt
text    data     bss     dec     hex filename
76816     588   10648   88052   157f4 /home/francisco/workspace/RIOT2/examples/nimble_gatt/bin/nrf52dk/nimble_gatt.elf
```
- master
```
→ RIOT_VERSION=0 RIOT_CI_BUILD=1 make -C examples/nimble_gatt/ clean all -j3 …
```
> pkg/nimble: use tinycrypt pkg

- sys/net/link_layer/ieee802154/submac.c
- tests/ieee802154_submac/main.c
…y in RX
During the re-refactor of #16746 I missed one: if the radio indicates RX_DONE or CRC_FAIL, the SubMAC must manually trigger `request_set_trx_state(RX_ON)` if the SubMAC state is RX.
It also fixes a concurrency issue, where `netdev_ieee802154_submac` in `tests/ieee802154_submac` was running distributed in 2 threads. I synchronize it with mutex.
Ping command is not enough because the SubMAC state goes back and forth between RX and TX.
For testing this one, send several frames to a `nrf52840` using the SubMAC. Without this PR, only the first frame will be received.
Test results for `nrf802154` and `cc2538_rf`:
```
2021-09-07 16:55:36,546 # Trying to register cc2538_rf.
2021-09-07 16:55:36,548 # Success
2021-09-07 16:55:36,552 # Initialization successful - …
```
> ieee802154/submac: fix leftovers of #16746

- pkg/edhoc-c/Makefile.dep
- pkg/tinycrypt/Makefile
With https://github.com/RIOT-OS/RIOT/pull/16540 the blacklist can be reverted.
A compile test is enough...
```
USEPKG="edhoc-c" USEMODULE="edhoc-c_cbor_nanocbor edhoc-c_crypto_tinycrypt" make -C examples/nimble_gatt/
Building application "nimble_gatt" for "nrf52dk" with MCU "nrf52".
make[1]: Nothing to be done for 'prepare'.
[INFO] updating nanocbor /home/francisco/workspace/RIOT2/build/pkg/nanocbor/.pkg-state.git-downloaded
echo 7728af0633a8d9d119c9b36a5c5a441e11e75ff1 > /home/francisco/workspace/RIOT2/build/pkg/nanocbor/.pkg-state.git-downloaded
[INFO] patch nanocbor
"make" -C /home/francisco/workspace/RIOT2/pkg/c25519
"make" -C /home/francisco/workspace/RIOT2/build/pkg/c25519/src -f /home/francisco/workspace/RIOT2/Makefile.base MODULE=c25519
"make" -C …
```
> pkg/edhoc-c: remove nimble blacklist 

- dist/tools/buildsystem_sanity_check/check.sh
- doc/doxygen/src/kconfig/kconfig.md
- makefiles/kconfig.mk
If there is one thing I will miss when we go full Kconfig, is setting configuration and module selection via the environment variables without having to touch random files. This drafts out how to do that regardless with Kconfig by using the `RIOT_CONFIG_` prefix for environement variables. At least for the generated output config this seems to be working as I was able to include modules into my build with that, but this is still lacking some functionality:
TODOs:
I used a random app of those that already support building with Kconfig:
```
$ TEST_KCONFIG=1 make -C tests/driver_dht/ info-modules
make: Entering directory '/home/mlenders/Repositories/RIOT-OS/RIOT/tests/driver_dht'
=== [ATTENTION] Testing Kconfig dependency modelling ===
=== [ATTENTION] Testing Kconfig dependency modelling === …
```
> makefiles/kconfig.mk: generate config file from RIOT_CONFIG_% environment variables

- tests/ieee802154_hal/main.c
This PR does essentially 2 things:
- Check error codes when requesting state transitions and transmission. In some cases radios were BUSY when requesting transmission or a new state (because of IFS or the hardware accelerator was finishing a task). This ended up with a situation where "confirm_xxx" functions were called without a successful request.
- Report errors when CCA failed or the transmission could not be performed.
I think https://github.com/RIOT-OS/RIOT/pull/15761 would be appropiate to test this. This issue was triggered when using the `txtspam` command (Radios simply stop receiving packets after one is successfully received).
@LarsKowoll could you give it a look? :)
Discovered by @LarsKowoll in https://github.com/RIOT-OS/RIOT/pull/15761
> tests/ieee802154_hal: check error codes and improve error reporting

- tests/gnrc_dhcpv6_client/Makefile
- tests/gnrc_dhcpv6_client/tests-with-config/check-config.sh
Adds a checker script if the required interface for `tests/gnrc_dhcpv6_client` exists.
Run `tests/gnrc_dhcpv6_client` with and without a TAP interface
```sh
make -C tests/gnrc_dhcpv6_client flash -j test-with-config # should succeed
sudo dist/tools/tapsetup/tapsetup -d
make -C tests/gnrc_dhcpv6_client flash -j test-with-config # should fail with appropriate error message
```
Depends on #16795 for the config check to work ~~and #16796 for the `$IFACE` export~~ (see https://github.com/RIOT-OS/RIOT/pull/16797#issuecomment-911714794).
> tests/gnrc_dhcpv6_client: add script to check if $IFACE exists

- boards/nrf9160dk/Kconfig
- boards/nrf9160dk/Makefile.features
- boards/nrf9160dk/include/periph_conf.h
- cpu/nrf5x_common/periph/Makefile
- cpu/nrf5x_common/periph/i2c_nrf52_nrf9160.c
- cpu/nrf5x_common/periph/spi_nrf52_nrf9160.c
- cpu/nrf9160/include/periph_cpu.h
- cpu/nrf9160/spi_twi_irq.c
- pkg/mynewt-core/contrib/Makefile
- pkg/mynewt-core/mynewt-core_os.mk
- pkg/uwb-core/Makefile.dep
This PR adds support for I2C and SPI for nRF9160 MCUs.
Since these IPs are the same as nRF52. I moved SPI and I2C code to nrf5x_common (I did not touch nRF51 drivers). And I also recreate a SPI/I2C irq handler to match the behaviour of nrf52 platform.
It would be good to ensure nothing is broken on nRF52 platform with this PR but I don't have the hardware with me for now.
on nRF52 based board and nRF9160dk, use `tests/periph_i2c` and `tests/periph_spi` to test.
I provide some output from my custom nRF9160 based board:
tests/driver_hts221:
```
2021-09-05 22:14:24,606 # main(): This is RIOT! (Version: 2021.04-devel-2410-gc333e-pr/cpu/nrf9160_add_twi_and_spi_support)
2021-09-05 22:14:24,607 # Init HTS221 on I2C_DEV(0)
2021-09-05 22:14:24,664 # H: 63.0%, T: 37.0°C
2021-09-05 22:14:26,704 # H: …
```
> cpu/nrf9160: add twi and spi support

- sys/include/net/ipv6/addr.h
It doesn't make any sense that `result_len` should specify the length of
`result_len`. Instead, `result_len` should specify the length of the
`result` parameter.
> ipv6: fix typo in ipv6_addr_to_str documentation

- sys/net/gnrc/sock/gnrc_sock.c
avoid spinning xtimer on socket receive with short timeout by increasing the timeout to XTIMER_BACKOFF
run benchmark_udp with short intervalls
possibly Fixes #16808
> gnrc/sock: recv avoid spinning xtimer

- pkg/nimble/netif/include/nimble_netif.h
- pkg/nimble/netif/nimble_netif.c
- sys/shell/commands/sc_nimble_netif.c
This PR extends `nimble_netif` to support connecting to other devices by sending directed advertising packets (`DIRECT_IND`). This is a special type of advertising packets has as payload only a target BLE address. These packets are ignored by all other nodes except the one directly addressed by this included address. 
Using these advertisements is useful for e.g. reconnecting to a specific node after a connection loss... I am using this in a more advanced BLE connection manager (PR will follow soon).
This PR also extends the `ble` shell command to expose this new functionality -> use `ble adv direct xx:xx:xx:xx:xx:xx` to trigger directed advertisements. But note: you won't be able to see them e.g. on the nrfConnect mobile app, if the given address does not match your scanning device...
- …
> pkg/nimble/netif: add nimble_netif_accept_direct()

- sys/include/net/ieee802154_security.h
The security module introduced in #15150 was, in my understanding, not intended for security critical use ("waives to use a proper key store to mitigate complexity"), but that didn't come across clearly in the documentation, and might thus give wrong impressions.
* Doc only change: Look at the new infobox in ~~ieee802154__security_8h.html~~ group__net__ieee802154__security.html of the built documentation.
#15150 was where the module was introduced
[edit: Hotfixed after I found that the box wound up in the header file and not the module description]
> net/ieee802154_security doc: Shape security expectations

- boards/samd21-xpro/Kconfig
- boards/samd21-xpro/Makefile.features
- boards/samd21-xpro/include/periph_conf.h
This changes  adds usbdev support to the SAMD21-XPRO board. 
The GPIO configuration for the usb is exactly the same as in the SAMR21-XPRO.
```txt
USB D-  = GPIO_PIN(PA, 24)
USB D+  = GPIO_PIN(PA, 25)
``` 
Go to `examples/usbus_minimal` and type:
```sh
make BOARD=samd21-xpro USB_VID=03eb USB_PID=2169 flash
```
Connect the  port; `USB TARGET` to the computer and type `lsusb`, a device should appear such that::
```sh
Bus 003 Device 037: ID 03eb:2169 Atmel Corp. USB device
```
> boards/samd21-xpro:  Add peripheral usbdev to samd21-xpro

- sys/include/net/gnrc/tcp/config.h
- sys/net/gnrc/transport_layer/tcp/Kconfig
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c
- tests/gnrc_tcp/Makefile
This PR adds an experimental feature to gnrc_tcp called "dynamic MSL".
It calculates the otherwise static MSL value based on the last calculated re-transmission timeout value times
a configurable constant factor. This leads to a much shorter MSL causing gnrc_tcp_close to return faster if the TCP teardown sequence causes GNRC_TCP to wait in state TIME-WAIT.
Although this feature is a deviation from the TCP Standard, it should not cause any Issues. If a packet is received after the shorter TIME-WAIT timer times out, a reset packet is sent in return. 
This PR is not really testable in a deterministic way. It depends on heavily the scheduling of the
test runner and the packet transmission order between host system and riot node.
I enabled this feature in the gnrc_tcp test suite located under …
> gnrc_tcp: experimental feature "dynamic msl"

- cpu/cc26x0_cc13x0/include/cc26x0_cc13x0_fcfg.h
0d9f6ca broke the build for `cpu/cc26xx_cc13xx`
CI build should work again. 
#16813
> cpu/cc26x0_cc13x0: fix build

- core/include/thread.h
- sys/ps/ps.c
This PR creates some getters for internal thread_t defines as used by ps().
Main reason is "cleanup", I also want to be able to have alternative core implementations.
Binaries should not change.
> core/thread: add getters for thread_t

- core/include/sched.h
- core/sched.c
- makefiles/pseudomodules.inc.mk
This adds a runqueue callback to core/sched that is called on changes to runqueue if they are active or their last thread is removed. (callbacks are issued when: a runqueue gets active, the active runqueue grows or a runqueue is emptied)
This also adds functions to gather informations about the length of runqueues. (empty, one thread, more than one thread)
Both features together may be used to implement schedulers that are able to adapt to demand (active if required, inactive if not)
none yet but testing #16126
#16311 added the required interface to change threads by advancing the runqueue
this is derived from #16126 which also adds a matching round robin scheduler
> core/sched: add runq_callback hook and runq inspection functions

- CODEOWNERS
Following the maintainer ping, Robert Hartung answered that he has no longer time for maintaining RIOT and requested to be taken off the CODEOWNERS list.
This PR implements this request. 
> I was quite busy with my PhD thesis (and still am), therefore, feel free
> to take me off the active maintainers list.
> Note: I am still listed as a code owner at some places, can you remove
> @roberthartung from there for now as well?
> CODEOWNERS: remove Robert Hartung

- cpu/cc2538/include/cc2538_rf.h
- cpu/cc2538/include/cpu_conf.h
- cpu/cc2538/periph/hwrng.c
`cc2538_rfcore.h` contains enums with non-prefixed single-word constants.
Those cause ugly naming conflicts down the line.
Only include the file when needed, don't include it in `cpu_conf.h` which gets pulled in everywhere.
Everything should still compile.
> cpu/cc2538: don't pollute global namespace with cc2538_rfcore.h

- pkg/nimble/autoconn/nimble_autoconn.c
- pkg/nimble/netif/include/nimble_netif.h
- pkg/nimble/netif/include/nimble_netif_conn.h
- pkg/nimble/netif/nimble_netif.c
- pkg/nimble/netif/nimble_netif_conn.c
- pkg/nimble/rpble/nimble_rpble.c
- sys/shell/commands/sc_nimble_netif.c
Took me some time but at some point even I started to understand the value of using `errno` values for functions :-)
This PR adapts `nimble_netif` to do just so, its pretty much a plain replacement of custom values with fitting `errno` values, so this change should be straight forward.
Build test and a manual code review should be sufficient in this case
none
> pkg/nimble/netif: migrate to use errno return values

- doc/doxygen/dot/porting-boards.dot
- doc/doxygen/riot.doxyfile
- doc/doxygen/src/porting-boards.md
- doc/doxygen/src/porting-cpus.md
The main objective of this PR is to provide a porting flowchart similar to the one [AWS FreeRTOS provides](https://docs.aws.amazon.com/freertos/latest/portingguide/porting-chart.html) (but way simpler, since we have a HAL). For the color scheme I oriented myself on other graphs (like the `netdev` description or the one on the `gnrc` main page).
Since we lack some guides however ("How to port a CPU?", "How to make a network device compatible with a network stack?") I added some TODO notes for those to the be provided so I have something to link to.
Regarding the "How to port a CPU?" part @akshaim has already something in the pipeline AFAIK, @jia200x, @fjmolinas should we look into the "How to make a network device compatible with a network stack?" part?
Read the doc generated by CircleCI. …
> doc/porting-boards.md: improve with porting graph and reference section

- drivers/ina3221/alerts.c
- drivers/ina3221/ina3221.c
- drivers/ina3221/ina3221_saul.c
- drivers/include/ina3221.h
- drivers/saul/init_devs/auto_init_ina3221.c
- tests/driver_ina3221/main.c
This is a follow up PR of #15898.
It fixes style issues and contains some minor improvements.
`tests/driver_ina3221:`
```
2021-02-02 13:43:23,953 # [SUCCESS] ina3221_init
2021-02-02 13:43:23,954 # [SUCCESS] ina3221_read_shunt_uv
2021-02-02 13:43:23,955 # [SUCCESS] ina3221_calculate_current_ua
2021-02-02 13:43:23,956 # [SUCCESS] ina3221_read_bus_mv
2021-02-02 13:43:23,957 # [SUCCESS] ina3221_calculate_power_uw
2021-02-02 13:43:23,958 # [SUCCESS] ina3221_set_enable_sum_channel
2021-02-02 13:43:23,959 # [SUCCESS] ina3221_read_shunt_sum_uv
2021-02-02 13:43:23,961 # [SUCCESS] INA3221_TRIGGER_SHUNT_AND_BUS
2021-02-02 13:43:24,060 # [SUCCESS] ina3221_read_shunt_uv (triggered)
2021-02-02 13:43:24,062 # [SUCCESS] ina3221_read_bus_mv (triggered)
2021-02-02 13:43:24,063 # [SUCCESS] …
```
> drivers/ina3221: style fixes and improvements

- boards/adafruit-clue/include/board.h
- boards/adafruit-clue/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
Fix warnings of `boards/adafruit-clue`. There is still one warning left that seems to be a false positive:
```
boards/adafruit\-clue/include/board\.h:[0-9]+: warning: end of file with unbalanced grouping commands
```
Because each `@{` is matched with their corresponding `@}`.
- `make static-test` on newer Doxygen versions.
> boards/adafruit-clue: fix doxygen warnings

- drivers/lm75/Kconfig
- drivers/lm75/include/lm75_params.h
Fixed a small typo (missing L) present in the lm75 driver Kconfig. As well as an incoherent connection in lm75_params.h.
--
--
> drivers/lm75: fixed a typo in Kconfig

- dist/tools/backport_pr/backport_pr.py
- dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
- dist/tools/compile_and_test_for_board/tests/test_compile_and_test_for_board.py
In current master `tools-test` [fails](https://github.com/RIOT-OS/RIOT/runs/3629809579), due to pylint checking for f-strings in `backport_pr` and `compile_and_test_for_board` with its latest version. This uses f-strings in those scripts whereever possible.
With this change we effectively drop Python <=3.5 support for these scripts. As python 3.5 is EOL since September 2015, I think that is acceptable (and as far as I know these scripts are not used on some out-dated nodes in our CI infrastructure).
- `tox` should now pass again for both tests (`cd <scriptdir>; tox`).
- both scripts should have the same output in master and this PR.
None
> dist/tools: use f-strings where possible

- sys/include/net/gnrc/lorawan.h
- sys/include/net/loramac.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mcps.c
- sys/net/gnrc/link_layer/lorawan/include/gnrc_lorawan_internal.h
- sys/net/link_layer/Kconfig.lorawan
This PR implements uplink redundancy for GNRC LoRaWAN.
Uplink redundancy is used to retransmit unconfirmed uplink frames. The retransmission stops when either a downlink message is received or the number of uplink retransmissions is reached. This functionality doesn't affect confirmed uplinks.
Although this functionality is intended to be used by the upcoming implementation of ADR, this can be also set at compile time by the user.
- Configure the LORAMAC_DEFAULT_REDUNDANCY parameter using Kconfig (e.g to 3). Then, please check the following stuff:
```
diff --git a/sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c b/sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
index 963e1197e9..2865b74748 100644
--- a/sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
+++ …
```
> net/gnrc_lorawan: implement unconfirmed uplink redundancy

- boards/avsextrem/Makefile.dep
- boards/msba2/Makefile.dep
- boards/msbiot/Makefile.dep
- drivers/cc110x/Makefile.dep
- drivers/cc110x/include/cc110x_params.h
- makefiles/pseudomodules.inc.mk
CC110x modules on ebay are commonly using the 433 MHz band.
Add a pseudo-module for band selection and default to that band, manually select band for 868 MHz boards.
The code should not change compared to `master`.
Boards from this branch (e.g `msba2`) should still be able to communicate with boards on the master branch.
https://github.com/RIOT-OS/RIOT/pull/16232#issuecomment-861267025
> drivers/cc110x: use pseudo-modules for band selection

- pkg/nimble/addr/nimble_addr.c
- pkg/nimble/scanlist/nimble_scanlist_print.c
Seems like `nimble_addr` module hasn't been used too much, as the `nimble_addr_sprint()` function was broken in two cases:
- the byteorder was incorrect: `ble_addr_t` holds the addresses in little endian, however in RIOT (and same for e.g. the Nordic Android app) print the byteorder in big-endian -> so we need to swap it here
- the address type in the output string was cut off: the `\0` termination character needs to be put at he position of `NIMBLE_ADDR_STRLEN` instead of `BLUETIL_ADDR_STRLEN`
Both errors are fixed in this PR.
This PR further cleans up  `nimble_scanlist` by removing the custom print function and instead make use of `nimble_addr_print`. 
- Run the NimBLE Scanner `examples/nimble_scanner`
- alternatively run `gnrc_networking` on a IP over BLE capable platform and run the …
> nimble/addr|scanlist: fix nimble_addr_sprint() and use in nimble_scanlist_print()

- pkg/nimble/scanner/include/nimble_scanner.h
- pkg/nimble/scanner/nimble_scanner.c
- sys/shell/commands/sc_nimble_netif.c
Same as #16838: this PR migrates the return values to use `errno` values instead of custom ones.
As further optimization the `nimble_scanner_status()` function was changed to `bool nimble_scanner_is_active()`, as this feels more natural in terms of both wording as well as return value...
Build test and code review should do the trick.
none
> nimble/scanner: migrate to errno return values

- sys/include/net/ieee802154/submac.h
Docs used to be garbled (line-joined, non-fixed-width ASCII art and table); fixing to be verbatim block (for diagram) and markdown table
* Look at changed group__net__ieee802154__submac.html file in built docs: any `+------+` parts should form a readable image, and there should be a table.
> ieee802154_submac doc: Make readable in doxygen builds

- pkg/edhoc-c/Makefile
Fixed a compilation issue, with llvm.
```
TOOLCHAIN=llvm make -C tests/pkg_edhoc_c/ all -j7
Building application "tests_pkg_edhoc_c" for "native" with MCU "native".
make[1]: Nothing to be done for 'prepare'.
[INFO] cloning EDHOC-C
Cloning into '/home/francisco/workspace/RIOT2/build/pkg/EDHOC-C'...
remote: Enumerating objects: 1367, done.
remote: Counting objects: 100% (376/376), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 1367 (delta 277), reused 265 (delta 225), pack-reused 991
Receiving objects: 100% (1367/1367), 531.33 KiB | 5.21 MiB/s, done.
Resolving deltas: 100% (835/835), done.
HEAD is now at 1366035 src/cbor/nanocbor: bump nanocbor version
[INFO] updating EDHOC-C /home/francisco/workspace/RIOT2/build/pkg/EDHOC-C/.pkg-state.git-downloaded
echo …
```
> pkg/edhoc-c: ignore llvm flagged error

- pkg/tinydtls/Makefile.include
As reported in #16873, the tinyDTLS example fails to build with Kconfig, because the Makefile fails to detect that Kconfig is being used, and injects CFLAGS. This makes PSK and ECC to be built, which is not supported by the example application so far.
You can follow the procedure described in #16873.
Fixes #16873.
> pkg/tinydtls: fix detection of Kconfig usage

- cpu/riscv_common/start.S
This PR simplifies the code in the reset trampoline that is used to jump to the right flash base address for the real startup code. By loading the absolute address of `_start_real` we can unconditionally jump to it regardless if the PC is somewhere at `0x0` or at `ROM_START_ADDR`.
Background:
The whole logic in this function both before and after this PR is there because on GD32V, the PC jumps to `0x0` on system reset, which is an alias address for the flash, but our code in the ELF file is linked at `0x08000000` which makes GDB not understand any symbol addresses until we jump to the real flash base address. Without jumping to the correct base we also get the wrong address for `__global_pointer$` a few lines below this change.
This change was spawned from a discussion in the Matrix room …
> riscv: Simplify reset trampoline

- cpu/fe310/Kconfig
- cpu/fe310/Makefile.features
- cpu/gd32v/Kconfig
- cpu/gd32v/Makefile.features
- cpu/riscv_common/Kconfig
- cpu/riscv_common/Makefile.features
adds CPU_ARCH information to riscv_common similar to arm / mips / xtensa
> cpu/riscv: add CPU_ARCH information

- sys/auto_init/auto_init.c
This change switch the gnrc ipv6 and tcp typed from void to kenrel_pid_t and int respectively in auto init.
> sys/auto_init: change gnrc ipv6 and tcp types.

- sys/include/net/sock/tcp.h
`sock_tcp_read()` will return 0 if the connection was closed, we need to check for this.
https://github.com/RIOT-OS/RIOT/pull/16494#issuecomment-899027401
> sock: tcp: fix sock_tcp_read() example

- sys/riotboot/slot.c
`sys/riotboot/slot.c` is using e.g., `uint32_t`, but was missing the header for that.
It seems to be included in some dependency header, but still...
> sys/riotboot: add missing "inttypes.h" include

- drivers/Makefile.dep
- drivers/include/lpsxxx.h
- drivers/lpsxxx/Kconfig
- drivers/lpsxxx/include/lpsxxx_internal.h
- drivers/lpsxxx/include/lpsxxx_params.h
- drivers/lpsxxx/lpsxxx.c
- drivers/lpsxxx/lpsxxx_saul.c
- makefiles/pseudomodules.inc.mk
- tests/driver_lpsxxx/README.md
- tests/driver_lpsxxx/main.c
I added support for the [LPS22HH](https://www.st.com/en/mems-and-sensors/lps22hh.html) pressure sensor based on the already supported LPS22HB.
There are a few differences in the register mappings and two new sample rates.
I flashed `tests/driver_lpsxxx` on a nrf52840dk with an X-NUCLEO-IKS01A3 (which includes an LPS22HH sensor). It successfully printed sensor readings:
```
2021-09-22 17:34:23,074 # Pressure value: 1021hPa - Temperature: 26.37°C
2021-09-22 17:34:24,009 # Pressure value: 1021hPa - Temperature: 26.37°C
2021-09-22 17:34:25,013 # Pressure value: 1021hPa - Temperature: 26.37°C
2021-09-22 17:34:26,017 # Pressure value: 1021hPa - Temperature: 26.37°C
2021-09-22 17:34:27,020 # Pressure value: 1021hPa - Temperature: 26.36°C
2021-09-22 17:34:28,024 # Pressure value: 1021hPa - …
```
> drivers/lpsxxx: add support for lps22hh

- cpu/stm32/cpu_common.c
Added `apbmul` array entry for APB12, which is used on several STM32G and L series boards.
Loaded to an STM32G030 board and verified that TIM1 (on APB12 bus) was operating at the desired frequency, which was only achievable if the APB12 bus multiplier was set to 2.
> added APB12 bus multiplier entry for applicable cpus

- pkg/nimble/netif/nimble_netif_conn.c
Straight forward bug fix: the validity check for `nimble_netif_conn_get_itvl_ms()` should test for a handle value < 0, as `0` is actually a valid input value...
Compile test and code review should do the trick here, as this line is (not yet) used anywhere in RIOT... 
none
> nimble/netif_conn: fix _conn_get_itvl_ms()

- sys/event/thread.c
I've gotten many times scared by having the impression that my event thread is completely collapsed, but it's just because it's the only one not initialized with STACKTEST. This  PR changes the behaviour so its is.
If there is some value in making it configurable I can.
Run an application with a shell and `USEMODULE="ps event_thread"`
before:
```
main(): This is RIOT! (Version: 2021.10-devel-492-g719a1-HEAD)
test_shell.
> ps
ps
pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
- | isr_stack            | -        - |   - |   8192 (   -1) ( 8193) | 0x5661a720 | 0x5661a720
1 | idle                 | pending  Q |  15 |   8192 (  436) ( 7756) | 0x56613020 | 0x56614e7c 
2 | main                 | running  Q |   7 |  12288 ( 3020) ( 9268) | …
```
> sys/event/thread: add STACKSTEST flag

- boards/nucleo-g070rb/Kconfig
- boards/nucleo-g070rb/Makefile.features
- boards/nucleo-g070rb/include/periph_conf.h
- boards/nucleo-g071rb/Kconfig
- boards/nucleo-g071rb/Makefile.features
- boards/nucleo-g071rb/include/periph_conf.h
- cpu/stm32/periph/Makefile
- cpu/stm32/periph/adc_f0_g0.c
Adding ADC functionality for STM32 G0 series MCUs.
Verify calls to `adc_init` and `adc_sample` are compilable and linkable.
> cpu/stm32: added ADC for g0

- Makefile.include
If the repository was checked out without tags, parsing `RIOT_VERSION` will fail.
Fall back to creating a fake release version code based on the current year and month.
Release tests should be working again.
> build system: add fallback for RIOT_VERSION_CODE

- makefiles/pseudomodules.inc.mk
- sys/Kconfig
- sys/Makefile.dep
- sys/random/Kconfig
- sys/random/fortuna.c
- sys/random/fortuna/fortuna.c
- sys/random/fortuna/fortuna.h
- tests/bench_sys_atomic_utils/app.config.test
- tests/sys_atomic_utils/app.config.test
- tests/sys_atomic_utils_unittests/app.config.test
`fortuna` suggests a 100ms reseed interval, therefore msec resolution should be enough for the reseed value which. This PR also uses a timer to set a flag when a reseed is necessary this allows using `ztimer` without the need of including `now64` and ticks an item off https://github.com/RIOT-OS/RIOT/issues/13667.
To do that I realized that Fortuna is actually relying on an xtimer call before the module is initialized, therefore I had to move timer initialization up, I'll split this part out.
I applied the following patch:
```diff
diff --git a/examples/hello-world/Makefile b/examples/hello-world/Makefile
index 258d8e9baf..f389bea7ca 100644
--- a/examples/hello-world/Makefile
+++ b/examples/hello-world/Makefile
@@ -15,4 +15,11 @@ DEVELHELP ?= 1
QUIET ?= 1
+USEMODULE += xtimer
+USEMODULE += …
```
> sys/random/fortuna: change interval ressed to ms

- tests/gnrc_dhcpv6_client/dhcpv6_server.sh
Polly needs to die ;-).
Re-issuing `make -C tests/gnrc_dhcpv6_client` multiple times should now restart a new Kea session with the old one being killed (can be seen by a `DHCP6_SHUTDOWN server shutdown` in the output).
Follow-up for #16796 and #16797
> tests/gnrc_dhcpv6_client: kill potential previous Kea session

- cpu/stm32/stm32_mem_lengths.mk
Add definition of RAM_LEN for G03x STM32 MCUs.
Without this, compliation failed b/c of undefined RAM_LEN.
> cpu/stm32: added RAM_LEN identifier for stm32g03x

- cpu/avr8_common/Makefile.include
tests/thread_float should no report correct output
Fixes https://github.com/RIOT-OS/RIOT/issues/16896
> cpu/avr8_common: implement printf_float

- sys/Makefile.dep
- tests/ieee802154_submac/Makefile
- tests/ieee802154_submac/main.c
This PR removes the netdev dependency from `tests/ieee802154_submac`. From now on, there's no dependency to `netdev` from the submac. 
I also cleaned the code a bit and replaced xtimer by ztimer.
Sending and receiving frames with `tests/ieee802154_submac` should work. Here are my tests results:
```
2021-09-08 17:52:20,032 # txt: Lorem ipsu
2021-09-08 17:52:20,034 # RSSI: 134, LQI: 164
2021-09-08 17:52:20,035 # 
2021-09-08 17:52:20,151 # 
2021-09-08 17:52:20,152 # DATA
2021-09-08 17:52:20,157 # Dest. PAN: 0x0023, Dest. addr.: de:82:3e:96:37:07:21:33
2021-09-08 17:52:20,162 # Src. PAN: 0x0023, Src. addr.: ae:8d:fe:e1:60:89:37:c4
2021-09-08 17:52:20,167 # Security: 0, Frame pend.: 0, ACK req.: 1, PAN comp.: 1
2021-09-08 17:52:20,168 # Version: 1, Seq.: 7
2021-09-08 17:52:20,173 # 00000000 …
```
> tests/ieee802154_submac: remove netdev dependency

- pkg/tinydtls/contrib/sock_dtls.c
For global addresses, the out-going interface is typically decided by the forwarding information base, so _requiring_ the user to set it with `sock_dtls` is undesirable. This has the caveat, that now on `sock_udp_send()` in the `_write()` method, the sock does not know via which network interface to send a packet with a global address, but again: this is really more a task for the underlying network stack, not the sock layer.
I used `tests/pkg_tinydtls_sock_async` to test this. I needed to restart both applications between sending to global and link-local, as the server otherwise runs into an assert. But that is the case on master as well (but you have to use `2001:db8::2%7` as the address there).
```console
> dtlss start 
dtlss start 
> ifconfig 7 add 2001:db8::2/64
ifconfig 7 add …
```
> tinydtls: sock_dtls: only use ifindex with link-local addresses

- cpu/avr8_common/include/cpu.h
Clang doesn't like the inline assembly of `cpu_print_last_instruction()`. The new version should be functionally equivalent, but also safe two instructions.
Kernel panics should still print the stack address.
None
> cpu/avr8_common: Clean up cpu_print_last_inscrution()

- .murdock
- pkg/pkg.mk
- pkg/yxml/Makefile
As discussed on today's weekly, this PR:
1. adds support for specifying a package mirror URL, sets that as default
2. makes murdock not use mirrors for nightlies
3. adds a mirror for yxml
> make: support package mirrors

- cpu/atmega_common/atmega_cpu.c
- cpu/atxmega/atxmega_cpu.c
core_panic() doesn't expect the message to be in program memory, but
in data memory. Bad things will happen on AVR when the address is
interpreted as being in data address space, but the allocation is
done in program address space.
The corresponding panics (and IRQ without provided ISR) should print something sensible again.
None
> cpu/{atxmega,atmega_common}: fix invalid use of PSTR()

- drivers/lm75/include/lm75_params.h
This PR just makes a minor rename cleanup change in the LM75 driver.
The I2C definition was named as `PARAMS`, changed that to `PARAM`. Aligned the definition to the other i2c definition as well.
> drivers/lm75: minor cleanup

- cpu/atmega_common/atmega_cpu.c
- cpu/atxmega/atxmega_cpu.c
core_panic() doesn't expect the message to be in program memory, but
in data memory. Bad things will happen on AVR when the address is
interpreted as being in data address space, but the allocation is
done in program address space.
The corresponding panics (and IRQ without provided ISR) should print something sensible again.
None
> cpu/{atxmega,atmega_common}: fix invalid use of PSTR() [backport 2021.10]

- pkg/emlearn/Makefile
As the title says, this PR bumps the emlearn package to the latest 0.12 release. There are no fundamental changes in this release and the test application still works as before.
- A green CI
- `tests/pkg_emlearn` works:
<details>
```
BUILD_IN_DOCKER=1 make -C tests/pkg_emlearn/ all test --no-print-directory  …
```
> pkg/emlearn: bump to 0.12

- pkg/jerryscript/Makefile
- pkg/jerryscript/Makefile.dep
- pkg/jerryscript/Makefile.include
This PR bumps the jerryscript package to [version 2.4](https://github.com/jerryscript-project/jerryscript/releases/tag/v2.4.0).
Some minor things had to be adapted in the build system to fix the build. Then I noticed that by default there was a **100KB increase** on flash. This can be fixed by setting the `JERRY_PROFILE` variable to `minimal` (set as default in RIOT), the default in Jerryscript being set to `es.next` which supports more javascript features but seems to increase significantly flash memory usage. This variable can be configured so users can try other ES profiles.
See below for test outputs. On nrf52840dk compared to master, this PR shaves 63KB (from 154KB to 91KB).
- Green CI
- `examples/javascript` works on native:
<details>
```
$ BUILD_IN_DOCKER=1 RIOT_CI_BUILD=1 make -C …
```
> pkg/jerryscript: bump to 2.4.0

- drivers/w5100/w5100.c
drivers/w5100/w5100.c
fix w5100's TX_WR register's value. Let the value exceed 0x2000.
Fixes #16417
> drivers/w5100/w5100.c: fix TX_WR register's value

- pkg/hacl/Makefile
hacl is a pkg we already use in mirrored mode since the upstream went away. So far, @benpicco has persisted a copy of that repository, and there is no indication it'd go away -- this is primarily to set a precedent for the next repo where there is not already a good upstream.
This commit itself keeps Ben's repository as the main pkg_url, and sets https://github.com/RIOT-OS-pkgmirror/hacl-c_archived as the mirror URL using the mechanism introduced in #16927.
Had we used the pkgmirror concept already, it'd have been a great fit -- but what'd we do when upstream goes away for good? Right now, if the upstream goes away the PR builds keep working, but the nightlies start failing because there the original URLs are used.
So in a situation like this (assuming that the upstream mirror would be …
> hacl: Switch git address to RIOT-OS-pkgmirror

- cpu/cc2538/include/cc2538_rf.h
- cpu/cc2538/radio/cc2538_rf.c
- cpu/cc2538/radio/cc2538_rf_radio_ops.c
This PR removes the RX Busy detection because it doesn't seem to be reliable enough to ensure the radio is not locked. 
For instance, some SFDs and FRAME_ACCEPTED are generated without an RX_DONE in between:
```
2021-09-07 12:06:56,883 # Last 16 IRQs:
2021-09-07 12:06:56,884 # SFD 
2021-09-07 12:06:56,884 # FRAME_ACCEPTED 
2021-09-07 12:06:56,884 # SFD 
2021-09-07 12:06:56,884 # TXDONE 
2021-09-07 12:06:56,884 # SFD 
2021-09-07 12:06:56,884 # CSP_STOP
2021-09-07 12:06:56,884 # SFD 
2021-09-07 12:06:56,885 # TXDONE 
2021-09-07 12:06:56,885 # SFD 
2021-09-07 12:06:56,885 # CSP_STOP
2021-09-07 12:06:56,885 # TXACKDONE 
2021-09-07 12:06:56,885 # SFD 
2021-09-07 12:06:56,885 # RXPKTDONE 
2021-09-07 12:06:56,886 # FRAME_ACCEPTED 
2021-09-07 12:06:56,886 # SFD 
2021-09-07 12:06:56,886 # …
```
> cc2538_rf: remove RX Busy detection in request_set_trx_state

- sys/include/net/gnrc/ipv6/nib/conf.h
- sys/net/gnrc/network_layer/ipv6/nib/Kconfig
When probing for an unknown neighbor, the NIB on a 6LoWPAN border router currently drops the packet that triggered that probing in accordance with RFC 6775. However, it also does that on the upstream interface, as queuing support is removed at compile-time altogether. This adds an exception to the compile-time config 
Try to ping an Internet host via a border router from a 6LoWPAN host (see e.g. [Task 8.5](https://github.com/RIOT-OS/Release-Specs/tree/master/08-interop#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router) of the release specs). The first message should go through with this PR, without it, the message  will get lost.
None, but the issue in https://github.com/RIOT-OS/RIOT/issues/11988 might be related.
> gnrc_ipv6_nib: queue packets that trigger probing on border router

- .murdock
- cpu/fe310/Kconfig
- cpu/fe310/periph/Kconfig
- cpu/fe310/vendor/Kconfig
- cpu/gd32v/Kconfig
- cpu/gd32v/periph/Kconfig
- cpu/riscv_common/Kconfig
- cpu/riscv_common/periph/Kconfig
- makefiles/features_modules.inc.mk
- sys/Kconfig
- sys/Kconfig.newlib
- sys/Kconfig.picolibc
- sys/Kconfig.stdio
- sys/ztimer/Makefile.dep
This models the Kconfig modules for risc-v and adds two boards for the CI tests. For this I had to model libc modules, I'd like some feedback on those.
- CI should take care of comparing binaries.
- Check list of modules compiled with and without Kconfig
#16875
> cpu/riscv: model Kconfig

- Makefile.base
As explained in #16942, since #14754 we select all object files when linking, which is a problem when the selection of module sources change between two builds. This adds a cleanup for non selected source object files on modules.
A minimal example that shows the current issue:
```diff
diff --git a/tests/external_module_dirs/Makefile b/tests/external_module_dirs/Makefile
index f44d1e3e8e..f4a82e6c16 100644
--- a/tests/external_module_dirs/Makefile
+++ b/tests/external_module_dirs/Makefile
@@ -4,4 +4,6 @@ USEMODULE += random
USEMODULE += external_module
EXTERNAL_MODULE_DIRS += external_modules
+USEMODULE += external_module_implementation_a
+
diff --git a/tests/external_module_dirs/external_modules/external_module/Makefile …
```
> Makefile.base: cleanup non selected source object files

- drivers/include/net/netdev.h
- tests/driver_at86rf215/Makefile
- tests/driver_at86rf215/main.c
This PR is an alternative to #16921 but more generic (as proposed by @benpicco ).
It adds a callback mechanism to indicate the upper layer that a netdev device finished its setup/registration procedure.
This function can be used as a post_setup hook to do clock configuration or trimming, without requiring to get the private descriptor through the network interface (without this PR the device descriptor is retrieved with gnrc_netif_get_by_type).
This PR is required to remove the GNRC<->netdev dependency, because it won't be guaranteed that the device descriptor of GNRC netif points to a netdev device.
Compile test should be enough.
Alternative to #16921
> netdev: add netdev_register_signal

- boards/nucleo-g070rb/include/periph_conf.h
- boards/nucleo-g071rb/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
This PR fixes some doxygen warnings, and adds the remaining patterns that focal's doxygen still complains.
~~For future use, a commit also adds a script to create the patterns from doxygen warnings, with the logic taken from https://github.com/RIOT-OS/RIOT/pull/16779#issue-980190050.~~ (split out into #17082)
CI should be fine.
https://github.com/RIOT-OS/riotdocker/pull/104
> boards/nucleo-g07xrb: fix or exclude some doxygen warnings [backport 2021.10]

- dist/tools/doccheck/exclude_patterns
This adds new Doxygen warnings to the exclude pattern.
Static tests should pass.
> dist/tools/doccheck/exclude_patterns: add new warnings

- sys/usb/usbus/cdc/acm/cdc_acm.c
The SetLineCoding request is optional to support (CDC PSTN subclass). No
need to claim to support it to the host and actually discard the data if
it is not supported by the implementation.
Running the `tests/usbus_cdc_acm_stdio/` case, use a serial console to change the baud rate. This should still work. Bonus points for sniffing the USB traffic with wireshark, that should look like this:
Main thing is the "Broken pipe" in the reply packet which indicates a stall from the device side.
None
> usbus/cdc_acm: Return stall on line coding not supported

- sys/shell/commands/sc_gnrc_netif.c
Currently a valid netif name must be passed to show the usage
instructions:
```
> ifconfig help
error: invalid interface given
> ifconfig 6 help
usage: ifconfig
usage: ifconfig <if_id> [up|down]
[...]
```
Flash an app using GNRC and shell (like `examples/gnrc_networking`), and run `ifconfig help`
> sys/shell/gnrc_netif: Allow 'ifconfig help'

- boards/common/silabs/Makefile.dep
The module silabs_pic depends on the feature periph_i2c. However, the
dependency resolution just selected the module implementing that
feature which bypasses feature checks.
E.g. add `FEATURES_BLACKLIST += periph_i2c` to the `Makefile` of `examples/default` and check if it now fails to build, which is not the case in `master`.
Bug detected in https://github.com/RIOT-OS/RIOT/pull/17076
> boards/common/silabs: fix dependencies

- pkg/wakaama/Makefile.dep
- pkg/wakaama/contrib/lwm2m_platform.c
This changes the platform adaption for Wakaama to use ztimer (`ZTIMER_SEC`) instead of xtimer.
- The example application should work as usual. Nodes should update their registration before it expires.
Ticks an item of #13667
> pkg/wakaama: use ztimer

- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
As mentioned in https://github.com/RIOT-OS/RIOT/pull/17099 auto-select rtc for `ztimer_sec` done in https://github.com/RIOT-OS/RIOT/pull/16909 seems to not be a good idea, this reverts that change while still preferring `rtt` over `periph_timer`.
> sys/ztimer: don't default to rtc for ztimer_sec

- drivers/include/xbee.h
- drivers/xbee/Makefile.dep
- drivers/xbee/include/xbee_params.h
- drivers/xbee/xbee.c
- tests/driver_netdev_common/main.c
- tests/driver_xbee/Makefile
This PR makes `xbee` use `ztimer_msec` instead of `xtimer`.
I ran the release test spec between `arduino_zero` + `xbee` and `samr21-xpro`
- master
```
2021-11-02 16:59:24,939 # 58 bytes from fe80::213:a200:40c2:d4c4%6: icmp_seq=999 ttl=64 rssi=-52 dBm time=171.931 ms
2021-11-02 16:59:25,759 #
2021-11-02 16:59:25,763 # --- fe80::213:a200:40c2:d4c4 PING statistics ---
2021-11-02 16:59:25,768 # 1000 packets transmitted, 963 packets received, 3% packet loss
2021-11-02 16:59:25,773 # round-trip min/avg/max = 170.971/172.520/213.558 ms
```
- pr
```
2021-11-02 16:56:06,125 #
2021-11-02 16:56:06,129 # --- fe80::213:a200:40c2:d4c4 PING statistics ---
2021-11-02 16:56:06,135 # 1000 packets transmitted, 965 packets received, 3% packet loss
2021-11-02 16:56:06,140 # round-trip min/avg/max = …
```
> drivers/xbee: migrate to ztimer_msec

- SECURITY.md
the `mailto` was missing in the following reference: `The issue will be tracked in the [security mailing list](mailto:security@riot-os.org).`
follow the reference in "security mailing list".
> SECURITY.md: fix broken email reference

- makefiles/stdio.inc.mk
- sys/stdio_semihosting/stdio_semihosting.c
Convert stdio_semihosting to ztimer
Tested on the samr21-xpro by adding `USEMODULE += stdio_semihosting` to the default example:
```Shellsession
koen@morgen ~/dev/RIOT-review $ make -C examples/default/ BOARD=samr21-xpro term RIOT_TERMINAL=semihosting
make: Entering directory '/home/koen/dev/RIOT-review/examples/default'
/home/koen/dev/RIOT-review/dist/tools/openocd/openocd.sh debug /home/koen/dev/RIOT-review/examples/default/bin/samr21-xpro/default.elf 
Reading symbols from /home/koen/dev/RIOT-review/examples/default/bin/samr21-xpro/default.elf...
Open On-Chip Debugger 0.11.0+dev-gd2928fa86 (2021-10-26-12:15)
Remote debugging using :3333
0xfffffffe in ?? ()
(gdb) run
The program being debugged has …
```
> stdio_semihosting: Convert to ztimer

- pkg/semtech-loramac/contrib/semtech_loramac_getset.c
This PR fixes the issue reported in #17056. For the get/set the default values where being fetched.
See testing procedure in #17056:
```
2021-11-02 21:56:44,254 # main(): This is RIOT! (Version: 2022.01-devel-322-g49cec-HEAD)
2021-11-02 21:56:44,256 # All up, running the shell now
> loramac join otaa
2021-11-02 21:56:47,804 # loramac join otaa
2021-11-02 21:56:56,172 # Join procedure succeeded!
loramac link_check
2021-11-02 21:57:02,469 # loramac link_check
2021-11-02 21:57:02,471 # Link check request scheduled
loramac tx This\ is\ RIOT! cnf 2
2021-11-02 21:57:04,975 # loramac tx This\ is\ RIOT! cnf 2
2021-11-02 21:57:13,000 # Link check information:
2021-11-02 21:57:13,002 #   - Demodulation margin: 27
2021-11-02 21:57:13,005 #   - Number of gateways: 2
2021-11-02 21:57:13,007 # Received …
```
> pkg/semtech-loramac: fix get/set dr command

- pkg/wolfssl/Makefile.dep
- pkg/wolfssl/Makefile.wolfcrypt
This PR fixes a couple of minor issues with the wolfssl package:
- remove an unnecessary dependency to xtimer with `wolfcrypt-benchmark`. Xtimer is only used by the `tests/pkg_wolfssl` test application which is pulling it itself
- Fix a compilation error with gcc 11 on native
- Green CI
- `tests/pkg_wolfssl` is still working:
<details>
```
$ make -C tests/pkg_wolfssl all test --no-print-directory 
Building application "tests_pkg_wolfssl" for "native" with MCU "native".
"make" -C /work/riot/RIOT/pkg/wolfssl
"make" -C /work/riot/RIOT/build/pkg/wolfssl/wolfcrypt/src -f /work/riot/RIOT/pkg/wolfssl/Makefile.wolfcrypt
"make" -C /work/riot/RIOT/build/pkg/wolfssl/wolfcrypt/benchmark -f /work/riot/RIOT/pkg/wolfssl/Makefile.wolfcrypt-benchmark
"make" -C …
```
> pkg/wolfssl: fix minor issues

- sys/usb/usbus/dfu/dfu.c
This PR fixes an underflow condition which can occurs if host sends less than 4 bytes of data during a DFU download operation.
While loading a new firmware through a `DFU_DNLOAD` request, DFU skips the `RIOTBOOT_FLASHWRITE_SKIPLEN` bytes as we don't need them in flash. This skip wasn't guarded so if the`DFU_DNLOAD` request contains less than `RIOTBOOT_FLASHWRITE_SKIPLEN` bytes, an underflow integer occurs with unexpected behaviour. Thus, add a proper check to prevent this situation from happening by stalling the request if it has less than `RIOTBOOT_FLASHWRITE_SKIPLEN` bytes of data.
edit:
The internal DFU state machine was also updated and will now returns dfuERROR in case of failure (underflow or flash write failure) to the host (through GET_STATUS request).
A new request handling was …
> usbus/dfu: fix underflow condition while updating firmware

- examples/gcoap/Makefile
adds the possibility to easily build  the gcoap example with LWIP
`LWIP=1 make -C examples/gcoap`
and use  like described in `examples/gcoap/README.md`
used these lines while testing #16378
> example/gcoap: add LWIP make option

- drivers/bmp180/Kconfig
- drivers/bmp180/Makefile.dep
- drivers/bmp180/bmp180.c
- drivers/bmp180/bmp180_saul.c
- drivers/bmp180/include/bmp180_internals.h
- tests/driver_bmp180/Makefile
- tests/driver_bmp180/app.config.test
- tests/driver_bmp180/main.c
This PR migrates the bmp180 driver implementation to ztimer. I'm not sure about the Kconfig part.
- Test application is still functional (but I don't have the hardware for testing...)
> drivers/bmp180: migrate to ztimer

- sys/usb/usbus/hid/hid.c
This fixes a possible null pointer dereference in the USBUS HID code by always supplying an argument to the `_gen_hid_descriptor` function
Not sure what the best way is to trigger the issue though.
Pointed out by cppcheck
> usbus_hid: Fix possible null pointer dereference

- drivers/include/rn2xx3.h
- drivers/rn2xx3/Kconfig
- drivers/rn2xx3/Makefile.dep
- drivers/rn2xx3/include/rn2xx3_params.h
- drivers/rn2xx3/rn2xx3.c
- drivers/rn2xx3/rn2xx3_internal.c
This PR migrates the rn2xx3 lora driver to ztimer. Like in #17105 there are use of ticks conversion not directly available in ztimer.
- Driver is still functional (I might be able to test this by the end of this week and will report there)
#17111
> drivers/rn2xx3: migrate to ztimer

- cpu/nrf52/periph/usbdev.c
- cpu/sam0_common/periph/usbdev.c
- drivers/usbdev_mock/usbdev_mock.c
- sys/include/usb/usbopt.h
- sys/usb/usbus/cdc/acm/cdc_acm.c
- tests/usbus/main.c
This PR collects and fixes the current set of static-check warnings and errors with USB-related files
Check the changes, only the sam0_common usb device had a change that will be reflected in the binary (deduplicated a write to a register). The other changes should be only cosmetic.
The static-checks should be happy after this PR
Required for all other usbdev PRs
> usb(dev|bus): Fix static-check issues

- core/include/sched.h
- core/include/thread.h
- core/sched.c
- core/thread.c
- cpu/esp_common/thread_arch.c
- tests/bench_sizeof_coretypes/main.c
- tests/driver_dose/Makefile.ci
- tests/gnrc_sixlowpan_frag_minfwd/Makefile.ci
I've run into this trap now often enough that I'd like to have a warning about stack overflows, at least with `DEVELHELP`. If *I* still run into this trap, how must newcomers feel.
Try causing a stack overflow, the scheduler should warn you about it now when compiled with DEVELHELP (and `SCHED_TEST_STACK` unset).
None
> core: make SCHED_TEST_STACK boolean and default to 1 with DEVELHELP

- drivers/include/periph/gpio.h
This allows us to use `assert(cb != NULL)` inside `gpio_init_int()` and save a few cycles of interrupt latency.
https://github.com/RIOT-OS/RIOT/pull/17007#discussion_r731257586
> drivers/periph/gpio: state that interrupt callback must not be NULL

- boards/stk3200/include/periph_conf.h
The spi bus for the stk3200 doesn't actually work.
Other efm32 based boards do work.
After some guessing and some checking it turns out that the .loc is wrong.
The original was USART_ROUTE_LOCATION_LOC1, which appears in other periph_conf.
After changing it to USART_ROUTE_LOCATION_LOC2 the spi bus actually outputs data.
loopback on the board and run the `tests/periph_spi` with some values or just check the HiL results...
> boards/stk3200: Fix spi config

- drivers/ata8520e/Kconfig
- drivers/ata8520e/Makefile.dep
- drivers/ata8520e/ata8520e.c
- drivers/include/ata8520e.h
This PR migrates the ata8520e driver (for SigFox) to ztimer. It's still untested, and I don't know how to test it TBH since my SigFox test account has expired  for quite some time now.
The migration is not straight forward since there's some timer based logic to wait for an event from the driver. I tried to adapt it but it seems to me that there are no ztimer equivalent to all xtimer functions used there.
- The driver is still functional
#17111
> drivers/ata8520e: migrate to ztimer

- core/include/kernel_defines.h
- tests/unittests/tests-kernel_defines/tests-kernel_defines.c
It can be quite useful to have a macro to get the index of an element in an array.
Instead of open-coding it, add a macro to `kernel_defines.h` so that everyone can use it without code duplication.
> core/include/kernel_defines.h: add index_of() macro

- cpu/sam0_common/periph/gpio.c
This PR fixes the issue reported by @biboc with #16978 
With this PR, disabled GPIO IRQs are no longer trigger by another (enabled) GPIO IRQ.
At the same time, ensure callback are defined before calling it and replace some computation with a mask.
I tested the following boards with master and this PR:
- saml10-xpro (Fixed by this PR)
- saml21-xpro (Fixed by this PR)
- same54-xpro (Not affected by #16978 because each GPIO irqs lines have a dedicated IRQ)
- arduino-zero (Fixed by this PR)
See #16978 
Fixes #16978 
Thanks @biboc for spotting this !
> cpu/sam0: prevent disabled irq from being called

- makefiles/arch/riscv.inc.mk
This is an attempt at resolving a catch-22 situation.
Currently riotdocker installs `riscv-none-embed-gcc`. We want to move to `riscv64-unknown-elf` as provided by Debian.
But the Debian toolchain includes no newlib, there is only picolibc.
We can transition to picolibc by default on RISC-V too, but in order to get the riotdocker changes in, it must still build with the old RISC-V toolchain.
Then we can [enable picolibc support](https://github.com/RIOT-OS/RIOT/blob/master/cpu/riscv_common/Makefile.features#L13) in RIOT and switch to the new toolchain.
For this, the old toolchain triple has to take precedence over the new one if both are installed.
> makefiles: RISC-V: prefer target triple from riotdocker

- makefiles/arch/riscv.inc.mk
This is an attempt at resolving a catch-22 situation.
Currently riotdocker installs `riscv-none-embed-gcc`. We want to move to `riscv64-unknown-elf` as provided by Debian.
But the Debian toolchain includes no newlib, there is only picolibc.
We can transition to picolibc by default on RISC-V too, but in order to get the riotdocker changes in, it must still build with the old RISC-V toolchain.
Then we can [enable picolibc support](https://github.com/RIOT-OS/RIOT/blob/master/cpu/riscv_common/Makefile.features#L13) in RIOT and switch to the new toolchain.
For this, the old toolchain triple has to take precedence over the new one if both are installed.
> makefiles: RISC-V: prefer target triple from riotdocker [backport 2021.10]

- core/include/kernel_defines.h
Calculate the size of the element based on the array given, not based on the element pointer.
The element might as well be given as a `void *` via a callback.
In that case, if the user forgets to cast the `void *` to the array element type, the calculation returns false values.
Disarm this foot gun by basing the element size off the given array.
> core/include/kernel_defines.h: Fix index_of()

- pkg/arduino_sdi_12/Makefile.dep
- pkg/arduino_sdi_12/patches/0002-Integration-with-RIOT-to-support-other-boards.patch
- sys/arduino/include/arduino.hpp
- tests/pkg_arduino_sdi_12/Makefile
- tests/pkg_arduino_sdi_12/Makefile.ci
Add support for the `remote-revb` board to the `arduino_sdi_12` package.
Testing that the test program builds:
BOARD=remote-revb make -C tests/pkg_arduino_sdi_12/
This is a test I've done using RE-Mote board and the Decagon CTD-10 sensor:
```
$ BOARD=remote-revb make -C tests/pkg_arduino_sdi_12/ all flash term
[...]
Building application "tests_pkg_arduino_sdi_12" for "remote-revb" with MCU "cc2538".
[...]
2021-11-03 08:50:49,480 # main(): This is RIOT! (Version: 2022.01-devel-338-gb2761-sdi12-remote)
2021-11-03 08:50:49,480 # Testing the Arduino-SDI-12 package
2021-11-03 08:50:49,480 # 
2021-11-03 08:50:49,481 # Send: ?!
2021-11-03 08:50:49,695 # Recv: 0
2021-11-03 08:50:49,695 # Send: 0I!
2021-11-03 08:50:50,046 # Recv: 013DECAGON …
```
> pkg/arduino_sdi_12: support the remote-revb board

- tests/lwip_sock_ip/stack.c
- tests/lwip_sock_udp/stack.c
Lock lwIP before adding static entry to etharp (fixing assert)
`BOARD=native LWIP_IPV6=0 LWIP_IPV4=1 make -C tests/lwip_sock_ip/ clean flash test -j`
`BOARD=native LWIP_IPV6=0 LWIP_IPV4=1 make -C tests/lwip_sock_udp/ clean flash test -j`
Fixes #17144
> tests/lwip_sock: Take lock before calling etharp

- .murdock
Current .murdock is using `redis-cli` with the default host setting of `127.0.0.1`.
I'm building a docker-compose version of `redis-cli` which runs the ssh tunnel in an extra container. That needs passing to `redis-cli`, which this PR does.
I've tested this manually, here's output from `beast` (running the docker-compose worker) with a commit printing the used value when set to "ssh_bridge" as default:
<details>
```
riot on  murdock_redis_host via ⍱ took 54s 
❯ dwqc -q beast -E RUN_TESTS=1 "./.murdock compile tests/fmt_print samr21-xpro:gcc"                                                                
MURDOCK_REDIS_HOST=ssh_bridge                                                                                                                      
-- running on worker beast thread 1, …
```
> murdock: allow specifying redis host

- drivers/include/lis3dh.h
The bogus packed attribute added to lis3dh_data_t resulted in the structure being aligned two 1 byte. It was later casted to an `uint16_t` pointer (which is aligned two 2 bytes). By dropping the packed attribute the alignment mismatch is fixed.
Except for potential crashes on architectures that do not support unaligned memory access that this fixes, the driver should work as before.
> drivers/lis3dh: fix unaligned memory access

- sys/include/net/dns/msg.h
This structure is used to parse data from unaligned buffers, so make sure the compiler issues instructions suitable for unaligned memory access.
sock_dns should now work reliably on platforms that do not support unaligned memory access.
> sys/net/dns: mark dns_hdr_t as packed

- drivers/encx24j600/encx24j600.c
This should prevent crashes on platforms that do not support unaligned memory accesses.
> drivers/encx24j600: fix unaligned memory access

- cpu/esp_common/periph/flash.c
This should make sure that the buffer never gets allocated at an address not suitable for 32 bit reads / writes, which I believe would have cause hard faults on Xtensa.
> cpu/esp_common: fix unaligned access in periph_flashpage

- boards/lora-e5-dev/Kconfig
- boards/lora-e5-dev/Makefile.dep
- boards/lora-e5-dev/board.c
- boards/lora-e5-dev/include/board.h
While trying to fix #17052, I realized that when connecting  groove sensor the power led did not turn on, when checking the [schematic](https://files.seeedstudio.com/products/113990934/LoRa-E5%20Dev%20Board%20v1.0.pdf) I realized two GPIO's enable/disable 3.3V and 5V output. This being disabled was the only reason why i2c was not working and therefore the lm75 sensor.
`BOARD=lora-e5-dev make -C tests/saul/ clean flash term -j`
```
2021-11-07 18:52:39,010 # ##########################
2021-11-07 18:52:39,991 # 
2021-11-07 18:52:39,992 # Dev: LED(red)	Type: ACT_SWITCH
2021-11-07 18:52:39,992 # Data:	              1 
2021-11-07 18:52:39,992 # 
2021-11-07 18:52:39,997 # Dev: Button(B1 Boot)	Type: SENSE_BTN
2021-11-07 18:52:39,998 # Data:	              0 
2021-11-07 18:52:39,998 # 
2021-11-07 …
```
> boards/lora-e5-dev: enable 3.3V and 5V output by default

- sys/net/application_layer/uhcp/uhcp.c
- sys/net/application_layer/uhcp/uhcpc.c
uhcp is pretty noisy compared to DHCPv6 as INFO log level is enabled by default.
Tone it down to LOG_DEBUG to keep the output clean.
Run `examples/gnrc_border_router`.
The console should no longer be spammed with output from uhcp.
> sys/net/uhcp: use LOG_DEBUG instead of LOG_INFO

- pkg/littlefs/fs/littlefs_fs.c
- pkg/littlefs2/fs/littlefs2_fs.c
The generated binaries should remain identical to before, but compilation with `-Wcast-align` won't fail.
> pkg/littlefs{,2}: fix compilation with -Wcast-align

- drivers/dose/dose.c
- drivers/dose/include/dose_params.h
- drivers/include/dose.h
Some CAN transceivers have a standby pin that has to be pulled low in order to use it.
If the interface is disabled we can set it to high again to save some power.
> drivers/dose: enable standby pin

- tests/thread_float/Makefile
- tests/thread_float/README.md
- tests/thread_float/main.c
- tests/thread_float/tests/01-run.py
- Perform the same computation over and over again. If the results differ, context switches have an impact on the calculation (e.g. when the FPU internally uses more bits than a float, but that bits are not saved / restored on context switch)
- Give the three threads the names "t1", "t2", and "t3" and print them on console, instead of the process ID. This makes interpretation of the output easier, as the process IDs depend e.g. on whether a given platforms requires an idle thread or not.
- Do not use the thread ID in the calculation, but the number at the end of the thread name. This will result in the number printed only depending on the precision of the (software) FPU and the printf() implementation, and not on which threads are created in which order (including the idle thread)
- Add a …
> tests/thread_float: improve and add script

- drivers/ccs811/doc.txt
This PR fixes the broken HTML output for the CCS811 driver:
https://doc.riot-os.org/group__drivers__ccs811.html
In detail, it
- replaces HTML anchor tags in markdown headings by markdown heading IDs,
- replaces heading IDs by more unique identifiers,
- defines stable references to driver documentation,
- replaces the TOC link in headers by a back to TOC link below each section,
- replaces ``` fenced code blocks by ~~~,
Doxygen should generate correct HTML output for
https://doc.riot-os.org/group__drivers__ccs811.html
Same issues were fixed in PR #16985 and #16952.
> drivers/ccs811: fix of documentation

- drivers/include/ds18.h
> drivers/ds18.h: add missing stdint.h include

- dist/tools/uhcpd/Makefile
- sys/net/application_layer/uhcp/Makefile
- sys/net/application_layer/uhcp/uhcp.c
Previously, this used plain defines. This makes it make use of "MODULE_UHCPx" defines.
Confirm `tests/gnrc_border_router` still gets an address, which would show that both host and RIOT side compile in the necessary bits.
> net/uhcp[cd]: use modules to select client/server code

- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/lwip/include/lwipopts.h
* Disable ARP if Ethernet is not used
* Use macro converting netif v6 address to `ip6_addr_t` (which is noop in v6-only setup)
`BOARD=iotlab-m3 LWIP_IPV4=1 LWIP_IPV6=1 make -C tests/lwip  -j` now works
`BOARD=iotlab-m3 LWIP_IPV4=1 make -C tests/lwip  -j` is still broken (since it disables IPv6): linking fails with `undefined reference to 'ipv6_addr_link_local_prefix'`
Part of #17162
> pkg/lwip: Fix dualstack build when only using 6lowpan

- drivers/dose/Kconfig
- drivers/dose/dose.c
- drivers/include/dose.h
A fixed timeout is either too long for high symbol rates or too short for low symbol rates.
To fix this, calculate the timeout based on the symbol rate.
For this, the old 5ms timeout is equivalent to 58 bytes being transmitted at 115200 baud (8 data bit + start & stop bit).
I rounded this to 50 bytes which should yield 4340 µs.
```
2021-08-23 13:30:48,954 # main(): This is RIOT! (Version: 2021.10-devel-406-gdbd4d5-drivers/dose-timeout_bytes)
2021-08-23 13:33:21,675 # dose dose_setup(): mac addr a6:ed:29:ec:c3:f3
2021-08-23 13:33:21,678 # dose timeout set to 4340 µs
```
> drivers/dose: calculate timeout based on symbol rate

- examples/paho-mqtt/Makefile
- examples/paho-mqtt/main.c
- pkg/paho-mqtt/Makefile.dep
- pkg/paho-mqtt/contrib/riot_iface.c
- pkg/paho-mqtt/include/paho_mqtt.h
This PR migrate the paho-mqtt package to ztimer.
- Green CI
- `examples/paho-mqtt` is still working: I was able to publish/subscribe on topics between a native instance and a local mosquitto MQTT broker.
Ticks an item in #17111
> pkg/paho-mqtt: migrate to ztimer

- pkg/nimble/autoconn/nimble_autoconn.c
- pkg/nimble/rpble/nimble_rpble.c
- pkg/nimble/scanlist/nimble_scanlist_print.c
- pkg/nimble/scanner/include/nimble_scanner.h
Turns out we have a miss-match of scan type defines used by some RIOT modules and the correct defines as intended by NimBLE in some of the nimble submodules. When scanning (`ble_gap_disc`), the NimBLE GAP APIs callback function returns the scan event type as a list of possible defines, `BLE_HCI_ADV_RPT_EVTYPE_x`. Hoever, in RIOT we are currently using the `BLE_HCI_ADV_TYPE_x` group of defines. Fortunately, this is not a big issue, as those groups are mostly identical:
```c
// from nimble/hci_common.h
#define BLE_HCI_ADV_RPT_EVTYPE_ADV_IND      (0)
#define BLE_HCI_ADV_RPT_EVTYPE_DIR_IND      (1)
#define BLE_HCI_ADV_RPT_EVTYPE_SCAN_IND     (2)
#define BLE_HCI_ADV_RPT_EVTYPE_NONCONN_IND  (3)
#define BLE_HCI_ADV_RPT_EVTYPE_SCAN_RSP     (4)
#define BLE_HCI_ADV_TYPE_ADV_IND            (0) …
```
> pkg/nimble: fix scan event type define usage

- core/include/kernel_defines.h
- tests/unittests/tests-kernel_defines/tests-kernel_defines.c
`WITHOUT_PEDANTIC(expr)` disables `-Wpedantic` for `expr`, but switches back to the previous diagnostic settings afterwards. This helps defining macros that are not strictly ISO compliant without having to drop the `-Wpedantic` flag entirely.
`DECLARE_CONSTANT(identifier, const_expr)` declares an anonymous `enum` constant named `identifier` and assigns it the value `const_expr`. Here, `const_expr` has to be a compile time constant, but is not needed to be an integer constant expression. It basically is a tool to magically convert a non-integer constant expression into a integer constant
expression.
A unit test was added to check if it works as intended. As this uses `static_assert()`, there is no need to actually run the test.
Needed by https://github.com/RIOT-OS/RIOT/pull/17177.
> core: add WITHOUT_PEDANTIC() and DECLARE_CONSTANT()
