RIOT-OS/RIOT

makefiles/pseudomodules.inc.mk
sys/include/net/gnrc/sixlowpan/frag/sfr/congure.h
sys/net/gnrc/Makefile.dep
sys/net/gnrc/network_layer/sixlowpan/frag/sfr/congure_quic.c
tests/gnrc_sixlowpan_frag_sfr_congure_impl/Makefile

This provisions GNRC's 6LoWPAN SFR implementation with the CongURE implementation of QUIC. It also adds that implementation to the `tests/gnrc_sixlowpan_frag_sfr_congure_impl` test application.
The test `tests/gnrc_sixlowpan_frag_sfr_congure_impl` where extended to support `congure_quic`:
```sh
CONGURE_IMPL=congure_quic make -C tests/gnrc_sixlowpan_frag_sfr_congure_impl
```
Ping some nodes with at least 1 hop separation with large payloads. Exchange between should work.
Depends on ~~#15952~~ (merged) and ~~#16158~~ (merged) and their respective dependencies.

gnrc_sixlowpan_frag_sfr_congure: add congure_quic support

---

makefiles/pseudomodules.inc.mk
sys/include/net/gnrc/sixlowpan/frag/sfr/congure.h
sys/net/gnrc/Makefile.dep
sys/net/gnrc/network_layer/sixlowpan/frag/sfr/congure_reno.c
tests/gnrc_sixlowpan_frag_sfr_congure_impl/Makefile

This provisions GNRC's 6LoWPAN SFR implementation with the CongURE implementation of TCP Reno. It also adds that implementation to the `tests/gnrc_sixlowpan_frag_sfr_congure_impl` test application.
The test `tests/gnrc_sixlowpan_frag_sfr_congure_impl` where extended to support `congure_abe`:
```sh
CONGURE_IMPL=congure_abe make -C tests/gnrc_sixlowpan_frag_sfr_congure_impl
```
Ping some nodes with at least 1 hop separation with large payloads. Exchange between should work.
Running the tests with `CONGURE_IMPL=congure_reno` also should still work.
Depends on ~~#15968~~ (merged) and #16170 and their respective dependencies.

gnrc_sixlowpan_frag_sfr_congure: add congure_abe support

---

sys/net/gnrc/netif/init_devs/include/init_devs.h

Since it was ported to the radio HAL, at86rf2xx requires more stack. This is a problem on AVR where the default stack is just 512 bytes:
```
2023-03-02 01:00:52,637 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current
2023-03-02 01:00:52,646 # 	  1 | idle                 | pending  Q |  15 |    192 (  130) (   62) |     0x263a |     0x269f
2023-03-02 01:00:52,655 # 	  2 | main                 | running  Q |   7 |   2560 ( 1732) (  828) |     0x26fa |     0x2cb1
2023-03-02 01:00:52,663 # 	  3 | 6lo                  | bl rx    _ |   3 |    512 (  276) (  236) |     0x5446 |     0x559b
2023-03-02 01:00:52,672 # 	  4 | ipv6                 | bl rx    _ |   4 |    512 (  372) (  140) |     0x318e |     0x32c4
2023-03-02 01:00:52,681 # 	  5 | udp …
```

gnrc_netif: set lower bound for IEEE802154_STACKSIZE_DEFAULT

---

pkg/tinydtls/Kconfig
pkg/tinydtls/Makefile
pkg/tinydtls/Makefile.include
sys/include/net/dtls.h

This adjusts two defaults in tinydtls:
* Default verbosity is set to warning. At the info level, this module produces way more output (several lines per new connection, and even per message) than is common in RIOT.
* If gcoap is used, the buffer size is adjusted to the gcoap buffer size plus overhead. Otherwise, CoAP-over-DTLS works fine until one happens to request larger resources.
* Run examples/gcoap_dtls
* Send a CoAP request from outside, eg. with `aiocoap-client 'coaps://[fe80::3c63:beff:fe85:ca96%tapbr0]/.well-known/core' --credentials testserver.json` (where testserver.json is `{"coaps://[fe80::3c63:beff:fe85:ca96%tapbr0]/*": {"dtls": {"psk": {"ascii": "secretPSK"}, "client-identity": {"ascii": "Client_identity"}}}}`).
Before, there are messages shown for every request; now there …

pkg/tinydtls: Adjust defaults

---

tests/periph_rtc/main.c
tests/periph_rtc/tests/01-run.py

while reviewing #19340 i found test/periph_rtc to be insufficient to prove rtc_set_time is working. this changes that and avoids accidental reuse of struct tm time and ms  values by resetting time and ms;
run the test
#19340

test/periph_rtc: reset struct tm time between tests

---

core/thread.c
cpu/cortexm_common/ldscripts/cortexm_base.ld
cpu/lpc23xx/ldscripts/lpc23xx.ld
cpu/riscv_common/ldscripts/riscv_base.ld
sys/picolibc_syscalls_default/syscalls.c

Minor updates to picolibc support for newer versions of picolibc, including 1.8.
Here's the current build result for a board I happen to have on my bench right now:
```
$ make -C examples/blinky BOARD=nucleo-f103rb FEATURES_REQUIRED=picolibc
...
/home/keithp/src/RIOT/sys/picolibc_syscalls_default/syscalls.c:319:1: error: unknown type name '_READ_WRITE_RETURN_TYPE'
319 | _READ_WRITE_RETURN_TYPE read(int fd, void *dest, size_t count)
| ^~~~~~~~~~~~~~~~~~~~~~~
/home/keithp/src/RIOT/sys/picolibc_syscalls_default/syscalls.c:351:1: error: unknown type name '_READ_WRITE_RETURN_TYPE'
351 | _READ_WRITE_RETURN_TYPE write(int fd, const void *src, size_t count)
| ^~~~~~~~~~~~~~~~~~~~~~~
...
```
1. Fix the read/write return values (Picolibc 1.8 uses POSIX standard types now)
2. Add new symbols to …

Picolibc updates

---

cpu/riscv_common/irq_arch.c
cpu/riscv_common/periph/plic.c
cpu/riscv_common/thread_arch.c

This PR makes use of `uword_t` type in a few places in `cpu/riscv_common`.
This should not have any effect on produced binaries.
CI should be enough. 
Quickly adapt from #16994. It will help for 64 bits support one day ;)

cpu/riscv_common: convert to uword_t usage

---

boards/native/Kconfig
boards/native/Makefile.features
cpu/native/periph/rtc.c

`periph_rtc` on `native` can have ms accuracy, so implement the `periph_rtc_ms` interface.
`tests/periph_rtc` now shows sub-second precision:
```
RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
Native RTC initialized.
Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57.393
Setting alarm to   2020-02-28 23:59:59
Alarm is set to   2020-02-28 23:59:59
Alarm cleared at   2020-02-28 23:59:57.393
No alarm at   2020-02-28 23:59:59.393
Setting alarm to   2020-02-28 23:59:61
Alarm!
Alarm!
Alarm!
Alarm!
{ "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 1100 }]}
{ "threads": [{ "name": "main", "stack_size": 12288, "stack_used": 2732 }]}
```

cpu/native: implement periph_rtc_ms

---

pkg/tinydtls/Makefile.dep

The [RIOT integration](https://github.com/eclipse/tinydtls/blob/main/dtls_time.c#L44) makes no use of ztimer64, so drop it.
Code still compiles, ztimer64 is not used.

pkg/tinydtls: don't require ztimer64

---

makefiles/features_modules.inc.mk

Whenever the module of a peripheral driver, i.e., periph_* should be used, the corresponding entry in the FEATURES_REQUIRED should be added. Conflicts between these modules are only checked when this entry is present.
Use, for example, the `default` example on a board with `periph_rtt` and `periph_rtc` available (e.g., the iotlab-m3). 
Change the Makefile from `FEATURES_OPTIONAL += periph_rtc` to `USEMODULE += periph_rtc`. Build and flash the application and call the `rtc gettime` shell command a couple of times.
You should see incorrect timestamps because the `periph_rtc` conflicts with `periph_rtt` (which is pulled in by the `ztimer_periph_rtt` module).
You should see a warning like
```
The following features may conflict: periph_rtc periph_rtt
Rationale: On the STM32F1, the RTC and RTT …
```

Makefile.dep: pull in FEATURES_REQUIRED for periph

---

sys/include/net/sock/udp.h
sys/net/application_layer/gcoap/gcoap.c
sys/net/application_layer/nanocoap/sock.c

If a node has multiple addresses we must reply to a request with the same address on which the request was received.
Since nanoCoAP is not always used as a server and often with only a single address, keep it optional and only enable it when the `sock_aux_local` module is used.
CoAP server needs to have two public addresses for this issue to occur:
e.g. set `CFLAGS += -DCONFIG_GNRC_NETIF_IPV6_ADDRS_NUMOF=3` in `examples/suit_update` and do
```
> ifconfig 5 add 2001:9e8:1416:8f00::1234
success: added 2001:9e8:1416:8f00::1234/64 to interface 5
> ifconfig
Iface  5  HWaddr: 7A:37:FC:7D:1A:AF 
L2-PDU:1500  MTU:1492  HL:255  RTR  
inet6 addr: fe80::7837:fcff:fe7d:1aaf  scope: link  VAL
inet6 addr: 2001:9e8:1416:8f00:7837:fcff:fe7d:1aaf  scope: global …
```

nanocoap_sock: ensure response address is the same as request address

---

cpu/stm32/periph/timer.c

From the commit msg:
>     cpu/stm32/periph/timer: remove unneeded header
>     
>     I see no reason this header should be included. It does not exist in
>     RIOT's source tree. This patch removes the include.
and 
>     cpu/stm32/periph/timer: fix execution flow
>     
>     The implmentation of `timer_set_absolute()` has The following problems.
>     First, it attempts to restore the auto reload register (ARR) to it's
>     default if the ARR was previosly set by `timer_set_periodic()` by
>     comparing it to the channel's capture compare (CC) register _after_ it
>     has already set the CC register. Secondly, it clears spurious IRQs
>     _after_ the CC register has been set. If the value being set is equal to
>     the timer's current count (or the two become equal before the …

Fix stm32 timer periodic

---

bootloaders/riotboot_dfu/main.c
bootloaders/riotboot_tinyusb_dfu/main.c
sys/include/riotboot/bootloader_selection.h
sys/riotboot/serial.c

In lastest master, the `BTN_BOOTLOADER_INVERTED` logic doesn't work as expected.
This PR fixes the underlying logic by replacing the `BTN_BOOTLOADER_INVERTED` macro definition by a runtime function.
In fact the current code:
```
#ifndef BTN_BOOTLOADER_INVERTED
#if (BTN0_MODE == GPIO_IN_PD)
#define BTN_BOOTLOADER_INVERTED false
#else
#define BTN_BOOTLOADER_INVERTED true
#endif
#endif
```
cannot work because both `BTN0_MODE` and `GPIO_IN_PD` are not known by the precompiler as they are enum values defined at cpu level.
Thus, replaces it by a runtime function in our bootloader applications.
I've also add `GPIO_OD_PU` along side `GPIO_IN_PU` and add a new define (which can be override at board level or app level) in case an external pullup is used.
Flash the riotboot_dfu bootloader:
`make …

bootloaders: fix bootloader button logic

---

sys/net/application_layer/nanocoap/sock.c

CoAP doesn't expect a Token in an empty ACK, but `coap_build_hdr()` will copy it over if we give it a token length.
This is bad as here we only provide space for the CoAP header `ack`. `coap_build_hdr()` will copy the token into `snip` where it causes all kinds of mayhem.

nanocoap_sock: don't include token in empty ACK response

---

sys/include/net/cord/ep.h

The draft is an RFC, this bumps the "see also" in the docs to the rfc.
Check that the correct RFC is linked in the docs.
None

cord: bump reference from draft to rfc

---

dist/tools/compile_test/compile_like_murdock.py

This adds a few nice-to-have features:
- The `-b all` allows all supported boards to build
- The `-v, -vv, -vvv` allows different levels of verbosity, the most useful might be `-v` which filters only the kconfig diffs
- All warning or STDERR based output from `info-*` are hidden
- The `-m` that only runs a diff of modules and packages, skipping any compilation
In induce a mismatch and check the output with `-v`, `-vv` options, clean it up and see the full output with `-vvv`:
```
./dist/tools/compile_test/compile_like_murdock.py -a APP -d -b BOARD -v
```
Check all supported boards are listed with
```
./dist/tools/compile_test/compile_like_murdock.py -a examples/hello-world/ -d -b all
```

tools/compile_like_murdock: Add features

---

drivers/include/mtd_default.h
sys/auto_init/usb/auto_init_usb.c
sys/include/usb/usbus.h
sys/include/usb/usbus/msc.h
sys/usb/usbus/msc/Kconfig
sys/usb/usbus/msc/msc.c
tests/mtd_raw/main.c
tests/usbus_msc/Makefile
tests/usbus_msc/main.c

I had some trouble combining `tests/usbus_msc` with `stdio_cdc_acm`.
Turns out the test was creating it's own usbus and was therefore not compatible with other modules that make use of usbus.
Fix this by adding USB MSC to `auto_init_usbus` and add a config option `CONFIG_USBUS_MSC_AUTO_MTD` to export all MTD devices on startup.
`tests/usbus_msc` now provides all MTD devices via USB without manual configutaiton.
More importantly, it now also works on boards that use `stdio_cdc_acm` like `adafruit-itsybitsy-m4`:
```
[ 5252.107261] usb 1-1.4: new full-speed USB device number 40 using ehci-pci
[ 5252.217906] usb 1-1.4: New USB device found, idVendor=1209, idProduct=7d01, bcdDevice= 1.00
[ 5252.217917] usb 1-1.4: New USB device strings: Mfr=3, Product=2, SerialNumber=4
[ 5252.217920] usb …
```

usbus/msc: add CONFIG_USBUS_MSC_AUTO_MTD option to create LUNs on init

---

cpu/nrf52/periph/usbdev.c
cpu/sam0_common/periph/usbdev.c
drivers/include/periph/usbdev.h
drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
sys/usb/usbus/usbus_control.c

This PR adds dedicated stall functions for usbdev peripherals. Two
functions are added. The first function (usbdev_ep_stall) to enable and
disable the stall condition on generic endpoints. The second function is
a dedicated function to set the stall condition on endpoint zero in both
directions. This status can only be set and should automatically be
cleared by the usbdev implementation (or hardware) after a new setup
request is received from the host.
- examples/usbus_minimal should still enumerate correctly on the host side.
- #17085 can be used to demonstrate the ep0_stall function with the `tests/usbus_cdc_acm_stdio/` test
None

usbdev: Add dedicated stall functions

---

sys/usb/usbus/cdc/acm/cdc_acm.c
sys/usb/usbus/cdc/ecm/cdc_ecm.c
sys/usb/usbus/hid/hid.c
sys/usb/usbus/msc/msc.c

This PR fixes issue #19359 for STM32 USB OTG cores partially:
1. It must not be silently ignored if the number of endpoints is not sufficient for an application. Instead of producing a non-working application, the application stops now with `kernel_panic` if the number of EPs is exhausted. This fixes the problem described in issue #19359 for USB cores with CID version 1.x, e.g. for STM32F439ZI FS interface (CID 1200) since they only have 4 IN and 4 OUT endpoints including the control endpoint EP0.
2. [Update: this part was fixed by PR #17086] ~If a feature is not supported, the device has to signal a STALL on the endpoint that should be used for the data phase in a control transaction. This means that for control read transactions the IN endpoint must signal a STALL and for control write …

sys/usbus: handle exceeding number of endpoints

---

makefiles/boards/stm32.inc.mk

This PR fixes the still existing problem that an application can't be flashed to a STM32 board if it uses `riotboot_dfu` with default  VID/PID (1209:7d02).
In PR #18964 item 1, the problem was already described that an application can't be flashed on a board that is using `riotboot_dfu`. Using for example
```python
FEATURES_REQUIRED+=riotboot USEMODULE+=usbus_dfu make -C examples/saul BOARD=nucleo-f767zi \
PROGRAMMER=dfu-util all riotboot/flash-slot0
```
always leads to error
```python
/home/gs/src/RIOT-Xtensa-ESP.esp-idf-4.4/makefiles/boards/stm32.inc.mk:28: *** DFU_USB_ID is not set.  Stop.
/home/gs/src/RIOT-Xtensa-ESP.esp-idf-4.4/makefiles/boot/riotboot.mk:87: recipe for target 'riotboot/bootloader/binfile' failed
```
even if `DFU_USB_ID` variable is set as described in documentation. …

makefiles/boards/stm32: fix DFU_USB_ID handling

---

drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c

This PR fixes the problem that the driver uses the wrong number of EPs when using the USB OTG HS core.
The constant `DWC2_USB_OTG_FS_NUM_EP` was used in several places independent on whether the USB OTG FS core or the USB OTG HS core is used even though there is a function `_max_endpoints` which takes into account the configuration used. For most MCUs this was not a problem, because they have only a USB OTG FS core anyway. But for MCUs like the STM32, which have both a USB OTG FS core and a USB OTG HS core, it matters.
Use either
```
USEMODULE='stdio_cdc_acm' BOARD=stm32f429i-disc1 make -j8 -C tests/usbus_cdc_ecm flash
```
or
```
BOARD=stm32f429i-disco make -j8 -C tests/usbus_cdc_ecm flash
```
Without this PR it just stucks due to an `assert` here: …

driver/usbdev_synopsys_dwc2: use correct number of EPs

---

cpu/sam0_common/periph/usbdev.c

Reverting theses changes from #17086 because it breaks SAM0 `usbdev` in master.
The idea was to following the USB spec but for not obvious reason yet, it doesn't work as intended.
So revert these changes so `usbdev` works again on master.
We will try to figured out what's wrong later.
Test any `usbus` related test application w/ a SAM0-based board.
See discussion in #17086

sam0/usbdev: partial revert of #17086

---

sys/net/application_layer/cord/ep/cord_ep.c

gcoap_req_send returns 0 if it was unable to send the CoAP request. CoRD did not include that case in the return code checks. This changes CoRD to include it and drop the registration if CoAP could not send the request. The old behaviour made the CoRD thread lock up.
- Check with the gcoap API docs.
- I can reliable trigger the issue with a RIOT application including both the `cord_ep_standalone` module and some measurement reported both sending requests to the same application. If at some point the application is shut down, gcoap has all its memo's occupied with the measurement reporting and can't add the CoRD update request. Thus the CoRD update request fails with a zero code and the thread (previously) would lock up.
None

cord: include gcoap_req_send returning 0 in error

---

cpu/stm32/periph/timer.c

From the git commit:
> The STM32 periph_timer driver reads the timer's status flags, then clears them all. It is possible that a timer interrupt could occur between reading the flag and clearing it. This would lead to a lost interrupt.
> 
> The timer's status flags can be cleared by software, but can only be set by the hardware. This patch takes advantage of this by only clearing the flags it knows are set. The rest of the flags are set, which doesn't actually change their state.
I had trouble finding anything in ST's datasheet saying that software could not set the timer's status flags, but testing showed that this is how it works in practice. Further, [ST's own HAL ](https://github.com/STMicroelectronics/STM32CubeF4/blob/master/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h#L1258)c …

cpu/stm32/periph/timer: fix clobered IRQ flag

---

sys/usb/usbus/dfu/dfu.c

In some cases, it is really useful to build `riotboot` with `NUM_SLOTS=1`.
When use in combination with `riotboot_dfu`, there is no need to export the second slot if `riotboot` is built with `NUM_SLOTS=1`.
Thus, prevent the alt interface declaration in dfu if `NUM_SLOTS=1` so that only slot0 can be used to flash.
Add `NUM_SLOTS=1` to `bootloaders/riotboot_dfu/Makefile`
Flash the riotboot DFU bootloader to any board supported by USBUS:
`make BOARD=xxx -C bootloaders/riotboot_dfu flash`
and run
`dfu-util -l`
With NUM_SLOTS=2 you will get:
```
dfu-util -l  
dfu-util 0.11
Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to …
```

usbus/dfu: do not create alt interface if NUM_SLOTS=1

---

drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c

This PR disables the DMA mode for HS cores due to several problems found:
- The STALL bit of the OUT control endpoint does not seem to be cleared automatically on the next SETUP received. At least the USB OTG HS core does not generate an interrupt on the next SETUP received. This happens, for example, when CDC ACM is used and the host sends the `SET_LINE_CODING` request which is answered with setting the STALL bit of the OUT endpoint. In this case the enumeration of further interfaces, for example CDC ECM, is stopped. This problem was described in https://github.com/RIOT-OS/RIOT/pull/17085#issuecomment-1464928744
- The Enumeration fails for CDC ECM interface which uses URB support (PR #17091) 
Use a STM32 board with USH OTG HS interface:
```python
USEMODULE='stdio_cdc_acm …
```

drivers/usbdev_synopsys_dwc2: disable DMA mode

---

cpu/efm32/include/periph_cpu.h
cpu/esp32/include/periph_cpu_esp32s2.h
cpu/esp32/include/periph_cpu_esp32s3.h
cpu/gd32v/include/periph_cpu.h
cpu/stm32/include/periph_cpu.h
cpu/stm32/include/usbdev_stm32.h
sys/auto_init/usb/auto_init_usb.c
sys/include/usb/hid.h
sys/include/usb/usbus/cdc/acm.h
sys/include/usb/usbus/cdc/ecm.h
sys/include/usb/usbus/control.h
sys/include/usb/usbus/msc.h
tests/usbus_cdc_ecm/Makefile

This PR provides a static check at compile time whether the number of EPs required in a static configuration does not exceed the number of EPs provided by the USB device.
In issue #19359 the problem was reported that `usbus_cdc_ecm` didn't work together with `stdio_cdc_acm` on some STM32 boards. The reason for some of the boards was simply that the application tried to allocate more EPs than available and simply ignored this and just didn't work.
Since `auto_init_usb` uses a static configuration with exactly one USBUS stack instance and one USB device, at least in case `auto_init` is used a static check can be carried out to make sure that the number of EPs required by the application doesn't exceed the number of EPs provided by the USB device. For this purpose, each `usbus_*` module …

sys/usbus: check for the number of required and provided EPs in static configurations

---

pkg/nanors/Makefile
tests/pkg_nanors/main.c

`reed_solomon_new()` uses `malloc()` internally, use `reed_solomon_new_static()` instead to use a static work buffer.
`tests/pkg_nanors` still works:
```
2023-03-14 19:43:21,130 # main(): This is RIOT! (Version: 2023.04-devel-648-g94ba33-pkg/nanors-static)
2023-03-14 19:43:21,132 # START
2023-03-14 19:43:21,135 # total: 30 shards (1920 bytes)
2023-03-14 19:43:21,150 # clear shard 25 (64 byte)
2023-03-14 19:43:21,152 # clear shard 17 (64 byte)
2023-03-14 19:43:21,154 # clear shard 18 (64 byte)
2023-03-14 19:43:21,156 # clear shard 18 (64 byte)
2023-03-14 19:43:21,159 # clear shard 28 (64 byte)
2023-03-14 19:43:21,161 # clear shard 12 (64 byte)
2023-03-14 19:43:21,163 # clear shard 11 (64 byte)
2023-03-14 19:43:21,165 # clear shard 0 (64 byte)
2023-03-14 19:43:21,168 # clear shard 12 (64 …
```

tests/pkg_nanors: use static allocation

---

sys/include/ztimer.h
sys/include/ztimer/periodic.h
sys/ztimer/convert.c
sys/ztimer/convert_frac.c

Noticed this while looking at https://github.com/RIOT-OS/RIOT/pull/19392.
Uncrustify should now pass without warning on the files changed here.
In fact, I just ran
```sh
uncrustify -c uncrustify-riot.cfg --replace sys/ztimer64/*.c sys/ztimer/*.c sys/include/ztimer*.h sys/include/ztimer*/*.h
```
to generate this PR.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/19392

ztimer/ztimer64: uncrustify code

---

sys/net/gnrc/network_layer/ipv6/static_addr/gnrc_ipv6_static_addr.c

Using `gnrc_ipv6_static_addr` with only `CONFIG_GNRC_IPV6_STATIC_ADDR` set fails due to a copy & paste error.
Also remove the need to specify the interface if there is only one.
Running `examples/gnrc_networking` with 
```make
USEMODULE += gnrc_ipv6_static_addr
CFLAGS += -DCONFIG_GNRC_IPV6_STATIC_ADDR=\"2001:db8::2\"
```
now has the expected result
```
Iface  7  HWaddr: 4F:C5  Channel: 26  NID: 0x23  PHY: O-QPSK 
Long HWaddr: A6:8F:3A:12:5E:63:4F:C5 
State: IDLE 
ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
6LO  IPHC  
inet6 addr: fe80::a48f:3a12:5e63:4fc5  scope: link  VAL
inet6 addr: 2001:db8::2  scope: global  VAL
inet6 group: ff02::1:ff63:4fc5
inet6 group: ff02::1a
inet6 group: ff02::1:ff00:2
```

gnrc_ipv6_static_addr: fix build with only static address

---

drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c

This PR adds power management handling for ESP32x SoCs.
Use and ESP32-S2 or ESP32-S3 board and flash `tests/periph_pm` using the `stdio_cdc_acm`
```
USEMODULE=stdio_cdc_acm BOARD=esp32s3-devkit make -j8 -C tests/periph_pm flash
```
Connect the terminal to the board and execute command:
```
set_rtc 1 1
```
The console should continue to work after the 1-s light sleep.

drivers/usbdev_synopsys_dwc2: add ESP32x power management

---

boards/adafruit-itsybitsy-m4/board.c

`adafruit-itsybitsy-m4` comes with a serial APA102 that is left on by the bootloader.
It's really bright and the only way to turn it off is by communication with it through it's SPI interface.
We have a proper driver for it, but pulling that in unconditionally feels wrong.
Instead just bit-bang the simple protocol on startup set all colors + alpha to 0.
- `adafruit-itsybitsy-m4` no longer glows blindingly pink.
- `tests/driver_apa102` still does it's fading

boards/adafruit-itsybitsy-m4: turn off APA102 LED on startup

---

cpu/efm32/periph/pwm.c
tests/periph_pwm/main.c

pwm_init is documented to return 0 on errors, and has an unsigned return value.
EFM32's initialization function returned negative values, which through implicit casting become 0xffffffff or 0xfffffffe, which are successful by the documentation.
This makes all the EFM32 error paths return 0 as they should.
Also, it fixes a variable name and the corresponding error message that used to talk of "initiation" (which would be the start of a process) rather than "initialization" (which is a process that is completed before something else can happen).
* on stk3700, tests/periph_pwm, run `init 0 0 10 1000` / `set 0 0 500`
* The init used to respond with "The pwm frequency is set to 4294967294", and the set does nothing.
* The init now responds with "Error: device is not …

cpu/efm32: pwm_init errors are zeros

---

boards/esp32c3-devkit/doc.txt
boards/esp32c3-devkit/include/board.h
boards/esp32s2-devkit/doc.txt
boards/esp32s2-devkit/include/board.h
boards/esp32s2-devkit/include/periph_conf.h
boards/esp32s3-devkit/doc.txt
boards/esp32s3-devkit/include/board.h

A couple of ESP32x boards have a SK68XXMINI-HS RGB LED on board.
- `esp32c3-devkit`
- `esp32s2-devkit`
- `esp32s3-devkit`
This RGB LED can be used with the driver module `ws2812x`. This PR adds the `WS2812X_PARAMS*` parameter definitions to the board definition and updates the documentation.
Use any of these boards to flash `tests/driver_ws2812x`, for example:
```
BOARD=esp32c3-devkit make -j8 -C tests/driver_ws281x/ flash
```
The RGB LED should work as expected.

boards/esp32: enable RGB LED support

---

boards/common/gd32v/dist/openocd.cfg

This PR improves the OpenOCD config for GD32V.
To restart GD32V after flashing, a special magic procedure has to be used. For short:
```python
halt
gd32vf103.cpu mww 0xe004200c 0x4b5a6978      # unlock 0xe0042008, the next write triggers a reset
riscv set_mem_access abstract                # set abstract memory access
gd32vf103.cpu mww 0xe0042008 0x1             # write to 0xe0042008 to triggers a reset
riscv set_mem_access progbuf                 # set memory access mode back
resume
```
The final `resume` was missing so that a timeout with an error message happened after flashing, for example:
```python
wrote 14692 bytes from file tests/shell/bin/sipeed-longan-nano/tests_shell.elf in 1.845550s (7.774 KiB/s)
verified 14692 bytes in 0.071006s (202.063 KiB/s)
Info : JTAG tap: gd32vf103.cpu …
```

boards/common/gd32v: improve openocd config

---

sys/bitfield/bitfield.c
sys/include/bitfield.h
tests/unittests/tests-bitfield/tests-bitfield.c

When I added those functions I thought there was no use-case for *not* touching the remaining bits of the last byte of the bitfield (e.g. in a bitfield of size 5 a `bf_clear_all()` would set all 8 bits of the bitfield-byte to 0).
But it turns out there *is* a use case for only clearing/setting part of a bitfield, so make the `bf_{set, clear}_all()` functions actually honor the proper size they are called with.
A new test case has been added to the unit test to check if no unrelated bits are touched.
This test case will fail on `master`.

sys/bitfield: don't touch unrelated bits in bf_{set, clear}_all()

---

cpu/esp32/stdio_usb_serial_jtag/usb_serial_jtag.c

This PR fixes problem with `stdio_usb_serial_jtag` for ESP32-C3.
Flash any ESP32-C3 board with the USB interface connected USB D+/D- (GPIO19, GPIO18) using the `stdio_usb_serial_jtag` module:
```
USEMODULE=stdio_usb_serial_jtag BOARD=hip-badge make -j8 -C tests/shell flash term
```

cpu/esp32: fix stdio_usb_serial_jtag for ESP32-C3

---

boards/sipeed-longan-nano/doc.txt
boards/sipeed-longan-nano/include/board.h
boards/sipeed-longan-nano/include/gpio_params.h

This PR makes the BOOT button usable as a user button.
The test requires PR #19418 to work.
Flash and test:
```
BOARD=sipeed-longan-nano make -j8 -C tests/saul flash term
```
The output
```
Dev: BOOT	Type: SENSE_BTN
Data:	              0 
```
should change to
```
Dev: BOOT	Type: SENSE_BTN
Data:	              1 
```
when the BOOT button is pressed.
Depends on PR #19418

boards/sipeed-longan-nano: add BOOT as user button

---

boards/stm32f429i-disc1/Kconfig
boards/stm32f429i-disc1/Makefile.dep
boards/stm32f429i-disc1/Makefile.features
cpu/stm32/include/periph_cpu.h
cpu/stm32/include/usbdev_stm32.h
drivers/periph_common/Kconfig.usbdev
drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
tests/usbus_cdc_ecm/Makefile

This PR fixes the DMA mode for all STM32 USB OTG HS cores (including that for STM32F4xx CID 1.xxx) and reenables it. It fixes remaining problems in issue #19359.
This PR includes also includes some changes that are needed to use the DMA mode:
- EP number is used as defined in CMSIS (if defined) for STM32
- `periph_usbdev_hs` feature is added in Kconfig
- `periph_usbdev_hs` feature is added in board definition of `stm32f429i-disc1`
- largest number of available EPs is used for STM32 instead of the smallest number (to be able to use all EPs of HS peripheral)
- `stm32f429i-disco` is removed from blacklist in `tests/usbus_cdc_ecm` since it uses the HS peripheral
The following tests should work
```python
USEMODULE=stdio_cdc_acm BOARD=stm32f429i-disc1 make -j8 -C tests/usbus_cdc_ecm flash
``` …

drivers/usbdev_synopsys_dwc2: fix and reenable DMA mode

---

cpu/esp32/startup.c

This PR provides a workaround that fixes the problem that restarting an application automatically after flashing it in download mode via USB Serial/JTAG doesn't work and requires a hard reset by pressing the RESET button before it starts.
The reason that the application doesn't restart automatically after flashing it is that an exception occurs if `puts` or `printf` is called during startup before the first interrupt driven context switch in `thread_yield_higher`. The console seems to hange after bootloader:
```
EESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380786
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x6c
load:0x403ce000,len:0x7ec
load:0x403d0000,len:0x2170
entry 0x403ce000
Pro cpu up.
``` …

cpu/esp32: use ets_printf instead of puts in startup

---

drivers/ws281x/esp32.c

This PR provides a small change which improves the timing for ESP32x SoCs.
If overhead like the loop control or the calculation of the waiting times for the next bit are performed while waiting for the end of the LOW phase, the time required for such operations is included in the LOW phase. This makes both the LOW phase and the period more precise.
According to the definitions
```c
#define WS281X_T_DATA_NS                (1250U)
#define WS281X_T_DATA_ONE_NS            (650U)
#define WS281X_T_DATA_ZERO_NS           (325U)
```
the following timing is used:
| Parameter    | Value | Master | this PR |
|:-------------|------:|-------:|--------:|
| 1-Bit Period | 1250  | 1820   | 1400    |
| 1-Bit HIGH   | 650   | 690    | 710     |
| 1-Bit LOW    | 600   | 1130   | 690     |
|              | …

drivers/ws281x: improve timing for ESP32x

---

.github/workflows/tools-test.yml
dist/tools/compile_test/compile_like_murdock.py
dist/tools/compile_test/tests/test.sh

Turns out we didn't test the simplest case, board being empty.
I added some automatic testing to check that and we can build when needed...
Green `tools-test` action

Fix `compile_like_murdock.py` when board is empty

---

examples/suit_update/Makefile
examples/suit_update/main.c
sys/suit/handlers_global.c

- when we set `USE_ETHOS=0` the default netdev should be selected instead of no netdev
- include `board.h` so the button auto-detection works.
- this example does not need the routing module
- drop the `)` from output such as `)Manifest seq_no`
Updating the board via a press of the button does now work again:
```
2023-03-10 02:25:50,790 # Button pressed! Triggering suit update! 
2023-03-10 02:25:50,792 # suit_worker: started.
2023-03-10 02:25:50,799 # suit_worker: downloading "coap://[2001:db8:1::1]/fw/samr21-xpro/riot.suit.latest.bin"
2023-03-10 02:25:50,912 # suit_worker: got manifest with size 445
2023-03-10 02:25:50,915 # suit: verifying manifest signature
2023-03-10 02:25:55,616 # suit: validated manifest version
2023-03-10 02:25:55,620 # Manifest seq_no: 10, highest available: 1 …
```

examples/suit_update: improve default module selection

---

boards/common/stm32/include/cfg_usb_otg_hs_phy_fs.h
boards/stm32f429i-disc1/Kconfig
boards/stm32f429i-disc1/Makefile.dep
boards/stm32f429i-disc1/Makefile.features
tests/usbus_cdc_ecm/Makefile

This PR fixes the problem that CDC ECM is not working for `stm32f429i-disco`.
With PR #19358, the EP data size for CDC ECM bulk endpoints was increased to 512 byte to fix the problem that CDC ECM was not working for boards with USB High-Speed peripherals. Module `periph_usbdev_hs` was introduced to indicate whether a high-speed peripheral is used.
However, the `stm32f429i-disco` board uses a mixture of USB OTG HS peripheral together with the on-hip FS PHY. Using the USB OTG HS peripheral together with a FS-PHY and increasing the EP data size for the CDC ECM bulk endpoint to 512 bytes doesn't work. Therefore, module `periph_usbdev_hs` is not used for now to workaround the problem. Thus, the maximum number of EPs used is that of the USB OTG FS peripheral, which is only 4. This is not …

boards: fix USB configuration for stm32f429i-disco

---

boards/common/stm32/include/cfg_usb_otg_hs_phy_fs.h
boards/stm32f429i-disc1/Kconfig
boards/stm32f429i-disc1/Makefile.dep
boards/stm32f429i-disc1/Makefile.features
drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
sys/include/usb.h
sys/include/usb/usbopt.h
sys/include/usb/usbus.h
sys/usb/usbus/cdc/ecm/cdc_ecm.c
sys/usb/usbus/cdc/ecm/cdc_ecm_netdev.c
sys/usb/usbus/usbus.c
tests/usbus_cdc_ecm/Makefile

This adds infrastructure around usbus and usbdev to query the speed of the USB link after enumeration. This as the maximum speed of the link might be slower than the maximum speed of the peripheral. This is the case with the stm32f429i-disco board that has a full speed phy coupled with the high speed peripheral.
This also adds the necessary code to the cdc_ecm code to use the correct packet size. The allocated buffer size is not modified with this PR unfortunately.
The `cdc_ecm` handler should work with a HS peripheral coupled with a FS phy.
Fixes an issue caused by #19358

usbus: Add support for full speed with high speed phy

---

pkg/semtech-loramac/doc.txt

This PR fixes the highlighting of Makefile snippets in the semtech-loramac package documentation.
In the current documentation the words `for` in comments are interpreted while they shouldn't. Comment text is also not hightighted.
With this PR:
None

pkg/semtech-loramac: fix makefile highlighting in documentation

---

cpu/stm32/periph/spi.c

The driver previously failed to reliably clear the RXNE bit, resulting in the next transfer to incorrectly read a stale register value. This was noticed with the SD card SPI driver on an STM32F4, in which the 0xff byte of the previous byte transfer was returned instead of the actual status byte, throwing the SD card driver off the rails.
Connecting an SD card via SPI to a Nucleo-2F429ZI should now result is almost reliable operation.
None

cpu/stm32: Fix periph_spi operation in non-DMA mode

---

makefiles/tools/serial.inc.mk

While testing examples/micropython I notice that the default of miniterm.py is actually miniterm. To simplify user setups, this checks for miniterm.py first then falls back to miniterm.
Take any board with any newish version of Ubuntu and run
```
make -C flash test examples/micropython
```
If you have `miniterm.py` in `PATH` or if it is `miniterm` both should work.

makefiles/tools/serial.inc.mk: Handle new miniterm versions [backport 2023.01]

---

README.md

Since the HAW-Hamburg hack and change to the RIOT community server the HiL is not operating.  We should remove it until it is brought back. likely with some improvements and with different links.
Before this PR: click on it  and be sad
After PR: Forget your sorrows

README.md: Remove HiL Badge

---

sys/usb/usbus/msc/msc.c

This PR provides two fixes for USBUS MSC driver.
9e88db7 removes a call to `usbdev_control_slicer_ready()` as this function is called by USBUS stack right after so remove this call to avoid duplication.
608d49c moves the call to `usbdev_ep_xmit()`, which prepares the bulk MSC OUT endpoint to receives data, from the `_init()` function to `USB_MSC_SETUP_REQ_GML` control request. The issue was that this endpoint was prepare to early and an USB reset might reset this setting. (This is the case for the `usbdev_synopsys_dwc2` driver) Thus the endpoint is not ready to receive data when the host send it. 
Test this PR with `tests/usbus_msc` on any board using the `usbdev_synopsys_dwc2` driver **with a FS PHY**
There is another issue with HS PHY that should be fix too.
None.

usbus/msc: fixes for synopsys dwc2 driver

---

sys/include/usb/usbus/msc.h
sys/usb/usbus/msc/msc.c

This PR fixes the EP data sizes for the bulk endpoints of USB HS peripherals and the buffer alignment required in DMA mode.
The fixes are required to get USBUS MSC working with USB HS peripherals.
The test requires PR #19459.
Connect a SPI SD Card interface with a STM32 board with USB HS port and HS PHY and use `tests/usbus_msc` to test, for example:
```
USEMODULE='sdcard_spi mtd_sdcard_default periph_usbdev_hs_ulpi' \
CFLAGS='-DSDCARD_SPI_PARAM_CLK=GPIO_PIN\(PORT_I,1\) -DSDCARD_SPI_PARAM_MISO=GPIO_PIN\(PORT_B,14\) -DSDCARD_SPI_PARAM_MOSI=GPIO_PIN\(PORT_B,15\) -DSDCARD_SPI_PARAM_CS=GPIO_PIN\(PORT_A,8\)' \
BOARD=stm32f746g-disco make -j8 -C tests/usbus_msc flash
```
SD card should work with this PR.

sys/usbus/msc: fix EP sizes for USB HS and buffer alignment in DMA-mode

---

cpu/stm32/periph/gpio_ll.c
cpu/stm32/periph/gpio_ll_irq.c

The comments still claim STM32F1 support is missing, but this was recently added.
Also, drop an empty line to fix `too many consecutive empty lines` nitpick of the CI.
This since only changes comments, this won't effect the binaries. Technically, those comments would be Doxygen compatible comments. But as only Doxygen comments in headers are parsed, these are in practice regular plain comments.
https://github.com/RIOT-OS/RIOT/pull/19407 added basic GPIO LL support for STM32F1, https://github.com/RIOT-OS/RIOT/pull/19412 added the IRQ support on top of that.

cpu/stm32/periph_gpio_ll: Fix misleading comments

---

cpu/stm32/periph/usbdev_fs.c

This PR provides two fixes for the `usbdev_fs` driver:
- Fix endpoints registration
- Fix assignment of toggleable bits in EP_REG(x) registers
These bugs were encountered with the USBUS MSC implementation.
Regarding the endpoints registration:
For the `usbdev_fs` peripheral, IN and OUT endpoints of the same index must have the same type.
For instance, if EP1 OUT is a bulk endpoint, EP1 IN must either be unused or used as bulk too but it cannot be used as interrupt or isochronous.
With the previous check, the following registration pattern (EP OUT Bulk -> EP IN Interrupt -> EP IN Bulk) would assign both EP OUT Bulk and EP IN Interrupt to same endpoint index. So the configuration would be broken.
Applying the same registration pattern with this patch would now produce EP OUT Bulk -> 1 / EP …

cpu/stm32/usbdev_fs: fix ep registration and EP_REG assignments

---

sys/include/usb/descriptor.h
sys/include/usb/usbus.h
sys/usb/usbus/usbus.c
sys/usb/usbus/usbus_control.c

This PR adds support for the endpoint halt condition on the USBUS side.
Instead of directly stalling an endpoint, handlers should enable the
halt condition on an usbus endpoint to signal error condition.
This can then be cleared via a CLEAR FEATURE request from the host.
This PR also extends support for the GET STATUS requests to support endpoints
and interfaces as recipient. It also adds the SET and CLEAR FEATURE
requests for the endpoints with support to set and clear the halt
condition on an endpoint.
The feature can be shown when adding the following patch to the CDC_ECM code:
```Patch
diff --git a/sys/usb/usbus/cdc/ecm/cdc_ecm.c b/sys/usb/usbus/cdc/ecm/cdc_ecm.c
index f580209e03..3d87a67087 100644
--- a/sys/usb/usbus/cdc/ecm/cdc_ecm.c
+++ b/sys/usb/usbus/cdc/ecm/cdc_ecm.c
@@ -31,7 …
```

usbus: Add support for endpoint halt condition

---

drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c

This PR fixes the interrupt handling for IN endpoints in DMA mode.
In DMA mode, both the `XFRC` (Transfer Complete) interrupt and the `TXFE` (TX FIFO Empty) interrupt for IN EP1 ... EPn were used to generate the `USBDEV_EVENT_TR_COMPLETE`. This led to problems with USBUS MSC. With this fix, the `TXFE` interrupt is used only in non-DMA mode or only for IN EP0 in DMA mode while the `XFRC` (Transfer Complete) is used only in DMA mode for IN EP1 ... EPn.
This PR should work together with PR #19458 for SD Card interface for a board with USB HS port, for example:
```
USEMODULE='sdcard_spi mtd_sdcard_default periph_usbdev_hs_ulpi' \
CFLAGS='-DSDCARD_SPI_PARAM_CLK=GPIO_PIN\(PORT_I,1\) -DSDCARD_SPI_PARAM_MISO=GPIO_PIN\(PORT_B,14\) -DSDCARD_SPI_PARAM_MOSI=GPIO_PIN\(PORT_B,15\) …
```

drivers/usbus_synopsys_dwc2: fix interrupt handling in DMA mode

---

drivers/sx126x/Kconfig
drivers/sx126x/Makefile.dep
sys/shell/cmds/gnrc_netif.c
tests/Makefile.boards.netif

This PR is fixing the missing bandwitdh, SF and CR LoRa parameter in the ifconfig command. In the `gnrc_netif.c`, they are only available when using `gnrc_lorawan` while they are more generally specific to LoRa (and there's a module for that).
So this PR basically just fixes the module used to enable them.
Run the `examples/default` on a LoRa board, for example b-l072z-lrwan1 (there are a few available on iot-lab).
On master, the BW, SF and CR are missing:
<details>
```
$ IOTLAB_NODE=auto make BOARD=b-l072z-lrwan1 -C examples/default/ flash term
make: Entering directory '/work/riot/RIOT/examples/default'
Building application "default" for "b-l072z-lrwan1" with MCU "stm32".
"make" -C /work/riot/RIOT/boards/b-l072z-lrwan1
"make" -C /work/riot/RIOT/boards/common/init
"make" -C …
```

sys/shell: fix missing generic lora settings in ifconfig

---

drivers/at86rf2xx/at86rf2xx.c

This PR fixes the default page of the AT86rf2xx radios (subghz variants).
After restructuring the driver, it turns out the `dev->page` variable was never being set. Since we allocate drivers in the data segment, the page was always zero.
Although the `at86rf2xx_reset` function was setting the PHY configuration, changing any PHY parameter would simply set the page to zero (unless `NETOPT_CHANNEL_PAGE` is explicitly used).
Make sure the subghz `at86rf2xx` variantes (e.g AT86RF212B) init with the default channel page (2).
EDIT: 
<details> <summary> Test results on IoT-LAB </summary>
```
1681378526.749873;samr30-1;> reboot
1681378526.750161;samr30-2;> reboot
1681378526.798788;samr30-1;main(): This is RIOT! (Version: 2023.07-devel-45-g26848-pr/at86rf2xx_fix_default_page) …
```

drivers/at86rf2xx: fix default page being ignored

---

drivers/at86rf2xx/at86rf2xx.c

This PR fixes the default page of the AT86rf2xx radios (subghz variants).
After restructuring the driver, it turns out the `dev->page` variable was never being set. Since we allocate drivers in the data segment, the page was always zero.
Although the `at86rf2xx_reset` function was setting the PHY configuration, changing any PHY parameter would simply set the page to zero (unless `NETOPT_CHANNEL_PAGE` is explicitly used).
Make sure the subghz `at86rf2xx` variantes (e.g AT86RF212B) init with the default channel page (2).
EDIT: 
<details> <summary> Test results on IoT-LAB </summary>
```
1681378526.749873;samr30-1;> reboot
1681378526.750161;samr30-2;> reboot
1681378526.798788;samr30-1;main(): This is RIOT! (Version: 2023.07-devel-45-g26848-pr/at86rf2xx_fix_default_page) …
```

drivers/at86rf2xx: fix default page being ignored [backport 2023.01]

---

cpu/stm32/periph/usbdev_fs.c

This backport PR provides two fixes for the usbdev_fs driver:
Fix endpoints registration
Fix assignment of toggleable bits in EP_REG(x) registers
These bugs were encountered with the USBUS MSC implementation.
Regarding the endpoints registration:
For the usbdev_fs peripheral, IN and OUT endpoints of the same index must have the same type.
For instance, if EP1 OUT is a bulk endpoint, EP1 IN must either be unused or used as bulk too but it cannot be used as interrupt or isochronous.
With the previous check, the following registration pattern (EP OUT Bulk -> EP IN Interrupt -> EP IN Bulk) would assign both EP OUT Bulk and EP IN Interrupt to same endpoint index. So the configuration would be broken.
Applying the same registration pattern with this patch would now produce EP OUT Bulk -> 1 / EP …

cpu/stm32/usbdev_fs: fix ep registration and EP_REG assignments [backport 2023.04]

---

sys/usb/usbus/msc/msc.c

This is a backport PR containing two fixes for USBUS MSC driver so it can works with `usbdev_synopsys_dwc2` driver
See #19455 for more context.
Same as #19455 
See #19455

usbus/msc: fixes for synopsys dwc2 [backport 2023.04]

---

drivers/include/periph/usbdev.h
drivers/include/usbdev_synopsys_dwc2.h
sys/usb/usbus/usbus_control.c

This PR allows to define when the device address is set on receipt of a SETUP with `SET ADDRESS Request`. It fixes the problem with enumeration of the Synopsys DWC2 USB OTG Core due to the wrong time of setting the device address.
Especially, it fixes the problem that the enumeration fails completely for the `stm32f723e-disco` board with CDC ECM if CDC ACM is not used and the additional reset cycles during the enumeration for a couple of platforms such as ESP32-S2 and ESP32-S3.
**Background**
The address in the USB device can be set either directly after the SETUP stage on receipt of the `SET ADDRESS Request` or after the associated STATUS stage. When the USB device address has to be set depends on the hardware implementation.
**Solution**
To control the time of setting the device …

drivers/periph_usbdev: fix set device address

---

sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c

This PR fixes setting the `nwkskey` via `ifconfig`. As it is now, the NETOPT implementation reverses the array, which is not what we want for keys.
Therefore, this simply replaces the `_memcpy_reverse` call with regular `memcpy`.
Compile and flash `examples/gnrc_lorawan` and set all ABP parameters using `ifconfig`:
```
ifconfig 3 set addr AAAAAAAA
ifconfig 3 set nwkskey BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
ifconfig 3 set appskey CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
ifconfig 3 -otaa
ifconfig 3 up
```
Transmit payload using `txtsnd` and make sure it is received by the network server:
```
txtsnd 3 01 RIOT
```
None so far

gnrc_netif/lorawan: fix setting nwkskey via NETOPT

---

boards/common/stm32/include/cfg_timer_tim5_and_tim2.h
boards/nucleo-f429zi/include/periph_conf.h

- Add a common timer config with two (instead of only one) timer using TIM2 + TIM5
- Mostly copy-pasting the cfg_timer_tim2.h and cfg_timer_tim5.h together
- Make use of that for the `nucleo-f429zi`
E.g. `tests/periph_timer`, but also grepping for TIM2 and TIM5 in `boards/nucleo-f429zi/include/periph_conf.h` to detect any conflict e.g. between PWM and timer config.
None

boards/nucleo-f429zi: Provide 2nd timer

---

sys/cpp11-compat/include/riot/thread.hpp
sys/cpp11-compat/thread.cpp

after reviewing #19369  i found that there is a conversion to nanoseconds just to convert it to microseconds some instrunctions later for ztimer64_usec to handle it this removes one of the conversions (convert once direct to microseconds)
run the cpp tests
#19369

cpp11-compat: thread::sleep_for in microseconds

---

cpu/native/include/native_internal.h
cpu/native/periph/timer.c
cpu/native/syscalls.c

When compiling RIOT for native using a recent LLVM and enabling ASAN, one might encounter "Duplicated symbol".
This is due to a name clash with `real_clock_gettime()` in compiler-rt from [LLVM](https://github.com/llvm/llvm-project/commit/f50246da651ee11fec68b2a29c3b21325cdc12b1), I renamed RIOTs `real_clock_gettime` and just default to the posix function `clock_gettime`. The wrapper existed, most likely, for consistency only.
(The best solution would probably to convince the LLVM folks to declare their symbol as `static` and refactor a bit)
Passing CI should be enough.

native/syscalls: rename real_clock_gettime to clock_gettime

---

cpu/esp32/Makefile.include
cpu/esp32/bootloader/Makefile
cpu/esp32/esp-idf/esp_idf_cflags.mk
cpu/esp32/esp-idf/esp_idf_support.c
cpu/esp32/esp-idf/nvs_flash/Makefile
cpu/esp32/include/periph_cpu.h
cpu/esp32/periph/adc.c
cpu/esp32/periph/flashpage.c
cpu/esp32/periph/gpio.c
cpu/esp32/periph/gpio_ll.c
cpu/esp32/periph/gpio_ll_irq.c
cpu/esp32/periph/rtt.c
cpu/esp32/periph/rtt_hw_rtc.c
cpu/esp32/startup.c
cpu/esp32/syscalls.c
cpu/esp_common/esp-now/esp_now_netdev.c
cpu/esp_common/esp-wifi/esp_wifi_netdev.c
cpu/esp_common/esp-xtensa/irq_arch.c
cpu/esp_common/esp-xtensa/thread_arch.c
cpu/esp_common/freertos/ringbuf.c
pkg/esp32_sdk/patches/0028-hal-cast-esp-interrupt-type-to-riscv-interrupt-type.patch
pkg/esp32_sdk/patches/0029-nfs_flash-include-stddef.h-for-size_t-deklaration.patch
pkg/esp32_sdk/patches/0030-bt-controller-esp32s3-fix-return-types-in-functions.patch

This PR provides the changes in `cpu/esp32` and `cpu/esp_common` to fix the compilation issues with GCC v12.2.  It is required as the first step in the preparation of the upgrade to ESP-IDF version 5.1.
**Please note**: Insead of fixing the ESP-IDF 4.4 code itself by a big bunch of patches to fix the compilation problems with GCC v12.2, it temporarily disables some warnings. The reason is that the ESP-IDF 5.1 requires GCC v12.2 and should be fixed for this compiler version by the vendor.
Green CI
The change were already tested with all ESP-specific modules like `esp_now`, `esp_wifi`, `esp_spi`  and `esp_ble` for all supported ESP platforms.
Prerequisite for https://github.com/RIOT-OS/riotdocker/pull/227
Fixes issue #19421

cpu/esp32: fix compilation issues with GCC 12.2

---

drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c

This PR fixes the interrupt handling for IN endpoints in DMA mode.
In DMA mode, both the `XFRC` (Transfer Complete) interrupt and the `TXFE` (TX FIFO Empty) interrupt for IN EP1 ... EPn were used to generate the `USBDEV_EVENT_TR_COMPLETE`. This led to problems with USBUS MSC. With this fix, the `TXFE` interrupt is used only in non-DMA mode or only for IN EP0 in DMA mode while the `XFRC` (Transfer Complete) is used only in DMA mode for IN EP1 ... EPn.
This PR should work together with PR #19458 for SD Card interface for a board with USB HS port, for example:
```
USEMODULE='sdcard_spi mtd_sdcard_default periph_usbdev_hs_ulpi' \
CFLAGS='-DSDCARD_SPI_PARAM_CLK=GPIO_PIN\(PORT_I,1\) -DSDCARD_SPI_PARAM_MISO=GPIO_PIN\(PORT_B,14\) -DSDCARD_SPI_PARAM_MOSI=GPIO_PIN\(PORT_B,15\) …
```

drivers/usbus_synopsys_dwc2: fix interrupt handling in DMA mode [backport 2023.04]

---

drivers/at86rf2xx/at86rf2xx.c

This PR fixes the default page of the AT86rf2xx radios (subghz variants).
After restructuring the driver, it turns out the `dev->page` variable was never being set. Since we allocate drivers in the data segment, the page was always zero.
Although the `at86rf2xx_reset` function was setting the PHY configuration, changing any PHY parameter would simply set the page to zero (unless `NETOPT_CHANNEL_PAGE` is explicitly used).
Make sure the subghz `at86rf2xx` variantes (e.g AT86RF212B) init with the default channel page (2).
EDIT: 
<details> <summary> Test results on IoT-LAB </summary>
```
1681378526.749873;samr30-1;> reboot
1681378526.750161;samr30-2;> reboot
1681378526.798788;samr30-1;main(): This is RIOT! (Version: 2023.07-devel-45-g26848-pr/at86rf2xx_fix_default_page) …
```

drivers/at86rf2xx: fix default page being ignored [backport 2023.04]

---

sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c

This PR fixes setting the `nwkskey` via `ifconfig`. As it is now, the NETOPT implementation reverses the array, which is not what we want for keys.
Therefore, this simply replaces the `_memcpy_reverse` call with regular `memcpy`.
Compile and flash `examples/gnrc_lorawan` and set all ABP parameters using `ifconfig`:
```
ifconfig 3 set addr AAAAAAAA
ifconfig 3 set nwkskey BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
ifconfig 3 set appskey CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
ifconfig 3 -otaa
ifconfig 3 up
```
Transmit payload using `txtsnd` and make sure it is received by the network server:
```
txtsnd 3 01 RIOT
```
None so far

gnrc_netif/lorawan: fix setting nwkskey via NETOPT [backport 2023.04]

---

boards/common/gd32v/Makefile.features
boards/seeedstudio-gd32/Kconfig
boards/sipeed-longan-nano/Kconfig
cpu/cortexm_common/Makefile.include
cpu/fe310/include/cpu.h
cpu/gd32v/Makefile.include
cpu/gd32v/clock.c
cpu/gd32v/include/cpu.h
cpu/riscv_common/Makefile.include
cpu/riscv_common/include/cpu_common.h
cpu/riscv_common/ldscripts/riscv.ld
examples/suit_update/Makefile.ci
sys/Makefile.include
sys/riotboot/Makefile.include
sys/riotboot/slot.c
tests/riotboot_flashwrite/Makefile.ci

This PR provides `riotboot` support for GD32V.
Use any GD32V board with a JTAG adapter and flash the bootloader:
```python
PROGRAMMER=openocd BOARD=sipeed-longan-nano make -C bootloaders/riotboot flash
```
Flash slot 0 and set `RIOT_VERSION` to 1
```python
USEMODULE=stdio_uart FEATURES_REQUIRED=riotboot RIOT_VERSION=1 \
PROGRAMMER=openocd BOARD=sipeed-longan-nano make -C tests/shell riotboot/flash-slot0
...
Binfile detected, adding ROM base address: 0x08000000
Flashing with IMAGE_OFFSET: 0x08001000
```
```python
> main(): This is RIOT! (Version: 1)
test_shell.
```
Flash slot 1 and set `RIOT_VERSION` to 2
```python
USEMODULE=stdio_uart FEATURES_REQUIRED=riotboot RIOT_VERSION=2 \
PROGRAMMER=openocd BOARD=sipeed-longan-nano make -C tests/shell riotboot/flash-slot1
...
Binfile detected, …
```

cpu/gd32v: add riotboot support

---

makefiles/tools/serial.inc.mk

While testing examples/micropython I notice that the default of miniterm.py is actually miniterm. To simplify user setups, this checks for miniterm.py first then falls back to miniterm.
Take any board with any newish version of Ubuntu and run
```
make -C flash test examples/micropython
```
If you have `miniterm.py` in `PATH` or if it is `miniterm` both should work.

makefiles/tools/serial.inc.mk: Handle new miniterm versions [backport 2023.04]

---

sys/include/usb/usbus.h
sys/usb/usbus/usbus.c

This PR removes the deprecated `USBUS_HANDLER_FLAG_TR_FAIL` flag.
CI should be enough.
Was deprecated by #17046

usbus: remove deprecated USBUS_HANDLER_FLAG_TR_FAIL flag

---

makefiles/features_modules.inc.mk

`periph_wdt_auto_start` is not a feature but a pseudo-module that indicates that the Watchdog should be initialized in early boot.
Add
USEMODULE += auto_init_wdt_thread
to your application.
fixes build error introduced with #19234

makefiles/features_modules: ignore periph_wdt_auto_start

---

makefiles/features_modules.inc.mk

`periph_spidev_linux` is not a feature.
`tests/pkg_fatfs` builds on `native` again
fixes build error introduced with https://github.com/RIOT-OS/RIOT/pull/19234

makefiles/features_modules: ignore periph_spidev_linux

---

makefiles/tools/openocd.inc.mk

The OPENOCD_CMD_RESET_HALT was not longer correctly passed to the script. This fixes the issue.
Flashing of e.g. the `cc2650-launchpad` with upstream OpenOCD should work again.
The change was added to https://github.com/RIOT-OS/RIOT/pull/19050 after testing the PR and before merging. I'm not sure if the fix never worked because of this, or if behavior of `target-export-variables` or GNU Make changed.

tools/openocd: Fix handling of OPENOCD_CMD_RESET_HALT

---

examples/nanocoap_server/Makefile
examples/nanocoap_server/coap_handler.c
sys/Makefile.dep
sys/auto_init/auto_init.c
sys/auto_init/include/auto_init_priorities.h
sys/include/net/nanocoap.h
sys/include/net/nanocoap_sock.h
sys/net/application_layer/gcoap/gcoap.c
sys/net/application_layer/nanocoap/nanocoap.c
sys/net/application_layer/nanocoap/sock.c
tests/nanocoap_cli/Makefile
tests/nanocoap_cli/request_handlers.c

Having to define all CoAP resources in one continuous array is a bit of a hassle.
We have XFA now which is a perfect fit for this kind of thing.
The only caveat is that `coap_handle_req()` lives in `nanocoap.c` which is shared by all CoAP users.
By the nature of XFAs, we can't have them garbage collected by the linker as the linker is what brings them into existence.
So I added a new `nanocoap_resources` pseudo-module that needs to be selected to enable the XFA. This has the advantage that we can use the absence of this module to fall-back to the previous implementation, so existing users are not forced to change their code.
`examples/nanocoap_server` still works:
```
$ aiocoap-client coap://[fe80::7837:fcff:fe7d:1aaf%tapbr0]/.well-known/core
application/link-format content was …
```

nanocoap: allow to define CoAP resources as XFA

---

core/Kconfig
core/include/mutex.h
core/mutex.c

Adding `USEMODULE += core_mutex_debug` to your `Makefile` results in
on log messages such as
[mutex] waiting for thread 1 (pc = 0x800024d)
being added whenever `mutex_lock()` blocks. This makes tracing down
deadlocks easier.
Run e.g.
```sh
USEMODULE=core_mutex_debug BOARD=nucleo-f767zi make -C tests/mutex_cancel flash test
```
which should provide output such as
```
READY
s
[mutex] waiting for thread 1 (pc = 0x8000f35)
START
main(): This is RIOT! (Version: 2022.10-devel-841-g5cc02-core/mutex/debug)
Test Application for mutex_cancel / mutex_lock_cancelable
=========================================================
Test without cancellation: OK
Test early cancellation: OK
Verify no side effects on subsequent calls: [mutex] waiting for thread 1 (pc = …
```

core: add core_mutex_debug to aid debugging deadlocks

---

boards/native/Makefile.dep
boards/native/board_init.c
boards/native/include/board.h
cpu/native/Makefile
cpu/native/fs/Makefile
cpu/native/fs/native_fs.c
cpu/native/include/native_internal.h
cpu/native/periph/pm.c
cpu/native/syscalls.c
sys/include/fs/native_fs.h
sys/include/vfs_default.h
sys/net/application_layer/gcoap/fileserver.c
sys/vfs/vfs.c
tests/gcoap_fileserver/Makefile
tests/gcoap_fileserver/tests/01-run.py

It is often quite handy to access files from Linux on RIOT and the other way round.
With `native` this is very straightforward as `native` is just a Linux process.
This adds a VFS driver to access the host file system from `native`.
Run e.g. `tests/vfs_default`
USEMODULE += fs_native
This will create a folder `nvm0` in the current working directory that is also accessible from RIOT.
To change the exported directory to the current dir, set
CFLAGS += -DFS_NATIVE_DIR=\"\"
You should now be able to access the directory of the example from withing RIOT:
```
main(): This is RIOT! (Version: 2023.04-devel-487-gaf076-cpu/native_fs)
mount points:
/nvm0
data dir: /nvm0
> ls /nvm0
./
Makefile.ci	252 B
nvm0/
main.c	858 B
Makefile	431 B
MEMORY.bin	8388608 B
../
bin/
total 4 files
> vfs r /nvm0/Makefile …
```

cpu/native: add host fs access via VFS

---

drivers/Makefile.dep

The servo test app uses `USEMODULE += servo` and lets the build system pick automatically the best suitable backend. If one explicitly chooses a backend e.g. via `USEMODULE += servo_timer`, this currently requires adding `USEMODULE += servo` in addition. This commit fixes the issue.
The app provided in https://github.com/RIOT-OS/RIOT/issues/19474 should now compile. (It does so for me.)
Fixes https://github.com/RIOT-OS/RIOT/issues/19474

drivers/servo: Fix missing dep

---

SUBSYSTEMS.md

This PR adds me (@jia200x) to the subsystem list.
Not so much to do here. Maybe check that the list is displayed correctly.
None so far

SUBSYSTEMS.md: add jia200x to subsystems

---

boards/nrf52840dongle/doc.txt

Nordic changed its nrfutil; this change adjust to it.
I'm not fully happy with recommending that tool at all due to its bad quality (see rambling in https://github.com/RIOT-OS/RIOT/issues/19511), but short of soldering on a debug header or touch-probing it with wires it's the only way in to the device. I may later add follow-up recommendations to switch to riotboot, but this now at least fixes the immediate issue.
* Look at the updated documentation.
Closes: https://github.com/RIOT-OS/RIOT/issues/19511

boards/nrf52840dongle/doc: Update nrfutil pointers

---

cpu/avr8_common/avr_libc_extra/posix_unistd.c
examples/dtls-echo/Makefile.ci
examples/dtls-sock/Makefile.ci
examples/gcoap_dtls/Makefile.ci
pkg/tinydtls/Makefile
pkg/tinydtls/Makefile.dep
pkg/tinydtls/patches/0001-dtls_debug-mock-dsrv_log-when-NDEBUG.patch
tests/gcoap_dns/Makefile.ci
tests/gnrc_sock_dodtls/Makefile
tests/gnrc_sock_dodtls/Makefile.ci
tests/nanocoap_cli/Makefile.ci
tests/pkg_tinydtls_sock_async/Makefile
tests/pkg_tinydtls_sock_async/Makefile.ci

tinyDTLS builds and works just fine on AVR, we only have to disable the custom logging functions as those will try to call `printf()` with non-literal strings. (We don't even call them, but they get built anyway)
I used `tests/nanocoap_cli` for testing. As `THREAD_STACKSIZE_DEFAULT` is lower on AVR we have to bump the main stack size here:
```patch
--- a/tests/nanocoap_cli/Makefile
+++ b/tests/nanocoap_cli/Makefile
@@ -43,7 +43,7 @@ ifeq (,$(filter $(BOARD),$(LOW_MEMORY_BOARDS)))
USEMODULE += shell_cmds_default
-  CFLAGS += -DTHREAD_STACKSIZE_MAIN=\(3*THREAD_STACKSIZE_DEFAULT\)
+  CFLAGS += -DTHREAD_STACKSIZE_MAIN=\(5*THREAD_STACKSIZE_DEFAULT\)
ifeq ($(BOARD),native)
```
I ran a border router on `samr21-xpro` with 
```
sudo dist/tools/tapsetup/tapsetup -u eno1
make BOARD=samr21-xpro …
```

pkg/tinydtls: allow build for AVR

---

boards/rpi-pico/Kconfig
boards/rpi-pico/Makefile.features
boards/rpi-pico/include/periph_conf.h
cpu/rpx0xx/clock.c
cpu/rpx0xx/cpu.c
cpu/rpx0xx/include/periph_cpu.h
cpu/rpx0xx/periph/adc.c

This PR adds initial support for RP2040 ADC peripheral.
It is rather minimalist, and only use oneshot trigger to perform a single acquisition.
I've tested this PR using a potentiometer connected between GND and 3V3.
GP26, GP27, GP28 has been tested.
Select `ADC_RES_12BIT` and flash `tests/periph_adc`
`make BOARD=rpi-pico -C tests/periph_adc`
None.

cpu/rpx0xx: add initial ADC support

---

release-notes.txt

This are the release notes for the 2023.04 Release. Please give it a look and make sure that your work in the last 3 months is present here.
- Read the document

release-notes.txt: add 2023.04 release notes

---

drivers/lsm303agr/src/lib.rs
examples/rust-gcoap/Cargo.lock
examples/rust-gcoap/Cargo.toml
examples/rust-hello-world/Cargo.lock
sys/rust_riotmodules_standalone/Cargo.lock
tests/rust_minimal/Cargo.lock

This updates both the RIOT-specific and generic dependencies of Rust examples and modules.
It also follows a deprecation from the G unit renaming originally done in https://github.com/RIOT-OS/RIOT/pull/19292.
* Green CI should do
Copying from one of the commits with some sed:
* riot-sys:
* https://github.com/RIOT-OS/rust-riot-sys/pull/26
* https://github.com/RIOT-OS/rust-riot-sys/pull/31
* https://github.com/RIOT-OS/rust-riot-sys/pull/30
* https://github.com/RIOT-OS/rust-riot-sys/pull/28
* https://github.com/RIOT-OS/rust-riot-sys/pull/27
* https://github.com/RIOT-OS/rust-riot-sys/pull/25
* https://github.com/RIOT-OS/rust-riot-sys/pull/23
* https://github.com/RIOT-OS/rust-riot-sys/pull/22
* https://github.com/RIOT-OS/rust-riot-sys/pull/21
* riot-wrappers:
* …

Rust: Update dependencies [backport 2023.04]

---

cpu/cc26xx_cc13xx/periph/uart.c

GCC 12 create a bogus array out of bounds warning as it assumes that because there is special handling for `uart == 0` and `uart == 1`, `uart` can indeed be `1`. There is an `assert(uart < UART_NUMOF)` above that would blow up prior to any out of bounds access.
In any case, optimizing out the special handling of `uart == 1` for when `UART_NUMOF == 1` likely improves the generated code and fixes the warning.
/home/maribu/Repos/software/RIOT/cc2650/cpu/cc26xx_cc13xx/periph/uart.c:88:8: error: array subscript 1 is above array bounds of 'uart_isr_ctx_t[1]' [-Werror=array-bounds]
88 |     ctx[uart].rx_cb = rx_cb;
|     ~~~^~~~~~
/home/maribu/Repos/software/RIOT/cc2650/cpu/cc26xx_cc13xx/periph/uart.c:52:23: note: while referencing 'ctx'
52 | static uart_isr_ctx_t ctx[UART_NUMOF];
| …

cpu/cc26xx_cc13xx: Fix bogus array-bound warning [backport 2023.04]

---

makefiles/tools/openocd.inc.mk

The OPENOCD_CMD_RESET_HALT was not longer correctly passed to the script. This fixes the issue.
Flashing of e.g. the `cc2650-launchpad` with upstream OpenOCD should work again.
The change was added to https://github.com/RIOT-OS/RIOT/pull/19050 after testing the PR and before merging. I'm not sure if the fix never worked because of this, or if behavior of `target-export-variables` or GNU Make changed.

tools/openocd: Fix handling of OPENOCD_CMD_RESET_HALT [backport 2023.04]

---

boards/e180-zg120b-tb/doc.txt
boards/ikea-tradfri/doc.txt
boards/slstk3400a/doc.txt
boards/slstk3401a/doc.txt
boards/slstk3402a/doc.txt
boards/sltb001a/doc.txt
boards/slwstk6220a/doc.txt
boards/stk3200/doc.txt
boards/stk3600/doc.txt
boards/stk3700/doc.txt
cpu/gd32v/periph/i2c.c
cpu/native/async_read.c
cpu/native/include/async_read.h
cpu/nrf52/include/periph_cpu.h
cpu/nrf9160/include/periph_cpu.h
dist/tools/codespell/ignored_words.txt
drivers/bq2429x/include/bq2429x_internal.h
drivers/cc110x/cc110x_rx_tx.c
drivers/cc110x/include/cc110x_params.h
drivers/include/nrf24l01p_ng.h
drivers/netdev/ieee802154.c
drivers/soft_uart/soft_uart.c
pkg/openwsn/contrib/openwsn.c
sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c
sys/ztimer/mock.c
tests/driver_nrf24l01p_lowlevel/main.c

This fixes some typos and adds one correctly used abbreviation to the ignore list.
If bors merges this without static tests failing, it did what it intended to do.
Fixes issues that prevent https://github.com/RIOT-OS/RIOT/pull/19440 from merging

treewide: fix typos and false positives found by codespell

---

examples/lorawan/README.md
pkg/semtech-loramac/doc.txt
tests/pkg_semtech-loramac/README.md

Fixes #19524 
The documentation/README update was overlooked in #16238 
Just read the modified files.
#19524, #16238

semtech-loramac: extend list of supported radio with sx1261, sx1262 and sx1268

---

boards/arduino-mkrwan1300/doc.txt

The board name in the documentation for the Arduino MKR WAN 1300 is wrong (https://doc.riot-os.org/group__boards__arduino-mkrwan1300.html). I presume since it was part of a larger pull-request and simply got overlooked.
Read the `doc.txt` and check that it matches the name of the board folder.

boards/arduino-mkrwan1300: update board name to correct one

---

boards/rpi-pico/Kconfig
boards/rpi-pico/Makefile.features
boards/rpi-pico/include/periph_conf.h
cpu/rpx0xx/include/periph_cpu.h
cpu/rpx0xx/periph/spi.c

This PR adds spi functionality to the `rpx0xx` MCU. It also adds spi configurations to the `rpi-pico` board's `periph_conf.h`.
The RP2040 has two SPI blocks of the PL022 type, which are DMA-capable and can be configured in various modes. The SPI clock can be set from `clock_periph` by means of two clock divisors. With the 125MHz clock of the RPi Pico, only the 100 KHz clock setting can be met exactly. See below.
DMA is not supported by this PR by now. Implementation should be easy once someone can add DMA support.
I have set the default pinout for the RPi Pico as follows in `periph_conf.h`:
- SPI 0
- MOSI: pin 3
- MISO: pin 4
- CLK: pin 2
- SPI 1
- MOSI: pin 11
- MISO: pin 12
- CLK: pin 10
The pinout might be worth discussing. There might be collisions soon when someone also ad I2C …

cpu/rpx0xx: implement periph_spi

---

boards/common/iotlab/Kconfig
boards/common/iotlab/Makefile.dep
drivers/include/l3gxxxx.h
drivers/l3gxxxx/l3gxxxx.c

We can use the more capable `l3gxxxx` driver here, so enable it.
The sensor is listed and can be read.
``` 
> saul
ID	Class		Name
#0	ACT_SWITCH	LED(red)
#1	ACT_SWITCH	LED(green)
#2	ACT_SWITCH	LED(orange)
#3	SENSE_LIGHT	isl29020
#4	SENSE_GYRO	l3gxxxx
#5	SENSE_PRESS	lps331ap
#6	SENSE_TEMP	lps331ap
#7	SENSE_ACCEL	lsm303dlhc
#8	SENSE_MAG	lsm303dlhc
> saul read 4
Reading from #4 (l3gxxxx|SENSE_GYRO)
Data:	[0]         0.0 dps
[1]         0.0 dps
[2]         0.1 dps
```

boards/iotlab-m3: enable l3g4200d_ng

---

cpu/stm32/periph/dac.c

The current implmentation right shifted the 16 bit value passed into `dac_set()` down to the 12 bits that the DAC is actually capable of. This patch drops the shift and instead writes the 16 bit value to the DAC's left aligned 12 bit wide data holding register.
do something like:
``` c
#include "perip/dac.h"
int main(void)
{
dac_set(DAC_LINE(0), 0xffff/2);
return 0;
}
```
- observe DAC's output is half of vref
- none known

cpu/stm32/periph/dac: optimize setting DAC

---

tests/unittests/Makefile

Previously, it was possible to select unittests like this: `make tests-core tests-base64`.
With this PR, it's also possible to pass the tests via environment, e.g.,
`UNIT_TESTS=tests-core make`
I stumbled over this when running the unittests individually under RIOT-rs. I had infrastracture to pass environment variables to the RIOT-c build system, but not extra / different make goals. Adding this to RIOT-c was simpler, and IMO is also consistent.
A good look should be sufficient.

tests/unittests: allow passing `UNIT_TESTS` via env

---

core/lib/assert.c
core/lib/include/debug.h
cpu/cortexm_common/include/architecture_arch.h
cpu/native/include/architecture_arch.h
cpu/native/native_cpu.c
sys/include/architecture.h

This provides an architecture independent macro to set breakpoints. So far it has only been implemented for Cortex-M and native, but it degrades to a no-op if not defined, so the situation is the same as before.
To make use of this, I added a breakpoints to the `assert()` function in the case of failure. 
This makes debugging failed asserts much easier. 
I simply added a `assert(0)` to `main()` in `examples/hello-world` and ran `make debug`:
```
main(): This is RIOT! (Version: 2023.04-devel-583-gb13ed2-DEBUG_BREAKPOINT)
Hello World!
You are running RIOT on a(n) native board.
This board features a(n) native MCU.
examples/hello-world/main.c:32 => *** RIOT kernel panic:
*** halted.
native: exiting
[Inferior 1 (process 17242) exited normally]
``` 
```
main(): This is RIOT! …
```

debug: add DEBUG_BREAKPOINT() macro, set breakpoint on failed assertion

---

boards/rpi-pico/Makefile.include

This PR adds the jlink device variable and use hexfile to flash application with a jlink probe.
Attach a `jlink` probe to SWD pins.
Try to flash any app with `jlink`
`PROGRAMMER=jlink make BOARD=rpi-pico -C examples/blinky flash`
None.

boards/rpi-pico: specify needed args when using jlink flasher

---

boards/rpi-pico/Makefile.include
dist/tools/jlink/jlink.sh
makefiles/tools/jlink.inc.mk

There seems to be a consensus to go for a more ELF centric approach whenever possible. J-Link seems to work fine with ELF files, so let's avoid the extra step to create a bin file from the ELF file prior to flashing.
Flashing with J-Link should still just work
In https://github.com/RIOT-OS/RIOT/pull/19537#discussion_r1183378501 I was made aware that we use the bin file by default for J-Link flashing.

makefiles/tools/jlink.inc.mk: use ELF file for flashing

---

sys/cpp11-compat/include/riot/chrono.hpp
sys/cpp11-compat/include/riot/thread.hpp
sys/cpp11-compat/thread.cpp

remove pseudo anonymous namespaces in favor of defines that are used thoughout the rest of riot 
cpp test do not fail

sys /cpp11-compat: remove pseudo anonymous namespaces

---

boards/telosb/board.c
boards/telosb/doc.txt
boards/telosb/include/board.h
boards/telosb/include/periph_conf.h
dist/tools/doccheck/exclude_simple
dist/tools/doccheck/generic_exclude_patterns

This cleans up the documentation and the header files of the TelosB board. It is supposed to not changed the generated firmware (except for debug symbols).
Green CI + no diffs in binaries.
None

boards/telosb: minor clean ups

---

drivers/include/mtd_default.h

The `mtd_default` module defines `MTD_NUMOF`, if not present, based on the `MTD_*` defines. These defines are set to the corresponding `mtd*` MTD device pointer variables in the board definitions. However, not all `mtd*` MTD device pointer variables are  always made known by external variable declarations. An example are SD Card Interfaces that are defined via the `mtd_sdcard_default` module. As a result, it may be necessary for an application using `mtd_default` to declare an external MTD device pointer variable `mtd`. To be able to use SD card for testing MTD based application, `mtd_default` also declares up to six `mtd*` MTD device pointer variables.
Use any board without SD Card definition and compile `tests/pkg_litllefs`,  `tests/pkg_litllefs2` or `tests/pkg_spiffs`, for example to …

drivers/mtd_default: add external declarations for mtd*

---

pkg/openthread/contrib/netdev/openthread_netdev.c

When using openthread with the ieee802154_submac module, a hard fault is triggered otherwise because the submac's init function calls the event_handler callback.
Flash the `examples/openthread` application on the nrf52840dk board. Without this patch the board is stuck in a hard fault loop. With this patch the application starts successfully.
None

pkg/openthread: set event callback before netdev init

---

tests/periph_rtt/main.c

Type casting and `printf` formatting for the `RTT_MAX_VALUE` and `RTT_FREQUENCY` are fixed so 32-bit value is properly handled by  'avr-libc'.
The original tick conversion test assumes that `RTT_FREQUENCY` is power of 2 so forward and backward ticks to seconds conversion results in the original ticks value. To fix it the result of the forward-backward conversion is compared with `ticktest / RTT_FREQUENCY * RTT_FREQUENCY` that considers rounding errors.
Changes were tested on deRFmega256 and nrf52840dongle.
tests/periph_rtt on a board with ATmega256RFR2 shall:
* show correct RTT_MAX_VALUE 
* conversion check shall report no error.
Fixes #15940

tests/periph_rtt: Fix for tick conversion test 

---

tests/drivers/l3gxxxx/Makefile

This PR fixes the `l3gxxxx` driver version used in `tests/drivers/l3gxxxx` for IoT-Lab boards. It hopefully fixes the compilation of nightly.
The problem occurred with PR #19523. 
```
BOARD=iotlab-a8-m3 make -j8 -C tests/drivers/l3gxxxx info-modules | grep l3g4200d_ng
```
should succeed.

tests/drivers/l3gxxxx: fix used sensor version for iotlab boards

---

tests/pkg_fatfs/create_fat_image_file.sh
tests/pkg_fatfs_vfs/create_fat_image_file.sh

When running `make static-tests` with PR #19551, shellcheck reports warnings with some scripts provided with `tests/pkg_fatfs` and `tests/pkg_fatfs_vfs`. The warnings are about missing double quotes around variables. This PR is fixing them.
I did a brief test of `tests/pkg_fatfs` on native and it seems to work.
Noticed that while running static tests locally with #19551

tests/pkg_fatfs*: fix shellcheck warnings

---

core/lib/include/xfa.h

With current llvm, read-only XFA's are broken.
Somehow llvm optimizes too much if the XFA is defined in the same file it is used. I'm assuming that by using the zero-sized marker array for 0+N subscript access, llvm just declares that UB.
This is how a fail looks like (llvm compile of `tests/xfa` on nrf52dk, native fails in the same way):
<details>
```
Connect to serial port /dev/ttyACM0                                            
Welcome to pyterm!                                                             
Type '/exit' to exit.                                                                                                                                          
READY
s
START
main(): This is RIOT! (Version: 2023.07-devel-211-gae51cb)
Cross file array test
xfatest[2]:
[0] = 1, …
```

core/lib: drop read only XFA's `const volatile` modifiers

---

pkg/lv_drivers/doc.txt
pkg/lv_drivers/include/lv_drv_conf.h
pkg/lvgl/Makefile
pkg/lvgl/contrib/lvgl.c
pkg/lvgl/doc.txt
pkg/lvgl/include/lv_conf.h
pkg/lvgl/include/lvgl_riot.h
pkg/lvgl/include/lvgl_riot_conf.h
tests/pkg/lvgl/README.md
tests/pkg/lvgl/main.c
tests/pkg/lvgl_touch/README.md
tests/pkg/lvgl_touch/main.c

Change all references of LittlevGL to LVGL in pkg/lvgl/doc.txt per request of LVGL team (https://github.com/lvgl/lvgl/pull/3761)
Changing parts of the pkg/lvgl/doc.txt to replace "LittlevGL" to LVGL as per request of the LVGL team
https://github.com/lvgl/lvgl/pull/3761

pkg/lvgl: Change all references of LittlevGL to LVGL

---

cpu/esp32/Makefile.include
cpu/esp32/bootloader/Makefile
cpu/esp32/esp-idf/esp_idf_cflags.mk
cpu/esp32/esp-idf/esp_idf_support.c
cpu/esp32/esp-idf/nvs_flash/Makefile
cpu/esp32/include/periph_cpu.h
cpu/esp32/periph/adc.c
cpu/esp32/periph/flashpage.c
cpu/esp32/periph/gpio.c
cpu/esp32/periph/gpio_ll.c
cpu/esp32/periph/gpio_ll_irq.c
cpu/esp32/periph/rtt.c
cpu/esp32/periph/rtt_hw_rtc.c
cpu/esp32/startup.c
cpu/esp32/syscalls.c
cpu/esp_common/esp-now/esp_now_netdev.c
cpu/esp_common/esp-wifi/esp_wifi_netdev.c
cpu/esp_common/esp-xtensa/irq_arch.c
cpu/esp_common/esp-xtensa/thread_arch.c
cpu/esp_common/freertos/ringbuf.c
pkg/esp32_sdk/patches/0028-hal-cast-esp-interrupt-type-to-riscv-interrupt-type.patch
pkg/esp32_sdk/patches/0029-nfs_flash-include-stddef.h-for-size_t-deklaration.patch
pkg/esp32_sdk/patches/0030-bt-controller-esp32s3-fix-return-types-in-functions.patch

This PR provides the changes in `cpu/esp32` and `cpu/esp_common` to fix the compilation issues with GCC v12.2.  It is required as the first step in the preparation of the upgrade to ESP-IDF version 5.1.
**Please note**: Insead of fixing the ESP-IDF 4.4 code itself by a big bunch of patches to fix the compilation problems with GCC v12.2, it temporarily disables some warnings. The reason is that the ESP-IDF 5.1 requires GCC v12.2 and should be fixed for this compiler version by the vendor.
Green CI
The change were already tested with all ESP-specific modules like `esp_now`, `esp_wifi`, `esp_spi`  and `esp_ble` for all supported ESP platforms.
Prerequisite for https://github.com/RIOT-OS/riotdocker/pull/227
Fixes issue #19421

cpu/esp32: fix compilation issues with GCC 12.2 [backport 2023.04]

---

boards/e180-zg120b-tb/doc.txt
boards/ikea-tradfri/doc.txt
boards/slstk3400a/doc.txt
boards/slstk3401a/doc.txt
boards/slstk3402a/doc.txt
boards/sltb001a/doc.txt
boards/slwstk6220a/doc.txt
boards/stk3200/doc.txt
boards/stk3600/doc.txt
boards/stk3700/doc.txt
cpu/gd32v/periph/i2c.c
cpu/native/async_read.c
cpu/native/include/async_read.h
cpu/nrf52/include/periph_cpu.h
cpu/nrf9160/include/periph_cpu.h
dist/tools/codespell/ignored_words.txt
drivers/bq2429x/include/bq2429x_internal.h
drivers/cc110x/cc110x_rx_tx.c
drivers/cc110x/include/cc110x_params.h
drivers/include/nrf24l01p_ng.h
drivers/netdev/ieee802154.c
drivers/soft_uart/soft_uart.c
pkg/openwsn/contrib/openwsn.c
sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c
sys/ztimer/mock.c
tests/driver_nrf24l01p_lowlevel/main.c

This fixes some typos and adds one correctly used abbreviation to the ignore list.
If bors merges this without static tests failing, it did what it intended to do.
Fixes issues that prevent https://github.com/RIOT-OS/RIOT/pull/19440 from merging

treewide: fix typos and false positives found by codespell [backport 2023.04]

---

boards/p-l496g-cell02/include/periph_conf.h

This PR fixes the configuration of `UART_DEV(2)`. RX and TX pin were reversed in configuration. The TX pin is connected to PB6 instead of PG10 and the RX pin is connected to PG10 instead of PB6, see [schematic](https://www.st.com/content/ccc/resource/technical/layouts_and_diagrams/schematic_pack/group2/f5/28/1b/e1/55/12/4d/3c/mb1261-cell02-b06-schematic/files/mb1261-cell02-b06-schematic.pdf/jcr:content/translations/en.mb1261-cell02-b06-schematic.pdf), page 14.
The UART interface at STMOD+ or PMOD connector should work.

boards/p-l496g-cell02: fix UART_DEV(2) configuration

---

cpu/esp32/periph/pwm.c
sys/shell/cmds/gnrc_icmpv6_echo.c

This brings format specifiers and the passed type back into sync. This won't change observable behavior in one case, and won't even change machine code in the other. But formally, this fixes bugs.
Code review is sufficient.
Fixes https://github.com/RIOT-OS/RIOT/issues/19517

treewide: fix format specifiers

---

cpu/msp430_common/ldscripts/riot-msp430f1611.ld
cpu/msp430_common/ldscripts/riot-msp430f1612.ld
cpu/msp430_common/ldscripts/riot-msp430f1617.ld
cpu/msp430_common/ldscripts/riot-msp430f2617.ld
makefiles/arch/avr8.inc.mk
makefiles/arch/msp430.inc.mk
makefiles/toolchain/gnu.inc.mk

This fixes the following compilation issues:
/home/maribu/Repos/software/RIOT/cpu/msp430fxyz/periph/gpio.c: In function 'gpio_periph_mode':
/home/maribu/Repos/software/RIOT/cpu/msp430fxyz/periph/gpio.c:95:15: error: array subscript 0 is outside array bounds of 'msp_port_isr_t[0]' [-Werror=array-bounds]
95 |         sel = &(isrport->SEL);
|               ^~~~~~~~~~~~~~~
by adding `CFLAGS += --param-min-pagesize=0` for GCC 12 (same issue as already fixed for AVR).
and:
/usr/lib/gcc/msp430-elf/12.2.0/../../../../msp430-elf/bin/ld: warning: /home/maribu/Repos/software/RIOT/cpu/msp430_common/ldscripts/xfa.ld contains output sections; did you forget -T?
by adding the missing `-T`.
The following should still work:
- `make BOARD=msb-430 -C …

makefiles/arch/msp430.inc.mk: Fix compilation issues with GCC 12

---

cpu/stm32/periph/gpio_all.c

This PR provides a small fix that is relevant when a GPIO has been used as input/output with a pull resistor before it is initialized as an ADC channel.
The PU/PD configuration has to be `0b00` for analog outputs which is corresponds to the reset state. However, if the GPIO is not in the reset state but was used digital input/output with any pull resistor, the PU/PD configuration has also to be reset to use it as ADC channel.
- Green CI
- The `periph_adc` test application should still work for any board that supports the `periph_adc` feature.

cpu/stm32/periph_gpio: reset PU/PD for ADC channels

---

cpu/stm32/periph/dac.c

This PR provides the following improvements for `periph_dac` on STM32
- Support for `RCC_APB1ENR1_DAC1EN` symbol added.
- For boards that have not connected the V_REF+ pin to an external reference voltage, the VREFBUF peripheral can be used as V_REF+ (if supported) by setting `VREFBUF_ENABLE=1`.
- If the DAC peripheral has a mode register (`DAC_MCR`), it is set to normal mode with buffer enabled and connected to external pin and on-chip peripherals. This allows to measure the current value of a DAC channel with an ADC channel or to use the DAC channel also for other on-chip peripherals.
- Green CI
- `tests/periph_dac` should still work for any board supporting the `periph_dac` feature.

cpu/stm32/periph_dac: small improvements

---

tests/build_system/external_board_dirs/external_board_dir_1/native1
tests/build_system/external_board_dirs/external_board_dir_2/native2

For native1 and native1 external boards, symlinks to boards/native are used. After #19567 these symlinks were broken and for some reason they went through the CI. This PR is fixing them.
Green CI
#19567

tests/build_system/external_board_dirs: fix broken symlinks

---

doc/doxygen/src/flashing.md

Doxygen fails to render inline code in headers correctly in the version the CI uses. So, work around the issue by not typestetting `stm32flash` as inline code but as regular text.
Check the generated doc. It the header no longer reads 
> <h2>&lt;tt&gt;stm32flash&lt;/tt&gt; Configuration</h2>
but instead
> <h2>stm32flash Configuration</h2>
the work around did the trick.
None

doc/doxygen/src/flashing.md: work around Doxygen bug

---

tests/sys/usbus_cdc_ecm/Makefile

In the Makefile of tests/sys/usbus_cdc_ecm, there's a make command given which is still using the old path to the application. This PR is fixing that.
- Green CI
- The make command given in the README works
Leftover from #19566

tests/sys/usbus_cdc_ecm: fix wrong path in make command

---

doc/doxygen/src/mainpage.md

> We moved to C11. And before that, we were at C99.
(When can we add Rust to this list?)
Check the docs
None

doc: Remove ANSI

---

sys/include/byteorder.h
sys/posix/pthread/include/pthread_cond.h

This drops special handling for Mac OS (X) `native`, which is not supported anymore anyway and causing issues when building for non-`native` targets on Mac OS.
Compilation of applications include `byteorder.h` should work again on Mac OS.
Fixes https://github.com/RIOT-OS/RIOT/issues/19590

sys: drop broken and legacy Mac OS handling

---

sys/include/net/nanocoap_sock.h
sys/net/application_layer/nanocoap/sock.c

The function has been deprecated in favor of `nanocoap_sock_get()`
#18752

nanocoap_sock: remove nanocoap_get()

---

dist/tools/insufficient_memory/add_insufficient_memory_board.sh
dist/tools/insufficient_memory/create_makefile.ci.sh

When a region wraps around the address space, the application typically is way too large to fit into the 16 bit address space of 16 bit or 8 bit platforms.
The tools should still run as before, except for the linking failures with MSP430 boards that now are classified as `too big` instead of as error.
None

dist/tools/insufficient_memory: handle address space wraps

---

makefiles/pseudomodules.inc.mk
sys/shell/cmds/Kconfig
sys/shell/cmds/coreclk.c

The coreclk shell command now prints the CPU frequency in Hz, which can be useful for boards with RC generated CPU frequency (e.g. RP2040, FE310, or MPS430Fx1xx MCUs allow this) which may quite a bit off the target frequency.
```
USEMODULE=shell_cmd_coreclk make BOARD=hifive1b -C examples/default flash term
```
And in the opened RIOT shell then `coreclk` should print the frequency of the HiFive 1b's CPU.
(Should also work with every other board, but might be boring if the CPU frequency is a compile time constant.)
Split out of https://github.com/RIOT-OS/RIOT/pull/19558. Compared to the commit in https://github.com/RIOT-OS/RIOT/pull/19558 which added this to the `shell_cmd_sys` module, this makes it its own module. This avoids pulling it in by default, as mostly the ROM spent on this cmd …

sys/shell: Add coreclk command to shell_cmd_sys

---

boards/msb-430/doc.txt

This adds basic documentation, schematics, pinouts, and info how to get started with the `msb-430` board.
The CI will provide a doc preview here that can be checked.
None

boards/msb-430: add documentation

---

Makefile.include
cpu/stm32/Makefile.cmsis
cpu/stm32/Makefile.include
cpu/stm32/dist/kconfig/README.md
dist/tools/openvisualizer/makefile.openvisualizer.inc.mk
doc/doxygen/src/advanced-build-system-tricks.md
pkg/doc.txt
pkg/lvgl/Kconfig
tests/sys/fido2_ctap/Makefile

- Replace all users of `$(RIOTBASE)/build` with the already present `$(BUILD_DIR)` variable
- Replace all users of `$(BUILD_DIR)/pkg` with the already present `$(PKGDIRBASE)` variable
- Create a `CACHEDIR.TAG` file in the `$(BUILD_DIR)`
- Green CI
- `BUILD_DIR=~/.cache/RIOT make -C tests/pkg/foobar` should work and foobar should be checked out into `~/.cache/RIOT` rather than into the `$(RIOTBASE)/build`
- A `CACHEDIR.TAG` file should be created in that directory
None

build-system: Allow out of tree BUILD_DIR

---

tests/sys/shell_coreclk/Makefile
tests/sys/shell_coreclk/main.c
tests/sys/shell_coreclk/tests/01-run.py

#19597 added the `coreclk` shell but it's not added as a default shell command, so the new shell command code (even if simple) is never built by the CI (for example with `examples/default`).
This PR is adding a simple test application for the `shell_cmd_coreclk` with a basic test script.
- Green CI
- The automatic test is working (tested on nrf52dk on iot-lab):
```
$ make -C tests/sys/shell_coreclk/ flash test BOARD=nrf52dk IOTLAB_NODE=auto
make: Entering directory '/work/riot/RIOT/tests/sys/shell_coreclk'
Building application "tests_shell_coreclk" for "nrf52dk" with MCU "nrf52".
"make" -C /work/riot/RIOT/pkg/cmsis/ 
"make" -C /work/riot/RIOT/boards/common/init
"make" -C /work/riot/RIOT/boards/nrf52dk
"make" -C /work/riot/RIOT/boards/common/nrf52xxxdk
"make" …
```

tests/sys/shell_coreclk: add test application for shell_cmd_coreclk

---

boards/adafruit-clue/Makefile.include

Most of the variables defined in the Makefile.include are the same in `usb_board_reset.mk`. Let's include that file instead.
- flash, reset, term are working as expected on adafruti-clue:
```
$ make -C examples/default BOARD=adafruit-clue flash term --no-print-directory 
Building application "default" for "adafruit-clue" with MCU "nrf52".
"make" -C /work/riot/RIOT/pkg/cmsis/ 
"make" -C /work/riot/RIOT/boards/adafruit-clue
"make" -C /work/riot/RIOT/boards/common/init
"make" -C /work/riot/RIOT/core/lib
"make" -C /work/riot/RIOT/cpu/nrf52
"make" -C /work/riot/RIOT/cpu/cortexm_common
"make" -C /work/riot/RIOT/cpu/cortexm_common/periph
"make" -C /work/riot/RIOT/cpu/nrf52/periph
"make" -C /work/riot/RIOT/cpu/nrf52/vectors
"make" -C /work/riot/RIOT/cpu/nrf5x_common …
```

boards/adafruit-clue: use shared usb_board_reset.mk for flash/reset/term targets

---

makefiles/tools/usb_board_reset.mk

When running `make info-boards-supported` in an application directory, I got several warning from make:
```
$ make -C examples/hello-world info-boards-supported --no-print-directory 
/work/riot/RIOT/makefiles/tools/usb_board_reset.mk:32: warning: overriding recipe for target 'preflash-delay'
/work/riot/RIOT/makefiles/tools/usb_board_reset.mk:32: warning: ignoring old recipe for target 'preflash-delay'
/work/riot/RIOT/makefiles/tools/usb_board_reset.mk:35: warning: overriding recipe for target 'term-delay'
/work/riot/RIOT/makefiles/tools/usb_board_reset.mk:35: warning: ignoring old recipe for target 'term-delay'
/work/riot/RIOT/makefiles/tools/usb_board_reset.mk:32: warning: overriding recipe for target 'preflash-delay'
/work/riot/RIOT/makefiles/tools/usb_board_reset.mk:32: warning: …
```

make/usb_board_reset: define {preflash,term}-delay when necessary

---

cpu/atmega_common/include/cpu_conf.h
drivers/at86rf2xx/at86rf2xx_netdev.c
drivers/at86rf2xx/include/at86rf2xx_internal.h
sys/include/net/gnrc/netif/hdr.h
sys/net/gnrc/netif/hdr/gnrc_netif_hdr_print.c
tests/net/gnrc_netif_ieee802154/Makefile
tests/net/gnrc_netif_ieee802154/main.c

The PR adds setting the 802.15.4 packet reception timestamp based on the symbol counter available in ATmega64/128/256RFR2 MCU. The counter restarts every ~19 hours.
To enable the feature the `USEMODULE += gnrc_netif_timestamp` needs to be added to a Makefile.
The `tests/net/gnrc_netif_iee802154` was updated to check the behavior on real boards.
The test was performed on `derfmega256` and `nrf52840dongle` boards:
Two commands `txtsnd 4 bcast test` issued on nrf52840dongle 10 seconds apart, lead to the following result on the `derfmega256`:
>PKTDUMP: data received:
~~ SNIP  0 - size:   4 byte, type: NETTYPE_UNDEF (0)
00000000  74  65  73  74
~~ SNIP  1 - size:  20 byte, type: NETTYPE_NETIF (-1)
if_pid: 4  rssi: -25   timestamp: _**769.117280000**_ lqi: 65
flags: BROADCAST TIMESTAMP …

drivers/at86rf2xx: setting rx timestamp based on symbol counter for ATmega*RFR2

---

drivers/dfplayer/include/dfplayer_implementation.h
drivers/include/dfplayer.h

Apparently, those functions have never been used. Otherwise this obvious bug wouldn't have sailed unnoticed for so long.
The bug is so obvious that code review is sufficient.
None

drivers/dfplayer: fix bug in utility function

---

drivers/pcf857x/pcf857x.c

This fixes a typo/copy paste error in the error handling.
Code review should be sufficient
None

drivers/pcf857x: fix error handling

---

drivers/slipdev/slipdev.c

A typo resulted in a boolean expression to always be true and the `_poweron()` function to always exit early. This fixes the issue.
Code review should be sufficient, IMO. But one could test the poweron function.
None

drivers/slipdev: fix logic bug

---

makefiles/deprecated_modules.inc.mk
makefiles/pseudomodules.inc.mk
sys/include/event/thread.h

And its remaining references in the documentation. It was marked as to removed after  2021.10 and it's not used anywhere in the codebase.
- Green CI

makefiles/pseudomodules: remove deprecated event_thread_lowest module

---

cpu/stm32/include/periph/cpu_pwm.h
cpu/stm32/periph/pwm.c

This PR provides the support of complementary timer outputs as PWM channels for advanced timers (TIM1/TIM8).
To use a complementary output of an advanced timer as PWM channel, the output is defined with an offset of 4, i.e. normal outputs are in the range of 0 to 3 (CH1...CH4) and complementary outputs are in the range of 4 to 6 (CH1N...CH3N). If the defined output is less than 4, the normal output is enabled, otherwise the complementary output is enabled.
This change is required to support PWM on boards that have connected the complementary outputs of advanced timers to the PWM connector pins, for example the STM32L496-DISCO board.
- Green CI
- Use any STM32 board which supports the `periph_pwm` feature. `tests/periph_pwm` should still work.
- Change the configuration for this board so …

cpu/stm32/periph_pwm: support of complementary timer outputs

---

cpu/arm7_common/common.s

Hellooo! 🦤
In this PR a single `NOP` is added after an `ldm` in ARM7 common code in the scheduling management.
The change is necessary because this particular `ldm` affects certain banked registers, including `R14 / lr`. The next instruction then immediately accesses `lr`. This is invalid and the exact effect depends on the underlying hardware implementation. An intermediate `NOP` ensures correct behaviour in such cases.
The ARM docs can be found [here](https://documentation-service.arm.com/static/5f8dacc8f86e16515cdb865a), in section `A4.1.21 LDM (2)`. It states:
> In ARM architecture versions earlier than ARMv6, this form of LDM must not be
followed by an instruction that accesses banked registers. A following NOP is a good
way to ensure this.
Without this change, on the Game Boy …

cpu/arm7: Fix undefined behavior based on invalid assembly

---

drivers/mrf24j40/mrf24j40_radio_hal.c

`_set_csma_params()` spends some time to prepare a value in `uint8_t tmp`, which then is never used. Likely this is a leftover of moving code to `mrf24j40_set_csma_max_retries()`. This drops the leftover code.
The driver should still correctly apply CSMA settings.
Split out of https://github.com/RIOT-OS/RIOT/pull/19634

drivers/mrf24j40: cleanup function

---

drivers/periph_common/Kconfig
drivers/periph_common/Kconfig.timer

This PR is a very small fix of inconsistent peripheral driver entry in `Kconfig` for `periph/timer`.
In Kconfig menu `(Top) → Drivers → Peripherals drivers` all entries start with the peripheral name in alphabetical order with only one exception, the timer entry. This entry is called `Configure timer peripheral driver`:
```
[ ] CPU unique ID
[ ] EEPROM peripheral driver
[ ] Flashpage peripheral driver  ----
[*] GPIO peripheral driver  --->
[ ] HWRNG peripheral driver
[ ] PWM peripheral driver
[*] Power Management (PM) peripheral driver
[*]     Auto initialize Power Management (PM) peripheral
[ ] Quadrature Decoder (QDEC) peripheral driver
[ ] RTC peripheral driver  ----
[ ] SPI peripheral driver  ----
[*] UART peripheral driver  --->
[*] Configure timer peripheral driver  --->
```
This is …

periph/timer: fix Kconfig menu title

---

cpu/stm32/cpu_common.c
cpu/stm32/include/periph/cpu_common.h

This fixes some minor doc and argument type errors. See commit messages for details.
It compiles without errors for me.
None known

Fix periph clk

---

sys/usb/usbus/msc/scsi.c

Rather than setting the correct blk_len, the code only wrote 1 and 0 into the three bytes due to the use of a logic and where a bitwise and should be used.
Code review should be sufficient, the issue is pretty obvious in the diff.
Split out of https://github.com/RIOT-OS/RIOT/pull/19634

sys/usb/usbus_msc: fix typo in C expression

---

sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c

We have put a Raspberry Pi behind a 6Lo network and discovered that the 6Lo router includes the 6Lo ND options in router advertisements over the non sixlowpan interface to the Pi.
This behaviour is probably not useful/intended. So we check if the interface over which the RA is sent, is a 6Lo interface before the 6Lo ND options are appended. 
Our setup is Raspi --> 6LBR --> 6LR --> Raspi
alternative to #17594

gnrc/ipv6/nib: fix 6Lo ND options on non 6Lo interface

---

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c

No regression in RPL. (Beware: Fully untested!)
fixes https://github.com/RIOT-OS/RIOT/issues/15006 (or rather the last issue of the three instances reported there)

sys/net/rpl: fix possible NULL dereference

---

core/include/thread.h
cpu/cortexm_common/include/thread_arch.h

No architecture makes use of thread_arch_t anymore, so let's drop it.
Green CI and no change in binaries.
None

core/thread: drop unused thread_arch_t

---

drivers/sx126x/sx126x_netdev.c

The lowest possible value is `LORA_SF5` and not `LORA_SF6`. This fixes the argument validation to allow setting `LORA_SF5` as spreading factor.
Code review with this snipped in mind should be sufficient:
https://github.com/RIOT-OS/RIOT/blob/eb10a5ccd8d810ed2ff5e6451035c0d83351061b/sys/include/net/lora.h#L249-L261
Otherwise, testing to set the spreading factor is possible.
Fixes https://github.com/RIOT-OS/RIOT/issues/17861

drivers/sx126x: fix argument validation in spreading factor

---

drivers/mtd_spi_nor/mtd_spi_nor.c

This patch adds a missing release of the SPI bus on error
This was discovered while attempting to bring up a board where I had the pin definitions wrong for a SPI flash part. Once the driver was fixed I was able to get the debug messages and not hang other drivers using the same bus.
None known

drivers/mtd_spi_nor: fix hang and debug msgs

---

dist/tools/compile_commands/compile_commands.py

Filter out GCC only `--param=min-pagesize=0` in `clangd` mode. This fixes compilation of rust applications, that now fails with:
thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("error: argument unused during compilation: '--param=min-pagesize=0' [-Wunused-command-line-argument]\n")', /home/maribu/.cargo/git/checkouts/rust-riot-sys-d12733b89271907c/b4bd4bd/build.rs:224:10
```
make BOARD=cc1352-launchpad -C examples/rust-hello-world
```
fails in `master`, but should work again with this PR.
None

dist/tools/compile_commands: add another workaround

---

sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c
sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c

Linux will ignore RIOs with preference NONE, so set the preference to zero instead.
RIOT currently ignores the preference.
Linux accepts the route from an upstream RIOT node
fd00::/32 via fe80::6481:20ff:fef9:b694 dev usb0 proto ra metric 1024 expires 4294451sec pref medium

gnrc_ipv6_nib: set default RIO preference to zero

---

core/lib/include/bitarithm.h
sys/net/network_layer/ipv6/addr/ipv6_addr.c

Make use of the `clz` (count leading zeros) instruction present on most CPUs instead of coding it manually.
This saves 40 bytes on Cortex-M0+.
`tests-ipv6_addr` still succeeds.

net/ipv6: make use of clz in ipv6_addr_match_prefix()

---

cpu/samd5x/cpu.c
cpu/samd5x/include/periph_cpu.h

This PR allows to use the second FDPLL (the first one is used to generated the 120MHz frequency used by the core and some peripherals). The second FDPLL is setup to run at 200MHz which is the maximum allowed by this MCU.
In fact, I reused the existing function which setup FDPLL0 so it can be used in a generic way for both PLL (since they are the same IP).
I change the way the computation offset (left shift by 5)  is done because 200MHz << 5 wouldn't fit inside an `uint32_t` and I wanted to avoid using an `uint64_t` here
Two additional commits are present for a small cleanup and a fix.
This is currently unused in our codebase, so it shouldn't impact this platform too much as the `ONDEMAND` bit is set. the FDPLL will not be running out of the box. But @gschorcht might need it pretty soon. …

cpu/samd5x: enable FDPLL1 at 200MHz

---

examples/suit_update/tests-with-config/01-run.py

Seems like this test wasn't updated when we introduced suit_workers.
The test-with-config make target fails on master, succeeds with this PR.

examples/suit_update: some test fixes

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

I think the 6LBR is not supposed to send RS on its downstream 6LO interface.
Consequently, I think the 6LBR interface is also not supposed to handle RA on the downstream interface.
Code existed to exclude the border router but it was not fully working.
```diff
diff --git a/sys/net/gnrc/network_layer/ndp/gnrc_ndp.c b/sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
index ec9e18b3a7..cafd6dd644 100644
--- a/sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
+++ b/sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
@@ -441,7 +441,7 @@ void gnrc_ndp_rtr_sol_send(gnrc_netif_t *netif, const ipv6_addr_t *dst)
if (dst == NULL) {
dst = &ipv6_addr_all_routers_link_local;
}
-    DEBUG("ndp: send router solicitation (iface: %" PRIkernel_pid
+    printf("ndp: send router solicitation (iface: %" PRIkernel_pid
", dst: %s)\n", …
```

ipv6/nib: 6LBR should not send RS on their downstream interface

---

cpu/stm32/stm32_riotboot.mk

This PR fixes the `riotboot` configuration for L4 and WB.
The family is not called `stm32l4` or `stm32wb` but `l4` and `wb`. That is, the `riotboot` configuration didn't work at all. Furthermore, a minimum `RIOTBOOT_LEN` of `0x2000` is required for L4.
Found when investigating the compilation errors for `bootloaders/riotboot_serial` in PR #19576.
1. Green CI.
2. Use the following commands:
```
BOARD=nucleo-l496zg make -C tests/riotboot info-debug-variable-RIOTBOOT_HDR_LEN
BOARD=p-nucleo-wb55 make -C tests/riotboot info-debug-variable-RIOTBOOT_HDR_LEN
```
In master these commands give
```
0x400
```
With this PR these commands give
```
0x200
```
as expected.
3. Use the following commands:
```
BOARD=nucleo-l496zg make -C tests/riotboot info-debug-variable-RIOTBOOT_LEN
BOARD=p-nucleo-wb55 …
```

cpu/stm32: fix riotboot settings for L4 and WB

---

tests/net/gnrc_mac_timeout/tests/01-run.py

in ##19636 (and more precisely in da854bb8f8783f022040e1dc2ee0625170fdcf6e), I noticed that this test could be automated quite easily.
- Green CI (Murdock should run the test on native)
- Tested on iotlab-m3 and nrf52dk remotely on IoT-LAB and it works as expected:
<details>
- iotlab-m3:
```
$ make -C tests/net/gnrc_mac_timeout/ flash test BOARD=iotlab-m3 IOTLAB_NODE=auto
make: Entering directory '/work/riot/RIOT/tests/net/gnrc_mac_timeout'
Building application "tests_gnrc_mac_timeout" for "iotlab-m3" with MCU "stm32".
"make" -C /work/riot/RIOT/pkg/cmsis/ 
"make" -C /work/riot/RIOT/boards/common/init
"make" -C /work/riot/RIOT/boards/iotlab-m3
"make" -C /work/riot/RIOT/boards/common/iotlab
"make" -C /work/riot/RIOT/core/lib
"make" -C /work/riot/RIOT/cpu/stm32 …
```

tests/net/gnrc_mac_timeout: add automated test

---

sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c

We have a `/33` compression context
```
2023-05-23 11:41:47,813 - INFO # cid|prefix                                     |C|ltime
2023-05-23 11:41:47,819 - INFO # -----------------------------------------------------------
2023-05-23 11:41:47,823 - INFO #   0|                          fd00:0:8000::/33 |1| 1439min
``` 
And a route to a `/64` subnet inside the previous network.
```
2023-05-23 11:41:55,146 - INFO # fd00::/32 dev #6
2023-05-23 11:41:55,148 - INFO # fd00:0:8000::/33 dev #5
2023-05-23 11:41:55,153 - INFO # fd00:0:c000::/64 via fe80::e858:4ed2:564e:345b dev #5
2023-05-23 11:41:55,157 - INFO # default via fe80::6a9a:4308:e40a:aa8a dev #6
```
We can successfully ping a host inside the `/64` network.
```
2023-05-23 11:42:38,163 - INFO # > ping fd00:0:c000:0:6481:20ff:fef9:b694 …
```

gnrc_sixlowpan_iphc: prefix bits outside context must be zero

---

core/lib/include/compiler_hints.h
sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c

Linux only accepts Router Advertisements for SLAAC [if the prefix length is /64](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/addrconf.c#n2790).
Add a config option to `gnrc_ipv6_auto_subnets` to create smaller subnets if necessary.
A downstream Linux host gets a prefix from the upstream RIOT router with `gnrc_ipv6_auto_subnets`:
```
104: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
link/ether 66:81:20:f9:aa:94 brd ff:ff:ff:ff:ff:ff
inet 169.254.226.86/16 brd 169.254.255.255 scope global noprefixroute usb0
valid_lft forever preferred_lft forever
inet6 fd00:0:c000:0:e46:895a:43bc:f080/64 scope global dynamic mngtmpaddr noprefixroute 
valid_lft 72155sec preferred_lft 155sec
inet6 …
```

gnrc/ipv6_auto_subnets: allow to configure minimal prefix length

---

dist/tools/openocd/openocd.sh
dist/tools/openocd/openocd_flashinfo.py

Since [80fc9fabc66a0bc767467fa14c703e5a9f340cd3] the format of the `flash list` command changed to a more human readable multi-line variant. Technically, the change is white-space only. Still, the current approach of parsing them with awk, sed and cut doesn't like the new multi-line format. The parsing is now delegated into a python script that is compatible across OpenOCD versions.
[80fc9fabc66a0bc767467fa14c703e5a9f340cd3]: https://github.com/openocd-org/openocd/commit/80fc9fabc66a0bc767467fa14c703e5a9f340cd3
```
PROGRAMMER=openocd BOARD=nrf52840dk make -C tests/riotboot/ riotboot/flash-slot1
```
Should now work even with an fresh OpenOCD build from git
Found while looking into https://github.com/RIOT-OS/RIOT/issues/14576

dist/tools/openocd: fix parsing of flash bank base

---

pkg/littlefs2/Makefile

This release bumps the on-disk minor version of littlefs from lfs2.0 -> lfs2.1.
This change is backwards-compatible, but after the first write with the new version, the image on disk will no longer be mountable by older versions of littlefs.
https://github.com/littlefs-project/littlefs/releases/tag/v2.6.0
`tests/pkg_littlefs2` still works

pkg/littlefs2: bump version to 2.6

---

Makefile.include

Just run `make compile-commands` outside of docker, as the compile commands generated in the docker container won't be helpful for tools outside of the container anyway.
```
make BOARD=<some board> BUILD_IN_DOCKER=1 -C examples/default compile-commands
```
Should now work (but run on the host's system anyway).
Fixes https://github.com/RIOT-OS/RIOT/issues/17507

build system: fix `make compile-commands BUILD_IN_DOCKER=1`

---

drivers/mpu9x50/mpu9x50.c

Avoid using floating point arithmetic and some minor cleanups.
```sh
make BOARD=msbiot -C examples/default flash term
```
```
> 2023-05-23 21:40:13,551 # main(): This is RIOT! (Version: 2023.07-devel-420-geb10a)
2023-05-23 21:40:13,553 # Welcome to RIOT!
> saul read 5
2023-05-23 21:40:16,845 # saul read 5
2023-05-23 21:40:16,849 # Reading from #5 (mpu9x50|SENSE_ACCEL)
2023-05-23 21:40:16,852 # Data:	[0]         -25 mgₙ
2023-05-23 21:40:16,854 # 	[1]         -36 mgₙ
2023-05-23 21:40:16,856 # 	[2]         998 mgₙ
> saul read 6
2023-05-23 21:40:20,102 # saul read 6
2023-05-23 21:40:20,106 # Reading from #6 (mpu9x50|SENSE_GYRO)
2023-05-23 21:40:20,109 # Data:	[0]         0.0 dps
2023-05-23 21:40:20,110 # 	[1]         0.2 dps
2023-05-23 21:40:20,112 # 	[2]         0.0 dps
> saul read 7 …
```

drivers/mpu9x50: clean up code

---

sys/posix/sockets/posix_sockets.c

- Fix double indent of switch cases to single indent, as per coding convention. (Whitespace only change.)
- Set sin6_scope_id to netif in `_ep_to_sockaddr()`
- Check the first commit indeed is a whitespace only change
- except for an `assert(0)` added to the `default:` case of a switch replacing an `assert((ep->family == AF_INET) || (ep->family == AF_INET6));` before the `switch(ep->family)`. But this does the same, while being more readable.
- Review the second commit (a one-liner)
Fixes https://github.com/RIOT-OS/RIOT/issues/19486

sys/posix/sockets: fix code style & set sin6_scope_id in _ep_to_sockaddr() 

---

.murdock
cpu/rpx0xx/Kconfig
drivers/periph_common/Kconfig
kconfigs/Kconfig.features

Broken master due to incorrect model of the periph_pio in kconfig.
Green murdock (now that the board is added to the list)
Look at the master CI...

cpu/rpx0xx: Fix kconfig model

---

drivers/lc709203f/lc709203f.c

removes a unnecessary use of float
read and test if you got that hardware (I don't)
#19614

driver/lc709203f: remove unnecessary use of float

---

doc/doxygen/Makefile

- simplify the makefile
- changing behavior depending on lessc being installed is surprising and makes the Makefile less readable
- failing with `make: lessc: No such file or directory` is helpful, but `make: No rule to make target 'src/css/riot.css'` is not clearly indicating that `lessc` was not found
- don't rebuild `riot.css` when generating HTML output
- anyone touching the less file will have to manually call `make src/css/riot.css -C doc/doxygen`
- this happens so rarely that implementing a convenient mechanism is not worth the trouble
`make doc` should no longer regenerate `riot.css`, regardless of whether `lessc` is available or not.
Fixes https://github.com/RIOT-OS/RIOT/issues/8122

doc: do not rebuild riot.css

---

boards/stm32l496g-disco/Kconfig
boards/stm32l496g-disco/Makefile
boards/stm32l496g-disco/Makefile.dep
boards/stm32l496g-disco/Makefile.features
boards/stm32l496g-disco/Makefile.include
boards/stm32l496g-disco/doc.txt
boards/stm32l496g-disco/include/arduino_board.h
boards/stm32l496g-disco/include/arduino_pinmap.h
boards/stm32l496g-disco/include/board.h
boards/stm32l496g-disco/include/gpio_params.h
boards/stm32l496g-disco/include/periph_conf.h

The PR adds the board definition for the STM2L496G-DISO board.
It is the same board that is also shipped with the P-L496G-CELL02 LTE pack for which we already have the board definition `p-l496g-cell02`. However, `stm32l496g-disco` provides a complete configuration of the board and supports the following features in addition to `p-l496g-cell02`:
```
> FEATURES_PROVIDED += periph_adc
> FEATURES_PROVIDED += periph_dac
> FEATURES_PROVIDED += periph_dma
> FEATURES_PROVIDED += periph_pwm
> FEATURES_PROVIDED += periph_uart_hw_fc
> FEATURES_PROVIDED += arduino
```
In the long term, `p-l496g-cell02` is to be based on the new full `stm32l496g-disco` board definition.
The CPT and the LCD display are not yet supported since they are connected to/controlled by the MFX (a STM32L152-based sub-system) …

boards: add stm32l496g-disco support

---

sys/include/suit/transport/worker.h
sys/suit/transport/worker.c

While SUIT can generally be used already with manifests that are "dropped into memory" (by any mechanism), the convenient SUIT worker thread mechanism so far could not be used with it.
This adds the suit_worker_try_prepare / suit_worker_trigger_prepared
pair for using the SUIT worker, and breaks suit_handle_manifest_buf out
of suit_handle_url (where the latter now calls the former).
As part of factoring out reaping of the zombie worker thread, a locking
error that deadlocks the SUIT worker in case the race between the mutex
being unlocked and the thread being reaped hits the necessary handling
code is fixed (and mutex_unlock is called in the error path).
SUIT tests should pass.
https://github.com/RIOT-OS/RIOT/pull/19659 provides a demo of how the new API is used.
I think that the …

SUIT: Prepared manifests

---

sys/include/shell.h
sys/include/shell_lock.h
sys/shell/shell.c
sys/shell_lock/shell_lock.c
tests/sys/shell_lock/Makefile

We *always* want `CONFIG_SHELL_SHUTDOWN_ON_EXIT` not to be set if `shell_lock` us used as `shell_lock` will exit the shell to lock it.
Run `tests/shell_lock` on `native` (or any other `native` app with `shell_lock` enabled)

shell_lock: don't set CONFIG_SHELL_SHUTDOWN_ON_EXIT

---

cpu/stm32/periph/adc_f1.c
cpu/stm32/periph/adc_f2.c
cpu/stm32/periph/adc_f4_f7.c

The current implementation uses the core clock frequency to calculate the needed prescalar to achieve a given ADC clock frequency. This is incorrect. This patch fixes the calculation to use the correct source clock (PCKLK2 ie APB2). It also changes the defined max clock rate to use the frequency macro to improve readability.
I based on code similarity. I believe the gd32v CPU may need this same fix, but I am not familiar with that MCU.
I tested this on a nucleo-f767zi. The the MCU's reference manual is in agreement with what I have implemented here. I spot checked references manuals for a random [STM32F1](https://www.st.com/resource/en/reference_manual/cd00171190-stm32f101xx-stm32f102xx-stm32f103xx-stm32f105xx-and-stm32f107xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf) and …

cpu/stm32/periph/adc: fix setting ADC clock

---

dist/tools/buildsystem_sanity_check/check.sh

This is a follow-up of all PRs that moved/grouped test applications into subdirectories, to prevent tests application placed in `tests/pkg_<something>`, etc.
- Green CI
- There's a REMOVEME commit that should make static tests fail
Follow-up of the many PRs related to tests subdirectories

tools/build_system_sanity_check: add check to verify test applications are at the right place

---

cpu/stm32/include/gpio_ll_arch.h

sometimes one wants to save one instruction :) 
just write the bits we need to write.
tests/periph/gpio_ll tests this 
@maribu might know some reference
maybe #19407

cpu/stm32: stm32f4 BRR from BSRR

---

cpu/native/periph/rtc.c
cpu/qn908x/periph/rtc.c
cpu/sam0_common/periph/rtc_rtt.c
drivers/include/periph/rtc.h
drivers/rtt_rtc/rtt_rtc.c

- point out behavior on denormalized time stamps
- use errno codes to indicate errors (and adapt the few instances of actual error handling to use them)
This should not really effect behavior, except for error return codes. But nobody checks them anyway :sweat_smile:
Fixes https://github.com/RIOT-OS/RIOT/issues/16574

drivers/periph/rtc: improve doc on rtc_set_alarm

---

boards/common/stm32/include/cfg_timer_tim2_tim15_tim16.h
boards/nucleo-l432kc/include/periph_conf.h
cpu/stm32/include/periph/cpu_timer.h
cpu/stm32/periph/timer.c

- `cpu/stm32/periph_timer`: Generalize to also work with timers that do not have 4 channels
- `boards/common/stm32`: Add timer config for three timers based on TIM2, TIM15, and TIM16 (the three general-purpose timers of the STM32L4)
- `boards/nucleo-l432kc`: Make use of the new timer config
`make BOARD=nucleo-l432kc -C tests/periph/timer flash test`
```
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.07-devel-510-ge690e-stm32_cfg_timer_tim2_tim15_tim16)
Test for peripheral TIMERs
Available timers: 3
Testing TIMER_0:
TIMER_0: initialization successful
TIMER_0: stopped
TIMER_0: set channel 0 to 5000
TIMER_0: set channel 1 to 10000
TIMER_0: set channel 2 to 15000
TIMER_0: set channel 3 to 20000
TIMER_0: starting
TIMER_0: channel 0 fired at SW count    24996 - init:    24996
TIMER_0: …
```

boards/nucleo-l432k: provide three periph_timer instances

---

cpu/sam0_common/periph/eth.c

Just some small quirks I noticed when looking at the driver
- don't enable PHY twice
- properly set `NCFGR` register
- `sam0_read_phy()` does not return a signed value
There is no change in observed functionality.

cpu/sam0_eth: clean up init()

---

sys/include/string_utils.h
sys/libc/string.c
sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
tests/unittests/tests-libc/tests-libc.c

This adds a function to check if all bytes in a buffer are set to a certain value.
Currently only gnrc_pktbuf_static` makes use of this, but I've used something similar in other places, often open-coded - so let's add it in a common place instead.
A new unit test has been added.

sys/string_utils: add memchk()

---

tests/unittests/tests-core/tests-core-atomic.c

This reverts #13462, this workaround is no longer needed with newer GCC version.
Try to compile tests/unittests for `saml11-xpro` or `saml10-xpro`
This is a revert of #13462.

tests/unittests: remove old workaround for SAML1X and gcc9.X bug

---

sys/usb/usbus/usbus.c

- flash `tests/sys/usbus_cdc_ecm`
- reboot the host system
On `master` this assertion will trigger, with this patch the duplicate URB is ignored.
Network operation continues normal:
```
2023-05-24 18:24:36,366 - INFO # > ping -c 200 ff02::1%8
2023-05-24 18:24:36,367 - INFO # 
2023-05-24 18:24:36,375 - INFO # 12 bytes from fe80::650a:e7fd:8b57:c7e8%8: icmp_seq=0 ttl=64 time=1.639 ms
2023-05-24 18:24:37,375 - INFO # 12 bytes from fe80::650a:e7fd:8b57:c7e8%8: icmp_seq=1 ttl=64 time=1.433 ms
2023-05-24 18:24:38,377 - INFO # 12 bytes from fe80::650a:e7fd:8b57:c7e8%8: icmp_seq=2 ttl=64 time=2.525 ms
2023-05-24 18:24:39,377 - INFO # 12 bytes from fe80::650a:e7fd:8b57:c7e8%8: icmp_seq=3 ttl=64 time=2.372 ms
2023-05-24 18:24:40,378 - INFO # 12 bytes from fe80::650a:e7fd:8b57:c7e8%8: icmp_seq=4 …
```

usbus: don't trigger assertion in usbus_urb_submit()

---

drivers/saul/init_devs/auto_init_shtcx.c

In `master` the assertion triggers:
```
2023-05-31 14:30:08,173 - INFO # 4e7f
2023-05-31 14:30:08,173 - INFO # 
2023-05-31 14:30:08,173 - INFO # Context before hardfault:
2023-05-31 14:30:08,174 - INFO #    r0: 0x00000005
2023-05-31 14:30:08,174 - INFO #    r1: 0x2000544d
2023-05-31 14:30:08,175 - INFO #    r2: 0x00000005
2023-05-31 14:30:08,175 - INFO #    r3: 0x12000000
2023-05-31 14:30:08,175 - INFO #   r12: 0x00000005
2023-05-31 14:30:08,189 - INFO #    lr: 0x0000056b
2023-05-31 14:30:08,189 - INFO #    pc: 0x0000056a
2023-05-31 14:30:08,190 - INFO #   psr: 0x21000000
2023-05-31 14:30:08,190 - INFO # 
2023-05-31 14:30:08,190 - INFO # FSR/FAR:
2023-05-31 14:30:08,191 - INFO #  CFSR: 0x00000000
2023-05-31 14:30:08,191 - INFO #  HFSR: 0x80000000
2023-05-31 14:30:08,192 - INFO #  DFSR: …
```

drivers/shtcx: fix assertion and shtcx_saul_info idx

---

drivers/bmx055/bmx055.c

As the title says...
Code review should be sufficient
None

drivers/bmx055: fix crazy use of FPU

---

drivers/include/mq3.h
drivers/mq3/mq3.c

Code review should be sufficient.
https://github.com/RIOT-OS/RIOT/issues/19614

drivers/mq3: avoid use of floats

---

tests/pkg/lvgl/main.c

Code review should be sufficient. Alternatively, one could even do stuff like
```C
((uint32_t)hres * 26214) >> 16
```
to get rid of the division, but that is IMO not worth the mental overhead here.
None

tests/pkg/lvgl: avoid using floats

---

cpu/sam0_common/periph/eth.c

When we put the interface to sleep, also disable the PHY. This saves 75 µA of current on the `same54-xpro` (value will differ depending on the PHY used)
- idle         13.88 mA
- MAC off      11.48 mA
- MAC+PHY off  10.73 mA
```
2023-05-31 14:06:56,000 - INFO # > ifconfig 5 set state sleep
2023-05-31 14:06:56,000 - INFO # 
2023-05-31 14:06:56,004 - INFO # success: set state of interface 5 to SLEEP
2023-05-31 14:07:00,049 - INFO # > ifconfig 5 set state idle
2023-05-31 14:07:00,049 - INFO # 
2023-05-31 14:07:00,052 - INFO # success: set state of interface 5 to IDLE
2023-05-31 14:07:03,686 - INFO # > ping 2600::
2023-05-31 14:07:03,687 - INFO # 
2023-05-31 14:07:03,811 - INFO # 12 bytes from 2600::: icmp_seq=0 ttl=50 time=119.139 ms
2023-05-31 14:07:04,811 - INFO # 12 bytes from 2600::: …
```

cpu/sam0_eth: disable PHY when MAC is sleeping

---

sys/usb/Kconfig

Seems like I just didn't have the correct `USB_PID` defined in the `usb-codes.inc.mk`.
It should be 0x7D01 not 0x7001.
It only shows up in nightlies since the hash would mismatch.
Simulated nightly testing with:
```
./dist/tools/compile_test/compile_like_murdock.py -j 8 -a tests/pkg/tinyusb_cdc_acm_stdio/ tests/pkg/tinyusb_cdc_msc/ tests/pkg/tinyusb_cdc_msc/ tests/sys/fido2_ctap/ tests/sys/usbus_board_reset/ tests/sys/usbus_msc/  -b arduino-zero samd21-xpro nucleo-f767zi -v
```
<details>
```
tests/pkg/tinyusb_cdc_acm_stdio/ arduino-zero                   PASS
ctests/pkg/tinyusb_cdc_acm_stdio/ nucleo-f767zi                  PASS
tests/pkg/tinyusb_cdc_acm_stdio/ samd21-xpro                    PASS
tests/pkg/tinyusb_cdc_msc/     arduino-zero                   PASS
tests/pkg/tinyusb_cdc_msc/ …
```

sys/usb/Kconfig: Fix default PID

---

makefiles/toolchain/gnu.inc.mk

The `--param=min-pagesize=0` needed since GCC 12 is still needed with GCC 13. This time at least the message is more meaningful:
note: source object is likely at address zero
This is something that is not expected in a userspace app, but with bare metal MCUs and often flash or memory mapped I/O starting from address zero, this warning prevents legitimate code from compiling.
With `master`:
```
$ make BOARD=olimex-msp430-h1611 -C examples/hello-world
Building application "hello-world" for "olimex-msp430-h1611" with MCU "msp430fxyz".
"make" -C /home/maribu/Repos/software/RIOT/master/boards/olimex-msp430-h1611
"make" -C /home/maribu/Repos/software/RIOT/master/core
"make" -C /home/maribu/Repos/software/RIOT/master/core/lib …
```

makefiles/toolchain/gnu.inc.mk: fix compilation

---

sys/include/imath.h
tests/drivers/dac_dds/main.c

An integer-only `sin()` function is generally useful, move it to a common place `imath` where more integer-only math functions can be added when needed.
This only moves code around.

sys: add common imath module mv isin() form test/driver_dac_dds

---

sys/color/color.c
tests/unittests/tests-color/tests-color.c

this extends the unittest for sys_color testing more colors 
```
RIOT_tree/tests/unittests$ make tests-color test
```
will fail since our `rgb2hsv` implementation is wrong (or is using an other colorspace than hsv2rgb (without documenting))
the new `hsv2rgb` test will succeed
#19614  was the reason i had a look at this 
#1315 added the rgb2hsv and hsv2rgb function
#9940 added the test for black special case
https://www.vagrearg.org/content/hsvrgb << some optimization for that function (avoiding float)

sys/color: extend unittest and fix module

---

drivers/include/mrf24j40.h

This adds a note that wake pin handling is not implemented and users need to connect the wake pin to VCC, or drive it high in the board / application logic prior to initializing the driver.
Read the generated doc.
Fixes https://github.com/RIOT-OS/RIOT/issues/19711

drivers/mrf24j40: add note about missing wake pin handling

---

boards/z1/include/periph_conf.h
cpu/msp430fxyz/clock.c

The MSP430F2xx family has on RSEL bit more than the MSP430x1xxx family. The first commit updates the clock calibration accordingly.
https://github.com/RIOT-OS/RIOT/commit/df5c319978570f90071bbc83ddf10eea5449d46d from https://github.com/RIOT-OS/RIOT/pull/19558 broke the clock configuration of the Z1 by relying on the incorrect documentation of what clock is actually used. Closely reading the convoluted clock initialization code revealed that no XT2 crystal is present (as also indicated by some comments in `board.c`), contradicting the `#define MSP430_HAS_EXTERNAL_CRYSTAL 1` in the `board.h`.
The second commit should restore behavior (but with calibrated DCO than hard coded magic numbers).
`make BOARD=z1 -C examples/default flash term`
should work again, but fail with `master`.
Regression …

boards/z1: fix broken clock configuration

---

examples/gcoap_block_server/Makefile.ci
sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/nanocoap.c

Currently we don't have a public way to iterate all options of the same type - `coap_iterate_option()` was intended to be public (it's not `static`) but was never declared in any header file.
This allows for the opportunity to clean up the API to make it more palatable for public consumption.  
The function is only used by `coap_opt_get_string()` for which we have unit tests that are still passing.

nanocoap: clean up coap_iterate_option(), make it public

---

boards/rpi-pico/dist/openocd.cfg

This PR fixes the use of openOCD to flash a rpi-pico board.
Currently on master, trying to flash this board with openOCD (v12) and a CMSIS-DAP probe fails.
with this PR, it now works as expected (even debugging)
Moreover, the configuration file used by RIOT is now deprecated on openOCD v12 so changes it while we're at it.
master:
```
Open On-Chip Debugger 0.12.0
swd
Warn : rp2040-core0.cfg configuration file is deprecated and will be
removed in the next release. Use following parameters instead:
-c 'set USE_CORE 0' -f target/rp2040.cfg
Warn : Transport "swd" was already selected
adapter speed: 4000 kHz
Info : Using CMSIS-DAPv2 interface with VID:PID=0x2e8a:0x000c, serial=E46170D59B552B2C
Info : …
```

boards/rpi-pico: update openocd.cfg file

---

sys/include/net/gcoap.h
sys/include/net/gcoap/forward_proxy.h
sys/include/net/nanocoap.h
sys/include/net/nanocoap/cache.h
sys/include/net/nanocoap_sock.h
sys/net/application_layer/gcoap/Kconfig
sys/net/application_layer/nanocoap/Kconfig
sys/net/application_layer/nanocoap/nanocoap.c
sys/net/application_layer/nanocoap/sock.c
sys/net/application_layer/nanocoap/vfs.c

Always stylize the name as nanoCoAP instead of Nanocoap. 
Same for Gcoap -> GCoAP

nanocoap, gcoap: homogenize name of the module

---

dist/tools/jlink/jlink.sh

Adopted from openocd script in order to prevent killing the gdb server upon SIGINT.
Thanks to @maribu for the pointer.
Prevent gdb server from being killed by SIGINT when using jlink for debugging.
Debug any arbitrary RIOT application on a board where jlink is supported as a programmer and `PROGRAMMER` is set to `jlink` by calling `make debug`. Hit Ctrl-C. The program debugging should get interrupted but can be continued via `continue`.

tools/jlink.sh: start gdb server with setsid

---

boards/adafruit-grand-central-m4-express/Kconfig
boards/adafruit-grand-central-m4-express/Makefile
boards/adafruit-grand-central-m4-express/Makefile.dep
boards/adafruit-grand-central-m4-express/Makefile.features
boards/adafruit-grand-central-m4-express/Makefile.include
boards/adafruit-grand-central-m4-express/board.c
boards/adafruit-grand-central-m4-express/doc.txt
boards/adafruit-grand-central-m4-express/include/arduino_board.h
boards/adafruit-grand-central-m4-express/include/arduino_pinmap.h
boards/adafruit-grand-central-m4-express/include/board.h
boards/adafruit-grand-central-m4-express/include/gpio_params.h
boards/adafruit-grand-central-m4-express/include/periph_conf.h

This PR provides the support for Adafruit Grand Central M4 Express board. The main features of the board are:
- ATSAMD51 Cortex M4 running at 120 MHz
- 1MB Flash
- 256 KB RAM
- external 8 MB QSPI Flash storage
- Micro SD Card slot connected to SPI

board: add Adafruit Grand Central M4 Express support

---

boards/qn9080dk/include/periph_conf.h

- Document which I2C/SPI/UART peripheral maps to which FLEXCONN IP block to easily detect potential overlap
- Switch conflict between SPI and I2C peripheral by using a different FLEXCONN for I2C
I2C should still work. In fact, https://github.com/RIOT-OS/RIOT/pull/19729 was tested with both https://github.com/RIOT-OS/RIOT/pull/19729 and this applied and the output was:
```
make BOARD=qn9080dk -C examples/default flash term
[...]
2023-06-12 21:08:02,168 # main(): This is RIOT! (Version: 2023.07-devel-610-g0e09b)
2023-06-12 21:08:02,170 # Welcome to RIOT!
> saul
2023-06-12 21:08:05,285 # saul
2023-06-12 21:08:05,287 # ID	Class		Name
2023-06-12 21:08:05,289 # #0	ACT_SWITCH	LED red
2023-06-12 21:08:05,291 # #1	ACT_SWITCH	LED green
2023-06-12 21:08:05,293 # #2	ACT_SWITCH	LED blue
2023-06-12 …
```

boards/qn9080dk: fix periph conflict

---

boards/qn9080dk/doc.txt

- update the doc on the internal programmer firmware:
- not only switching to J-Link, but also just updating it does improve reliability of flashing
- give hints in how to get the ~~shitty~~ wonderful update process working
- update notes on OpenOCD requirements
The CI will generate a doc preview that can be checked.
None

boards/qn9080dk: update doc on flashing

---

drivers/sx127x/sx127x_getset.c
drivers/sx127x/sx127x_internal.c
sys/include/net/lora.h

Convert the floating point arithmetic to integer arithmetic.
***Beware:*** I neither tested this nor did I try to understand the calculations.
- air time computation should yield roughly the same result
- frequency / channel computation should yield roughly the same result
https://github.com/RIOT-OS/RIOT/issues/19614

drivers/sx127x: reduce use of floats

---

cpu/qn908x/include/flexcomm.h
cpu/qn908x/periph/flexcomm.c
cpu/qn908x/periph/i2c.c

Allow the board config to specify use of external or external pull-up resistor on the SCL up. Default to the internal pull-up, two weak pull ups in parallel are preferable over no pull-up.
```
make BOARD=qn9080dk -C examples/default flash term
```
On `master`: No output at all, board hangs.
This PR:
```
2023-06-12 21:08:02,168 # main(): This is RIOT! (Version: 2023.07-devel-610-g0e09b)
2023-06-12 21:08:02,170 # Welcome to RIOT!
> saul
2023-06-12 21:08:05,285 # saul
2023-06-12 21:08:05,287 # ID	Class		Name
2023-06-12 21:08:05,289 # #0	ACT_SWITCH	LED red
2023-06-12 21:08:05,291 # #1	ACT_SWITCH	LED green
2023-06-12 21:08:05,293 # #2	ACT_SWITCH	LED blue
2023-06-12 21:08:05,295 # #3	SENSE_BTN	Button(SW1)
2023-06-12 21:08:05,297 # #4	SENSE_BTN	Button(SW2)
2023-06-12 21:08:05,299 # #5 …
```

cpu/qn908x/periph_i2c: allow internal pull-up on SCL

---

drivers/include/pcf857x.h

As the address is hardware-configurable, some modules are delivered with a different address. For example, the one I received has the address pins connected to Vcc, so its address is 0x3f instead of 0x38. With this modification, I can use CFLAGS += -DPCF8574A_BASE_ADDR=0x3f in the Makefile.

drivers/pcf857x: allow to define PCF857x_BASE_ADDR at compile time

---

cpu/nrf5x_common/periph/i2c_nrf52_nrf9160.c

The I2C peripheral's shortcuts are used with the read and write register to automatically stop the I2C transaction or to continue with the next stage.
With simple I2C read and write bytes these shorts are not used, but are also not cleared by the function in all cases, causing it to use the shortcut configuration set by a previous function call. This patch ensures that the shorts are always set by the read and write functions
Should be possible to spot with a logic analyzer and the I2C periph test. Maybe the HIL test can also detect it :)
None

nrf5x_common: Clear I2C periph shorts

---

sys/net/gnrc/routing/rpl/of0.c

Checking for overflow of integer addition by comparing against one of the arguments of the addition does not work when the result of the addition is automatically promoted to a larger type.
Fix by using an explicit cast to make sure that the result of the addition is not implicitly converted to a larger type.
` make -C examples/gnrc_networking`

gnrc/rpl: fix incorrect addition overflow check

---

drivers/dht/Kconfig
drivers/dht/Makefile.dep
drivers/dht/dht.c
drivers/dht/include/dht_params.h
drivers/include/dht.h
tests/drivers/dht/Makefile
tests/drivers/dht/app.config.test
tests/drivers/dht/main.c

In PR #19674, I also provided quick and dirty fixes to restore functionality on esp8266 and enable operation on AVR. While reviewing PR #18591, it became apparent to me that this driver needed a refresh, particularly its migration to ztimer.
The cause of the malfunction on esp8266 was that since the default switch to ztimer as the backend for xtimer, XTIMER_BACKOFF was no longer taken into account. Therefore, the correction I provided in PR #19674 simply made explicit what was previously done implicitly with xtimer and now needs to be done explicitly with ztimer (spinning instead of sleeping).
Moreover, it was unnecessarily complex to measure the pulse duration in a busy-wait implementation, which required 2 calls to ztimer_now() and  32-bit operations expensive on 8-bit architecture. …

drivers/dht: busy wait reimplementation

---

makefiles/cflags.inc.mk
sys/Makefile.include

Hello :penguin: 
This moves the definition of `CPU_RAM_BASE/SIZE` from being only available in certain situation to be always available.
Reason for change is to simplify common code in the cpu folder.
In cooperation with @benpicco 
Passing CI
First usage will be in the PMP driver. Although there is more code in RIOT that could be refactored to use these defines instead of hacks / hardcoded values.

buildsystem: Always expose CPU_RAM_BASE & SIZE flags

---

dist/tools/usb-serial/ttys.py

This fixes:
File "/home/maribu/Repos/software/RIOT/master/dist/tools/usb-serial/ttys.py", line 259, in <module>
print_ttys(sys.argv)
File "/home/maribu/Repos/software/RIOT/master/dist/tools/usb-serial/ttys.py", line 255, in print_ttys
print_results(args, ttys)
File "/home/maribu/Repos/software/RIOT/master/dist/tools/usb-serial/ttys.py", line 189, in print_results
if item.rfind(args.format_sep) >= 0:
^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'rfind'
Which occurs while testing whether a string requires special quoting if an attribute is None.
```
make term MOST_RECENT_PORT=1
```
with a TTL adapter that has no serial should no longer trigger above exception.
None

dist/tools/usb-serial: Fix handling of None while quoting

---

cpu/avr8_common/ldscripts/avr4.ld
cpu/avr8_common/startup.c

Splitted from:
- #19740
Tested on atmega8 with:
- #19755

cpu/avr8 common: added avr4.ld script

---

examples/gnrc_networking_mac/mac.c
examples/gnrc_networking_mac/udp.c
sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c
sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.c
sys/net/gnrc/network_layer/ipv6/nib/nib.c
sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c
sys/net/gnrc/transport_layer/tcp/gnrc_tcp_pkt.c
sys/shell/cmds/gnrc_icmpv6_echo.c
sys/shell/cmds/gnrc_udp.c

Check return values of following functions for null:
- gnrc_netif_iter
- gnrc_netif_hdr_build
``` bash
make -C examples/gnrc_networking_mac/
make -C examples/gnrc_networking
make -C examples/telnet_server/
```

all/gnrc: fix null pointer dereference

---

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c

GNRC_RPL_COUNTER_INCREMENT has no external side effects.
Fix by assigning function call result to a variable.
` make -C examples/gnrc_networking`

sys/net/rpl: fix missing assignment operator

---

cpu/esp32/Makefile.include
cpu/esp32/include/sdkconfig_esp32.h
cpu/esp32/ld/esp32/sections.ld.in
cpu/esp32/ld/esp32c3/sections.ld.in
cpu/esp32/ld/esp32s2/sections.ld.in
cpu/esp32/ld/esp32s3/sections.ld.in

This PR fixes the problem
```
/bin/sh: 1: arithmetic expression: expecting primary: ""
```
for ESP32x SoCs that was introduced with PR #19746. The reason for the error message was that `RAM_LEN` was not defined for ESP32x SoCs.
The solution is a bit tricky since ESP32x SoCs use a combination of SRAMs of different sizes and with different byte/word access requirements. Additionally, several hardware components such as the instruction cache or the Bluetooth controller share the RAM so that the start address and the size that is usable may differ depending on the hardware components used and configured parameters like the cache size a.s.o.
Therefore, the DRAM region parameters as defined in the memory layout of the linker scripts are used to define `RAM_START_ADDR` and `RAM_LEN` in …

cpu/esp32: define RAM_START_ADDR and RAM_LEN

---

makefiles/cflags.inc.mk

This gets rid of the following ugly warnings:
/bin/sh: 1: arithmetic expression: expecting primary: ""
With `master`:
```
$ make BOARD=native BUILD_IN_DOCKER=1 -j -C examples/hello-world     
make: Entering directory '/home/maribu/Repos/software/RIOT/master/examples/hello-world'
Launching build container using image "docker.io/riot/riotbuild:latest".
podman run --rm --tty --userns keep-id -v '/etc/zoneinfo/Europe/Berlin:/etc/localtime:ro' -v '/home/maribu/Repos/software/RIOT/master:/data/riotbuild/riotbase:delegated' -v '/home/maribu/.cargo/registry:/data/riotbuild/.cargo/registry:delegated' -v '/home/maribu/.cargo/git:/data/riotbuild/.cargo/git:delegated' -e 'RIOTBASE=/data/riotbuild/riotbase' -e 'CCACHE_BASEDIR=/data/riotbuild/riotbase' -v …
```

buildsystem: only expose CPU_RAM_BASE & SIZE when known

---

boards/common/arduino-atmega/include/arduino_iomap.h
boards/common/arduino-due/include/arduino_iomap.h

The correct macro name is `ARDUINO_I2C_UNO` for Arduino UNO compatible I2C bus location, or `ARDUINO_I2C_NANO` for Arduino Nano compatible I2C bus location. Hence, rename it from `ARDUINI_I2C0` to the correct name.
Check the documentation at https://doc.riot-os.org/iomaps.html#iomaps-mapping-i2c and confirm:
The I2C bus macros should indeed be named `ARDUINO_I2C_UNO` (when compatible with shields targeting the Arduino UNO R3) or `ARDUINO_I2C_NANO` (when compatible with shields targeting the Arduino Nano).
Introduced by https://github.com/RIOT-OS/RIOT/pull/19759

boards: Fix I2C Arduino mapping

---

makefiles/pseudomodules.inc.mk
sys/arduino/Makefile.include

This allows using the arduino_pwm feature (which is translated into a module) without the arduino module; e.g. for only using the Arduino I/O mapping but not the Arduino API.
Compilation of an app using `arduino_pwm` with a board that provides this should still work.
--> The CI will do this for us.
Since https://github.com/RIOT-OS/RIOT/pull/19759 decoupled the Arduino I/O mapping from the Arduino API, it is now possible to take advantage of Arduino I/O PWM mapping not only from Arduino code, but also from RIOT code. However, without this, compilation will fail as the `arduino_pwm` module is automatically pulled in even without the `arduino` module used, but only considered a pseudo module when `arduino` is used.

sys/arduino: move pseudo modules to makefiles

---

core/lib/assert.c
core/lib/include/assert.h
tests/sys/sema_inv/Makefile.ci

This PR makes the use of `DEBUG_BREAKPOINT` on failed assertion optional.
The behavior of `assert` has been changed with PR #19368. Instead of printing some useful information, either a breakpoint is inserted and the execution of the MCU stops in debugger or a endless while loop is executed.
Before PR #19368 the user got on failed assertion:
```
Starting ESP32x with ID: 7cdfa1e36a34
ESP-IDF SDK Version v4.4.1-0-g1329b19fe49
...
*** halted.
```
This was very helpful during development, especially to identify quickly the cause of problems with `DEBUG_ASSERT_VERBOSE` enabled, e.g. when misconfiguration led to failed assertions.
With PR #19368 the user gets an address in best case (or even `0` on platforms like ESP32), in worst case the MCU seems to …

core/lib: make the use of DEBUG_BREAKPOINT on assert optional

---

Makefile.dep
core/lib/include/panic.h
cpu/fe310/Kconfig
cpu/fe310/Makefile.features
cpu/fe310/include/cpu_conf.h
cpu/riscv_common/include/pmp.h
cpu/riscv_common/include/vendor/riscv_csr.h
cpu/riscv_common/irq_arch.c
cpu/riscv_common/periph/Kconfig
cpu/riscv_common/periph/pmp.c
cpu/riscv_common/riscv_init.c
kconfigs/Kconfig.features
makefiles/pseudomodules.inc.mk
tests/cpu/pmp_noexec_ram/Makefile
tests/cpu/pmp_noexec_ram/README.md
tests/cpu/pmp_noexec_ram/main.c
tests/cpu/pmp_noexec_ram/tests/01-run.py

Hi! :elephant: 
this adds a basic RISC-V physical memory protection (PMP) driver to RIOT. Well, 'driver' might be a stretched, feels more like a little utility :)
EDIT: Also added  a no-execute RAM option for the hifive & a corresponding test
Since I only have an Hifive rev b, it's only enabled on this board / cpu. I also tested the code on an ESP32-C but the feature can't be enabled there, as `cpu/riscv_common/` is not used by the ESP32...
* Grab a hifive rev b
* go to `examples/hello-world`
* Add `USEMODULES += periph_pmp` to the `Makefile`
* Include `pmp.h` in `main.c`
* Add code e.g. `print_pmpcfg(0);`
* compile & flash & term 
You should see something like this:
```
```

cpu/riscv: Add PMP driver

---

Makefile.include

The MAP file does not provide all information necessary to do a full analize of generated code. This automatically generate the LST file with all relavant C and ASM code to help inspect code generated.
This was tested using AVR and Cortex-M toolchains.

Makefile.include: Generate lst file using objdump

---

cpu/atmega_common/periph/gpio.c

Vera++ doesn't like `#error` preprocessor directives without a quoted string afterwards (and also my syntax highlighter doesn't like this as well). So let's add the quotes to have the tools not spooked out.
Green CI and no vera++ annotations on the changed file.
The vera++ annotations cluttered the source view when reviewing https://github.com/RIOT-OS/RIOT/pull/19777, despite none of the annotations being relevant to the PR changes.

cpu/atmega_common: make vera++ happy

---

cpu/esp8266/ld/esp8266.riot-os.ld

This pull request addresses an issue where a region overflow occurs during the generation of the `.elf` file when the application path contains a directory named '*periph'. The problem arises due to an incorrect section mapping in the `esp8266.riot-os.ld` linker script.
The issue was causing the compilation of all tests which were moved to the `tests/periph` directory by PR #19552 to fail on the ESP8266 architecture.
To resolve the issue, the `esp8266.riot-os.ld` script has been modified. The section mapping for the `*periph` directory has been changed to `*esp_common_periph`, ensuring that the correct sections are included in the final binary.
To verify the effectiveness of this fix, the following testing procedure was performed:
1. Checked out the `master` branch of the RIOT repository …

cpu/esp8266: fix region overflow with '*periph' directory in app path

---

boards/seeedstudio-gd32/doc.txt
boards/sipeed-longan-nano/doc.txt

With the support of the USB OTG interface, both the flash method and the stdio interface module used were changed for the GD32V boards. However, the documentation was not updated. With this PR, the documentation is updated accordingly.
Green CI

boards: fix documentation for GD32V boards

---

tests/core/Makefile.sys_common

This remove Makefile.sys_common from tests/core directory which was likely a copy past mistake from the PR that moved the core related tests.
Untested
#19565 #19566

tests/core: remove Makefile.sys_common copy past mistake

---

boards/sipeed-longan-nano/Kconfig
boards/sipeed-longan-nano/Makefile.dep
boards/sipeed-longan-nano/doc.txt
boards/sipeed-longan-nano/include/board.h
boards/sipeed-longan-nano/include/periph_conf.h

This PR fixes the configuration of the TFT Display of Sipeed Longan Nano boards and improves the documentation regarding the use of the TFT Display.
```
CFLAGS='-DCONFIG_SIPEED_LONGAN_NANO_WITH_TFT=1' BOARD=sipeed-longan-nano make -C tests/drivers/st7735/ flash
```
should work with this PR.

boards/sipeed-longan-nano: fix TFT display config and documentation

---

boards/nrf9160dk/include/periph_conf.h

`nRF9160` has 6 CC per timer.
You can `grep -ra "CC_NUM" cpu/nrf9160 ` to check it.
So let's use all available CC.
You can run `tests/periph/timer` to see the new CC.
None.

boards/nrf9160dk: use all available CC timer channels

---

cpu/nrf5x_common/periph/timer.c

Properly reset all CC channels of a given timer at initialization (except the last one which seems to be used for capture only in the driver).
The issue with the previous code was that some CCs were not clear on some nRF52 MCUs.
For instance, nRF52840 has 4 CCs for its two first timers, then 6 CCs for all others.
nRF9160 and nRF5340 also have 6 CCs for all its timer peripherals.
Thus, loop through the reported number of channels and clear the associated register instead of hardcoding the first 3 CC channels.
CI should be enough I think.
None.

cpu/nrf5x_common: reset all available CC channels

---

cpu/nrf52/cpu.c
cpu/nrf9160/cpu.c

This PR removes duplicate calls of `SCB_SCR_SEVONPEND` bit in nRF52 and nRF9160.
This call is already done [here](https://github.com/RIOT-OS/RIOT/blob/7c320055a1d83f8fc2a9e16562a72c700bb3e01c/cpu/cortexm_common/cortexm_init.c#L60) 
Flash a nRF52 or nRF9160-based board and check that the board is still alive.
None. I notice this duplicate call when porting nRF53.

cpu/nrf{52,9160}: remove duplicate sevonpend bit

---

boards/frdm-k22f/include/periph_conf.h

Extracted from #16727 because unrelated.

boards/frdm-k22f: fixes long lines in periph_conf.h

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

Between `netif down` and `netif up` events, the counter for router solicitations must also be reset for non-6LN interfaces.
If it is not done, router solicitations will be retransmitted the first time but at some point not anymore because [this](https://github.com/RIOT-OS/RIOT/blob/4deca3dfd7cf813f74ba81feb5befbcdfdecffce/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L1487-L1492)
check fails.
Testing with `atwinc15x0`, this should be reproduceable when exiting early on `_handle_rtr_adv` to pretend that no RA was received. And shutting the interface down with `ifconfig x set state sleep` and bringing it back up again with `ifconfig x set state idle`. You would see that only one RS goes out after the interface has been sent to sleep and brought up again.

gnrc/ipv6/nib: reset rs_sent counter also for not-6LN interfaces

---

makefiles/arch/msp430.inc.mk

My msp430 toolchain (https://www.ti.com/tool/MSP430-GCC-OPENSOURCE) was broken by #19484:
```
hugues@p700:~/github/cpu_msp430_common/RIOT$ BOARD=msb-430 make -j64 -C examples/hello-world
make : on entre dans le répertoire « /home/hugues/github/cpu_msp430_common/RIOT/examples/hello-world »
Building application "hello-world" for "msb-430" with MCU "msp430fxyz".
"make" -C /home/hugues/github/cpu_msp430_common/RIOT/boards/common/init
"make" -C /home/hugues/github/cpu_msp430_common/RIOT/boards/msb-430
"make" -C /home/hugues/github/cpu_msp430_common/RIOT/core
"make" -C /home/hugues/github/cpu_msp430_common/RIOT/core/lib
"make" -C /home/hugues/github/cpu_msp430_common/RIOT/cpu/msp430fxyz
"make" -C /home/hugues/github/cpu_msp430_common/RIOT/drivers
"make" -C …
```

cpu/msp430: fix for ti's msp430-gcc-opensource package ld version

---

cpu/atmega_common/atmega_cpu.c
cpu/atmega_common/include/atmega_regs_common.h
cpu/atmega_common/include/cpu_clock.h
cpu/atmega_common/include/periph_cpu_common.h
cpu/atmega_common/periph/adc.c
cpu/atmega_common/periph/gpio.c
cpu/atmega_common/periph/i2c.c
cpu/atmega_common/periph/pwm.c
cpu/atmega_common/periph/spi.c
cpu/atmega_common/periph/timer.c
cpu/atmega_common/periph/uart.c

Splitted from:
- #19740
Tested on atmega8 with:
- #19755
This one probably need to be tested on others cpu.
```
tests/periph/adc$ BOARD=atmega1284p make -j64 clean all | grep '^  ' && BOARD=atmega1284p AVRDUDE_PROGRAMMER='usbasp -F' make flash 2>&1 | grep -- 'of flash' && BOARD=atmega1284p PORT=/dev/ttyACM0 make term
10712	    304	   1021	  12037	   2f05	/home/hugues/github/cpu_atmega_common/RIOT/tests/periph/adc/bin/atmega1284p/tests_adc.elf
avrdude: 11016 bytes of flash written
avrdude: 11016 bytes of flash verified
/home/hugues/github/cpu_atmega_common/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "9600"  
2023-06-22 18:44:54,846 # Connect to serial …
```

cpu/atmega_common: checking features instead of CPU models

---

Makefile.include

This PR reverts a part of PR #19745. It removes the `$(LSTFILE)` from the `BUILD_FILES` variable so that the `.lst` file isn't generated implicitly. If the `.lst` file is needed, it can be generated with `lstfile` target.
**Background**
The compilation time increased a lot with PR #19745. The reason is that the generation of the `.lst` file seems to be time-consuming. For example, on an Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz` with 8 cores and a SSD, it takes about 15 seconds for a complex application such as `tests/sys/usbus_msc` for a STM32F7 MCU.
Therefore, the compilation time for
```
BOARD=stm32f723e-disco make -j8 -C tests/sys/usbus_msc
```
increased from about 1 sec to about 16 seconds (all source files were already compiled).
Even for a small application
``` …
```

Makefile.include: don't use target lstfile implicitly

---

boards/doc.txt

This adds a board selection guide to the documentation to aid new users picking good hardware for their use case.
Check the generated documentation.
fixes https://github.com/RIOT-OS/RIOT/issues/18021

doc: add board selection guide

---

core/msg.c

Check return values of following functions for null:
- thread_get
- thread_get_unchecked

core: fix null pointer dereference

---

cpu/nrf53/Kconfig
cpu/nrf5x_common/Makefile.features
cpu/nrf5x_common/periph/wdt.c
cpu/nrf9160/Kconfig

This PR enables support for the watchdog driver on nRF53.
This MCU has two watchdog peripherals, for now, it only uses the first one.
The use of the second watchdog can be add in a followup PR later.
Flash and play with `tests/periph/wdt` application.
None.

cpu/nrf5x/periph/wdt: enable support for nRF53/nRF9160

---

boards/b-u585i-iot02a/Kconfig
boards/b-u585i-iot02a/Makefile.features
boards/b-u585i-iot02a/include/periph_conf.h
boards/common/stm32/include/cfg_usb_otg_fs_u5.h
cpu/stm32/Makefile.include
cpu/stm32/stmclk/stmclk_u5.c
drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
pkg/tinyusb/hw/hw_stm32_otg.c

This PR adds the USB OTG support for STM32U5 and the `b_u585i_iot02a` board.
This PR includes PR #19795 since it uses directly the changes made in PR #19795.
Compile and flash
```
BOARD=b-u585i-iot02a make -C tests/sys/usbus_cdc_ecm/ flash term
```
Use the `sudo dmesg` command to get the kernel messages.
```pyhon
[766948.556645] usb 1-2.2: new full-speed USB device number 108 using xhci_hcd
[766948.658688] usb 1-2.2: New USB device found, idVendor=1209, idProduct=7d00, bcdDevice= 1.00
[766948.658696] usb 1-2.2: New USB device strings: Mfr=3, Product=2, SerialNumber=4
[766948.658699] usb 1-2.2: Product: b-u585i-iot02a
[766948.658702] usb 1-2.2: Manufacturer: RIOT-os.org
[766948.658704] usb 1-2.2: SerialNumber: AA140057DA41D467
[766948.668681] cdc_ether 1-2.2:1.0 usb0: register 'cdc_ether' …
```

boards/b_u585i_ iot02a/periph usbdev

---

boards/common/e104-bt50xxa-tb/include/periph_conf.h
boards/common/nrf51/include/cfg_clock_16_0.h
boards/common/nrf51/include/cfg_clock_16_1.h
boards/common/nrf52/include/cfg_clock_32_0.h
boards/common/nrf52/include/cfg_clock_32_1.h
boards/nrf5340dk-app/include/board.h
boards/nrf9160dk/include/board.h
cpu/nrf51/cpu.c
cpu/nrf52/cpu.c
cpu/nrf53/cpu.c
cpu/nrf5x_common/clock.c
cpu/nrf9160/cpu.c

This PR changes the source selection of LFCLK for all nRF families.
This idea is to use the values provided by Nordic vendor files to properly populate the source of the LFCLK. Then setup a per CPU check to ensure the value provided at board level is fine. In the end, the LFCLK source selection is a mere assignment.
The selection of the LFCLK source is still done at board level. I also add a bit of documentation to help users to select another value if needed.
I'll provide in a followup PR, `periph_rtt` support for both nRF9160 and nRF53.
CI should be enough I think. Otherwise, one can ran tests/periph/rtt on any nRF51-based board and any nRF52-based board.
You can also change the LFCLK source at board level to ensure the guards are doing their jobs.
None.

cpu/nrf5x_common: rework LFCLK source selection

---

makefiles/arch/riscv.inc.mk

- Use a sane (a.k.a. simply expanded) variable for the `$(TARGET_ARCH)` instead of an insane (a.k.a. recursive expended) variable - The toolchain detection will now happen only once, rather than each and every time `$(TARGET_ARCH)` is referenced
- Use a single call to `which` rather than one per possible target triple
Fixes https://github.com/RIOT-OS/RIOT/issues/19788
```
unset TARGET_ARCH
unset TARGET_ARCH_RISCV
make BOARD=hifive1b -C examples/default clean
```
should no be faster than in `master`
Fixes https://github.com/RIOT-OS/RIOT/issues/19788

makefiles/arch/riscv.inc.mk: speed up toolchain detection

---

sys/include/usb/usbus.h
sys/usb/usbus/usbus_control.c

While working on the `qmk_firmware` integration, a slight behavioural difference was noted in Windows 10/11 hosts.
Stalling on `SET_FEATURE`/`CLEAR_FEATURE` can make upstream hubs disable ports. This in turn stops the device from instantiating a remote wakeup (currently implemented with some MCU specific logic).
According to the USB 2.0 spec, remote wakeup should be disabled by default, and should only be enabled if the host explicitly requests it. Handling `USB_FEATURE_DEVICE_REMOTE_WAKEUP` and storing its status allows devices to also be more compliant in its wakeup process. 
Right now its been tested via wireshark and a heavily modified qmk_firmware branch.
Please do let me know if theres existing test cases to update.
Hardware tested was a ATSAMD51J18A MCU and USB2422 Hub, as well as …

usbus: Implement USB_FEATURE_DEVICE_REMOTE_WAKEUP handling

---

boards/nrf5340dk-app/Kconfig
boards/nrf5340dk-app/Makefile.features
boards/nrf5340dk-app/include/periph_conf.h
boards/nrf9160dk/Kconfig
boards/nrf9160dk/Makefile.features
boards/nrf9160dk/include/periph_conf.h
cpu/nrf53/cpu.c
cpu/nrf5x_common/periph/rtt.c

This PR enables support for `periph_rtt` on both nRF9160 and nRF53.
This PR is based on #19803 
I was only able to test on nrf5340dk-app as I don't have access to any nrf9160-based board.
Here is `test/periph/rtt` output for reference on `nrf5340dk-app`:
flash `tests/periph/rtt` on `nrf9160dk` or `nrf5340dk-app`  and check the results.
```
s
2023-07-06 16:11:16,471 # START
2023-07-06 16:11:16,479 # main(): This is RIOT! (Version: 2023.07-devel-765-g02c65-cpu/nrf53/add_rtt_support)
2023-07-06 16:11:16,480 # 
2023-07-06 16:11:16,482 # RIOT RTT low-level driver test
2023-07-06 16:11:16,483 # RTT configuration:
2023-07-06 16:11:16,485 # RTT_MAX_VALUE: 0x00ffffff
2023-07-06 16:11:16,487 # RTT_FREQUENCY: 1024
2023-07-06 16:11:16,487 # 
2023-07-06 16:11:16,494 # Testing the tick conversion (with …
```

cpu/nrf{53,9160}: add periph_rtt support

---

sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/nanocoap.c
tests/unittests/tests-nanocoap/Makefile.include
tests/unittests/tests-nanocoap/tests-nanocoap.c

[RFC8974](https://datatracker.ietf.org/doc/html/rfc8974) allows for token length of up to 65804 Byte in order to store Client state in the token.
This is easy to implement in nanoCoAP, so let's give it a try.
Currently no use case is associated with this, but I extended the unit test.
Maybe we should only enable this when a pseudo-module `nanocoap_token_ext` is used.

nanocoap: implement extended tokens (RFC 8974)

---

boards/esp32s3-box/Kconfig
boards/esp32s3-box/Makefile
boards/esp32s3-box/Makefile.dep
boards/esp32s3-box/Makefile.features
boards/esp32s3-box/Makefile.include
boards/esp32s3-box/board.c
boards/esp32s3-box/doc.txt
boards/esp32s3-box/include/board.h
boards/esp32s3-box/include/gpio_params.h
boards/esp32s3-box/include/periph_conf.h
cpu/esp32/Kconfig.esp32s3

This PR provides the support for the [ESP32-S3-Box](https://github.com/espressif/esp-box).
The board has been tested with all basic tests for supported hardware including `tests/drivers/ili9341`:

boards: add ESP32-S3-Box support

---

boards/esp32s3-box/Makefile.dep
boards/sipeed-longan-nano/Kconfig
drivers/st7735/Kconfig

This adds three commits each addressing a deviation between dependency resolutions done with and without Kconfig. Hopefully, these in combination should fix the nightly builds.
For each `$failing_board` and `$failing_app` pair in the latest nightly build, do:
```
make BOARD=$failing_board -C $failing_app TEST_KCONFIG=0 info-modules > ~/without-kconfig
make BOARD=$failing_board -C $failing_app TEST_KCONFIG=1 info-modules > ~/with-kconfig
diff -rupN ~/without-kconfig ~/with-kconfig
```
should yield an empty diff other than the `=== [ATTENTION] Testing Kconfig dependency modelling ===`.
None

buildsystem: fix kconfig mismatches

---

boards/common/arduino-atmega/include/board_common.h
boards/common/arduino-due/include/board.h
drivers/Makefile.dep
drivers/doc.txt
drivers/w5100/include/w5100_params.h
makefiles/pseudomodules.inc.mk

This module provides no more than the correct configuration parameters for the `w5100` driver using the Arduino I/O mapping features. But by doing so, it will work out of the box with every mechanically and electrically compatible board for which the Arduino I/O mapping features are implemented.
```
USEMODULE=shield_w5100 make BOARD=arduino-due -C examples/gnrc_networking flash term
```
Should just work. And it should also work e.g. for the Arduino MEGA2560 or the Arduino Zero. By adding Arduino I/O mapping features to the nRF52840DK, this should also work there.
Depends on https://github.com/RIOT-OS/RIOT/pull/19759

drivers/shield_w5100: add module for the W5100 Ethernet Shield

---

cpu/atmega_common/atmega_cpu.c
cpu/atmega_common/periph/gpio.c
cpu/atmega_common/periph/gpio_ll_irq.c
cpu/atmega_common/periph/rtc.c
cpu/atmega_common/periph/rtt.c
cpu/atmega_common/periph/timer.c
cpu/atmega_common/periph/uart.c
cpu/atxmega/atxmega_cpu.c
cpu/atxmega/periph/gpio.c
cpu/atxmega/periph/i2c.c
cpu/atxmega/periph/timer.c
cpu/atxmega/periph/uart.c
cpu/avr8_common/avr8_cpu.c
cpu/avr8_common/include/cpu.h
cpu/avr8_common/include/irq_arch.h
cpu/avr8_common/include/states_internal.h
cpu/avr8_common/thread_arch.c
drivers/at86rf2xx/at86rf2xx_netdev.c

This prepares for rework how ISR is handled for AVR-8 platform. It is not expected changes on the behavior but tests on other boards were welcome to avoid regressions.
* Split UART state from ISR states. Now it is necessary two variables and GPIORx registers are automatically selected when available.
* UART states now supports up to 8 UARTs.
* Added AVR8_ISR macro do clean-up and hide internals related to ISR processing. This allows changes on ISR without any other changes on drivers.
Tests were conducted using atmega328p-xplained-mini and atxmega-a1u-xpro and the zigduino board was only built. The example thread_duel was used to test regressions.

cpu/avr8_common: Prepare for rework ISR

---

drivers/ili9341/ili9341.c
drivers/include/lcd.h
drivers/include/st7735.h
drivers/lcd/lcd.c
drivers/st7735/Kconfig
drivers/st7735/st7735.c

In preparation for the parallel interface support the following changes were made:
1. The code for basic communication (acquire/release SPI device, SPI transfers), which were always duplicated by copy & paste in each display driver again and again, has been moved to the LCD driver as low-level functions that are now used by the display drivers. These low level function allow 
- code deduplication and
- to define a more abstract communication interface that can then be extended later by parallel communication interface
2. Identical GPIO initializations has also been moved from display drivers to the LCD driver.
3. Using a default implementation of `lcd_set_area` function allows further code deduplication.
Finally, the `ili9341` and `st7735` drivers only implement the inialization sequence …

drivers/lcd: code deduplication for st7735 and ili9341

---

sys/ztimer/periodic.c

If `ztimer_periodic_init()` is called on a periodic timer that is already running, the init function will completely overwrite the `ztimer_t` structure that then is already part of a linked list.
This causes corruption of the clock's timer list and leads to *interesting* results (e.g. if the timer was the first element in the list, it will now be added again causing `->next` to point to itself which creates a circular list and an infinite loop when iterating the clock's timers.)

ztimer/periodic: remove timer on init if already running

---

boards/sipeed-longan-nano/Kconfig
boards/sipeed-longan-nano/Makefile.include

This PR reverts commit 69fb00bdfa13c5e83409fd6b5bd5068cf00fc08b to fix CI compilation.
Green CI with full build.

boards/sipeed-longan-nano: revert default to variant with TFT

---

dist/tools/usb-serial/find-tty.sh
dist/tools/usb-serial/list-ttys.sh

This PR provides a fix for #19805
When calling `SERIAL=xxx make flash` the command failed because the script `dist/tools/usb-serial/find-ttys.sh` tries to call `ttys.py` but it doesn't find it. So pass the full path to `ttys.py` to get rid of the problem.
Connect at least two boards to your computer
run `make list-ttys ` to get the ID of your boards
Try to flash one of them with (replace SERIAL with the one you get with the previous command):
`BOARD=xxx SERIAL=xxx make -C tests/leds flash`
It fails on master.
It should works with this PR.
Fixes #19805

dist/tools/usb-serial: call ttys.py with its path [backport 2023.07]

---

cpu/atmega_common/atmega_cpu.c

When we get a low battery event, post it on the power bus.
Not sure yet how to test this

cpu/atmega_common: hook up BAT LOW irq to power bus

---

pkg/heatshrink/patches/0003-allow-to-overwrite-config-defines.patch

The pkg already provides a `heatshrink_config.h` but it should be possible to tweak those values depending on what the application needs.
Add a way to overwrite them via `CFLAGS`.

pkg/heatshrink: allow to overwrite config defines

---

makefiles/pseudomodules.inc.mk
sys/include/net/sock.h
sys/include/net/sock/udp.h
sys/net/gnrc/sock/udp/gnrc_sock_udp.c
tests/net/gnrc_sock_udp/Makefile
tests/net/gnrc_sock_udp/main.c

This adds the option to read out the TTL of a received UDP packet.
@fabian18 this might come in handy if we don't want to hard-code topology information to restart nodes from the outside inward.
`tests/net/gnrc_sock_udp` has been extended to test the new option.

sys/net/sock: add sock_aux_ttl

---

pkg/arduino_adafruit_sensor/Makefile.dep

This fixes the dependencies of the `arduino_adafruit_sensor` package, which previously relied on the `arduino` feature. This feature no longer exists, as it was split into more fine granular features. However, the module should never have used that feature directly in the first place, but rather just use the arduino module. This in turn depends on the correct features.
`tests/arduino_adafruit_sensor` should again be supported by boards that have the features required by the `arduino` module.
Fallout of https://github.com/RIOT-OS/RIOT/pull/19759

pkg/arduino_adafruit_sensor: fix dependencies

---

pkg/arduino_adafruit_sensor/Makefile.dep

This fixes the dependencies of the `arduino_adafruit_sensor` package, which previously relied on the `arduino` feature. This feature no longer exists, as it was split into more fine granular features. However, the module should never have used that feature directly in the first place, but rather just use the arduino module. This in turn depends on the correct features.
`tests/arduino_adafruit_sensor` should again be supported by boards that have the features required by the `arduino` module.
Fallout of https://github.com/RIOT-OS/RIOT/pull/19759

pkg/arduino_adafruit_sensor: fix dependencies [backport 2023.07]

---

tests/drivers/disp_dev/main.c

This PR fixes a bug that was introduced in #17921. Especially this change:
```diff
- disp_dev_map(
-    disp_dev->dev,
-    ((max_width - RIOT_LOGO_WIDTH) >> 1), ((max_width + RIOT_LOGO_WIDTH) >> 1) - 1,
-    ((max_height - RIOT_LOGO_HEIGHT) >> 1), ((max_height + RIOT_LOGO_HEIGHT) >> 1) - 1,
-    (const uint16_t *)picture
-);
+ area.x1 = ((max_width - RIOT_LOGO_WIDTH) >> 1);
+ area.x2 = ((max_width + RIOT_LOGO_WIDTH) >> 1);
+ area.y1 = ((max_height - RIOT_LOGO_HEIGHT) >> 1);
+ area.y2 = ((max_height + RIOT_LOGO_HEIGHT) >> 1);
+ disp_dev_map(disp_dev->dev, &area, (const uint16_t *)picture);
```
a `-1` was removed from the x2 and y2 coordinates which leads to a bad display of the RIOT logo (it looks shifted).
On the adafruit-clue I can reproduce the bug (and also on stm32f429i-disc1). This …

tests/drivers/disp_dev: fix off by one in display area

---

dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
dist/tools/compile_and_test_for_board/tests/test_compile_and_test_for_board.py

Since we have a no-test flag that prevents executing tests, I think a no-compile flag is a nice compliment. Why? Well if I want to use this script for running multiple boards at the same time, RIOT is not so great handling parallel compile steps with conflicts on lockfiles happening, mostly due to packages. With this I can compile a list of boards sequentially, then flash and run tests in parallel, skipping the compile step.
Run the following once to compile and clean:
```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . native --applications tests/sys/shell --clean-after
```
Then try to run without the compile step and it should fail due to lack of the binary
```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . native --applications …
```

compile_and_test_for_boards: Add no-compile flag

---

sys/ztimer/periodic.c

#19806 added some retinit handling for ztimer periodic removing the timer from the new clock 
This tries to detect if this is a reinit and remove the timer from the old clock
this also removes the ztimer_acquire/_release handling by removing now calls in favour of set return value and now values  that are allready in ztimer,
that also has the potential to reduce the jitter of the periodic calls and bus-usage (for cpus that take their time to get "now") 
read
run tests/sys/ztimer_periodic
Fixes #19806

ztimer/periodic: reinit remove from right clock and handle aquired ztimer

---

boards/adafruit-itsybitsy-nrf52/doc.txt
boards/adafruit-itsybitsy-nrf52/include/board.h

This adds the configuration for the on-board DotStar/APA102 LED for the adafruit-itsybitsy-nrf52. I based the change on the board definitions for the adafruit-itsybitsy-m4, which also has a DotStar.
I also fixed a small error in the doc. The other LED is red, not blue. See [here](https://www.adafruit.com/product/4481) (I can also verify by looking at the board in person):
> Red LED for general purpose blinking, mini DotStar RGB LED for colorful feedback
I tested this on the board using the program in `tests/drivers/apa102` and all looks correct to me.
N/A

boards/adafruit-itsybitsy-nrf52: Add configuration for DotStar LED

---

cpu/stm32/ldscripts/stm32.ld

This PR fixes the LD script for STM32.
Since the CCM and SRAM4 length are defined as symbols with perifx `_`, the LD script didn't use them correctly. Instead of using `ccmram_length` and `sram4_length`, `_ccmram_length` and `_sram4_length` have to be used. Furthermore, the location counter for the SRAM has to be set to the beginning of SRAM4 to work.
BTW, I don't understand why the `ccmram` region is defined. There is no section definition that would use it to place code or data with attribute `.ccmram.*` there.
Without the fix in this PR, defined symbols in `tests/sys/malloc` for the `b-u585i-iot02a` board were:
```python
00000000 T _sheap2     <== wrong start position because of wrong location counter
28000000 T _eheap2     <== wrong end position because of `sram4_length` is 0.
``` …

cpu/stm32: fix ld script for SRAM4

---

drivers/enc28j60/enc28j60.c

This PR disables flow control in the ENC28J60 driver init function.
Setting FCEN1 in the EFLOCON register causes the ENC28J60 to periodically send pause frames. It should only be set when the receiver is running out of buffer space [1].
(Also, the FULDPXS bit in EFLOCON is read-only.)
[1] https://ww1.microchip.com/downloads/en/devicedoc/39662c.pdf
Launch Wireshark / tshark on an interface connected to an ENC28J60 controlled by RIOT. Without this PR you should see a pause frame being sent about every 100 ms (~10x per second):
1 0.000000000 b2:db:01:ec:f7:be → MAC-specific-ctrl-proto-01 MAC CTRL 60 Pause: pause_time: 4096 quanta
2 0.104906555 b2:db:01:ec:f7:be → MAC-specific-ctrl-proto-01 MAC CTRL 60 Pause: pause_time: 4096 quanta
3 0.209834541 b2:db:01:ec:f7:be → MAC-specific-ctrl-proto-01 …

drivers/enc28j60: disable flow control

---

tests/pkg/cayenne-lpp/main.c
tests/pkg/lora-serialization/main.c

As promised (with a delay for vacation), here is the nightlies fix.  It is very easy...
I guess previously native had different handling of floating points (similar to cross-compiled gcc) when using clang.  thanks to @maribu great work on fixing the llvm toolchain issues, that seems to not be an issue anymore (though I don't know the commit that fixed it).
Thus we remove clang conditions and enjoy a green CI.
It seems like this wasn't tested or doesn't get tested in the normal murdock/bors procedure (still don't know why) but can be easily verified with a/b testing (master vs this PR)
```
TOOLCHAIN=llvm make all test -C tests/pkg/cayenne-lpp/
```
and
```
TOOLCHAIN=llvm make all test -C tests/pkg/lora-serialization/
```
I also tested with cross compiling on  the samr21 and they all work... …

clang floating point handling fix

---

cpu/esp_common/esp-wifi/esp_wifi_netdev.c

The `assert()` in `_esp_wifi_get` is excessive and wrong for `NETOPT_IS_WIRED` where `val == NULL` is valid.
Running applications that query the `NETOPT_IS_WIRED` option (e.g. `gnrc_ipv6_static_addr`) should now work without triggering the assertion.
https://forum.riot-os.org/t/border-router-ota-using-wifi/3895/24

cpu/esp_common: esp-wifi: drop assert(val)

---

tests/net/gcoap_fileserver/tests/01-run.py

This test has been failing inconsistently in the nightlies and sometimes on unrelated PRs. I was able to reproduce it with murdock and as soon as I added some print statements to the test it went away.  Since the issue is something to do with a failure when comparing 2 files after a node sends a file I am guessing that the comparison comes occasionally too fast and the file is not ready.
Maybe there is some more synchronization needed after a `ncput` but for now just adding a small sleep should prevent this issue.
Run murdock multiple times or try to get it failing on a local setup then apply the PR...

tests/net/gcoap_fileserver: Fix failing nightlies

---

sys/net/gnrc/network_layer/ipv6/static_addr/gnrc_ipv6_static_addr.c

Both `CONFIG_GNRC_IPV6_STATIC_ADDR_UPSTREAM` and `CONFIG_GNRC_IPV6_STATIC_ADDR_DOWNSTREAM` get set to 0 if they are not defined, so we don't need the `IS_ACTIVE()` - in fact, using `IS_ACTIVE()` leads to wrong results here.
Build an application with
```
CFLAGS += -DCONFIG_GNRC_IPV6_STATIC_ADDR_UPSTREAM=8       # netif-esp-wifi
CFLAGS += -DCONFIG_GNRC_IPV6_STATIC_ADDR_DOWNSTREAM=9     # slipdev
```
Turns out the `IS_ACTIVE(DCONFIG_GNRC_IPV6_STATIC_ADDR_UPSTREAM)` would evaluate to `false`.
https://forum.riot-os.org/t/border-router-ota-using-wifi/3895/24

gnrc_static: fix static PID assignment

---

cpu/riscv_common/Kconfig
cpu/riscv_common/Makefile.features

`picolibc` is now supported by the RISC-V toolchain in `riotdocker`. It is not necessary to blacklist it in CI any longer.
Reference: `picolib` was blacklisted by commit 45270dada0af1269f8499f04e4f82329230e6944 in PR #15011.
1. Green CI
2. Check feature list for CI compilation:
```
BUILD_IN_DOCKER=1 RIOT_CI_BUILD=1 FEATURES_OPTIONAL=picolibc \
BOARD=sipeed-longan-nano make -j8 -C tests/sys/shell info-modules | grep picolib
picolibc
picolibc_stdout_buffered
picolibc_syscalls_default
```

cpu/riscv_common: remove picolibc from blacklisting in CI

---

tests/net/gcoap_fileserver/Makefile
tests/net/gcoap_fileserver/tests/01-run.py
tests/net/gnrc_rpl/Makefile
tests/net/gnrc_sixlowpan_frag_sfr_congure_impl/Makefile

The test needs `zep_dispatch` to run.
Without it the nodes can't communicate.
CI should no longer fail because test is started while `TERMDEPS` are still being built.

tests/gcoap_fileserver: add zep_dispatcher to TEST_DEPS

---

tests/pkg/lvgl/Makefile
tests/pkg/lvgl_touch/Makefile

ESPx SoC need more stack size for the main thread to avoid stack overflows.
Use any ESP32 board or any ESP32-S2 board and flash `tests/pkg/lvgl` for the `esp32-wrover-kit` respective the `esp32s2-lilygo-ttgo-t8`, for example:
```
BOARD=esp32-wrover-kit make -j8 -C tests/pkg/lvgl flash
```
Without this PR the application crashes
```
main(): This is RIOT! (Version: 2023.10-devel-106-gd512f-tests/pkg/lvgl_fix_main_stack_size)
EXCEPTION!! exccause=29 (StoreProhibitedCause) @4008274a excvaddr=fefffffb
heap: 310368 (used 4176, free 306192) [bytes]
register set
pc      : 40082f74	ps      : 00050033	exccause: 0000001d	excvaddr: fefffffb
epc1    : 40082f74	
a0      : 4008274a	a1      : 3ffb1bd0	a2      : fefffff7	a3      : 00000000
a4      : 3ff000dc	a5      : 400826e0	a6      : 00000000	a7      : …
```

tests/pkg/lvgl*: fix the main thread stack size for ESPs

---

Makefile.include

`COMPILE_COMMANDS_PATH` currently defaults to `RIOTBASE` which may not be an parent path for external applications -> set to `APPDIR` in case
- current good will stay good 
test with riot examples and or testes `$make compile-commands` should create a `compile_command.json` in `<RIOT>`
- test with external app  Makefile including
`include $(RIOTBASE)/Makefile.include`
should create `compile_command.json` in `APPDIR`

make: COMPILE_COMMANDS_PATH adapt for external apps

---

.github/workflows/release-test.yml

Reporting the release tests to Matrix never really worked and currently it makes the release tests look like failing. So lets just remove this action.
This effectively reverts commits 98100704ab74 and 764f7f0bf4cf.
Release tests should still work... we can start a run, but since this just reverts the to commits that added this which are the two last changes in the log to tha workflow file, I am pretty confident that this does not break anything:
```console
$ git log upstream/master -- .github/workflows/release-test.yml
commit 98100704ab74a7163bb2a32c4d1d4c25a6ad588a
Author: Martine Lenders <m.lenders@fu-berlin.de>
Date:   Sat Jan 14 09:49:52 2023 +0100
release-tests: fix PASSED chat message
commit 764f7f0bf4cff93676f830e5bad441e534a20b1e
Author: Martine Lenders <m.lenders@fu-berlin.de> …
```

gh-actions: remove reporting release tests to Matrix

---

boards/sltb009a/doc.txt
boards/sltb009a/include/periph_conf.h

This PR completes and fixes the documentation which was still in the state as generated automatically by `efm2riot`.
The PR also includes a fix of the configuration of the second UART device that was find out while completing the documentation.
Green CI

boards/sltb009a: complete and fix documentation

---

sys/include/net/ipv4/addr.h

This patch fixes some typos in the doxygen doc.
Nothing to test. No change to code.
- None known

sys/net/ipv4/addr: fix typos

---

makefiles/tools/usb_board_reset.mk

While testing #19726 on adafruit-clue I noticed that the `test` target was broken because on this kind of board (with an integrated bootloader and stdio over usb) it expects the `term-delay` to be defined and without this PR it fails.
`make test` works on adafruit-clue and similar boards.
<details><summary>master:</summary>
```
$ BUILD_IN_DOCKER=1 RIOT_CI_BUILD=1 BOARD=adafruit-clue make -C tests/periph/cpuid/ flash test --no-print-directory 
Launching build container using image "docker.io/riot/riotbuild:latest".
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -v '/home/aabadie/.cargo/registry:/data/riotbuild/.cargo/registry:delegated' -v …
```

makefiles/usb_board_reset.mk: declare term-delay target with test target

---

pkg/tinyusb/contrib/tinyusb.c

The macro `AUTO_INIT_PRIO_MOD_TINYUSB` was being used, but not defined. This patch includes the header where `AUTO_INIT_PRIO_MOD_TINYUSB` is defined to fix the compiler error.
Run any build with `auto_init` and `stdio_tinyusb_cdc_acm` modules active and see that build fails without patch and succeeds with the patch.
- none known

pkg/tinyusb: add missing include

---

drivers/ft5x06/ft5x06.c
drivers/ft5x06/include/ft5x06_constants.h

This PR provides a fix of the vendor ID for FT6xx6 touch panel driver ICs and a fix of register addresses for FTxxxx.
According to the [Application Note for FT6x06 CTPM](https://cdn-shop.adafruit.com/datasheets/FT6x06_AN_public_ver0.1.3.pdf), the vendor ID of FT6x06 touch panel driver ICs is `0x11` instead of `0xcd`. Although there are no information found in the Web about the FT6x36, the FT6336U touch panel of a ESP32-S3 WT32 SC01 Plus is also working with `0x11` as vendor ID so that it seems that FT6x36 is also using `0x11` as vendor ID.
Figured out with a `stm32f723e-disco` board (revision D03). Without this PR, `tests/drivers/ft5x06` gives:
```
+------------Initializing------------+
[ft5x06] init: invalid vendor ID: '0x11' (expected: 0xcd)
[Error] Initialization failed
```
With this …

drivers/ft5x06: fix vendor ID for FT6xx6 and FTxxxx register addresses

---

boards/slwstk6220a/include/periph_conf.h
boards/stk3600/include/periph_conf.h
boards/stk3700/include/periph_conf.h
cpu/efm32/include/periph_cpu.h
cpu/efm32/periph/dac.c

The EFM32 MCU allows the reference voltage to be configured per DAC device, not per DAC channel. Also, the DAC reference voltage was defined in the configuration but not used anywhere.
At the moment we have only defined one board (`stwstk6220a`) that uses the DAC, so changing the configuration interface shouldn't be critical.
`tests/periph/dac` should still work for the `stwstk6220a`
```
BOARD=slwstk6220a make -j8 -C tests/periph/dac flash
```
I don't have a `stwstk6220a` board (EFM32 Series 0) so that I can't test it. I could only test it for the `sltb009a` board (EFM32 Series 1) with the change for VDAC in PR #19887.

cpu/efm32: fix DAC configuration

---

drivers/ft5x06/ft5x06.c
drivers/ft5x06/ft5x06_internal.c
drivers/ft5x06/ft5x06_touch_dev.c
drivers/include/ft5x06.h

There is no need to copy the configuration parameter set to the device descriptor. A const pointer to the configuration parameter set in ROM is sufficient. It saves 16 byte of RAM.
Includes PR #19860 for the moment to be compilable.
Use 
```
CFLAGS='-DNDEBUG' BOARD=stm32f723e-disco make -j8 -C tests/drivers/touch_dev/
```
with and w/o this PR and compare the sizes.
Without the PR the sizes are:
```
text	   data	    bss	    dec
14652	    136	   2704	  17492
```
With the PR the sizes are:
```
text	   data	    bss	    dec
14676	    136	   2688	  17500
```
~Depends on PR #19860~

drivers/ft5x06: use a pointer to config parameters instead of copying them

---

sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h
sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c

A border router should not send router advertisements on it's 6LoWPAN interfaces, but if it also has classic IPv6 downstream interfaces it should very much do so.

gnrc_ipv6_nib: fix for border router with non-6lo interfaces

---

tests/net/gcoap_fileserver/Makefile

We see a lot of failures on this on CI with LLVM.
Blacklist the LLVM build until someone manages to find out what the problem is.

tests/gcoap_fileserver: only enable test with GCC

---

boards/stm32f723e-disco/include/board.h
boards/stm32f746g-disco/include/board.h
dist/tools/doccheck/exclude_simple
drivers/ft5x06/ft5x06.c
drivers/ft5x06/include/ft5x06_params.h
drivers/include/ft5x06.h

This PR provides the parameter option to define how the X and Y coordinates have to be converted.
To get coordinates from the touch panel that correspond to the display coordinates, it is often necessary to convert the coordinates from the touch pannel by swapping and mirroring them. For the sake of simplicity, possible rotations are additionally defined.
The PR includes PRs #19860 and #19866 to be compilable.
`tests/pkg/lvgl_touch` should still work for the `stm32f746g-disco` board.
```
BOARD=stm32f746g-disco make -C tests/pkg/lvgl_touch
```
~Depends on PR #19860~
Depends on PR #19866

drivers/ft5x06: introduce conversion for X and Y coordinates

---

drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c

Found this was missing when trying to use `examples/sniffer` with the `nrf52840dk`. The solution was actually provided by @benpicco on the matrix channel.
Use the `examples/sniffer` following its README.
N/A.

netdev/ieee802154_submac: support setting promiscuous mode option

---

drivers/ft5x06/ft5x06.c
tests/drivers/ft5x06/Makefile
tests/drivers/ft5x06/README.md
tests/drivers/ft5x06/main.c

This PR fixes the `ft5x06` driver initialization if the callback function parameter `cb` is `NULL. This might be the case for example if the application uses the touch device in polling mode.
If the interrupt pin is initialized if the callback function parameter `cb` is `NULL`, the driver crashes the first time an interrupt is triggered. Therefore, the INT pin must be initialized only if also the callback function parameter `cb` is not `NULL`.
To be able to test the polling mode, this PR also includes a change of the `tests/drivers/ft5x06` application which introduces the environment variables `FT5X06_POLLING_MODE` `FT5X06_POLLING_PERIOD` and in the makefile.
1. Use any board with a FTXXXX touch device and test it in polling mode, for example:
```
FT5X06_POLLING_MODE=1 …
```

drivers/ft5x06: fix initialization if callback function parameter is NULL

---

tests/net/gcoap_fileserver/Makefile

Recently this test is failing pretty often.
As there are currently no resources to debug this, disable the test to keep CI running.
CI should no longer fail.
We should first try if #19870 is enough

tests/net/gcoap_fileserver: disable test on CI

---

drivers/mtd_spi_nor/mtd_spi_nor.c

If only `ztimer_msec` (and not `ztimer_usec`) is used, the `mtd_spi_nor_power()` function will not execute the `wait_chip_wake_up` delay.
This causes `mtd_init()` to fail (and in a very annoying way: adding debug prints can cause enough of a delay that the init then works again).
`tests/drivers/mtd_raw`  should work with only `ztimer_msec`  instead of `ztimer_usec`.
wouldn't have happened if we had #19719

drivers/mtd_spi_nor: fix init when only ztimer_msec is used

---

dist/tools/doccheck/exclude_simple
drivers/include/stmpe811.h
drivers/stmpe811/include/stmpe811_params.h
drivers/stmpe811/stmpe811.c
drivers/stmpe811/stmpe811_touch_dev.c

To obtain coordinates from the touch panel that correspond to the display coordinates, it is often necessary to convert the coordinates by swapping and mirroring. Instead of hard coding this conversion, it is now controlled by an additional conversion parameter. For the sake of simplicity, possible rotations are predefined.
The PR fixes `tests/pkg/lgvl_touch` for the `stm32f429i-disc1`  board where the coordinates from the touch panel seem to be mirrored in relation to the screen coordinates at the vertical axis.
Flash `tests/pkg/lvgl_touch`. Without this PR the coordinates of the button don't correspond to the touch panel coordinates once the button has been pressed. Instead they seem to be mirrored at the vertical axis. With this PR, the coordinates should be correct.

drivers/stmpe811: introduce conversion for X and Y coordinates

---

boards/adafruit-itsybitsy-m4/Makefile.dep
boards/adafruit-itsybitsy-m4/board.c

The board comes with 2 MiB QSPI flash, we might as well configure a filesystem on it.
`tests/vfs_default` works as expected. 
```
2023-03-07 01:28:39,730 # > vfs df
2023-03-07 01:28:39,732 # Mountpoint              Total         Used    Available     Use%
2023-03-07 01:28:39,737 # /nvm0                   2 MiB        8 KiB     2040 KiB       0%
2023-03-07 01:28:46,010 # > ls /nvm0
2023-03-07 01:28:46,012 # ./
2023-03-07 01:28:46,012 # ../
2023-03-07 01:28:46,014 # total 0 files
```

boards/adafruit-itsybitsy-m4: configure littleFS on external flash

---

boards/stm32f746g-disco/Makefile.include
boards/stm32f746g-disco/doc.txt
boards/stm32f746g-disco/include/periph_conf.h
boards/stm32f769i-disco/Kconfig
boards/stm32f769i-disco/Makefile.dep
boards/stm32f769i-disco/Makefile.features
boards/stm32f769i-disco/Makefile.include
boards/stm32f769i-disco/include/periph_conf.h
tests/periph/fmc/main.c

This PR enables the FMC support on the `stm32f769i-disco` board and the on-board SDRAM MT48LC4M32B2B5-6A with 16 MByte.
The PR also includes a very small documentation fix for the `stm32f746g-disco` board (commit
f761e2d616c861e4857563bae26152bc1f1699d7) and removes double empy line in the test app `tests/periph/fmc`.
1. `tests/periph/fmc` should succeed, just compile and flash the app with
```
BOARD=stm32f769i-disco make -C tests/periph/fmc flash term
```
2. `tests/sys/malloc` should also use the SDRAM. Use
```
USEMODULE=periph_fmc_sdram CFLAGS='-DCHUNK_SIZE=131072' \
BOARD=stm32f769i-disco make -C tests/sys/malloc flash term
```
and check that the heap also uses the memory in the range from `0xc0000000` to `0xc0fffffff`.
**UPDATE:** Tested with a `stm32f769i-disco` board.
<details> …

boards/stm32f769i-disco: enable FMC with SDRAM support

---

drivers/include/periph/doc.txt
drivers/include/periph/init.h

The CI will generate a doc preview that can be reviewed.
None

drivers/periph: Add documentation on thread safety and initialization

---

cpu/sam0_common/periph/gpio.c
drivers/at86rf215/include/at86rf215_params.h

Attaching the `at86rf215` reference module to a `same54-xpro` (via EXT1) stops working after 2a255ff3e80111682aac9df0e2a49974e770ba16 configured the PHY IRQ pin to produce interrupts.
This is because both the PHY IRQ (PD12) as well as the `at86rf215` IRQ (PB07) map to EXI7.
Whatever of the two pins gets configured last wins.
Attach the REB215-XPRO module to EXT3 on `same54-xpro`.
Frame reception should now work again even if `sam0_eth` is in use.
fixes #19911

drivers/at86rf215: switch example config to use EXT3 on same54-xpro 

---

drivers/include/st77xx.h
drivers/lcd/include/lcd_internal.h
drivers/lcd/lcd.c
drivers/st77xx/Kconfig.st7735
drivers/st77xx/Kconfig.st7789
drivers/st77xx/Kconfig.st7796
drivers/st77xx/Makefile
drivers/st77xx/include/st7735_internal.h
drivers/st77xx/include/st7789_internal.h
drivers/st77xx/include/st7796_internal.h
drivers/st77xx/include/st77xx_internal.h
drivers/st77xx/st7735_init.c
drivers/st77xx/st7789_init.c
drivers/st77xx/st7796_init.c
drivers/st77xx/st77xx.c

This PR implements correct initialization for ST7735, ST7789 and ST7796. A number of configuration parameters are exposed via Kconfig. The user can decide whether to use custom configuration parameters or reset defaults.
~To be compilable, the PR includes PR #19824 and PR #19825~
- Green CI
- `tests/drivers/disp_dev` and `tests/drivers/st77xx` should still work for all boards using a ST77xx display.
- The PR was already tested for these tests for:
~Depends on #19825~
Fixes #19818

drivers/st77xx: implement initialization

---

drivers/include/sdmmc/sdmmc.h
drivers/sdmmc/sdmmc.c

SDIO/SD/MMC device descriptor references are now defined as members of an XFA array `sdmmc_devs`. The i-th device in this array can then be accessed with `sdmmc_devs[i]`. The number of SDIO/SD/MMC device descriptors `SDMMC_NUMOF` is `XFA_LEN(sdmmc_devs)`.
Green CI

drivers/sdmmc: store SDMMC device descriptor references in XFA

---

sys/include/net/gnrc/ipv6/nib/conf.h
sys/net/gnrc/routing/rpl/gnrc_rpl.c

Router Advertisements are enabled automatically for routing nodes as soon as they obtain a prefix (e.g. via DHCPv6, UHCP, …).
Enabling router advertisements without a prefix to advertise is wrong and causes no router solicitations to be send on an upstream interface.
Also from https://www.rfc-editor.org/rfc/rfc4861#section-6.2.1
Note that AdvSendAdvertisements MUST be FALSE by
default so that a node will not accidentally start
acting as a router unless it is explicitly
configured by system management to send Router
Advertisements.
`examples/gnrc_networking` does now instantly obtain an address on a network with an upstream router.
`examples/gnrc_border_router` had this disabled already because an automatic prefix configuration method was used. 
`tests/net/gnrc_rpl` shows that RPL …

gnrc_ipv6_nib: disable router advertisements on interface startup

---

dist/tools/pyterm/pyterm

A common source of error is that a user connects to a serial port that has already been opened in another terminal.
This may lead to garbled output or no output at all.
To avoid this, claim exclusive access on the serial port so we get a proper error instead of corrupted output.
Connect to a serial port
```
$ ./dist/tools/pyterm/pyterm
2023-09-13 12:07:44,770 # Connect to serial port /dev/ttyUSB0
```
Now try to open the same port again in a different terminal
```
$ ./dist/tools/pyterm/pyterm
2023-09-13 12:08:07,907 # Connect to serial port /dev/ttyUSB0
2023-09-13 12:08:07,908 # Could not exclusively lock port /dev/ttyUSB0: [Errno 11] Resource temporarily unavailable
2023-09-13 12:08:07,908 # Trying to reconnect to /dev/ttyUSB0 in 10 sec
2023-09-13 …
```

dist/tools/pyterm: set exclusive access on port

---

boards/msb-430/Kconfig
boards/msb-430/Makefile.features
boards/msb-430/doc.txt
boards/msb-430/include/periph_conf.h

tl;dr: This fixes the periph config of the MSB-430 board and improves the documentation.
The pins P5.2, P5.1, P5.3 configured as SPI pins are only routed to USART1 and not to USART0, but previously USART0 was configured as peripheral backing the bus. This fixes the peripheral configuration by changing it to USART1.
This is quite unfortunate as USART1 is also used to provide the UART interface used for `stdio`. Hence, one can either use `stdio` or SPI. A feature conflict between UART and SPI has therefore been added.
Note that while it would be possible to use P3.2, P3.1, P3.3 to provide SPI with USART0, this would not work in practise: P3.1 and P3.3 are connected to the CC1020 transceiver.
Switching to P3.4/P3.5 for UART to provide it using USART 0 would also resolve the resource …

boards/msb-430: Fix periph config & improve doc

---

drivers/include/pcf857x.h
drivers/pcf857x/pcf857x.c

This allows including the header without using the module. Obviously, calls to the functions provided by the header won't like without using the module. But including the header can still be useful for e.g.:
if (IS_USED(MODULE_PCF857x)) {
/* make use of the module */
}
In the above example all calls to pcf857x functions would be optimized out when the module is not used, full compile checks happen in either case.
- binaries should not change
- including the pcf857x header should work without having selected one of the pcf857x variants, if the driver is not actually used
- when calling any of the functions provided, linking should fail
- when using the `pcf857x` module without any variant, compiling should still fail with a message indicating that (at least) one of the pcf857x needs to be …

drivers/pcf857x: Move compile time check to compilation unit

---

cpu/sam3/periph/timer.c

The API of timer_init() expects callers to know what frequencies are supported and only use valid frequencies. So let's add an `assert()` to aid debugging if the app uses an invalid.
- any valid application should compile and work as before
- an application using an unsupported timer frequency should trigger an `assert()`, rather than letting the timer silently run at a (possibly widely) different frequency
None

cpu/sam3: assert valid freq in timer_init()

---

examples/gcoap/Makefile.ci

Bors run for PR #19927 reveals that ```examples\gcoap``` do not fit in saml11-xpro board. 
I checked and this same linker error also appears on current master branch. 
This PR add sampl11-xpro board to the Makefile.ci BOARD_INSUFFICIENT_MEMORY list.
See logs from bors https://ci.riot-os.org/details/073c5dadc6ba4bc8a613edb78a1a4a2d
PR #19927

examples/gcoap: add saml11-xpro to CI boards with insufficient memory

---

boards/seeedstudio-gd32/doc.txt
boards/sipeed-longan-nano-tft/doc.txt
boards/sipeed-longan-nano/doc.txt

This PR fixes some small problems in documentation of `sipeed-longan-nano`, `sipeed-longan-nano-tft` and `seeedstudio-gd32` for doxygen 1.9.4 that is used on `doc.riot-os.org`.
Doxygen version 1.9.4 doesn't like anymore
- single double quotes as symbol for the inches unit in the text
- line breaks in `[]()` to avoid exhausting the 100 characters per line.
See https://doc.riot-os.org/group__boards__sipeed__longan__nano.html for example.
Doxygen 1.9.1 which is part of `riot-docker` container didn't have theses problems :worried:
Documentation should be fixed.

boards: fix documentation for GD32V boards and doxygen 1.9.4

---

boards/common/nucleo64/include/arduino_iomap.h

Before, the Arduino SPI mapping for all Nucleo-64 boards was incorrect. With this, the situation improves to the following:
- No SPI buses provided.
- No SPI bus at D11, D12, D13 provided
- No SPI bus at D11, D12, D13 provided
The remaining offenders still need to be fixed, but that is better done one PR at a time.
- Check if the SPI device provided in the given `boards/<BOARD_NAME>/incude/periph_conf.h` is indeed `SPI_DEV(0)`, or in `periph_conf.h` the correct SPI dev is found
- this should be fine for all boards above, except for the unchecked ones
or:
- run https://github.com/RIOT-OS/RIOT/pull/19932: The SPI test should pass now
Bug found in https://github.com/RIOT-OS/RIOT/pull/19932#issuecomment-1726305437

boards/nucleo64: fix SPI Arduino mapping for most boards

---

boards/common/esp32x/include/board_common.h
boards/seeedstudio-gd32/include/board.h
boards/sipeed-longan-nano/include/board.h
boards/waveshare-nrf52840-eval-kit/include/board.h

This PR completes the MTD definition for the following boards:
- `seeedstudio-gd32`
- `sipeed-longan-nano` including `sipeed-longan-nano-tft`
- `waveshare-nrf52840-eval-kit`
- ESP32x boards that have an SPI SD Card interface and use `mtd_sdcard_default`
Green CI
Prerequisite for PR #19465

boards: complete SD Card MTD definition for several bords

---

drivers/ili9341/include/ili9341_params.h
drivers/include/lcd.h
drivers/include/st77xx.h
drivers/lcd/Kconfig
drivers/lcd/Makefile.dep
drivers/lcd/Makefile.include
drivers/lcd/lcd.c
drivers/lcd/lcd_disp_dev.c
drivers/st77xx/include/st77xx_params.h

LCD driver ICs usually support
- SPI serial mode,
- MCU 8080 8-bit parallel mode and
- MCU 8080 16-bit parallel mode.
This PR extends the LCD display driver API to support the MCU 8080 8-/16-bit parallel modes and implements a GPIO-driven MCU 8080 8-bit parallel mode.
The following features are already working locally and will be provided as follow-on PRs for which this PR is a prerequisite.
- GPIO-driven bit-banging implementation of the 16-bit mode of the MCU 8080 parallel interface
- Enabling the display on `stm32f723e-disco` and `stm32l496g-disco` using the feature above
- Definition of a low-level API for the parallel modes using the LCD controller of the MCU
- Using FMC for the display on `stm32f723e-disco` and `stm32l496g-disco`
- Using LCD controller for the display of …

drivers/lcd: support MCU 8080 8-bit parallel mode

---

examples/gcoap/Makefile.ci
sys/net/gnrc/network_layer/icmpv6/echo/gnrc_icmpv6_echo.c
sys/shell/cmds/gnrc_icmpv6_echo.c

In #19829 @mchesser point out integer overflow in the ```ping``` command and API. This PR fix this issue in two ways:
1) Add protection in the API.
2) Add protection in the user command.
Without this PR passing negative number to the ```ping -s``` option cause segmentation fault, for example in the 
```example/gnrc_networking```:
```
> ping -s -7 ::1
ping -s -7 ::1
Segmentation fault
```
With this PR user shows appropriate warning test:
```
> ping -s -7 ::1
ping -s -7 ::1
ICMPv6 datagram size should be in range <0, 65527>.
> 
``` 
Issue #19829

sys/shell/ping: fix ping packet size overflow

---

boards/stm32f723e-disco/Kconfig
boards/stm32f723e-disco/Makefile.dep
boards/stm32f723e-disco/board.c
boards/stm32f723e-disco/include/board.h
boards/stm32l496g-disco/include/board.h
tests/drivers/st77xx/Makefile

This PR enables the ST7789 display and the touch panel for the `stm32f723e-disco`.
The PR requires PR #19937.
```
BOARD=sstm32f723e-disco make -j8 -C tests/drivers/st77xx
```
should work.
Depends on PR #19937

boards/stm32f723e-disco: enable ST7789 display

---

pkg/littlefs2/Makefile

New [upstream release](https://github.com/littlefs-project/littlefs/releases/tag/v2.8.0
), what's new:
-  littlefs no longer needs the block_count when mounting an existing filesystem (https://github.com/littlefs-project/littlefs/pull/866)
Simply set block_count=0 in your configuration, and littlefs will automatically determine the block_count based on what's on disk. This allows you to mount a filesystem of unknown size.
- Added `lfs_fs_grow` which allows you to change the size of an existing filesystem (https://github.com/littlefs-project/littlefs/pull/872)
- Added `lfs_fs_gc` which allows you to manually run the block allocator (https://github.com/littlefs-project/littlefs/pull/875)
`tests/pkg/littlefs2` still works

pkg/littlefs2: bump to v2.8

---

boards/esp32s3-wt32-sc01-plus/Kconfig

This PR fixes the `Kconfig` mismatch for the I2C peripheral driver selection for the `esp32s3-wt32-sc01-plus` board.
```
python3 dist/tools/compile_test/compile_like_murdock.py -a tests/periph/i2c -b esp32s3-wt32-sc01-plus
```
fails w/o this PR
```
tests/periph/i2c               esp32s3-wt32-sc01-plus         FAIL: Kconfig module or pkg mismatch
```
and should succeed with this PR
```
tests/periph/i2c               esp32s3-wt32-sc01-plus         PASS
```

boards/esp32-wt32-sc01-plus: fix I2C driver selection in Kconfig

---

.github/workflows/test-on-iotlab.yml

It seems all dwm1001 boards on the IoT-LAB Lille site are down and the Toulouse site should now be considered as the preferred site anyway.
Not sure how this can be tested.
None

.github/test-on-iotlab: prefer Toulouse site for dwm1001 board

---

tests/pkg/lwip/README.md

While `tests/pkg/lwip` is automated, it is only so for `native` and IPv6. This adds some doc how to test for other modes, e.g. 6LoWPAN and IPv4.
Read, follow the instructions, give feedback what can be improved :-).
None

tests/pkg/lwip: Add README.md

---

sys/posix/sockets/posix_sockets.c

When building with `POSIX_SETSOCKOPT `defined (to be able to use the posix `setsockopt()` function to set `SO_RCVTIMEO`), this code fails to build with 16 bit integer compilers for some of the boards as there is an integer overflow for `1000*1000`.
There is also an invalid test that the provided `tv->tv_sec` is less than 0 as it is a `uint32_t`.
Murdock should fail if the following change is made to tests/sys/posix_sleep/Makefile without this PR.
````
diff --git a/tests/sys/posix_sleep/Makefile b/tests/sys/posix_sleep/Makefile
index 5dcb9ed74c..9e4f881492 100644
--- a/tests/sys/posix_sleep/Makefile
+++ b/tests/sys/posix_sleep/Makefile
@@ -5,4 +5,9 @@ USEMODULE += posix_sleep
TEST_ON_CI_BLACKLIST += microbit
+USEMODULE += gnrc_ipv6_default
+USEMODULE += sock_udp
+USEMODULE += posix_sockets …
```

posix_sockets.c: Fix 2 byte int compilation errors

---

cpu/esp32/ld/esp32s2/sections.ld.in
cpu/esp32/ld/esp32s3/sections.ld.in

For ESP32-S2 and ESP32-S3 the symbol `_heap_end` must not be used as `_eheap` for the newlibc `malloc` and function `sbrk`.
`_heap_end` is used by the ESP-IDF heap implementation `esp-idf-heap` and points to the highest possible address (0x40000000) that could be used for the heap in ESP-IDF. It doesn't point to the top address of the unused SRAM area that can be used in newlibc `malloc` and function `sbrk`. Instead, the origin and the length of `dram0_0_seg` must be used to calculate the end of the heap `_eheap`.
The problem only occurs for the newlibc `malloc` when the `sbrk` function is used but not for the ESP-IDF heap implementation `esp_idf_heap`.
Use any ESP32-S2 or ESP32-S3 board and flash `tests/sys/malloc`, e.g.
```
CFLAGS='-DCHUNK_SIZE=16384' USEMODULE='stdio_uart' …
```

cpu/esp32: fix heap definition for ESP32-S2 and ESP32-S3

---

boards/esp32s3-box/doc.txt
boards/esp32s3-pros3/doc.txt
cpu/esp32/ld/esp32s3/sections.ld.in

This PR fixes Octal SPI RAM handling for ESP32-S3.
Functions that are used during the initialization of the Octal SPI RAM must reside in IRAM instead of Flash. Otherwise, the system stucks during boot once the Octal SPI RAM is enabled. The reason is that the Flash is not available during the initialization of the Octal SPI RAM and the functions that are called during that initialization can't be accessed in Flash. As a result the call of such a function leads to code that is messed up and the system crashes.
The PR also includes the documentation fixe for the `esp32s3-box`. It also includes a small documentation fix regarding the SPI RAM for the `esp32s3-pros3` board.
Use a board that has Octal SPI RAM and flash `tests/sys/malloc`, e.g.:
```
CFLAGS='-DCHUNK_SIZE=16384' …
```

cpu/esp32: fix Octal SPI RAM for ESP32-S3

---

pkg/c25519/Makefile
pkg/driver_cryptocell_310/Makefile

- make sure to download/extract during prepare, instead of build
- this fixes the issue of missing include dependencies for other pkgs at build time
- for an app Makefile, include both `c25519` and `driver_cryptocell_310`
- on `master`, `make all` fails with a missing include path from the `driver_cryptocell_310` package
- with this change, it works
- isolated from #19954 as suggested by @miri64

pkg/driver_cryptocell_310: Fix Makefile

---

dist/tools/jlink/jlink.sh

I have noticed that when debugging the "hifive1b" board, JLinkGDBServer is still running after exiting GDB. 
After investigating the issue, it appears to be just a minor confusion of `$?` and `$!`.
```
$ BOARD=hifive1b make -C examples/hello-world all flash debug
$ ps aux | grep JLink
```
None

dist/tools/jlink: fix DBG_PID assignment

---

sys/include/ztimer/periodic.h

The `ztimer_periodic` callback function must return a `bool`, but in the example it's a `void` function.

ztimer_periodic: fix example in documentation

---

cpu/esp32/Makefile.include

This PR fixes the RISC-V ISA spec in compiler and linker flags for ESP32-C3 and GCC 12.2.
Earlier versions of the specs and tools subsumed `zicsr` and `zifencei` into the `I` extension which is no longer the case. Therefore, the RISC-V ISA spec in compiler and linker flags had to be changed from `-march=rv32imc` to `-march=rv32imc_zicsr_zifencei`.
As a consequence floating-point arithmetics and I/O were no longer working with `-march=rv32imc` with GCC 12.2 since `riscv32-esp-elf/lib/libm_nano.a` was linked instead of `riscv32-esp-elf/lib/rv32imc_zicsr_zifencei/ilp32/libm_nano.a` because `riscv32-esp-elf/lib/rv32imc/ilp32/libm_nano.a` is not existing in the toolchain.
Add a
```c
#include <math.h>
...
printf("sin(x): %f\n", sin(1.0f));
``` 
in the `main` function of any application. Without …

cpu/esp32: fix RISC-V ISA for ESP32-C3 with GCC 12.2

---

drivers/include/lcd.h
drivers/lcd/Kconfig
drivers/lcd/Makefile.dep
drivers/lcd/Makefile.include
drivers/lcd/include/lcd_internal.h
drivers/lcd/include/lcd_ll_par_gpio.h
drivers/lcd/lcd.c
drivers/lcd/lcd_ll_par_gpio.c
drivers/st77xx/st7735_init.c
drivers/st77xx/st7789_init.c
drivers/st77xx/st7796_init.c
tests/drivers/st77xx/main.c

The PR extends the LCD driver by a low-level interface for MCU-driven implementations of the MCU 8080 16-/8-bit parallel interface, allowing the MCU to use special peripherals for the interface, such as the FMC for STM32 MCUs, which is significantly faster than the integrated GPIO-driven parallel interface implementation of the LCD driver.
~Once PR #19938 and PR #19939 are merged, a PRs for these board can be pushed that allow to test this PR.~
Use either PR #19943 or PR #19944 on top of this PR to test, e.g. with PR #19943:
```
BOARD=stm32f723e-disco make -j8 -C tests/drivers/st77xx flash
```

drivers/lcd: add MCU-driven low-level parallel interface

---

sys/event/event.c
sys/include/event.h

It can be useful to know if an event is already queued. I was looking for such an API.
I tried `event_timeout_is_set()` but this only checks if the timer is scheduled which would put the event in the event list, which is fine IMO.
This checks if the event is in the event queue.
Given the other  `event_*` functions, implementation is straight forward, I would say.
#19963

sys/event: add event_is_queued()

---

sys/shell/cmds/gnrc_netif.c

This PR fix some language issues in the output of `ifconfig set`.
Compile any program with `gnrc_netif` module, for example `examples/gcoap`. 
Compare last line of presented outputs.
Output of `ifconfig help` without this PR.
```
> ifconfig help
ifconfig help
usage: ifconfig help
usage: ifconfig <if_id> [up|down]
usage: ifconfig <if_id> set <key> <value>
Sets an hardware specific specific value
```
Output of `ifconfig help` with this PR.
```
> ifconfig help
ifconfig help
usage: ifconfig
usage: ifconfig help
usage: ifconfig <if_id> [up|down]
usage: ifconfig <if_id> set <key> <value>
Sets a hardware specific value
```
None

sys/shell/gnrc_netif: fix ifconfig set language issue

---

pkg/lwip/contrib/_netif.c
sys/include/net/netopt.h
sys/net/crosslayer/netopt/netopt.c
sys/shell/cmds/gnrc_netif.c

Similar to Linux, lwIP has separate link and interface statuses. 
This change expose this in a netopt and updates gnrc ifconfig to show and set it.
I am not really happy with the `NETOPT_ACTIVE` name. Maybe `NETOPT_STATE` could be renamed to `NETOPT_RF_STATE`?
The code for setting up/down is not very nice. Not sure if link state will be controllable in lwIP - maybe for 6lowpan radios.
Flash `tests/pkg/lwip` . Any traffic received while the interface is down is dropped.
```
> ifconfig
Iface  ET0  HWaddr: 24:0A:C4:E6:0E:9F  Link: up  State: up 
L2-PDU:1500  Source address length: 6
inet6 addr: fe80::260a:c4ff:fee6:e9f  scope: link
> ifconfig ET0 down
> ifconfig
Iface  ET0  HWaddr: 24:0A:C4:E6:0E:9F  Link: up  State: down 
L2-PDU:1500  Source address length: 6
Link type: …
```

RFC: Support enabling/disabling lwIP netifs from gnrc_netif shell

---

sys/include/event/timeout.h
tests/sys/events/main.c

This adds a small convenience function to check if an event is scheduled.
`tests/sys/events` includes a test for the new function.

sys/event/timeout: add event_timeout_is_pending()

---

sys/shell/Makefile.dep
sys/shell/cmds/gnrc_netif.c

When using general IPv6 functions, require only shared IPV6 module instead of gnrc version.
Print addresses using l2util functions in gnrc_netif instead of with gnrc wrappers.
* ifconfig with gnrc_networking example still works
```
> ifconfig
Iface  8  HWaddr: 24:0A:C4:E6:0E:9F  Link: up
L2-PDU:1500  MTU:1500  HL:64  RTR
RTR_ADV
inet6 addr: fe80::260a:c4ff:fee6:e9f  scope: link  VAL
inet6 group: ff02::1:ffe6:e9f
inet6 group: ff02::1a
```
* tests/pkg/lwip ifconfig prints v6 info when 7160ed925813334f89875d0245980af1d25c6a5b applied
```
> ifconfig
Iface  ET0  HWaddr: 24:0A:C4:E6:0E:9F  Link: up
L2-PDU:1500  Source address length: 6
inet6 addr: fe80::260a:c4ff:fee6:e9f  scope: link
inet6 …
```

sys/shell/gnrc_netif: Fix a few blockers for sharing ifconfig shell

---

sys/net/gnrc/network_layer/ipv6/ext/frag/gnrc_ipv6_ext_frag.c

Should avoid some confusion in security reviews.

gnrc_ipv6_ext_frag: _completed: Add comment why list head is not checked for NULL pointer dereference

---

pkg/nanocbor/Makefile

Not much to see here
Important changes:
- Add stream-like interface for encoder
- Separate functions for number of items left in arrays and maps
The usual test should still work
None

pkg/nanocbor: Bump to latest commit

---

core/include/sched.h

When compiling _rust-hello-world_ for the _nrf52840dongle_, c2rust seem to generate code which casts -1 to u8 which fails because it's unsigned. Changing to ~0 fixes this.
```
error[E0600]: cannot apply unary operator `-` to type `u8`
--> RIOT/examples/rust-hello-world/bin/nrf52840dongle/target/thumbv7em-none-eabihf/release/build/riot-sys-a758a33386ee540f/out/riot_c2rust_replaced.rs:6813:39
|
6813 |     let mut result: thread_status_t = -1 as thread_status_t;
|                                       ^^
|                                       |
|                                       cannot apply unary operator `-`
|                                       help: you may have meant the maximum value of `u8`: `u8::MAX`
|
= note: unsigned values cannot be negated
For more information about this …
```

core: Express -1 as ~0 in thread_status_t cast

---

dist/testbed-support/makefile.iotlab.archi.inc.mk

As part of fixing the automated release specs test we will need support for another `cc2538` based board.  I was able to get the tests passing with adaption here and to the release specs.

dist/testbed-support: Add openmote board

---

sys/net/application_layer/gcoap/gcoap.c

Fixes an underflow error when getting a new ETag from cache, by returning early.
I repeated the testing procedures from https://github.com/RIOT-OS/RIOT/pull/17801#issuecomment-1123432269 (attention, the expected input for `examples/gcoap` changed slightly in the last year and a half)
```diff
diff --git a/aiocoap/cli/fileserver.py b/aiocoap/cli/fileserver.py
index 6af2b84..f5a9e71 100644
--- a/aiocoap/cli/fileserver.py
+++ b/aiocoap/cli/fileserver.py
@@ -154,6 +154,7 @@ class FileServer(Resource, aiocoap.interfaces.ObservableResource):
elif S_ISREG(st.st_mode):
response = await self.render_get_file(request, path)
+        response.opt.max_age = 10
response.opt.etag = etag
return response
```
)
```console
$ sudo ./dist/tool/tapsetup/tapsetup
$ PORT=tap1 USEMODULE="gcoap_forward_proxy …
```

gcoap: fix underflow when correcting ETag from cache

---

pkg/nanocbor/Makefile

@miri64 found a bug in NanoCBOR which is fixed with the latest commit.
Important changes:
- Fixed a bug in nanocbor_skip_simple with (b|t)str types
The pkg test should still pass.
None

pkg/nanocbor: Update for fixed nanocbor_skip_simple()

---

dist/testbed-support/makefile.iotlab.archi.inc.mk

As part of fixing the automated release specs test we will need support for another `cc2538` based board.  I was able to get the tests passing with adaption here and to the release specs.

dist/testbed-support: Add openmote board [backport 2023.10]

---

sys/checksum/fletcher32.c
sys/include/checksum/fletcher32.h
tests/unittests/tests-checksum/tests-checksum-fletcher32.c

This PR extends the current fletcher32 checksum with an incremental API mode. This way the bytes to be checksummed can be supplied via multiple successive calls and do not have to be provided in a single consecutive buffer.
I've also rephrased the warning with the original function a bit as that function uses an `unaligned_get_u16` to access the data. The data thus does not require alignment, but the length does need to be supplied as number of 16 bit words.
The test has been extended
None

Fletcher32: Add incremental API

---

boards/adafruit-grand-central-m4-express/board.c
boards/adafruit-itsybitsy-m4/board.c
boards/adafruit-pybadge/board.c
boards/common/weact-f4x1cx/board.c
boards/ikea-tradfri/board.c
boards/iotlab-m3/mtd.c
boards/mcb2388/board_init.c
boards/msba2/board_init.c
boards/mulle/board.c
boards/native/board_init.c
boards/nrf52840dk/mtd.c
boards/nrf5340dk-app/board.c
boards/nrf5340dk-app/include/board.h
boards/pinetime/board.c
boards/qn9080dk/board.c
boards/same54-xpro/board.c
boards/same54-xpro/include/board.h
boards/samr34-xpro/board.c
boards/serpente/board.c
cpu/esp_common/periph/flash.c
drivers/include/mtd.h
drivers/include/mtd_default.h
drivers/include/mtd_emulated.h
drivers/mtd/mtd.c
drivers/mtd_sdcard/mtd_sdcard.c
drivers/mtd_sdmmc/mtd_sdmmc.c
sys/include/usb/usbus/msc.h
sys/usb/usbus/msc/msc.c
tests/drivers/mtd_raw/main.c

This PR provides the support to hold pointers to defined MTDs within a XFA. The XFA allows
- to access MTDs of different types (`mtd_flashpage`, `mtd_sdcard`, `mtd_emulated`, ...) by an index
- to determine the number of MTDs defined in the system.
To be defined once PR #19443 is merged because emulated MTDs will allow to test this PR on arbitrary boards.
For external boards:
- remove the `MTD_NUMOF` definition from `board.h`
- add `MTD_XFA_ADD(<mtd_dev>, <idx>);` to the definition of `<mtd_dev>`.
- `MTD_0`, `MTD_1`, … defines are no longer needed.
Related to PR #19443

drivers/mtd: use XFA for pointers to defined MTDs

---

tests/unittests/Makefile

This test is randomly failing CI, so disable it.
Hopefully less [sporadic](https://ci.riot-os.org/details/eb28f35184364283979f048387078f3b) [CI](https://ci.riot-os.org/details/ba8dc586773848169e824fef3040ba9e) [failures](https://ci.riot-os.org/details/8758555a2c3b49938a64bfecf958e44b).
same as #19634
708e5eadb4e

tests/unittests: blacklist LLVM on native

---

.github/workflows/release-test.yml

This adds creds for stasbourg needed for the `openmote-b` tests in the release specs.
Hmmm... I don't know how easy it is.  I will try to link results of the workflow from my personal fork maybe?
Needed for https://github.com/RIOT-OS/Release-Specs/pull/289

release-test.yml: Add stasbourg creds

---

pkg/nanocbor/Makefile

Manually created the backport this time :cry: 
Includes both #19975 and #19983 to include the nanocbor bug fix for the `nanocbor_skip_simple()` function
The usual nanocbor test in `tests/pkg/nanocbor`
None

pkg/nanocbor: Update for fixed nanocbor_skip_simple() [backport 2023.10]

---

tests/unittests/tests-ztimer/tests-ztimer-mock.c

This adds test coverage for removing ztimers with focus on ensuring that offsets are correctly updated on subsequent timers (e.g. not having timers fire too early).
Run the unit tests (will be done by the CI as well). Maybe also introduce a random bug in `ztimer_remove()` and check if this is indeed caught by the unit tests.
Prompted by https://github.com/RIOT-OS/RIOT/pull/18977#issuecomment-1764258356

tests/unittests: add a unit test for ztimer

---

sys/crypto/psa_riot_cipher/aes_128_cbc.c
sys/psa_crypto/psa_crypto.c
tests/sys/psa_crypto/Makefile
tests/sys/psa_crypto/Makefile.ci
tests/sys/psa_crypto/main.c
tests/sys/psa_crypto/tests/01-run.py

- simple unit test which calls `psa_crypto_init()` twice
- fix to no re-initialize key slots (which left them in a broken state)
- `make -C tests/sys/psa_crypto all test` succeeds
- `git checkout HEAD~1 && make -C tests/sys/psa_crypto all test` fails

sys/psa_crypto: allow repeated initialization

---

sys/net/application_layer/nanocoap/nanocoap.c

If uri contains no path but only a query "?foo=bar" `len` would underflow. Fix this by detecting if there is no path.
Reported by @Yu3H0
https://github.com/RIOT-OS/RIOT/security/advisories/GHSA-4hvc-7m7r-78xq

nanocoap: prevent integer underflow in coap_opt_put_uri_pathquery()

---

.github/workflows/release-test.yml

This adds creds for stasbourg needed for the `openmote-b` tests in the release specs.
Hmmm... I don't know how easy it is.  I will try to link results of the workflow from my personal fork maybe?
Needed for https://github.com/RIOT-OS/Release-Specs/pull/289

release-test.yml: Add strasbourg creds [backport 2023.10]

---

sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c

The function checks for `netif == NULL` several times, but if `netif` really is NULL we will already crash on `_nib_drl_get(NULL, netif->pid);`.

nib/_nib-6ln: bail out early if address is no longer assigned

---

sys/include/net/coap.h
sys/include/net/gcoap/dns.h

Some housekeeping on `gcoap_dns`:
- Update URL to draft, it is a Working Group draft since last year (September 2022)
- Update `application/dns-message` Content-Format: In `draft-ietf-core-dns-over-coap-03` it was set to 553
Only reading and successful compilation is required.
:x:

gcoap_dns: Housekeeping with regards to draft status

---

.vscode/settings.json

The vertical rulers in Visual Studio Code are set to 80 and 120, while the coding conventions says to aim for no more than 80 characters and a maximum of 100 ( https://github.com/RIOT-OS/RIOT/blob/master/CODING_CONVENTIONS.md ).
So I changed the second ruler to 100.

.vscode/settings.json: change vertical ruler to comply with coding conventions

---

drivers/slipdev/include/slipdev_params.h
pkg/lwip/contrib/netdev/lwip_netdev.c
pkg/lwip/init_devs/auto_init_slipdev.c

This hooks up support for `slipdev` in LWIP.
I tested with `examples/gcoap` with `LWIP_IPV6=1` and `USEMODULE += slipdev_l2addr` on one side and `tests/net/nanocoap_cli` on the other side with two `saml21-xpro` boards where the pins of UART1 are connected.
Issuing a CoAP request via the SLIP interface returns the expected respnose:
```
2023-10-26 15:54:43,302 - INFO # > ncget coap://[fe80::e858:4ed2:564e:215a]/.well-known/core -
2023-10-26 15:54:43,302 - INFO # 
2023-10-26 15:54:43,327 - INFO # </cli/stats>;ct=0;rt="count";obs,</riot/board>
```

pkg/lwip: add support for slipdev

---

tests/drivers/at/main.c

This PR fix device table overflow in `tests/driver/at`, which could lead to device crash.
PR was tested on two nucleo boards with 2 and 3 UARTs (nucleo-l476rg and nucleo-l496zg).
Flash `tests/driver/at` with and without this PR.
Output with this PR:
```
> main(): This is RIOT! (Version: 2022.07-devel-5083-g2b9e8-tests-drivers-at)
AT command test app
> init 5 9600
Wrong UART device number - should by in range 0-2.
>
```
Output without this PR:
```
> main(): This is RIOT! (Version: 2022.07-devel-5083-g2b9e8)
AT command test app
> init 5 9600
8001afd
*** halted.
Context before hardfault:
r0: 0x0000000a
r1: 0x00000000
. . . 
```
None

tests/drivers/at: fix device table overflow

---

boards/feather-nrf52840-sense/Kconfig
boards/feather-nrf52840-sense/Makefile
boards/feather-nrf52840-sense/Makefile.dep
boards/feather-nrf52840-sense/Makefile.features
boards/feather-nrf52840-sense/Makefile.include
boards/feather-nrf52840-sense/doc.txt
boards/feather-nrf52840-sense/include/board.h
boards/feather-nrf52840-sense/include/gpio_params.h
boards/feather-nrf52840-sense/include/periph_conf.h
boards/feather-nrf52840-sense/reset.c

This adds support for the [Adafruit Feather nRF52840 Sense](https://learn.adafruit.com/adafruit-feather-sense). A nice prototyping board that comes with many onboard sensors. RIOT already supports most of it.
Note: you may need to [update the bootloader](https://learn.adafruit.com/adafruit-feather-sense/update-bootloader) in order to make flashing work. Version 0.7 worked fine for me. Note that some OSes do not auto mount the UF2 drive which prevents flashing. The uf2 helper `dist/tools/uf2/uf2conv.py` could use some improvements for handling distro-specific mount paths properly, which also applies to existing boards.
Making use of the LSM6DS33 gyro/accelerometer might need some work on an existing driver (https://github.com/RIOT-OS/RIOT/issues/17053). Currently there is no support for …

boards: add support for Adafruit Feather nRF52840 Sense

---

boards/nucleo-l552ze-q/Kconfig
boards/nucleo-l552ze-q/Makefile.features
boards/nucleo-l552ze-q/include/periph_conf.h

This PR adds to the Nucleo-l552ze-q PWM configuration
Flash the board using `tests/periph/pwm` program. Check if you could, for example, change LED 
intensity using PWM. 
None.

boards/nucleo-l552ze: add PWM configuration

---

dist/tools/zep_dispatch/start_network.sh
examples/gnrc_border_router/Makefile.native.conf

When simulating a IEEE 802.15.4 network, it is handy being able to specify a topoloy.
make -C examples/gnrc_border_router ZEP_TOPO_FILE=network.topo ZEP_MONITOR=1 term
will make use of the file `network.topo` and create a `wpan0` with which the traffic on the simulated wireless network can be monitored with Wireshark.
```
A	B
B	C
C	D
```
To start the wireless nodes, run 3 instances of `examples/gnrc_networking` with `USE_ZEP=1`.

examples/gnrc_border_router: enable setting ZEP topology

---

boards/feather-nrf52840-sense/doc.txt

Add some info on how to deal with really old bootloaders on the `boards/feather-nrf52840-sense`.
Read it and maybe try the example.
Here is the script I used:
<details><summary>update-bootloader-less-than-0.4.sh</summary>
```bash
command -v arm-none-eabi-gcc >/dev/null 2>&1 || echo "gcc-arm-none-eabi must be installed!"
FOLDER="/tmp/Adafruit_nRF52_Bootloader"
if [ ! -d "$FOLDER" ] ; then
git clone https://github.com/adafruit/Adafruit_nRF52_Bootloader.git $FOLDER
fi
cd $FOLDER
git submodule update --init
make BOARD=feather_nrf52840_sense SERIAL=/dev/ttyACM0 flash-dfu
```
stdout:
```
$ ./boards/feather-nrf52840-sense/update-bootloader.sh 
Submodule 'lib/nrfx' (https://github.com/NordicSemiconductor/nrfx.git) registered for path 'lib/nrfx'
Submodule 'lib/tinyusb' …
```

boards/feather-nrf52840-sense: Add bootloader info

---

dist/tools/uf2/Makefile

Bump UF2 package version. The new version, besides many other things, also includes an improvement to search more potential mount paths, which gives better compatibility for different distros.
Test if flashing still works for boards that use UF2 (e.g., `feather-nrf52840`, `feather-nrf52840-sense`, `nrf52840-mdk-dongle`):
`BUILD_IN_DOCKER=1 BOARD=feather-nrf52840-sense make -C examples/hello-world all flash term`
With master you should get this error, during flashing: `No drive to deploy.` if you run it on a distro that mounts your device under something like `/run/media/<username>/FTHRSNSBOOT`, or other paths not supported by the old version. To me this happened on Arch.
**Note: you will still get this error if your system doesn't auto mount the device.** But now it will be found when …

Bump version of UF2 package

---

sys/include/net/coap.h
sys/include/net/nanocoap_sock.h

Avoid confusion between `COAP_PUT` and `COAP_METHOD_PUT` by creating a type for the latter.
Shuld result in no change in the binary.

coap: create typedef for CoAP methods

---

sys/net/application_layer/gcoap/fileserver.c
sys/net/application_layer/gcoap/gcoap.c
sys/net/application_layer/nanocoap/cache.c
sys/net/application_layer/nanocoap/sock.c

These users were not meant to check for the decimal representation of the code.
split off from #20004

nanocoap: fix incorrect uses of coap_get_code()

---

boards/nucleo-l4r5zi/Kconfig
boards/nucleo-l4r5zi/Makefile.features
boards/nucleo-l4r5zi/include/periph_conf.h

This PR adds to the Nucleo-l4r5zi PWM configuration
Flash the board using `tests/periph/pwm` program. Check if you could, for example, change LED 
intensity using PWM. 
None.

boards/nucleo-l4r5zi : add PWM configuration

---

sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c

The function checks for `netif == NULL` several times, but if `netif` really is NULL we will already crash on `_nib_drl_get(NULL, netif->pid);`.

nib/_nib-6ln: bail out early if address is no longer assigned [backport 2023.10]

---

sys/net/application_layer/nanocoap/nanocoap.c

If uri contains no path but only a query "?foo=bar" `len` would underflow. Fix this by detecting if there is no path.
Reported by @Yu3H0
https://github.com/RIOT-OS/RIOT/security/advisories/GHSA-4hvc-7m7r-78xq

nanocoap: prevent integer underflow in coap_opt_put_uri_pathquery() [backport 2023.10]

---

cpu/native/periph/timer.c
cpu/native/syscalls.c

While debugging https://github.com/RIOT-OS/RIOT/pull/18977#issuecomment-1764258356 it became obvious that the `periph_timer` in `native` is broken and issues early IRQs. This replaces the use of `setitimer` that cannot use a monotonic clock source with `timer_settime()`.
I have some non-publishable code that tests if the time an ISR fires in terms of `timer_read()` is no earlier than the time expected. This occasionally triggered with `master`, but I didn't see any of these issues anymore with this PR. I guess I should revive my PR to spice up the periph timer tests and add a polished version of this and let this run for an hour or two.
The tests ins `tests/periph/timer*` should still succeed on `native`. (They do for me in a container running `riot/riotbuild`).
Found while debugging …

cpu/native: fix bug in periph_timer

---

dist/tools/uf2/Makefile

The updated UF2 pkg (#20035) stores the family ID in an external .json file. I overlooked that and flashing fails if this file is not present. This PR fixes it by also copying the json into the tool folder.
Check if the `feather-nrf52840-sense` can be flashed when the new UF2 pkg is cloned freshly.
Fixes a regression introduced with #20035

dist/tools/uf2: add target to also copy families.json file

---

.murdock.yml

This PR adds the [github merge train branch spec](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-third-party-ci-providers) to our Murdock config.
It's a prerequisite for murdock even looking at those branches.
Let's add it now, even if we don't need it.
#20051

ci: build github merge train branches with murdock

---

.github/workflows/check-commits.yml
.github/workflows/check-labels.yml
.github/workflows/labeler.yml
.github/workflows/static-test.yml
.github/workflows/tools-buildtest.yml
.github/workflows/tools-test.yml
.murdock

This allows merge_groups on all "required" checks for a PR and skips the ones that would not be required when merging though the merge queue such as `check_labels`.  This will allow simple branch protection rules for all checks run in a PR that would also apply (or be skipped) when merging with the queue.
Setup the branch protections and try to fail and make sure thing cannot get merged in.

.github/workflows/*: Allow merge_groups and prs to be required

---

.github/workflows/static-test.yml

Update workflows to pass a correct `CI_BASE_BRANCH` when building a merge_group.
"static-tests" on merge_groups should be fast.

ci: fix github.base-ref for merge_group builds

---

.github/workflows/check-commits.yml
.github/workflows/check-labels.yml
.github/workflows/labeler.yml
.github/workflows/static-test.yml
.github/workflows/tools-buildtest.yml
.github/workflows/tools-test.yml
.murdock

These are changes required to switch merging from bors to Merge Queues.
Ideally required tests pass and we can enter it into a merge queue.
Tracking issue: #20051

ci: migrate to github merge queues

---

boards/common/esp32x/doc.txt

The PR fixes the doxygen group for ESP32x boards so that `ESP32x Common` isn't shown any longer as top level entry in `Modules` menu.
`make doc` and check documentation locally.

boards/common/esp32x: fix doxygen group

---

dist/tools/uf2/.gitignore

With the updated `uf2` tool it seems like the `uf2families.json` is not ignored, which can be annoying.
Run:
```
BUILD_IN_DOCKER=1 BOARD=feather-nrf52840-sense make flash -C examples/hello-world/
```
and check that the `git status` no longer shows:
```
$ git status
On branch master
Untracked files:
(use "git add <file>..." to include in what will be committed)
dist/tools/uf2/uf2families.json
```

dist/tools/uf2: Ignore the .json file

---

drivers/pcf857x/pcf857x.c

- make sure format specifiers match variable arguments in debug statements
- drop unused headers
- when build without `ENABLE_DEBUG`, the binaries should not change
- compiling with `ENABLE_DEBUG` in `drivers/pcf857x/pcf857x.c` set to `1` should now work with modern toolchains
None

drivers/pcf857x: minor cleanup

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

The border router would send multicast neighbor solicitations when resolving node addresses. 
This is against the specification.
Check if the interface is 6lo before starting multicast address resolution.
https://github.com/RIOT-OS/RIOT/pull/16988#discussion_r778008765

gnrc/ipv6/nib: don't do multicast address resolution on 6LoWPAN

---

boards/nucleo-wl55jc/include/arduino_iomap.h
tests/periph/selftest_shield/Makefile
tests/periph/selftest_shield/Makefile.board.dep
tests/periph/selftest_shield/README.md
tests/periph/selftest_shield/main.c
tests/periph/selftest_shield/tests-with-config/01-run.py
tests/periph/selftest_shield/tests/01-run.py

This adds a test that makes use of the peripheral selftesting shield.
- grab an Arduino UNO compatible board that has the Arduino pin map feature
- connect it to the testing shield
- configure the testing shield
- make sure the VCC selector matches the logic level of the board (3.3V and 5V are the only options)
- enabled all the "loops" needed for testing on SW1
- it could be that the UART on D0, D1 is used for stdio. In that case, do *NOT* close the loop
- flash and run the test application
none

tests/periph: Add test using the Peripheral Selftest Shield

---

cpu/sam0_common/periph/adc.c

This one slipped through. When only ADC1 is used, `adc0` remains uninitialized.

cpu/sam0_common: adc_continuous: fix uninitialized access

---

drivers/include/mtd.h
drivers/include/mtd_default.h
sys/include/usb/usbus/msc.h
sys/usb/usbus/msc/msc.c
tests/drivers/mtd_raw/main.c
tests/sys/usbus_msc/main.c

With the introduction of XFA based MTD registration, the canonical way to get an MTD is now via `mtd_default_get_dev()`.
This is a bit awkward as the `mtd_default.h` purely existed as a workaround for what is now provided by XFA.
Use a better name for the function to indicate that this is now really the only way to get e.g. the first MTD device. 
follow-up to #19465

drivers/mtd: rename mtd_default_get_dev() -> mtd_dev_get()

---

boards/nucleo-f070rb/Kconfig
boards/nucleo-f070rb/Makefile.features
boards/nucleo-f070rb/include/periph_conf.h
tests/drivers/cc110x/Makefile.ci

This PR adds SPI configuration to nucleo-f070rb board.
Flash the board using `tests/periph/spi` . Check if SPI works.
Lack of this feature reported in Issue #20071

boards/nucleo-f070rb: add SPI configuration

---

cpu/avr8_common/Makefile.include
cpu/avr8_common/include/flash_utils_arch.h
cpu/avr8_common/work_around_for_shitty_ubuntu_toolchain.c
sys/include/flash_utils.h

- The signature of `flash_memcpy()` in the Doxygen output was incorrect. This is fixed by the first commit
- Using the prepocessor to alias the `<funcname>_P()` functions to `flash_<funcname>()` doesn't work with LLVM
- unlike GCC, LLVM doesn't like dropping `FLASH_ATTR` (or `__flash`) silently, but wants a cast
- using C code (`static inline` wrappers) in place of the preprocessor makes the use of clangd much easier with AVR, and will make future support of LLVM for AVR easier
- for `flash_printf()`, `flash_fprintf()`, and `flash_snprintf()` the `static inline` wrapper would have to be implemented by calling `vprintf_P()`, `vfprintf_P()` and `vsnprintf_P()` with added impedance matching. This impedance matching would add 400 B of `.text`, so instead the linker is used to create aliases
- …

sys/flash_utils: Minor bug fixes

---

.murdock.yml

This PR adds the [github merge train branch spec](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-third-party-ci-providers) to our Murdock config.
It's a prerequisite for murdock even looking at those branches.
Let's add it now, even if we don't need it.
#20051

ci: build github merge train branches with murdock [backport 2023.10]

---

.github/workflows/check-commits.yml
.github/workflows/check-labels.yml
.github/workflows/labeler.yml
.github/workflows/static-test.yml
.github/workflows/tools-buildtest.yml
.github/workflows/tools-test.yml
.murdock

These are changes required to switch merging from bors to Merge Queues.
Ideally required tests pass and we can enter it into a merge queue.
Tracking issue: #20051

ci: migrate to github merge queues [backport 2023.10]

---

boards/nucleo-f030r8/Kconfig
boards/nucleo-f030r8/Makefile.features
boards/nucleo-f030r8/include/periph_conf.h
tests/drivers/atwinc15x0/Makefile.ci
tests/drivers/cc110x/Makefile.ci
tests/drivers/nrf24l01p_ng/Makefile.ci
tests/pkg/cryptoauthlib_internal-tests/Makefile.ci

This enables the SPI and I2C feature for the `nucleo-f030r8`. The SPI configuration was already provided, but the feature never exposed. The common PB8/PB9 I2C config is used to for I2C.
The two peripheral test apps or the peripheral selftesting shield can be used. I tested it with the selftesting shield.
None

boards/nucleo-f030r8: enable SPI and I2C

---

boards/nucleo-wl55jc/include/periph_conf.h

The macro `ARDUINO_SPI_D11D12D13` is used to refer to the SPI bus on the pins D11/D12/D13 on Arduino UNO compatible boards. For all Nucleo64 boards this is `SPI_DEV(0)`, but for this board `SPI_DEV(0)` is internally connected to the radio. Instead `SPI_DEV(1)` is connected to the correct pins. This provides the macro explicitly in `periph_conf.h`, which takes preference over the fallback in `boards/common/nucleo64` when provided.
Check the lines above the macro in `periph_conf.h` and confirm that the GPIO pins match the Arduino pin names.
Or run the peripheral self test using the shield. With this, it hopefully passes.
None

boards/nucleo-wl55jc: Fix Arduino SPI bus

---

cpu/native/periph/timer.c
cpu/native/syscalls.c

While debugging https://github.com/RIOT-OS/RIOT/pull/18977#issuecomment-1764258356 it became obvious that the `periph_timer` in `native` is broken and issues early IRQs. This replaces the use of `setitimer` that cannot use a monotonic clock source with `timer_settime()`.
I have some non-publishable code that tests if the time an ISR fires in terms of `timer_read()` is no earlier than the time expected. This occasionally triggered with `master`, but I didn't see any of these issues anymore with this PR. I guess I should revive my PR to spice up the periph timer tests and add a polished version of this and let this run for an hour or two.
The tests ins `tests/periph/timer*` should still succeed on `native`. (They do for me in a container running `riot/riotbuild`).
Found while debugging …

cpu/native: fix bug in periph_timer [backport 2023.10]

---

boards/common/nucleo64/include/arduino_iomap.h
boards/p-nucleo-wb55/Kconfig
boards/p-nucleo-wb55/Makefile.features
boards/p-nucleo-wb55/include/arduino_iomap.h

This provides the features:
- `arduino_i2c`
- `arduino_spi`
- `arduino_uart`
A second commit is sneaked in that fixes doc.
The selftest shield app should now run more tests. But also code review should be sufficient.
None

boards/p-nucleo-wb55: provide Arduino features

---

tests/periph/selftest_shield/main.c

The R-2R resistor ladder dac --> ADC test was disabled due to a bug in the v0.1 version of the shield. Since this has been fixed in v0.2 and v0.3 of the shield, it can be re-enabled.
The comment regarding the high accuracy of the resistor is dropped, as v0.3 has been ordered with cost efficient resistors rather than with accurate ones. As a result, the tolerance for error has been increased to 10%. This quite a bit more lax than I have hoped for, but false positives would be something to avoid.
A second commit drops the abuse of `DEBUG()` for more detailed error messages. Instead, now `make DETAILED_OUTPUT=1 flash test-with-config` will be sufficient now to get detailed output.
Running the test on a board with the features `periph_adc`, `periph_i2c`, `arduino_analog`, `arduino_i2c`, and …

tests/periph/selftest_shield: re-enable ADC test

---

drivers/at/at.c
drivers/include/at.h
tests/drivers/at/main.c
tests/drivers/at/tests-with-config/sneaky_urc.py

Fix URCs being occasionally mistaken for command response.  
Some DCEs (e.g. LTE modules from uBlox) define a grace period where URCs are
guaranteed NOT to be sent as the time span between:
- the command EOL character reception AND command being internally accepted
- the EOL character of the last response line
As follows, there is an indeterminate amount of time between:
- the command EOL character being sent
- the command EOL character reception AND command being internally accepted,
i.e. the begin of the grace period  
In other words, we can get a URC (or more?) just after issueing the command 
and before the first line of response. The net effect is that such URCs will 
appear to be the first line of response to the last issued command.
The current solution is to skip characters that …

drivers/at: fix URC collision with command response

---

tests/periph/selftest_shield/main.c

- fix a copy-paste error (`TIMER_FREQ_UART_TEST` was used in the SPI test, but that should be `TIMER_FREQ_SPI_TEST`)
- use 400 kHz as slow SPI frequency, as faster STM32 MCUs just cannot divide the APB clock down to 100 kHz
- when detailed output is enabled, print the SPI clock in addition to the SPI mode to ease figuring out what went wrong
- only have one `FAILURE` message for a too fast byte transfer per check, rather than per transmitted byte, to reduce the noise
- work around a bug of `periph_timer` on STM32 by reducing the clock speed of the timer for the SPI test
This should fix the failure of the test on the Nucleo-F446RE.
None

tests/periph/selftest_shield: improve SPI test

---

drivers/at24cxxx/include/at24cxxx_defines.h

Those are 512 Byte / 1024 Byte EEPROMS, [Datasheet](https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/20006350A.pdf)
`tests/drivers/mtd_raw` on a board with `at24cs08` passes the self-test
```
2023-11-16 14:24:48,310 - INFO # Manual MTD test
2023-11-16 14:24:48,324 - INFO # init MTD_0… OK (1 kiB)
2023-11-16 14:27:12,239 - INFO # > test 0
2023-11-16 14:27:12,239 - INFO # 
2023-11-16 14:27:12,239 - INFO # [START]
2023-11-16 14:27:12,286 - INFO # [SUCCESS]
2023-11-16 14:30:31,510 - INFO # > info
2023-11-16 14:30:31,511 - INFO # 
2023-11-16 14:30:31,511 - INFO # mtd devices: 1
2023-11-16 14:30:31,511 - INFO #  -=[ MTD_0 ]=-
2023-11-16 14:30:31,511 - INFO # sectors: 64
2023-11-16 14:30:31,512 - INFO # pages per sector: 1
2023-11-16 14:30:31,526 - INFO # …
```

drivers/at24cxxx: add defines for AT24CS04 & AT24CS08

---

boards/common/blxxxpill/include/board_common.h
boards/nucleo-f103rb/Makefile.include
cpu/stm32/cpu_init.c
cpu/stm32/include/periph/f1/periph_cpu.h
cpu/stm32/periph/i2c_2.c

The RIOT cpu stm32 peripheral i2c_2 is involved, a bug was reported that undefined bits were being read and reassigned to a register, that is now solved by masking those bits when modifying the register.
Testing should be performed on the stm32 cpu
Fixes #19787

cpu/stm32/periph_i2c: prevent corrupting AFIO->MAPR

---

tests/periph/selftest_shield/main.c

- Detect when the same timer is used by `ztimer` (pulled in as dependency for a peripheral driver, e.g. `periph_adc` on STM32F3) and the test application
- Try to provide a better default (e.g. `TIMER_DEV(1)` when `ztimer_periph_timer` is in use, `TIMER_DEV(0)` otherwise)
- Run the app on the `nucleo-f303re` in `master`: A hard fault is triggered during `adc_init()` due to a conflict in the use of the same `periph_timer` peripheral by the app and ztimer
- In this branch, the test will no longer hard fault, but rather fail to do `timer_init()` failing (because the board only has a single timer peripheral exposed)
None

tests/periph/selftest_shield: timer allocation conflict

---

boards/nucleo-l433rc/doc.txt

This PR adds to the `nucleo-l433rc` board documentation page:
- image, 
- MCU table with links to datasheets.
The issue was detected during working on PR #20071. 
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l433rc.html 
```
Lacks in documentation detected during works on PR #20071

boards/nucleo-l433rc: doc update - image and MCU table

---

boards/common/stm32/include/cfg_timer_tim2_tim15_tim16.h
boards/nucleo-f303re/include/periph_conf.h

As trivial as the title says. The common timer config was tweaked a bit as the `.rcc_mask` was named a bit different on STM32F3.
<details><summary><code>$ make BOARD=nucleo-f303re flash test -j -C tests/periph/timer</code></summary>
```
Building application "tests_timer" for "nucleo-f303re" with MCU "stm32".
"make" -C /home/maribu/Repos/software/RIOT/master/pkg/cmsis/ 
"make" -C /home/maribu/Repos/software/RIOT/master/boards/nucleo-f303re
"make" -C /home/maribu/Repos/software/RIOT/master/core
"make" -C /home/maribu/Repos/software/RIOT/master/core/lib
"make" -C /home/maribu/Repos/software/RIOT/master/cpu/stm32
"make" -C /home/maribu/Repos/software/RIOT/master/drivers
"make" -C /home/maribu/Repos/software/RIOT/master/sys …
```

boards/nucleo-f303re: add more timers

---

drivers/include/pcf857x.h
drivers/pcf857x/pcf857x.c
tests/periph/selftest_shield/Makefile
tests/periph/selftest_shield/main.c

While debugging the I2C bug on STM32F1, I found the output of the test application lacking. This addresses this by using `tiny_strerror()` to print the error codes indicating what went wrong (not only for pcf857x, but for every other initialization call as well).
In order to make use of this, the `pcf857x` driver was updated to return negative errno codes. This also as the advantage to provide more details on what specifically went wrong when the I2C communication fails, rather than just a single I2C error code.
Run the test on a board without the peripheral selftest shield attach. Upon initialization of the PCF587x chip the test should fail with a meaningful error message.
```
~/Repos/software/RIOT/master/tests/periph/selftest_shield % make BOARD=nucleo-l152re flash test-with-config -j …
```

tests/periph/selftest_shield: Improve error output

---

sys/include/random.h

Users reading https://doc.riot-os.org/group__sys__random.html have no clue that there is auto-initialization, let alone how to assess it.
Read the produced docs.

sys/rng doc: Point to auto initialization

---

cpu/nrf51/periph/i2c.c

The `i2c_read_bytes()` and `i2c_write_bytes()` function return the number of bytes written / read, instead of `0` as the API contract says. This fixes the issue.
Combined with https://github.com/RIOT-OS/RIOT/pull/20106 the peripheral selftest app should now get past the `pcf857x` driver initialization. It still fails (hangs) during the SPI test, but at least the I2C part now works.
None

cpu/nrf51: fix periph_i2c driver

---

boards/nrf51dk/Kconfig
boards/nrf51dk/Makefile.features
boards/nrf51dk/include/arduino_iomap.h
boards/nrf51dk/include/periph_conf.h

- add ADC channel mapping and provide `periph_adc` feature
- add Arduino I/O mapping for GPIO pins, ADC channels, I2C and SPI bus
The peripheral selftesting shield can help here
None

boards/nrf51dk: add ADC and Arduino features

---

Makefile.include

This changes a Makefile info into a warning because the latter goes to stderr, whereas the former broke the output of `make info-boards-supported`
* Go to tests/build_system/external_board_native
* `BOARDS=samr21-xpro make info-boards-supported | wc`
Before this patch, this shows `2       8      69` (which is the info message "Using BOARDSDIR is deprecated use EXTERNAL_BOARD_DIRS instead"). After,  it shows `1 0 1`, which is the same as an empty output. (It may show more things through stderr now than before).
This helps riot-wrappers' CI work without workarounds, as tracked in (or experimented with in) https://github.com/RIOT-OS/rust-riot-wrappers/pull/68

makefile: Don't $(info) when the output can break info-boards-supported

---

boards/same54-xpro/Kconfig
boards/same54-xpro/Makefile.features
boards/same54-xpro/Makefile.include
boards/same54-xpro/include/periph_conf.h
cpu/sam0_common/include/periph_cpu_common.h
cpu/sam0_common/periph/freqm.c
cpu/samd5x/cpu.c
cpu/samd5x/include/periph_cpu.h
dist/tools/doccheck/generic_exclude_patterns
drivers/include/periph/freqm.h
drivers/periph_common/Kconfig
kconfigs/Kconfig.features
tests/periph/freqm/Makefile
tests/periph/freqm/README.md
tests/periph/freqm/main.c

This PR adds a peripheral driver for frequency meter (FREQM). Tested with SAM E54 XPLAINED PRO EVALUATION KIT (ATSAME54P20A microcontroller).
I think I have access to some other boards to test the driver in the near future.
As the FREQM needs a reference clock to measure the frequency of another clock this test uses two internal clocks. The slower internal clock is used as reference to measure the faster internal clock.
The test can be invoked with:
make -C tests/periph/freqm flash
Expected result (via serial):
main(): This is RIOT! (Version: <INSERT VERSION HERE>)
FREQM peripheral driver test
Measured Clock Frequency: <MEASURED CLOCK FREQUENCY> Hz

drivers/include/periph: add FREQM peripheral driver

---

drivers/include/mtd.h

The commit fixes the order of entries in the MTD pointer XFA `mtd_dev_xfa` according to their index by using the index as the priority in the XFA.
Since PR #19465, the pointers to existing MTD devices `mtd0`, `mtd1`, ... `mtd<n>` are hold in the MTD pointer XFA `mtd_dev_xfa`. The order of these pointers in the XFA should correspond to their index so that `mtd_dev_xfa[i]` gives `mtd<i>` which points to the i-th MTD. For that purpose the `idx` parameter of the `MTD_XFA_ADD` macro has to be used as priority.
Compile 
```
BOARD=same54-xpro make -j8 -C tests/sys/vfs_default/
```
with and without this PR. Without this PR, command
```
nm -s tests/sys/vfs_default/bin/same54-xpro/tests_vfs_default.elf | sort | grep "mtd[0-9]"
```
will give
```
0001039c T mtd1
000103a0 T mtd0
000103a4 T mtd2
``` …

drivers/mtd: fix the order of entries in the MTD pointer XFA `mtd_dev_xfa`

---

examples/gcoap/Makefile.ci
sys/net/gnrc/sock/udp/gnrc_sock_udp.c

`sock_udp_recv_buf_aux()` sometimes will return `-ETIMEDOUT` before the given timeout has expired (e.g. after 28798µs instead of 160000µs).
This messes with many assumptions and breaks protocols that rely on the timeout.
Until we have a proper fix, add this workaround.
`tests/net/gcoap_fileserver` should now be more reliable even without the increased retries.

sock/udp: work around gnrc_sock_recv() returning early timeout

---

boards/p-nucleo-wb55/doc.txt

This PR updates/cleans/enhance `p-nucleo-wb55' boards documentation page:
- move Overview section at the top,
- add section concerning `cpy2remed' PROGRAMMER (tested on real hardware),
- enhance section concerning STDIO/RIOT OS console access (Issue #17453)
- change Doxygen headings from `=======` and `--------` to `##` and `###` .
```
make doc
xdg-open doc/doxygen/html/group__boards__p-nucleo-wb55.html
```
Issue #17453

boards/p-nucleo-wb55: documentation update

---

sys/net/gnrc/netif/gnrc_netif.c

If a netif fails to init, we only get the errno. Also print which interface failed to init.

sys/net/gnrc/netif: print which netif failed to init

---

boards/p-nucleo-wb55/Kconfig
boards/p-nucleo-wb55/Makefile.features
boards/p-nucleo-wb55/doc.txt
boards/p-nucleo-wb55/include/periph_conf.h

This PR adds to the Nucleo-wb55 PWM configuration.
Flash the board using `tests/periph/pwm` program. Check if you could, for example, change LED 
intensity using PWM. 
None.

boards/p-nucleo-wb55: add PWM configuration

---

doc/doxygen/riot.doxyfile
doc/doxygen/src/roadmap.md

This moves the road map from the wiki (which has little visibility) to a place where it is visible.
While technically this adds hurdles to changes (PR instead of just-edit), practically this should be better because people know the process, and experience shows that people are hesitant to edit the wiki b/c they can't get it ACKed.
* Look at the doc build output.
(This was discussed during the 2023.11 VMA)
We can start shaping this up more as a collection of topics and people's/groups' concrete sub-roadmaps. This PR just increases the roadmap's visibility, and increases the visibility of roadmap adjustments.

doc: Move roadmap in from the wiki

---

doc/doxygen/riot.doxyfile
doc/doxygen/src/roadmap.md

This puts details to, and answers questions currently open in, the road map around 802.15.4 security.
While I won't fix that alone, I think it makes sense to place myself as the person coordinating this.
This is an example of the changes in the direction discussed during the 2023.11 VMA, and a follow-up to https://github.com/RIOT-OS/RIOT/pull/20122
Depends on https://github.com/RIOT-OS/RIOT/pull/20122

doc: Extend and take responsibility for 802.15.4 security roadmap

---

pkg/nanopb/Makefile

simply bumps the version of nanopb to `0.4.8`
`tests/pkg/nanopb` runs as it should on `native`
no PR related

Bumb nanopb to 0.4.8

---

doc/doxygen/src/roadmap.md

- drop completed tasks
- drop tasks that make no sense anymore (e.g. cleanup up MIPS, as MIPS was dropped or improving xtimer, as it was superseded by ztimer)
Read the markdown and the generated HTML (see link posted by Murdock).
None

doc: clean up roadmap

---

core/mutex.c
cpu/sam0_common/periph/adc.c

The mutex is already locked in `adc_continuous_begin()`, so don't try to lock it again in `adc_continuous_sample()`.
`tests/periph/adc_continuous` no longer hangs.

cpu/sam0_common: fix adc_continuous_sample()

---

core/msg.c
sys/include/net/gnrc/ipv6.h
sys/include/net/gnrc/pktdump.h
sys/include/net/gnrc/sixlowpan/config.h
sys/include/net/gnrc/udp.h
sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c
sys/net/gnrc/network_layer/sixlowpan/gnrc_sixlowpan.c
sys/net/gnrc/pktdump/gnrc_pktdump.c
sys/net/gnrc/transport_layer/udp/gnrc_udp.c

I saw messages sent to the IPv6 thread being dropped.
I think it could happen that an address does not become valid for that reason.
So I increased `CONFIG_GNRC_IPV6_MSG_QUEUE_SIZE_EXP` and a stack overflow happened.
This is not supposed to happen for a `CONFIG_` variable. 
- internal application
```
2023-10-19 17:19:17,118 # queue_msg(): Cannot send message 0x2000a7b0 to message queue of thread 4 is full (or there is none)
2023-10-19 17:19:17,148 # queue_msg(): Cannot send message 0x2000a7b0 to message queue of thread 4 is full (or there is none)
2023-10-19 17:19:17,149 # queue_msg(): Cannot send message 0x2000a7b0 to message queue of thread 4 is full (or there is none)
2023-10-19 17:19:17,422 # queue_msg(): Cannot send message 0x2000a7b0 to message queue of thread 4 is full (or there is …
```

gnrc: make message queues static

---

.github/workflows/labeler.yml

Due to the [breaking changes](https://github.com/actions/labeler#breaking-changes-in-v5) in the `labeler` github action we need to adapt our config.  I will also set the major version since deprecation messages would seem preferable to failing actions.
Labeler action passes now
[Example of the issue](https://github.com/RIOT-OS/RIOT/actions/runs/7087797156/job/19290204707?pr=20135)

Fix labeler action

---

drivers/sdmmc/sdmmc_sdhc.c

Otherwise this won't compile if there is no `SDHC1`

drivers/sdmmc: fix placement of #endif

---

tests/sys/psa_crypto_se/Makefile

This PR should pass the CI, unlike most CI runs recently.
None

tests/sys/psa_crytpo_se: disable test on esp32-wroom-32

---

tests/net/gnrc_sixlowpan_frag_sfr_congure_impl/Makefile

This test sporadically failed on multiple machines compiled with both GNU and LLVM toolchains. To not waste more CI time by sporadically failing unrelated CI runs, let's disable the test for now.
The test should no longer be run automatically in the CI.
None

tests/net/gnrc_sixlowpan_frag_sfr_congure_impl: disable test on native

---

drivers/include/periph/timer.h
drivers/periph_common/Kconfig.timer
drivers/periph_common/timer.c
kconfigs/Kconfig.features
makefiles/features_modules.inc.mk
tests/periph/timer/Kconfig
tests/periph/timer/Makefile
tests/periph/timer/main.c
tests/periph/timer/tests/01-run.py

Allow accessing supported timer frequencies with a dedicated API.
This API needs to be implemented per platform and is available with
the feature `periph_timer_query_freqs`.
The test in `tests/periph_timer` has been extended to make use of the new API to increase test coverage.
Implementations:

drivers/periph_timer: add timer_query_freqs()

---

boards/esp32s3-usb-otg/doc.txt

This PR provides a small fix in the documentation for the `esp32s3-usb-otg` board.
`make doc` and check the documentation.

boards/esp32s3-usb-otg: fix the table of contents in documentation

---

boards/esp32-ethernet-kit-v1_0/Makefile.include
boards/esp32-mh-et-live-minikit/Makefile.include
boards/esp32-olimex-evb/Makefile.include
boards/esp32-ttgo-t-beam/Makefile.include
boards/esp32-wemos-lolin-d32-pro/Makefile.include
boards/esp32-wroom-32/Makefile.include
boards/esp32-wrover-kit/Makefile.include
boards/esp32c3-devkit/Makefile.include
boards/esp32s2-devkit/Makefile.include
boards/esp32s2-lilygo-ttgo-t8/Makefile.include
boards/esp32s3-devkit/Makefile.include

This adds a TTY board filter to only select TTYs that match the attributes of the correct TTY interface. When using `make flash` or `make term` with `MOST_RECENT_PORT=1`, RIOT should now select relatively robustly the most recently connected ESP32 Ethernet Kit board, even with other TTYs present.
Connect a bunch of boards including at least one Ethernet Kit board and run
```sh
make MOST_RECENT_PORT=1 BOARD=esp32-ethernet-kit-v1_2 BUILD_IN_DOCKER=1 -j flash -C examples/default
```
This should now pick the most recently connected Ethernet Kit board. It may pick a different board when another Dual RS232-HS USB<-->UART adapter is connected, though. But those are relatively rare as integrated UART<-->USB converters, as they are (unless they are used to bit-bang JTAG) an overkill for a simple …

boards/esp32*: add TTY board filter

---

cpu/msp430/include/f2xx_g2xx/msp430_regs.h
cpu/msp430/include/msp430_regs_common.h
cpu/msp430/include/x1xx/msp430_regs.h
cpu/msp430/ldscripts/msp430_common.ld
cpu/msp430/periph/gpio.c
cpu/msp430/periph/uart_usart.c
cpu/msp430/periph/uart_usci.c

Previously sometimes `msp_` was used as prefix, sometimes `msp430_`. This makes the naming consistent.
This only changes type names, not semantics. The generated binaries should be the same, except for debug symbols.
None

cpu/msp430: consistently use msp430 prefix in names

---

sys/net/gnrc/netif/gnrc_netif_device_type.c

AFAIU the `gnrc_sixloenc` enables 6lo encoding on ethernet.
This can be useful for very slow busses, where we want to reduce traffic as much as possible.
I noticed that GNRC would still perform duplicate address detection on startup - this was because the 6LN flag was not set yet. 
I enabled
```
USEMODULE += gnrc_sixloenc
CFLAGS += -DCONFIG_GNRC_IPV6_NIB_SLAAC=1
CFLAGS += -DCONFIG_GNRC_IPV6_NIB_NO_RTR_SOL=1
CFLAGS += -DCONFIG_GNRC_IPV6_NIB_ARSM=0
```
and now get serene silence on the bus if there is no traffic.

net/gnrc/netif: set 6LN flag for ethernet if gnrc_sixloenc is used

---

makefiles/arch/riscv.inc.mk

This fixes issues with `make compile-commands`, as this by default generates clangd/LLVM compatible flags. Without `TARGET_ARCH_LLVM` exported, this will fall back to `TARGET_ARCH`, which is different for LLVM and GCC.
Run e.g. `make BOARD=hifive1b -C examples/default compile-commands` and open the `main.c` in that example with an LSP enabled editor (e.g. vim/nvim + ALE or vs code). In `master` it won't even dare linting due to `-target riscv-none-elf` not being technically correct. With this PR `-target riscv32-none-elf` is used instead.
None

makefiles/arch/riscv.inc.mk: Always provide TARGET_ARCH_LLVM

---

pkg/flashdb/Makefile
pkg/flashdb/patches/0001-remove-example-fdb_cfg.h.patch

Update to the latest version. Incorporate upstream patch by @fzi-haxel to prepare for 64bit platforms.
The tests are still working:
pkg/flashdb_vfs
pkg/flashdb_mtd

pkg/flashdb: bump to 2.1.0

---

cpu/kinetis/Kconfig
cpu/kinetis/Makefile.features
cpu/kinetis/include/periph_cpu.h
cpu/kinetis/periph/timer.c

Run the test provided by https://github.com/RIOT-OS/RIOT/pull/16349.
Depends on https://github.com/RIOT-OS/RIOT/pull/16349 and includes the first commit of it.

cpu/kinetis: implement periph_timer_query_freqs

---

cpu/cortexm_common/include/cpu.h
cpu/stm32/include/cpu_conf.h

See [1] for details. (archive.org backup at [2]).
[1]: https://cliffle.com/blog/stm32-wfi-bug/
[2]: https://web.archive.org/web/20231205101603/https://cliffle.com/blog/stm32-wfi-bug/
See https://github.com/RIOT-OS/RIOT/issues/13918
Fixes https://github.com/RIOT-OS/RIOT/issues/13918 
Fixes https://github.com/RIOT-OS/RIOT/issues/14015

cpu/cortexm_common: work around bug on WFI for STM32

---

cpu/nrf5x_common/periph/uart.c

The functions `uart_poweron()`, `uart_poweroff()` and  `uart_mode()` can share code between the UART (UART without EasyDMA) and UARTE (UART with EasyDMA) implementations, so let's do that.
UART should still work including switching modes - best checked with a logic analyzer attached to verify the output - for:
Follow up to / made possible by https://github.com/RIOT-OS/RIOT/pull/20102

cpu/nrf5x_common: clean up UART implementation

---

tests/unittests/tests-hashes/tests-hashes-sha512.c

Incorrect use of `sizeof` for string length in test `test_hashes_sha512_hash_update_twice`.
`static const char *teststring` is a pointer, therefore `sizeof(teststring)` returns the pointer size instead of the intended string length. ~~This PR uses `strlen` instead of `sizeof` to fix this. Alternatively, we could change the type of the string to `static const char teststring[]`.~~
~~Note the subtle difference between `sizeof(char[])` and `strlen`: The former includes the null terminator, while `strlen` does not. This should not change the test behavior.~~
Edit:
This PR changes the type to `static const char teststring[]` so that `sizeof` returns the string length (including the null terminator). 
Compile and run unittests.
Note for 32-bit architectures: The test also passed before, but …

tests/unittests/tests-hashes: fix wrong string length

---

cpu/stm32/periph/i2c_2.c

cpu/stm32: fix periph_i2c for F1, F2, L1 and F4 families

---

cpu/sam0_common/periph/uart.c
drivers/include/periph/uart.h

Just like `uart_pin_tx()`/`uart_pin_rx()` we want to have a function to query the RTS/CTS pins.

cpu/sam0/uart: implement uart_pin_cts()/uart_pin_rts()

---

CONTRIBUTING.md
tests/build_system/warn_conflict/README.md

Using the wiki for docs is deprecated but we still refer to it in some places. This PR at least fixes the currently broken links to wiki pages which do not longer exist.
Hm... Check that the old links are gone and the new ones work maybe.

Fixing broken Wiki links

---

MAINTAINING.md

Since the service has been deactivated we do not longer use it.

Maintaining: remove obsolete bors section

---

boards/wemos-zero/Makefile.include
boards/wemos-zero/doc.txt

Fix flashing with `MOST_RECENT_PORT=1` by detecting the board when either in RIOT mode or in bootloader mode (which matches different USB vendor and model strings).
Support for programming with the nrf52-u2f bootloader was dropped apparently, but the documentation still recommends that over the Arduino Bootloader. This brings doc and code in sync.
```
make BOARD=wemos-zero MOST_RECENT_PORT=1 -C examples/default
```
should now succeed, even after double-pressing the reset button.
None

boards/wemos-zero: fix flashing and doc

---

cpu/esp_common/periph/flash.c
cpu/native/mtd/mtd_native.c
drivers/at25xxx/mtd/mtd.c
drivers/include/mtd.h
drivers/mtd/mtd.c
drivers/mtd_emulated/mtd_emulated.c
drivers/mtd_mapper/mtd_mapper.c
drivers/mtd_sdcard/mtd_sdcard.c
drivers/mtd_sdmmc/mtd_sdmmc.c
drivers/mtd_spi_nor/mtd_spi_nor.c
tests/drivers/mtd_mapper/main.c
tests/unittests/tests-mtd/tests-mtd.c

The old `.write()` function is only used as a fall-back if `.write_page()` is not implemented.
We can drop it.
Everything will fall back to `.write_page` now, so no user visible change.
On the driver level, `.write_page` can be much simpler than `.write` as all the common logic is handled by MTD and we can do partial writes (only write to page boundary, MTD will split up the transaction).
<details><summary>AT25xxx</summary>
```
2023-03-09 23:26:41,366 # init MTD_0… OK (128 kiB)
2023-03-09 23:26:43,208 # > test 0
2023-03-09 23:26:43,208 # [START]
2023-03-09 23:26:43,286 # [SUCCESS]
2023-03-09 23:28:20,306 # > read 0 0 32
2023-03-09 23:28:20,312 # 00000000  31  32  33  34  35  36  FF  F7  6C  69  74  74  6C  65  66  73
2023-03-09 23:28:20,318 # 00000010  2F  E0  00  10  00  00  02  00  00 …
```

mtd/*: drop .write() if .write_page() is implemented

---

pkg/libcose/init/init.c

The file `pkg/libcose/init/init.c` is just missing the include of  `pkg/libcose/include/cose/crypto/riot.h` to know about `AUTO_INIT_PRIO_MOD_LIBCOSE`.
`CFLAGS+=-DCONFIG_AUTO_INIT_ENABLE_DEBUG=1 USEPKG+=libcose BOARD=same54-xpro make -C examples/suit_update` compiles with this fix.

pkg/libcose: fix auto_init compilation

---

tests/periph/uart/main.c

Often when interacting with other devices they might expect a different line ending than `\n` used by RIOT.
Since especially the uart test might be used in an explorative way, add a way to configure the line ending at run-time.

tests/periph/uart: allow to set line ending

---

dist/tools/edbg/edbg.sh

Likely a change in the command line interface of EDBG broke the `make reset` integration. This adds the missing flag.
Note: Since the binary is build on demand with our build system, we
can in fact rely on every using the same version of EDBG. Hence,
we don't need to be backwards compatible with the flag.
In one terminal session run
```
make -C examples/default BOARD=samr21-xpro flash term
```
While connected to the RIOT shell, run
```
make -C examples/default BOARD=samr21-xpro reset
```
With `master`, the board won't reboot. With this PR, it will reboot on the `make reset` command again.
None

tools/edbg: fix `make reset`

---

drivers/include/mtd.h
drivers/include/mtd_sdmmc.h
drivers/mtd/mtd.c
drivers/mtd_sdmmc/Kconfig
drivers/mtd_sdmmc/mtd_sdmmc.c
pkg/fatfs/fatfs_diskio/mtd/mtd_diskio.c
pkg/lwext4/fs/lwext4_fs.c

For some reason the `.erase_sector` is a no-op by default when there is a perfectly cromulent implementation available.
Always enable it to comply with the MTD API.
I run `tests/drivers/mtd_raw` on `same54-xpro`
```
2023-12-13 17:00:25,934 - INFO # Manual MTD test
2023-12-13 17:00:25,937 - INFO # init MTD_0… OK (8 MiB)
2023-12-13 17:00:25,940 - INFO # init MTD_1… OK (256 byte)
2023-12-13 17:00:26,150 - INFO # init MTD_2… OK (15223 MiB)
2023-12-13 17:00:41,721 - INFO # > test 2
2023-12-13 17:00:41,722 - INFO # 
2023-12-13 17:00:41,726 - INFO # [START]
2023-12-13 17:00:41,862 - INFO # tests/drivers/mtd_raw/main.c:382 => failed condition
```
```
2023-12-13 17:07:07,125 - INFO # Manual MTD test
2023-12-13 17:07:07,128 - INFO # init MTD_0… OK (8 MiB)
2023-12-13 17:07:07,131 - INFO # init …
```

drivers/mtd_sdmmc: always enable the erase function

---

cpu/sam0_common/include/mtd_sam0_sdhc.h
drivers/include/mtd_emulated.h
drivers/include/mtd_flashpage.h
drivers/include/mtd_sdcard.h
drivers/include/mtd_sdmmc.h
drivers/include/sdcard_spi.h

This PR provides some small changes in documentation to improve the consistency of documentation for MTD devices.
While fixing PR #19786, I realized that the list of MTD devices is inconsistent: 
- Some entries use "MTD wrapper for ..."
- Some entries use "mtd wrapper for ..."
- Other entries just use "xxxx MTD"
- SAM0 SDHC is just listed as file
- The MTD wrapper for emulated MTD devices isn't listed at all but part of the MTD main page by acciedent
This PR tries to make the list a bit more consistent to improve its readability.
I'm a bit unsure about Serial NOR flash which is also just a MTD.
Generae the doc and check the output.

drivers/mtd: improve doc consistency

---

boards/same54-xpro/Kconfig
boards/same54-xpro/Makefile.features
boards/same54-xpro/include/board.h
boards/same54-xpro/include/gpio_params.h
boards/same54-xpro/include/periph_conf.h

On EXT1 the pins for RTS and CTS are accessible, so configure them.

boards/same54-xpro: configure pins for UART HW flow control & ethernet LED

---

Makefile

There is no target similar to `make help` available when calling `make` from the RIOT base directory, although there are several useful targets that are supposed to be called from there. Instead of adding a new `help` target, this PR lists the available targets manually in the `welcome` message.
With these changes, `make` or `make all` from the RIOT base directory gives:
```
Welcome to RIOT - The friendly OS for IoT!
You executed 'make' from the base directory.
Usually, you should run 'make' in your application's directory instead.
Please see our Quick Start Guide at:
https://doc.riot-os.org/getting-started.html
You can ask questions or discuss with other users on our forum:
https://forum.riot-os.org
Available targets for the RIOT base directory include: …
```

make all: document targets for RIOT base module

---

pkg/lwip/contrib/_netif.c
sys/include/net/netif.h
sys/net/gnrc/netif/_netif.c

We don't modify the contents of `netif`, so the pointer can be `const`.
Code still compiles.

sys/net/netif: constify netif access

---

sys/include/net/nanocoap.h
tests/unittests/tests-nanocoap/tests-nanocoap.c

`coap_get_uri_query()` takes no size parameter and assumes the buffer supplied by the caller will be sufficiently large.
This is a huge foot-gun and we can actually supply the max length to the underlying `coap_opt_get_string()` function, so just do that.
Also that function is not very useful. It's nice for debugging, but when actually wanting to obtain the query parameters, we certainly don't want to first convert them into a string only to then parse the string. Rename the function to `coap_get_uri_query_string()` to better reflect what it does and to make the name available for a more useful query iterator function. 
The `tests-nanocoap` test in `tests/unittests` still works. 
includes #20195 because I don't like merge conflicts.

nanocoap: defuse footgun in coap_get_uri_query()

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

I forgot to take `GNRC_IPV6_STATIC_LLADDR` into account when doing the `gnrc_ipv6_nib_iface_up()`/`gnrc_ipv6_nib_iface_down()` changes.
When the interface goes down, we remove all link-local addresses - but when it goes up again we did not add back the static address.
Fix this by moving `_add_static_lladdr()` to `gnrc_ipv6_nib_iface_up()`.
Enable `GNRC_IPV6_STATIC_LLADDR` e.g. in `examples/gnrc_networking`. I tested this on `same54-xpro` where I can unplug the Ethernet cable to make the link go down.
```
2023-12-19 18:41:43,176 - INFO # Iface  5  HWaddr: FC:C2:3D:22:12:3B  Link: up 
2023-12-19 18:41:43,180 - INFO #           L2-PDU:1500  MTU:1500  HL:64  RTR  
2023-12-19 18:41:43,182 - INFO #           RTR_ADV  
2023-12-19 18:41:43,185 - INFO #           Source address length: 6 …
```

gnrc/ipv6/nib: fix GNRC_IPV6_STATIC_LLADDR when link state changes

---

makefiles/pseudomodules.inc.mk
sys/include/net/gnrc/ipv6/nib/conf.h
sys/net/gnrc/Makefile.dep

When mixing 6lo interfaces with 'classic' IPv6 interfaces we would always see strange behavior in RIOT. E.g. if we enable `gnrc_ipv6_default` together with an Ethernet interface and a IEEE 802.15.4 interface, the node would get a global address on the Ethernet interface but seemingly can't be reached via that address. (After manually enabling `CONFIG_GNRC_IPV6_NIB_SLAAC` and `CONFIG_GNRC_IPV6_NIB_ARSM`)
This is because the 6lo optimizations would always get turned on globally when the `gnrc_ipv6_nib_6ln` module is in use, disregarding what other interfaces might be present.
In this case the `CONFIG_GNRC_IPV6_NIB_NUMOF` would get set to 1, leading to no space being left for any neighbor's address, other than the default router, so address resolution would always fail.
Fix this by …

gnrc_ipv6_nib: fix config for mixed 6lo/classic setup

---

pkg/micropython/Makefile

As part of [the effort](https://github.com/RIOT-OS/RIOT/pull/20154) to make RIOT 64 bit ready various data types in RIOT and in the packages needs to be updated. This PR includes a patch by @fzi-haxel to the Micropython repository we're using to make this package 64 bit ready.
`make -C examples/micropython all term`
and run your favorite (micro)python script on RIOT.
Prerequisite for #20154.

pkg: micropython: bump version

---

examples/wasm/iwasmt.c

wasm: fix the memory leak: wasm_buf
Signed-off-by: zengwei zengwei1@uniontech.com

wasm: fix the memory leak: wasm_buf

---

boards/nucleo-l452re/doc.txt

This PR adds to the `nucleo-l452re` board documentation page MCU table with links to datasheets.
The issue was detected during working on PR #20071. 
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l452re.html 
```
Detected during works on PR #20071

boards/nucleo-l452re: doc update

---

sys/include/shell.h
sys/shell/shell.c

This patch adds the missing NULL terminator to the argv passed to shell command handlers. Without it, Newlib's getop() was intermittently causing hardfaults. Closer inspection of NewLib's code revealed that it relies in this NULL termination. ANSI-C also requires it of the argv passed to main().
Also included are some minor improvements to the documentation.
For me `getopt()` no longer causes hardfaults. Also code in shell.c now does what the doc in shell.h advertises that it does.
- I suspect the bug was introduced in PR #12085, but I have not confirmed
- I suspect that this originally worked when argv/argc functionality was introduced in PR #760, but have not confirmed

sys/shell: fix getopt() support

---

tests/build_system/test_tools/Makefile

The test appears to expect the 'classic' `native` output. 
CI should work again.
#20172

tests/build_system/test_tools: use `native` terminal

---

pkg/fatfs/fatfs_vfs/fatfs_vfs.c

fatfs_vfs: fix the Memory leak: work
Signed-off-by: zengwei zengwei1@uniontech.com

fatfs_vfs: fix the Memory leak: work

---

examples/dtls-sock/dtls-client.c

This PR adds `sock_udp_close()` in the error paths, as otherwise the stack allocated sock structure gets out of scope while still being registered to the network stack. This fixes a crash when running both server and client on the same device, which triggers `credman_add()` to fail due to insufficient space.
Run the example app and start both server and client. On AVR I was able to trigger a blowing assertion on the second try to use the client.
Found while testing https://github.com/RIOT-OS/RIOT/pull/20196

examples/dtls-sock: fix error handling in client

---

examples/dtls-sock/Makefile
examples/dtls-sock/Makefile.ci

Minor change:
Remove the unnecessary `FEATURES_REQUIRED += arch_32bit` filter from the dtls-sock example.  
(Which the similar dtls-echo example also does not have.)
Test the dtls-sock example with non 32-bit boards.
***DISCLAIMER: I only compiled the example for all boards. I don't have an 8-bit board with enough memory to test this. If someone could test this, I would appreciate it.***

examples/dtls-sock: Enable non 32-bit architectures

---

boards/nucleo-f439zi/doc.txt
boards/nucleo-l031k6/doc.txt
boards/nucleo-l073rz/doc.txt
boards/nucleo-l432kc/doc.txt
boards/nucleo-l476rg/doc.txt
boards/nucleo-l552ze-q/doc.txt
cpu/stm32/periph/gpio_ll_irq.c

In PR #20207 @mguetschow point out typo "or RAM" instead of "of RAM"  ... this typo appears in some
nucleo boards doc as well one other comment.
This PR fixes this typo.
_**Happy New Year for all RIOT OS users and developers!**_
```make doc``` and see if all pages are generated properly.
None

treewise: typo "or RAM"

---

boards/native/Makefile.include
makefiles/tests/tests.inc.mk
tests/build_system/test_tools/Makefile
tests/periph/rtt_min/Makefile
tests/rust_libs/Makefile
tests/sys/congure_reno/Makefile
tests/sys/congure_test/Makefile
tests/sys/shell/Makefile
tests/sys/shell_ble/Makefile
tests/sys/shell_lock/Makefile
tests/turo/Makefile

Always use the `native` terminal for the automatic tests when using the `native` board.
The affected tests should still succeed on `native`.
<details><summary>tests/sys/log_color on native</summary>
```
% make test
r
/home/benpicco/dev/RIOT/tests/sys/log_color/bin/native/tests_log_color.elf tap0 
READY
s
START
main(): This is RIOT! (Version: 2024.01-devel-461-g5898c)
Logging value '42' and string 'test'
Logging value '42' and string 'test'
Logging value '42' and string 'test'
Logging value '42' and string 'test'
{ "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 436 }]}
{ "threads": [{ "name": "main", …
```

makefiles/tests/tests.inc.mk: use native term for tests

---

CODEOWNERS

This drops people who have not contributed to RIOT (including, most importantly, reviews) for at least a year.
For contributors it is a bit annoying to have a long list of assigned reviewers, but none of them will ever show up to do the review. This is especially true for new contributors who don't know which of the reviewers are active which are ["Karteileichen"][1].
[1]: https://de.wikipedia.org/wiki/Karteileiche
Let's see if any of the removed persons starts to scream in the next four weeks. If not, I guess it is safe to remove them.
None

CODEOWNERS: clean up

---

drivers/mtd_flashpage/mtd_flashpage.c

Some time ago I noticed that the mtd_flashpage driver was not writing the size of a full block (`FLASHPAGE_WRITE_BLOCK_SIZE`) when it could be, on unaligned access.
It was only writing `FLASHPAGE_WRITE_BLOCK_ALIGNMENT`.
So this PR is just a tiny performance improvement.
That case even happens in the test `tests/drivers/mtd_flashpage`.
And with his change it still passes on `same54-xpro`.
```
2023-12-13 00:07:20,959 # START
2023-12-13 00:07:20,967 # main(): This is RIOT! (Version: 2024.01-devel-360-ga5be0-pr/mtd_flashpage_improve_write_page)
2023-12-13 00:07:22,206 # .....
2023-12-13 00:07:22,207 # OK (5 tests)
2023-12-13 00:07:22,213 # { "threads": [{ "name": "main", "stack_size": 1536, "stack_used": 448 }]}
```

drivers/mtd_flashpage: improve _write_page

---

sys/psa_crypto/psa_key_slot_mgmt/psa_crypto_slot_management.c

Building any PSA Crypto example with `CONFIG_PSA_ASYMMETRIC_KEYPAIR_COUNT=1` and `CONFIG_PSA_SINGLE_KEY_COUNT=1` results in a compile-time error on `master` due to the combination of preprocessor ifs and if-else-clauses.
This PR moves the preprocessor ifs inside the if-else-clauses, hoping that the compiler optimization will remove checks for empty branches.
1. On `master`, comment out `CFLAGS += -DCONFIG_PSA_SINGLE_KEY_COUNT=1` in `tests/sys/psa_crypto_eddsa/Makefile` (or any other test that uses asymmetric keys).
2. Build, see compile-time error.
3. Change to this branch, build, see no error.
Note that the test will not succeed with the Makefile change, but just because it actually needs a single key slot at runtime.

sys/psa_crypto: fix compile bug for certain configuration

---

sys/fmt/fmt.c
sys/include/fmt.h
tests/unittests/tests-fmt/tests-fmt.c

Hello 🦙
this adds a few new test cases to the `tests-fmt` unit tests.
The changes only apply to these functions:
* `fmt_is_digit()`
* `fmt_is_upper()`
* `fmt_is_number()`
* `fmt_byte_hex()`
* `fmt_bytes_hex()`
* `fmt_bytes_hex_reverse()`
* `fmt_hex_byte()`
* `fmt_hex_bytes()`
I found the behavior of `fmt_bytes_hex_reverse()` to be not conform with the API description. In this case, a null-pointer de-reference could be triggered while complying with the API, by passing a `NULL` pointer as the output buffer. A search through the code base returned only few usage of this function and none of it was affected. I applied a fix and also moved the function closer to its relative `fmt_bytes_hex()`, thereby mimicking the order present in `fmt.h`. As an extra, I refactored the function to look even …

tests: Slightly increase coverage of fmt unittests

---

makefiles/boot/riotboot.mk
sys/include/riotboot/slot.h

These patches fix some builds errors I experienced when playing with riotboot. The commit comments contain the details of each.
Include riotboot/slots.h with riotbuild not enabled and observe that without this patch, the build will fail.
Attempt to build with an externally defined board which adds to the INCLUDES make macro and riotbuild enabled. Observe that without this patch, doing so will result in headers not being found which are located in those added include folders. 
- none known

riotboot: fix build errors

---

.murdock

We want to remove Kconfig, so don't fail CI when the Kconfig build no longer aligns with the classic make based build.
CI should continue functioning for non-Kconfig builds. 
https://forum.riot-os.org/t/last-chance-for-kconfig-dependency-modelling/4068

.murdock: drop Kconfig compile check

---

boards/nucleo-f413zh/include/periph_conf.h

While attempting to test #20214, I didn't get any output.  Long story short the DMA mappings for the UART are clearly incorrect.
I just added them and fixed it so I get output now... 
Before:
```
BOARD=nucleo-f413zh make flash term -C tests/periph/spi_dma
```
would not give any output, now it does.
One could try to test easy periph but I feel like reading the datasheet is the easiest test.

boards/nucleo-f413zh: Fix DMA mapping

---

Makefile.include

`generate-Makefile.ci` is the only target interesting to the user containing uppercase and a dot, which wasn't matched by the `sed` command used in `make help`. Changing that accordingly matches `*.module` and `*.xml` targets, too, which still shouldn't be part of the user-visible targets. Therefore, those are filtered out with `grep`.
1. on `master`: `make -C examples/hello-world help > before`
2. with this PR: `make -C examples/hello-world help > after`
3. `diff before after` results in:
```
46a47
> generate-Makefile.ci
```
`generate-Makefile.ci` was added with https://github.com/RIOT-OS/RIOT/pull/19244

make help: show generate-Makefile.ci

---

dist/tools/zep_dispatch/main.c
dist/tools/zep_dispatch/topogen.c
dist/tools/zep_dispatch/topology.c
dist/tools/zep_dispatch/topology.h

This is a collection of improvements I added while working on the CoAP multicast implementation.
- binary mode: links will be dropped below a cutoff-point, above it they are always successful
- numeric node names: allows for easier scripting
- make link quality drop off quadratically with distance
- always place the first node at a known location
- fix bug where packet won't get delivered to any node after it was dropped on a single link
- count rx/tx frames per node
- add possibility to store pidfile

tools/zep_dispatch: enhancements and fixes

---

sys/benchmark/benchmark.c

This PR fixes an integer overflow, that causes incorrect results to be reported when running a benchmark that takes longer than 4.2s.
Run a benchmark that takes longer than 4.2s with less than 1us per function call.
None

sys/benchmark: fix integer overflow in benchmark_print_time()

---

drivers/include/slipdev.h
drivers/slipdev/Kconfig
drivers/slipdev/Makefile.dep
drivers/slipdev/include/slipdev_internal.h
drivers/slipdev/slipdev.c
drivers/slipdev/stdio.c

Just a test to see if this can increase performance with high data ingress.
But turns out this also solves two nasty SLIP bugs:
- trivial solution for frames stuck in RX queue
- fixes pktbuf corruption (#18229) by removing the offending code
SLIP should work as before, ideally a bit better.
alternative to #18826, #18229

drivers/slipdev: make use of chunked ringbuffer

---

cpu/cc2538/include/cc2538_eui_primary.h
sys/net/link_layer/eui_provider/include/eui64_provider_params.h

The `cc2538_get_eui64_primary` function was not used because `cc2538_eui_primary.h` gets included by `board.h` but `board.h` is not included by `eui64_provider_params.h`.
```
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:18:F1:D6:5E
Erase before write done                 
Writing 524288 bytes starting at address 0x00200000
Write 16 bytes at 0x0027FFF0F8
Write done                              
/home/benpicco/dev/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyUSB1" -b "115200"  
2024-01-04 13:15:16,895 # Connect to serial port /dev/ttyUSB1
ifconfig
2024-01-04 13:15:29,967 # > ifconfig
2024-01-04 13:15:29,983 # Iface  6  HWaddr: 56:5E  Channel: 26  NID: 0x23  PHY: O-QPSK 
2024-01-04 …
```

cpu/cc2538: fix EUI provider

---

cpu/sam0_common/periph/spi.c
cpu/stm32/periph/spi.c
drivers/include/periph/spi.h

Same as for sam0, only perform DMA transfer if there are more than `CONFIG_SPI_DMA_THRESHOLD_BYTES` to transfer to avoid a net slowdown for single byte transfers due to DMA setup overhead.

cpu/stm32/periph_spi: only perform DMA transfer above threshold

---

dist/tools/insufficient_memory/Makefile.for_sh
dist/tools/insufficient_memory/create_makefile.ci.sh
dist/tools/insufficient_memory/update_insufficient_memory_board.sh

Previously the `add_insufficient_memory_board.sh` script would only add the tested board to `Makefile.ci` when resource requirements grew, but never remove it when resource requirements got lower.
This updates the script to also remove boards from `Makefile.ci` if it is no longer needed. It is also rename (`add` --> `update`) to match the change in behavior.
Mess up some `Makefile.ci` files by randomly adding and remove board `$BOARD`. Run `./dist/tools/insufficient_memory/add_insufficient_memory_board.sh $BOARD`. The `Makefile.ci`s should be fixed by adding `$BOARD` where needed, and dropping it where it wasn't needed.
None

dist/tools/insufficient_memory: always update Makefile.ci

---

examples/gnrc_networking/Makefile
examples/gnrc_networking_mac/Makefile
sys/include/net/gnrc/ipv6.h
sys/net/gnrc/network_layer/ipv6/Kconfig
sys/net/gnrc/network_layer/ipv6/nib/nib.c

With `GNRC_IPV6_STATIC_LLADDR` we can set static link-local addresses.
They are however not predictable: the interface ID gets added to least significant byte of the address. Add another option `CONFIG_GNRC_IPV6_STATIC_LLADDR_IS_FIXED` to avoid that.
```
2024-01-03 13:56:03,778 # Iface  7  HWaddr: 42:72  Channel: 26  NID: 0x23  PHY: O-QPSK 
2024-01-03 13:56:03,778 #           Long HWaddr: EE:9A:35:CC:EB:C8:42:72 
2024-01-03 13:56:03,779 #            State: IDLE 
2024-01-03 13:56:03,779 #           ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
2024-01-03 13:56:03,779 #           RTR_ADV  6LO  IPHC  
2024-01-03 13:56:03,779 #           Source address length: 8
2024-01-03 13:56:03,780 #           Link type: wireless
2024-01-03 13:56:03,780 #           inet6 addr: fe80::cafe:cafe:cafe:8  scope: …
```

gnrc/ipv6/nib: allow for predictable static link-local addresses

---

boards/generic-cc2538-cc2592-dk/Kconfig
boards/generic-cc2538-cc2592-dk/Makefile
boards/generic-cc2538-cc2592-dk/Makefile.dep
boards/generic-cc2538-cc2592-dk/Makefile.features
boards/generic-cc2538-cc2592-dk/Makefile.include
boards/generic-cc2538-cc2592-dk/dist/openocd.cfg
boards/generic-cc2538-cc2592-dk/doc.txt
boards/generic-cc2538-cc2592-dk/include/board.h
boards/generic-cc2538-cc2592-dk/include/gpio_params.h
boards/generic-cc2538-cc2592-dk/include/periph_conf.h
examples/lua_REPL/Makefile.ci
tests/Makefile.boards.netif
tests/unittests/Makefile.ci

The CC2538-CC2592-DK is one of the few readily available and affordable boards featuring a legacy CC2538 MCU. This PR adds support for that board. This hopefully makes maintaining RIOT support for that legacy MCU more affordable :-)
- read the documentation
- `make flash` should work
- `make debug` should work
- `make term` should work
- the SAUL integration of all buttons and the four user LEDs should work. (The fifth LED is an always-on power LED.)
None
-----
Update: I found the schematics here: https://github.com/knowic/CC2538_CC2592_DK
This enabled exposing all four user LEDs.

boards/generic-cc2538-cc2592-dk: add board support

---

drivers/mtd/mtd.c

This PR fixes `mtd_write_sector` function introduced with PR #20180.
`mtd_write_page_raw` requires the number of bytes to be written as parameter, which is the number of sectors to be written (parameter `count`) multiplied by the pages per sector `mtd->pages_per_sector` and the page size `mtd->page_size`.
Use any board with SPI SD Card interface and set `ENABLE_DEBUG` in `drivers/mtd_sdcard.c`. Without the PR, writing to the SD card fails because of the wrong size. Formatting the SD card doesn't hangs.
```
> vfs w /sd0/test1.txt ascii o hello
mtd_sdcard_read_page: page:1991 offset:0 size:512
mtd_sdcard_write_page: page:1991 offset:0 size:1019392
mtd_sdcard_write_page: error 4
Write error: -EIO
mtd_sdcard_write_page: page:1991 offset:0 size:1019392
mtd_sdcard_write_page: error 3
```
With …

drivers/mtd: fix mtd_write_sector

---

sys/include/suit/transport/worker.h
sys/suit/transport/worker.c

This makes the SUIT worker a bit more flexible: Currently the board will always reboot after the update process, there is no way for the application to tell whether the update was successful.
This patch moves the 'reboot after update' policy to a `suit_worker_done_cb()` function that can be overwritten by custom application logic. 
No change in default behavior.

sys/suit: introduce suit_worker_done_cb()

---

dist/tools/riotboot_gen_hdr/common.c
dist/tools/riotboot_gen_hdr/common.h
dist/tools/riotboot_gen_hdr/genhdr.c
dist/tools/riotboot_gen_hdr/main.c

Sometimes we want to roll-back to a previous firmware version. To do so we need a higher riotbot version numbers still.
Add an update command to the riotboot_gen_hdr tool so that an existing firmware image can be re-rolled out with a new version number.
```
$ dist/tools/riotboot_gen_hdr/bin/genhdr show /tmp/slot0.1704742721.bin
version: 1704742721
address: 0x1100
checksum: valid
$ dist/tools/riotboot_gen_hdr/bin/genhdr update /tmp/slot0.1704742721.bin 12345
$ dist/tools/riotboot_gen_hdr/bin/genhdr show /tmp/slot0.1704742721.bin 
version: 12345
address: 0x1100
checksum: valid
```

dist/tools/riotboot_gen_hdr/genhdr: add update command

---

core/lib/init.c
cpu/avr8_common/thread_arch.c
cpu/native/native_cpu.c
makefiles/features_modules.inc.mk

When we don't enable thread mode, all schedule functions should be no-ops.
We also don't want to pull in `core_idle_thread` here. 
Run a simple application that does not make use of threads with
DISABLE_MODULE += core_thread

cpu/avr8_common: fix build with !core_thread

---

sys/include/net/nanocoap_sock.h
sys/net/application_layer/nanocoap/sock.c

Mostly for completeness' sake, works just like PUT/POST.

nanocoap_sock: implement FETCH methods

---

cpu/avr8_common/include/cpu.h
cpu/cortexm_common/include/cpu_conf_common.h
cpu/esp32/include/periph_cpu_esp32.h
cpu/esp32/include/periph_cpu_esp32c3.h
cpu/esp32/include/periph_cpu_esp32s2.h
cpu/esp32/include/periph_cpu_esp32s3.h
cpu/esp8266/include/periph_cpu.h
cpu/msp430/clock.c
sys/include/busy_wait.h
tests/sys/busy_wait/Makefile
tests/sys/busy_wait/Makefile.ci
tests/sys/busy_wait/main.c

We often need to wait for a short period of time before timers are initialized, e.g. in `board_init()`.
Instead of ad-hoc busy wait implementations, provide a common `busy_wait()` helper function (taken from msp430) and add a `busy_wait_us()` for a rough time approximation based on the CPU frequency. 
A new test application is provided in `tests/sys/busy_wait` that will measure the diversion from the usec timer:
```
2024-01-09 18:34:38,799 # waiting for 10 µs…
2024-01-09 18:34:38,801 # took 29 µs (diff: 19 µs)
2024-01-09 18:34:38,803 # waiting for 100 µs…
2024-01-09 18:34:38,806 # took 119 µs (diff: 19 µs)
2024-01-09 18:34:38,808 # waiting for 1000 µs…
2024-01-09 18:34:38,812 # took 1012 µs (diff: 12 µs)
2024-01-09 18:34:38,814 # waiting for 10000 µs…
2024-01-09 18:34:38,827 # took 9942 …
```

sys/busy_wait: add busy wait helper

---

boards/samd20-xpro/Makefile.features
boards/samd21-xpro/Makefile.features
sys/shell/cmds/sys.c

We don't have a way to tell which firmware version is currently running on the device, so add this information to the `version` command when running with `riotboot_slot`.
The current firmware version is now printed when entering `version` (tested with `examples/suit_update`):
```
2024-01-11 14:40:33,170 # > version
2024-01-11 14:40:33,170 # 
2024-01-11 14:40:33,172 # 2024.01-devel-567-gbb4c4d
2024-01-11 14:40:33,175 # suit_update v1704980244, slot 0
```

sys/shell: add firmware version to version cmd

---

core/lib/panic.c
cpu/avr8_common/Makefile.dep

`pm_layered` is a `DEFAULT_MODULE` for all other arches so we can disable it - do the same for AVR8.
Also add a fallback for `panic()` if `periph_pm` is not enabled. 
```
DISABLE_MODULE += core_thread pm_layered
FEATURES_BLACKLIST += periph_pm
```
now allows to minimize simple programs.

cpu/avr8_common: allow to build with !periph_pm

---

core/doc.txt
doc/doxygen/src/mainpage.md

Don't call RIOT a microkernel, that just sets the wrong expectations.
We only have threads, but no separation between them or any notion of kernel/userspace.
By that notion Linux would also be a microkernel.

doc/mainpage: don't claim to be a microkernel

---

drivers/atwinc15x0/atwinc15x0_netdev.c
drivers/lcd/lcd.c
drivers/nrf24l01p_ng/nrf24l01p_ng_netdev.c
drivers/sx126x/sx126x_netdev.c
drivers/sx1280/sx1280_netdev.c
sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
sys/net/gnrc/pktdump/gnrc_pktdump.c
tests/unittests/tests-uri_parser/tests-uri_parser.c

I seem to have missed some `size_t` prints without casts in `drivers` and `tests/unittests/tests-uri_parser/tests-uri_parser.c`.
I also made two mistakes in `sys/net/gnrc`.
This PR fixes them.
This should have no functional impact on currently supported architectures, as `sizeof(size_t) == sizeof(unsigned)` is true for all them. Test as usual.
Fixes #20194

print: Missing size_t print format specifiers

---

boards/e180-zg120b-tb/Makefile.include
boards/e180-zg120b-tb/dist/openocd.cfg
boards/e180-zg120b-tb/doc.txt

As the title says. The documentation is duly updated as well and an image of the board is added.
Flashing the board with OpenOCD e.g. with an ST-Link should now work.
```
git:(boards/e180-zg120b-tb/openocd) ~/Repos/software/RIOT/master ➜ make BOARD=e180-zg120b-tb -C examples/default/ flash
make: Entering directory '/home/maribu/Repos/software/RIOT/master/examples/default'
Building application "default" for "e180-zg120b-tb" with MCU "efm32".
"make" -C /home/maribu/Repos/software/RIOT/master/pkg/cmsis/ 
"make" -C /home/maribu/Repos/software/RIOT/master/pkg/gecko_sdk/ 
"make" -C /home/maribu/.cache/RIOT/pkg/gecko_sdk/dist
"make" -C /home/maribu/.cache/RIOT/pkg/gecko_sdk/dist/emlib-extra/src
"make" -C /home/maribu/.cache/RIOT/pkg/gecko_sdk/dist/emlib/src
"make" -C …
```

boards/e180-zg120b-tb: add support for OpenOCD

---

dist/tools/openocd/openocd.sh

When using OpenOCD RTT (real-time transfer) for stdio with `USEMODULE=stdio_rtt make ...`, it is no longer possible to debug while being connected to stdio. By also opening gdb at RIOT's default GDB port, `make debug-client` can be used to connect from GDB to the OpenOCD instance providing stdio via RTT.
1. `USEMODULE=stdio_rtt make BOARD=<some_board_with_openocd-support> -C examples/default flash term`
2. `make BOARD=<same_board_with_openocd-support> -C examples/default debug-client`
Note: `make debug-client` will only work when the connection to RIOT's serial via OpenOCD RTT is still open.
None

tools/openocd-rtt: also open GDB port

---

dist/tools/zsh-completion/zsh-riot.sh

Also complete and explain `PROGRAMMER=`, `OPENOCD_DEBUG_ADAPTER=`, and `OPENOCD_RESET_USE_CONNECT_ASSERT_SRST=` when using zsh.
Install the completion as stated in the documentation and confirm that completion with zsh now indeed explains and completes aforementioned options.
None

dist/tools/zsh-completion: add completion for flash

---

cpu/sam0_common/sam0_sdhc/sdhc.c
drivers/mtd_spi_nor/mtd_spi_nor.c

We can use this as a fallback when no ZTimer is enabled (e.g. in riotboot).

drivers: make use of busy_wait()

---

tests/unittests/tests-fib/tests-fib.c

Reverts the type changes for the array size variables that I made as a fixup along with other changes in #20194.
Pointers to the variables are sometimes passed as `size_t *` in the `fib_get_next_hop` and `fib_get_destination_set` function calls, which becomes a problem when `sizeof(size_t) != sizeof(unsigned)`. 
While this is not true for any of the currently supported platforms, it is true for most 64-bit architectures.
`make -C tests/unittests all test`
Fixes 475a55136a4ae6bc57c77bb891e3867aa44dc8c0

unittests/tests-fib: Fix array size types

---

dist/tools/zsh-completion/zsh-riot.sh

This fixes a typo in a description.
When completing `PROGRAMMER=`, there is a stray `,` after the description of `bmp`:
```
adafruit-nrfutil  -- program via Adafruits nRF5x bootloader
avrdude           -- default for AVR boards
bmp               -- Black Magic Probe,
bossa             -- for SAM based Arduino boards
cc2538-bsl        -- for CC2538 boards
cpy2remed         -- program via ST-Link using filesystem disk interface
dfu-util          -- Flash using DFU Bootloader
edbg              -- for SAM based evaluation board
elf2uf2           -- program via UF2 bootloader (RP2040)
esptool           -- program ESP32 (S2,S3,C2,C3,C6,...) ESP8266 via UART
goodfet           -- for some MSP430 boards
jlink             -- use Segger's JLinkExe for programming (requires original Segger …
```

dist/tools/zsh-completion: fix typo

---

sys/hashes/sha224.c
sys/hashes/sha256.c
sys/include/hashes/sha224.h
sys/include/hashes/sha256.h

This removes the static (thread-unsafe) variables from sha256 and hmac_sha256 to remove a potential footgun. The static variable is only used when the caller does not supply a pointer to store the digest and it is returned via the (undocumented) return value.
This commit removes this option and makes the digest argument mandatory.
The tests-hashes unittest should still work:
```
main(): This is RIOT! (Version: 2024.01-devel-240-gc98f3-pr/sha256/no_static)
s
START
...........................................
OK (43 tests)
```
Introduced in #124

hashes/sha2{24,56}: Remove static variables from sha256

---

.murdock

With https://github.com/RIOT-OS/riotdocker/pull/237 I broke murdock tests on the pifleet. This should fix them.
*edit*
So what happened here is that dwq dropped support for specifying the target path of a file sent along with a job.
That feature might come back.
In the meantime, this PR makes BINDIR match on compiler (mobi*, breeze, ...) and tester (pifleet).
(I've piggybacked a commit that makes the tester fail early if flashing returned an error code.)

ci: fix murdock tests after dwq change

---

core/lib/include/priority_queue.h
core/lib/priority_queue.c
core/mbox.c
core/thread_flags.c
drivers/mtd_flashpage/mtd_flashpage.c
drivers/soft_uart/soft_uart.c
sys/cpp11-compat/condition_variable.cpp
sys/include/architecture.h
sys/include/bloom.h
sys/include/vfs.h
sys/posix/include/sys/bytes.h
sys/posix/pthread/pthread_cond.c
sys/ztimer/core.c
sys/ztimer64/ztimer64.c

Since #20154 still seems a bit too big to discuss properly, I decided to split it into smaller PRs.
This PR includes the changes to `core`, `sys` and `drivers` to enable 64-bit support.
The commits are part of this patch series
- #19890
All tests and applications should remain unchanged for existing platforms.
See also #19890, #20154

core, sys, drivers: 64-bit support preparations

---

core/lib/init.c
tests/periph/uart_locate_pins/Makefile
tests/periph/uart_locate_pins/README.md
tests/periph/uart_locate_pins/include/soft_uart_params.h
tests/periph/uart_locate_pins/main.c

This application uses `soft_uart` to bit-bang the name of a number of configured GPIO pins via said pins at 9600 Bd. This way attaching an USB UART bridge to one pin at a time easily reveals which MCU GPIO pin a given pin on a board corresponds to. This is useful when no schematic and no silkscreen labeling is available, or when the information is misleading or outright incorrect (looking at the E180-ZG120B-TB).
1. Extend the list of pins in `main.c` to contain some pins to detect where they are routed to on the board.
- beware: Some pins shouldn't be configured as output (e.g. pins connected to a crystal
2. Flash the app on a board
3. Connect an USB UART bridge configured at 9600 Bd to one pin at a time. Each pin should tell you its name
None

tests/periph/uart_locate_pins: new test/utility app

---

.murdock

This PR makes .murdock make use of the newly introduced `dwq-localjob`, which allows injecting command output as if it were run as ci (dwq) job. "native" tests should now end up in the "test" tab in the CI results, instead of being inlined in the compilation output.

ci: make native tests show up in "tests"

---

cpu/stm32/periph/uart.c
drivers/include/periph/uart.h

For small transfers, setting up the DMA will take much longer than sending the bytes, so avoid doing DMA there to avoid a slowdown with DMA enabled.

cpu/stm32: uart: don't do DMA for small transfers

---

boards/e180-zg120b-tb/doc.txt

Revision 1.0 of the board has an incorrect pin labeling on the silkscreen, presumably because the board was initially developed for a different E180 module and the silkscreen was not updated when populated with a different E180 module.
It is very likely that if newer revisions of the test board get produced, they will use the same very systematical routing as revision 1.0 and only the silkscreen labeling will be fixed. Hence, documenting the correct pin mapping will be useful even for newer revisions.
The pins on the header not routed to an NC pin on the module can be identified using https://github.com/RIOT-OS/RIOT/pull/20253 and the remaining can be traced with a multi-meter.
Note: The routing is pretty systematically and the pattern is quite obvious (only pin 1, the ANT pin, is not …

boards/e180-zg120b-tb: Document correct pin mapping

---

sys/shell/cmds/i2c_scan.c

There are only 8 reserved addresses on the low end of the address space.
A sensor with address `0x8` is now detected by `i2c_scan`:
```
2024-01-18 15:11:40,685 # Scanning I2C device 0...
2024-01-18 15:11:40,691 # addr not ack'ed = "-", addr ack'ed = "X", addr reserved = "R", error = "E"
2024-01-18 15:11:40,695 #      0 1 2 3 4 5 6 7 8 9 a b c d e f
2024-01-18 15:11:40,699 # 0x00 R R R R R R R R X - - - - - - -
2024-01-18 15:11:40,704 # 0x10 - - - - - - - - - - - - - - - -
2024-01-18 15:11:40,709 # 0x20 - - - - - - - - - - - - - - - -
2024-01-18 15:11:40,714 # 0x30 - - - - - - - - - - - - - - - -
2024-01-18 15:11:40,719 # 0x40 - - - - - - - - - - - - - - - -
2024-01-18 15:11:40,724 # 0x50 - - - - - - - - - - - - - - - -
2024-01-18 15:11:40,729 # 0x60 - - - - - - - - - - - - - - - - …
```

sys/shell: fix reserved addresses in i2c_scan

---

boards/native/Makefile.include
dist/pythonlibs/riotctrl_ctrl/native.py
dist/pythonlibs/riotctrl_ctrl/requirements.txt
makefiles/tests/tests.inc.mk

Only enable the pyterm wrapper if we are executing the `term` target to avoid breaking things.
`make debug` should work again on `native`.
So does e.g. `tests/sys/log_color` without the previously added workaround.
reverts #20215
fixes #20265

boards/native: only use pyterm wrapper with term target

---

tests/net/gcoap_dns/Makefile
tests/net/gcoap_fileserver/Makefile
tests/net/gnrc_dhcpv6_client_6lbr/Makefile
tests/net/gnrc_netif_ieee802154/Makefile
tests/net/gnrc_rpl/Makefile
tests/net/gnrc_sixlowpan_frag_sfr_congure_impl/Makefile
tests/net/ieee802154_hal/Makefile
tests/net/socket_zep/Makefile

`RIOT_TERMINAL=pyterm` is now only used with the `term` target, the `native` term is the default for everything else, including tests. So we don't have to set it for every test.
CI should do the job
follow-up to #20264

tests: don't explicitly set RIOT_TERMINAL=native

---

sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/nanocoap.c
tests/unittests/tests-nanocoap/tests-nanocoap.c

This adds a new function `coap_find_uri_query()` with which we can find a URI query on a request packet.
This makes handling requests with query options easier as we don't have to manually iterate all options in the handler. 
`tests-nanocoap` was extended to exercise the new function.
suggested in #20197

nanocoap: implement coap_find_uri_query()

---

examples/rust-gcoap/Cargo.lock

The older version of the external module used to have an `embedded-hal = "*"` dependency that finally broke; the updated version is fixed.
This did not cause trouble in test builds, but would cause
```
--> /github/home/.cargo/git/checkouts/riot-module-examples-d2e3e2ff5ccfa52a/5aa33e8/riot-coap-handler-demos/src/graphics.rs:10:19
|
10 | use embedded_hal::blocking::i2c::{Write, Read};
```
when any part of the build runs a `cargo update`.
Green CI.
The commit in the external module that fixes this is https://gitlab.com/etonomy/riot-module-examples/-/commit/de9fb3332c2a5125ac97ee29f5f61deba444aa99; the 3 commits before it that are pulled in as well contain various minor fixes or add unrelated modules.

examples/rust-gcoap: Fix transitive unbounded dependency

---

boards/common/gd32v/Makefile.include
boards/common/gd32v/include/cfg_usbdev_default.h
boards/gd32vf103c-start/Makefile
boards/gd32vf103c-start/Makefile.dep
boards/gd32vf103c-start/Makefile.features
boards/gd32vf103c-start/Makefile.include
boards/gd32vf103c-start/dist/openocd.cfg
boards/gd32vf103c-start/doc.txt
boards/gd32vf103c-start/include/arduino_iomap.h
boards/gd32vf103c-start/include/board.h
boards/gd32vf103c-start/include/gpio_params.h
boards/gd32vf103c-start/include/periph_conf.h
boards/seeedstudio-gd32/Makefile.include
boards/sipeed-longan-nano/Makefile.include
cpu/gd32v/cpu.c
cpu/gd32v/include/cpu_conf.h
cpu/gd32v/periph/pwm.c
examples/dtls-wolfssl/Makefile.ci
examples/suit_update/Makefile.ci
makefiles/tools/openocd.inc.mk
makefiles/tools/serial.inc.mk
tests/pkg/utensor/Makefile.ci
tests/pkg/wolfssl/Makefile.ci
tests/riotboot_flashwrite/Makefile.ci
tests/unittests/Makefile.ci

This pull request adds support for the GD32VF103C-START board, the official evaluation board of the GD32VF103C MCU by the MCU vendor. Sadly, there is relatively little documentation provided on the board.
Output when testing with the selftesting shield:
```
main(): This is RIOT! (Version: 2024.01-devel-611-gc01b6b4-boards/gd32vf103c-start)
self-testing peripheral drivers
===============================
Starting test for GPIO at tests/periph/selftest_shield/main.c:346
[OK]
Starting test for GPIO at tests/periph/selftest_shield/main.c:368
[OK]
Starting test for GPIO at tests/periph/selftest_shield/main.c:398
[OK]
Starting test for GPIO at tests/periph/selftest_shield/main.c:428
(skipped)
Starting test for GPIO at tests/periph/selftest_shield/main.c:454
(skipped)
Starting test for GPIO-IRQ …
```

boards/gd32vf103c-start: new board 

---

cpu/atmega_common/include/periph_cpu_common.h
cpu/atmega_common/periph/gpio_ll.c
cpu/efm32/periph/gpio_ll.c
cpu/esp32/include/periph_cpu.h
cpu/esp32/periph/gpio_ll.c
cpu/gd32v/include/periph_cpu.h
cpu/gd32v/periph/gpio_ll.c
cpu/nrf5x_common/include/periph_cpu_common.h
cpu/nrf5x_common/periph/gpio_ll.c
cpu/stm32/include/periph/cpu_gpio_ll.h
cpu/stm32/periph/eth.c
cpu/stm32/periph/eth_common.c
cpu/stm32/periph/gpio_ll.c
drivers/include/periph/gpio_ll.h
drivers/periph_common/gpio_ll.c
drivers/ws281x/timer_gpio_ll.c
tests/bench/periph_gpio_ll/main.c
tests/periph/gpio_ll/Makefile
tests/periph/gpio_ll/main.c

This commit optimizes the `gpio_conf_t` type in the following regards:
- The "base" `gpio_conf_t` is stripped from members that only some platforms support, e.g. drive strength, slew rate, and disabling of the Schmitt Trigger are no longer universally available but platform-specific extensions
- The `gpio_conf_t` is now crammed into a bit-field that is 8 bit or 16 bit wide. This allows for storing lots of them e.g. in `driver_foo_params_t` or `uart_conf_t` etc.
- A `union` of the `struct` with bit-field members and a `bits` is used to allow accessing all bits in a simple C statement and to ensure alignment for efficient handling of the type
In addition `gpio_conf_t` is no longer passed via pointer, but by value. Because it now is small enough to fit in a register on all supported …

drivers/periph/gpio_ll: shrink gpio_conf_t

---

examples/dtls-sock/Makefile
examples/dtls-sock/dtls-client.c

We have helper functions for parsing the destination address and establishing a DTLS connection now, so don't open-code it.
The app still works as described
```
main(): This is RIOT! (Version: 2024.01-devel-246-gde89f7-examples/dtls-sock-cleanup)
DTLS sock example application
> dtlsc fe80::581a:98ff:fe23:2d6c test
Connection to server successful
Sent DTLS message
Received 4 bytes: "test"
Terminating
```

examples/dtls-sock: make use of helper functions

---

drivers/include/periph/gpio_ll.h
tests/periph/gpio_ll/README.md
tests/periph/gpio_ll/main.c

The documentation on the state `GPIO_DISCONNECT` was a bit vague. The API doc said it should disconnect the GPIO from all peripherals, the test also tested them for being electrically disconnected.
The documentation in both the test and the API is extended to point out that a GPIO indeed SHOULD be in high impedance state, but that user MUST NOT expect that this requested is honored by every implementation and for every GPIO pin.
In the test it is also pointed out that failing the test for a GPIO in the `GPIO_DISCONNECT` state being electrically disconnected is for some pins expected, and that the test should be just run again with different GPIOs. The test intentionally tests for a feature not provided by every GPIO pin rather than warning on a failure: The effort to just flash and run …

drivers/periph_gpio_ll: Improve documentation

---

boards/msb-430/include/periph_conf.h
boards/msb-430h/include/periph_conf.h
boards/olimex-msp430-h1611/Makefile.include
boards/olimex-msp430-h1611/include/periph_conf.h
boards/telosb/include/periph_conf.h
cpu/msp430/include/x1xx/periph_cpu.h
cpu/msp430/periph/Makefile
cpu/msp430/periph/spi_usart.c
cpu/msp430/periph/uart_usart.c
cpu/msp430/periph/usart.c
tests/net/gnrc_netif_ipv6_wait_for_global_address/Makefile.ci
tests/sys/suit_manifest/Makefile.ci

- Move common code for USART (shared SPI / UART peripheral) to its own file and allow sharing the USART peripheral to provide both UART and SPI in round-robin fashion.
- Configure both UART and SPI bus via a `struct` in the board's `periph_conf.h`
- this allows allocating the two UARTs as needed by the use case
- since both USARTs signals have a fixed connection to a single GPIO, most configuration is moved to the CPU
- the board now only needs to decide which bus is provided by which USART
Note: Sharing an USART used as UART requires cooperation from the app:
- If the UART is used in TX-only mode (no RX callback), the driver will release the USART while not sending
- If the UART is used to also receive, the application needs to power the UART down while not expecting something to send. …

cpu/msp430: rework MSP430 x1xx periph drivers

---

boards/nrf52dk/Makefile.features
boards/nrf52dk/include/arduino_iomap.h

This defines the Arduino GPIO pins, sets the shield I2C bus and the form factor.
Run tests/periph/selftest_shield with an nrf52dk and a [Peripheral Selftest Shield](https://github.com/RIOT-OS/RIOT-Open-Hardware/tree/main/selftesting-shield) in "all off, D-3-4 on" configuration.
This simplifies testing https://github.com/RIOT-OS/RIOT/pull/20282
I'm keeping this as Draft PR because I'm still looking at whether there are cheap extras to enable (maybe SPI bus, maybe the ADC pins). If I find none, this will be changed to "ready for review" without further comment.

boards/nrf52dk: Minimal Arduino pinout support

---

cpu/nrf5x_common/periph/i2c_nrf52_nrf9160.c

On nrf5x chips (tested on nrf52840), I2C_NOSTOP is not implemented correctly: It sets up the interrupts for the ERROR and STOPPED events, but the STOPPED condition is only reached when the "short" (nRF5x ling for triggering actions after state transitions) LASTTX_STOP causes the STOP condition to be set after the last transmission (eventually winding up in STOPPED). But when setting I2C_NOSTOP, the only interrupt that triggers is LASTTX, and that is not enabled.
In the periph_i2c test (with DEBUG enabled for full output, but you'll see the hang anyway):
```
> i2c_acquire 0
2024-01-22 01:55:00,900 # i2c_acquire 0
2024-01-22 01:55:00,902 # Command: i2c_acquire(0)
2024-01-22 01:55:00,903 # [i2c] acquired dev 0
2024-01-22 01:55:00,905 # Success: i2c_0 acquired
> i2c_write_byte 0 30 0 4 …
```

cpu/nrf5x i2c: Set up correct interrupts after NOSTOP transmissions

---

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c

When we send a packet out, GNRC checks with `gnrc_netif_get_by_ipv6_addr()` if the destination address is configured on a local interface. If this is the case, it won't send the packet, but directly deliver it to a local thread.
This has a tiny bug though: When the destination is link-local, we only must consider addresses on the interface we are sending on, not all addresses.
On a board with two interfaces (e.g. two UARTS with SLIP) connect them in loop-back mode.
```
2024-01-22 20:14:37,850 # Iface  6  HWaddr: 7A:F4:3C:20:AB:61 
2024-01-22 20:14:37,853 #           L2-PDU:1500  MTU:1500  HL:64  Source address length: 6
2024-01-22 20:14:37,854 #           Link type: wired
2024-01-22 20:14:37,856 #           inet6 addr: fe80::78f4:3cff:fe20:ab61  scope: link  VAL
2024-01-22 20:14:37,867 # …
```

gnrc/ipv6: only send link-local loopback if it's on the same interface

---

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c

Hello! :shell: 
This PR consists of two changes:
* The first commit are a few minor style fixes. Manually done by me, inspired by #14623 
* The second commit is the result of running uncrustify over my first commit. 
Because uncrustify would hide my changes regarding function signitures & variable renaming, I split it up in two commits.
I can understand if the second commit is objected - it's purely optional for me.
Beside some `statics` no functional changes have been made. If it still builds and the ci passes, this should be fine!

routing/rpl: Fixing styling & format

---

pkg/uzlib/doc.txt

uzlib (zlib-compatible compression/decompression) contains a memory leak during compression. Add a warning to the documentation until the issue is resolved upstream, see https://github.com/pfalcon/uzlib/issues/41#issuecomment-1907807048

pkg/uzlib: warn about memory leak during compression

---

sys/include/net/coap.h
sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/nanocoap.c

The `coap_build_reply()` function is kind of awkward to use.
`coap_reply_simple()` is nicer, but always requires keeping a separate buffer for the payload that then gets copied into the reply buffer anyway.
Add a new function `coap_build_reply_header()` that covers all uses of `coap_build_reply()` but is simpler to use: It builds the response header in the response buffer and sets the payload pointer to after the header, so a user can write the payload directly into the response buffer without having to copy it.
`coap_reply_simple()` has been re-implemented using the new function.

nanocoap: add coap_build_reply_header()

---

cpu/nrf5x_common/periph/i2c_nrf52_nrf9160.c

The underlying peripheral can only read from RAM. This uses the existing infrastructure (already needed to work around the lack of a hardware support for I2C_NOSTART) to unconditionally copy any to-be-sent data into RAM.
There is certainly an alternative where we determine at runtime whether the data is in RAM or in ROM and only lock and copy if it's in ROM, but I'd only do that if we have concrete benchmarks that show that this is an issue.
* To see that the old behavior works, run the saul demo on a microbit-v2, or any other board's I2C.
* To see that things work even from flash, run the saul demo on a microbit-v2 with my lsm303agr-0.3 branch -- that updated the driver such that it can send its commands from ROM, which broke things here.

cpu/nrf52 i2c: Always buffer writes

---

drivers/w5100/w5100.c

This allows the use of EUI provider for setting a fixed MAC address.

drivers/w5100: make use of netdev_eui48_get()

---

cpu/nrf5x_common/periph/i2c_nrf52_nrf9160.c

(Reviewers, beware that the first two commits are actually #20298, see below for details).
When https://github.com/RIOT-OS/RIOT/pull/20282 which enabled continuation from NOSTOP writes on nRF52 I2C in the first place, my hope was that waiting for the LASTTX signal and then starting a read operation could rely on the hardware to synchronize -- after all, LASTTX indicates that the write *was* started, so the hardware would not cancel the write in progress when there is a subsequent read, especially when the hardware doesn't signal that the last transmission was completed in situations when NOSTOP is required, right?
Nope:
The capture shows that a write operation is started, the address is written with the W bit, ACKed, and then before the last byte (the only byte) containing the I2C …

cpu/nrf52 i2c: Wait for complete transmission when writing NOSTOP

---

sys/include/vfs.h

At least for `same54-xpro`, when `fatf_vfs` is used and `VFS_NAME_MAX` is increased a static assert triggers.
`BOARD=same54-xpro CFLAGS+=-DVFS_NAME_MAX=44 make -C tests/sys/vfs_default`
```
"make" -C /home/fabian.huessler@ml-pa.loc/RIOT/pkg/fatfs/fatfs_vfs
In file included from /home/fabian.huessler@ml-pa.loc/RIOT/pkg/fatfs/fatfs_vfs/fatfs_vfs.c:21:
/home/fabian.huessler@ml-pa.loc/RIOT/pkg/fatfs/fatfs_vfs/fatfs_vfs.c: In function '_mount':
/home/fabian.huessler@ml-pa.loc/RIOT/core/lib/include/assert.h:148:28: error: static assertion failed: "fatfs_file_desc_t must fit into VFS_FILE_BUFFER_SIZE"
148 | #define static_assert(...) _Static_assert(__VA_ARGS__)
|                            ^~~~~~~~~~~~~~
/home/fabian.huessler@ml-pa.loc/RIOT/pkg/fatfs/fatfs_vfs/fatfs_vfs.c:123:5: note: in …
```

vfs: fix FATFS_VFS_FILE_BUFFER_SIZE for increased VFS_NAME_MAX

---

cpu/native/Makefile.features
cpu/native/include/periph_conf.h
cpu/native/periph/timer.c

This pull request adds support for the `periph_timer_query_freqs` feature to the `native` platform.
The feature allows software to query the supported frequency of the timer, which in this case is
a fixed frequency used internally for time conversions.
This allows software which depends on this feature to run on the `native` board. Since the `periph/timer`
test expects all timers supporting this feature to also define `TIMER_CHANNEL_NUMOF`, the necessary define
was added to the CPU configuration.
Build:
`make BOARD=native -C tests/periph/timer flash test`
> TIMER 0
> =======
>
>   - supported frequencies:
>     0: 1000000
>   - Calling timer_init(0, 1000000)
>     initialization successful
>   - timer_stop(0): stopped
>   - timer_set(0, 0, 5000)
>     Successfully set timeout 5000 for …

cpu/native: Add support for periph_timer_query_freqs

---

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c

This PR provides a fix for a double-free in `gnrc_ipv6`.
This occurs because the `_safe_fill_ipv6_hdr` function already calls `gnrc_pktbuf_release`. Therefore, calling it again in `_send_to_self` crashes the devices
Try pinging to a TNT loopback address. Without this PR, it crashes:
```
2024-01-29 12:01:44,285 # ping 2001:67c:254:b0c1:204:2519:1801:bddb
2024-01-29 12:01:44,286 # 8841
2024-01-29 12:01:44,288 # *** RIOT kernel panic:
2024-01-29 12:01:44,290 # FAILED ASSERTION.
2024-01-29 12:01:44,290 # 
2024-01-29 12:01:44,299 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2024-01-29 12:01:44,308 # 	 - | isr_stack            | -        - |   - |    512 (  348) (  164) | 0x20000000 | 0x200001b8
2024-01-29 12:01:44,317 # 	 1 | main …
```

gnrc_ipv6: fix double-free when pinging TNT loopback address

---

sys/random/fortuna/fortuna.c

sys/random/fortuna/fortuna.c:add error check of aes_encrypt()
I'm not sure which exact value should be returned when aes_encrypt() is not on success. I just return the return value of it. 
Addresses parts of #15524

add error check of aes_encrypt()

---

pkg/cmsis/Makefile
pkg/pkg.mk

This PR adds support for the [Rust version of git-cache](https://github.com/kaspar030/git-cache-rs).
The shell version that we've integrated in `dist/tools/git` is quite a mess, barely maintainable. But most importantly, it is slow, and gets slower over time, due to the way the cache stores tags. Also, it doesn't support sparse checkouts. Crude measurements show that for our CI builds, for cortex-m builds **20-50%** of time spent on each built are spent on checking out "pkg/cmsis".
git-cache-rs' syntax is compatible with regular `git clone` to the point where any `git clone ...` command that doesn't work with just changing to `git cache clone` is considered a bug.
Unfortunately that requires some changes. This PR introduces git-cache-rs support as fully optional, it'll only be used if …

ci: support git-cache-rs

---

cpu/sam0_common/periph/flashpage.c

This disabled interrupts while write operations on the internal flash are ongoing.
@firas-hamdi discovered that firmware updates over 802.15.4 with 1024 byte CoAP block size would sometimes (~10% of all updates) trigger a hard fault caused by an *Imprecise data access* (`IMPRECISERR`) on samd51.
I failed to re-create this on same54-xpro over Ethernet, so I was wondering if the increased interrupt load due to 6lo fragmentation might have something to do with it.
I'll try to come up with a setup that triggers this via GPIO interrupts.

cpu/sam0_common: flashpage: disable interrupts while writing

---

pkg/cmsis/Makefile
pkg/pkg.mk

This PR adds support for the [Rust version of git-cache](https://github.com/kaspar030/git-cache-rs).
The shell version that we've integrated in `dist/tools/git` is quite a mess, barely maintainable. But most importantly, it is slow, and gets slower over time, due to the way the cache stores tags. Also, it doesn't support sparse checkouts. Crude measurements show that for our CI builds, for cortex-m builds **20-50%** of time spent on each built are spent on checking out "pkg/cmsis".
git-cache-rs' syntax is compatible with regular `git clone` to the point where any `git clone ...` command that doesn't work with just changing to `git cache clone` is considered a bug.
Unfortunately that requires some changes. This PR introduces git-cache-rs support as fully optional, it'll only be used if …

ci: support git-cache-rs [backport 2024.01]

---

cpu/native/periph/timer.c

This pull request contains some fixes for the `periph_timer` module of the `native` platform.
The first patch is a minor cleanup patch while the next two patches fix some issues
regarding the handling of errors.
Build:
`make BOARD=native -C tests/periph/timer flash test`
> TIMER 0
> =======
>
>  - supported frequencies:
>     0: 1000000
>   - Calling timer_init(0, 1000000)
>     initialization successful
>   - timer_stop(0): stopped
>   - timer_set(0, 0, 5000)
>     Successfully set timeout 5000 for channel 0
>   - timer_start(0)
>   - Results:
>     - channel 0 fired at SW count   240171      - init:   240171
>   - Validating no spurious IRQs are triggered:
>     OK (no spurious IRQs)
>
> TEST SUCCEEDED
> { "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 436 }]}
> { …

Fix for `periph_timer` on `native`

---

examples/gcoap_fileserver/Makefile
examples/gcoap_fileserver/main.c
examples/nanocoap_server/Makefile
examples/nanocoap_server/coap_handler.c
makefiles/pseudomodules.inc.mk
sys/Makefile.dep
sys/include/net/nanocoap/fileserver.h
sys/net/application_layer/nanocoap/fileserver.c
tests/net/gcoap_fileserver/Makefile
tests/net/gcoap_fileserver/main.c

There isn't really anything GCoAP specific about the fileserver module, it can just as well be used with nanoCoAP. Move and rename it to reflect that.
Both `examples/gcoap_fileserver` and `examples/nanocoap_server` keep serving files, but the latter one without pulling in a GCoAP dependency.

gcoap_fileserver: rename to nanocoap_fileserver

---

tests/pkg/lwip/Makefile

For the release tests we decided to randomize the PAN ID to not interfere with ongoing RIOT-based experiments in the testbed (see https://github.com/RIOT-OS/Release-Specs/pull/300). However, lwIP currently does not include the Makefile to set the PAN ID at compile time. This fixes that.
Apply the following patch
```diff
diff --git a/drivers/netdev/ieee802154.c b/drivers/netdev/ieee802154.c
index cf5a39d4b4..9068a1e8fa 100644
--- a/drivers/netdev/ieee802154.c
+++ b/drivers/netdev/ieee802154.c
@@ -44,6 +44,7 @@ void netdev_ieee802154_reset(netdev_ieee802154_t *dev)
/* Initialize PAN ID and call netdev::set to propagate it */
dev->pan = CONFIG_IEEE802154_DEFAULT_PANID;
+    printf("PANID: 0x%04x\n", dev->pan);
dev->netdev.driver->set(&dev->netdev, NETOPT_NID, &dev->pan, sizeof(dev->pan)); …
```

tests/pkg/lwip: include default-radio-settings.inc.mk

---

dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
makefiles/tests/tests.inc.mk
makefiles/vars.inc.mk

The overall goal of this PR is to be able to keep running the `compile_and_test_for_board.py` script without destroying ones boards.  Useful if you are a board owner that wants to keep testing on master (say with nightlies, say in a CI).
For example, I could now just run and rerun the following:
```
./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . <MY_BOARD> -c
```
and monitor the results, even after updating a branch.
This is because the hashes now get stored with the results (thanks to the `RIOT_TEST_HASH_DIR` var) which means cleaning will not wipe them out.  Specifically in (`<results_base>/<board>/hashes/<app_dir>/test-input-hash.sha1`)
I tried to do as much as I could with make and only alter the python script when needed.
Clear results folder and run:
``` …
```

Enable compile_and_test_for_board to skip if nothing changed

---

boards/native/Makefile.include
boards/native/doc.txt
cpu/native/Kconfig
cpu/native/Makefile.features
cpu/native/Makefile.include
cpu/native/include/architecture_arch.h
cpu/native/include/c11_atomics_compat_cpu.hpp
cpu/native/include/native_internal.h
cpu/native/irq_cpu.c
cpu/native/native_cpu.c
cpu/native/periph/flashpage.c
cpu/native/periph/spidev_linux.c
cpu/native/periph/timer.c
cpu/native/socket_zep/socket_zep.c
cpu/native/syscalls.c
cpu/native/tramp.S
pkg/wamr/Makefile

Native for Linux x86-64
For the initial version, instead of creating a separate `native64` board, I decided to add the variable `NATIVE_64BIT` to the native board Makefiles. Setting the environment to `NATIVE_64BIT=1` will enable 64-bit mode for native, which is disabled by default.
While I don't necessarily think this is the best long-term solution, it does ensure that all tests run with the same configuration as the 32-bit version. A separate board would require a major refactoring of many tests, which often have different configurations in the Makefile, C code, and Python tests if the board is native, and I didn't want to increase the size of an already large pull request.
Almost all of the same features as the 32-bit version are supported by the 64-bit version, but the following are …

native: Linux/x86_64 support

---

tests/pkg/lwip/Makefile

For the release tests we decided to randomize the PAN ID to not interfere with ongoing RIOT-based experiments in the testbed (see https://github.com/RIOT-OS/Release-Specs/pull/300). However, lwIP currently does not include the Makefile to set the PAN ID at compile time. This fixes that.
Apply the following patch
```diff
diff --git a/drivers/netdev/ieee802154.c b/drivers/netdev/ieee802154.c
index cf5a39d4b4..9068a1e8fa 100644
--- a/drivers/netdev/ieee802154.c
+++ b/drivers/netdev/ieee802154.c
@@ -44,6 +44,7 @@ void netdev_ieee802154_reset(netdev_ieee802154_t *dev)
/* Initialize PAN ID and call netdev::set to propagate it */
dev->pan = CONFIG_IEEE802154_DEFAULT_PANID;
+    printf("PANID: 0x%04x\n", dev->pan);
dev->netdev.driver->set(&dev->netdev, NETOPT_NID, &dev->pan, sizeof(dev->pan)); …
```

tests/pkg/lwip: include default-radio-settings.inc.mk [backport 2024.01]

---

doc/doxygen/src/using-rust.md
examples/rust-gcoap/Cargo.lock
examples/rust-gcoap/Makefile
examples/rust-hello-world/Cargo.lock
examples/rust-hello-world/Makefile
makefiles/cargo-settings.inc.mk
makefiles/cargo-targets.inc.mk
makefiles/info.inc.mk
sys/rust_riotmodules_standalone/Cargo.lock
tests/rust_libs/Makefile
tests/rust_minimal/Cargo.lock
tests/rust_minimal/Makefile

The Rust makefiles contain some stuff that is needlessly complex and was necessary due to earlier Rust versions that have long been unsupported. This cleans them up; see individual commits for details.
Apart from CI, I tested:
* in examples/rust-hello-world: `make BOARD=microbit-v2 CARGO_PROFILE=dev`, with profile values also using `test` and `bench` because they are special cases to Cargo; `rm -rf bin` inbetween to see it's not tapping into old existing files. To test `CARGO_PROFILE=foo`, add this to Cargo.toml:
```toml
[profile.foo]
inherits = "release"
```
* Any of the examples can still just be built, but you can also
* run `rustup override set beta` in the directory of an example and run it there; you'll see everything recompiling because a different compiler is now used, and `make …

makefiles/cargo: Remove CARGO_CHANNEL and other simplifications

---

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c

This PR provides a fix for a double-free in `gnrc_ipv6`.
This occurs because the `_safe_fill_ipv6_hdr` function already calls `gnrc_pktbuf_release`. Therefore, calling it again in `_send_to_self` crashes the devices
Try pinging to a TNT loopback address. Without this PR, it crashes:
```
2024-01-29 12:01:44,285 # ping 2001:67c:254:b0c1:204:2519:1801:bddb
2024-01-29 12:01:44,286 # 8841
2024-01-29 12:01:44,288 # *** RIOT kernel panic:
2024-01-29 12:01:44,290 # FAILED ASSERTION.
2024-01-29 12:01:44,290 # 
2024-01-29 12:01:44,299 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2024-01-29 12:01:44,308 # 	 - | isr_stack            | -        - |   - |    512 (  348) (  164) | 0x20000000 | 0x200001b8
2024-01-29 12:01:44,317 # 	 1 | main …
```

gnrc_ipv6: fix double-free when pinging TNT loopback address [backport 2024.01]

---

boards/common/nrf52/dist/openocd.cfg

This enables RIOT awareness in OpenOCD, so that `info threads` actually shows RIOT's threads.
Run `make debug`, at a point after the scheduler has started:
```
(gdb) info threads 
Id   Target Id                                                Frame 
* 1    Thread 1 "main" (Name: main, Blocked mutex)              sched_arch_idle ()
at /home/maribu/Repos/software/RIOT/master/cpu/cortexm_common/thread_arch.c:529
2    Thread 2 "pktdump" (Name: pktdump, Blocked receive)      _msg_receive (m=0x0 <sched_change_priority>, 
m@entry=0x200016c0 <_stack+1392>, block=block@entry=1)
at /home/maribu/Repos/software/RIOT/master/core/include/thread.h:401
3    Thread 3 "nrf802154" (Name: nrf802154, Blocked any flag) 0x00000898 in _thread_flags_wait_any (mask=mask@entry=32769)
at …
```

boards/common/nrf52: add OpenOCD's RIOT awareness

---

Makefile
doc/doxygen/src/getting-started.md

This improves documentation at two locations:
1. The getting started section previously never stated that `make` is supposed to be run in an applications folder
2. The help message when `make` in the root directory got a `tl'dr` section at the end
1. The CI will add a link to the doc
2. Run `make` in the root directory of the repo. The output should be:
```
make
Welcome to RIOT - The friendly OS for IoT!
You executed 'make' from the base directory.
Usually, you should run 'make' in your application's directory instead.
Please see our Quick Start Guide at:
https://doc.riot-os.org/getting-started.html
You can ask questions or discuss with other users on our forum:
https://forum.riot-os.org
Available targets for the RIOT base directory include:
generate-{board,driver,example,module,pkg,test} …
```

doc/getting-started: point out where to run make

---

cpu/atmega_common/Makefile.features
cpu/atmega_common/include/gpio_ll_arch.h
cpu/sam0_common/Makefile.features
cpu/sam0_common/include/gpio_ll_arch.h
drivers/include/periph/gpio_ll.h
drivers/periph_common/Makefile.dep
tests/periph/gpio_ll/main.c

This adds two functions:
void gpio_ll_switch_dir_output(gpio_port_t port, uword_t outputs);
void gpio_ll_switch_dir_input(gpio_port_t port, uword_t inputs);
The first configures GPIO pins specified by a bitmask as output, the second configures the specified pins as input.
The main use case is to allow bit-banging bidirectional protocols using more basic GPIO peripherals that do not implement open drain mode, such as found e.g. on MSP430, ATmega, or SAM0.
It is not intended to implement this feature on modern MCUs with sophisticated GPIO peripherals.
This PR provides implementations for ATmega and SAM0, the only two GPIO peripherals currently supported by GPIO LL that lack open drain mode.
The GPIO LL test was extended to also test for switching the direction, if supported. …

drivers/periph_gpio_ll: Implement API to switch direction

---

sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c
sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h

Splitting out the no-brain fixes from #20329 that timers must be canceled when the corresponding NIB entry gets deleted.
#20329

ipv6/nib: cancel timers when NIB entry gets deleted

---

sys/include/net/gnrc/ipv6/nib/ft.h
sys/net/gnrc/network_layer/ipv6/nib/nib.c
sys/net/gnrc/network_layer/ipv6/nib/nib_ft.c

The lifetime of a prefix comes as a `uint32_t` and not as a `uint16_t`.
Infinite lifetime is assumed when `0` is passed to `gnrc_ipv6_nib_ft_add()`.
In `_handle_rio()` this was not correctly transformed from the option's value to the input of `gnrc_ipv6_nib_ft_add()`. 
The impact is not really big, it should just run fine.

ipv6/nib: fix router lifetime handling in RIO and fix gnrc_ipv6_nib_ft_add() api

---

pkg/c25519/psa_c25519/edsign.c
pkg/driver_cryptocell_310/psa_cryptocell_310/error_conversion.c

Just a very small fixup for #19954, returning the proper error code in case signature validation fails because of an invalid signature, as documented in the API: https://arm-software.github.io/psa-api/crypto/1.1/api/ops/sign.html#c.psa_verify_message
All PSA Crypto tests should still pass.

sys/psa_crypto: return proper error code for psa_verify_msg

---

cpu/avr8_common/Makefile.dep
sys/Makefile.dep
sys/cpp11-compat/Makefile.dep

Newer toolchains appear to expect the presence of `__dso_handle`, so always enable the module.
The linker will collect unused sections anyway.
`sys/cpp_ctors` builds again on Ubuntu 23.10.
On `master` it would produce
```
/usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/lib/thumb/v7e-m/nofp/libstdc++_nano.a(eh_globals.o): in function `_GLOBAL__sub_I___cxa_get_globals_fast':
./build_nano/thumb/v7e-m/nofp/libstdc++/libsupc++/../../../../../../src/libstdc++-v3/libsupc++/eh_globals.cc:85: undefined reference to `__dso_handle'
/usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: /home/benpicco/dev/RIOT/tests/sys/cpp_ctors/bin/nucleo-wl55jc/tests_cpp_ctors.elf: hidden symbol `__dso_handle' isn't defined
```

sys/cpp_new_delete: always enable the module when C++ is used

---

sys/shell/cmds/gnrc_icmpv6_echo.c
tests/net/gcoap_fileserver/Makefile.ci

If we can't resolve the address, that's not an input error - don't print the help message, instead show a more helpful message.
On `master`:
```
2024-02-07 16:04:48,519 # > ping global.azure-devices-provisioning.net
2024-02-07 16:04:48,520 # ping [-c <count>] [-h] [-i <ms interval>] [-s <packetsize>]
2024-02-07 16:04:48,520 #      [-t hoplimit] [-W <ms timeout>] <host>[%<interface>]
2024-02-07 16:04:48,521 #      count: number of pings (default: 3)
2024-02-07 16:04:48,522 #      ms interval: wait interval milliseconds between sending (default: 1000)"     packetsize: number of bytes in echo payload; must be >= 4 to measure round trip time (default: 4)
2024-02-07 16:04:48,523 #      hoplimit: Set the IP time to life/hoplimit (default: interface config)
2024-02-07 16:04:48,525 #      ms …
```

sys/shell/ping: print error when DNS resolve fails

---

sys/include/net/ipv4/addr.h

This patch adds a macro to statically initialize an IPv4 address.
It's fairly trivial. I have used it and it works in my application code.
- none known

sys/net/ipv4: add IPV4_ADDR_INIT() macro

---

boards/olimex-msp430-h1611/doc.txt
boards/olimex-msp430-h2618/doc.txt
boards/olimex-msp430-h2618/include/periph_conf.h
cpu/msp430/include/x1xx/periph_cpu.h

Change UART configuration to match `olimex-msp430-h1611`. This allows using the [olimex-msp430-arduino-uno][board] breakout board to be used with the `olimex-msp430-h2618` as well.
[board]: https://github.com/RIOT-OS/RIOT-Open-Hardware/tree/main/olimex-msp430-arduino-uno
In addition, to minor MSP430 related doc fixes are sneaked in a individual commits.
With said breakout board attached to the `olimex-msp430-h2618`:
```
make BOARD=olimex-msp430-h2618 -C examples/default flash term
make: Entering directory '/home/maribu/Repos/software/RIOT/master/examples/default'
Building application "default" for "olimex-msp430-h2618" with MCU "msp430".
"make" -C /home/maribu/Repos/software/RIOT/master/boards/olimex-msp430-h2618
"make" …
```

boards/olimex-msp430-h2618: change UART config 

---

release-notes.txt

It is that time again!  Please add changes and comments as needed!
Read it!

release-notes.txt: add 2024.01 release notes

---

cpu/stm32/periph/adc_f4_f7.c

The register access to SMPR1/SMPR2 was incorrect in three aspects:
1. For channels < 10, SMPR1 was cleared but SMPR2 should have been cleared
2. The code was not thread-safe
3. An unneeded write was issued. (The compiler won't combine the in-place bitwise operations into a single read-modify-write sequence on `volatile` memory.)
- Using ADC lines < 10 should no longer corrupt settings on ADC lines >= 10.
- Using line x and y with x!=y concurrently should no longer result in race conditions
Fixes https://github.com/RIOT-OS/RIOT/issues/20261

cpu/stm32/periph_adc: fix register access

---

sys/include/net/dns_mock.h
tests/net/netutils/main.c

This commit makes use of the newly added static initializer for IPv4 addresses. I should have included this in the PR that added the macro but did not think to seek out and make these changes until after it was already merged.
The patch includes an update to the test suite that should prove the macro works.
- PR which added the new macro: #20354

treewide: make use of new IPv4 static init macro

---

core/lib/include/macros/utils.h
tests/unittests/tests-core/tests-core-macros.c

This patch adds a macro that can be used to limit a value to a given range. It also adds the classic `ABS()` macro to go along with the existing `MAX()` and `MIN()` macros.
It's fairly trivial. I have used it and it works in my application code.
- none known

macros/utils: add LIMIT() and ABS() macros

---

sys/include/fmt.h
tests/unittests/tests-fmt/tests-fmt.c

Moin :octopus: 
This adds three missed test-cases for `NULL` arguments.
`make -C tests/unittests/ tests-fmt test`

tests: Add NULL pointer argument test for fmt_lpad/to_lower/str

---

tests/bench/xtimer_load/Makefile
tests/core/thread_flags/Makefile
tests/sys/evtimer_underflow/Makefile
tests/sys/xtimer_hang/Makefile
tests/sys/ztimer_underflow/Makefile

This disables some more flakey native tests.
The failures are all timer related.
(I'm a bit sad about `tests/core/thread_flags`, maybe at some point we could split out or disable the timer test for native.)

ci: disable some more flakey native tests

---

cpu/esp32/stdio_usb_serial_jtag/usb_serial_jtag.c
drivers/ethos/stdio.c
drivers/slipdev/slipdev.c
drivers/slipdev/stdio.c
makefiles/pseudomodules.inc.mk
makefiles/stdio.inc.mk
pkg/tinyusb/cdc_acm_stdio/cdc_acm_stdio.c
sys/fmt/fmt.c
sys/include/stdio_base.h
sys/include/stdio_uart.h
sys/net/application_layer/telnet/stdio_telnet.c
sys/net/application_layer/telnet/telnet_server.c
sys/stdio/Makefile
sys/stdio/stdio.c
sys/stdio_nimble/stdio_nimble.c
sys/stdio_null/stdio_null.c
sys/stdio_rtt/stdio_rtt.c
sys/stdio_semihosting/stdio_semihosting.c
sys/stdio_uart/stdio_uart.c
sys/stdio_udp/stdio_udp.c
sys/usb/usbus/cdc/acm/cdc_acm_stdio.c

This implements the option to have multiple stdio methods active at the same time.
This can be useful to allow e.g. remote debugging while also retaining the possibility for local shell access.
To implement this, all `stdin` implementations are expected to write to a common `stdin_isrpipe`.
Two stdio providers have not been converted to the new interface yet, that means they can't be combined with a second stdio method:
- `stdio_native`: depends on #19002
- ~~`slipdev_stdio`: depends on #18066~~
- `stdio_ethos`: requires a similar patch as `slipdev_stdio`
If only a single stdio method is used, the function pointer/XFA based interface degrades into the traditional in-place implementations of `stdio_init()`/`stdio_write()` to avoid introducing any overhead in the common case.
It is now …

stdio_dispatch: allow to select multiple stdio methods at the same time 

---

cpu/native/async_read.c
cpu/native/include/async_read.h
cpu/native/periph/uart.c

This is needed if for re-initializing the UART device. An example use-case is baud-rate probing.
On Linux, the extended baud-rates are defined in `bits/termios-baud.h` as follows:
```c
/* Extra output baud rates (not in POSIX).  */
#define  B57600    0010001
#define  B115200   0010002
#define  B230400   0010003
#define  B460800   0010004
...
```
As such, I'm not sure if they are available on other platforms too, so I enabled them for Linux only.
The following should be a valid use-case:
```c
static uint32_t const baud_rates[] = {
230400,
460800,
921600,
3000000,
};
int res;
for (unsigned i = 0; i < ARRAY_SIZE(baud_rates); i++) {
uart_poweroff(UART_DEV(0));
res = uart_init(UART_DEV(0), baud_rates[i], device_rx_handler, dev);
assert(res == 0);
res = device_probing_procedure(UART_DEV(0));
if …
```

cpu/native/periph/uart: uart_poweroff() closes the file descriptor + extended baud-rate support on Linux

---

cpu/native/async_read.c
cpu/native/periph/uart.c

Fix previous [PR](https://github.com/RIOT-OS/RIOT/pull/20365).
https://github.com/RIOT-OS/RIOT/pull/20365

cpu/native: fix native_async_read_remove_handler() + enable all baudrates

---

pkg/flashdb/Kconfig
pkg/flashdb/include/fal_cfg.h
pkg/flashdb/mtd/fal_mtd_port.c
tests/pkg/flashdb_fal_cfg/Makefile
tests/pkg/flashdb_fal_cfg/Makefile.ci
tests/pkg/flashdb_fal_cfg/main.c
tests/pkg/flashdb_mtd/Makefile.ci
tests/pkg/flashdb_vfs/main.c

I wanted to split out the FlashDB fal_cfg partition offset fix from #19557.
This also adds a short test to see if all partitions initialize fine and it adds a configuration option for the sector size.
The test very much reminds of an `auto_init` module for FLashDB. 
Test output of `BOARD=same54-xpro make -C tests/pkg/flashdb_fal_cfg flash term`
```
2024-01-03 00:09:14,858 # main(): This is RIOT! (Version: 2024.01-devel-475-g2de30-pr/flashdb_cfg_enhancement)
2024-01-03 00:09:14,862 # Initializing FlashDB KVDB partition part0
2024-01-03 00:09:14,869 # [I/FAL] Flash Abstraction Layer (V0.5.99) initialize success.
2024-01-03 00:09:14,879 # Initializing FlashDB KVDB partition part1
2024-01-03 00:09:14,883 # Initializing FlashDB TSDB partition part2
2024-01-03 00:09:14,887 # Initializing …
```

pkg/flashdb: enhance FAL config

---

tests/periph/spi_dma/Makefile.ci

The `Makefile.ci` was intended to be read and generated by command line utilities and the contents should look exactly like this:
```
BOARD_INSUFFICIENT_MEMORY += \
board_a \
board_b \
... \
#
```
No fancy schmancy, no `include`, no nothing. This fixes the format.
The tools in `dist/tools/insufficient_memory` should work again.
None

tests/periph/spi_dma: fix Makefile.ci

---

dist/tools/insufficient_memory/create_makefile.ci.sh
dist/tools/insufficient_memory/update_insufficient_memory_board.sh

On RISC-V a RAM overlow is reported as:
/opt/xpack-riscv-none-elf-gcc-13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: section .stack VMA [80003f00,80003fff] overlaps section .bss VMA [800000a8,80003fb7]
This extends the list of patters detecting RAM overflow.
The tool should now correctly classify RAM overflows of RISC-V boards.
None

dist/tools/insufficient_memory: add RISC-V failure mode

---

drivers/include/periph/spi.h
drivers/w5100/w5100.c

This adds `spi_transfer_u16_be()` intended to replace the free coded (and buggy) variant in the w5100 driver. This will also be useful for https://github.com/RIOT-OS/RIOT/pull/20301 that needs the same functionality.
The W5100 should work as before on little endian systems, and show now also work on big endian systems. (E.g. running `native` on a MIPS router with OpenWRT and using the SPI sysfs interface may work.)

drivers/periph_spi: Add `spi_transfer_u16_be()`

---

boards/common/makefiles/stdio_cdc_acm.dep.mk

This fixes compilation issues in `tests/pkg/tinyusb_netdev` with newer versions of the RISC-V toolchain due to two competing USB stacks being pulled in. With the older toolchain the build system warns:
The following features may conflict: periph_usbdev tinyusb_device
But builds fine (even though surprises at runtime are likely). The newer toolchain takes an issue with the same symbol being linked in more than once (and more than one instance not being `weak`).
` make BOARD=seeedstudio-gd32 -C tests/pkg/tinyusb_netdev` should no longer pull in two USB stacks.
None

boards/common/makefiles/stdio_cdc_acm.dep.mk: fix

---

sys/include/net/nanocoap/cache.h
sys/net/application_layer/nanocoap/cache.c
tests/unittests/tests-nanocoap_cache/tests-nanocoap_cache.c

This adds a pair of functions to the nanocoap_cache module to generate cache keys only based on the options in a request. These can be used to correlate individual requests of a blockwise tranfer with each other. For example in a larger coreconf request.
It would still be up to the user to match the peers and the coap method code in the requests involved.
I've extended the unittest for the nanocoap_cache module
Could be useful for CORECONF and such.

nanocoap/cache: Extend with option-only cache keygen

---

examples/suit_update/Makefile
examples/suit_update/main.c
tests/pkg/edhoc_c/Makefile
tests/pkg/edhoc_c/main.c
tests/riotboot_flashwrite/Makefile
tests/riotboot_flashwrite/main.c

Apps don't need to create the nanoCoAP server thread manually, they can just pull in `nanocoap_server_auto_init`.

make use of nanocoap_server_auto_init

---

examples/gcoap/client.c
sys/include/net/gcoap.h
sys/net/application_layer/gcoap/gcoap.c

Enables some client-side observe operation of gcoap (and improve server side a bit).
Currently, when registering an observe from a gcoap client, the first notification consumes the request memo state. Any following notifications are therefore dropped silently afterwards.
When I Initially saw this behavior I thought it's a bug, but turns out gcoap never had client-side observe handling :open_mouth: 
This PR tries to improve the situation like this: requests initiated with an observe option are simply kept open beyond the first response.
The first commit of this PR adds some client side observe functionality to examples/gcoap to reproduce this behavior.
With two `native` instances, check out the first commit and follow below steps.
```
sudo ./dist/tools/tapsetup/tapsetup
BOARD=native …
```

gcoap: add some client-side observe handling

---

tests/pkg/edhoc_c/Makefile

The CoAP thread stack size needs to be the same as the main thread stack size to accommodate the EDHOC stack requirements. This was lost when moving to the common CoAP server code.
Lo longer crashes on hardware, e.g. `nrf52840dk`:
<details><summary>test output</summary>
```
> ifconfig
ifconfig
Iface  6  HWaddr: 3A:F1  Channel: 26  NID: 0x23  PHY: O-QPSK 
Long HWaddr: AA:CC:F4:7B:67:C4:BA:F1 
State: IDLE 
ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
6LO  IPHC  
inet6 addr: fe80::a8cc:f47b:67c4:baf1  scope: link  VAL
init handshake fe80::a8cc:f47b:67c4:baf1%6 5683
inet6 group: ff02::1:ffc4:baf1
> init handshake fe80::a8cc:f47b:67c4:baf1%6 5683
[initiator]: sending msg1 (37 bytes):
0x0d 0x00 0x58 0x20 0x8d …
```

tests/pkg/edhoc_c: bump CoAP thread stack size

---

pkg/openthread/doc.txt
sys/net/ieee802154.txt

The Thread protocol is not easily accessible because its specs are behind EULAs, and many intro articles are super vague.
I've found a good one at https://openthread.io/guides/thread-primer, linking it where relevant, and removed
* Look at the generated docs.
<del>This is a draft PR until I've verified that the generated help looks nice.</del>
[edit] Docs look good now after two rounds through markdown, ready for review.

doc: Link OpenThread primer, cleanup

---

examples/dtls-sock/Makefile

It should be possible to test DTLS via `::1`, but this requires 4 slots in the credman instead of just two.
Running both server and client on the same app should now succeed; or at least no longer fail when adding the credentials.
Found while testing https://github.com/RIOT-OS/RIOT/pull/20196

examples/dtls-sock: fix credman capacity

---

Makefile.include

$(info ...) produces output to stdout, which in our makefiles is sometimes used to produce machine readable data, eg. in info-build-json; this fixes such a case.
```
$ cd tests/minimal
$ make BOARD=f4vi1 info-build-json | jq
```
Before, this erred due to non-JSON output in the text. After, it prettyprints.
Had something similar in https://github.com/RIOT-OS/RIOT/pull/20109

makefile: Don't $(info) when the output can break info-build-json

---

tests/net/gnrc_rpl/Makefile
tests/sys/ztimer_msg/Makefile

As the title says, this disables `tests/sys/ztimer_msg` ([example flaky failure](https://ci.riot-os.org/details/c25e00f3fb704a148d452199a190d1cc/tests)) and tries to disable `tests/net/gnrc_rpl` for good, which was already marked as disabled.
I theorize that the reason the RPL test was still run in the order of evaluation. Due to the default recursive definitions of variables in Makefile often the order of definition can change while still achieving the same result, except when the order does matter. This is a bit of an unfortunate default.
In the CI the RPL test should not be run on native. (This has `CI: full build` set so that we can observe this even without hitting merge.)
None

tests: disable flaky tests on `native` in the CI

---

sys/include/net/nanocoap.h
sys/include/net/nanocoap_sock.h
sys/net/application_layer/nanocoap/nanocoap.c
sys/net/application_layer/nanocoap/sock.c

This is pretty subtle: `coap_opt_put_uri_pathquery()` will detect the presense of a query parameter, `coap_opt_put_uri_path()` will not.
That means that when you request `path/to/resource?option=1` with `coap_opt_put_uri_path()` you get the path `resource?option=1` whereas with `coap_opt_put_uri_pathquery()` you get the path `resource` with query parameter `option=1`.
We really want the latter.

nanocoap_sock: always use coap_opt_put_uri_pathquery()

---

doc/doxygen/src/roadmap.md

This adds Home-Assistant integration to the roadmap
Read the roadmap changes
None

Roadmap: Add Home-Assistant integration on the roadmap

---

cpu/stm32/periph/eeprom.c

While looking through the `eeprom.c` code, I discovered an off-by-one error in the `DEBUG` statements. This fixes that by subtracting 1 from the pointer before we dereference. I also add debug statements to the `eeprom_write` with the same fix
run the code with `ENABLE_DEBUG 1` and see it prints correct values

periph/eeprom: fix off-by-one error in debug statement

---

boards/common/makefiles/stdio_cdc_acm.dep.mk
dist/tools/ci/print_toolchain_versions.sh
examples/asymcute_mqttsn/Makefile.ci
examples/cord_ep/Makefile.ci
examples/cord_epsim/Makefile.ci
examples/cord_lc/Makefile.ci
examples/emcute_mqttsn/Makefile.ci
examples/javascript/Makefile.ci
makefiles/arch/riscv.inc.mk
makefiles/cargo-targets.inc.mk
tests/bench/xtimer_load/Makefile
tests/core/thread_flags/Makefile
tests/net/gcoap_dns/Makefile.ci
tests/net/gnrc_dhcpv6_relay/Makefile.ci
tests/net/gnrc_ipv6_ext/Makefile.ci
tests/net/gnrc_netif_ipv6_wait_for_global_address/Makefile.ci
tests/net/gnrc_rpl/Makefile
tests/net/gnrc_rpl_srh/Makefile.ci
tests/net/gnrc_sock_dns/Makefile.ci
tests/pkg/edhoc_c/Makefile.ci
tests/pkg/lwip/Makefile.ci
tests/sys/conn_can/Makefile.ci
tests/sys/evtimer_underflow/Makefile
tests/sys/pthread_cooperation/Makefile.ci
tests/sys/xtimer_hang/Makefile
tests/sys/ztimer_msg/Makefile
tests/sys/ztimer_overhead/Makefile
tests/sys/ztimer_underflow/Makefile

This fixes compilation issues in `tests/pkg/tinyusb_netdev` with newer versions of the RISC-V toolchain due to two competing USB stacks being pulled in. With the older toolchain the build system warns:
The following features may conflict: periph_usbdev tinyusb_device
But builds fine (even though surprises at runtime are likely). The newer toolchain takes an issue with the same symbol being linked in more than once (and more than one instance not being `weak`).
` make BOARD=seeedstudio-gd32 -C tests/pkg/tinyusb_netdev` should no longer pull in two USB stacks.
None
This contains fixed needed after updating the RISC-V toolchain in the CI
Build `riotbuild` from https://github.com/RIOT-OS/riotdocker/pull/248 locally, then run
```
env DOCKER_IMAGE=<LOCAL_BUILD_ID> …
```

tree wide: accomodate RISC-V toolchain update & boards/common/makefiles/stdio_cdc_acm.dep.mk: fix [backport 2024.01]

---

drivers/at/at.c
drivers/include/at.h
tests/drivers/at/Makefile
tests/drivers/at/main.c
tests/drivers/at/tests-with-config/emulate_dce.py
tests/drivers/at/tests-with-config/native_stdin

Modems, especially mobile ones, can be very shaky. As such, in the scope of debugging, it is very helpful to know failure reasons.
Luckily, many modems can offer detailed error codes. Once this feature is enabled, they will answer with `+CME ERROR: <error_code>` (or `+CMS ERROR: <error_code>` for SMS-related commands), where `<error_code>` is either an integer error code or a string. This is much better than the standard `ERROR` response, which provides no further information.
Unfortunately, in the current state, the AT driver does not parse any errors. Generally, if the response is not `OK` then `-1` is returned and that's it.
This patch enables extended error parsing. If a `+CME/+CMS` answer is detected, most functions will return `-AT_ERR_EXTENDED`, and the `<error_code>` will be …

drivers/at: parse +CME/+CMS responses and save error value

---

cpu/esp8266/vendor/esp-idf/esp8266/source/startup.c
cpu/esp_common/vendor/xtensa/xtensa_vectors.S

Some vendor files we have in the ESP CPU area were modified to pick up our defines, in particular MCU_ESP8266. Our MCU went away in #20397, this fixes things by doing a change in the style of what was already done there for the ESP CPUs. (My original checks left those out because those were vendor files, and most other vendors have all kinds of MCU_SOMETHING_INTERNAL defines that are unrelated to our MCU defines).
* ESP8266 comes up with any applicaiton (I don't have one, reviewers please check)
Follow-up-for: https://github.com/RIOT-OS/RIOT/pull/20397 (where I broke this)
Closes: https://github.com/RIOT-OS/RIOT/pull/20409 (which inspired this)
Closes: https://github.com/RIOT-OS/RIOT/pull/20415 (which would also solve the issue but also keep the MCU_ variable mess)
Thanks @maribu for …

cpu/esp: Use CPU_ESP8266 define instead of the removed MCU_ESP8266

---

cpu/native/panic.c
cpu/native/periph/pm.c

When `native` hits a failed assertion, it will exit but the exit code will still be `EXIT_SUCCESS`.
Fix this by setting an error exit code in the `panic_arch()` handler.
I added an `assert(0)` in `examples/hello-world`:
```
main(): This is RIOT! (Version: 2024.04-devel-291-gd83ec)
Hello World!
You are running RIOT on a(n) native board.
This board features a(n) native CPU.
examples/hello-world/main.c:32 => *** RIOT kernel panic:
*** halted.
native: exiting
22 benpicco@T430s ~/dev/RIOT/examples/hello-world (git)-[cpu/native_assert-reval] %
```

cpu/native: return error code on failed assertion

---

.vscode/c_cpp_properties.json

When run from Windows via WSL, VS Code just won't find the `compile_commands.json` otherwise.
1. Install VS Code in Windows (not in WSL)
2. Install WSL + Ubuntu
3. Install clang, clang, gcc-multilib, python3-serial, etc. in Ubuntin in WSL on Windows
4. Clone RIOT in Ubuntu in WSL on Windows, run `make compile-commands` in `examples/hello-world`
5. Install the WSL extension in VS Code in Windows (not in WSL)
6. Reboot WSL so that the WSL extensions gets automagically installed on the next run
7. Within Ubuntu/WSL inside the RIOT Repo run `code .` to launch VS Code in Windows, connected to WSL
8. Open `examples/hello-world/main.c`
9. Check if the `RIOT_BOARD` and the `RIOT_CPU` macros are defined an the value is presented as `"native"` when hovering with the mouse
In `master`, this doesn't …

vscode: Add hard-coded path to compile_commands.json

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c
tests/net/gnrc_ipv6_nib_6ln/main.c

This PR directly addresses the changes suggested in #20377 
Tests are adjusted accordingly.
Fixes #20377

gnrc_ipv6_nib: Ignore PIO with on-link flag

---

boards/feather-nrf52840-sense/doc.txt
boards/feather-nrf52840/doc.txt

Make sure the board name (needed for `BOARD=`) is mentioned in the documentation.
Look at the CI-generated docs for [`boards/feather-nrf52840`](https://ci.riot-os.org/results/130163c049924aafb514f5d690466a9b/doc-preview/group__boards__feather-nrf52840.html) and [`boards/feather-nrf52840-sense`](https://ci.riot-os.org/results/130163c049924aafb514f5d690466a9b/doc-preview/group__boards__feather-nrf52840-sense.html).

boards/feather-nrf52840*: doc cleanup

---

boards/native64/doc.txt
cpu/native/Kconfig
cpu/native/Makefile.features
examples/rust-gcoap/Cargo.lock
examples/rust-hello-world/Cargo.lock
sys/rust_riotmodules_standalone/Cargo.lock
tests/rust_minimal/Cargo.lock

This updates the riot-sys dependency and then removes the lock-out of Rust on NATIVE_64BIT builds.
* Green CI
Back in https://github.com/RIOT-OS/RIOT/pull/20315, Rust was excluded because it had build failures. https://github.com/RIOT-OS/rust-riot-sys/pull/40 works around the failures.
Thanks @fzi-haxel for preparing everything!
[edit:] Found some more errors, which so far all look like i32 vs isize mismatches. I'm on it; definitely easier to fix here than when some 16bit arch support is added :-D

cpu/native: Enable Rust on 64bit

---

pkg/flashdb/mtd/fal_mtd_port.c
tests/pkg/flashdb_fal_cfg/main.c

Instead of doing random things with uninitialized data, abort the test if there is no MTD device.
Now a clear error message is printed in absence of a MTD device instead of a random failure.

tests/pkg/flashdb_fal_cfg: abort test if no MTD device is configured

---

doc/memos/rdm-draft-chrysn-boardnames.md
doc/memos/rdm0003.md

I was recently *very* frustrated with how off-brand boards were documented.
This is supposed to fix this:
[rendered](https://github.com/chrysn-pull-requests/RIOT/blob/rdm-board-names/doc/memos/rdm-draft-chrysn-boardnames.md)
There are probably issues around for concrete boards / board groups whose naming was problematic, but I haven't found them yet.

RDM: Naming boards

---

drivers/include/pcf857x.h

If not included before, IS_USED macro from modules.h is undefined, leading to such errors:
error: missing binary operator before token "("
```shell
make -C tests/drivers/pcf857x/ BOARD=native
```
Depends on https://github.com/RIOT-OS/RIOT/pull/20430
Depends on https://github.com/RIOT-OS/RIOT/pull/20431

drivers/pcf857x: fix missing include kernel_defines.h

---

drivers/include/pcf857x.h
drivers/pcf857x/pcf857x.c

The driver only supports addressing GPIOs by their index, (ab)using `gpio_t` for that will break on platforms that encode GPIO values differently.
I don't have the hardware to test this, but this should be a simple conversion as the driver expects that `gpio_t` just encodes the pin number in lower 3 bits of `gpio_t`.
It never accesses the 'port' bits (which would be implementation defined anyway).
triggered some unnecessary workarounds in #20431

drivers/pcf857x: stop (ab)using gpio_t

---

boards/feather-nrf52840-sense/Makefile.dep

Declare that the accelerometer/gyroscope/temperature sensor `lsm6ds33` is available on the `feather-nrf52840-sense` so it is recognized by SAUL.
`make -C tests/drivers/saul BOARD=feather-nrf52840-sense term`
this adds the following to the output compared to `master` (example values):
```
2024-02-27 19:41:53,945 # Dev: lsm6dsxx Type: SENSE_ACCEL
2024-02-27 19:41:53,946 # Data: [0]           0 mgₙ
2024-02-27 19:41:53,946 #       [1]          37 mgₙ
2024-02-27 19:41:53,947 #       [2]        1030 mgₙ
2024-02-27 19:41:53,948 # 
2024-02-27 19:41:53,949 # Dev: lsm6dsxx Type: SENSE_GYRO
2024-02-27 19:41:53,949 # Data: [0]         3.2 dps
2024-02-27 19:41:53,950 #       [1]        -5.5 dps
2024-02-27 19:41:53,950 #       [2]        -1.6 dps
2024-02-27 19:41:53,950 # 
2024-02-27 19:41:53,951 # …
```

boards/feather-nrf52840-sense: declare lsm6ds33 accelerometer

---

bootloaders/riotboot_common.mk
cpu/cortexm_common/Makefile.features
cpu/cortexm_common/ldscripts/cortexm_base.ld
cpu/cortexm_common/ldscripts/cortexm_rom_offset.ld
cpu/gd32v/Makefile.include
cpu/riscv_common/Makefile.features
cpu/riscv_common/Makefile.include
cpu/riscv_common/ldscripts/riscv.ld
cpu/riscv_common/ldscripts/riscv_vars.ld
dist/tools/insufficient_memory/create_makefile.ci.sh
drivers/Makefile.dep
drivers/include/mtd_flashpage.h
drivers/mtd_flashpage/mtd_flashpage.c
features.yaml
makefiles/features_existing.inc.mk
sys/Makefile.include
sys/riotboot/Makefile.include
sys/slot_aux/Makefile.include
tests/drivers/mtd_flashpage/Makefile
tests/drivers/mtd_flashpage/Makefile.ci
tests/drivers/mtd_flashpage/main.c

The issue for needing a config area on the MCU flash has been brought up multiple times now.
So far the 'solution' has been to arbitrarily define a flash page and using the `periph_flashpage` API to write to it.
This has several issues, the most obvious being non-portability and silent firmware corruption if the firmware reaches into the chosen flash page region.
To fix this, this defines a new AUX Slot (similar to SLOT0/SLOT1 with SUIT) that occupies a linker section. This way, if things do not fit, it will fail at link-time and not at run-time.
The `mtd_flashpage` driver has been extended to implement the pagewise API. (#19258) This makes use of it more straightforward (tests in `tests/mtd_raw` now pass) and allows the user to interact with this through the MTD API, allowing to move the …

drivers/mtd_flashpage: allow to define AUX slot on flash

---

pkg/uwb-dw1000/doc.txt

The doc.txt file of the uwb-dw1000 package included to the incorrect README.md file (from pkg/ucglib) instead of pkg/uwb-dw1000, which led to the generation of incorrect Doxygen documentation.
With the change applied, the Doxygen documentation should still successfully build and now have the correct description of the UWB-DW1000 package.
No separate issue opened.

pkg/uwb-dw1000: fix README include

---

examples/filesystem/Makefile
examples/filesystem/README.md

This pull request updates the filesystem example. In a previous commit https://github.com/RIOT-OS/RIOT/commit/e657590ce09dd1ad9bc80b57e9945446d4766fef the behaviour of the filesystem example was changed, but the README was not updated, making it hard for new users to apply it to an actual board.
Therefore, the README was extended.
Furthermore, the Makefile was extended to add an option to increase stack size for larger flash memories to avoid Kernel Panics due to a stack overflow.
The changes were tested with a Nordic Semiconductor nRF52840-DK development board. The behaviour of the `native` implementation is unchanged and reflects the behavior shown in the README.
The behaviour with a real board should equally reflect the behavior shown in the README in the section about the `nrf52840dk` …

examples/filesystem: Update README and increase default stack size

---

dist/tools/doccheck/exclude_simple
doc/doxygen/RIOTDoxygenLayout.xml

Beginning with doxygen 1.9.8 "Modules" are renamed to "Topics" (see [here](https://github.com/doxygen/doxygen/issues/10562) and [here](https://github.com/doxygen/doxygen/issues/3319#issuecomment-1720923984)). This patch adds the new entry to the layout file. Having both, "Modules" and "Topics" in the layout file should generate similar output for older and newer doxygen versions.
Run `make doc` and check the output. Verify whether the menus (navigation bars) on the left and on top contain either "Modules" or "Topics". Should work with all known doxygen versions.

doc: doxygen: add "Topics" to menus

---

README.md
doc/doxygen/src/mainpage.md

During the [last VMA](https://forum.riot-os.org/t/notes-virtual-maintainer-assembly-vma-2024-02/4118#twitterx-freeze-5min-emmanuel-11) we decided to abandon Xitter. So let's replace also the link to the now obsolete account with a link to our mastodon account.
- Check the [VMA notes](https://forum.riot-os.org/t/notes-virtual-maintainer-assembly-vma-2024-02/4118#twitterx-freeze-5min-emmanuel-11) that we indeed agreed upon dropping Xitter
- Check the generated doc
None

doc: replace obsolete xitter link with mastodon link

---

boards/common/nucleo144/include/board.h
boards/nucleo-u575zi-q/Makefile
boards/nucleo-u575zi-q/Makefile.dep
boards/nucleo-u575zi-q/Makefile.features
boards/nucleo-u575zi-q/Makefile.include
boards/nucleo-u575zi-q/doc.txt
boards/nucleo-u575zi-q/include/periph_conf.h
cpu/stm32/periph/uart.c

This PR adds support for the NUCLEO-U575ZI-Q board.
+ Tested UART based on RIOT shell
+ Tested pwm via `tests/periph/pwm`
+ LEDs work
+ Tested USB via `usbus_minimal` & `usbus_hid`

boards/nucleo-u575zi-q: Add support

---

makefiles/features_modules.inc.mk

This does not change binaries, but it drops a lot of bogus modules that do not exist from `make info-modules`.
1. Run `make BOARD=<SOME_BOARD> -C tests/periph/gpio_ll info-modules` with `master` and this PR. Modules like `periph_init_gpio_ll_input_pull_down` should disappear.
2. Bun `make RIOT_CI_BUILD=1 BOARD=<SOME_BOARD> -C tests/periph/gpio_ll` in `master` and in this PR. The binaries should not differ.
None

build system: drop bogus periph_init_gpio_ll* modules

---

core/lib/init.c
cpu/native/native_cpu.c
sys/embunit/TestRunner.c
sys/include/embUnit/TestRunner.h
tests/Makefile.tests_common
tests/sys/pthread_condition_variable/Makefile
tests/unittests/Makefile
tests/unittests/main.c

When no more threads are running, we can exit `native` for all tests.
In this case, also return `_native_retval` instead of `EXIT_SUCCESS`.

tests: exit `native` with error value on failure

---

cpu/sam0_common/periph/rtc_rtt.c

On power-on reset, all RTC register values are 0, but January is expected to be month 1.
Since `struct tm` expects January to be 0, we subtract 1 from the month, leading to a negative month after POR.
This of course causes all kinds of trouble, so only subtract 1 if the month will not turn out negative. 
The issue occurs when reading the RTC before the first second has ticked:
```C
int main(void)
{
struct tm now;
rtc_get_time(&now);
_print_time(&now);
return 0;
}
```
on `master` this will print
```
2024-03-07 11:24:16,694 # main(): This is RIOT! (Version: 2024.04-devel-361-g31d23)
2024-03-07 11:24:16,694 # 2020-00-00 00:00:00
```
With this patch, we get a valid date
```
2024-03-07 11:29:32,008 # main(): This is RIOT! (Version: 2024.04-devel-363-ge3708-cpu/sam0_common-rtc-0)
2024-03-07 …
```

cpu/sam0_common: RTC: avoid negative month after POR

---

Makefile.base
Makefile.include
pkg/nanopb/Makefile.gensrc

This PR aims to
- make the results of GENSRC available to all modules (and be robust against multiple dependencies against the same protobuf schema)
- compile protobuf schema outside the current directory without caring much about the shortcomings of protoc
To achieve that
- The GENSRC target is moved into a more central place. Before, it did run on every module build. GENSRC is known already much earlier and can be run once for all modules. This PR suggests to run it once after pkg-prepare.
- The output of nanopb is put into a central place in $(BINDIR)/nanopb to make it accessible to all modules which depend on nanopb. While not normally required, this allows for multiple modules using the generated sources. Without the changes of this PR the options for usage by multiple modules was to …

Makefile.{include,base},pkg/nanopb: fix target deps & code generation

---

tests/unittests/tests-fmt/tests-fmt.c

Hej :shark: 
This adds the test case to the unit-tests of `scn_u32_hex()` in which parsing is aborted on non hex characters.
`make -C tests/unittests/ tests-fmt term`
This lacking coverage was brought up twice! In #19894 and #19027
There are still test holes remaining in that unittest...

tests: Cover API of scn_u32_hex in the unittest

---

examples/psa_crypto/main.c

There was an error in the compile time conditionals that did not consider secure elements.
This means that when running the example with a secure element, the ECDSA functions were not executed anymore. 
This provides a fix for that. 
When running `SECURE_ELEMENT=1 BOARD=nrf52840dk make flash term` on master
```
2024-03-12 14:23:31,097 # main(): This is RIOT! (Version: 2024.01-devel-1054-g03c05f-pr/run-ecdsa-functions-with-secure-elements)
2024-03-12 14:23:31,098 # HMAC SHA256 took 56402 us
2024-03-12 14:23:31,098 # Cipher AES 128 took 68853 us
2024-03-12 14:23:31,099 # All Done
2024-03-12 14:25:03,072 # Exiting Pyterm
```
After applying these changes:
```
2024-03-12 14:41:09,059 # main(): This is RIOT! (Version: 2024.01-devel-1054-g03c05f-pr/run-ecdsa-functions-with-secure-elements) …
```

examples/psa_crypto: Fix modules to run ECDSA on SEs

---

tests/unittests/tests-fmt/tests-fmt.c

Follow-up to #20458 
@kfessel discovered that the tests were still insufficient. This adds the missing cases.
Technically, all ascii characters could be tested separately...
`make -C tests/unittests/ tests-fmt term`
#19894

tests: Add cases to the scn_u32_hex unittest

---

tests/sys/psa_crypto_se_ecdsa/Makefile.ci
tests/sys/psa_crypto_se_mac/Makefile.ci

My last two PRs (#20460 and #20461) slightly increased the memory sizes, which makes two tests too large for the Arduino Leonardo.
I added it to the list of boards with insufficient memory.

tests/sys/psa_crypto_se*: add arduino leonardo to board insufficient memory list

---

examples/lwm2m/Makefile
examples/lwm2m/README.md
examples/lwm2m/lwm2m_cli.c
pkg/wakaama/Kconfig
pkg/wakaama/contrib/objects/Kconfig
pkg/wakaama/contrib/objects/Kconfig.light_control
pkg/wakaama/contrib/objects/light_control.c
pkg/wakaama/include/objects/light_control.h

This PR adds the implementation of the [Light Control LwM2M object](https://raw.githubusercontent.com/OpenMobileAlliance/lwm2m-registry/prod/3311.xml). The object takes care of the resources, the actual interaction to the light is done via a callback registered during instance creation. The wakaama example has been adapted to instantiate this object once ~if the `LED0` is present~.
- Check that the example works and the LED0 can be accessed.
None

pkg/wakaama: add Light Control object implementation

---

doc/memos/README.md

fix the list of available RDMs in the readme (was missing rdm0003)
nothing much ;)

rdm/README: add rdm0003 to the list

---

sys/include/net/sock/udp.h
sys/net/application_layer/nanocoap/sock.c

NanoCOAP is already agnostic towards the IP version, but there is one part where the code checks if the destination address is link-local, to see if an interface id is needed.
Since there are no link-local addresses with IPv4, we can simply not do that in the v4 only case.
Build an LWIP IPv4 application with the `nanocoap_vfs` module (and default shell commands)
```
2024-03-17 17:42:20,985 # > ifconfig
2024-03-17 17:42:20,990 # Iface ET0 HWaddr: 7c:df:a1:02:ec:d4 Link: up State: up
2024-03-17 17:42:20,991 #         Link type: wireless
2024-03-17 17:42:20,998 #         inet addr: 10.53.4.195 mask: 255.255.0.0 gw: 10.53.0.1
2024-03-17 17:42:22,763 # > ncget coap://134.102.218.18/
2024-03-17 17:42:22,791 # /test
2024-03-17 17:42:22,792 # /validate
2024-03-17 17:42:22,814 # /hello
2024-03-17 …
```

nanocoap_sock: add support for IPv4

---

Makefile.include
makefiles/libc/picolibc.mk

Before we disabled the warning about RWX segments only for picolibc, but this issue is popping up on more and more toolchains (looking at MSP430 and RISC-V). Other than on `native`/`native64`, there is no MMU to enforce whatever permissions the segments contain anyway. (And writing to ROM with regular store instructions will not be possible even without the need for an MMU.)
So let's just globally disable this warning, unless building for `native` and `native64`.
Building in `master` with https://github.com/RIOT-OS/riotdocker/pull/248 will issue the RWX warning for every app now. And so does building on Alpine for MSP430.
With this PR the in our context not helpful warning is disabled.
Not necessary, but useful for https://github.com/RIOT-OS/riotdocker/pull/248

build sytem: add `--no-warn-rwx-segments` to linker

---

tests/periph/uart/main.c

The first change is to improve the visibility of incoming CRs (carriage return). They will now be shown as `\r`. Also, the LF (that usually comes after a CR) is now shown inside `[`..`]`, not after the closing `]`.
The second change is a re-implementation of [PR20128](https://github.com/RIOT-OS/RIOT/pull/20128). I hope that @benpicco is not offended by it. I had this change lying around for more than a year, sorry about that. I want to include the change in the current PR because I consider the code in PR20128 too "hackish".
I've tested the change on a `sodaq-sara-sff` board which has a Ublox SARA N310. For that a few extra steps are needed because the Ublox needs two pins to be `ON`, plus one pin needs to be toggled low for roughly one second. Otherwise the Ublox remains off.
After that: …

Refactor tests periph uart

---

sys/usb/usbus/usbus_control.c

this PR intends to fix #20474. In current master, a device doesn't behave properly when `dfu-util` is sending a detach request.
Once this request is sent, device must reboot into bootloader. However, it doesn't work in master since #17090.
#17090 introduces (among other things) a way for `USBUS` to answer standard requests (received on the control endpoints aka EP0).
However, DFU is an USB class which uses the same endpoints to operate. When `dfu-util` sends the detach request, `USBUS` wrongly interprets it as a standard `get_status` request so the stack answers it instead of the DFU interface.
Indeed, both the DFU detach request and the standard `get_status` have the same request number. `USB_SETUP_REQ_GET_STATUS` and `DFU_DETACH` are both 0x00.
Thus, this PR introduces a new check to …

sys/usbus: answer get_status if request is standard type

---

makefiles/deprecated_modules.inc.mk
makefiles/pseudomodules.inc.mk
sys/Makefile.dep
sys/net/gnrc/Makefile.dep
sys/net/gnrc/pktbuf/Makefile.include
sys/shell/Makefile.dep
sys/shell/doc.txt
tests/core/sched_change_priority/Makefile

This PR removes a bunch of deprecated modules that I found while looking at the `makefiles/pseudomodules.inc.mk` so I guess it is time to do some cleanup.
There are still some deprecated modules in the wild, but they will need a little bit more attention so I think it is better if this is done in another PR.
I think CI should be enough but you could run a quick `grep` to ensure I didn't forget something.
None.

treewide: remove deprecated modules

---

boards/rpi-pico/Kconfig
boards/rpi-pico/Makefile.features
boards/rpi-pico/include/periph_conf.h
cpu/rpx0xx/include/periph_cpu.h
cpu/rpx0xx/periph/pwm.c

This PR adds an initial PWM peripheral driver for RP2040-based board.
PWM IP block is feed by the system clock (fixed) so it is not very flexible but it works as intended.
So far I've only add the LED pin as PWM as it is convenient to check with the `osci` command from `tests/periph/pwm`
However, I've also tested locally other pins to check the overall logic.
Play with `tests/periph/pwm` on `rpi-pico` for instance.
None.

cpu/rpx0xx: add initial pwm support

---

core/lib/include/cib.h
tests/unittests/tests-core/tests-core-cib.c

This patch adds some more peek functions to `cib`. It also makes some minor fixes to the existing unit tests and doc.
``` bash
cd tests/unittests
make all 
make tests-core test
```
none known

core/lib/cib: add new functionality

---

doc/doxygen/src/getting-started.md

Check if the links in "Windows users can refer to this guide to setup the development environment on Windows." work in the doc preview generated by the CI.
Reported in https://matrix.to/#/!pqHdpanAvkJvlCwUDE:matrix.org/$BijYISxb1sS2ObDdd7P1ox9Vbz8PYTR4R0CvIHMD_aQ?via=matrix.org&via=utwente.io&via=tu-dresden.de

doc/doxygen/src/getting-started.md: fix broken link

---

.murdock

The comment above TESTS_BOARDS_LLVM_COMPILE is misleading and outdated. This is due to an oversight in 52cf2b46c3ee607e43e824d0f9f8ef1a10a9c914 where tests on LLVM where re-enabled.
This drops the old comment and instead adds a comment why only a subset of boards are build on LLVM.
Read the comment added. This changes no code, so no breaking in the CI or on hardware is expected.
Reported in https://github.com/RIOT-OS/RIOT/pull/15595#issuecomment-2003129592

.murdock: document TESTS_BOARDS_LLVM_COMPILE

---

core/include/mbox.h
pkg/lwip/include/arch/sys_arch.h

Split out of https://github.com/RIOT-OS/RIOT/pull/15484, as suggested in https://github.com/RIOT-OS/RIOT/pull/15484#discussion_r527685477.
The following tests should still compile and run successfully:
- `tests/lwip`
- `tests/lwip_sock_ip` (both with `LWIP_IPV4=1` and `LWIP_IPV6=1` and their combination)
- `tests/lwip_sock_tcp` (both with `LWIP_IPV4=1` and `LWIP_IPV6=1` and their combination)
- `tests/lwip_sock_udp` (both with `LWIP_IPV4=1` and `LWIP_IPV6=1` and their combination)
Split out of https://github.com/RIOT-OS/RIOT/pull/15484

mbox: provide function to unset initialized mbox

---

drivers/mtd_flashpage/mtd_flashpage.c

the variable cpu_flash_base is only used in asserts. This gives errors if you compile without them.
compile with NDEBUG enabled and see that no errors are produced

drivers/mtd_flashpage: fix comperror when compiling without asserts

---

sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/fileserver.c

This is just an alias for `coap_get_code_raw()`.
When writing a CoAP handler function, it's very unintuitive that the 'raw Code' is needed to obtain the request method.
This also gives us the opportunity to use the `coap_method_t` type to avoid ambiguity. 
No functional changes.

nanocoap: introduce coap_get_method()

---

sys/tiny_strerror/tiny_strerror.c

Mixing address spaces is something LLVM doesn't like (for good reason). This re-organized the code a bit so that this does not happen anymore, even on AVR.
The function should still be semantically equivalent; ideally even the machine code generated is not changed (or at least not larger).
Split out of https://github.com/RIOT-OS/RIOT/pull/16924

sys/tiny_strerror: fix compilation on LLVM

---

cpu/sam0_common/periph/usbdev.c
drivers/include/periph/usbdev.h

This PR removes a deprecated event flag in `periph_usbdev`.
This flag was only generated by sam0 `periph_usbdev` but was never used anywhere in `usbus`. 
It was deprecated more than 2 years ago by #17046 
CI should be enough.
None.

periph_usbdev: remove deprecated event flag

---

cpu/stm32/cpu_init.c

Related to #18851 
When building example/gnrc_lorawan using LLVM two unused function error are raised. Those are fixed by only include said functions when they are needed. 
~~Additionally, LLVM complains about lorawan struct being not packed correctly. I believe this is because GCC applies the given attribute(packed) to all elements of a given struct including the anonymous struct and unions if present. Clang on the other does not seem to do that. The fix works by adding the packed attribute to the anonymous union as well.~~

llvm: Fix unused function warning

---

dist/tools/dhcpv6-pd_ia/pkg/__init__.py

At least on my system, `cat /etc/os-release` contains `NAME="Debian GNU/Linux"` and not just `NAME="Debian"`. This fixes the recognition logic to work in this case, too.
Also removing the `platform.linux_distribution()` part since that is deprecated since python 3.5 and removed since 3.7: https://docs.python.org/3.5/library/platform.html#platform.linux_distribution
on Debian without keas installed, compile on `master` for a board with usb-cdc-ecm:
```
$ make -C examples/gnrc_border_router BOARD=feather-nrf52840-sense UPLINK=cdc-ecm term
...
File ".../RIOT/dist/tools/dhcpv6-pd_ia/dhcpv6-pd_ia.py", line 72, in <module>
main()
File ".../RIOT/dist/tools/dhcpv6-pd_ia/dhcpv6-pd_ia.py", line 68, in main
server.run()
File …
```

dist/tools/dhcpv6-pd_ia: recognize Debian correctly

---

examples/rust-gcoap/Cargo.lock
examples/rust-hello-world/Cargo.lock
sys/rust_riotmodules_standalone/Cargo.lock
tests/rust_minimal/Cargo.lock

This is one of the semi-regular updates of riot-sys, -wrappers and other dependencies, split up by
```
$ find -name Cargo.toml -exec cargo update --manifest-path "{}" --package riot-wrappers --package riot-sys ';'
$ find -name Cargo.toml -exec cargo update --manifest-path "{}" ';'
```
for cleaner per-commit comments.
This applies one issue from riot-sys (https://github.com/RIOT-OS/rust-riot-sys/pull/43), everything else is maintenance-only.
Automated tests suffice.
... will be a good time for me to publish updated versions to crates.io, so that users of out-of-tree builds get the same experience as users of in-tree builds for the release.

Rust updates for 2024.04

---

CODEOWNERS

This creates a section in CODEOWNERS for Rust files unless they are part of a concrete module further down. (In particular, examples and sys/rust_riotmodules* are not "taken", so these will also notify me).

codeowners: Notify chrysn on Rust PRs

---

cpu/stm32/Makefile.dep
cpu/stm32/periph/usbdev_fs.c

Avoid pulling `ztimer` and `ztimer_msec` dependencies by default when using `usbdev_fs` peripheral driver.
If another module needs `ztimer`, then we can keep using it but otherwise use `busy_wait()` to perform the small delay needed by the driver.
My main idea is to avoid pulling `ztimer` when it is possible, to save ROM for `riotboot_dfu` bootloader application.
`make BOARD=bluepill-stm32f103c8 -C tests/sys/usbus_cdc_acm_stdio` must compile (and `ztimer` should not appear if you use `info-build`)
`make BOARD=bluepill-stm32f103c8 -C tests/sys/usbus_cdc_ecm` must compile (and `ztimer` should appear if you use `info-build` because `ztimer` dependency is pulled by another module
None.

cpu/stm32/periph/usbdev_fs: avoid using ztimer when not needed

---

doc/doxygen/riot.doxyfile
doc/doxygen/src/vision.md

added vision.md imported from Wiki
docs should work!

doxygen: added vision.md imported from Wiki

---

cpu/stm32/periph/gpio_all.c

I am testing the water with this patch. If it is well received, there will be more coming. As I am adding support for the STM32H7 family of chips, I noticed I needed to add the chip family's name to several lists of chips to select the right code for the build. The aim here is to let the build system do the work for us to reduce the overhead of adding new chips.
I tested by doing:
``` bash
make -C examples/blinky BOARD=nucleo-f303ze
```
The above also works for my work-in-progress port to the Nucleo-STM32H723ZG. Other testers welcome.
None known

cpu/stm32/periph/gpio: simplify condition code

---

cpu/stm32/include/clk/c0/cfg_clock_default.h
cpu/stm32/include/clk/cfg_clock_common_fx_gx_mp1_c0.h
cpu/stm32/include/clk/cfg_clock_common_lx_u5_wx.h
cpu/stm32/include/clk/clk_conf.h
cpu/stm32/include/clk/f0f1f3/cfg_clock_default.h
cpu/stm32/include/clk/f2f4f7/cfg_clock_default.h
cpu/stm32/include/clk/f2f4f7/cfg_clock_default_100.h
cpu/stm32/include/clk/f2f4f7/cfg_clock_default_120.h
cpu/stm32/include/clk/f2f4f7/cfg_clock_default_180.h
cpu/stm32/include/clk/f2f4f7/cfg_clock_default_216.h
cpu/stm32/include/clk/f2f4f7/cfg_clock_default_84.h
cpu/stm32/include/clk/g0g4/cfg_clock_default.h
cpu/stm32/include/clk/l0l1/cfg_clock_default.h
cpu/stm32/include/clk/l4l5wx/cfg_clock_default.h
cpu/stm32/include/clk/mp1/cfg_clock_default.h
cpu/stm32/include/clk/u5/cfg_clock_default.h

This patch removes a largely redundant block of conditional includes.
The removed includes are moved into the family specific headers so that the more specific headers may override defaults defined in the shared headers.
The changes are paternalistic enough that it should be obvious in review if this breaks anything.
I did do:
``` bash
$ make -C examples/blinky BOARD=nucleo-f303ze
```
and 
``` bash
$ make -C examples/blinky BOARD=nucleo-f767zi
```
This relates to the work I am doing to port RIOT to the STM32H7 family.

cpu/stm32: remove redundant conditional compile block

---

sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/nanocoap.c

Token is copied into the header, it's not being modified.
Allow to pass `const` data as token.
No change in binaries expected.

nanocoap: allow token to be const in coap_build_hdr()

---

tests/unittests/README.md

This commit changes the link about supported boards in the README from the wiki page to the RIOT-OS website. Since the wiki is not up to date.
Read the text, test the links. 
See also https://github.com/RIOT-OS/riot-os.org/pull/109 that fixed the same link on the website.

tests/unittests/README: link to Supported Boards updated (wiki -> site)

---

drivers/at/at.c
drivers/include/at.h
tests/drivers/at/main.c
tests/drivers/at/tests-with-config/test_all_configs.sh
tests/unittests/tests-at/Makefile
tests/unittests/tests-at/Makefile.include
tests/unittests/tests-at/tests-at.c
tests/unittests/tests-at/tests-at.h

Changes in this PR:
- remove asynchronous URC handling, as it is broken (see https://github.com/RIOT-OS/RIOT/issues/20059). I might get back to this feature in the future and re-implement it, but it would need a complete re-work.
- add robust URC handling where it's possible and document which actions the user has to take where it's not
- refactor the response parsing to make it individually testable and add extensive unit testing.
At the first glance, the diffs in this PR are huge. However, much of it comes from refactoring. Therefore, I have split this PR in three commits:
1. [drivers/at: removed async URC handling.](https://github.com/RIOT-OS/RIOT/commit/735edd1ec37769ef47a5f68ce5fd58c77698a793) - removes asynchronous URC handling. **I am not sure I properly removed this feature from …

drivers/at: fix URC handling and add better testing

---

examples/default/README.md
makefiles/deprecated_modules.inc.mk
makefiles/pseudomodules.inc.mk
pkg/nimble/Makefile.dep
pkg/openwsn/Makefile.dep
sys/Makefile.dep
sys/shell/cmds/nice.c
sys/shell/doc.txt
tests/sys/shell/ReadMe.txt

This PR removes a deprecated module that should have been removed a few release ago.
I've replaced it by `shell_cmds_default` where needed.
CI should be enough to catch up any miss.
None.

treewide: remove deprecated shell_commands module

---

boards/nucleo-c031c6/doc.txt
boards/nucleo-c031c6/include/periph_conf.h

This PR fix ADC configuration for Nucleo-c031c6 board. Additionally it enhance documentation page by adding standard
for Nucleo boards MCU table.
Flash board with `testes/periph/adc` and check if ADC works properly - my tests with connection of potentiometer shows changes in presented value.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-c031c6.html 
```
None

boards/nucleo-c031c6: fix ADC and enhance doc

---

doc/doxygen/src/community-processes.md

This contains minor changes to ease maintaining the document (e.g. by using reference-style links so that an URL needs to be updated only in a single place) and adds explicit anchors to ease linking to a certain section.
This should not change the visible text generated in any way. In fact, other than the anchors now being named like `community-process-maintainers` instead of something like `autotoc_md2117` the generated HTML should be the same.
None

doc/community-process: improve markdown style

---

examples/rust-gcoap/Cargo.lock
examples/rust-hello-world/Cargo.lock
sys/rust_riotmodules/Cargo.toml
sys/rust_riotmodules_standalone/Cargo.lock
sys/rust_riotmodules_standalone/Cargo.toml
tests/rust_minimal/Cargo.lock

The Cargo.lock of rust_riotmodules_standalone should explicitly list all
versions of software that would ever be pulled in by enabling RIOT
modules backed by a Rust crate. This did not happen before, because
while the optional dependencies could all be selected on the command
line, they were not visible as possible features to `cargo update`, and
were thus not encoded in the Cargo.lock file.
CI is probably good enough, but to understand what it does, look at `cargo tree --all-features` in `sys/rust_riotmodules_standalone` before and after -- and compare those with the output of `make` in `tests/rust_libs`. You will see that before, `cargo tree -all-features` did not show the `lsm303agr` crate as a listed dependency, even though the `make` output clearly illustrates that it *is* being …

rust: Make dependencies visible

---

doc/doxygen/RIOTDoxygenLayout.xml

This fixes a regression from https://github.com/RIOT-OS/RIOT/pull/20443 which does cause the modules to re-appear in the side panel, but under the name "Topics" rather than "Modules".
Check the generated doc with a modern version of Doxygen. The module section should be named "Modules" again.
https://github.com/RIOT-OS/RIOT/pull/20443

doc/doxygen: fix name and intro of "Modules" section

---

doc/doxygen/riot.doxyfile
doc/doxygen/src/terminal-programs.md

This is mostly an import from https://github.com/RIOT-OS/RIOT/wiki/Configure-terminal-programs-for-correct-display-of-newlines.
Checkout this branch, run `make doc` and check the link "Terminal programs configuration" in the navigation menu.

doc: add terminal program configuration

---

sys/net/gnrc/link_layer/gomach/gomach.c
sys/net/gnrc/link_layer/lwmac/lwmac.c

While using [simian](https://www.harukizaemon.com/simian/) (a tool that can detect code duplication) on RIOT-OS, I found two snippets of code that were good candidates for being factorized.
This pull request does not change the behavior of gnrc.
I compiled for the SAMD21-XPRO board the following examples: `gnrc_minimal`, `gnrc_networking` and `gnrc_networking_mac`.
None.

sys/net/gnrc: Remove code duplication

---

pkg/tinydtls/contrib/sock_dtls.c
sys/include/net/sock/dtls.h

Incorporating the tinydtls build package, this code addresses a failure encountered during the DTLS handshake between the client and the server. The issue arose from the client imposing default user parameters, which mandate setting extended master secret and renegotiation info to 1. However, not all servers support these extensions. To ensure greater flexibility, it's more appropriate to make these parameters user-configurable
I utilized the 'examples/gcoap_dtls' on a native environment for the client. However, for the server, I deployed it on my Ubuntu machine, which lacks support for these extensions
results when the extensions are set to 0:
````
2024-03-18 16:45:30,983 # RIOT native interrupts/signals initialized.
2024-03-18 16:45:30,984 # RIOT native board initialized.
2024-03-18 …
```

pkg/tinydtls: enforce the default dtls user params to be configurable

---

makefiles/tools/openocd-adapters/ftdi.inc.mk

The upstream OpenOCD config for Tigard does not define SWD_EN, as it can also be used in JTAG mode.
However, OpenOCD will complain when the signal is not set. A quick and dirty solution is directly editing `/usr/share/openocd/scripts/interface/ftdi/tigard.cfg`, but this is of course not a great user experience. 
To solve this, add the [line from the example config](https://github.com/tigard-tools/tigard?tab=readme-ov-file#swd-on-cortex-header) to our OpenOCD command line if tigard is used in SWD mode.
In `master` interacting with OpenOCD and Tigard either requires editing `tigard.cfg` or you'll get
```
/home/benpicco/dev/RIOT/dist/tools/openocd/openocd.sh reset
Open On-Chip Debugger 0.12.0
none …
```

tools/openocd: define SWD_EN signal for tigard

---

sys/psa_crypto/Makefile.dep
tests/sys/psa_crypto_hashes/Makefile.ci

So far the PSA Crypto implementation used MUSL C PRNG as the default random number generator, which is not cryptographically secure.
This PR uses the SHA256 RNG instead, which is a CSPRNG.
When building `examples/psa_crypto`: `make info-modules` should list `prng_sha256prng`

sys/psa_crypto: use SHA256 CSPRNG as default

---

core/lib/init.c

🙃
I think `pm_set_lowest()` needs to be guarded against the module `periph_pm`. Otherwise you can not build RIOT if `periph_pm` is not provided by the target board.
I wasn't super sure if it needs to be `periph_pm` maybe it should be `pm_layered` instead?
CI, I guess? Very unsure here!

core: Guard pm_set_lowest with module_periph_pm
