RIOT-OS/RIOT

- boards/lora-e5-dev/board.c
- boards/lora-e5-dev/include/board.h
- dist/tools/doccheck/exclude_patterns
- drivers/include/sx126x.h
- drivers/sx126x/include/sx126x_params.h
- drivers/sx126x/sx126x.c
- drivers/sx126x/sx126x_netdev.c
I was testing OTAA and LoRaWAN altogether on sx126x devices and realized that it was actually not working on `lora-e5-dev` (not sure how I was able to get it to work on the original PR).
One of the reasons is incorrect sync-word selections, for these devices, it's actually 16bit and has different values than the other sx12xxx devices. This might need fixing for `gnrc_lorawan` as well @jia200x.
The second is that this BOARD  only supports HPA, and the driver was hardcoded to use LPA.
- `lora-e5-dev`
```
2021-11-04 21:56:42,700 # loramac              Control Semtech loramac stack
: loramac set deveui 70B3D57ED0045DBC
2021-11-04 21:56:44,600 # loramac set deveui 70B3D57ED0045DBC
loramac set appeui 0000000000000000C
2021-11-04 21:56:45,848 # loramac set appeui 0000000000000000
: loramac set …
```
> drivers/sx126x: fix sync word and TX PA configuration

- boards/native/Makefile.include
- tests/backtrace/tests/01-run.py
This fixes the following warning on newer gcc/ld:
```
/usr/bin/ld: examples/hello-world/bin/native/cpu/tramp.o: warning: relocation against `_native_saved_eip' in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
```
I've had this warning for many months and finally found a way to silence it.
~~As far as I can tell, the resulting binaries are identical.~~
CI runs all tests, should suffice.
> cpu/native: add `-no-pie` to LINKFLAGS

- cpu/stm32/include/cpu_conf_stm32_common.h
Not sure what made this not pop up earlier...
Look at the code...
> cpu/stm32/include/cpu_conf_stm32_common.h: fix typo in macro

- boards/lora-e5-dev/doc.txt
This adds a warning to the `lora-e5-dev` documentation since the arduino pin headers are quite misleading.
Waiting for circle-ci...
> boards/lora-e5-dev: add warning in doc

- sys/include/architecture.h
- tests/sys_architecture/main.c
This adds the `HAS_ALIGNMENT_OF(addr, alignment_requirement)` macro to check if a given address fulfills a given alignment requirement. This is useful to add (static and non-static) `assert()`s to code where reasoning about alignment is done when casting addresses. Those `assert()` allow keeping the code fast (at least when `static_assert()`s are used or `DEVELHELP` is off) while preventing alignment bugs from sneaking in.
The test application has been extended and uses `static_assert()`. So if it compiles, it is fine.
~~Depends on https://github.com/RIOT-OS/RIOT/pull/17176~~
> sys/architecture: add HAS_ALIGNMENT_OF() helper

- drivers/include/dose.h
By moving all the single byte struct elements to the end, we can reduce padding inside `dose_t` and ensure that `recv_buf` is always aligned.
This saves some RAM:
master
------
36384	    136	  12944	  49464	   c138 tests/driver_dose/bin/samr21-xpro/tests_driver_dose.e
this patch
----------
36484	    136	  12936	  49556	   c194	tests/driver_dose/bin/samr21-xpro/tests_driver_dose.elf
> drivers/dose: reduce struct padding

- drivers/ads101x/Kconfig
- drivers/ads101x/Makefile.dep
- drivers/ads101x/ads101x.c
- tests/driver_ads101x/Makefile
- tests/driver_ads101x/Makefile.ci
- tests/driver_ads101x/app.config.test
- tests/driver_ads101x/main.c
This PR migrates the ads101x driver to ztimer.
- Test application still works (cannot test because of missing hardware)
> drivers/ads101x: migrate to ztimer

- cpu/stm32/Kconfig
- cpu/stm32/Makefile.include
- cpu/stm32/cpu_init.c
- cpu/stm32/include/periph/f0/periph_cpu.h
- cpu/stm32/include/periph/f1/periph_cpu.h
- cpu/stm32/include/periph/f2/periph_cpu.h
- cpu/stm32/include/periph/f3/periph_cpu.h
- cpu/stm32/include/periph/f4/periph_cpu.h
- cpu/stm32/include/periph/f7/periph_cpu.h
- cpu/stm32/include/periph/l1/periph_cpu.h
Initialize STM32 RDP in a glitch-resistant fashion to prevent
debugger use when restrictions are set by the designer.
> cpu/stm32: Add hardening changes to stm32

- boards/dwm1001/include/periph_conf.h
Trying to connect an spi device to the dwm1001 I realized the pin assignment was wrong:
Test with any SPI device, I used an sd card, without this change the init would fail:
```
2021-11-15 10:54:29,872 # WARNING: using 'write' or 'copy' commands WILL overwrite data on your sd-card and
2021-11-15 10:54:29,872 # init
2021-11-15 10:54:29,884 # Initializing SD-card at SPI_0...[OK]
> 2021-11-15 10:54:34,232 # Exiting Pyterm
```
https://github.com/RIOT-OS/RIOT/pull/14314, was not tested at the time.
> boards/dwm1001: fix SPI0 miso/mosi pins

- examples/suit_update/Makefile
- sys/Makefile.dep
This adds the `sock_util` module dependency to the SUIT CoAP transport module and automatically loads the `nanocoap_sock` module instead of the `nanocoap` module. Without these changes, choosing CoAP transport and a UDP socket implementation, e.g. `USEMODULE += gnrc_sock_udp`, will leave undefined references at link time. The missing functions are from the `sock_util` and `nanocoap_sock` modules. 
Compiling examples/suit as modified in the second commit of this PR without the changes of the first commit will result in undefined references at link time.
None.
> sys/suit: adjust dependencies for CoAP transport

- Makefile.include
- dist/tools/insufficient_memory/create_makefile.ci.sh
- makefiles/info-global.inc.mk
- makefiles/info.inc.mk
For adding a new board we have `add_insufficient_memory_board.sh` to automatically update all `Makefile.ci` lists for tests that do not fit the memory of the CPU.
This adds a similar script for doing the same when adding / modifying a test and generates a `Makefile.ci` by compiling the application for all supported boards.
For any test / application run
rm Makefile.ci
make Makefile.ci
In the end, a new `Makefile.ci` should be created that is indistinguishable from the original one, if that one was correct.
> tools/insufficient_memory: add create_makefile.ci.sh and Makefile.ci make target

- boards/lora-e5-dev/Kconfig
- boards/lora-e5-dev/Makefile.features
- boards/lora-e5-dev/include/periph_conf.h
- cpu/stm32/Makefile.dep
- cpu/stm32/include/periph/wl/periph_cpu.h
- cpu/stm32/include/periph_cpu.h
- cpu/stm32/periph/Kconfig
- cpu/stm32/periph/adc_wl.c
- dist/tools/doccheck/exclude_patterns
This PR adds an initial implementation for `periph_adc` on the stm32wl plarforms.
Run `tests/periph_adc`, here had the pins plugged into GND and then switched to 3.3V (note that there are some suppurios measurements when pi is floating)
```
2021-11-11 14:29:12,174 # ADC_LINE(1): 1
2021-11-11 14:29:12,273 # ADC_LINE(0): 1
2021-11-11 14:29:12,274 # ADC_LINE(1): 0
2021-11-11 14:29:12,373 # ADC_LINE(0): 1
2021-11-11 14:29:12,374 # ADC_LINE(1): 1
2021-11-11 14:29:12,474 # ADC_LINE(0): 1
2021-11-11 14:29:12,474 # ADC_LINE(1): 2
2021-11-11 14:29:12,573 # ADC_LINE(0): 3
2021-11-11 14:29:12,574 # ADC_LINE(1): 1
2021-11-11 14:29:12,673 # ADC_LINE(0): 0
2021-11-11 14:29:12,674 # ADC_LINE(1): 2
2021-11-11 14:29:12,774 # ADC_LINE(0): 0
2021-11-11 14:29:12,774 # ADC_LINE(1): 2
2021-11-11 14:29:12,874 # …
```
> cpu/stm32/wl: initial periph_adc implementation

- cpu/cortexm_common/periph/flashpage.c
- cpu/riscv_common/periph/flashpage.c
Fix incorrect doxygen group in some flashpage files based on the [comment](https://github.com/RIOT-OS/RIOT/pull/16972#issuecomment-966298211) from @PeterKietzmann .
> periph/flashpage: fix wrong doxygen group

- Makefile.include
- makefiles/info-global.inc.mk
- makefiles/info.inc.mk
If we
-include Makefile.ci
and `Makefile.ci` does not exist, but we provide `make` with a way on how to do so, it will try to create `Makefile.ci`.
This is not what we want, but I don't know how to disable this automagic.
So rename the target to `create-Makefile.ci` to avoid the conflict.
make info-boards-supported
should no longer attempt to create `Makefile.ci`
alternative to #17204
> Makefile.include: rename Makefile.ci target to create-Makefile.ci

- sys/usb/usbus/cdc/ecm/cdc_ecm.c
This truncates the incomming frames to ETHERNET_FRAME_LEN and silently
discards the rest of the frame until the end of the frame. This should
be modified to an endpoint halt condition after #17090 is merged, but
for now this should be good enough.
Stalling the endpoint with the current stall implementation could cause
a ping of death scenario, so for now the data is truncated until the
above solution can be implemented.
(I've also removed an duplicate `USBOPT_EP_AVAILABLE` call)
The `tests/usbus_cdc_ecm` application should still work on a platform of choice.
Reported in detail by @szymonh
> cdc_ecm: Truncate frames at max ethernet size

- examples/lorawan/Makefile
- examples/lorawan/Makefile.ci
- examples/lorawan/main.c
`examples/lorawan` currently forces the use of `periph_rtc`. This makes sense when wanting to achieve the deepest sleeps, but instead of blacklisting all `BOARD`s that do not have this feature make it optional and allow `ztimer_msec` (and therefore potentially rtt) to be used.
Test the example on any BOARD with no rtt, eg. `lora-e5-dev`
```
2021-11-11 10:33:53,817 # LoRaWAN Class A low-power application
2021-11-11 10:33:53,820 # =====================================
2021-11-11 10:33:53,835 # Starting join procedure
2021-11-11 10:33:58,974 # Join procedure succeeded
2021-11-11 10:33:58,975 # Sending: This is RIOT!
2021-11-11 10:34:24,081 # Sending: This is RIOT!
2021-11-11 10:34:49,188 # Sending: This is RIOT!
2021-11-11 10:35:14,290 # Sending: This is RIOT!
2021-11-11 10:35:39,391 # …
```
> examples/lorawan: use ztimer_msec if not rtc

- tests/pthread_barrier/tests/01-run.py
Previously the test script relied on the exact sequence of numbers
returned by the used PRNG. This resulting e.g. in
```
$ USEMODULE=prng_musl_lcg make -C tests/pthread_barrier flash test
```
to fail, only because the order in which the children completed is
slightly different due to different sleep durations. This fixes the
issue.
The command above should succeed, no with and without `USEMODULE=prng_musl_lcg` before the invocation of `make`.
Useful for https://github.com/RIOT-OS/RIOT/pull/17188
> tests/pthread_barrier: fix test script

- cpu/stm32/include/usbdev_stm32.h
- cpu/stm32/periph/usbdev.c
Make sure in `_usbdev_new_ep()` that `usbdev_ep_t::buf` is always aligned to 4 bytes. With this in mind, add intermediate casts to `uintptr_t` before casting `usbdev_ep_t::buf` to `uint32_t *` to silence `-Wcast-align`, as we now manually enforced correct alignment.
Everything should still work as before, but unaligned memory access should now prevented. (That is, no crash on architectures that do not support them.)
> cpu/stm32/periph/usbdev: fix alignment issues

- boards/stm32f746g-disco/Kconfig
- boards/stm32f746g-disco/Makefile
- boards/stm32f746g-disco/Makefile.dep
- boards/stm32f746g-disco/Makefile.features
- boards/stm32f746g-disco/Makefile.include
- boards/stm32f746g-disco/board.c
- boards/stm32f746g-disco/clock.config
- boards/stm32f746g-disco/doc.txt
- boards/stm32f746g-disco/include/board.h
- boards/stm32f746g-disco/include/gpio_params.h
- boards/stm32f746g-disco/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
- tests/Makefile.boards.netif
This PR adds support for the [stm32f746g-disco](https://www.st.com/en/evaluation-tools/32f746gdiscovery.html) board.
This board provides USB FS/HS connectors (not configured), an Ethernet interface (configured and tested) and a large screen (272 x 400 with 24bits color depth) with a touch screen. The screen support if not provided by this PR.
- Green CI
- Run `test_and_compile_for_board.py` ~(still running, but DMA is not correctly configured for stdio UART apparently and there's an issue with Kconfig clock configuration)~
<details>
```
$ ./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . stm32f746g-disco --jobs=4 --with-test-only
[...]
ERROR:stm32f746g-disco:Tests failed: 9
Failures during compilation:
- [tests/gnrc_sixlowpan_frag_minfwd](tests/gnrc_sixlowpan_frag_min …
```
> boards: add support for stm32f746g-disco

- makefiles/arch/mips.inc.mk
- pkg/ccn-lite/patches/0001-cmake-Use-std-c11-instead-of-std-c99.patch
- sys/posix/include/sys/socket.h
Align the first member of `struct sockaddr` and `struct sockaddr_storage` as `uint32_t` to elevate the alignment of the structure to level of `uint32_t`. This is needed as `struct sockaddr_in` uses an `uint32_t` to store the IPv4 address, previously resulting in `struct sockaddr_in` currently having a greater alignment requirement that `struct sockaddr_storage`.
POSIX sockets should still work, and now do so reliably on platforms that do not support unaligned memory accesses.
This contains the same commit to enable C11 for MIPS as https://github.com/RIOT-OS/RIOT/pull/17195 - so if one of the two gets in first the other should be rebased on `master`.
> sys/posix/socket: align struct sockaddr{,_storage}

- boards/native/include/board.h
native has some simulated "motor driver" support, which is *always* compiled in. This PR guards it on ~~`MODULE_MOTOR_DRIVER`~~`MODULE_PERIPH_QDEC`.
> boards: native: guard motor driver simulation code

- cpu/native/irq_cpu.c
- cpu/native/native_cpu.c
- cpu/native/syscalls.c
Unaligned accesses on x86(_64) are allowed, but slow. However, some host systems might not be that forgiving. Aligning the stack to `sizeof(uintptr_t)` should be a pretty safe safety measure.
And with this done, all casts of the stack pointer that increase alignment requirements are now intermediately casted to `uintptr_t` to silence warnings from `-Wcast-align` - after all the stacks are now manually aligned.
This should not break anything on `native`, but might speed up things on x86_64 and fix crashes (I think with SIGBUS?) on some host architectures.
> cpu/native: align stack in thread_stack_init()

- sys/usb/usbus/cdc/acm/cdc_acm.c
- sys/usb/usbus/usbus_control.c
This PR adds two sanity checks to the usbus stack.
- A check to verify that the amount of data received with a setup request doesn't exceed the amount indicated within the setup request length field
- A check to ensure that the length of the line coding setup request in the CDC ACM handler matches the expected length.
Testing that the CDC ACM test still works as expected should be sufficient
None
> usbus: check received setup request data amount

- cpu/nrf52/include/nrfusb.h
- cpu/nrf52/include/periph_cpu.h
- cpu/nrf52/periph/usbdev.c
- cpu/sam0_common/include/periph_cpu_common.h
- cpu/sam0_common/include/sam_usb.h
- cpu/sam0_common/periph/usbdev.c
- cpu/stm32/include/periph_cpu.h
- cpu/stm32/include/usbdev_stm32.h
- cpu/stm32/periph/usbdev.c
- drivers/include/periph/usbdev.h
- drivers/include/usbdev_mock.h
- drivers/usbdev_mock/usbdev_mock.c
- sys/include/usb/usbopt.h
- sys/include/usb/usbus/cdc/acm.h
- sys/include/usb/usbus/cdc/ecm.h
- sys/include/usb/usbus/control.h
- sys/include/usb/usbus/hid.h
- sys/usb/usbus/cdc/acm/cdc_acm.c
- sys/usb/usbus/cdc/ecm/cdc_ecm.c
- sys/usb/usbus/cdc/ecm/cdc_ecm_netdev.c
- sys/usb/usbus/hid/hid.c
- sys/usb/usbus/hid/hid_io.c
- sys/usb/usbus/usbus.c
- sys/usb/usbus/usbus_control.c
- sys/usb/usbus/usbus_control_slicer.c
- tests/usbus/main.c
This API change refactors the usbdev API to supply buffers via the
usbdev_ep_xmit function. This changes from the usbdev_ep_ready call to allow
separate buffers per call. 
Main advantage is that the usbdev peripherals no longer have to allocate
oversized buffers for the endpoint data, potentially saving multiple KiB
of unused buffer space. These allocations are now the responsibility of
the individual USB interfaces in the firmware
An usbdev_ep_buf_t pseudotype is available and must
be used when defining buffers used for endpoints to adhere to the DMA alignment
restrictions often required with usb peripherals.
usbdev implementations:
Interfaces implemented:
(DFU only uses control requests and didn't need adaptations)
None
> USB: refactor to xmit-based API

- Makefile.base
- doc/doxygen/src/creating-modules.md
This allows for SUBMODULE PSEUDOMODULES to conditionally not be linked
to an existing *.c file.
It can be seen in https://github.com/RIOT-OS/RIOT/pull/16958, where its used to conditionally compile `event/timeout.c`.
Split out of #16958.
> Makefile.base: add SUBMODULE_NO_SRC to excluded a selected SUBMODULE *.c

- cpu/esp32/esp_xtimer.c
- cpu/esp32/periph/can.c
- cpu/esp32/periph/i2c_hw.c
- cpu/esp32/periph/pm.c
- cpu/esp32/startup.c
- The CI will run the `static-tests`, which should now pass for everything in `cpu/esp32/*`.
- The code changes should *NOT* translate to changed in generated binaries
None
> cpu/esp32: make CI happy

- sys/usb/usbus/hid/hid.c
This PR corrects the readyness of the OUT endpoint for HID.
Before that, EP was configured as waiting for OUT data during the initialization phase.
Unfortunately, during the enumeration phase, the USB endpoint is reset and thus, the endpoint configuration is lost.
Somehow, nRF52 and SAM0 usbdev implementation are able to workaround this issue but this should be fixed on HID side.
Flash `tests/usbus_hid` and follow the test procedure.
None.
> usbus/hid: fix ep_out readyness

- cpu/esp32/ld/esp32.common.ld
This PR moves the code from `cpu/esp_common/periph` and `cpu/esp_common/freertos` from IROM to IRAM.
The IRAM is much faster than the IROM. Furthermore, IROM can only be accessed via a cache which is sometimes disabled, e.g. by the WiFi module or when writing to the flash. Therefore, time-critical code as well as code that has to work even when the IROM cache is disabled must be placed in the IRAM.
The PR should increase stability.
Tests in Murdock should still success.
Additionally, a networking application should be tested.
```
USEMODULE='esp_wifi' CFLAGS='-DESP_WIFI_SSID=\"ssid\" -DESP_WIFI_PASS=\"pass\"' make -C examples/gnrc_networking BOARD=esp32-wroom-32 flash term
```
Found when fixing #16281.
> cpu/esp32: place freertos and periph in IRAM

- Makefile.dep
- Makefile.include
- makefiles/info-global.inc.mk
- tests/pkg_arduino_sdi_12/Makefile.ci
Currently `arch_%` and `cpu_core_%` features are required after the first iteration of the dependency resolution. This may cause race conditions when checking for them in `FEATURES_USED`. This moves them up, also for the "quick" version used by the CI.
- `make info-applications-supported-boards` should stay the same, **BUT** this change caught a race condition in the dependency resolution for the `arduino_sdi_12` package:
https://github.com/RIOT-OS/RIOT/blob/0c9240125e80103bbcb57a7177935be23b854556/pkg/arduino_sdi_12/Makefile.dep#L3-L7
My diff between the results for 5e925e1906a7d10b2ab6f8d9b972755b8d290d19 and after this PR:
```diff
67485a67486,67488
> tests/pkg_arduino_sdi_12 arduino-duemilanove
> tests/pkg_arduino_sdi_12 arduino-leonardo
> tests/pkg_arduino_sdi_12 arduino-mega2560 …
```
> makefile.dep: require `arch_%` `cpu_core_%` features first

- cpu/esp32/periph/can.c
- cpu/esp32/periph/i2c_hw.c
- cpu/gd32v/periph/uart.c
- cpu/nrf5x_common/periph/i2c_nrf52_nrf9160.c
- cpu/nrf5x_common/periph/spi_nrf52_nrf9160.c
- drivers/include/periph/adc.h
- drivers/include/periph/dac.h
- drivers/include/periph/i2c.h
- drivers/include/periph/pwm.h
- drivers/include/periph/qdec.h
- drivers/include/periph/spi.h
- drivers/include/periph/timer.h
- drivers/include/periph/uart.h
- drivers/soft_uart/soft_uart.c
- tests/driver_soft_uart/main.c
- tests/periph_qdec/main.c
- tests/periph_uart/main.c
The default driver type is just an index into a device array defined by the board.
If a platform wants to encode additional information in the device type, it can define a custom type.
This means we can just set the default type to a single byte (similar to enums) and save some memory.
Entirely untested. Ideally, nothing should change.
But Murdock will hopefully tell us if anything implicitly relies on those types being a specific size.
> drivers/periph: use uint_fast8_t as default type

- sys/include/ztimer.h
- sys/ztimer/core.c
this marks `ztimer_update_head_offset` as static to the `ztimer/core` compilation unit since there are no user outside of core
```
$ rg ztimer_update_head_offset\\\(
sys/include/ztimer.h
569:void ztimer_update_head_offset(ztimer_clock_t *clock);
sys/ztimer/core.c
75:        ztimer_update_head_offset(clock);
91:    ztimer_update_head_offset(clock);
189:void ztimer_update_head_offset(ztimer_clock_t *clock)
198:        "clock %p: ztimer_update_head_offset(): diff=%" PRIu32 " old head %p\n",
218:            "ztimer %p: ztimer_update_head_offset(): now=%" PRIu32 " new head %p",
377:            ztimer_update_head_offset(clock);
```
compile and run ztimer tests
e.g.:
```
tests/ztimer_overhead$ RIOT_VERSION=test make all test
```
ante patch:  
```
text    data     bss     dec     hex filename …
```
> sys/ztimer: make internal head update static

- cpu/nrf5x_common/Makefile.features
- cpu/nrf5x_common/periph/flashpage.c
- cpu/nrf9160/Kconfig
- cpu/nrf9160/include/cpu_conf.h
This PR adds periph_flashpage support for nRF9160 family. Changes in nrf5x_common driver is minimal (only the erase page is different from nRF51/nRF52).
Flash tests/periph_flashpage on `nrf9160dk` board and play with the test app.
I provide the following [gist](https://gist.github.com/dylad/8285886a66a393773f803a497c4bbcbe) for some test output.
I also tried riotboot_serial on my custom nrf9160 board and it works like a charm.
None.
> cpu/nrf9160: add periph_flashpage support

- cpu/nrf5x_common/include/periph_cpu_common.h
- cpu/nrf5x_common/periph/qdec.c
- tests/periph_qdec/Makefile
- tests/periph_qdec/boards_modded/nrf52840dk/Kconfig
- tests/periph_qdec/boards_modded/nrf52840dk/Makefile
- tests/periph_qdec/boards_modded/nrf52840dk/Makefile.dep
- tests/periph_qdec/boards_modded/nrf52840dk/Makefile.features
- tests/periph_qdec/boards_modded/nrf52840dk/Makefile.include
- tests/periph_qdec/boards_modded/nrf52840dk/include/board.h
- tests/periph_qdec/boards_modded/nrf52840dk/include/periph_conf.h
This PR adds a simple implementation of the qdec peripheral for the nrf5x devices.
As far as I know there is no board with both an nrf5x chip and a rotary encoder present. 
I have some test output from my own board, but I can imagine that it doesn't look that convincing :)
<details><summary>Output</summary>
```
/home/koen/dev/RIOT-dev/dist/tools/jlink/jlink.sh term-rtt 
2021-11-15 15:15:03,208 # Host name for TCP connection is missing, defaulting to "localhost"
2021-11-15 15:15:03,208 # Connect to localhost:19021
2021-11-15 15:15:04,211 # SEGGER J-Link V7.58 - Real time terminal output
2021-11-15 15:15:04,212 # J-Link EDU Mini V1 compiled Nov  2 2021 11:12:01 …
```
> nrf5x_common: Add qdec peripheral implementation

- boards/stm32f469i-disco/Kconfig
- boards/stm32f469i-disco/Makefile.features
- boards/stm32f469i-disco/include/periph_conf.h
Adds DAC support for the stm32f469i-disco board
Tested with `tests/periph_dac/` the output on the terminal is:
```sh
2021-11-16 12:38:02,701 # main(): This is RIOT! (Version: 2022.01-devel-498-g39b9c-stm32f469i-disco)
2021-11-16 12:38:02,701 # 
2021-11-16 12:38:02,704 # RIOT DAC peripheral driver test
2021-11-16 12:38:02,704 # 
2021-11-16 12:38:02,709 # This test application produces a saw tooth signal on each available
2021-11-16 12:38:02,715 # DAC line. The period of the signal should be around 100ms
2021-11-16 12:38:02,716 # 
2021-11-16 12:38:02,718 # Successfully initialized DAC_LINE(0)
2021-11-16 12:38:02,721 # Successfully initialized DAC_LINE(1)
2021-11-16 12:38:02,721 #
```
We have `PORT_A, 5`  available on the  connector CN12, pin 7. The oscilloscope shows us the following image …
> boards/stm32f469i-disco: Add DAC

- sys/ztimer/xtimer2ztimer.cocci
The change should be easy to check.
Can be run with:
```
spatch --sp-file sys/ztimer/xtimer2ztimer.cocci --macro-file-builtins dist/tools/coccinelle/include/riot-standard.h . -include_headers
```
Cherry-picked out of  #16903
> sys/ztimer/xtimer2ztimer.cocci: extend and fix api replacements

- boards/nrf9160dk/Kconfig
- boards/nrf9160dk/Makefile.features
- cpu/nrf9160/Makefile.include
This PR enables riotboot features for nRF9160DK.
Play with `tests/riotboot`
or `bootloader/riotboot_serial`
requires #17225
> boards/nrf9160dk: add riotboot support

- cpu/sam0_common/periph/Kconfig.spi
- cpu/sam0_common/periph/spi.c
- cpu/samd21/periph/Kconfig.spi
- cpu/samd5x/periph/Kconfig.spi
- cpu/saml1x/periph/Kconfig.spi
- cpu/saml21/periph/Kconfig.spi
- drivers/periph_common/Kconfig.spi
Setting up a DMA transfer can take longer than sending out a buffer byte by byte if the buffer is small.
DMA only shows advantages for large buffers, using it for every transfer will cause a net slowdown.
Since we did not come up with a good way to determine the treshold based on the SPI frequency, just use a fixed buffer for now so that DMA can be used without slowing things down overall.
The benchmark function of `tests/periph_spi_dma` make the effect apparent:
```
2021-10-07 13:36:58,396 # init 0 0 3
2021-10-07 13:36:58,406 # Trying to initialize SPI_DEV(0): mode: 0, clk: 3, cs_port: 0, cs_pin: 0
2021-10-07 13:36:58,408 # Note: Failed assertion (crash) means configuration not supported
2021-10-07 13:37:06,204 # bench
2021-10-07 13:37:06,208 # ### Running some benchmarks, all values in …
```
> cpu/sam0_common: SPI: don't perform DMA transfer for small buffers

- CODEOWNERS
- drivers/dht/dht.c
- drivers/dht/include/dht_params.h
- drivers/include/dht.h
- tests/driver_dht/Makefile
- tests/driver_dht/app.config.test
- tests/driver_dht/main.c
The existing driver only had an accuracy of 1°C instead of 0.1°C. This was due to an incorrect interpretation of the datasheet. The lower bits were discarded. This patch corrects the use of how the raw data should be interpreted and converted. 
The proof of the pudding is in the eating:
```
2021-10-02 00:56:24,832 # RAW values: temp: 23.6 hum: 52.0
2021-10-02 00:56:24,837 # DHT values - temp: 23.6°C - relative humidity: 52.0%
2021-10-02 00:56:26,857 # RAW values: temp: 22.9 hum: 54.0
2021-10-02 00:56:26,861 # DHT values - temp: 22.9°C - relative humidity: 54.0%
2021-10-02 00:56:28,881 # RAW values: temp: 22.9 hum: 54.0
2021-10-02 00:56:28,886 # DHT values - temp: 22.9°C - relative humidity: 54.0%
2021-10-02 00:56:30,905 # RAW values: temp: 22.9 hum: 54.0
2021-10-02 00:56:30,910 # DHT …
```
> drivers/dht: correct interpreting raw values

- core/mutex.c
- cpu/fe310/include/periph_cpu.h
- cpu/riscv_common/include/atomic_utils_arch.h
- cpu/riscv_common/include/clic.h
- cpu/riscv_common/include/irq_arch.h
- cpu/riscv_common/include/thread_arch.h
- cpu/riscv_common/irq_arch.c
- cpu/riscv_common/periph/plic.c
- sys/riotboot/flashwrite.c
- sys/riotboot/hdr.c
- sys/riotboot/serial.c
This PR makes a couple of minor changes to get rid of the uncrustify suggestions made in the CI.
The changes in `sys/include/ztimer.h` are the result of false positives and can probably be dropped. Maybe there is a way to adjust the config to get rid of warnings like these?
All static tests should pass without suggestions/warnings while the CI stays green as well.
The false postives for `sys/include/ztimer.h` have been mentioned in #15802 before.
> treewide: Address uncrustify suggestions

- .murdock
- boards/cc1312-launchpad/Kconfig
- boards/cc1350-launchpad/Kconfig
- boards/cc1352-launchpad/Kconfig
- boards/cc1352p-launchpad/Kconfig
- boards/cc2650-launchpad/Kconfig
- cpu/cc26x0_cc13x0/Kconfig
- cpu/cc26x0_cc13x0/vendor/driverlib/Kconfig
- cpu/cc26x2_cc13x2/Kconfig
- cpu/cc26xx_cc13xx/Kconfig
- cpu/cc26xx_cc13xx/periph/Kconfig
This models the Kconfig modules for all boards based on cc26xx and cc13xx CPUs. The list of boards is:
- cc1312-launchpad
- cc1352-launchpad
- cc1352p-launchpad
- cc2650-launchpad
- cc2650stk
- cc1350-launchpad
- Green CI
- Check the modelling and compare `make info-modules` list with and without `TEST_KCONFIG=1`, they should match.
Part of #16875
> cpu/{cc26xx, cc13xx}: model kconfig

- makefiles/pseudomodules.inc.mk
- sys/shell/commands/Makefile
- sys/shell/commands/shell_commands.c
- tests/rng/Makefile
These commands cost 248 bytes of memory, we don't want to always include them when the `random` module is selected.
Compile `examples/gnrc_networking`
```
100384	    188	  18984	 119556	  1d304	/home/benpicco/dev/RIOT-staging/examples/gnrc_networking/bin/samr21-xpro/gnrc_networking.elf
```
```
100136	    188	  18984	 119308	  1d20c	/home/benpicco/dev/RIOT-staging/examples/gnrc_networking/bin/samr21-xpro/gnrc_networking.elf
```
> sys/shell: hide random commands behind random_cmd pseudo-module

- boards/ek-lm4f120xl/Kconfig
Turns out that `lm4f120` does not require extra modelling, so just adding the single board that uses it: `ek-lm4f120xl`. I don't think it is really worth it add it to the CI list to test every single time, so I added a temporary commit for that.
- Green CI
- Module lists should match between makefile and kconfig
Part of #16875
> boards/ek-lm4f120xl: model kconfig

- dist/tools/openocd/openocd.sh
> tools/openocd: check OPENOCD_VERIFY after IMAGE_OFFSET is computed

- examples/openthread/Makefile
- pkg/doc.txt
- pkg/openthread/Makefile
- pkg/openthread/Makefile.include
- pkg/openthread/contrib/netdev/openthread_netdev.c
- pkg/openthread/patches/0001-RIOT-use-assert.h.patch
This PR bumps the version of openthread to the [latest 20200818 release](https://github.com/openthread/openthread/releases/tag/thread-reference-20200818). Since this release can now be built using CMake, this PR also adapt the package to cmake instead of autotools to build it: this enables out-of-source build like all other packages (except micropython).
- A green CI
- Follow the readme of `examples/openthread` and ensure that it's still functional
None
> pkg/openthread: bump version to 20200818 + adapt to use CMake to configure the build

- sys/fmt/fmt.c
- sys/include/fmt.h
- tests/unittests/tests-fmt/tests-fmt.c
This re-writes `fmt_s32_dfp()` to be string based (adding "." or "0" instead of using arithmetics). This makes it independent of TENMAP_SIZE.
Code is roughly the same size, performs roughly the same. The dropped tenmap dependency makes binaries ~32b smaller.
> sys/fmt: make fmt_s32_dfp() string based

- .murdock
- boards/common/arduino-due/Kconfig
`sam3` does not seem to need extra modelling, so this just adds does it for the `arduino-due` common group. Build currently limited in 3cade20b79ab5c79c2eb875ed7ada2436f821c2b
- Green CI, and consistent module lists between Makefile and Kconfig.
Part of #16875
> boards/common/arduino due: model kconfig

- drivers/dsp0401/Kconfig
- drivers/dsp0401/Makefile.dep
- drivers/dsp0401/dsp0401.c
- tests/driver_dsp0401/Makefile
- tests/driver_dsp0401/app.config.test
- tests/driver_dsp0401/main.c
This PR migrates the dsp0401 (16 segment alphanumeric LED display) driver to ztimer.
- Green CI
- Test application should still work (let's see if I can wire-up my module and try by the end of the week)
> drivers/dsp0401: migrate to ztimer

- sys/include/atomic_utils.h
- tests/sys_atomic_utils_unittests/main.c
```
$ make -C tests/sys_atomic_utils_unittests flash test
[...]
/home/maribu/Repos/software/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM1" -b "115200" --no-reconnect --noprefix --no-repeat-command-on-empty-line 
Connect to serial port /dev/ttyACM1
READY
s
START
main(): This is RIOT! (Version: 2022.01-devel-709-gc360b-sys/atomic_utils)
.......
OK (7 tests)
make: Leaving directory '/home/maribu/Repos/software/RIOT/tests/sys_atomic_utils_unittests'
```
None
> sys/atomic_utils: add atomic_{load,store}_ptr()

- pkg/openthread/Makefile.dep
- pkg/openthread/contrib/openthread.c
- pkg/openthread/contrib/platform_alarm.c
This PR migrates the openthread package to ztimer (using msec). It's quite straight forward.
- Green CI
- `examples/openthread` is still working (untested yet)
> pkg/openthread: migrate to ztimer

- examples/paho-mqtt/Makefile
- tests/lwip/Makefile
- tests/lwip_sock_ip/Makefile
- tests/lwip_sock_tcp/Makefile
- tests/lwip_sock_udp/Makefile
lwIP can run in dualstack mode, so there is no reason to disable IPv6 just because IPv4 is enabled.
Enabling `LWIP_IPV4` no longer changes the state of `LWIP_IPV6`.
* `tests/lwip_sock_{ip,tcp,udp}` still pass (in any combination with at least one of IPv4/IPv6 enabled)
* `tests/lwip` still pass with dualstack or IPv6 configured
`paho_mqtt` example needs testing - I don't know how to do it. Try connecting against both IPv4 and IPv6 mqtt via `con` shell command?
It looks like it should work: https://github.com/RIOT-OS/RIOT/blob/master/pkg/paho-mqtt/contrib/riot_iface.c#L128
Somewhat related to #17162
> pkg/lwip: Don't control IPv6 via IPv4 flag

- examples/twr_aloha/control.c
- pkg/uwb-core/Kconfig
- pkg/uwb-core/Makefile.dep
- pkg/uwb-core/contrib/uwb_core.c
- pkg/uwb-core/contrib/uwb_core_init.c
- pkg/uwb-core/include/uwb_core.h
- pkg/uwb-dw1000/include/uwb_dw1000_config.h
Some cleanups to the port:
- allow for using a common event thread instead of a custom one, this can save some RAM
- It enables frame filtering but accepting all type of frames with matching PANID, destination address.
- moves common configuration to the init function
`examples/twr_aloha` still works:
```
2021-11-24 17:04:28,351 # main(): This is RIOT! (Version: 2022.01-devel-719-gc860f-pr_pkg_uwb_core_fixes)
2021-11-24 17:04:28,352 # pkg uwb-dw1000 + uwb-core test application
2021-11-24 17:04:28,353 # {"utime": 24578,"exec": "/home/francisco/workspace/RIOT2/examples/twr_aloha/control.c"}
2021-11-24 17:04:28,355 # {"device_id"="deca0130","panid="DECA","addr"="C329","part_id"="cc95c329","lot_id"="82b3107"}
2021-11-24 17:04:28,355 # {"utime": 24578,"msg": "frame_duration = 201 usec"} …
```
> pkg/uwb-core: multiple cleanups

- dist/tools/cppcheck/check.sh
`cppcheck` has a non-zero exit code even on warnings, so to not confuse contributors, align the annotation output with that.
I can add a test commit if necessary.
None
> cppcheck: output all annotations as error

- boards/common/saml1x/Kconfig
SAML1X CPU requires no special handling for Kconfig, this just adds the missing boards common module. The boards using this CPU are:
- saml10-xpro
- saml11-xpro
4afc1e986b3cc9d7833ce40c2d73a0d0da073200 limits the CI to test only these boards.
- Green CI
Part of #16875
> boards/common/saml1x: model kconfig

- sys/test_utils/result_output/Makefile.dep
A sort is missing on the filter to no fault on the same module being twice during a dependency resolution loop.
In master this patch would make it fail:
```
diff --git a/sys/test_utils/result_output/Makefile.dep b/sys/test_utils/result_output/Makefile.dep
index c02452577c..112a71bdde 100644
--- a/sys/test_utils/result_output/Makefile.dep
+++ b/sys/test_utils/result_output/Makefile.dep
@@ -3,6 +3,9 @@ test_utils_result_output_check \
test_utils_result_output_json \
test_utils_result_output_txt
+USEMODULE += test_utils_result_output_json
+USEMODULE += test_utils_result_output_json
+
USED_TURO_OUTPUT_FORMAT := $(filter test_utils_result_output_%,$(USEMODULE))
ifeq (0,$(words $(USED_TURO_OUTPUT_FORMAT)))
```
you get:
```
make -C tests/turo/ 
Only one test_utils_result_output format can be …
```
> sys/test_utils/result_output: add sort to multiple output check

- bootloaders/riotboot_dfu/Makefile
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
- sys/ztimer/init.c
To avoid confusions between `auto_init_ztimer` and `ztimer_auto_init`
rename `ztimer_auto_init` to `ztimer_init`.
This allows for similar handling as `saul_init_devs` and
`auto_init_devs`. Dependencies are therefore done against the USEMODULE
and not DEFAULT_MODULE or checking DISABLE_MODULE. For this, both
`ztimer_init` and `auto_init_ztimer` are added to DEFAULT_MODULE and
both need disabling if the user does not want that module in.
With this, the comment in Kconfig no longer applies.
Murdock should still be green.
> sys/ztimer: remove double ztimer indirection

- .murdock
- Makefile.include
- makefiles/kconfig.mk
When there is a difference between the make dependency resolution and kconfig resolution (ie. `TEST_KCONFIG=1`) this gets murdock to show the diff of the modules and packages.
This gives clearer feedback than the binary mismatch error message.
Note that this comparison only occurs when there is a mismatch and shouldn't affect the a passing PR.
I will add a failure commit so it should be viewable from murdock.
One can also check with
```
/bin/bash -c "source .murdock; JOBS=4 compile ${TEST_DIR} ${BOARD}:gnu"
```
or with the `REMOVEME!!!` commit
```
/bin/bash -c "source .murdock; JOBS=4 compile examples/hello-world native:gnu"
```
> .murdock: Add modules/pkgs diff of make/kconfig

- boards/alientek-pandora/Kconfig
- boards/alientek-pandora/Makefile
- boards/alientek-pandora/Makefile.dep
- boards/alientek-pandora/Makefile.features
- boards/alientek-pandora/Makefile.include
- boards/alientek-pandora/board.c
- boards/alientek-pandora/doc.txt
- boards/alientek-pandora/include/board.h
- boards/alientek-pandora/include/gpio_params.h
- boards/alientek-pandora/include/periph_conf.h
Alientek Pandora (product info [link](http://www.alientek.com/productinfo/716137.html), board pinout [link](https://blog.csdn.net/weixin_40973138/article/details/89042523)) is a development board with an stm32l475ve. This adds support for serial stdio, RGB-LED and buttons on board for RIOT operating system.
> boards: add board support for Alientek Pandora

- dist/tools/ci/static_tests.sh
cppcheck produces too many false positives to be useful.
This is likely due to a configuration error (not all header files are included?) but until this is sorted out, disable the tool as it currently does more harm than good.
> static-tests: disable cppcheck

- boards/stm32f746g-disco/Kconfig
- boards/stm32f746g-disco/Makefile.features
- boards/stm32f746g-disco/include/periph_conf.h
This PR provides and configure usbdev feature to the stm32f746g-disco board. The change is straight forward.
- Green CI
- USB is working:
<details><summary>Using `examples/usbus-minimal`</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=stm32f746g-disco -C examples/usbus_minimal flash term --no-print-directory  …
```
> boards/stm32f746g-disco: add usbdev feature

- drivers/sx126x/Kconfig
- tests/driver_sx126x/app.config.test
Split from #17232. This rework how sx126x driver modules are selected, making the entry-point the driver module and using a choice for model selection, in combination with features to default to the correct option.
- Check that the new model makes sense and shows up correctly in menuconfig
- Green CI
#17232
> drivers/sx126x/Kconfig: rework model selection

- tests/unittests/tests-base64/tests-base64.c
This PR fixes `base64url_encode()` using some space "behind" the supplied output buffer.
Found with `make -Ctests/unittests all-asan tests-base64`.
<details>
```
❯ /home/kaspar/src/riot/tests/unittests/bin/native/tests_unittests.elf
RIOT native interrupts/signals initialized.                  
LED_RED_OFF                                                              
LED_GREEN_ON                                                             
RIOT native board initialized.                                           
RIOT native hardware initialization complete.                
main(): This is RIOT! (Version: 2022.01-devel-716-g45add4)          
rs                                                                       
READY …
```
> tests/unittests/tests-base64: enlarge test buffer for worst case

- sys/shell/commands/sc_gnrc_icmpv6_echo.c
`msg_avail()` will return -1 if the thread has no message queue.
Casting this to unsigned will result in the `ping` command to try receiving 4294967295 messages, which hangs the shell.
Drop the cast to `unsigned` and the loop behaves as intended.
But then it's still wrong: If new messages become available, they would be ignored.
So change the `for` loop to a `while` loop. The index variable is not used at all.
> shell/gnrc_icmpv6_echo: Fix hang with no msg queue

- .murdock
- boards/common/qn908x/Kconfig
- boards/qn9080dk/Kconfig
- cpu/qn908x/Kconfig
- cpu/qn908x/Makefile.dep
- cpu/qn908x/periph/Kconfig
- cpu/qn908x/vendor/Kconfig
- makefiles/features_modules.inc.mk
This models modules for qn908x CPU and the only board that uses it: qn9080dk
- Green CI
- Module list between makefile and Kconfig should match.
Part of #16875
> cpu/qn908x: model kconfig

- drivers/include/soft_spi.h
- drivers/soft_spi/soft_spi.c
- pkg/u8g2/contrib/u8x8_riotos.c
- sys/include/xtimer.h
This PR deprecates `nanosleep`, realistically this made no sense since no backend was able at running at this speed.
A green ci should be enough...
> sys/include/xtimer.h: deprecate nanosleep

- tests/pthread_barrier/tests/01-run.py
- tests/thread_float/tests/01-run.py
A simple PR that replaces the fstring formatting in the tests with a `.format` to support the older version of python use in the pi-fleet for the nightly HiL tests.
run murdock with hil tests
> tests/*: Fix nightly failures due to f-string

- sys/include/net/gnrc/sixlowpan/frag/rb.h
- sys/net/gnrc/network_layer/sixlowpan/frag/sfr/gnrc_sixlowpan_frag_sfr.c
This PR fixes compilation with `-Wcast-align`. It also adds a `static_assert()` to check that the alignment is indeed word size (why word size: Because the alignment of `uint32_t` is word sized for all architectures).
1. No change in generated binaries
2. Compilation should fail if the following patch is applied
```diff
diff --git a/sys/include/net/gnrc/sixlowpan/frag/rb.h b/sys/include/net/gnrc/sixlowpan/frag/rb.h
index 2cf6110b38..b6395a6938 100644
--- a/sys/include/net/gnrc/sixlowpan/frag/rb.h
+++ b/sys/include/net/gnrc/sixlowpan/frag/rb.h
@@ -101,13 +101,14 @@ typedef struct {
*/
gnrc_pktsnip_t *pkt;
#if IS_USED(MODULE_GNRC_SIXLOWPAN_FRAG_SFR) || defined(DOXYGEN)
+    uint8_t padding;
/**
* @brief   Bitmap for received fragments
*
* @note    Only available with module …
```
> sys/net/gnrc: fix compilation with -Wcast-align

- pkg/nimble/Makefile.include
- pkg/nimble/contrib/include/nimble_riot.h
- pkg/nimble/netif/nimble_netif.c
In current master, the thread priority of the nimble host could only be overridden, if `nimble_netif` is not used. This PR allows to override the nimble host thread priority no matter what by moving the priority override from nimbles `Makefile.include` into the `nimble_netif.h`, where the host priority is defined in the first place. This should be much cleaner and easier to comprehend...
Additionally, this PR adds the option to override the thread priority of the `nimble_netif` thread specifically. Before, this was hard coded to always be `GNRC_NETIF_PRIO`. However, when playing with border router configurations, I found that there might be problems when assigning the same thread prio to NimBLE and e.g. usb-cdc-ecm devices. So at least for debugging it is quite useful to have more precise …
> nimble: allow to override host and netif thread priorities

- drivers/dfplayer/dfplayer.c
- drivers/feetech/feetech.c
- drivers/grove_ledbar/grove_ledbar.c
- drivers/hmc5883l/hmc5883l.c
- drivers/hts221/hts221.c
- drivers/sds011/sds011_saul.c
- drivers/si114x/si114x_saul.c
- drivers/tsl2561/tsl2561_saul.c
- drivers/vcnl40x0/vcnl40x0_saul.c
- drivers/veml6070/veml6070.c
- drivers/veml6070/veml6070_saul.c
- drivers/ws281x/atmega.c
- drivers/ws281x/esp32.c
Some old drivers were still including xtimer in their implementation although it's unused.
A green CI should be enough
None
> drivers: remove some useless xtimer includes

- sys/net/network_layer/fib/fib.c
It might make sense to verify that a `memcpy()` is indeed needed. If one could deduce that alignment is provided at the caller site under all circumstances, the `memcpy()` introduced unneeded overhead.
> sys/net/fib: fix compilation with -Wcast-align

- .murdock
- cpu/nrf9160/Kconfig
- cpu/nrf9160/vectors/Kconfig
These models modules for nrf9160 CPU and the only BOARD using it.
- Green CI
- Module list between makefile and Kconfig should match.
Part of #16875
> cpu/nrf9160: add Kconfig dependencies

- drivers/include/periph/rtt.h
- sys/include/ztimer.h
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
- sys/ztimer/Makefile.include
- tests/ztimer_msg/Makefile
- tests/ztimer_underflow/Makefile
This PR splits the initial approach in #17099 to its own PR to be easier to compare. Instead of `DEFAULT_MODULE` a module can be included to disable auto-inclusion. The advantage being that there is no `ztime_auto_select_rtt` module used even where `ztimer`is not used.
```
sys/ztimer: add 'ztimer_no_periph_rtt'
This is a temporary fix for Issue #17060. It allows to disable
auto inclusion of `ztimer_periph_rtt` in cases where another
module or application requires direct access.
Limitations:
- as ifeq are involved order of inclusion matters, therefore
these modules should be included early in the build at application
level and not in modules `Makefile.dep`
- this does not disallow direct inclusions of `ztimer_periph_rtt`,
since this only disables auto inclusion of these modules
This is a …
```
> sys/ztimer: add 'ztimer_no_periph_rtt'

- sys/Makefile.dep
It seems in the original PR the dependency was not adapted to the name change. Also this module depends on ztimer, there is no need for `event_timeout`.
> sys/Makefile.dep: fix event periodic dependency

- dist/tools/zep_dispatch/main.c
- dist/tools/zep_dispatch/topology.c
- dist/tools/zep_dispatch/topology.h
This adds support for a sniffer node to the non-flat topology in ZEP dispatcher
A sniffer is a node (e.g. [foren6](https://cetic.github.io/foren6/)) that should receive every packet sent by any node.
For the flat topology we don't have to do anything as this will by default forward every packet to every node.
In 'advanced' topology mode we have to add a special case: The sniffer should not take up a spot in the topology but instead will just receive a copy of every packet sent by any node.
To identify the sniffer node, the sniffer will not include a (virtual) MAC address in it's HELLO packet.
I have a patched version of foren6 that includes support for a ZEP sniffer interface: https://github.com/benpicco/foren6
With this it is possible to analyze a virtual RPL network on `native`:
- build …
> tools/zep_dispatch: add support for foren6 sniffer

- drivers/ili9341/Kconfig
This adds a symbol to indicate the presence of an ili9341 display on a board in Kconfig. When present and `MODULE_DISP_DEV` is enabled, it enables the driver.
- No board is actually using this so far, but needed for #17232
- Green CI
#17232
> drivers/ili9341/Kconfig: add feature to indicate hardware

- .murdock
- boards/common/msb-430/Kconfig
- boards/common/msb-430/Makefile
- boards/msb-430/Kconfig
- boards/msb-430/Makefile.dep
- boards/msb-430h/Makefile.dep
- cpu/msp430_common/Kconfig
- cpu/msp430_common/Makefile.dep
- cpu/msp430fxyz/Makefile.dep
These models modules for msp430 CPU. Only z1 is added to `.murdock` except for the one REMOVE ME commit. 
Netdev is not modeled, since there is also discussion on removing `cc2420`
- Green CI
- Module list between makefile and Kconfig should match.
Part of #16875
> cpu/msp430: add Kconfig

- tests/malloc/main.c
There is a corner cases in which the counting of allocated memory
previously was wrong: When the allocation of the chunk succeeded but the
allocation of the next struct  node fails. This was relatively unlikely
to happen, as the chunk size was much bigger than the memory required by
the struct node. But it happens on the ESP32 boards resulting in failing
nightlies. This fixes the issue.
The test should now succeed on both ESP32 and non ESP32 boards.
None
> tests/malloc: fix counting bugs

- boards/nrf9160dk/include/board.h
LED macros were inverted, so `LEDn_ON` would turn the LED off and `LEDn_OFF` would turn it on.
From the board [HW user guide](https://infocenter.nordicsemi.com/pdf/nRF9160_DK_HW_User_Guide_v1.0.0.pdf) (p. 25): 
> The LEDs are active high, meaning that writing a logical one ('1') to the output pin will illuminate the LED.
I confirmed this locally.
- Using `tests/leds` you should see one LED blinking at a time and the rest off. On master the the rest of the LEDs are on.
#16650
> boards/nrf9160dk: fix LED macros

- dist/tools/ci/README.md
- dist/tools/ci/can_fast_ci_run.py
This PR add a simply script to check if a PR could be tested with a fast CI run that only builds a subset of apps and/or all apps for a subset of boards.
Check the [provided documentation of the tool](https://github.com/maribu/RIOT/tree/dist/tools/ci/dist/tools/ci#checking-if-fast-ci-runs-are-sufficient) for more details.
This PR contains a commit that contains a bunch of bogus changes that do not justify full rebuild. Run the script as specified and it should give you a list of build targets as JSON.
None
> dist/tools/ci: add can_fast_ci_run.py

- sys/net/application_layer/sock_dns/dns.c
Needed by the following code in `dns.c`:
https://github.com/RIOT-OS/RIOT/blob/e8cbc6da85c2f5c39f2f970e058ff7747bcd2ad2/sys/net/application_layer/sock_dns/dns.c#L39-L41
The `string.h` include was present previously and probably wrongfully removed by accident in e8cbc6da85c2f5c39f2f970e058ff7747bcd2ad2 (CC: @miri64).
> sock_dns: include string.h for strlen(3) function prototype

- sys/net/link_layer/ieee802154/ieee802154.c
- tests/unittests/tests-ieee802154/tests-ieee802154.c
In current master, when running `make -C tests/unittests all-asan tests-ieee802154` and the `make -C tests/unittests test`, the address sanitizer reports several stack-buffer overflows within `sys/net/link_layer/ieee802154/ieee802154.c`. While some of these errors are indeed too short test vectors within the unittests, it also revealed a parser bug in `ieee802154_get_src()`, when it tries to read a PAN ID for a source address in reserved mode (which is unspecified behavior and also reported by the function with an `-EINVAL` as such, but it still tries to read the PAN ID which is not there).  
```sh
make -C tests/unittests all-asan tests-ieee802154
make -C tests/unittests test
```
should succeed for this PR's HEAD.
```sh
make -C tests/unittests tests-ieee802154
make -C tests/unittests test …
```
> ieee802154 / tests/unittests: fix all-asan reported errors

- sys/net/gnrc/routing/rpl/gnrc_rpl_auto_init.c
If there is only a single interface, we can auto-init RPL without an additional user supplied define. 
Handle this the same as the `gnrc_netif_highlander()` case. 
Run `examples/gnrc_networking`. You now don't have to specify
CFLAGS=-DCONFIG_GNRC_RPL_DEFAULT_NETIF=7 
anymore to auto-start RPL.
```
> rpl
RPL not initializied
```
```
> rpl
instance table:	[ ]	
parent table:	[ ]	[ ]	[ ]	
```
> gnrc/rpl: auto-init RPL if there is only a single interface

- boards/iotlab-m3/Makefile.dep
- boards/iotlab-m3/doc.txt
- boards/iotlab-m3/include/board.h
- boards/iotlab-m3/include/periph_conf.h
- boards/iotlab-m3/mtd.c
The board comes with a 16 MiB SPI-NOR flash (N25Q128).
Provide the needed MTD definitions to support it.
If you have an account on the IoT Lab you can create a [new experiment](https://www.iot-lab.info/testbed/dashboard). 
Select a `m3` node, e.g. in `grenoble` and select the firmware to flash. If you need to re-flash the firmware, make sure to reload the page before each flashing of a new firmware as otherwise the flash process will hang.
Connect with `ssh` to `grenoble.iot-lab.info` and connect to your node with `nc m3-$NODE 20000` where `$NODE` is the node ID of the node that was assigned to you.
This way you can flash e.g. `tests/mtd_raw`:
```
main(): This is RIOT! (Version: 2022.01-devel-964-g83291)
Manual MTD test
init MTD_0… OK (16 MiB)
> test 0
[START]
[SUCCESS]
> info
mtd …
```
> boards/iotlab-m3: add MTD definition

- drivers/ccs811/ccs811.c
- drivers/include/ccs811.h
- tests/driver_ccs811/README.md
- tests/driver_ccs811/main.c
- tests/driver_ccs811_full/README.md
- tests/driver_ccs811_full/main.c
PR #16215 fixed the handling of the error returned by function `ccs811_read_iaq`. After this change, however, the test applications didn't work anymore for me because of a bug in the driver function `ccs811_read_iaq`. 
The `DATA_RDY` flag in the `STATUS` register which is part of the `ALG_RESULT_DATA` register set is already cleared when the `ALG_RESULT_DATA` register set, although it was definitely set before when checking for new data with the `ccs811_data_ready` function or the interrupt due to new data. So it seems that the `DATA_RDY` is cleared as soon as the reading of the `ALG_RESULT_DATA` register set starts. Thus the `DATA_RDY`  can't be checked in the resulting data. Therefore the function always returned `CCS811_ERROR_NO_NEW_DATA` and the test applications worked before PR …
> driver/css811: fix read status

- makefiles/pseudomodules.inc.mk
As the title says, the PCF7857x pseudomodule definitions that were accidentally added by PR #10430 are removed.
The pseudomodules used by the PCF7857x driver are correctly defined by the `Makfefile.include` of the driver. However, by mistake they were left in `makefiles/pseudomodules.mk` when the very old PR was rebased to the current master. That is, they were only leftovers that have been overseen after rebasing an squashing dozens of fixup commits.
Compilation in Murdock succeed.
Added with PR #10430
> makefiles: remove PCF857x pseudomodule definitions

- pkg/nimble/autoconn/nimble_autoconn.c
- pkg/nimble/rpble/nimble_rpble.c
- pkg/nimble/scanner/include/nimble_scanner.h
- pkg/nimble/scanner/nimble_scanner.c
follow up on #16843: some things were missed :-)
This PR fixes regressions introduced by #16843: 
- setting the scan duration in the `nimble_scanner` was faulty: `BLE_HS_FOREVER` was never applied correctly when using extended advertisements and the delay was never applied to legacy advertisements in the first place
- for `nimble_autoconn` and `nimble_rpble` the scanning did not work anymore, as we forgot to set the `NIMBLE_SCANNER_PHY_1M` flag...
- use `tests/nimble_autoconn_gnrc` and `tests/nimble_rpble` examples to verify that nodes successfully connect to one another
- the `nimble_scanner_set_duration()` function is nowhere used in the RIOT codebase (its initial PR did not provide a test with it...), so I'd say manual code review should suffice for now.
fixes regressions of #16843
> nimble: fix nimble_scanner regression bugs

- pkg/nimble/statconn/include/nimble_statconn.h
- pkg/nimble/statconn/nimble_statconn.c
- sys/shell/commands/sc_nimble_statconn.c
I recently ported most of the nimble submodules from using custom return values to using `errno` values. This PR applies that same changes to `nimble_statconn` to make this module more coherent to the rest. Should be pretty straight forward...
Code review and build test should do the trick.
none
> nimble/statconn: use errno return values

- pkg/uwb-core/include/uwb_core.h
Pretty dumb mistake because of lazy testing on my side.
This now compiles:
```
USEMODULE=uwb-core_twr_aloha make -C examples/twr_aloha/ -j
Building application "twr-aloha" for "dwm1001" with MCU "nrf52".
"make" -C /home/francisco/workspace/RIOT/pkg/mynewt-core
"make" -C /home/francisco/workspace/RIOT/pkg/uwb-core
"make" -C /home/francisco/workspace/RIOT/pkg/uwb-dw1000
"make" -C /home/francisco/workspace/RIOT/build/pkg/uwb-core/lib/dsp/src -f /home/francisco/workspace/RIOT/Makefile.base MODULE=uwb-core_dsp
"make" -C /home/francisco/workspace/RIOT/build/pkg/uwb-core/lib/uwb_rng/src -f /home/francisco/workspace/RIOT/Makefile.base MODULE=uwb-core_rng
"make" -C /home/francisco/workspace/RIOT/build/pkg/uwb-core/lib/rng_math/src -f /home/francisco/workspace/RIOT/Makefile.base …
```
> pkg/uwb-core: fix wrong header include

- cpu/qn908x/Makefile.dep
- cpu/qn908x/periph/Kconfig
- cpu/qn908x/periph/adc.c
This PR migrates the ADC implementation of the qn908x cpu to ztimer. The missing dependency resolution is also added.
- `tests/periph_adc` should still work on this platform (but I can't test unfortunately). Maybe @iosabi you can give this a try ?
> cpu/qn908x: migrate ADC periph to ztimer

- drivers/bme680/Kconfig
- drivers/bme680/Makefile.dep
- drivers/bme680/bme680_saul.c
- pkg/cryptoauthlib/Makefile.dep
- pkg/cryptoauthlib/contrib/atca.c
- pkg/driver_bme680/Kconfig
- pkg/driver_bme680/Makefile.dep
- pkg/driver_bme680/contrib/bme680_hal.c
- pkg/u8g2/Kconfig
- pkg/u8g2/Makefile.dep
- pkg/u8g2/contrib/u8x8_riotos.c
- pkg/ucglib/Kconfig
- pkg/ucglib/Makefile.dep
- pkg/ucglib/contrib/ucg_riotos.c
- tests/driver_bme680/Makefile
- tests/driver_bme680/app.config.test
- tests/driver_bme680/main.c
- tests/pkg_u8g2/Makefile
- tests/pkg_u8g2/main.c
- tests/pkg_ucglib/main.c
This PR migrates a few packages to ztimer:
- cryptoauthlib
- driver_bme680
- u8g2
- ucglib
The changes are quite straight forward but needs careful review because of conversions used.
After that PR only lwip and tinydtls will be missing. lwip is addressed by #17115. For tinydtls, we will have to check its dependencies since some are still using xtimer and evtimer.
- Green CI
- The affected applications are still working but unfortunately I don't have the hardware (maybe I have a bme680 somewhere but need to find it)
**test output:**
<details><summary>bme680:</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=b-l475e-iot01a -C tests/driver_bme680 flash term --no-print-directory 
docker run --rm --tty --user $(id -u) -v …
```
> pkg: migrate some packages to ztimer

- cpu/sam0_common/periph/uart.c
- drivers/dose/dose.c
Previously we would not disable the sense pin, this meant that a node could still wake up if the standby pin is not connected.
Properly disable sensing when in standby and wait for a state transition to IDLE to avoid aborting a reception and messing up the DOSE internal state.
Standby / Sleep mode still work
```
2021-11-11 14:30:18,950 #  ping ff02::1
2021-11-11 14:30:18,958 # 12 bytes from fe80::649b:87ff:fe4c:5752%5: icmp_seq=0 ttl=64 time=1.596 ms
2021-11-11 14:30:18,965 # 12 bytes from fe80::ac8d:c2ff:fe75:35de%5: icmp_seq=0 ttl=64 time=8.182 ms (DUP!)
2021-11-11 14:30:19,958 # 12 bytes from fe80::649b:87ff:fe4c:5752%5: icmp_seq=1 ttl=64 time=1.594 ms
2021-11-11 14:30:19,965 # 12 bytes from fe80::ac8d:c2ff:fe75:35de%5: icmp_seq=1 ttl=64 time=8.180 ms (DUP!)
2021-11-11 14:30:20,959 # …
```
> drivers/dose: fix standby mode

- sys/picolibc_syscalls_default/syscalls.c
This PR changes our picolibc stdin and stderr to be string references to stdout, allowing to share flash space for them, if used.
Result:
PR:
```
riot/examples/default on  picolibc_stdio_strong_reference 
❯ FEATURES_REQUIRED=picolibc USEMODULE=picolibc RIOT_CI_BUILD=1 BOARD=nrf52840dk make clean all -j8 
Building application "default" for "nrf52840dk" with MCU "nrf52".
text    data     bss     dec     hex filename
34936     416    6348   41700    a2e4 /home/kaspar/src/riot/examples/default/bin/nrf52840dk/default.elf
```
master:
```
❯ FEATURES_REQUIRED=picolibc USEMODULE=picolibc RIOT_CI_BUILD=1 BOARD=nrf52840dk make clean all -j8                                      [35/34163]
Building application "default" for "nrf52840dk" with MCU "nrf52".
text    data     bss     dec     hex filename …
```
> sys/picolibc_syscalls_default: make stdin and stderr strong refs

- makefiles/stdio.inc.mk
- sys/stdio_rtt/README.md
- sys/stdio_rtt/stdio_rtt.c
- tests/events/main.c
- tests/unittests/tests-rtt_rtc/Makefile.include
Convert `stdio_rtt` to ztimer
Tested on the nRF52840dk by adding `USEMODULE += stdio_rtt` to the default example:
```Shellsession
koen@morgen ~/dev/RIOT-review $ make -C examples/default/ BOARD=nrf52840dk RIOT_TERMINAL=jlink term                 
make: Entering directory '/home/koen/dev/RIOT-review/examples/default'                                              
/home/koen/dev/RIOT-review/dist/tools/jlink/jlink.sh term-rtt                                                       
help                                                                                                                
2021-11-03 11:18:26,828 # Host name for TCP connection is missing, defaulting to "localhost" …
```
> stdio_rtt: Convert to ztimer

- sys/include/isrpipe.h
- sys/isrpipe/isrpipe.c
The `isrpipe` module is lacking a function to add a batch of values so we don't need to externally loop on `isrpipe_write_one`. This PR introduces `isrpipe_write`.
There is no dedicated test for `isrpipe` but it's basically covered by the test of `tsrb` already.
> sys/isrpipe: add isrpipe_write

- tests/ieee802154_hal/app.config.test.native
#16932 introduced `app.config.test.native` but back when that PR was created the default was still tinymt32.
Now the default is musl lcg - this must also be reflected by Kconfig.
Fixes CI build
```
-- running on worker riotbuild-0 thread 3, build number 9661.
make: Entering directory '/tmp/dwq.0.915265949079789/4a5d8cd9d792a713bd5ebbf844208c96/tests/ieee802154_hal'
make: Leaving directory '/tmp/dwq.0.915265949079789/4a5d8cd9d792a713bd5ebbf844208c96/tests/ieee802154_hal'
make: Entering directory '/tmp/dwq.0.915265949079789/4a5d8cd9d792a713bd5ebbf844208c96/tests/ieee802154_hal'
Building application "tests_ieee802154_hal" for "native" with MCU "native".
sha1sum /tmp/dwq.0.915265949079789/4a5d8cd9d792a713bd5ebbf844208c96/build/tests_ieee802154_hal.elf > …
```
> tests/ieee802154_hal: fix default RNG selection

- sys/event/periodic.c
- sys/include/event/periodic.h
- sys/ztimer/periodic.c
- tests/event_ztimer/main.c
This PR adds a count parameter to the `event_periodic` api, this allows setting a periodic event for x iterations.
Not sure if this should be optional to keep api compatibility, the api is quite new. I could also add a new `event_periodic_start_n()` for `n` times, and leave the old function as is, or another name.
```
make -C tests/event_ztimer/ flash test -j
Building application "tests_event_ztimer" for "native" with MCU "native".
"make" -C /home/francisco/workspace/RIOT/boards/native
"make" -C /home/francisco/workspace/RIOT/cpu/native
"make" -C /home/francisco/workspace/RIOT/sys
"make" -C /home/francisco/workspace/RIOT/boards/native/drivers
"make" -C …
```
> sys/include/event/periodic: add count

- .gitignore
- examples/thread_duel/Makefile
- examples/thread_duel/Makefile.ci
- examples/thread_duel/README.md
- examples/thread_duel/main.c
- sys/Makefile.dep
- sys/auto_init/auto_init.c
- sys/include/sched_round_robin.h
- sys/sched_round_robin/Kconfig
- sys/sched_round_robin/Makefile
- sys/sched_round_robin/sched_round_robin.c
- tests/sys_sched_round_robin/Makefile
- tests/sys_sched_round_robin/Makefile.ci
- tests/sys_sched_round_robin/README.md
- tests/sys_sched_round_robin/main.c
- tests/sys_sched_round_robin/tests/01-run.py
I would like to use RIOT with multiple threads at the same priority,
that might not cooperate but should share CPU time. see #14810
sys is not allowed to access core structures see  #14810
core is not allowed to rely sys/xtimer see #15069
a core/timer is unlikely to come #15080 
This:
- implements the timing part in a module in sys and
- adds an interface to core that provides information about the runqueues and the core round robin functionality. 
- adds an thread duel example with multiple implementations for concurrent thread 
This round robin scheduler, round robins the active priorities runqueue -that was what #14810 did- , if there is more than one thread. 
It uses extra information to activate or inactivate -this was added with #15069-:
- It is inactivated if the last thread leaves …
> sys/sched_rr: Add a round robin scheduler module

- cpu/esp_common/periph/i2c_sw.c
- drivers/aip31068/Makefile.dep
This PR adds a clear bus mechanism to the I2C software implementation, which is executed during initialization.
On the ESP32 it it often not possible with the I2C software implementation to communicate with an AIP31068 based LCD module.  Therefore, the I2C hardware implementation is enabled when the AIP31068 driver is used. The timing of the two implementations seems to be almost identical. The only difference is that the hardware implementation clears the bus before each access by sending 10 clock pulses on the SCL line while the SDA is held LOW. Using the same mechanism during the I2C initialization for the software implementation solves the communication problem with the AIP31068.
Because the I2C hardware implementation is more buggy than stable and the AIP31068 driver is the only …
> cpu/esp32: add clear bus during init to the I2C software implementation

- cpu/atmega_common/include/cpu_conf.h
- makefiles/pseudomodules.inc.mk
- sys/Kconfig
- sys/Makefile.dep
- sys/auto_init/auto_init.c
- sys/include/ztimer64.h
- sys/ztimer/periph_timer.c
- sys/ztimer64/Kconfig
- sys/ztimer64/Makefile
- sys/ztimer64/Makefile.dep
- sys/ztimer64/overhead.c
- sys/ztimer64/util.c
- sys/ztimer64/ztimer64.c
- tests/unittests/tests-ztimer64/Makefile
- tests/unittests/tests-ztimer64/Makefile.include
- tests/unittests/tests-ztimer64/tests-ztimer64-core.c
- tests/unittests/tests-ztimer64/tests-ztimer64.c
- tests/unittests/tests-ztimer64/tests-ztimer64.h
- tests/ztimer64_msg/Makefile
- tests/ztimer64_msg/Makefile.ci
- tests/ztimer64_msg/README.md
- tests/ztimer64_msg/app.config.test
- tests/ztimer64_msg/main.c
- tests/ztimer64_msg/tests/01-run.py
This PR contains my work on a 64bit ztimer. As discussed before, this is a new module that sits on top of ztimer(32), and uses that as backend.
Pros:
- only users pay, compared to current ztimer_now64, which causes overhead to *every* ztimer user when used by a single module
- keeps ztimer32 simpler, extra logic is here
- ztimer64 can base on ztimer32 (with conversions, extension, ...), making ztimer64 quite a bit simpler than ztimer32
Cons:
- duplicate list management
- probably others
Envisioned usage:
Each ztimer64 instance needs a ztimer(32) backend clock. Initialization is simple:
`ztimer64_init(ZTIMER64_MSEC, ZTIMER_MSEC);`
I'd suggest mirroring the ztimer32 ones, e.g.,
there'd be ZTIMER64_MSEC, ZTIMER64_USEC, ..., with corresponding ztimer64_Xsec pseudomodules that modules/apps can …
> sys/ztimer64: initial PR

- Makefile.include
- boards/6lowpan-clicker/doc.txt
- boards/pic32-wifire/doc.txt
- cpu/mips_pic32_common/doc.txt
- makefiles/deprecated_boards.inc.mk
- makefiles/deprecated_cpus.inc.mk
Add deprecate note in the mips cpu.
Add warning in make when any mips based board is being used (6lowpan-clicker, pic32-wifire).
After some discussion on the forum and between some maintainers we have decided to drop mips cpu as nobody is willing to continue to maintain it.
Read the docs and run:
```
BOARD=6lowpan-clicker make all -C examples/hello-world/ && BOARD=pic32-wifire make all -C examples/hello-world/
```
then check for the error messages.
Related to #11788
[Forum post discussing dropping mips] (https://forum.riot-os.org/t/dropping-support-of-outdated-poorly-supported-boards-and-modules/3343/19)
> cpu/mips: deprecate mips cpu

- core/include/debug.h
- cpu/gd32v/periph/timer.c
- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
- drivers/mtd_spi_nor/mtd_spi_nor.c
- drivers/stmpe811/stmpe811_touch_dev.c
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/dsm/dsm.c
- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c
- sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c
- sys/ut_process/ut_process.c
Since the DEBUG and DEBUG_PUTS macros include semicolons in their definition, using a semicolon after their invocations in other files is unneeded, and certain code inspection programs output this as a code smell/bug. At the same time, a line which doesn't end in a semicolon looks weird in C so I propose this change.
> core/include/debug.h: minor fix in debug.h

- cpu/sam0_common/Makefile.dep
- cpu/stm32/periph/usbdev_fs.c
> cpu: remove unused `xtimer.h` headers

- cpu/atxmega/include/cpu_conf.h
While cleaning up all xtimer users in `cpu` I noticed we missed this in #16928. I don't have a BOARD to test, put I think the change is straight forward enough.
`tests/ztimer64_msg` on a atxmega, maybe @maribu?
Cleanup from #16928
> cpu/atxmega/include/cpu_conf: ztimer64 arithmetic idle stack fix

- examples/cord_epsim/main.c
- sys/Makefile.dep
- sys/include/net/gcoap.h
- sys/net/application_layer/gcoap/gcoap.c
- tests/unittests/main.c
- tests/unittests/tests-rtt_rtc/Makefile.include
- tests/unittests/tests-ztimer/tests-ztimer-convert-muldiv64.c
switches gcoap to use ztimer
run and manualy test with examples/gcoap
~waiting for #16958 which would enable ztimer_msec  use~
> net/gcoap: port to ztimer

- sys/ztimer64/ztimer64.c
- tests/unittests/tests-ztimer64/tests-ztimer64-core.c
ztimer64's `_is_set()` might return true on uninitialized timer structs. e.g., `ztimer64_set()` would then call `_del_entry_from_list()`, which expects the clock's list to be non-empty.
This might cause a NULL dereference.
This PR adds an early out to `_del_entry_from_list()` to handle that case.
There's a regression test. Revert 7b9a6850a3fc11b22d202229edd6a9af8df9d3b3 to see the unittests crash.
> sys/ztimer64: make _del_entry_from_list() safe for uninit ztimer64_t

- LOSTANDFOUND.md
This PR  fixes the the reference to the commit for removing the `libcoap` package in `LOSTANDFOUND.md`.
With PR #17163 for removing the `libcoap` package, the file `LOSTANDFOUND.md` was updated to reference the corresponding commit. However, when the PR was merged, the commit got a different ID. Thus, the reference in `LOSTANDFOUND.md` was wrong.
`make doc` with doxygen 1.9.2 or 1.8.17 and check `doc/doxygen/html/md_LOSTANDFOUND.html`
Without the PR, the term in brackets is just a text, with this PR it is a link.
```
pkg/libcoap [d83d08f0995a88f399e70a7d07b44dd780082436]
```
Found when investigating issue #17063
> doc: fix the reference to libcoap removal commit in LOSTANDFOUND.md

- boards/lora-e5-dev/Makefile.include
This fixes the default OSX PORT, I don't have OSX but just fixed this for a student running on OSX and it worked. Note that this BOARD is under USB0 on linux, and the new default matches the one for other BOARDs under USB0.
- Just checking the code should do
> boards/lora-e5-dev: fix default DARWIN port

- .murdock
When limiting builds by just adding `BOARDS` or `APPS`, murdock calls "make info-boards-supported", then filters by BOARDS. This is slower than just exporting BOARDS, which is honoured by "make info-boards-supported".
This PR adds some (uncommented) examples on how to limit builds, with "export" in place. Hopefully users will use those in the future.
> murdock: add some doc on how to efficiently limit builds

- sys/ztimer/Makefile.dep
With the introduction of `ztimer_no_periph_rtt` in #17284 `ztimer_msec` and `ztimer_sec` don't fallback to `ztimer_periph_timer` when the pseudomodule is active. This adds the fallback selection again.
- Something like `BOARD=samr21-xpro USEMODULE="ztimer_msec ztimer_no_periph_rtt" make -C examples/hello-world/` should work with this PR, but fails on master due to lack of backend selection.
#17284
> sys/ztimer: fix backend selection

- boards/esp32-wrover-kit/Makefile.dep
- boards/esp32-wrover-kit/include/board.h
- boards/esp8266-olimex-mod/Makefile.dep
- cpu/esp32/Makefile.include
- cpu/esp32/periph/timer.c
- cpu/esp8266/periph/timer.c
A number of optional ESP modules (#12960) can be used by an application to select additional features of the ESP implementation. Since these optional ESP modules are not enabled by default, they are not covered by the compilation test in CI. This led to compilation issues in the past from time to time, for example #17305.
This PR adds some dependencies for two boards (an ESP8266 and an ESP32 board) that enable all these optional ESP modules when compiled in the CI. Some of these optional ESP models are used by these boards by default, others are only used in certain test applications depending on the use of other modules.
This PR is a try to solve the problem without the necessity to create copies of existing test applications for these optional modules like in PR #12971 or to define a …
> cpu/esp: compile optional modules in CI

- LOSTANDFOUND.md
This PR is a follow-up of PR #17371. It reverts the commit c558599b2895db141ba089a719df3b503538aac8 and adds the missing reference.
With PR RIOT-OS#17163 for removing `libcoap`, the file `LOSTANDFOUND.md` was updated to reference the commit for removing `libcoap`. The reference was not defined at the end of the file.
`make doc` with doxygen 1.9.2 or 1.8.17 and check `doc/doxygen/html/md_LOSTANDFOUND.html`
Without the PR, the term in brackets is just a text, with this PR it is a link.
```
pkg/libcoap [d83d08f0995a88f399e70a7d07b44dd780082436]
```
Follow-up of PR #17371
> doc: fix libcoap removal commit

- pkg/driver_bme680/Kconfig
As indicated by @gschorcht [here](https://github.com/RIOT-OS/RIOT/commit/18c937ab697a1c8bc178dc7268b6991f9824da11#r61736966), the BME680 package cannot be used by itself, but is needed for RIOT BME680 driver. The user should not select this directly, so we remove the prompt and additionally add a dependency on the driver.
- Check menuconfig, the package should not be selectable.
- Green CI, the test application should work as usual.
#15466
> pkg/driver_bme680/kconfig: remove prompt and depend on driver module

- cpu/efm32/periph/wdt_series0.c
- cpu/efm32/periph/wdt_series1.c
- pkg/littlefs2/Makefile.include
- pkg/qr-code-generator/Makefile
- pkg/u8g2/Makefile.u8g2_csrc
- pkg/wakaama/contrib/lwm2m_client.c
- sys/fuzzing/netdev.c
- sys/net/gnrc/network_layer/ipv6/ext/opt/gnrc_ipv6_ext_opt.c
- tests/bitarithm_timings/main.c
- tests/candev/main.c
- tests/gnrc_ipv6_ext_frag/main.c
- tests/gnrc_sixlowpan_frag_minfwd/mockup_netif.c
- tests/gnrc_sixlowpan_frag_sfr/mockup_netif.c
- tests/gnrc_sock_ip/main.c
- tests/gnrc_sock_udp/main.c
- tests/gnrc_tx_sync/main.c
- tests/ieee802154_hal/main.c
- tests/ieee802154_submac/main.c
- tests/lwip_sock_ip/main.c
- tests/lwip_sock_udp/main.c
- tests/mtd_raw/main.c
This PR fixes compilation problems when `NDEBUG` is defined.
Commit https://github.com/RIOT-OS/RIOT/pull/14364/commits/deb2d466c40422a3942062aafa55cc03a2379f9d is only for defining `NDEBUG` for compilation. It must be dropped before merge.
Compilation in CI has to succeed.
> Fix NDEBUG compilation problems

- .murdock
- dist/tools/ci/can_fast_ci_run.py
This PR integrates can_fast_ci_run.py into the .murdock job collection, filtering jobs if possible.
TODO:
I've hooked in printing of `can_fast_ci_run.py` to the "static-tests" job (which was unused for some time). That can be used to verify it's decisions. I used that because there's special handling, "static-tests" output will be printed at the beginning of the full build log.
I'll try to create test commits and show the resulting build list somehow.
Limited builds:
Fallback to full build:
> murdock: make use of can_fast_ci_run.py

- sys/include/ztimer.h
- sys/ztimer/core.c
This PR makes `ztimer_set` return the `now` value it was set against. This change although an API change should not break anything since the function was returning void, but it should allow estimating the actual value against which the set function was used.
My main motivation for this is that `esp` timer implementation sets a `timer_expire` value that cant be directly translated from `ztimer` to `xtimer`. So I'm open to any other better suggestion on doing such a thing.
everything should still build ok!
> sys/ztimer: ztimer_set() return the now value

- cpu/atmega_common/periph/timer.c
On `cpu/atmega_common` the `periph_timer_periodic` implementation does not keep correct counting mode with `TIM_FLAG_RESET_ON_MATCH`. This PR fixes this issue.
To reproduce:
1. Create a periodic timeout with `TIM_FLAG_RESET_ON_MATCH` set.
2. Stop the timer.
3. Start/Resume the timer.
4. Now the counting mode is restored to its initial value (without CTC mode enabled), resulting in a timeout miss. The implementation falsely waits until the timer overflows instead of the desired periodic counter top value.
The `timer_start()` function sets the counting mode to `ctx[tim].mode`, as initialized in `timer_init()`. To preserve `TIM_FLAG_RESET_ON_MATCH`, `timer_set_periodic()` now also updates `ctx[tim].mode`.
> cpu/atmega_common: Remember CTC mode with timer_periodic

- examples/gnrc_networking/Makefile
- examples/gnrc_networking/main.c
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/net/gnrc/Makefile.dep
- sys/shell/commands/Makefile
- sys/shell/commands/sc_gnrc_udp.c
- sys/shell/commands/shell_commands.c
The `udp` command is a valuable debugging tool that is also useful outside of the gnrc_networking example.
To enable easy sending of udp messages in other applications during development, move the `udp` command to the shell module and introduce the `gnrc_udp_cmd` pseudo-module to enable it.
The `udp` command is still present in the `gnrc_networking` example.
But it's now also possible to add
USEMODULE += gnrc_udp_cmd
to e.g. `examples/gnrc_border_router` and have a simple test for one-way communication available there.
> examples/gnrc_networking: move udp command to shell commands

- drivers/atwinc15x0/Makefile.dep
- drivers/atwinc15x0/atwinc15x0_bsp.c
- drivers/atwinc15x0/atwinc15x0_netdev.c
This PR migrates the `atwinc15x0` driver to ztimer.
```
CFLAGS='-DWIFI_SSID=\"ssid\" -DWIFI_PASS=\"pass\" \
make BOARD=feather-m0-wifi -C examples/gnrc_networking flash term
```
should still work.
> drivers/atwinc15x0: migrate to ztimer

- pkg/ccn-lite/Makefile.dep
- pkg/ccn-lite/patches/0002-src-ccnl-migrate-from-xtimer-to-ztimer64.patch
- pkg/ccn-lite/patches/0003-src-ccnl-riot-move-late-initialization-of-evtimer.patch
- pkg/ndn-riot/Makefile.dep
- pkg/ndn-riot/patches/0005-use-ztimer_msec-instead-of-xtimer.patch
This PR migrate the `ndn-riot` and `ccn-lite` package to RIOT. With migrating `ccn-lite` I also ran into a bug where the `evtimer` was actually initialized later than the event were added to it. I'm not sure why but this issue only triggered when testing on `iotlab-m3` with `evtimer_on_ztimer`.
<details><summary>examples/ccn-lite-relay</summary>
```
2021-12-10 16:57:56,827 # help
2021-12-10 16:57:56,828 # Command              Description
2021-12-10 16:57:56,828 # ---------------------------------------
2021-12-10 16:57:56,829 # reboot               Reboot the node
2021-12-10 16:57:56,830 # version              Prints current RIOT_VERSION
2021-12-10 16:57:56,830 # pm                   interact with layered PM subsystem
2021-12-10 16:57:56,831 # ps                   Prints information about …
```
> pkg/ccn-ndn: migrate to ztimer

- sys/shell/commands/sc_gnrc_udp.c
The static functions in `examples/gnrc_networking/udp.c` were defined somewhat sloppy - back in 2015 our coding conventions and best practices weren't as detailed out as they are today :-)
This properly PR marks the applicable function parameters as `const`. Further while at it, I renamed the static functions by adding underscores in front of the function names as it is done as best practice in large parts of the RIOT codebase.
Build test should do.
None
> examples/gnrc_networking: cleanup and static function declarations in udp.c

- pkg/mynewt-core/patches/0004-kernel-os-silence-Wcast-align.patch
This PR silence an error that shows up when compiling `nimble` with `mynewt-core`
On master:
`USEPKG=mynewt-core make -C examples/nimble_gatt/ -j7`
```
/home/francisco/workspace/RIOT2/examples/nimble_gatt/main.c: In function 'gatt_svr_chr_access_rw_demo':
/home/francisco/workspace/RIOT2/build/pkg/mynewt-core/kernel/os/include/os/os_mbuf.h:136:31: error: cast increases required alignment of target type [-Werror=cast-align]
136 | #define OS_MBUF_PKTHDR(__om) ((struct os_mbuf_pkthdr *)     \
|                               ^
/home/francisco/workspace/RIOT2/build/pkg/mynewt-core/kernel/os/include/os/os_mbuf.h:147:31: note: in expansion of macro 'OS_MBUF_PKTHDR'
147 | #define OS_MBUF_PKTLEN(__om) (OS_MBUF_PKTHDR(__om)->omp_len)
|                               ^~~~~~~~~~~~~~ …
```
> pkg/mynewt-core/patches: silence cast-align

- cpu/esp32/Makefile
- cpu/esp32/Makefile.dep
- cpu/esp32/doc.txt
- cpu/esp32/esp-eth/esp_eth_netdev.c
- cpu/esp32/esp_ztimer.c
- cpu/esp32/periph/Kconfig.i2c
- cpu/esp32/periph/i2c_hw.c
- cpu/esp32/periph/pm.c
- cpu/esp32/periph/timer.c
- cpu/esp32/syscalls.c
- cpu/esp8266/doc.txt
- cpu/esp8266/ld/esp8266.riot-os.ld
- cpu/esp8266/periph/timer.c
- cpu/esp8266/syscalls.c
- cpu/esp_common/Makefile.dep
- cpu/esp_common/esp-now/doc.txt
- cpu/esp_common/esp-now/esp_now_netdev.c
- cpu/esp_common/esp-now/esp_now_params.h
- cpu/esp_common/esp-wifi/esp_wifi_netdev.c
- cpu/esp_common/freertos/portable.c
- cpu/esp_common/freertos/task.c
- cpu/esp_common/freertos/timers.c
- cpu/esp_common/include/freertos/timers.h
`esp` has a couple of uses of `xtimer` that can't be directly translated to `ztimer`, so it seems better to do it in its own PR. I also don't have hardware to tests so would appreciate if maybe @gschorcht could complement murdock's testing.
The most delicate change is https://github.com/fjmolinas/RIOT/blob/6a736e4cdfb57ee446050d8fd0c455f120dd381c/cpu/esp32/esp_ztimer.c#L153-L157 since this is not a direct translation, so depending on how sensitive this value is some adjustment might be needed, thougts @gschorcht?
- All `esp` tests should pass
- Murdock tests should pass
depends on #17385
part of #16903
> cpu/esp: migrate to ztimer

- cpu/kinetis/include/periph_cpu.h
- cpu/kinetis/periph/rtt.c
- tests/periph_rtt_min/Makefile
While testing #17357 I had the test fail on `frdm-kw41z`, while investigating I realized there was a wrong define and that the rtt callback was not cleared.
I also added a fix to the rtt_min_offset test which was not updated since now kinetis runs at 32khz.
`USEMODULE=evtimer_on_ztimer BOARD=frdm-kw41z make -C tests/evtimer_msg/ flash test -j` now passes
```
main(): This is RIOT! (Version: 2022.01-devel-1233-gbf0546-pr_kinetis_fix_rtt)
Testing generic evtimer
This should list 2 items
ev #1 offset=999
ev #2 offset=500
This should list 4 items
ev #1 offset=659
ev #2 offset=341
ev #3 offset=500
ev #4 offset=2454
Are the reception times of all 4 msgs close to the supposed values?
At   3854 ms received msg 0: "#2 supposed to be 3854"
.At   4195 ms received msg 1: "#0 supposed to be 4195"
.At …
```
> cpu/kinetis/include: fix xtimer backend timer selection

- makefiles/docker.inc.mk
This PR passes `TEST_KCONFIG` to docker to allow building with kconfig.
Build with `TEST_KCONFIG` in docker, it now works. For example, this would have wrongly built-in master:
```
TEST_KCONFIG=1 BUILD_IN_DOCKER=1 BOARD=esp8266-esp-12x make -C examples/gnrc_networking clean all -j
```
> makefiles/docker.inc.mk: pass TEST_KCONFIG

- drivers/mhz19/Kconfig
- drivers/mhz19/Makefile.dep
- drivers/mhz19/mhz19_pwm.c
- drivers/mhz19/mhz19_uart.c
- tests/driver_mhz19/Makefile
- tests/driver_mhz19/app.config.test
- tests/driver_mhz19/main.c
Changes should be straight forward but care should be taken with the ppm computation which depends on ztimer_now results (expressed in ticks).
- Green CI
- `tests/driver_mhz19` is still working (but I don't have the hardware to test)
> drivers/mhz19: migrate to ztimer

- boards/common/nrf52xxxdk/Kconfig
- boards/common/nrf52xxxdk/Makefile.dep
- boards/common/nrf52xxxdk/include/gpio_params.h
- boards/common/nrf52xxxdk/include/periph_conf_common.h
- boards/common/nrf52xxxdk/include/pwm_params.h
As the title says. This allows dimming the LEDs instead of only turning them on and off.
```
make BOARD=nrf52840dk PROGRAMMER=openocd -C examples/saul
[...]
help
2021-12-14 20:34:02,723 # help
2021-12-14 20:34:02,725 # Command              Description
2021-12-14 20:34:02,728 # ---------------------------------------
2021-12-14 20:34:02,732 # reboot               Reboot the node
2021-12-14 20:34:02,736 # version              Prints current RIOT_VERSION
2021-12-14 20:34:02,741 # pm                   interact with layered PM subsystem
2021-12-14 20:34:02,747 # ps                   Prints information about running threads.
2021-12-14 20:34:02,753 # saul                 interact with sensors and actuators using SAUL
> saul
2021-12-14 20:34:03,742 # saul
2021-12-14 20:34:03,743 # ID	Class		Name …
```
> boards/common/nrf52xxxdk: Expose LEDs via saul_pwm

- sys/evtimer/evtimer.c
With #17385 a call to `ztimer_now` can be saved.
`USEMODULE=evtimer_on_ztimer  BOARD=<some board> make -C tests/evtimer_msg/ flash test` still passes
Found on #17357.
> sys/evtimer: use now returned by set

- tests/periph_timer_periodic/main.c
- tests/periph_timer_periodic/tests/01-run.py
The test should detect some bugs regarding incorrect behavior regarding `timer_start()` not resuming periodic timers as expected.
The test should still pass (hopefully) for all non-AVR boards, but fail on AVR due to the bug fixed in https://github.com/RIOT-OS/RIOT/pull/17387
Used to test https://github.com/RIOT-OS/RIOT/pull/17387
> tests/periph_timer_periodic: spice up test

- examples/nanocoap_server/Makefile
- examples/suit_update/main.c
- pkg/tinydtls/Makefile.dep
- pkg/tinydtls/contrib/sock_dtls.c
- sys/Makefile.dep
- sys/include/evtimer.h
- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/sock/gnrc_sock.c
- sys/test_utils/Makefile.dep
- sys/ztimer/Makefile.dep
- tests/driver_encx24j600/Makefile.ci
- tests/evtimer_underflow/Makefile
- tests/evtimer_underflow/main.c
- tests/gnrc_dhcpv6_relay/Makefile.ci
- tests/gnrc_sock_ip/Makefile
- tests/gnrc_sock_neterr/Makefile.ci
- tests/gnrc_sock_udp/Makefile
- tests/pkg_microcoap/Makefile
- tests/riotboot_flashwrite/Makefile.ci
evtimer uses 32 bits of msec -> there is no reason to pull ztimer_now64 
run evtimer tests `evtimer_mbox, evtimer_msg, evtimer_underflow` with `USEMODULE=evtimer_on_ztimer`
> sys/evtimer,ztimer: do not depend on ztimer_now64

- boards/qn9080dk/include/board.h
- boards/qn9080dk/include/periph_conf.h
- cpu/esp32/include/periph_cpu.h
- cpu/esp8266/include/periph_cpu.h
- cpu/fe310/clock.c
- cpu/fe310/cpu.c
- cpu/fe310/include/clk_conf.h
- cpu/fe310/include/periph_cpu.h
- cpu/fe310/periph/i2c.c
- cpu/fe310/periph/spi.c
- cpu/fe310/periph/uart.c
- cpu/native/include/periph_conf.h
- drivers/ws281x/atmega.c
- examples/blinky/Makefile
- examples/blinky/main.c
- pkg/openwsn/contrib/leds.c
- sys/include/clk.h
- tests/bench_msg_pingpong/main.c
- tests/bench_mutex_pingpong/main.c
- tests/bench_sched_nop/main.c
- tests/bench_thread_flags_pingpong/main.c
- tests/bench_thread_yield_pingpong/main.c
- tests/leds/main.c
- tests/periph_timer/Makefile
- tests/periph_timer/main.c
- tests/periph_uart_mode/main.c
This PR introduces the `sysclk()` to get the value of the system core clock frequency. In most situation, this frequency corresponds to the `CLOCK_CORECLOCK` constant. But in some cases, this constant is wrong or not defined:
- with native it's not defined at all so when using CLOCK_CORECLOCK some preprocessor checks are needed
- on fe310, when using the internal oscillator clocks, the constant is not defined but the system clock is computed at runtime. This behavior could be extend to other families: on STM32, one could imagine fine tuning at runtime the trimming value of internal oscillator to get an approximate of a desired clock value (HSI16 or HSI48 - without autotrim - for example).
As an example, doing the following doesn't build on hifive1b:
```
$ …
```
> sys: introduce sysclk function to retrieve core clock frequency

- sys/include/ztimer.h
Add another warning to not compare `ztimer_now()` values from different clocks.
> sys/ztimer: ztimer_now() add warning regarding comparing now() values

- .murdock
Introduce the TEST_KCONFIG_TEST_ALLOWLIST and TEST_KCONFIG_BOARD_BLOCKLIST
This will test kconfig modeling on a small subset of apps
for all boards that are not on the blocklist.
This should automatically test new boards, preventing merging
of non-kconfig complete boards.
CI green and verify that boards are being tested by murdock for the specified apps.
Part of #16875
> .murdock: Kconfig test apps for all boards

- drivers/Makefile.dep
- drivers/ethos/Makefile
- drivers/ethos/Makefile.dep
- drivers/ethos/ethos.c
- drivers/ethos/stdio.c
- drivers/include/ethos.h
- makefiles/pseudomodules.inc.mk
- makefiles/stdio.inc.mk
- sys/stdio_uart/stdio_uart.c
This tries to fix https://github.com/RIOT-OS/RIOT/issues/17254 by eliminating the condition that causes the race altogether. It moves the following parts of ethos' state machine out of ISR context, inspired by the way it is done in `slipdev`:
- Sending and replying to HELLO messages
- Byte-unstuffing
Some escape handling is still needed in the ISR handler, due to ethos' protocol design, to determine if a received byte must go into the netdev queue (tsrb) or the STDIO queue (isrpipe), but the actual unstuffing is now done in the STDIO and netdev handler threads, respectively.
This causes a slight increase of ROM, as byte unstuffing needs to be now handled in both stdio and the netdev context, but we also gain some RAM, as the `ethos_t` members `framesize`, `last_framesize`, and …
> ethos: move bulk of state machine out of ISR context

- sys/ztimer64/Makefile.dep
Cherry-picked from #17367, currently, ztimer64_init is not selected. This fixes it while still allowing to disable it.
- in master
```
USEMODULE=ztimer64_usec make -C examples/hello-world/ info-modules | grep ztimer64_init
#empty
```
- this pr
```
USEMODULE=ztimer64_usec make -C examples/hello-world/ info-modules | grep ztimer64_init
ztimer64_init
```
> sys/ztimer64: default select ztimer64_init

- sys/include/ztimer.h
- sys/ztimer/core.c
An application that set a timer and removes it could previously not reliably tell whether the timer fired without keeping track in an atomic (or otherwise synchronized) variable. This introduces a return value to ztimer_remove that allows building applications that do something precisely once (that is, to do whatever cleanup the timeout's callback would do if it had been called.
This is particularly pressing for Rust code, as the language is very picky about closures declared to run exactly once really being called only once. (And while leaking something is generally considered OK there language-wise, on an embedded system the leakage typically means that some mutex is forever locked).
The alternative for the user is to disable interrupts, query ztimer_is_set, and then to remove the …
> sys/ztimer: ztimer_remove report success

- cpu/esp32/doc.txt
- cpu/esp8266/doc.txt
- cpu/esp_common/esp-wifi/esp_wifi_netdev.c
- cpu/esp_common/esp-wifi/esp_wifi_params.h
This PR simplifies the definition of the option to use dynamic SSIDs for the SoftAP, especially with regard to the migration to `Kconfig`.
The semantics of defining a separate SSID prefix string that overrides the already defined SSID and enables the dynamic SSID generation with that prefix exactly when and only when it is set, made the handling of the parameter definition unnecessarily difficult and hard to understand.
Defining a boolean option that just enables the dynamic SSID generation, which then simply reuses the defined SSID as a prefix, makes it much more understandable and easier to handle, especially with respect to Kconfig.
This PR removes the configuration parameter `ESP_WIFI_PREFIX` and introduces the boolean configuration parameter `ESP_WIFI_SSID_DYNAMIC` which is defined …
> cpu/esp: change dynamic SSID option handling

- sys/ztimer/core.c
There is a possible race between triggering and removing a timer, which might lead to reading uninitialized memory.
I triggered the case on native with this patch: https://gist.github.com/18ba849370a64b3562d06776b894caed
It doesn't show on nrf52840dk. I guess this depends on whether an rtt cancel properly clears a possibly pending interrupt.
> sys/ztimer: don't access non-existant timer

- cpu/esp32/doc.txt
- cpu/esp32/periph/i2c_hw.c
- cpu/esp_common/periph/i2c_sw.c
- cpu/esp_common/periph/spi.c
This PR provides some small changes for SPI and I2C (software and hardware implementation) to support CPU clock frequencies of 2 MHz and 40 MHz. The advantage of using a CPU clock frequency of 40 MHz or 2 MHz is that the power consumption is reduced to the half or even one third of the power consumption with a CPU clock frequency of 80 MHz.
So far the ESP32 port supports the CPU clock frequencies 80 MHz, 160 MHz and 240 MHz. The CPU clock of 80 MHz is the default setting. With all these CPU clock frequencies, an APB clock of 80 MHz is used for peripherals. However, for CPU clock frequencies of 40 MHz and 2 MHz, an APB frequency of 40 MHz and 2 MHz, respectively, is used. To support these CPU clock frequencies some changes were necessary for the peripherals that use APB clocks. 
With a CPU …
> cpu/esp32: support CPU clocks 2 MHz and 40 MHz

- cpu/stm32/Kconfig
This PR is a simple cleanup of stm32 Kconfig where some invalid family symbols are used: `CPU_FAM_F5` and `CPU_FAM_F6`. Obviously F5 and F6 families don't exist.
A green Murdock should be enough
Noticed that while trying to understand why there's a difference between Kconfig/no kconfig builds on stm32u5 in #17410
> cpu/stm32: remove invalid family symbols used in Kconfig

- doc/doxygen/riot.doxyfile
- doc/doxygen/src/using-rust.md
- makefiles/info.inc.mk
This adds overview documentation to using Rust on RIOT, similar to the one existing for C++; much of it is adapted from the riot-examples docs at https://gitlab.com/etonomy/riot-examples (which can then be trimmed down, referring to upstream support).
As a singular non-doc change this contains the addition of RUST_TARGET to `make info-build`, which paves a path (taken in the new documentation) toward proactively installing the right tools, rather than running `make` and waiting for the error message to tell one what is missing.
* View the docs
* Run `make info-build` on an arbitrary example, with BOARD set to microbit-v2 (has a RUST_TARGET) and 6lowpan-clicker (has no RUST_TARGET, shows empty)
Follow-up for: #16274 (where this should have been done already)
> doc: Rust overview

- boards/b-l072z-lrwan1/include/board.h
- boards/b-l072z-lrwan1/include/gpio_params.h
- boards/b-l475e-iot01a/include/board.h
- boards/b-l475e-iot01a/include/gpio_params.h
- boards/pyboard/include/board.h
- boards/pyboard/include/gpio_params.h
- boards/ublox-c030-u201/include/board.h
- boards/ublox-c030-u201/include/gpio_params.h
There are a few boards that define there user button as `BTN_B1_PIN` without defining the GPIO mode. This is not compatible with the `tests/buttons` application which expects the defines to be called `BTNx_PIN` and `BTNx_MODE`.
This PR renamed these defines to make them compatible and testable with `tests/buttons`.
`tests/buttons` now works with `b-l072z-rwan1`, `b-l475e-iot01a`, `pyboard` and `ublox-c030-u201`.
Noticed that when working on #17410
> boards: unify user button defines

- cpu/stm32/Makefile.dep
This PR fixes a typo in a comment in `cpu/stm32/Makefile.dep`.
I think we can skip the CI here.
Noticed that while trying to understand why there's a difference between Kconfig/no kconfig builds on stm32u5 in #17410
> cpu/stm32/Makefile.dep: fix typo

- cpu/esp_common/esp-wifi/esp_wifi_params.h
This PR reverts a change made as part of PR #17415.
Previously, the default value for `ESP_WIFI_PASS` was intentionally defined only when `DOXYGEN` is also defined to allow `ESP_WIFI_PASS` to be left undefined for using APs without authentication. As part of PR #17415 the definition was changed to always define a default value for `EPS_WIFI_PASS`.  This made it impossible to use APs without authentication. This PR reverts this change.
The change in PR #17415 that is undone by this PR was supposedly a correction and  was made in preparation for the migration to `Kconfig`. There are no other changes in PR #17415 affected by this change. 
It is a very small fix back to the former definition (comment https://github.com/RIOT-OS/RIOT/pull/17415/files#r771905996). There are no functional or …
> cpu/esp: revert the change for default definition of ESP_WIFI_PASS

- doc.txt
- doc/doxygen/src/using-cpp.md
- sys/cpp11-compat/doc.txt
- sys/cxx_ctor_guards/doc.txt
- sys/include/c11_atomics_compat.hpp
This should make it easier for C++ developers to find C++ related modules in RIOT-OS.
#17066 and other C++ related additions can then be better placed in the documentation.
> doc: Improve C++ documentation

- core/include/irq.h
- drivers/motor_driver/motor_driver.c
Setting the system in a state with more interrupts enabled than expected by the caller is generally unexpected -- if this were allowed unchecked, many components would need to revisit and tighten their synchronization efforts making them less efficient. (I didn't do a precise check, but I expect that ztimer might *not* tolerate interrupts to be enabled by the callback, especially as that means that unrelated interrupts might manipulate ztimer again).
One offending user was found in the implementations (motor_driver) and changed to use irq_restore. All others have some justification for using enable (eg. it's done in an ISR).
* Look at whether you agree with the doc change.
* Test the motor example. (I didn't, and don't have the hardware -- but what could go wrong?).
This came up looking …
> core: Warn about using irq_enable

- boards/feather-m0/Kconfig
- boards/feather-m0/Makefile.features
- boards/feather-m0/include/arduino_board.h
- boards/feather-m0/include/arduino_pinmap.h
Adds the **arduino** feature to the **feather-m0** board.
This is a follow up of PR #17335 ; it contains the first 3 commits from that PR rebased and merged.
Use `tests/periph_gpio_arduino` and `tests/sys_arduino_lib`.
`examples/arduino_hello-world` and `tests/sys_arduino` don't work, as discussed in PR #17335 this is to be fixed in a different PR.
This is a follow up of PR #17335
> boards/feather-m0: add arduino feature

- boards/feather-m0-lora/Kconfig
- boards/feather-m0-wifi/Kconfig
This PR solves the problem with the `arduino` feature introduced with PR #17401 for the `feather-m0` base board, in the `Kconfig` for derived `feather-m0-*` boards.
With PR #17401 the `arduino` feature for the `feather-m0` baseboard was introduced. Since all derived `feather-m0-*` boards with additional hardware modules have all features of the `feather-m0` base board, just `Makefile.features` of the `feather-m0` base board is included by `Makefile.features` of all derived `feather-m0 boards-*`. Thus all derived boards also have this feature.
However, the `Kconfig` file is defined separately for derived `feather-m0-*` boards. In PR #17401, it was forgotten to include the `arduino` feature in the `Kconfig` file for the derived boards. This wasn't realized before merging because the CI …
> boards/feather-m0-*: fix Arduino feature in Kconfig

- boards/feather-m0-lora/Kconfig
- boards/feather-m0-wifi/Kconfig
- boards/feather-m0/Kconfig
- boards/feather-m0/Kconfig.feather-m0-base
This PR introduces a base board definition in Kconfig for all `feather-m0*` boards.
Derived `feather-m0-*` boards have all features of the `feather-m0` base board and `Makefile.features` of derived `feather-m0-*` boards just include `Makefile.features` of the `feather-m0` base board. Therefore a base board definition is introduced in Kconfig for all `feather-m0*` boards.
Such a base board definition in Kconfig helps to avoid problems as introduced with PR #17401 and fixed with PR #17444.
Green CI.
> boards/feather-m0*: base board definition in Kconfig

- boards/common/microbit/include/microbit.h
Otherwise the "Common microbit LED handling" group appears at the top-level modules group:
Just check the generated documentation, the microbit common group has moved under the common boards doxygen group.
None
> boards/common/microbit: fix doxygen grouping

- sys/arduino/base.cpp
This PR add assertion to GPIO handling to the Arduino module to avoid system lock if an Arduino pin is used that is defined as `GPIO_UNDEF`
Not all boards that provide a Arduino pin layout break out all GPIOs. A good example are the Adafruit `feather-m0` boards. For such boards, GPIO pins that are not broken out have to be defined as `GPIO_UNDEF` to preserve the Arduino pin layout. However, GPIO functions lead to a complete system lock on `feather-m0` boards if a pin is used that is defined as `GPIO_UNDEF`. Therefore, at least an assert should blow up in that case.
Compile and flash
```
make BOARD=feather-m0 -C tests/periph_gpio_arduino flash term
```
Execute
```
toggle 13
toggle 3
```
After the second command, the system hangs without this PR. With this PR, the second command should lead …
> sys/arduino: add assertion to gpio handling

- cpu/esp32/doc.txt
- cpu/esp8266/doc.txt
This PR contains a number of formatting fixes but no content changes:
- `<b> ... </b>` tags replaced by `**`
- `...` doesn't work in headings anymore
- `doxygen` doesn't work if `**` at the beginning of a line
- Identifier are formatted consistently with `fixed font`
- some line breaks
Green CI.
> cpu/esp*: small documentation fixes

- boards/rpi-pico/doc.txt
This PR adds to Raspberry Pi Pico board documentation section concerning accessing RIOT shell.
Information in description accordingly to the Issue [17453](https://github.com/RIOT-OS/RIOT/issues/17453).
```
make doc
xdg-open doc/doxygen/html/group__boards__rpi__pico.html
```
See Issue  [#17453](https://github.com/RIOT-OS/RIOT/issues/17453).
> doc/boards/rpi-pico: Addition of section concerning shell access

- sys/net/application_layer/dhcpv6/client.c
This PR adds a small check to the DHCPv6 client that prevents the `_restart` function from being called multiple times during setup. The check uses a new  `client_initialized` variable that has to be `true` for a restart to happen. Otherwise the `_restart` function simply returns.
All DHCPv6 tests should still pass. However, the `_restart` function should only be called once during these tests.
The issue was raised in https://github.com/RIOT-OS/RIOT/issues/16971#issuecomment-944317134.
> sys/net/dhcpv6: fix variable shadowing issue

- sys/include/usb/usbus/hid.h
This PR removes the declaration for the unimplemented function `usbus_hid_flush`. This function used to be a wrapper for `usbdev_ep_xmit` which I didn't need anymore after chaning parts of the initial USB HID implementation. I forgot to remove this declaration.
> usbus/hid: Remove unimplemented function declaration

- drivers/include/can/candev.h
- drivers/include/net/netdev.h
- sys/include/crypto/ciphers.h
- sys/include/net/cord/ep_standalone.h
- sys/include/net/sock/async/types.h
This PR provides minor Doxygen documentation fixes that are reported locally when running `make static-test`
- Green CI
- Check the generated documentation on Circle CI
- Issues are not reported anymore when running Doxygen (1.9.1 locally):
```
$ make static-test 
./dist/tools/ci/static_tests.sh
Running "./dist/tools/whitespacecheck/check.sh master" ✓
Running "./dist/tools/licenses/check.sh" ✓
Running "./dist/tools/licenses/check.sh" ✓
Running "./dist/tools/doccheck/check.sh" ✓
Running "./dist/tools/externc/check.sh" ✓
Required command 'vera++' for './dist/tools/vera++/check.sh' not found in PATH •
Running "./dist/tools/coccinelle/check.sh" ✓
Running "./dist/tools/flake8/check.sh" ✓
Running "./dist/tools/headerguards/check.sh" ✓
Running …
```
> doc: fix missing or non matching arguments in Doxygen documentation

- boards/stm32f723e-disco/Makefile.include
This PR enables the `connect_assert_srst` of OpenOCD `reset_config` command with the `stm32f723e-disco` board. After being plugged the first time, the first flash attempt always fails on master. With this PR it works.
- Green CI
- Flashing works reliably:
<details><summary>this PR (just after the board is plugged)</summary>
```
$ make BOARD=stm32f723e-disco -C examples/hello-world/ flash-only --no-print-directory 
/work/riot/RIOT/dist/tools/openocd/openocd.sh flash /work/riot/RIOT/examples/hello-world/bin/stm32f723e-disco/hello-world.elf
Open On-Chip Debugger 0.11.0+dev-00546-g5795f4d3e (2021-12-23-10:48)
hla_swd
Info : The selected transport took over low-level target control. The results might …
```
> boards/stm32f723e-disco: use connect_assert_srst with openocd

- boards/stm32f746g-disco/Makefile.include
This PR enables `connect_assert_srst` in the `reset_config` option of OpenOCD for the stm32f746g-disco board. Without this option, the board is sometimes unflashable automatically (especially just after it's plugged to the computer).
- on master I sometimes get the following openocd output:
<details>
```
$ BOARD=stm32f746g-disco make -C examples/hello-world flash-only --no-print-directory 
/work/riot/RIOT/dist/tools/openocd/openocd.sh flash /work/riot/RIOT/examples/hello-world/bin/stm32f746g-disco/hello-world.elf
Open On-Chip Debugger 0.11.0+dev-00546-g5795f4d3e (2021-12-23-10:48)
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain …
```
> boards/stm32f746g-disco: use connect_assert_srst with openocd

- sys/include/time_units.h
- sys/include/timex.h
It itched for a long time that "timex" needs to be included everywhere just to get its convenience defines.
This PR moves those out into "time_units.h". That is included in "timex.h" for backwards compat.
CI should be enough due to timex.h including time_units.h.
> sys: factor out US_PER_SEC etc from timex.h into time_units.h

- boards/p-l496g-cell02/Kconfig
- boards/p-l496g-cell02/Makefile.features
- Green CI
- `tests/riotboot` works on p-l496g-cell02:
<details>
```
$ make BOARD=p-l496g-cell02 -C tests/riotboot flash test
make: Entering directory '/work/riot/RIOT/tests/riotboot'
Building application "tests_riotboot" for "p-l496g-cell02" with MCU "stm32".
"make" -C /work/riot/RIOT/boards/p-l496g-cell02
"make" -C /work/riot/RIOT/cpu/stm32
"make" -C /work/riot/RIOT/cpu/cortexm_common
"make" -C /work/riot/RIOT/cpu/cortexm_common/periph
"make" -C /work/riot/RIOT/cpu/stm32/periph
"make" -C /work/riot/RIOT/cpu/stm32/stmclk
"make" -C /work/riot/RIOT/cpu/stm32/vectors
"make" -C /work/riot/RIOT/drivers
"make" -C /work/riot/RIOT/drivers/periph_common
"make" -C /work/riot/RIOT/sys
"make" -C /work/riot/RIOT/sys/auto_init
"make" -C …
```
> boards/p-l496g-cell02: add riotboot feature

- makefiles/pseudomodules.inc.mk
- makefiles/stdio.inc.mk
- sys/Kconfig.stdio
- sys/include/stdio_base.h
- sys/stdio_uart/stdio_uart.c
- sys/usb/usbus/cdc/acm/Kconfig
- sys/usb/usbus/cdc/acm/cdc_acm_stdio.c
This PR provides the definition of an additional `stdio` function to check how many bytes are available for reading.
A number of `stdio` backend implementations allow to check the number of bytes available for reading before calling the blocking `stdio_read`. This helps to implement non-blocking functionalities while waiting for `stdin`.
This PR provides the implementation for
```
stdio_uart
stdio_cdc_acm
```
Green CI.
Follow-up of PR #17335
Required for PR #17447
> sys/stdio: add optional function stdio_available

- pkg/fatfs/Makefile
- pkg/fatfs/patches/0001-remove-ffconf.h.patch
- pkg/fatfs/patches/0002-remove-diskio.c.patch
- pkg/fatfs/vendor/include/ffconf.h
R0.14b (April 17, 2021)
- Made FatFs uses standard library <string.h> for copy, compare and search instead of built-in string functions.
- Added support for long long integer and floating point to f_printf(). (FF_STRF_LLI and FF_STRF_FP)
- Made path name parser ignores the terminating separator to allow "dir/".
- Improved the compatibility in Unix style path name feature.
- Fixed the file gets dead-locked when f_open() failed with some conditions. (appeared at R0.12a)
- Fixed f_mkfs() can create wrong exFAT volume due to a timing dependent error. (appeared at R0.12)
- Fixed code page 855 cannot be set by f_setcp(). (appeared at R0.13)
- Fixed some compiler warnings.
-- http://elm-chan.org/fsw/ff/updates.txt
> pkg/fatfs: bump version to r0.14b

- cpu/esp32/Kconfig
- cpu/esp32/include/sdk_conf.h
- cpu/esp8266/Kconfig
- cpu/esp8266/include/cpu_conf.h
As the title says, this PR integrates CPU clock frequency selection in `Kconfig`.
Futhermore, it contains a small fix which removes the duplicate of `HAS_ESP_SPI_RAM` feature definition (https://github.com/RIOT-OS/RIOT/commit/f01e0804ffefb72a4e56e44ddb10e1e5f19c1799)
1. Compilation has to succeed.
2. Use commands:
```
TEST_KCONFIG=1 make BOARD=esp32-wroom-32 -C tests/shell menuconfig
TEST_KCONFIG=1 make BOARD=esp8266-esp-12x -C tests/shell menuconfig
```
The CPU clock frequency should be selectable in ESP32 and ESP8266 specific configurations.
> cpu/esp: integrate CPU clock frequency selection in Kconfig

- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/application_layer/dhcpv6/client.c
- sys/net/gnrc/application_layer/dhcpv6/client_simple_pd.c
- sys/net/gnrc/application_layer/uhcpc/gnrc_uhcpc.c
The border router does not send out router solicitations as it sends out router advertisements instead.
This delays the reception of router advertisements from upstream routers.
Instead, start with router advertisements disabled and only enable them when we received a global prefix via DHCPv6 or UHCP.
Run `examples/gnrc_border_router` both with `USE_DHCPV6=1` and without.
You should notice that now a configuration on the upstream interface is obtained much faster.
alternative to #16590
> gnrc_dhcpv6_client / uhcp: delay router advertisements until prefix was received

- drivers/sdcard_spi/sdcard_spi.c
This is a partial takeover of #6486: it addresses the `sdcard_spi` driver related changes.
A green Murdock is enough.
Partial takeover of #6486
> drivers/sdcard_spi: replace GPIO_UNDEF by SPI_CS_UNDEF

- core/include/kernel_defines.h
- core/thread.c
Since we moved to C11 now for all platforms, using `alignof()` provided by `<stdalign.h>` has become the better option.
I personally consider `kernel_defines.h` as a RIOT internal, so that we can drop this without the usual deprecation procedure. Also note that a simple `sed -e 's/ALIGN_OF/alignof/g' -i <FILE_TO_MIGRATE>` would be sufficient to migrate to the C11 macro.
The generated binaries must not differ, as `alignof()` and `ALIGN_OF()` must yield the exact same compile time constant number.
None
> core/kernel_defines.h: drop ALIGN_OF()

- core/include/msg.h
- core/msg.c
- tests/msg_avail/main.c
- tests/msg_queue_print/tests/01-run.py
For the caller there should be no difference if there is no message in the queue and if there can't be a message in the queue.
The current API works as one would expect if there is a message queue, but once called from a thread that does not have a message queue configured, code that does
while (msg_avail())
will end up in an infinite loop.
Remove this foot-gun from the API by making the return value of `msg_avail()` independent of the availability of a message queue.
prevents issues like  #17261
> core/msg: make msg_avail() return 0 on no queue

- sys/posix/sockets/posix_sockets.c
Implicit bind leads to StoreProhibitedCause on esp32 and an implicit bind at this point does not really makes sense to me either. Can someone explain why it was an implicit bind?
You can test this PR e.g. in conjunction with everything else in #15969.
This PR is split out from the chunky #15969.
> sys/posix/socket: use explicit bind

- core/include/kernel_defines.h
- drivers/sps30/sps30.c
- pkg/fatfs/fatfs_vfs/fatfs_vfs.c
- pkg/littlefs/fs/littlefs_fs.c
- pkg/littlefs2/fs/littlefs2_fs.c
- sys/arduino/SPI.cpp
This PR replaces all uses of `BUILD_BUG_ON()` with `static_assert()`. Since C11 `static_assert()` is now a first class feature that provides the exact same functionality. For this reason, this PR also drops `BUILD_BUG_ON()`.
I consider `kernel_defines.h` a RIOT internal, so IMO we can skip the usual deprecation routine. The migration path is relatively easy, just replace `BUG_BUG_ON(<BOOLEAN_EXPRESSION>)` by `static_assert(!<BOOLEAN_EXPRESSION>, "<SOME DEBUG MESSAGE>")`.
Since this is a built time feature, Murdock will test that it still works for the case when all requirements are met. Once could test that compilation does fail when requirements are not met e.g. by changing the size of the buffers. But honestly, `static_assert()` is a compiler feature that is well known and well tested - …
> core/kernel_defines: drop BUILD_BUG_ON()

- sys/Makefile.dep
- sys/cpp11-compat/cppsupport.cpp
- sys/cpp_new_delete/cppsupport.cpp
This PR provides code deduplication as well as the ability for an application to use (re)defined `new`/`delete` operators without requiring `libstdc++`.
1. The `sys/cpp11-compat` module (re)defines the `new`/`delete` operators but depends on `libstdc++` even for `new`/`delete` operators that don't need `libtsdc++`. Module `sys/cpp_new_delete` provides these operators for platforms that don't have the `libstdc++`. Since these operators in `sys/cpp11-compat` are just wrappers for standard `malloc`/`free` functions like in `sys/cpp_new_delete`, the `new`/`delete` operators that don't need `libstdc++` are used from `sys/cpp_new_delete`. Only the `new`/`delete` operators that require the `libstd++` are left in `sys/cpp11-compat`.
So it is sufficient for the use of the (re)defined …
> sys/cpp11-compat: use new/delete operators from sys/cpp_new_delete

- examples/gcoap/client.c
- examples/gcoap/gcoap_example.h
- examples/gcoap/main.c
- examples/gcoap/server.c
- examples/gcoap_dtls/client.c
- examples/gcoap_dtls/gcoap_cli.c
- examples/gcoap_dtls/gcoap_example.h
- examples/gcoap_dtls/server.c
Move client and server side implementations into separate files to
increase readability. Also get rid of a goto.
The example should still work as before. Some changes in `.text` are expected, but RAM consumption should stay identical. (For my `.bss` and `.data` remain identical and `.text` grows by 20 bytes for `samr21-xpro`.)
None
> examples/gcoap: split client and server implementation

- dist/testbed-support/makefile.iotlab.single.inc.mk
`auto-ssh` was deprecated since 2021.04 and marked for removal after 2021.07. It's time to remove it.
- Green CI
- deprecation warning is now removed
None
> dist/iotlab: remove deprecated auto-ssh backward compatibility

- examples/rust-gcoap/Cargo.lock
- examples/rust-gcoap/Makefile
- examples/rust-hello-world/Cargo.lock
- examples/rust-hello-world/Makefile
- tests/rust_minimal/Cargo.lock
- tests/rust_minimal/Makefile
This pulls in adjustments to the C-nonbreaking but Rust-breaking API
change in https://github.com/RIOT-OS/RIOT/pull/17359
* Green CI
> {examples,tests}/rust*: Update Cargo.toml

- boards/common/arduino-mkr/include/arduino_board.h
- boards/feather-m0/include/arduino_board.h
- boards/sodaq-autonomo/include/arduino_board.h
- boards/sodaq-explorer/include/arduino_board.h
- boards/sodaq-one/include/arduino_board.h
- boards/sodaq-sara-aff/include/arduino_board.h
- boards/sodaq-sara-sff/include/arduino_board.h
- sys/Makefile.dep
- sys/arduino/Kconfig
- sys/arduino/Makefile.include
- sys/arduino/serialport.cpp
- tests/sys_arduino/app.config.test
This PR provides the support for using the `Serial` over `stdio_*`
On Arduino boards, the `Serial` object uses
- either an UART interface connected to an USB interface via an additional ATmega chip (class `HardwareSerial`)
- or directly the USB CDC interface (class `_Serial`).
However, the `Serial` object in RIOT always uses the UART interface defined by `ARDUINO_UART_DEV`, usually `UART_DEV(0)`. Therefore `Serial` does not work for boards like `feather-m0` and `arduino-mkr` which use the USB CDC interface directly. Since the STDIO already uses the USB CDC interface for such boards with the help of the module `stdio_cdc_acm`, it is possible to realize the `Serial` object for such boards on top of the STDIO.
For this purpose the module `arduino_serial_stdio` is introduced. If this module …
> sys/arduino: add Serial over stdio support

- sys/include/shell.h
They were advertised for complete removal after 2021.07.
Green CI
None
> sys/shell: remove deprecated SHELL_NO_{ECHO,PROMPT} defines

- cpu/sam0_common/include/periph_cpu_common.h
This adds the missing PINMUX modes to the enum.
> cpu/sam0_common: add missing MUX definitions

- core/include/kernel_defines.h
- tests/unittests/tests-kernel_defines/tests-kernel_defines.c
This adds a simple macro to check (at C level) whether a given expression is proven to be compile time constant and suitable for constant folding. This allows writing code like this:
```C
int gpio_read(gpio_t pin) {
if (IS_CT_CONSTANT(pin)) {
/* this implementation should even be able to use the port and
* pin number as immediate in inline assembly */
}
else {
/* less efficient implementation that cannot use port and pin
* number as immediate in inline assembly */
}
}
```
A unit test was provided that should do the trick.
None
> core: Add IS_CT_CONSTANT()

- pkg/ndn-riot/patches/0006-replace-deprecated-CIPHER_AES_128-by-CIPHER_AES.patch
- sys/crypto/aes.c
- sys/fido2/ctap/ctap_crypto.c
- sys/include/crypto/ciphers.h
- tests/sys_crypto_aes_ccm/tests-crypto-modes-ccm-128.c
This PR removes the definition and use of CIPHER_AES_128 which is deprecated and marked for removal after 2021.07.
Green CI
None
> sys/crypto: remove deprecated CIPHER_AES_128

- drivers/stmpe811/stmpe811.c
- drivers/stmpe811/stmpe811_touch_dev.c
Inspired by https://github.com/RIOT-OS/RIOT/pull/17448#discussion_r779749191
- Green CI
- `tests/driver_stmpe811` and ` tests/touch_dev` should still work (I'll be able to test later)
Inspired by @benpicco's review in #17448
> drivers/stmpe811: improve interrupt callback management

- sys/include/net/asymcute.h
This PR remove the deprecated (and unused) `CONFIG_ASYMCUTE_BUFSIZE_EXP` define which was marked for removal after 2021.04 release.
- Green CI
None
> sys/asymcute: remove deprecated CONFIG_ASYMCUTE_BUFSIZE_EXP

- sys/include/saul_reg.h
- sys/saul_reg/saul_reg.c
- tests/unittests/tests-saul_reg/tests-saul_reg.c
This function was deprecated in #10605 without a clear removal date. The PR was merged end of May 2020 so I think the grace period is enough.
- Green CI
Remove a function marked as deprecated in #10605
> sys/saul_reg: remove deprecated saul_reg_rm function

- sys/include/usb.h
- sys/usb/usbus/usbus_fmt.c
While working on a potential qmk_firmware integration, a few inconsistencies were noticed in the resulting USB descriptors.
* Added remote wakeup capability
* Set configured device version
TODO: Right now its been tested via wireshark and a heavily modified qmk_firmware branch.
Please do let me know if theres existing test cases to update.
None.
> usbus: Bind extra USB config

- sys/fido2/ctap/transport/hid/ctap_hid.c
- sys/include/usb/hid.h
- sys/include/usb/hid/hid_usage.h
- tests/usbus_hid/main.c
This PR adds a bunch of defines to help create USB HID report descriptors.
- Check the doxygen
- Binaries of:
- tests/sys_fido2_ctap
- tests/usbus_hid
Should be unchanged
None
>  usb/hid: Add HID report descriptor defines 

- cpu/cc2538/radio/cc2538_rf_radio_ops.c
- cpu/native/include/socket_zep.h
- cpu/native/socket_zep/socket_zep.c
- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
- pkg/openwsn/contrib/radio_hal.c
- sys/include/net/ieee802154/radio.h
- sys/net/link_layer/ieee802154/submac.c
- tests/ieee802154_hal/main.c
This PR implements the latest proposals of the Radio HAL described in https://github.com/RIOT-OS/RIOT/pull/13943#issuecomment-927798070.
- A `request_op` and `confirm_op` mechanism in order to simplify the TX logic
- `xxx_transmit` are not needed anymore
- CCA and set_trx_state functions were merged into these functions
- TX_ON state was removed and TRX_OFF was renamed to IDLE.
- A mechanism to force transition to IDLE (TRX_OFF).
- Assume the transceiver is turned off on reception
This changes make drivers easier to implemented and provide extra guarantees to both the driver and upper layer. I tested this one with the ongoing port of OpenDSME and it seems to be compatible.
A stress ping test would be optimal. Also, make sure `tests/ieee802154_hal` work as expected.
Here are some stress …
> ieee802154/hal: adapt to latest changes of #13943

- pkg/nimble/netif/nimble_netif.c
- sys/include/net/gnrc/netif.h
- sys/net/gnrc/link_layer/gomach/gomach.c
- sys/net/gnrc/link_layer/lwmac/lwmac.c
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
- tests/gnrc_netif/main.c
This PR moves the netdev initialization in the gnrc_netif thread to the netif specific `ops`. This is required in order to remove the GNRC<-> netdev dependency and be able to use non netdev layers with GNRC netif (e.g `ieee802154_submac`).
It also has the advantage that the specific interface has control of the netdev callbacks, in cases where the default is replaced ( `gnrc_lorawan`, `gnrc_gomach`, etc).
Make sure that the following modules still work.
- esp_now_gnrc
- nrfmin_gnrc
- gnrc_netif_cc1xxx
- gnrc_netif_nrf24l01p_ng
- gnrc_xbee
- nimble_netif
- gomach
- lwmac
- gnrc_netif_ethernet
- gnrc_netif_raw
- gnrc_netif_ieee802154
- gnrc_netif_lorawan
Same as https://github.com/RIOT-OS/RIOT/pull/13614/files, but this time going in smaller steps.
> gnrc_netif: move netdev initialization to ops->init

- dist/tools/zep_dispatch/main.c
Murdock does not support IPv6 on link-local interfaces.
Therefore in order to being able to use ZEP dispatcher in automated tests on CI, we have to add dual-stack support.
Make ZEP dispatcher listen on an IPv4 address
zep_dispatch 127.0.0.1 17754
Patch the `gnrc_networking` example to use IPv4 for ZEP
```patch
diff --git a/examples/gnrc_networking/Makefile b/examples/gnrc_networking/Makefile
index fcdcc3fb55..784d1fcaa8 100644
--- a/examples/gnrc_networking/Makefile
+++ b/examples/gnrc_networking/Makefile
@@ -47,7 +47,7 @@ USE_ZEP ?= 0
ZEP_PORT_BASE ?= 17754
ifeq (1,$(USE_ZEP))
-  TERMFLAGS += -z [::1]:$(ZEP_PORT_BASE)
+  TERMFLAGS += -z 127.0.0.1:$(ZEP_PORT_BASE)
USEMODULE += socket_zep
endif
```
And start two `native` instances with ZEP:
make -C examples/gnrc_networking USE_ZEP=1 all …
> tools/zep_dispatch: basic dual-stack support

- .murdock
The fast build script seems to have broken nightlies, as those don't have a base branch configured:
```
-- running on worker breeze thread 5, build number 213193.
--- can_fast_ci_run:
usage: can_fast_ci_run.py [-h] [--explain] [--debug] [--riotbase RIOTBASE]
[--upstreambranch UPSTREAMBRANCH] [--changed-boards]
[--changed-apps] [--json]
can_fast_ci_run.py: error: argument --upstreambranch: expected one argument
```
> murdock: don't run can_fast_ci_run if `FULL_BUILD==1`

- pkg/arduino_sdi_12/patches/0001-Use-RIOT-s-gpio-to-handle-pin-change-interrupts.patch
- pkg/arduino_sdi_12/patches/0002-Integration-with-RIOT-to-support-other-boards.patch
- pkg/arduino_sdi_12/patches/0003-RIOT-Fix-for-SAMD-boards.patch
Fix `pkg/arduino_sdi_12` to work with the `feather-m0` board, and probably any other SAMD board.
This adds a patch that removes SAMD specific code, so it defaults to use RIOT's API.
Use `tests/pkg_arduino_sdi_12`, tested with the `feather-m0` board.
None.
> pkg/arduino_sdi_12: fix for the feather-m0 board

- drivers/ethos/ethos.c
This define was marked as deprecated in #11668 (merged in june 2019) so probably no longer used (and even more since using it triggers a failed build).
- Green CI
Marked as deprecated in #11668
> drivers/ethos: remove deprecated USE_ETHOS_FOR_STDIO define

- sys/Makefile.dep
- sys/can/conn/isotp.c
- sys/can/conn/raw.c
- sys/can/device.c
- sys/can/isotp/isotp.c
- sys/include/can/device.h
- sys/include/can/isotp.h
As the title says, this PR migrates the CAN stack to ztimer. The changes are pretty straight forward.
- Green CI
- I don't have any hardware to test this, so would appreciate if someone could test. Maybe @vincent-d ?
> sys/can: migrate to ztimer

- pkg/paho-mqtt/patches/0001-MQTTClient-C-Fix-memory-corruptions.patch
This fixes instances where a pointer to an `enum` (possibly sized one byte) is casted to a pointer to `int` (which is at least two and in most cases four bytes in size). As result, out-of-bounds memory accesses are bound to happen.
This was detected by GCC 11.2.0 with `-Wstringop-overflow`.
Green Murdock & pkg should still work as before
Found in https://github.com/RIOT-OS/RIOT/pull/17004
> pkg/paho-mqtt: fix memory corruption

- sys/Makefile.include
- sys/net/sock/sock_util.c
- tests/unittests/tests-sock_util/Makefile.include
Add a define analogous to `SOCK_HAS_IPV6` so we can skip compilation of IPv4 related code if only IPv6 is used.
> sys/net/sock: introduce SOCK_HAS_IPV4

- sys/include/net/gnrc/ipv6/nib/abr.h
- sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c
- sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h
- sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c
- sys/net/gnrc/network_layer/ipv6/nib/nib_abr.c
remove the only use of evtimer_now_min()
not yet sure
"test/gnrc_ipv6_nib*"
should not fail
#17357 deprecated the need for min to avoid ztimer_now64
> gnrc/ipv6nib: remove the need for evtimer-minutes

- core/init.c
- includes sorted alphabetically
- use C language conditional and rely on elimination of dead code branches rather that the preprocessor doing so
This should not change generated binaries (except maybe for `native`, due do `-Og` instead of `-Os`).
None
> core/init: minor code cleanup

- .murdock
Fix exit -> return in a subfunction, turning an early out into a full script exit.
This is probably what's keeping the nightly builds empty.
> murdock: fix exit -> return in subfunction

- drivers/at/at.c
- drivers/include/at.h
This define is deprecated and was marked for removal after 2021.01.
- Green CI
- Echo is sent by default (as before)
Remove a define marked as deprecated in #14019
> drivers/at: remove deprecated AT_SEND_ECHO define

- pkg/semtech-loramac/contrib/semtech_loramac.c
- sys/include/net/loramac.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan.c
And use inverse `CONFIG_LORAMAC_DEFAULT_PRIVATE_NETWORK` instead.
- Green CI
- `examples/gnrc_lorawan` and `tests/pkg_semtech-loramac` are still working (untested yet)
`LORAMAC_DEFAULT_PUBLIC_NETWORK` was marked for removal after 2021.04 in  #15507
> sys/loramac: remove deprecated LORAMAC_DEFAULT_PUBLIC_NETWORK

- boards/cc1352-launchpad/doc.txt
This PR adds to TI CC1352 Launchpad board documentation section concerning accessing RIOT shell.
The description is provided according to the Issue [#17453](https://github.com/RIOT-OS/RIOT/issues/17453).
I noticed that in all CCXXXX boards, there are some problems with HTML tags in headers generated by doxygen 1.9.1,
used in the official documentation at the project web page, for example [cc1352-launchad](https://doc.riot-os.org/group__boards__cc1352__launchpad.html).  In my environment using older doxygen 1.8.13, this problem is not observed. 
Are there plans for updating doxygen or temporarily, these links should be removed from the documentation? 
```
make doc
xdg-open doc/doxygen/html/group__boards__cc1352__launchpad.html
```
See also #17453
> boards/cc1352-launchpad doc: adding information concerning shell acccess

- core/include/msg.h
- tests/driver_nrf24l01p_lowlevel/main.c
- tests/posix_semaphore/main.c
- tests/thread_msg_block_w_queue/main.c
When a message queue is configured from the stack, that main function
must never return -- otherwise, during sched_task_exit (which the
thread's function "returns" to), message senders might still send
messages into already freed stack space (which would be reused by
sched_task_exit).
[new] A follow-up commit adds a line on this to the msg_init_queue documentation.
Most occurrences of queue initialization throughout RIOT are either static or followed by an endless loop without breaks / returns; the few examples not matching either pattern are fixed here.
I don't see any way to make the fixed behavior actually happen; this is more about best practice. (Especially given that sched_task_exit currently starts with a debug statement followed by `irq_disable`, so the message would need to hit …
> tests: Fix thread return with local message queue

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- tests/rust_minimal/Cargo.lock
This is a simple `cargo update` for a newly released riot-wrappers; the only thing non-simple about is is that cstr_core is still held at 0.2.4 awaiting roll-out of the latest CI builders (does no harm, this is just for anyone curious why `cargo update` would still indicate a change for them).
* Green CI
This unblocks https://github.com/RIOT-OS/RIOT/pull/16458
> rust: Update to riot-wrappers 0.7.15

- drivers/sx126x/sx126x.c
- drivers/sx127x/sx127x.c
- sys/include/net/lora.h
And use the inverse `CONFIG_LORA_PAYLOAD_CRC_OFF_DEFAULT` instead as advertised by the doc.
- Green CI
- `tests/sx126x` and `tests/sx127x` are still working as expected
`LORA_PAYLOAD_CRC_ON_DEFAULT` was marked for removal in #15007
> sys/lora: remove deprecated LORA_PAYLOAD_CRC_ON_DEFAULT define

- sys/net/gnrc/Makefile.dep
- tests/gnrc_udp/Makefile
The `pktbuf` shell command only prints something with `gnrc_pktbuf_static`, when the `od` module is also compiled in. Currently, it is up to the user to include that module, however, I don't think there is much sense behind that. This PR pulls in `od` when `gnrc_pktbuf_cmd` and `gnrc_pktbuf_static` are compiled in.
Revert the commit that adds the new dependency (d4f7f9182b172cdbbd48218997e2e0f5a22bb4ac when this PR was opened). Flash `tests/gnrc_udp` to a board of your choice, run `make term` and type `pktbuf`. No output will be shown. If you then reintroduce the addition of the dependency and repeat the flashing, `pktbuf` will show a similar output (if not the same) as in master.
None
> gnrc_pktbuf_cmd: add od dependency with gnrc_pktbuf_static 

- cpu/esp32/vendor/esp-idf/nvs_flash/Makefile
- cpu/esp8266/vendor/esp-idf/nvs_flash/src/Makefile
- makefiles/cflags.inc.mk
- pkg/arduino_api/Makefile.include
- pkg/flatbuffers/Makefile.include
- pkg/talking_leds/Makefile.include
- pkg/utensor/Makefile.include
- sys/arduino/Makefile.include
- sys/cpp11-compat/Makefile
- sys/cpp11-compat/cppsupport.cpp
- sys/cpp_new_delete/Makefile
- sys/cpp_new_delete/new_delete.cpp
- tests/cpp11_condition_variable/Makefile
- tests/cpp11_mutex/Makefile
- tests/cpp11_thread/Makefile
The GCC version of all used toolchains supports at least C++14. Option `-std=c++14` is therefore set by default for C++ compilations.
Green CI.
> makefiles: use C++14 standard by default for C++ compilations

- cpu/esp32/startup.c
- cpu/esp32/syscalls.c
Use macros/unit instead of custom`MHZ` define.
- murdock should take of everything
> cpu/esp32: use macros/units

- cpu/lpc23xx/Makefile.dep
- cpu/lpc23xx/mci/Kconfig
- cpu/lpc23xx/mci/lpc23xx-mci.c
This PR make `lpc23xx-mci` use ztimer_msec instead of xtimer. Timeout where all > 1ms.
`tests/drivers_mtd_mci` should still work.
> cpu/lpc23xx-mci: migrate to ztimer_msec

- doc/doxygen/src/using-rust.md
The `--locked` is required since dependencies increased their MSRV to
something later than C2Rust's fixed nightly. That was already reflected
in the riotdocker installation steps, but not here where the line was
taken from upstream's docs.
Look at built docs.
Closes: https://github.com/RIOT-OS/RIOT/issues/17492
> doc: Fix C2Rust installation procedure

- drivers/atwinc15x0/atwinc15x0_netdev.c
- drivers/include/net/netdev/lora.h
- drivers/sx126x/sx126x_netdev.c
- drivers/sx127x/sx127x_netdev.c
- pkg/semtech-loramac/contrib/semtech_loramac_radio.c
- sys/include/net/netopt.h
- sys/shell/commands/sc_gnrc_netif.c
The RSSI values reported by LoRa transceiver can be less than -127.
Therefore, `int8_t` is not enough. This commit defines the RSSI of
`netdev_lora_rx_info` as `int16_t` and adapt the drivers accordingly
(sx126x, sx127x).
BTW, the `sx126x` was writing an `int16_t` into an `int8_t`. :man_shrugging:. It's indirectly fixed by this commit.
- Check that the RSSI values reported by the LoRa radios (sx126x, sx127x) are right (negative values, starting from around -140). Use `tests/driver_sx127x` and `test/drivers_sx126x` for that.
Fixes #17451
> [treewide] lora: use int16_t for RSSI value

- drivers/atwinc15x0/atwinc15x0_netdev.c
- drivers/include/net/netdev/lora.h
- drivers/sx126x/sx126x_netdev.c
- drivers/sx127x/sx127x_netdev.c
- pkg/semtech-loramac/contrib/semtech_loramac_radio.c
- sys/include/net/netopt.h
- sys/shell/commands/sc_gnrc_netif.c
The RSSI values reported by LoRa transceiver can be less than -127.
Therefore, `int8_t` is not enough. This commit defines the RSSI of
`netdev_lora_rx_info` as `int16_t` and adapt the drivers accordingly
(sx126x, sx127x).
BTW, the `sx126x` was writing an `int16_t` into an `int8_t`. :man_shrugging:. It's indirectly fixed by this commit.
- Check that the RSSI values reported by the LoRa radios (sx126x, sx127x) are right (negative values, starting from around -140). Use `tests/driver_sx127x` and `test/drivers_sx126x` for that.
Fixes #17451
> [treewide] lora: use int16_t for RSSI value [backport 2022.01]

- tests/pkg_relic/Makefile
Bumping relic seems to have increased stack usage, this made the test fail on some BOARDs as showed in release tests, this PR in
e.g. on iotlab:
`IOTLAB_NODE=auto BOARD=b-l475e-iot01a make -C tests/pkg_relic/ clean flash test -j`
```
main(): This is RIOT! (Version: 2022.04-devel-1-g102534-pr_test_pkg_relic_stacksize)
.
OK (1 tests)
```
See [here](https://github.com/RIOT-OS/RIOT/runs/4834912248?check_suite_focus=true) for a failed iot-lab run.
#17161
> tests/pkg_relic: increase stacksize

- drivers/rtt_rtc/Kconfig
- drivers/rtt_rtc/Makefile.dep
- makefiles/features_modules.inc.mk
Spotted by @emmanuelsearch during release tests, if compiling only the `rtt_rtc` module with the mock then there is a missing dependency against `rtc_utils`.
master
```
make -C tests/unittests/ tests-rtt_rtc
Building application "tests_unittests" for "native" with MCU "native".
"make" -C /home/francisco/workspace/RIOT2/boards/native
"make" -C /home/francisco/workspace/RIOT2/boards/native/drivers
"make" -C /home/francisco/workspace/RIOT2/core
"make" -C /home/francisco/workspace/RIOT2/cpu/native
"make" -C /home/francisco/workspace/RIOT2/cpu/native/periph
"make" -C /home/francisco/workspace/RIOT2/cpu/native/stdio_native
"make" -C /home/francisco/workspace/RIOT2/drivers
"make" -C /home/francisco/workspace/RIOT2/drivers/periph_common
"make" -C /home/francisco/workspace/RIOT2/drivers/rtt_rtc …
```
> drivers/rtt_rtc: select rtc_utils

- cpu/stm32/periph/spi.c
- drivers/include/periph/spi.h
- drivers/sx127x/sx127x.c
When the `spi_init_with_gpio_mode` was added I'm not sure why but we passed the mode by value, as its a structure it makes more sense to pass it by reference.
The code should be the same. This is only used to minimize power consumption on BOARDS including an `sx127x`. I think a compilation check should be enough.
Split from #17233
> drivers/periph_spi: spi_init_with_gpio_mode mode by reference

- drivers/rtt_rtc/Kconfig
- drivers/rtt_rtc/Makefile.dep
- makefiles/features_modules.inc.mk
Spotted by @emmanuelsearch during release tests, if compiling only the `rtt_rtc` module with the mock then there is a missing dependency against `rtc_utils`.
master
```
make -C tests/unittests/ tests-rtt_rtc
Building application "tests_unittests" for "native" with MCU "native".
"make" -C /home/francisco/workspace/RIOT2/boards/native
"make" -C /home/francisco/workspace/RIOT2/boards/native/drivers
"make" -C /home/francisco/workspace/RIOT2/core
"make" -C /home/francisco/workspace/RIOT2/cpu/native
"make" -C /home/francisco/workspace/RIOT2/cpu/native/periph
"make" -C /home/francisco/workspace/RIOT2/cpu/native/stdio_native
"make" -C /home/francisco/workspace/RIOT2/drivers
"make" -C /home/francisco/workspace/RIOT2/drivers/periph_common
"make" -C /home/francisco/workspace/RIOT2/drivers/rtt_rtc …
```
> drivers/rtt_rtc: select rtc_utils [backport 2022.01]

- cpu/cc2538/periph/rtt.c
RTT test was failing on `cc2538` looks like the `set-counter` function was wrong, this should fix it.
The test now passes
```
main(): This is RIOT! (Version: 2022.04-devel-54-g8c8ab-pr_cc2538_set_counter)
RIOT RTT low-level driver test
RTT configuration:
RTT_MAX_VALUE: 0xffffffff
RTT_FREQUENCY: 32768
Testing the tick conversion
Trying to convert 1 to seconds and back
Trying to convert 256 to seconds and back
Trying to convert 65536 to seconds and back
Trying to convert 16777216 to seconds and back
Trying to convert 2147483648 to seconds and back
All ok
Initializing the RTT driver
This test will now display 'Hello' every 5 seconds
RTT now: 4283511575
Setting RTT timer to 1337
RTT now: 1337
rtt_set_counter() PASSED
Setting initial alarm to now + 5 s (165177)
rtt_get_alarm() PASSED
Done …
```
> cpu/cc2538/rtt: fix rtt_set_counter

- pkg/mbedtls/Makefile
Bump the package to the latest version of the 2.x branch
https://github.com/ARMmbed/mbedtls/releases/tag/v2.28.0
`tests/pkg_mbedtls ` still works
```
main(): This is RIOT! (Version: 2022.04-devel-57-g5e599)
mbedtls test
SHA-224 test #1: passed
SHA-224 test #2: passed
SHA-224 test #3: passed
SHA-256 test #1: passed
SHA-256 test #2: passed
SHA-256 test #3: passed
ENTROPY test: passed
```
> pkg/mbedtls: bump version to v2.28.0

- drivers/dose/Makefile.dep
- drivers/dose/dose.c
- drivers/include/dose.h
- sys/chunked_ringbuffer/Makefile
- sys/chunked_ringbuffer/chunked_ringbuffer.c
- sys/include/chunked_ringbuffer.h
- tests/unittests/tests-chunked_ringbuffer/Makefile
- tests/unittests/tests-chunked_ringbuffer/Makefile.include
- tests/unittests/tests-chunked_ringbuffer/tests-chunked_ringbuffer.c
The DOSE driver only has a single RX buffer to store one packet.
That means that when, at high data rates, a second packet arrives while the first packet has not been processed yet, it will be dropped.
This can be seen when e.g. `ping ff02::1` on `samr21-xpro` when operating DOSE at 2 MBit/s: only the first response is received.
To fix this, this PR introduces a 'chunked ringbuffer', a Ringbuffer to store chunks of data - in this case frames.
I added this code in a common place (as `chunked_ringbuffer` module) as it might come in handy for other use cases.
However, since we don't have much time inside the irq handler at high data rates, the producer side needs to be kept slim.
To achieve those data rates we also need two other PRs: #16681 #17180
I have [a …
> drivers/dose: make use of ringbuffer for RX

- doc/doxygen/riot.doxyfile
- pkg/doc.txt
- sys/Makefile.dep
Documentation on how to handle package includes is misleading (maybe outdated?), as it indicates to manually include package's header files in the application Makefile. This is no longer needed.
This PR fixes the documentation, and removes an unnecessary include in `Makefile.dep`.
I'm also piggybacking 6257442e4e7054e8c42834c5f56527a617474882 which assigns a project name to our documentation, because currently I see "My Project" as the top level label. I can split this though if needed.
- Build and read the docs
- Verify that `tests/sys_fido2_ctap` still compiles
Found while reviewing #17435
> pkg: fix documentation on includes

- core/include/thread.h
In #16818 a helper to access a thread's `stack_start` member was introduced.
The documentation of `thread_measure_stack_free` still used the member access rather than the new method.
* Look at diff
> core/thread doc: Point to helper function

- cpu/cortexm_common/vectors_cortexm.c
- cpu/stm32/Makefile.features
- cpu/stm32/cpu_init.c
- cpu/stm32/include/cpu_conf.h
- cpu/stm32/include/periph/cpu_backup_ram.h
- cpu/stm32/include/periph/cpu_pm.h
- cpu/stm32/include/periph_cpu.h
- cpu/stm32/include/stmclk.h
- cpu/stm32/kconfigs/f2/Kconfig
- cpu/stm32/kconfigs/f4/Kconfig.lines
- cpu/stm32/kconfigs/f7/Kconfig
- cpu/stm32/kconfigs/u5/Kconfig
- cpu/stm32/ldscripts/stm32.ld
- cpu/stm32/periph/pm.c
- cpu/stm32/stm32_mem_lengths.mk
- cpu/stm32/stmclk/stmclk_common.c
- cpu/stm32/stmclk/stmclk_u5.c
- tests/periph_backup_ram/Kconfig
- tests/periph_backup_ram/Makefile
This PR aims to make the backup SRAM available for `stm32` MCUs.
<del>It also includes renaming of `backup_ram` to `periph_backup_ram` to better fit in the line with other peripheral features. I can split out the latter, if you agree to the renaming.</del>
`tests/periph_backup_ram` with `nucleo-f767zi`
```
2021-09-19 10:35:10,955 # Try to reconnect to /dev/ttyACM0 again...
2021-09-19 10:35:10,957 # Reconnected to serial port /dev/ttyACM0
2021-09-19 10:35:14,657 # counter: 2
2021-09-19 10:35:18,610 # counter: 3
2021-09-19 10:35:22,563 # counter: 4
2021-09-19 10:35:26,517 # counter: 5
2021-09-19 10:35:30,470 # counter: 6
2021-09-19 10:35:34,423 # counter: 7
2021-09-19 10:35:38,375 # counter: 8
2021-09-19 10:35:42,328 # counter: 9
2021-09-19 10:35:46,280 # counter: 10
2021-09-19 10:35:50,232 …
```
> cpu/stm32: make backup SRAM available

- boards/mulle/board.c
- drivers/include/ltc4150.h
- drivers/ltc4150/Kconfig
- drivers/ltc4150/Makefile.dep
- drivers/ltc4150/ltc4150.c
- drivers/ltc4150/ltc4150_last_minute.c
- drivers/nrf24l01p/Makefile.dep
- drivers/nrf24l01p/nrf24l01p.c
- drivers/nvram_spi/Kconfig
- drivers/nvram_spi/Makefile.dep
- drivers/nvram_spi/nvram-spi.c
- drivers/pir/Kconfig
- drivers/pir/Makefile.dep
- drivers/pir/pir.c
- drivers/si1133/Kconfig
- drivers/si1133/Makefile.dep
- drivers/si1133/si1133.c
- tests/driver_ltc4150/Makefile
- tests/driver_ltc4150/main.c
- tests/driver_nrf24l01p_lowlevel/Makefile
- tests/driver_nrf24l01p_lowlevel/main.c
- tests/driver_nvram_spi/Makefile
- tests/driver_nvram_spi/app.config.test
- tests/driver_nvram_spi/main.c
- tests/driver_pir/Makefile.ci
- tests/driver_pir/main.c
- tests/driver_si1133/Makefile
- tests/driver_si1133/app.config.test
- tests/driver_si1133/main.c
- tests/events/Makefile.board.dep
This PR takes care of the user's of xtimer which can't be directly changed to ztimer with the coccinelle script.
I don't have any of the hardware sadly... but I tagged people that are susceptible to having the hardware, it will at least document what was and not tested.
Part of #13667 and #17111
> drivers: migrate xtimer64 and xtimer/ticks users to ztimer

- boards/stm32f429i-disc1/Kconfig
- drivers/stmpe811/Kconfig
- tests/disp_dev/app.config.test
- tests/driver_stmpe811/app.config.test
- tests/touch_dev/Makefile
- tests/touch_dev/app.config.test
- tests/touch_dev/main.c
This PR improves the Kconfig support around disp/touch_dev at several levels:
- add an app.config.test in related test applications (`tests/disp_dev` and `tests/touch_dev`)
- add missing `HAVE_` with the stmpe811 touch device (and also does some cleanup there)
- extend the stm32f429i-disc1 board Kconfig to declare it has an ili9341 compatible display and stmpe811 touch panel
- migrate the `tests/touch_dev` app to ztimer (since I was on it)
- add `tests/disp_dev` and `tests/touch_dev` apps to the list of apps tested on Murdock with Kconfig. That should help with #17437 and #17448.
A green Murdock should be enough
Noticed that there were missing Kconfig options in stm32f429i-disc1 when working on #17448
> {disp,touch}_dev: improve Kconfig at different levels

- makefiles/libc/newlib.mk
With this PR it becomes possible to use toolchains that provide `newlib-nano` and use `nano.specs` but do not have a separate directory for the newlib version of `newlib.h` because they are only intended to use the nano version.
`makefiles/libc/newlib.mk` assumes that a toolchain which provides the `newlib-nano` provides both the normal version and the nano version of the `newlib`. The nano version of `newlib.h` is therefore stored in its own include directory.  This is necessary for toolchains which allow to use both the normal and the nano version, e.g. for ARM and RISC-V.
However, if the toolchain provides `newlib_nano` but only allows the use of the nano version, it will only have the nano version of `newlib.h` and no separate directory for it, e.g. for ESP32.
To still be able to use …
> makefiles/libc/newlibc: allow toolchains with nano version only

- boards/nucleo-f767zi/include/periph_conf.h
Fix wrong adc pins in periph_conf of nucleo 767zi board for Arduino A0 - A5. Previous configuration was not working and did not match the datasheet description.
New configuration matches the description in [datasheet](https://www.st.com/resource/en/user_manual/um1974-stm32-nucleo144-boards-mb1137-stmicroelectronics.pdf) page 60. See screenshot for convenience. Was tested with all 6 Pins by a simple voltage divider.
--
> boards/nucleo-f767zi: Fix adc pin config in periph_conf.h

- sys/ztimer64/util.c
`ztimer64_set_timeout_flag_at` should use `ztimer_set_at` to be consistent with absolute timeouts.
Cherry-picked from #17365 where `ztimer64` is used for `xtimer` compat module. With this commit `test/thread_flags` and `test/event_wait_timeout` pass
```
BOARD=native make -C tests/event_wait_timeout flash test -j
Building application "tests_event_wait_timeout" for "native" with MCU "native".
"make" -C /home/francisco/workspace/RIOT/boards/native
"make" -C /home/francisco/workspace/RIOT/cpu/native
"make" -C /home/francisco/workspace/RIOT/sys
"make" -C /home/francisco/workspace/RIOT/drivers/periph_common
"make" -C /home/francisco/workspace/RIOT/sys/auto_init
"make" -C …
```
> sys/ztimer64/util.c: fix ztimer64_set_timeout_flag

- examples/gcoap_dtls/Makefile
Repeats #17130 for `examples/gcoap_dtls` as it works with `lwIP` too.
I tested it by connecting to the `SecureServer` example of `Californium`. Don't forget to set `LWIP ?= 1`
> examples/gcoap_dtls: match Makefile of examples/gcoap

- sys/ztimer64/util.c
`ztimer64_set_timeout_flag_at` should use `ztimer_set_at` to be consistent with absolute timeouts.
Cherry-picked from #17365 where `ztimer64` is used for `xtimer` compat module. With this commit `test/thread_flags` and `test/event_wait_timeout` pass
```
BOARD=native make -C tests/event_wait_timeout flash test -j
Building application "tests_event_wait_timeout" for "native" with MCU "native".
"make" -C /home/francisco/workspace/RIOT/boards/native
"make" -C /home/francisco/workspace/RIOT/cpu/native
"make" -C /home/francisco/workspace/RIOT/sys
"make" -C /home/francisco/workspace/RIOT/drivers/periph_common
"make" -C /home/francisco/workspace/RIOT/sys/auto_init
"make" -C …
```
> sys/ztimer64/util.c: fix ztimer64_set_timeout_flag [backport 2022.01]

- drivers/lis2dh12/lis2dh12.c
Using IS_USED leads to undefined API references if `ztimer` is not used, it should also be guarding against `ZTIMER_MSEC` instead of `ZTIMER`.
- Running the `lis2dh12` would be good as well (no hardware available right now for me)
> drivers/lis2dh12: use ifdef instead of IS_USED

- tests/driver_motor_driver/main.c
- tests/thread_priority_inversion/main.c
This PR removes explicit calls to `xtimer-init()` in tests not disabling `auto-init`.
Split from #17365
> tests/*: remove uneeded xtimer_init

- tests/periph_uart_nonblocking/Makefile
- tests/periph_uart_nonblocking/app.config.test
- tests/periph_uart_nonblocking/main.c
This PR migrates the `periph_uart_nonblocking` to use `ztimer`, avoiding accessing `xtimer` internals.
- ` make -C tests/periph_uart_nonblocking/ flash test -j`
```
main(): This is RIOT! (Version: 2022.04-devel-126-g621d8-pr_xtimer_init_in_test)
puts with disabled interrupts and a full transmit buffer
Join us now and share the software;
You'll be free, hackers, you'll be free.
Join us now and share the software;
You'll be free, hackers, you'll be free.
Hoarders can get piles of money,
That is true, hackers, that is true.
But they cannot help their neighbors;
That's not good, hackers, that's not good.
When we have enough free software
At our call, hackers, at our call,
We'll kick out those dirty licenses
Ever more, hackers, ever more.
Join us now and share the software; …
```
> tests/periph_uart_nonblocking: migrate to ztimer

- boards/nucleo-f767zi/include/periph_conf.h
Fix wrong adc pins in periph_conf of nucleo 767zi board for Arduino A0 - A5. Previous configuration was not working and did not match the datasheet description.
New configuration matches the description in [datasheet](https://www.st.com/resource/en/user_manual/um1974-stm32-nucleo144-boards-mb1137-stmicroelectronics.pdf) page 60. See screenshot for convenience. Was tested with all 6 Pins by a simple voltage divider.
--
> boards/nucleo-f767zi: Fix adc pin config in periph_conf.h [backport 2022.01]

- cpu/riscv_common/Kconfig
- cpu/riscv_common/Makefile.features
- makefiles/cargo-targets.inc.mk
- makefiles/docker.inc.mk
This is largely just stating it works.
It contains a workaround for
https://github.com/rust-lang/rust-bindgen/issues/1555 (withouot which
bindgen would fail, with little information helping remedy the cause)
[edit: added] Note that the actual RUST_TARGET referred to in "HAS_RUST_TARGET" has already been set since the introduction to Rust (so that experimentation could be done when forcing one's way around the features); only now it is used. When any other targets than riscv32imac are supported, `makefiles/arch/riscv.inc.mk` will need adjustments both on the CFLAGS and RUST_TARGET side.
* Take a RISC-V board, run one of the Rust examples or tests.
(I did it with a hifive1 and rust-hello).
Even though I thought I had all the right and matching compilers, things did not work for me when …
> cpu/riscv_common: Enable Rust applications

- dist/tools/compile_commands/compile_commands.py
The --clangd adjustments showed to be faulty by not being acceptable for Rust's bindgen when used on RISC-V builds. This fixes things by
* adding `-msmall-data-limit=8` to the clangd filter-out list (the option *is* supported by clang, but only in versions more recent than the libclang shipped with current riotdocker), and
* replacing all the `-Wformat-truncation` etc. warning filter-outs with an added `-Wno-unknown-warning-option` flag.
Its documentation is adjusted to no longer exhaustively list what is done, but to give an overview.
* My main use case is covered in re-runs of #17491, which now passes. (Before, it failed complaining about `-msmall-data-limit=8`).
* I don't know how else compile_commands is used, any ideas for extra testing or whether it's necessary?
(I'd think that the …
> tools/compile_commands: Update --clangd set

- cpu/cortexm_common/vectors_cortexm.c
- doc.txt
- doc/doxygen/riot.doxyfile
- makefiles/pseudomodules.inc.mk
This adds a module documentation group to pseudomodules, and populates a few first entries that would have been needed in #17132.
* Look at documentation
* Makefiles are treated like Python files; this seems to be the only way to get Doxygen to look at them and not ignore the Makefile comments because they look like C directives. This could be prettier if Doxygen's [extension mappings](https://www.doxygen.nl/manual/starting.html#default_file_extension_mapping) were extensible beyond picking one of the known languages.
* A dedicated group is created for each module. This is a bit ugly as it's many small pages, and pages without content practically always repeat their brief line.
I think these are acceptable as long as we're using Doxygen.
The last commit soft-depends on #17132 which …
> doc: Start documenting pseudomodules

- cpu/riscv_common/ldscripts/riscv_base.ld
Since commit 3a11b1fbd280b2b46ef0a8011bead180800f83c2 (#16972) building RIOT applications with `BOARD=hifive1` causes the following linker warning to be emitted on my system:
/opt/rv32imc/lib/gcc/riscv32-unknown-elf/10.2.0/../../../../riscv32-unknown-elf/bin/ld:riscv_base.ld:220: warning: memory region `rom' not declared
This is due to the fact that the RISC-V linker script doesn't have a rom memory region. While many other ARM-based boards have a rom memory region defined in the linker script, the corresponding region name in the RISC-V linker script is flash and rom is not declared as a memory region hence the warning.
I think this was accidentally overlooked in 3a11b1fbd280b2b46ef0a8011bead180800f83c2. It is fixed in this commit by replacing the rom region with the flash region. The …
> cpu/riscv_common: fix undeclared memory region linker error

- boards/samr34-xpro/doc.txt
- boards/samr34-xpro/include/board.h
- dist/tools/doccheck/exclude_patterns
- drivers/sx127x/include/sx127x_registers.h
- drivers/sx127x/sx127x_internal.c
The [ WLR089 Xplained Pro](https://www.microchip.com/en-us/development-tool/EV23M25A)  is pretty much identical to the [SAM R34 Xplained Pro](https://www.microchip.com/en-us/development-tool/DM320111) - this adds a `doc.txt` to clarify that.
The only notable difference so far is, that the device ID returned by the sx1276 radio is `0x13` instead of `0x12`.
It works when adjusting the check accordingly.
@firas-hamdi ran `examples/gnrc_lorawan` and `tests/driver_sx127x`
> boards/samr34-xpro: add minimal support for WLR089 Xplained Pro

- boards/p-nucleo-wb55/doc.txt
This PR improves a bit the documentation of this board:
- use the main `boards` Doxygen group as parent group: the board is listed with all other boards (for the moment it's listed alone under a common nucleo group and is difficult to find)
- update the notes about the OpenOCD version to use to flash this board. It's supported in 0.11.0 release, so just mention it as a minimal requirement
- add new features supported: Watchdog is supported, according to the STM32 features and USB support was added recently in #17281
Check the documentation
None
> boards/p-nucleo-wb55: update documentation

- drivers/dose/Makefile.dep
- drivers/dose/dose.c
- drivers/include/dose.h
This PR migrate `dose` to use `ztimer`. It's untested.
Maybe @benpicco can suggest the best testing procedure?
Split from #17365
> drivers/dose: migrate to ztimer_usec

- core/include/sched.h
- core/sched.c
- makefiles/pseudomodules.inc.mk
- sys/shell/commands/Makefile
- sys/shell/commands/sc_nice.c
- sys/shell/commands/shell_commands.c
- tests/sched_change_priority/Makefile
- tests/sched_change_priority/Makefile.ci
- tests/sched_change_priority/main.c
- tests/sched_change_priority/tests/01-run.py
This PR is a rebase of the `sched_change_priority()` function from https://github.com/RIOT-OS/RIOT/pull/7445 (introduced in commit https://github.com/RIOT-OS/RIOT/pull/7445/commits/976d17f8b1076568c0df0e6053893557f441ce2b) with some changes:
1. No module required to unlock this
- The linker does a fine job at garbage collecting the function, if it is unused
2. The function works as expected in corner cases
- If the modified thread is the running one, this will work
- If the modified thread is pending and becomes a higher priority than the active one, it will now preempt the running one
A test application was added that contains an automatic test. E.g.
```
$ make BOARD=nucleo-f767zi -C tests/sched_change_priority flash test
[...]
socat - open:/dev/ttyACM0,b115200,echo=0,raw 
main(): This …
```
> core/sched: add sched_change_priority()

- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
According to ieee802154_radio_confirm_transmit docs, the parameter of
confirm_op for IEEE802154_HAL_OP_TRANSMIT is to be populated as an out
parameter -- but this implementation unconditionally left info
unpopulated. Thus, when run with LLVM, _fsm_state_tx_process_tx_done
looked into an uninitialized info and thus crashed into failing
assertions.
---
Note that the init was initialized NULL and later that init is checked for being NULL; now there's an actual non-NULL (or maybe non-NULL as the caller may well pass in NULL) writing access.
I checked the wrappers for the other _confirm_op operations, and they either pass in NULL as the argument, or pass in a boolean clear parameter that does get set, so it seems justified to only set info in this particular branch. (One might consider moving …
> cpu/nrf52 radio: Populate info

- sys/ztimer64/ztimer64.c
adds stdio.h include in front of inttypes.h fixes:
```
ztimer64.c:298:26: error: expected ')' before 'PRIu64'
298 |         printf("0x%08x:%" PRIu64 "\n", (unsigned)entry, entry->target);
```
```
examples/hello-world$ USEMODULE=ztimer64_msec BOARD=nucleo-f767zi make clean all
```
with master:
```
ztimer64.c:298:26: error: expected ')' before 'PRIu64'
298 |         printf("0x%08x:%" PRIu64 "\n", (unsigned)entry, entry->target);
```
with PR:
SUCCESS
https://github.com/mirror/newlib-cygwin/blob/d079ab4d37ca37cef04e43aa333ab2b53c81699d/newlib/libc/include/inttypes.h#L216
> sys/ztimer64: PRIu64 requires stdio before inttypes

- tests/pkg_mbedtls/Makefile
The ENTROPY test always fails on this board
```
main(): This is RIOT! (Version: buildtest)
mbedtls test
SHA-224 test #1: passed
SHA-224 test #2: passed
SHA-224 test #3: passed
SHA-256 test #1: passed
SHA-256 test #2: passed
SHA-256 test #3: passed
ENTROPY test: failed
```
> tests/pkg_mbedtls-blacklist: blacklist samr21-xpro

- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/netif/gnrc_netif.c
- tests/driver_at86rf215/Makefile.ci
- tests/gnrc_netif_ipv6_wait_for_global_address/main.c
This converts gnrc_netif.c to use ztimer instead of xtimer.
I think the test in tests ` tests/gnrc_netif_ipv6_wait_for_global_address` should be sufficient:
```Shellsession
koen@zometeen ~/dev/RIOT-dev $ make -C tests/gnrc_netif_ipv6_wait_for_global_address/ term
make: Entering directory '/home/koen/dev/RIOT-dev/tests/gnrc_netif_ipv6_wait_for_global_address'
/home/koen/dev/RIOT-dev/tests/gnrc_netif_ipv6_wait_for_global_address/bin/native/tests_gnrc_netif_ipv6_wait_for_global_address.elf /dev/ttyACM0 
LED_RED_OFF
LED_GREEN_ON
s
START
....
OK (4 tests)
```
On the list of #17111
> gnrc/netif: convert to ztimer

- Makefile.dep
- Makefile.include
As the `dir` make function considers the last slash as part of the directory-part of a file name, we don't need to add an extra one. From the [function documentation](https://www.gnu.org/software/make/manual/html_node/File-Name-Functions.html):
> The directory-part of the file name is everything up through (and including) the last slash in it. 
Alternatively we can go the other way, and remove the slash from the variable. I took this path because of the natural way make seems to consider directory paths.
`tests/external_module_dirs` should work as usual
Spotted while reviewing #17596
> makefiles: avoid extra "/" when including files from external modules

- .murdock
Previously, the fanned out job collection would add it's jobs to the
"default" queue, competing with build jobs. This could lead to a
situation where job collection would take very long or even time out.
This PR choses "default-first" as queue for the fan-out. Workers are
expected to add that queue *before* "default", so its jobs get processed
first.
> murdock: prioritize job collection over build jobs

- boards/feather-m0/include/board.h
In the `feather-m0` board the `sx127x` pin parameters are hardcoded for the
`feather-m0-lora` variant, but this is not compatible with other configurations.
For example in the feather-m0 adalogger `PA06` and `PA08` are used for the
SD card. When combined with the RFM95W FeatherWing the IRQ/CS/RST pins
must be wired, and then the sx127x pins must be configured to match the
wiring (which will be necessarily different from the lora variant configuration).
With the proposed change the pin configuration only applies to the `feather-m0-lora`
variant. If a different configuration is used, the pins must be defined somewhere else.
This change fixes a preprocessor redefined error:
```
error: "SX127X_PARAM_SPI_NSS" redefined [-Werror]
```
I've tested `tests/driver_sx127x` with two Feathers M0 …
> boards/feather-m0: sx127x params only valid for lora variant

- drivers/dose/dose.c
- drivers/include/dose.h
`DOSE_TIMER_DEV` is defined in `board.h`, so we have to include it.
It's not included by the header (and should not), so move the check to the .c file.
> drivers/dose: include board.h

- dist/pythonlibs/testrunner/spawn.py
- makefiles/pseudomodules.inc.mk
- makefiles/stdio.inc.mk
- pkg/nimble/Makefile.include
- pkg/nimble/contrib/nimble_riot.c
- sys/include/stdio_nimble.h
- sys/stdio_nimble/Makefile
- sys/stdio_nimble/README.md
- sys/stdio_nimble/stdio_nimble.c
- tests/shell/tests/01-run.py
- tests/shell_ble/Makefile
- tests/shell_ble/README.md
- tests/shell_ble/main.c
- tests/shell_ble/tests-with-config/01-run.py
Implement a new module stdio_nimble, which uses UART and nimble in parallel for stdio. The characteristic for stdin is writable and the characteristic for stdout uses the indicate mechanism to publish the system's output to a connected device. Calls of "_send_from_ringbuffer" to send data via nimBLE are chained together using a callback in nimBLE called "_gap_event_cb".
Module can be enabled with `USEMODULE += stdio_nimble`
UART can be disabled with `CFLAGS += -DSTDIO_NIMBLE_DISABLE_UART`
For automatic advertising a new module is provided: "auto_nimble_advertise". It will take care to enable advertising on disconnect and disable on connect.
Module can be enabled with `USEMODULE += auto_nimble_advertise`
Advertised device name can be configured with
`CFLAGS += …
> sys/stdio_nimble: add new stdio module using nimble

- core/include/rmutex.h
- core/rmutex.c
- sys/include/atomic_utils.h
- sys/xtimer/xtimer.c
- sys/ztimer/util.c
- sys/ztimer64/util.c
- tests/xtimer_rmutex_lock_timeout/main.c
- tests/ztimer_rmutex_lock_timeout/main.c
Replace use of C11 atomics with atomic utils. This fixes
>     error: address argument to atomic operation must be a pointer to a
>            trivially-copyable type ('_Atomic(int) *' invalid)
error when compiling on AVR with LLVM.
`tests/rmutex` should still pass
None
> core/rmutex: use atomic utils

- boards/adafruit-itsybitsy-m4/board.c
- boards/common/weact-f4x1cx/board.c
- boards/ikea-tradfri/board.c
- boards/iotlab-m3/mtd.c
- boards/mulle/board.c
- boards/nrf52840dk/mtd.c
- boards/pinetime/board.c
- boards/qn9080dk/board.c
- boards/same54-xpro/board.c
- boards/serpente/board.c
- drivers/include/mtd_spi_nor.h
- drivers/mtd_spi_nor/mtd_spi_nor.c
New variants of the `same54-xpro` board now come with the SST26VF064B QSPI flash instead of N25Q256A.
This requires some changes:
- the capacity encoding scheme is different from existing chips
- Global Block-Protection Unlock is required before the chip accepts writes (but this is only needed once)
- 8 MiB device instead of 32 MiB, does *only* support 24 bit addressing
To solve the third problem, `addr_width` is not determined at run-time so it does not have to be set by the board anymore.
I used `tests/mtd_raw` to test the changes:
```
2022-02-03 22:03:44,478 # main(): This is RIOT! (Version: 2022.04-devel-223-g9fd1b-drivers/mtd_spi_nor-microchip)
2022-02-03 22:03:44,479 # Manual MTD test
2022-02-03 22:03:44,483 # init MTD_0… OK (32 MiB)
2022-02-03 22:03:44,486 # init MTD_1… OK (256 …
```
> boards/same54-xpro: support for board variation with SST26VF064B flash

- .murdock
- boards/stm32mp157c-dk2/Kconfig
- cpu/stm32/kconfigs/Kconfig.clk
This adds the clock config and makes kconfig work for the stm32mp1 based boards (currently only stm32mp157c-dk2).
U also added some way to print the values of the macros... Maybe we would leave it in, especially for some of the more complex things.
murdock passes and kconfig binaries match.
#14975
> cpu/stm32: Add clock config for mp1 to kconfig

- .murdock
- boards/lora-e5-dev/Kconfig
- cpu/stm32/kconfigs/Kconfig.clk
This implements the clock configuration of the stm32wl CPU in Kconfig.
It is largely based off the stm32wb config.
The `lora-e5-dev` board can now indicate that the HSE/LSE should be used.
Murdock green and compare what is in the header.
Part of #14975
> cpu/stm32/wl: Model kconfig clocks

- pkg/fatfs/fatfs_vfs/fatfs_vfs.c
- pkg/littlefs/fs/littlefs_fs.c
- pkg/littlefs2/fs/littlefs2_fs.c
- pkg/spiffs/fs/spiffs_fs.c
- sys/include/vfs.h
- sys/vfs/vfs.c
All file systems provide a means to flush pending data to storage without closing the filedescriptor.
Expose this function via VFS.
> sys/vfs: provide vfs_fsync()

- .murdock
- boards/ublox-c030-u201/Makefile.dep
Run all non-blockisted boards for every kconfig enabled app only during nightlies.
This should find any corner cases slipping through the regular testing (currently only one on the ublox-c030-u201 board due to incorrect makefile modelling).  This should also have no impact on regular CI times, only the nightly will be longer (since it will eventually double the jobs).
Check to see that the removeme commit, forcing nightly, tests a board that would not normally be tested for kconfig.
> kconfig explore all allowed boards on all apps

- tests/pkg_mbedtls/Makefile
- tests/pkg_mbedtls/main.c
- tests/pkg_mbedtls/tests/01-run.py
*tests/pkg_mbedtls* failed the entropy tests on some boards (compare [this](https://github.com/RIOT-OS/RIOT/pull/15671#issuecomment-1020920722) and [this](https://github.com/RIOT-OS/RIOT/pull/15671#issuecomment-1022361502) comment).
This PR applies the following changes:
- Indicate when `adc noise` is the only source for the mbedtls entropy module. In this case, it can occur that the test fails due to improper ADC configurations and hardware properties.
- The testrunner checks for the occurrence of "adc_noise_single_entropy" and does not wait for a successful entropy test result in this case.
- Remove CI blacklisting introduced in #17588.
- Execute *tests/pkg_mbedtls* on boards (`samr21-xpro` and `nucleo-l152re` in particular) and native using  `make test`.
- CI passes execution on …
> tests/pkg_mbedtls: improve entropy test case and doc

- pkg/littlefs/fs/littlefs_fs.c
- pkg/littlefs2/fs/littlefs2_fs.c
- tests/pkg_littlefs/main.c
- tests/pkg_littlefs2/main.c
`readdir()` should only output the name of the file, but littleFS adds a leading `/`.
Neither FAT nor Linux will exhibit this behavior. (SPIFFS does not support directories)
struct dirent *entry;
DIR *dir = opendir(".");
while ((entry = readdir(dir))) {
printf("%s\n", entry->d_name);
}
This results in surprising failures of code that expects filenames to match that was tested on a different FS, when suddenly there is a `/` in front of the filename.
```
> ls /
/.
/..
/test
total 3 files
> ls /test
/.
/..
/0.cnk
/1.cnk
total 4 files
```
```
> ls /
.
..
test
total 3 files
> ls /test
.
..
0.cnk
1.cnk
total 4 files
```
> pkg/littlefs*: align readdir() with documentation

- cpu/nrf52/Kconfig
- cpu/nrf52/Makefile.dep
- cpu/nrf52/Makefile.features
- cpu/nrf5x_common/periph/spi_nrf52_nrf9160.c
- cpu/nrf9160/Kconfig
- cpu/nrf9160/Makefile.dep
- cpu/nrf9160/Makefile.features
- cpu/nrf9160/periph/Kconfig
This PR allows nrf52-9160 to init spi with pull-up/pull-downs. The motivation was to be able to get rid of the use of `soft-spi` code in #17233, used in init just because spi was not able to set pull-up, but many platforms can.
Tested on a dwm1001 with an sdcard attached:
```
2022-02-04 09:41:23,859 # help
2022-02-04 09:41:23,861 # Command              Description
2022-02-04 09:41:23,865 # ---------------------------------------
2022-02-04 09:41:23,869 # mount                mount flash filesystem
2022-02-04 09:41:23,873 # format               format flash file system
2022-02-04 09:41:23,877 # umount               unmount flash filesystem
2022-02-04 09:41:23,881 # cat                  print the content of a file
2022-02-04 09:41:23,885 # tee                  write a string in a file …
```
> cpu/nrf52-9160: add periph_spi_init_gpio

- pkg/nimble/README.ipv6-over-ble.md
sudo doesn't work here as only the `echo` command is executed with elevated permission and the pipe is not.
Reading the changes should be sufficient.
None
> nimble: Use sysctl in docs

- sys/fs/constfs/constfs.c
- sys/shell/commands/sc_vfs.c
This aligns ConstFS readdir() implementation more with POSIX.
```
main(): This is RIOT! (Version: 2022.04-devel-288-g28fa5)
constfs mounted successfully
> ls /const
ls /const
hello-world	14 B
hello-riot	13 B
total 2 files
> cat /const/hello-world
cat /const/hello-world
Hello World!
```
#14635
> fs/constfs: omit leading '/' in readdir() 

- pkg/tinydtls/Makefile.dep
- pkg/tinydtls/patches/0001-dtls_time-migrate-to-ztimer64_msec.patch
`tinydtls` is usins some `xtimer` externals which prevent a drop in replacement with `ztimer_xtimer_compat`, so this PR migrate it to use `ztimer64_msec` instead of `xtimer`.
The patch would be upstreamed later, but I think it makes more sense to get it reviewed here first.
- Running some dtls tests
Split form #17365
> pkg/tinydtls: migrate to ztimer64_msec

- sys/include/xtimer.h
- sys/include/xtimer/implementation.h
- tests/xtimer_remove/main.c
There are [cases](https://github.com/RIOT-OS/RIOT/pull/17365/commits/6d88a942c4b059158f928093b64eb0c5495c5668#r802579616) where code is using internal xtimer struct members to figure out if a given xtimer is currentlly set. So, provide a function in the public API.
I've added some uses of this function (both ways, on set timers and unset timers) to `xtimer_remove()`.
I consider this addition as an intermediate step, easing migration to ztimer_xtimer_compat.
CI should be fine.
> sys/xtimer: introduce `xtimer_is_set()`

- dist/tools/kconfiglib/genconfig.py
This extends the error messages to check if a symbol could not be set due to its visibility.
One can quickly test this by trying to enable a hidden symbol. For example, in `tests/kconfig/Kconfig` defining:
```
config HIDDEN_SYMBOL
bool
```
And trying to enable it in `tests/kconfig/app.config`: `CONFIG_HIDDEN_SYMBOL=y`. When calling `make menuconfig` for instance, you should see this new error message.
None
> dist/tools/genconfig: add error on hidden symbols

- sys/include/net/gnrc/pkt.h
Currently this header can't be included from C++ files when building for native:
```
/data/riotbuild/riotproject/RIOT/sys/include/net/gnrc/pkt.h: In function ‘gnrc_pktsnip_t* gnrc_pkt_delete(gnrc_pktsnip_t*, gnrc_pktsnip_t*)’:
/data/riotbuild/riotproject/RIOT/sys/include/net/gnrc/pkt.h:213:26: error: C++ designated initializers only available with ‘-std=c++2a’ or ‘-std=gnu++2a’ [-Werror=pedantic]
213 |     list_node_t list = { .next = (list_node_t *)pkt };
|                          ^
cc1plus: all warnings being treated as errors
make[2]: *** [/data/riotbuild/riotproject/RIOT/Makefile.base:166: /data/riotbuild/riotproject/sock_udp_example_cpp/bin/native/sock_udp_base_cpp/sock_udp_base.o] Error 1
make[1]: *** [/data/riotbuild/riotproject/RIOT/Makefile.base:31: …
```
> net/gnrc/pkt: Fix ISO C++ compatibility

- cpu/native/include/netdev_tap.h
- cpu/native/netdev_tap/netdev_tap.c
- drivers/include/net/netdev.h
- pkg/lwip/init_devs/auto_init_netdev_tap.c
- sys/net/gnrc/netif/init_devs/auto_init_netdev_tap.c
This adds the `netdev_tap` device to `netdev_register`. This is convenient for testing.
N/A
N/A
> cpu/native/netdev_tap: Add to netdev_register

- sys/include/net/af.h
This adds a `typedef` to the unix interface family enum.
This is useful as it allows to have the interface family as enum method parameter and then improves compile time type checks.
> net: Add typedef for AF enum

- boards/nucleo-l552ze-q/doc.txt
Improvements to STM Nucleo L552ZE-QE documentation:
- Add board image,
- Add MCU table - similar to those, for example for, Nucleo F103RB, F302R8 or F446RE,
- Add information concerning accessing RIOT shell (see Issue #17453) 
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l552ze-q.html
```
Issue #17453
> boards/nucleo-l552ze-q doc: Improvements to documentation

- boards/nucleo-l552ze-q/Makefile.include
- boards/nucleo-l552ze-q/doc.txt
- dist/tools/cpy2remed/cpy2remed.sh
- makefiles/tools/cpy2remed.inc.mk
This PR adds a new programmer to the Nucleo boards with an on-board ST-LINK debugger. On-board ST-LINK provides removable media to which program image file in HEX format could be copied for programing. Introduced **_cpy2remed_** (copy two removable media) script automates programming process.
OpenOCD programmer could utilize ST-LINK, but in my opinion, more straightforward method without installing additional software could be beneficial for users not familiar with micro-controllers.
Currently, programmer was tested on STM Nucleo-L552ZE-Q board; however, all Nucleo boards with ST-LINK should work after a minor enhancement - add **DIR_NAME_AT_REMED**  variable to the **_Makefile.include_** file.
Go to RIOT/examples/blinky and run command:
```
make BOARD=nucleo-l552ze-q PROGRAMMER=cpy2remed …
```
> tools/cpy2remed: Addition of new programmer for nucleo boards

- pkg/fatfs/fatfs_vfs/fatfs_vfs.c
- pkg/spiffs/fs/spiffs_fs.c
- sys/fs/constfs/constfs.c
- sys/posix/sockets/posix_sockets.c
- sys/vfs/vfs.c
File systems are sloppy around stat buffer initialization; this moves the zeroing over from the drivers to the VFS in general (before it even dispatches to the file system).
This was originally a problem of littlefs (fixed in the alternative PR https://github.com/RIOT-OS/RIOT/pull/17644) as found when reviewing the FatFS statvfs that would have had the same issue in https://github.com/RIOT-OS/RIOT/pull/17634#discussion_r805144779), and (when removing all the memsets that should have been there) also found in mtd-vfs and nvram-vfs (both around devfs, IIUC)
```
$ make -C examples/filesystem all term
main(): This is RIOT! (Version: 2022.04-devel-321-g02109f-littlefs-stat-buffers)
constfs mounted successfully
> format
format
/sda successfully formatted
> mount
mount
/sda successfully mounted …
```
> vfs: Initialize stat buffers so FSs don't have to

- makefiles/default_modules.deps.mk
- makefiles/defaultmodules.inc.mk
- makefiles/dependency_resolution.inc.mk
- makefiles/features_modules.inc.mk
- sys/Makefile.dep
- sys/ztimer/Makefile.dep
- tests/gnrc_dhcpv6_relay/Makefile
Some DEFAULT_MODULEs in tree have dependencies of their own. This is
usually done for aliases of init modules, and do not have dependencies
themselves.
This adds the final stage to dependency resolutions where DEFAULT_MODULEs
dependencies MAY be included. These included modules MUST NOT have
dependencies themselves.
This allows for modules to disable DEFAULT_MODULEs during dependencies
resolution independent of the inclusion order.
auto_init and periph_init modules are moved to this outer-loop, allowing
therefore for modules to disable them during the dependency resolution
Dependencies should not have changed.
Could be used by #17584
> makefiles/dependency_resolution: add outer loop for DEFAULT_MODULE deps 

- boards/native/Makefile.dep
- boards/native/board_init.c
- boards/same54-xpro/Makefile.dep
- boards/same54-xpro/board.c
- examples/filesystem/Makefile
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/vfs/Kconfig
This adds a `vfs_default` pseudo-module that works analogous to the `netdev_default` module and let's a board specify a default file system and mount point.
As an example I configured littlefs2 for the external flash on the `same54-xpro` which gets mounted to `/nvm`.
Add 
USEMODULE += vfs_default
to any application (e.g. `examples/gnrc_networking`). You now have a file system! (and a `ls` command) 
Add the
USEMODULE += vfs_auto_format
module if you want to automatically create the file system too.
> sys/vfs: add vfs_default, configure default fs for same54-xpro

- boards/native/include/board.h
- examples/filesystem/README.md
- tests/pkg_fatfs/Makefile
- tests/pkg_fatfs_vfs/Makefile
The FAT file system makes some strong assumptions about sector and block size that are not met by the default native MTD emulation.
To avoid this trip hazard, change the native MTD defaults when FAT is used.
The tests still work without overwriting the default values.
> boards/native: select MTD defaults for FAT

- sys/include/ztimer.h
ztimer_now() is hard to use correctly, and even though it set out to allow implementation flexibility, expectations are already creeping up based on properties ZTimer happens to have now.
This puts a damper on any expectations one might have on ztimer_now() values. It documents design goals (as I understand them), and may easily be stricter than the current implementation is -- but that is necessary to keep implementation flexibility that is already being exercised in PRs like https://github.com/RIOT-OS/RIOT/pull/17607.
(It may also help motivate the creation of a high-level stopwatch mechanism as sketched in #17607, because yes that's a scary wall of text any user would have to go through).
If a timer is set with a timeout way less than 2^32 (say, 2^31, as interrupts need to happen at …
> sys/ztimer doc: List prerequisites for successful use of ztimer_now

- boards/msba2/include/periph_conf.h
- core/assert.c
- core/include/assert.h
- core/panic.c
- cpu/stm32/periph/i2c_1.c
- cpu/stm32/periph/i2c_2.c
- drivers/disp_dev/disp_dev.c
- drivers/saul/init_devs/auto_init_sgp30.c
- examples/nanocoap_server/coap_handler.c
- examples/suit_update/coap_handler.c
- sys/fmt/fmt.c
- sys/include/net/gnrc/ipv6/nib/pl.h
- sys/include/net/gnrc/sixlowpan/ctx.h
- sys/include/utlist.h
- tests/nanocoap_cli/request_handlers.c
- tests/sys_architecture/main.c
remove panic.h include from assert.h
since assert.h is a stdlib header it should follow the rules for stdlib headers (one of them being only define marcos that the header is used for and have every thing else in _<n/Name> and __<n/Name>
successful ci-run  (avoid something depending on  `panic.h` being included by `assert.h`
The remove me has a patched hello-world example:
for the non assert code path:
```
DEVHELP=0 CFLAGS=-DNDEBUG make flash term
```
for the panic assert code path:
```
DEVHELP=1 make flash term
```
for the verbose assert code path:
```
DEVHELP=1 CFLAGS=-DDEBUG_ASSERT_VERBOSE make flash term
```
> core/assert: avoid including panic.h with assert.h

- sys/include/evtimer.h
removes deprecated `evtimer_now_min()`
grep for  'evtimer_now_min' and see there is nothing left
deprecated in #17357
last know user was fixed with #17411
> sys/evtimer: remove deprecated evtimer_now_min

- makefiles/cflags.inc.mk
- sys/malloc_thread_safe/malloc_wrappers.c
https://github.com/RIOT-OS/RIOT/pull/14754 broke LTO as it created significantly larger binaries (instead of smaller) with LTO enabled. Our micro benchmarks showed increased performance, so LTO still worked partially.
I tracked this down to `-ffunction-sections -fdata-sections` missing for the linker invocation.
This PR fixes that by adding those flags to LINKFLAGS if LTO is enabled.
binary (text) sizes for examples/hello-world on nrf52840dk:
|  | LTO=0 | LTO=1 |
| ----- | ----- | ----- |
| master | 8688 | 10188 |
| PR | 8688| 7792 |
non-LTO binaries should be identical. lto binaries should be smaller and still work.
I did not enable "run tests" as no LTO tests are run on CI.
https://github.com/RIOT-OS/RIOT/pull/14754
fixes #16202
> make: add -ffunction-sections -fdata-sections to LINKFLAGS if LTO=1

- examples/filesystem/Makefile
- examples/filesystem/README.md
- makefiles/pseudomodules.inc.mk
- pkg/fatfs/Makefile.dep
- pkg/fatfs/fatfs_diskio/mtd/mtd_diskio.c
- pkg/fatfs/fatfs_vfs/fatfs_vfs.c
- pkg/fatfs/vendor/include/ffconf.h
- sys/include/fs/fatfs.h
- tests/pkg_fatfs_vfs/Makefile
- tests/pkg_fatfs_vfs/main.c
This hooks up `vfs_format` to `f_mkfs()`.
fatfs also provides a `f_fdisk()` function to create a partition table, but this doesn't seem to be necessary. 
Since pulling in the format logic adds 3.5k `.text` and will not be needed on many applications, it is added as a  `fatfs_vfs_format` pseudo-module.
`tests/pkg_fatfs_vfs` will now format the storage before testing, so beware :wink: 
This is consistent with the other file-system tests though.
> pkg/fatfs: fatfs_vfs: wire up format()

- drivers/include/mtd.h
- drivers/include/mtd_flashpage.h
MTD doesn't explicitly say what it is about, picking the term from a Linux subsystem but using different terms internally (sector and page vs. Linux's eraseblock). This adds clarifying text and links relevant modules.
* Look at built docs, confirm they match your expectations of MTD.
Contributes-To: https://github.com/RIOT-OS/RIOT/issues/17663
> mtd doc: Add overview defining terms; link modules

- drivers/at86rf215/Makefile
- drivers/at86rf215/at86rf215_netdev.c
If only a single modulation is used by the application, we can save some ROM by disabling modes that are not used.
However, this is broken as the .c files were still compiled and then failed because now struct members were missing,
Only compile the relevant .c files if the modulation is used.
This should work now:
DISABLE_MODULE += netdev_ieee802154_mr_oqpsk
DISABLE_MODULE += netdev_ieee802154_mr_ofdm
DISABLE_MODULE += netdev_ieee802154_mr_fsk
> drivers/at86rf215: fix disabling individual modulations

- sys/include/vfs.h
- sys/shell/commands/sc_vfs.c
- sys/vfs/vfs.c
If auto-init of a default mount fs failed (e.g. because an SD card was not inserted on boot) or `vfs_auto_mount` was disabled, there is no way to mount such an auto-mount fs later manually.
Fix this by introducing a `vfs_mount_by_path()` function that takes the mount point of a pre-configured mount to trigger the mount procedure at run-time (e.g. when an SD card was inserted).
I extended the `vfs` command with a `mount` sub-command.
vfs mount /
> sys/vfs: add vfs_mount_by_path()

- sys/net/gnrc/network_layer/sixlowpan/frag/sfr/gnrc_sixlowpan_frag_sfr.c
The change should be trivial, use `xtimer_is_set` which does the same thing, and avoid touching `.long_offset` for ztimer compatibility. Since those are static variables they are initialized as 0 anyway.
- green murdock should do
```
make -C tests/gnrc_sixlowpan_frag flash test -j
LED_RED_OFF
LED_GREEN_ON
READY
s
START
main(): This is RIOT! (Version: 2022.04-devel-389-g13bb0-pr_sixlowpanfrag_xtimer_is_set)
..............
OK (14 tests)
```
Split and adapted from  #17365
> sys/net/gnrc_sixlowpan_frag_sfr: use xtimer_set

- drivers/include/mtd_sdcard.h
- drivers/mtd_sdcard/mtd_sdcard.c
- tests/mtd_raw/Makefile
This allows to use SD card as a MTD backed even if users want to do unaligned reads and writes (e.g. SPIFFS, FlashDB). 
The `test` command from `tests/mtd_raw` should now work on SD cards. 
<details><summary>master</summary>
```
main(): This is RIOT! (Version: 2022.04-devel-401-g130eb42)
Manual MTD test
init MTD_0… OK (8 MiB)
init MTD_1… OK (256 byte)
init MTD_2… OK (15247 MiB)
> test 2
[START]
tests/mtd_raw/main.c:432 => failed condition
CONDITION FAILED.
*** halted.
```
</details>
```
main(): This is RIOT! (Version: 2022.04-devel-221-g91ca7-drivers/mtd_sdcard-unaligned)
Manual MTD test
init MTD_0… OK (0 byte)
init MTD_1… OK (256 byte)
init MTD_2… OK (15247 MiB)
> test 2
[START]
[SUCCESS]
```
</details>
If the SD card is not …
> drivers/mtd_sdcard: support unaligned reads & writes

- sys/include/vfs.h
- sys/shell/commands/sc_vfs.c
- sys/vfs/vfs.c
- tests/vfs_iterate_mount/Makefile
- tests/vfs_iterate_mount/Makefile.ci
- tests/vfs_iterate_mount/main.c
- tests/vfs_iterate_mount/tests/01-run.py
Listing mount points was previously documented as racy, and generic modules using it could barely ensure that nothing else in the system would mount/unmount at impractical times (#17658 was an attempt to fix that by making the mutex public, but that had other downsides).
This introduces an iteration mechanism that is thread-safe because it keeps a directory handle open for the currently viewed FS, and that (just like an open file) keeps the FS from being unmounted.
In bycatch and related changes, it
* removes per-filesystem `fstatvfs` calls (for lack of reason to have that as a separate driver method, when all users go through the generic `statvfs` method that has the same properties anyways)
* alters `vfs_iterate_mounts` to produce the actual mount sequence (and not some …
> vfs: Introduce reliable disk enumeration

- cpu/efm32/Makefile.dep
- cpu/efm32/periph/Makefile
- pkg/gecko_sdk/Makefile
Currently, RIOT supports only Series 0 and 1 EFM32 CPUs. I'm about to bring the first Series 2 CPU into RIOT. This PR updates the SDK to version 4.0, which is required for Series 2 support.
Furthermore, I have done some housekeeping and changed the mechanics how series-specific periph drivers are selected. I've found this trick in the STM32 cpu family ;-)
All EFM32-based boards should still work.
https://github.com/basilfx/RIOT-gecko-sdk/pull/4#issuecomment-1008045570
> cpu/efm32: bump Gecko SDK version

- dist/tools/dhcpv6-pd_ia/kea.py
I was wondering why the border router would not work on `native` witth `USE_DHCPV6=1`, then I remembered that I manually have to create `/run/kea` each time.
So let's add this to the `dhcpv6-pd_ia.py` script so it will 'just work' in the future. 
It looks like on Arch something simimar was needed, but on Ubuntu `/run` is a tmpfs, so we have to create the directory after each reboot.
make -C examples/gnrc_border_router USE_DHCPV6=1 all term
should get a global address on the ZEP interface.
> tools/dhcpv6-pd_ia: create /run/kea on startup

- cpu/riscv_common/Kconfig
- cpu/riscv_common/Makefile.features
- cpu/riscv_common/include/cpu_conf_common.h
- cpu/riscv_common/ldscripts/riscv_base.ld
- cpu/riscv_common/riscv_init.c
- cpu/riscv_common/start.S
This pull request enables the `puf_sram` feature for RISC-V platforms. The changes include:
- Add a `.noinit` section to the RISC-V linker script.
- Clear `.bss` section only until actual end of that section, to prevent clearing `.noinit`.
- New helper function that calls `puf_sram_init` is executed from startup code.
- Enable the feature via `Makefile.features`.
Execute *tests/puf_sram* on a RISC-V board as explained in the test [README](https://github.com/RIOT-OS/RIOT/tree/master/tests/puf_sram#readme). I have used the `hifive1b` board. Note that this platform requires a power-off time of ~10 seconds to produce fresh memory pattern on startup.  
1. Run the example test script alike `python tests/example_test.py -t 10 -n 100`. This produces 100 SRAM based seeds with a power-off time of …
> cpu/riscv_common: enable puf_sram feature

- boards/nucleo-f767zi/include/periph_conf.h
> boards/nucleo-f767zi: fix adc_config indentation

- pkg/tinydtls/Makefile.dep
- pkg/tinydtls/contrib/sock_dtls.c
In  #17564 `tinydtls` code was migrated to `ztimer`, but for some reason, `sock_dtls` was looked over, and not caught by the CI, it's now resurfaced with #17670, so this PR cleans this up.
Since `sock` timeous are in `us` this PR us using `ztimer_usec, only 32bits are required here.
I also uncrustified in a separate commit.
I ran `examples/dtls-sock` between two native nodes, also change the timeouts from `SOCK_NO_TIMEOUT` to `5 * US_PER_SEC` and saw it timeout after 5 second when only one native node was up:
- timeout
```
main(): This is RIOT! (Version: 2022.04-devel-416-g092ca-pr_tinydtls_ztimer_cleanup)
DTLS sock example application
> dtlsc fe80::4cb2:45ff:fe3a:8461 "secure data"
dtlsc fe80::4cb2:45ff:fe3a:8461 "secure data"
Error creating session: -110
> …
```
> pkg/tinydtls/sock_dtls: use ztimer_usec

- sys/Makefile.dep
- sys/net/dsm/Makefile.dep
Caught by CI when running on #17670. `sock_dtls` is a module and not a feature, the Makefile.dep was never included, move it to the generic `sys/Makefile.dep`
Green Murdock should be enough
Split from #17670.
> sys/net/dsm: add missing dependencies

- cpu/sam0_common/sam0_info.mk
- cpu/saml21/Makefile.include
The size of the low power SRAM on SAM L21 family chips varies between members.
Decode the model number just like it's done for STM32 so we don't need to maintain an ever expanding list.
`tests/periph_backup_ram` should still compile.
> cpu/saml21: derive low power SRAM length from model number

- sys/shell/commands/sc_gnrc_udp.c
i noticed that lately `udp send ff02::1 1234 test` would not return back to the shell and appear blocked.
Some investigation into the code revealed that with xtimer the command would add a 1000000 µs delay after each packet, but with ztimer it would add a 1000000 **ms** delay (~16 minutes).
Fix this by setting the proper default delay depending on the timer used.
There is also no need for a delay after the last packet to begin with, this is only an artifact of sending multiple packets - so add a check to only delay if the packet was not the last one.
`udp send` should work again.
> shell/sc_gnrc_udp: always use delay in µs

- makefiles/boards/ztimer_only.dep.mk
- sys/Kconfig.newlib
- sys/Makefile.dep
- sys/include/xtimer.h
- sys/include/ztimer64.h
- sys/include/ztimer64/xtimer_compat.h
- sys/xtimer/Kconfig
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
- tests/xtimer_drift/Makefile
- tests/xtimer_drift/app.config.test
This PR makes `ztimer_xtimer_compat` use `ztimer64_usec` implementing all `xtimer` api, with this `ztimer64_usec` can be used as a drop-in replacement for `xtimer`.
- Green Murdock should be enough, #17365 will flag possible remaining offenders.
Split from #17365
> sys/ztimer: add ztimer64_xtimer_compat complete xtimer replace module

- doc/doxygen/src/using-rust.md
Doc fix: Some line duplication happened already in the initial version, and when [17504] had the `--locked` added, the opportunity to remove the duplication was missed.
[17504]: https://github.com/RIOT-OS/RIOT/pull/17504
This obsoletes https://github.com/RIOT-OS/RIOT/pull/17694 which would solve half of that line's problem (the missing `--locked`; the other is that it's not installing from the checked-out source)
Later https://github.com/RIOT-OS/RIOT/pull/17536 will touch this all again, but that's still waiting for a CI update and for a full test run.
> doc/rust: Remove duplicate (and wrong) line

- sys/include/ztimer/xtimer_compat.h
removes all functions from `ztimer/xtimer_compat.h` (32 Bit) that are not implementable by using ztimer (32 Bit)
if these functions are used `ztimer64/xtimer_compat.h` should be used
#17670
> sys/ztimer: cleanup xtimer_compat.h for 32Bit only

- examples/rust-gcoap/Cargo.lock
- examples/rust-gcoap/Cargo.toml
- examples/rust-gcoap/src/lib.rs
- examples/rust-hello-world/Cargo.lock
- tests/rust_minimal/Cargo.lock
This restores compatibility with current nightlies by using the latest
coap-message version (after a nightly-only feature that uses saw a late
change), and also removes obstacles for use with stable Rust 1.59 (in
unrelated parts; the CoAP example is still nightly-only).
In addition, two deprecations in the used libraries are followed to ensure a warning-free output.
* Green CI
* In addition, I did `make -C tests/run_minimal all flash test` on native and microbit-v2, as well as a native test run on the gcoap example. (Both with latest nightly and with BUILD_IN_DOCKER=1)
Contributes-To: https://github.com/RIOT-OS/RIOT/issues/17526
> {examples,tests}/rust: cargo update and deprecation fixes

- pkg/fatfs/Makefile.include
- pkg/fatfs/doc.txt
- pkg/fatfs/fatfs_vfs/fatfs_vfs.c
- sys/include/vfs.h
For increased performance it can be desireable to disable the tiny option.
The config option enables a per-file cache which increases the size of `fatfs_file_desc_t`.
Build with 
CFLAGS += -DFATFS_FFCONF_OPT_FS_TINY=0
CFLAGS += -DFATFS_FFCONF_OPT_USE_FASTSEEK=1
> pkg/fatfs_vfs: support FF_FS_TINY=0

- sys/include/ztimer/xtimer_compat.h
while working on #17693 a bug in #17690 was detected
`xtimer_usleep(x)` -which redirects to `ztimer_sleep(ZTIMER_USEC,x)` needs no `clock` in `xtimer_tsleep64()`
also adds  missing
```
dummy XTIMER_BACKOFF
xtimer_init
xtimer_is_set
xtimer_rmutex_lock_timeout
```
build xtimer_test using ztimer/xtimer_compat
either by include of ztimer/xtimer_compat.h and adding ztimer_usec to USEMODULE
or adding 
ztimer_xtimer_compat to USEMODULE
while working on #17693 a bug in #17690 was detected
> sys/ztimer/xtimer_compat: fix bug introduced in #17690

- pkg/nanors/Makefile
- pkg/nanors/Makefile.include
- pkg/nanors/doc.txt
- tests/pkg_nanors/Makefile
- tests/pkg_nanors/Makefile.ci
- tests/pkg_nanors/main.c
- tests/pkg_nanors/tests/01-run.py
[nanors](https://github.com/sleepybishop/nanors) provides fast reed solomon codes in GF2^8.
On Cortex-M4 the implementation (`rs.o`) only consumes a little less than 2k ROM. 
A test application is provided in `tests/pkg_nanors`.
It generates random data, parity shards and then deletes random shards and attempts to reconstruct them.
> pkg/nanors: add reed solomon codec implementation

- sys/Makefile.dep
- sys/include/net/coap.h
- sys/include/net/gcoap.h
- sys/include/net/nanocoap.h
- sys/include/net/nanocoap_sock.h
- sys/include/suit/transport/coap.h
- sys/net/application_layer/Kconfig.coap
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/net/application_layer/nanocoap/sock.c
- sys/suit/handlers_command_seq.c
- sys/suit/transport/coap.c
- tests/nanocoap_cli/main.c
- tests/nanocoap_cli/nanocli_client.c
- tests/pkg_edhoc_c/initiator.c
This refactors the nanocoap API to not open/close a socket for each request, to allow for socket re-use and align it more with what SUIT does.
As a result, we can remove the copy of `_nanocoap_request()` from SUIT.
The timeout handling differs a bit: In SUIT `CONFIG_COAP_ACK_TIMEOUT` is used as a timeout for the whole request (for all retransmissions combined) whereas nanocoap uses it as the initial timeout for the first request and then doubles the timeout.
I kept the nanocoap behavior, but changed the timeout to milliseconds so lower initial values can be used.
As a next step, this also moves `suit_coap_get_blockwise()` to `nanocoap_get_blockwise()` so it can be used outside SUIT.
`examples/suit_update` still works
<details><summary>make BOARD=same54-xpro  test-with-config</summary> …
> sys/net/nanocoap: introduce `nanocoap_sock_*()`, use in suit/transport/coap

- core/include/msg.h
- core/include/thread_flags.h
How to make sure own thread flags or message types do not conflict with preexisting ones (especially with the lack of a comprehensive of predefined ones for the latter) is difficult from the current documentation; this change set:
* clarifies that flags *will* be set by the OS without solicitation,
* and adds a single define against which custom use can be checked; and
* states that messages are *not* set by the OS willy-nilly, and that system-wide uniqueness of numbers is not really necessary (but just a good practice by the standard library)
(and fixes an obsolete number in the process).
* Agree with the changes to the docs
* Watch nothing break in the tests from an added define
This contains clean-up from https://github.com/RIOT-OS/RIOT/pull/7717
> core (largely doc): Differentiate message types from thread flags

- doc/doxygen/riot.doxyfile
- pkg/driver_bme680/doc.txt
- pkg/u8g2/doc.txt
- pkg/ucglib/doc.txt
- pkg/uwb-dw1000/README.md
- pkg/uwb-dw1000/doc.txt
add RIOT root to Doxygen example path
and include some Readme.md with their respective doc.txt  
sadly we can't use `@includedoc` or `@include{doc}` until Doxygen 1.9.2 
see https://github.com/doxygen/doxygen/pull/8395
read
and
check circleci: doc-build artifact 
eg
https://15379-7370241-gh.circle-artifacts.com/0/doc/group__pkg__u8g2.html
vs
https://doc.riot-os.org/group__pkg__u8g2.html
#10815
> doc: add RIOT root doxygen example path

- examples/cord_epsim/main.c
- examples/cord_lc/cord_lc_cli.c
- examples/dtls-echo/dtls-client.c
- examples/dtls-sock/dtls-client.c
- examples/dtls-wolfssl/dtls-client.c
- examples/emcute_mqttsn/main.c
- fuzzing/gnrc_tcp/main.c
- sys/include/net/gnrc/ipv6.h
- sys/include/net/sock/dtls.h
- sys/include/net/sock/ip.h
- sys/include/net/sock/tcp.h
- sys/include/net/sock/udp.h
- sys/net/application_layer/dhcpv6/client.c
- sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c
- sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.c
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
- sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
- sys/net/gnrc/sock/include/sock_types.h
- sys/shell/commands/sc_cord_ep.c
- sys/shell/commands/sc_sntp.c
- tests/gnrc_sock_neterr/main.c
- tests/gnrc_sock_tcp/main.c
- tests/nanocoap_cli/nanocli_client.c
- tests/pkg_edhoc_c/initiator.c
- tests/pkg_tinydtls_sock_async/dtls-client.c
- tests/sock_udp_aux/main.c
a huge examples and tests, some sys-modules and fuzzing/gnrc use functions of xtimer, gnrc(/nteif), without including the header, this PR adds these includes.
- reading
- Murdock 
- build them
was found while working on #17693
> sys,examples,tests,fuzzing: add missing includes 

- examples/arduino_hello-world/Makefile
- tests/candev/Makefile
- tests/conn_can/Makefile
- tests/dbgpin/Makefile
- tests/mpu_noexec_ram/Makefile
- tests/mpu_stack_guard/Makefile
- tests/mtd_at24cxxx/Makefile
- tests/periph_backup_ram/Makefile
- tests/periph_dma/Makefile
- tests/periph_gpio/Makefile
- tests/periph_gpio_arduino/Makefile
- tests/periph_uart_mode/Makefile
- tests/periph_uart_nonblocking/Makefile
- tests/periph_vbat/Makefile
- tests/pkg_arduino_sdi_12/Makefile
- tests/pkg_cryptoauthlib_compare_sha256/Makefile
- tests/pkg_cryptoauthlib_internal-tests/Makefile
- tests/sys_arduino/Makefile
- tests/sys_arduino_lib/Makefile
This adds a building default Board to many tests that are currently missing one
when working on  #17693 ( the part that has become #17714) I wanted to build ~all Tests (for any BOARD) - prior to uploading that for murdock to do the same for all boards, and some of them did just fail because they where build for native, because there was no Board set
<details>
Makefile i used (copied to examples or tests)
https://gist.github.com/kfessel/9af890ddf7e7088cec9acbddbda4ebdb
</details>
```
$ make -C <some test>
```
before PR
```
$ make -C tests/periph_dma
make: Entering directory ' ... /tests/periph_dma'
There are unsatisfied feature requirements: periph_dma
```
after PR
```
$ make -C tests/periph_dma
make: Entering directory '... /tests/periph_dma'
Building application "tests_periph_dma" for …
```
> tests: add default BOARDS

- drivers/dose/dose.c
The DOSE watchdog should only run if at least one interface is in RECV state.
That means it must be enabled when entering RECV state and disabled when leaving RECV state.
The watchdog was *always* disabled on a transition to IDLE.
This is wrong: If there are two interfaces and one is in RECV state but the other did just SEND something and transitions to IDLE state from SEND state, it would still disable the watchdog.
Fix this by only disabling the watchdog if the current state is RECV.
This can be hard to reproduce, but when it occurs it can forever lock an interface in `RECV` state:
A board with two DOSE interfaces is required. You need to enable the `dose_watchdog` module.
Lines are disconnected / no regular traffic *but* spurious UART interrupts caused by noise.
When such an interrupt …
> drivers/dose: only disable watchdog when transiting from RECV state

- tests/sys_crypto/tests-crypto-modes-ocb.c
On resent gcc I get a warning on the test:
```
/home/francisco/workspace/RIOT/tests/sys_crypto/tests-crypto-modes-ocb.c:407:5: error: ‘key’ may be used uninitialized [-Werror=maybe-uninitialized]
407 |     cipher_init(&cipher, CIPHER_AES, key, 16);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/francisco/workspace/RIOT/tests/sys_crypto/tests-crypto-modes-ocb.c:9:
/home/francisco/workspace/RIOT/sys/include/crypto/ciphers.h:141:5: note: by argument 3 of type ‘const uint8_t *’ {aka ‘const unsigned char *’} to ‘cipher_init’ declared here
141 | int cipher_init(cipher_t *cipher, cipher_id_t cipher_id, const uint8_t *key,
|     ^~~~~~~~~~~
/home/francisco/workspace/RIOT/tests/sys_crypto/tests-crypto-modes-ocb.c:404:13: note: ‘key’ declared here
404 |     uint8_t …
```
> tests/sys_crypto: fix potentially unitialized error

- sys/ztimer64/ztimer64.c
- tests/unittests/tests-ztimer64/tests-ztimer64-core.c
ztimer64 wasn't properly clearing a removed timer struct, but depended on that for it's `ztimer64_is_set()`.
This PR adds a fix, and a regression test.
regression test output with the fix reverted:
```
main(): This is RIOT! (Version: 2022.04-devel-568-g33dae8-fix_ztimer64_remove)
rs
READY
START
.......
ztimer64_tests.test_ztimer64_remove_clear (tests/unittests/tests-ztimer64/tests-ztimer64-core.c 238) !ztimer64_is_set(&timer)
run 7 failures 1
```
CI tests this now. :)
Found with #17365.
> sys/ztimer64: fix `ztimer64_remove()` not properly clearing timer struct

- pkg/lwip/contrib/sock/lwip_sock.c
- pkg/lwip/contrib/sock/udp/lwip_sock_udp.c
- pkg/lwip/include/lwip/sock_internal.h
- pkg/openwsn/sock/openwsn_sock_udp.c
- sys/Makefile.dep
- sys/include/net/sock.h
- sys/include/net/sock/udp.h
- sys/net/gnrc/sock/udp/gnrc_sock_udp.c
- tests/gnrc_sock_udp/main.c
- tests/gnrc_sock_udp/stack.c
- tests/lwip_sock_udp/main.c
Both GNRC and LWIP support the notion of packet snips/slices: A packet does not have to be in continuous memory.
This is useful when e.g. sending a blockwise CoAP message where the CoAP header can be a small buffer and the CoAP block payload can be just a pointer into a larger buffer (possibly on ROM).
However, the sock API completely throws this out of the window by only allowing a single payload buffer in `sock_udp_send()`.
This means we need another buffer to copy the payload and the header into, artificially doubling memory requirements and introducing an unnecessary copy step. 
Fix this by introducing a new `sock_udp_sendv()` function. This allows to specify an array of payload chunks instead of a single buffer. `sock_udp_send()` is now simple a wrapper around the new function.
> sys/net/sock: add sock_udp_sendv() API

- cpu/stm32/include/clk/l0l1/cfg_clock_default.h
Fixes the `CLOCK_CORECLOCK` value for STM32L0/L1 MCUs, previously the value would lose some precision when dividing the PLL source clock (e.g.: `(MHZ(8)/3)*12` would result in 31999992 Hz instead of 32 MHz).
Compilation on STM32L0/L1 MCUs should succeed
> cpu/stm32: Fix CLOCK_CORECLOCK on stm32l0/l1

- tests/bench_xtimer_load/main.c
- tests/xtimer_drift/main.c
This PR removes unneeded `xtimer_now_timex` calls, the value was never used.
Found in #17365 and split.
> tests/*xtimer*: remove uneeded timex calls

- sys/net/gnrc/Makefile.dep
gomach uses periph_rtt therefore should not have rtt used by ztimer.
- in gomach example rtt is used but not by ztimer:
```
BOARD=iotlab-m3 make -C examples/gnrc_networking_mac/ info-modules | grep rtt
periph_init_rtt
periph_rtt
ztimer_no_periph_rtt
```
Split from #17365
> sys/net/gnrc: ztimer_no_periph_rtt if gomach

- sys/include/net/gnrc/sixlowpan/frag/fb.h
This guards the header.
- in master the following error showed up if using `ztimer_xtimer_compat` (no 64bit), which exposed the wrongful inclusion.
`USEMODULE=ztimer_xtimer_compat make -C tests/gnrc_sixlowpan_frag -j`
```
In file included from /home/francisco/workspace/RIOT/sys/include/evtimer_msg.h:24,
from /home/francisco/workspace/RIOT/sys/include/net/gnrc/sixlowpan/frag/sfr_types.h:25,
from /home/francisco/workspace/RIOT/sys/include/net/gnrc/sixlowpan/frag/fb.h:31,
from /home/francisco/workspace/RIOT/sys/net/gnrc/network_layer/sixlowpan/frag/fb/gnrc_sixlowpan_frag_fb.c:20:
/home/francisco/workspace/RIOT/sys/include/evtimer.h: In function ‘evtimer_now_msec’:
/home/francisco/workspace/RIOT/sys/include/evtimer.h:134:12: error: implicit declaration of function …
```
> sys/gnrc/sixlowpan/frag/fb: guard sfr_types.h header include

- dist/tools/buildsystem_sanity_check/check.sh
- makefiles/docker.inc.mk
This PR adds a potential solution for #14504
This adds a list of variables that should always be passed to docker
since they are commonly set in Makefile/Makefile.include and therefore
can not be checked for their origin.
~~This one should carefully be tested, at least so that dependencies do not change with or without this PR. I think `/dist/tools/buildsystem_sanity_check/save_all_dependencies_resolution_variables.sh ` should be ran at least.~~
Kconfig run https://github.com/RIOT-OS/RIOT/pull/17396#issuecomment-1034856703
Test out passing dependency-related variables...
@leandrolanzieri what Kconfig related things should be added as well.
Partial fix to #14504
> makefiles/docker.inc.mk: add DOCKER_ENV_VARS_ALWAYS

- doc/memos/README.md
The RDMs page lists the currently released memos, but the ones currently in progress are at least as relevant to casual readers because they are where input is needed. This documents a) that they are agreed on in PRs, and b) where those currently under discussion can be found.
> doc/memo: Link to RDMs in development

- sys/posix/pthread/include/pthread_once.h
- sys/posix/pthread/pthread_once.c
This PR provides a `pthread_once_t` type that is compatible with newlib's `pthread_once_t`.
When using a toolchain with built-in POSIX thread support, static C++ constructors use a static (fake) mutex variable which is initialized with `pthread_once` when first used. However, since RIOT's `pthread_once_t` type is different from that in newlib's `pthread`, which is assumed by GCC, RIOT crashes as soon as static constructors are used.
Changing the `pthread_once_t` type to be compatible with newlib's `pthread_once_t` type solves the problem and allows the RIOT `pthread` modules to be used even with toolchains with built-in POSIX thread support. The costs for this change is one additional `int` variable.
With this change, the precompiled ESP32 toolchains including OpenOCD from Espressif can …
> sys/posix/pthread: newlib compatibility

- examples/gcoap/server.c
- sys/include/net/gcoap.h
- sys/include/net/nanocoap.h
- sys/net/application_layer/gcoap/gcoap.c
https://github.com/RIOT-OS/RIOT/pull/15549 introduced DTLS support for CoAP, but did not make it possible to select the transport on request. Since switching between CoAP and CoAPS (CoAP-over-DTLS) as client is a valid use case (one might want to e.g. talk to one server over CoAP and to another over CoAPS), this change makes that possible.
This is only a draft for now.
TODOs:
Untested for now.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/15549
> gcoap: multi-transport support

- sys/event/periodic.c
- sys/include/ztimer/periodic.h
- sys/ztimer/periodic.c
- tests/ztimer_periodic/main.c
The callback function of `ztimer_periodic` is only expected to have two states.
So let it return `true` if the timer should keep repeating, `false` otherwise.
**This is an API change**: Previously users had to return `0` to keep going, now `!0` needs to be returned to keep the timer running. But the meaning of the return value was previously undocumented and the functionality is rather new, I expect there to be not many (if any) users.
`tests/ztimer_periodic` still works
> ztimer_periodic: make callback function return bool

- sys/net/link_layer/csma_sender/csma_sender.c
The private API should not be used.
Found in [#17365](https://github.com/RIOT-OS/RIOT/pull/17365)
> sys/net/link_layer/csma_sender: use public xtimer_now()

- pkg/lwip/Makefile.dep
- pkg/lwip/contrib/sys_arch.c
- tests/lwip/Makefile
- tests/lwip/ip.c
- tests/lwip/tcp.c
- tests/lwip/udp.c
- tests/lwip_sock_ip/main.c
- tests/lwip_sock_ip/stack.c
- tests/lwip_sock_tcp/main.c
- tests/lwip_sock_tcp/stack.c
- tests/lwip_sock_udp/main.c
- tests/lwip_sock_udp/stack.c
This package changes `lwip` to use `ztimer_msec` instead of `xtimer`.
Run all `tests/lwip*` tests
- `test/lwip_sock_ip`
```
main(): This is RIOT! (Version: 2022.01-devel-323-g3f03ac-pr_lwip_use_ztimer)
code 0x41
Calling test_sock_ip_create6__EAFNOSUPPORT()
Calling test_sock_ip_create6__EINVAL_addr()
Calling test_sock_ip_create6__EINVAL_netif()
Calling test_sock_ip_create6__no_endpoints()
Calling test_sock_ip_create6__only_local()
Calling test_sock_ip_create6__only_local_reuse_ep()
Calling test_sock_ip_create6__only_remote()
Calling test_sock_ip_create6__full()
Calling test_sock_ip_recv6__EADDRNOTAVAIL()
Calling test_sock_ip_recv6__EAGAIN()
Calling test_sock_ip_recv6__ENOBUFS()
Calling test_sock_ip_recv6__ETIMEDOUT()
* Calling sock_ip_recv()
* (timed out with timeout 1000000)
Calling …
```
> pkg/lwip: use ztimer_msec instead of xtimer

- cpu/native/Kconfig
- cpu/native/Makefile.dep
- sys/Kconfig.newlib
- sys/Makefile.dep
- sys/net/gnrc/Makefile.dep
- sys/ztimer/Kconfig
This PR splits from [#17365](https://github.com/RIOT-OS/RIOT/pull/17365) all modules depending on 64bit features of xtimer. It allows not using `64bit` if not needed, note that because of `newlib` this is actually used most of the time (a nice case to optimize @kfessel)
In cases where there was already a ztimer based alternative for xtimer, those get used instead.
Note that some might still be missed as covered in the build but some of these modules.
Split from [#17365](https://github.com/RIOT-OS/RIOT/pull/17365)
> sys: sort out ztimer_xtimer_compat and ztimer64_xtimer_compat depes

- sys/net/gnrc/sock/include/sock_types.h
This guards the tcp header inclusion since it holds references to `evtimer` which may not be included in the build if `gnrc_tcp` is not
This fails in master
```
BOARD=arduino-mega2560 USEMODULE=ztimer_xtimer_compat make -C tests/gnrc_sock_async_event/ -j
```
```
"make" -C /data/riotbuild/riotbase/sys/ztimer
make[1]: *** [/data/riotbuild/riotbase/Makefile.base:146: /data/riotbuild/riotbase/tests/gnrc_sock_async_event/bin/arduino-mega2560/application_tests_gnrc_sock_async_event/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /data/riotbuild/riotbase/sys/include/evtimer_msg.h:24:0,
from /data/riotbuild/riotbase/sys/include/net/gnrc/tcp/tcb.h:26,
from /data/riotbuild/riotbase/sys/include/net/gnrc/tcp.h:27,
from …
```
> sys/net/gnrc/sock_types: guard tcp.h header inclusion

- tests/driver_scd30/Makefile.ci
- tests/pkg_libfixmath_unittests/Makefile.ci
- tests/pkg_wolfssl/Makefile.ci
These BOARDs overflowed in ROM after arm-none-eabi-gcc version
in riot/riotbuild changed to 10.3.2
Green murdock.
> tests/*: add BOARDs to Makefile.ci

- tests/cpu_avr8_xmega_drivers/Makefile
> tests/cpu_avr8_xmega_driver: fix BOARD name

- tests/driver_dfplayer/Makefile
Avoid deprecated module.
Green murdock
> tests/driver_dfplayer: use event_thread instead of event_thread_lowest

- dist/tools/doccheck/exclude_patterns
- drivers/encx24j600/include/encx24j600_params.h
- sys/net/gnrc/netif/init_devs/auto_init_encx24j600.c
- tests/driver_encx24j600/Makefile
This adds default params to the `encx24j600` (the values are taken from the test application), and modifies the `auto_init` code to support multiple driver instances.
- Green CI
- Optionally run the test application (I could not do this as I don't have the device)
Split from #17739
> drivers/encx24j600: define default parameters

- boards/common/qn908x/Makefile.include
**WIP**
Some sort of race condition seems to be triggering random errors on the `qn9080dk` board: `arm-none-eabi-size: /tmp/dwq.0.09674638050766471/103682e29d7607ed5a01e49cd01d1398/build/tests_driver_dcf77.elf: file format not recognized`.
I could reproduce this locally when running murdock script:
```
/bin/bash -c "source .murdock; JOBS=4 compile tests/driver_mag3110 qn9080dk:gnu"
```
~~This seems to fix the problem locally for me, but I'm not 100% sure this is the cause.~~
For what we observed, the operations of objcopy on the `.elf` file are affecting the file itself, so other operations (e.g.: calculating hash for Kconfig test, printing size) seem to fail depending on when the file is accessed. As there is no strong dependency for the `$(ELFFILE_CHECKSUM)` target on the other targets …
> boards/common/qn908x: perform elf checksum on shadow copy

- boards/nucleo-f334r8/Makefile.include
- boards/nucleo-f334r8/doc.txt
- boards/nucleo-f429zi/Makefile.include
- boards/nucleo-f429zi/doc.txt
- boards/nucleo-f446ze/Makefile.include
- boards/nucleo-f446ze/doc.txt
This PR enables **_cpy2remed_** programmer (see #17550) to three STM Nucleo boards: F334r8, F429ZI and F446ZE.
All boards have initially older ST-LINK firmware - the oldest was:
```
Version: 0221
Build:   Nov  4 2015 15:25:25  
``` 
During firmware update I checked few, and the minimal version of the ST-LINK firmware which works with **_cpy2remed_** programmer is 2.37.36 (V2.J37.M26 - shown in the  ST-LinkUpgrade program).  
Go to RIOT/examples/blinky and run command
```
make BOARD=nucleo-f334r8 PROGRAMMER=cpy2remed flash
make BOARD=nucleo-f429zi PROGRAMMER=cpy2remed flash
make BOARD=nucleo-f446ze PROGRAMMER=cpy2remed flash
```
After a while, green LED (LED0) should start blinking.
Changes in documentaion can be observed using commands:
```
make doc
xdg-open …
```
> boards/nucleo-f334r8 f429zi and f446ze: enable cpy2remed programmer

- sys/net/gnrc/network_layer/ipv6/nib/nib.c
As the title says. I guess that is what it was supposed to be.
> ipv6/nib: fix memcpy() bug in _handle_rtr_timeout()

- cpu/sam0_common/sam0_eth/sam0_eth_netdev.h
- sys/net/gnrc/netif/init_devs/auto_init_sam0_eth.c
Currently `sam0_eth_netdev.h` exposes `sam0_eth_netdev_setup`, which is not defined. Instead `sam0_eth_setup` is used, but not exposed. This fixes the issue by changing the exposed setup function.
- Green CI
- Alternatively run a networking example on a board sam0-based board with Ethernet (e.g., `same54-xpro`).
Split from #17739
> cpu/sam0_common/eth: expose correct setup function

- cpu/esp32/Makefile.include
- sys/net/gnrc/netif/init_devs/auto_init_esp_eth.c
This moves the GNRC auto_init of ESP32 ethernet peripheral driver to `init_devs`, where all the other drivers are initialized.
- Test some GNRC-based example while using `esp_eth` module
Split from #17739
> cpu/esp32/esp-eth: move GNRC auto_init to init_devs

- pkg/lvgl/include/lv_conf.h
The default memory size is good for the current test, but depends on created objects, so needs to be customizable.
The test should still work.
> pkg/lvlgl: allow cusomizing LV_MEM_SIZE

- sys/include/net/ipv4/addr.h
The pointers are not written to, so it should be const.
Can be tested with #17763
> sys/net/ipv4: ipv4_addr_t pointer should be const

- sys/include/ztimer.h
- sys/include/ztimer/periodic.h
This introduces a name to the callback types of ztimer_t and ztimer_periodic_t.
This is has no effect in C directly, where the weak typing of macros in ZTIMER_PERIODIC_KEEP_GOING and the unchecked casting of function pointers makes this invisible, but when wrapping things for Rust I have to use matching types (or assert for all perpetuity that the casts are OK, which might make future changes not ring any bells).
This is one of the rare times a change is requested only for the benefit of Rust and with no tangible upsides on C, so please review carefully with that in mind.
A build test should cover all effects of this.
The change of periodic callback return values from int to bool in https://github.com/RIOT-OS/RIOT/pull/17351 triggered this.
More on the topic of types for callbacks in [in …
> sys/ztimer: Name callback types

- doc/doxygen/src/using-rust.md
- examples/rust-gcoap/Cargo.lock
- examples/rust-gcoap/Cargo.toml
- examples/rust-gcoap/Makefile
- examples/rust-gcoap/Makefile.ci
- examples/rust-hello-world/Cargo.lock
- examples/rust-hello-world/Cargo.toml
- tests/rust_minimal/Cargo.lock
- tests/rust_minimal/Cargo.toml
Another round of updates to the Rust examples, with the usual steps of
* updating versions and
* following all the latest riot-wrappers deprecations (so that going through a breaking version will be painless),
with extas of
* increasing the stack size (cherry-picked from #17554 -- turned out some resources' rendering overflew the stack), and
* documenting it's now usable in some cases with stable Rust.
Disabling default-features on two examples sits somewhere between them -- the deprecation note says only that we have to pull in those that were default so far, but it is necessary to make things work on stable unmodified.
* Green CI (which includes tests)
* Optionally, `make all term CARGO_CHANNEL=stable BOARD=microbit-v2 all flash term -C examples/rust-hello-world` (if you have Rust 1.59 …
> {examples,tests}/rust: Rust updates (-sys/-wrappers version, stable)

- sys/net/sock/sock_util.c
Fix compilation when using IPv4 only. `addr.ipv6` is not found otherwise.
Can be tested with #17763
> sys/net/sock_util: fix compilation for IPv4-only mode

- sys/include/net/utils.h
- sys/net/netutils/util.c
- tests/netutils/Makefile
- tests/netutils/main.c
- tests/netutils/mock_dns.c
Add function `netutils_get_ipv4()` to `netutils`.
Existing test in `tests/netutils` was extended.
Can be tested with #17763
> sys/net/netutils: add netutils_get_ipv4()

- pkg/mynewt-core/contrib/sem.c
- pkg/uwb-core/include/dpl/dpl_sem.h
The current implementation could not block forever, this did not really show since it would result in waiting for `UINT32_MAX`, bode makes for a more complete implementation.
Green murdock should be enough.
> pkg/mynewt-core: fix semaphore

- core/include/cib.h
- core/include/msg.h
- core/msg.c
- tests/msg_queue_capacity/Makefile
- tests/msg_queue_capacity/main.c
- tests/msg_queue_capacity/tests/01-run.py
This adds functions to get the message slots still available in a queue as well as its total length from another thread. Using those a GNRC module can gauge how congested the input queue of a module it wants to send to is.
```sh
make -C tests/msg_avail -j flash test
make -C tests/msg_queue_len -j flash test
```
should both pass, `msg_avail` does not increase in size when build with `RIOT_CI_BUILD=1` compared to master (I tested on `nrf52dk`, `z1`, and `arduino-mega2560`).
None
> core: add functionality to check queue state of another thread 

- drivers/Makefile.dep
- drivers/include/lpsxxx.h
- drivers/lpsxxx/Kconfig
- drivers/lpsxxx/Makefile.include
- drivers/lpsxxx/include/lpsxxx_internal.h
- drivers/lpsxxx/include/lpsxxx_params.h
- drivers/lpsxxx/lpsxxx.c
- drivers/lpsxxx/lpsxxx_saul.c
- tests/driver_lpsxxx/README.md
Integrates the LPS22CH as a pseudomodule into the lpsxxx driver.
Integration is seamless as the sensor is nigh identical to the LPS22HH save for the a few details, but from a driver point of view both sensors are identical. 
Flashing a board with the software and then getting console output. A finger was place on the sensor to see if the temperature was increasing(as it should) and air was blown onto the sensor to see if the pressure was increasing. Both worked fine and the results are present below:
-
> driver/lpsxxx: adding lps22ch support

- doc/doxygen/src/using-rust.md
C2Rust has accepted most of the patches in the current for-riot; what's left needs riot-sys fixes anyway on the long run.
* Look at the docs.
For full testing:
* Install C2Rust as documented (replacing any old C2Rust installation)
* Build any of the Rust examples (ideally rust-gcoap as it has the largest coverage) on native and a cortex-m board (and on a RISC-V board if overtaken by #17520)
A sibling PR on riotdocker is https://github.com/RIOT-OS/riotdocker/pull/173.
This is on hold as a draft because it still depends on two things:
[edit: Finish incomplete sentence, cross-link to sibling PR; turned into bulled list after first blocker is resolved].
> doc: C2Rust does not need patching any more.

- sys/bitfield/bitfield.c
- sys/include/bitfield.h
- tests/unittests/tests-bitfield/tests-bitfield.c
This adds support for bit-wise (AND, OR, XOR, NOT) operations to bitfields.
The `tests-bitfield` unit test has been extended with the new operations.
> sys/bitfield: add support for bit-wise bitfield operations

- pkg/edhoc-c/Makefile
This rebases to latest master, it also includes a patch to allow
generating credentials when using tinycrypt as the crypto backend
as well as patch conn_id generaiton.
```
src/crypto/tinycrypt: add crypto_gen_keypair
src/process: use random for conn_id generation
```
Follow the README
```
NETOPT_RX_END_IRQ not implemented by driver
main(): This is RIOT! (Version: 2022.04-devel-670-gc5860-pr_edhoc_c_bump)
[initiator]: load ephemeral key: ONLY FOR TESTING
[initiator]: preset cid: ONLY FOR TESTING
[responder]: load ephemeral key: ONLY FOR TESTING
[responder]: preset cid: ONLY FOR TESTING
Starting the shell
>
>
> ifconfig
ifconfig
Iface  5  HWaddr: 0E:0D:B4:B7:C5:92 …
```
> pkg/edhoc-c: bump version

- sys/Makefile.dep
- sys/auto_init/auto_init.c
- sys/include/net/sock/dns.h
- sys/net/application_layer/sock_dns/dns.c
This PR adds the pseudomodule `auto_init_sock_dns` to `sock_dns` such that the DNS server can be set automatically.
You can test this by adding `USEMODULE += auto_init_sock_dns` to the makefile of `tests/gnrc_sock_dns`. When running the program with a terminal and execute `dns server` it will immediatly return `DNS server: [2001:4860:4860::8888]:53` showing that a DNS server is alredy set up automatically.
> sys/net/application_layer/sock_dns: add pseudomodule auto_init_sock_dns

- drivers/sht3x/Kconfig
- drivers/sht3x/Makefile.dep
- drivers/sht3x/sht3x.c
- tests/driver_sht3x/main.c
The PR contains the changes to use `ztimer_msec` instead of `xtimer`.
`tests/driver_sht3x` should still work.
> drivers/sht3x: ztimer_msec port

- sys/net/gnrc/Makefile.dep
`gnrc_sock` requires `iolist` since #17485.
Looks like that got pulled in by other modules for GNRC so far.
Discovered when doing
make -C examples/gnrc_border_router BOARD=esp32-wroom-32 UPLINK=wifi
```
/home/benpicco/dev/RIOT/examples/gnrc_border_router/bin/esp32-wroom-32/gnrc_sock_udp/gnrc_sock_udp.o: In function `sock_udp_recv_aux':
/home/benpicco/dev/RIOT/sys/net/gnrc/sock/udp/gnrc_sock_udp.c:187: undefined reference to `iolist_size'
/home/benpicco/dev/RIOT/examples/gnrc_border_router/bin/esp32-wroom-32/gnrc_sock_udp/gnrc_sock_udp.o: In function `sock_udp_sendv_aux':
/home/benpicco/dev/RIOT/sys/net/gnrc/sock/udp/gnrc_sock_udp.c:346: undefined reference to `iolist_size'
collect2: error: ld returned 1 exit status
make: *** [/home/benpicco/dev/RIOT/examples/gnrc_border_router/../../Makefi …
```
> net/gnrc_sock: depend on iolist

- Makefile.include
- dist/tools/usb-serial/ttys.py
- doc/doxygen/src/advanced-build-system-tricks.md
- makefiles/tools/serial.inc.mk
This provides `dist/tools/usb-serial/ttys.py` to list and filter TTY interfaces. I just give some example invocations to show the features:
```
$ ./dist/tools/usb-serial/ttys.py 
path         | driver  | vendor              | model                                | model_db                                                      | serial                   | ctime   
-------------|---------|---------------------|--------------------------------------|---------------------------------------------------------------|--------------------------|---------
/dev/ttyUSB0 | cp210x  | Silicon Labs        | CP2102 USB to UART Bridge Controller | CP210x UART Bridge                                            | 0001                     | 12:41:35
/dev/ttyACM1 | cdc_acm | STMicroelectronics  | STM32 STLink …
```
> dist/tools/usb_serial: Add tool for listing and filtering TTY interfaces

- makefiles/deprecated_modules.inc.mk
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/sema.h
- sys/posix/pthread/pthread_cond.c
- sys/posix/pthread/pthread_rwlock.c
- sys/posix/select/posix_select.c
- sys/posix/semaphore/posix_semaphore.c
- sys/sema/Kconfig
- sys/sema/sema.c
- tests/posix_semaphore/Makefile
- tests/posix_semaphore/main.c
- tests/sema/Makefile
This PR takes for `sema` a similar approach to `event_timeout`. The module is switched to `ztimer` removing the `xtimer` based implementation.
To keep compatibility the old api (using 64bit timeouts) is kept if selecting `sema` module, which uses `ztimer64`, but this module is marked now as deprecated.
This PR also migrates posix to use `ztimer64` and in therefore gives a user for `sema_ztimer64` by using it to implement `posix_sempahore`
> sys/sema: add sema_ztimer64 to implement old api, deprecate sema

- drivers/mrf24j40/Makefile.dep
- drivers/mrf24j40/Makefile.include
CFLAGS should be added in `Makefile.include`s. For mrf24j40 it was being done in `Makefile.dep`, so this corrects it.
- Green CI
- Check that the external PA CFLAG is set when not using `mrf24j40ma` but other variant
Split from #17789
> drivers/mrf24j40: move CFLAG to Makefile.include

- cpu/samd21/include/periph_cpu.h
- cpu/saml1x/include/periph_cpu.h
PM_BLOCKER_INITIAL cannot overridden on samd21 and saml21 boards. This PR changes that.
Green Murdock
Needed by #11237 where the PM_BLOCKER_INITIAL value is already set at application level (with no effect on samd21/saml21).
> cpu/samx21: allow to override PM_BLOCKER_INITIAL

- drivers/sdcard_spi/include/sdcard_spi_internal.h
Include `board.h` so we can overwrite `SD_CARD_SPI_SPEED_POSTINIT` there.
> drivers/sdcard_spi: allow board to overwrite SD_CARD_SPI_SPEED_POSTINIT

- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/net/gcoap/forward_proxy.h
- sys/include/net/nanocoap.h
- sys/net/application_layer/gcoap/Makefile
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/gcoap/gcoap.c
This PR adds a simple [forward-proxy](https://tools.ietf.org/html/rfc7252#section-5.7.2) to gcoap.
See https://github.com/RIOT-OS/RIOT/pull/13637 for related info.
A forward proxy parses a `Proxy-Uri` option of incoming requests and constructs a new request with the proper `Uri-Path` and `Uri-Query` options. This newly created request is then sent to an endpoint that is specified in the `Proxy-Uri` option of the initial request.
The second method using the `Proxy-Scheme` [option](https://tools.ietf.org/html/rfc7252#section-5.10.2) is not implemented.
Currently, gcoap does not support standalone acknowledgements. Therefore, the forward proxy is not able to stop the retransmissions on the client side. Hence, the client and the proxy will both do retransmissions for confirmable requests. I …
> gcoap: add simple forward-proxy

- pkg/fatfs/vendor/include/ffconf.h
- sys/include/vfs.h
Enabling exFAT requires enabling long file names, so enable LFN if exFAT is enabled.
exFAT (and LFN) also requires bumping the per-file/per-dir buffer.
Can be tested with
CFLAGS += -DFATFS_FFCONF_OPT_FS_EXFAT=1
```
2022-03-11 13:25:24,438 - INFO # > ls /
2022-03-11 13:25:24,438 - INFO # 
2022-03-11 13:25:24,441 - INFO # System Volume Information
2022-03-11 13:25:24,441 - INFO # test
2022-03-11 13:25:24,443 - INFO # hello.txt	19 B
2022-03-11 13:25:24,444 - INFO # total 1 files
2022-03-11 13:25:28,907 - INFO # > vfs r /hello.txt 32
2022-03-11 13:25:28,908 - INFO # 
2022-03-11 13:25:28,915 - INFO # 00000000: 4865 6c6c 6f20 6672 6f6d 2057 696e 646f  Hello from Windo
2022-03-11 13:25:28,920 - INFO # 00000010: 7773 21                                  ws!
2022-03-11 13:25:28,921 - INFO # -- EOF …
```
> pkg/fatfs: enable exFAT support

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- tests/rust_minimal/Cargo.lock
These updates enable tests on beta (stable for the 2022.04 release) on
all platforms, and open the way for [17804].
[17804]: https://github.com/RIOT-OS/RIOT/pull/17804
* green CI
> {examples,tests}/rust: Rust updates

- boards/adafruit-pybadge/Kconfig
- boards/adafruit-pybadge/Makefile
- boards/adafruit-pybadge/Makefile.dep
- boards/adafruit-pybadge/Makefile.features
- boards/adafruit-pybadge/Makefile.include
- boards/adafruit-pybadge/board.c
- boards/adafruit-pybadge/doc.txt
- boards/adafruit-pybadge/include/board.h
- boards/adafruit-pybadge/include/gpio_params.h
- boards/adafruit-pybadge/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
This PR adds support for the [Adafruit PyBadge](https://www.adafruit.com/product/4200) board(s). The board support should also work for PyBadge LC (this one has only one NeoPixel instead of 5) and EdgeBadge (this one provides a microphone) variants.
They are very similar to the Itsybitsy (SAMD51, same QSPI nor flash, etc) but don't use the same MCU variant (samd51j19a instead of samd51**g**19a) and have some small configuration difference.
The current port provides definitions for the Neopixel LEDs, the TFT backlight and TFT screen although they are not really supported:
- the Neopixel requires WS281X driver but no compatible backend is available
- the TFT display is a ST7735 so requires #16176 (and I tried with it but didn't succeed)
Other things that are missing:
- there's an LIS3DH …
> boards/adafruit-pybadge: add support

- drivers/at86rf215/at86rf215.c
The macro name is `CONFIG_AT86RF215_RPC_EN`, not `CONFIG_AT86RF215_RPC` .
> drivers/at86rf215: fix CONFIG_AT86RF215_RPC_EN macro name

- makefiles/docker.inc.mk
This PR reverts part of #17396 for issues mentioned in https://github.com/RIOT-OS/RIOT/issues/17770. `CFLAGS` will often hold characters that need escaping when passing to docker which makes it harder to generalize.
The following fails in master and passes now:
```
BUILD_IN_DOCKER=1 make -C tests/progress_bar/ clean all -j
```
#17396
> makefiles/docker.ink.mk: do not always pass CFLAGS to docker

- sys/fido2/ctap/ctap_cbor.c
The tinyCBOR version bump in #17604 uncovered an error while initializing the CBOR parser for CTAP requests, causing a hard fault in current master. The flag that was used should be used during calls to `cbor_value_validate` to perform the actual validation. This PR fixes the initialization and adds the validation.
- Test `tests/sys_fido2_ctap`
#17604
> sys/fido2/ctap: fix parsing validation

- dist/tools/pr_check/check.sh
When one accepts a suggestion in a review, Github by default creates commits with a message that starts with `Update`. This PR adds a rule to make the needs squashing check to fail in this case.
With auto-merge enabled, some already ACKed PR could go in if a contributor accepts a suggestion afterwards and Murdock hasn't completed yet for example.  This PR should mitigate this.
There an empty commit that should make the check to fail. I'll remove it before merging.
Noticed that issue in #10082
> tools/pr_check: add "Update" keywork to "needs squashing" check

- cpu/efm32/periph/Kconfig
- cpu/qn908x/periph/Kconfig
- drivers/ccs811/Kconfig
- makefiles/boards/ztimer_only.dep.mk
- makefiles/default_modules.deps.mk
- makefiles/pseudomodules.inc.mk
- pkg/u8g2/Kconfig
- pkg/ucglib/Kconfig
- sys/Makefile.dep
- sys/shell/commands/sc_gnrc_udp.c
- sys/trace/Kconfig
- sys/xtimer/Kconfig
- sys/xtimer/Makefile.dep
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
- tests/xtimer_now32_overflow/Makefile
- tests/xtimer_now32_overflow/app.config.test
- tests/xtimer_now64_continuity/Makefile
- tests/xtimer_now64_continuity/app.config.test
Although I prefer how it's done in #17809, I realize I'm changing a lot of things when the initial objective was only to have an easy-to-switch backend default for `xtimer`, so let's do it simple, even if it keeps all the indirections...
Note this PR also changes the default prefered `xtimer` backend to `ztimer_on_xtimer`, that can also be an individual PR.
~~Marking as WIP will I let Murdock check I didn't make a fundamentally wrong change.~~
#17721
> sys/*timer: rework dependecies to ease backend switch, prefer ztimer_xtimer_compat over xtimer_on_ztimer

- boards/nucleo-f429zi/Kconfig
- boards/nucleo-f429zi/Makefile.dep
- boards/nucleo-f429zi/Makefile.features
- boards/nucleo-f429zi/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
- tests/Makefile.boards.netif
As the title says. With #17827 which is very similar, I saw that the Ethernet configuration was missing for this board.
The Ethernet interface pops up in ifconfig when flashing `examples/default`:
<details>
```
2022-03-18 16:10:12,993 # NETOPT_RX_END_IRQ not implemented by driver
2022-03-18 16:10:12,996 # main(): This is RIOT! (Version: 2022.04-devel-893-g1de68-pr/boards/nucleo-f429zi-eth)
2022-03-18 16:10:12,996 # Welcome to RIOT!
> 2022-03-18 16:10:13,911 # PKTDUMP: data received:
2022-03-18 16:10:13,912 # ~~ SNIP  0 - size:  96 byte, type: NETTYPE_UNDEF (0)
2022-03-18 16:10:13,923 # 00000000  60  00  00  00  00  38  00  01  FE  80  00  00  00  00  00  00
2022-03-18 16:10:13,929 # 00000010  DE  82  33  B9  9A  73  C6  90  FF  02  00  00  00  00  00  00
2022-03-18 16:10:13,935 # 00000020 …
```
> boards/nucleo-f429zi: add support for ethernet

- core/Kconfig
#17652 split the library code in core, adding the new symbol `MODULE_CORE_LIB`. As it was placed directly after `MODULE_CORE` the rest of modules, although still depending on `MODULE_CORE`, are not displayed as a submenu. This moves the symbol down (which has no effects on the dependencies), but groups all core options again.
- In any application run `env TEST_KCONFIG=1 make menuconfig`, you should see all core modules inside the `RIOT Core` menu, in master they are in a flatten layout.
#17652
> core/Kconfig: move MODULE_CORE_LIB symbol to fix menuconfig display

- doc/doxygen/riot.doxyfile
- doc/doxygen/src/build-in-docker.md
- doc/doxygen/src/getting-started.md
- doc/doxygen/src/mainpage.md
How to correctly pass variables to DOCKER is missing some doc, so this adds some more doc on `BUILD_IN_DOCKER`
Check the doc.
#17770
> doc/doxygen: add BUILD_IN_DOCKER extended doc

- boards/nucleo-f439zi/Kconfig
- boards/nucleo-f439zi/Makefile
- boards/nucleo-f439zi/Makefile.dep
- boards/nucleo-f439zi/Makefile.features
- boards/nucleo-f439zi/Makefile.include
- boards/nucleo-f439zi/doc.txt
- boards/nucleo-f439zi/include/periph_conf.h
- cpu/stm32/kconfigs/f4/Kconfig.lines
- dist/tools/doccheck/exclude_patterns
- tests/Makefile.boards.netif
This PR adds support for another STM32 nucleo board, the nucleo-f439zi which is very similar to the nucleo-f429zi. It's also interesting because it provides an Ethernet port.
- I tested all features provided except SPI, but according to the datasheet and board documentation the provided configuration is ok
- I ran compile_and_test_for_board.py and got the following result:
```
ERROR:nucleo-f439zi:Tests failed: 2
Failures during compilation:
- [tests/rust_minimal](tests/rust_minimal/compilation.failed)
Failures during test:
- [tests/malloc](tests/malloc/test.failed)
```
I don't understand the malloc failure but I get the same error on nucleo-f429zi. Maybe it's also related to #17439 because the error seems similar:
```
Allocated 128 Bytes at 0x0x2002fd70, total 170944
Allocated 128 Bytes …
```
> boards: add support for nucleo-f439zi

- tests/thread_float/Makefile
- tests/thread_float/main.c
If using `ztimer_xtimer_compat` then `XTIMER_BACKOFF` is meaningless, the small offset leads to an offset that is
shorter than the time taken to set the timer, and therefore it gets stuck in a timer firing loop. Instead, directly use `ztimer_usec` with a 100usec base offset.
```
BOARD=samr21-xpro RYOT_CI=1 make -C tests/thread_float/ flash test -j7
main(): This is RIOT! (Version: 2022.04-devel-904-g0e462-pr_tests_thread_float_ztimer)
THREADS CREATED
THREAD t1 start
THREAD t2 start
THREAD t3 start
t1: 141.443787
t3: 141.466812
t1: 141.443787
t3: 141.466812
t1: 141.443787
t3: 141.466812
t1: 141.443787
t3: 141.466812
t1: 141.443787
t3: 141.466812
t1: 141.443787
t3: 141.466812
```
Found in #17721
> tests/thread_float: use ztimer_usec

- pkg/uwb-dw1000/patches/0001-uwb_dw1000-include-dw1000-dw1000_dev-add-linked-list.patch
- pkg/uwb-dw1000/patches/0002-uwb_dw1000-dw1000_hal-send-spi-cmd-and-data-separetl.patch
- pkg/uwb-dw1000/patches/0003-uwb_dw1000-dw1000_hal-define-even-if-DW1000_DEVICE_0.patch
- pkg/uwb-dw1000/patches/0004-uwb_dw1000-dw1000_hal-os_sr_t-by-dpl_sr_t.patch
- pkg/uwb-dw1000/patches/0005-dw1000-dw1000_dev-use-gpio_t-types-for-dev_cfg.patch
- pkg/uwb-dw1000/patches/0006-hw-drivers-uwb_dw100-update-RF_TXCTRL-value-for-chan.patch
This PR adds a patch for https://github.com/Decawave/uwb-dw1000/issues/2, if this is merged upstream I'll remove the patch.
Just checking the reference manual value is enough, see Table 38: Sub-Register 0x28:0C– RF_TXCTRL values in https://www.decawave.com/sites/default/files/resources/dw1000_user_manual_2.11.pdf
https://github.com/Decawave/uwb-dw1000/issues/2
PR fixing issue: https://github.com/Decawave/uwb-dw1000/pull/4
> pkg/uwb-dw1000: add patch for rf_txctrl value

- boards/arduino-mega2560/include/board.h
- boards/z1/include/board.h
- dist/tools/doccheck/exclude_patterns
This fixes the values.
Simply run `tests/ztimer_overhead`
```
BUILD_IN_DOCKER=1  BOARD=z1 make -C tests/ztimer_overhead/ flash test -j
main(): This is RIOT! (Version: 2022.04-devel-905-g6ce15-pr_ztimer_adjust_correcitons)
ZTIMER_USEC auto_adjust params:
ZTIMER_USEC->adjust_set = 99
ZTIMER_USEC->adjust_sleep = 100
ZTIMER_USEC auto_adjust params cleared
zitmer_overhead_set...
min=99 max=100 avg_diff=99
zitmer_overhead_sleep...
min=100 max=101 avg_diff=100
ZTIMER_USEC adjust params for z1:
CONFIG_ZTIMER_USEC_ADJUST_SET    99
CONFIG_ZTIMER_USEC_ADJUST_SLEEP  100
```
```
BUILD_IN_DOCKER=1  BOARD=arduino-mega2560 make -C tests/ztimer_overhead/ flash test -j
main(): This is RIOT! (Version: 2022.04-devel-905-g6ce15-pr_ztimer_adjust_correcitons)
ZTIMER_USEC auto_adjust params: …
```
> boards: fix ztimer adjust values for arduino-mega2560 and z1

- examples/lorawan/Makefile
- examples/lorawan/README.md
- examples/lorawan/main.c
~**don't merge this PR**: it is RFC and contains broken things~
~~This PR splits the lorawan examples in 2 distinct applications:~~
~~one showing the OTAA join procedure (as before)~~
~~one showing the ABP join procudure~~
This PR adds the possibility to use ABP activation procedure to the existing application.
This PR also enables the low-power modes "manually". 2 different strategies are used depending on the activation procedure:
- OTAA: use STOP mode (well I'm targetting STM32 here) because it provides RAM retention while sleeping, keeping the loramac state when waking up.
- ABP: use STANDBY mode + EEPROM storage. This allows very low power consumption + no need for RAM retention since session keys and device address are already known.
With OTAA + STOP mode, I was expecting an issue …
> examples/lorawan: add the possibility to use ABP activation procedure

- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
The ieee802.15.4 info structure was never modified by the `confirm_op` radio operation. This fixes it.
- Run some networking application on a board with the nrf52 radio.
None
> cpu/nrf52/radio: fix confirm_op info cast

- doc/doxygen/src/porting-boards.md
Add doc to porting boards.
Read the doc.
#17111
> doc/doxygen: recommend adding ADJUST ztimer values for new boards

- sys/net/gnrc/sock/gnrc_sock.c
Split as from #17836 as requested in https://github.com/RIOT-OS/RIOT/pull/17836#issuecomment-1076313870.
Sure with `ztimer_usec` being no the default I could have just removed `xtimer`, but this works as well, and I already did it, so its less work to keep as is. 
- murdock should be enough
- local tests `for app in tests/gnrc_sock_udp tests/gnrc_sock_ip; do USEMODULE=ztimer_usec RIOT_CI_BUILD=1 make -C ${app} flash test test-as-root -j; done`
```
Building application "tests_gnrc_sock_udp" for "native" with MCU "native".
129899	    756	  67848	 198503	  30767	/home/francisco/workspace/RIOT/tests/gnrc_sock_udp/bin/native/tests_gnrc_sock_udp.elf
r
/home/francisco/workspace/RIOT/tests/gnrc_sock_udp/bin/native/tests_gnrc_sock_udp.elf /dev/ttyACM0 …
```
> sys/net/gnrc/sock: use ztimer_usec or xtimer for timeout

- cpu/native/Kconfig
- cpu/native/Makefile.dep
- cpu/native/syscalls.c
- makefiles/pseudomodules.inc.mk
- pkg/lua/Makefile.dep
- pkg/tinydtls/Makefile.dep
- pkg/wolfssl/Makefile.dep
- sys/Kconfig
- sys/Kconfig.newlib
- sys/Makefile.dep
- sys/newlib_syscalls_default/syscalls.c
- tests/cpp11_mutex/Makefile
A follow-up to #17732  to not force 64bit on all syscalls users.
With this PR the users of ztimer64 should be limited to:
Revisited list of apps using `ztimer64`:
`for app in examples/* tests/*; do make -C ${app} info-modules | if grep -q ztimer64; then echo ${app};fi;done`
```
examples/ccn-lite-relay
examples/cord_ep
examples/cord_lc
examples/dtls-echo
examples/dtls-sock
examples/dtls-wolfssl
examples/gcoap_dtls
examples/gnrc_networking_mac
examples/lua_basic
examples/lua_REPL
examples/openthread
examples/posix_select
examples/wasm
tests/cpp11_condition_variable
tests/cpp11_mutex
tests/cpp11_thread
tests/driver_ltc4150
tests/driver_pir
tests/gnrc_gomach
tests/lua_loader
tests/nimble_autoconn_ccnl
tests/pkg_arduino_sdi_12
tests/pkg_flatbuffers
tests/pkg_tensorflow-lite …
```
> sys/syscalls: make gettimeofday() implementation optional

- boards/pba-d-01-kw2x/board.c
Fixes the execution order of clock init steps.
#16055 moved all cpu_init() calls from board_init() to startup code which changed the execution order of clock init code for this board. The cpu_init() implementation and config of this board assumes that CLK_OUT of the radio drives the MCU PTA18/EXTAL0 pin at 4 MHz, which are setup by modem_clock_init(). However, on master the modem clock init happens after cpu_init(), wich potentially locks up the MCU.
Confirm that the order was swapped before [diff](https://github.com/RIOT-OS/RIOT/pull/16055/commits/fc88c4c4e5b9c03403b9284534babbc965974deb#diff-5bcd5d3402646b3c5072df4840062c20ed5e6f5cfdd14926a560a3eabc092132) + [diff](https://github.com/RIOT-OS/RIOT/pull/16055/commits/bcb0df8e18837d2ce71b106cbbc2415b533a2ad5)
`BOARD=pba-d-01-kw2x make -C …
> pba-d-01-kw2x: fix clock init by preceding cpu_init with modem clock init

- sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c
The condition to check the length of an 6LoWPAN-ND Context Option was wrong.
If the prefix length > 64 it must be 3 (MAX), if it is less or equal 64 it must be 2 (MIN).
RFC6775 section 4.2
See https://github.com/RIOT-OS/RIOT/pull/17803#issuecomment-1074031270.
At least `nib: received 6CO of invalid length (3), must be 3 or wasn't delivered by RA.` does not show up anymore.
> ipv6/nib: bugfix of 6CO length checking

- examples/dtls-echo/dtls-client.c
- examples/dtls-echo/dtls-server.c
- pkg/tinydtls/contrib/sock_dtls.c
- pkg/tinydtls/patches/0002-session.h-Modify-session_t-for-RIOT.patch
The size field in the session_t structure should reflect the size of the addr field for the particular OS. This was producing random errors when calculating the client_hello cookie, because the address is part of the hash, and the length used to update the `sha256_update` function was set to 18.
- `dtls_sock` application should work reliably. 
None
> pkg/tinydtls/contrib/sock_dtls: fix ep_to_session

- drivers/include/mtd_flashpage.h
- sys/fido2/ctap/ctap_mem.c
- tests/mtd_flashpage/main.c
This introduces a `mtd_flashpage_t` to make mtd_flashpage behave more like other MTD implementations.
The generated code of `tests/sys_fido2_ctap` does not change.
> drivers/mtd_flashpage: add mtd_flashpage_t type

- drivers/atwinc15x0/atwinc15x0_netdev.c
- drivers/include/atwinc15x0.h
This allows the interface to enter SLEEP state in which it only consumes 4µA.
As with some other drivers the STANDBY state was used to model automatic wake on send. 
Tested with `tests/driver_atwinc15x0`:
```
main(): This is RIOT! (Version: 2022.04-devel-934-g6be6c-drivers/atwinc15x0-sleep)
> [atwinc15x0] WiFi connected
PKTDUMP: data received:
~~ SNIP  0 - size:  42 byte, type: NETTYPE_UNDEF (0)
00000000  00  00  F5  81  80  00  00  06  00  00  00  00  00  00  00  00
00000010  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00  00
00000020  00  00  00  00  00  00  00  00  00  00
~~ SNIP  1 - size:  20 byte, type: NETTYPE_NETIF (-1)
if_pid: 3  rssi: -32768  lqi: 0
flags: 0x0
src_l2addr: 98:D8:63:7B:D3:70
dst_l2addr: F8:F0:05:A9:EB:F0
~~ PKT    -  2 snips, total size:  62 byte
> …
```
> drivers/atwinc15x0: enable sleep state

- pkg/fatfs/fatfs_vfs/fatfs_vfs.c
- tests/pkg_fatfs_vfs/Makefile
If `fatfs_vfs_format` is built with `CONFIG_FATFS_FORMAT_ALLOC_STATIC=1`, mutex headers are missing.
Compile `tests/pkg_fatfs_vfs`.
> pkg/fatfs: fix missing mutex header

- examples/dtls-echo/dtls-client.c
- examples/dtls-echo/dtls-server.c
- pkg/tinydtls/Makefile.include
- pkg/tinydtls/contrib/sock_dtls.c
- pkg/tinydtls/patches/0003-session-Rename-condition-WITH_RIOT_GNRC-to-WITH_RIOT.patch
- pkg/tinydtls/patches/0004-session-Add-support-for-IPv4-on-RIOT-OS.patch
Add IPv4 support to `pkg/tinydtls`.
This PR contains two patches which I will try to get merged in the upstream repository once this PR is merged.
Can be tested with #17763
Dependencies:
- #17762
> pkg/tinydtls: add IPv4 support

- drivers/mtd_mapper/mtd_mapper.c
- tests/mtd_mapper/Makefile
- tests/mtd_mapper/app.config.test
- tests/mtd_mapper/main.c
This PR fixes the `mtd_mapper` backend for `read_page` and `write_page`.
The implementation uses `mtd_read_page()` and `mtd_write_page_raw()` on the backing device. These methods return `0` on successful [read](https://github.com/RIOT-OS/RIOT/blob/753b435cb50543a68b43354773c4ff0603ab9f58/drivers/include/mtd.h#L305) resp. [write](https://github.com/RIOT-OS/RIOT/blob/753b435cb50543a68b43354773c4ff0603ab9f58/drivers/include/mtd.h#L353). But the backend is expected to return the amount of [read](https://github.com/RIOT-OS/RIOT/blob/753b435cb50543a68b43354773c4ff0603ab9f58/drivers/include/mtd.h#L166) resp. [written](https://github.com/RIOT-OS/RIOT/blob/753b435cb50543a68b43354773c4ff0603ab9f58/drivers/include/mtd.h#L206) bytes.
Run `tests/mtd_mapper`. I've added a test triggering this bug. …
> drivers/mtd_mapper: fix read_page and write_page backend

- sys/net/gnrc/netif/gnrc_netif.c
While it appears to be okay, UBSAN actually catches this as a potential NULL pointer dereference.
Compile and run `gnrc_networking` with `all-ubsan`:
```sh
UBSAN_MODE=msg_recover make -C examples/gnrc_networking all-ubsan -j
make -C examples/gnrc_networking term
```
In current `master`, UBSAN will complain: `sys/net/gnrc/netif/gnrc_netif.c:142:23: runtime error: member access within null pointer of type 'const struct gnrc_netif_t'`, with this fix it will not.
None
> gnrc_netif: fix potential null pointer dereference

- drivers/mtd_spi_nor/mtd_spi_nor.c
Lower bits of the device ID are not the capacity in bytes but in sectors:
4 - 4 Mb -> 32k << 4
5 - 8 Mb -> 32k << 5
…
split off #17692
> drivers/mtd_spi_nor: fix Atmel size calculation

- boards/nucleo-f429zi/doc.txt
Improvements to STM Nucleo f429zi documentation:
- Add board image,
- Add MCU table - similar to those, for example for, Nucleo F103RB, F302R8 or F446RE,
- Add information concerning accessing RIOT shell (see Issue #17453) 
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f429zi.html
```
Issue #17453
> boards/nucleo-f429zi: improvements to documentation

- sys/net/gnrc/sock/gnrc_sock.c
- sys/ztimer/util.c
While digging around for my TinyDTLS issue reported in https://github.com/RIOT-OS/RIOT/pull/17849, I did some valgrind probes with `gcoap_dtls` and noticed some missing initializations of timers. This PR fixes those.
Compile `examples/gcoap_dtls` with valgrind support (for `native`) and start a shell with valgrind support:
```
make -C examples/gcoap_dtls -j all-valgrind
make -C examples/gcoap_dtls term-valgrind
```
open another shell
```
PORT=tap1 make -C examples/gcoap_dtls term-valgrind
```
and send a coap request using the `coap` command. With this PR, valgrind will remain mostly silent, while in current master it will complain about several "`Conditional jump or move depends on uninitialised value(s)`"
e.g.:
```
==76316==    at 0x806F620: …
```
> treewide: initialize several stack-allocated, but uninitialized timer structs

- drivers/mtd_spi_nor/mtd_spi_nor.c
In #17721 I realized some code depends on or uses `XTIMER_BACKOFF` and that this behavior is not directly translated to `ztimer_usec` wrappers. This PR uses `ztimer_usec` as an alternative for `driver_mtd_spi_nor`
Green Murdock should be enough.
Sparked from #17721
> drivers/mtd_spi_nor: add ztimer_usec alternative 

- dist/tools/goodfet/goodfet.bsl
- makefiles/tools/serial.inc.mk
- tests/shell/Makefile
- tests/shell_ble/Makefile
For some reason `z1` does not work with socat, all tests forcing socat ar bound to fail on `z1`.
A run of tests in master: https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/lastSuccessfulBuild/artifact/ all fail without event starting the terminal, a run of tests with this commi https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/327/artifact/z1/tests/, `congure` still is failing a couple of tests as well as `pkdf2` but not for the same reasons.
First time this issue was reported https://github.com/RIOT-OS/RIOT/pull/14658
> makefiles: socat set tty mode 8N1 

- sys/net/gnrc/network_layer/ipv6/nib/nib_pl.c
When manually adding a global address with `gnrc_netif_ipv6_addr_add()` or `ifconfig add` it would be advertised as a /128 prefix in router advertisements.
This causes the receiving node to take that address, only to discard it via DAD - the second, real prefix is ignored.
The interface on the upstream router has `fd11::/16` and `fdea:dbee:f::10` configured on it's interface:
```
2022-03-12 15:49:15,050 - INFO # Iface  7 
2022-03-12 15:49:15,053 - INFO #           Long HWaddr: EE:FA:C6:85:D7:AF:25:E2 
2022-03-12 15:49:15,057 - INFO #           MTU:65535  HL:64  RTR  
2022-03-12 15:49:15,058 - INFO #           RTR_ADV  
2022-03-12 15:49:15,061 - INFO #           Link type: wired
2022-03-12 15:49:15,066 - INFO #           inet6 addr: fe80::ecfa:c685:d7af:25e2  scope: link  VAL
2022-03-12 …
```
> gnrc/nib: don't advertise single address for auto-configuration

- examples/asymcute_mqttsn/main.c
- examples/cord_epsim/main.c
- examples/cord_lc/cord_lc_cli.c
- sys/net/application_layer/nanocoap/sock.c
- sys/net/sock/sock_util.c
- sys/shell/commands/sc_cord_ep.c
- tests/emcute/main.c
- tests/lwip/tcp.c
- tests/lwip/udp.c
The `sock_tl_name2ep()` class of functions behave exactly as `sock_tl_str2ep()` except for when the `sock_dns` module is enabled.
In this case they will also be able to resolve a name via DNS in addition to parsing raw IP addresses.
This enables e.g. to fetch SUIT updates using a domain name instead of a hard coded IP address or supplying domain names in interactive tests.
No functional changes unless `sock_dns` is used. 
follow-up to #17510
> treewide: use sock_tl_name2ep() class of functions where applicable

- boards/common/weact-f4x1cx/Makefile.dep
- boards/common/weact-f4x1cx/board.c
- boards/iotlab-m3/Makefile.dep
- boards/iotlab-m3/mtd.c
- boards/mcb2388/Makefile.dep
- boards/mcb2388/board_init.c
- boards/msba2/Makefile.dep
- boards/msba2/board_init.c
- boards/native/board_init.c
- boards/nrf52840dk/Makefile.dep
- boards/nrf52840dk/mtd.c
- boards/same54-xpro/board.c
- sys/include/vfs_default.h
- tests/vfs_default/Makefile
- tests/vfs_default/Makefile.ci
- tests/vfs_default/main.c
This adds a compile-test application `tests/vfs_default` as well as more default mount configurations for existing boards.
Run the new `tests/vfs_default` application. 
```
main(): This is RIOT! (Version: 2022.04-devel-500-g74115-vfs_default-test)
mount points:
/nvm0
data dir: /nvm0
```
> vfs_default: add compile test and add default mount for more boards

- sys/net/application_layer/dhcpv6/client.c
- sys/net/gnrc/application_layer/dhcpv6/client_simple_pd.c
If `dhcpv6_client_ia_na` is enabled, `gnrc_dhcpv6_client_simple_pd ` should also attempt to get an address for the upstream interface via DHCPv6. The module only makes sense when router advertisements/SLAAC is disabled in the router.
The DHCP client should also not reject a response if no downstream interfaces are configured for IA_PD but the module is enabled - they might simple not be initialized yet.
The DHCP server in the TP-Link WR400 sends a response that ends with option 0 (Reserved), which has a bogus length of 4 when the remaining length is 3, which would cause an underflow.
To fix getting a DHCP configuration from that router, consider option 0 end and marker.
I used the following modules: `gnrc_dhcpv6_client_simple_pd dhcpv6_client_ia_na sock_dns atwinc15x0`
```
main(): This is …
```
> sys/net/dhcpv6: miscellaneous tweaks 

- boards/b-l475e-iot01a/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
This PR adds support for the missing SPI2 and SPI3 buses on the b-l4753-iot0a1 board.
SPI2 is exposed on the PMOD connector, SPI3 is used internally to communicate with the radio modules onboard
SPI3 was tested by interfacing with the bluetooth module with the following code:
```c
#include "clk.h"
#include "board.h"
#include "periph_conf.h"
#include "timex.h"
#include "xtimer.h"
#include "periph/gpio.h"
#include "periph/spi.h"
#include "fmt.h"
spi_t spi = SPI_DEV(2);
gpio_t cs = GPIO_PIN(PORT_D, 13);
gpio_t rst = GPIO_PIN(PORT_A, 8);
gpio_t ble_int = GPIO_PIN(PORT_E, 6);
uint8_t txbuf[256];
uint8_t rxbuf[256];
char hexbuf[256];
void ble_int_cb(void *arg) {
(void)arg;
puts("Interrupt called");
}
bool ble_data_present(void) {
return gpio_read(ble_int) != 0;
}
void …
```
> boards/b-l475e-iot01a: Add SPI2 and SPI3 buses

- sys/test_utils/print_stack_usage/print_stack_usage.c
- tests/pthread_flood/Makefile
#17706 introduced printing of stack metrics. But, it printed them in the exiting thread, causing stack overflows due to `printf()`, for very small stacks.
This PR fixes the issue two-fold:
1. `print_str()` is used, if `fmt` is linked in.
2. the actual stack size is checked, and nothing is printed if the stack is too small
> sys/test_utils/print_stack_usage: work with small stacks

- drivers/include/periph/flashpage.h
The functions `flashpage_first_free` and `flashpage_last_free` added with #16972 were introduced to avoid overwriting and therefore corrupting firmware / bootloaders when writing to flash memory. These functions have the flaw that if multiple modules simultaneously use them they will not be aware of each other. E.g. `flashpage_first_free` will return the same value for all modules and can therefore lead to the modules corrupting each others data by writing to the same flashpage.
With #17436 being merged a new and better mechanism has been introduced that achieves the same goal as #16972 but without the flaws. It enables the reservation of flash memory at compile time and ensures that no data is corrupted. Furthermore multiple modules can use this mechanism simultaneously. Based on this …
> periph/flashpage: deprecate *_free functions

- cpu/samd5x/include/periph_cpu.h
- cpu/samd5x/periph/pm.c
If SDHC runs off the CPU clock and we wait for the transfer to complete, we can *not* enter IDLE mode as that will stop the CPU clock.
Add a new mode that acts as a no-op where we just spin the CPU.
No change in behavior or power consumption as IDLE is unblocked by default.
> cpu/samd5x: allow to block IDLE mode

- pkg/tinydtls/patches/0005-crypto-remove-unnecessary-usage-of-malloc-dtls_hmac_.patch
- pkg/tinydtls/patches/0006-crypto-only-one-HMAC-context-is-required.patch
Removes an unnecessary usage of malloc() within TinyDTLS. In certain cases (actually depending on a binaries layout and RAM usage) this malloc() usage can lead to a silent failure of a handshake, as the failing HMAC calculation leads to the server declining a client trying to establish a session without a configured secret (as that calculation failed).
TinyDTLS should (still) work (e.g. when using `examples/gcoap_dtls`). If you had problems before establishing a session, this might solve it.
Patch provided upstream in https://github.com/eclipse/tinydtls/pull/130
> pkg/tinydtls: crypto: remove unnecessary usage of malloc()

- pkg/pkg.mk
Don't call `git am` if there are no patches. Git *should* gracefully handle it, but somehow doesn't always (like, /dev/null broken).
And, no need to call `git` if a simple test is sufficient.
> make: pkg.mk: don't call `git am` if there are no patches

- pkg/semtech-loramac/contrib/semtech_loramac_getset.c
- pkg/semtech-loramac/include/semtech_loramac.h
- pkg/semtech-loramac/patches/0005-relax-channel-mask-rules-in-regi.patch
- sys/include/net/loramac.h
- sys/shell/commands/sc_loramac.c
This change contains an addition to pkg/semtech-loramac/contrib and a patch to be applied on the original semtech-loramac code. Specifically, it:
- enable users to set the channels mask
- includes a patch that enables arbitrary channels masks to be set on region AU915. The change was extracted from the original *Lora-net/LoRaMac-node* repository, see [this commit](https://github.com/Lora-net/LoRaMac-node/commit/e60bd869). It reflects restrictions that were relaxed in a newer LoRa spec (v1.0.3rA).
I could not find automated unit tests for `semtech_loramac_getset.c`.
Manual testing could be performed as follows:
- on `examples/lorawan/main.c`, just after `semtech_loramac_set_dr`, add the following:
```.c
/* Set a mask for using only the first 8 channels */
uint16_t channel_mask[6] = …
```
> pkg/semtech-loramac: enable setting channels mask

- pkg/openwsn/patches/0014-openstack-03a-IPHC-use-memmove-instead-of-memcpy.patch
OpenWSN in one place uses `memcpy()` where `memmove()` is required due to overlapping memory regions.
Patch it to fix this.
Should fix
```
[INFO] cloning openwsn
git-cache: cloning from cache. tag=commite2958a031ad50a6f3eeca3a98ad1ae85aa773a48-688996
[INFO] updating openwsn /tmp/dwq.0.44905491325747215/3c9f2b3f67a3e6785d234b81f525a663/build/pkg/openwsn/.pkg-state.git-downloaded
echo e2958a031ad50a6f3eeca3a98ad1ae85aa773a48 > /tmp/dwq.0.44905491325747215/3c9f2b3f67a3e6785d234b81f525a663/build/pkg/openwsn/.pkg-state.git-downloaded
[INFO] patch openwsn
frag.c: In function 'frag_timerq_dequeue':
frag.c:711:5: error: 'memcpy' accessing 3 bytes at offsets 500 and 501 overlaps 2 bytes at offset 501 [-Werror=restrict]
711 |     memcpy((uint8_t *) frag_vars.frag_timerq, (uint8_t * ) & …
```
> pkg/openwsn: add patch to use memmove() instead of memcpy()

- sys/Makefile.dep
- sys/net/application_layer/uhcp/uhcpc.c
- sys/net/link_layer/csma_sender/csma_sender.c
- sys/suit/transport/coap.c
do some simple xtimer->ztimer conversions avoid using any xtimer_compat 
These modules only use 32Bit of xtimer and and therefor are easy conversions to use ztimer(32)
Somehow there is another PR with the same Title doing something different 
#17693
> sys: some simple xtimer->ztimer conversions

- cpu/arm7_common/Makefile.include
- makefiles/arch/cortexm.inc.mk
Re-enable compiler builtins for arm processors by removing the -fno-builtin flag from the arm7_common and cortexm makefile fragments.
The -fno-builtin flag disables all builtin functions provided by the compiler as well as disabling all optimizations and error checking related to standard C library functions. If you're using a C library which conforms to the ANSI C standard, you want to leave these compiler features enabled.
Pre-patch, note that printf calls are not optimized to puts calls (yeah, not a terribly helpful optimization, but it's how I discovered the issue):
```
$ sed -i '1a \
FEATURES_OPTIONAL += picolibc\
' examples/hello-world/Makefile
$ make -C examples/hello-world BOARD=microbit
$ nm -u examples/hello-world/bin/microbit/core_lib/init.o 
U auto_init
U …
```
> cpu/arm7, arch/cortexm: Remove -fno-builtin flag

- sys/auto_init/Kconfig
- sys/auto_init/Makefile
- sys/auto_init/auto_init.c
- sys/auto_init/include/auto_init_priorities.h
- sys/include/auto_init_utils.h
- tests/external_module_dirs/README.md
- tests/external_module_dirs/external_modules/external_module/external_module.c
- tests/external_module_dirs/external_modules/external_module/include/external_module.h
- tests/external_module_dirs/main.c
> sys/auto_init: custom auto-initialization sequence (simple)

- drivers/atwinc15x0/atwinc15x0_netdev.c
I noticed the wifi module would not receive any router advertisements while an esp8266 did just fine.
Turns out joining the multicast groups was not enabled.
With this it works as expected.
Just connect to a IPv6 enabled WiFi network:
```
nib: Handle timer event (ctx = 0x20001778, type = 0x4fc3, now = 4335ms)
nib: Handle packet (icmpv6->type = 134)
nib: Received valid router advertisement:
- Source address: fe80::3e37:12ff:fe9a:7d18
- Destination address: ff02::1
- Cur Hop Limit: 255
- Flags: -O
- Router Lifetime: 1800s
- Reachable Time: 0ms
- Retrans Timer: 0ms
nib: received valid Prefix Information option:
- Prefix: 2a00:20:6006:a846::/64
- Flags: LA
- Valid lifetime: 7200
- Preferred lifetime: 3600
nib: Handle timer event (ctx = 0x200017ba, type = 0x4fd1, now = 4414ms)
nib: Handle …
```
> drivers/atwinc15x0: join multicast groups

- doc/doxygen/src/using-rust.md
- tests/rust_minimal/Cargo.toml
- tests/rust_minimal/Makefile
This
* <del>updates Rust dependencies (pulling in a few changes that enable building on all platforms on beta)</del> already done in #17806
* changes <del>2</del>1 out of 3 tests/examples to actually run on beta (while the gcoap test stays on nightly, conveniently ensuring that we still have coverage on both, even though it is rather unlikely that things that work on beta (well, at least on stable) break on nightly)
* updates documentation to reflect all that.
* Green CI
(If it complains about beta not being installed, workers may need a boot)
One more piece of progress for https://github.com/RIOT-OS/RIOT/issues/17526 (now we're testing it as well).
In the interest of not making lives of new users more complicated than necessary, both examples are now still on nightly even though hello …
> rust: test on stable

- cpu/atxmega/include/periph_cpu.h
- cpu/cc2538/include/periph_cpu.h
- cpu/efm32/include/periph_cpu.h
- cpu/esp32/include/periph_cpu.h
- cpu/kinetis/include/periph_cpu.h
- cpu/lpc1768/include/periph_cpu.h
- cpu/lpc23xx/include/periph_cpu.h
- cpu/samd21/include/periph_cpu.h
- cpu/samd5x/include/periph_cpu.h
- cpu/saml1x/include/periph_cpu.h
- cpu/saml21/include/periph_cpu.h
- cpu/stm32/include/periph/cpu_pm.h
- examples/lorawan/Makefile
- examples/lorawan/main.c
- sys/include/pm_layered.h
- sys/pm_layered/pm.c
- sys/shell/commands/sc_pm.c
- tests/periph_pm/main.c
`PM_NUM_MODES` is confusing as it must *not* include the default IDLE mode.
In #17883 I added the IDLE mode to `PM_NUM_MODES` of `samd5x` so it *can* be blocked too (falling back to polling the CPU), which introduced an introducing.
I think this was done to fit all blockers for the modes into an `uint32_t`, but is is entirely unnecessary as the blockers are typically accessed as an array anyway.
So always make `pm_blocker_t` an array to remove the limitation to 4 modes.
This should retain the current behavior. `samd5x` was not changed as it already implements the new convention.
`native` was accidentally already using the new convention, causing it not to enter sleep at all with the current implementation. As a side effect, this is now fixed by this PR.
#13475
> sys/pm_layered: use array representation, get rid of implicit IDLE mode

- drivers/mtd_spi_nor/mtd_spi_nor.c
while reviewing #17836 i found the wait function timing calculation quiet strange with this i try to write that clearer
the wait timing is `us / (the numbers of loops)`
i did not test this patch,
do not know how to,
don't have hardware with a mtd_spi_nor
#9349 introduced that calculation
> driver/mtd_spi_nor: cleanup sleep timing

- boards/nucleo-f334r8/doc.txt
Improvements to STM Nucleo f336r8 documentation:
- Fix wrong parameter in command used for flashing
- Add information concerning accessing RIOT shell (see Issue #17453) 
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f334r8.html
```
Issue #17453
> boards/nucleo-f334r8: improvements to documentation

- drivers/periph_common/cpuid.c
I have encountered the following on current master:
`BOARD=nrf52840dk make -C tests/periph_cpuid/`
```
/home/fabian/forks/RIOT/drivers/periph_common/cpuid.c: In function 'cpuid_get':
/home/fabian/forks/RIOT/drivers/periph_common/cpuid.c:38:5: error: 'memcpy' offset [0, 7] is out of the bounds [0, 0] [-Werror=array-bounds]
38 |     memcpy(id, (void *)CPUID_ADDR, CPUID_LEN);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This PR suppresses the warnings because they seem to be false positive and we should rather keep builtin bounds checking enabled. Also I would be interested if someone else can reproduce the compilation error.
If someone sees why the warnings could be justified, then of course the actual cause must be fixed. 
```
cd …
```
> drivers/periph_common/cpuid: disable false positive warnings

- drivers/periph_common/cpuid.c
I have encountered the following on current master:
`BOARD=nrf52840dk make -C tests/periph_cpuid/`
```
/home/fabian/forks/RIOT/drivers/periph_common/cpuid.c: In function 'cpuid_get':
/home/fabian/forks/RIOT/drivers/periph_common/cpuid.c:38:5: error: 'memcpy' offset [0, 7] is out of the bounds [0, 0] [-Werror=array-bounds]
38 |     memcpy(id, (void *)CPUID_ADDR, CPUID_LEN);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This PR suppresses the warnings because they seem to be false positive and we should rather keep builtin bounds checking enabled. Also I would be interested if someone else can reproduce the compilation error.
If someone sees why the warnings could be justified, then of course the actual cause must be fixed. 
```
cd …
```
> drivers/periph_common/cpuid: disable false positive warnings [backport 2022.04]

- drivers/periph_common/cpuid.c
Avoid use of `memcpy` altogether to work around false positive of `-Warray-bounds` in newer GCC versions.
Ideally, binaries should change. But more importantly, `tests/periph_cpuid` should yield the same output (which it at least does for my Nucleo-F767ZI).
Alternative to https://github.com/RIOT-OS/RIOT/pull/17909#event-6403618777
> drivers/periph_cpuid: Minor cleanup

- boards/samr34-xpro/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
Make use of the helper macros to clean up the board definition, add a second timer and uart instance.
<details><summary>tests/periph_uart</summary>
``` 
2022-04-11 17:58:47,592 # UART INFO:
2022-04-11 17:58:47,593 # Available devices:               2
2022-04-11 17:58:47,594 # UART used for STDIO (the shell): UART_DEV(0)
2022-04-11 17:58:47,594 # 
2022-04-11 17:58:52,271 # > test 1
2022-04-11 17:58:52,271 # [START]
2022-04-11 17:58:52,390 # [SUCCESS]
```
</details>
<details><summary>tests/periph_timer</summary>
```
2022-04-11 18:02:03,178 # main(): This is RIOT! (Version: 2022.07-devel-8-g760b7-boards/samr34-xpro-enhance)
2022-04-11 18:02:03,178 # 
2022-04-11 18:02:03,180 # Test for peripheral TIMERs
2022-04-11 18:02:03,180 # 
2022-04-11 18:02:03,182 # Available timers: 2
2022-04-11 …
```
> boards/samr34: cleanup, add 2nd uart & timer

- drivers/periph_common/cpuid.c
Avoid use of `memcpy` altogether to work around false positive of `-Warray-bounds` in newer GCC versions.
Ideally, binaries should change. But more importantly, `tests/periph_cpuid` should yield the same output (which it at least does for my Nucleo-F767ZI).
Alternative to https://github.com/RIOT-OS/RIOT/pull/17909#event-6403618777
> drivers/periph_cpuid: Minor cleanup [backport 2022.04]

- sys/include/net/loramac.h
When using the LoRa driver from C++, the following error is emitted:
```
/[...]/RIOT/sys/include/net/loramac.h: In function 'uint32_t lora_time_on_air(size_t, uint8_t, uint8_t)':
/[...]/RIOT/sys/include/net/loramac.h:1005:41: error: enumeral and non-enumeral type in conditional expression [-Werror=extra]
1005 |     uint8_t index = (dr < LORAMAC_DR_6) ? dr : LORAMAC_DR_5;
```
g++ complains about the differing types in the ternary statement. This patch changes `dr`'s type to `loramac_dr_idx_t` to reflect its real type and avoid the error.
> Fix argument type of lora_time_on_air to avoid errors in C++

- cpu/stm32/include/periph/f7/periph_cpu.h
`#define ADC_DEVS` was missing for `stm32f7xxxx`. All have 3 ADC units. 
`BOARD=nucleo-f767zi  make -C tests/pkg_mbedtls flash term` crashes on `master` branch.
ADC3 is used in `periph_conf.h`.
```C
static const adc_conf_t adc_config[] = {
{GPIO_PIN(PORT_A, 3), 2, 3},
{GPIO_PIN(PORT_C, 0), 2, 10},
{GPIO_PIN(PORT_C, 3), 2, 13},
{GPIO_PIN(PORT_F, 3), 2, 9},
{GPIO_PIN(PORT_F, 5), 2, 15},
{GPIO_PIN(PORT_F, 10), 2, 8},
{GPIO_UNDEF, 0, 18}, /* VBAT */
};
```
Locks for every ADCx are defined in `adc_f4_f7.c`.
```C
static mutex_t locks[] = {
#if ADC_DEVS > 1
MUTEX_INIT,
#endif
#if ADC_DEVS > 2
MUTEX_INIT,
#endif
MUTEX_INIT
};
```
When `prep()` in `adc_f4_f7.c` tries to lock the mutex at `locks[2]`, illegal memory is accessed.
Using this PR, it runs successful. (`tests/pkg_mbedtls` uses ADC noise …
> cpu/stm32/include/periph/f7: add missing ADC_DEVS

- sys/Makefile.dep
- sys/fido2/ctap/Kconfig
- sys/fido2/ctap/ctap.c
- sys/fido2/ctap/ctap_cbor.c
- sys/fido2/ctap/ctap_mem.c
- sys/fido2/ctap/ctap_utils.c
- sys/fido2/doc.txt
- sys/include/fido2/ctap/ctap.h
- sys/include/fido2/ctap/ctap_crypto.h
- sys/include/fido2/ctap/ctap_mem.h
- tests/sys_fido2_ctap/README.md
- tests/sys_fido2_ctap/reset.py
This PR adjusts the FIDO2 CTAP flash handling to reserve flash memory at compile time using a `static const` buffer. This ensures that the FIDO2 CTAP implementation does not interfere with other modules wanting to use flash memory and doesn't corrupt firmware or e.g. bootloaders at the end of flash. Furthermore configuring `CONFIG_FIDO2_CTAP_NUM_FLASHPAGES` such that more flash than available is required will fail at build time rather than runtime.
*  `tests/sys_fido2_ctap`
I successfully ran the tests on the `nrf52840dongle` and `nrf52840dk`.
> Fido2 follow up

- pkg/pkg.mk
This clones repositories used by pkgs without downloading all the history. Due to git clone not being able to load a specific commit: this initializes the packages directory (PKG_SOURCE_DIR) adds the remote configures it and fetches the least amount of data to checkout the PKG_VERSION (commit-id or branch or tag)
for example: this reduces the download of wolfssl from 159.42 MiB to 9.70 MiB + 6.65 MiB ~=16.35MiB
this method or the previous git cache method is selected by the availability of the PATH named by $(GIT_CACHE_DIR) (default: $HOME/.gitcache)
make a test/example that uses a pkg that uses a git repo
non to my knowledge
> makesystem: speedup pkg cloning if no git-cache is available

- boards/adafruit-pybadge/Kconfig
- boards/adafruit-pybadge/Makefile.dep
- boards/adafruit-pybadge/board.c
- boards/adafruit-pybadge/include/board.h
This PR enables the st7735 driver and update the board configuration on the pybadge.
The board display can now be used with disp_dev and lvgl after #16176 is merged.
`tests/driver_st7735`, `tests/disp_dev` and `tests/pkg_lvgl*` are working on the pybadge.
Requires #16176
> boards/adafruit-pybadge: enable ST7735 display

- tests/pbkdf2/Makefile
The pbkdf2-test contains transfers of upto 67 byte (65+2) only limited by the speed of the serial connection.
The default rx buffer is 64 bytes -> if uart irqs are tight enough the bytes are not taken fast enough from the buffer and some are lost -> test fails 
the failing test can be seen by sometimes failing on the emulated microbit in murdock.
The large writes are defined by [pbkdf2/tests/02-random.py](https://github.com/RIOT-OS/RIOT/blob/32ac29bd9838f871f8022594de8d7bba55e50615/tests/pbkdf2/tests/02-random.py#L72:L73)
This enlarges the buffer to 2^7 (128) bytes 
read and exec that test; sadly one might have to do multiple execs of that test to see it fail without this PR
split out from #17918 as it is not that related to murdock
> test/pbkdf2: enlarge stdio rx buffer

- sys/net/gnrc/network_layer/ipv6/nib/nib.c
When a 6LR receives a Router Advertisement on it's 6Lo interface, it will automatically start sending router advertisements on that interface.
If the 6LoWPAN link is used as an uplink to a downstream network on another interface with `gnrc_ipv6_auto_subnets`, this is not the intended behavior. 
Follow the instructions in #17594
The upstream 6Lo interface on the 6LR node should no longer have the `RTR_ADV` set automatically:
```
2022-04-13 00:35:30,130 # Iface  7  HWaddr: 3A:F1  Channel: 26  NID: 0x23  PHY: O-QPSK 
2022-04-13 00:35:30,134 #           Long HWaddr: AA:CC:F4:7B:67:C4:BA:F1 
2022-04-13 00:35:30,137 #            State: IDLE 
2022-04-13 00:35:30,142 #           ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
2022-04-13 00:35:30,144 #           6LO  IPHC  
2022-04-13 00:35:30,147 # …
```
> gnrc/nib: only enable RTR_ADV on RA if MULTIHOP_P6C is enabled

- sys/include/net/nanocoap.h
- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/sock.c
- sys/suit/handlers_command_seq.c
- sys/suit/transport/coap.c
- tests/nanocoap_cli/nanocli_client.c
Nanocoap would always require a work buffer of CoAP header + payload block size for (blockwise) requests, even though this is then handed to the user via a callback and has to be copied again.
Avoid the need for this additional buffer and copying by using the `sock_udp_recv_buf()` API and hand the user callback a pointer to network stack memory directly without the need to copy it to a separate temporary buffer.
<details><summary>examples/suit_update</summary>
```
suit: received URL: "coap://[2001:db8::1]/fw/same54-xpro/suit_update-riot.suit_signed.latest.bin "
suit_coap: trigger received
suit_coap: downloading "coap://[2001:db8::1]/fw/same54-xpro/suit_update-riot.suit_signed.latest.bin"
suit_coap: got manifest with size 495
suit: verifying manifest signature
suit: validated manifest …
```
> sys/net/nanocoap: refactor to remove work-buffer requirement

- sys/include/net/af.h
The documentation comment was off.
> sys/include/net/af: fix doc comment

- sys/net/application_layer/gcoap/forward_proxy.c
Just a cleanup, make it use the `COAP_PORT` define instead of inlining the value.
> sys/net/application_layer/gcoap: use COAP_PORT

- drivers/ethos/stdio.c
Fix compilation issue.
Fails on master:
`USEMODULE=vfs BOARD=samr21-xpro make -C examples/gnrc_border_router/`
> drivers/ethos: add missing vfs include

- sys/Makefile.dep
- sys/net/gnrc/Makefile.dep
`gcoap` uses `random` but does not pull it indirectly, this fixes it. It's currently not shown because all possible network stacks pull in `random` for it.
> gcoap: small dependencies fixes

- boards/nucleo-f401re/Kconfig
- boards/nucleo-f401re/Makefile.features
Adds riotboot.
Runt `tests/riotboot`. I can put tests results on Tuesday, I don't have the BOARD ATM but I've tested `suit` and `riotboot` in this BOARD.
> boards/nucleo-f401re: add riotboot

- sys/riotboot/hdr.c
No need for the verbose LOG on by default.
> sys/riotboot/hdr: change header validation log to DEBUG

- sys/include/suit.h
- sys/suit/handlers_global.c
- sys/suit/storage/ram.c
- tests/suit_manifest/create_test_data.sh
At the end of an update the manifest `seq_no` should set "somewhere". For firmware update, this is done implicitly since the `seq_no` is contained in the firmware update. But for other storage units, it needs to be obtained from the manifest.
Therefore when parsing the manifest save the sequence number, and for `ram` storage set it during `install`.
In master, the `sequence_no` is never checked when using RAM storage, with this PR it is (although only ephemerally). Follow the [README.native.md](https://github.com/RIOT-OS/RIOT/blob/master/examples/suit_update/README.native.md)
Or alternatively, leverage https://github.com/RIOT-OS/RIOT/pull/16771.
> sys/suit: save seq_number when parsing manifest

- dist/testbed-support/makefile.iotlab.single.inc.mk
- dist/tools/buildsystem_sanity_check/check.sh
Shell redirects in the form of `2>&1 >/dev/null` do not, as one might think, redirect both stdout and err to /dev/null, but put stdout to /dev/null and redirect stderr to the process's standard output.
This adds an automated test for such redirects, and removes two more redirects that were spotted with its help.
* CI says Go
* Adding Makefile code with `2>&1 >/dev/null` trips up the static checks.
This is a follow-up on https://github.com/RIOT-OS/RIOT/pull/16775 with the unproblematic parts of https://github.com/RIOT-OS/RIOT/pull/16776 (which had to be reverted; the problematic parts come up in a different PR with more caution this time).
> makefiles: Reject `2>&1 >/dev/null`, and weed out remaining offenders

- drivers/mtd_spi_nor/mtd_spi_nor.c
The boolean expression to detect when 32 bit address mode are needed was off by one, this fixes the issue.
`tests/unittests/tests-mtd` should pass again on the `iotlab-m3`.
https://github.com/RIOT-OS/RIOT/pull/17613
> drivers/mtd_spi_nor: fix off by one bug [backport 2022.04]

- dist/pythonlibs/riotctrl_shell/sys.py
- dist/pythonlibs/riotctrl_shell/tests/test_sys.py
- sys/shell/commands/sc_suit.c
Adds a command to retrieve the highest `seq_no` of all storage units.
Shell interactions are also added.
```
2022-04-14 08:45:25,013 # suit
2022-04-14 08:45:25,015 # Usage: suit fetch <manifest url>
2022-04-14 08:45:25,017 #        suit seq_no
2022-04-14 08:45:30,173 # suit seq_no
2022-04-14 08:45:30,180 # seq_no: 1649918660
```
> sys/sc_suit: add seq_no command

- doc/doxygen/src/using-rust.md
Fixed a footnote in the ["Using Rust in RIOT"](https://doc.riot-os.org/using-rust.html) section of the documentation, that pointed to the [rust_minimal test's README](https://github.com/RIOT-OS/RIOT/blob/master/tests/rust_minimal/README.md).
The (current) live version of the [Using Rust](https://doc.riot-os.org/using-rust.html) page's link tag is
```html
<a href="(https://github.com/RIOT-OS/RIOT/blob/master/tests/rust_minimal/README.md).">
```
After this change, using `make doc` regenerates it to
```html
<a href="https://github.com/RIOT-OS/RIOT/blob/master/tests/rust_minimal/README.md">
```
I have not found any existing Issue/PR for this.
> doc: fix broken link/footnote in using-rust.md/maintenance

- sys/net/gnrc/network_layer/ipv6/nib/_nib-6lr.c
- sys/net/gnrc/network_layer/ipv6/nib/_nib-6lr.h
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
When I was Iooking through the code and was following debug messages, I discovered that the SLLA option in a Neighbor Solicitation is "stored for later handling" but it is never touched again if not also an AR option is present on 6LR.
This can be fixed by removing a `break`.
Two `nrf52840dk` `node A` and `node B` running `gnrc_networing.`
Assign both nodes an ipv6 address.
`$A ifconfig 6 add fd00:b:b::1`
`$B ifconfig 6 add fd00:b:b::2`
When `B` tries to ping `A`, it sends a multicast NS to ask for the L2 address of the target `fd00:b:b::1`.
`B` includes an SLLA option, so `A` knows the L2 address of `B` and can reply with a Neighbor Advertisement.
If `A` does not handle the SLLA option, it does not create a Neighbor Cache Entry for `B`, so it fails to deliver the NA.
Hence, the ping …
> ipv6/nib: bugfix handle SLLAO on 6LR if ARO is not present

- sys/event/event.c
- sys/include/event.h
- d3ee32fe97aceeea3b5fa26b91084f561f31225b explicitly documents that a queue needs to be initialized (either attached or detached) before posting events to it.
- b3b76bf6f35c1a940fe36c3777ccfb319e477053 documents and enforces that a queue has a `waiter` assigned before waiting for thread flags.
- `tests/events` should work as usual
None
> sys/event: Add documentation and enforce waiter on wait

- cpu/stm32/periph/ltdc.c
- drivers/disp_dev/disp_dev.c
- drivers/include/disp_dev.h
- drivers/lcd/lcd_disp_dev.c
- pkg/lvgl/contrib/lvgl.c
- pkg/lvgl7/contrib/lvgl.c
- tests/disp_dev/main.c
- tests/pkg_qr-code-generator/main.c
This PR is a take over of #14051 to only update the `disp_dev` API. Since now there are new modules that implements an adapter to this API (STM32 LTDC periph, LCD common drivers) and several users (lvgl packages, tests/disp_dev and tests/pkg_qr-code-generator).
This PR also contains small improvements compared to #14051:
- make input the parameter const
- call it `disp_dev_area_t` to better reflects what it is about
Compared to master this PR increases the ROM size by 16B (checked by compiling `tests/disp_dev` for the adafruit-clue board).
I guess that this is acceptable.
- `tests/disp_dev`, `tests/pkg_lvgl` and `tests/pkg_qr-code-generator` are still working
Closes #14051, depends on #16176
> drivers/disp_dev: use struct to store display area coordinates

- boards/adafruit-clue/include/board.h
- drivers/ili9341/ili9341.c
- drivers/ili9341/include/ili9341_params.h
- drivers/include/lcd.h
- drivers/include/st7735.h
- drivers/lcd/include/lcd_internal.h
- drivers/st7735/include/st7735_params.h
- drivers/st7735/st7735.c
- sys/auto_init/screen/auto_init_st7735.c
- tests/driver_st7735/main.c
This is a follow-up of #16176 that reworks the ili9341 parameters to also expose X/Y offset values. The idea behind this PR is about the adafruit-clue display that was not oriented correctly.
Setting the orientation parameter to the right value (`LCD_ROTATION_VERT`) raised an offset issue with the ili9341.
It seems that the offset values can be handled in a similar way as for the st7735 driver. So this PR unifies all this.
What is not done by this PR is to add the possibility to play with the ST7735 orientation parameters (they are actually still hard coded) but I couldn't find a combination that works for all possible values.
- `tests/driver_ili9341` display is correctly oriented on adafruit-clue (tested and it works)
Follow-up of #16176
> drivers/lcd: slightly rework params to expose offset values to ili9341 driver

- examples/suit_update/tests-with-config/01-run.py
Cleanup from #17941 where I didn't realize the test-checked for the cmd being there.
`examples/suit_update` is still failing but the issue is another, as it fails to verify the signature after the first slot update...
```
riotboot-hdr
>
>
>
> riotboot-hdr
Image magic_number: 0x544f4952
Image Version: 0x625e98d3
Image start address: 0x00001100
Header chksum: 0x09e4a9d3
> ifconfig
ifconfig
Iface  4  HWaddr: AA:04:26:28:76:39
L2-PDU:1500  MTU:1500  HL:64  RTR
inet6 addr: fe80::a804:26ff:fe28:7639  scope: link  VAL
pinging node...
PING fe80::a804:26ff:fe28:7639%riot0(fe80::a804:26ff:fe28:7639%riot0) 56 data bytes
--- fe80::a804:26ff:fe28:7639%riot0 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = …
```
> examples/suit_udpate: update check suit command

- drivers/include/candev_mcp2515.h
- drivers/mcp2515/Kconfig
- drivers/mcp2515/Makefile.dep
- drivers/mcp2515/candev_mcp2515.c
- drivers/mcp2515/mcp2515.c
- drivers/mcp2515/mcp2515_spi.c
- sys/auto_init/can/auto_init_mcp2515.c
This PR addresses some issues with the `mcp2515` driver:
- ef3d8349b9e6010eef0c769de2da261b9be59b70: not all breakouts have a reset pin, this allow it to be set to GPIO_UNDEF
- 16921869da5fa99adeb88b999539df81bdf82acd: currently after the first read `irq_flags` are not cleared, and the flags are re-read before clearing, this results in the same flags triggering twice. This fixes it by clearing it after reading.
- 2f31ab4a33db208820bf70f3d89665489110ca03 and 2e4840e79e2d863a4282cf07272ccc3d4858220a: address value checks that should be allowed
- dc206bce5b7bd984225b5d53f3175b5b07b2ff57: increases the default bitrate
- fa147b7c3af58d9542fe468c553428e8d5ac8221: uses ztimer
- `tests/conn_can`
- `tests/candev`:
first mcp2515
```
2022-04-19 09:02:49,687 # receive
2022-04-19 09:02:49,689 # …
```
> drivers/mcp2515: fixes and cleanups

- boards/native/Makefile.dep
- cpu/native/Makefile.include
- pkg/libsocketcan/Kconfig
- pkg/libsocketcan/Makefile
- pkg/libsocketcan/Makefile.include
- pkg/libsocketcan/Makefile.libsocketcan
- pkg/libsocketcan/doc.txt
- tests/candev/Makefile
- tests/candev/Makefile.board.dep
- tests/candev/main.c
- add libsocketcan as a package to resolve its reduced availability (Ubuntu dropped it for i386 builds)
- allow switching between OS provided and package provided libsocketcan for cpu/native
- make tests/candev more readable
On Ubuntu 20.04 with libsocketcan2:amd64 available, libsocketcan-dev available, libsocketcan2:i386 unavailable.
In `tests/candev`:
- `make -j BOARD=native CAN_DRIVER=PERIPH_CAN` should fail
- `make -j BOARD=native CAN_DRIVER=PERIPH_CAN USEPKG=libsocketcan` should build
- `sudo modprobe vcan; sudo ip link add dev vcan0 type vcan; sudo ip link set up dev vcan0` should create a virtual can device
- install can-utils for the OS
- run the native build, run `candump vcan0` in another terminal
- run `receive` in the native build's terminal
- run `cansend vcan0 …
> periph_can,candev: socketcan pkg for native, candev test cleanup

- examples/lorawan/Makefile
This is an attempt to fix the problem with `examples/loramac` raised in the 2022.04 release tests when the EEPROM of a board under test already contains a loramac stack state from a previous user.
The proposed fix is to simply disable the use of `periph_eeprom` by default. This way no previously stored stack state is reloaded and the test should succeed in any case.
A comment is added to explain how to reenable that feature and how to avoid the same issues as in the release tests.
- Green CI
- `make test-with-config` should work.
This is an attempt to fix the LoRaWAN failing release tests: https://github.com/RIOT-OS/Release-Specs/issues/244
Might also fix #17907
> examples/lorawan: disable loramac state persistence on EEPROM

- examples/lorawan/Makefile
This is an attempt to fix the problem with `examples/loramac` raised in the 2022.04 release tests when the EEPROM of a board under test already contains a loramac stack state from a previous user.
The proposed fix is to simply disable the use of `periph_eeprom` by default. This way no previously stored stack state is reloaded and the test should succeed in any case.
A comment is added to explain how to reenable that feature and how to avoid the same issues as in the release tests.
- Green CI
- `make test-with-config` should work.
This is an attempt to fix the LoRaWAN failing release tests: https://github.com/RIOT-OS/Release-Specs/issues/244
Might also fix #17907
> examples/lorawan: disable loramac state persistence on EEPROM [backport 2022.04]

- examples/lorawan/main.c
- pkg/openwsn/contrib/board.c
This is already unblocked and will trigger an assertion.
The code is still broken as other modes might be unblocked too, but at least it is just as broken as it was before #17895
`examples/lorawan` should no longer crash on most boards.
(should still crash on samd21 boards as it would since ed9f740edde87fb69ed2a214ed6348024088fa2f)
follow-up to #17895
> pm: don't (un)block IDLE mode

- examples/lorawan/main.c
- pkg/openwsn/contrib/board.c
This is already unblocked and will trigger an assertion.
The code is still broken as other modes might be unblocked too, but at least it is just as broken as it was before #17895
`examples/lorawan` should no longer crash on most boards.
(should still crash on samd21 boards as it would since ed9f740edde87fb69ed2a214ed6348024088fa2f)
follow-up to #17895
> pm: don't (un)block IDLE mode [backport 2022.04]

- sys/include/net/nanocoap_sock.h
- sys/include/net/sock/util.h
- sys/net/application_layer/nanocoap/sock.c
- sys/net/sock/sock_util.c
- tests/unittests/tests-sock_util/tests-sock_util.c
This introduces a `sock_urlpath()` function that just returns a pointer to the path component of a URL without having to copy it.
This moves the URL parsing code out of `nanocoap_get_blockwise_url()` into `nanocoap_sock_url_connect()` and save some stack by not having to allocate a `CONFIG_SOCK_URLPATH_MAXLEN` sized buffer there.
The `url` command in `tests/nanocoap_cli` still works
```
main(): This is RIOT! (Version: 2022.07-devel-91-g135d3-sock_urlpath)
nanocoap test app
> url get coap://[fe80::90a7:a6ff:fe4b:2e32%5]/.well-known/core
url get coap://[fe80::90a7:a6ff:fe4b:2e32%5]/.well-known/core
offset 000: </>;ct=40;rt="tag:chrysn@fsfe.or
offset 032: g,2022:fileserver"
```
useful for #17962, #17937
> nanocoap_sock: add nanocoap_sock_url_connect()

- dist/pythonlibs/riotctrl_shell/sys.py
- dist/pythonlibs/riotctrl_shell/tests/test_sys.py
- examples/suit_update/tests-with-config/01-run.py
- sys/shell/commands/sc_suit.c
Follow-up to #17941, it changes the `examples/suit_update` teste to use the `suit seq_no` command and adapts that command formatting to be as `riotboot` hdr dump.
- murdock should test the `shell` changes
- `exmples/suit_update` rebase on #17950
Depends on #17950 since the current SUIT CoAP is broken.
> examples/suit_update/test: use 'suit seq_no' to get version

- sys/include/net/nanocoap.h
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/application_layer/nanocoap/nanocoap.c
This adds a `coap_get_token()` function so we can eventually get rid of the token pointer in `coap_pkt_t`.
> nanocoap: add coap_get_token()

- Makefile.features
- drivers/include/periph/gpio_ll.h
- drivers/include/periph/gpio_ll_irq.h
- drivers/periph_common/Makefile.dep
- drivers/periph_common/gpio_ll.c
- drivers/periph_common/gpio_ll_irq.c
- kconfigs/Kconfig.features
- tests/bench_periph_gpio_ll/.gitignore
- tests/bench_periph_gpio_ll/Makefile
- tests/bench_periph_gpio_ll/Makefile.ci
- tests/bench_periph_gpio_ll/README.md
- tests/bench_periph_gpio_ll/main.c
- tests/bench_periph_gpio_ll/tests-with-config/01-run.py
- tests/periph_gpio_ll/.gitignore
- tests/periph_gpio_ll/Makefile
- tests/periph_gpio_ll/README.md
- tests/periph_gpio_ll/main.c
- tests/periph_gpio_ll/tests-with-config/01-run.py
This PR proposes a new peripheral GPIO API. It is orthogonal to https://github.com/RIOT-OS/RIOT/pull/14602, which tries to expose GPIO-expanders under the same API. It doesn't intend to replace the pin-based `periph/gpio` API (but on the long term the intention is that this API is implemented on top of this API, to avoid having to maintain two implementations for each MCU).
Main differences:
- low-level port-based GPIO access functions to allow fast and parallel access to GPIO pins
- this enables bit-banging when high throughput, parallel interfaces, strict timing, or any combination of these are required
- higher-level configuration API using structs
- this allows adding new members to the structs without breaking the API (when choosing the default value to be zero, so that zero …
> periph/gpio_ll: New Peripheral GPIO API

- sys/Makefile.dep
- sys/net/application_layer/nanocoap/sock.c
- tests/nanocoap_cli/Makefile
NanoCoAP should use random message IDs and randomize the retransmit timeout.
This PR takes care of this.
Block-wise does still work:
```
main(): This is RIOT! (Version: 2022.07-devel-63-g12dbc-nanocoap-fixes)
nanocoap test app
> url get coap://[fe80::581a:98ff:fe23:2d6c%5]/riot/ver
offset 000: This is RIOT (Version: 2022.07-d
offset 032: evel-64-g414f73-nanocoap_vfs) ru
offset 064: nning on a native board with a n
offset 096: ative MCU.
```
> nanocoap: follow-up fixes

- sys/include/ztimer64/xtimer_compat.h
`ztimer_msleep()` should use `ZTIMER_MSEC`, not `ZTIMER_USEC`.
> ztimer64_xtimer_compat: fix ztimer_msleep()

- sys/include/ztimer64/xtimer_compat.h
`ztimer_msleep()` should use `ZTIMER_MSEC`, not `ZTIMER_USEC`.
> ztimer64_xtimer_compat: fix ztimer_msleep() [backport 2022.04]

- sys/include/net/nanocoap.h
- sys/include/suit/transport/coap.h
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/suit/transport/coap.c
This adds a coap_handler_t function that can be used to parse new
subtrees. The subtree information is included in the context pointer of
the call and must be of type coap_resource_subtree_t. This object then
contains the pointer and length of a different coap_resource_t instance.
The coap handlers in `examples/suit-update` should still work as before
Follow-up with more cleanups to #13687
> nanocoap: Add handler for resource-based subtrees

- boards/native/Makefile.dep
- boards/native/Makefile.include
- cpu/native/include/can_params.h
- cpu/native/include/candev_linux.h
- tests/candev/README.md
- tests/candev/README.native.can.md
- tests/conn_can/README.md
This PR wants to make the `vcan` setup usage for native easier. It does so by:
- 2a5879aecc42c8b1af022bdc2bec11c39e634823: combining setup `README` for virtual can interfaces while adding details on how to connect two can interface instead of relying on `candump`/`cansend` and others.
- 3143a99991bdff0205f8151d8170853288dd4719: add `PERIPH_CAN_FLAGS` to specify the can interface to be used, similar to how `PORT` is used with `tap*`, but using an explicitly distinct variable for this.
I've also removed the `apt-get` instructions for installing the `32bit` libsocketcan instructions since it's not packages in recent distro versions and with #17533 its used through a pkg by default.
Follow the `README.native.can.md` instructions to se tup two native can interfaces, and send messages between …
> native/periph_can: usability improvements and documentation updates

- sys/include/ztimer64/xtimer_compat.h
A fix for `xtimer64`. Correction for the clock argument in `xtimer_msg_receive_timeout64`: sec -> usec
> ztimer64/xtimer_compat: fix ztimer64_msg_receive_timeout() use ZTIMER_USEC

- examples/twr_aloha/Makefile
- pkg/uwb-core/include/dpl_syscfg/syscfg_twr_ds.h
- pkg/uwb-core/include/dpl_syscfg/syscfg_twr_ds_ext.h
- pkg/uwb-core/include/dpl_syscfg/syscfg_twr_ss.h
- pkg/uwb-core/include/dpl_syscfg/syscfg_twr_ss_ack.h
- pkg/uwb-core/include/dpl_syscfg/syscfg_twr_ss_ext.h
- pkg/uwb-core/include/dpl_syscfg/syscfg_uwb_rng.h
Currently if enabling `uwb-core_rng_trx_info` module (which enables RX_DIAGNOSTICS in the uwb-dw1000 package), then TWR exchange procedure fails since it adds some processing delay that is not accounter for in the holdoff time (time before a responder node answers to an initiator TWR request). This PR fixes it by accounting for that in the holdoff configuration values.
The following fails in master: `USEMODULE=uwb-core_rng_trx_info make -C examples/twr_aloha/ flash term -j7`
```
> twr lst on
2022-04-25 13:13:11,759 # twr lst on
2022-04-25 13:13:11,761 # [twr]: start listening
2022-04-25 13:13:32,217 # twr req 03:B4 -p ds -c 5 -i 200
2022-04-25 13:13:32,218 # [twr]: start ranging
2022-04-25 13:13:32,432 # {"t": 32186, "src": "03:B4", "dst": "57:81", "d_cm": 56, "tof": 119.8907700, "los": …
```
> pkg/uwb-core: adjust holdoff time when rxdiag_enabled

- examples/lorawan/Makefile
- examples/lorawan/main.c
Change to use `auto_init_loramac`
This PR is sparked from https://forum.riot-os.org/t/cant-get-lorawan-shell-working/3526. 
> examples/lorawan/main: use auto_init_loramac

- makefiles/docker.inc.mk
When using `TEST_KCONFIG=1` along with `BUILD_IN_DOCKER=1` to build some test applications, the builds fails with this kind of error (here with `tests/shell`):
`make: *** No rule to make target '/work/riot/RIOT/tests/test_utils.config', needed by '/data/riotbuild/riotbase/tests/shell/bin/native/generated/out.config'`
This PR fixes the problem by using the docker path to `tests_utils.config` when using `BUILD_IN_DOCKER=1`.
I don't know if that's the better fix but that works.
Run `TEST_KCONFIG=1 BUILD_IN_DOCKER=1 make -C tests/shell --no-print-directory`
On master, you would get this:
```
TEST_KCONFIG=1 BUILD_IN_DOCKER=1 make -C tests/shell --no-print-directory 
=== [ATTENTION] Testing Kconfig dependency modelling ===
docker …
```
> docker: don't export KCONFIG_ADD_CONFIG variable

- dist/tools/doccheck/exclude_patterns
- sys/include/net/cord/config.h
The CoRD documentation had a few shortcomings, some of which doxygen already warned about, some from general usability, some because the text I added in #16113 was a bit too concise.
* Documentation builds without errors (even though some exclude patterns from #16779 were removed)
* All CoRD configuration macros are shown and searchable (for example, CONFIG_CORD_EP used to be shown but could not be found through the search;  CONFIG_CORD_EXTRAARGS was not shown before at all).
> net/cord doc: Usability fixes

- pkg/lwip/contrib/_netif.c
- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/lwip/include/lwip/netif/compat.h
- pkg/lwip/include/lwip/netif/netdev.h
- pkg/lwip/include/lwip_init_devs.h
- pkg/lwip/init_devs/auto_init_at86rf215.c
- pkg/lwip/init_devs/auto_init_at86rf2xx.c
- pkg/lwip/init_devs/auto_init_atwinc15x0.c
- pkg/lwip/init_devs/auto_init_cc2538_rf.c
- pkg/lwip/init_devs/auto_init_dose.c
- pkg/lwip/init_devs/auto_init_enc28j60.c
- pkg/lwip/init_devs/auto_init_esp_eth.c
- pkg/lwip/init_devs/auto_init_esp_wifi.c
- pkg/lwip/init_devs/auto_init_ethos.c
- pkg/lwip/init_devs/auto_init_mrf24j40.c
- pkg/lwip/init_devs/auto_init_netdev_tap.c
- pkg/lwip/init_devs/auto_init_nrf802154.c
- pkg/lwip/init_devs/auto_init_sam0_eth.c
- pkg/lwip/init_devs/auto_init_socket_zep.c
- pkg/lwip/init_devs/auto_init_stm32_eth.c
- pkg/lwip/init_devs/init.c
- sys/shell/commands/sc_lwip_netif.c
- tests/lwip_sock_ip/stack.c
- tests/lwip_sock_udp/stack.c
* Add `lwip_netif_t` struct which includes a `netif_t` as well as lwIP's own `struct netif`.
* Register all new netifs (using `netif_register`)
* Update `netif_get_name` implementation to expect the new struct instead of `struct netif`.
Minimizing the change to `sc_lwip_netif.c` for now as it should go away soon.
* lwIP `ifconfig` shell command still works (for IPv4 and/or IPv6). In `tests/lwip` for example
* lwIP network interfaces still initialize successfully and can send/receive traffic.
Start of fix to part of #9287 
Coming in a later PR: `netif_(get|set)_opt` implementations
> pkg/lwip: Add netif_t struct, register all netifs

- sys/include/suit.h
- sys/suit/handlers_command_seq.c
For some reason the generated manifest triggers the payload to be installed twice:
```
SUIT policy checks OK.
Formatted component name: .ram.0
Fetching firmware |█████████████████████████| 100%
Finalizing payload store
Verifying image digest
Starting digest verification against image
Install correct payload
Verifying image digest
Starting digest verification against image
Install correct payload
```
Why I'm not sure is whether this is an issue in the manifest generation or if it's something to handle in code. Pinging @bergzand on this.
Run `examples/suit_update` payload is installed once:
```
SUIT policy check OK.
Formatted component name: .ram.0
Fetching firmware |█████████████████████████| 100%
Finalizing payload store
Verifying image digest
Starting digest verification against image …
```
> sys/suit: avoid installing payload twice

- examples/twr_aloha/control.c
- examples/twr_aloha/control.h
- examples/twr_aloha/tests-with-config/01-run.py
- examples/twr_aloha/twr_shell.c
- examples/twr_aloha/twr_shell.py
This PR fixes some issues with the `examples/twr_aloha` example and some improvements to work better as read-eval-print-loops:
repl improvements:
- 359ad5e356d0a8a2f3456b6ca647fe52278f3820: only print distance values on initiator to avoid spurious data on the other node pexpect buffer
- 93f7066916497f1105313937be8b3f800d1503a3: make sure the function blocks for the whole request time
misc improvemtns:
- 5e7bb6c88ac4f98f4f23bd02baea9fc87c7484e8: error on invalid short address
- 1af9cdbef277d6c5240ab9b314997991afc69b98: extends ifconfig command
fixes:
- 26969e299bdbaadb7c5a0d8c3c780b8ba4c50f8e: should be `&` and not `&&`
- 544551de86543ff61c599f3c60c1f4d97bdfea78: adds missing request parameters
`examples/twr_aloha` still functions correctly
```
> main(): This is RIOT! (Version: …
```
> example/twr_aloha: fixes

- pkg/uwb-core/include/uwb_core.h
When support for this package was introduced printf calls inside the
uwb-core where bloating stack usage, but this is no longer the case,
so prefer lower stack usage.
The example still works fine:
```
twr req  03:B4 -c 100 -i 10 -p ds
[twr]: start ranging
{"t": 105120, "src": "03:B4", "dst": "57:81", "d_cm": 35, "tof": 75.2620086, "los": 1, "rssi": -80}
{"t": 105136, "src": "03:B4", "dst": "57:81", "d_cm": 38, "tof": 82.0272750, "los": 1, "rssi": -80}
{"t": 105150, "src": "03:B4", "dst": "57:81", "d_cm": 35, "tof": 76.2679443, "los": 1, "rssi": -80}
{"t": 105166, "src": "03:B4", "dst": "57:81", "d_cm": 37, "tof": 80.7902908, "los": 1, "rssi": -79}
{"t": 105179, "src": "03:B4", "dst": "57:81", "d_cm": 37, "tof": 80.5273514, "los": 1, "rssi": -79}
{"t": 105195, "src": "03:B4", "dst": …
```
> pkg/uwb-core: reduce default stacksize

- Makefile.include
- dist/tools/doccheck/exclude_patterns
- examples/nimble_gatt/Makefile
- examples/nimble_gatt/main.c
- examples/nimble_heart_rate_sensor/Makefile
- examples/nimble_heart_rate_sensor/main.c
- makefiles/pkg/nimble.adv.mk
- makefiles/pseudomodules.inc.mk
- pkg/nimble/Makefile
- pkg/nimble/Makefile.dep
- pkg/nimble/Makefile.include
- pkg/nimble/autoadv/Makefile
- pkg/nimble/autoadv/README.md
- pkg/nimble/autoadv/include/nimble_autoadv.h
- pkg/nimble/autoadv/include/nimble_autoadv_params.h
- pkg/nimble/autoadv/nimble_autoadv.c
- pkg/nimble/autoadv/shell.c
- pkg/nimble/contrib/include/nimble_riot.h
- pkg/nimble/contrib/nimble_riot.c
- pkg/nimble/netif/nimble_netif.c
- sys/stdio_nimble/README.md
- sys/stdio_nimble/stdio_nimble.c
- tests/shell_ble/Makefile
With `ext_adv` we can now have multiple independent advertisement state machines in parallel. This is useful for example when wanting to use `stdio_nimble` as well as `nimble_netif`, this PR enables this.
This configuring the advertisement indexes needs to be based on the enabled instances, a convenience make function is added to keep track of this and increase the advertisement index.
On two  `nrf52` based board (e.g. dwm1001):
`USEMODULE="nimble_autoadv stdio_nimble" BOARD=dwm1001 make -C examples/gnrc_networking flash term -j7`
For each open  a serial terminal using `ble-serial` (`ble-scan` can be used if using https://github.com/Jakeler/ble-serial)
```
$ ble-serial -d DE:DC:34:12:9A:F0 -p /tmp/dwad55 --write-uuid ccdd113f-40d5-4d68-86ac-a728dd82f4aa --read-uuid …
```
> pkg/nimble/autoadv: add support for ext_adv

- sys/include/net/nanocoap.h
deprecate the token ptr from nanocoap coap_pkt_t in favour of coap_get_token() introduced in #17976
check documentation
[cricle-ci-artifact](https://output.circle-artifacts.com/output/job/016d43a3-7f2e-4abd-98fe-4b5604acb8d3/artifacts/0/doc/deprecated.html)
#17976
#17983
> net/nanocoap: deprecate coap_pkt token ptr

- sys/include/net/sock/udp.h
Compiling RIOT for native while including `sys/include/net/sock/udp.h` from a C++ file will result in this error:
```
<RIOTBASE>/sys/include/net/sock/udp.h: In function ‘ssize_t sock_udp_send_aux(sock_udp_t*, const void*, size_t, const sock_udp_ep_t*, sock_udp_aux_tx_t*)’:
<RIOTBASE>/sys/include/net/sock/udp.h:686:9: error: C++ designated initializers only available with ‘-std=c++2a’ or ‘-std=gnu++2a’ [-Werror=pedantic]
686 |         .iol_base = (void *)data,
|         ^
<RIOTBASE>/sys/include/net/sock/udp.h:687:9: error: C++ designated initializers only available with ‘-std=c++2a’ or ‘-std=gnu++2a’ [-Werror=pedantic]
687 |         .iol_len  = len,
|         ^
<RIOTBASE>/sys/include/net/sock/udp.h:688:5: error: missing initializer for member ‘iolist::iol_next’ …
```
> net/sock/udp: designated intializer, C++ compatibility

- sys/include/net/gnrc.h
Hi 👋 
In the example code given in [the documentation about gnrc](https://api.riot-os.org/group__net__gnrc.html) / receiving packets is unnecessary whitespace.
This PR touches a single file: `sys/include/net/gnrc.h`
It is a fix for the documentation, no "real" code is being touched.
The issue is resolved in this PR by removing the unneeded whitespace
I honestly did not test if doxygen still builds. 😅
> net/gnrc: Fixing whitespace in the documentation

- sys/net/application_layer/nanocoap/sock.c
Some user callbacks might just return the result of some other operation that returns written bytes or negative error.
Let's not break those, only consider negative callback returns an error.
I discovered this when rebasing #17937 onto master.
Only the first block of a file would be written.
This is because the callback just returns the result of `vfs_write()`. This used to work fine (because `nanocoap_sock_request_cb()` would change the return code based on the CoAP response code), now it is handed through to the user, breaking `nanocoap_sock_get_blockwise()`.
follow-up to #17950
> nanocoap_sock: only abort nanocoap_sock_get_blockwise() on negative error

- boards/stm32f469i-disco/Makefile.include
- boards/stm32f469i-disco/doc.txt
I found old STM Disco board and check that **_cpy2remed_** works (after ST-LINK firmware upgrade).
This PR enables **_cpy2remed_** programmer (see #17550) to stm32f469i-disco.
Initial version of the ST-LINK firmware:
```
Version: 0221
Build:   Nov  4 2015 15:25:25
``` 
Firmware  upgraded without any problems.
Go to RIOT/examples/blinky and run command
```
make BOARD=stm32f469i-disco: PROGRAMMER=cpy2remed flash
```
After a while, green LED (LED0) should start blinking.
Changes in documentation can be observed using commands:
```
make doc
xdg-open doc/doxygen/html/group__boards__stm32f469i-disco.html
```
#17550
> boards/stm32f469i-disco: enable cpy2remed programmer

- drivers/mcp2515/candev_mcp2515.c
- apply hardware dependent parameters to bittiming struct before
reinitializing the hardware with the new parameter set
- this normalizes the bittiming struct wrt. `can_device_calc_bittiming` which may be undesired in very
experimental conditions
- normal users will set the bitrate and assume that the setting is honored which is not the case
without running `can_device_calc_bittiming`
- another way of fixing this issue would be to expose the `bittiming_const` struct and add information
to the documentation about the requirements and `can_device_calc_bittiming`
- without this change, the bitrate is not actually changed when solely changing this parameter in the `bittiming` struct & using the `set` method of the device interface
- with this change, modifying the bitrate as sole parameter …
> drivers/mcp2515: fix set bittiming

- makefiles/arch/riscv.inc.mk
A backward incompatible change in the RISC-V resulting in instructions previously included by rv32imac to only be available with rv32imac_zicsr. All RISC-V CPUs supported by RIOT are hence either considered as rv32imac (from the old ISA spec point of view) or as rv32imac_zicsr (from the new ISA spec point of view). This adds a simple test if GCC understands rv32imac_zicsr and uses it then as march, but uses rv32imac as march if not.
When running `make BOARD=hifive1b -C examples/default` with newer GCC versions, one will see an error message similar to:
```
/home/foobar/RIOT/cpu/riscv_common/start.S: Assembler messages:
/home/foobar/RIOT/cpu/riscv_common/start.S:20: Error: unrecognized opcode `csrc 0x300,0x00000008'
```
With this PR, the compilation should work again, but also remain …
> build system: Fix compilation for RISC-V with newer GCC

- sys/include/net/gnrc/netif/internal.h
- sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c
Currently there is no way to initialize a RPL root from the shell in the same way as with automatic prefix configuration.
This changes the `nib prefix add` command to use the same mechanism as `uhcpc` and `dhcpv6` when adding a new prefix.
I also added this to the `ipv6_auto_subnets` as this was missing there before.
To avoid conflicts with heterogeneous downstream networks (wired and wireless downstream) I added a check to only initialize RPL on a wireless interface.
> gnrc/ipv6_auto_subnets: init RPL root when adding a prefix

- sys/include/iolist.h
- sys/include/vfs.h
- sys/iolist/iolist.c
- sys/net/gnrc/sock/udp/gnrc_sock_udp.c
- sys/vfs/vfs.c
- tests/driver_pcf857x/main.c
- tests/unittests/tests-mtd/tests-mtd.c
So I stopped worrying and learned to love iolist, but I noticed some useful functions could be needed.
This adds:
- `iolist_to_buffer()` to copy the iolist to a buffer
- `vfs_write_iol()` to write the iolist to a file
`gnrc_sock_udp` has been modified to make use of `iolist_to_buffer()`. With this, `tests/gnrc_sock_udp` still passes.
> sys/iolist: add helper functions

- cpu/atmega_common/periph/timer.c
- cpu/gd32v/periph/timer.c
- cpu/lpc23xx/periph/timer.c
- cpu/native/periph/timer.c
- cpu/nrf5x_common/periph/timer.c
- cpu/rpx0xx/periph/timer.c
- cpu/sam0_common/periph/timer.c
- cpu/stm32/periph/timer.c
- drivers/dose/dose.c
- drivers/include/periph/timer.h
- tests/periph_timer_periodic/main.c
Currently it is not possible to initialize a timer with an alarm and then, at a later time, start the timer.
This is because it is assumed that the timer is always running, which leads to racy code like
```C
timer_set_periodic(timer, 0, timeout_us, TIM_FLAG_RESET_ON_MATCH);
timer_stop(timer);
```
which e.g. on sam0 currently does not what one would expect (the timer is not stopped).
Stopping the timer *before* setting the alarm will not work as many implementations assume the timer to be always running, thus when stopped internally in `timer_set_periodic()` they will restart it again.
Leverage that by adding a new flag to set the alarm but not run the timer. Implementations that do disable the timer for setting the alarm can then just skip the re-enabling step.
Implementations that do not …
> drivers/periph/timer: add TIM_FLAG_SET_STOPPED flag

- core/Kconfig
- core/Makefile
- core/include/mutex.h
- core/include/sched.h
- core/include/thread.h
- core/lib/init.c
- core/mutex.c
- makefiles/defaultmodules.inc.mk
Riotboot does not enter thread mode.
It can still be desirable to use periph code in this environment, e.g. SPI drivers that make use of mutex.
Since there are no threads, the implementation can be very simple: Busy wait on lock with the expectation to be un-locked from e.g. the TX complete ISR.
`mtd_spi_nor` nakes use of `thread_yield()` so provide a dummy implementation of that which is simple a no-op.
Add 
DISABLE_MODULE += core_thread
to some single-threaded tests. You might have to bump `ISR_STACKSIZE`.
split off #17379
> core: provide dummy implementation of thread and mutex for riotboot

- makefiles/deprecated_modules.inc.mk
- sys/include/ztimer.h
This deprecates `ztimer_now64`-module and `ztimer_now_t` in favour of ztimer64-module `ztimer64_now()` if 64Bit are need or 
`uint32_t` the return type of `ztimer_now()`
read doc and murdock green
> ztimer: deprecate ztimer_now64 and ztimer_now_t

- pkg/openwsn/patches/0015-drivers-common-crypto-fix-mismatching-function-signa.patch
This allows OpenWSN again to be compiled with newer versions of GCC, which in `master` fails with:
```
"make" -C /home/maribu/Repos/software/RIOT/build/pkg/openwsn/drivers/common/crypto -f /home/maribu/Repos/software/RIOT/Makefile.base MODULE=openwsn_crypto
/home/maribu/Repos/software/RIOT/build/pkg/openwsn/drivers/common/crypto/aes128.c:49:30: error: argument 1 of type 'uint8_t[16]' {aka 'unsigned char[16]'} with mismatched bound [-Werror=array-parameter=]
49 | owerror_t aes128_enc(uint8_t buffer[16], uint8_t key[16]) {
|                      ~~~~~~~~^~~~~~~~~~
In file included from /home/maribu/Repos/software/RIOT/build/pkg/openwsn/drivers/common/crypto/aes128.c:12:
/home/maribu/Repos/software/RIOT/build/pkg/openwsn/drivers/common/crypto/aes128.h:22:31: note: previously declared as …
```
> pkg/openwsn: fix mismatching function signatures

- cpu/cortexm_common/Kconfig
- cpu/cortexm_common/Makefile.features
- makefiles/arch/cortexm.inc.mk
[Cortex-M33 CPUs provide an FPU](https://developer.arm.com/documentation/100230/0002/functional-description/floating-point-unit/about-the-fpu?lang=en). This PR enables this feature for this CPU core.
- `tests/float` is working on CortexM33 boards:
<details><summary>b-u585i-iot02a</summary>
```
$ BUILD_IN_DOCKER=1 BOARD=b-u585i-iot02a make -C tests/float flash test --no-print-directory 
docker run --rm --tty --user $(id -u) -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -v '/home/aabadie/.cargo/registry:/data/riotbuild/.cargo/registry:delegated' -v '/home/aabadie/.cargo/git:/data/riotbuild/.cargo/git:delegated' -e …
```
> cpu/cortexm_common: enable FPU on cortexm33

- core/msg.c
Alternative version of #16751, doesn't require changing `thread_yield_higher()` semantics.
Without this fix, it is possible that a thread got set to "PENDING"
after being woken up by a message flag, but no scheduling gets
triggered. `thread_flag_wake()` (called by `queue_msg()`) does set `sched_context_switch_request=1`, which in all other cases
in msg.c will be used to conditionally call `thread_yield_higher()`.
This PR adds the missing case in `_msg_send()`.
https://github.com/RIOT-OS/RIOT/pull/16751
> core/msg: yield after thread_flags_wake() in queue_msg()

- dist/tools/zep_dispatch/Makefile
- dist/tools/zep_dispatch/example.topo
- dist/tools/zep_dispatch/topology.c
- examples/gnrc_border_router/Makefile.native.conf
- examples/gnrc_networking/Makefile
Positions in the topology are handed out first come first serve.
This makes it hard to have a reproducible setup if the ZEP dispatcher is restarted (e.g. to modify the topology) or if a node is restarted.
Fix this by allowing to specify a MAC address for each node.
If a node with a pinned MAC address connects, it will always be assigned to the same topology node.
Create a topology file with nodes pinned to specific MAC addresses:
```
A := AA:AA:AA:AA:AA:AA:AA:AA
B := BB:BB:BB:BB:BB:BB:BB:BB
C := CC:CC:CC:CC:CC:CC:CC:CC
A B
B C
```
Run the ZEP dispatcher with this file:
make -C dist/tools/zep_dispatch TOPOLOGY=test.topo run
Now start three instances of `native` with the set IDs:
make -C examples/gnrc_networking USE_ZEP=1 ZEP_MAC=AA:AA:AA:AA:AA:AA:AA:AA all term
make -C …
> tools/zep_dispatch: allow to pin nodes to MAC address

- sys/posix/include/arpa/inet.h
Replace `restrict` with `__restrict` in `sys/posix/include/arpa` because the `restrict` keyword is not available in C++.
Resolves this error message:
```
<RIOTBASE>/sys/posix/include/arpa/inet.h:62:52: error: expected ‘,’ or ‘...’ before ‘src’
62 | const char *inet_ntop(int af, const void *restrict src, char *restrict dst,
|                                                    ^~~
```
Green Murdock
> sys/posix/include/arpa: use `__restrict` instead of `restrict`

- dist/tools/compile_commands/compile_commands.py
This fixes bogus clangd linting errors for C11 `stdatomic.h` due to incorrect order of header search paths and missing `-nostdinc`
```
make BOARD=nucleo-f767zi -C tests/event_wait_timeout compile-commands
nvim tests/event_wait_timeout/main.c
```
In master, clangd (via [ALE](https://github.com/dense-analysis/ale)) is very unhappy:
```
address argument to atomic operation must be a pointer to integer, pointer or supported floating point type ('atomic_uint *' (aka '_Atomic(unsigned int) *') invalid) [clang-diagnostic-error]
/usr/lib/gcc/arm-none-eabi/11.2.0/include/stdatomic.h:192:36: note: expanded from macro 'atomic_fetch_add'
```
With this PR, clangd is happy again :)
None
> dist/tools/compile_commands: fix clangd linting

- release-notes.txt
These are the release notes for the 2022.04 release. Please note that this initial version contains mostly the automated output from release-manager tool. There's probably still a lot of room for improvement.
@chrysn, what were the most important improvements regarding RUST support?
@kaspar030, what was the major step regarding ztimer in this release?
Everyone, please check whether I missed to explicitly list a highlight.
Read it!
n/a
> Pr/release notes 2022.04 [backport 2022.04]

- dist/tools/compile_commands/compile_commands.py
This fixes unintended side affects on rust compilation, which currently relies on this tool to generate appropriate flags.
Green Murdock on a full CI run
Partially reverts https://github.com/RIOT-OS/RIOT/pull/18063 - alternative to https://github.com/RIOT-OS/RIOT/pull/18079
> dist/tools/compile_commands: don't adds -nostdinc

- sys/net/gnrc/sock/include/gnrc_sock_internal.h
The interface is already set implicitly for the `gnrc_netif_highlander()` case - also set it implicitly if there is only a single interface.
alternative to #17927
> gnrc_sock: implicitly set netif if there is only a single one

- pkg/lwip/contrib/_netif.c
Add basic netif get/set opt implementation for lwIP. 
Only supporting getting IPv6 addresses and underlying netif options. Setting options not supported.
Apply e22fe428b4da8f6cc058577ffe0d27b5ed065ced and f502b031f2935e50306fa083e8f9ddebaa98930d, and build and flash `tests/lwip` (l2util module needs to be added).
The gnrc version of `ifconfig` then prints the lwIP netifs including IPv6 addresses, link type and channel for WiFi:
```
> ifconfig 
Iface  ET1  HWaddr: 24:0A:C4:E6:0E:9C  Channel: 11  Link: up 
L2-PDU:1500  Source address length: 6
inet6 addr: fe80::260a:c4ff:fee6:e9c  scope: link
inet6 addr: 2001:db8:0:0:260a:c4ff:fee6:e9c  scope: global
[..]
```
Part of #9287
> pkg/lwip: Add basic version of netif_get/set_opt

- sys/include/net/gnrc/netif.h
Reformulate the documentation to make it clear that this returns the *size* of the addresses, not the number of addresses.
Just read and see if this is less easy to misunderstand.
> net/gnrc_netif: clarify documentation of gnrc_netif_ipv6_addrs_get()

- sys/shell/shell.c
Arch just upgraded to arm-none-eabi-gcc  12.1.0, and a new warning popped up:
```
/home/kaspar/src/riot.rs/sys/shell/shell.c: In function 'find_handler':                                                                            
/home/kaspar/src/riot.rs/sys/shell/shell.c:120:42: error: the comparison will always evaluate as 'true' for the address of '_shell_command_list' wi
ll never be NULL [-Werror=address]                                                                                                                 
120 |     if (handler == NULL && _builtin_cmds != NULL) {                                                                                        
|                                          ^~ …
```
> sys/shell: drop `_builtin_cmds` define

- sys/include/net/nanocoap.h
- sys/net/application_layer/nanocoap/nanocoap.c
Casting payload to `(uint8_t *)` or `(void *)` is really annoying and unnecessary. 
No change in code output or on the caller side, just more convenient interface.
> nanocoap: use void * for payload bytes

- sys/Makefile.dep
- sys/include/net/sock.h
- sys/include/net/sock/ip.h
- sys/include/net/sock/udp.h
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/gnrc/sock/ip/gnrc_sock_ip.c
- sys/net/gnrc/sock/udp/gnrc_sock_udp.c
If a node has multiple addresses we must reply to a request with the same address on which the request was received.
Run GCoAP on a node that has multiple addresses assigned to it's interface, or a second interface with a global address:
```
2022-04-27 18:01:21,824 # Iface  7 
2022-04-27 18:01:21,828 #           Long HWaddr: AA:EC:E6:8B:F9:BA:BD:C8 
2022-04-27 18:01:21,831 #           MTU:65535  HL:64  RTR  
2022-04-27 18:01:21,833 #           RTR_ADV  
2022-04-27 18:01:21,835 #           Link type: wired
2022-04-27 18:01:21,841 #           inet6 addr: fe80::a8ec:e68b:f9ba:bdc8  scope: link  VAL
2022-04-27 18:01:21,847 #           inet6 addr: fd11::a8ec:e68b:f9ba:bdc8  scope: global  VAL
2022-04-27 18:01:21,852 #           inet6 addr: fdea:dbee:f::1  scope: global  VAL
2022-04-27 …
```
> gcoap: ensure response address is the same as request address

- dist/tools/doccheck/exclude_patterns
- sys/Makefile.dep
- sys/include/net/coap.h
- sys/include/net/nanocoap/cache.h
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/nanocoap/Kconfig
- sys/net/application_layer/nanocoap/cache.c
- tests/unittests/tests-nanocoap_cache/Makefile
- tests/unittests/tests-nanocoap_cache/Makefile.include
- tests/unittests/tests-nanocoap_cache/tests-nanocoap_cache.c
- tests/unittests/tests-nanocoap_cache/tests-nanocoap_cache.h
This PR adds a cache for CoAP response messages to `nanocoap`. [RFC7252, Section-5.6](https://tools.ietf.org/html/rfc7252#section-5.6) elaborates on the internals of a cache implementation.
The basic idea is to reduce response time and enhance bandwidth usage by storing CoAP responses at intermediary proxy nodes. The cache key is calculated using the information in [RFC7252, Section 5.10](https://tools.ietf.org/html/rfc7252#section-5.10). Optimized cache key calculations based on other mechanisms (e.g., using the ETAG) are not included in this PR (and firstly require a proper cache<->proxy integration).
This proposed implementation uses a simple LRU strategy to replace cache entries as soon as the available cache space is used up. The replacement strategy is passed as a function pointer, …
> nanocoap: cache for CoAP responses

- sys/uri_parser/uri_parser.c
- tests/unittests/tests-uri_parser/tests-uri_parser.c
Ports cannot exceed "65535", thus five characters.
This PR adds enforcement and a regression test.
Thanks @Teufelchen1 for report and fix!
> sys/uri_parser: check port length

- sys/uri_parser/uri_parser.c
- tests/unittests/tests-uri_parser/tests-uri_parser.c
Ports cannot exceed "65535", thus five characters.
This PR adds enforcement and a regression test.
Thanks @Teufelchen1 for report and fix!
> sys/uri_parser: check port length [backport 2022.04]

- dist/tools/doccheck/exclude_patterns
- sys/include/net/coap.h
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/nanocoap/cache.c
This provides support for the [cache validation mechanism of CoAP](https://datatracker.ietf.org/doc/html/rfc7252#section-5.6.2) for the `gcoap_forward_proxy` module if `nanocoap_cache` is also provided.
TBD procedurally, but could be easily done with an `aiocoap` server with ETag support, a RIOT client and a RIOT forward proxy inbetween the two. The client requests a resource via the proxy (the server delivers the data with an ETag), waits until the Max-Age (default 60 seconds) of the resource passed, then requests the (assumed to be unchanging) resource again. This should trigger the proxy to send a request with the resource's ETag to the server which in turn answers with a 2.03 Valid response. The proxy should then send the original cached response back (and update the cache entries …
> gcoap_forward_proxy: provide cache validation mechanism

- tests/cpp_exclude/external_modules/module_exclude/Kconfig
- tests/cpp_exclude/external_modules/module_exclude/Makefile.dep
- tests/cpp_ext/external_modules/module/Kconfig
- tests/cpp_ext/external_modules/module/Makefile.dep
Follow up due to my slowness of reviewing.  
The HAS_* should only be selected by boards/cpus, at least in the cpp case.
- `TEST_KCONFIG=1 BOARD=arduino-mega2560 make all -C tests/cpp_exclude/` should show unmet dependencies and not a compilation error
#17994
> tests/{cpp_ext, cpp_exclude}: cleanup HAS_*

- sys/include/net/gcoap.h
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/gcoap/gcoap.c
Just some code-deduplication.
`examples/gcoap` should still compile with and without the `gcoap_forward_proxy`.
Spotted by @cgundogan in #17801 but can be merged independent of it (but might cause merge conflicts there or here).
> gcoap: add helper function to get request header from a request memo

- boards/native/Makefile.include
- tests/unittests/Makefile
- tests/unittests/tests-uri_parser/tests-uri_parser.c
This PR wires up the Address Sanitizer for the unittests on native.
Another ~~PR~~ commit fixes the last remaining issue ASAN reported (a scratch buffer was too small in tests-uri_parser).
This only affects native, and makes it running unittests more likely to fail. CI tests all of it.
#17800
> unittests: enable ASAN on native

- tests/pkg_tflite-micro/Makefile.ci
During execution of `./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py` for nucleo-432kc i notice that this test cannot be programmed due to problems with insufficient flash memory. I see such error:
```
. . .
"make" -C /data/RIOT-public/RIOT/tests/pkg_tflite-micro/external_modules/mnist
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /data/RIOT-public/RIOT/tests/pkg_tflite-micro/bin/nucleo-l432kc/tests_pkg_tflite-micro.elf section `.text' will not fit in region `rom'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: region `rom' overflowed by 16468 bytes
collect2: error: ld returned 1 exit status
make: *** [/data/RIOT-public/RIOT/tests/pkg_tflite-micro/../../Makefile.include:735: …
```
> tests/pkg_tflite-micro: update list of low memory boards

- sys/include/net/gcoap.h
- sys/include/net/nanocoap/cache.h
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/application_layer/nanocoap/cache.c
- tests/unittests/tests-gcoap/tests-gcoap.c
- tests/unittests/tests-nanocoap_cache/tests-nanocoap_cache.c
This provides caching support (via `nanocoap_cache`) for `gcoap` clients. For the moment this is still a draft, as I am sure there is some cleanup possible now in caching parts of the `gcoap_forward_proxy` module. However, I invite still everyone to review this PR.
Use `tapsetup` to create a TAP bridge
```sh
./dist/tools/tapsetup/tapsetup
```
Patch [`aiocoap`](https://aiocoap.readthedocs.io/en/latest/installation.html#development-version) to include the `ETag` and `Max-Age` option in the responses of its file server example
<details><summary>Patch</summary>
```diff
diff --git a/aiocoap/cli/fileserver.py b/aiocoap/cli/fileserver.py
index 10df38e..92ef7d7 100644
--- a/aiocoap/cli/fileserver.py
+++ b/aiocoap/cli/fileserver.py
@@ -20,7 +20,7 @@ import mimetypes
import aiocoap
import …
```
> gcoap: add nanocoap_cache support for clients

- dist/tools/compile_commands/compile_commands.py
- makefiles/arch/riscv.inc.mk
Use -misa-spec=2.2 on newer toolchains, which allows passing the same `-march=` value to both the linker and the compiler even when binutils and GCC support difference ISA specs.
Compilation for RISC-V should still work for all toolchains it works in `master`.
Note that the warnings at link time (e.g. `mis-matched ISA version 2.0 for 'a' extension, the output version is 2.1` on Arch Linux) will still pop up. Hopefully the ISA specs implemented by existing MCUs won't be touched much more, so that eventually binutils, GCC, and newlib/picolibc eventually converge to the same ISA spec eventually.
Suggested in https://github.com/RIOT-OS/RIOT/pull/17951#issuecomment-1124663834
> buildsystem: Improve RISC-V compilation handling with newer toolchain

- makefiles/pseudomodules.inc.mk
- sys/include/net/gnrc/netif.h
- sys/include/net/gnrc/netif/internal.h
- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/link_layer/gomach/gomach.c
- sys/net/gnrc/link_layer/lwmac/lwmac.c
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
- tests/gnrc_netif/main.c
This PR removes the NETDEV_MSG_TYPE_EVENT and forces GNRC Netif to do the Bottom Half processing (ISR offload) using event loops instead of msg queues.
Msg queues are not safe for processing ISR because they might be lost. Indeed this might happen often if the device is under stress (e.g Border Router). Losing these events tend to have catastrophic consequences such as:
- Radios might stop receiving frames if the FB is lock and nobody cares to read the framebuffer
- The IEEE 802.15.4 SubMAC might be go to the wrong state if one of the radio events get lost.
I suspect some of the BR freezes might be related to this.
This PR also removes the `gnrc_netif_events` since it's not optional anymore. We should adapt it in the future to use `thread_flags` directly though (I know @maribu already did …
> gnrc_netif: use event loops by default to process ISR

- cpu/esp32/Makefile.dep
- cpu/esp32/vendor/esp-idf/ethernet/emac_dev.h
This PR provides two fixes that are required to make the ESP32 code compilable with gcc 5.2.0 and gcc 8.2.0.
Green CI
Fixes the compilation problems occured in CI with https://github.com/RIOT-OS/riotdocker/pull/190.
> cpu/esp32: fixes for gcc 8.4.0

- drivers/at86rf215/at86rf215_netdev.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
- drivers/cc2420/cc2420_netdev.c
- drivers/kw2xrf/kw2xrf_netdev.c
- drivers/kw41zrf/kw41zrf_netdev.c
- drivers/mrf24j40/mrf24j40_netdev.c
- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/openthread/contrib/netdev/openthread_netdev.c
- pkg/openwsn/contrib/radio_netdev.c
- sys/include/net/netopt.h
- sys/net/crosslayer/netopt/netopt.c
- sys/net/gnrc/link_layer/gomach/gomach.c
- sys/net/gnrc/link_layer/lwmac/lwmac.c
- sys/net/gnrc/netif/gnrc_netif.c
- tests/driver_at86rf2xx/main.c
The option makes no sense as there will always be an IRQ on RX end.
This option was only set by all network stacks, but no driver implemented the set function.
Some drivers implemented a get function that would always return true.
This means this option is entirely useless.
No change in behavior expected, but we save some bytes of ROM and a warning message on drivers that did not implement the GET function.
> net/netopt: drop NETOPT_RX_END_IRQ

- examples/gcoap_dtls/Makefile
With the current configuration via CFLAGS it is impossible to change `DTLS_PEER_MAX` from console (without editing the Makefile) and even worse: config via Kconfig is not possible. This removes the definition of DLTS_PEER_MAX. It could make sense to add a `app.config` to this example, however, `CONFIG_DTLS_PEER_MAX` [already defaults to 1](https://github.com/RIOT-OS/RIOT/blob/d28a45e93964be8fdf03994b6ada27ffbcbed964/pkg/tinydtls/Kconfig#L41), so setting it to 1 really is not necessary.
`examples/gcoap_dtls` should still compile, now compiling it with e.g.
```sh
RIOT_CONFIG_KCONFIG_USEPKG_TINYDTLS=y RIOT_CONFIG_DTLS_PEER_MAX=2 make -C examples/gcoap_dtls flash ter
```
should also work (or the corresponding `app.config`). Mind you, it did work before as well, the new value was just ignored. …
> examples/gcoap_dtls: remove CFLAGS define of DTLS_PEER_MAX

- sys/Makefile.dep
- sys/include/vfs.h
- sys/include/vfs_util.h
- sys/vfs_util/Makefile
- sys/vfs_util/vfs_util.c
It is often quite handy to have a small file to store a flag or an instruction or similar.
Instead of writing the same sequence of commands each time, provide a small helper function so the job can be done with a single line of code.
split off #17379
> sys/vfs_util: add VFS helper functions

- tests/unittests/tests-sock_util/tests-sock_util.c
I moved the test stings to their tests to ease read ablility  (not scroling from line 200 to 20 and back again)
Also added some comments why a certain case is invalid.
read and murdock 
inspired while adding tests in #18061
> unittest/sock_util: move test_strings to their tests

- boards/native/Makefile.dep
The `native` board is special in that it creates a new storage instance for each test application and provides default mount pints for each file system, so the current hard default is rather arbitrary.
Make this soft default more easy to use by allowing to just supply a different file system without having to remove the `vfs_default` module (and then manually adding the auto-mount module).
Add e.g. `USEMODULE += fatfs_vfs` to `tests/vfs_default`
- littlefs2 does not get build
- an `MEMORY.bin` image with a FAT fs does not get auto-formatted with littlefs2
> boards/native: allow to overwrite default fs

- drivers/at86rf215/Makefile.dep
So it can be disabled.
DISABLE_MODULE += at86rf215_blocking_send
should work now.
> drivers/at86rf215: make at86rf215_blocking_send a DEFAULT_MODULE

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- tests/rust_minimal/Cargo.lock
Updating to riot-sys 0.7.7 enables support for more recent C2Rust
versions.
* Green CI
Supporting the most recent C2Rust helps unblock <https://github.com/RIOT-OS/riotdocker/pull/189>.
> {examples,tests}/rust: Rust updates [backport 2022.04]

- pkg/littlefs2/Makefile
Bump version to [2.5.0](https://github.com/littlefs-project/littlefs/releases/tag/v2.5.0)
`tests/pkg_littlefs2` still works
```
main(): This is RIOT! (Version: 2022.07-devel-309-gf3c364-pkg/littlefs2-bump)
........
OK (8 tests)
{ "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 436 }]}
{ "threads": [{ "name": "main", "stack_size": 12288, "stack_used": 2828 }]}
```
Old fs can also still be mounted.
> pkg/littlefs2: bump version to 2.5.0

- sys/include/vfs.h
- sys/vfs/vfs.c
If we mount a file system by path we also might want to unmount it, e.g. for clean shutdown or reboot.
Just adds a function that does the same as `vfs_mount_by_path()` but with unmount instead of mount.
Complements #17661
> sys/vfs: add vfs_unmount_by_path()

- sys/include/net/nanocoap.h
- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/net/application_layer/nanocoap/sock.c
- tests/nanocoap_cli/main.c
- tests/nanocoap_cli/nanocli_client.c
This implements a `nanocoap_sock_block_request()` function for block-wise (block1) requests.
The function is expected to be called in a loop and will transmit a block each time it's called.
As an alternative to #17544 I simple added a `iolist_t *snips` to `coap_pkt_t` so we don't have to copy the payload into a temporary buffer and can leverage `sock_udp_sendv()` instead.
The `tests/nanocoap_cli` has been extended with a (crude) `put` command.
It will simply upload the lyrics of the Free Software Song via blockwise PUT, it can be used with
put coap://[fe80::90a7:a6ff:fe4b:2e32%5]/song.txt
with
aiocoap-fileserver --write .
on the other end.
This will be changed to instead integrate with `nanocoap_vfs` to upload files and integrate with the `url put/post` command, but I wanted to get some …
> nanocoap_sock: add nanocoap_sock_block_request()

- cpu/sam0_common/include/periph_cpu_common.h
- cpu/sam0_common/periph/adc.c
The ADC can be configured to use an input pin for the external reference voltage.
Automatically configure this pin when `ADC_REF_DEFAULT` is set accordingly.
On all members of the family PA03 and P04 can be used as reference A and B respectively. SAM D5x/E5x also allows to use PA06 as reference C.
Set `ADC_REFSEL_AREFB_PIN` to e.g. `ADC_REFCTRL_REFSEL_AREFA` and connect a reference voltage to PA03, then run `tests/periph_adc`.
> cpu/sam0_common: adc: Automatically configure external reference pin

- boards/iotlab-m3/doc.txt
The [lsm303dlhc](https://doc.riot-os.org/group__drivers__lsm303dlhc.html) is the accelerometer/magnetometer sensor and the [l3g4200d](https://doc.riot-os.org/group__drivers__l3g4200d.html) is the gyroscope. The sensor are switched in the documentation.
Just read the documentation
None
> boards/iotlab-m3: fix mixed sensors in implementation status

- drivers/atwinc15x0/atwinc15x0_netdev.c
Don't try to re-connect when the interface is in SLEEP state.
Also disconnect before entering sleep.
This prevents an issue where the devices sleep state would get out of sync with the requested sleep state. The device would try to re-connect even though it should be asleep. 
follow-up to #17854
> drivers/atwinc15x0: disconnect when sleeping

- sys/net/application_layer/nanocoap/sock.c
This gets rid of the implicit additional state added by the `retry_rx`variable and makes it an explicit state.
Functionality should stay the same.
> nanocoap_sock: clean up state management

- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/vfs_util.h
- sys/shell/commands/sc_vfs.c
- sys/shell/commands/shell_commands.c
- sys/vfs_util/vfs_util.c
This adds helper functions to compute the hash of a file as well as accompanying shell functions `md5sum`, `sha1sum` and  `sha256sum`.
Just add the module with the name of the shell function, e.g
```
USEMODULE += md5sum
USEMODULE += sha1sum
USEMODULE += sha256sum
```
```
2022-04-30 18:22:26,944 # > md5sum /nvm0/image.bin /nvm0/old_image.bin
2022-04-30 18:22:27,025 # 927c31ba0e221b6b0ed916d0f6bb794f  /nvm0/image.bin
2022-04-30 18:22:27,098 # 0e4c7aaf386573e4a4a872d28afd066a  /nvm0/old_image.bin
2022-04-30 18:22:34,224 # > sha1sum /nvm0/image.bin /nvm0/old_image.bin
2022-04-30 18:22:34,334 # 6c1207ba448d380133ada360f42633d2bdfd83e4  /nvm0/image.bin
2022-04-30 18:22:34,433 # a3b4b6aafef50f0efcff0b0fc52fc98ef1c80217  /nvm0/old_image.bin
2022-04-30 18:22:48,370 # > sha256sum /nvm0/image.bin …
```
> sys/vfs_util: add vfs_file_<hash>() functions and md5sum, sha1sum and sha256sum shell commands

- pkg/wamr/Makefile
change package-version to released and tagged WAMR
build and run `examples/wamr` or/and your own wamr/wasm application
https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-05-18-2022
> pkg/wamr: update to tagged release WAMR-05-18-2022

- sys/fs/constfs/constfs.c
- sys/vfs/vfs.c
- tests/unittests/tests-vfs/tests-vfs-file-system-ops.c
VFS will handle it if those functions are not implemented.
> sys/fs/constfs: drop dummy implementations

- sys/include/phydat.h
- sys/phydat/phydat_json.c
RIOT kernel panics when calling phydat_to_json with dim=3:
```
sys/phydat/phydat_json.c:46 => 0x8049c14
*** halted.
```
The precondition/assertion for parameter 'dim' in phydat_to_json is to restrictive. Calling phydat_to_json with dim=3 should be valid as can be seen in the documentation of phydat_to_json itself:
https://doc.riot-os.org/group__sys__phydat.html#gad7a5978e5119e3976addffd2891c76fa
This pull request allows phydat_to_json to be called with dim=3.
Just call phydat_to_json with dim=3. For example:
```
#include <phydat.h>
int main(void)
{
char json[100];
phydat_t data = {0};
phydat_to_json(&data, 3, json);
puts(json);
}
```
Expected output would be:
```
{"d":[0,0,0],"u":"undefined"}
```
(no references)
> sys/phydat: fix phydat_to_json precondition

- boards/native/board_init.c
- boards/native/include/board.h
- cpu/esp_common/periph/flash.c
- drivers/at24cxxx/mtd/mtd.c
- drivers/at25xxx/mtd/mtd.c
- drivers/include/mtd.h
- drivers/include/mtd_flashpage.h
- drivers/include/mtd_mapper.h
- drivers/mtd/mtd.c
- drivers/mtd_mapper/mtd_mapper.c
- drivers/mtd_mci/mtd_mci.c
- drivers/mtd_sdcard/mtd_sdcard.c
- drivers/mtd_spi_nor/mtd_spi_nor.c
- tests/mtd_mapper/main.c
- tests/pkg_littlefs/main.c
- tests/pkg_littlefs2/main.c
- tests/pkg_spiffs/main.c
- tests/unittests/tests-mtd/tests-mtd.c
MTD does not describe all that a user may need to know when only passed a driver-based device (which usually comes with the expectation that no more needs to be known about the device than that it provides the API).
In particular, what was missing was:
* Information that arbitrary overwrites are permitted (which they are not on flashpage_mtd devices)
* Information that writes are constrained to aligned regions. This was not super important previously (as the drivers might emulate unaligned writes, though docs already said that they might also not), but now that writes are somewhat distinguished from overwrites, a user needs to know the alignment to not accidentally perform two logically independent writes that would still constitute an overwrite (say, writing the first 4 bytes one-by-one, …
> mtd: Introduce write granularity

- .github/workflows/release-test.yml
- boards/native/doc.txt
See #18099 and https://github.com/RIOT-OS/RIOT/runs/6534330826?check_suite_focus=true
Will start a standalone release test.
Follow-up on #18099.
> release-tests: install libasan as native dependency

- tests/unittests/tests-nanocoap_cache/tests-nanocoap_cache.c
The doc states only that the result is <0, not -1. The result isn't the latter for some platforms (see https://github.com/RIOT-OS/RIOT/runs/6534330788?check_suite_focus=true#step:13:696)
Run unittests on e.g. an ARM-Cortex-based platform. On my system there is another failure for `tests-pkt` ATM which I will also investigate.
None, showed up in weekly release tests.
> unittests: fix assertion for nanocoap_cache_key_compare()

- sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c
- sys/net/gnrc/network_layer/ipv6/nib/nib_abr.c
Fixes inconsistent representation of the ABR valid lifetime as described in #17512.
Run a `gnrc_border_router` and a `gnrc_networking` application on a 6LoWPAN-compatible device. `nib abr` should now list the lifetimes correctly and it should be updated to the original 10000min, whenever the BR sends another ABRO.
Fixes #17512.
> gnrc_ipv6_nib: fix inconsistent ABR valid lifetime representation

- sys/shell/commands/sc_vfs.c
Follow up to #18109, add the shell commands.
Run the commands.
> sys/shell/vfs: add umount, rmount and mkdir commands

- sys/net/gnrc/network_layer/ipv6/nib/nib.c
This avoids a race condition where the default router slots for the 6LBR are used up by router advertisements from the 6Lo network that arrived before router advertisements from the upstream network.
The border router should ignore 'default routers' from the 6Lo network as it consitutes the uplink for that network.
You should no longer see
```
nib: default router list is full. Ignoring RA from fe80::fec2:3d00:0:bb1
nib: Handle packet (icmpv6->type = 134)
nib: Received valid router advertisement:
- Source address: fe80::ac8d:fee1:6041:91f1
- Destination address: fe80::a8cc:f47b:67c4:baf1
- Cur Hop Limit: 0
- Flags: --
- Router Lifetime: 1800s
- Reachable Time: 0ms
- Retrans Timer: 0ms
nib: default router list is full. Ignoring RA from fe80::ac8d:fee1:6041:91f1
```
On the border router. In …
> gnrc/nib: don't add routers from WPAN as default router on the 6LBR

- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/network_layer/sixlowpan/frag/sfr/gnrc_sixlowpan_frag_sfr.c
- tests/gnrc_tx_sync/Makefile
- tests/gnrc_tx_sync/Makefile.ci
- tests/gnrc_tx_sync/main.c
Implement TX synchronization for `gnrc_sixlowpan_frag_sfr` and also extend the corresponding test.
`tests/gnrc_tx_sync` should pass
None
> sys/net/gnrc: add gnrc_tx_sync for gnrc_sixlowpan_frag_sfr

- drivers/mtd/mtd.c
MTD drivers set their `write_size` member in their `init()` function, so the assertion should be checked afterwards.
For example look at `mtd_spi_nor_init()`, `_mtd_at24cxxx_init()`,  `mtd_sdcard_init()`.
> drivers/mtd: move write_size assertion after init call

- boards/common/nucleo/Makefile.include
- boards/nucleo-f303k8/doc.txt
- boards/nucleo-f334r8/Makefile.include
- boards/nucleo-f429zi/Makefile.include
- boards/nucleo-f446ze/Makefile.include
- boards/nucleo-l031k6/doc.txt
- boards/nucleo-l073rz/doc.txt
- boards/nucleo-l432kc/doc.txt
- boards/nucleo-l552ze-q/Makefile.include
- boards/p-nucleo-wb55/Makefile.include
This PR enables **_cpy2remed_** programmer (see #17550) to four STM Nucleo boards: l031k8, l073rz, f303k8 and l432kc .
All boards have initially older ST-LINK firmware - the oldest was:
```
Version: 0221
Build:   Nov 19 2015 15:23:07
``` 
All are updated (without any problems) to minimal firmware which works with **_cpy2remed_** programmer - 2.37.36 (V2.J37.M26 - shown in the  ST-LinkUpgrade program).  
Go to RIOT/examples/blinky and run command
```
make BOARD=nucleo-l031k8 PROGRAMMER=cpy2remed flash
make BOARD=nucleo-l073rz PROGRAMMER=cpy2remed flash
make BOARD=nucleo-f303k8 PROGRAMMER=cpy2remed flash
make BOARD=nucleo-l432kc  PROGRAMMER=cpy2remed flash
```
After a while, green LED (LED0) should start blinking.
Changes in documentaion can be observed using commands:
```
make doc
xdg-open …
```
> boards/nucleo-X: enable cpy2remed programmer

- sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c
When a single address is added to an interface, it will be included in the RA as a /128 prefix
```
2022-05-10 16:45:00,550 # Iface  8 
2022-05-10 16:45:00,554 #           Long HWaddr: AA:EC:E6:8B:F9:BA:BD:C8 
2022-05-10 16:45:00,557 #           MTU:65535  HL:64  RTR  
2022-05-10 16:45:00,559 #           RTR_ADV  
2022-05-10 16:45:00,562 #           Link type: wired
2022-05-10 16:45:00,567 #           inet6 addr: fe80::a8ec:e68b:f9ba:bdc8  scope: link  VAL
2022-05-10 16:45:00,573 #           inet6 addr: fd11::a8ec:e68b:f9ba:bdc8  scope: global  VAL
2022-05-10 16:45:00,578 #           inet6 addr: fdea:dbee:f::1  scope: global  VAL
2022-05-10 16:45:00,581 #           inet6 group: ff02::2
2022-05-10 16:45:00,584 #           inet6 group: ff02::1
2022-05-10 16:45:00,587 #           inet6 group: …
```
> gnrc/ipv6_auto_subnets: only use prefixes meant for automatic address configuration

- examples/suit_update/Makefile
- sys/Makefile.dep
- sys/include/net/nanocoap.h
- sys/include/net/nanocoap_vfs.h
- sys/include/suit/transport/coap.h
- sys/net/application_layer/nanocoap/vfs.c
- sys/shell/commands/Makefile
- sys/shell/commands/sc_nanocoap_vfs.c
- sys/shell/commands/shell_commands.c
- tests/nanocoap_cli/Makefile
This adds a convenience function `nanocoap_vfs_get()` to download a file from a CoAP server and store it on the local filesystem.
In addition a shell command `ncget` is provided that makes use of the function.
Run the `tests/nanocoap_cli` example. If you are on `native` you want to enable the `vfs_auto_format` module to automatically create a file system on the auto-generated virtual storage.
Run `aiocoap-fileserver .` in e.g. the RIOT root directory.
```
main(): This is RIOT! (Version: 2022.07-devel-20-g7d76a-nanocoap_vfs)
nanocoap test app
> ls /nvm0
./
../
total 0 files
> ncget coap://[fe80::90a7:a6ff:fe4b:2e32%5]/
/.git
/CODE_OF_CONDUCT.md
/LICENSE
/.github/
/boards/
/dist/
/examples/
/sys/
/build/
/bootloaders/
/core/
/cpu/
/doc/
/drivers/
/makefiles/ …
```
> nanocoap_vfs: add nanocoap_vfs_get()

- sys/net/gnrc/sock/gnrc_sock.c
It took me nearly a day of debugging to find out that my event queue was broken due to the handler thread being stuck in a `sock_udp_recv()`. To prevent that in the future, issue a warning about non-zero-timeouts when the asynchronous callback is set.
Apply the following patch:
```patch
diff --git a/tests/gnrc_sock_async_event/main.c b/tests/gnrc_sock_async_event/main.c
index d77e84c084..93bdc9a485 100644
--- a/tests/gnrc_sock_async_event/main.c
+++ b/tests/gnrc_sock_async_event/main.c
@@ -78,7 +78,7 @@ static void _recv_udp(sock_udp_t *sock, sock_async_flags_t flags, void *arg)
sock_udp_ep_t remote;
ssize_t res;
-        if ((res = sock_udp_recv(sock, _buffer, sizeof(_buffer), 0,
+        if ((res = sock_udp_recv(sock, _buffer, sizeof(_buffer), 20,
&remote)) >= 0) {
printf("Received UDP …
```
> gnrc_sock: warn about non-zero receive timeouts with sock_async

- sys/include/net/gnrc/netif/conf.h
- sys/net/gnrc/netif/Kconfig
- sys/net/gnrc/netif/gnrc_netif.c
For a set of my currently ongoing experiments it is important that the 6LoWPAN header stays roughly the same over all hops. With global addresses this can easily be achieved by not configuring a compression context. However, when using a border router with UHCP or DHCPv6, the compression context will be configured automatically and when you try to delete it, it is most often to late, as the prefix and the compression contexts are already disseminated throughout the network (and any further auto config message for the prefix might re-add it).
This change makes the auto-configuration of the compression context by setting the Kconfig variable `CONFIG_GNRC_NETIF_IPV6_DO_NOT_COMP_PREFIX` to false.
Flash and run the `examples/gnrc_border_router` twice: Once as is, and once with the new option …
> gnrc_netif: make auto-config of compression context optional

- makefiles/features_modules.inc.mk
None of the periph_gpio_ll* features provides or requires a `periph_init` hook. Hence, blacklist them for `periph_init` conversion.
E.g. run `$ make BOARD=nucleo-f767zi info-modules -C tests/periph_gpio_ll/ | grep gpio_ll`.
In addition, this should not change binaries in any way.
```
$ make BOARD=nucleo-f767zi info-modules -C tests/periph_gpio_ll/ | grep gpio_ll
make: Entering directory '/home/maribu/Repos/software/RIOT/tests/periph_gpio_ll'
periph_gpio_ll
periph_gpio_ll_irq
periph_gpio_ll_irq_level_triggered_high
periph_gpio_ll_irq_level_triggered_low
periph_init_gpio_ll
periph_init_gpio_ll_irq
periph_init_gpio_ll_irq_level_triggered_high
periph_init_gpio_ll_irq_level_triggered_low
make: Leaving directory '/home/maribu/Repos/software/RIOT/tests/periph_gpio_ll'
```
```
$ make …
```
> build system: no periph_init for periph_gpio_ll*

- drivers/st7735/Kconfig
In #17903 the st7735 feature was selected, but the symbol was actually not defined. Seems to be the cause for the current failures in the nightlies CI run.
- Green CI
- Compare that the list of modules with and without Kconfig
#17903
> drivers/st7735/kconfig: add hardware feature symbol

- core/lib/bitarithm.c
- core/lib/include/bitarithm.h
Work around a [transpilation issue](https://github.com/immunant/c2rust/issues/423) in bitarithm.h that'd be triggered if bitarithm.h were included through any header file transpiled through C2Rust.
This is a temporary workaround that unblocks cases when this would make Rust builds fail; once a newer C2Rust version is in CI, it can be reverted.
* Make bitarithm.h visible to C2Rust, eg. by working from https://github.com/RIOT-OS/RIOT/pull/17962, or more easily by applying
```patch
diff --git a/core/lib/include/irq.h b/core/lib/include/irq.h
index 25b609f95b..b84bf6819f 100644
--- a/core/lib/include/irq.h
+++ b/core/lib/include/irq.h
@@ -24,6 +24,7 @@
#include <stdbool.h>
#include "cpu_conf.h"
+#include <bitarithm.h>
#ifdef __cplusplus
extern "C" {
```
* Build the rust-hello-world example …
> bitarithm: Move `extern const` out of static inline functions

- sys/net/gnrc/netreg/gnrc_netreg.c
If there are still messages in the mbox when `gnrc_netreg_unregister()` is called, we must release the associated pktbuf snips, otherwise they are leaked away forever.
E.g. `sock_udp_close()` was called without receiving all messages with `sock_udp_recv()`.
Move the `sock_udp_create()` into the sender thread loop of #18142, followed by a `sock_udp_close()` after the `ztimer_sleep()`.
The application will leak all the echo messages that are still in the mbox associated with the closed socket. With this patch, this pktbuf leak is gone.
> gnrc_netreg: drain mbox on unregister

- sys/net/gnrc/Makefile.dep
- sys/net/gnrc/netif/Kconfig
- sys/net/gnrc/netif/pktq/Kconfig
This fixes an issue [uncovered in the recent release tests](https://github.com/RIOT-OS/RIOT/runs/6634316502?check_suite_focus=true#step:14:281), which according to `git bisect` is a problem ever since https://github.com/RIOT-OS/RIOT/commit/3a0e5fd7753475087cefec92c1ef155a23312273 was merged.
While this linking issue could also be solved by adding `USEMODULE += gnrc` to `tests/unittests/tests-gnrc_netif_pktq/Makefile.include`, removing `gnrc_netif` as a dependency for `gnrc_netif_pktq` keeps the unittests more minimal, so I decided to go for that direction.
Run (1)
```console
$ make -C tests/unittests test-gnrc_netif_pktq
```
for `native` and then, if it succeeds (2)
```console
$ make -C tests/unittests test
```
(`make -C tests/unittests test-gnrc_netif_pktq test` may **not** work due to …
> gnrc: gnrc_netif etc. modules are not required by gnrc_netif_pktq

- sys/include/net/sock/udp.h
If a socket is created we must also call sock_udp_recv() on it as otherwise messages will get stuck in it's queue until the socket is closed (which might be never).
If applications only want to send without receiving, they must use sock_udp_send().
> sys/net/sock: add a word of warning to sock_udp_create()

- pkg/fatfs/Makefile.dep
- pkg/fatfs/Makefile.include
- sys/shell/commands/Makefile
- sys/shell/commands/shell_commands.c
`rtt_rtc` implements the same interface as `periph_rtc`, so enable the `rtc` shell command and RTC support in fatfs if it's used.
> pkg/fatfs, shell: enable RTC support if rtt_rtc is used

- boards/same54-xpro/Kconfig
- boards/same54-xpro/Makefile.dep
- boards/same54-xpro/board.c
- boards/same54-xpro/include/board.h
- boards/same54-xpro/include/periph_conf.h
- cpu/sam0_common/Makefile
- cpu/sam0_common/include/mtd_sam0_sdhc.h
- cpu/sam0_common/include/sdhc.h
- cpu/sam0_common/sam0_sdhc/Makefile
- cpu/sam0_common/sam0_sdhc/mtd_sdhc.c
- cpu/sam0_common/sam0_sdhc/sdhc.c
- cpu/sam0_common/sam0_sdhc/vendor/sd_mmc_protocol.h
- cpu/samd5x/include/periph_cpu.h
- dist/tools/doccheck/exclude_patterns
- drivers/mtd/Kconfig
- sys/include/vfs_default.h
This implements support for the SD/MMC host controller found on SAM D5x/E5x family chips.
It is based on the code from [initmaker](https://github.com/alkgrove/initmaker) (and the accompanying [blog post](http://www.alkgrove.com/articles/SAMD51_MicroSD_article.html)) with interrupt support instead of busy-waiting.
Insert an SD card into the SD card slot of the `same54-xpro`
`tests/mtd_raw` should work:
```
2022-03-25 11:57:43,168 # main(): This is RIOT! (Version: 2022.04-devel-912-g8732f-sam0_sdhc)
2022-03-25 11:57:43,169 # Manual MTD test
2022-03-25 11:57:43,173 # init MTD_0… OK (32 MiB)
2022-03-25 11:57:43,176 # init MTD_1… OK (256 byte)
2022-03-25 11:57:43,210 # init MTD_2… OK (7580 MiB)
> test 2
2022-03-25 11:57:44,557 # test 2
2022-03-25 11:57:44,558 # [START]
2022-03-25 11:57:44,588 …
```
> cpu/samd5x: add SD Host Controller implementation

- .cargo/config.toml
- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- tests/rust_minimal/Cargo.lock
With Rust crate repositories currently being created in the RIOT group, this uses the repositories, allowing maintainers (with the usual ACKs) to fix breakage without the need to go through a crates.io release.
This enacts a switch discussed in a recent maintainers meeting.
* Green CI
* Check whether the referenced repositories have something CI-like set up.
> Rust: Build from git branches

- cpu/native/include/netdev_tap.h
- cpu/native/netdev_tap/netdev_tap.c
- cpu/native/startup.c
- pkg/lwip/init_devs/auto_init_netdev_tap.c
- sys/net/gnrc/netif/init_devs/auto_init_netdev_tap.c
`netdev_tap` is a virtual interface, make it possible to simulate both a wired and a wireless interface.
```
$ bin/native/gnrc_networking.elf tap0
Iface  6  HWaddr: 7A:37:FC:7D:1A:AF 
L2-PDU:1500  MTU:1500  HL:64  RTR  
RTR_ADV  
--->      Link type: wired
inet6 addr: fe80::7837:fcff:fe7d:1aaf  scope: link  VAL
inet6 group: ff02::1:ff7d:1aaf
inet6 group: ff02::1a
Statistics for Layer 2
RX packets 4  bytes 480
TX packets 1 (Multicast: 1)  bytes 78
TX succeeded 1 errors 0
Statistics for IPv6
RX packets 4  bytes 424
TX packets 1 (Multicast: 1)  bytes 64
TX succeeded 1 errors 0
```
```
$ bin/native/gnrc_networking.elf -w tap0
Iface  6  HWaddr: 7A:37:FC:7D:1A:AF 
L2-PDU:1500  MTU:1500  HL:64  RTR  
RTR_ADV  
Source address …
```
> netdev_tap: make 'wired' property configurable

- sys/net/gnrc/netif/pktq/gnrc_netif_pktq.c
The `_get_free_entry()` accesses a static buffer, so we must protect it from concurrent access to avoid corruption.
Run the `examples/gnrc_border_router` on e.g. a `nrf52840dk` with another node in the network, in my case an `avr-rss2` which got the address `2001:db8::fec2:3d00:0:bb1`.
Now start two pings in parallel on your host machine:
ping -A 2001:db8::fec2:3d00:0:bb1 -s 512
sudo ping -f 2001:db8::fec2:3d00:0:bb1
On `master` this will crash & burn:
```
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
Stack pointer corrupted, reset to top …
```
> gnrc_netif_pktq: protect against concurrent access

- examples/gnrc_minimal/Makefile
- examples/gnrc_networking/Makefile
- tests/periph_timer/Makefile
This PR adds `esp32-ci` and `esp8266-ci` as external boards to following tests/examples to cover all optional modules by CI compilation:
- `tests/periph_timer` to compile `esp_hw_counter` (ESP32)
- `tests/periph_timer` to compile `esp_sw_timer` (ESP8266)
- `examples/gnrc_networking` to compile `esp_wifi_ap` (ESP32 and ESP8266)
- `examples/gnrc_minimal` to compile `esp_wifi_enterprise` (ESP32)
Green CI
Missing compilations were found in PR https://github.com/RIOT-OS/RIOT/pull/17601#issuecomment-1139553202
> cpu/esp: add compilation tests for optional ESP modules

- cpu/esp_common/Makefile.dep
- cpu/esp_common/periph/flash.c
SPIFFS appears to be what's configured by default on the SPI flash of the esp* boards, so also configure that in RIOT.
LittleFS2 would IMHO be a better choice as it's the faster, more advanced and better maintained filesystem, but it appears as if the esp* boards ship with SPIFFS by default.
I don't have any esp* board still in mint condition to confirm that though.
If there is no such thing as a 'default fs' on those boards, I think we should go with littlefs2 instead.
Run `tests/vfs_default`.
The SPI flash should be mounted to `/nvm0`.
> cpu/esp_common: use LittleFS2 as default FS

- drivers/mtd_mapper/mtd_mapper.c
- tests/mtd_mapper/main.c
A MTD mapper region must adhere to the same physical constraints as the underlying MTD device, so inherit it's physical properties instead of relying on the user to set them correctly.
`tests/mtd_mapper` still works without the redundant information
```
s
START
main(): This is RIOT! (Version: 2022.07-devel-448-ge28040-drivers/mtd_mapper-inherit)
......
OK (6 tests)
{ "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 436 }]}
{ "threads": [{ "name": "main", "stack_size": 12288, "stack_used": 2508 }]}
```
> drivers/mtd_mapper: inherit physical properties

- sys/fmt/fmt.c
- tests/fmt_print/main.c
Mixing `print*()` from `fmt.h` with `puts()` `*printf()` from `stdio.h` results in corrupted output even with only one thread printing. That's an obvious footgun. This fixes the issue.
The first commit extends `tests/fmt_print` to detect output corruptions when mixing with `stdio.h` (this should fail on `master`). The second fixes the issue (so it should pass again after the second commit).
Alternative to dropping the use of `fmt` in https://github.com/RIOT-OS/RIOT/pull/18161
> sys/fmt: disarm footgun

- cpu/esp32/esp-idf/esp_idf_support.c
- pkg/esp32_sdk/Makefile
- pkg/esp32_sdk/patches/0001-esp_hw_support-rename-rtc_init.patch
- pkg/esp32_sdk/patches/0003-wpa_supplicant-declare-variables-in-header-files-as-.patch
- pkg/esp32_sdk/patches/0006-compilation-include-missing-header-files.patch
- pkg/esp32_sdk_lib_phy/Makefile
- pkg/esp32_sdk_lib_wifi/Makefile
This updates the ESP-IDF package to the latest tagged version.
Only the [esp32-wifi-lib](https://github.com/espressif/esp32-wifi-lib) could not be updated to the latest version as the current RIOT drivers will crash after [c73ee33](https://github.com/espressif/esp32-wifi-lib/commit/c73ee337c334597378e79219c9f59525116437d2) - `Remove legacy system event framework(1948a1c7)`.
`examples/gnrc_border_router` still works with `esp_now` and `esp_wifi`.
```
2022-06-02 23:55:01,101 # main(): This is RIOT! (Version: 2022.07-devel-646-g95f8ce-pkg/esp32_sdk-4.4.1)
2022-06-02 23:55:01,105 # RIOT border router example application
2022-06-02 23:55:01,107 # All up, running the shell now
2022-06-02 23:57:14,345 # Iface  10  HWaddr: 3C:71:BF:9E:13:FC  Channel: 1  Link: up 
2022-06-02 23:57:14,349 # …
```
> pkg/esp32_sdk: Update version to 4.4.1 

- cpu/sam0_common/periph/rtc_rtt.c
`rtt_get_counter()` already waits for syncbusy before reading the time, but we also have to do this in RTC mode (`rtc_get_time()`) to avoid reading old values.
Thus, always wait for syncbusy to clear when accessing the COUNT register.
> cpu/sam0_common: RTC: wait for syncbusy in rtc_get_time()

- examples/gnrc_minimal/main.c
- examples/nanocoap_server/Makefile
- examples/nanocoap_server/main.c
- examples/telnet_server/main.c
- sys/include/net/ipv6/addr.h
- sys/include/net/netif.h
- sys/net/netif/netif.c
- sys/net/network_layer/ipv6/addr/ipv6_addr.c
- tests/pkg_microcoap/Makefile
- tests/pkg_microcoap/main.c
At a few places this was already either done by hand or via an ugly hack to call the shell handler if `ifconfig` from C, so apparently there is a use for it. In addition, the hack of calling a single shell handler doesn't work well with XFA, as XFA items are not subject to link time garbage collection.
Run `examples/gnrc_minimal` and it should still print all IPv6 address (but now as JSON, because that's what cool kids do now).
```
2022-06-02 12:30:55,146 # RIOT network stack example application
2022-06-02 12:30:55,159 # {"IPv6 addresses": ["fe80::a04d:49ff:fe6f:54ff", "fe80::ff:fe00:ff", "fe80::4c49:6f54:4f76:1ff", "fe80::4c49:6f54:4f76:ff", "fe80::4c49:6fff:fe54:ff"]}
```
Needed for https://github.com/RIOT-OS/RIOT/pull/18152
> sys/net/netif: add convenience functions for getting/printing IPv6 addresses

- boards/common/cc26xx_cc13xx/Makefile.include
- boards/common/nucleo/Makefile.include
- boards/nrf52840dk/Makefile.include
- boards/same54-xpro/Makefile.include
- boards/samr21-xpro/Makefile.include
- dist/tools/usb-serial/ttys.py
- makefiles/tools/serial.inc.mk
- extend `dist/tools/usb-serial/ttys.py` with a `--ifcae-num` parameter
- the CC2650-Launchpad exposes two USB serials, but only one is the UART bridge. The USB iface number is the only stable difference between the two
- introduce `TTY_BOARD_FILTER` to let boards provide flags for `dist/tools/usb-serial/ttys.py` to filter only matching USB serials
- if port selection via `MOST_RECENT_PORT=1` is enabled, this will fist apply the filter and select the most recent port of the matching USB serials (if more than one)
- provide `TTY_BOARD_FILTER` for a couple of boards
- This will allow having a `same54-xpro`, `nrf52840dk`, `nucleo-f767zi`, and a `cc2650-launchpad` plugged in and `make BOARD=<foo> MOST_RECENT_PORT=1 term` will always pick the right USB serial
- Beware: It cannot tell apart two …
> buid system: improve serial port selection

- examples/suit_update/Makefile
- sys/Makefile.dep
- sys/include/suit.h
- sys/include/suit/transport/vfs.h
- sys/shell/commands/Makefile
- sys/shell/commands/shell_commands.c
- sys/suit/handlers_command_seq.c
- sys/suit/transport/coap.c
- sys/suit/transport/vfs.c
- sys/suit/transport/worker.c
- tests/suit_manifest/main.c
This allows to load firmware updates from files on local storage.
make SUIT_COAP_ROOT=file:///sd0/fw suit/publish
Place the two slot files as well as the latest manifest on an SD card in the `fw/` folder.
```
> suit fetch file:///nvm0/fw/riot.suit.1653475132.bin
2022-05-25 12:52:51,855 # suit fetch file:///nvm0/fw/riot.suit.1653475132.bin
2022-05-25 12:52:51,858 # suit_worker: trigger received
2022-05-25 12:52:51,864 # suit_worker: downloading "file:///nvm0/fw/riot.suit.1653475132.bin"
2022-05-25 12:52:51,874 # suit_worker: got manifest with size 421
2022-05-25 12:52:51,877 # suit: verifying manifest signature
2022-05-25 12:52:53,020 # suit: validated manifest version
2022-05-25 12:52:53,025 # )Manifest seq_no: 1653475132, highest available: 1653474249
2022-05-25 12:52:53,028 # suit: …
```
> suit/transport/vfs: add VFS as source for firmware updates

- fuzzing/README.md
The [documentation](https://aflplus.plus/docs/parallel_fuzzing/#2-single-system-parallelization
) says
> Note that you must always have one -M main instance!
> Running multiple -M instances is wasteful!
Run
make -C fuzzing/gcoap AFL_SKIP_CPUFREQ=1 AFL_FLAGS="-M fuzzer0" all fuzz
and
make -C fuzzing/gcoap AFL_SKIP_CPUFREQ=1 AFL_FLAGS="-S fuzzer01" fuzz
> fuzzing: fix parameter for second fuzzing instance in README.md

- examples/telnet_server/Makefile
- examples/telnet_server/main.c
Just enables the telnet example to be build with LWIP.
Just build the `examples/telnet_server` with `LWIP=1`
Output is a bit broken compared to GNRC:
```
% telnet fe80:0:0:0:7837:fcff:fe7d:1aaf%tapbr0
Trying fe80::7837:fcff:fe7d:1aaf%tapbr0...
Connected to fe80:0:0:0:7837:fcff:fe7d:1aaf%tapbr0.
Escape character is '^]'.
RIOT telnet example application╔═══════════════════════════════════════════════════╗║telnet is entirely unencrypted and unauthenticated.║║Do not use this on public networks.                ║╚═══════════════════════════════════════════════════╝ps
p
s
pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
- | isr_stack            | -        - |   - |   8192 (   -1) ( 8193) |  0x8084880 |  0x8084880
1 | idle                 | …
```
> examples/telnet_server: add support for LWIP

- boards/msba2/Makefile.include
- boards/nrf52dk/Makefile.include
As trivial as the title says.
I used this for testing:
```diff
diff --git a/Makefile.include b/Makefile.include
index d8fd372480..9ca4948a17 100644
--- a/Makefile.include
+++ b/Makefile.include
@@ -876,8 +876,13 @@ cleanterm: $(TERMDEPS)
$(call check_cmd,$(TERMPROG),Terminal program)
$(TERMPROG) $(TERMFLAGS) $(TERMTEE)
+# Allow testing TTY_BOARD_FILTER by explicitly setting the board from command
+# line.
+ifeq ($(origin BOARD),command line)
+  LIST_TTYS_FILTER := $(TTY_BOARD_FILTER)
+endif
list-ttys:
-    $(Q)$(RIOTTOOLS)/usb-serial/ttys.py
+    $(Q)$(RIOTTOOLS)/usb-serial/ttys.py $(LIST_TTYS_FILTER)
doc:
$(MAKE) -BC $(RIOTBASE) doc
```
The `make list-ttys BOARD=msba` only listed the MSB-A2 board, and same for the nRF52DK.
None
> boards/{nrf52dk,msba2}: provide TTY_BOARD_FILTER

- drivers/mtd/mtd.c
If init fails (e.g. because an SD card was not inserted) don't fail the `mtd->write_size != 0` assertion but instead return early.
Run `tests/mtd_raw` without an SD card on `same54-xpro`
```
2022-06-07 00:47:51,353 # Manual MTD test
2022-06-07 00:47:51,356 # init MTD_0… OK (8 MiB)
2022-06-07 00:47:51,360 # init MTD_1… OK (256 byte)
2022-06-07 00:47:51,362 # init MTD_2… 0xd5f
2022-06-07 00:47:51,364 # *** RIOT kernel panic:
2022-06-07 00:47:51,365 # FAILED ASSERTION.
2022-06-07 00:47:51,366 # 
2022-06-07 00:47:51,367 # *** halted.
2022-06-07 00:47:51,367 # 
2022-06-07 00:47:51,367 # 
2022-06-07 00:47:51,369 # Context before hardfault:
2022-06-07 00:47:51,371 #    r0: 0x0000000a
2022-06-07 00:47:51,372 #    r1: 0x00000000
2022-06-07 00:47:51,374 #    r2: 0xc0000000
2022-06-07 00:47:51,375 # …
```
> drivers/mtd: return early if init fails

- boards/common/cc26xx_cc13xx/Makefile.include
- boards/common/nrf52/Makefile.include
For nRF52xxx and CC26xx and CC13xx MCUs J-Link and uniflash are currently chosen as default flashers, without checking if they are available. This adds a check and only picks them as default if they are available, falling back to OpenOCD when not. Behavior should remain unchanged for happy users of J-Link and uniflash, but life should be better for those who prefer to stick with OpenOCD.
`make flash` should now work out of the box when OpenOCD is installed but J-Link and uniflash are not, but should not change when there are available.
None
> boards/common/{nrf52,cc26xx_cc13xx}: improve default programmer selection

- dist/tools/zep_dispatch/topogen.sh
With this patch, any custom topology will remain unaltered after run command execution. This also allows random topology generation.
Create a new custom file topology [filenew.topo] in the folder /tools/zep_dispatch. Then, run:
```
make run TOPOLOGY= filenew.topo
```
Then check that filenew.topo remain unaltered.
For random generation, check:
```
make run
```
Fixes #18169
> tools/zep_dispatch: run dispatch with custom topology

- examples/telnet_server/main.c
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/Makefile.include
- sys/include/net/telnet.h
- sys/include/shell_lock.h
- sys/net/application_layer/telnet/telnet_server.c
- sys/shell/shell.c
- sys/shell_lock/Makefile
- sys/shell_lock/Makefile.include
- sys/shell_lock/shell_lock.c
- tests/shell_lock/Makefile
- tests/shell_lock/Makefile.ci
- tests/shell_lock/main.c
- tests/shell_lock/tests/01-run.py
This PR adds a locking mechanism to the shell, implemented by the new `shell_lock` module. It's not meant as a super secure system protection, it should rather be thought of as a small simple protection for demo environment purposes. For example, I recently raised a PR (#12012) for stdio over Blueooth. I might want to show a demo and control my project via bluetooth and I don't want other people to be able to connect to my device and use the shell. Using this new module you have to type in a password first. The mentioned bluetooth service only allows a single connection per device, that is an assumption that needs to be maintained, because there is only a single shell instance per device. A second user would get access to the previous unlocked shell by another user otherwise. Furthermore …
> sys/shell: new module shell_lock 

- makefiles/vars.inc.mk
- pkg/c25519/Makefile
- pkg/edhoc-c/Makefile
- pkg/mynewt-core/Makefile
- pkg/pkg.mk
Silence most pkg clonning/handling related logs when QUIETER is set.
For some reason event though `--quiet` is passed I still get the progress report:
```
Building application "tests_pkg_edhoc_c" for "native" with MCU "native".
2022-04-28 14:07:29 URL:https://www.dlbeer.co.nz/downloads/c25519-2017-10-05.zip [68419/68419] -> "/home/francisco/workspace/RIOT/build/pkg/c25519-2017-10-05.zip" [1]
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 111 (delta 14), reused 71 (delta 7), pack-reused 0
Receiving objects: 100% (111/111), 188.56 KiB | 3.85 MiB/s, done.
Resolving deltas: 100% (14/14), done.
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: …
```
> pkg/pkg.mk: silence info if QUIETER

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- tests/rust_minimal/Cargo.lock
This updates riot-sys and riot-wrappers to their latest git versions (along with some other crates mainly from the build system), providing:
* Add and use the coap_request_ctx_t marker for https://github.com/RIOT-OS/RIOT/pull/17957
* If that PR goes through as it is now, its API change is hidden from Rust users already with the latest changes here.
* Avoid theoretical undefined behavior around packed structs. (This was always there, but rustc is becoming stricter; this also unblocks the next CI upgrade where the nightly version would be bumped).
* Remove legacy code (for supporting RIOT before 2022.04), and cleanups.
(and a lot of README, CI and URI updates that are not really visible inside RIOT)
* Green CI (with tests enabled)
> rust: Update versions

- boards/samd20-xpro/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
We can't use PB13/PB12 which would be the 'standard' UART pins on the -xpro EXT connectors since only SERCOM4 can map to those - and that's already used on EXT1.
So use the adjacent PA08/PA09 with SERCOM0.
Run `tests/periph_uart` with the UART pins connected
```
2022-06-09 13:10:58,792 - INFO # Manual UART driver test application
2022-06-09 13:10:58,795 - INFO # ===================================
2022-06-09 13:10:58,800 - INFO # This application is intended for testing additional UART
2022-06-09 13:10:58,806 - INFO # interfaces, that might be defined for a board. The 'primary' UART
2022-06-09 13:10:58,811 - INFO # interface is tested implicitly, as it is running the shell...
2022-06-09 13:10:58,811 - INFO # 
2022-06-09 13:10:58,817 - INFO # When receiving data on one of the additional …
```
> boards/samd20-xpro: add definition for UART on EXT2

- sys/fmt/fmt.c
- sys/net/network_layer/ipv6/addr/ipv6_addr.c
- tests/fmt_print/main.c
As the title says (hopefully...). It works at least with `riot/riotbuild`, but it also did so before...
I also sneaked in a fix for `ipv6_addrs_print()` that is unrelated, but equally trivial.
E.g. `examples/telnet_server` should now print the IPv6 address.
Alternative to https://github.com/RIOT-OS/RIOT/pull/18183
> sys/fmt: fix output on native

- sys/include/rtc_utils.h
As the the title says, this PR fixes a copy and paste error in the documentation of function `rtc_mktime`.
`make doc` and check that the documented precondition for `rtc_mktime` is correct.
> sys/rtc_utils: small doc fix of rtc_mktime

- drivers/rtt_rtc/rtt_rtc.c
This PR provides a small fix of function `rtc_set_alarm` in module `rtt_rtc`.
Function `rtc_set_alarm` in module `rtt_rtc` calls function `rtc_mktime` which expects that the given time structure is normalized.
Use an ESP32 module to compile and test `tests/periph_rtc` where the alarm time is calculated by incrementing the seconds only.
Output without this PR:
```
RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
Setting alarm to   2020-02-28 23:59:59
Alarm is set to   2020-02-28 23:59:59
Alarm cleared at   2020-02-28 23:59:57
No alarm at   2020-02-28 23:59:59
Setting alarm to   2020-02-29 23:59:61     <================
```
Output with this PR:
```
RIOT RTC low-level …
```
> drivers/rtt_rtc: normalize tm struct in rtc_set_alarm

- sys/fs/constfs/constfs.c
- sys/include/fs/constfs.h
Don't require data to be a `uint8_t` array to to be casted into one.
No changes to the binary, but `constfs` can be used a bit more ergonomically.
> sys/fs/constfs: allow to host arbitrary data

- dist/tools/kconfiglib/genconfig.py
- dist/tools/kconfiglib/riot_kconfig.py
This removes the existing hack, in which we wrote the configuration to `/dev/null` to trigger its evaluation. Instead a function for this specific purpose is added. Besides being cleaner, it avoids issues like the one reported at https://forum.riot-os.org/t/kconfig-issues-in-riot/3646.
- To verify that configuration issues are still being caught, you can apply an invalid one like the following in the kconfig test app, and run `make`:
```diff
diff --git a/tests/kconfig/Kconfig b/tests/kconfig/Kconfig
index c18dffdd8f..cbfec4b519 100644
--- a/tests/kconfig/Kconfig
+++ b/tests/kconfig/Kconfig
@@ -20,3 +20,8 @@ config APP_MSG_2
Activate printing the second message
endmenu # Application
+
+config FOO_VALUE
+    int "Foo"
+    range 1 3
+    default 4
```
- Green CI
Forum post …
> dist/tools/kconfiglib: add configuration evaluation function

- drivers/hd44780/hd44780.c
- drivers/hd44780/include/hd44780_params.h
There are tons of cheap alphanumeric displays with a dimension of 2 x 16 characters that are controlled by a HD44780 over an I2C interface.
The I2C interface of these displays is simply realized by an I2C 8bit I/O expander which provides the I2C interface and is connected to the pins of the HD44780. All these I2C displays use either PCF8574 or PCF8574A for this purpose. That is, using the HD44780 driver togehter with PCF8574 driver work as driver for these displays.
This PR provides small changes of the HD44780 driver which demonstrates how it is possible to use it together with the PCF857X driver as provided in PR #10430. The PR requires some more work, e.g., an approach on how to define and initialize the PCF8574.
Fetch PR #10430 and this PR. Checkout this PR and rebase it onto PR …
> drivers/hd44780: PCF857x I2C interface added

- dist/tools/compile_commands/compile_commands.py
`detect_includes_and_version_gcc()` previously only detected the includes, but has been extended to also return the version. This is done by returning a tuple, with the first item being the list of include paths, and the second being the version. In the error handling the script still returns only an empty list of includes, but not an empty version. This
fixes the issue.
`make compile-commands` should now also work even when the toolchain is not installed, rather than crash.
```
$ make BOARD=esp32-ttgo-t-beam compile-commands
[...]
Compiler xtensa-esp32-elf-gcc not found, not adding system include paths
File "/home/maribu/Repos/software/RIOT/dist/tools/compile_commands/compile_commands.py", line 328, in <module>
generate_compile_commands(_args)
File …
```
> dist/tools/compile_commands: fix error handling

- dist/tools/compile_commands/compile_commands.py
In clangd mode drop a number of compiler flags not supported by LLVM.
Run `make compile-commands BOARD=<SOME-ESP32-board> -C examples/default` and open a C file with an editor that uses clangd as language server (e.g. vim/neovim with ALE, or VS Code). In `master` clangd should be really unhappy, with this it should provide decent linting/analysis/code completion/....
None
> dist/tools/compile_commands: fix clangd mode with ESP32

- pkg/driver_atwinc15x0/patches/0007-nmasic-always-use-2000-retries.patch
- pkg/driver_atwinc15x0/patches/0008-nmasic-limit-retries-in-wait_for_bootrom.patch
- pkg/driver_atwinc15x0/patches/0009-nmasic-limit-retries-in-chip_apply_conf.patch
This enables a timeout on init to not hang there forever if init fails but instead return an error.
Run `tests/driver_atwinc15x0` on any board without the module connected.
On `master` this would hang indefinitely, with this patch you get
```
[atwinc15x0] Driver initialization error -5
2022-06-15 18:18:09,854 - INFO # gnrc_netif: init failed: -5
2022-06-15 18:18:09,859 - INFO # main(): This is RIOT! (Version: 2022.07-devel-770-g9827e)
2022-06-15 18:18:09,859 - INFO # >
```
upstream PR https://github.com/arduino-libraries/WiFi101/pull/335
> drivers/atwinc15x0: add timeout to init

- sys/include/net/nanocoap.h
- sys/include/net/nanocoap_vfs.h
- sys/net/application_layer/nanocoap/vfs.c
- sys/shell/commands/sc_nanocoap_vfs.c
- tests/nanocoap_cli/Makefile
This adds a function to upload a file from VFS to a CoAP server via block-wise PUT request.
You can test this with `aiocoap-fileserver -w`:
```
> ncget coap://[fe80::2454:cfff:fea7:4598]/LICENSE
Saved as /nvm0/LICENSE
```
```
> ncput /nvm0/LICENSE coap://[fe80::2454:cfff:fea7:4598]/LICENSE-2
Saved to coap://[fe80::2454:cfff:fea7:4598]/LICENSE-2
```
```
$ md5sum LICENSE*
a4ce26a8dcc018faa99a6cd08cbcd1c3  LICENSE
a4ce26a8dcc018faa99a6cd08cbcd1c3  LICENSE-2
```
depends on ~~#17937~~, ~~#17960~~, ~~#17958~~
> nanocoap_vfs: add nanocoap_vfs_put()

- cpu/esp32/periph/pm.c
This PR fixes the blocking when the `reboot` command is used in shell under certain conditions and the `pm_reboot` function tries to reboot the system.
In the test run of PR #18202 in CI the test of `tests/shell` failed because the system blocks when executing command `reboot` if another command was executed before, see the log, see the [log](https://ci.riot-os.org/RIOT-OS/RIOT/18202/4cf3e1a06c9c05e8a92aed6e938b3cfe90efe69a/output/run_test/tests/shell/esp32-wroom-32:gnu.txt). The reason for this is that the system will block while waiting for the UART interfaces to become idle.
1. Make `BOARD=esp32-wroom-32 make -C tests/shell flash term` and execute:
```
> reboot
> help
> reboot
```
Without this PR, the system blocks on second `reboot` command. With this PR, the command sequence works as …
> cpu/esp32: fix pm_reboot function

- cpu/stm32/Makefile.dep
An network devices that supports `netdev_driver_t::get(NETOPT_LINK, ...)`
also has to emit NETDEV_EVENT_LINK_UP and NETDEV_EVENT_LINK_DOWN with
lwip for IPv6 duplicate address detection to work. The background is
that the STM32 Ethernet MAC requires a periodic timer to poll for the
state to emit these events. For this reason, `stm32_eth_link_up` was
introduced to allow applications to select if they need these events.
With this dependency in place, IPv6 addresses won't get stuck in a
tentative state any more.
```
$ make BOARD=nucleo-f767zi LWIP=1 -C examples/gcoap flash term
[...]
> ifconfig
```
With `master`:
```
ifconfig
Iface ET0 HWaddr: aa:84:9d:12:bb:2d Link: down State: up
inet6 addr: fe80:0:0:0:a884:9dff:fe12:bb2d scope: link state: tentative (0 probes send)
``` …
> cpu/stm32/periph_eth: enable stm32_eth_link_up with lwip_ipv6

- sys/net/application_layer/nanocoap/sock.c
The assertion is a bit overeager.
In case of receiving a wrong message ID, we re-try receive without entering the STATE_REQUEST_SEND state again, so it is expected that we get a non-NULL ctx/response from `sock_udp_recv_buf()`. 
What this assert should actually check is that we don't get a non-NULL ctx after calling `sock_udp_recv_buf()` with a non-NULL ctx.
So make this explicit to not falsely fail the assertion.
CoAP operations should no longer trigger the assertion in the wake of re-transmissions/wrong message IDs.
> nanocoap_sock: fix wrong assertion

- cpu/sam0_common/sam0_sdhc/mtd_sdhc.c
The source / destination address of the SDHC transfer needs to be word-aligned.
Use the mtd buffer to fix the alignment if `mtd_write_page` is used, otherwise return `-ENOTSUP`.
> cpu/sam0_common: mtd_sdhc: ensure source address alignment

- core/lib/include/kernel_defines.h
- sys/include/tm.h
This is not used anywhere in RIOT, but causes conflicts with external library code.
So let's just get rid of this.
Green CI
Was introduced by #689
> core/kernel_defines: drop CONST definition

- Makefile.include
- cpu/mips_pic32mx/Makefile.include
- cpu/mips_pic32mz/Makefile.include
- makefiles/tests/tests.inc.mk
Let's consider firmwares as identical if their binfiles are matching, e.g. in case the `.debug` section ends up being different for whatever reason.
This hopefully makes sure false positives on hash mismatches are a thing of the past.
Murdock should be happy. Even for ESP32 builds, every time.
None
> makefiles/tests: use BINFILE for hash comparision instead of ELFFILE

- boards/esp32-wrover-kit/include/board.h
- tests/external_board_dirs/esp-ci-boards/esp32-ci/Makefile.include
This PR is a cleanup of the CI compilation of optional ESP module `esp_wifi_enterprise`.
In the board definition of `esp32_wrover_kit`, default values for `ESP_WIFI_EAP_USER` and `ESP_WIFI_EAP_PASS` had to be defined because this board was used in the CI to compile the optional module `esp_wifi_enterprise` (PR #17314).
Now where the CI compilation for the `esp_wifi_enterprise` module is realized by an external board definition `esp32-ci`, these default values should be removed from `esp32_wrover_kit` to let the compilation fail if the user did not define these required variables. Instead, the variables are defined for the CI compilation in `Makefile.include` of external board definition `esp32-ci`.
1. GreenCI
2. `USEMODULE=esp_wifi_enterprise BOARD=esp32-wrover-kit make -j8 -C …
> boards/esp32: cleanup CI compilation for esp_wifi_enterprise

- cpu/cortexm_common/include/vectors_cortexm.h
- cpu/cortexm_common/vectors_cortexm.c
If a user wants to handle NMI events, let them do so by providing an implementation for `nmi_handler()` instead of panicking.
> cpu/cortexm_common: allow to overwrite nmi_handler

- boards/nucleo-f031k6/doc.txt
- boards/nucleo-f042k6/doc.txt
- boards/nucleo-f303k8/doc.txt
- boards/nucleo-l011k4/doc.txt
- boards/nucleo-l031k6/doc.txt
- boards/nucleo-l412kb/doc.txt
- boards/nucleo-l432kc/doc.txt
PR #18057 enables **_cpy2remed_** programmer for all STM Nucleo boards.
This PR adds to nucleo32 boards documentation:
-  information about usage of **_cpy2remed_** programmer,
-  short information about board (used MCU, available RAM and Flash),
-  change all memory sizes to KiB (before kB or Kb are used) .
Changes in documentation can be observed using commands:
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f031k8.html
xdg-open doc/doxygen/html/group__boards__nucleo-l042k6.html
xdg-open doc/doxygen/html/group__boards__nucleo-l011k4.html
xdg-open doc/doxygen/html/group__boards__nucleo-l412kb .html
```
or direct link to files generated by [CI](https://output.circle-artifacts.com/output/job/7534b085-3830-4333-8a3f-667e689d0387/artifacts/0/doc/group__boards__nucleo-f031k6.html …
> boards/nucleo32: doc update - usage of cpy2remed programmer and short overview of board

- cpu/avr8_common/include/cpu.h
- cpu/avr8_common/thread_arch.c
Fixes `cpu_print_last_instruction()` to actually the address a function was called from. It only works reliably if this is the first statement in a function, though.
See https://github.com/RIOT-OS/RIOT/pull/18226
Requested to be split out from https://github.com/RIOT-OS/RIOT/pull/18226#discussion_r901366829
Depends on and includes https://github.com/RIOT-OS/RIOT/pull/18233
> cpu/avr8_common: fix cpu_print_last_instruction

- boards/common/esp32/board_common.c
- boards/common/esp32/include/board_common.h
- boards/esp32-ttgo-t-beam/board.c
- boards/esp32-wrover-kit/board.c
This PR removes `board_init_common` for ESP32 as it is no longer needed.
Since `board_init_common` was empty, green CI should be sufficient.
Split off from PR #17841
> boards/esp32: cleanup board_init_common

- cpu/esp32/Makefile.dep
- cpu/esp_common/Kconfig
- cpu/esp_common/Makefile.dep
- cpu/esp_common/Makefile.include
- cpu/esp_common/freertos/queue.c
- cpu/esp_common/freertos/ringbuf.c
- cpu/esp_common/freertos/semphr.c
- cpu/esp_common/freertos/task.c
- cpu/esp_common/freertos/timers.c
- cpu/esp_common/include/freertos/FreeRTOS.h
- cpu/esp_common/include/freertos/portmacro.h
- cpu/esp_common/include/freertos/queue.h
- cpu/esp_common/include/freertos/ringbuf.h
- cpu/esp_common/include/freertos/semphr.h
- cpu/esp_common/include/freertos/task.h
As discussed in PR #17841, this PR is a split out of the changes and extensions that are required to use the ESP-IDF HAL or LL. It includes:
- fixes for platform independent compilation (figured out in PR #17844)
- implementation of additionally required function `xQueueReset`
- implementation of additionally required function `xSemaphoreGetMutexHolder`
- implementation of additionally required functions `pcTaskGetTaskName` and `uxTaskGetStackHighWaterMark`
- implementation of additionally required functions `pvTaskGetThreadLocalStoragePointer` and `vTaskSetThreadLocalStoragePointerAndDelCallback`
- implementation of additionally required task notification functions `xTaskNotify` and `xTaskNotifyWait`
- implementation of timeout handling in `xQueue*` functions
- implementation of …
> cpu/esp_common: FreeRTOS adaptation layer changes/extension required for ESP-IDF HAL/LL

- cpu/esp32/Makefile.dep
- cpu/esp32/esp-idf/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/esp_idf_wpa_supplicant.mk
- cpu/esp32/esp-idf/wpa_supplicant/esp_supplicant/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/esp_supplicant/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/port/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/port/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/ap/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/ap/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/common/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/common/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/crypto/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/crypto/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/eap_peer/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/eap_peer/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/rsn_supp/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/rsn_supp/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/tls/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/tls/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/utils/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/utils/Makefile
- cpu/esp32/esp-idf/wpa_supplicant/src/wps/Kconfig
- cpu/esp32/esp-idf/wpa_supplicant/src/wps/Makefile
The module `esp_wpa_supplicant` is quite large and its compilation takes a long time. Therefore it is better to split the PR into several submodules.
1. Green CI
2. Compile and test a WiFi example, for example:
```
USEMODULE=esp_wifi CFLAGS=-DESP_WIFI_SSID=\"ssid\" -DESP_WIFI_PASS=\"pass\" \
BOARD=esp32-wroom-32 make -C examples/gnrc_networking flash term
```
Split off from PR #17841
> cpu/esp32: split modul esp_wpa supplicant into several modules

- sys/net/application_layer/nanocoap/sock.c
- sys/net/application_layer/nanocoap/vfs.c
- only print the 'waiting for response' text when we are actually waiting for a response, not freeing the packet
- don't print buffer *before* destination file name has been written to it
-  print remaining retries
> nanocoap_sock: fix debug output

- makefiles/cargo-targets.inc.mk
Experienced RIOT users, when building Rust based examples for the first time, can easily miss subtle parts of the required tooling when not installing through BUILD_IN_DOCKER.
To enhance the user experience, this adds a few checks to the builds to ensure that usable error messages are produced before kicking off the Rust tools, which do generally provide good error output, but [currently not in the most concise way](https://github.com/rust-lang/rust/issues/97685) and generally not by pointing to the relevant RIOT related documentation).
[edit] To some extent the tests may be overly strict (eg. it tests for the presence of rustup, which technically is not required); the error message shown then explains why that is usually necessary and also guides about what to do if the ecosystem changes …
> makefiles/rust: Err early, provide suggestions

- sys/net/gnrc/pktbuf/include/pktbuf_internal.h
- sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
This overwrites the memory of the pktbuf chunk with a canary value and checks if the value is still there on allocation.
Enable the option with `CFLAGS += -DCONFIG_GNRC_PKTBUF_CHECK_USE_AFTER_FREE=1`.
This should now catch errors where a pktbuf chunk is written to after its been freed:
```
2022-06-17 19:52:45,990 # [0x2000ebf4] mismatch at offset 392/600
2022-06-17 19:52:45,997 # 00000000  55  55  55  55  DD  16  55  55  55  55  55  55  55  55  55  55
2022-06-17 19:52:46,002 # 00000010  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55
2022-06-17 19:52:46,009 # 00000020  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55
2022-06-17 19:52:46,015 # 00000030  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55  55
2022-06-17 19:52:46,022 # 00000040  55  55  55 …
```
> sys/net/gnrc_pktbuf_static: add use-after-free detection

- doc/doxygen/src/using-rust.md
- examples/rust-gcoap/Makefile
- examples/rust-hello-world/Makefile
- makefiles/cargo-settings.inc.mk
Examples have previously relied on the (really: some) nightly toolchain
to be the default. As that, in practice, is a problematic assumption,
the latest toolchain to use is now determined programmatically, and that
is set explicitly on the examples that use nightly.
Workaround-For: https://github.com/rust-lang/rustup/issues/3015
---
This is somewhat related to https://github.com/RIOT-OS/RIOT/pull/18220 -- but they should complement each other transparently enough that merging them in any order should do the right thing.
* CI still passes
* Set your Rust to any of `rustup default nightly` or `rustup default stable`, or set a `rustup override`, and the examples should still all build, with and without BUILD_IN_DOCKER=1.
(Even a rust-toolchain.yaml file should be ignored in the examples -- …
> rust: Explicitly select nightly

- sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
The bug I was hunting wasn't a use after free after all. Don't let the user think that this is the only kind of malady that triggers this test.
> sys/net/gnrc_pktbuf_static: fix documentation of use-after-free detection

- cpu/esp_common/esp-wifi/esp_wifi_netdev.c
- cpu/esp_common/include/esp_common.h
- cpu/esp_common/include/gpio_arch_common.h
- cpu/esp_common/periph/i2c_sw.c
- makefiles/tools/esptool.inc.mk
This PR is a split-off from PR #17841. It provides the following changes to allow the compilation for different ESP32x SoC variants:
- `MCU_*` conditionals in source code are inverted so that they can be tested for `MCU_ESP8266`. In all other cases the MCU is any ESP32x SoC variant.
- `CPU` conditionals in `esptool.mk` are inverted so that they can be tested for `esp8266`. In all other cases the MCU is any ESP32x SoC variant.
Green CI.
Split-off from PR #17841.
> cpu/esp32: invert MCU_* and CPU* conditionals

- boards/common/arduino-atmega/include/board_common.h
[valentinpi](https://github.com/valentinpi) in Issue #18228 reports BUG with arduino UNO and NANO LED0. 
Investigation of this bug reveals two independent problems:
1. There is a wrong port for LED0_ON, OFF and TOGGLE in **_board_common.h_** for atmega328p and atmega2560 - this PR fix this issue.
2. There are still some problems with _**periph_gpio**_ for atmega. In current RIOT master _**example/blinky**_ did not work. However, when **_2022.04-branch_** is used with fix from this PR everything works fine. Initial workaround for this problem could be merging this commit directly to **_2022.04-branch_**, and temporary using it for atmega. 
Compile and flash  _**example/blinky**_ for arduino uno or mega using current RIOT master - LED0 did not blink.
Switch to **_2022.04-branch_**, apply …
> boards/common/arduino-atmega: fix issue with wrong port for LED0

- cpu/esp32/bootloader/Makefile
This PR is a split-off from PR #17841. It provides a bootloader makefile that can be used for different ESP32x SoC variants.
1. Green CI
```
```
> cpu/esp32: ESP32 SoCx variant independent bootloader makefile

- .murdock
Otherwise, with `-j>1`, test-input-hash might hash before clean has cleaned.
Split from https://github.com/RIOT-OS/RIOT/pull/18236.
> murdock: don't do both "clean" and "test-input-hash" targets

- sys/net/link_layer/eui_provider/eui_provider.c
An EUI provider can provide EUIs for multiple interfaces based on their index.
For this is should get the index of the interface, not the index of the EUI provider.
Before both interfaces would get the same L2 address
```
2022-06-23 13:43:20,211 # Iface 5 HWaddr: 02:00:00:00:20:C7
2022-06-23 13:43:20,215 # L2-PDU:1500 MTU:1500 HL:64 RTR
2022-06-23 13:43:20,218 # Source address length: 6
2022-06-23 13:43:20,219 # Link type: wired
2022-06-23 13:43:20,225 # inet6 addr: fe80::ff:fe00:20c7 scope: link VAL
2022-06-23 13:43:20,228 # inet6 group: ff02::2
2022-06-23 13:43:20,230 # inet6 group: ff02::1
2022-06-23 13:43:20,234 # inet6 group: ff02::1:ff00:20c7
2022-06-23 13:43:20,235 #
2022-06-23 13:43:20,239 # Iface 4 HWaddr: 02:00:00:00:20:C7
2022-06-23 13:43:20,243 # L2-PDU:1500 MTU:1500 HL:64 RTR …
```
> net/eui_provider: provide netif index to EUI provder function

- cpu/esp32/Kconfig
- cpu/esp32/Makefile.dep
- cpu/esp32/Makefile.features
- cpu/esp32/Makefile.include
- cpu/esp32/esp-idf/Kconfig
- cpu/esp32/esp-idf/Makefile
- cpu/esp32/esp-idf/common/Makefile
- cpu/esp32/esp-idf/esp_idf.mk
- cpu/esp32/esp-idf/esp_idf_cflags.mk
- cpu/esp32/esp-idf/nvs_flash/Kconfig
- cpu/esp32/esp-idf/nvs_flash/Makefile
- cpu/esp32/esp-idf/spi_flash/Makefile
- cpu/esp32/esp-idf/wifi/Makefile
- cpu/esp32/periph/Kconfig
- cpu/esp_common/Makefile
- cpu/esp_common/Makefile.dep
- cpu/esp_common/Makefile.include
This PR is a split-off from PR #17841. It provides the changes of all makefiles and Kconfigs that are necessary to allow the compilation for different ESP32x SoC variants.
Green CI.
> cpu/esp32: ESP32x SoC variant independent makefiles

- drivers/mcp2515/include/mcp2515_params.h
`mcp2515_params.h` sets a default value to `rst_pin` which will make it a valid gpio and thus a hardware reset will be always triggered. However the `rst_pin` from the MCP2515 is not available on all boards which makes the hardware reset not effective. This PR is undefining the `rst_pin` by default so that the software reset over SPI will be provided
> drivers/mcp2515: undefine rst_pin

- drivers/ws281x/esp32.c
This PR is a splitt-off from PR #17841. It updates the ESP32 driver to use ESP-IDF CPU HAL.
1. Green CI
2. If the hardware is at hand, compile and test it with:
```
BOARD=esp32-wroom-32 make -C tests/driver_ws281x flash term
```
Split-off from PR #17841.
> drivers/ws281x: update ESP32 driver to use ESP-IDF CPU HAL

- cpu/esp_common/Kconfig
- cpu/esp_common/Makefile
- cpu/esp_common/Makefile.dep
- cpu/esp_common/Makefile.features
- cpu/esp_common/esp-xtensa/Kconfig
- cpu/esp_common/esp-xtensa/Makefile
- cpu/esp_common/esp-xtensa/exceptions.c
- cpu/esp_common/esp-xtensa/irq_arch.c
- cpu/esp_common/esp-xtensa/thread_arch.c
- cpu/esp_common/irq_arch.c
- cpu/esp_common/thread_arch.c
This PR is a splitt-off from PR #17841 and replaces partially PR #18247.
To allow a platform independent implementation of `tread_arch.c`, `irq_arch.c` and `exception.c` for different ESP32x SoC variants, the platform specific code for Xtensa-based ESP SoCs is moved to the separate module `esp_xtensa`.
** Background**
The file `thread_arch.c` in module `esp_xtensa` is not really independent of the used ESP SoC. Although ESP8266 and ESP32 share most of the code, that's why `thread_arch.c` is defined in module `esp_xtensa` in `cpu/esp_common`, they require some SoC specific code, especially in `thread_yield_*` functions. These functions are something very special to ESP SoCs and not common for Xtensa cores. That is, the Xtensa code is not general enough to justify a `cpu/xtensa_common` …
> cpu/esp32: move platform code for Xtensa-based ESP32x SoCs to module esp_xtensa

- cpu/esp32/Kconfig
- cpu/esp32/Makefile
- cpu/esp32/Makefile.dep
- cpu/esp32/esp-idf-api/Kconfig
- cpu/esp32/esp-idf-api/Makefile
- cpu/esp32/esp-idf-api/doc.txt
- cpu/esp32/esp-idf-api/periph_ctrl.c
- cpu/esp32/include/esp_idf_api/periph_ctrl.h
This PR is a split-off from PR #17841. It adds the basic structure for an API which is used for ESP-IDF types and functions that are required by RIOT-OS but cannot be included directly due to naming conflicts.
For this purpose, the header files of this API declare the types and functions that are required from the ESP-IDF, but without using the ESP-IDF header files to avoid conflicting names. The implementation of the API then uses the ESP-IDF. In most cases, simple wrapper functions are sufficient.
Since the basic structure of the API contains almost no functionality, a green CI is sufficient.
> cpu/esp32: add ESP-IDF API

- dist/tools/doccheck/exclude_patterns
- drivers/mcp2515/candev_mcp2515.c
- drivers/mcp2515/mcp2515.c
- drivers/mcp2515/mcp2515.h
- drivers/mcp2515/mcp2515_defines.h
- tests/candev/Makefile.board.dep
- tests/candev/main.c
The MCP2515 driver initialization sets the acceptance mode to receiving all packets without checking the filters set for each mailbox. This leads to the situation where the node is receiving all messages on the CAN bus.
This PR goal is to enable filtering the CAN messages that are having a CAN ID that matches the CAN filters.
This was tested using a SAME54-xpro and a MCP2515 breakout board following these steps:
- Enable filtering macro `MCP2515_RECV_FILTER_EN`
- Set the CAN filters for both mailboxes to reject totally the CAN message. If not, the message will be accepted on the second mailbox (according to Figure4.3 in the MCP2515 datasheet)
- Send CAN messages with matching and not matching CAN IDs
> drivers/mcp2515: enable filtering

- cpu/atmega_common/include/atmega_gpio.h
In 04ab5a74f3d7f205aace713701fadb7da4065242 a bug was introduced in
the calculation of the GPIO port address by refactoring code. This
fixes the issue by extracting the GPIO port first from the pin.
See https://github.com/RIOT-OS/RIOT/pull/18245#issuecomment-1166608376
Reported in https://github.com/RIOT-OS/RIOT/pull/18245#issuecomment-1166608376
> cpu/atmega_common: Fix atmega_port_addr()

- sys/include/net/ieee802154.h
- sys/include/net/ieee802154/submac.h
- sys/net/link_layer/ieee802154/Kconfig
- sys/net/link_layer/ieee802154/submac.c
This PR adds a IEEE 802.15.4 configuration for setting the maximum number of frame retransmissions.
Thereby the IEEE802154_SUBMAC_MAX_RETRANSMISSIONS is not needed anymore and the user can simply set the number of retransmissions from Kconfig/CFLAGS.
Try e.g `examples/gnrc_networking` with any IEEE 802.15.4 HAL based radio (e.g nrf52840). Try pinging with a stress configuration (e.g `ping <addr> -c 50 -s 1024 -i 200`.
Then, set CONFIG_IEEE802154_DEFAULT_MAX_FRAME_RETRANS to a low value (e.g 1). Repeat the procedure. Packet losses should increase.
None
> ieee802154: add default max frame retransmissions config

- cpu/esp32/include/irq_arch.h
- cpu/esp32/irq_arch.c
- cpu/esp32/periph/rtt_hw_rtc.c
- cpu/esp32/periph/rtt_hw_sys.c
This PR is a splitt-off from PR #17841 and replaces partially PR #18247.
It provides the changes in interrupt handling for ESP32x SoCs to use the ESP-IDF interrupt handling API. Also, `CPU_INUM_RTC` is renamed to `CPU_INUM_RTT` to correctly identify the interrupt source.
1. Green CI
```
```
Splitt-off from PR #17841 and PR #18247
Replaces PR #18247 partially
> cpu/esp32: use ESP-IDF interrupt handling API

- cpu/esp32/include/periph_cpu.h
- cpu/esp32/periph/cpuid.c
This PR is a split-off from PR #17841 and provides the changes to use the MAC address as returned by the ESP-IDF function `esp_efuse_mac_get_default` as CPU ID.
1. Green CI
2. Compile and test with
```
BOARD=esp32-wroom-32 make -C tests/periph_cpuid flash term
```
> cpu/esp32: use ESP-IDF function esp_efuse_mac for CPU ID

- cpu/esp32/syscalls.c
This PR is a split-off from PR #17841. It contains the changes needed for compilation for all other ESP32x SoC variants. For that purpose, It also uses the ESP-IDF interrupt HAL.
1. Green CI
```
```
Split-off from PR #17841.
> cpu/esp32:  ESP32x SoC variant independent syscalls

- cpu/atmega_common/include/cpu_conf.h
- cpu/atxmega/include/cpu_conf.h
- tests/slip/Makefile.ci
Our AVR port doesn't make use of an ISR stack and just victimizes the
stack of whatever thread happens to be running, which in most cases is
the idle thread. Hence, the idle stack has to be large enough to
support the ztimer ISR.
Run program given in https://github.com/RIOT-OS/RIOT/pull/18245#issuecomment-1166608376 - with `master` you'll get something like
```
2022-06-27 12:49:44,725 # main(): This is RIOT! (Version: 2022.07-devel-898-gd9fc08)
2022-06-27 12:49:45,770 # scheduler(): stack overflow detected, pid=1
2022-06-27 12:49:46,815 # scheduler(): stack overflow detected, pid=1
2022-06-27 12:49:47,859 # scheduler(): stack overflow detected, pid=1
```
but with this PR the stack overflow should no longer be detected. (Test successfully with both Alpine's AVR toolchain in …
> cpu/{atmega_common,atxmega}: increase idle thread stack size

- sys/include/net/netopt.h
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c
- sys/shell/commands/sc_gnrc_netif.c
Instead of retrieving a pointer with NETOPT_STATS, retrieve the current
data. This avoids data corruptions when reading from one thread (e.g.
the thread running the shell (ifconfig command)) while another thread
is updating it (e.g. the netif thread).
The issue affects all boards, as users typically expect the count of
TX packets and the number of TX bytes to refer to the same state. For
16 bit and 8 bit platforms even a single netstat entry can read back
corrupted.
This fixes the issue by just copying the whole netstat_t struct over
without requiring explicit locking on the user side. A multi-threaded
network stack still needs to synchronize the thread responding to
netopt_get with the thread writing to the netstat_t structure, but that
is an implementation detail no relevant to the user …
> sys/net/netopt: change NETOPT_STATS semantics

- .github/ISSUE_TEMPLATE/bug_report.md
- boards/cc2538dk/doc.txt
- boards/cc2650stk/doc.txt
- boards/firefly/doc.txt
- boards/iotlab-m3/doc.txt
- boards/openmote-b/doc.txt
- boards/openmote-cc2538/doc.txt
- boards/remote-pa/README.md
- boards/remote-reva/README.md
- boards/remote-revb/README.md
- boards/samr21-xpro/doc.txt
- boards/stm32f4discovery/doc.txt
- cpu/native/README.md
- cpu/native/async_read.c
- cpu/native/include/clang_compat.h
- cpu/native/include/cpu_conf.h
- cpu/native/netdev_tap/netdev_tap.c
- cpu/native/osx-libc-extra/malloc.h
- cpu/native/periph/qdec.c
- cpu/native/periph/timer.c
- doc/doxygen/src/getting-started.md
- doc/doxygen/src/mainpage.md
- examples/emcute_mqttsn/README.md
- examples/gnrc_border_router/README.md
- tests/unittests/tests-fib/tests-fib.c
- Renaming some occurrences of "OS X" (and other variations) to "macOS". 
- I wasn't sure about changing the old release notes too (so I didn't).
- Patches and packages were also excluded, e.g. sys/embunit/readme_en.txt
- limited to txt|c|h|md files
- I tried to keep specific version names, e.g. `Mac OSX El Capitan users`.
- Some of these files should be checked® in the future if they are still needed / up to date
- I added a warning to guidance that instructed users to disable Apple's macOS System Integrity Protection. I do not believe this is something that RIOT should casually advise. (Somebody® should check if this section is even still needed)
Apple changed the name of the operating system to "macOS" in 2016 to match the branding of Apple's other operating systems.
Users might search …
> Documentation: Renaming OS X to macOS

- tests/thread_float/tests/01-run.py
Previously the test script expected runnable threads of the same
priority to be running in a specific order. But the only tool that is
guaranteed to enforce a specific order of runnable threads is assigning
them different priority levels.
This should fix a test failure in the nightlies.
Murdock will do so
None
> tests/thread_float: fix test script
