- sys/include/net/gnrc/rpl.h
- sys/include/net/rpl/rpl_netstats.h
- sys/net/gnrc/routing/rpl/gnrc_rpl_internal/netstats.h
- sys/shell/commands/sc_gnrc_rpl.c
This PR firsts refactors the `netstats_rpl_t` structure to avoid repeated blocks in that structure by declaring a `netstats_rpl_block_t` structure, which is than used for DIO, DIS, DAO, and DAO-ACK statistics. Building on that the printing of the statistics in the `rpl` shell command is refactored to avoid duplicated code.
On top of that the second commit synchronizes the RPL thread updating the RPL netstats with the RPL shell command reading the stats by disabling IRQs. This will prevent printing corrupted data on non-32bit platforms as well as printing inconsistent data (e.g. TX count of old state in conjunction with TX bytes of new state) for all platforms.
The statistics printed by the `rpl` shell command should still make sense and not being affected by rare data corruptions during …
> sys/net/gnrc/rpl: sync access to netstats

- sys/net/application_layer/asymcute/asymcute.c
The handlers for the `REGACK`, `SUBACK` and `UNSUBACK` MQTT message lock the connection mutex on function entry via `mutex_lock(&con->lock)`. During automated testing of `asymcute` with [SymEx-VP](https://github.com/agra-uni-bremen/symex-vp), I discovered return paths for these functions which do not unlock the connection mutex. This results in a deadlock which prevents asymcute from sending any further messages.
I think this is fairly obvious just by reading the code, i.e. check that there is a `mutex_lock(&con->lock)` but no matching `mutex_unlock(&con->lock)` for the modified return paths.
None.
> asymcute: Fix deadlocks in REGACK, SUBACK and UNSUBACK handler

- drivers/at86rf2xx/at86rf2xx.c
- drivers/at86rf2xx/at86rf2xx_internal.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
- drivers/at86rf2xx/include/at86rf2xx_internal.h
- drivers/at86rf2xx/include/at86rf2xx_registers.h
- drivers/include/at86rf2xx.h
- tests/driver_at86rf2xx/cmd.c
- tests/driver_at86rf2xx/common.h
- tests/driver_at86rf2xx/main.c
This Pr is dedicated to resolve the random generation numbers from at86rf233, this should establish the device in a basic operation mode states. also needs to the preamble detector is disabled (RX_PDT_DIS=1). Something else that should be considered is the state of Smart Receiver Technology (SRT), this is an element used to manage the Reception Power Consumption (RPC) and it's affecting the `random_number_generator()` of the `at86rf2xx`. Well this Pull request add the functionality to disable temporarily the `smart_idle_mode` because the random number generator needs take values from RSSI register. When the SRT is active could won´t get the wished random values).
Also to integrate the number generator by the driver implementation, also let's to manipulate the functionality by network …
> drivers/at86rf2xx: Switch SRT mode to get random values.

- pkg/emlearn/Kconfig
- pkg/emlearn/Makefile.include
There was a mismatch between Kconfig and make, after some digging it
appears that the make never used the emlearn module, only the package.
This removes the emlearn pseudomodule from make since nothing selects it
and removes the MODULE_EMLEARN from Kconfig to match the make dependency
resolution.
Green murdock and I guess just understand it
> pkg/emlearn: Remove unused emlearn module

- Makefile.include
- dist/tools/cosy/patches/0001-cosy-allow-to-specify-port.patch
This allows to run multiple instances of `cosy` in parallel to compare binary sizes.
make -C examples/hello-world cosy COSY_PORT=8888
```
Result validation: both size outputs below should match
Computed sums of parsed symbols:
text    data     bss     dec     hex
13384   11458  432958  457800   6fc48
Output of the 'size' command:
26878	    548	  47796	  75222	  125d6	/home/benpicco/dev/RIOT/examples/hello-world/bin/native/hello-world.elf
Started frontend server, connect you browser to http://localhost:8888
```
upstream PR https://github.com/haukepetersen/cosy/pull/14
> dist/tools/cosy: allow to specify port

- cpu/esp32/include/periph_cpu.h
- cpu/esp32/periph/hwrng.c
- cpu/esp8266/periph/hwrng.c
This PR is a split-off from PR #17841 and provides the changes to use the ESP-IDF random API for `periph/hwrng`. This RNG uses the noise in the RF system of the WiFi or the BT interface as entropy source. If neither WiFi nor BT are used, an internal non-RF entropy source is used, the internal reference voltage noise.
Compile and test
```
BOARD=esp32-wroom-32 make -j8 -C tests/periph_hwrng/ flash term
```
> cpu/esp_common: use ESP-IDF random API for ESP32

- boards/nucleo-f207zg/doc.txt
- boards/nucleo-f303ze/doc.txt
- boards/nucleo-f412zg/doc.txt
- boards/nucleo-f413zh/doc.txt
- boards/nucleo-f429zi/doc.txt
- boards/nucleo-f439zi/doc.txt
- boards/nucleo-f446ze/doc.txt
- boards/nucleo-f722ze/doc.txt
- boards/nucleo-f746zg/doc.txt
- boards/nucleo-f767zi/doc.txt
- boards/nucleo-l496zg/doc.txt
- boards/nucleo-l4r5zi/doc.txt
- boards/nucleo-l552ze-q/doc.txt
PR #18057 enables **_cpy2remed_** programmer for all STM Nucleo boards.
This PR adds to nucleo144 boards documentation:
-  information about usage of **_cpy2remed_** programmer,
-  short information about board (used MCU, available RAM and Flash),
-  change all memory sizes to KiB (before kB or Kb are used) .
Changes in documentation can be observed using commands:
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f207zg.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f303ze.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f412zg.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f413zh.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f722ze.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f746zg.html 
xdg-open …
```
> boards/nucleo144: doc update - usage of cpy2remed programmer and short overview of board

- cpu/stm32/stm32_mem_lengths.mk
Now selecting stm32g0b1re as a target mcu and the likes of its subfamily should compile fine.
> cpu/stm32: support for B subfamily of g0 to determine the ram length

- cpu/esp32/startup.c
- tests/periph_gpio_ll/Makefile
- tests/pkg_fff/Makefile
ESP32 has an esp_timer thread in addition to the main and the idle thread. So applications that work fine with 2 threads on other platforms will break on ESP32. This adds a `static_assert()` to enforce `MAXTHREADS` is never less than 3 on ESP32 and fixes the offenders.
Green Murdock and `tests/pkg_fff` should now pass on ESP32 boards.
https://github.com/RIOT-OS/RIOT/pull/17076#issuecomment-1155787669
> cpu/esp32: enforce MAXTHREADS is at least 3

- pkg/lv_drivers/Makefile
While working on #18301, I noticed some inconsistencies in this Makefile. This PR addresses them:
- the IGNORE_MODULES variable is empty and there's no way to modify it. So let's just drop it
- the PHONY targets are wrong
- there's a tiny generalization of the `lv_drivers_%` target. I can drop that change if this is controversial. Normally each possible drivers (sdl, wayland, win32drv, gtkdrv) should work with that but I don't think they are used by this package anyway.
- `tests/pkg_lvgl` and `tests/pkg_lvgl_touch` are still working on native (so with the sdl driver)
None
> pkg/lv_drivers: cleanup Makefile

- boards/im880b/include/periph_conf.h
Commit [c14d7ec7dbc2238ad251a70904407e503342b82d](https://github.com/RIOT-OS/RIOT/commit/c14d7ec7dbc2238ad251a70904407e503342b82d) requires the definition of the clock peripherals on a given board but the im880b does not provide such a definition in its configuration file. This PR defines the HSE clock as the 16 MHz external clock.
This PR aims at solving https://github.com/RIOT-OS/RIOT/pull/18293
Signed-off-by: Jean-Michel Friedt <friedtj@free.fr>
> boards/im880b: im880b board clock definition

- tests/driver_at86rf2xx/cmd.c
- tests/driver_at86rf2xx/main.c
The random test function should be guarded by `AT86RF2XX_RANDOM_NUMBER_GENERATOR` not by `AT86RF2XX_SMART_IDLE_LISTENING`. This fixes the issue and also sneaks in a test for the return value.
Murdock and it may make sense to run the test once.
None
> tests/driver_at86rf2xx: fix use of incorrect macro

- cpu/esp32/Makefile.include
- cpu/esp32/include/periph_cpu.h
- cpu/esp32/periph/rtt_hw_rtc.c
- cpu/esp32/periph/rtt_hw_sys.c
- cpu/esp32/syscalls.c
This PR is a split-off from PR #17841. It contains the changes to use the ESP-IDF timer HAL for the system timer and the watchdog.
1. Green CI
```
```
> cpu/esp32: use ESP-IDF timer HAL for system timer and watchdog

- .github/workflows/test-on-iotlab.yml
After today's maintenance on IoT-LAB some boards are no longer available on the Saclay site and some are now only available in Lille. This PR updates the test-on-iotlab build matrix to reflect that change.
- test-on-iotlab should run as expected, e.g use dwm1001 from lille and don't build on nrf51dk and nrf52832mdk
None
> gh_action/test-on-iotlab: update available boards

- sys/net/gnrc/netif/gnrc_netif.c
This PR moves the netdev specific `options_tested` to the `gnrc_netif_default_init`.
Although the current implementation of `gnrc_netif` is still dependent to `netdev`, this allows to encapsulate all `netdev` specific calls in the `gnrc_netif_ops_t` functions.
Probably a compile test should suffice...
Required by #18156
> gnrc_netif: move `option_tested` to default init function

- .murdock
- makefiles/tests/tests.inc.mk
This prints the hash input when KConfig and non-KConfig builds differ in hash. Hopefully, this helps debugging the issue.
Murdock will do so.
None
> .murdock: print hash input when hashes mismatch

- examples/gnrc_border_router/README.md
The last element of a JSON array must not be terminated with a `,` character. As such, the configuration documented currently in the `README.md` file of gnrc_border_router is invalid and rejected by Kea.
> gnrc_border_router: Fix syntax error in Kea configuration

- drivers/mcp2515/candev_mcp2515.c
- drivers/mcp2515/mcp2515_defines.h
- sys/include/can/can.h
- tests/candev/main.c
The MCP2515 presents two RX mailboxes, the first has two CAN filters and the second has four CAN filters. The current implementation of the driver obliges the user to apply all the filters for mailbox1 in order to be able to apply the filters for mailbox2. E.g: **If the user wants to accept only CAN messages with CAN ID 0x012, the filter 0x012 must be applied for the two mailboxes. However, to do that, two filters must be applied for the first mailbox and then the second mailbox will be accessible for filtering which means a second dummy filter is applied to the first mailbox.**
This PR allows to specify a target mailbox when applying the CAN filters, so there will be no need to apply dummy filters to be able to filter in the second mailbox
This was tested using a SAME54-xpro and a …
> drivers/mcp2515: apply filters to target mailbox

- cpu/esp32/include/can_esp.h
- cpu/esp32/periph/can.c
This PR is a split-off from PR #17841 and provides the changes to use the ESP-IDF twai HAL for `periph/can`.
Compile and test with
```
BOARD=esp32-wroom-32 make -j8 -C tests/conn_can flash term
```
> cpu/esp32: use to ESP-IDF twai HAL for periph/can

- cpu/esp32/esp-idf-api/uart.c
- cpu/esp32/include/esp_idf_api/uart.h
- cpu/esp32/include/periph_cpu.h
- cpu/esp_common/periph/uart.c
This PR is a split-off from PR #17841 that:
- provides the changes to use ESP-IDF interrupt HAL for `periph/uart` and
- inverts the `MCU_*` conditionals so that they can be tested for ESP8266. In all other cases the MCU is any ESP32x SoC.
1. Green CI
```
```
Split-off from PR #17841 
Prerequisite for PR #18280
> cpu/esp32: use ESP-IDF interrupt HAL for periph/uart

- cpu/esp32/include/periph_cpu.h
- cpu/esp32/periph/spi.c
- cpu/esp8266/periph/spi.c
This PR is a split-off from PR #17841 and provides the following changes:
- Uses the former `periph/spi` implementation only for ESP8266. It is therefore moved from `cpu/esp_common/periph` to `cpu/esp8266/perip`.
- Implements `periph/spi` for ESP32x SoC using using the ESP-IDF spi HAL interface.
Compile and test
```
USEMODULE='esp_log_startup' BOARD=esp32-wroom-32 make -j8 -C tests/periph_spi flash term
```
> cpu/esp32: use ESP-IDF spi HAL for periph/spi

- cpu/esp32/Makefile.dep
- cpu/esp32/esp-idf-api/gpio.c
- cpu/esp32/esp-idf/gpio/Kconfig
- cpu/esp32/esp-idf/gpio/Makefile
- cpu/esp32/include/esp_idf_api/gpio.h
- cpu/esp32/include/gpio_arch.h
- cpu/esp32/include/periph_cpu.h
- cpu/esp32/periph/Makefile
- cpu/esp32/periph/gpio.c
- cpu/esp32/periph/gpio_arch.c
- tests/external_board_dirs/esp-ci-boards/esp32-ci/Makefile.dep
This PR is a split-off from PR #17841 and provides:
- the ESP-IDF gpio interface API for RIOT
- the changes to use the ESP-IDF gpio HAL
Please note: The ESP-IDF gpio HAL is used in any case for the `gpio_init*` functions. For the GPIO access, however, the ESP-IDF gpio HAL is only used if the `esp_idf_gpio_hal` module is enabled. Otherwise, the peripheral GPIO driver still uses direct access to the GPIO input/output registers for better performance and for future implementation of the `gpio_ll` API.
~This PR depends on PR #18261~
Compile and test basic GPIO functionality with
```
BOARD=esp32-wroom-32 make -j8 -C tests/periph_gpio flash term
```
~Depends on PR #18261~
Prerequisite for PR #18271 
Prerequisite for PR #18279
> cpu/esp32: use ESP-IDF gpio HAL for periph/gpio

- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/net/dns/msg.h
- sys/net/application_layer/dns/msg.c
- sys/net/application_layer/gcoap/dns.c
- sys/net/application_layer/sock_dns/Makefile
- sys/net/application_layer/sock_dns/dns.c
- sys/net/application_layer/sock_dns/dns_cache.c
- sys/net/application_layer/sock_dns/dns_cache.h
- tests/unittests/tests-sock_dns_cache/Makefile
- tests/unittests/tests-sock_dns_cache/Makefile.include
- tests/unittests/tests-sock_dns_cache/tests-sock_dns_cache.c
- tests/unittests/tests-sock_dns_cache/tests-sock_dns_cache.h
If a domain is used multiple times, RIOT will issue a new DNS query each time. This can add unwanted network overhead and latency, so caching DNS entries can be desirable. 
If the cache is full, the first entry to expire will be evicted.
The DNS cache is enabled with
USEMODULE += sock_dns_cache
```
> ping riot-os.org
2022-02-19 14:36:58,953 # dns_cache miss
2022-02-19 14:36:58,990 # dns_cache: lifetime of riot-os.org is 86227 s
2022-02-19 14:36:58,992 # dns_cache[0] add cache entry
2022-02-19 14:36:59,029 # 12 bytes from 2001:67c:254:b0b0::1: icmp_seq=0 ttl=56 time=30.365 ms
2022-02-19 14:37:00,032 # 12 bytes from 2001:67c:254:b0b0::1: icmp_seq=1 ttl=56 time=33.197 ms
2022-02-19 14:37:01,039 # 12 bytes from 2001:67c:254:b0b0::1: icmp_seq=2 ttl=56 time=40.015 ms
2022-02-19 14:37:01,039 # …
```
> sock_dns: implement DNS cache

- doc/doxygen/riot.doxyfile
- sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c
A *smaller* prefix makes a *larger* subnet and vice versa.
Make the wording in the documentation more precise. 
Only doc changes.
> gnrc/ipv6_auto_subnets: improve wording in documentation, add to Doxygen

- cpu/esp32/periph/pm.c
This PR is a split-off from PR #17841 and provides the changes to use the ESP-IDF sleep API for `periph/pm`
~This PR depends on PR #18274.~
Compile and test the hardware implementation with
```
USEMODULE='esp_i2c_hw esp_log_startup' BOARD=esp32-wroom-32 make -j8 -C tests/periph_pm flash term
```
~Depends on PR #18274~
> cpu/esp32: use ESP-IDF sleep API for periph/pm

- examples/cord_ep/main.c
- examples/cord_epsim/main.c
- examples/gcoap/server.c
- examples/gcoap_block_server/gcoap_block.c
- examples/gcoap_fileserver/main.c
- examples/nanocoap_server/coap_handler.c
- examples/suit_update/coap_handler.c
- sys/include/net/gcoap/fileserver.h
- sys/include/net/nanocoap.h
- sys/net/application_layer/gcoap/Makefile
- sys/net/application_layer/gcoap/fileserver.c
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/net/application_layer/nanocoap/nanocoap_internal.h
- sys/suit/transport/coap.c
- tests/gcoap_dns/main.c
- tests/nanocoap_cli/request_handlers.c
- tests/pkg_edhoc_c/responder.c
- tests/riotboot_flashwrite/coap_handler.c
Currently a resource handler has no information about the resource it handles.
This leads to awkward work-around such as specifying the resource path in the user context again.
To avoid this, introduce a `coap_resource_ctx_t` struct that contains the user context and the resource path, that can be easily extended if more context is needed in the future.
All CoAP applications should still work.
Since the user context was usually NULL, most will not even notice a change.
https://github.com/RIOT-OS/RIOT/pull/14397#issuecomment-1100191189
Can provide an alternative to #16827 (and also move `tl_type` out of `coap_pkt_t` into  `coap_resource_ctx_t`)
depends on [!11](https://gitlab.com/etonomy/riot-wrappers/-/merge_requests/11)
> nanocoap: define and use coap_request_ctx_t for request handlers

- boards/common/esp32/include/periph_conf_common.h
- cpu/esp32/include/periph_cpu.h
- cpu/esp32/periph/i2c_hw.c
- cpu/esp_common/periph/i2c_sw.c
- pkg/esp32_sdk/patches/0015-driver-i2c-remove-the-include-gpio.h-in-i2c.h-header.patch
- pkg/esp32_sdk/patches/0016-driver-i2c.h-expose-i2c_hw_fsm_reset-to-RIOT-code.patch
This PR is a split-off from PR #17841 and provides the following changes:
- ESP-IDF i2c HAL and ESP-IDF interrupt HAL are used in hardware implementation (module `esp_i2c_hw`).
- In software implementation, which is used by default, fixed delay values are replaced by calculated delays measured in CPU cycles. The advantage is that for each ESP SoC only a clock calibration offset has to be specified. The delay measured in CPU cycles are then derived from current CPU frequency for the given bus speed. The disadvantage is that the calculated delays are not as precise as the predefined fixed delays before.
~This PR depends on PR #18270.~
1. Green CI (compilation of hardware implementation is covered by board `esp32-ci`).
2. Compile and test the hardware implementation with
``` …
```
> cpu/esp32: use ESP-IDF i2c HAL for ESP32 periph/i2c

- cpu/esp32/Kconfig
- cpu/esp32/periph/Kconfig
- cpu/esp8266/Kconfig
- cpu/esp_common/Kconfig
This PR improves the Kconfig submenu structure for ESP SoCs.
Without this PR, some ESP SoC specific configurations are shown in top menu and not in the ESP specific submenus:
- ESP8266
```
(Top)
RIOT Configuration
ESP8266 specific configurations  --->
ESP configurations  --->
[ ] Simulate ESP with QEMU
[ ] Use software timer
[ ] gdbstub interface support
[*] RIOT Core  --->
...
```
- ESP32
```
(Top)
RIOT Configuration
ESP32 specific configurations  --->
[ ] Use hardware counter
ESP configurations  --->
[ ] Simulate ESP with QEMU
[*] RIOT Core  --->
...
```
With this PR, these ESP SoC specific configurations are moved to the appropriate submenus and give a much more structured view of the ESP specific configuration options:
- ESP8266
```
(Top)
RIOT Configuration
ESP8266 specific …
```
> cpu/esp_{common,32,8266}: improve Kconfig submenu structure

- cpu/esp32/esp_ztimer.c
- cpu/esp32/periph/rtt.c
- cpu/esp_common/Kconfig
- cpu/esp_common/Makefile
- cpu/esp_common/Makefile.dep
- cpu/esp_common/Makefile.features
- cpu/esp_common/esp-riscv/Kconfig
- cpu/esp_common/esp-riscv/Makefile
- cpu/esp_common/esp-riscv/exceptions.c
- cpu/esp_common/esp-riscv/irq_arch.c
- cpu/esp_common/esp-riscv/thread_arch.c
This PR is a splitt-off from PR #17841 and replaces partially PR #18247.
To allow the compilation for RISC-V based ESP32x SoCs, platform independent implementation of `tread_arch.c`, `irq_arch.c` and `exception.c` are required that are provided by a platform-specific module `esp_riscv`.
Additionally, some DEBUG message formatting are fixed with this PR to become platform independent.
~This PR includes PR #18259 at the moment to be compilable. The first commit of this PR is d05dacda1e9fc4b0139e4191cea35cbe250b89e4. Once PR #18529 is merged, it will be rebased.~
**Background:**
- The file `thread_arch.c` in module `esp_xtensa` is not really independent of the used ESP SoC. Although ESP8266 and ESP32 share most of the code, they require some SoC specific code, especially in `thread_yield_*` …
> cpu/esp32: add platform code for RISC-V based ESP32x SoCs

- cpu/esp_common/vendor/xtensa/Kconfig
This PR is a split-off from PR #17842 and provides a change that is needed to support ESP32x SoCs that are RISC-V based.
ESP32x SoC use either Xtensa cores or RISC-V cores. The Xtensa vendor code has to be compiled only for ESP32x SoCs that are Xtensa-based. Therefore, `MODULE_XTENSA` in Kconfig has to depend on `HAS_ARCH_ESP_XTENSA` instead of `HAS_ARCH_ESP`.
Green CI
Split-off from PR #17842
> cpu/esp_common: MODULE_XTENSA has to depend on HAS_ARCH_ESP_XTENSA

- cpu/esp32/doc.txt
- cpu/esp32/doc_esp32.txt
This PR is a split-off from #17842, providing the separation of of the documentation into a part common to all ESP32x SoCs and a part specific to ESP32 to support different ESP32x SoC variants.
1. Green CI
2. `make doc` and check that there is a new sub-menu `RIOT OS -> Modules -> CPU -> ESP32x SoC Series -> ESP32 family` which contains specific information about ESP32.
Split-off from #17842
> cpu/esp32: split the doc into ESP32x common and ESP32 specific parts

- cpu/esp32/Kconfig
- cpu/esp32/Makefile.features
Feature `esp_hw_counter` is not supported by all ESP32x SoC variants (families). Therefore, it has to be defined dependent on `CPU_FAM`.
This PR is a split-off from PR #17842.
Green CI
Split-off from PR #17842
> cpu/esp32: make esp_hw_counter feature dependent on ESP32x SoC family

- cpu/esp32/include/cpu_conf.h
- cpu/esp32/include/cpu_conf_esp32.h
This PR is a split-off from #17842, providing the separation of of `cpu/esp32/include/cpu_conf.h` into a part common to all ESP32x SoCs and a part specific to ESP32 to support different ESP32x SoC variants.
Green CI
Split-off from #17842
> cpu/esp32: split cpu_conf.h into ESP32x common and ESP32 specific parts

- cpu/esp32/Kconfig
- cpu/esp32/Kconfig.common
- cpu/esp32/Kconfig.esp32
This PR is a split-off from PR #17842, providing the separation of Kconfig into a part common to all ESP32x SoCs and a part specific to ESP32 to support different ESP32x SoC variants.
1. Green CI
2. Use command
```
TEST_KCONFIG=1 BOARD=esp32-wrover-kit make -C tests/periph_timer menuconfig
```
and check that the sub menu for ESP32 specific configuration is still the same as before:
```
(Top) → ESP32 specific configurations
RIOT Configuration
CPU clock frequency (80 MHz)  --->
[*] Enable JTAG debugging interface
[ ] Enable SPI RAM support
[ ] Use hardware counter as low-level timer peripheral    ```
Split-off from PR #17842
> cpu/esp32: split Kconfig into ESP32x common and ESP32 specific parts

- cpu/esp32/include/periph_cpu.h
- cpu/esp32/include/periph_cpu_esp32.h
- dist/tools/doccheck/exclude_patterns
This PR is a split-off from #17842, providing the separation of of `cpu/esp32/include/periph_cpu.h` into a part common to all ESP32x SoCs and a part specific to ESP32 to support different ESP32x SoC variants.
Green CI
Split-off from #17842
Requires PR #18321
> cpu/esp32: split periph_cpu.h into ESP32x common and ESP32 specific parts

- tests/periph_gpio_ll/main.c
This PR provides a small fix of the output for GPIO_OUTPUT_OPEN_SOURCE tests.
Green CI without compilation tests.
> tests/periph_gpio_ll: fix the output for GPIO_OUTPUT_OPEN_SOURCE tests

- cpu/esp32/Makefile.dep
- cpu/esp32/periph/Kconfig
This PR is a split-off from PR #17844, which provides a fix of module dependency for `periph_rtt`.
If the ESP32 has an external 32k crystal connected, the clock from this crystal should be used for the RTT peripheral and not only for the RTC peripheral. Since the ESP32 RTC implementation uses RTT on top of RTT (module `rtc_rtt`), with this change the 32k crystal will be used for both RTT and RTC if present.
1. Use command:
```
BOARD=esp32-wrover-kit make -j8 -C tests/periph_rtt info-modules | grep esp_rtc_timer_32k
BOARD=esp32-wroom-32 make -j8 -C tests/periph_rtt info-modules | grep esp_rtc_timer_32k
```
Module `esp_rtc_timer_32k` is used for board `esp32-wrover-kit` but not for board `esp32-wroom-32` with this PR. Without this PR it is not used at all.
2. Use command:
```
TEST_KCONFIG=1 …
```
> cpu/esp32: fix dependency for periph/rtt and module esp_rtc_timer_32k

- sys/net/application_layer/dns/cache.c
In https://github.com/RIOT-OS/RIOT/pull/18329#discussion_r924622627, @benpicco realized, that synchronization of cache access is missing for `dns_cache`. This adds the missing synchronization.
`tests/unittests` should still pass.
Follow-up on #18318.
> dns_cache: synchronize access with mutex [backport 2022.07]

- cpu/esp32/ld/esp32c3/memory.ld
- cpu/esp32/ld/esp32c3/sections.ld
This PR is a split-off from PR #17844, which provides the linker scripts for ESP32-C3.
It is not yet possible to cover this PR when compiling in CI without having ESP32-C3 support and a board definition with an ESP32-C3. Vice versa, the ESP32-C3 port that needs this PR cannot be compiled in CI without it.
Therefore a green CI with the label `CI: skip compile test` must be sufficient for the moment. If it doesn't work, the problem will pop up as soon as ESP32-C3 support is provided. And of course, I have tested it together with the ESP32-C3 support in PR #17844.
> cpu/esp32: add linker scripts for ESP32-C3

- drivers/ws281x/esp32.c
This PR is a split-off from PR #17844 and provides a fix in DEBUG format string to be compilable for different ESP32x SoCs.
Green CI
> drivers/wx281x: fix DEBUG format string for ESP32x SoCs

- cpu/esp32/esp-idf/esp_idf_support.c
- cpu/esp_common/include/esp_common_log.h
This PR is a split-off from PR #17844, which provides
- a cleanup in function `esp_write_log` and
- a change in `esp_log` to be compilable for different ESP32x SoC variants.
1. Green CI
2. Compile and flash with
```
USEMODULE='esp_log_startup esp_log_tagged esp_log_colored' BOARD=esp32-wroom-32 make -j8 -C tests/shell flash term
```
Colored and tagged output with boot log should still work.
> cpu/esp32: cleanup of esp_log_write

- cpu/esp32/Makefile.features
- cpu/esp32/Makefile.include
- cpu/esp_common/Makefile.dep
- cpu/esp_common/Makefile.features
This PR is a split-off from PR #17844, which adds the support of ESP32-C3 in makefiles.
It is not yet possible to cover this PR when compiling in CI without having ESP32-C3 support and a board definition with an ESP32-C3. Vice versa, the ESP32-C3 port that needs this PR cannot be compiled in CI without it.
Therefore a green CI with the label `CI: skip compile test` must be sufficient for the moment. If it doesn't work, the problem will pop up as soon as ESP32-C3 support is provided. And of course, I have tested it together with the ESP32-C3 support in PR #17844.
> cpu/esp32: add ESP32-C3 support in makefiles

- pkg/esp32_sdk/patches/0017-esp_phy-add-missing-header-includes.patch
- pkg/esp32_sdk/patches/0018-bootloader-changes-for-esp32c3.patch
- pkg/esp32_sdk/patches/0019-hal-fix-spi_ll-compilation-errors-for-riscv32.patch
- pkg/esp32_sdk/patches/0020-freertos-portasm-changes-for-RIOT-for-riscv32.patch
This PR is a split-off from PR #17844, which provides additional patches of `pkg/esp32_sdk` required for ESP32-C3.
It is not yet possible to cover this PR when compiling in CI without having ESP32-C3 support and a board definition with an ESP32-C3. Vice versa, the ESP32-C3 port that needs this PR cannot be compiled in CI without it.
Therefore a green CI with the label `CI: skip compile test` must be sufficient for the moment. If it doesn't work, the problem will pop up as soon as ESP32-C3 support is provided. And of course, I have tested it together with the ESP32-C3 support in PR #17844.
> pkg/esp32_sdk: additional patches required for ESP32-C3

- sys/net/application_layer/gcoap/dns.c
- tests/gcoap_dns/main.c
- tests/gcoap_dns/tests/01-run.py
This adds DNS cache support to our DNS over CoAP implementation `gcoap_dns`.
Both of the following commands should succeed:
```sh
make -C tests/gcoap_dns/ flash -j test                      # also tested by Murdock
USEMODULE=dns_cache make -C tests/gcoap_dns/ flash -j test  # NOT tested by Murdock
```
Follow-up on #16705 and #18318.
> gcoap_dns: Add DNS cache support

- makefiles/suit.base.inc.mk
This fixes a trigger of re-creation of an already existing SUIT
key when combining a build target with the clean target, e.g.
`make clean all`.
**Without the changes of this PR**
`make -j` in `${RIOTBASE}/examples/suit_update` will build & conditionally create a key in `${RIOTBASE}/keys/default.pem` if none is there.
Running `make clean` will leave the key in place.
Re-running `make -j` will reuse the existing key.
Running `make -j clean all` will try to re-create a key in the location although it exists. The process will fail because the key generator checks for an existing key. However, it should not even be executed.
**With the changes of this PR**
Making the dependency on `CLEAN` order-only will avoid attempting to re-create a key when there is already one. `make -j clean all` does …
> makefiles/suit: avoid unwanted key creation trigger

- cpu/esp32/doc.txt
- cpu/esp32/doc_esp32c3.txt
This PR is a split-off from PR #17844, which updates the documentation for ESP32-C3.
Green CI without compilation test since only `*.txt` files are changed.
> cpu/esp32: update documentation for ESP32-C3

- dist/tools/cosy/patches/0002-parse_elffile-fix-riot_base.patch
The upstream PR #13 is not yet merged but fixes classification to no
longer classify most of RIOT's object files "unspecified" in the
`.text` view.
Since @Jnae authored the fix, I added her as author in the commit adding the patch to not steal credit.
`make cosy` with a recent should now give sensible output. I can confirm that it fixes the issue for me.
Apparently on @benpicco 's machine it worked before. Maybe he can confirm it doesn't break anything.
Upstream PR: https://github.com/haukepetersen/cosy/pull/13
Implementation of @leandrolanzieri suggestion: https://forum.riot-os.org/t/suggestions-for-measuring-memory-usage/3666/7
> dist/tools/cosy: provide patch for PR #13

- tests/unittests/main.c
@miri64 found an issue with unittest and ztimer_sleep in
https://github.com/RIOT-OS/RIOT/pull/17680#issuecomment-1184312760
PR #18312 identified a potential double initialization of ztimer.
this removes the xtimer initialzation call if  xtimer is used via ztimer_xtimer_compat. (this is the same behavior found in `auto_init`)
see #18312
> unittest/main: do not intialize xtimer if ztimer_xtimer_compat

- examples/asymcute_mqttsn/Makefile.ci
- examples/cord_lc/Makefile.ci
- examples/gcoap/Makefile.ci
- sys/Makefile.dep
- sys/shell/commands/Makefile
- sys/shell/commands/sc_gnrc_icmpv6_echo.c
- tests/gnrc_rpl/Makefile.ci
Add missing dependency to xtimer so that the shell command `ping` is
again provided when requested.
Run `make BOARD=nucleo-f767zi -C examples/gnrc_networking flash term` and then `help`. If the `ping` command is listed again, the bug is fixed. (Did so, worked for me.)
None
> sys/shell/commands/ping: fix dependency & convert to ztimer

- pkg/lwip/contrib/_netif.c
- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/lwip/contrib/sock/ip/lwip_sock_ip.c
- pkg/lwip/contrib/sock/lwip_sock.c
- pkg/lwip/contrib/sock/tcp/lwip_sock_tcp.c
- pkg/lwip/contrib/sys_arch.c
This mostly converts switch statements from double indent style to Linux kernel style, as required per the coding convention.
From the C compiler perspective, this is a whitespace only change.
Double checking that changes are indeed white-space only is sufficient. Sadly, the github diff view doesn't really work well here...
I split this out of a yet to be opened PR, so that the PR with actual changes only contains actual changes.
> pkg/lwip: fix code style

- pkg/lwip/Makefile
- pkg/lwip/contrib/sock/lwip_sock.c
This does three things:
- Add `-Wno-format` to the `CFLAGS` for LWIP, as it uses (from a pedantic point of view) incorrect format specifiers in its debug statements
- This issue is not triggered without enabling debugging, so this did not show up in the CI
- Add a few debug prints to the `sock_lwip`code that can be enabled by setting `ENABLE_DEBUG` to `1`
- Fix sending from a socket bound to anyaddr
I mostly opened this PR so that I can reference it. But I guess it may be useful to have upstream anyway.
1. Set `ENABLE_DEBUG` to `1` and e.g. `examples/gcoap` with `LWIP=1` should print some output when sending.
2. `LWIP=1 make -C examples/gcoap` should now work, such that the server actually sends out the responses to requests it receives
Note: LWIP still does not implement module …
> pkg/lwip: ease debugging & fix sending from socket bound to anyaddr

- pkg/lvgl/Makefile
As the title says. This version of lvgl only contains bug fixes.
Firmware size of `tests/pkg_lvgl `is the same between master and this PR. For `tests/pkg_lvgl_touch`, it's smaller with this PR.
I tested `tests/pkg_lvgl` and `tests/pkg_lvgl_touch` on native and both still works.
- `tests/pkg_lvgl` and `tests/pkg_lvgl_touch` are still functional
None
> pkg/lvgl: bump version to 8.3.1

- sys/net/application_layer/gcoap/dns.c
While doing some more experiments with the current version of `gcoap_dns`, I noticed some bugs, specifically, when using block-wise transfer. This PR fixes those and also replaces some left-over `printf`s with `DEBUG`.
Similar to the testing procedures in #16705:
```console
$ sudo dist/tools/tapsetup/tapsetup
$ sudo ip addr add 2001:db8::1 dev tapbr0
$ sudo ip route add 2001:db8::/64 via "<native link-local>" dev tapbr0
$ pip install --upgrade git+https://github.com/miri64/aiodnsprox.git@exp  # blockwise does not work with upstream aiodnsprox yet
$ cat << EOF > config.yaml
dtls_credentials:
client_identity: Client_identity
psk: secretPSK
mock_dns_upstream:
IN:
A: 192.0.2.7
AAAA: 2001:db8::7
$ aiodns-proxy -C config.yaml -c 2001:db8::1
```
```shell
RIOT_CONFIG_KCONFIG_USEMODULE_GCOAP_DNS=y …
```
> gcoap_dns: various fixes

- examples/dtls-echo/dtls-client.c
- examples/dtls-echo/dtls-server.c
d424aaedacf5e77a8310edaf1a87543d22f6e6ab introduced address families to the RIOT interpretation of tinydtls-`session_t`s. However, while fixing the naming for the `addr` field, it did not set the `family` member for the sessions in the `dtls-echo` example, having that example run into [an assertion][1]. This patch fixes that.
[1]: https://github.com/eclipse/tinydtls/blob/bda40789a7c280f248eeca6d09ddd624cdaf5dc8/session.c#L146
I used the same script to [find the issue](https://github.com/RIOT-OS/RIOT/pull/18368#issuecomment-1195474091) to test its fix (assuming you are in `RIOTBASE`:
```sh
cat << EOF > test_dtls.py
#! /usr/bin/env python3
import sys
from riotctrl.ctrl import RIOTCtrl
sys.path.append("dist/pythonlibs")
from riotctrl_shell.netif import …
```
> examples/dtls-echo: set address family for sessions

- sys/include/net/gnrc/netif/conf.h
When configuring a boolean via Kconfig and setting it to `n`, the result is that the symbol will not be defined as a preprocessor macro. As a result, setting `CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX` to `n` has no effect, as
```
#ifndef CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX
#define CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX   1
#endif
```
(as was pointed out in https://github.com/RIOT-OS/RIOT/pull/17678#discussion_r810259709). Without changing the name to a negative, the only other valid option is to check if `gnrc_netif` was configured via Kconfig in addition to the normal `#ifndef`. This PR applies that change.
Once a global address is configured with
```
BOARD=native RIOT_CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX=n RIOT_CONFIG_KCONFIG_USEMODULE_GNRC_NETIF=y make -C examples/gnrc_border_router flash -j …
```
> gnrc_netif_conf: fix auto-6ctx switch

- examples/dtls-echo/dtls-client.c
- examples/dtls-echo/dtls-server.c
d424aaedacf5e77a8310edaf1a87543d22f6e6ab introduced address families to the RIOT interpretation of tinydtls-`session_t`s. However, while fixing the naming for the `addr` field, it did not set the `family` member for the sessions in the `dtls-echo` example, having that example run into [an assertion][1]. This patch fixes that.
[1]: https://github.com/eclipse/tinydtls/blob/bda40789a7c280f248eeca6d09ddd624cdaf5dc8/session.c#L146
I used the same script to [find the issue](https://github.com/RIOT-OS/RIOT/pull/18368#issuecomment-1195474091) to test its fix (assuming you are in `RIOTBASE`:
```sh
cat << EOF > test_dtls.py
#! /usr/bin/env python3
import sys
from riotctrl.ctrl import RIOTCtrl
sys.path.append("dist/pythonlibs")
from riotctrl_shell.netif import …
```
> examples/dtls-echo: set address family for sessions [backport 2022.07]

- sys/net/application_layer/gcoap/dns.c
While doing some more experiments with the current version of `gcoap_dns`, I noticed some bugs, specifically, when using block-wise transfer. This PR fixes those and also replaces some left-over `printf`s with `DEBUG`.
Similar to the testing procedures in #16705:
```console
$ sudo dist/tools/tapsetup/tapsetup
$ sudo ip addr add 2001:db8::1 dev tapbr0
$ sudo ip route add 2001:db8::/64 via "<native link-local>" dev tapbr0
$ pip install --upgrade git+https://github.com/miri64/aiodnsprox.git@exp  # blockwise does not work with upstream aiodnsprox yet
$ cat << EOF > config.yaml
dtls_credentials:
client_identity: Client_identity
psk: secretPSK
mock_dns_upstream:
IN:
A: 192.0.2.7
AAAA: 2001:db8::7
$ aiodns-proxy -C config.yaml -c 2001:db8::1
```
```shell
RIOT_CONFIG_KCONFIG_USEMODULE_GCOAP_DNS=y …
```
> gcoap_dns: various fixes [backport 2022.07]

- sys/include/net/gnrc/netif/conf.h
When configuring a boolean via Kconfig and setting it to `n`, the result is that the symbol will not be defined as a preprocessor macro. As a result, setting `CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX` to `n` has no effect, as
```
#ifndef CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX
#define CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX   1
#endif
```
(as was pointed out in https://github.com/RIOT-OS/RIOT/pull/17678#discussion_r810259709). Without changing the name to a negative, the only other valid option is to check if `gnrc_netif` was configured via Kconfig in addition to the normal `#ifndef`. This PR applies that change.
Once a global address is configured with
```
BOARD=native RIOT_CONFIG_GNRC_NETIF_IPV6_BR_AUTO_6CTX=n RIOT_CONFIG_KCONFIG_USEMODULE_GNRC_NETIF=y make -C examples/gnrc_border_router flash -j …
```
> gnrc_netif_conf: fix auto-6ctx switch [backport 2022.07]

- tests/ieee802154_hal/main.c
- tests/ieee802154_submac/main.c
This PR takes over original work by @MichelRottleuthner and does essentially 3 things:
1. It fixes a missing call to `ieee802154_set_rx` on TX_DONE if the radio supports ACK_TIMEOUT or FRAME_RETRANS.
2. It adds support for ACK_REQ flag in `tests/ieee802154_hal`
3. It indicates the received packet length in `tests/ieee802154_submac`
1. Make sure `tests/ieee802154_hal` works as expected and try sending messages with and without ACK_REQ:
```
txtsnd <ext_addr> <len> ack_req
txtsnd <ext_addr> <len>
```
3. Make sure `tests/ieee802154_submac` works as expected and displays the received packet length.
None so far, but it will be required for the KW2xRF Radio HAL port
> tests/ieee802154_*: fix tx_done handler on ACK_TIMEOUT and improve tests

- boards/common/saml1x/include/periph_conf.h
- boards/saml11-xpro/doc.txt
- dist/tools/edbg/Makefile
This PR updates EDBG version to its lastest master. It contains a fix needed by SAML11 so we can properly set fuses in User ROW memory.
Also update SAML11 board documentation: In order to use SERCOM1 on EXT1 connector. A special fuse bit must be set to enable non-secure operation on this SERCOM (As RIOT doesn't support the secure world of the SAML11 yet).
Enable SERCOM1 non-secure mode using EDBG and try to use SERCOM1 with `tests/periph_uart`
`EDBG_ARGS="-F w0,194,1" BOARD=saml11-xpro make flash term -C tests/periph_uart`
Fixes #17206
> dist/tools/edbg: bump version (and update SAML11 documentation)

- sys/include/net/sock/dtls.h
Currently, using optional DTLS code, requires a lot of preprocessor-foobar. With this change, it should be possible to use more C-conditionals instead.
E.g. `make -C examples/gcoap -j` compiles with the following patch
```patch
diff --git a/sys/include/net/gcoap.h b/sys/include/net/gcoap.h
index 92006c045a..c54b225c3a 100644
--- a/sys/include/net/gcoap.h
+++ b/sys/include/net/gcoap.h
@@ -403,5 +403,3 @@
#include "net/sock/udp.h"
-#if IS_USED(MODULE_GCOAP_DTLS)
#include "net/sock/dtls.h"
-#endif
#include "net/nanocoap.h"
```
On the flip-side, apps that use `sock_dtls` should also still compile.
See https://github.com/RIOT-OS/RIOT/pull/18378#issuecomment-1197995428
> sock_dtls: make sock_dtls-header includeable without `sock_dtls` module

- pkg/littlefs/fs/littlefs_fs.c
- pkg/littlefs2/Kconfig
- pkg/littlefs2/fs/littlefs2_fs.c
- sys/include/fs/littlefs2_fs.h
- sys/include/fs/littlefs_fs.h
- tests/pkg_littlefs/main.c
- tests/pkg_littlefs2/main.c
The reason for me to create this PR was that I was experiencing problems when I tried to run `littlefs` and `littlefs2` on my `at24c256` EEPROM.
Currently, the block size is always equal to `mtd->page_size * mtd->pages_per_sector`, but in practice the block size must only be a multiple of the sector size.
In my case, the resulting block size was 64 bytes, equal to the sector size, equal to the page size.
I read some `littlefs` [documentation](https://github.com/ARMmbed/mbed-littlefs/blob/master/littlefs/DESIGN.md) and found out that the minimum block size must be 104 bytes.
With this patch, resulting in a block size of 128 bytes, problems seemed to be gone.
```diff
diff --git a/drivers/at24cxxx/mtd/mtd.c b/drivers/at24cxxx/mtd/mtd.c
index 73b530a98c..76588c8efd 100644
--- …
```
> littlefs: make block size configurable at compile time

- pkg/tinydtls/Makefile
- pkg/tinydtls/contrib/sock_dtls.c
- sys/include/net/sock/dtls.h
Just the same as `sock_udp_sendv_aux()`, but for `sock_dtls`.
I modified `examples/dtls-sock`:
```patch
diff --git a/examples/dtls-sock/dtls-client.c b/examples/dtls-sock/dtls-client.c
index 71560c22b4..cb27ed5ae1 100644
--- a/examples/dtls-sock/dtls-client.c
+++ b/examples/dtls-sock/dtls-client.c
@@ -199,7 +199,18 @@ static int client_send(char *addr_str, char *data, size_t datalen)
}
printf("Connection to server successful\n");
-    if (sock_dtls_send(&dtls_sock, &session, data, datalen, 0) < 0) {
+    const iolist_t tail = {
+        .iol_base = (void *)data,
+        .iol_len  = datalen,
+    };
+
+    const iolist_t head = {
+        .iol_base = "Hello ",
+        .iol_len  = 6,
+        .iol_next = (void *)&tail,
+    };
+
+    if (sock_dtls_sendv(&dtls_sock, &session, &head, 0) < …
```
> net/sock/dtls: introduce sock_dtls_sendv_aux()

- sys/Makefile.dep
- sys/include/net/dns.h
- sys/net/netutils/util.c
- sys/net/sock/sock_util.c
Since we can have multiple DNS backends now, provide a common `dns_query()` wrapper function that allows to write backend agnostic applications.
> dns: provide generic dns_query() function

- examples/asymcute_mqttsn/Makefile.ci
- examples/cord_lc/Makefile.ci
- examples/gcoap/Makefile.ci
- sys/Makefile.dep
- tests/gnrc_rpl/Makefile.ci
Add missing dependency to xtimer so that the shell command `ping` is
again provided when requested.
Run `make BOARD=nucleo-f767zi -C examples/gnrc_networking flash term` and then `help`. If the `ping` command is listed again, the bug is fixed. (Did so, worked for me.)
None
> sys/shell/commands/ping: fix dependency [backport 2022.07]

- drivers/dose/dose.c
- drivers/include/dose.h
To benefit from the chunked ringbuffer if large frames are being sent, we need to allocate more than one ethernet frame length to it.
Rename the define and make it overwriteable by the user.
Only a define was renamed, no change in code.
> drivers/dose: make RX buffer size configurable

- sys/shell/commands/sc_nanocoap_vfs.c
Currently the `ncget` command always requires to specify the full destination path (including destination filename).
Allow to specify only the destination directory and concatenate the filename automatically from the source URL.
```
2022-08-01 17:05:27,664 - INFO # > ncget coap://[2001:1438:400c:7710:ab73:e659:68de:da87]/ict_concentrator-v3-12_fw1.bin /sd0/fw/
2022-08-01 17:05:42,296 - INFO # Saved as /sd0/fw/ict_concentrator-v3-12_fw1.bin
```
> sys/shell: improve 'ncget' command

- cpu/esp32/esp-eth/esp_eth_netdev.c
- cpu/esp_common/esp-wifi/esp_wifi_netdev.c
- drivers/include/net/netdev.h
This PR fixes missing netdev types and registration for `esp_wifi` and `esp_eth` and `tests/driver_esp_eth`.
In investigating why the nightlies have been failing since merging PR #17739, I found that `tests/driver_esp_eth` in `event_post` crashes when called here https://github.com/RIOT-OS/RIOT/blob/24ff493d048d4f511fd198ec022b32157d054ef6/sys/test_utils/netdev_eth_minimal/netdev_eth_minimal.c#L71-L77 because `dev->context` is not set. The reason is that `NETDEV_ESP_ETH` was not defined and `netdev_register` is not called during setup in `esp_eth` driver.
This PR
- adds `NETDEV_ESP_ETH` and `NETDEV_ESP_WIFI`
- calls `netdev_register` in setup of `esp_eth` and `esp_wifi`
This PR **might need a backport** to 2022.07.
BTW, a fix for the compilation problem in nightlies will be provided once …
> cpu/esp: fix netdev register

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- sys/rust_riotmodules_standalone/Cargo.lock
- tests/rust_minimal/Cargo.lock
The riotmodules dependency was missed in bc8ec6d5, and while generally
it does not severly harm builds, it does harm builds riotdocker CI where
branches are switched, which is blocked by dirty files in the checkout.
The riot-wrappers version was missed when what is now 5e75f4bd was
rebased onto fdc4e11a.
* Green CI
* Building anything (eg `riot-hello-world) locally does not result in a dirty checkout after building. (CI doesn't check for that, but riotdocker CI does).
Unblocks: https://github.com/RIOT-OS/riotdocker/pull/200 (or any other CI update, really)
> rust: Bring lock files in sync with toml files

- boards/nucleo-f767zi/Kconfig
- boards/nucleo-f767zi/Makefile.features
- boards/nucleo-f767zi/include/periph_conf.h
This is a verbatim copy of the PWM config of `boards/nucleo-f746zg`. However, those boards are almost identical. I successfully tested the configuration via https://github.com/RIOT-OS/RIOT/pull/18392
E.g. using `tests/periph_pwm` or any driver than uses PWM, such as https://github.com/RIOT-OS/RIOT/pull/18392
But to be honest, the F746ZG is a "subset" of the F767ZI MCU. So everything working on the F746ZG should just work on the F767ZI.
None
> boards/nucleo-f767zi: add PWM config

- drivers/mtd/Kconfig
This PR fixes the module name in `drivers/mtd/Kconfig` for module `mtd_sdcard`.
The used module is called `mtd_sdcard`. Dependencies in Kconfig has to use same name for the module and should use the name for the feature. Therefore,
- `HAVE_MTD_SD_CARD` is changed to `HAVE_MTD_SDCARD` and
-  `MODULE_MTD_SD_CARD` is changed to `MODULE_MTD_SDCARD`.
Green CI
> drivers/mtd: fix module name for mtd_sdcard in Kconfig

- tests/README.md
During running all tests for few boards I noticed some lack of information in the tests doc page, for example, information how execute all automatic tests for particular board or about cleaning intermediate files. Moreover, current version of the documentation mixes information about running and implementation of tests.
My contribution:
- add section concerning execution of all automate tests for particular boards,
- add section concerning cleaning all intermediate files,
- reorganization of documentation - move to the begin of page all information concerning test execution, later all information concerning implementation,
- change section heading style, from dashed line (first time spotted in this file) to hashes (used in all other doc files).     
```
make doc
xdg-open …
```
> tests/doc: some additions and reorganization of doc page

- dist/tools/doccheck/exclude_patterns
- examples/gcoap_fileserver/Makefile
- examples/gcoap_fileserver/main.c
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/net/coap.h
- sys/include/net/gcoap/fileserver.h
- sys/include/vfs_util.h
- sys/net/application_layer/gcoap/fileserver.c
- sys/shell/commands/sc_vfs.c
- sys/vfs_util/vfs_util.c
With this PR I added write support for the `gcoap` fileserver, using `POST`, `PUT` and `DELETE` methods.
~`POST`: used to create files and directories~
`PUT` : creates files or directories or updates files in a random access fashion
`DELETE`: delete files and directories
CoAP options `If-Match` and `If-None-Match` are added and handled in `PUT` requests.
Somehow directory deletion does not work for me. I end up in `littlefs2/lfs.c:1457`.
```C
// check if we fit
lfs_size_t dsize = lfs_tag_dsize(tag);
if (commit->off + dsize > commit->end) {
return LFS_ERR_NOSPC;
}
```
~I don´t know why. Maybe it works for you.~
Works with #18141
Flash `examples/gcoap_fileserver` to a board with Ethernet support, connect with your PC and use a CoAP client to upload some files to the board´s VFS.
<details> …
> gcoap/fileserver: add file and directory creation and deletion

- .murdock
- boards/waveshare-nrf52840-eval-kit/Kconfig
- boards/waveshare-nrf52840-eval-kit/Makefile
- boards/waveshare-nrf52840-eval-kit/Makefile.dep
- boards/waveshare-nrf52840-eval-kit/Makefile.features
- boards/waveshare-nrf52840-eval-kit/Makefile.include
- boards/waveshare-nrf52840-eval-kit/board.c
- boards/waveshare-nrf52840-eval-kit/doc.txt
- boards/waveshare-nrf52840-eval-kit/include/arduino_board.h
- boards/waveshare-nrf52840-eval-kit/include/arduino_pinmap.h
- boards/waveshare-nrf52840-eval-kit/include/board.h
- boards/waveshare-nrf52840-eval-kit/include/gpio_params.h
- boards/waveshare-nrf52840-eval-kit/include/periph_conf.h
- dist/tools/doccheck/exclude_patterns
This PR adds the support for the [Waveshare nRF52840 Eval Kit](https://www.waveshare.com/wiki/NRF52840_Eval_Kit).
The main on-board components of the Waveshare nRF52840 Eval Kit are:
- Arduino headers for connecting Arduino shields
- Raspberry Pi GPIO header for connecting Raspberry Pi HATs
- USB to UART bridge
- Optical sensor (LDR)
- 2 user keys RESET and KEY
- 4 User LEDs
- TF card slot
- CR2032 battery holder
The board definition include SAUL support as well Arduino support including Arduino PWM. The follwing peripherals and on-board components were tested:
[UPDATE] ~Commit https://github.com/RIOT-OS/RIOT/commit/84db9c269736e9a33d3a8c49489130dc583ccc0f can be dropped once PR #13858 is merged.~
~Depends on PR #14480~
> boards: add support for the Waveshare nRF52840 Eval Kit

- pkg/nimble/Makefile.include
Using double quotes can cause issues when the final cmake command is called, and you end up with un-escaped nested double quotes.
> pkg/nimble: Replace double quotes with single quotes for two CFLAGS

- sys/net/ieee802154.txt
Fixed a typo in the IEEE 802.15.4 docs.
```eanbled -> enabled```
(am I being helpful yet ?)
> sys/net: fix typo in docs

- dist/tools/zep_dispatch/README.md
- dist/tools/zep_dispatch/main.c
- dist/tools/zep_dispatch/zep_parser.c
- dist/tools/zep_dispatch/zep_parser.h
This adds support to view the entire traffic of the simulated network in Wireshark.
For this all packets are sent to a virtual 802.15.4 device (`mac802154_hwsim`) that then acts as a capture source in Wireshark.
Create the simulated 802.15.4 device by loading the `mac802154_hwsim` module
sudo modprobe mac802154_hwsim
Now start the dispatcher (needs elevated privileges to send raw 802.15.4 frames)
sudo bin/zep_dispatch -w wpan1 ::1 17754
Start two `native` nodes that make use of ZEP
make -C examples/gnrc_networking USE_ZEP=1 all term
make -C examples/gnrc_networking USE_ZEP=1 all term
If you connect to the `wpan0` interface in Wireshak now, you should see the packets on the network:
> tools/zep_dispatch: add Wireshark capture support (via mac802154_hwsim)

- .murdock
- boards/esp32-ethernet-kit-v1_0/Kconfig
- boards/esp32-ethernet-kit-v1_0/Makefile.features
- boards/esp32-ethernet-kit-v1_1/Kconfig
- boards/esp32-ethernet-kit-v1_2/Kconfig
- boards/esp32-olimex-evb/Kconfig
- boards/esp32-olimex-evb/Makefile.features
- cpu/esp32/Makefile.dep
- cpu/esp32/esp-eth/Kconfig
- tests/driver_esp_eth/Kconfig
- tests/driver_esp_eth/Makefile
This PR fixes Kconfig problems for `esp_eth` introduced with PR #17739.
In `Makefiles.features`, `periph_eth` was defined as provided feature without having a peripheral driver implementation for the ETH interface  in `cpu/esp32/periph`. Instead, the `esp_eth` netdev driver directly uses the ESP-IDF Ethernet API. This caused compilation problems with Kconfig. Therefore the required feature `periph_eth` is replaced by the feature `esp_eth` and `HAS_PERIPH_ETH` is replaced by `HAS_ESP_ETH` in Kconfig.
Furthermore, the selection of modules in Kconfig was not correct if the module `esp_eth` was used. The reason for this is that the dependencies of modules have changed with the migration to ESP-IDF 4.4.
Since no board with the feature `esp_eth` was compiled with `TEST_KCONFIG=1`, the problems …
> cpu/esp32: fix provided features and Kconfig for esp_eth

- dist/tools/esptools/export.sh
- dist/tools/esptools/install.sh
This PR is a split-off from PR #18185 which extends the  the `{install,export}.sh` scripts  by the support of the ESP32-S3 toolchain.
Test the installation and the export of the path of the ESP32-S3 toolchain by executing following commands:
```
dist/tools/esptools/install.sh esp32s3
. dist/tools/esptools/export.sh esp32s3
```
> dist/tools/esptools: add ESP32-S3 toolchain support to {install,export}.sh

- cpu/stm32/periph/eth.c
A single character type resulted in way fewer TX descriptors being available than allocated. Not only resulted this in wasting memory, but also when more iolist chunks than descriptors are send, the
```C
assert(iolist_count(iolist) <= ETH_TX_DESCRIPTOR_COUNT);
```
does not trigger. As a result, old TX descriptors are being overwritten in this case.
@fabian18 has a test that reliably triggers the bug. He should be able to confirm it is gone now. But actually, it should be pretty obvious from the code that this fixes a typo.
None
> cpu/stm32/periph_eth: fix typo in initialization code

- cpu/stm32/periph/eth.c
A single character type resulted in way fewer TX descriptors being available than allocated. Not only resulted this in wasting memory, but also when more iolist chunks than descriptors are send, the
```C
assert(iolist_count(iolist) <= ETH_TX_DESCRIPTOR_COUNT);
```
does not trigger. As a result, old TX descriptors are being overwritten in this case.
@fabian18 has a test that reliably triggers the bug. He should be able to confirm it is gone now. But actually, it should be pretty obvious from the code that this fixes a typo.
None
> cpu/stm32/periph_eth: fix typo in initialization code [backport 2022.07]

- cpu/stm32/periph/eth_common.c
We can just clear both TX and RX IRQ flags in any case, as clearing a non-set flag is just a nop.
Network operation should still work as usual.
> cpu/stm32/periph_eth: optimize IRQ handler

- cpu/esp32/Kconfig
- cpu/esp32/Kconfig.esp32s3
This PR is a split-off from #18185 and adds the support of ESP32-S3 in Kconfig.
Green CI
> cpu/esp32: add ESP32-S3 support in Kconfig

- boards/nucleo-f030r8/doc.txt
- boards/nucleo-f070rb/doc.txt
- boards/nucleo-f072rb/doc.txt
- boards/nucleo-f091rc/doc.txt
- boards/nucleo-f103rb/doc.txt
- boards/nucleo-f302r8/doc.txt
- boards/nucleo-f303re/doc.txt
- boards/nucleo-f334r8/doc.txt
- boards/nucleo-f401re/doc.txt
- boards/nucleo-f410rb/doc.txt
- boards/nucleo-f411re/doc.txt
- boards/nucleo-f446re/doc.txt
- boards/nucleo-g070rb/doc.txt
- boards/nucleo-g071rb/doc.txt
- boards/nucleo-g431rb/doc.txt
- boards/nucleo-g474re/doc.txt
- boards/nucleo-l053r8/doc.txt
- boards/nucleo-l073rz/doc.txt
- boards/nucleo-l152re/doc.txt
- boards/nucleo-l433rc/doc.txt
- boards/nucleo-l452re/doc.txt
- boards/nucleo-l476rg/doc.txt
- boards/nucleo-wl55jc/doc.txt
PR #18057 enables **_cpy2remed_** programmer for all STM Nucleo boards.
This PR adds to nucleo64 boards documentation:
-  information about usage of **_cpy2remed_** programmer,
-  short information about board (used MCU, available RAM and Flash),
-  change all memory sizes to KiB (before kB or Kb are used) .
Changes in documentation can be observed using commands:
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f030r8.html
xdg-open doc/doxygen/html/group__boards__nucleo-f070rb.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f072rb.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f091rc.html
xdg-open doc/doxygen/html/group__boards__nucleo-f103rb.html
xdg-open doc/doxygen/html/group__boards__nucleo-f302r8.html 
xdg-open …
```
> boards/nucleo64: doc update - usage of cpy2remed programmer and short board overview

- cpu/esp32/ld/esp32c3/sections.ld
- cpu/esp32/ld/esp32s3/memory.ld
- cpu/esp32/ld/esp32s3/sections.ld
This PR is a split-off from #18185. It adds the linker script for ESP32-S3 and modify the ESP32-C3 linker scripts to be compatible with them. The goal is to use a section list of objects that is common for all ESP32x SoCs in future.
Green CI.
> cpu/esp32: add linker scripts for ESP32-S3

- sys/net/application_layer/gcoap/gcoap.c
gcoap's `_find_req_memo` compares tokens and IP addresses. That's generally a good thing, but when requests are sent to a multicast address, it is not right (RFC7252 has an explicit exception there).
There may be other areas of multicast support that are lacking, but this is a small enhancement step.
Have a local CoAP server that responds to multicasts (`aiocoap-fileserver` will do, even though that might be a bug there, gotta check out whether it's supposed to do that by default).
```
$ make -C examples/gcoap
> coap get ff01::2 5683 /.well-known/core
</>;ct=40
```
Previously, the request timed out.
Note that good multicast behavior would be to accept several servers' responses, and (in the command line client) to show the address of the server where the response came from, both is left …
> gcoap: Forego IP address comparison in memo finding of multicasts

- cpu/esp32/Makefile.dep
- cpu/esp32/Makefile.features
- cpu/esp32/Makefile.include
- cpu/esp32/esp-idf/adc/Makefile
- cpu/esp32/esp-idf/common/Makefile
- cpu/esp32/esp-idf/spi_flash/Makefile
- cpu/esp32/esp-idf/spi_ram/Makefile
This PR is a split-off from #18185 and adds the support of ESP32-S3 to the makefiles.
Green CI
> cpu/esp32: add ESP32-S3 support to makefiles

- sys/net/application_layer/gcoap/gcoap.c
This adds two fixes around the handling and sending of empty ACKs:
1. Send empty ACKs on CON response, even if there is no `memo` that matches this response.
2. Expire request on empty ACK when there is no response handler to wait for.
The 1. fix may be disputable. In my opinion it makes more sense to send a few short empty ACKs more than having some server sending a potentially large CON response multiple times just because the server missed a previous ACK, but I can remove this if this is for some reason not a good idea.
Not sure how to test this... I saw it while running some experiments with #18386.
None, but improves behavior in #18386.
> gcoap: fixes around empty ACKs

- sys/net/application_layer/asymcute/asymcute.c
Currently, asymcute matches an MQTT-SN request to its acknowledgement using *only* the MsgId header. However, I strongly believe this to be insufficient as asymcute would thus also match a SUBACK to a prior PUBLISH request (for example) as long as the message ID matches. If this happens (e.g. because of a malicious MQTT-SN broker) then this can trigger various bugs in asymcute, e.g. due to incorrect casts of the `req->arg` `void*` pointer. To address this issue, this commit modifies `_req_preprocess` to also compare the request message type in addition to the message id.
I haven't tested my fix extensively yet but existing tests should continue to work. Unfortunately, it also a bit difficult to provide a simple test setup for triggering this edge case. 
None.
> asymcute: Compare request message type when matching acknowledgement

- sys/net/application_layer/gcoap/gcoap.c
This adds two fixes around the handling and sending of empty ACKs:
1. Send empty ACKs on CON response, even if there is no `memo` that matches this response.
2. Expire request on empty ACK when there is no response handler to wait for.
The 1. fix may be disputable. In my opinion it makes more sense to send a few short empty ACKs more than having some server sending a potentially large CON response multiple times just because the server missed a previous ACK, but I can remove this if this is for some reason not a good idea.
Not sure how to test this... I saw it while running some experiments with #18386.
None, but improves behavior in #18386.
> gcoap: fixes around empty ACKs [backport 2022.07]

- cpu/esp32/doc.txt
- cpu/esp32/periph/gpio.c
This PR extends the GPIO wake-up logic from deep sleep.
Depending on SoC capabilities, ESP32x SoC variants support different logical combinations of GPIO levels to wake-up from deep sleep. This change is necessary for example necessary to use GPIOs for waking up ESP32-C3 from deep sleep.
Without this PR, the compilation for all `ESP_PM_WUP_LEVEL` values:
```
CFLAGS='-DESP_PM_WUP_PINS=GPIO8 -DESP_PM_WUP_LEVEL=ESP_PM_WUP_PINS_ANY_HIGH \
-DESP_PM_WUP_UART0=6 -DESP_PM_GPIO_HOLD' make BOARD=esp32c3-devkit -C tests/periph_pm
```
fail with `implicit declaration of function 'esp_sleep_enable_ext1_wakeup'`
With this PR
```
CFLAGS='-DESP_PM_WUP_PINS=GPIO8 -DESP_PM_WUP_LEVEL=ESP_PM_WUP_PINS_ANY_HIGH \
-DESP_PM_WUP_UART0=6 -DESP_PM_GPIO_HOLD' make BOARD=esp32c3-devkit -C tests/periph_pm
```
and
``` …
```
> cpu/esp32: extend GPIO wake-up from deep sleep

- sys/net/application_layer/asymcute/asymcute.c
> [Backport] asymcute: Compare request message type when matching acknowledgement

- cpu/nrf52/Kconfig
- cpu/nrf52/Makefile.features
- cpu/nrf5x_common/Kconfig
- kconfigs/Kconfig.features
- pkg/nimble/Makefile.dep
This PR provides the following changes regarding BLE features:
- Since the existing Kconfig features `HAS_BLE_NIMBLE*` and `HAS_BLE_PHY_*` can also be provided by other platforms, the definition of these features are moved to the common file `$(RIOTBASE)/kconfigs/Kconfig.feature`.
- To control the compilation of NimBLE modules `nimble_*_ext` that require the Bluetooth 5 Advertising Extension, the `ble_adv_ext`/`HAS_BLE_ADV_EXT` feature is introduced to indicate that a platform supports this feature.
- Add feature `ble_adv_ext`/`HAS_BLE_ADV_EXT` for nRF52 MCUs.
- Fixes the alphabetical order of Kconfig feature `HAS_RUST_TARGET` in file `$(RIOTBASE)/kconfigs/Kconfig.feature`.
Green CI
Prerequisite for PR #18439
> pkg/nimble: add feature ble_adv_ext and cleanup ble_* features

- sys/net/application_layer/asymcute/asymcute.c
> [Backport] asymcute: fix one byte out-of-bounds access in _len_get

- cpu/nrf52/radio/nrf802154/nrf802154_radio.c
This changes were (almost) cherry-picked from #18156.
It addresses three things:
- It fixes CCA result (before was just throwing garbage)
- It fixes a variable initialization
- It prevents the broadcast PAN ID being filtered.
These commits are required in order to run #18156.
- Try running the cca command in `tests/ieee802154_hal`. It should report a mixture of "BUSY" and "CLEAR".
- Set the PAN address of any node to the PAN broadcast (0xffff). The node should still be able to receive frames.
#18156
> drivers/nrf802154: do not filter broadcast PAN ID

- tests/unittests/README.md
This pull request corrects a typo in the documentation for the unit tests.
The name in `EMB_UNIT_TESTCALLER` and the name in the cast should be equal:
``` c++
EMB_UNIT_TESTCALLER(<module>_<header>_tests, set_up, tear_down, fixtures);
return (Test *)&<module>_<header>; // should be <module>_<header>_test
```
> tests/unittests: Correct typo in documentation

- pkg/nimble/statconn/nimble_statconn.c
This PR fixes a small formatting bug of the flags in Advertising Data in Legacy Advertising for `pkg/nimble/statconn`.
Without this PR, the slave nodes advertise improperly formatted data. The `nRFConnect` app shows "Error while parsing EIR (0x06)". The reason is that a static character buffer is used as Advertising Data https://github.com/RIOT-OS/RIOT/blob/f2720940d76829ac494cde582e2d347efdf4e755/pkg/nimble/statconn/nimble_statconn.c#L52 which is not formatted properly. Each Advertising Data field has to consist of a length, the type and the data.
In case of the flags that are advertised in `pkg/nimble/statconn`, the data have to consist of the 3 bytes:
```
static const uint8_t _ad[] = { 2, BLE_GAP_AD_FLAGS, BLUETIL_AD_FLAGS_DEFAULT };
```
Furthermore, it is not necessary to define the …
> pkg/nimble: fix of legacy advertising in statconn

- cpu/esp32/doc.txt
- cpu/esp32/doc_esp32s3.txt
This PR is a split-off from #18185 which adds ESP32-S3 support to the documentation.
Green CI
> cpu/esp32: add ESP32-S3 support to documentation

- sys/include/vfs.h
- sys/shell/commands/sc_vfs.c
- sys/vfs/vfs.c
This adds `vfs_format_by_path()` analoguous to `vfs_mount_by_path()` and `vfs_unmount_by_path()`.
Just as with `vfs_format()` the file system needs to be unmounted first before it can be formatted.
```
> vfs w /nvm0/test.txt ascii a "Hello World!"
> ls /nvm0
./
../
test.txt	12 B
total 1 files
> vfs format /nvm0
-EBUSY
> vfs umount /nvm0
> vfs format /nvm0
> vfs mount /nvm0
> ls /nvm0
./
../
total 0 files
```
> vfs: introduce vfs_format_by_path()

- sys/include/net/nanocoap.h
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/net/application_layer/nanocoap/nanocoap_internal.h
We don't have to carry this information inside every `coap_pkt_t`, it's enough to provide it via the request context information.
`examples/gcoap_dtls` still works
```
> coap get fe80::7837:fcff:fe7d:1aaf 5684 /.well-known/core
gcoap_cli: sending msg ID 7277, 23 bytes
gcoap: response Success, code 2.05, 46 bytes
</cli/stats>;ct=0;rt="count";obs,</riot/board>
```
> gcoap: move tl_type to coap_request_ctx_t

- cpu/sam0_common/sam0_eth/Kconfig
- cpu/stm32/periph/Kconfig.eth
- drivers/sx1280/Kconfig
- pkg/lorabasics/patches/0003-ral_sx1280-fix-unused-parameter-warning.patch
This fixes the discrepancy between the `USEMODULE` based dependency resolution and the KConfig based dependency resolution.
CI should build again
follow-up to #18426
> cpu/{sam0_common, stm32}: select netdev_legacy_api in KConfig

- drivers/kw2xrf/Kconfig
This PR removes a leftover dependency from the Kconfig file of KW2XRF radios. Since this radio supports the Radio HAL, the `netdev_ieee802154` module is not required anymore
`NIGHTLY=1 /bin/bash -c "source .murdock; JOBS=4 compile tests/ieee802154_hal pba-d-01-kw2x:gnu"`should pass
None so far
> kw2xrf/Kconfig: remove netdev_ieee802154 from dependency resolution

- sys/include/fs/littlefs2_fs.h
- sys/include/fs/littlefs_fs.h
This aligns the buffers in `littlefs_desc_t` / `littlefs2_desc_t` to fix hard faults on Cortex M0+ MCUs such as the `samr21-xpro`.
Prior to https://github.com/RIOT-OS/RIOT/pull/18141 the alignment requirement was met but luck. With this, the alignment requirement is now communicated to the compiler, which should fix future issues.
> pkg/{littlefs,littlefs2}: fix unaligned memory accesses

- sys/bhp/Kconfig
- sys/bhp/Makefile.dep
- sys/bhp/Makefile.include
- sys/bhp/msg.c
- sys/include/bhp/msg.h
- tests/unittests/tests-bhp_msg/Makefile
- tests/unittests/tests-bhp_msg/Makefile.include
- tests/unittests/tests-bhp_msg/tests-bhp_msg.c
- tests/unittests/tests-bhp_msg/tests-bhp_msg.h
This PR adds an IPC version of the `bhp` module. It allows device independent IRQ offloading using message queues.
A `bhp_msg_t` descriptor holds the PID of a thread that performs Bottom Half processing on reception of a message with a dedicated type. Similar to https://github.com/RIOT-OS/RIOT/pull/18435, this mechanism can be adapted to existing `init` functions of drivers to hook in IRQ offloading.
`tests/unittests` should pass.
https://github.com/RIOT-OS/RIOT/pull/18435
Required for adding LWIP support for radios that require IRQ offloading
> sys/bhp_msg: add IPC based implementation of Bottom Half Processor

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- sys/rust_riotmodules_standalone/Cargo.lock
- tests/rust_minimal/Cargo.lock
A change in Rust nightly features broke version 0.2.5 of the `cstr`
crate, whose nightly-only features are enabled in some examples. The
breakage was quickly fixed upstream in the 0.2.6 version, this updates
the locks.
---
We could (and should, to minimize this on the long run) also stop using the nightly features -- but given that riot-wrappers are about to switch over to what the standard library now provides anyway, this is the least intrusive fix.
The issue doesn't hit us now because our Rust nightly version is pinned, but it'd hit us as soon as we updated the Rust nightly version in riotdocker.
* Green CI
* The breakage before this PR only shows when using a local Rust installation and building the rust-gcoap example with a recent nightly. (I tested that).
Builds on #18388 (they …
> rust: Update cstr dependency

- pkg/nimble/statconn/nimble_statconn.c
- sys/shell/commands/sc_nimble_netif.c
This PR fixes a problem when using `nimble_statconn`.
`nimble_statconn` master has to define the peer address type of the slave node to which the connection is established by the master. Using a `BLE_ADDR_RANDOM` as the peer address type allows connecting only to peers that have a static random address. Deriving the peer address type from the peer address is simple and allows connections to be established with peers that have either a public or static random address.
Furthermore, to see which type of address is used as own address, the output of the `ble info` command has been extended by the address type info.
The problem was found when investigating in PR #18439 the reason why `tests/nimble_statconn_gnrc*` failed.
Use two BLE nodes and flash `tests/nimble_statconn_gnrc` and check that …
> pkg/nimble:derive peer address type from peer address

- pkg/ccn-lite/patches/0004-ccnl_content_remove-Fix-use-after-free.patch
Build the pkg/ccn-lite example with a current GCC. Before this patch, this fails as described in https://github.com/RIOT-OS/RIOT/issues/18480 -- after, it passes.
Closes: https://github.com/RIOT-OS/RIOT/issues/18480
Found while doing final tests for the 2022.07-RC3 at https://github.com/RIOT-OS/Release-Specs/issues/257
This has been reported upstream as https://github.com/cn-uofbasel/ccn-lite/pull/388
> pkg/ccn-lite: patch to fix use-after-free

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- sys/rust_riotmodules_standalone/Cargo.lock
- tests/rust_minimal/Cargo.lock
A change in Rust nightly features broke version 0.2.5 of the `cstr`
crate, whose nightly-only features are enabled in some examples. The
breakage was quickly fixed upstream in the 0.2.6 version, this updates
the locks.
---
We could (and should, to minimize this on the long run) also stop using the nightly features -- but given that riot-wrappers are about to switch over to what the standard library now provides anyway, this is the least intrusive fix.
The issue doesn't hit us now because our Rust nightly version is pinned, but it'd hit us as soon as we updated the Rust nightly version in riotdocker.
* Green CI
* The breakage before this PR only shows when using a local Rust installation and building the rust-gcoap example with a recent nightly. (I tested that).
Builds on #18388 (they …
> rust: Update cstr dependency [backport 2022.07]

- pkg/lvgl/Makefile
This change resolves a built issue cause by the added comment to the release tag in the Makefile.
Tested by compiling a project using LVGL.
N/A
> remove version comment fixing build issue

- makefiles/tools/kconfiglib.inc.mk
After introducing #18423 there are occasional messages that still happen.
These messages cause a diff output when testing with TEST_KCONFIG=1.
This then causes a failure when comparing make/kconfig modules and packages.
```
rm -f dist/tools/kconfiglib/menuconfig.py && /bin/bash -c "source .murdock; compile tests/shell native:gnu"
```
Introduced in #18423
Discovered by #18466
> makefiles: quiet messages on CI

- tests/ztimer_periodic/main.c
- Explain the reason on why the test fails if it fails
- Relax offset for ZTIMER_USEC on native, as this depends on the jitter
emitted by the non-realtime OS native is running on
The test should now pass most of the time on `native`.
Fixes #18490
> tests/ztimer_periodic: improve output and relax on native

- sys/include/net/gnrc/netif.h
- sys/net/gnrc/link_layer/gomach/gomach.c
- sys/net/gnrc/link_layer/lwmac/lwmac.c
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/netif/init_devs/auto_init_kw2xrf.c
- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
This PR adds support for `gnrc_netif` priority queues.
Since some drivers run a Bottom Half Processor in the same `gnrc_netif` thread, events from MAC layers (e.g submac) can delay IRQ offloading. To avoid that, a second event queue with high priority is introduced if `MODULE_BHP_EVENT` is present.
I also use this queue for the event based Bottom Half Processor of `kw2xrf` radios.
Make sure all unittests pass. Also, `kw2xrf` should still work in GNRC.
Since I'm currently on the train I couldn't test it on real hardware. I will post tests results asap.
This should make MAC layers such as the SubMAC or openDSME more robust.
> net/gnrc_netif: add support for priority queues

- sys/net/application_layer/dns/cache.c
- tests/unittests/tests-dns_cache/tests-dns_cache.c
Existing entries should be expired, new entries should not be created.
I added a test case for TTL=0 to the unittests, so
```sh
make -C tests/unittests/ tests-dns_cache test
```
should succeed.
> dns_cache: handle TTL=0 properly

- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/lwip/include/lwip/netif/compat.h
This PR fixes a concurrency issue in LWIP, as a result of calling `netdev` functions from different context.
Traditionally our netdev driver model assumes implicitly that all `netdev` functions run on the same thread. As it is now, LWIP calls all send functions from the caller thread (e.g `main`), but processes ISR on a higher priority thread. This not only creates concurrency issues in existing devices, but renders other modules such as the SubMAC unusable...
To (temporally) solve this, I implemented some recursive mutex lock functions to acquire the device before calling any internal operation. In the future it would be better to schedule all transmissions from a single thread.
Although this won't make the current situation worse, I'm assuming LWIP uses mutex internally to prevent …
> pkg/lwip: fix netdev concurrency issues

- dist/tools/esptools/export.sh
- dist/tools/esptools/install.sh
This PR is a split-off from PR #18235 which extends the  the `{install,export}.sh` scripts  by the support of the ESP32-S2 toolchain.
Test the installation and the export of the path of the ESP32-S2 toolchain by executing following commands:
```
dist/tools/esptools/install.sh esp32s2
. dist/tools/esptools/export.sh esp32s2
```
> dist/tools/esptools: add ESP32-S2 toolchain support to {install,export}.sh

- cpu/esp32/Makefile.features
- cpu/esp32/Makefile.include
- cpu/esp32/esp-idf/adc/Makefile
- cpu/esp32/esp-idf/common/Makefile
- cpu/esp32/esp-idf/spi_flash/Makefile
This PR is a split-off from #18235 and adds the support of ESP32-S2 to the makefiles.
Green CI
> cpu/esp32: add ESP32-S2 support to makefiles

- LICENSE
It seems we have a very fun [not identifiable by github](https://img.shields.io/github/license/RIOT-OS/RIOT) github badge.
This allows github to identify our license.
Check out my [cutting edge repo badge](https://img.shields.io/github/license/MrKevinWeiss/RIOT) after merging it into my master. (note that in MrKevinWeiss/RIOT/README.md it still is showing the RIOT-OS badge)
> LICENSE: Fix github badge

- cpu/esp32/Kconfig
- cpu/esp32/Kconfig.esp32
- cpu/esp32/Kconfig.esp32c3
- cpu/esp32/Kconfig.esp32s2
- cpu/esp32/Kconfig.esp32s3
- cpu/esp_common/Kconfig
This PR is a split-off from #18235 and adds the support of ESP32-S2 in Kconfig.
Green CI
> cpu/esp32: add ESP32-S2 support in Kconfig

- cpu/esp32/doc.txt
- cpu/esp32/doc_esp32s2.txt
This PR is a split-off from #18235 which adds ESP32-S2 support to the documentation.
Green CI
> cpu/esp32: add ESP32-S2 support in documentation

- tests/periph_timer_short_relative_set/README.md
- tests/periph_timer_short_relative_set/main.c
Clarify the outcome of `tests/periph_timer_short_relative_set`, just so the next tester doesn't get confused/frustrated.
This is purely changing output, so, run `tests/periph_timer_short_relative_set` and see it output an additional note on failure.
Improves on #12610.
Fixes #18511.
> tests/periph_timer_short_relative_set: clarify outcome

- drivers/include/kw2xrf.h
- pkg/lwip/Makefile.dep
- pkg/lwip/contrib/netdev/lwip_netdev.c
- pkg/lwip/include/lwip/netif/compat.h
- pkg/lwip/init_devs/auto_init_kw2xrf.c
This PR utilizes https://github.com/RIOT-OS/RIOT/pull/18464 to run radio HAL based devices with LWIP. This also allows the usage of other non-netdev devices that require ISR offloading.
As a result of this PR, I also push support for KW2XRF radios on LWIP.
Murdock compile output should be fine
Test LWIP with any KW2XRF based radio.
~Depends on https://github.com/RIOT-OS/RIOT/pull/18464~
Now it depends on https://github.com/RIOT-OS/RIOT/pull/18479
> pkg/lwip: add support for HAL radios that require IRQ offloading

- cpu/sam0_common/periph/eth.c
- cpu/sam0_common/sam0_eth/eth-netdev.c
- drivers/dose/dose.c
- drivers/include/slipdev.h
- drivers/slipdev/slipdev.c
I was debugging the issue that packets where stuck in the RX path until the next packet was received, turns out they were stuck in the driver's RX queue:
```
2022-06-08 19:15:52,658 - INFO # > ping -i 2000 fd11:a000::e858:4ed2:564e:215b
2022-06-08 19:15:52,658 - INFO # 
2022-06-08 19:15:54,667 - INFO # 12 bytes from fd11:a000::e858:4ed2:564e:215b: icmp_seq=0 ttl=64 time=2001.958 ms
2022-06-08 19:15:56,667 - INFO # 12 bytes from fd11:a000::e858:4ed2:564e:215b: icmp_seq=1 ttl=64 time=2001.959 ms
2022-06-08 19:15:59,658 - INFO # 
2022-06-08 19:15:59,662 - INFO # --- fd11:a000::e858:4ed2:564e:215b PING statistics ---
2022-06-08 19:15:59,667 - INFO # 3 packets transmitted, 2 packets received, 33% packet loss
2022-06-08 19:15:59,672 - INFO # round-trip min/avg/max = 2001.958/2001.958/2001.959 …
```
> drivers/{dose, slipdev, sam0_eth}: generate RX event for queued packets

- boards/samr34-xpro/Kconfig
- boards/samr34-xpro/Makefile.dep
- boards/samr34-xpro/board.c
- boards/samr34-xpro/include/board.h
- boards/samr34-xpro/include/periph_conf.h
There was only SPI config for the internal SPI (wired to sx1276). Also add an external SPI bus wired to the EXT pin headers.
The WLR089 board also comes with a NOR flash soldered on that is connected to this bus, so also configure it.
(It's the same as on `samd21-xpro`, see #17692)
> boards/samr34-xpro: configure SPI NOR flash 

- cpu/esp32/Kconfig
- cpu/esp32/Kconfig.common
- cpu/esp32/Kconfig.esp32c3
- cpu/esp32/Makefile.dep
- cpu/esp32/Makefile.features
- cpu/esp32/Makefile.include
- cpu/esp32/doc.txt
- cpu/esp32/include/sdkconfig.h
- cpu/esp32/include/sdkconfig_esp32c3.h
- cpu/esp32/ld/esp32c3/sections.ld
- cpu/esp8266/vendor/esp-idf/esp8266/source/esp_wifi_os_adapter.c
- cpu/esp_common/include/freertos/portmacro.h
- pkg/esp32_sdk_lib_bt_esp32c3/Kconfig
- pkg/esp32_sdk_lib_bt_esp32c3/Makefile
- pkg/esp32_sdk_lib_bt_esp32c3/Makefile.dep
- pkg/esp32_sdk_lib_bt_esp32c3/Makefile.include
- pkg/esp32_sdk_lib_bt_esp32c3/doc.txt
This PR enables the Bluetooth 5 including advertising extension and NimBLE host support for ESP32-C3.
BLE and NimBLE host support for ESP32-C3 including advertising extension was already tested when BLE and NimBLE host support was tesed for ESP32 in  PR #18439.
The easiest way to test the PR is to use an ESP32 node and an ESP32-C3 node and flash `tests/nimble_autoconn_gnrc` and test it.
```
BOARD=esp32-wroom-32 make -j8 -C examples/nimble_autoconn_gnrc flash term
```
```
BOARD=esp32c3-devkit make -j8 -C examples/nimble_autoconn_gnrc flash term
```
Use command `ble info` to check that a connection between the two nodes is established after some seconds.
Node 1:
```
> ble info
Own Address: 60:55:F9:6E:6E:69 (public) -> [FE80::6055:F9FF:FE6E:6E69]
Supported PHY modes: 1M
Free slots: 1/3 …
```
> cpu/esp32: enable BLE and NimBLE host support for ESP32-C3

- tests/pkg_lvgl_touch/Makefile
- tests/pkg_lvgl_touch/app.config.test
- tests/pkg_lvgl_touch/main.c
The test is a bit boring. To spice it up, randomize the button position to show the user it worked without having to attach a serial console.
> tests/pkg_lvgl_touch: randomize button position on click

- cpu/esp32/Kconfig
- cpu/esp32/Kconfig.esp32s3
- cpu/esp32/Makefile.dep
- cpu/esp32/Makefile.features
- cpu/esp32/Makefile.include
- cpu/esp32/doc.txt
- cpu/esp32/include/esp_ble_nimble/syscfg/syscfg.h
- cpu/esp32/include/sdkconfig_esp32s3.h
- cpu/esp32/ld/esp32s3/sections.ld
- cpu/esp_common/include/freertos/portmacro.h
This PR enables the Bluetooth 5 including advertising extension and NimBLE host support for ESP32-S3.
~The PR includes the changes of PR #18510 for now to be compilable. It has to be rebased once PR #18510 is merged.~
Please note: The binary Bluetooth library that is used as package is the same as for ESP32-C3 and is called [esp32c3-bt-lib](https://github.com/espressif/esp32c3-bt-lib). That's the reason why feature `esp_ble_esp32c3` is enabled for ESP32-S3 BLE implementation.
The easiest way to test the PR is to use an ESP32 node and an ESP32-S3 node and flash `tests/nimble_autoconn_gnrc` and test it.
```
BOARD=esp32-wroom-32 make -j8 -C examples/nimble_autoconn_gnrc flash term
```
```
BOARD=esp32s3-devkit make -j8 -C examples/nimble_autoconn_gnrc flash term
```
Use command `ble info` to …
> cpu/esp32: enable BLE and NimBLE host support for ESP32-S3

- makefiles/tools/dfu-util.inc.mk
Add an option to dfu-util to pass DFU Serial ID.
This is useful when you need to flash a board and you have more than one DFU capable devices connected on your computer. 
Get your DFU Serial ID of your boards using:
`dfu-util -l`
Flash the right board using:
`DEBUG_ADAPTER_ID=XXXXX USEMODULE+=usbus_dfu make -C tests/leds BOARD=samr21-xpro PROGRAMMER=dfu-util riotboot/flash-slot0 `
None
> makefiles/tools/dfu-util: add option to pass DFU_SERIAL id

- examples/filesystem/Makefile
- examples/filesystem/README.md
- examples/filesystem/main.c
File systems should be mounted via `vfs_default`, not manually by the application.
Also, `vfs` gained the `format` sub-command, so no need to provide it in the example application.
Run the example.
> examples/filesystem: drop manual mounts

- dist/tools/usb-serial/ttys.py
- makefiles/tools/serial.inc.mk
- sys/include/usb.h
- sys/usb/Kconfig
This does mainly two things:
- Set the USB model to `$(BOARD)` by default
- Filter USB serials with `--vendor RIOT-os\.org` and `--model $(BOARD)`, so that the right board type is picked automagically with `MOST_RECENT_PORT=1`
Flash two boards of different type that use USB CDC ACM for serial. Test if `MOST_RECENT_PORT=1 BOARD=<foo> make term` picks the right board when both are plugged in, no matter which board was plugged in first.
Suggested in https://github.com/RIOT-OS/RIOT/pull/18512#discussion_r954983129
> makefiles/tools/serial.inc.mk: Improve PORT selection when RIOT's USB CDC ACM is used for stdio

- Makefile.include
- dist/tools/openocd/openocd.sh
- makefiles/info.inc.mk
- makefiles/tools/serial.inc.mk
- makefiles/vars.inc.mk
The RTT mechanism, by which a debugger emulates a serial interface, has been [invented and described by Segger (creator of JLink)](https://wiki.segger.com/RTT), but was so far only available through their own JLink program. As the same interface is also implemented by OpenOCD, it can be used with that and thus any debug adapter (eg. STLink).
* Do we need any parametrization?
* Channel 0 is hard-coded which is probably OK
* No clue where the addresses come from.
* The string "SEGGER JLINK" is the sentinel value also hardcoded in stdio_rtt.c, so that should be OK.
* Do we need better autoselection? (See future steps)
* Pick any board that has an OpenOCD-style debugger and usually runs serial stdio; I picked `microbit-v2`, and an example that has nice shell (eg. `saul`)
* Add lines to the …
> makefiles: Add openocd-rtt

- cpu/nrf52/include/periph_cpu.h
- cpu/nrf52/spi_twi_irq.c
- cpu/nrf5x_common/periph/i2c_nrf52_nrf9160.c
- cpu/nrf5x_common/periph/spi_nrf52_nrf9160.c
- cpu/nrf9160/include/periph_cpu.h
- cpu/nrf9160/spi_twi_irq.c
This allows to use the same hardware peripheral for different I2C / SPI busses when the `nrf5x_periph_shared` module is enabled. 
Since I2C and SPI share the peripheral, this means that now SPI0 can be used event when TWIM0 is used for I2C.
Or multiple I2C busses that use TWIM0 can be defined.
*This is entirely untested* 
Define several I2C or SPI busses that use the same hardware peripheral, but with different pins.
With `nrf5x_periph_shared` enabled, they should all work and re-mux as needed.
> cpu/nrf5x: allow multiple I2C and SPI buses on a shared periph 

- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/sock.c
- tests/nanocoap_cli/nanocli_client.c
Same as `nanocoap_sock_get()`, but for PUT and POST.
Run two instances of `tests/nanocoap_cli`, on one do a `server start` and on the other
```
> url get coap://[fe80::581a:98ff:fe23:2d6c]/value
offset 000: 0
> url put coap://[fe80::581a:98ff:fe23:2d6c]/value 23
> url get coap://[fe80::581a:98ff:fe23:2d6c]/value
offset 000: 23
```
> nanocoap_sock: add nanocoap_sock_put()

- tests/pkg_tinyvcdiff/fakemtd.h
An assert `assert(mtd->write_size != 0);` is being hit with `native`.
```
main(): This is RIOT! (Version: buildtest)
..drivers/mtd/mtd.c:53 => *** RIOT kernel panic:
*** halted.
```
It seems that initializing this to 1 in the fakemtd fixes it.
Not that I know anything about what it should be.  If one looks at some of the other write_sizes it seems that would make sense.
Run the following, it should not longer fail:
```
make all test -C tests/pkg_tinyvcdiff/
```
I think murdock should have caught it... Maybe add CI: run_tests label.
Introduced with the initial test #17797
> tests/pkg_tinyvcdiff: Initialize mtd->write_size

- makefiles/tools/serial.inc.mk
When stdio_rtt is used, the default value of RIOT_TERMINAL (pyterm) with some PORT makes little sense -- the board won't be using that.
Instead, when stdio_rtt is detected, the selected PROGRAMMER is introspected, and the used to pick the corresponding terminal transport.
* Pick any board that is used with a debugger and usually runs serial stdio; I picked `microbit-v2`, and an example that has nice shell (eg. `saul`)
* Add lines to the Makefile:
```
USEMODULE += stdio_rtt
```
* `make -C examples/saul BOARD=microbit-v2 all flash term`
(Note that this is identical to that of #18526 except that no RIOT_TERMINAL is set).
I've tried this with PROGRAMMER values of openocd and pyocd (for which RTT is not implemented, falling back to the pyterm default but issuing a warning); I'd appreciate if …
> makefiles: Select suitable terminal when stdio_rtt is used

- cpu/sam0_common/periph/timer.c
This PR fixes an issue in `timer_init()` 
Ensure all clocks needed by the periph are set before accessing any registers as we might get stuck in some conditions.
Test all timers related tests.
See #18520 for details
> cpu/sam0/timer: supply all clocks before accessing any regs

- makefiles/arch/avr8.inc.mk
As the title says. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105523 for details.
```
$ make BOARD=arduino-uno -C examples/hello-world
make: Entering directory '/home/maribu/Repos/software/RIOT/examples/hello-world'
Building application "hello-world" for "arduino-uno" with MCU "atmega328p".
"make" -C /home/maribu/Repos/software/RIOT/boards/arduino-uno
"make" -C /home/maribu/Repos/software/RIOT/boards/common/arduino-atmega
"make" -C /home/maribu/Repos/software/RIOT/boards/common/atmega
"make" -C /home/maribu/Repos/software/RIOT/boards/common/init
"make" -C /home/maribu/Repos/software/RIOT/core
"make" -C /home/maribu/Repos/software/RIOT/core/lib
"make" -C /home/maribu/Repos/software/RIOT/cpu/atmega328p
"make" -C /home/maribu/Repos/software/RIOT/cpu/atmega_common
In file included from …
```
> makefiles/arch/avr8.inc.mk: Fix compilation with GCC 12.2.0

- bootloaders/riotboot_dfu/main.c
When updating an application to the second `riotboot` slot, `ztimer_init()` is called too late leading to issue with `dfu-util` at the end of the flash process such as:
`dfu-util: unable to read DFU status after completion (LIBUSB_ERROR_PIPE)`
This PR fixes this issue by initializing ztimer prior to setup DFU.
Note: I'm considering dropping ztimer utilisation in the future for USB DFU. But let's fix this issue properly for now.
Flash bootloader/riotboot_dfu on your board:
`make BOARD=samr21-xpro -C bootloaders/riotboot_dfu flash`
Flash any application (several times on both slots !)
`USEMODULE+=usbus_dfu make -C tests/leds BOARD=samr21-xpro PROGRAMMER=dfu-util riotboot/flash-slot0`
Fixes #18456
Replaces #18520
> bootloader/riotboot_dfu: move ztimer_init() prior to usbus start

- sys/net/application_layer/gcoap/fileserver.c
- sys/vfs_util/vfs_util.c
Two stupid bugs have sneaked in from #18133. They are fixed here.
Obvious.
> gcoap_fileserver: bugfix recursive delete

- examples/.gitignore
- tests/.gitignore
As the title says. It also adds a `.gitignore` in `tests/` and `examples/` that matches files named `core` in a direct subfolder of `tests/` and `examples/`
```
$ touch core/foo # should *NOT* be ignored
$ touch core/core # should *NOT* be ignored
$ touch drivers/core # should *NOT* be ignored
$ touch examples/hello-world/core # should be ignored
$ touch tests/unittests/core # should be ignored
$ git add .
$ git status
On branch core_dumps
Your branch is up to date with 'origin/core_dumps'.
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
new file:   core/core
new file:   core/foo
new file:   drivers/core
```
https://github.com/RIOT-OS/RIOT/pull/16787#issuecomment-1232793630
> tests/periph_gpio_ll: drop core dump merged by accident

- sys/include/fmt.h
The current wording of the `fmt` module may be a bit confusing (see https://github.com/RIOT-OS/RIOT/pull/18310). This PR aims to fix that.
Read.
Alternative to https://github.com/RIOT-OS/RIOT/pull/18310
> fmt: unify and align wording regarding characters, digits, and bytes

- .murdock
Currently, if CI runs `./.murdock`, it blindly sets`RUN_TESTS=1` if `CI: run tests` is set, even if it was already set to `0`. This makes it impossible to disable tests altogether, e.g., for https://ci-staging.riot-os.org`.
This PR provides a change in the logic that keeps a previously set RUN_TESTS.
> murdock: honour RUN_TESTS setting

- pkg/lvgl/contrib/lvgl.c
When running a RIOT native app using SDL, the display window for SDL is adjustable, but the display driver used by LVGL is not - it always defaults to the 320x240 size provided in the lv_disp_drv_init.
When driving an LCD, the resolution for the disp driver is updated post-init of the driver. Following the similar conventions, this tidbit references LCD_SCREEN_HEIGHT/WIDTH defines, which can be passed to an app as a CFLAG in a Makefile.include, or defaulting to the SDL_HOR/VER_RES defines passed in through lv_drv_conf.h in lv_drivers package.
This enables SDL native applications to better emulate the exact resolution of an LCD screen.
Using a test package for a custom LVGL RIOT application, I verified that SDL_HOR/VER_RES can adjust the SDL window, but not the display driver used by LVGL …
> lvgl/contrib: allow for SDL display driver height/width to be adjusted

- examples/suit_update/main.c
- sys/include/suit/transport/coap.h
- sys/include/suit/transport/worker.h
- sys/shell/commands/sc_suit.c
- sys/suit/transport/coap.c
- sys/suit/transport/worker.c
The SUIT worker thread functions do not deal with CoAP but only signal the worker thread. The worker thread can also use the VFS backed (and no CoAP backend at all), so the name is misleading.
`static inline` aliases have been provided for compatibility. 
CI should verify everything still compiles.
> suit: rename worker thread functions

- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/sock.c
It should return `-ENOBUFS` like the other `nanocoap_…()` functions, not `-1`.
> nanocoap_sock: use correct error code in nanocoap_get_blockwise_url_to_buf()

- sys/newlib_syscalls_default/syscalls.c
That comment seems to be really outdated. `ptrdiff_t` can be negative and `tests/malloc` explicitly tests for `free()`.
Run `tests/malloc`, see that memory was freed.
> sys/syscalls: drop outdated comment on _sbrk_r()

- sys/shell/commands/sc_suit.c
This adds the `suit revert` sub-command to roll-back to the previous image.
This can be useful for testing firmware updates or to revert in case of a bug.
Can be tested with `examples/suit_update`:
```
2022-09-05 09:46:52,965 - INFO # > suit revert
2022-09-05 09:46:52,965 - INFO # 
2022-09-05 09:46:52,969 - INFO # reverted to previous version, rebooting…
2022-09-05 09:46:53,011 - INFO # main(): This is RIOT! (Version: 2022.10-devel-577-gc9b69-suit_enhance)
2022-09-05 09:46:53,015 - INFO # RIOT SUIT update example application
2022-09-05 09:46:53,016 - INFO # Running from slot 0
2022-09-05 09:46:53,019 - INFO # Image magic_number: 0x544f4952
2022-09-05 09:46:53,022 - INFO # Image Version: 0x00000001
2022-09-05 09:46:53,024 - INFO # Image start address: 0x00001100
2022-09-05 09:46:53,027 - …
```
> sys/shell/commands: add suit revert sub-command

- sys/shell/commands/sc_vfs.c
Currently `vfs df` outputs size as filesystem blocks. It is not clear how big a filesystem block is, so the output is hard to interpret.
Instead, output the sizes in Bytes like `df -h`. 
Run e.g. `examples/filesystem`:
```
2022-09-04 12:46:51,962 # > vfs df
2022-09-04 12:46:51,967 # Mountpoint              Total         Used    Available     Capacity
2022-09-04 12:46:51,973 # /sd0                   15223M      129912k    15458440k       0%
2022-09-04 12:46:52,006 # /nvm0                     32M         220k       32548k       0%
2022-09-04 12:46:52,011 # /const                     27           27            0     100%
```
> sys/shell/vfs: make output of vfs df human readable

- core/sched.c
An `1 << x` with `x >= 15` is undefined behavior on 8-bit / 16-bit machines (which typically have `sizeof(int) == 2`).
Using `1UL << x` is safe for `x <= 31`, which is large enough to make use of the full 32 bits in `runqueue_bitcache`.
In addition, a `static_assert()` is added to enforce that `SCHED_PRIO_LEVELS` is never set to anything larger than 32.
Code review should be sufficient IMO.
None
> core/sched.c: fix undefined behavior on 8-bit/16-bit

- drivers/include/sdcard_spi.h
- drivers/sdcard_spi/sdcard_spi.c
- tests/vfs_default/Makefile
- replace all `int`s and `unsigned`s with integers with fixed width
- replaced all signed integers of sizes with unsigned ones (sizes cannot be negative)
- made bitshifts 8-bit safe (e.g. `1 << 24` is valid on 32-bit, but undefined behavior on 8-bit, as a 16 bit wide `int` would be shifted by more than the type width)
- use `void *` / `const void *` for data buffers to ease use
```
$ make BOARD=<RANDOM_BEEFY_AVR_BOARD_WITH_SD_CARD> -C examples/vfs_default
> vfs ls /sd0
```
```
2022-09-09 17:08:51,026 # main(): This is RIOT! (Version: 2022.10-devel-591-g494f5d-drivers/sdcard_spi)
2022-09-09 17:08:51,040 # mount points:
2022-09-09 17:08:51,046 # 	/sd0
2022-09-09 17:08:51,047 # 
2022-09-09 17:08:51,063 # data dir: /sd0
> vfs ls /sd0
2022-09-09 17:08:56,155 # vfs ls /sd0
2022-09-09 …
```
> drivers/sdcard_spi: make 8-bit safe

- SECURITY.md
CVEs reported about RIOT have been assigned to the CPE `cpe:2.3:o:riot-os:riot:2021.01` and similar. Adding this to the SECURITY file makes it more accessible both to users (who can add it to their filter for advisories of which they will be notified) and to reporters.
I was approached about whether RIOT has a CPE number and a CSAF file by a visitor from DGUV during FrOSCon. Given that I've gone through the process of reporting a RIOT security vulnerability, I should really have known that we already have a CPE identifier that is used -- I didn't because the security documentation did not tell me.
> security: Reference CPE used for RIOT

- doc/doxygen/src/flashing.md
- The tool compatibility matrix got super large - split out all "single-purpose" tools and list them per platform
- Highlighting code via backticks in titles doesn't render well with Doxygen
Check the generated documentation
https://github.com/RIOT-OS/RIOT/pull/18562#discussion_r967299742
> doc: improve flashing documentation

- dist/tools/bossa-1.8/patches/0002-src-PosixSerialPort.cpp-Add-missing-include.patch
- dist/tools/bossa-1.9/patches/0001-src-PosixSerialPort.cpp-add-missing-include.patch
- dist/tools/bossa-nrf52/patches/0001-src-PosixSerialPort.cpp-Add-missing-include.patch
As the title says. This fixes compilation on systems with a sane C lib, such as:
```
[INFO] bossac 1.9 binary not found - building it from source
[INFO] compiling bossac from source now
make[2]: wx-config: No such file or directory
make[2]: wx-config: No such file or directory
CPP APPLET src/WordCopyArm.cpp
CPP COMMON src/Samba.cpp
CPP COMMON src/Flash.cpp
CPP COMMON src/D5xNvmFlash.cpp
CPP COMMON src/D2xNvmFlash.cpp
CPP COMMON src/EfcFlash.cpp
CPP COMMON src/EefcFlash.cpp
CPP COMMON src/Applet.cpp
CPP COMMON src/WordCopyApplet.cpp
CPP COMMON src/Flasher.cpp
CPP COMMON src/Device.cpp
CPP COMMON src/PosixSerialPort.cpp
src/PosixSerialPort.cpp: In member function 'virtual int PosixSerialPort::read(uint8_t*, int)':
src/PosixSerialPort.cpp:216:5: error: 'fd_set' was not declared in this scope …
```
> dist/tools/bossa*: add missing include

- boards/common/stm32/include/stm32_leds.h
The inverted and non-inverted `LED<num>_ON` and `LED<num>_OFF` macros are swapped. This didn't reveal in testing as the `LED<num>_IS_INVERTED` macros where not properly evaluated, due to a typo in the check. This fixes both.
I noticed the issues when flashing `examples/saul` on a Nucleo-F767ZI and all LEDs went up like on a xmas tree
Regression introduced by https://github.com/RIOT-OS/RIOT/pull/18415
> boards/common/stm32: Fix LED configuration

- core/mutex.c
This fixes https://github.com/RIOT-OS/RIOT/issues/18545 as the code previously relied on `sched_change_priority()` not directly scheduling a new thread while IRQs are disabled, but rather later when IRQs are restored. This is true for Cortex-M MCUs (where the PendSV IRQ is used to trigger the scheduler), but not e.g. for AVR.
`tests/thread_priority_inversion` should now pass on AVR and still pass on Cortex-M
Fixes https://github.com/RIOT-OS/RIOT/issues/18545
> core/mutex: fix priority inheritance on AVR

- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/sock.c
The `remote` argument is passed to a function that accepts a `const` pointer.
Since we might want to store `remote` in flash or use the one returned by `coap_request_ctx_get_remote_udp()`, also make the `remote` argument `const` in nanoCoAP sock.
Green CI
> nanocoap_sock: consitfy remote

- cpu/esp32/esp-eth/esp_eth_netdev.c
- pkg/lwip/contrib/netdev/lwip_netdev.c
lwIP did not set the netdev callback early enough, so events triggered during or right after initialization were lost.
After the IDF upgrade my board could not receive packets via Ethernet anymore since the cable connect event id was still stored as the pending event. This had not been processed by the ISR due to the missing callback, and the stored event id stopped other events from triggering.
This explains why the connect/rx event clash seen in "esp32/eth: Don't overwrite queued event with RX packet" (https://github.com/RIOT-OS/RIOT/commit/95196fb7e40b12c7824e9827aadcc2ace35016a5) only happened with lwIP. The fix for that is no longer needed and therefore reverted.
`tests/lwip` still works and interfaces can get IPv4 or IPv6 address dynamically (meaning RX & TX works).
Broken for me …
> pkg/lwip: Set netdev callback before driver init 

- doc/doxygen/src/flashing.md
- makefiles/boards/stm32.inc.mk
Allow issuing a reset to bootloader sequence by abusing the RTS and the DTR pins of a TTL adapter. This makes flashing via UART much more convenient, as no jumpers need to be placed to select booting to the bootloader / flash and no reset buttons need to be pressed.
~~It is btw. about time we create a documentation page on programmers. I hope to open a PR adding this today. If this PR is not merged by then, I will rebase this on top and document the new feature in the newly added `stm32flash` programmer documentation page.~~
Update: Documentation added in this PR :smile:
I tested this with a Blackpill (but a Bluepill or any other STM32 board should also work), but this also needs https://github.com/RIOT-OS/RIOT/pull/18450 to map stdio to UASRT1 for Bluepill/Blackpill boards.
- wire …
> makefiles/boards/stm32.inc.mk: improve stm32flash support

- cpu/native/socket_zep/socket_zep.c
So far, ZEP would accept all frames even if they are sent on the wrong 'channel'.
Apply phy configuration and filter incoming frames based on the radio channel.
Run `examples/gnrc_border_router` and `examples/gnrc_networking` with `USE_ZEP=1`
```
main(): This is RIOT! (Version: 2022.10-devel-608-g36eac)
RIOT network stack example application
> ping ff02::1
12 bytes from fe80::ac5a:b682:da1f:f3c1%7: icmp_seq=0 ttl=64 rssi=0 dBm time=0.544 ms
12 bytes from fe80::ac5a:b682:da1f:f3c1%7: icmp_seq=1 ttl=64 rssi=0 dBm time=0.556 ms
12 bytes from fe80::ac5a:b682:da1f:f3c1%7: icmp_seq=2 ttl=64 rssi=0 dBm time=0.565 ms
--- ff02::1 PING statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.544/0.555/0.565 ms
> ifconfig …
```
> socket_zep: ignore packets sent on the wrong radio channel

- sys/include/net/sock/tcp.h
The include "sock_types.h" should be outside of the linkage-specification.
```C++
extern "C"
{
// #include "sock_types.h"
}
#include "sock_types.h" // outside
```
The header "sock_types.h" has his own linkage-specification.
Otherwise this leads to problems in IntelliSense in VS Code.
> sys/net: include misplacement inside linkage-specification

- core/lib/assert.c
- cpu/avr8_common/include/architecture_arch.h
- cpu/avr8_common/include/cpu.h
- cpu/cortexm_common/include/cpu.h
- cpu/esp_common/include/cpu.h
- cpu/lpc23xx/include/cpu.h
- cpu/mips32r2_common/include/cpu.h
- cpu/msp430_common/include/cpu.h
- cpu/native/include/cpu.h
- cpu/riscv_common/include/cpu.h
- sys/include/architecture.h
Returning the last instruction is more flexible than just always printing it.
This allows users to store the last instruction for some trace debug functionality. 
A failing assertion should still print the correct location, e.g. on Cortex-M:
```patch
--- a/examples/hello-world/main.c
+++ b/examples/hello-world/main.c
@@ -20,11 +20,14 @@
*/
+#include <assert.h>
int main(void)
{
puts("Hello World!");
+    assert(0);
+
printf("You are running RIOT on a(n) %s board.\n", RIOT_BOARD);
printf("This board features a(n) %s MCU.\n", RIOT_MCU);
``` 
```
2022-06-17 17:10:20,615 - INFO # main(): This is RIOT! (Version: 2022.07-devel-795-g24f7c)
2022-06-17 17:10:20,616 - INFO # Hello World!
2022-06-17 17:10:20,616 - INFO # 0xc1
2022-06-17 17:10:20,619 - INFO # *** RIOT kernel panic: …
```
> cpu: cpu_print_last_instruction() -> cpu_get_caller_pc()

- sys/ztimer/init.c
adds LPTIMER to ztimer auto init
```
CONFIG_ZTIMER_LPTIMER_DEV
CONFIG_ZTIMER_LPTIMER_FREQ
CONFIG_ZTIMER_LPTIMER_WIDTH
CONFIG_ZTIMER_LPTIMER_BLOCK_PM_MODE
```
have to be defined 
and 
`ztimer_periph_lptimer `
be used
msec and sec prefer lptimer over rtt
I the details a diff can be found adding a second timer for stm32 (may not work on all devices) and using that in the `ztimer_xsec` example since this PR is about adding the lowpower-timer (`lptimer`) support to `ztimer` this was removed from it.
<details>
```
diff --git a/boards/common/stm32/include/cfg_timer_tim2.h b/boards/common/stm32/include/cfg_timer_tim2.h
index d7f6008c6f..c9c7126b30 100644
--- a/boards/common/stm32/include/cfg_timer_tim2.h
+++ b/boards/common/stm32/include/cfg_timer_tim2.h
@@ -47,10 +47,18 @@ static const …
```
> sys/ztimer: add LPTIMER auto init

- dist/tools/doccheck/exclude_patterns
with #18444 being merged I did another check for patterns that aren't just undocumented marcos.
I found some non needed patterns this removes them
i expect the static tests to do all the work
#18444
> doccheck: remove exclude_patterns not needed

- dist/tools/doccheck/exclude_patterns
- dist/tools/doccheck/generic_exclude_patterns
- drivers/include/sht1x.h
- drivers/sht1x/include/sht1x_params.h
- replace auto-generated patterns with generic ones
- fix `warning: return value '\-EBADMSG' of sht1x_read has multiple documentation sections`
The CI will do
https://github.com/RIOT-OS/RIOT/pull/18597#issuecomment-1248232952
> drivers/sht1x: fix doccheck

- core/include/mutex.h
Was reading the sacred texts and spotted this one.
> core/mutex: fix typo in docs

- core/msg.c
The irqs are not restored properly in function `msg_queue_print()`
> core/msg.c: irq was not restored properly 

- cpu/esp_common/esp-now/esp_now_netdev.c
- cpu/native/netdev_tap/netdev_tap.c
- cpu/nrf5x_common/radio/nrfble/nrfble.c
- cpu/nrf5x_common/radio/nrfmin/nrfmin.c
- cpu/sam0_common/sam0_eth/eth-netdev.c
- cpu/stm32/periph/eth.c
- drivers/at86rf215/at86rf215_netdev.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
- drivers/cc110x/cc110x_netdev.c
- drivers/cc2420/cc2420_netdev.c
- drivers/dose/dose.c
- drivers/ethos/ethos.c
- drivers/kw41zrf/kw41zrf_netdev.c
- drivers/mrf24j40/mrf24j40_netdev.c
- drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c
- drivers/nrf24l01p_ng/nrf24l01p_ng_netdev.c
- drivers/slipdev/slipdev.c
- drivers/sx126x/sx126x_netdev.c
- drivers/sx127x/sx127x_netdev.c
- drivers/sx1280/sx1280_netdev.c
- drivers/w5100/w5100.c
- drivers/xbee/xbee.c
- sys/include/net/gnrc/ipv6/nib.h
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.h
- sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
- sys/usb/usbus/cdc/ecm/cdc_ecm_netdev.c
If an interface goes offline we can to stop sending router solicitations on it.
But more importantly, if the interface gets online again, we need to send out a router solicitation immediately to get a fresh address.
This was tested with a `atwinc15x0` WiFi module. When it connects to a WiFi network it generates a `NETDEV_EVENT_LINK_UP` event, when the WiFi is no longer connected a `NETDEV_EVENT_LINK_DOWN` event is generated.
I used two custom functions to manage the netif state, but `ifconfig` should work too:
```C
static void _netup(gnrc_netif_t *netif)
{
netopt_state_t state = NETOPT_STATE_IDLE;
while (gnrc_netapi_set(netif->pid, NETOPT_STATE, 0, &state, sizeof(state)) == -EBUSY) {}
}
```
```C
static void _drop_global_addr(gnrc_netif_t *netif)
{
ipv6_addr_t …
```
> gnrc_netif: handle NETDEV_EVENT_LINK_UP/DOWN events

- sys/include/net/gnrc/netif.h
- sys/include/net/gnrc/netif/flags.h
- sys/net/gnrc/netif/ethernet/gnrc_netif_ethernet.c
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/netif/gnrc_netif_raw.c
- sys/net/gnrc/netif/ieee802154/gnrc_netif_ieee802154.c
- Introduce modules `netdev_legacy_api` and `netdev_new_api` to allow optimizing for the "with `confirm_send()`" and "without `confirm_send()`" variant of the netdev API
- Each netdev driver has to depend on exactly one of those
- If both are used (because two or more netdevs are in use and one is migrated and the other not), the API version is checked at runtime
- With `netdev_new_api` translate `NETDEV_EVENT_TX_COMPLETE` into an `sys/event` event, so that this can be signaled from ISR. This safes a roundtrip to the ISR handler if the type of the event is known at ISR time (e.g. multiple signal pins or peripheral netdev)
- If the new API is used, wait for the `NETDEV_EVENT_TX_COMPLETE` event before signalling upper layers completion with `gnrc_tx_sync`.
This needs to be tested in …
> sys/net/gnrc_netif: Make use of confirm send

- cpu/stm32/Makefile.dep
- cpu/stm32/periph/eth.c
- cpu/stm32/periph/eth_common.c
- makefiles/pseudomodules.inc.mk
This PR improves debugging of the peripheral STM32 Ethernet driver. It was used to debug the issue fixed in https://github.com/RIOT-OS/RIOT/pull/18416
It does two things:
- sprinkle a bit more and more verbose `DEBUG()` output over the code
- introduce the module `stm32_eth_tracing` that allows tracing and debugging the STM32 state
- it uses GPIO LL for low overhead to be useful when `DEBUG()` impacts performance to much
- one GPIO is toggled for each ISR entry
- one GPIO is set on TX start and cleared on TX done
- one GPIO is set on RX completed and cleared when the frame is passed up the network stack
- by default, LEDs are used to allow seeing where the state machine is stuck without a scope or logic analyzer
On an STM32 board with Ethernet and at least three LEDs, e.g. the …
> cpu/stm32/periph_eth: Add stm32_eth_tracing

- dist/tools/doccheck/check.sh
- sys/include/ztimer/xtimer_compat.h
- sys/include/ztimer64/xtimer_compat.h
doccheck checks the `@defgroup` and  `@ingroup` commands for doxygen sadly it uses a wrong list of files
this brings them more in sync 
the file pattern used by doxygen can be found here: https://github.com/RIOT-OS/RIOT/blob/2dd185448f1b65fc97df885f9933f70b96377ecc/doc/doxygen/riot.doxyfile#L801-L804
run doccheck
> doccheck: make the file pattern more match riot.doxyfile

- pkg/wakaama/contrib/lwm2m_client_connection.c
- sys/include/uri_parser.h
- sys/net/application_layer/gcoap/dns.c
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/uri_parser/uri_parser.c
- tests/unittests/tests-uri_parser/tests-uri_parser.c
Hi! 👋
This PR aims to add a `uint16_t port` to the `struct uri_parser_result_t` of the URI parser module.
The already existing `const char *port` is renamed to `const char *port_str`. I'm open for other naming suggestions.
I touched:
* `sys/include/uri_parser.h`: Adding said member `port`
* `sys/uri_parser/uri_parser.c`: Making use of the new member & filling it with data
* `sys/net/application_layer/gcoap/forward_proxy.c`: This file used the old string-based port and got updated accordingly, fixing a potential integer overflow
* `pkg/wakaama/contrib/lwm2m_client_connection.c`: This file used the old string-based port and got updated accordingly, fixing a potential integer overflow
* `tests/unittests/tests-uri_parser/tests-uri_parser.c`: Adjusted the test accordingly
I was working on PR …
> sys/uri_parser: Adding the port as uint16_t

- sys/net/application_layer/gcoap/dns.c
This implements the TTL calculation algorithm that is described in [Section 4.3.2](https://www.ietf.org/archive/id/draft-lenders-dns-over-coap-04.html#name-support-of-coap-caching-2) of the current draft.
`tests/gcoap_dns` should still compile. DNS caching itself is currently not implemented in tests, but the code should speak for itself.
None
> gcoap_dns: implement Max-Age-based TTL calculation

- sys/Makefile.dep
- sys/include/event/periodic_callback.h
- tests/event_periodic_callback/Makefile
- tests/event_periodic_callback/Makefile.ci
- tests/event_periodic_callback/main.c
- tests/event_periodic_callback/tests/01-run.py
We have `event_periodic` to periodically trigger an event (callback in interrupt context) and we have `event_callback` to execute an event callback by the event thread.
Putting both together always requires some boilerplate and is not easy to discover - let's add a `event_periodic_callback` convenience module that ties it all together nicely.
A new test case is provided with `tests/event_periodic_callback`.
Event callbacks are executed in thread context.
> event_periodic_callback: add convenience wrapper for periodic callbacks

- sys/Makefile.dep
- sys/include/event/periodic_callback.h
- tests/event_periodic_callback/Makefile
- tests/event_periodic_callback/main.c
Removes an unnecessary dependency I saw during the review #18598. Since I did not deactivate @maribu's auto-merge and did make a change request, it slipped into master.
`tests/event_periodic_callback/` should still run and work.
Follow-up on #18598
> event_periodic_callback: remove unnecessary dependency

- doc/doxygen/src/getting-started.md
Several packages (openthread, utensor, and openDSME coming in #18156) nowadays use C++, so it makes sense to add the C++ standard libraries to the set we recommend that be installed on a Debian-style system.
* Look at the documentation change; verify that the package exists on Ubuntu by entering it into the [Ubuntu package search](https://packages.ubuntu.com/search?keywords=libstdc%2B%2B-arm-none-eabi-newlib&searchon=names&suite=all&section=all)
* If you're feeling diligent, try building any C++ using application with the default set of packages, see that it can't find `#include <cmath>`, and then see the error go away once you install that package.
(And maybe put yourself into the shoes of a newcomer who's trying to find out where to find this particular file)
> doc/getting-started: Add C++ standard library to the list

- boards/common/saml1x/include/board.h
- boards/hamilton/include/board.h
- boards/pba-d-01-kw2x/include/board.h
- boards/samd10-xmini/include/board.h
- boards/samd20-xpro/include/board.h
- boards/samd21-xpro/include/board.h
- boards/same54-xpro/include/board.h
- boards/saml21-xpro/include/board.h
- boards/samr21-xpro/include/board.h
- boards/samr30-xpro/include/board.h
- boards/samr34-xpro/include/board.h
- boards/sensebox_samd21/include/board.h
- boards/stm32l0538-disco/include/board.h
This define isn't used anywhere in RIOT and only some boards have it, so drop it.
CI will tell that this was indeed unused.
> boards: drop unused BTN0_PORT define

- drivers/dfplayer/Kconfig
- pkg/lwip/include/lwipopts.h
- pkg/nimble/contrib/nimble_riot.c
As a leftovers from https://github.com/RIOT-OS/RIOT/pull/18355 are still present that check for `MODULE_SHELL_COMMANDS` rather than `MODULE_SHELL_CMDS`. This updates the conditionals as needed.
- The `ifconfig` shell command in `tests/lwip` should show an IPv6 address again. (I can confirm that is does so.)
- Some regression in `tests/nimble_netif_ext` should be fixed. (I can confirm that the text size grows with this, but I wasn't able to detect an obvious issue with the `ifconfig` cmd there.)
Regression introduced in https://github.com/RIOT-OS/RIOT/pull/18355
> treewide: fix conditionals on deprecated module

- sys/fido2/ctap/ctap.c
- sys/include/string_utils.h
- sys/net/credman/credman.c
This header-only module provides a `string_utils.h` that currently only provides the non-standard function `explicit_bzero()` to securely wipe memory. It may be extended with other utility functions in the future.
Using this, the insecure memory wiping in `sys/fido2` and `sys/net/credman` is fixed.
Code review should be sufficient here, as the change is rather trivial.
https://godbolt.org/z/rzxbrhxTn shows an example where `memset()` is optimized out, but `explicit_bzero()` is (under the same circumstances) not.
Fixes https://github.com/RIOT-OS/RIOT/issues/10751
> sys/string_utils : new (header-only) module for string utilities

- core/lib/include/panic.h
- core/sched.c
Presently, RIOT just emits a warning when a stack overflow is encountered but still resumes execution. In my view, execution should be aborted as the detection of a stack overflows via the heuristic provided by the scheduler is an unrecoverable error.
I ran into this while performing automated tests of a RIOT application where a stack overflow occurred but I only noticed this after inspecting the application output more closely.
Similar to SSP failures, I added crash_code for stack overflows and also bumped the log level from warning to error.
I don't think there is a test case for the `SCHED_TEST_STACK` heuristic but basically the testing procedure would boil down to ensuring that execution does not continue after a stack overflow is detected by the scheduler.
None.
> core: Treat stack overflows as an unrecoverable error

- boards/remote-reva/doc.txt
- boards/remote-revb/doc.txt
Fixes pinout image in the documentation page of the remotre-revb board.
In https://doc.riot-os.org/group__boards__remote-revb.html#autotoc_md932 the image is wrong, it's from rev. A and should be rev. B
Fixes #18612
> boards/remote-revb: fix pinout image in doc.txt

- core/include/macros/math.h
- tests/unittests/tests-core/tests-core-macros.c
- tests/unittests/tests-core/tests-core.c
- tests/unittests/tests-core/tests-core.h
This adds a few commonly useful math helper macros to `core/macros`:
- `SIGNOF()` returns the sign of an integer
- `DIV_ROUND()` performs arithmetic integer division
- `DIV_ROUND_UP()` performs arithmetic integer division, always rounding to the next integer larger in magnitude. 
`unittests/tests-core` was extended with test cases for the new macros
> core/macros: add math helper macros

- boards/atxmega-a1u-xpro/include/periph_conf.h
- cpu/atxmega/include/periph_cpu.h
Due to the lack of new official avr-libc releases (which includes the vendor header files needed to support different version of MCUs), support for new MCUs was lacking. Distributions such as Debian addressed this by extending the upstream code with vendor header files directly obtained from Atmel / Microchip, but without paying attention to details. As such, a naming inconsistency (ASIZE vs ASPACE) between officially supported MCUs and new MCUs was introduced.
Now that avr-libc 2.1.0 is officially released, hardware support for new MCUs is provided by upstream out of the box and only ASIZE is used as name. This commit adds a bit of glue code to create aliases for ASIZE on older avr-libc versions where needed. This fixes compilation with the new avr-libc release and results in more …
> cpu/atxmega: fix building with avr-libc 2.1.0

- sys/net/application_layer/dhcpv6/client.c
As far as I can tell, no DHCPv6 RFC specifies this option.
The handling for the zero option was added in #17736 by @benpicco to fix issues encountered while trying to retrieve a DHCHPv6 lease. However, I strongly suspect that the zero option was encountered in this case due to an out-of-bounds read performed in RIOT's DHCPv6 client implementation (i.e. the option parsing loop read beyond the packet bounds). This issue was fixed in #18307 and I strongly suspect that it should also fix the issue @benpicco originally encountered in #17736. As such, I propose that we remove the if statement which treats the zero option as an end-of-payload marker.
@benpicco could you test this with the DHCPv6 server implementation with which you originally encountered the error described in #17736 and report …
> dhcpv6: don't treat zero option as an end-of-payload marker

- cpu/avr8_common/avr_libc_extra/include/strings.h
This adds `strings.h` missing in AVR libc and implements the most commonly used functions in it (which are all trivial).
The functions are trivial enough that code review should be sufficient. But I could add a test application, if reviewers would prefer.
Noticed due to Murdock failures in https://github.com/RIOT-OS/RIOT/pull/18621
> cpu/avr8_common: add strings.h for compatibility

- makefiles/tools/avrdude.inc.mk
If `AVRDUDE_PROGRAMMER` is already set to a programmer that is also capable of debugging, we can assume that typically the user will want to use the same hardware for debugging. Thus, let `AVR_DEBUGDEVICE` default to the matching hardware.
`$ make BOARD=microduino-corerf AVRDUDE_PROGRAMMER=dragon_jtag -C examples/hello-world debug` should call AVaRICE with `--dragon` to select the AVR Dragon:
```
make: Entering directory '/home/maribu/Repos/software/RIOT/examples/hello-world'
"/home/maribu/Repos/software/RIOT/dist/tools/avarice/debug.sh" "--dragon -j usb :4242" /home/maribu/Repos/software/RIOT/dist/tools/avarice 4242 "-x /home/maribu/Repos/software/RIOT/dist/tools/avarice/gdb.conf /home/maribu/Repos/software/RIOT/examples/hello-world/bin/microduino-corerf/hello-world.elf"
```
But `$ make …
> tools/avarice: deduce debugger from AVRDUDE_PROGRAMMER

- tests/heap_cmd/tests/01-run.py
In c95e8553ef4761f145b51ebc9997bcfa8def48b4 the shell output of the heap command was changed and no longer matched the expectation of the test script. This adapts the test to again match the output.
```
$ make BOARD=nucleo-f767zi -C tests/heap_cmd flash test
make: Entering directory '/home/maribu/Repos/software/RIOT/tests/heap_cmd'
Building application "tests_heap_cmd" for "nucleo-f767zi" with MCU "stm32".
[...]
text	  data	   bss	   dec	   hex	filename
16016	   132	  2424	 18572	  488c	/home/maribu/Repos/software/RIOT/tests/heap_cmd/bin/nucleo-f767zi/tests_heap_cmd.elf
/home/maribu/Repos/software/RIOT/dist/tools/openocd/openocd.sh flash /home/maribu/Repos/software/RIOT/tests/heap_cmd/bin/nucleo-f767zi/tests_heap_cmd.elf
[...]
> heap
> heap
heap: …
```
> tests/heap_cmd: fix test script

- makefiles/tools/openocd-adapters/ftdi.inc.mk
This adds a generic `ftdi` OpenOCD debug adapter.
There are [many](https://github.com/openocd-org/openocd/tree/master/tcl/interface/ftdi) programmers based on the FTDI interface and they all work the same, with varying pin configurations. Instead of wrapping them all individually, a generic `ftdi.inc.mk` is provided, the exact board type can then be specified by setting `OPENOCD_FTDI_ADAPTER`.
This defaults to [`tigard`](https://github.com/tigard-tools/tigard) for personal convenience.  
Flash any board with 
PROGRAMMER=openocd OPENOCD_DEBUG_ADAPTER=ftdi
In case you are on an older version of OpenOCD than 0.12, you have to provide the `tigard.cfg`
```
adapter driver ftdi
ftdi_vid_pid 0x0403 0x6010
ftdi_channel 1
adapter speed 2000
ftdi_layout_init 0x0028 0x002b
ftdi_layout_signal SWD_EN …
```
> tools/openocd: add generic FTDI adapter

- cpu/arm7_common/Makefile.include
This fixes:
Assembler messages:
Fatal error: unknown option `-ggdb'
Run with a recent toolchain:
```
$ make BOARD=msba2 -C examples/hello-world/
```
```
$ make BOARD=msba2 -C examples/hello-world/
make: Entering directory '/home/maribu/Repos/software/RIOT/examples/hello-world'
Building application "hello-world" for "msba2" with MCU "lpc23xx".
"make" -C /home/maribu/Repos/software/RIOT/boards/common/init
"make" -C /home/maribu/Repos/software/RIOT/boards/msba2
"make" -C /home/maribu/Repos/software/RIOT/core
"make" -C /home/maribu/Repos/software/RIOT/core/lib
"make" -C /home/maribu/Repos/software/RIOT/cpu/lpc23xx
Assembler messages:
Fatal error: unknown option `-ggdb'
make[2]: *** [/home/maribu/Repos/software/RIOT/Makefile.base:176: …
```
> cpu/arm7_common: fix compilation with 12.2.0

- tests/gnrc_ipv6_fwd_w_sub/mockup_netif.c
- tests/gnrc_ipv6_nib/mockup_netif.c
- tests/gnrc_ipv6_nib_6ln/mockup_netif.c
- tests/gnrc_sixlowpan_frag_minfwd/main.c
- tests/gnrc_sixlowpan_frag_minfwd/mockup_netif.c
- tests/gnrc_sixlowpan_frag_sfr/main.c
- tests/gnrc_sixlowpan_frag_sfr/mockup_netif.c
We now have to call `gnrc_ipv6_nib_iface_up()` to configure addresses / start ARSM after calling `gnrc_ipv6_nib_init_iface()`
Run the tests *on a board*. For some reason this is not failing on `native` without the patch, but does on e.g. `samd20-xpro`.
https://github.com/RIOT-OS/RIOT/pull/17893#issuecomment-1256123393
> tests: call gnrc_ipv6_nib_iface_up() after gnrc_ipv6_nib_init_iface()

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- sys/rust_riotmodules_standalone/Cargo.lock
- tests/rust_minimal/Cargo.lock
This will allow more components to build on 1.64 stable, and contains a fix relevant for https://github.com/RIOT-OS/RIOT/pull/18619.
---
The versions of riot-sys and riot-wrappers referenced here will likely be tagged as the next releases for those once this PR is through.
Green CI
https://github.com/RIOT-OS/RIOT/pull/18619 can be rebased onto this to fix the API-change-for-Rust it is causing.
> rust: Update dependencies

- boards/nucleo-f446ze/Kconfig
- boards/nucleo-f446ze/Makefile.features
- boards/nucleo-f446ze/include/periph_conf.h
This PR adds to the Nucleo-f446ze ADC configuration.
None
> boards/nucleo-f446ze: add support for ADC

- boards/nrf52dk/doc.txt
The board definition of the `nrf52dk` was likely created for some clone board. However, an official board name nRF52 DK provided by Nordic also exists. This resulted in previous contributors in confusing this with the official board and "fixing" the board definition to match the nRF52 DK board.
Or maybe it always has been meant to be the official board and someone just added a wrong image to it.
In either case, this brings the documentation back in alignment with the code by replacing references to some random clone board and the image of the random clone board with those to/of the official Nordic nRF52 DK board.
Proof reading the doc should be sufficient. In addition, one may want to check that e.g. the button and LED definitions in SAUL indeed work with a legitimate nRF52 DK board (it …
> boards/nrf52dk: fix doc

- makefiles/arch/riscv.inc.mk
With RISC-V being a relatively young toolchain, a lot of inconsistencies between different toolchains are to be found that differ in the target triple and the flags supported. This build system performs run-time tests to detect the toolchain and supported flags.
With `BUILD_IN_DOCKER=1` issues arise, as this checks are performed outside of the docker container. However, the host may have no RISC-V toolchain installed or a different toolchain, so there is little reason in performing this detection then. Instead, a hard coded target triple and supported flags are provided when using `BUILD_IN_DOCKER=1`.
E.g. `make BOARD=hifive1b BUILD_IN_DOCKER=1 -C examples/default` should work even if no host RISC-V toolchain is installed.
Fixes https://github.com/RIOT-OS/RIOT/issues/18653
> makefiles/arch/riscv.inc.mk: Fix with BUILD_IN_DOCKER

- cpu/atxmega/include/periph_cpu.h
- examples/micropython/Makefile
- pkg/libhydrogen/Makefile
- sys/shell/cmds/dfplayer.c
Collects build fixes necessary since https://github.com/RIOT-OS/riotdocker/pull/189.
> treewide: Ubuntu jammy build fixes

- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/gcoap/gcoap.c
At the moment, the Max-Age option is not set in a forwarded Valid message by a forward proxy. This is a bug, as the downstream clients then assume that the Max-Age is the default 60s, possibly breaking Cache validation, if Max-Age actually was smaller. This PR fixes that.
During testing this fix, I found another bug in the client-side cache validation: when the ETag is shorter than 8 bytes (e.g. with the fileserver), it is shortened after the fact. For that the wrong bitmask was used to protect the Option Delta.
I applied the following patch to add a Max-Age option to `gcoap_fileserver`
<details>
```patch
diff --git a/sys/net/application_layer/gcoap/fileserver.c b/sys/net/application_layer/gcoap/fileserver.c
index eaf14a252b..45bf652507 100644
--- …
```
> gcoap_forward_proxy: copy Max-Age from forwarded Valid if it exists

- sys/include/net/gcoap.h
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/application_layer/nanocoap/nanocoap.c
`coap_match_path()` returns the result of `strcmp`, so 0 is a match, non-zero give the order of the two strings.
For some reason GCoAP things the order is important - which leads to surprising results.
E.g. if you have
```C
static const coap_resource_t _resources[] = {
{ "/fw", COAP_GET | COAP_MATCH_SUBTREE, gcoap_fileserver_handler, SUIT_FW_DIR },
{ "/cmd", COAP_PUT, _coap_cmd_handler, NULL },
{ "/log", COAP_PUT, _coap_log_handler, NULL },
};
```
The `/cmd` endpoint will always return 404.
> gcoap: accept resources in any order

- boards/remote-revb/Kconfig
- boards/remote-revb/Makefile.dep
- boards/remote-revb/Makefile.features
- boards/remote-revb/board.c
- boards/remote-revb/include/board.h
Add MTD configuration to the remote-revb board.
```
$ BOARD=remote-revb make -C tests/mtd_raw all flash term
[...]
2022-09-20 09:48:12,881 # main(): This is RIOT! (Version: 2022.10-devel-680-gf03f5-remote-revb-mtd)
2022-09-20 09:48:12,881 # Manual MTD test
2022-09-20 09:48:12,882 # init MTD_0… OK (1915 MiB)
> info
2022-09-20 09:48:52,809 # info
2022-09-20 09:48:52,809 # mtd devices: 1
2022-09-20 09:48:52,809 #  -=[ MTD_0 ]=-
2022-09-20 09:48:52,810 # sectors: 3921920
2022-09-20 09:48:52,810 # pages per sector: 1
2022-09-20 09:48:52,810 # page size: 512
2022-09-20 09:48:52,810 # total: 1915 MiB
```
```
$ BOARD=remote-revb make -C tests/vfs_default all flash term
[...]
2022-09-20 09:49:37,168 # main(): This is RIOT! (Version: 2022.10-devel-680-gf03f5-remote-revb-mtd)
2022-09-20 09:49:37,168 …
```
> boards/remote-revb: define default MTD device

- examples/micropython/Makefile
Accidentally disabled for _all_ in https://github.com/RIOT-OS/RIOT/pull/18652.
https://github.com/RIOT-OS/RIOT/pull/18652
> examples/micropython: re-enable CI test on non-native

- boards/adafruit-itsybitsy-m4/include/periph_conf.h
- boards/adafruit-pybadge/include/periph_conf.h
- boards/arduino-nano-33-iot/include/periph_conf.h
- boards/bastwan/include/periph_conf.h
- boards/common/arduino-mkr/include/periph_conf_common.h
- boards/common/arduino-zero/include/periph_conf.h
- boards/common/saml1x/include/periph_conf.h
- boards/feather-m0/include/periph_conf.h
- boards/hamilton/include/periph_conf.h
- boards/samd10-xmini/include/periph_conf.h
- boards/samd20-xpro/include/periph_conf.h
- boards/samd21-xpro/include/periph_conf.h
- boards/same54-xpro/include/periph_conf.h
- boards/saml21-xpro/include/periph_conf.h
- boards/samr21-xpro/include/periph_conf.h
- boards/samr30-xpro/include/periph_conf.h
- boards/samr34-xpro/include/periph_conf.h
- boards/seeeduino_xiao/include/periph_conf.h
- boards/sensebox_samd21/include/periph_conf.h
- boards/serpente/include/periph_conf.h
- boards/sodaq-autonomo/include/periph_conf.h
- boards/sodaq-explorer/include/periph_conf.h
- boards/sodaq-one/include/periph_conf.h
- boards/sodaq-sara-aff/include/periph_conf.h
- boards/sodaq-sara-sff/include/periph_conf.h
- boards/yarm/include/periph_conf.h
- cpu/sam0_common/include/periph_cpu_common.h
- cpu/sam0_common/periph/adc.c
The `.pin` member is no longer used and the `.muxpos` member is much more than just MUXPOS now - so drop the `.pin` and while we change the API anyway, also rename `.muxpos`.
follow-up to #18146
> cpu/sam0_common: adc: drop pin from adc_conf_chan_t

- makefiles/defaultmodules_regular.inc.mk
- sys/Kconfig
- sys/include/string_utils.h
- sys/libc/Kconfig
- sys/libc/Makefile
- sys/libc/string.c
- tests/unittests/tests-libc/Makefile
- tests/unittests/tests-libc/tests-libc.c
- tests/unittests/tests-libc/tests-libc.h
`strncpy` is known to be dangerous as it will truncate the string without inserting a terminating zero.
The replacement `strlcpy` had the problem that the return value had to be compared to the destination buffer to detect truncation.
In Linux the consensus now seems to have settled on `strscpy()` which returns `-E2BIG` if the string was truncated.
https://lwn.net/Articles/905777/
> sys/string_utils: add strscpy()

- examples/gcoap_dtls/README.md
Add a simple usage example to the gcoap_dtls example 
Read the new documentation, and:
In one shell:
```Console
$ make -C examples/gcoap_dtls/ all term
```
In the other:
```Console
$ coap-client coaps://[fe80::d83c:a5ff:fe9c:3a41%tapbr0]/.well-known/core -k "secretPSK" -u "Client_identity"
```
Adjust the IP address of course
None
> examples/gcoap_dtls: Add coap-client example

- .murdock
This PR is the next step in migrating to the new CI frontend.
It basically configures the available pifleet boards depending on the actual CI instance.
This also disables the default test board collection for our current CI, ci-prod will take over once this is merged.
> murdock: make available boards instance dependent

- sys/include/net/sixlowpan/nd.h
- sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
On `master`, a `6LR` is sending Router solicitations like crazy, after it found a `6LBR`, because the lifetime of an `ABR` in an `ABRO` is not corrected to the default value, if it was 0.
A `6LBR` is allowed to set the lifetime of an `ABR` in an `ABRO` to 0, if the default value can be assumed. 
[RFC6775](https://datatracker.ietf.org/doc/html/rfc6775#section-4.3):
>    Valid Lifetime:             16-bit unsigned integer.  The length of
time in units of 60 seconds (relative to
the time the packet is received) that
this set of border router information is
valid.  A value of all zero bits (0x0)
assumes a default value of 10,000
(~one week).
We do that here:
https://github.com/RIOT-OS/RIOT/blob/09fd98c0c6f13c9dba2cbce7c4301465f4bfdab9/sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c#L199-L206 …
> nib/_nib-6ln: correct ABR timeout in ABRO

- dist/tools/codespell/ignored_words.txt
Static tests currently fail in master due to some false positives in `codespell`. This adds those to the ignore_words.txt.
static-tests should pass.
None
> codespell: add false positives for v2.2.1

- pkg/fatfs/fatfs_vfs/fatfs_vfs.c
- pkg/littlefs/fs/littlefs_fs.c
- pkg/littlefs2/fs/littlefs2_fs.c
- pkg/spiffs/fs/spiffs_fs.c
- sys/fs/constfs/constfs.c
- sys/fs/devfs/devfs.c
- sys/include/vfs.h
- sys/vfs/vfs.c
- tests/devfs/main.c
Both `open()` and `opendir()` also get the absolute path in VFS.
This is used by no filesystem and worse, only present for those two functions.
So even if a filesystem would rely on the absolute path, it could not `mkdir`, `unlink` or `rename` files.
Remove it as it only adds clutter and confusion.
CI should be enough, this parameter was unused by every implementation.
> vfs: drop unused abs_path parameter

- .murdock.yml
This will provide a link to the rendered documentation in Murdock's stick comment.
Once https://github.com/murdock-ng/murdock/pull/9 is deployed, we can set the "CI: ready for build" label. The comment by Murdock should then contain a link to the documentation preview.
Requares https://github.com/murdock-ng/murdock/pull/9 and the code in it being deployed.
> .murdock.yml: Add preview link to documentation to comment

- cpu/native/include/native_internal.h
- cpu/native/mtd/mtd_native.c
- cpu/native/syscalls.c
When `native` is provided with a `MEMORY.bin` file that is a file system image, it should use the whole image and not just the size specified by `MTD_SECTOR_NUM`.
Create a 16 MiB file in `tests/vfs_default`
dd if=/dev/zero of=MEMORY.bin bs=4096 count=4096
and verify that `native` detects the whole size
```
Manual MTD test
init MTD_0… OK (16 MiB)
> info
info
mtd devices: 1
-=[ MTD_0 ]=-
sectors: 4096
pages per sector: 16
page size: 256
total: 16 MiB
> test 0
test 0
[START]
[SUCCESS]
```
> cpu/native: get mtd size from file size

- boards/stm32f746g-disco/include/board.h
- boards/stm32f746g-disco/include/gpio_params.h
This PR adds LED LD1 of STM32F746-DISCO as LED0.
LED LD1 has no special function on the board STM32F746-DISCO and therefore can be used freely. This LED is also defined as ARDUINO LED pin D13 in the schematic.
Compile and flash
```
BOARD=stm32f746g-disco make -j8 -C tests/leds flash term
```
and check that LD1 works.
> boards/stm32f746g-disco: add LD1 as LED0 definition

- .cargo/config.toml
- examples/rust-gcoap/Cargo.lock
- examples/rust-gcoap/Cargo.toml
- examples/rust-hello-world/Cargo.lock
- examples/rust-hello-world/Cargo.toml
- sys/rust_riotmodules_standalone/Cargo.lock
- tests/rust_libs/Makefile
- tests/rust_minimal/Cargo.lock
- tests/rust_minimal/Makefile
This is a bit more than the usual "bump dependencies", as it also reaps the benefits from the latest crate updates:
* The overrides that say "we take riot-sys and riot-wrappers from git" are commented out. This results in builds (especially those of the imminent release) will thus fetch code from crates.io only, and not resort to direct git fetching. I consider this fitting for a release, see also <https://github.com/RIOT-OS/Release-Specs/issues/251>. If updates need to be done during the next release cycle that require quick fixes, the lines can just be enabled again in the same commit that then also does the `cargo update` that is necessary to apply the updates into the Cargo.lock files anyway.
* Tests can be run on stable.
* Examples are prepared to run on stable (which for native …
> rust: Update dependencies, build and test more on stable

- core/include/mutex.h
- core/mutex.c
- cpu/atxmega/periph/gpio.c
- cpu/atxmega/periph/pm.c
- cpu/atxmega/periph/timer.c
- cpu/atxmega/periph/uart.c
- drivers/atwinc15x0/atwinc15x0_netdev.c
- drivers/sgp30/sgp30.c
- drivers/sm_pwm_01c/sm_pwm_01c.c
- pkg/driver_bme680/contrib/bme680_hal.c
- sys/riotboot/reset.c
- tests/periph_gpio_ll/main.c
This restores a pre-existing design decision to implement both blocking and non-blocking mutex locking with the same code. Those implementations have been split prior to the introduction of the `core_mutex_priority_inheritance` module when `mutex_trylock()` indeed was trivial. This decision didn't age well, so undo it.
Let's have the CI run some tests.
None
> core/mutex: clean up

- boards/nucleo-l4r5zi/Kconfig
- boards/nucleo-l4r5zi/Makefile.features
- boards/nucleo-l4r5zi/include/periph_conf.h
- cpu/stm32/include/periph/l4/periph_cpu.h
- cpu/stm32/periph/adc_l4.c
This PR adds to the Nucleo-l4r5zi ADC configuration.
None
> boards/nucleo-l4r5zi:  support for ADC

- sys/include/event/callback.h
- sys/include/event/periodic_callback.h
- tests/event_periodic_callback/main.c
- tests/event_periodic_callback/tests/01-run.py
This is a purely aesthetic addition: When initializing an event, e.g. to measure a sensor, I want to have a locally visible `static lm75_t lm75_dev` that I use as the event argument.
I can access this in the callback, but if I want to access it outside the callback, e.g. to re-init the sensor after the callback was suspended, I have to access `event->event.arg` which feels dirty.
Instead, add a nice getter function that does the same.
An easy helper to execute a function by the event thread, to be called e.g. in an interrupt or by another function that is not supposed to block.
> event_periodic_callback: add getter for user context, one-shot event

- dist/tools/codespell/ignored_words.txt
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/checksum/crc32.c
- sys/include/checksum/crc32.h
- tests/unittests/tests-checksum/tests-checksum-crc32.c
- tests/unittests/tests-checksum/tests-checksum.c
- tests/unittests/tests-checksum/tests-checksum.h
The CRC-32 checksum algorithm was previously absent in RIOT, so add it.
This is with the polynomial used by e.g. Ethernet, SATA, PNG, etc.
A new unit test was added to `tests-checksum`.
> sys/checksum: add CRC-32 checksum 

- cpu/sam0_common/include/periph_cpu_common.h
The `.muxpos` member was renamed to `.inputctrl` to make clearer that it can contain more than just the positive mux.
This however makes working with external boards much more painful, especially when bisecting something.
The semantics of the field did not change, so also provide the old name in a `union` to make the transition less painful. 
follow-up to #18658
> cpu/sam0_common: ADC keep muxpos as legacy define

- boards/nucleo-f303ze/Kconfig
- boards/nucleo-f303ze/Makefile.features
- boards/nucleo-f303ze/include/periph_conf.h
- boards/p-nucleo-wb55/include/periph_conf.h
- cpu/stm32/Makefile.dep
- cpu/stm32/include/periph/cpu_usbdev.h
- cpu/stm32/periph/Makefile
- cpu/stm32/periph/usbdev_fs.c
This PR provides some changes of the `cpu/stm32/periph/usbdev_fs` driver to support STM32F3. In detail, it includes the following changes:
- Small bug fix of the register name (commit 1ed26d83a20fee62b52297682eb781c378d59b27)
- Conditional conpilation of the Clock Recovery System configuration (commit b287a72c7afb8d950abda986b3f67a099a354bfd)
- Defiinition of GPIOs for USB_DM and USB_DP signals as additional function instead of alternative function (commit 332c39908e63b9787425a1e8154a7d8e9d5f1a7d)
- Definition of a GPIO used for USB Connect/Disconnect (commit 3693e16b770cc5f57f6f238f4b1ff028c7ca0713)
- Changes to support STM32F3 family (commit ca9cedb2ac508111c4a2457da10844af88be35b1)
- `periph_usbdev` support for `nucleo-f303ze`
Other boards using STM32F303 MCU such as `stm32f3discovery` …
> cpu/stm32/periph/usbdev_fs: add support for STM32F3 family

- makefiles/docker.inc.mk
This change allows the use of podman instead of docker.
On a system where `podman` is installed, build an example
```
BUILD_IN_DOCKER=1 make -C examples/hello-world DOCKER=podman BOARD=sodaq-sara-sff clean all
```
If the docker command is redirected to podman you don't need the `DOCKER=podman`.
```
$ BUILD_IN_DOCKER=1 make -C examples/hello-world BOARD=sodaq-sara-sff clean all
```
On a system where `docker` is installed do:
```
$ BUILD_IN_DOCKER=1 make -C examples/hello-world BOARD=sodaq-sara-sff clean all
```
Examples: Fixes #18552
> Add podman support

- sys/include/net/ipv4/addr.h
- sys/net/network_layer/ipv4/addr/ipv4_addr.c
Adds the function `ipv4_addr_print`, similar to the already existing to `ipv6_addr_print`.
Dependency for and split out from #16853
> sys/net/network_layer/ipv4/addr: add ipv4_addr_print function

- boards/common/arduino-zero/Kconfig
- boards/common/arduino-zero/Makefile.features
- boards/samd21-xpro/Kconfig
- boards/samd21-xpro/Makefile.features
- boards/same54-xpro/Kconfig
- boards/same54-xpro/Makefile.features
- boards/saml21-xpro/Kconfig
- boards/saml21-xpro/Makefile.features
- boards/samr21-xpro/Kconfig
- boards/samr21-xpro/Makefile.features
- boards/samr30-xpro/Kconfig
- boards/samr30-xpro/Makefile.features
- boards/samr34-xpro/Kconfig
- boards/samr34-xpro/Makefile.features
- pkg/tinyusb/Kconfig
- pkg/tinyusb/Makefile
- pkg/tinyusb/Makefile.dep
- pkg/tinyusb/Makefile.include
- pkg/tinyusb/hw/Makefile
- pkg/tinyusb/hw/hw_sam0.c
- pkg/tinyusb/patches/0003-src-portable-microchip-update-header-file-for-RIOT-s.patch
This PR add tinyusb pkg support for SAM0-based MCUs.
I used `usbdev` support as pattern to enable tinyusb on them.
I tested this PR on `same54-xpro`, `samr21-xpro` and `saml21-xpro`
Use any SAM0-based board declare in this PR with tinyusb:
`BOARD=samr21-xpro make -C tests/pkg_tinyusb_cdc_msc flash`
tinyusb should works as expected.
None.
> pkg/tinyusb: add support for SAM0-based boards

- cpu/cortexm_common/thread_arch.c
When an exiting thread that was using the FPU would cause a context switch to a non-FPU-using thread, the lazy stacking could stay activated with outdated info, causing memory corruption:
1. fpu using thread exits, lands in `sched_task_exit`
2. `sched_active_thread` is set to NULL
3. `cpu_switch_context_exit` triggers pendsv
4. pendsv exception entry creates an extended stack frame, configures lazy stacking with FPCAR pointing to the exiting thread's reserved space
5. isr_pendsv *skips storing the thread context* because sched_active_thread is NULL
6. isr_pendsv, when jumping to a thread that didn't use fpu (thus the restored EXC_RETURN[4] is set), *doesn't restore FPU context
8. note that lazy stacking was activated due to the thread using FPU, but in ISR, no fpu is used, and the …
> cpu/cortexm: clear FPU state in `cpu_switch_context_exit()`

- sys/shell/Makefile.dep
- sys/shell/cmds/cord_ep.c
* (Everything was done on the lastest master as of 2022-05-04T10:00)
* This PR only touches the shell command handling of `cord_ep`
* Not sure if I want to call it a fix; It fixes an issue where running the subcommand `cord_ep register` just slightly wrong, an assertion in [gcoap.c](https://github.com/RIOT-OS/RIOT/blob/a427d630f17799188c0caf95d8dd327846d39a23/sys/net/application_layer/gcoap/gcoap.c#L1134) would get triggered - resulting in a RIOT kernel panic.
* I consider this behaviour to be a bug, reasoning that a shell should be able to cope with users that do not exactly know what they are doing. (Go figure who that user was 😇)
* This PR corrects this behaviour by doing a short sanity check on the user input - yielding an error if necessary.
For reproducing the bug do:
1. Go to …
> shell/cord_ep: Add user guidance & prevent accidental crash

- boards/common/esp32s2/include/periph_conf_common.h
- boards/common/esp32s3/include/periph_conf_common.h
- boards/common/stm32/include/cfg_usb_otg_hs_phy_fs.h
- boards/stm32f429i-disc1/include/periph_conf.h
- boards/stm32f746g-disco/Kconfig
- boards/stm32f746g-disco/doc.txt
- boards/stm32f746g-disco/features-shared.mk
- boards/stm32f746g-disco/include/periph_conf.h
- boards/stm32f7508-dk/Kconfig
- drivers/Makefile.dep
- drivers/include/usbdev_synopsys_dwc2.h
- drivers/periph_common/Kconfig
- drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
- kconfigs/Kconfig.features
This PR adds the support for external ULPI HS PHYs.
Boards whose USB OTG HS peripherals use an external HS-PHY via the ULPI interface, such as the board `stm32f746g-disco`, can be used with this PR in USB HS mode. For this purpose, the USB OTG configuration structure has been extended by the ULPI interface configuration. ULPI HS PHY support is enabled by the `periph_usbdev_hs_ulpi` module, which requires the `periph_usbdev_hs_ulpi` feature.
Boards whose USB OTG HS peripherals use an external HS-PHY via the ULPI interface must define the ULPI interface configuration and provide the `periph_usbdev_hs_ulpi` feature. The application can then enable the USB OTG HS port by enabling the `periph_usbdev_hs_ulpi` module.
The best way to test the PR is to use a board with two USB OTG ports (one FS …
> drivers/usbdev_synopsys_dwc2: add USB OTG HS peripheral support for external ULPI HS PHYs

- makefiles/pseudomodules.inc.mk
- sys/include/event/thread.h
Alternative to the non-semantical page introduced in https://github.com/RIOT-OS/RIOT/pull/18649.
`make doc` and look at the resulting `doc/doxygen/html/deprecated.html` (or see documentation artifcats in https://github.com/RIOT-OS/RIOT/pull/18698#issuecomment-1269481501).
Alternative to a proposal in https://github.com/RIOT-OS/RIOT/pull/18649.
> doc: add deprecation notice on deprecated pseudo-modules

- makefiles/deprecated_modules.inc.mk
- makefiles/pseudomodules.inc.mk
- sys/net/gnrc/Makefile.dep
- sys/shell/Makefile.dep
- sys/shell/cmds/Kconfig
- sys/shell/cmds/gnrc_netif.c
Model the LoRaWAN integration to GNRC's netif command (ifconfig) as submodule of it, namely `shell_cmd_gnrc_netif_lorawan`.
This should fix a regression introduced by https://github.com/RIOT-OS/RIOT/pull/18355
Run and compile `examples/gnrc_lorawan` for `BOARD=b-l072z-lrwan1` as described in https://github.com/RIOT-OS/RIOT/pull/18355#issuecomment-1257780845
https://github.com/RIOT-OS/RIOT/pull/18355#issuecomment-1257780845
Alternative to https://github.com/RIOT-OS/RIOT/pull/18648
> sys/shell/cmds: fix shell_cmd_netif LoRaWAN integration

- drivers/dose/Kconfig
- drivers/dose/Makefile.dep
- drivers/dose/dose.c
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/checksum/crc16_ccitt.c
- sys/include/checksum/crc16_ccitt.h
The look-up table for CRC-16 can be quite heavy, so also provide an implementation without it.
The look-up table can be enabled with the `crc16_fast` pseudo-module.
Since this removes @jue89's concern with the common implementation, also use it in DOSE instead of re-implementing CRC-16 there. (DOSE's CRC-16 implementation is now the common one without the look-up table).
The `tests-checksum` unittest still works with and without `crc16_fast`.
> sys/checksum: add CRC-16 implementation without lookup table

- makefiles/pseudomodules.inc.mk
This adds the deprecation of `gnrc_netif_cmd_lora` that was introduced in https://github.com/RIOT-OS/RIOT/pull/18649 to the documentation list of deprecated things.
`make doc` and read doc/doxygen/html/deprecated.html.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/18649 and semantically requires it to be merged.
> pseudomodules: document gnrc_netif_cmd_lora as deprecated

- pkg/cryptoauthlib/Makefile
ATCA_NO_HEAP must be passed to cryptoauthlib build system in order to not use dynamic memory allocation.
Build fails when using KCONFIG for dependency resolution, because ATCA_NO_HEAP is not defined.
This fixes the problem.
Build `tests/pkg_cryptoauthlib_compare_sha256/` using KCONFIG dependency resolution.
> pkg/cryptoauthlib: Pass ATCA_NO_HEAP Flag to library

- .github/workflows/release-test.yml
We are using Ubuntu Jammy (22.04) with our docker containers to build the release, but the release tests are still run in `ubuntu-latest`, which, at the moment, is still Ubuntu Focal (20.04): https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources. Because of that, both the libasan used and libc used differ between builder and the test runner which leads to an execution error of the `native` binaries. This moves the Github Action runner to `ubuntu-2204` and installs libasan 6 instead of libasan 5.
I ran the release tests with a representative subset of the tests that are currently failing with master: https://github.com/miri64/RIOT/actions/runs/3209912518/jobs/5246989391 they now succeed. I also started a full run …
> release-tests: use Ubuntu Jammy runner

- .github/workflows/release-test.yml
This adds the capability to trigger a `release-tests` run when a member or owner of the RIOT-OS organization leaves a review that contains "@riot-ci do release tests" (case insensitive).
I decided to go for a review rather than comments, since
1. the comments trigger would also include issue comments and it would spin up the action every time a comment is made (it is then however canceled early, but it would just clutter our already full Actions tab)
2. the comment trigger would not add the results to the checks for the PR.
Additionally, a pytest filter can be used by commenting '@riot-ci do release tests with "\<pytest filter>"' instead.
I did extensive testing of this functionality here: https://github.com/miri64/RIOT/pull/37. AFAIK for this to work in main RIOT, this PR has to be …
> release-tests: add capability to run on PR comment

- dist/pythonlibs/riotctrl_shell/cord_ep.py
- dist/pythonlibs/riotctrl_shell/tests/test_cord_ep.py
The argument regif was removed from the shell command in https://github.com/RIOT-OS/RIOT/pull/18053, so there is not much need to keep it in the ShellInteraction for that command.
```
cd dist/pythonlibs/riotctrl_shell; tox
```
should still succeed 
Follow-up on https://github.com/RIOT-OS/RIOT/pull/18053
Also see https://github.com/RIOT-OS/Release-Specs/pull/260 for the fix of release spec 9.1 and the test for it.
> riotctrl_shell.cord_ep: remove regif parameter

- examples/telnet_server/Makefile.ci
- sys/include/net/gnrc/ipv6/nib.h
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c
The main motivation for this was, that I observed that with #18700 the LoRaWAN thread suddenly used a huge amount of stack space. Given that `gnrc_ipv6_nib_iface_up` accumulated already uses over 100 bytes on the board I was using (`b-l072z-lrwan1`), the function is called very deep in the stack, and since it is really weird, that the netif calls a function that configures an IPv6 component, I decided to decouple this call into the `gnrc_ipv6` handler, which is actually a cleaner approach.
I do not have a device that supports this currently in master, but I confirmed that the up-event is still executed when merging this PR (and the changes I will push to #18699 in a moment) by checking if the link-local address was configured, using `ifconfig`.
Follow-up on #17893
> gnrc_ipv6_nib: handle iface_up/iface_down in IPv6 thread

- sys/net/sock/sock_util.c
- tests/unittests/tests-sock_util/tests-sock_util.c
`_find_hoststart()` would increment `urlpos` twice on each iteration, making it impossible to work with schemas of uneven length (e.g. `https://` or `coaps://`).
I modified the `sock_util` test case to also test for a schema of uneven length.
> sys/net/sock_util: fix _find_hoststart()

- cpu/esp32/Makefile.include
- pkg/esp32_sdk/Makefile.include
The definition in `pkg/esp32_sdk/Makefile.include` was evaluated by `make` after the include paths were already set, resulting in `ESP32_SDK_DIR` being empty in
INCLUDES += -I$(ESP32_SDK_DIR)/components
[...]
This in turn resulted in
cc1: error: /components: No such file or directory [-Werror=missing-include-dirs]
[...]
```
$ make BOARD=esp32-mh-et-live-minikit -C examples/hello-world
make: Entering directory '/home/maribu/Repos/software/RIOT/examples/hello-world'
Building application "hello-world" for "esp32-mh-et-live-minikit" with MCU "esp32".
"make" -C /home/maribu/Repos/software/RIOT/pkg/esp32_sdk/ 
"make" -C /home/maribu/Repos/software/RIOT/boards/common/init
"make" -C /home/maribu/Repos/software/RIOT/boards/esp32-mh-et-live-minikit
"make" -C …
```
> cpu/esp32: move ESP32_SDK_DIR definition here

- cpu/esp_common/periph/uart.c
The parameters for parity and stop bits was confused, resulting in the following compilation error with GCC 12.2.0:
/home/maribu/Repos/software/RIOT/cpu/esp_common/periph/uart.c: In function '_uart_config':
/home/maribu/Repos/software/RIOT/cpu/esp_common/periph/uart.c:394:61: error: implicit conversion from 'uart_stop_bits_t' to 'uart_parity_t' -Werror=enum-conversion]
394 |     if (_uart_set_mode(uart, _uarts[uart].data, _uarts[uart].stop,
|                                                 ~~~~~~~~~~~~^~~~~
/home/maribu/Repos/software/RIOT/cpu/esp_common/periph/uart.c:395:42: error: implicit conversion from 'uart_parity_t' to 'uart_stop_bits_t' -Werror=enum-conversion]
395 |                              _uarts[uart].parity) != UART_OK) {
|                              ~~~~~~~~~~~~^~~~~~~ …
> cpu/esp_common/periph_uart: fix call to _uart_set_mode

- sys/net/application_layer/gcoap/fileserver.c
- tests/gcoap_fileserver/Makefile
- tests/gcoap_fileserver/Makefile.ci
- tests/gcoap_fileserver/main.c
- tests/gcoap_fileserver/tests/01-run.py
This adds a test for blockwise PUT to `tests/gcoap_fileserver`.
Doing so uncovered a bug: When a block would be transmitted, but the ACK got lost, the sender would re-transmit the block.
This triggered the `block1.offset != (unsigned)ret` check in the GCoAP fileserver which considered this an error and aborted the transmission.
To fix this, simply ignore old blocks and send a `COAP_CODE_CONTINUE` anyway.
CI will run `tests/gcoap_fileserver`.
> tests/gcoap_fileserver: add test for PUT

- sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c
- sys/net/gnrc/network_layer/ipv6/nib/_nib-slaac.c
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
- tests/gnrc_ipv6_nib/mockup_netif.c
This prepares for SCHC support with LoRaWAN, by adding UP/DOWN events to `gnrc_netif_lorawan`. Since with LoRaWAN there is only a hardware address (and thus an IID) after the device joined the network (which is the UP event), auto-configuration of link-local addresses needs to be done on UP. Since the hardware address (and the IID for that matter, see https://datatracker.ietf.org/doc/html/rfc9011#section-5.3) might change on the next connect, the link-local address needs to be removed on down.
Sadly, there is no IPv6 support for LoRaWAN yet, so only a compile test must suffice for now. However, I need this for SCHC and IPv6 support (i.e. SCHC) for LoRaWAN is needed to test this, so this is somewhat of a hen-and-egg problem...
In preparation for #18700.
Requires ~~#18708~~ (merged).
> gnrc_netif_lorawan: add support for LINK_UP/_DOWN events

- drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
When using DMA to transfer endpoint data from the RX FIFO to the endpoint memory, the RXFLVL irq is not needed as that is already handled by the DMA. Furthermore, servicing this irq anyway can cause the event handling to interpret data from the FIFO as the endpoint and status marker during the DMA transfer.
This commit masks the RXFLVL irq while DMA is used for the endpoint transfers.
On my side current master quickly triggers faults because the somewhere halfway through the DMA transaction, the RXFLVL irq is serviced and the logic reads out data from the RX FIFO and assumes it is the first value containing the endpoint number (which has already been removed by the DMA).
On the nucleo-f746zg everything still works (not using DMA):
```
[ 3078.031400] usb 7-3.2.2: new full-speed USB device …
```
> usbdev_synopsys_dwc2: Mask RX FIFO irq when using DMA

- cpu/stm32/periph/usbdev_fs.c
This PR provides the following changes for the USB Device FS driver for STM32 MCUs to support STM32F1 MCUs.
1. Implementation of PMA access schemes:  MCUs with USB Device FS IP cores use two different schemes for the access to the Packet buffer Memory Area (PMA):
- 2 x 16 bit/word access scheme where two 16-bit half-words per word can be accessed. With this scheme the access can be half-word aligned and the  PMA address offset corresponds therefore to the local USB IP address.  The size of the PMA SRAM is usually 1024 byte.
- 1 x 16 bit/word access scheme where one 16-bit half word per word can be  accessed. With this scheme the access can only be word-aligned and the  PMA address offset to a half-word is therefore twice the local USB IP  address. The size of the PMA SRAM is usually 512 …
> cpu/stm32/periph/usbdev_fs: support for STM32F1 family

- .github/workflows/check-pr.yml
- .github/workflows/release-test.yml
- .github/workflows/static-test.yml
- .github/workflows/test-on-iotlab.yml
- .github/workflows/test-on-ryot.yml
- .github/workflows/tools-buildtest.yml
- .github/workflows/tools-test.yml
Github is complaining about deprecation of Node.js 12 deprecation in our Github Actions (one example can be found here: https://github.com/RIOT-OS/RIOT/actions/runs/3235426917) this is due to us using an outdated version of the actions/checkout Action. This bumps all of them to follow the master branch (as some already do, e.g. tools-buildtests).
See if the Node.js deprecation warning disappears.
None
> gh-actions: move actions/checkout to main

- boards/samr21-xpro/doc.txt
The stdin line length limitation can be very surprising and there is nothing in RIOT that would explain it.
To prevent users from scratching their head, add a note to the docs. 
execute 
echo 012345678901234567890123456789012345678901234567890123456789
in e.g. `tests/shell`
> boards/samr21-xpro: add a note about EDBG UART limitation

- makefiles/arch/avr8.inc.mk
At this point `$(CC)` will evaluate to `cc` which is the host compiler, not `avr-gcc`.
Test explicitly for `avr-gcc` to get the right compiler version.
alternative to #18643
> makefiles/arch/avr8.inc.mk: fix detection of GCC 12

- dist/tools/esptools/export.sh
- dist/tools/esptools/install.sh
This PR provides the folling changes in `dist/tools/esptools/{install,export}.sh` to support macOS:
- Since macOS doesn't have `ldconfig` command, the test for `libncursesw.so` version using the `ldconfig` command is moved to function `install_qemu`.
- Since the only platform support by `qemu-esp32` is `linux-amd64`, a platform test is added to the `export_qemu` function.
- Platform `Darwin-x86_64` added to the installation script.
The problem was found in https://forum.riot-os.org/t/esp32-undefined-reference-to-esp-mesh-is-scan-allowed/3680
Please note: I don't know whether the changes really work on macOS because of missing hardware.
- `dist/tools/esptools/{install,export}.sh all` should work as before on Linux.
- `dist/tools/esptools/{install,export}.sh all` should now work on macOS as …
> dist/tools/esptools: add macOS support to install/export scripts

- sys/include/net/gnrc/netif.h
- sys/net/gnrc/netif/gnrc_netif.c
- sys/net/gnrc/netif/init_devs/auto_init_atwinc15x0.c
- sys/net/gnrc/netif/init_devs/auto_init_cc110x.c
- sys/net/gnrc/netif/init_devs/auto_init_dose.c
- sys/net/gnrc/netif/init_devs/auto_init_enc28j60.c
- sys/net/gnrc/netif/init_devs/auto_init_encx24j600.c
- sys/net/gnrc/netif/init_devs/auto_init_esp_eth.c
- sys/net/gnrc/netif/init_devs/auto_init_ethos.c
- sys/net/gnrc/netif/init_devs/auto_init_netdev_tap.c
- sys/net/gnrc/netif/init_devs/auto_init_nrf24l01p_ng.c
- sys/net/gnrc/netif/init_devs/auto_init_sam0_eth.c
- sys/net/gnrc/netif/init_devs/auto_init_slipdev.c
- sys/net/gnrc/netif/init_devs/auto_init_stm32_eth.c
- sys/net/gnrc/netif/init_devs/auto_init_sx126x.c
- sys/net/gnrc/netif/init_devs/auto_init_sx127x.c
- sys/net/gnrc/netif/init_devs/auto_init_usbus_cdc_ecm.c
- sys/net/gnrc/netif/init_devs/auto_init_w5100.c
- sys/net/gnrc/netif/init_devs/auto_init_xbee.c
- sys/net/gnrc/netif/init_devs/include/init_devs.h
- tests/netutils/Makefile
The message queue of the netif was allocated on the netif stack, so we had to increase the netif stack size if we increase the message queue size.
CC110x was the only driver to get this right - add a new `GNRC_NETIF_STACKSIZE_DEFAULT` define so all drivers will get this right by default.
This should not change the stack size except for one case: `cc110x` had `CC110X_EXTRA_STACKSIZE` set to `(GNRC_NETIF_MSG_QUEUE_SIZE - 8) * sizeof(msg_t))` but the default message queue size is 16, adding `(16 - 8) * 8` = 64 bytes to the stack.
Leaving this at 8 for all drivers would effectively bump their stack by 8 messages.
Maybe this was a mistake or maybe `cc110x` really needs the extra 64 bytes of stack. 
@maribu might be able to give this a try and say if stack size is still sufficient.
> gnrc_netif: don't allocate message queue on the stack

- boards/common/blxxxpill/Kconfig
- boards/common/blxxxpill/Makefile.features
- boards/common/blxxxpill/include/periph_conf.h
- cpu/stm32/Makefile.dep
- cpu/stm32/include/periph/cpu_gpio.h
- cpu/stm32/periph/Makefile
- tests/sys_fido2_ctap/Makefile.ci
This attempts to enable the `usbdev_fs` module on STM32F1.
Unfortunately this does not work yet - It builds, but it looks like something else needs to be enabled on this platform.
Nothing shows up in `dmesg` when the USB test code is run (also no errors).
I don't know where to start looking for what it could be, but looking for some pointers to get USB support for this popular board.
Flash e.g. `tests/usbus_hid` or `tests/usbus_cdc_acm_stdio` on a bluepill or blackpill board.
> boards/blxxxpill: configure usbdev_fs

- .github/workflows/release-test.yml
Reverts RIOT-OS/RIOT#18713
Turns out: The secrets (TTN and IoT-Lab credentials) required for the release tests would be required to be configured in the fork. At this point it is easier to just trigger a release test run manually than to ask a contributor to configure those credentials in their fork... Maybe a route we can follow in a follow-up PR to maybe still trigger a test run via comment, but this requires some time and definitely not the changes introduced in #18713, so let's just revert it, since it does not work as intended and just spams the [release-tests tab](https://github.com/RIOT-OS/RIOT/actions/workflows/release-test.yml) in the actions atm.
> Revert "release-tests: add capability to run on PR comment"

- sys/include/net/gcoap/forward_proxy.h
- sys/net/application_layer/gcoap/Kconfig
- sys/net/application_layer/gcoap/forward_proxy.c
- sys/net/application_layer/gcoap/gcoap.c
This allows a forward proxy to ACK a request early, if the response from upstream takes too long. This is [based on the work](https://github.com/cgundogan/RIOT/commit/b4d727bd60f403e246ec9a8e34db370a10e83b36) by @chrysn for https://doi.org/10.1145/3405656.3418718 which is why I gave the main authorship of the commit to him. I merely adopted the state of change to the best practices and changes to `forward_proxy` in current master and optimized the `client_ep_t` to keep the increase in RAM-usage minimal (compared to just plane using `uint8_t`s, I was able to safe 3 bytes per entry, compared to using bitmaps, I was able to safe 16 bytes of ROM with my flag-based approach).
I used a version of my trusty proxy testing script again:
```python
#! /usr/bin/env python3
import subprocess
import …
```
> gcoap_forward_proxy: send empty ACK when response takes too long

- cpu/stm32/Makefile.dep
- cpu/stm32/periph/Kconfig
This fixes incorrect module selection for STM32F1 boards with feature periph_usbdev, a regression introduced by https://github.com/RIOT-OS/RIOT/pull/17812
```
~/Repos/software/RIOT $ BOARD=bluepill TEST_KCONFIG=0 make info-modules -C tests/sys_fido2_ctap > ~/mods-no-k 
~/Repos/software/RIOT $ BOARD=bluepill TEST_KCONFIG=1 make info-modules -C tests/sys_fido2_ctap > ~/mods-k 
~/Repos/software/RIOT $ diff ~/mods-no-k ~/mods-k 
--- /home/maribu/mods-no-k
+++ /home/maribu/mods-k
@@ -1,4 +1,6 @@
make: Entering directory '/home/maribu/Repos/software/RIOT/tests/sys_fido2_ctap'
+=== [ATTENTION] Testing Kconfig dependency modelling ===
+=== [ATTENTION] Testing Kconfig dependency modelling ===
auto_init
auto_init_random
auto_init_ztimer
@@ -85,6 +87,7 @@
stm32_vectors
sys
tsrb
+usbdev_synopsys_dwc2 …
```
> cpu/stm32: fix KConfig modeling for STM32F1 / usbdev_synopsys_dwc2

- examples/cord_ep/Makefile.ci
- sys/include/net/gnrc/netreg.h
- sys/net/gnrc/netapi/gnrc_netapi.c
- sys/net/gnrc/netreg/gnrc_netreg.c
- tests/gcoap_fileserver/Makefile.ci
- tests/unittests/tests-netreg/tests-netreg.c
GNRC netreg unregistration of interfaces has a subtle race condition: If a high-priority thread unregisters, it might be preempting a different thread that just used gnrc_netreg_lookup to find an active registration before that thread can act on it, unregister, and reuse the netreg entry (worst case, for something completely different). When then the low-priority thread continues, it still has a pointer to that reused location, and will take a callback address from there, or take some of that memory as a pointer to an mbox into which to deliver a message. Both of these are undefined behavior. (In the mbox case the damage is the least, it just sends a message to a thread that may have terminated and has its PID repurposed; while that is merely considered an error, it might still cascade). …
> gnrc_netreg: Use locks around netreg

- tests/driver_cc2538_rf/main.c
- tests/driver_nrf802154/main.c
- tests/driver_sx126x/main.c
- tests/driver_sx127x/main.c
- tests/driver_sx1280/main.c
- tests/socket_zep/main.c
See https://github.com/RIOT-OS/RIOT/pull/17893#issuecomment-1279037495.
All tests should compile and run as expected.
#17893
> tests: set netdev `event_callback` before calling init

- boards/nucleo-l4r5zi/doc.txt
Improvements to STM Nucleo l4r5zi documentation:
- Add board image,
- Add MCU table - similar to those, for example for, Nucleo F103RB, F302R8 or F446RE,
- Add information concerning accessing RIOT shell (see Issue #17453) 
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo144-l4r5.html
```
Issue #17453
> boards/nucleo-l4r5zi: doc improvements

- cpu/efm32/Makefile.features
- cpu/efm32/Makefile.include
- cpu/efm32/families/efr32mg12p/Kconfig
- cpu/efm32/families/efr32mg12p/Makefile.features
- cpu/efm32/families/efr32mg12p/Makefile.include
- cpu/efm32/families/efr32mg1b/Kconfig
- cpu/efm32/families/efr32mg1b/Makefile.features
- cpu/efm32/families/efr32mg1b/Makefile.include
- cpu/efm32/families/efr32mg1p/Kconfig
- cpu/efm32/families/efr32mg1p/Makefile.features
- cpu/efm32/families/efr32mg1p/Makefile.include
- cpu/efm32/periph/gpio.c
- pkg/gecko_sdk/Kconfig
- pkg/gecko_sdk/Makefile
- pkg/gecko_sdk/Makefile.dep
- pkg/gecko_sdk/Makefile.include
This PR updates the SDK to the latest release.
The update is required to bring back SiLabs' RAIL lib support to RIOT.
I've run buildtests for all EFM32-based boards that are present in RIOT:
```
jue@baxxter ~/P/s/RIOT (feature/pkg-gecko_sdk_41)> BOARDS="ikea-tradfri e180-zg120b-tb slstk3400a stk3200 slstk3401a slwstk6220a stk3700 slstk3402a sltb001a stk3600 slstk3400a slwstk6000b-slwrb4150a slwstk6000b-slwrb4162a" make -C examples/default buildtest
make: Entering directory '/home/jue/Projects/ssv/RIOT/examples/default'
Building for ikea-tradfri ... success.
Building for e180-zg120b-tb ... success.
Building for slstk3400a ... success.
Building for stk3200 ... success.
Building for slstk3401a ... success.
Building for slwstk6220a ... success.
Building for stk3700 ... success.
Building for …
```
> pkg/gecko_sdk: Bump to version 4.1.2

- sys/include/net/coap.h
- sys/include/net/nanocoap.h
- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/net/application_layer/nanocoap/sock.c
- tests/nanocoap_cli/main.c
- tests/nanocoap_cli/nanocli_client.c
This adds support for the no-response option ([RFC 7968](https://datatracker.ietf.org/doc/rfc7967/)) in the nanoCoAP server.
To allow for testing and easy use, the two client functions `nanocoap_sock_put_non()` and `nanocoap_sock_post_non()` are also added which will add the no-response option if no payload response is requested. 
A new `put_non` command has been added to `tests/nanocoap_cli`:
```
> put_non coap://[fe80::58b0:8ff:fe67:ad82]/value 42
> ncget coap://[fe80::58b0:8ff:fe67:ad82]/value -
42
```
Verify in Wireshark that indeed no response was generated to the PUT request
> nanocoap: add support for no-response option 

- boards/im880b/Makefile.include
Using the common STM32 board makefile provides all supported programmers for STM32 boards. This allows e.g. to flash with stm32flash via `make BOARD=im880b PROGRAMMER=stm32flash flash`.
`make flash` and `make term` should still work for OpenOCD with ST-Links as before, but additional programmers should now be available. I was able to program with `stm32flash`.
None
> boards/im880b: refactor code

- tests/driver_cc2538_rf/main.c
- tests/driver_nrf802154/main.c
- tests/driver_sx126x/main.c
- tests/driver_sx127x/main.c
- tests/driver_sx1280/main.c
- tests/socket_zep/main.c
See https://github.com/RIOT-OS/RIOT/pull/17893#issuecomment-1279037495.
All tests should compile and run as expected.
#17893
> tests: set netdev `event_callback` before calling init [backport 2022.10]

- makefiles/pseudomodules.inc.mk
- sys/Kconfig.stdio
- sys/include/stdio_uart.h
- sys/stdio_uart/stdio_uart.c
Add USE_MODULE += "stdio_uart_onlcr" to enable it. This is named after the "onlcr" stty flag, which does the same thing.
```
USEMODULE=stdio_uart_onlcr make BOARD=<board-with-stdio_uart> -C examples/default
```
The shell should now work with a terminal that expects DOS line endings.
Alternative to: https://github.com/RIOT-OS/RIOT/pull/18703 and https://github.com/RIOT-OS/RIOT/pull/15619
This is basically picking up https://github.com/RIOT-OS/RIOT/pull/15619 and polishing it a bit.
> sys/stdio_uart: add stdio_uart_onlcr (pseudo-) module

- sys/include/net/nanocoap.h
- sys/net/application_layer/gcoap/gcoap.c
- sys/net/application_layer/nanocoap/nanocoap.c
- sys/net/application_layer/nanocoap/sock.c
this might need a deprecation period first
remove the token ptr from nanocoap `coap_pkt_t` in favour of `coap_get_token()` introduced in #17976
murdock build 
#17976
wait for #17950
> net/nanocoap: remove coap_pkt token ptr

- boards/common/stm32/include/cfg_usb_otg_hs_phy_utmi.h
- boards/stm32f723e-disco/Kconfig
- boards/stm32f723e-disco/Makefile.features
- boards/stm32f723e-disco/doc.txt
- boards/stm32f723e-disco/include/periph_conf.h
- drivers/Makefile.dep
- drivers/include/usbdev_synopsys_dwc2.h
- drivers/periph_common/Kconfig
- drivers/periph_common/Kconfig.usbdev
- drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
- kconfigs/Kconfig.features
This PR adds the support for internal UTMI+ HS PHYs.
Boards whose MCU integrate an UMTI+ HS PHY for their USB OTG HS peripherals, such as the STM32F723xx used on board `stm32f723e-disco`, can be used in USB HS mode with this PR. The UTMI+ HS PHY support is enabled by the `periph_usbdev_hs_utmi` module, which requires the `periph_usbdev_hs_utmi` feature.
The best way to test the PR is to use a board with two USB OTG ports (one FS port and one HS port with internal UTMI+ HS PHY, such as the board "stm32f723e-disco") connected to the host with two USB cables.
1. Compile and flash application `tests/usbus_hid`
```
BOARD=stm32f723e-disco make -C tests/usbus_hid flash term
```
The FS port should still work.
```python
Oct  9 17:14:16 gunny8 kernel: [2342975.208076] usb 1-2.2: new full-speed USB …
```
> drivers/usbdev_synopsys_dwc2: add support for internal UTMI HS PHY

- .github/workflows/test-on-iotlab.yml
- tests/gnrc_rpl/Makefile
Adds a few fixes, so that some of the tests currently failing in the test-on-iotlab action run again.
I will start a manual run of the action.
None
> test-on-iotlab: several fixes to make it runnable again

- .github/workflows/test-on-iotlab.yml
- tests/gnrc_rpl/Makefile
Adds a few fixes, so that some of the tests currently failing in the test-on-iotlab action run again.
I will start a manual run of the action.
None
> test-on-iotlab: several fixes to make it runnable again [backport 2022.10]

- drivers/at/at.c
- drivers/include/at.h
There are many modem commands for which you get a line of response followed by an OK. Take for example the AT+CGSN command to get the IMEI of a Ublox G350.
```
>> AT+CGSN
<< 004999010640000
<< OK
```
> drivers/at: add a function read a response plus the OK

- cpu/efm32/cpu.c
- cpu/efm32/include/periph_cpu.h
- cpu/efm32/periph/gpio.c
- cpu/efm32/periph/pm.c
This is split-off #18760 and provides commits that are useful for #18756.
1. Compile testing.
2. `tests/periph_gpio` should be able to raise IRQs even with `PM_BLOCKER_INITIAL` set to `{ 0, 0, 0 }`. Make sure to configure `GPIO_INT_PM_BLOCKER` to the lowest power mode that is able to register IRQs.
#18760 
#18756
> cpu/efm32: preparing introduction of Gecko Series 2 

- makefiles/pseudomodules.inc.mk
- sys/include/tiny_strerror.h
- sys/tiny_strerror/tiny_strerror.c
`tiny_strerror` is still quite heavy (1200 bytes on Cortex-M4), so add a more minimal version that only prints the error code.
This allows to use the same code and have pretty error messages if ROM is ample, but still have the option to strip it down easily.
> sys/tiny_strerror: add tiny_strerror_minimal

- examples/gcoap/Makefile
- examples/gcoap/client.c
- examples/gcoap_dtls/Makefile
- sys/Makefile.include
- sys/include/net/ipv4/addr.h
- sys/net/application_layer/gcoap/Makefile.include
- sys/net/application_layer/gcoap/gcoap.c
Add IPv4 support to `examples/gcoap`and `examples/gcoap_dtls`.
Dual stack mode using IPv4 and IPv6 would require some changes on the gcoap API, therefore compilation stops with an error right now.
Use the example applications to connect by IPv4 instead of IPv6 by compiling with `LWIP_IPV4=1`
Dependencies:
- #17765
- #17766
- #17764
> examples/gcoap: add IPv4 support

- tests/congure_abe/tests/01-run.py
Fixes synchronization issues on stdio_uart. Copied from the setup function in tests/congure_reno/tests/01-run.py.
See https://github.com/RIOT-OS/RIOT/pull/15968#issuecomment-1283456600 ff.
`CI: run tests` should pass on both Murdocks.
Follow-up fix on https://github.com/RIOT-OS/RIOT/pull/15968
> tests/congure_abe: reset node before starting terminal

- examples/sniffer/Makefile
- tests/gcoap_fileserver/Makefile
- tests/nimble_esp_wifi_coexist/Makefile
PR #18355 adds submodules for dedicated commands. However, there are few examples and tests, which still used deprecated modules:
- examples/sniffer
- tests/gcoap_fileserver
- tests/nimble_esp_wifi_coexist
This PR changes configuration to use new submodules for dedicated commands.
Without this PR during compilation makefile prints some warnings, respectively for listed programs:
```
Deprecated modules are in use: shell_commands
Deprecated modules are in use: md5sum shell_commands
Deprecated modules are in use: gnrc_udp_cmd shell_commands
```
With this  PR this warnings are not presented. I tested first two programs with `native`  board, and PR works. The last one uses `xtensa-esp32-elf-gcc` - tests are needed.
PR #18355
> sys/shell: fix deprecated shell_command in examples and tests

- sys/include/net/nanocoap.h
- sys/net/application_layer/nanocoap/nanocoap.c
- tests/unittests/tests-nanocoap/tests-nanocoap.c
Working with content negotiation in the context of gcoap/nanocoap, I noticed that it would be handy to be able to access the Accept option of a request more easily. Therefore, this PR adds a new helper function `coap_get_accept` that gets the respective option value from a CoAP packet. It reuses most of the code from the existing `coap_get_content_type` helper, moving its logic to a new internal function that is called by both `coap_get_content_type` and `coap_get_accept`.
I adjusted the existing unit tests to assert that new the helper works.
—
> sys/net/nanocoap: introduce Accept option helper

- makefiles/tests/tests.inc.mk
I sometimes find it more convenient to use `pytest` to execute and debug my more complex tests (it shows output in order of test execution, in color, you can filter tests and has flags to step in with `pdb`, ...). However, for that I either need to define all the RIOT environment in my shell, or touch `makefile/tests/tests.mk` to execute the test with `pytest`. Since I do not want to enforce `pytest` on everyone and the CI, this amends that file with two optional macros `TEST_EXECUTOR` and `TEST_EXECUTOR_FLAGS`, so the executor for the tests can be selected from the environment.
Sadly, not all tests are able to be run this way: when the `test...` function has an argument, `pytest` thinks that argument is a fixture and gets confused (another reason why I made `pytest` optional). However, …
> build-system: add capability to execute scripts with custom executor

- cpu/efm32/periph/pm.c
This PR enable users to block `EFM32_PM_MODE_EM1` if required.
Programming `tests/periph_pm` to an EFM32-based board:
```
2022-10-19 17:56:56,151 # main(): This is RIOT! (Version: 2023.01-devel-93-g345af-feature/efm32-series2)
2022-10-19 17:56:56,157 # This application allows you to test the CPU power management.
2022-10-19 17:56:56,214 # The available power modes are 0 - 2. Lower-numbered power modes
2022-10-19 17:56:56,217 # save more power, but may require an event/interrupt to wake up
2022-10-19 17:56:56,218 # the CPU. Reset the CPU if needed.
2022-10-19 17:56:56,218 # mode 0 blockers: 0 
2022-10-19 17:56:56,218 # mode 1 blockers: 1 
2022-10-19 17:56:56,218 # mode 2 blockers: 0 
2022-10-19 17:56:56,219 # Lowest allowed mode: 2
2022-10-19 17:56:56,219 # [pm] enter EFM32_PM_MODE_EM1
> …
```
> cpu/efm32/pm: fix blocking EM1

- drivers/sdcard_spi/sdcard_spi.c
Use `crc16_ccitt` instead of `ucrc16`.
This can be speed up by using a look-up table if desired and does not use more memory in the default configuration.
In fact, it saves some bytes compared to the generic CRC implementation:
```
text	   data	    bss	    dec	    hex	
62808	    892	  43688	 107388	  1a37c	
```
```
text	   data	    bss	    dec	    hex	
62744	    892	  43688	 107324	  1a33c	
```
SD card still works:
```
2022-10-20 00:42:07,483 # main(): This is RIOT! (Version: 2023.01-devel-92-g10296)
> ls /sd0
2022-10-20 00:42:12,533 # test/
2022-10-20 00:42:12,534 # hello.txt	19 B
2022-10-20 00:42:12,536 # total 1 files
> vfs r /sd0/hello.txt
2022-10-20 00:45:13,936 # 00000000: 4865 6c6c 6f20 6672 6f6d 204c 696e 7578  Hello from Linux
```
> drivers/sdcard_spi: make use of crc16_ccitt_false_update()

- dist/tools/pyterm/pyterm
pyterm uses a (now) deprecated method `threading.setDaemon()`
```
receiver_thread = threading.Thread(target=self.reader)
receiver_thread.setDaemon(1)
receiver_thread.start()
```
With Python 3.10 the `setDaemon` method is deprecated. You get a warning each time `pyterm` is used.
To avoid the warning we should set the property `daemon` instead.
```
receiver_thread.daemon = True
```
I've checked this syntax with 3.6 and it is supported at least since that version.
> dist/tools/pyterm: avoid deprecated .setDaemon

- cpu/native/socket_zep/socket_zep.c
Use `crc16_ccitt` instead of `ucrc16` as it is faster and smaller than the generic CRC16 implementation.
ZEP can still communicate with an unmodified instance.
```
Iface  7  HWaddr: 50:3C  Channel: 26  NID: 0x23  PHY: O-QPSK 
Long HWaddr: E6:DF:AB:47:75:1A:50:3C 
State: IDLE 
ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
RTR_ADV  6LO  IPHC  
inet6 addr: fe80::e4df:ab47:751a:503c  scope: link  VAL
inet6 addr: 2001:db8::e4df:ab47:751a:503c  scope: global  VAL
inet6 group: ff02::1:ff1a:503c
inet6 group: ff02::1a
Statistics for Layer 2
RX packets 3  bytes 222
TX packets 3 (Multicast: 2)  bytes 0
TX succeeded 3 errors 0
Statistics for IPv6
RX packets 2  bytes 224
TX packets 3 (Multicast: 2)  bytes 210
TX …
```
> socket_zep: make use of crc16_ccitt_false_update()

- boards/stm32f746g-disco/Kconfig
- boards/stm32f746g-disco/features-shared.mk
- boards/stm32f7508-dk/Kconfig
- cpu/stm32/include/tinyusb_hw_defaults.h
- pkg/tinyusb/contrib/include/tinyusb_config.h
- pkg/tinyusb/hw/hw_stm32.c
This PR provides the support of external ULPI and internal UTMI+ HS PHYs for STM32 USB OTG HS ports. The support of these HS PHYs allows the use of the tinyUSB package also for STM32 USB OTG HS ports. The HS PHY is used by enabling either the `periph_usbdev_ulpi_hs` pseudomodule or the `periph_usbdev_ulpi_hs` pseudomodule for boards that have an USB OTG FS as well as an USB OTG  HS port and provide the corresponding feature.
The PR also enables the tinyUSB feature for boards with USB OTG HS ports.
1. Use a board with an USB OTG FS port and an USB OTG HS port with external ULPI HS PHY, for example: 
```
USEMODULE=periph_usbdev_ulpi_hs BOARD=stm32f746g-disco make -j8 -C tests/pkg_tinyusb_cdc_msc/
```
With the `periph_usbdev_ulpi_hs` module, the test should work for the USB OTG HS port. …
> pkg/tinyusb: add ULPI and UTMI+ HS PHY support for STM32 USB OTG HS ports

- makefiles/tools/gdb.inc.mk
In an ideal world everyone would just install `gdb-multiarch` and be happy. However, some MCUs need magic GDB versions sprinkled with unicorn-stardust-Espressif-patches...
Since there is little reason to have `$(target)-gdb` installed in addition to `gdb-multiarch` if `gdb-multiarch` would work fine, let's assume the user wants to use `$(target)-gdb` when present over `gdb-multiarch`.
```
USEMODULE=esp_jtag make BOARD=esp32-ethernet-kit-v1_2 PROGRAMMER=openocd OPENOCD=openocd-esp32 debug -C examples/default
```
In `master`:
```
/home/maribu/Repos/software/RIOT/dist/tools/openocd/openocd.sh debug /home/maribu/Repos/software/RIOT/examples/default/bin/esp32-ethernet-kit-v1_2/default.elf
Open On-Chip Debugger v0.11.0-snapshot (2022-10-21-10:40) …
```
> makefiles/tools/gdb.inc.mk: prefer $(target)-gdb over gdb-multiarch

- sys/stdio_uart/Makefile
- sys/stdio_uart/stdio_uart.c
As the title says and slso drop the `-Wno-cast-function-type` hack that allowed the bug to sneak past Murdock.
Ideally the compiler notices that the wrapper is not needed for platforms where the calling conventions of the two signatures are indeed compatible and the machine code doesn't change. I didn't test this, though.
In any case, `examples/default` should still work on boards that use UART for stdio.
https://github.com/RIOT-OS/RIOT/issues/18766
> sys/stdio_uart: fix undefined behavior

- pkg/arduino_sdi_12/Makefile
- pkg/arduino_sdi_12/patches/0001-Use-RIOT-s-gpio-to-handle-pin-change-interrupts.patch
- pkg/arduino_sdi_12/patches/0002-Integration-with-RIOT-to-support-other-boards.patch
- pkg/arduino_sdi_12/patches/0003-RIOT-Fix-for-SAMD-boards.patch
Mostly doc changes since the last commit hash, patches now apply without the 3-way merge.
> pkg/arduino_sdi_12: bump version, fix patches

- sys/include/net/coap.h
This PR expands the `coap.h` header file with macro definitions for the Size2 and Size1 option numbers, making it a bit more convenient to use these two options. The PR does not contain any actual new logic, but it could be a first step for reviving https://github.com/RIOT-OS/RIOT/issues/10169 and augmenting either nanocoap or gcoap.
Since there is no new logic introduced, comparing the numbers with the [IANA registry](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml) and proofreading the documentation should suffice for this PR.
—
> sys/net: add Size1 and Size2 option numbers

- boards/lora-e5-dev/Kconfig
- boards/lora-e5-dev/Makefile.features
- boards/lora-e5-dev/include/arduino_board.h
- boards/lora-e5-dev/include/arduino_pinmap.h
Adds the arduino feature to the `lora-e5-dev` board.
The board is not compatible with Arduino shields. The pin definition comes from the LoRa-E5 datasheet, see https://files.seeedstudio.com/products/317990687/res/LoRa-E5%20module%20datasheet_V1.0.pdf page 6.
I've tested the following programs:
- examples/arduino_hello-world
- tests/periph_gpio_arduino
- tests/sys_arduino
- tests/sys_arduino_lib
None.
> boards/lora-e5-dev: add arduino feature

- boards/nrf52840-mdk/Kconfig
- boards/nrf52840-mdk/Makefile.features
- boards/nrf52840dk/Kconfig
- boards/nrf52840dk/Makefile.features
- boards/reel/Kconfig
- boards/reel/Makefile.features
- boards/waveshare-nrf52840-eval-kit/Kconfig
- boards/waveshare-nrf52840-eval-kit/Makefile.features
- pkg/tinyusb/Kconfig
- pkg/tinyusb/Makefile
- pkg/tinyusb/Makefile.dep
- pkg/tinyusb/Makefile.include
- pkg/tinyusb/Makefile.nrf52
- pkg/tinyusb/hw/hw_nrf52.c
- pkg/tinyusb/hw/include/nrf52/nrf_clock.h
This PR adds nRF52xxx support for tinyUSB package. The tinyUSB support is only enabled by the `tinyusb_feature` for boards that have a separate USB OTG port which is not used for `stdio_cdc_acm`.
Use one of the boards for which the `tinyusb_device` feature is enabled by this PR and use `tests/pkg_tinyusb_cdc_msc` to test it, for example:
```
BOARD=waveshare-nrf52840-eval-kit make -j8 -C tests/pkg_tinyusb_cdc_msc flash term
```
The node should be mounted as storage device to the host.
> pkg/tinyusb: add nrf52 support

- sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c
In situations with high packet loss, if all sync packets are lost, conflicting subnets will be configured.
If the network is static, this can be prevented by always using the highest number of subnets that has been observed.
This assumes no nodes are physically added / removed from the network. This is typically given in a wired sensor network.
Add 
CFLAGS += -DCONFIG_GNRC_IPV6_AUTO_SUBNETS_STATIC=1
to the `Makefile` of `examples/gnrc_networking_subnets`.
Configure a topology with multiple routers on the same subnet. Now even if you remove a router, the subnet assignments should not change.
> gnrc/ipv6_auto_subnets: add CONFIG_GNRC_IPV6_AUTO_SUBNETS_STATIC option

- drivers/atwinc15x0/atwinc15x0_netdev.c
Globally disabling interrupts is *very bad* if done for an extended period of times.
Here `atwinc15x0` would disable interrupts for up to 55µs which leads to lost bytes when used with UART based interfaces like SLIP or DOSE. 
When looking at the code it's not clear why the interrupts were disabled in the first place. Only the `atwinc15x0` thread itself will interact with the data, even if there is a GPIO interrupt from the module it will only call `netdev_trigger_event_isr()` which adds an entry to the event queue to be processed by the `atwinc15x0` thread.
I ran `examples/gnrc_networking` with
```
2022-10-25 14:51:26,075 # ping -c 10 -i 100 riot-os.org
2022-10-25 14:51:26,246 # 12 bytes from 2001:67c:254:b0b0::1: icmp_seq=0 ttl=60 time=156.320 ms
2022-10-25 14:51:26,257 # 12 bytes from …
```
> drivers/atwinc15x0: don't disable interrupts

- sys/clif/clif.c
- sys/include/clif.h
- tests/unittests/tests-clif/tests-clif.c
Hi 😈
This fixes a potential out of bounds read in `clif_encode_link`. There is no code in RIOT that can be exploited & and the close by `memcpy` only operates within a safe/length checked buffer.
The fix does not break the current API.
I also added a new test which also acts as an example on how to use clif. 
Run `make -C tests/unittests tests-clif` and `make -C tests/unittests term` to test the fix.
Side note: I did not run uncrustify as this would have filled this PR with a lot of unrelated changes. Somebody should open a separate PR for those cosmetic changes.
cc @leandrolanzieri
> sys/clif: Fixing out of bounds read under certain conditions

- README.md
Give the features section an update.
The native port for macOS doesn't work on any recent version of macOS, FreeBSD port isn't maintained either - better not advertise it.
Claiming to be a micro-kernel is very misleading (and gives a bad look IMO):
- we have a unified address space and many APIs assume this to be the case
- there is no privilege separation, no system calls - just normal function calls
- having threads doesn't make us a microkernel
> README.md: update features

- cpu/stm32/include/periph/cpu_dma.h
- cpu/stm32/periph/dma.c
This fixes some bugs I found in the STM32 DMA module. See commit messages for further details.
Perhaps a better fix would have been to add a second parameter to the `dma_conf_t` struct to separately define the DMA controller and stream/channel. This would be similar to the how the ADC module handles the ADC and channel number for ADC lines. Should I have done this instead of fixing the current way of mapping DMA stream 0-7 to DMA controller 1, and streams 8 and beyond to controller 2?
On any STM32 based board:
1. initiate a DMA transfer with width not equal to one byte and auto indexing enabled on the destination buffer
1. call `dma_suspend` followed `dma_resume` after some time
1. observe that after the DMA transfer is complete, the write will underflow the destination buffer
1. initiate …
> cpu/stm32: fix periph_dma

- boards/blackpill-128kib/Kconfig
- boards/bluepill-128kib/Kconfig
- sys/ztimer/Kconfig
Nightlies are failing due to kconfig mismatch.
It would seem this is a result of bringing in the USB stuff. I assume that this uses ztimer periph_timer as a backend as periph_timer is already selected. However, kconfig only resolves one and not recursively making it hard to match. For not a hack is added to override for these boards.
Fixed in murdock with NIGHTLY=1
> Fix kconfig mismatch breaking nightlies

- examples/gnrc_networking/Makefile.ci
- sys/include/net/gnrc/udp.h
I don't remember the stack for UDP ever being fuller than half full. So let's use half the stack size.
Sending UDP packets should still work without crashes on all supported boards.
Taken out of #18700 to discuss separately.
> gnrc_udp: use small stack-size

- boards/cc1350-launchpad/doc.txt
This PR adds to TI CC1350 Launchpad board documentation section concerning accessing RIOT shell.
The description is provided according to the Issue [#17453](https://github.com/RIOT-OS/RIOT/issues/17453).
```
make doc
xdg-open doc/doxygen/html/group__boards__cc1350__launchpad.html
```
See also #17453
> boards/cc1350: add info concerning shell access

- boards/cc1312-launchpad/doc.txt
- boards/cc1350-launchpad/doc.txt
- boards/cc1352-launchpad/doc.txt
- boards/cc1352p-launchpad/doc.txt
- boards/cc2650-launchpad/doc.txt
- cpu/cc26xx_cc13xx/doc.txt
Currently used by CI doxygen version, which generates public documentation for RIOT OS webpage, do not handle HTML tags in headings. In effect, documentation for TI boards shows some "strange" HTML tags in heading [example for cc1315](https://doc.riot-os.org/group__boards__cc1312__launchpad.html).
This PR removes all HTML tags from headings as well as TOC with HTML links. Changes could be `git revert`-ed when doxygen version in the CI will be changed.
See current version of the doc in RIOT OS webpage - [example for cc1315](https://doc.riot-os.org/group__boards__cc1312__launchpad.html).
And doc generated by this PR.
```
make doc
xdg-open doc/doxygen/html/group__boards__cc1312__launchpad.html
```
none
> boards/cc13xx_cc26xx: remove broken HTML links and headings in doc

- dist/tools/nrf52_resetpin_cfg/Makefile
Set "RESET_PIN" to 21 if the selected board is "dwm1001".
The data sheet linked below confirms that this is the cannonical reset pin. 
[DWM1001C Data Sheet](https://www.qorvo.com/products/d/da007950)
*Section 3: DWM1001 Pin Connections, page 9*
> dist/tools: add "RESET_PIN" value for the dwm1001

- sys/clif/clif.c
- sys/include/clif.h
- tests/unittests/tests-clif/tests-clif.c
Hi 😈
This fixes a potential out of bounds read in `clif_encode_link`. There is no code in RIOT that can be exploited & and the close by `memcpy` only operates within a safe/length checked buffer.
The fix does not break the current API.
I also added a new test which also acts as an example on how to use clif. 
Run `make -C tests/unittests tests-clif` and `make -C tests/unittests term` to test the fix.
Side note: I did not run uncrustify as this would have filled this PR with a lot of unrelated changes. Somebody should open a separate PR for those cosmetic changes.
cc @leandrolanzieri
> sys/clif: Fixing out of bounds read under certain conditions [backport 2022.10]

- sys/net/gnrc/netif/ieee802154/gnrc_netif_ieee802154.c
- sys/net/gnrc/network_layer/sixlowpan/frag/rb/gnrc_sixlowpan_frag_rb.c
- sys/net/gnrc/network_layer/sixlowpan/frag/vrb/gnrc_sixlowpan_frag_vrb.c
- sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c
- sys/net/link_layer/ieee802154/ieee802154.c
- tests/unittests/tests-ieee802154/tests-ieee802154.c
Title says everything
Fragmentation and header compression (e.g. as outlined in Release Specs 4 and 6) should still work.
> gnrc_sixlowpan: Various hardening fixes

- sys/net/gnrc/netif/ieee802154/gnrc_netif_ieee802154.c
- sys/net/gnrc/network_layer/sixlowpan/frag/rb/gnrc_sixlowpan_frag_rb.c
- sys/net/gnrc/network_layer/sixlowpan/frag/vrb/gnrc_sixlowpan_frag_vrb.c
- sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c
- sys/net/link_layer/ieee802154/ieee802154.c
- tests/unittests/tests-ieee802154/tests-ieee802154.c
Title says everything
Fragmentation and header compression (e.g. as outlined in Release Specs 4 and 6) should still work.
> gnrc_sixlowpan: Various hardening fixes [backport 2022.10]

- boards/dwm1001/Kconfig
- boards/dwm1001/Makefile.dep
- boards/dwm1001/include/gpio_params.h
Add saul support for the dwm1001-dev's LEDs and "USER" button.
The pin macros were already present for this board, all that remained was to add the `gpio_params.h` header and include the `saul_gpio` pseudomodule in the board's `Makefile.dep`.
- LED0 - Green
- LED1 - Red
- LED2 - Red
- LED3 - Blue
- Button 1 - Labelled as "USER"
| <img src="https://user-images.githubusercontent.com/30503300/198588724-356e6b44-58a6-4fbb-ae38-939da2ec3f51.jpg"> |  <img src="https://user-images.githubusercontent.com/30503300/198588735-5828e155-2539-4e37-b7cb-095578fe0fde.jpg"> |
| ----- | ----- |
| dwm1001 front | blurry leds - the bokeh actually helps with seeing each LED color |
Below is the terminal output where each LED has been toggled by shell command, and a before/after of pressing the "USER" button. …
> boards/dwm1001: add saul_gpio support

- drivers/ethos/ethos.c
The ethernet over serial driver `_recv` function checks the buffer size after writing the data.
To fix this I moved the bounds check before the function writing to the buffer.
> drivers/ethos: Fix off-by-one bug

- cpu/saml21/include/periph_cpu.h
- cpu/saml21/periph/pm.c
- sys/pm_layered/pm.c
This PR allow to block the IDLE mode on the `saml21` cpu.
Programming `tests/periph_pm` to a saml21-based board:
```
make -C tests/periph_pm BOARD=samr30-xpro flash term
2022-10-31 22:24:23,596 # main(): This is RIOT! (Version: 2023.01-devel-216-g4b802-fix/saml21-pm-modes)
2022-10-31 22:24:23,601 # This application allows you to test the CPU power management.
2022-10-31 22:24:23,607 # The available power modes are 0 - 2. Lower-numbered power modes
2022-10-31 22:24:23,612 # save more power, but may require an event/interrupt to wake up
2022-10-31 22:24:23,615 # the CPU. Reset the CPU if needed.
2022-10-31 22:24:23,617 # mode 0 blockers: 1 
2022-10-31 22:24:23,619 # mode 1 blockers: 1 
2022-10-31 22:24:23,621 # mode 2 blockers: 0 
2022-10-31 22:24:23,623 # Lowest allowed mode: 2
2022-10-31 …
```
> cpu/saml21/pm: allow blocking IDLE mode

- drivers/slipdev/slipdev.c
This fixes the off-by-one error in SLIP the same way as it was fixed in ethos.
Previously I tried to make SLIP use the chunked ringbuffer to handle this with common code or clean up the driver while fixing the bug, but neither reached consensus.
So this minimal solution should fix the bug while not touching the driver otherwise.
alternative to #18229, #18066
same as #18823
> drivers/slipdev: fix off-by-one error in _recv()

- tests/thread_msg_bus/main.c
- tests/thread_msg_bus/tests/01-run.py
I got a bit confused if mixing bus messages with non-bus messages works, but that is indeed already covered…
So let's extend the test so this is also exercised / demonstrated.
> tests/thread_msg_bus: enhance test with non-bus message

- drivers/slipdev/slipdev.c
This fixes the off-by-one error in SLIP the same way as it was fixed in ethos.
Previously I tried to make SLIP use the chunked ringbuffer to handle this with common code or clean up the driver while fixing the bug, but neither reached consensus.
So this minimal solution should fix the bug while not touching the driver otherwise.
alternative to #18229, #18066
same as #18823
> drivers/slipdev: fix off-by-one error in _recv() [backport 2022.10]

- drivers/ethos/ethos.c
The ethernet over serial driver `_recv` function checks the buffer size after writing the data.
To fix this I moved the bounds check before the function writing to the buffer.
> drivers/ethos: Fix off-by-one bug [backport 2022.10]

- boards/xg23-pk6068a/Kconfig
- boards/xg23-pk6068a/Makefile.dep
- boards/xg23-pk6068a/include/board.h
- sys/include/ztimer/config.h
- sys/ztimer/Kconfig
- sys/ztimer/Makefile.dep
While working on #18760, I realized that #17654 hasn't modeled the module `ztimer_periph_lptimer`.
This PR tries to fix that. For that I added the feature `HAS_ZTIMER_PERIPH_LPTIMER_CONFIG` which should be selected by boards that has the required configuration for `ztimer_periph_lptimer`.
```diff
diff --git a/tests/ztimer_msg/Makefile b/tests/ztimer_msg/Makefile
index 247bbc2030..0d53a02304 100644
--- a/tests/ztimer_msg/Makefile
+++ b/tests/ztimer_msg/Makefile
@@ -1,6 +1,6 @@
include ../Makefile.tests_common
-USEMODULE += ztimer_usec
+USEMODULE += ztimer_msec
#USEMODULE += ztimer_msec
diff --git a/tests/ztimer_msg/app.config.test b/tests/ztimer_msg/app.config.test
index 2fc4266478..1857316235 100644
--- a/tests/ztimer_msg/app.config.test
+++ b/tests/ztimer_msg/app.config.test
@@ -1,4 +1,4 …
```
> sys/ztimer: model ztimer_periph_lptimer for Kconfig

- pkg/tinyusb/doc.txt
Users who find tinyusb in the documentation might be misled into thinking that this is what backs the USB features advertised around RIOT, or think that one of the stacks can use the other. This adds text to the docs to say that they are distinct and incompatible.
* Look at text: Is it correct?
* Look at rendered documentation to see whether it looks nice.
> pkg/tinyusb: Note distinction from USBUS

- core/lib/include/xfa.h
This PR is a very small fix of the documentation of parameters in `core/lib/include/xfa.h`. I guess this was just a copy&paste bug.
Green CI and correct documentation of the `XFA_{INIT|USE}*` macros in https://doc.riot-os.org/xfa_8h.html.
> core/lib/xfa: fix parameter documentation

- sys/net/application_layer/nanocoap/sock.c
If a NON confirmable message is sent with a callback function, not receiving a response in time would lead to a retransmission.
This is of course an error, as only CON messages are to be retransmitted.
> nanocoap_sock: only re-transmit CON messages

- sys/pm_layered/pm.c
@jue89 is doing good work adding pm_layerd where its needed, this PR shall optimize pm_block and unblock
this moves the assert into the  irq guard guard which will spare us the extra load that is need for it (irq disable invalidate memory to ensure there is not reordering)
read 
compile 
do speed tests 
read assembly
I do not have a slow arm at hand -> i read the assembly for 
old:
```
00000000 <pm_block>:
0:	b508      	push	{r3, lr}
2:	4b07      	ldr	r3, [pc, #28]	; (20 <pm_block+0x20>)
4:	5c1a      	ldrb	r2, [r3, r0]
6:	2aff      	cmp	r2, #255	; 0xff
8:	d101      	bne.n	e <pm_block+0xe>
a:	f7ff fffe 	bl	0 <_assert_panic>
e:	f3ef 8110 	mrs	r1, PRIMASK
12:	b672      	cpsid	i
14:	5c1a      	ldrb	r2, [r3, r0]
16:	3201      	adds	r2, #1
18:	541a      	strb	r2, [r3, r0]
1a:	f381 8810 	msr …
```
> sys/pm_layered: move (un)block assert for minor speedup

- boards/nucleo-f207zg/Kconfig
- boards/nucleo-f207zg/Makefile.features
- boards/nucleo-f207zg/include/periph_conf.h
- cpu/stm32/include/periph/f2/periph_cpu.h
This PR adds to the Nucleo-f207zg ADC configuration.
None
> boards/nucleo-f207zg:  support for ADC

- examples/emcute_mqttsn/README.md
- examples/gnrc_border_router/README.md
Removed references to macOS from two README.md as supporting macOS (native & networking) is no longer in scope for RIOT.
@miri64  I'm assuming the future you were talking about is not going to happen? 😉
> examples: Remove macOS references in README

- sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c
While investigating #18851 I discovered an issue when compiling the gnrc_networking example using LLVM. 
It fails since there is an unused function:
```
sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c:140:24: error: unused function '_nib_abr_entry_valid_offset' [-Werror,-Wunused-function]
static inline uint16_t _nib_abr_entry_valid_offset(const _nib_abr_entry_t *abr)
```
The fix works by only including this function when it is needed. In this case, when the `CONFIG_GNRC_IPV6_NIB_MULTIHOP_P6C` option is set. 
I'm currently limited to macOS and couldn't test further than "it compiles". 
Help? 🥺
cc @miri64 👀
> gnrc: Fix unused function error when using LLVM

- makefiles/cflags.inc.mk
- makefiles/libc/newlib.mk
- makefiles/libc/picolibc.mk
- makefiles/cflags.inc.mk: add `-z noexecstack` to link flags
- GCC on some platforms does need an executable stack to generate trampoline code, but use of nested functions is not allowed in RIOT's code base anyway.
- makefiles/libc: fix wchar_t size warnings on LLVM
- The test for the requirement of disabling wchar_t size warnings assumed that `$(CC)` is used for linking, instead of `$(LINK)`. With GCC `$(LINK)` and `$(CC)` happen to be (in most cases) identical, but with LLVM they are not. This results in issues with compiling with LLVM.
No change in binaries and everything should still compile.
Inspired by https://github.com/RIOT-OS/RIOT/pull/18844
> build system: fix compilation with LLVM

- cpu/sam0_common/periph/gpio.c
- cpu/sam0_common/periph/rtc_rtt.c
- cpu/sam0_common/periph/spi.c
- cpu/sam0_common/periph/timer.c
- cpu/sam0_common/periph/uart.c
- cpu/sam0_common/periph/usbdev.c
- cpu/samd21/include/periph_cpu.h
- cpu/saml21/include/periph_cpu.h
Currently, RIOT just runs with by-default blocked power modes. This PR changes this for the saml21 family: All peripheral drivers now block and unblock pm modes depending on whether they are used or nor. In combination with #17607 this will get us near to *seamless power management*
Current state of this PR:
Affected boards (using `saml21`):
- bastwan
- saml21-xpro
- samr30-xpro
- samr34-xpro
- yarm
Flash `test/periph_timer` on a `saml21` board:
<details>
```
make -C tests/periph_timer BOARD=samr30-xpro flash term
2022-10-31 22:43:18,356 # Help: Press s to start test, r to print it is ready
s
2022-10-31 22:43:20,390 # START
2022-10-31 22:43:20,397 # main(): This is RIOT! (Version: 2023.01-devel-225-gd564e-feature/saml21_pheriph_pm)
2022-10-31 22:43:20,397 # 
2022-10-31 22:43:20,399 # Test …
```
> cpu/saml21: add interaction with pm_layered for peripheral drivers

- sys/bitfield/bitfield.c
- sys/include/bitfield.h
- tests/unittests/tests-bitfield/tests-bitfield.c
I noticed that I needed these functions independent from #17045 and just as I was about to re-implement them, stale bot reminded me that I already did so a year ago.
So let's try to salvage them from that PR.
Unittests are provided an can be build with
make -C tests/unittests tests-bitfield
split from #17045
> sys/bitfield: add bf_find_first_{set, unset}()

- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/sock.c
- sys/net/application_layer/nanocoap/vfs.c
- tests/nanocoap_cli/nanocli_client.c
I previously thought it would be convenient to store the socket struct inside `coap_block_request_t`. 
This turned out to inhibit flexibility if the socket is to be used outside the blockwise request.
Worse even, in `nanocoap_vfs_put()` it would be copied (which turned out to not be safe for listening sockets).
So get rid of the misguided `nanocoap_block_request_init()` function - it never used in tree and was only added for 'API symmetry'.
Instead add a `sock` parameter to `nanocoap_block_request_init_url()` and since the user is now aware that they have a socket at their hands, just let them call `nanocoap_sock_close()` instead of providing an otherwise useless `nanocoap_block_request_done()` wrapper.
`tests/gcoap_fileserver` will ensure that block-wise PUT and GET do still work (via …
> nanocoap_sock: don't store entire sock in coap_block_request_t

- sys/include/pm_layered.h
- sys/pm_layered/pm.c
pm_(un)block add attribute optimize(3) - shortens hotpath by moving the jump to panic behind return
pm_get_blocker `=` instead of memcpy to ease readability
this PR aligns pm_blocker_t that enables the compiler to use word loads instead of byte loads with 
cortexm0: whole struct access (pm_get_blocker and pm_set_lowest used memcpy or bytewise access to read pm_blocker) with this it is ldr (word) and some register operations
read 
#17607 started the journey
#18821 opened the rabbit hole 
#18842
> sys/pm_layered: align pm_blocker_t for speed

- boards/dwm1001/Kconfig
- boards/dwm1001/Makefile.dep
Use the i2c version of the lis2df12 driver instead of the spi one for the dwm1001.
When including saul, I get the following error:
```
[auto_init_saul] error initializing lis2dh12 #0
```
As I understand it, the lis2df12 is capable of both i2c and spi communication, however I believe with the dwm1001, it is only connected by i2c. 
|<img src="https://user-images.githubusercontent.com/30503300/200798135-77778835-1527-48dc-a5c1-fae8cd96c394.png" width=50%>|
|-----|
| *Page 7, 2. DWM1001 MODULE* - [DWM data sheet](https://www.qorvo.com/products/d/da007952) |
When switching to the i2c implementation, the error disappears, and the previously un-detected sensors now show up (`6` and `7`):
```
> saul
saul
ID      Class           Name
#0      ACT_SWITCH      LED0 (Green)
#1      ACT_SWITCH …
```
> boards/dwm1001: use lis2dh12_i2c instead of lis2dh12_spi

- pkg/utensor/patches/0004-core-tensor.cpp-fix-uninitialized-variable.patch
This fixes compilation with modern GCC. (And likely runtime issues...)
`tests/pkg_utensor` should still pass.
None
> pkg/utensor: fix uninitialized variable

- dist/tools/flatc/patches/0001-CMakeLists.txt-fix-compilation-on-musl.patch
flatc uses `strto<foo>_l()` over `strto<foo>()` when available, so that they behave reproducible. The musl libc has no locale support, which has the added benefit of reproducible behavior being the default.
For some reason a `strtof_l()` compatibility wrapper was added in musl, but the other `strto<foo>_l()` wrappers are missing. This adds a patch to check for `strtoull_l()` instead of `strtof_l()`. This will not make a difference on a libc that supports all of them, but fixes compilation on musl.
`tests/pkg_flatbuffers` should still build and pass. (In fact, no changes in the binary in both the `flatc` host utility and the `tests/pkg_flatbuffers` test application are expected.)
None
> dist/tools/flatc: Fix compilation on musl

- dist/tools/backport_pr/backport_pr.py
Add `search_parent_directories=True` to `git.Repo()` so that `backport_pr.py` can be called anywhere within the RIOT git repo without manually passing the repo root path via `--gitdir`.
Previously the tool had to be called from the RIOT base repo.
The script should no longer throw
```
$ ./backport_pr.py --comment <num>
[...]
File "/home/maribu/Repos/software/RIOT/dist/tools/backport_pr/./backport_pr.py", line 314, in <module>
main()
File "/home/maribu/Repos/software/RIOT/dist/tools/backport_pr/./backport_pr.py", line 227, in main
repo = git.Repo(args.gitdir)
File "/usr/lib/python3.10/site-packages/git/repo/base.py", line 224, in __init__
self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
File …
```
> tools/backport_pr.py: improve usability

- dist/tools/flatc/patches/0001-CMakeLists.txt-fix-compilation-on-musl.patch
flatc uses `strto<foo>_l()` over `strto<foo>()` when available, so that they behave reproducible. The musl libc has no locale support, which has the added benefit of reproducible behavior being the default.
For some reason a `strtof_l()` compatibility wrapper was added in musl, but the other `strto<foo>_l()` wrappers are missing. This adds a patch to check for `strtoull_l()` instead of `strtof_l()`. This will not make a difference on a libc that supports all of them, but fixes compilation on musl.
`tests/pkg_flatbuffers` should still build and pass. (In fact, no changes in the binary in both the `flatc` host utility and the `tests/pkg_flatbuffers` test application are expected.)
None
> dist/tools/flatc: Fix compilation on musl [backport 2022.10]

- examples/wasm/wasm_sample/Makefile
Apparently the order of the flags now became significant. This fixes:
wasm-ld: error: entry symbol not defined (pass --no-entry to suppress)
This fixes https://github.com/maribu/riot-test-results/blob/main/2022.10-branch-bf7e4f6ca8096de94c7f2274d4406de7263e9493/samr21-xpro/examples/wasm/compilation.failed
None
> examples/wasm/wasm_sample: fix linking with new wasm-ld

- pkg/utensor/patches/0004-core-tensor.cpp-fix-uninitialized-variable.patch
This fixes compilation with modern GCC. (And likely runtime issues...)
`tests/pkg_utensor` should still pass.
None
> pkg/utensor: fix uninitialized variable [backport 2022.10]

- tests/mpu_stack_guard/main.c
The `mpu_stack_guard` test intentionally overflows the stack with a stupid infinite recursion. Newer versions of GCC started to dislike this, so this disables the corresponding diagnostics to get the intentional stack overflow still compiled.
The test application should now compile on both older toolchains (e.g. the one used by Murdock) and modern toolchains (e.g. the one provided by Arch Linux or Alpine).
None
> tests/mpu_stack_guard: Fix compilation on modern GCC (>= 12.x)

- tests/mpu_stack_guard/main.c
The `mpu_stack_guard` test intentionally overflows the stack with a stupid infinite recursion. Newer versions of GCC started to dislike this, so this disables the corresponding diagnostics to get the intentional stack overflow still compiled.
The test application should now compile on both older toolchains (e.g. the one used by Murdock) and modern toolchains (e.g. the one provided by Arch Linux or Alpine).
None
> tests/mpu_stack_guard: Fix compilation on modern GCC (>= 12.x) [backport 2022.10]

- sys/usb/usbus/hid/hid_io.c
This PR fixes a potential buffer overflow inside `usb_hid_io_write` which occurs when `len > CONFIG_USBUS_HID_INTERRUPT_EP_SIZE`.
> usbus/hid: fix buffer overflow in hid_io

- dist/tools/uncrustify/uncrustify.sh
we treat uncrustify comment like warnings (failed uncrustify does not fail static tests) -> we should display them as that.
read
> utils/uncrustify: display warning instead of error

- sys/include/net/gnrc/pkt.h
The previous implementation used creative construct for impedance mismatching between the core list API (which returns a ptr to the removed element if found) and the GNRC pkt list API (which returns a ptr to the new list head) that creates a temporary list head on the stack.
I'm not entirely sure if the previous implementation is containing undefined behavior that is used against us with GCC >= 12.x, or if this is a compiler bug. In either case, not reusing the core list API here and just having a textbook linked list delete function here is not much less readable and fixes the issue for our users.
```
$ make BOARD=nucleo-f767zi -C tests/unittests tests-pkt flash test
```
```
READY
s
START
.......................
OK (23 tests)
```
```
READY
s
START
............... …
```
> sys/net/gnrc/pkt: fix gnrc_pkt_delete()

- sys/bitfield/bitfield.c
- sys/include/bitfield.h
- tests/unittests/tests-bitfield/tests-bitfield.c
Add a function to count the number of set bits in a bitfield.
The `tests-bitfield` unit test was extended with a test for the new function.
> sys/bitfield: add bf_popcnt()

- pkg/littlefs2/Makefile
Bumpity bump!
the `tests/pkg_littlefs2` application should still succeed.
Follow-up to #18049 :stuck_out_tongue_winking_eye:
> pkg/littlefs2: bump version to 2.5.1

- pkg/wolfssl/patches/0001-wolfssl-wolfcrypt-fix-signature-mismatch-to-compile-.patch
This fixes a signature mismatch between forward declaration and implementation, which in turn fixes the following error during compilation:
/home/maribu/Repos/software/RIOT/build/pkg/wolfssl/wolfcrypt/src/ge_low_mem.c:179:30: error: argument 1 of type 'unsigned char[64]' with mismatched bound [-Werror=array-parameter=]
179 | void sc_reduce(unsigned char x[64])
|                ~~~~~~~~~~~~~~^~~~~
In file included from /home/maribu/Repos/software/RIOT/build/pkg/wolfssl/wolfcrypt/src/ge_low_mem.c:34:
/home/maribu/Repos/software/RIOT/build/pkg/wolfssl/wolfssl/wolfcrypt/ge_operations.h:81:36: note: previously declared as 'byte *' {aka 'unsigned char *'}
81 | WOLFSSL_LOCAL void sc_reduce(byte* s);
|                              ~~~~~~^
The following test applications should now compile with …
> pkg/wolfssl: fix compilation with GCC >= 12.x

- sys/include/net/gnrc/pkt.h
The previous implementation used creative construct for impedance mismatching between the core list API (which returns a ptr to the removed element if found) and the GNRC pkt list API (which returns a ptr to the new list head) that creates a temporary list head on the stack.
I'm not entirely sure if the previous implementation is containing undefined behavior that is used against us with GCC >= 12.x, or if this is a compiler bug. In either case, not reusing the core list API here and just having a textbook linked list delete function here is not much less readable and fixes the issue for our users.
```
$ make BOARD=nucleo-f767zi -C tests/unittests tests-pkt flash test
```
```
READY
s
START
.......................
OK (23 tests)
```
```
READY
s
START
............... …
```
> sys/net/gnrc/pkt: fix gnrc_pkt_delete() [backport 2022.10]

- dist/tools/tapsetup/tapsetup
This adds an option to simulate loss links with `netdev_tap`
Create lossy TAP interfaces
sudo dist/tools/tapsetup/tapsetup --loss 20% --delay 10ms
Start two `native` instances
> ping -c 100 -i 10 fe80::58b0:8ff:fe67:ad82   
12 bytes from fe80::58b0:8ff:fe67:ad82%5: icmp_seq=1 ttl=64 time=20.407 ms
12 bytes from fe80::58b0:8ff:fe67:ad82%5: icmp_seq=5 ttl=64 time=20.355 ms
12 bytes from fe80::58b0:8ff:fe67:ad82%5: icmp_seq=6 ttl=64 time=20.357 ms
…
12 bytes from fe80::58b0:8ff:fe67:ad82%5: icmp_seq=98 ttl=64 time=20.383 ms
--- fe80::58b0:8ff:fe67:ad82 PING statistics ---
100 packets transmitted, 67 packets received, 33% packet loss
round-trip min/avg/max = 20.233/20.373/20.509 ms
Note that ping measures round-trip-time, so two packets: 10 ms + 10 ms -> 20ms, 80% * 80% -> 64% success
> tapsetup: add --loss & --delay option

- dist/tools/backport_pr/backport_pr.py
It turned out that 4983f8bb6042018ce762c0d64b21ca09ccb00ceb was not enough to allow the tool to be executed from within `dist/tools/backport_pr`. With this, I successfully tested it :)
Run `./backport_pr --comment <NUM>` inside `<RIOT_DIR>/dist/tools/backport_pr`. In `master`, it still fails, with this, it succeeds.
First attempt (that only partially succeeded) to do this was https://github.com/RIOT-OS/RIOT/pull/18866
> tools/backport_pr: finally fix running outside of repo's root

- tests/pkg_tinyusb_cdc_acm_stdio/Makefile
- tests/pkg_tinyusb_cdc_msc/Makefile
`tests/pkg_tinyusb*` did not build because no BOARD was set and native has no USB for tinyusb
this sets a board enabling default buildability. 
this also changes the deprecated `shell_commands` to the new `shell_cmds_default'
```
tests/pkg_tinyusb_cdc_acm_stdio$ make
```
```
tests/pkg_tinyusb_cdc_msc$ make
```
> tests/pkg_tinyusb*: add a BOARD to make make build

- pkg/tflite-micro/patches/0002-Compare-names-without-over-reading-in-micro_allocati.patch
Use C++ style string comparison instead of `strncmp()` to get rid of the following warning:
/home/maribu/Repos/software/RIOT/build/pkg/tflite-micro/tensorflow/lite/micro/micro_allocation_info.cc: In member function 'TfLiteStatus tflite::AllocationInfoBuilder::GetOfflinePlannedOffsets(const int32_t**)':
/home/maribu/Repos/software/RIOT/build/pkg/tflite-micro/tensorflow/lite/micro/micro_allocation_info.cc:294:18: error: 'int strncmp(const char*, const char*, size_t)' specified bound 23 exceeds source size 0 [-Werror=stringop-overread]
294 |       if (strncmp(metadata->name()->c_str(), kOfflineMemAllocMetadata,
|           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
295 |                   strlen(kOfflineMemAllocMetadata)) == 0) {
| …
> pkg/tflite-micro: fix compilation with GCC >= 12.x

- pkg/ccn-lite/patches/0006-src-ccnl-core-src-ccnl-relay.c-fix-use-after-free.patch
This fixes compilation with GCC >= 12.x, which is unhappy about the use after free:
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c: In function 'ccnl_fib_rem_entry':
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:916:16: error: pointer 'fwd' used after 'free' [-Werror=use-after-free]
916 |         if (fwd->face) {
|             ~~~^~~~~~
In file included from /home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:33:
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/../ccnl-riot/include/ccn-lite-riot.h:52:41: note: call to 'free' here
52 | #define ccnl_free(p)                    free(p)
|                                         ^~~~~~~ …
> pkg/ccn-lite: Fix use after free bug

- makefiles/arch/cortexm.inc.mk
Drop `CFLAGS_DBG` from `ASFLAGS` to fix
make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C /home/maribu/Repos/software/RIOT/tests/pkg_qdsa clean all
rm -rf /home/maribu/Repos/software/RIOT/tests/pkg_qdsa/bin/samr21-xpro/pkg-build/qdsa
Building application "tests_pkg_qdsa" for "samr21-xpro" with MCU "samd21".
Assembler messages:
Fatal error: unknown option `-ggdb'
make[3]: *** [/home/maribu/Repos/software/RIOT/Makefile.base:176: /home/maribu/Repos/software/RIOT/tests/pkg_qdsa/bin/samr21-xpro/qdsa_asm/bigint_red.o] Error 1
make[2]: *** [/home/maribu/Repos/software/RIOT/Makefile.base:31: ALL--/home/maribu/Repos/software/RIOT/build/pkg/qdsa/arm/asm] Error 2
make[1]: *** [Makefile:11: all] Error 2
make: *** [/home/maribu/Repos/software/RIOT/tests/pkg_qdsa/../../Makefile.include:803: …
> makefiles/arch/cortexm.inc.mk: fix ASMFLAGS

- tests/bitarithm_timings/main.c
This test eats 25 whole seconds at 100% of one CI core for the native test, for each build.
The results on an actual MCU won't change, whether it runs for 25s or 1s.
So, reduce the test timeout for each test from 5s to 200ms.
> tests/bitarithm_timings: shorten timeout from 5s to 200ms

- pkg/tflite-micro/patches/0002-Compare-names-without-over-reading-in-micro_allocati.patch
Use C++ style string comparison instead of `strncmp()` to get rid of the following warning:
/home/maribu/Repos/software/RIOT/build/pkg/tflite-micro/tensorflow/lite/micro/micro_allocation_info.cc: In member function 'TfLiteStatus tflite::AllocationInfoBuilder::GetOfflinePlannedOffsets(const int32_t**)':
/home/maribu/Repos/software/RIOT/build/pkg/tflite-micro/tensorflow/lite/micro/micro_allocation_info.cc:294:18: error: 'int strncmp(const char*, const char*, size_t)' specified bound 23 exceeds source size 0 [-Werror=stringop-overread]
294 |       if (strncmp(metadata->name()->c_str(), kOfflineMemAllocMetadata,
|           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
295 |                   strlen(kOfflineMemAllocMetadata)) == 0) {
| …
> pkg/tflite-micro: fix compilation with GCC >= 12.x [backport 2022.10]

- pkg/ccn-lite/patches/0006-src-ccnl-core-src-ccnl-relay.c-fix-use-after-free.patch
This fixes compilation with GCC >= 12.x, which is unhappy about the use after free:
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c: In function 'ccnl_fib_rem_entry':
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:916:16: error: pointer 'fwd' used after 'free' [-Werror=use-after-free]
916 |         if (fwd->face) {
|             ~~~^~~~~~
In file included from /home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:33:
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/../ccnl-riot/include/ccn-lite-riot.h:52:41: note: call to 'free' here
52 | #define ccnl_free(p)                    free(p)
|                                         ^~~~~~~ …
> pkg/ccn-lite: Fix use after free bug [backport 2022.10]

- pkg/wolfssl/patches/0001-wolfssl-wolfcrypt-fix-signature-mismatch-to-compile-.patch
This fixes a signature mismatch between forward declaration and implementation, which in turn fixes the following error during compilation:
/home/maribu/Repos/software/RIOT/build/pkg/wolfssl/wolfcrypt/src/ge_low_mem.c:179:30: error: argument 1 of type 'unsigned char[64]' with mismatched bound [-Werror=array-parameter=]
179 | void sc_reduce(unsigned char x[64])
|                ~~~~~~~~~~~~~~^~~~~
In file included from /home/maribu/Repos/software/RIOT/build/pkg/wolfssl/wolfcrypt/src/ge_low_mem.c:34:
/home/maribu/Repos/software/RIOT/build/pkg/wolfssl/wolfssl/wolfcrypt/ge_operations.h:81:36: note: previously declared as 'byte *' {aka 'unsigned char *'}
81 | WOLFSSL_LOCAL void sc_reduce(byte* s);
|                              ~~~~~~^
The following test applications should now compile with …
> pkg/wolfssl: fix compilation with GCC >= 12.x [backport 2022.10]

- tests/pkg_emlearn/Makefile
It turns out that the fix for the missing terminating newline is not robust. This hopefully fixes the issue and resolves the following error message:
In file included from /home/maribu/Repos/software/RIOT/tests/pkg_emlearn/main.c:25:
/home/maribu/Repos/software/RIOT/tests/pkg_emlearn/model.h:7221:36: error: stray '\' in program
7221 |     /* fix for no newline at eof */\n
|                                    ^
/home/maribu/Repos/software/RIOT/tests/pkg_emlearn/model.h:7221:38: error: expected ';' before '_Alignas'
7221 |     /* fix for no newline at eof */\n
|                                      ^
|                                      ;
```
$ make BOARD=samr21-xpro -j 8 -C tests/pkg_emlearn/
```
Should succeed consistently, rather than fail when the `\n` is not being turned into a …
> tests/pkg_emlearn: fix compilation

- makefiles/arch/cortexm.inc.mk
Drop `CFLAGS_DBG` from `ASFLAGS` to fix
make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C /home/maribu/Repos/software/RIOT/tests/pkg_qdsa clean all
rm -rf /home/maribu/Repos/software/RIOT/tests/pkg_qdsa/bin/samr21-xpro/pkg-build/qdsa
Building application "tests_pkg_qdsa" for "samr21-xpro" with MCU "samd21".
Assembler messages:
Fatal error: unknown option `-ggdb'
make[3]: *** [/home/maribu/Repos/software/RIOT/Makefile.base:176: /home/maribu/Repos/software/RIOT/tests/pkg_qdsa/bin/samr21-xpro/qdsa_asm/bigint_red.o] Error 1
make[2]: *** [/home/maribu/Repos/software/RIOT/Makefile.base:31: ALL--/home/maribu/Repos/software/RIOT/build/pkg/qdsa/arm/asm] Error 2
make[1]: *** [Makefile:11: all] Error 2
make: *** [/home/maribu/Repos/software/RIOT/tests/pkg_qdsa/../../Makefile.include:803: …
> makefiles/arch/cortexm.inc.mk: fix ASMFLAGS [backport 2022.10]

- pkg/tinyusb/doc.txt
This PR updates the doc to take into account the following changes:
- With PR #18804 the approach to override the default tinyUSB configuration was changed.
- With PR #18835, the automatic generation of descriptors for the most common device classes and their handling was introduced. 
`make doc` and check the results.
Fixes the doc for PR #18804
Fixes the doc for PR #18835
> pkg/tinyusb: update doc for tusb_app_config.h and common descriptor handling

- sys/usb/usbus/hid/hid_io.c
This PR fixes a potential buffer overflow inside `usb_hid_io_write` which occurs when `len > CONFIG_USBUS_HID_INTERRUPT_EP_SIZE`.
> usbus/hid: fix buffer overflow in hid_io [backport 2022.10]

- makefiles/cargo-targets.inc.mk
`--quiet` is a GNUism; Alpine's busybox grep only supports the minimal `-q` option required by POSIX.
This allows using Rust on RIOT on an Alpine build system to fail one step later (but as for the correctness of the PR, this shoudl be evident by reading the file).
> makefiles: Use `grep -q` rather than `--quiet`

- .murdock.yml
We're migrating to the new Murdock frontend, no need for the note anymore.
> CI: drop obsolete murdock note

- README.md
Before I forget, this PR is updating the README links to the CI status badge and job details of the new Murdock instance.
Check the [README](https://github.com/aabadie/RIOT/tree/pr/readme_ci_status):
- the badge is displayed 
- the link points to the last nightly job run on master
This is part of the migration to the new Murdock instance
> README.md: update CI badge

- tests/shell/Makefile
- tests/shell/main.c
- tests/shell/tests/01-run.py
The test (at least locally) fails on the long shell line detection in `master`, as the EDBG UART adapter drops chars when more than 64 bytes are send at a time. This works around the issue:
- The line buffer in the test is reduced to 60 bytes, so that overflowing it becomes possible with sending less than 64 bytes.
- The test script is adapted to exceed the shell buffer size by one byte only (due to linefeed char), rather than significantly. - Sending more than 64 bytes would result in the linefeed being dropped by the EDBG adapter and the test failing
Finally, the shell buffer is no longer allocated on the stack and, hence, the main stack size could be reduced a bit. The test still passes on the Nucleo-F767ZI which is notorious in failing on tight stacks due to the MPU stack guard - so …
> tests/shell: fix failure on samr21-xpro

- makefiles/libc/picolibc.mk
Modern binutils complain about segments with RWX permissions. While this is indeed a bad habit, RIOT ignores segments permissions anyway. (We do have a `mpu_noexec_ram` module to disable execution of all of RAM, which would do so regardless of the segment permission.) So for now, we can safely just disable the warning.
This fixes:
/usr/lib/gcc/arm-none-eabi/12.2.0/../../../../arm-none-eabi/bin/ld: warning: /home/maribu/Repos/software/RIOT/examples/default/bin/nucleo-f767zi/default.elf has a LOAD segment with RWX permissions
collect2: error: ld returned 1 exit status
```
$ FEATURES_REQUIRED=picolibc make BOARD=nucleo-f767zi -C examples/default
```
With `master`, the above warning pops up with `binutils` 2.39. With this PR, it is disabled.
None
> makefiles/libc/picolibc.mk: fix compilation with modern binutils

- tests/shell/Makefile
- tests/shell/main.c
- tests/shell/tests/01-run.py
The test (at least locally) fails on the long shell line detection in `master`, as the EDBG UART adapter drops chars when more than 64 bytes are send at a time. This works around the issue:
- The line buffer in the test is reduced to 60 bytes, so that overflowing it becomes possible with sending less than 64 bytes.
- The test script is adapted to exceed the shell buffer size by one byte only (due to linefeed char), rather than significantly. - Sending more than 64 bytes would result in the linefeed being dropped by the EDBG adapter and the test failing
Finally, the shell buffer is no longer allocated on the stack and, hence, the main stack size could be reduced a bit. The test still passes on the Nucleo-F767ZI which is notorious in failing on tight stacks due to the MPU stack guard - so …
> tests/shell: fix failure on samr21-xpro [backport 2022.10]

- makefiles/libc/picolibc.mk
Modern binutils complain about segments with RWX permissions. While this is indeed a bad habit, RIOT ignores segments permissions anyway. (We do have a `mpu_noexec_ram` module to disable execution of all of RAM, which would do so regardless of the segment permission.) So for now, we can safely just disable the warning.
This fixes:
/usr/lib/gcc/arm-none-eabi/12.2.0/../../../../arm-none-eabi/bin/ld: warning: /home/maribu/Repos/software/RIOT/examples/default/bin/nucleo-f767zi/default.elf has a LOAD segment with RWX permissions
collect2: error: ld returned 1 exit status
```
$ FEATURES_REQUIRED=picolibc make BOARD=nucleo-f767zi -C examples/default
```
With `master`, the above warning pops up with `binutils` 2.39. With this PR, it is disabled.
None
> makefiles/libc/picolibc.mk: fix compilation with modern binutils [backport 2022.10]

- sys/include/net/sock.h
- sys/net/gnrc/sock/udp/gnrc_sock_udp.c
- tests/gnrc_sock_udp/main.c
`sock_udp_create()` with a set remote is not just a convenient way to not having to keep the remote around when calling `sock_udp_send()` it actually binds the socket to that remote and will drop any response from a different address.
This is of course not very practical when the remote is a multicast address as this means all unicast responses are dropped.
This adds a new `SOCK_FLAGS_BIND_REMOTE` flag that gets set automatically for unicast remotes to retain current behavior.
This also moves the remote-checking code `sock_udp_recv_buf_aux()` to make it more readable as this was not so straightforward to debug. 
A new test case was added to `tests/gnrc_sock_udp`.
> gnrc_sock_udp: accept response from any address if remote is multicast

- sys/net/gnrc/sock/udp/gnrc_sock_udp.c
Indentation was wrong and function name reversed.
Just style fix.
> gnrc_sock_udp: style fix in sock_udp_recv_buf_aux()

- doc/doxygen/src/kconfig/kconfig.md
> docs/kconfig: "not longer" -> "no longer" typo

- makefiles/pseudomodules.inc.mk
- sys/malloc_thread_safe/Kconfig
- sys/malloc_thread_safe/malloc_wrappers.c
Hooking into the existing wrappers for `malloc()`, `calloc()`, `realloc()`, and `free()`, the new (pseudo) module `malloc_tracing` prints out the calls to the given functions, the program counter of the caller, as well as the return result.
The intent is to aid debugging double-frees, invalid frees, or memory leaks.
```
$ USEMODULE=malloc_tracing make BOARD=nucleo-f767zi -C tests/pthread_flood flash test
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-357-g180da-sys/malloc_tracing)
Spawning pthreads
calloc(1, 36) @0x8001737 returned 0x20001cf0
.calloc(1, 36) @0x8001737 returned 0x20001d18
.calloc(1, 36) @0x8001737 returned 0x20001d48
.calloc(1, 36) @0x8001737 returned 0x20001d70
.calloc(1, 36) @0x8001737 returned 0x20001da0
.calloc(1, 36) @0x8001737 returned 0x20001dc8 …
```
> sys/malloc_tracing: add module to trace dyn memory management

- sys/test_utils/print_stack_usage/print_stack_usage.c
Since fmt no longer has a significant advantage in stack consumption, we need to bump the `MIN_SIZE` guard that prevents causing stack overflows due to the printing of the stack consumption.
```
$ make BOARD=nucleo-f767zi -C tests/pthread_flood flash test
```
Should no longer print stack usage for the dummy POSIX threads and not result in hard faults due to stack overflows anymore.
Better alternative to https://github.com/RIOT-OS/RIOT/pull/18916
> sys/print_stack_usage: update MIN_SIZE [backport 2022.10]

- makefiles/cflags.inc.mk
- makefiles/libc/newlib.mk
- makefiles/libc/picolibc.mk
- makefiles/cflags.inc.mk: add `-z noexecstack` to link flags
- GCC on some platforms does need an executable stack to generate trampoline code, but use of nested functions is not allowed in RIOT's code base anyway.
- makefiles/libc: fix wchar_t size warnings on LLVM
- The test for the requirement of disabling wchar_t size warnings assumed that `$(CC)` is used for linking, instead of `$(LINK)`. With GCC `$(LINK)` and `$(CC)` happen to be (in most cases) identical, but with LLVM they are not. This results in issues with compiling with LLVM.
No change in binaries and everything should still compile.
Inspired by https://github.com/RIOT-OS/RIOT/pull/18844
> build system: fix compilation with LLVM [backport 2022.10]

- boards/nucleo-l476rg/doc.txt
This PR adds missing link to the board MCU Datasheet.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l476rg.html
```
None
> boards/nucleo-l476zg: doc improvements

- cpu/stm32/include/cpu_conf.h
Run `tests/malloc` on a supported CPU
```
2022-11-16 13:25:06,756 # Allocated 128 Bytes at 0x0x20001c58, total 128
2022-11-16 13:25:06,757 # Allocated 128 Bytes at 0x0x20001cf0, total 264
2022-11-16 13:25:06,757 # Allocated 128 Bytes at 0x0x20001d88, total 400
2022-11-16 13:25:06,758 # Allocated 128 Bytes at 0x0x20001e20, total 536
2022-11-16 13:25:06,759 # Allocated 128 Bytes at 0x0x20001eb8, total 672
…
2022-11-16 13:25:07,614 # Allocated 128 Bytes at 0x0x2002fef8, total 169312
2022-11-16 13:25:07,615 # Allocated 128 Bytes at 0x0x40024008, total 169448
2022-11-16 13:25:07,615 # Allocated 128 Bytes at 0x0x40024090, total 169584
2022-11-16 13:25:07,616 # Allocated 128 Bytes at 0x0x40024118, total 169720
2022-11-16 13:25:07,616 # Allocated 128 Bytes at 0x0x400241a0, total 169856
… …
```
> cpu/stm32: add unused backup RAM as extra heap

- cpu/esp8266/Makefile.include
- makefiles/arch/avr8.inc.mk
- makefiles/cflags.inc.mk
`__FILE__` will resolve to the absolute path of the file.
This adds a lot of noise (and ROM size) when debugging with tracer macros.
Luckily, starting with GCC 8 we can drop the common `$(RIOTBASE)` prefix, this makes for much nicer output.
Used in e.g. #18795
> makefiles/cflags.inc.mk: don't include absolute path in __FILE__ macro

- sys/fmt/fmt.c
- sys/include/fmt.h
- tests/fmt_print/main.c
- tests/fmt_print/tests/01-run.py
Pretty straightforward function to print a byte buffer
> sys/fmt: add print_bytes_hex()

- sys/shell/cmds/gnrc_icmpv6_echo.c
We don't need two names for the same command, `ping` is enough.
> sys/shell: drop ping6 alias

- core/lib/include/assert.h
- core/msg.c
- cpu/lpc23xx/mci/lpc23xx-mci.c
- cpu/native/netdev_tap/netdev_tap.c
- sys/include/embUnit/AssertImpl.h
- sys/include/test_utils/expect.h
- sys/net/gnrc/transport_layer/tcp/include/gnrc_tcp_common.h
With a recent compiler (GCC ≥ 8) we can define `__FILE__` to be relative to the RIOT base directory, so there is no more need for the custom (and fragile) `RIOT_FILE_RELATIVE` macro.
Output should stay the same.
https://github.com/RIOT-OS/RIOT/pull/18913#issuecomment-1320647678
> treewide: replace RIOT_FILE_RELATIVE with __FILE__

- cpu/esp8266/Makefile.include
- makefiles/arch/avr8.inc.mk
- makefiles/toolchain/gnu.inc.mk
`-fmacro-prefix-map` was introduced in GCC 8, so only set it if the compiler version is 8 or newer.
https://github.com/RIOT-OS/RIOT/pull/18913#issuecomment-1320555878
> makefiles/gnu.inc.mk: set flags based on compiler version

- makefiles/toolchain/gnu.inc.mk
`make` on Arch rightfully complains about the extra parenthesis
/home/benpicco/dev/RIOT/makefiles/toolchain/gnu.inc.mk:29: extraneous text after 'ifneq' directive
~~It's the same version that Ubuntu ships, but for some reason that just silently ignores it.~~
It's also there on Ubuntu, I just didn't see it because it scrolled away so fast.
[![image](https://user-images.githubusercontent.com/1301112/202906243-48731344-38fd-454f-9123-8329c70101fd.png)](https://xkcd.com/859/)
follow-up to #18935
> makefiles/gnu.inc.mk: fix "extraneous text after 'ifneq' directive"

- boards/common/nrf52/include/cfg_timer_default.h
- All nRF52 timers support 32 bit mode, so use that
- All nRF52 timers support at least 4 channels, the timers NRF_TIMER3 and NRF_TIMER4 even support 6 channels.
- Add a warning that `TIMER_DEV(1)` is used by the IEEE 802.15.4 driver
Use a timer other than `TIMER_DEV(0)` (that is used by ztimer) and set a timeout that cannot be represented in 8 bits. This should now work.
Needed for https://github.com/RIOT-OS/RIOT/pull/18392 to work
> boards/common/nrf52: improve default clock config

- tests/pbkdf2/main.c
What the title says.
Should not result in changes in binaries. And Murdock should give green light.
The removed `#include` caused issues in [a backport](https://github.com/RIOT-OS/RIOT/pull/18941), but it is actually uneeded in `master` as well. I cannot recall why it was there in the first place - maybe a leftover from the flaky test?
> tests/pbkdf2: remove unused #include

- core/lib/include/compiler_hints.h
There are static functions and variables that may be unused if certain modules are used or not used.
Instead of adding a guard around these marking them as "maybe unused" is much clearer C23 seems to add a stadat attribute system where [[maybe_unused]]  would be that mark
this adds a`MAYBE_UNUSED` define that uses the badly name `__attribute((unused))__` to mark such `maybe unused` cases
read
this contains #18882
> core/lib: define MAYBE_UNUSED

- boards/common/nrf52/include/cfg_timer_default.h
- cpu/nrf5x_common/include/periph_cpu_common.h
The `channels` member should not be set to the number of hardware channels *n*, but to *n* - 1 instead. The last channel is implicitly used in `timer_read()`. Hence out of *n* hardware channels, only *n* - 1 are available to the application.
This fixes a bug introduced by 4d02e1524732b040f5109adbeed416b38ceb8c19 which incorrectly set the channel number to *n* rather than to *n* - 1.
`timer_read()` should work again on nRF52 MCUs.
Introduced in https://github.com/RIOT-OS/RIOT/pull/18811
> boards/common/nrf52: fix timer config

- core/mbox.c
The mbox code contains a race condition in `mbox_put()`: When it waits for a slot in the queue to become available, it is woken up with IRQs enabled. It disables IRQs again as first thing, but by then another thread may already have preempted the running thread and filled the queue back up. In this case, a message in the queue would be silently overwritten.
Actually triggering the race condition would require some effort with a specially crafted test application, which I am unable to currently provide. It should however be quite easy to reason that the change fixes the potential race condition.
In addition, the usual regression tests may make sense.
None
> core/mbox: fix race condition

- tests/pkg_utensor/Makefile
The MPU based stack guard is very unpleased by the stack overflow happening during the test. The increase in stack size makes the MPU stack guard happy again.
```
make BOARD=nrf52840dk -C tests/pkg_utensor flash test
```
In `master`, the test fails with a stack overflow being detected. In this PR, it succeeds.
None
> tests/pkg_utensor: increase main threads stack size

- cpu/nrf5x_common/periph/timer.c
While testing #17607 I realized that the timer peripheral consumes significant amounts of current even in stopped state. I had a look into the [implementation of our Zephyr friends](https://github.com/zephyrproject-rtos/zephyr/blob/178bdc4afcd54e2bd5b986d0de4591a6f888d874/drivers/counter/counter_nrfx_timer.c#L67) and found this [Errata PDF](https://infocenter.nordicsemi.com/pdf/nRF52833_Engineering_A_Errata_v1.4.pdf).
TBD
> cpu/nrf5x/timer: fix high current consumption in powered off state

- tests/pkg_utensor/Makefile
The MPU based stack guard is very unpleased by the stack overflow happening during the test. The increase in stack size makes the MPU stack guard happy again.
```
make BOARD=nrf52840dk -C tests/pkg_utensor flash test
```
In `master`, the test fails with a stack overflow being detected. In this PR, it succeeds.
None
> tests/pkg_utensor: increase main threads stack size [backport 2022.10]

- sys/net/gnrc/netreg/gnrc_netreg.c
When freeing any stale pktsnips from stale messages in the mbox, make sure that the messages actually contains a pktsnip before freeing.
The test `tests/pkg_edhoc_c` should no longer crash
Split out of https://github.com/RIOT-OS/RIOT/pull/18949
> sys/net/grnc/netreg: avoid freeing wild pointers

- boards/nucleo-l496zg/Kconfig
- boards/nucleo-l496zg/Makefile.features
- boards/nucleo-l496zg/include/periph_conf.h
- cpu/stm32/include/periph/l4/periph_cpu.h
- cpu/stm32/periph/adc_l4.c
This PR adds to the Nucleo-l496zg ADC configuration.
None
> boards/nucleo-l496zg: add ADC support

- examples/gcoap/README.md
- examples/gcoap/client.c
Replace custom endpoint parsing function with the use of `sock_udp_name2ep`.
This changes the way be input the address and the port. These are now not two arguments anymore but only a single one.
Dependencies:
- #17763
> examples/gcoap: replace _parse_endpoint by sock_udp_name2ep

- core/mbox.c
The mbox code contains a race condition in `mbox_put()`: When it waits for a slot in the queue to become available, it is woken up with IRQs enabled. It disables IRQs again as first thing, but by then another thread may already have preempted the running thread and filled the queue back up. In this case, a message in the queue would be silently overwritten.
Actually triggering the race condition would require some effort with a specially crafted test application, which I am unable to currently provide. It should however be quite easy to reason that the change fixes the potential race condition.
In addition, the usual regression tests may make sense.
None
> core/mbox: fix race condition [backport 2022.10]

- sys/net/gnrc/netreg/gnrc_netreg.c
When freeing any stale pktsnips from stale messages in the mbox, make sure that the messages actually contains a pktsnip before freeing.
The test `tests/pkg_edhoc_c` should no longer crash
Split out of https://github.com/RIOT-OS/RIOT/pull/18949
> sys/net/grnc/netreg: avoid freeing wild pointers [backport 2022.10]

- cpu/nrf5x_common/periph/uart.c
The `examples/hello-world` shows a power consumption of 400uA on the `nrf52dk` board, even though stdin isn't wired and, thus, RX of the `periph_uart` isn't wired.
This PR makes sure that `TASKS_STARTTX` is called before a transmission. After completion the `TASKS_STOPTX` is run allowing for entering low power mode.
`nrf51` and `nrf52` CPUs should be able to transmit octets using `periph_uart` with and without the `uart_nonblocking` feature.
> cpu/nrf5x/uart: run STOPTX task after finished tx

- boards/common/particle-mesh/bootloader.c
- boards/esp32-mh-et-live-minikit/include/board_modules.h
- sys/include/net/ipv4/hdr.h
- sys/posix/pthread/include/pthread_cleanup.h
- tests/driver_mcp47xx/main.c
- tests/driver_pca9685/README.md
- tests/driver_pca9685/main.c
- tests/driver_pcf857x/README.md
- tests/driver_pcf857x/main.c
Static tests are currently failing on master.
Green static tests.
> treewide: fix typos found by recent codespell

- doc/doxygen/src/using-rust.md
- examples/rust-gcoap/Makefile
- examples/rust-hello-world/Makefile
Since Rust 1.65, we don't depend on anything nightly any more. This changes the examples and documentation to use stable.
* Green CI with tests enabled
* Look at changed documentation ([rendered](https://ci.riot-os.org/results/2923b30a4ba04dbface1ed38fb6aae12/doc-preview/using-rust.html#toolchain))
<del>Note that these will *not* pass yet: This needs a CI update (no PR associated: Any CI image built from now on will do).</del>
A follow-up will simplify things a bit further, but that will depend on CI to have made stable the default, which is a later step in what is a bit of a lock-step game:
> rust: Use stable Rust

- cpu/stm32/periph/timer.c
This fixes in the `periph_timer` implementation of STM32:
- race conditions when two threads share the same timer peripheral, but distinct sets of timer channel
- spurious IRQs
The test in https://github.com/RIOT-OS/RIOT/pull/18963 should now pass
> cpu/stm32/periph_timer: fix spurious IRQs and race conditions

- cpu/esp32/periph/timer.c
- cpu/esp8266/periph/timer.c
Allow multiple calls to `timer_init()`, as this is the only way to change the timer frequency or the callback function.
The test in https://github.com/RIOT-OS/RIOT/pull/18963 should now pass.
> cpu/esp{32,8266}/periph_timer: allow changing callback or freq

- cpu/nrf5x_common/periph/timer.c
The test in https://github.com/RIOT-OS/RIOT/pull/18963 should now pass
> cpu/nrf5x_common/periph_timer: fix spurious IRQs

- cpu/stm32/periph/timer.c
This fixes in the `periph_timer` implementation of STM32:
- race conditions when two threads share the same timer peripheral, but distinct sets of timer channel
- spurious IRQs
The test in https://github.com/RIOT-OS/RIOT/pull/18963 should now pass
> cpu/stm32/periph_timer: fix spurious IRQs and race conditions [backport 2022.10]

- cpu/esp32/periph/timer.c
- cpu/esp8266/periph/timer.c
Allow multiple calls to `timer_init()`, as this is the only way to change the timer frequency or the callback function.
The test in https://github.com/RIOT-OS/RIOT/pull/18963 should now pass.
> cpu/esp{32,8266}/periph_timer: allow changing callback or freq [backport 2022.10]

- cpu/nrf5x_common/periph/timer.c
The test in https://github.com/RIOT-OS/RIOT/pull/18963 should now pass
> cpu/nrf5x_common/periph_timer: fix spurious IRQs [backport 2022.10]

- drivers/at86rf2xx/at86rf2xx.c
- drivers/at86rf2xx/at86rf2xx_getset.c
- drivers/at86rf2xx/at86rf2xx_internal.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
- drivers/at86rf2xx/include/at86rf2xx_internal.h
- drivers/at86rf2xx/include/at86rf2xx_params.h
- drivers/include/at86rf2xx.h
It has been [very hard](https://github.com/RIOT-OS/RIOT/pull/16535) to port AT86RF based radios to the Radio HAL because the presentation layer is mixed with the interface layer (netdev). Even more, variant specific stuff are scattered everywhere, which makes it hard to write a compatible Radio HAL interface. Therefore, I think the only way to move forward is to clean-up the driver a bit.
This PR tries to define variant specific caps (e.g `HAVE_ED_REGISTER`, `HAVE_SUBGHZ` , `AT86RF2XX_PERIPH`) based on the variant.
In a follow up, I plan to move the PERIPH parts to its own file and separate the SPI implementation with the PERIPH version. The idea is to have provide a common abstraction for the hardware interface layer, so it becomes relatively straight forward to replace …
> drivers/at86rf2xx: define caps in macros

- pkg/nimble/netif/nimble_netif.c
Since commit ab32ad50 netifs are required to signal NETDEV_EVENT_LINK_UP at least once; commit 838a5e4b adds this to all netifs except nimble_netif, which basically breaks all of the usage scenarios for 6LoWPAN over BLE; this is a fix of this issue.
Compile gnrc_networking for nrf52dk, then run ifconfig; a link-local address should be available.
Fixes https://github.com/RIOT-OS/RIOT/issues/18923
> pkg/nimble: signal LINK_UP on initialisation

- pkg/nimble/netif/nimble_netif.c
Since commit ab32ad50 netifs are required to signal NETDEV_EVENT_LINK_UP at least once; commit 838a5e4b adds this to all netifs except nimble_netif, which basically breaks all of the usage scenarios for 6LoWPAN over BLE; this is a fix of this issue.
Compile gnrc_networking for nrf52dk, then run ifconfig; a link-local address should be available.
Fixes https://github.com/RIOT-OS/RIOT/issues/18923
> pkg/nimble: signal LINK_UP on initialisation [backport 2022.10]

- cpu/atmega_common/periph/timer.c
As the tile says
`tests/periph_timer` from https://github.com/RIOT-OS/RIOT/pull/18963 and `tests/periph_timer_periodic` should pass. (They do on the `arduino-mega2560`.)
https://github.com/RIOT-OS/RIOT/issues/18976
> cpu/atmega_common/periph_timer: fix spurious IRQs

- cpu/atmega_common/periph/timer.c
As the tile says
`tests/periph_timer` from https://github.com/RIOT-OS/RIOT/pull/18963 and `tests/periph_timer_periodic` should pass. (They do on the `arduino-mega2560`.)
https://github.com/RIOT-OS/RIOT/issues/18976
> cpu/atmega_common/periph_timer: fix spurious IRQs [backport 2022.10]

- boards/nucleo-g070rb/include/periph_conf.h
- boards/nucleo-g071rb/include/periph_conf.h
- boards/nucleo-l476rg/include/periph_conf.h
- boards/nucleo-l496zg/include/periph_conf.h
- boards/nucleo-l4r5zi/include/periph_conf.h
In PR #18940 @maribu point out that vbat ADC channel for nucleo-l496zg has voltage divider.
I checked datasheets for other nucleo boards with configured ADC and find that this behavior is 
documented only on few L and G family MCUs. 
This PR improves documentation adding such information. Moreover, I moved doxygen section 
from the middle of   `adc_config[]` as it do not appear in the generated HTML documentation.
```
make doc
xdg-open doc/doxygen/html/boards_2nucleo-l496zg_2include_2periph__conf_8h.html
xdg-open doc/doxygen/html/boards_2nucleo-l476rg_2include_2periph__conf_8h.html
xdg-open doc/doxygen/html/boards_2nucleo-l4r5zi_2include_2periph__conf_8h.html
xdg-open doc/doxygen/html/boards_2nucleo-g070rb_2include_2periph__conf_8h.html
xdg-open …
```
> boards/nucleo-l* and g*: update doc concerning Vbat

- boards/qn9080dk/Makefile.include
The board has integrated debugger:
1fc9:0090 NXP Semiconductors LPC-LINK2 CMSIS-DAP V5.173
This commit changes the default debug adapter to this one.
Connect the board via USB to the connector labeled `DFU Link` (rather than the one labeled `Target`) and set the jumper JP2 to use the internal debugger (for me, this is how the board came out of the box). Then, in any RIOT app, run:
```
make BOARD=qn9080dk flash
```
This yields on `master`:
```
Open On-Chip Debugger 0.12.0-rc2+dev-snapshot (2022-11-28-13:26)
swd
Warn : Transport "swd" was already selected
Error: No J-Link device found
```
With this PR it yields:
```
Open On-Chip Debugger 0.12.0-rc2+dev-snapshot (2022-11-28-13:26)
Licensed under GNU GPL …
```
> boards/qn9080dk: add default OPENOCD_DEBUG_ADAPTER

- cpu/qn908x/periph/timer.c
Previously, the callback was incorrectly passed a channel of zero as argument regardless of the channel that triggered the IRQ. This fixes the issue and also uses `bitarithm_test_and_clear()` to only iterate over the channels that actually have an IRQ flag set, rather than all channels.
```
$ make BOARD=qn9080dk flash test -C tests/periph_timer
```
for the test application pimped up by https://github.com/RIOT-OS/RIOT/pull/18963
```
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-473-g496ab-tests/periph_timer)
Test for peripheral TIMERs
Available timers: 4
Testing TIMER_0:
TIMER_0: initialization successful
TIMER_0: stopped
TIMER_0: set channel 0 to 5000
TIMER_0: set channel 1 to 10000
TIMER_0: set channel 2 to 15000
TIMER_0: …
```
> cpu/qn908x: use bitarithm_test_and_clear() & fix cb

- cpu/qn908x/periph/timer.c
Previously, the callback was incorrectly passed a channel of zero as argument regardless of the channel that triggered the IRQ. This fixes the issue and also uses `bitarithm_test_and_clear()` to only iterate over the channels that actually have an IRQ flag set, rather than all channels.
```
$ make BOARD=qn9080dk flash test -C tests/periph_timer
```
for the test application pimped up by https://github.com/RIOT-OS/RIOT/pull/18963
```
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-473-g496ab-tests/periph_timer)
Test for peripheral TIMERs
Available timers: 4
Testing TIMER_0:
TIMER_0: initialization successful
TIMER_0: stopped
TIMER_0: set channel 0 to 5000
TIMER_0: set channel 1 to 10000
TIMER_0: set channel 2 to 15000
TIMER_0: …
```
> cpu/qn908x: use bitarithm_test_and_clear() & fix cb [backport 2022.10]

- tests/unittests/tests-uri_parser/tests-uri_parser.c
Hi! 👋 
As prototyped and reviewed in #18629, this is the start of rewriting the unit tests of the uri_parser.
I believe it can safely be merged into RIOT there are however some things worth noting:
* I wanted to tests for invalid schemes but failed since the uri_parser just can't 😢
* Some minor coverage is lost compared to the old test but a lot is gained including new (different) coverage. (Again, see my comments)
* This only partially rewrites the tests, some old tests remain.
* The test size (as in bytes & execution time) has increased. Be aware of that when testing via HIL.
This is related work to #18702 
The testing of the uri_parser remains far from being complete after this is merged.
> unittests/uri_parser: Rework tests to be more verbose

- pkg/wamr/Makefile
Update WAMR pkg to new release `WAMR-1.1.1` (2022-10-18)
> pkg/wamr: Update to WAMR-1.1.1

- dist/tools/ci/can_fast_ci_run.py
This PR should fix #18987.
I first started with some sophisticated regex based generic replacement / mapping functionality, then decided to go simple...
The issue is that can_fast_ci_run.py *correctly* classifies any change to `tests/unittests/tests-$foo` to be a change to that module, but unittests are special in our build system - they can be built as one huge binary (`tests/unittests`), or individually (`tests/unittests/tests-*`). The latter are not built by CI and are not listed when doing `make info-applications`.
Fixes #18987.
> CI: can_fast_ci_build.py unittests fix

- examples/suit_update/main.c
- sys/include/suit/transport/coap.h
- sys/include/suit/transport/worker.h
- sys/suit/transport/worker.c
Drop the need to call `suit_worker_run()` before calling `suit_worker_trigger()` - the thread only has a single purpose anyway.
Also make the `suit_handle_url()` function available to users who already have a sufficiently large stack, when no worker thread should be started at all.
Follow the steps in `examples/suit_update`:
```
> suit: received URL: "coap://[2001:db8::1]/fw/suit_update/samr21-xpro/riot.suit.latest.bin"
suit_worker: started.
suit_worker: downloading "coap://[2001:db8::1]/fw/suit_update/samr21-xpro/riot.suit.latest.bin"
suit_worker: got manifest with size 485
suit: verifying manifest signature
suit: validated manifest version
)Manifest seq_no: 1669802730, highest available: 1669802619
suit: validated sequence number
)Formatted component name: 
Comparing manifest offset …
```
> suit: start worker thread on demand, make suit_handle_url() public

- pkg/paho-mqtt/Makefile.dep
Paho won't compile on platforms where an Integer is smaller than 32 bit.
This PR adds the corresponding requirement to the package.
Build paho_mqtt example application and check if it still building for a 32 bit platform. (It won't build for a 16 bit platform even without this PR because of LWIP having the same requirement.)
Take a look at https://github.com/eclipse/paho.mqtt.embedded-c/blob/master/MQTTPacket/src/MQTTPacket.c#L93 
#18982 relies on this PR.
> pkg: paho-mqtt: added missing requirement

- examples/paho-mqtt/Makefile
- examples/paho-mqtt/Makefile.ci
- examples/paho-mqtt/Makefile.gnrc
- examples/paho-mqtt/Makefile.lwip
- examples/paho-mqtt/main.c
- pkg/paho-mqtt/contrib/riot_iface.c
The example application for Paho MQTT is using lwip instead of GNRC because at the time of writing no TCP support for GNRC was available. However, in the meantime the situation has changed and with a tiny tweak of the adapter code Paho works like charm on GNRC TCP sockets.
Start a MQTT broker, e.g., mosquitto.
On native:
1. Start the example application and add the tab bridge as default route via `nib route add 7 :: <link-local address of the bridge>`
On iotlab-m3 (or similar):
1. Setup a border router (for instance in IoT-Lab following https://www.iot-lab.info/learn/tutorials/riot/riot-public-ipv6-m3/)
2. Start the example application on a second node
Finally, call `con <Broker IPv6 address>` followed by `sub <TOPIC>` and `pub <TOPIC>.
> paho: use GNRC instead of lwip

- examples/timer_periodic_wakeup/Makefile
- examples/timer_periodic_wakeup/main.c
`ztimer_msec` is entirely sufficient for this test.
> examples/timer_periodic_wakeup: switch to ztimer

- release-notes.txt
This contains the current state of the release notes for discussion. Note that the release is not yet ready and backports will still be made. However, only bug fixes will be backported, hence the release notes will only receive minor additions.
Proof reading ...
None
> release-notes.txt: add 2022.10 release notes [backport 2022.10]

- cpu/sam0_common/periph/i2c.c
See description in #19008 . I modified `_read` and `_write` in `cpu/sam0_common/periph/i2c.c` in order to use the declared `len` parameter.
> sam0_common: use size_t len for I2C transfers (fixes #19008)

- dist/tools/usb-serial/ttys.py
For some TTY interfaces no DB entry exists, which is reflected by having a `None` in `tty[key]`. Trying to match a regex against `None` in turn resulted then in an exception.
This fixes the issue by treating a filter applied on a non-existing entry as not matching.
With the following TTYs attached:
```
$ ./dist/tools/usb-serial/ttys.py
```
path         | driver  | vendor                   | model                      | model_db               | serial               | ctime    | iface_num
-------------|---------|--------------------------|----------------------------|------------------------|----------------------|----------|----------
/dev/ttyACM1 | cdc_acm | Arduino (www.arduino.cc) | 0042                       | Mega 2560 R3 (CDC ACM) | 857353134333519002C1 | 10:43:21 | 0 …
> dist/tools/usb-serial: fix exception on missing entries

- sys/include/puf_sram.h
- sys/puf_sram/puf_sram.c
`puf_sram.h` included `thread.h` and `hashes.h` without making use of it. This fixes that and adds includes of `std...h` that are used by it.
> sys/puf_sram: cleanup header

- dist/tools/zep_dispatch/start_network.sh
- examples/gnrc_border_router/Makefile
- examples/gnrc_border_router/Makefile.ethos.conf
- examples/gnrc_border_router/Makefile.native.conf
- examples/gnrc_border_router/README.md
When using `gnrc_border_router` on `native` the build system will take care of creating a TAP interface and running UHCP/DHCPv6 on it.
This is not always the desired behavior.
e.g. when a TAP bridge was created with a real interface to provide an uplink to `native` or `ethos`, we actually want to use that instead of creating a new one.
We then also want to use the real DHCPv6 server instead of starting our own one.
This adds the `REUSE_TAP=1` option to skip network setup and just use the provided TAP interface as the uplink.
- create a bridge with your Ethernet adapter (interface name may vary)
sudo dist/tools/tapsetup/tapsetup -u eno1
- start the border router with the `tap` uplink
make REUSE_TAP=1 -C examples/gnrc_border_router all term
- the border router should receive a global …
> examples/gnrc_border_router: add option to re-use existing TAP interface

- tests/periph_timer/main.c
Previously the test only checked if IRQs fired when expected. This extends the test to also check that IRQs do not fire when not expected.
In addition, some long overdue style / misuse of `volatile` fixes are added as separate commit.
The test app should pass on correct timer drivers (e.g. `samr21-xpro`), and fail on broken ones (e.g. `nucleo-f767zi`).
None
> tests/periph_timer: also test for spurious IRQs 

- .murdock
This PR implements "quick builds" (subset builds).
The logic is as following (checkmark for what was tested):
TBD: actual list of QUICKBUILD_BOARDS
bors tracking issue: https://github.com/RIOT-OS/RIOT/issues/18911
> CI: implement quick build logic

- examples/paho-mqtt/Makefile
- examples/paho-mqtt/main.c
- pkg/paho-mqtt/contrib/riot_iface.c
- sys/include/net/dns.h
This is pretty straightforward, we only need to hook up `dns_query()`.
Since paho supports both IPv4 and IPv6 we use `AF_UNSPEC` in the query.
This can however give us a A record if we only have IPv6 enabled, so translate the request based on what IP address module is enabled in `dns_query()`.
connecting by name works
```
> con test.mosquitto.org 1883
mqtt_example: Connecting to MQTT Broker from test.mosquitto.org 1883
mqtt_example: Trying to connect to test.mosquitto.org , port: 1883
user: clientId: password:
mqtt_example: Connection successfully
```
connecting by IP still works
```
> con 2001:41d0:1:925e::1 1883
mqtt_example: Connecting to MQTT Broker from 2001:41d0:1:925e::1 1883
mqtt_example: Trying to connect to 2001:41d0:1:925e::1 , port: 1883
user: clientId: password:
mqtt_example: …
```
> pkg/paho-mqtt: add support for DNS

- .github/workflows/check-pr.yml
See https://github.com/RIOT-OS/RIOT/pull/18956#issuecomment-1342781762
I've set the label in question, so the test should fail in the beginning.
See https://github.com/RIOT-OS/RIOT/pull/18956
> check-pr.yml: Fail when `State: waiting for CI update` is set

- dist/tools/compile_test/compile_like_murdock.py
Helper script to pre-test murdock build conditions.
This is intended to compile like murdock giving control for only a subset of boards or applications. One can use this if only a limited change should be build tested. Defaults boards and apps are selected to be an early warning if something is wrong.
This should be used before triggering much larger murdock builds.
The following use cases are:
I made a change to something in the stm32 clocks... ./compile_like_murdock.py -c stm32
I changed a driver the DHT driver
./compile_like_murdock.py -a tests/driver_dht tests/saul
I changed a nucleo-f103rb board...
./compile_like_murdock.py -a tests/driver_dht tests/saul
View the help...
```
./dist/tools/compile_test/compile_like_murdock.py -h
```
Do a dry run of the cpu...
``` …
```
> dist/tools: Add compile_like_murdock

- pkg/lwip/include/arch/cc.h
lwIP has already used its own log level when deciding what to print. If we reach the LWIP_PLATFORM_DIAG macro no further filtering should happen, so set the log level to match the macro used.
I am not sure where the log level got set to something else than `LOG_INFO` causing me to get no IP addresses shown (maybe esp32 logging magic?).
A nicer solution is hard to do since lwIP passes the variable part of the log in a separate set of parenthesis, like
`LWIP_DEBUGF(ICMP_DEBUG, ("icmp_input: ip_output_if returned an error: %s\n", lwip_strerr(ret)));`
so vprintf things are needed to add a new log level back to match the log module interface. If `log_write` was printf-like and didn't have the log_level argument it would be easy.
Flash an app using lwIP, I tested with `examples/paho-mqtt`
This …
> pkg/lwip: Force loglevel when using log module

- examples/paho-mqtt/Makefile.ci
- pkg/paho-mqtt/Makefile.dep
- pkg/paho-mqtt/patches/0002-MQTTPacket-removed-unused-function.patch
- pkg/paho-mqtt/patches/0003-MQTTPacket-use-int32_t-instead-of-int-where-necessar.patch
- pkg/paho-mqtt/patches/0004-MQTTPacket-fix-printf-formatters.patch
Providing a patch to Paho upstream which uses fixed size integers (int32_t) instead of plain int whenever it is used to represent a size of an object.
This patch will allow to build the Paho package for platforms where an integer has a width of less than 32 bit.
This patch is also provided as a PR to the upstream version of Paho (https://github.com/eclipse/paho.mqtt.embedded-c/pull/238) but unfortunately the upstream seems to be unmaintained.
Build for a 8 or 16 bit platform that has enough memory for the example, e.g., https://api.riot-os.org/group__boards__atxmega-a1u-xpro.html:
BUILD_IN_DOCKER=1 BOARD=atxmega-a1u-xpro make clean all
Without this PR this build will fail, with the patches applied it will succeed.
This PR makes #18997 obsolete and thus reverts the change.
> Paho: Allow building for 8 and 16 bit platforms

- boards/nucleo-l496zg/doc.txt
This PR adds to nucleo-l496zg documentation MCU table - similar to those, for example for, Nucleo F103RB, F302R8 or F446RE.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l496zg.html
```
None
> boards/nucleo-l496zg: doc improvement

- boards/arduino-mega2560/Makefile.include
- dist/tools/usb-serial/ttys.py
- doc/doxygen/src/flashing.md
- makefiles/tools/serial.inc.mk
This allows automatically selecting TTY actually belonging to an
Arduino Mega2560 if `MOST_RECENT_PORT=1` is set.
```
make BOARD=arduino-mega2560 MOST_RECENT_PORT=1 -C examples/default flash term
```
Should automatically select the TTY of the most recently connected Arduino Mega2560, even if a board of a different type is connect more recently.
> boards/arduino-mega2560: add TTY_BOARD_FILTER

- boards/common/particle-mesh/bootloader.c
- boards/esp32-mh-et-live-minikit/include/board_modules.h
- sys/include/net/ipv4/hdr.h
- sys/posix/pthread/include/pthread_cleanup.h
- tests/driver_mcp47xx/main.c
- tests/driver_pca9685/README.md
- tests/driver_pca9685/main.c
- tests/driver_pcf857x/README.md
- tests/driver_pcf857x/main.c
Static tests are currently failing on master.
Green static tests.
> treewide: fix typos found by recent codespell [backport 2022.10]

- dist/tools/vagrant/README.md
As [reported on the forum](https://forum.riot-os.org/t/reproducible-developer-setup-for-riot/3830/12), the README is not in sync with the current state of the VM, which is [based on 18.04](https://github.com/RIOT-OS/RIOT/blob/268e931f1c07e30c9ce87c92e3e352376556d424/Vagrantfile#L10).
Just read and compare the version. The brave could also try the vagrant image and check the ubuntu version using `lsb_release`
https://forum.riot-os.org/t/reproducible-developer-setup-for-riot/3830/12
> tools/vagrant: fix Ubuntu version in README

- .murdock.yml
Debugging the weird "trying.tmp" / "staging.tmp" builds in https://github.com/RIOT-OS/RIOT/pull/18910, I think I realize what's happening:
1. PR changes .murdock.yml, changing the .murdock.yml to not built .tmp branches
2. bors pushes master to .tmp (causing a build) -> murdock schedules a build
3. bors merges the PR commits
4. bors pushes the merged branch to .tmp
So, there's a push event that does not yet include the .murdock.yml changes, so the spurious build gets scheduled.
This PR cuts out those .murdock.yml changs commits from #18910, so that one can be built with the configuration in place.
#18910
> CI: update murdock yml [backport 2022.10]

- makefiles/tools/gdb.inc.mk
In an ideal world everyone would just install `gdb-multiarch` and be happy. However, some MCUs need magic GDB versions sprinkled with unicorn-stardust-Espressif-patches...
Since there is little reason to have `$(target)-gdb` installed in addition to `gdb-multiarch` if `gdb-multiarch` would work fine, let's assume the user wants to use `$(target)-gdb` when present over `gdb-multiarch`.
```
USEMODULE=esp_jtag make BOARD=esp32-ethernet-kit-v1_2 PROGRAMMER=openocd OPENOCD=openocd-esp32 debug -C examples/default
```
In `master`:
```
/home/maribu/Repos/software/RIOT/dist/tools/openocd/openocd.sh debug /home/maribu/Repos/software/RIOT/examples/default/bin/esp32-ethernet-kit-v1_2/default.elf
Open On-Chip Debugger v0.11.0-snapshot (2022-10-21-10:40) …
```
> makefiles/tools/gdb.inc.mk: prefer $(target)-gdb over gdb-multiarch [backport 2022.10]

- boards/arduino-zero/Kconfig
- boards/arduino-zero/Makefile.features
- boards/common/arduino-zero/Kconfig
- boards/common/arduino-zero/Makefile.features
- boards/stm32f429i-disc1/Kconfig
- boards/stm32f429i-disc1/Makefile.features
This PR tries to fix the [problems with `tinyUSB` in nightlies](https://ci.riot-os.org/details/d11b383ba0cd45048ed6f8d98abbc0de).
- The `tinyusb_device` feature had to be moved from `boards/common/arduino-zero` definition to the `boards/arduino-zero` definition because the common `arduino-zero` features are also used by `wemos-zero` which uses the `highlevel_stdio` feature via the `stdio_cdc_acm` module.
- The `tinyusb_device` feature had to be removed from Kconfig of board `stm32f429i-disco` since it uses the `highlevel_stdio` feature via the `stdio_cdc_acm` module.
Green CI
> pkg/tinyusb: fix Kconfig problems

- dist/tools/compile_commands/compile_commands.py
This fixes generating the compile commands with localization enabled GCC and non-English shell locale. The python script uses regexes to extract the required information. These only match on the default English output. GCC supports localized output messages which break the regexes used. Instead of matching any possible localization, this fix forces the C locale for message output on the compiler invocation, thus ensuring the regexes can match.
Needed: arm-none-eabi.gcc with localization support and non-English system locale.
Invoke the compile-commands make target (`make compile-commands`).
It should generate the `compile_commands.json` file correctly.
None found, fix was trivial enough to fix it directly.
> Ensure C locale when querying the compiler for compile commands

- cpu/sam0_common/periph/i2c.c
See description in #19008 . I modified `_read` and `_write` in `cpu/sam0_common/periph/i2c.c` in order to use the declared `len` parameter.
> sam0_common: use size_t len for I2C transfers (fixes #19008) [backport 2022.10]

- cpu/arm7_common/include/VIC.h
- cpu/lm4f120/include/cpu_conf.h
- sys/include/bitfield.h
This adds wrapper functions for all the bitfield functions that write to the bitfield, to allow two (or more) threads to set/clear bits on the bitfield.
This uses `irq_disable()` as the critical section that modifies the bitfield is shorter than a `mutex_lock()`.
This just adds a 2nd `_atomic()` variant of each function that wraps the original function within `irq_disable()`/`irq_restore()`.
> sys/bitfield: add atomic variants of write functions

- dist/tools/doccheck/exclude_patterns
- sys/include/net/coap.h
- sys/include/net/gnrc/netif.h
- sys/include/net/nanocoap.h
Those are some minor changes that have accumulated in a downstream branch.
They are just some minor quality of life improvements, no logic changes.
- `gnrc_netif_ipv6_group_XXX()` functions don't modify the parameter, allow them to take a `const` pointer
- add a definition for CoAP code 5.29
- turn `coap_szx2size()` into a macro so it can be used to initialize byte arrays.
> gnrc & coap: misc minor changes

- drivers/include/net/netdev/ieee802154_submac.h
- drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c
- sys/Makefile.dep
- sys/net/link_layer/ieee802154/submac.c
Migrate `ieee802154_submac` and `netdev_ieee802154_submac` to `ztimer`.
If it compiles, everything should be fine ... `ztimer_xtimer_compat` already did the same thing.
> ieee802154_submac: migrate to ztimer

- drivers/at86rf215/at86rf215.c
- drivers/at86rf2xx/at86rf2xx_netdev.c
- drivers/kw41zrf/kw41zrf.c
- drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c
- sys/include/net/ieee802154.h
- sys/net/link_layer/ieee802154/Kconfig
Currently, every IEEE802.15.4 netdev enables `NETOPT_ACK_REQ` by default. For some environments those ACK requests aren't required and can be disabled completely
`at86rf2xx`, `at86rf215`, `kw41zrf` and `ieee802154_submac`-based IEEE802.15.4 MACs shall respect this option
> net/ieee802154: make default ack request configurable

- drivers/include/sht2x.h
- drivers/sht2x/Kconfig
- drivers/sht2x/Makefile.dep
- drivers/sht2x/include/sht2x_params.h
- drivers/sht2x/sht2x.c
- tests/driver_sht2x/Makefile
- tests/driver_sht2x/app.config.test
- tests/driver_sht2x/main.c
This PR provides the following improvements for the SHT2x driver:
- migration to `ztimer` 8a605517f5343532a4cc25866c9bd18818f17d50 and 367549940de3bd8910052334c34af028d4992741
- floating point arithmetics replaced by integer arithmetics f424caebbfec9f2be56aa2337c6cc09dba5b97d6
- fix of sleep times (typical times replaced by maximum times as recommended by the datasheet) 13615c72094b8541ee62c3e8ed5a36dc4d725fd0
- release of the I2C bus during sleep 9415c216cfab734520ef98dd00b350c22f342c60
- Kconfig configuration of sensor parameters added dadbbcb4c328350893db53ba6743d03cb34ecc1c
- no-hold mode is now the default mode instead of the hold mode
Regarding the sleep times: The typical measurement times were used as sleep times. According to the datasheet, typical measurements are only …
> drivers/sht2x: some small improvements

- boards/common/silabs/include/usbdev_cfg_otg_fs.h
- boards/sltb009a/Kconfig
- boards/sltb009a/Makefile.features
- boards/sltb009a/include/periph_conf.h
- boards/stk3600/Kconfig
- boards/stk3600/Makefile.features
- boards/stk3600/include/periph_conf.h
- boards/stk3700/Kconfig
- boards/stk3700/Makefile.features
- boards/stk3700/include/periph_conf.h
- cpu/efm32/Makefile.dep
- cpu/efm32/Makefile.include
- cpu/efm32/include/periph_cpu.h
- cpu/efm32/include/vendor/usbdev_efm32.h
- cpu/efm32/periph/Kconfig
- drivers/usbdev_synopsys_dwc2/usbdev_synopsys_dwc2.c
This PR provides the changes for the Synopsys USB OTG IP core DWC2 driver for EFM32 MCUs. It also provides the changes of the board definition for `stk3600` and `stk3700` for testing.
`tests/usbus_hid` should work on the EFM32 boards `stk3600` (EFM32LG family) and `stk3700` (EFM32GG family).
It is already tested for a `sltb009a` board (EFM32GG12 family).
> drivers/usbdev_synopsys_dwc2: add EFM32 support

- .murdock
Make "bors try" behave like "bors merge", don't do a quick build.
fixes https://github.com/RIOT-OS/murdock-scripts/issues/45
> CI: no quickbuild on "bors try"

- examples/gnrc_border_router/Makefile
The space inside the expression made the ifneq always non-equal; the intended behavior is "if we're using any of these interfaces, or REUSE_TAP is set".
> examples/gnrc_border_router: Restore UHCP conditional default

- .murdock
This PR extends the list of boards used for per PR quickbuilds. In master only 4 are used and they only cover ARM, native and esp32. The list is extended with
- another ARM based board from STM32 because STM32 represent a large part of boards supported by RIOT
- one RISCV with hifive1b
- one AVR with atmega256rfr2-xpro
- one esp32s3 with esp32s3-devkit
Also the list of boards is sorted with one board per line to ease reviews/updates of this variable.
Normally this should almost double the build time of quick builds (which is in the worst case ~5 minutes at the moment).
Green Murdock but takes twice the time for quick builds
None
> .murdock: extend quickbuild boards list

- cpu/nrf5x_common/include/periph_cpu_common.h
- cpu/nrf5x_common/periph/timer.c
The fallback implementation of timer_set() in `drivers/periph_common` is known to fail on short relative sets. This adds a robust implementation.
Run `tests/periph_timer_short_relative_set` at least a few dozen times (or use https://github.com/RIOT-OS/RIOT/pull/19030 to have a few dozen repetitions of the test case in a single run of the test application). It should now succeed.
None
> cpu/nrf5x_common: implement timer_set()

- dist/tools/doccheck/exclude_patterns
- drivers/ds3231/include/ds3231_params.h
- drivers/include/ds3231.h
Two changes:
- Remove the text stating that setting alarms is not yet supported, because it is, since PR #16180
- Document DS3231_PARAM_INT_PIN
This is only a documentation fix, so there is not code to test.
Support for setting alarms was implemented in PR #16180
> drivers/ds3231 fix docs, alarms are supported

- cpu/native/include/native_internal.h
- cpu/native/include/netdev_tap.h
- cpu/native/irq_cpu.c
- cpu/native/native_cpu.c
- cpu/native/netdev_tap/netdev_tap.c
- cpu/native/periph/timer.c
- cpu/native/tramp.S
This PR removes code that was used to support macOS as native target. 
macOS / `__MACH__` is no longer supported by RIOT on master.
If murdock is happy, that should be enough.
> native: Remove code used for __MACH__ target

- Makefile.include
It turns out that `make clean all -j 16` previously failed every second time, as a dependency to a generated header (`preprocessor_succesor.h` in this case) is checked and considered to be up to date before running the `clean` target. However, after the `clean` target it is removed.
This fixes:
```
$ BOARD=nrf52840dk make -C examples/emcute_mqttsn clean all --jobs 16
make: Entering directory '/home/maribu/Repos/software/RIOT/examples/emcute_mqttsn'
make: Circular clean <- clean dependency dropped.
Building application "emcute_mqttsn" for "nrf52840dk" with MCU "nrf52".
[...]
cc1: error: /home/maribu/Repos/software/RIOT/examples/emcute_mqttsn/bin/nrf52840dk/preprocessor: No such file or directory [-Werror=missing-include-dirs]
[...]
```
Run
```
$ BOARD=nrf52840dk make -C …
```
> build system: Fix parallel build with clean

- .github/workflows/tools-buildtest.yml
- dist/tools/mosquitto_rsmb/Makefile
This PR updates the riot-action used to build the tools. This action is based on a Docker image that is still using Ubuntu 18.04. The [action was updated to use 22.04](https://github.com/aabadie/riot-action/commits/main).
Updating the Ubuntu version to 22.04 revealed a build issue with mosquitto.rsmb that is fixed by d0319304ae5ccc9d0547d8cade6505d8e74f538e. The issue was fixed upstream so just a version bump is enough.
Green CI, especially the tools-buildtest action.
None
> .github/tools-buildtest: use latest version of riot-action and fix build issue with mosquitto.rsmb

- cpu/qn908x/include/periph_cpu.h
- cpu/qn908x/periph/timer.c
This fixes test failures in tests/periph_timer_short_relative_set.
Note: This differs a bit from the implementation in e.g. nRF5x or STM32 in that it always briefly pauses the timer. The issue is that when running the timer can take a few ticks to actually react to the new compare target. So even if the previously written target is still in the future, the timer may not fire anyway. Pausing the timer while setting and setting the target at least one higher than the current count reliably triggers the IRQ.
Run `tests/periph_timer_short_relative_set` at least a few dozen times (or use https://github.com/RIOT-OS/RIOT/pull/19030 to have a few dozen repetitions of the test case in a single run of the test application). It should now succeed.
None
> cpu/qn908x/periph_timer: Implement timer_set()

- tests/thread_float/main.c
If the regular context switches are triggered too fast, slow MCUs will be able to spent little time on actually progressing in the test. This will scale the IRQ rate with the CPU clock as a crude way too keep load within limits.
The unit test should now pass on the Microduino CoreRF
```
$ make BOARD=microduino-corerf AVRDUDE_PROGRAMMER=dragon_jtag -C tests/thread_float flash test
make: Entering directory '/home/maribu/Repos/software/RIOT/tests/thread_float'
Building application "tests_thread_float" for "microduino-corerf" with MCU "atmega128rfa1".
[...]
text	  data	   bss	   dec	   hex	filename
12834	   520	  3003	 16357	  3fe5	/home/maribu/Repos/software/RIOT/tests/thread_float/bin/microduino-corerf/tests_thread_float.elf
avrdude -c dragon_jtag -p m128rfa1  -U …
```
> tests/thread_float: do not overload slow MCUs with IRQs

- cpu/stm32/include/periph/cpu_timer.h
- cpu/stm32/periph/timer.c
The fallback implementation of timer_set() in `drivers/periph_common` is known to fail on short relative sets. This adds a robust implementation.
Run `tests/periph_timer_short_relative_set` at least a few dozen times (or use https://github.com/RIOT-OS/RIOT/pull/19030 to have a few dozen repetitions of the test case in a single run of the test application). It should now succeed.
None
> cpu/stm32/periph_timer: implement timer_set()

- pkg/esp8266_sdk/patches/0001-bootloader-remove-compile-time-from-banner.patch
This PR fixes the problem with the compilation of the [nightlies](https://ci.riot-os.org/details/1f6a6179c0b74210940e84a6ea6e619d).
The compilation of the bootloader has been added with PR #19074. The compile time has been removed from the banner in the bootloader to fix the problem of different hashes when compiling with and without `TEST_KCONFIG`.
Green CI.
> cpu/esp8266/bootloader: remove compile time from banner

- cpu/sam0_common/periph/rtc_rtt.c
Related to #18851 
This fixes an unused function error when compiling the gnrc_networking_mac example using LLVM as toolchain.
The fix works by only including the function when it is actually needed.
> cpu/sam0_common/periph: Fix compilation with LLVM 

- boards/microbit/Makefile.include
this increases the timeout for tests run by murdock on emulated microbit (accounting for startup of qemu)
murdock
#17894
> board/microbit: increase testtimeout for emulated testing

- boards/qn9080dk/Makefile.include
With `MOST_RECENT_PORT=1` the TTY interface of the most recently connected board with an embedded NXP debugger is selected. If only a single board with an embedded NXP debugger is selected, this will automatically connect to the correct board using:
```
make term MOST_RECENT_PORT=1
```
Run `make term MOST_RECENT_PORT=1` with a qn9080dk board and some non-NXP boards attached. It should reliably select the qn9080dk regardless of TTY names and order they were connected.
None
> boards/qn9080dk: add TTY_BOARD_FILTER

- sys/include/net/coap.h
- sys/net/application_layer/nanocoap/sock.c
If an empty ACK was received and a payload is expected, wait for the separate response.
~~*still untested*~~
As @chrysn suggested: run aiocoap's `./server.py` and `tests/nanocoap_cli`, then fetch `/other/separate`:
```
> ncget coap://[fe80::90a7:a6ff:fe4b:2e32]/other/separate -
Three rings for the elven kings under the sky, seven rings for dwarven lords in their halls of stone, nine rings for mortal men doomed to die, one ring for the dark lord on his dark throne.
```
While on `master` no response is printed:
```
> ncget coap://[fe80::90a7:a6ff:fe4b:2e32]/other/separate -
>
```
> nanocoap_sock: fix handling empty ACKs with separate response

- cpu/esp32/include/sdkconfig_esp32c3.h
- cpu/esp32/include/sdkconfig_esp32s3.h
This PR provides a fix for the USB Serial/JTAG interface for ESP32C3.
When using USB Serial/JTAG/OTG/CDC, USB should be enabled in `phy_init`, otherwise the USB interface is not working properly. The problem was described https://github.com/espressif/esp-idf/issues/8046 and fixed with https://github.com/espressif/esp-idf/commit/93be7d5192a33df8bc97c5ebc6cb3b06b054a213:
```
#if CONFIG_ESP_PHY_ENABLE_USB
phy_bbpll_en_usb(true);
#endif
```
However, to work correctly, `CONFIG_ESP_PHY_ENABLE_USB` which was not the case for ESP32-C3.
Without this PR the USB Serial/JTAG interface is not working correctly when WiFi is used:
```
CFLAGS='-DESP_WIFI_SSID=\"ssid\" -DESP_WIFI_PASS=\"pass\"' USEMODULE=esp_wifi BOARD=esp32c3-devkit make -j8 -C examples/gnrc_networking flash
```
Using OpenOCD then fails: …
> cpu/esp32c3: fix SDK configuration for USB PHY

- boards/hamilton/include/board.h
The TMP006 driver has been renamed to TMP00x, as it (now) supports both TMP006 and TMP007 infrared thermopile sensors. However, the board configuration was never updated to match the new names. This fixes the issue.
Someone with the board could test if the TMP006 driver now starts to work again. Otherwise, it should be relatively straight forward to "test this by code review" (tm).
None
> boards/hamilton: Fix TMP00x parameters

- tests/periph_uart/main.c
If a board uses e.g. stdio via CDC ACM or RTT there is no reason to exclude the stdio uart from being used in `tests/periph_uart`.
In fact, the UART that can be used for stdio may well be the only UART that is exposed by the device. 
Without this patch
```
2023-01-06 16:10:20,282 # > init 0 9600
2023-01-06 16:10:20,285 # Error: The selected UART_DEV(0) is used for the shell!
```
With this patch
```
2023-01-06 16:18:08,291 # > init 0 9600
2023-01-06 16:18:08,295 # Success: Initialized UART_DEV(0) at BAUD 9600
2023-01-06 16:18:08,549 # UARD_DEV(0): test uart_poweron() and uart_poweroff()  ->  [OK]
```
> tests/periph_uart: only exclude STDIO_UART_DEV if stdio_uart is used

- sys/include/net/nanocoap_sock.h
This is an old holdover, all in-tree users have been converted to use `nanocoap_sock_get()` or similar functions.
Should we also drop `nanocoap_request()` in favor of `nanocoap_sock_request()`?
> nanocoap_sock: deprecate nanocoap_get()

- drivers/ws281x/vt100.c
The VT100 backend had a little confusion between array size and size in bytes, leading to a read beyond the end of the buffer.
This produced garbage colors on the terminal.
make -C tests/driver_ws281x BOARD=native all term
no longer prints garbage colors at the end of the line
> drivers/ws281x: fix out-of-bounds read on native

- boards/weact-f401cc/doc.txt
- boards/weact-f401ce/doc.txt
- boards/weact-f411ce/doc.txt
The  Weact boards with STM32F4x1Cx MCU's have their PWM outputs enabled. But these currently do not show in the the documentation. This PR updates the documentation for these 3 boards.  
I rebuild the documentation with `make doc` and checked the resulting 3 html files. 
Fixes this issue: https://github.com/jhaand/RIOT/issues/1
Also referred to in this issue: https://github.com/RIOT-OS/RIOT/issues/19103
Discussed @maribu and @benpicco on matrix [link](https://matrix.to/#/!pqHdpanAvkJvlCwUDE:matrix.org/$lEMfOAG5rGGrkEjfJcsg0nC1Ebj4vlitvH9zm8uP-NM?via=matrix.org&via=rubdos.be&via=schleiser.de)
> Documentation: Document PWM and other Peripherals for Weact STM32F4x1Cx boards

- dist/tools/usb-serial/README.md
- dist/tools/usb-serial/find-tty.sh
- dist/tools/usb-serial/list-ttys.sh
Refactor the old bash scripts to use `ttys.py` instead and update the documentation.
The pi fleet should still work without modification.
Fixes https://github.com/RIOT-OS/RIOT/issues/15814
> dist/tools/usb-serial: Clean up legacy scripts

- core/lib/include/macros/utils.h
- cpu/atmega_common/periph/rtt.c
- cpu/esp_common/include/esp_common.h
- cpu/native/mtd/mtd_native.c
- cpu/sam0_common/periph/flashpage.c
- cpu/stm32/periph/eth.c
- drivers/at24cxxx/at24cxxx.c
- drivers/lsm6dsl/lsm6dsl.c
- drivers/mtd_sdcard/mtd_sdcard.c
- drivers/mtd_spi_nor/mtd_spi_nor.c
- pkg/lua/contrib/lua_run.c
- sys/can/isotp/isotp.c
- sys/hashes/aes128_cmac.c
- sys/hashes/sha3.c
- sys/include/atomic_utils.h
- sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_region.c
- sys/net/gnrc/netif/gnrc_netif_device_type.c
- sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c
- sys/stdio_rtt/stdio_rtt.c
- sys/test_utils/benchmark_udp/benchmark_udp.c
- tests/bench_sys_atomic_utils/main.c
- tests/bench_sys_base64/main.c
- tests/driver_pn532/main.c
- tests/mtd_mapper/main.c
The macros CONCAT(), MIN(), and MAX() are defined over and over again in RIOT's code base. This de-duplicates the code by moving the macros to a common place.
Generated binaries don't change, as this only a de-duplication of macros that doesn't change their definition.
None
> core/lib: Add macros/utils.h header

- boards/hifive1b/Makefile.include
- Cleaning up flash config
- Only defaulting to J-Link as flasher when actually installed
- Add TTY_BOARD_FILTER to more reliably select the TTY of the HiFive1b board
- Flashing should still work
- Flashing should prefer J-Link over OpenOCD when both are available
- Flashing should prefer OpenOCD over J-Link when J-Link is not found
None
> boards/hifive1b: minor improvements

- boards/hamilton/doc.txt
- boards/hamilton/include/board.h
The doc of the board is still suboptimal, but at least an image to identify what board this is and a link to further information is a starting point.
The static tests will do.
None.
> boards/hamilton: Add minimal doc

- boards/common/nrf52/Makefile.include
For nRF52 J-Link was intended to be preferred as programmer over OpenOCD when both are available, but falling back to OpenOCD when JLinkExe is not found in `$PATH`. However, there was call the shell missing to actually detect `JLinkExe`.
E.g. `make BOARD=nrf52840dk -C examples/default flash` should use J-Link again as default when both are installed.
None
> boards/common/nrf52: Fix detection of JLinkExe

- cpu/riscv_common/periph/coretimer.c
Previously, timer_clear() was a no-op, resulting in spurious IRQs from already canceled timeouts. This fixes the issue.
```
$ make BOARD=hifive1b flash test -C tests/periph_timer
[...]
Bench Clock Reset Complete
ATE0-->ATE0
OK
AT+BLEINIT=0-->OK
AT+CWMODE=0-->OK
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-773-g441b69)
Test for peripheral TIMERs
Available timers: 1
Testing TIMER_0:
TIMER_0: initialization successful
TIMER_0: stopped
TIMER_0: set channel 0 to 5000
TIMER_0: starting
TIMER_0: channel 0 fired at SW count  3164199 - init:  3164199
TEST SUCCEEDED
```
(In `master`, the test fails with a spurious IRQ.)
https://github.com/RIOT-OS/RIOT/issues/18976
> cpu/riscv_common/periph_timer: Fix timer_clear()

- boards/native/Makefile.include
Even Debian [oldstable is now at glibc 2.28](https://packages.debian.org/source/buster/glibc), so it is safe to assume that nobody needs this anymore.
This also fixes garbage on the terminal on musl systems, where `ldd --version` is not supported (and output on `stderr` was not redirected to `/dev/null`).
The CI will check if this breaks the `native` board.
None
> boards/native: Drop backward compatibility code for glibc <= 2.17

- boards/seeedstudio-gd32/Kconfig
- boards/seeedstudio-gd32/include/periph_conf.h
- cpu/gd32v/clock.c
This PR fixes the following issus of the clock configuration which led to highly deviating peripheral clocks so that the UART interface was not usable in my case:
1. Setting the `RCU_CTL` register just to the IRC8M bit also removes the IRC8M calibration and trim adjust value in this register. Therefore IRC8M calibration and trim adjust value have to be preserved and the IRC8M has to be set.
2. `CLOCK_HXTAL` is a value and not a flag, so that shifting to the left changes anything in the register but does not set the PLLSEL bit. `RCU_CFG0_PLLSEL_Msk` has to be used instead to set the PLLSEL bit.
3. `CONFIG_BOARD_HAS_HXTAL` is used to indicate that the board has an HXTAL connected. If the HXTAL is present, it is used as PLL clock source. But if the HXTAL is not present, the half IRC8M clock …
> cpu/gd32v: fix and extend Kconfig clock settings

- boards/hip-badge/doc.txt
The [board documentation](https://doc.riot-os.org/group__boards__hip__badge.html) does exclude the entire body of the documentation.
Fix this by removing the faux-comment. 
Doc should now render correctly.
> boards/hip-badge: fix doc rendering

- makefiles/cargo-targets.inc.mk
Update the list of target triples to match
`makefiles/arch/riscv.inc.mk`. This fixes compilation with toolchains other than the obsolete toolchain that uses the incorrect `riscv-none-embed` triple.
```
make BOARD=hifive1b -C examples/rust-gcoap
```
Fails on `master` with a recent RISC-V toolchain, but hopefully compiles with this PR.
None
> makefiles/cargo-targets.inc.mk: Fix RISC-V target

- sys/ztimer/mock.c
Some ztimer_mock static functions need to be guarded.
This issue is not triggered by CI. To test manually, try
`make -C tests/unittests tests-ztimer64`, it should fail on master, succeed with this PR.
Fixes https://gist.github.com/riot-ci/ab2129a707fa5eb413a4a161d90ce3ac/aae0dceadb40acacc99d78ce9f0045c860bbe470#file-task_01-03-tests-ztimer64_result-md.
> sys/ztimer: ztimer_mock: guard ztimer_ondemand static functions

- sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.h
- sys/net/gnrc/network_layer/ipv6/nib/nib.c
I'm still trying to find a proper fix for #16988 (border router does ARSM on the 6lo interface) but still no avail.
But as a first step, clean up `_resolve_addr()` by getting rid of unececary pre-processor conditionals and moving logic blocks to separate functions. 
This makes it easier to figure out what's actually going on.
There should be no changes to the logic.
All tests should continue yielding the same results as before.
> gnrc_ipv6_nib: clean up _resolve_addr()

- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/sock.c
- tests/nanocoap_cli/nanocli_client.c
We support GET, PUT and POST, so also implement DELETE.
This can be tested with `examples/gcoap_fileserver`:
```
main(): This is RIOT! (Version: 2022.10-devel-1142-gbec06-nanocoap_sock_delete)
nanocoap test app
> url delete coap://[fe80::58b0:8ff:fe67:ad82]/vfs/core
nanocoap: send 13 bytes (5 tries left)
nanocoap: waiting for response (timeout: 2125925 µs)
nanocoap: response code=202
> url delete coap://[fe80::58b0:8ff:fe67:ad82]/vfs/core
nanocoap: send 13 bytes (5 tries left)
nanocoap: waiting for response (timeout: 2772702 µs)
nanocoap: response code=404
res: Unknown error -6
```
> nanocoap_sock: implement nanocoap_sock_delete()

- sys/Makefile.dep
- sys/include/net/nanocoap/link_format.h
- sys/net/application_layer/nanocoap/link_format.c
- sys/shell/Makefile.dep
- sys/shell/cmds/nanocoap_vfs.c
This moves the code to parse the [link format](https://www.rfc-editor.org/rfc/rfc6690.html) from the `ncget` shell command to a common location and makes it more general.
A callback is called for each resource path in the directory.
`ncget` still works as before for listing directories:
```
> ncget coap://[fe80::2454:cfff:fea7:4598]/
/fw/
/suit_manifest.signed
/suit_manifest
/payload.bin
> ncget coap://[fe80::2454:cfff:fea7:4598]/fw/
/fw/suit_update/
> ncget coap://[fe80::2454:cfff:fea7:4598]/fw/suit_update/
/fw/suit_update/same54-xpro/
/fw/suit_update/saml21-xpro/
```
> nanocoap_link_format: add helper function to parse Link Format

- .github/workflows/check-commits.yml
- .github/workflows/check-labels.yml
They were doing completely seperate things.
Also, `check-commits` was unnecessarily re-run for every label change due to shared `on:`.
This'll make it easier to get #19101 in.
> CI: seperate check-labels and check-commits workflows

- sys/net/gnrc/pktbuf/include/pktbuf_internal.h
- sys/net/gnrc/pktbuf_malloc/gnrc_pktbuf_malloc.c
- sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
- sys/net/gnrc/pktbuf_static/include/pktbuf_static.h
Since we are now using C11, we can make use of `alignas()` provided by `<stdalign.h>` to make the alignment code easier to read.
I didn't expect this to change binaries, but is safes 4 bytes. `elf_diff` shows that the compiler (at least GCC 11.3.0) was not able to detect that `gnrc_pktbuf_static_buf` was just an alias for `_pktbuf_buf`. That makes sense since it would be hard without LTO to rule out external writes to `gnrc_pktbuf_static_buf`, unless one would have added a `const` (to the pointer, not to the data the pointer points to).
The [output of `elf_diff`](https://mari-bu.de/pr_18348_gnrc_pktbuf_static_elf_diff.html) looks otherwise quite unscary.
Also:
```
$ make BOARD=nucleo-f767zi -C tests/unittests/ tests-pktbuf flash test
make: Entering directory …
```
> sys/net/gnrc/pktbuf_static: make use of alignas()

- drivers/include/slipdev.h
- drivers/slipdev/slipdev.c
This implements the SLEEP and STANDBY state analogous to DOSE. (In Standby, send will wake the device from sleep).
If `slipdev_stdio` is used this functionality is not available as we can not put the UART to sleep if it's used for stdio.
`ifconfig <id> set state sleep` and `ifconfig <id> set state idle` should work.
> drivers/slipdev: implement sleep states

- pkg/esp8266_sdk/Makefile
This PR (hopefully) fixes the problem of different binary hashes for the same application in subsequent compilations.
Patching a package creates a new HEAD of the package repository. Using `git describe --tag` to generate a version string used for the ESP8266 bootloader therefore generates a different version string for each new compilation, which in turn results in different hash values of the binaries for the same application in subsequent compilations in CI. To use the commit in `git describe --tag` for commit used by the package, the commit has to specified in the command.
Green CI
> pkg/esp8266_sdk: fix version string generation

- cpu/esp32/doc.txt
- dist/tools/esptools/export.sh
This PR re-adds the setting of the default value of the variable `IDF_TOOLS_PATH` which was accidentally removed with PR #18385.
The `IDF_TOOLS_PATH` variable is used by the ESP-IDF to define the path where the Espressif toolchain is installed. Reusing this variable to set the path of the toolchain in RIOT allows the use of an existing Espressif toolchain if it has already been installed with ESP-IDF. If the variable is not defined it is set to `${HOME}/.espressif` as described in [documentation](https://doc.riot-os.org/group__cpu__esp32.html#esp32_local_toolchain_installation):
```
if [ -z ${IDF_TOOLS_PATH} ]; then
IDF_TOOLS_PATH=${HOME}/.espressif
fi
```
Unfortunatly were these 3 lines be removed in `dist/tools/esptools/export.sh` accidentially with #18385 so that it became necessary to …
> dist/tools/esptools/export.sh: fixes IDF_TOOLS_PATH default setting

- sys/ztimer/mock.c
Some ztimer_mock static functions need to be guarded.
This issue is not triggered by CI. To test manually, try
`make -C tests/unittests tests-ztimer64`, it should fail on master, succeed with this PR.
Fixes https://gist.github.com/riot-ci/ab2129a707fa5eb413a4a161d90ce3ac/aae0dceadb40acacc99d78ce9f0045c860bbe470#file-task_01-03-tests-ztimer64_result-md.
> sys/ztimer: ztimer_mock: guard ztimer_ondemand static functions [backport 2023.01]

- pkg/esp8266_sdk/Makefile
This PR (hopefully) fixes the problem of different binary hashes for the same application in subsequent compilations.
Patching a package creates a new HEAD of the package repository. Using `git describe --tag` to generate a version string used for the ESP8266 bootloader therefore generates a different version string for each new compilation, which in turn results in different hash values of the binaries for the same application in subsequent compilations in CI. To use the commit in `git describe --tag` for commit used by the package, the commit has to specified in the command.
Green CI
> pkg/esp8266_sdk: fix version string generation [backport 2023.01]

- boards/common/qn908x/Makefile.include
- boards/qn9080dk/Makefile.include
- boards/qn9080dk/doc.txt
- document that the QN9080DK has an alternative firmware for the debugger/programmer that supports J-Link
- allow selecting the debugger firmware via parameter / environment variable
- add `JLINK_DEVICE` parameter to allow flashing via J-Link
- read the doc generated by the CI
- run `make flash BOARD=qn9080dk QN9080DK_JLINK=1` and `make flash BOARD=qn9080dk QN9080DK_JLINK=0`
- Confirm that in the former case flashing uses J-Link (if installed) or OpenOCD using the jlink interface (if J-Link is not installed)
- Confirm that in the second case (`QN9080DK_JLINK=0`) flashing uses OpenOCD and the dap interface.
- I tested this with the actual hardware, but it is sufficient to just check if the invocation of the flashing script is sane
None
> boards/qn9080dk: Improve doc and add J-Link support

- boards/seeedstudio-gd32/Kconfig
This PR fixes the wrong default value of `CLOCK_HXTAL` in Kconfig introduced with PR #19109. It was accidentally set to the default value of 80 MHz instead of 8 MHz.
```
python3 dist/tools/compile_test/compile_like_murdock.py -a tests/shell -b seeedstudio-gd32 -j8
```
Without the PR the command gives:
```
tests/shell                    seeedstudio-gd32               FAIL: Kconfig hash mismatch
```
WIth the PR the compile test should pass:
```
tests/shell                    seeedstudio-gd32               PASS
```
> boards/seeedstudio-gd32: fix HXTAL clock in Kconfig

- boards/seeedstudio-gd32/Kconfig
This PR fixes the wrong default value of `CLOCK_HXTAL` in Kconfig introduced with PR #19109. It was accidentally set to the default value of 80 MHz instead of 8 MHz.
```
python3 dist/tools/compile_test/compile_like_murdock.py -a tests/shell -b seeedstudio-gd32 -j8
```
Without the PR the command gives:
```
tests/shell                    seeedstudio-gd32               FAIL: Kconfig hash mismatch
```
WIth the PR the compile test should pass:
```
tests/shell                    seeedstudio-gd32               PASS
```
> boards/seeedstudio-gd32: fix HXTAL clock in Kconfig [backport 2023.01]

- .github/workflows/release-test.yml
Hoping to increase the audience for Release tests notifications beyond me ;-).
Will start a test run
> gh-actions: report release-tests result to Matrix

- boards/common/makefiles/stdio_cdc_acm.dep.mk
- tests/congure_abe/tests/01-run.py
- tests/congure_quic/tests/01-run.py
- tests/congure_reno/tests/01-run.py
- tests/congure_test/tests/01-run.py
Some tests may fail spuriously with `stdio_cdc_acm`, since the `tty` might not exist yet. This configures a small delay after resetting for `testutils` and also piggybacks the honoring of that delay for the `riotctrl`-based tests.
CI should pass all tests. Maybe we should also run `tests-on-iotlab` for this PR.
None
> boards: common: stdio_cdc_acm: let tests wait a bit for serial port

- makefiles/utils/strings.mk
The Makefile function `version_is_greater_or_equal` is used to check if a version of GNU Make is at least the required one. However, it has the built-in assumption the version numbers have to format x.y.z, but Alpine Linux currently ships GNU Make 4.4. This results in `$(call _pad_number,3,)` which runs `printf '$03d' ''` in the shell, which is not valid.
This fixes the issue by making `_pad_number` more robust by fall back to printing `0` with the given padding, if the number given to print is empty.
Append
```Makefile
$(info A=$(call version_is_greater_or_equal,4.2.0,4.2.0))
$(info B=$(call version_is_greater_or_equal,4.2,4.2.0))
$(info C=$(call version_is_greater_or_equal,4.1,4.2.0))
$(info D=$(call version_is_greater_or_equal,4.1.9,4.2.0))
$(info E=$(call …
```
> makefiles/utils/strings.mk: Fix version_is_greater_or_equal

- doc/doxygen/src/using-rust.md
- examples/rust-gcoap/Makefile
- examples/rust-hello-world/Makefile
Since Rust 1.65, we don't depend on anything nightly any more. This changes the examples and documentation to use stable.
* Green CI with tests enabled
* Look at changed documentation ([rendered](https://ci.riot-os.org/results/2923b30a4ba04dbface1ed38fb6aae12/doc-preview/using-rust.html#toolchain))
<del>Note that these will *not* pass yet: This needs a CI update (no PR associated: Any CI image built from now on will do).</del>
A follow-up will simplify things a bit further, but that will depend on CI to have made stable the default, which is a later step in what is a bit of a lock-step game:
> rust: Use stable Rust [backport 2022.10]

- makefiles/utils/strings.mk
The Makefile function `version_is_greater_or_equal` is used to check if a version of GNU Make is at least the required one. However, it has the built-in assumption the version numbers have to format x.y.z, but Alpine Linux currently ships GNU Make 4.4. This results in `$(call _pad_number,3,)` which runs `printf '$03d' ''` in the shell, which is not valid.
This fixes the issue by making `_pad_number` more robust by fall back to printing `0` with the given padding, if the number given to print is empty.
Append
```Makefile
$(info A=$(call version_is_greater_or_equal,4.2.0,4.2.0))
$(info B=$(call version_is_greater_or_equal,4.2,4.2.0))
$(info C=$(call version_is_greater_or_equal,4.1,4.2.0))
$(info D=$(call version_is_greater_or_equal,4.1.9,4.2.0))
$(info E=$(call …
```
> makefiles/utils/strings.mk: Fix version_is_greater_or_equal [backport 2023.01]

- cpu/esp32/doc.txt
- cpu/native/include/native_internal.h
- drivers/include/ethos.h
- drivers/include/slipdev.h
- makefiles/dependency_resolution.inc.mk
- makefiles/stdio.inc.mk
- pkg/tinyusb/doc.txt
- sys/include/net/telnet.h
- sys/include/stdio_nimble.h
- sys/include/stdio_rtt.h
- sys/include/stdio_semihosting.h
- sys/include/stdio_uart.h
- sys/include/usb/usbus/cdc/acm.h
- sys/net/application_layer/telnet/stdio_telnet.c
- sys/stdio_null/doc.txt
- sys/stdio_null/stdio_null.c
- sys/stdio_udp/Makefile
- sys/stdio_udp/doc.txt
- sys/stdio_udp/stdio_udp.c
`stdio_telnet` can sometimes be slow and also a bit heavy when TCP is otherwise not used.
When doing remote debugging, a lost packet isn't usually so bad, so we don't need the reliability we get from telnet.
This adds a stdio via UDP module that can be used with `nc` or `socat`:
Enable the module in e.g. `gnrc_networking`:
USEMODULE += stdio_udp
You will not see any output unless you connect to the instance from a 2nd terminal:
```
$ nc -u fe80::7837:fcff:fe7d:1aaf%tapbr0 2323
help
Command              Description
---------------------------------------
ifconfig             Configure network interfaces
nib                  Configure neighbor information base
ping                 Ping via ICMPv6
pm                   interact with layered PM subsystem
ps                   Prints information …
```
> sys/stdio_udp: add stdio over UDP

- .github/workflows/check-labels.yml
#19120 split check-labels and check-commits into different workflows. At the same time, I removed the `synchronize` event (indicating a change/push to the PR HEAD) for check-labels, as only label changes or reviews change the action's outcome.
But action result status is per-commit, and that's what bors waits for. So check-labels needs to run for each HEAD state, to set it's status on every commit.
#19120
> CI: re-add "synchronize" event to check-labels

- pkg/tinydtls/contrib/sock_dtls.c
- sys/Makefile.dep
- sys/include/net/coap.h
- sys/include/net/nanocoap_sock.h
- sys/include/ztimer.h
- sys/net/application_layer/nanocoap/sock.c
- sys/suit/handlers_command_seq.c
- sys/suit/transport/worker.c
- sys/ztimer/util.c
- tests/nanocoap_cli/Makefile
- tests/nanocoap_cli/main.c
- tests/nanocoap_cli/tinydtls_keys.h
This implements DTLS support for NanoCoAP.
When the `nanocoap_dtls` module is used, the `nanocoap_sock_t` struct is extended with session information.
All NanoCoAP API functions will automatically handle the new transport type, `nanocoap_sock_url_connect()` will automatically select the DTLS socket when a `coaps://` URL is used.
I'm a bit confused by credman. I now define a `CONFIG_NANOCOAP_SOCK_DTLS_TAG` by which NanoCoAP can get the credential tag to select the right credential for the connection without having to add new parameter to the API. This is convenient, but it only allows a single credential to be used with NanoCoAP (which is probably fine for the use case, there is only ever a single endpoint).
The `tests/nanocoap_cli` application works without modification. I used …
> nanocoap_sock: implement DTLS socket

- dist/tools/suit/suit-manifest-generator/suit_tool/get_pubkey.py
- makefiles/suit.base.inc.mk
- sys/suit/handlers_envelope.c
A board may be flashed with a development firmware. The development firmware should accept SUIT updates signed with *both* the development *and* the production key.
Therefore allow to include multiple public keys to verify the SUIT manifest with.
Run `tests/suit_manifest` with multiple keys, e.g.
SUIT_SECS="/home/benpicco/dev/RIOT/keys/default.pem /home/benpicco/.local/share/RIOT/keys/default.pem" make -C tests/suit_manifest all term
The tests should still success even though the 'wrong' key is tried first.
> makefiles/suit: make it possible to accept multiple SUIT keys

- sys/shell/cmds/rtc.c
Should be trivial enough, especially as the difference is hard to spot interactively.
On native, run the default example (and wait for the traffic to settle).
Then, run
```
> rtc poweron
> rtc settime 2022-01-01 00:00:00
> rtc settime 2022-99-01 00:00:00
```
Both still work, but the latter doesn't access unassigned memory any more
This fixes an issue that was submitted anonymously.
> shell/rtc: Fix out of bounds access; document error behavior

- makefiles/toolchain/gnu.inc.mk
With b30efeeb65 a warning was introduced when using `make term` without the proper toolchain installed (e.g. when using BUILD_IN_DOCKER, but `term` outside of the docker). This removes this warning.
Run `make term` for a board where you do not have the toolchain installed. Output such as
```
/bin/sh: line 1: xtensa-esp32-elf-gcc: command not found
```
should disappear with this PR.
Fixes a minor issue introduced in https://github.com/RIOT-OS/RIOT/pull/18935.
> toolchain/gnu.inc.mk: don't check version if CC is not installed

- sys/shell/cmds/rtc.c
Should be trivial enough, especially as the difference is hard to spot interactively.
On native, run the default example (and wait for the traffic to settle).
Then, run
```
> rtc poweron
> rtc settime 2022-01-01 00:00:00
> rtc settime 2022-99-01 00:00:00
```
Both still work, but the latter doesn't access unassigned memory any more
This fixes an issue that was submitted anonymously.
> shell/rtc: Fix out of bounds access; document error behavior [backport 2023.01]

- boards/common/makefiles/stdio_cdc_acm.dep.mk
- tests/congure_abe/tests/01-run.py
- tests/congure_quic/tests/01-run.py
- tests/congure_reno/tests/01-run.py
- tests/congure_test/tests/01-run.py
Some tests may fail spuriously with `stdio_cdc_acm`, since the `tty` might not exist yet. This configures a small delay after resetting for `testutils` and also piggybacks the honoring of that delay for the `riotctrl`-based tests.
CI should pass all tests. Maybe we should also run `tests-on-iotlab` for this PR.
None
> boards: common: stdio_cdc_acm: let tests wait a bit for serial port [backport 2023.01]

- .github/workflows/release-test.yml
When I was testing the new chat posting feature for the release-tests, the tests were not passing... of course [an error snuck in in that case](https://github.com/RIOT-OS/RIOT/actions/runs/3916585600/jobs/6697801134#step:16:14). This fixes this error.
I can start another release tests if desired.
Follow-up on #19102.
> release-tests: fix PASSED chat message

- boards/rpi-pico-w/Kconfig
- boards/rpi-pico-w/Makefile
- boards/rpi-pico-w/Makefile.dep
- boards/rpi-pico-w/Makefile.features
- boards/rpi-pico-w/Makefile.include
- boards/rpi-pico-w/doc.txt
- boards/rpi-pico/include/board.h
- boards/rpi-pico/include/gpio_params.h
This PR adds initial RIOT OS support for the Raspberry Pico W - the Raspberry Pico with a Wifi/Bluetooth Infineon CYW 43439 module (*).
The code is based on PR #15822 and contains changes associated with small differences between RPi Pico and Pico W. The most important is that LED0 is connected to the CYW 43439 module and without PIO (PR #17425) cannot be used (RP2040 and CYW 43439 are connected together using SPI and Pico SDK utilize PIO to program SPI). Current LED0 implementation is similar to one for `native` board and prints appropriate texts on STDIO.      
(*) Currently network connectivity not implemented.
Flash sample program and look at doc:
```
make doc
xdg-open doc/doxygen/html/group__boards__rpi__pico__w.html
```
Based on PR #15822.
Needs PR #17425.
Additional doc:
[Raspberry …
> boards/rpi-pico-w: initial support for rpi pico W board

- cpu/esp32/bootloader/sdkconfig.h
- cpu/esp32/startup.c
- cpu/esp_common/periph/uart.c
This PR fixes issue #19138 that was introduced with PR #19100. It contains the following changes to fix the problems and to improve the UART initialization:
- If `LOG_LEVEL` is greater or equal 4, such as in `tests/log_printfnoformat`, the ESP-IDF config function called for the GPIO pins of the UART will output the configuration with `printf` before the `_GLOBAL_REENT` structure is initialized. This causes a crash during system startup. Therefore the initialization by `syscalls_init` must be called by `earlier in the startup procedure.
- Since PR #19100 it is possible to define:
- other pins for `UART_DEV(0)` than the default pins
- different `UART_DEV(0)` pins for the bootloader and RIOT
To allow correct reinitialization of the UART pins used by the bootloader as well as their usage for …
> cpu/esp32: fix and improve UART initialization

- pkg/Kconfig
- pkg/arduino_adafruit_sensor/Kconfig
- pkg/arduino_adafruit_sensor/Makefile
- pkg/arduino_adafruit_sensor/Makefile.dep
- pkg/arduino_adafruit_sensor/Makefile.include
- pkg/arduino_adafruit_sensor/doc.txt
- pkg/arduino_adafruit_sensor/patches/0001-remove_include_Print_h.patch
- pkg/arduino_adafruit_sensor/patches/0002-add_F_for_string_literals.patch
- pkg/arduino_adafruit_sensor/patches/0003-add_include_string_h.patch
- tests/pkg_arduino_adafruit_sensor/Makefile
- tests/pkg_arduino_adafruit_sensor/Makefile.ci
- tests/pkg_arduino_adafruit_sensor/app.config.test
- tests/pkg_arduino_adafruit_sensor/main.cpp
- tests/pkg_arduino_adafruit_sensor/tests/01-run.py
This PR provides the [Adafruit Unified Sensor Driver](https://github.com/adafruit/Adafruit_Sensor) as package.
There are a number of Adafruit sensor drivers which all use a common base class `Adafruit_Sensor` from the [Adafruit Unified Sensor Driver](https://github.com/adafruit/Adafruit_Sensor). To support such drivers, the Adafruit Unified Sensor Driver is provided as package.
Adafruit sensor driver for ST LSM9DS0 will be provided as separat PR as package for demonstration and testing.
PR #12518 will be rebased for testing to have an Adafruit sensor driver for a sensor for which there is a native driver in RIOT.
Use a board that provides the `arduino` feature and flash
```
BOARD=... make -C tests/pkg_arduino_adafruit_sensor flash test
```
PR #12518 can be used as a more complex test for …
> pkg/arduino_adafruit_sensor: add Adafruit Unified Sensor Driver as package

- cpu/esp32/bootloader/sdkconfig.h
- cpu/esp32/startup.c
- cpu/esp_common/periph/uart.c
This PR fixes issue #19138 that was introduced with PR #19100. It contains the following changes to fix the problems and to improve the UART initialization:
- If `LOG_LEVEL` is greater or equal 4, such as in `tests/log_printfnoformat`, the ESP-IDF config function called for the GPIO pins of the UART will output the configuration with `printf` before the `_GLOBAL_REENT` structure is initialized. This causes a crash during system startup. Therefore the initialization by `syscalls_init` must be called by `earlier in the startup procedure.
- Since PR #19100 it is possible to define:
- other pins for `UART_DEV(0)` than the default pins
- different `UART_DEV(0)` pins for the bootloader and RIOT
To allow correct reinitialization of the UART pins used by the bootloader as well as their usage for …
> cpu/esp32: fix and improve UART initialization [backport 2023.01]

- pkg/fff/Makefile.include
- sys/include/cppunit.hpp
- sys/include/cppunit/cppunit_base.hpp
- sys/include/cppunit/cppunit_expect.hpp
- sys/include/cppunit/cppunit_fff.hpp
- sys/include/irq.hpp
- tests/irq_cpp/Makefile
- tests/irq_cpp/Makefile.ci
- tests/irq_cpp/irq.h
- tests/irq_cpp/main.cpp
- tests/irq_cpp/tests/01-run.py
This adds a C++ wrapper around the `irq.h` API. The wrapper uses RAII to accomplish a convenient and bug resistent use.
A little background: I'm currently writing my master thesis on using C++ for embedded development, at the working group that @maribu is part of. For that I will try to add better C++ support to several parts of RIOT and then do some benchmarking and metrics to compare it with the C implementation. For example, I also plan to add a wrapper around i2c, a std::cout drop-in replacement and probably some more about networks or threads.
I've added a unit test to verify that the IRQ wrapper calls the original `irq` functions as expected. As C++ and wrapper testing isn't done much so far in this project, I've added two additional headers to ease testing:
1.  #17076 - fake …
> sys/irq: Add C++ wrapper using RAII

- SECURITY.md
Our security policy does not contain provisions for the case when what is reported is not what we consider an actual security issue. As it is described now, everything reported through security@ would go through the full treatment, including a point release.
I'm not sure it belongs into the text itself (as it's more about how security reporters interact with the project than internals), but declassification should IMO be backed at least by 3 maintainers, and no strong NACK.
#19141 followed that procedure after some chat on it on the maintainers channel. (In the discussion, I proposed declassification, with 2.5 people supporting it and one "I was about to, but can we be sure nobody is using it?" voice).
> SECURITY: Describe that declassification is an option

- Makefile.dep
- bootloaders/riotboot_tinyusb_dfu/Makefile
- bootloaders/riotboot_tinyusb_dfu/doc.txt
- bootloaders/riotboot_tinyusb_dfu/main.c
- cpu/cortexm_common/Makefile.include
- cpu/nrf52/Makefile.include
- makefiles/boot/riotboot_dfu-util.mk
- pkg/tinyusb/Kconfig
- pkg/tinyusb/Makefile
- pkg/tinyusb/Makefile.dep
- pkg/tinyusb/Makefile.include
- pkg/tinyusb/contrib/include/tinyusb_descriptors.h
- pkg/tinyusb/contrib/include/tusb_config.h
- pkg/tinyusb/contrib/tinyusb.c
- pkg/tinyusb/contrib/tinyusb_descriptors.c
- pkg/tinyusb/dfu/Kconfig.dfu
- pkg/tinyusb/dfu/Kconfig.dfu_rt
- pkg/tinyusb/dfu/Makefile
- pkg/tinyusb/dfu/include/tinyusb_dfu.h
- pkg/tinyusb/dfu/tinyusb_dfu.c
- pkg/tinyusb/doc.txt
- pkg/tinyusb/hw/hw_stm32_fsdev.c
- pkg/tinyusb/hw/hw_stm32_otg.c
- sys/Makefile.dep
- sys/Makefile.include
- sys/riotboot/tinyusb_dfu.c
This PR provides
- the tinyUSB DFU and DFU Runtime support and
- the `riotboot_tinyusb_dfu` bootloader that uses the tinyUSB DFU mode to flash new application images.
~This PR includes PR #18983 for now to be compilable.~
1. Use any board that supports the `riotboot´ and `tinyusb_device` features and flash the bootloader first, for example
```
BOARD=nucleo-f767zi make -C bootloaders/riotboot_tinyusb_dfu flash
```
and check that the `riotboot_tinyusb_dfu` bootloader is in DFU mode:
```
dfu-util --list
```
3. Flash a first application using the following command:
```
FEATURES_REQUIRED=riotboot USEMODULE=tinyusb_dfu BOARD=nucleo-f767zi \
make -C tests/saul PROGRAMMER=dfu-util riotboot/flash-slot0
```
and check that the application starts and is seen as upgradable:
```
dfu-util --list
```
4. …
> bootloaders/riotboot: add tinyUSB DFU support

- examples/gcoap/client.c
Executing the shell command with an URI-Path that doesn't start with a slash results in an assertion error while composing the client side message. This is suboptimal user experience, so add an explicit check for a valid URI-Path and a dedicated error message.
```
$ make BOARD=microbit-v2 -C examples/gcoap flash term
[...]
2023-01-15 22:23:32,512 #  coap get [::1] /.well-known/core
2023-01-15 22:23:32,516 # gcoap_cli: sending msg ID 52272, 23 bytes
2023-01-15 22:23:32,520 # gcoap: response Success, code 2.05, 46 bytes
2023-01-15 22:23:32,524 # </cli/stats>;ct=0;rt="count";obs,</riot/board>
> coap get [::1] foo
2023-01-15 22:23:34,763 # coap get [::1] foo
2023-01-15 22:23:34,763 # 2329
2023-01-15 22:23:34,765 # *** RIOT kernel panic:
2023-01-15 22:23:34,767 # FAILED ASSERTION.
2023-01-15 …
```
> examples/gcoap: Fix shell parameter validation

- makefiles/toolchain/gnu.inc.mk
With b30efeeb65 a warning was introduced when using `make term` without the proper toolchain installed (e.g. when using BUILD_IN_DOCKER, but `term` outside of the docker). This removes this warning.
Run `make term` for a board where you do not have the toolchain installed. Output such as
```
/bin/sh: line 1: xtensa-esp32-elf-gcc: command not found
```
should disappear with this PR.
Fixes a minor issue introduced in https://github.com/RIOT-OS/RIOT/pull/18935.
> toolchain/gnu.inc.mk: don't check version if CC is not installed [backport 2023.01]

- .github/workflows/check-labels.yml
- bors.toml
This PR bumps the check-labels-action to the new version that sets a "Process: missing approvals" label, to be used as bors "block_labels" instead of relying on bors to pick up changes to the check-labels status.
~~TESTING STILL~~ waiting for https://github.com/RIOT-OS/check-labels-action/pull/1 to be merged & tagged
> CI: update check-labels-action

- sys/pm_layered/pm.c
Revert "sys/pm_layered: pm_(un)block add attribute optimize(3) -shortens hotpath"
This reverts commit 5447203921ab39962d7d378a631a6bc048e7f30b.
Compiling `examples/gnrc_networking_mac` using `TOOLCHAIN=llvm` yields the following error:
```
RIOT/sys/pm_layered/pm.c:77:16: error: unknown attribute 'optimize' ignored [-Werror,-Wunknown-attributes]
__attribute__((optimize(3)))
```
As indicated, this is because the attribute `optimize` is GCC only and not present in LLVM.
Compare the manpages of [GCC](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) and [LLVM](https://clang.llvm.org/docs/AttributeReference.html).
Since this should only affect performance and not behavior, no special testing is needed. I am not aware of any tests in RIOT which could verify that assumption. …
> Revert "sys/pm_layered: pm_(un)block add attribute optimize(3)"

- tests/gcoap_dns/main.c
Removes a duplicated test. Originally, the test should have looked different and not be a duplicate. However, the behavior the test aimed at is no longer present anyway, hence it can be removed - rather than fixed. 
Further insights can be provided by @miri64
> tests/gcoap_dns: Remove duplicate

- SUBSYSTEMS.md
This PR migrate the [existing list of subsystems](https://github.com/RIOT-OS/RIOT/wiki/Maintainers) to the RIOT repo.
I also updated the list to represent the actual state of the system.
The list is definitely not perfect and may need several iterations. Feel free to add commits on demand.
We should definitely add more descriptions though, at least for the top headings (CPU, Core, etc).
The original entry included boards as well, but IMO it doesn't really make sense, as they are not a subsystem.
Read. Make sure that the list makes sense.
Discussed during the Virtual Maintainer Assembly
> SUBSYSTEMS.md: migrate subsystem list from wiki

- examples/gcoap_fileserver/Makefile
- examples/gcoap_fileserver/main.c
- makefiles/pseudomodules.inc.mk
- sys/include/net/gcoap/fileserver.h
- sys/net/application_layer/gcoap/fileserver.c
When serving updates via GCoAP fileserver it turned out to be useful to know if a node started downloading the update and when it finished doing so.
But there are probably more use cases where some action might be taken or logged based on the events on the GCoAP fileserver.
This adds 5 event types:
- `GCOAP_FILESERVER_GET_START`: file download started (block 0 requested)
- `GCOAP_FILESERVER_GET_END`: file download finished (last block requested)
- `GCOAP_FILESERVER_PUT_START`:file upload started (block 0 uploaded)
- `GCOAP_FILESERVER_PUT_END`: file upload finished (last block uploaded)
- `GCOAP_FILESERVER_DELETE`:file deletion requested
To be a able to test this, the new callback module is enabled for `examples/gcoap_fileserver` to log file events:
```
> ls /nvm0
./
../
LICENSE	24310 B …
```
> gcoap/fileserver: add event callbacks

- .github/workflows/check-labels.yml
Fixes the current issue of the check-label action.
See https://github.com/miri64/RIOT/pull/39
Follow-up on #19101
> gh-actions: check-labels: move to upstream fix

- sys/shell_lock/shell_lock.c
the current `_safe_strcmp` depends on not being optimized and not being inlined (implicitly given by the -O0), this new one does less (would say not since even O3 had compile results that should not return early or show different runtimes for different secrets).
the runtime of strlen depend on the length of the string (password) therefor it is removed. `ifs` are very jumpy and depend on the contend of password, this avoids `ifs` sadly clang still compiles some boolean statements to if.  
with this PR the `__attribute__((optimize("O0")))` should be removable. 
see https://godbolt.org/z/x35b85cEx
and run the `<RIOT>/tests/shell_lock` 
#19155 made me aware of this function
> sys/shell_lock: do not call strlen, less jumpy

- drivers/matrix_keypad/matrix_keypad.c
During development of the original PR, a leftover `memcpy` slipped through causing a potential crash on initialization of the driver.
The other commit replaces all comparisons against `GPIO_UNDEF` with a call to `gpio_is_valid`.
The test should still compile and run.
None
> matrix keypad: Fix memcpy bug in initialization

- boards/rpi-pico-w/doc.txt
PR #19071 adds Raspberry Pico W board to RIOT. Unfortunately, current Doxygen version used for generation boards documentation available in RIOT webpage, do not scale images. In effect current [documentation](https://doc.riot-os.org/group__boards__rpi__pico__w.html) presents to users very, very huge board image. This PR change this image to smaller one, like in other boards. 
```
make doc
xdg-open doc/doxygen/html/group__boards__rpi__pico__w.htm
```
and compare with current [documentation](https://doc.riot-os.org/group__boards__rpi__pico__w.html).
PR #19071
> boards/rpi-pico-w: fix too large board image

- boards/seeedstudio-gd32/Kconfig
- boards/seeedstudio-gd32/Makefile.dep
- boards/seeedstudio-gd32/Makefile.include
- boards/seeedstudio-gd32/dist/openocd.cfg
- boards/seeedstudio-gd32/doc.txt
- boards/seeedstudio-gd32/include/board.h
- boards/seeedstudio-gd32/include/gpio_params.h
This PR completes and improves the board definition for the Seeedstudio GD32 RISC-V Dev board. It
- adds the user LED and Button definitions to `board.h` (bef42091091cfd8d79130f2109b22b2379959057)
- adds the SAUL support for user LED and Button definitions (7a5b2f1fb43f5e28eec4f65c8e7367510be6eb80)
- changes the OpenOCD configuration (32c0c4b1b5b9705ffcd2bb02a1d868ad35ca3bbc)
- to be usable with Upstream OpenOCD release version 0.12.0
- to allow different FTDI configuration and other adapters
- adds a documentation with flashing guide, feature list, support status, pinout, schematic reference (9dcc83b8ceb8a9ce526f0a03053a242e866ebf4a)
These changes is the first PR for a number of follow-up PR I will provide in next days to extend the GD32VF103 support. I have already working
- …
> boards/seeedstudio-gd32: complete and improve board definition

- tests/gnrc_rpl/Makefile
This disables the `tests/grnc_rpl` test run for `native`. This test is too flaky to be included in the CI.
Not needed
None
> tests/gnrc_rpl: Disable CI test for native

- cpu/sam0_common/include/periph_cpu_common.h
- cpu/sam0_common/periph/adc.c
- cpu/samd21/include/periph_cpu.h
- cpu/samd5x/include/periph_cpu.h
- cpu/saml1x/include/periph_cpu.h
- cpu/saml21/include/periph_cpu.h
`adc_res_t` is the same across all family members, so move it to common code.
This will help extending it as a follow-up.
Also move to `bit.RESSEL` access instead of masking the whole register to make the code more readable.
> cpu/sam0_common: move adc_res_t to common code

- tests/driver_ws281x/Makefile
If a board has fixed defines for `WS281X_PARAM_PIN` and `WS281X_PARAM_NUMOF` the test will overwrite them.
This leads to the LEDs *not* working in with the test, which is very confusing.
Run the test on any board that has `WS281X_PARAM_PIN` set  in `board.h`.
The test should now work properly on those without tweaking the Makefile.
> tests/driver_ws281x: don't overwrite board definition

- cpu/native/include/native_internal.h
- cpu/native/socket_zep/socket_zep.c
- cpu/native/syscalls.c
The use of `ioctl(zepdev->sock_fd, FIONREAD, &size)` would report the number of total bytes available on the socket. This could mean the cumulative sum of bytes of all datagrams, not just a single one.
Instead, use `recv(zepdev->sock_fd, &hdr, sizeof(hdr), MSG_TRUNC | MSG_PEEK)` to only read the ZEP header (without consuming the datagram) to get the real size of the ZEP message.
This prevents accidental concatenation of two ZEP packets into on, which with 6lo fragmentation, would cause the 2nd fragment to be lost as it is read together with the first fragment, but as part of the payload. 
Fragmented multicast datagrams should work now.
```
> ping -s 128 ff02::1
136 bytes from fe80::7c5e:5802:4449:e1b3%7: icmp_seq=0 ttl=64 rssi=0 dBm time=1.515 ms
136 bytes from …
```
> socket_zep: only report size of single datagram

- core/lib/assert.c
- core/lib/include/assert.h
If the `backtrace` module is enabled, use it to print a backtrace on a failed assertion. 
Add
USEMODULE += backtrace
(currently only implemented on `native`).
Now if an assertion fails:
```
main(): This is RIOT! (Version: 2022.07-devel-395-g2b9c0-backtrace-assert)
Hello World!
You are running RIOT on a(n) native board.
This board features a(n) native MCU.
examples/hello-world/main.c:27 => 0x80497c7
0x8049621
0x8049681
0x804980e
0x80497d8
*** halted.
```
> core/assert: print backtrace on failed assertion

- cpu/native/include/native_internal.h
- cpu/native/socket_zep/socket_zep.c
- cpu/native/syscalls.c
The use of `ioctl(zepdev->sock_fd, FIONREAD, &size)` would report the number of total bytes available on the socket. This could mean the cumulative sum of bytes of all datagrams, not just a single one.
Instead, use `recv(zepdev->sock_fd, &hdr, sizeof(hdr), MSG_TRUNC | MSG_PEEK)` to only read the ZEP header (without consuming the datagram) to get the real size of the ZEP message.
This prevents accidental concatenation of two ZEP packets into on, which with 6lo fragmentation, would cause the 2nd fragment to be lost as it is read together with the first fragment, but as part of the payload. 
Fragmented multicast datagrams should work now.
```
> ping -s 128 ff02::1
136 bytes from fe80::7c5e:5802:4449:e1b3%7: icmp_seq=0 ttl=64 rssi=0 dBm time=1.515 ms
136 bytes from …
```
> socket_zep: only report size of single datagram [backport 2023.01]

- examples/paho-mqtt/Makefile.ci
- sys/include/net/gnrc/icmpv6/echo.h
- sys/net/gnrc/network_layer/icmpv6/echo/gnrc_icmpv6_echo.c
- sys/shell/cmds/gnrc_icmpv6_echo.c
Sending and parsing ICMPv6 echo messages is deeply intertwined with the `_gnrc_icmpv6_ping` shell command.
This makes re-using the code e.g. for implementing `traceroute` very hard.
Therefore move the code to a common place in `gnrc_icmpv6_echo.c` so it can be re-used by other (shell) functions.
`ping` should function as before, no logic changes intended.
```
> ping ff02::1
12 bytes from fe80::90a7:a6ff:fe4b:2e32%6: icmp_seq=0 ttl=64 time=0.498 ms
12 bytes from fe80::7837:fcff:fe7d:1aaf%6: icmp_seq=0 ttl=64 time=0.760 ms (DUP!)
12 bytes from fe80::90a7:a6ff:fe4b:2e32%6: icmp_seq=1 ttl=64 time=0.187 ms
12 bytes from fe80::7837:fcff:fe7d:1aaf%6: icmp_seq=1 ttl=64 time=0.347 ms (DUP!)
12 bytes from fe80::90a7:a6ff:fe4b:2e32%6: icmp_seq=2 ttl=64 time=0.137 ms
--- ff02::1 PING statistics ---
3 …
```
> shell/gnrc_icmpv6_echo: separate ICMPv6 echo sending / parsing from shell command

- core/lib/include/assert.h
- core/lib/include/compiler_hints.h
- sys/include/test_utils/expect.h
The compiler can optimize the code better if it knows whether a condition is likely taken / not taken.
This is usually something the developer should not bother with, but for things like `assert()` where the condition should *always* be true, we can tell the compiler to optimize that path.
No logic changes, CI will ensure that all our compilers know about the builtin. 
https://github.com/RIOT-OS/RIOT/pull/19155#issuecomment-1384094781
> core/compiler_hints: add likely() / unlikely() hints

- drivers/periph_common/flashpage.c
This patch removes a test that silently hides failed writes to NULL. Instead, assert is used to ensure that the address is not NULL.
I am not certain how to update the tests to catch asserts. If this is possible, I will add a test, if someone will point me to a good example to learn from.
- none
> drivers/periph_common/flashpage: fix silent error

- pkg/nanopb/Makefile
Minor bugfix release
`tests/pkg_nanopb` still works
> pkg/nanopb: bump version to 0.4.7

- sys/include/net/nanocoap_sock.h
- sys/net/application_layer/nanocoap/sock.c
Create a new message ID for each nanoCoAP socket.
This addresses the concerns raised when I attempted to create a common `coap_next_msg_id()`.
With the requirements brought up in the discussion, such a common function is not possible across GCoAP and nanoCoAP, so at least have such a function for all nanoCoAP users.
alternative to #18991
> nanocoap_sock: store message ID in nanocoap_sock_t

- pkg/wolfssl/sock_tls/sock_tls.c
When sk->ssl is NULL it doesn't need to be free()d, otherwise it may be free()d
> pkg/wolfssl: Fix memory leaks in wolfSSL sock_tls

- boards/nucleo-wl55jc/Kconfig
- drivers/sx126x/Kconfig
Master is broken due to kconfig mismatch for the `nucleo-wl55jc`.  The radio was just not declared.
This fixes the board and cleans up some of the SX126X kconfig.
Murdock should pass
> Fix SX126X-STM32WL module in Kconfig

- cpu/esp32/startup.c
- cpu/esp_common/freertos/task.c
In syscalls_init() there is a call to malloc(), which will return NULL if the heap is not initialized before, causing the entire board to fail booting if MODULE_ESP_IDF_HEAP is used.
API of [vTaskDelete()](https://www.freertos.org/a00126.html) says, that if NULL is passed to vTaskDelete the calling task should be deleted.
This PR needs a backport to 2023.01.
Just compiling on the ESP32S2 and running it with WiFi caused it to not start anymore, no output, nothing. When Null is written to that null-pointer it hangs.
The second commit fixed an issue/assertion fail that happens when the WiFi connection drops/disconnects.
Issue was introduced with PR #19146
> cpu/esp32: fixes for boot issues and crashes on ESP32

- cpu/esp32/startup.c
- cpu/esp_common/freertos/task.c
In `syscalls_init()` there is a call to `malloc()`, which will return `NULL` if the heap is not initialized before, causing the entire board to fail booting if module `esp_idf_heap` is used, for example if the WiFi network interface is used.
API of [vTaskDelete()](https://www.freertos.org/a00126.html) says, that if NULL is passed to vTaskDelete the calling task should be deleted.
This PR needs a backport to 2023.01.
```
USEMODULE=esp_idf_heap BOARD=esp32-wroom-32 make -C tests/malloc
````
should work now but hangs in startup without the PR.
Issue was introduced with PR #19146
> cpu/esp32: fixes for boot issues and crashes on ESP32 [backport 2023.1]

- doc/doxygen/riot.doxyfile
- makefiles/blob.inc.mk
This PR changes the blob makefile documentation to be included in the doxygen output. I ~~didn't~~ slightly change the documentation itself to satisfy doxygen, just added another # and the doxygen boiler plating .
Take a look at the docs
None
> blobs: include documentation in doxygen

- boards/nucleo-wl55jc/Kconfig
- drivers/sx126x/Kconfig
It turns out this is really a board specific setting and should always and only be used when the onboard module is being used...
Green murdock with nightlies enabled...
Follow-up of #19191
> drivers/sx126x: make MODULE_SX126X_RF_SWITCH hidden in kconfig

- boards/seeedstudio-gd32/include/periph_conf.h
- boards/sipeed-longan-nano/include/periph_conf.h
- cpu/gd32v/Kconfig
- cpu/gd32v/Makefile.features
- cpu/gd32v/include/periph_cpu.h
- cpu/gd32v/periph/flashpage.c
- cpu/gd32v/periph/rtt.c
This PR provides the `periph_rtt` support and is one of a bunch of PRs that complete the peripheral drivers for GD32VF103.
`tests/periph_rtt` should work and give the following results:
```
START
main(): This is RIOT! (Version: 2023.04-devel-199-g2d429-cpu/gd32v/periph_rtt)
RIOT RTT low-level driver test
RTT configuration:
RTT_MAX_VALUE: 0xffffffff
RTT_FREQUENCY: 32768
Testing the tick conversion
Trying to convert 1 to seconds and back
Trying to convert 256 to seconds and back
Trying to convert 65536 to seconds and back
Trying to convert 16777216 to seconds and back
Trying to convert 2147483648 to seconds and back
All ok
Initializing the RTT driver
This test will now display 'Hello' every 5 seconds
RTT now: 148
Setting initial alarm to …
```
> cpu/gd32v: add periph_rtt support

- sys/suit/transport/worker.c
Closes: https://github.com/RIOT-OS/RIOT/issues/19195
If the thread has released the mutex but the thread has not terminated (which happens in the situation that would previously have overwritten a still active thread's state), then a warning is shown and the trigger is ignored.
This should work before and after:
* `make -C examples/suit_update BOARD=native all term`
* `aiocoap-client coap://'[fe80::3c63:beff:fe85:ca96%tapbr0]'/suit/trigger -m POST --payload 'coap://[2001:db8::]/foo'`
* In parallel, on the RIOT shell, run `suit fetch coap://[2001:db8::]/foo`
* After the first download fails, the second one starts right away ("suit_worker: update failed, hdr invalid" / "suit_worker: started").
Run again with the worker thread on low priority:
```patch
diff --git …
```
> sys/suit: Ensure previous thread is stopped before reusing its stack

- boards/common/gd32v/include/board_common.h
- boards/seeedstudio-gd32/include/board.h
- boards/sipeed-longan-nano/include/board.h
Turns out this is still needed.
Flash `examples/blinky` with this patch:
```patch
diff --git a/examples/blinky/Makefile b/examples/blinky/Makefile
index 2d58be2d6b..c25a66db48 100644
--- a/examples/blinky/Makefile
+++ b/examples/blinky/Makefile
@@ -16,6 +16,7 @@ DEVELHELP ?= 1
QUIET ?= 1
+USEMODULE += ztimer_msec
FEATURES_OPTIONAL += periph_timer
diff --git a/examples/blinky/main.c b/examples/blinky/main.c
index ac90ccbc15..23486e1c58 100644
--- a/examples/blinky/main.c
+++ b/examples/blinky/main.c
@@ -29,7 +29,7 @@
static void delay(void)
{
if (IS_USED(MODULE_ZTIMER)) {
-        ztimer_sleep(ZTIMER_USEC, 1 * US_PER_SEC);
+        ztimer_sleep(ZTIMER_MSEC, 1 * MS_PER_SEC);
}
else {
/*
```
<details><summary>on master this will get you very erratic LED …
> boards/common: add common timer config for GD32VF103 boards

- examples/gnrc_border_router/Makefile
- sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c
- sys/net/gnrc/network_layer/ipv6/static_addr/Kconfig
A router that does not support DHCPv6 IA_PD will typically still support sending router advertisements.
Setting `IPV6_DEFAULT_ROUTER` by default prevents the node from getting the router config via RAs, leading to a broken configuration.
Setting `IPV6_DEFAULT_ROUTER` should only be needed in special cases where routes are not advertised.
`examples/gnrc_border_router` with `PREFIX_CONF=static IPV6_ADDR=2001:1438:400c:7720::7771/64 IPV6_PREFIX=2001:1438:400c:7771::/64`:
```
2023-01-27 18:05:21,780 - INFO # > nib route
2023-01-27 18:05:21,781 - INFO # 
2023-01-27 18:05:21,783 - INFO # 2001:1438:400c:7720::/64 dev #8
2023-01-27 18:05:21,786 - INFO # 2001:1438:400c:7771::/64 dev #7
2023-01-27 18:05:21,790 - INFO # default* via fe80::290:7fff:fed7:c528 dev #8
2023-01-27 18:05:37,000 - INFO # > …
```
> examples/gnrc_border_router: static: use router from advertisements by default

- boards/common/gd32v/include/cfg_timer_default.h
- boards/seeedstudio-gd32/Kconfig
- boards/seeedstudio-gd32/Makefile.features
- boards/seeedstudio-gd32/doc.txt
- boards/seeedstudio-gd32/include/periph_conf.h
- boards/sipeed-longan-nano/Kconfig
- boards/sipeed-longan-nano/Makefile.features
- boards/sipeed-longan-nano/doc.txt
- boards/sipeed-longan-nano/include/periph_conf.h
- cpu/gd32v/include/periph_cpu.h
- cpu/gd32v/periph/pwm.c
- cpu/gd32v/periph/timer.c
- dist/tools/doccheck/generic_exclude_patterns
This PR provides the `periph_pwm` support for GD32VF103.
It includes a bug fix (2c6e527339f2cdbb4b0cccdc79d4abb6b0b60c12) of `periph_timer` which clears pending interrupts on setting the timer before the interrupt is enabled. This avoids that a pending interrupt is triggered immediately when the timer is set. The bug caused `tests/periph_timer` and `tests/periph_timer_periodic` to crash. (I could split-off this bug fix if necessary).
Furthermore, the default timer configuration has been extended and reordered. `TIMER0` can be used now as timer device (0dfbdebaf74050ca6b9cc764be73a635c915a884). The default timer configuration has been changed (377b5b321c0da8f0ed71a25719e8ec4a08ce972a) so that `TIMER0` and `TIMER1` are always timer devices. `TIMER2` can only be used as timer device if it is …
> cpu/gd32v: add periph_pwm support

- doc/doxygen/src/porting-boards.md
Current version of the file [`porting-boards.md`](https://github.com/RIOT-OS/RIOT/blob/master/doc/doxygen/src/porting-boards.md) did not present correctly in the github preview two snippets, presented in the sections: `doc.txt` and `Using Common code`. 
This PR fix this issue.
Check if these changes do not corrupt generated doxygen.
None
> doc/porting-boards.md: fix code snippets in md view

- boards/common/gd32v/include/periph_common_conf.h
- cpu/gd32v/include/periph_cpu.h
- dist/tools/doccheck/generic_exclude_patterns
This PR fixes the problem that the RTT frequency is defined to be 40.0 kHz instead of 32.768 kHz if `TEST_KCONFIG=1` is not defined.
The problem was caused by the order in which the headers were included. In `cpu/gd32v/include/periph_cpu.h` the RTT frequency was defined to be 32.768 kHz or 40.0 kHz, depending on the `CONFIG_BOARD_HAS_LXTAL` configuration of the board. If `TEST_KCONFIG=1` is used, it is defined in `autoconfig.h` and is always known, but without `TEST_KCONFIG=1` it is defined in the `periph_conf.h` of the board. If `periph_cpu.h` is included but not `periph_conf.h`, `CONFIG_BOARD_HAS_LXTAL` is not defined without `TEST_KCONFIG=1` and the RTT frequency is defined to be 40.0 kHz.
The solution is to move board dependent RTT configurations to `periph_common.conf`.
``` …
```
> cpu/gd32v: move board dependent RTT configs to board config

- drivers/at86rf2xx/at86rf2xx_netdev.c
This PR sets the correct value of `netdev_ieee802154->chan` during the at86rf2xx initialization.
This regression was introduced in https://github.com/RIOT-OS/RIOT/pull/18988, because it removes all `memcpy` instances from internal driver setters/getters. Since `netdev_ieee802154_reset`  does not set the value of `dev->chan`, nobody was setting the channel value.
This definitely needs a backport, but IMO it doesn't justify re-running release tests for AT86RF2XX related devices, since existing MAC layers store the channel in the MAC Information Base and don't rely on NETOPT_CHANNEL.
`ifconfig` should display the correct channel number:
```
2023-01-30 18:37:05,997 # Iface  6  HWaddr: 7B:4E  Channel: 26  NID: 0x23  PHY: O-QPSK 
2023-01-30 18:37:05,999 #           
2023-01-30 18:37:06,000 # …
```
> drivers/at86rf2xx: set netdev channel on init

- drivers/at86rf2xx/at86rf2xx_netdev.c
This PR sets the correct value of `netdev_ieee802154->chan` during the at86rf2xx initialization.
This regression was introduced in https://github.com/RIOT-OS/RIOT/pull/18988, because it removes all `memcpy` instances from internal driver setters/getters. Since `netdev_ieee802154_reset`  does not set the value of `dev->chan`, nobody was setting the channel value.
This definitely needs a backport, but IMO it doesn't justify re-running release tests for AT86RF2XX related devices, since existing MAC layers store the channel in the MAC Information Base and don't rely on NETOPT_CHANNEL.
`ifconfig` should display the correct channel number:
```
2023-01-30 18:37:05,997 # Iface  6  HWaddr: 7B:4E  Channel: 26  NID: 0x23  PHY: O-QPSK 
2023-01-30 18:37:05,999 #           
2023-01-30 18:37:06,000 # …
```
> drivers/at86rf2xx: set netdev channel on init [backport 2023.01]

- sys/test_utils/print_stack_usage/print_stack_usage.c
There's now an API for getting a thread's name, stack size and stack start value. So, use it.
CI should suffice. Here's some native output *with* this PR:
<details>
```
riot/tests/fmt_print on  print_stack_usage_use_api                                                                                                
❯ /home/kaspar/src/riot/tests/fmt_print/bin/native/tests_fmt_print.elf                                                                             
RIOT native interrupts/signals initialized.                                                                                                        
RIOT native board initialized.                                                                                                                     
RIOT native hardware initialization …
```
> test_utils/print_stack_usage: use thread.h API

- tests/periph_flashpage_unittest/Makefile
- tests/periph_flashpage_unittest/app.config.test
This PR enables the `periph_flashpage` module for  the unittest in `tests/periph_flashpage_unittest` so that it requires feature `periph_flashpage` and expects only correct calculation of flashpage indices if it is used.
Testing the correct calculation of flashpage indices without assuming the `periph_flashpage` feature and enabling the `periph_flashpage` module makes no sense. On ESP32x SoCs for example, the space in the flash is only reserved and `FLASHPAGE_NUMOF` is greater than 0 if `periph_flashpage` is used.
The PR fixes the unittest problem for ESP32x SoCs.
Green CI with label `CI: run test`.
> tests/periph_flashpage_unittest: enable periph_flashpage

- boards/common/gd32v/include/cfg_i2c_default.h
- boards/seeedstudio-gd32/Kconfig
- boards/seeedstudio-gd32/Makefile.features
- boards/seeedstudio-gd32/doc.txt
- boards/seeedstudio-gd32/include/periph_conf.h
- boards/sipeed-longan-nano/Kconfig
- boards/sipeed-longan-nano/Makefile.features
- boards/sipeed-longan-nano/doc.txt
- boards/sipeed-longan-nano/include/periph_conf.h
- cpu/gd32v/include/periph_cpu.h
- cpu/gd32v/include/vendor/gd32vf103_periph.h
- cpu/gd32v/periph/i2c.c
- dist/tools/doccheck/generic_exclude_patterns
This PR provides the `periph_i2c` support and is one of a bunch of PRs that complete the peripheral drivers for GD32VF103.
The driver is a modified version of the driver for STM32F1 with some changes that were necessary to get it working on GD32V. As  for STM32F1, the driver is using polling instead of interrupts for now. It will be implemented interrupt-driven later.
`tests/periph_i2c` as well as a test with any I2C sensor should work. The driver was tested with `tests/driver_l3gxxxx` and `tests/driver_bmp180`.
> cpu/gd32v: add periph_i2c support

- .cargo/config.toml
- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- sys/rust_riotmodules_standalone/Cargo.lock
- tests/rust_minimal/Cargo.lock
As riot-wrappers has advanced a bit since it was last released, Rust modules are switched to using it from git again. (This is a regular ping-pong between testing the latest release in RIOT master, and using released support crates when they're current).
This primarily updates riot-wrappers, which has accumulated several compatible changes. Several other crates receive updates as well.
* Green CI
Changes on the riot-wrappers side:
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/17
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/22
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/29
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/30
[edit: added:]
This also serves to help preparing a 0.8.1 release of riot-wrappers, which performs some deprecations so that a breaking 0.9 …
> rust: Update dependencies, use riot-wrappers from git

- boards/common/gd32v/include/cfg_spi_default.h
- boards/seeedstudio-gd32/Kconfig
- boards/seeedstudio-gd32/Makefile.features
- boards/seeedstudio-gd32/doc.txt
- boards/seeedstudio-gd32/include/periph_conf.h
- boards/sipeed-longan-nano/Kconfig
- boards/sipeed-longan-nano/Makefile.features
- boards/sipeed-longan-nano/doc.txt
- boards/sipeed-longan-nano/include/board.h
- boards/sipeed-longan-nano/include/periph_conf.h
- cpu/gd32v/include/periph_cpu.h
- cpu/gd32v/include/vendor/gd32vf103_periph.h
- cpu/gd32v/periph/spi.c
- dist/tools/doccheck/generic_exclude_patterns
This PR provides the `periph_spi` support and is one of a bunch of PRs that complete the peripheral drivers for GD32VF103.
The driver is a modified version of the driver for STM32F1 with some changes that were necessary to get it working on GD32V.
`tests/periph_spi` as well as a test with any SPI sensor should work. `tests/driver_sdcard_spi` should work on `sipeed-longan-nano`.
Depeneds on PR #19216
> cpu/gd32v: add periph_spi support

- dist/tools/doccheck/check.sh
- dist/tools/doccheck/exclude_patterns
- doc/doxygen/Makefile
doccheck without generating dot or html
this also has some new generated lines for exclude_pattern (some of them where broke so I regenerated the block)
doccheck
> doccheck: avoid generating dot or html

- dist/tools/backport_pr/backport_pr.py
This should make pylint happy again.
Static tests no longer fail with
backport_pr.py:253:4: R1720: Unnecessary "else" after "raise", remove the "else" and de-indent the code inside it (no-else-raise)
> tools/backport_pr: remove Unnecessary "else" after "raise"

- boards/seeedstudio-gd32/Kconfig
- boards/seeedstudio-gd32/Makefile.features
- boards/seeedstudio-gd32/doc.txt
- boards/seeedstudio-gd32/include/periph_conf.h
- boards/sipeed-longan-nano/Kconfig
- boards/sipeed-longan-nano/Makefile.features
- boards/sipeed-longan-nano/doc.txt
- boards/sipeed-longan-nano/include/periph_conf.h
- cpu/gd32v/include/periph_cpu.h
- cpu/gd32v/include/vendor/gd32vf103_periph.h
- cpu/gd32v/periph/adc.c
- dist/tools/doccheck/generic_exclude_patterns
This PR provides the `periph_adc` support and is one of a bunch of follow up PRs that complete the peripheral drivers for GD32VF103.
This PR depends on PR #19170 and includes this PR to be compilable since includes the ADC configuration also for Sipeed Longan Nano board.
`tests/periph_adc` should work on any GD32VF103 board.
Depends on PR #19170
> cpu/gd32v: add periph_adc support

- sys/shell/cmds/gnrc_icmpv6_echo.c
With the introduction of #17607, applications using `ztimer_now()` have to tell `ztimer` that it mustn't disable underlying clocks.
Ping should work. No warnings shall be displayed if `ztimer_ondemand` is active.
> shell/gnrc_icmpv6_echo: acquire ZTIMER_USEC clock for time measurement

- drivers/Kconfig
- drivers/Makefile.dep
- drivers/include/vl6180x.h
- drivers/saul/init_devs/auto_init_vl6180x.c
- drivers/saul/init_devs/init.c
- drivers/vl6180x/Kconfig
- drivers/vl6180x/Makefile
- drivers/vl6180x/Makefile.dep
- drivers/vl6180x/Makefile.include
- drivers/vl6180x/include/vl6180x_params.h
- drivers/vl6180x/include/vl6180x_regs.h
- drivers/vl6180x/vl6180x.c
- drivers/vl6180x/vl6180x_saul.c
- tests/driver_vl6180x/Makefile
- tests/driver_vl6180x/README.md
- tests/driver_vl6180x/app.config.test
- tests/driver_vl6180x/main.c
- tests/saul_drivers/Makefile
This PR adds a driver for the ST VL6180X ranging and ambient light sensor. The driver can be used in two variants which differ in functionality and size:
Module Name   | Driver
:-------------|:-------------------------------------------
vl6180x       | Driver with standard functionality and larger size
vl6180x_basic | Driver with only basic functionality and smaller size
Both driver variants provide
- continuous ranging and ambient light sensing,
- polling for new measurement results, and
- SAUL capabilies.
In addition to these basic functionalities, the standard driver `vl6180x`
provides interrupt handling, single shot measurements, a number of
configuration functions and power down / power up functionality.
Features of the driver variants are summarized in the following comparison …
> drivers: add driver for ST VL6180X ranging and ambient light sensor

- pkg/nimble/autoadv/nimble_autoadv.c
Fixes the following errors when building `examples/nimble_gatt` with `TOOLCHAIN=llvm`:
<details>
```
/home/kaspar/src/riot/pkg/nimble/autoadv/nimble_autoadv.c:195:25: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
else if (_cfg.flags && NIMBLE_AUTOADV_FLAG_CONNECTABLE) {
^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kaspar/src/riot/pkg/nimble/autoadv/nimble_autoadv.c:195:25: note: use '&' for a bitwise operation
else if (_cfg.flags && NIMBLE_AUTOADV_FLAG_CONNECTABLE) {
^~
&
/home/kaspar/src/riot/pkg/nimble/autoadv/nimble_autoadv.c:195:25: note: remove constant to silence this warning
else if (_cfg.flags && NIMBLE_AUTOADV_FLAG_CONNECTABLE) {
~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kaspar/src/riot/pkg/nimble/autoadv/nimble_autoadv.c:195:28: error: …
```
> pkg/nimble/autoadv: fix flag comparisons

- sys/vfs/vfs.c
`vfs.c` uses `container_of()` and `IS_USED()`, but doesn't (directly) include the necessary includes.
No changes with RIOT master. RIOT-rs stumbles over this.
> sys/vfs: vfs.c missing includes

- sys/net/crosslayer/inet_csum/inet_csum.c
`inet_csum.c` uses `IS_ACTIVE()` without the include.
> sys/net/crosslayer/inet_csum: add missing "modules.h" include

- sys/net/gnrc/netreg/gnrc_netreg.c
If a socket is registered twice, it's `next` pointer will point to itself, creating an infinite loop in `_netreg_lookup()` when a packet is received.
Especially when this only happens sporadically (code path that would normally close the socket is not taken) it creates a very hard to debug issue where the system is just locked up.
Instead, fail early and loud.
This would be an infinite loop on RX before, now it's a crash right at the place where the error condition occurs.
Call `gnrc_sock_create()` on the same socket twice.
On `master` this will not fail, but as soon as you receive a packet on the socket, the system locks up in an infinite loop.
With this patch, the assertion will trigger on the 2nd call to `gnrc_sock_create()`.
> sys/net/grnc/netreg: avoid creating an infinite loop

- dist/tools/backport_pr/backport_pr.py
This should make pylint happy again.
Static tests no longer fail with
backport_pr.py:253:4: R1720: Unnecessary "else" after "raise", remove the "else" and de-indent the code inside it (no-else-raise)
> tools/backport_pr: remove Unnecessary "else" after "raise" [backport 2023.01]

- dist/tools/testprogs/README.md
- dist/tools/testprogs/minimal_linkable.c
- makefiles/cflags.inc.mk
- makefiles/libc/newlib.mk
- makefiles/libc/picolibc.mk
Before the build system used something like
echo "int main(){} void _exit(int n) {(void)n;while(1);}" | LC_ALL=C $(LINK) -xc - -o /dev/null -lc -Wall -Wextra -pedantic <FLAGS_TO_TEST>
to check for flags supported by the compiler (used as linker frontend). This however no longer works with newlib 4.3.0, which requires the symbols `_sbrk_r`, `_close_r`, `_lseek_r`, `_read_r`, and `_write_r` to be present. Instead, now a new file `minimal_linkable.c` was added that adds all the missing symbols and is used in the linker feature tests instead.
- No regressions on the CI
- No changes in binaries
- Building rust apps with newlib 4.3.0 should work again
> build system: Fix linker feature test with newlib 4.3.0

- drivers/Kconfig.net
- drivers/include/net/netdev.h
- pkg/tinyusb/Kconfig
- pkg/tinyusb/Kconfig.net
- pkg/tinyusb/Makefile
- pkg/tinyusb/Makefile.dep
- pkg/tinyusb/Makefile.include
- pkg/tinyusb/Makefile.lib_networking
- pkg/tinyusb/contrib/include/tinyusb.h
- pkg/tinyusb/contrib/include/tinyusb_descriptors.h
- pkg/tinyusb/contrib/include/tusb_config.h
- pkg/tinyusb/contrib/tinyusb_descriptors.c
- pkg/tinyusb/doc.txt
- pkg/tinyusb/netdev/Kconfig
- pkg/tinyusb/netdev/Makefile
- pkg/tinyusb/netdev/include/tinyusb_netdev.h
- pkg/tinyusb/netdev/tinyusb_netdev.c
- pkg/tinyusb/patches/0004-lib-networking-remove-include-of-lwIP-netif-ethernet.patch
- sys/net/gnrc/netif/init_devs/auto_init_tinyusb_netdev.c
- sys/net/gnrc/netif/init_devs/init.c
- tests/pkg_tinyusb_netdev/Makefile
- tests/pkg_tinyusb_netdev/Makefile.ci
- tests/pkg_tinyusb_netdev/README.md
- tests/pkg_tinyusb_netdev/main.c
This PR adds the tinyUSB netdev driver.
The tinyUSB netdev driver is part of the tinyUSB package and is enabled by module `tinyusb_netdev`. It is available for boards that provide the `tinyusb_device` feature.
**Please note** Since the tinyUSB package is distinct from (and incompatible with) the USB stack provided around USBUS in RIOT (see USB), the tinyUSB netdev driver cannot be used together with with any USBUS device class.
The tinyUSB netdev driver uses Ethernet over USB and supports the following protocols:
- CDC ECM (Ethernet Control Model)
- CDC NCM (Network Control Model)
- RNDIS (Microsoft Remote NDIS)
While Linux and macOS support all these protocols, Microsoft Windows only supports the RNDIS protocol and since Windows version 11 also the CDC NCM protocol. macOS supports the …
> pkg/tinyusb: add tinyUSB netdev driver

- doc/doxygen/src/advanced-build-system-tricks.md
This documents the `generate-makefile.ci` target
Read the added section to the advanced build system tricks
None
> Doc: document generate-makefile.ci

- Makefile.include
- makefiles/info-global.inc.mk
- makefiles/info.inc.mk
This is the same as the create-Makefile.ci. The alias is added to stay in line with other generate-* Make targets. Now the documentation should also be valid again
The target should now match the documentation in the doxygen.
follow-up to #19239
> Make: Add generate-Makefile.ci

- .murdock
Currently, CI would not skip compilation for builds where `can_fast_ci_build.py`
can figure out that it should. That's because `cfcb.py` depends on `CI_BASE_COMMIT`
being set, which for a branch build like for bors' staging or trying, isn't.
This PR populates `CI_BASE_COMMIT` from the previous (second) merge commit, which
*should* always point to the base branch HEAD.
[here](https://ci.riot-os.org/details/701e23634700496e9c3b568422d4b1a2/output) is the result of a bors try of this PR, but with a "remove me"  commit disabling full builds on ".murdock" changes.
> CI: .murdock: fix bors fast build

- boards/common/makefiles/stdio_tinyusb_cdc_acm.dep.mk
- boards/esp32s3-pros3/Kconfig
- boards/esp32s3-pros3/Makefile
- boards/esp32s3-pros3/Makefile.dep
- boards/esp32s3-pros3/Makefile.features
- boards/esp32s3-pros3/Makefile.include
- boards/esp32s3-pros3/doc.txt
- boards/esp32s3-pros3/include/arduino_board.h
- boards/esp32s3-pros3/include/arduino_pinmap.h
- boards/esp32s3-pros3/include/board.h
- boards/esp32s3-pros3/include/gpio_params.h
- boards/esp32s3-pros3/include/periph_conf.h
- cpu/esp32/doc_esp32s3.txt
- sys/usb_board_reset/Kconfig
This PR provides the support for [ESP32 ProS3](https://esp32s3.com/pros3.html#home) board from Unexpected Maker.
This board doesn't have a USB-to-Serial chip on board. Therefore, USB Serial/JTAG is used for STDIO and the board is flashed via the USB Seral/JTAG interface by default.
Flashing `tests/shell` should work.
> boards: add esp32s3-pros3 support

- boards/common/gd32v/include/cfg_i2c_default.h
- boards/common/gd32v/include/cfg_spi_default.h
- boards/seeedstudio-gd32/doc.txt
- boards/seeedstudio-gd32/include/periph_conf.h
- boards/sipeed-longan-nano/Kconfig
- boards/sipeed-longan-nano/doc.txt
- boards/sipeed-longan-nano/include/periph_conf.h
- cpu/gd32v/periph/spi.c
This PR provides some small improvements of the existing board definitions for GD32VF103 boards for more flexibel default configurations and documentation of the board peripherals:
- Allow the remapping of SPI0 pins in SPI configuration (ae984b0bea59ba0803cd5418d1169f38a5fe3796)
- More flexible I2C configuration (0c337583b4a0542c109794b903433f6fde2b8a10)
The default I2C device configuration allows to define up to two I2C devices `I2C_DEV(0)` and `I2C_DEV(1)`. `I2C_DEV(0)` is always defined if the I2C peripheral is enabled by the module `periph_spi`. The second I2C device `I2C_DEV(1)` is only defined if `I2C_DEV_1_USED` is defined by the board. This allows to use the default configuration with one or two I2C devices depending on whether other peripherals are enabled that would collide with …
> boards/gd32v: improve board definitions

- tests/driver_dac_dds/main.c
The `sine` and `saw` commands have a bug that can lead to either distorted (sine) or no (saw) output.
- the sine function would overflow to 0 when doing the signed -> unsigned conversion
- the saw function would produce a step value of 0 if the frequency was too low
> tests/driver_dac_dds: fix output of sine and saw functions

- cpu/gd32v/Kconfig
- cpu/gd32v/Makefile.features
- cpu/gd32v/periph/rtc_mem.c
- tests/periph_rtt/main.c
This PR provides the `periph_rtc_mem` support for GD32VF103.
A modified version of this driver could also be used for STM32F1.
`tests/periph_rtt` should work on any GD32V board, for example:
```
BOARD=sipeed-longan-nano make -C tests/periph_rtt flash
```
```
START
main(): This is RIOT! (Version: 2023.04-devel-319-gebc86-cpu/gd32v/periph_rtc_mem)
RIOT RTT low-level driver test
RTT configuration:
RTT_MAX_VALUE: 0xffffffff
RTT_FREQUENCY: 32768
Testing the tick conversion
Trying to convert 1 to seconds and back
Trying to convert 256 to seconds and back
Trying to convert 65536 to seconds and back
Trying to convert 16777216 to seconds and back
Trying to convert 2147483648 to seconds and back
All ok
Initializing the RTT driver
RTC mem OK
This …
```
> cpu/gd32v: add periph_rtc_mem support

- boards/seeedstudio-gd32/doc.txt
- boards/sipeed-longan-nano/Kconfig
- boards/sipeed-longan-nano/Makefile.features
- boards/sipeed-longan-nano/doc.txt
- boards/sipeed-longan-nano/include/periph_conf.h
- cpu/gd32v/include/periph_cpu.h
- cpu/gd32v/periph/dac.c
- dist/tools/doccheck/generic_exclude_patterns
This PR provides the `periph_dac` support for GD32VF103.
`tests/periph_dac` should work on `sipeed-longan-nano` port on PA4 and PA5.
> cpu/gd32v: add periph_dac support

- boards/common/esp32/include/board_common.h
- boards/common/esp32c3/include/board_common.h
- boards/common/esp32s2/include/board_common.h
- boards/common/esp32s3/include/board_common.h
- boards/common/esp8266/include/board_common.h
- boards/esp32-wemos-lolin-d32-pro/Kconfig
- boards/esp32-wemos-lolin-d32-pro/Makefile.dep
- boards/esp32-wemos-lolin-d32-pro/Makefile.features
- boards/esp32-wrover-kit/Kconfig
- boards/esp32-wrover-kit/Makefile.dep
This PR provides the remaining changes necessary to use the generic MTD SD Card configuration as described in PR #19216. 
This includes defining the MTD offset for SD cards, since the default `MTD_0` device always uses the internal flash device, and the completion of the configuration for the ESP32 boards with a SD card interface.
`tests/vfs_default` should work now with SD Cards:
```
main(): This is RIOT! (Version: 2023.04-devel-323-gfcc07)
mount points:
/nvm0
/sd0
data dir: /sd0
> vfs df 
Mountpoint              Total         Used    Available     Use%
/nvm0                3052 KiB        8 KiB     3044 KiB       0%
/sd0                 7580 MiB 3632148992 B   21089792 B      99%
```
> boards/esp*: complete SD Card MTD config

- sys/Makefile.dep
- sys/coding/Makefile
- sys/coding/doc.txt
- sys/coding/xor.c
- sys/include/coding/xor.h
- tests/unittests/tests-coding/Makefile
- tests/unittests/tests-coding/Makefile.include
- tests/unittests/tests-coding/tests-coding-xor.c
- tests/unittests/tests-coding/tests-coding.c
- tests/unittests/tests-coding/tests-coding.h
This implements the XOR based error-correction code described by @jue89 [at the RIOT Summit](https://summit.riot-os.org/2021/wp-content/uploads/sites/16/2021/09/s02-01.pdf).
A parity byte is generated for each 3 payload bytes, then the payload array is transposed by interpreting it as a 2D matrix with height of 3.
This is to reduce the chance of consecutive bytes ending up in the same packet.
With this it is possible to recover one in 3 lost data packets (if parity packets are received).
I'm not sure if the transpose function is ideal for mixing the bytes as it still generates a rather predictable pattern and we can't recover from two consecutive lost packets, but this might require more advanced codes (e.g. [raptor codes](https://github.com/obolo/freeRaptor)).
So far only unit tests have …
> sys/coding: add XOR based coding module

- makefiles/stdio.inc.mk
`stdio_tinyusb_cdc_acm` benefits from stdio buffering (not transferring individual bytes) just like `stdio_cdc_acm`.
Run any application that uses `stdio_tinyusb_cdc_acm` with
FEATURES_REQUIRED += picolibc
with newlib, stdio buffering is the default.
> sys/stdio: mark stdio_tinyusb_cdc_acm as buffered

- sys/fmt/fmt.c
- sys/test_utils/print_stack_usage/print_stack_usage.c
Currently, fmt's `print()` is using libc's `fwrite()` in order to mitigate both
libc and fmt output clashing wrt. libc stdio buffers. That causes `print()` to
use quite a bit more stack, we had to remove the lower stack case in
`print_stack_usage_metrics()`.
This PR changes `print()` to use `fflush()`; `stdio_write()` instead, bypassing
a lot of libc's FILE machinery.
A quick test on nrf52840dk shows that `print_stack_usage_metrics()` on an
otherwise empty thread uses 124b stack without the `fflush()`, 160b with the
`fflush()` (this PR's state). So another commit re-adds the `MIN_SIZE` fmt
case.
> sys/fmt: use `fflush(); stdio_write()` instead of `fwrite()`

- cpu/stm32/periph/timer.c
From the git comment msg:
If a timer's channel was set with a really small realtive duration from now, such that it would be missed (underflowed), the driver would stop the timer, potentially causing missed ticks. It was stopped to ensure that the channel's output-compare register could be set to the current counter value, before re-enabling the timer's counter. This is a condition that will ensure that the underflow won't happen again and the interrupt will fire, at the cost of losing some ticks for very high speed clocks.
This patch replaces the logic that stopped the timer. Instead it uses a register provided by the timer hardware to trigger timer interrupts via software.
1. do
``` bash
$ cd tests/periph_timer_short_relative_set
$ make BOARD=nucleo-f303ze flash term
```
1. follow …
> cpu/stm32/periph/timer: don't stop counter

- boards/stm32f4discovery/Kconfig
- boards/stm32f4discovery/Makefile.dep
- boards/stm32f4discovery/Makefile.features
- boards/stm32f4discovery/doc.txt
- tests/xtimer_now32_overflow/Makefile
- tests/xtimer_now64_continuity/Makefile
Looks like `stm32f4discovery` also has one of the old on-board ST-Links that don't implement a USB-UART interface (like on `stm32f429i-disco`).
Since wiring up a USB-UART interface manually is annoying and the board provides a micro-USB port, default to `stdio_cdc_acm` so the user only needs an extra USB cable to access the shell.
Connect a micro-USB cable to he port of the `stm32f4discovery`.
It should be recognized as a CDC ACM interface and `make term` should automatically connect to it.
*I don't have this board.*
https://github.com/RIOT-OS/RIOT/pull/19248#issuecomment-1419723939
> boards/stm32f4discovery: default to stdio via CDC ACM

- sys/include/event/source.h
- tests/event_source/Makefile
- tests/event_source/Makefile.ci
- tests/event_source/main.c
- tests/event_source/tests/01-run.py
The idea is similar to the message bus, but instead of registering threads to which we send messages, instead we have a list of event handlers that can all be triggered at once.
The advantage is of course that as opposed to messages, events can't be lost.
A very simple test application has been added to `tests/event_bus`.
> sys/event: add event sources

- drivers/Makefile.dep
- drivers/include/periph/wdt.h
- drivers/periph_common/init.c
- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/auto_init/Makefile
- sys/auto_init/include/auto_init_priorities.h
- sys/auto_init/wdt_event/Makefile
- sys/auto_init/wdt_event/wdt.c
- sys/auto_init/wdt_thread/Makefile
- sys/auto_init/wdt_thread/wdt.c
Add an option to enable the watchdog early to detect hangs during initialization.
Add `USEMODULE += auto_init_wdt_thread` or `USEMODULE += auto_init_wdt_event` to your application.
This will automatically spawn a watchdog thread that runs with the lowest priority.
> drivers/wdt: add periph_wdt_auto_start for early watchdog

- sys/net/application_layer/gcoap/gcoap.c
Since https://github.com/RIOT-OS/RIOT/pull/18026, CoAP requests to multicast addresses (eg. `ff02::1`) came back from that exact address, which Linux rightfully just drops.
The fix uses the existing multicast check from https://github.com/RIOT-OS/RIOT/pull/17978 (thanks @benpicco for making me write this as dedicated function, I just had to generalize it removing one struct layer), and foregoes setting the source address when responding to multicasts.
* Run the gcoap example
* Send a CoAP request to a multicast address RIOT listens to, eg. `./aiocoap-client coap://'[ff02::1%tapbr0]'/.well-known/core --non`
Before, this got no response (while you see it arrive on wireshark). After, you get a correct response with two lines of note:
```
WARNING:coap:Sending request to multicast via unicast …
```
> gcoap: Do not send responses from multicast addresses

- .murdock
Using our nice graphana metrics, @bergzand pointed out some serious (~3MB/s) disk writes during CI runs. We figured out that .ccache is using the `/cache` volume for its temporary files, which is now on a real file system (since we've switched to redis for ccache).
This PR makes `CCACHE_TEMPDIR` point to the build checkout, which is on tmpfs.
> CI: .murdock: use build checkout for ccache tmp

- pkg/tinyusb/Makefile
- pkg/tinyusb/patches/0002-src-portable-synopsys-define-SystemCoreClock-variabl.patch
Bump to the latest [upstream release](https://github.com/hathach/tinyusb/releases/tag/0.15.0). 
on `weact-f411ce` and `esp32s2-wemos-mini`
> pkg/tinyusb: bump to 0.15

- cpu/stm32/include/periph/cpu_i2c.h
- cpu/stm32/periph/i2c_1.c
This exports the previously internally defined `MAX_BYTES_PER_FRAME` in `cpu/stm32/periph/i2c_1.c`.
If such a limit exists, a driver must know about it.
CI
The problem came up in #19270.
> cpu/stm32/periph/i2c: export PERIPH_I2C_MAX_BYTES_PER_FRAME

- cpu/sam0_common/include/periph_cpu_common.h
- drivers/at24cxxx/at24cxxx.c
- drivers/at24cxxx/mtd/mtd.c
- drivers/include/at24cxxx.h
The function `read_page` was missing which lead to (from a user perspective) undefined behavior on the MTD layer.
Any application using MTD in conjunction with a board with an at24cxxx.
> drivers/at24cxxx: implement _mtd_at24cxxx_read_page

- core/lib/include/compiler_hints.h
- core/lib/include/xfa.h
Hi! 🦎
When using llvm and address sanitation, the XFA trip the sanitizer.
This PR attempts to fix this by adding the `no_sanitize` attribute to the XFA macros. Sadly, this attribute is not known by gnu, a guard is hence needed. I'm open for alternatives as I dislike this solution but it is the best I could come up with.
Before this patch:
Go to `examples/gnrc_minimal` and run `TOOLCHAIN=llvm make all-asan` and then `make term`.
You should see an error similar to this:
```
==3374719==ERROR: AddressSanitizer: global-buffer-overflow on address 0x080774e0 at pc 0x0804af5e bp 0x0808eb88 sp 0x0808eb78
READ of size 4 at 0x080774e0 thread T0
#0 0x804af5d in _auto_init_module /RIOT/sys/auto_init/auto_init.c:40
#1 0x804af5d in auto_init /RIOT/sys/auto_init/auto_init.c:339
#2 0x804b375 in …
```
> core/xfa: disable asan on llvm

- drivers/include/mtd_flashpage.h
- drivers/mtd/mtd.c
- drivers/mtd_flashpage/mtd_flashpage.c
- tests/mtd_flashpage/Makefile
- tests/mtd_flashpage/app.config.test
- tests/mtd_flashpage/main.c
The `mtd_flashpage` API is a bit special in that it experts the user to pass raw flash addresses to it.
This is very usual because every other MTD device will start at address 0, however with `mtd_flashpage` writing to address 0 will overwrite the firmware.
If the Flash is not mapped to zero, this would just crash.
To fix this an `.offset` member is added that should be set to the first writable page *after* the firmware.
With this, `mtd_flashpage` can then be used like any other MTD device.
#18608 will add a mechanism to set this offset at compile-time to allow for a MTD slot on the internal flash.
`tests/mtd_flashpage` should still work.
Split off #18608
alternative to #17964
> drivers/mtd_flashpage: implement pagewise API, don't use raw addresses

- pkg/nanors/Makefile
This is just a tiny update that fixes an error that occurs when the number of parity blocks is greater than the number of data blocks. 
`tests/pkg_nanors` still works
> pkg/nanors: bump version

- boards/esp32s2-lilygo-ttgo-t8/Kconfig
- boards/esp32s2-lilygo-ttgo-t8/Makefile
- boards/esp32s2-lilygo-ttgo-t8/Makefile.dep
- boards/esp32s2-lilygo-ttgo-t8/Makefile.features
- boards/esp32s2-lilygo-ttgo-t8/Makefile.include
- boards/esp32s2-lilygo-ttgo-t8/board.c
- boards/esp32s2-lilygo-ttgo-t8/doc.txt
- boards/esp32s2-lilygo-ttgo-t8/include/arduino_board.h
- boards/esp32s2-lilygo-ttgo-t8/include/arduino_pinmap.h
- boards/esp32s2-lilygo-ttgo-t8/include/board.h
- boards/esp32s2-lilygo-ttgo-t8/include/gpio_params.h
- boards/esp32s2-lilygo-ttgo-t8/include/periph_conf.h
- cpu/esp32/doc.txt
- cpu/esp32/doc_esp32s2.txt
- tests/malloc/main.c
This PR provides the support for the LILYGO TTGO T8 ESP32-S2 board which has a OLED display (not yet supported) and a SD-Card slot on board.
The board is equipped with a USB-C connector that connects either to a USB-to-UART bridge or to the USB-OTG/JTAG interface of the ESP32-S2 via some DIP switches.
The PR includes a very small fix of printf format string in `tests/malloc`. I can split it off.
t.b.d.
> boards: support for the LILYGO TTGO T8 ESP32-S2 board

- sys/fmt/fmt.c
Improves the compilation result for `scn_u32_dec` `scn_u32_hex` especially on `cortex-m` reducing either stack usage and or code size.
This makes use of unsigned int overflow (slightly less better without doing that `hexn`).
See godbolt (original versions got an `o` attached, modified versions got `k`s) all functions are  marked `_S_` defined to `static`
by assigning the global at end the compiled function can be changed (`deco deck  hexo hexk hexkk hexn`)
this PR is `hexkk` and `deck` 
run unit-test/test-fmt
```
<RIOT>/tests/unittests$ make tests-fmt
<RIOT>/tests/unittests$ make term
```
[godbolt](https://godbolt.org/z/MzT1zh4q1)
> sys/fmt: optimize scn_u32_dec scn_u32_hex

- cpu/gd32v/Kconfig
- cpu/gd32v/Makefile.dep
- cpu/gd32v/include/periph_cpu.h
- cpu/gd32v/periph/i2c.c
This PR provides an interrupt-driven version of the I2C low-level driver.
The existing I2C low-level driver for GDVF103 uses a busy-waiting approach where the status register is continuously polled while waiting for a certain status when sending or receiving. The MCU is thus occupied the whole time during a send or receive operation.
The driver provided with this PR uses an interrupt-driven approach. This is, while waiting for a certain status when sending or receiving, the calling thread is suspended and woken up by interrupts.
Since the I2C controller allows to receive up to two bytes before the application has to react, receiving a single byte, two bytes or more than two bytes needs a different handling for correct receiption. This requires a tricky implementation which distinguish a …
> cpu/gd32v/periph_i2c: interrupt based driver

- sys/include/net/nanocoap_sock.h
- sys/include/net/sock/util.h
- sys/net/application_layer/nanocoap/sock.c
- sys/net/application_layer/sock_dodtls/sock_dodtls.c
- sys/net/sock/sock_util.c
Currently the logic to establish a DTLS session is open-coded in each protocol that uses DTLS (CoAPS, DoDTLS).
To avoid code duplication, move the common code to establish a connection into a `sock_dtls_connect()` helper function that can be shared by it's users.
<details><summary>output of gnrc_sock_dodtls</summary>
```
> dodtls server [2001:db8::1]:853 5853 Client_identity secretPSK
DNS server: [2001:db8::1%5]:853
> dodtls request example.org inet6
example.org resolves to 2606:2800:220:1:248:1893:25c8:1946
> dodtls request example.org inet
example.org resolves to 93.184.216.34
```
</details>
> sock_dtls: move common code into sock_dtls_establish_session()

- examples/rust-gcoap/Cargo.lock
- examples/rust-hello-world/Cargo.lock
- sys/rust_riotmodules_standalone/Cargo.lock
- tests/rust_minimal/Cargo.lock
rust: Update riot-sys and riot-wrappers
* riot-wrappers:
* Fix infinite loop when using a Mutex
* Make ValueInThread Copy/Clone
* riot-sys:
* Export xxx_DEV (eg. I2C_DEV) C macros as functions
* Add auto_init_utils.h
CI checks should suffice.
This pulls in fixes from
* https://github.com/RIOT-OS/rust-riot-sys/pull/18
* https://github.com/RIOT-OS/rust-riot-sys/pull/17 / https://github.com/RIOT-OS/rust-riot-wrappers/issues/37
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/42 / https://github.com/RIOT-OS/rust-riot-wrappers/issues/41
> rust: Update riot-sys and riot-wrappers

- sys/include/net/gnrc/dhcpv6/client/simple_pd.h
- sys/net/gnrc/application_layer/dhcpv6/client_simple_pd.c
This makes it more straightforward to select an upstream interface if there are multiple possible options.
Tested `examples/gnrc_border_router` with
CFLAGS += -DCONFIG_GNRC_DHCPV6_CLIENT_6LBR_UPSTREAM_TYPE=NETDEV_ESP_WIFI
to set select the WiFi interface as the upstream.
The downstream was `tinyusb_netdev` in my case, so not a 6lo interface that could get auto-selected.
> gnrc_dhcpv6_client_simple_pd: select upstream based on type/index

- sys/crypto/aes.c
- sys/include/crypto/aes.h
- tests/sys_crypto/tests-crypto-aes.c
This struct is only used internally and it's naming does not follow the RIOT coding convention.
Code should still compile.
https://github.com/RIOT-OS/RIOT/pull/18148#issuecomment-1437337900
> sys/crypto: make AES_KEY struct private & rename it

- examples/suit_update/Makefile
- sys/shell/Makefile.dep
The `suit` command is pretty expensive as it calls `suit_worker_trigger()` which starts the SUIT worker thread.
If this function is not called otherwise, this will pull in the (quite substantial) suit worker thread stack.
If your application calls `suit_handle_url()` directly (doesn't make use of the worker thread) this saves `3 * THREAD_STACKSIZE_LARGE` Bytes of RAM.
> sys/shell: don't include suit command by default

- sys/include/net/gcoap.h
- sys/net/application_layer/cord/ep/cord_ep.c
- sys/net/application_layer/gcoap/gcoap.c
- tests/unittests/tests-gcoap/tests-gcoap.c
In #16688, an argument was added to the `gcoap_get_resource_list` function by creating a new function `gcoap_get_resource_list_tl` with a deprecation and roll-over plan.
This plan has not been acted on so far.
This PR shortens the original plan by just adding the argument to `gcoap_get_resource_list` and removing `gcoap_get_resource_list_tl` in a single go. The rationale for this deviation is that while it's a public API, its only two practical consumers are the (built-in) well-known/core implementation, and the (built-in) CoRE Resource Directory (cord) endpoint. Moreover, a further change to this API (switching over to `coap_block_slicer_t`) is expected to happen within this release cycle, which would take something like 4 total releases to get through otherwise, which is unrealistic for …
> gcoap: Finish the gcoap_get_resource_list_tl -> gcoap_get_resource_list renaming

- tests/rmutex/Makefile.ci
- tests/rmutex/README.md
- tests/rmutex/main.c
As the title says. This results in a few more boards being able to run the test.
Also, the wording in the README.md is improved to not be interpreted as generally threads with lower thread ID being preferred over threads with higher when locking a mutex.
```
make -C tests/rmutex BOARD=foo flash test
```
Fixes https://github.com/RIOT-OS/RIOT/issues/19140
> tests/rmutex: clean up test and reduce stack size

- doc/memos/README.md
- doc/memos/rdm0002.md
This RDM introduces a new Radio Hardware Abstraction Layer for 802.15.4 compliant radios.
Abstract:
```
This memo describes a Hardware Abstraction Layer (HAL) for radios compliant
with the IEEE802.15.4 standard. The work follows a technology-specific approach
to provide well defined hardware access that allows to implement agnostic
IEEE802.15.4 PHY and MAC layers on top. Additionally, the new HAL enables
integration of network stacks that require direct access to the radio.
```
~The proposed API, 2 PoC reference implementations (`nrf802154` and `at86rf23x`) and a small test application were implemented in [this branch](https://github.com/jia200x/RIOT/tree/poc/ieee802154_hal_pol).~
- [~Radio HAL API~](https://github.com/jia200x/RIOT/blob/poc/ieee802154_hal_pol/sys/include/net/ieee802154/rad …
> RDM: The 802.15.4 Radio HAL

- examples/telnet_server/main.c
From the commit msg:
> The telnet example prints a line to the console, but it is not ended with a newline. When using pyterm, the last line is then never shown as it reads the console line by line and is waiting for the end of the line.
> 
> This patch swaps use of `printf` for `puts` for the last line printed. This means the missing newline character gets added. This is also done to be consistent with the rest of the file, where puts is used whenever possible instead of printf.
1. `cd examples/telnet`
2. `make all flash term`
3. observe the final line "Local shell disabled" is printed, but would not have without this patch
- none known
> Add missing newline to output of telnet example

- drivers/include/matrix_keypad.h
This moves the documentation for the matrix keypad module from the header file to the doxygen group. With this a reader doesn't have to click to the header file definitions from the doxygen group to read the documentation.
Take a brief look at the generated doxygen.
None
> matrix_keypad: Move documentation to doxygen group

- sys/net/application_layer/nanocoap/link_format.c
We set the byte at the `end` postition [to 0](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/nanocoap/link_format.c#L61), but `buffer[sizeof(buffer)]` is actually outside of `buffer`, we have to use `sizeof(buffer) - 1`.
Thanks to @Teufelchen1 for spotting this!
Resource listing still works
```
> ncget coap://coap.me/
/test
/validate
/hello
/blåbærsyltetøy
/sink
/separate
/large
/secret
/broken
/weird33
/weird44
/weird55
/weird333
/weird3333
/weird33333
/123412341234123412341234
/location-query
/create1
/large-update
/large-create
/query
/seg1
/path
/location1
/multi-format
/3
/4
/5
```
> nanocoap_link_format: fix off-by-one error

- cpu/sam0_common/include/periph_cpu_common.h
- cpu/sam0_common/periph/adc.c
The precision of measurements can be increased by taking multiple measurements.
For this, the ADC implements an summation/averaging mode in hardware.
The best way I found to expose this in our ADC API is via the 16 bit resolution mode.
We can take up to 16 samples without exceeding the internal ADC register (after which 'automatic right shifts' happen - the result gets truncated).
> cpu/sam0_common: adc: implement 16 bit mode by oversampling

- dist/tools/insufficient_memory/add_insufficient_memory_board.sh
- dist/tools/insufficient_memory/create_makefile.ci.sh
`create_makefile.sh`:
- address all shellcheck warnings
- make script POSIX shell compatible
- use nproc to set the number of parallel jobs to increase throughput
- print error messages when building fails
- run `make info-boards-supported` with `EXTERNAL_BOARD_DIRS=""` to avoid adding out-of-tree boards to `Makefile.ci`.
- classify output as "not supported" also when used features are blacklisted, not only when required features are missing
`add_insufficient_memory_board.sh`:
- classify output as "not supported" also when used features are blacklisted, not only when required features are missing
Run the script; it should still work.
None
> dist/tools/insufficient_memory: Minor improvements

- dist/tools/ci/print_toolchain_versions.sh
Include the versions of the different ESP32 family toolchains in the output of `make print-versions`.
Run `make print-versions`
```
Operating System Environment
----------------------------
Operating System: "Ubuntu" "22.10 (Kinetic Kudu)"
Kernel: Linux 6.1.7-060107-generic x86_64 x86_64
System shell: /usr/bin/dash (probably dash)
make's shell: /usr/bin/dash (probably dash)
Installed compiler toolchains
-----------------------------
native gcc: gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0
arm-none-eabi-gcc: arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)
avr-gcc: avr-gcc (GCC) 5.4.0
msp430-elf-gcc: msp430-elf-gcc (Mitto Systems Limited - msp430-gcc 9.2.0.50) 9.2.0
riscv-none-elf-gcc: missing
riscv64-unknown-elf-gcc: riscv64-unknown-elf-gcc () 10.2.0
riscv-none-embed-gcc: missing …
```
> ci/print_versions: print all ESP32 toolchains

- sys/net/gnrc/network_layer/ipv6/static_addr/gnrc_ipv6_static_addr.c
To parse the static upstream address we should use `ipv6_addr_from_str()`, not `ipv6_prefix_from_str()` - otherwise the address will only be considered valid if it comes with a prefix length. 
Run `make -C examples/gnrc_border_router PREFIX_CONF=static all term` 
Upstream interface has no pre-configured address 
```
Iface  5  HWaddr: 76:8F:E6:D7:42:6D 
L2-PDU:1500  MTU:1500  HL:64  RTR  
inet6 addr: fe80::748f:e6ff:fed7:426d  scope: link  VAL
inet6 group: ff02::1:ffd7:426d
Iface  6  HWaddr: 56:FE  Channel: 26  NID: 0x23  PHY: O-QPSK 
Long HWaddr: AE:0F:4D:73:F7:54:56:FE 
State: IDLE 
ACK_REQ  L2-PDU:102  MTU:1280  HL:64  RTR  
RTR_ADV  6LO  IPHC  
inet6 addr: …
```
> gnrc_static: don't parse address as prefix

- boards/arduino-mega2560/Makefile.include
- boards/common/nucleo/Makefile.include
- boards/hifive1b/Makefile.include
- boards/microbit-v2/Makefile.include
- boards/nrf52840dk/Makefile.include
- boards/qn9080dk/Makefile.include
- dist/tools/usb-serial/README.md
- dist/tools/usb-serial/ttys.py
- doc/doxygen/src/flashing.md
- makefiles/tools/serial.inc.mk
This PR adds the ability to automatically detect the debug adapter for boards with an integrated programmer/debugger, if that debugger also provides the TTY.
This extends the TTY detection that can be enabled with `MOST_RECENT_PORT=1` to set `DEBUG_ADAPTER_ID` to the TTY's serial, but only if `DEBUG_ADAPTER_ID_IS_TTY_SERIAL` is set to `1` by the board (as not all boards have an integrated programmer/debugger).
Connect a HiFive-1B and a nRF52840DK at the same time and try `make BOARD=<nrf52840dk|hifive1b> MOST_RECENT_PORT=1 -C examples/default flash term` for both. The programmer will not reliably select the correct programmer in `master`. With this PR, it will.
None
> makefiles/tools/serial.inc.mk: Allow detection of debug adapter

- cpu/efm32/periph/dac.c
The documented behavior is:
> The value is always given as 16-bit value and is internally scaled to the actual resolution that the DAC unit provides (e.g. 12-bit). So to get the maximum output voltage, this function has to be called with value set to 65535 (UINT16_MAX).
The previous behavior was masking, now it's shifting.
* Run tests/periph_dac interactively and look at the voltage with an oscilloscope.
Before, the period was 100ms/16, now it's 100ms as advertised.
*Note: I couldn't do that yet, the above is just what I expect.*
Closes: https://github.com/RIOT-OS/RIOT/issues/19317
> efm32/dac: Shift instead of masking

- Makefile.dep
- boards/native/Makefile.dep
- boards/native/board_init.c
- boards/native/include/board.h
- boards/same54-xpro/Makefile.dep
- boards/same54-xpro/board.c
- makefiles/pseudomodules.inc.mk
- pkg/lwext4/Makefile
- pkg/lwext4/Makefile.dep
- pkg/lwext4/Makefile.include
- pkg/lwext4/doc.txt
- pkg/lwext4/fs/Makefile
- pkg/lwext4/fs/lwext4_fs.c
- pkg/lwext4/patches/0001-make-struct-ext4_mountpoint-public.patch
- sys/include/fs/lwext4_fs.h
- sys/include/vfs.h
- sys/include/vfs_default.h
- sys/vfs/vfs.c
This adds [lwEXT4](https://github.com/gkostka/lwext4) as a package and provides integration with MTD and VFS.
lwEXT4 is an implementation of the ext2/3/4 journaling file system. The different feature levels can be selected by the pseudo-modules `lwext2_vfs`, `lwext3_vfs` and `lwext4_vfs` respectively.
It is intended for use on SD cards (maybe large NAND flashes once we have support for those) as a more fault tolerant alternative to FAT. (If this is really the case has to be seen :wink:)
In `tests/vfs_default` enable one of the `lwext%_vfs` modules either on `native` or `same54-xpro`. (Other boards need the mount point configured)
> pkg/lwext4: add lightweight implementation of the ext2/3/4 filesystem

- makefiles/pseudomodules.inc.mk
- sys/Makefile.dep
- sys/include/usb/usbus.h
- sys/include/usb/usbus/cdc/ecm.h
- sys/usb/usbus/cdc/ecm/cdc_ecm.c
- sys/usb/usbus/cdc/ecm/cdc_ecm_netdev.c
- sys/usb/usbus/usbus.c
This commit adds support for URBs (USB Request/Response Blocks). These
allow for submitting multi-transfer sized buffers with USBUS handling
the individual usbdev xmits. Multiple URBs can be queued at once for a
single endpoint and USBUS will handle them in the order of submission.
OUT endpoint URBs must always consist of a whole number of full-sized
transfers (N x MaxEndpointSize). They will automatically finish after
the endpoint received a transfer less than the endpoint size.
IN endpoints can be arbitrary-sized and do not have to consist of a
whole number of full-sized transmissions. They support a flag to
indicate that the last transfer in the sequence must be less than a full
sized transfer (USBUS_URB_FLAG_AUTO_ZLP) and this adds a zero length
transfer at the end of the …
> USBUS: Add URB support

- dist/tools/esptools/install.sh
Quote all the things!
The script should still work as before
None
> esptools/install.sh: Fix shellcheck issues

- examples/gnrc_networking/Makefile.ci
- sys/net/network_layer/sixlowpan/sixlowpan_print.c
- sys/shell/cmds/gnrc_icmpv6_echo.c
- sys/shell/cmds/gnrc_netif.c
- sys/shell/cmds/gnrc_rpl.c
- sys/shell/cmds/gnrc_sixlowpan_ctx.c
- sys/shell/cmds/gnrc_udp.c
Strings output with `printf()` will automatically be placed in the `.text` section on AVR now.
This is not true for strings output with `puts()`.
Replace `puts()` with `puts()` by running 
sed -Ei 's/puts\(\"(.*)\"\)/printf\(\"\1\\n\"\)/g'
Observe the reduced `.data` RAM usage on AVR:
```
123950	   6710	  13123	 143783	  231a7	/home/benpicco/dev/RIOT/examples/gnrc_networking/bin/avr-rss2/gnrc_networking.elf
```
```
129840	   2042	  13123	 145005	  2366d	/home/benpicco/dev/RIOT/examples/gnrc_networking/bin/avr-rss2/gnrc_networking.elf
```
> shell/cmds: GNRC: replace puts() with printf()

- cpu/native/syscalls.c
This ensures that even when libc does not implement getchar through getc, any custom stdio is still in the loop when getchar is used.
Frankly, I don't know when this broke -- I'm pretty sure custom stdio worked just a few days ago -- but either way, without this patch RIOT on native currently bypasses a configured stdio for me.
* `make -C examples/saul all debug`
* `break stdio_read`
* `run`
Without this patch, observe how the shell runs w/o ever breaking. After, lots of breakpoint hits.
This is the way it behaves for me (Debian sid, libc6:i386 2.36-8). If it works for you before this patch, we might start bisecting the differences between the systems, but we may also accept that libcs may imlpement getchar in different ways, and not all of them pass by the getc which we're patching.
This …
> native/stdio: Explicitly provide getchar

- pkg/tinydtls/Makefile
- pkg/tinydtls/Makefile.dep
`gettimeofday()` (via `time()`) is only used to print timestamps in the debug output. 
We don't need this, use our own debug functions without the expensive timestamp.
With this, we can drop the requirement to include `libc_gettimeofday`.
Code should still compile
``` 
123068	    384	  24920	 148372	  24394	/home/benpicco/dev/RIOT/examples/dtls-sock/bin/openmote-b/dtls_sock.elf
```
```
107756	    272	  24776	 132804	  206c4	/home/benpicco/dev/RIOT/examples/dtls-sock/bin/openmote-b/dtls_sock.elf
```
upstream PR https://github.com/eclipse/tinydtls/pull/187
> pkg/tinydtls: drop libc_gettimeofday dependency

- sys/tiny_strerror/tiny_strerror.c
`tiny_strerror` was written specifically for AVR, so it makes sense to also use `flash_utils` there.
Modify `hello_world` to print an error:
```patch
+#include <string.h>
+#include <errno.h>
int main(void)
{
@@ -28,5 +30,7 @@ int main(void)
printf("You are running RIOT on a(n) %s board.\n", RIOT_BOARD);
printf("This board features a(n) %s MCU.\n", RIOT_MCU);
+    puts(strerror(EAGAIN));
+
return 0;
}
```
```
5520	   1098	    901	   7519	   1d5f	/home/benpicco/dev/RIOT/examples/hello-world/bin/avr-rss2/hello-world.elf
```
```
6532	    118	    917	   7567	   1d8f	/home/benpicco/dev/RIOT/examples/hello-world/bin/avr-rss2/hello-world.elf
```
```
2023-02-27 22:24:40,383 # main(): This …
```
> sys/tiny_strerror: make use of flash_utils.h

- Makefile.features
When running a command that affects multiple boards, it can be hard to find out what's the culprit, e.g. a leftover directory from a renamed board.
Generates errors like
```
/home/benpicco/dev/RIOT/Makefile.features:16: *** blackpill-128kib: CPU must be defined by board / board_common Makefile.features.  Stop.
```
instead of
```
/home/benpicco/dev/RIOT/Makefile.features:16: *** CPU must be defined by board / board_common Makefile.features.  Stop.
```
> Makefile.features: output board on error

- sys/include/vfs.h
- sys/shell/cmds/vfs.c
- sys/vfs/vfs.c
- tests/devfs/main.c
- tests/pkg_fatfs_vfs/main.c
- tests/pkg_littlefs/main.c
- tests/pkg_littlefs2/main.c
- tests/pkg_spiffs/main.c
- tests/pkg_tinyvcdiff/main.c
- tests/unittests/tests-vfs/tests-vfs-dir-ops.c
- tests/unittests/tests-vfs/tests-vfs-file-ops.c
- tests/unittests/tests-vfs/tests-vfs-file-system-ops.c
- tests/unittests/tests-vfs/tests-vfs-mount-constfs.c
- tests/vfs_iterate_mount/main.c
Sometimes we *need* to unmount the file-system *now* even if there are still open files (e.g. to perform a reboot).
So far this was prevented by a check in `vfs_umount()` to not allow to unmount a fs if it still has open files.
This adds a `force` option that will ignore the check and unmount the fs anyway.
> sys/vfs: add force option to vfs_umount()
