tests/sys/shell/Makefile, tests/sys/shell/Makefile.ci, tests/sys/shell/main.c, tests/sys/shell/tests/01-run.py
This tests if a blocking stdio read will allow other threads to be scheduled.
`periodic test 5` should print `test` 5 times from a separate thread
```
> periodic test 5
> test
test
test
test
test
```
requires #19002 to work on `native`
=> tests/shell: add test for preemption

tests/rust_libs/Makefile
In `main.c:115` the call
`ztimer_sleep(ZTIMER_MSEC, _periodic_ctx.period.ms);` depends on the module `ztimer_msec`. Apparently, this was previously pulled in indirectly and the missing dep has gone unnoticed. This adds the dep explicitly to fix compilation issues that now have surfaced in the CI.
Green CI
None
=> tests/rsut_libs: add missing dependency

doc/doxygen/src/js/riot-doxy.js
Fixes the bug that the side-nav on RIOT-doxygen website can not be resized (in Firefox) (See https://github.com/RIOT-OS/RIOT/issues/20414). 
Open <https://doc.riot-os.org/> and try to resize the side-nav on the left (using Firefox).
Closes https://github.com/RIOT-OS/RIOT/issues/20414
=> doc: Allow resizing of doxygen side-nav

makefiles/deprecated_modules.inc.mk, pkg/opendsme/include/opendsme/opendsme.h, sys/include/net/gnrc/gomach/gomach.h, sys/include/net/gnrc/lwmac/lwmac.h, sys/include/net/gnrc/mac/mac.h, sys/include/net/gnrc/nettype.h
Both `gnrc_lwmac` and `gnrc_gomach` as well as their common module `gnrc_mac` are effectively unmaintained (the last commit to these modules that wasn't a cleanup or adoption for API change was in 2017). So let's deprecate them and later on remove them. People requiring a MAC protocols can use OpenDSME as an alternative.
Since I also had a look at the OpenDSME doc, I found a rendering issue there for which I piggybacked a fix.
`make doc` should generate a documentation with those modules (and their `nettype` on the deprecated list. Building any application that uses those modules (e.g. `examples/gnrc_networking_mac`) should show a warning that deprecated modules are used.
As discussed in #16502.
=> gnrc_mac / gnrc_lwmac / gnrc_gomach: Deprecate modules

examples/gcoap/client.c, sys/include/net/gcoap.h, sys/net/application_layer/cord/ep/cord_ep.c, sys/net/application_layer/cord/epsim/cord_epsim.c, sys/net/application_layer/cord/lc/cord_lc.c, sys/net/application_layer/gcoap/dns.c, sys/net/application_layer/gcoap/forward_proxy.c, sys/net/application_layer/gcoap/gcoap.c
The deprecation notice for `gcoap_req_send_tl()` says, it was supposed to be made an alias for `gcoap_req_send()` after the 2022.01 release. This never happened, so let's do that 2 years after ;-). As a consequence I bumped up the actual removal of `gcoap_req_send_tl()` to after the 2024.10 release.
Should be straight forward, as `gcoap_req_send()` was a wrapper around `gcoap_req_send_tl()` with the default parameter `GCOAP_SOCKET_TYPE_UNDEF` already. As this adds that default parameter to all calls of `gcoap_req_send()`, nothing should change. So compilation should catch any issues.
=> gcoap: make gcoap_req_send_tl() an alias of gcoap_req_send()

boards/olimex-msp430-h2618/include/periph_conf.h, boards/z1/include/periph_conf.h, cpu/msp430/Makefile.features, cpu/msp430/include/f2xx_g2xx/msp430_regs.h, cpu/msp430/include/f2xx_g2xx/periph_cpu.h, cpu/msp430/periph/Makefile, cpu/msp430/periph/spi_usci.c, cpu/msp430/periph/uart_usci.c, cpu/msp430/periph/usci.c, examples/gnrc_lorawan/Makefile.ci, examples/suit_update/Makefile.ci, tests/drivers/bme680/Makefile.ci, tests/net/gnrc_ndp/Makefile.ci, tests/net/gnrc_rpl_p2p/Makefile.ci, tests/net/gnrc_sock_udp/Makefile.ci, tests/pkg/fatfs_vfs/Makefile.ci, tests/pkg/u8g2/Makefile.ci, tests/riotboot_flashwrite/Makefile.ci, tests/sys/bloom_bytes/Makefile.ci, tests/sys/conn_can/Makefile.ci, tests/sys/ps_schedstatistics/Makefile.ci, tests/sys/suit_manifest/Makefile.ci
This cleans up the USCI based UART and SPI implementations and allows
multiple instances of either interface to be configured by the
boards. In addition, it allows sharing the USCI peripherals to provide
multiple serial interfaces with the same hardware (round-robin).
With an PCB sandwich consisting of an `olimex-msp430-h2618` plugged into our Arduino UNO adapter and our peripheral selftest shield plugged into the other side of said adapter (so that SPI MISO and MOSI are conntected):
```
make BOARD=olimex-msp430-h2618 -C tests/periph/spi flash term
make: Entering directory '/home/maribu/Repos/software/RIOT/msp430/tests/periph/spi'
Building application "tests_spi" for "olimex-msp430-h2618" with MCU "msp430".
"make" -C /home/maribu/Repos/software/RIOT/msp430/boards/common/init
"make" -C …
```
=> cpu/msp430/f2xx: clean up periph_uart,periph_spi 

sys/include/net/gcoap.h
Of course I realize some quality defects in #20514 only after it was merged. This fixes that.
Just formatting and documentation fixes. So compilation by the CI and looking at the built documentation should suffice.
Follow-up on #20514
=> gcoap: fix code quality defects

boards/nucleo-c031c6/Makefile.features, boards/nucleo-c031c6/include/periph_conf.h
This PR adds to the Nucleo-0c31c6 PWM configuration.
Flash the board using `tests/periph/pwm` program. Check if you could, for example, change LED 
intensity using PWM. 
None.
=> boards/nucleo-c031c6: add PWM configuration

cpu/native/include/periph_cpu.h, cpu/native/periph/gpio_mock.c, cpu/native/periph/qdec.c
Modify gpio-mock to allow arbitrary GPIO emulation.
Build:
```shell
$ make -C tests/periph/gpio BOARD=native -j
make : on entre dans le répertoire « /home/gdo/Developpement/Informatique/Personnel/cogip/RIOT/tests/periph/gpio »
Building application "tests_gpio" for "native" with CPU "native".
"make" -C /home/gdo/Developpement/Informatique/Personnel/cogip/RIOT/boards/common/init
"make" -C /home/gdo/Developpement/Informatique/Personnel/cogip/RIOT/boards/native
"make" -C /home/gdo/Developpement/Informatique/Personnel/cogip/RIOT/core
"make" -C /home/gdo/Developpement/Informatique/Personnel/cogip/RIOT/core/lib
"make" -C /home/gdo/Developpement/Informatique/Personnel/cogip/RIOT/cpu/native
"make" -C /home/gdo/Developpement/Informatique/Personnel/cogip/RIOT/drivers
"make" -C …
```
=> cpu/native: add gpio-mock

dist/tools/eclipsesym/cmdline2xml.sh
This is a very simple change in `dist/tools/eclipsesym/cmdline2xml.sh`, just change `egrep` in `grep -E`.
The egrep and fgrep commands have been deprecated since 2007. Beginning with GNU Grep 3.8, calling these commands will now issue a warning to the user that instead they should use grep -E and grep -F, respectively.
=> Avoid using egrep

boards/b-u585i-iot02a/Makefile.features, boards/nucleo-u575zi-q/Makefile.features, cpu/stm32/periph/rtc_all.c, cpu/stm32/periph/rtc_mem.c
This PR adds support for the real-time clock on the stm32u5 series devices.
Tested with `tests/periph/rtc` with the following output:
Which indicates that everything works I think
=> cpu/stm32u5: Enable rtc support

boards/feather-nrf52840-sense/Makefile.dep
This will help handle multiple board variants such as rev B and C.
Test on both variants with SAUL.
I ran on both the blue and black boards:
<details>
```
$ BOARD=feather-nrf52840-sense make -C examples/saul flash-only term
make: Entering directory '/home/weiss/repos/RIOT/examples/saul'
stty -F /dev/ttyACM0 raw ispeed 1200 ospeed 1200 cs8 -cstopb ignpar eol 255 eof 255
sleep 3
[INFO] uf2conv.py not found - fetching it from GitHub now
CC= CFLAGS= make -C /home/weiss/repos/RIOT/dist/tools/uf2
[INFO] uf2conv.py successfully fetched!
/home/weiss/repos/RIOT/dist/tools/uf2/uf2conv.py -f 0xADA52840 /home/weiss/repos/RIOT/examples/saul/bin/feather-nrf52840-sense/saul_example.hex --base 0x1000
Converted to uf2, output size: 66560, start address: 0x1000
Flashing /media/weiss/FTHRSNSBOOT …
```
=> boards/feather-nrf52840-sense: use generic lsm6dsxx

sys/include/checksum/crc16_ccitt.h
Hello 🦔
This removes the long deprecated `crc16_ccitt_update` and `crc16_ccitt_calc` functions.
CI should be sufficient.
=> sys/checksum: Remove deprecated crc16_ccitt functions

sys/include/suit/transport/coap.h
Hey hey 🐐
This removes a deprecated function `suit_coap_run`. I do not see any usage within RIOT so the removal should not have side effects. 
CI should be sufficient. 
deprecated in #18551
=> sys/suit: Remove deprecated suit_coap_run function

examples/rust-gcoap/Cargo.lock, examples/rust-hello-world/Cargo.lock, sys/rust_riotmodules_standalone/Cargo.lock, tests/rust_minimal/Cargo.lock
This pulls in https://github.com/RIOT-OS/rust-riot-wrappers/pull/87, unblocking https://github.com/RIOT-OS/RIOT/pull/20529.
CI should suffice.
=> rust: Update riot-wrappers

cpu/stm32/periph/gpio_ll_irq.c
From the commit msgs:
```
cpu/stm32/gpio_ll: make style consistent
This block of code inconsistently made use of else-if statments. The
patch makes the use consistent. The change also makes the code a bit
simpler to read.
```
```
cpu/stm32/gpio_ll: fix ifdef
APB12 is never defined as a macro. It is an element in the bus_t enum.
Therefore, the test to check if it is defined will always fail.
APB12 is not a real bus. It is the second register of the APB1 bus. I am
not aware of any STM32 family where the ABP2 bus is implmented (ie
RCC_APB2ENR_SYSCFGEN is defined) and devices attached to said bus are
enabled via the APB1 second register. For this reason, the fix is to
simply remove the check.
```
I ensured I did not break the build by doing `make -C tests/periph/gpio_ll/ BOARD=nucleo-f767zi`. …
=> cpu/stm32: Fix ifdefs in periph_gpio_ll

sys/net/application_layer/gcoap/Makefile.include, sys/net/application_layer/nanocoap/Makefile.include
The initial DTLS handshake can be larger than a block in CoAP block-wise.
#19892 reduced the DTLS buffer to a CoAP block size + 36 bytes.
This has proven to be too little, breaking DTLS clients.
Bump `DTLS_MAX_BUF` to be at least 200 bytes as this has proven to work well in the past.
First, create the tap interfaces by running `sudo dist/tools/tapsetup/tapsetup`.
In one terminal, run the GCoAP DTSL server:
`make -C examples/gcoap_dtls PORT=tap1 all term`
```
2024-02-26 20:18:43,184 # main(): This is RIOT! (Version: 2024.04-devel-327-gb8d58-DTLS_MAX_BUF-fix)
2024-02-26 20:18:43,184 # gcoap example app
2024-02-26 20:18:43,185 # All up, running the shell now
2024-02-26 20:22:23,060 # > ifconfig
2024-02-26 20:22:23,060 # Iface  7  HWaddr: 5A:1A:98:23:2D:6C 
2024-02-26 20:22:23,061 # …
```
=> coap: ensure DTLS buffer is at least 200 bytes

sys/net/application_layer/cord/lc/cord_lc.c
When a Resource Directory reports overly long .well-known/core results, those might be truncated due to a limited buffer. This PR ensures that the parts that are received are processed.
It also removes zeroing of the buffer -- clif does not require C style string termination.
* Run aiocoap's aiocoap-rd
* run examples/cord_lc with cord_lc [fe80::f30:40e4:6c93:e17d]:5683 endpoint
* You should get error -4 indicating that there is no endpoint
@maribu provided the original version of this.
@Teufelchen1, can this still go in?
=> cord_lc: Process truncated reads

tests/sys/shell/Makefile.ci, tests/sys/shell/main.c
Increase the stack of the periodic thread which is started with the `periodic` command of `tests/sys/shell`.
On LLVM toolchain, the test fails as only one tick occurs. With this patch the test works as intended.
The behavior of the LLVM is unclear to me here, as it seems there is some data corruption occurring on the stack. 
CI catches this, so let's run the test on CI once again.
See [CI tests](https://ci.riot-os.org/details/branch/master/tests)
=> tests/sys/shell: increase the stack size of periodic thread

sys/include/shell.h
To my understanding it is widely understood in the community that shell access is equivalent to root access on the device -- a) because modules are additive and shell commands are easily pulled in that allow all kinds of access, and b) because string parsing is hard.
This states this plainly in the documentation.
=> sys/shell/doc: Shell access is root access

sys/net/application_layer/cord/lc/cord_lc.c
When a Resource Directory reports overly long .well-known/core results, those might be truncated due to a limited buffer. This PR ensures that the parts that are received are processed.
It also removes zeroing of the buffer -- clif does not require C style string termination.
* Run aiocoap's aiocoap-rd
* run examples/cord_lc with cord_lc [fe80::f30:40e4:6c93:e17d]:5683 endpoint
* You should get error -4 indicating that there is no endpoint
@maribu provided the original version of this.
@Teufelchen1, can this still go in?
=> cord_lc: Process truncated reads [backport 2024.01]

tests/drivers/at_unit/test_all_configs.sh, tests/drivers/at_unit/tests-at.c
#20540 breaks two things:
- `tests/drivers/at/tests-with-config/test_all_configs.sh` can not find the AT unit tests anymore
- afaik there is no UART dev 1 on native, so the unit tests segfault
This PR fixes these issues.
`tests/drivers/at_unit/test_all_configs.sh` should finish successfully.
#20540
=> tests/drivers/at_unit: fix unit tests on native

boards/feather-nrf52840-sense/include/board.h
Add the `WS281X_PARAM_PIN` for `feather-nrf52840-sense` so `tests/drivers/ws281x/` works out of the box.
```
BOARD=feather-nrf52840-sense make -C tests/drivers/ws281x/ flash
```
should flash :)
=> boards/feather-nrf52840-sense: Add WS281X_PARAM_PIN

pkg/nimble/scanlist/nimble_scanlist.c
Hello 🪰
this ensures that bogus advertisements are always ignored.
The behavior of a failing assertion during debug builds is kept.
One option is to build & run the scanner example:
`make -C examples/nimble_scanner/ flash term`
=> pkg/nimble: Ignore bogus adv. during scan

boards/nrf9160dk/include/board.h, cpu/nrf9160/vectors/vectors_nrf9160.c
On master, GPIO interrupts are broken for nRF9160 MCU. (Dummy handler is called and thus hardfault).
This PR renames the gpiote isr to matches the behavior of nRF53. With this, the GPIO ISR works as expected.
The second commit also enables internal pullups on all nRF9160DK boards buttons as they are required for the hardware to work.
Flash  `tests/buttons` on `nrf9160dk` board and play with the onboard buttons.
None.
=> cpu/nrf9160: fix GPIOTE ISR

sys/isrpipe/read_timeout/read_timeout.c
`isrpipe_read_timeout()` always sets a timer, adding unnecessary overhead for small, frequent reads (like in the AT driver). With this PR, a timer is set only if no data is available.
I tested this with the AT unit tests.
=> sys/isrpipe/read_timeout: don't set up timer if data is available

sys/include/shell.h
Trouble with stdin and the shell can be hard to debug, and may send people off to a wild goose chase:
```
> coap get 2001:db8:8000:0:acf7:8017:ce77:b42a 5683 /.well-known/core
```
Is that an issue with CoAP? No. The shell? No. Let's ask on matrix... 🪿🪿🪿
This PR cuts the chase short when looking at the shell documentation and its buffer length.
Please don't, it's annoying to forget everything written above and go through the debug steps once more with the updated documentation. Instead, just look at the documentation and ponder whether it'd have cut the chase short.
The warning can go away once the ISR queue mechanism for stdin is replaced with something that has backpressure, so that (in the concrete case where it was discovered) the USB CDC-ACM can start sending NACKs until the stdin …
=> shell/doc: Point users who run into shell buffer issues to the stdin buffer

boards/nucleo-f767zi/doc.txt
This PR adds to the `nucleo-f767zi` board documentation page MCU table with links to datasheets.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f767zi.html 
```
None
=> boards/nucleo-f767zi: doc update

sys/suit/handlers_command_seq.c
If we run production firmware and provide a manifest with a too large URL, don't crash with a hard to debug error, but return an error value instead.
https://github.com/RIOT-OS/RIOT/security/advisories/GHSA-c4p4-vv7v-3hx8
=> sys/suit: return error when URL buffer is too small

sys/shell/cmds/lwip_netif.c
This PR adds to lwip ifconfig shell command, ability to configure IPv4 address, mask and gateway.
Enable in `example/gcoap` lwip IPv4 stack: in Makefile, line 17 change:
```
LWIP_IPV4 ?= 0
```
to 
```
LWIP_IPV4 ?= 1
```
Configure `tap0` interface:
```
sudo ip tuntap add tap0 mode tap user ${USER}
sudo ip link set tap0 up
```
Compile example and run it with `tap0` interface:
```
make clean
make
./bin/native/gcoap_example.elf tap0
```
Test new subcommands added to `ifconfig` command:
```
ifconfig help
ifconfig add4 ...
```
None
=> sys/shell/lwip: add IPv4 configuration to lwip ifconfig command

sys/include/net/gcoap.h
PR #17471 moved the location of the example. This PR adjust sources to changes.
=> gcoap: update the example reference

core/include/thread.h, core/lib/include/irq.h, drivers/include/periph/gpio_ll.h, drivers/include/periph/timer.h, sys/include/architecture.h, sys/include/atomic_utils.h, sys/include/flash_utils.h
We occasionally have some public `foo.h` header that includes a private `foo_arch.h` header. Users are expected to include the `foo.h` header and not the `foo_arch.h`. However, clangd will claim that the `#include` of `foo.h` is unused if only functions / macros/ types / ... from `foor_arch.h` is used and nothing from `foo.h`.
This adds the `IWYU pragma: export` comment to the include of `foo_arch.h` in `foo.h`, so that clangd treats functions / macros / types provided by `foo_arch.h` as if they were instead provided by `foo.h`, which fixes the false positives.
In `master`, the include of `irq.h` is often incorrectly labeled as unneeded by clangd (e.g. in VS code). This should get rid of these false positives.
See also: https://github.com/RIOT-OS/RIOT/pull/20570
=> tree wide: add `IWYU pragma: export` where needed

cpu/msp430/periph/timer.c, tests/periph/timer/main.c
The API doc for `timer_query_freqs()` says it should return 0 Hz as frequency when the prescaler index is out of range. This changes the MSP430 timer driver to live up to the spec.
It also sneaks in an extension to the test app, so that in the future offending code is more easily detected.
Run the new test. It should pass with this PR, but would fail on master (when the next test is backported).
None
=> cpu/msp430/periph_timer: fix timer_query_freqs()

cpu/msp430/periph/timer.c
The driver assumes that timer A and timer B have the same register layout regarding all the features exposed by the driver. This is backed by the MCU family datasheets for the MSP430 x1xx and the MSP430 G2xx / F2xx MCUs (and likely more families).
The assert() is pretty limited in coverage, but more to document why a "timer A clear" mask is used but still claiming the driver also works for timer B. It just looks too much like a bug otherwise.
Green CI.
None
=> cpu/msp430/periph_timer: add a static_assert() for clear mask

boards/olimex-msp430-h2618/include/board.h
The MSP430 timer prescaler can device the 16 MHz clock down to (16 / 2^x) MHz, with 0 <= x < 4. So no slower than 2 MHz.
With the current ztimer config the clock would run at twice the speed.
The tests wouldn't really catch this, but the datasheet and the test in `tests/periph/timer` can confirm that it gets no slower than 2 MHz with a 16 MHz subsystem main clock.
None
=> boards/olimex-msp430-h2618: fix ztimer config

sys/net/application_layer/gcoap/dns.c
Hello 🦇
this fixes a small typo, ensuring the correct buffer is checked.
`make -C tests/net/gcoap_dns all test` should be enough, I do not see other use cases of this function.
=> net/gcoap: Fix typo, replacing _uri with _proxy

cpu/msp430/periph/uart_usci.c
In TX-only mode the UART was previously release before all bits of the last byte were shifted out. This adds a busy loop waiting while the peripheral is still busy, fixing the issue.
`make BOARD=olimex-msp430-h2618 flash term -C tests/sys/busy_wait` now gives:
```
[...]
2024-04-14 16:05:16,734 # main(): This is RIOT! (Version: 2024.04-devel-652-g3cdc43)
2024-04-14 16:05:16,734 # waiting for 10 µs…
2024-04-14 16:05:16,735 # took 427 µs (diff: 417 µs)
2024-04-14 16:05:16,735 # waiting for 100 µs…
2024-04-14 16:05:16,735 # took 848 µs (diff: 748 µs)
2024-04-14 16:05:16,735 # waiting for 1000 µs…
2024-04-14 16:05:16,735 # took 4508 µs (diff: 3508 µs)
2024-04-14 16:05:16,735 # waiting for 10000 µs…
2024-04-14 16:05:16,736 # took 40651 µs (diff: 30651 µs)
2024-04-14 16:13:23,451 # Exiting …
```
=> cpu/msp430/periph_uart: Fix uart_write() for USCI peripheral

drivers/lsm303agr/Cargo.toml, drivers/lsm303agr/Makefile.dep, drivers/lsm303agr/src/lib.rs, examples/rust-gcoap/Cargo.lock, examples/rust-gcoap/Cargo.toml, examples/rust-gcoap/src/lib.rs, examples/rust-hello-world/Cargo.lock, sys/rust_riotmodules_standalone/Cargo.lock, tests/rust_minimal/Cargo.lock
This PR does three things that are easiest done in one go (because due to git dependencies otherwise it would require selective updates):
* It does a big round of Rust dependency updates. Notable changes are:
* riot-sys: SUIT headers included, ADC line macros fixed, missing include paths fixed (b4bd4bde..501b3540)
* riot-wrappers (fbc6cfe8..05835b3d) -- PRs excluding CI and test related ones that have no impact on RIOT applications themselves:
* Additions (note that updates on the trait crates coap-message and embedded-hal are compatible, they *add* traits rather than updating dependencies):
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/60
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/72
* https://github.com/RIOT-OS/rust-riot-wrappers/pull/73
* …
=> treewide: Rust updates [backport 2024.01]

cpu/esp8266/include/periph_cpu.h, dist/tools/doccheck/exclude_simple
During working on PR #20556 I observe in the `make doc` output error:
```
.../RIOT/cpu/esp8266/include/periph_cpu.h:335: warning: end of file with unbalanced grouping commands
```
This PR fix it.
Execute `make doc` and observe output - with this PR mentioned error did not appear.
None
=> cpu/esp8266: fix doxygen unbalanced grouping

sys/include/vfs.h, sys/vfs/vfs.c, tests/unittests/tests-vfs/tests-vfs-file-system-ops.c
This has the following advantages:
- faster and leaner when C11 atomics are not efficient (e.g. on LLVM this is almost always the case, as LLVM will only use efficient atomics if it doesn't has to bail out to library calls even for exotic things)
- Even for GCC e.g. on the nucleo-f429zi this safes 72 B of .text for examples/filesystem despite runtime checks added for over- and underflow
- less pain in the ass for C++ and rust users, as both C++ and c2rust are incompatible with C11 atomics
- adds test for overflow of the open file counter for more robust operation
- adds `assumes()` so that underflows are detected in non-production code
No regressions in VFS operations.
**Beware:** I don't have the time to test this, so this is completely untested.
rust compatibility issues where reported …
=> sys/vfs: use atomic_utils rather C11 atomics

sys/net/ble/skald/skald_eddystone.c
Call for feedback: Should we assume somebody builds an app where the URL parameter is not a compile time constant?
If so, we need to check the length even when assertions are disabled.
=> ble/skald: Always enforce URL length check

boards/stm32f4discovery/doc.txt
Most importantly, this fixes outdated statements about stdio, which now by default is over USB rather than UART.
Check the generated doc
None
=> boards/stm32f4discovery: update and clean up doc

boards/feather-nrf52840-sense/Makefile.dep, boards/feather-nrf52840-sense/include/board.h, drivers/saul/init_devs/auto_init_ws281x.c, drivers/saul/init_devs/init.c, drivers/ws281x/Makefile, drivers/ws281x/Makefile.dep, drivers/ws281x/include/ws281x_params.h, drivers/ws281x/ws281x_saul.c, examples/rust-gcoap/Cargo.lock, examples/rust-hello-world/Cargo.lock, sys/rust_riotmodules_standalone/Cargo.lock, tests/rust_minimal/Cargo.lock
Support the ws281x driver on saul... starting with :drum: the `feather-nrf52840-sense` .
Note that this only allows control of all LEDs at once since saul does not really have a way to handle subindex or array control (for example LED array). For our use case we would like to keep it simple now but if we did want to allow saul to control individual LEDs in the future here are some considerations:
- `saul_entries` would be of size `WS281X_NUM * WS281X_PARAM_NUMOF` and one could iterate over this matrix, though there would still be no mechanism to address each one...
- The `ws281x_t` should change to be for each LED and not an array (likely a bit of rework) but then each `dev` could be for each LED
- Add a mechanism in saul to not only interact with an object, but an array of objects.
All …
=> drivers/ws281x: Add saul support

drivers/Makefile.dep, drivers/at24cxxx/Makefile.include, drivers/at24cxxx/include/at24cxxx_defines.h, drivers/at24cxxx/include/at24cxxx_params.h, drivers/include/at24cxxx.h
This PR adds the ST M24C01 I2C EEPROM to the predefined constants in the at24cxxx driver. Since it is the first non-Atmel/Microchip device, the documentation has been enhanced to make clear the driver is not exclusively for devices from Atmel/Microchip.
Furthermore, documentation has been added to make using the driver easier (via pseudomodules) and a small example how to initialize the EEPROM device with the given data structures.
The code has been tested with the Nordic nRF52840-DK and an ST M24C01WP EEPROM as shown in Issue #20202 with the example code and Makefile given in this issue.
The expected impact on other parts of RIOT is low, since only features have been added which concentrate on the at24cxxx driver which do not affect other parts.
A global driver pseudomodule with the …
=> drivers/at24cxxx: Add M24C01 device and enhance documentation

drivers/mtd_emulated/mtd_emulated.c, tests/pkg/littlefs/Makefile.ci
Hei 🦫
Fixes a minor potential for integer overflow.
CI / good review
Maybe `make -C tests/unittests tests-mtd test`
=> drivers/mtd: Add check for interger overflow

cpu/nrf5x_common/periph/pm.c
This PR implements `pm_off()` support for nRF9160 and nRF53.
The register moved to the regulator peripheral compared to nRF52.
Nordic also have two different names for the same bit of this register, so I add a small workaround. (Could have use '1' instead but I prefer to clearly identify bits within registers).
Run `tests/periph/pm` on `nrf9160dk` or `nrf5340dk-app`
and use `pm off` command
None.
=> cpu/nrf5x: implement pm_off() for nRF53/9160

cpu/samd5x/periph/can.c
The debug output was showing the standard filter section instead of showing the extended filter section.
This is fixed besides a little tweak to the debug output consisting of naming the message RAM section as in the datasheet
=> cpu/samd5x: reword & correct debug output

boards/nucleo-f429zi/doc.txt, boards/nucleo-f439zi/doc.txt
This PR adds some improvements to the boards documentation pages.
Nucleo-f439zi
- addition of MCU table,
- addition of section concerning RIOT shell access (see PR #17453)
Nucleo-f429zi
- minor changes in the MCU table (typos, ADC, RTC, Timers, etc.)
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f429zi.html 
xdg-open doc/doxygen/html/group__boards__nucleo-f439zi.html 
```
PR #17453
=> boards/nucleo-f429zi & f439zi: documentation improvements 

tests/drivers/at/main.c
This PR adds to the `tests/driver/at` send... functions checks if AT device is initialized and power on.
Flash device with `tests/driver/at` program and try to send some AT command without initialization and power on.
Without this PR send... commands waits for timeout.
With this PR appropriate error message is shown.
None.
=> tests/drivers/at: add check if device is initialized before sending command

boards/nrf5340dk-app/doc.txt, boards/thingy52/doc.txt
The nRF family's NFC radio part implements only the tag emulation, and can neither access other tags nor do peer-to-peer mode.
Look at the changed documentation.
I'd rather not rant on about how much time I've sunk without this warning. (Yes I wrote the thingy:52 documentation myself).
=> boards/doc: Explicitly warn when nRF chips are advertised as NFC supporting

doc/doxygen/src/getting-started.md
The problem of missing access rights to the serial device has come up for one of our students while trying to setup their RIOT development environment.
I would have liked to point them to a sentence in the RIOT documentation, preferably in one of the first documents that a new user would read.
This PR adds two sentences and an example command line to fix this to the "getting started" page.
Check the generated docs.
None
=> doc/getting-started: add hint for correct access rights on serial device

cpu/msp430/include/cpu.h
Apply the following patch:
```diff
diff --git a/examples/default/main.c b/examples/default/main.c
index b847e0e5a1..b8c6856395 100644
--- a/examples/default/main.c
+++ b/examples/default/main.c
@@ -32,6 +32,15 @@
#include "net/gnrc.h"
#endif
+static int _cmd_assert(int argc, char **argv)
+{
+    (void)argc;
+    (void)argv;
+    assert(0);
+}
+
+SHELL_COMMAND(assert_fail, "trigger a blowing assertion", _cmd_assert);
+
int main(void)
{
#ifdef MODULE_NETIF
```
Then run
```
make BOARD=olimex-msp430-h1611 flash term -C examples/default 
make: Entering directory '/home/maribu/Repos/software/RIOT/master/examples/default'
Building application "default" for "olimex-msp430-h1611" with CPU "msp430".
"make" -C …
```
=> cpu/msp430: implement get_caller_pc

boards/common/nrf52/Makefile.include, cpu/nrf52/Makefile.include
Since a version update of JLinkExe about four years ago, it performs a check of the Flash memory range, which depends on the JLINK_DEVICE selected. Currently, the JLINK_DEVICE variable is set in the boards/common/nrf52/Makefile.include file, which sets it to "NRF52". This seems to default to the nRF52832 chip, which is incorrect for all boards not using this chip.
The issue is described in #14576 and it seems to trigger (mostly? only?) when flashing images that are close to the maximum flash size of the nRF52832 or when specifying explicit memory addresses. Therefore the bug has been mostly unnoticed in normal operation and is triggered when trying to flash a bootloader to the nRF52840 chip.
This PR removes the JLINK_DEVICE variable from the common Makefile.include, because the boards …
=> boards/nRF52xx: correctly set JLINK_DEVICE

tests/sys/psa_crypto/tests/01-run.py
This should hopefully fix the failing nightly builds since https://github.com/RIOT-OS/RIOT/commit/ad9d50163e7b8c53e6c92016f3b3944adbb5023e
The test uses ed25519 in software and thereby takes some time to finish. Increasing the timeout to 20s fixed it locally with a samr21-xpro board.
Look at the minimal diff, merge and then hope for the next nightly.
thanks to @maribu for mentioning the failing builds
=> tests/sys/psa_crypto: increase timeout

boards/olimex-msp430-h2618/include/board.h
The MSP430 timer prescaler can device the 16 MHz clock down to (16 / 2^x) MHz, with 0 <= x < 4. So no slower than 2 MHz.
With the current ztimer config the clock would run at twice the speed.
The tests wouldn't really catch this, but the datasheet and the test in `tests/periph/timer` can confirm that it gets no slower than 2 MHz with a 16 MHz subsystem main clock.
None
=> boards/olimex-msp430-h2618: fix ztimer config [backport 2024.04]

cpu/msp430/periph/uart_usci.c
In TX-only mode the UART was previously release before all bits of the last byte were shifted out. This adds a busy loop waiting while the peripheral is still busy, fixing the issue.
`make BOARD=olimex-msp430-h2618 flash term -C tests/sys/busy_wait` now gives:
```
[...]
2024-04-14 16:05:16,734 # main(): This is RIOT! (Version: 2024.04-devel-652-g3cdc43)
2024-04-14 16:05:16,734 # waiting for 10 µs…
2024-04-14 16:05:16,735 # took 427 µs (diff: 417 µs)
2024-04-14 16:05:16,735 # waiting for 100 µs…
2024-04-14 16:05:16,735 # took 848 µs (diff: 748 µs)
2024-04-14 16:05:16,735 # waiting for 1000 µs…
2024-04-14 16:05:16,735 # took 4508 µs (diff: 3508 µs)
2024-04-14 16:05:16,735 # waiting for 10000 µs…
2024-04-14 16:05:16,736 # took 40651 µs (diff: 30651 µs)
2024-04-14 16:13:23,451 # Exiting …
```
=> cpu/msp430/periph_uart: Fix uart_write() for USCI peripheral [backport 2024.04]

cpu/msp430/periph/timer.c, tests/periph/timer/main.c
The API doc for `timer_query_freqs()` says it should return 0 Hz as frequency when the prescaler index is out of range. This changes the MSP430 timer driver to live up to the spec.
It also sneaks in an extension to the test app, so that in the future offending code is more easily detected.
Run the new test. It should pass with this PR, but would fail on master (when the next test is backported).
None
=> cpu/msp430/periph_timer: fix timer_query_freqs() [backport 2024.04]

doc/doxygen/src/terminal-programs.md
This PR adds `putty` terminal to the list (very convenient in the Windows ;) ) and sort all terminal programs alphabetically.
```
make doc
xdg-open doc/doxygen/html/terminal-programs.html 
```
PR #20493
=> doc/terminals: add putty and sort terminals

boards/common/stm32/include/cfg_timer_tim2.h, boards/common/stm32/include/cfg_timer_tim5.h, boards/common/stm32/include/cfg_timer_tim5_and_tim2.h
This patch just simplifies the the ifedef logic in a few shared stm32 headers, in support of the STM32H7 port.
try running:
``` sh
#! /bin/sh -e
boards=""
boards="$boards `ls -1 boards/ | grep stm32`"
boards="$boards `ls -1 boards/ | grep nucleo`"
for board in $boards
do
make -C examples/blinky BOARD=$board
done
```
none known
=> boards/common/stm32: simplify ifdef logic

cpu/cortexm_common/panic.c
Rework the way `bkpt` instruction is call on panic for Cortex-M MCU.
Currently, this instruction is called everytime on panic. However, when a debug session is not active (no GDB running),  and if a panic occured, the `bkpt` instruction will either escalate the current fault to hardfault or the CPU will enter LOCKUP state (it may reset automatically depending on how vendors handle this signal internally).
To mitigate this issue, one can check the `C_DEBUGEN` in `CoreDebug->DHCSR`. If this bit is set, it means a debug session is running, thus `bkpt` instruction can be used safely. Otherwise, skip this instruction. The execution will then [continue until `pm_off()` or `while(1) {}` is called.](https://github.com/RIOT-OS/RIOT/blob/009d76e4fee66bc53c6b97aee02c831f164328d6/core/lib/panic.c#L91) …
=> cpu/cortexm: rework bkpt instruction call on panic

sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/sock.c, sys/net/gnrc/sock/include/gnrc_sock_internal.h, sys/net/gnrc/sock/udp/gnrc_sock_udp.c
When working with go-coap we need to add several work-arounds:
- If the server has multiple IPv6 addresses, it might respond with a different one that the one where it received the request on. We fixed this in our implementations (#19361, #18026) but obviously there is third-party software that does not have such fixes and we need to work with it. So add an option to disable the check.
- go-coap expects to identify block-wise requests by token. This is against the spec, but since block-wise transfers don't work if there is no token, add an option to generate a random, per-transfer token to make the go-coap server happy.
https://github.com/plgd-dev/go-coap/issues/512
=> gnrc, nanocoap: add optional work-arounds for buggy CoAP servers

sys/shell/cmds/vfs.c
Hey 🐡
`snprintf` turned out to be difficult to get right.
Try `make -C tests/sys/vfs_default/ all-asan term` and play with `genfile
=> shell/vfs: Handle print failure in genfile cmd gracefully

cpu/esp_common/lib_printf.c
Hi 🦋
`vsnprintf` is not easy to use. This catches the error return and the truncation.
Not sure if my approach is good as I am lacking context knowledge for that function.
I don't know.
=> cpu/esp: Handle format print errors

cpu/msp430/periph/usci.c
For super low symbol rates the auxiliary clock (ACLK) is used to conserve power. But with only 32,678 Hz clock just prescaling will result in poor bit timing, hence correct modulation control settings to compensate are needed. Since computing this is too expensive, a look-up table (as switch statement) for the four most common symbol rates was used.
The datasheet gave the prescaler values ordered by ascending symbol rate, the switch statement was ordered descending. This changes the order to match the datasheets order and matches the correct prescaler setting to the corresponding symbol rate.
UART on MSP430F2xx is now working for symbol rates of 9600 Bd.
Fixes https://github.com/RIOT-OS/RIOT/issues/20620
=> cpu/msp430/perriph_usci: fix prescaler values for ACLK

core/lib/include/panic.h, core/lib/panic.c
Currently a `core_panic()` will reboot the system with `DEVELHELP=0` and print a crash trace and lock up the system with `DEVELHELP=1`.
There can be situations where this is not what's wanted, e.g. we might want to make a crash that only happens with `DEVELHELP=0` more visible or we want to run with `DEVELHELP=1` and still auto reboot on a crash because we want to debug something unrelated.
So add a config variable to toggle the behavior - the current configuration is kept as the default.
The system should now auto-restart with `DEVELHELP=1` and `CFLAGS += -DCONFIG_CORE_REBOOT_ON_PANIC=1`
=> core/panic: make reboot on panic configurable

doc/doxygen/src/js/riot-doxy.js
In https://github.com/RIOT-OS/RIOT/pull/20511/files a quick fix was added to allow resizing the sidenav. But this broke hiding the sidenav on mobile screen widths. This fixes the issue and also increase the default sidenav width a tad.
Check the generated doc preview also from a mobile device. It should no longer display the sidenav on small form factors (e.g. phones, or browsers resized to a narrow view) but still allow resizing the sidenav with the mouse on larger form factors.
Fixes regression from https://github.com/RIOT-OS/RIOT/pull/20511/files
=> doc/doxygen: fix sidenav handling [backport 2024.04]

makefiles/docker.inc.mk
When `BUILD_IN_DOCKER ?= 1` is set as default in an application Makefile, the build system currently tries to invoke docker recursively from within docker.
This PR adds `BUILD_IN_DOCKER=0` as environment variable to the docker invocation to explicitly disable recursive docker.
Note that this approach still fails if the application Makefile contains an unconditional `BUILD_IN_DOCKER = 1`.
Apply the following patch and run `make -C examples/hello-world all`:
```diff
diff --git a/examples/hello-world/Makefile b/examples/hello-world/Makefile
index 258d8e9baf..a05360cfd5 100644
--- a/examples/hello-world/Makefile
+++ b/examples/hello-world/Makefile
@@ -7,6 +7,8 @@ BOARD ?= native
+BUILD_IN_DOCKER ?= 1
+
```
On `master`, this fails with a recursive invocation of …
=> makefiles/docker: prevent recursive docker invocation

pkg/lwip/Makefile.dep, pkg/lwip/contrib/netdev/lwip_netdev.c, pkg/lwip/include/lwip.h, pkg/lwip/include/lwip/netif/compat.h, pkg/lwip/init_devs/auto_init_kw2xrf.c, pkg/lwip/init_devs/auto_init_mrf24j40.c
This is many providing infrastructure for later use, specifically for making use of the `netdev_driver_t::confirm_send()`. However, as a positive side-effect, this should prevent lost IRQs. (E.g. consider one netdev saturating the message queue. If now a second netdev would
also need its ISR being run, it cannot enqueue its message and the IRQ is lost.)
The expected failure mode is that no network operation is possible when the ISRs are not being run correctly. I ran `make LWIP=1 BOARD=nucleo-f767zi -C examples/gcoap` and could still successfully ping the board.
Contains https://github.com/RIOT-OS/RIOT/pull/18357
=> pkg/lwip: use sys/event for handling ISR and bhp

drivers/include/led.h
Currently `LEDX_ON`, `LEDX_OFF`, etc. are defined in the `board.h` (or `board_common.h` or similar) files. However, various boards could have from 0 to 8 internal LEDs and to write portable code each call of `LEDX_...` should be protected by `#ifdef LEDX_...` . Including `led.h` header file resolve this issue and defines empty `LEDX_...` if LED is not present for given board. However, after including `led.h` there is no possibility to check if given board, really posses particular LED.
This PR adds `LEDX_IS_PRESENT` define for each presented LED at given board.
This code snippet:
```
#if defined LED0_IS_PRESENT
printf("LED0_IS_PRESENT defined.\n");
#endif
#if defined LED1_IS_PRESENT
printf("LED1_IS_PRESENT defined.\n");
#endif
#if defined LED2_IS_PRESENT
printf("LED2_IS_PRESENT …
```
=> drivers/led: add LEDX_IS_PRESENT defines

pkg/wamr/Makefile
Edited wamr Makefile to support THUMB_VFP
Build and test with arduino-nano-33-ble (nrf52840 cpu) for THUMB_VFP mode and built with nrf51dk for THUMB mode.
=> pkg/wamr: Added support for THUMB_VFP in wamr Makefile

cpu/esp32/include/gpio_ll_arch.h, cpu/esp32/periph/gpio_ll.c, cpu/esp32/periph/gpio_ll_irq.c
- `gpio_ll_toggle()` now is race-free
- avoid using a look up table but branch to the two different registers
in the `gpio_ll*()` functions
- in most cases the GPIO port is a compile time constant and the dead branch is eliminated by the optimizer, making this vastly more efficient
- some MCUs do only have a single port, in which case `GPIO_PORT_NUM(port)` is known to return `0` even if `port` is not known, resulting in one of the branch being eliminated as dead branch no matter what
- in case it really is unknown at compile time which port to work on, the branch can still be implemented efficiently by the compiler e.g. using a conditional move; likely more efficient than fetching a value from the look up table.
```
$ cd tests/periph/gpio_ll
$ make BOARD=esp32-mh-et-live-minikit …
```
=> cpu/esp32/gpio_ll: fix & cleanup

examples/gcoap/Makefile
Pass through application configuration environment variables to docker, so that one can use e.g. `make LWIP_IPV4=1 BUILD_IN_DOCKER=1`.
```
make LWIP_IPV4=1 BUILD_IN_DOCKER=1 -C examples/gcoap
```
should now work.
Used to test https://github.com/RIOT-OS/RIOT/pull/18359
=> examples/gcoap: pass through variables to docker

release-notes.txt
Hello there! 🥳 
What are your favourite features, most interesting changes or the worst bug fixes in this release?
Let me know!
=> release-notes.txt: add 2024.04 release notes

makefiles/pseudomodules.inc.mk, sys/Makefile.dep, sys/net/application_layer/gcoap/Makefile.include, sys/net/application_layer/gcoap/forward_proxy.c, sys/net/application_layer/gcoap/forward_proxy_thread.c, sys/net/application_layer/gcoap/include/forward_proxy_internal.h
-  This mainly touches the forward proxy c file, the idea is to have coap-coaps proxy because on some nodes with small MCU flash, we don't want to handle the DTLS stack but also communicate securely with a remote server, therefore coap-coaps proxy would be a huge plus. 
- In order to test the changes,  I have used gcoap_dtls with enabling coap-cops proxy module on the client so it sends coaps requests and on the server I have set the gcoap dtls, enabled the coap-coaps proxy and added the module gcoap-forward-proxy.
I tested on native, so I created two taps: tap0 for the client which sets the remote proxy and tap1: for the proxy server which sets the route to the remote server.
- client: 
```
2024-03-11 12:28:14,334 # main(): This is RIOT! (Version: …
```
=> gcoap:  add coaps forward proxy

cpu/esp_common/Makefile.dep, cpu/native/Makefile.dep, cpu/nrf5x_common/Makefile.dep, cpu/nrf5x_common/radio/nrfmin/Makefile.dep, drivers/kw41zrf/Makefile.dep, examples/benchmark_udp/Makefile, examples/gcoap/Makefile, examples/gcoap_dtls/Makefile, examples/paho-mqtt/Makefile.lwip, examples/telnet_server/Makefile, pkg/lwip/Makefile.dep, pkg/lwip/contrib/netdev/lwip_netdev.c, pkg/lwip/contrib/sys_arch.c, pkg/lwip/include/arch/sys_arch.h, pkg/lwip/include/lwip/netif/compat.h, sys/Makefile.dep, tests/pkg/lwip/Makefile, tests/pkg/lwip_sock_ip/Makefile, tests/pkg/lwip_sock_tcp/Makefile, tests/pkg/lwip_sock_udp/Makefile
This prepares the lwIP adaption layer to work with netdevs that provide `netdev_driver_t::confirm_send()`, allowing to write event based non-blocking netdevs.
This PR does not update any drivers to actually provide `netdev_driver_t::confirm_send()`. 
https://github.com/RIOT-OS/RIOT/pull/18428 ports the STM32 Ethernet driver to the new API, so that this PR can be tested there.
Same as https://github.com/RIOT-OS/RIOT/pull/18139 but for lwIP
depends on and includes:
=> pkg/lwip: make use of confirm send

CODE_OF_CONDUCT.md
The list of communication tools has been outdated. Rather than keeping this list up to date, the list was dropped and the wording changed so that we refer to communication within the community.
Read the CoC and confirm that this:
1. Does not change the meaning of the CoC. Especially: It should still be obvious that it applies to communication via all the channels and tools we use
2. It does no longer contain references to specific channels or tools, so that we can evolve them without having to keep the CoC in sync
None
=> doc/CoC: Remove references to communication tools

boards/waspmote-pro/doc.txt
The board has history of bugs that (such as broken timer configuration) that would directly bite any users, but still have gone unnoticed for significant time periods due to lack of testing. It appears, that none of the core contributors has access to the boards and the number of users is limited.
Check the generated doc
https://github.com/RIOT-OS/RIOT/pull/5301#issuecomment-2092766969
=> boards/waspmote-pro: deprecate board

boards/mulle/Makefile.include, boards/mulle/dist/openocd/mulle-programmer-0.60.cfg, boards/mulle/dist/openocd/mulle-programmer-0.70.cfg, cpu/kinetis/dist/check-fcfield.sh
This does some minor clean up and updates:
- minor fixes to a shell script testing kinetis firmwares prior flashing
- this should now be POSIX shell compliant
- fix and update mulle's OpenOCD config
- previously JTAG was the defaul. The MCU needs special magic to switch into SWD mode, which is not implemented
- set JTAG as transport explicitly to get programming working again
- add a TTY_BOARD_FILTER
`make flash` does now work. Fast verification with CRC fails with:
```
Error: [kx.cpu] not halted (start target algo)
Error: error executing cortex_m crc algorithm
```
But OpenOCD gracefully handles this and falls back to slow verification by reading back what was written.
Sadly, `board_init` runs into a failing assertion when mounting the SPI flash as `/mtd0`. But the way the mulle …
=> boards/mulle: fix flashing

core/thread.c, cpu/cortexm_common/Makefile.features, cpu/cortexm_common/thread_arch.c, cpu/cortexm_common/vectors_cortexm.c, features.yaml, makefiles/features_existing.inc.mk, makefiles/features_modules.inc.mk, makefiles/pseudomodules.inc.mk, tests/cpu/cortexm_stack_limit/Makefile, tests/cpu/cortexm_stack_limit/main.c
ARMv8-M architecture introduces `PSPLIM` and `MSPLIM` as CPU registers to be used alongside with `PSP` and `MSP`.
The idea of these registers is to define the lower limit of a stack. If the stack pointer reaches this limit, a fault is generated before the adjacent memory of the stack can be corrupted.
This module is not enabled by default as it introduces a bit of overhead per context switch (We need to update `PSPLIM` every time we also change PSP).
I didn't add Cortex-M23 here on purpose. It seems to be a little be different because of
```
Devices without ARMv8-M Main Extensions (i.e. Cortex-M23) lack the non-secure
Stack Pointer Limit register hence zero is returned always in non-secure
mode.
```
This PR also introduces a basic test application. I don't know if it's relevant enough to …
=> cpu/cortexm: add stack limit support for Cortex-M33

cpu/msp430/clock.c, cpu/msp430/include/cpu.h, cpu/msp430/include/irq_arch.h, cpu/msp430/include/periph_cpu_common.h, cpu/msp430/periph/timer.c, cpu/msp430/periph/usart.c, cpu/msp430/periph/usci.c, examples/gnrc_lorawan/Makefile.ci, examples/suit_update/Makefile.ci, tests/drivers/atwinc15x0/Makefile.ci, tests/drivers/bme680/Makefile.ci, tests/drivers/nrf24l01p_ng/Makefile.ci, tests/drivers/w5100/Makefile.ci, tests/net/gnrc_ndp/Makefile.ci, tests/net/netstats_neighbor/Makefile.ci, tests/pkg/emlearn/Makefile.ci, tests/pkg/fatfs_vfs/Makefile.ci, tests/pkg/u8g2/Makefile.ci, tests/riotboot_flashwrite/Makefile.ci, tests/sys/bloom_bytes/Makefile.ci, tests/sys/conn_can/Makefile.ci, tests/sys/ps_schedstatistics/Makefile.ci, tests/sys/shell/Makefile.ci, tests/sys/suit_manifest/Makefile.ci, tests/sys/trace/Makefile.ci
This implements power management for the MSP430.
Flash this on any MSP430 board. No regressions should occur, but power consumption should drop. Your mileage may wary, though:
- There will be zero power safe while the CPU is still in use
- There will be more power saving when clock domains can be disabled
I attached a power monitor in-between the USB connection to our [Olimex MSP430Hxxx breakout board](https://github.com/RIOT-OS/RIOT-Open-Hardware/tree/main/olimex-msp430-arduino-uno) and monitored the power consumption in the following scenarios:
1. Nothing connected to the USB (e.g. Noise of the monitor)
2. The breakout board without the header board connected and the USB2UART adapter in use (`/dev/ttyUSB0` open). This is the baseline, as this power is used even without the MCU actually …
=> cpu/msp430: implement power management

sys/net/application_layer/nanocoap/link_format.c, sys/shell/cmds/nanocoap_vfs.c
If the directory entry returned by a CoAP server does not fit into `CONFIG_NANOCOAP_QS_MAX`, we get a call-back for the fragments.
Turns out this was not properly handled. 
I discovered this when running `aiocoap-fileserver` in `/tmp` where some very long directories live:
```
/test.sh
/.X11-unix/
/.font-unix/
/.com.google.Chrome.WsWxkT
/.ICE-unix/
/.XIM-unix/
[1]    52381 segmentation fault (core dumped)
```
```
> ncget coap://[fe80::607f:b1ff:fef7:689c]/
/test.sh
/.X11-unix/
/.font-unix/
/.com.google.Chrome.WsWxkT
/.ICE-unix/
/.XIM-unix/
/systemd-private-880118a9b51a45438f3c22d088d2e118-systemd-resolved.service-Jkz0l9/
/systemd-private-880118a9b51a45438f3c22d088d2e118-polkit.service-pHM9x2/
/snap-private-tmp/
/config-err-ErMZeV
/dock-replace.log …
```
=> nanocoap_link_format: don't drop characters in fragmented entries

cpu/native/backtrace/backtrace.c, cpu/native/include/backtrace.h, tests/cpu/native_backtrace/main.c, tests/cpu/native_backtrace/tests/01-run.py
this improve its print capabilities and test for the backtrace functionality of native 
adding symbol printing and depth information gathering making this a more complete package for using the GNU-libc execinfo.h
run the backtrace test  
~compile it with 'LINKERFLAGS=-no-pie' and it will no longer lie to you how many lines it will print~ #16186 does this
add some or all of of the functions to you own code (just Native) 
```
machine:<RIOT>/tests/cpu/native_backtrace/ > make
<RIOT>/makefiles/arch/native.inc.mk:24: module backtrace is used, do not omit frame pointers
Building application "tests_native_backtrace" for "native" with CPU "native".
"make" -C <RIOT>/boards/common/init
"make" -C <RIOT>/boards/native
"make" -C <RIOT>/boards/native/drivers
"make" -C <RIOT>/core
"make" -C …
```
=> native/backtrace: improve its print capabilitys and test

cpu/samd5x/periph/can.c
this sets the eff-flag and the rtr-flag on received frames as required by the can standard for reliable handling of can id
this also adds a helping assertion to the send 
missing handling of eff /eid / xtd flag was identified by @firas-hamdi in #20640
=> cpu/samd5x/can: fix flag handling on receive

boards/nucleo-f767zi/doc.txt, boards/nucleo-u575zi-q/doc.txt, boards/stm32f469i-disco/doc.txt
This PR fix some minor editorial mistakes:
- nucleo-f767 - add ending bracket in ADCs details,
- nucleo-u575zi-q - fix wrong board name - change nucleo-l552ze-q to u575zi-q,
- stmf469i-disco - change inch sign (`"`) which corrupt bottom of the doc page to (`''`).
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f767zi.html 
xdg-open doc/doxygen/html/group__boards__nucleo-u575zi-q.html 
xdg-open doc/doxygen/html/group__boards__nucleo-stm32f469i-disco.html 
```
None
=> doc/boards: fix minor editorial mistakes

cpu/stm32/Makefile.dep, cpu/stm32/periph/eth.c, cpu/stm32/periph/eth_common.c, sys/net/gnrc/netif/gnrc_netif.c
This updates the STM32 Ethernet driver to the new netdev API that includes `netdev_driver_t::confirm_send()`. It changes the `netdev_driver_t::send()` function to no longer block.
Networking with the STM32 Ethernet peripheral should still work correctly.
Depends on and includes:
=> cpu/stm32/periph/stm32_eth: provide confirm_send

sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c
This bug was spotted by GCC 14.1.0:
In file included from /home/maribu/Repos/software/RIOT/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h:27,
from /home/maribu/Repos/software/RIOT/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.h:33,
from /home/maribu/Repos/software/RIOT/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.h:30,
from /home/maribu/Repos/software/RIOT/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c:28:
In function 'bf_isset',
inlined from '_build_ext_opts' at /home/maribu/Repos/software/RIOT/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c:256:17,
inlined from '_snd_ra' at /home/maribu/Repos/software/RIOT/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c:368:20,
inlined from '_snd_rtr_advs' at …
=> sys/net/grnc: fix NULL ptr dereferencing

examples/psa_crypto/Makefile
`examples/psa_crypto` uses a custom environment variable to specify the presence of a secure element. When building within Docker, this environment variable needs to be explicitly passed down.
`make -C examples/psa_crypto BOARD=nrf52840dk SECURE_ELEMENT=1 BUILD_IN_DOCKER=1` fails on `master` and compiles fine with this fix.
Another instance of #20618. Maybe it's worth checking all the example applications for similar issues.
=> examples/psa_crypto: pass environment variable down to docker

dist/tools/bmp/bmp.py
Either GDB or pygdbmi changed behavior to trim off whitespace following the message, resulting in the `\\n` at the end of the regex no longer matching. This replaces the `\\n` with `\s*` to match both old and new output.
Fixes: https://github.com/RIOT-OS/RIOT/issues/20604
Run `make BOARD=nrf52840dk PROGRAMMER=bmp flash` with a [black magic probe](https://black-magic.org/hardware.html), a cheaper [Jeff Probe](https://flirc.tv/products/flirc-jeffprobe), or an even cheaper ST-Link V2 clone with BMP firmware flashed used as debugger.
In `master` this yields (with recent version of GDB and `pygdbmi` installed):
```
found following Black Magic GDB servers:
[/dev/ttyACM0] Serial: 3D8E4CC3 <- default 
connecting to [/dev/ttyACM0]...
connecting successful.
scanning using SWD...
res = [{'type': …
```
=> dist/tools/bmp: fix target parsing

boards/nucleo-f767zi/include/periph_conf.h, cpu/gd32v/periph/adc.c, cpu/stm32/periph/adc_f1.c, cpu/stm32/periph/adc_f2.c, cpu/stm32/periph/adc_f4_f7.c
This patch allows boards to declare their max ADC clock speed. As an example, the nucleo-f767zi declares it's ADC clock speed to be 36MHz (the max speed of the board's MCU).
The change is minor and fairly safe. I verified that the macro works by declaring it to "foo" in `periph_conf.h` to trigger a compiler error. Beyond that, it is up to board maintainers to use the macro wisely.
This PR is based off #19629 and should be merged after.
=> cpu/{gd32v,stm32}/periph/adc: make ADC clock setable

cpu/nrf5x_common/clock.c
We have been experiencing problems when using `ztimer` on the `feather-nrf52840-sense` boards under certain compiler versions (see https://github.com/inetrg/exercises/pull/5#issuecomment-2012535937 and following) after warm-boot (directly after flashing or after pressing the reset button on the board), while after a cold-boot (un- and re-plugging) the board would behave normally.
I've spent quite some time debugging this issue and finally found the culprit: the `NRF_CLOCK->LFCLKSTAT` is apparently latched for some short time after a softreset (see [this comment](https://devzone.nordicsemi.com/f/nordic-q-a/35792/nrf_clock--lfclkstat-register-contents-are-not-properly-evaluated-after-a-system-reset-if-rtc-compare-event-1-or-2-are-used/138995) by Nordic, sadly it is not reported as an …
=> cpu/nrf5x_common: fix ztimer issue on warm-boot

examples/gcoap/Makefile, examples/gcoap/README.md, examples/gcoap/client.c, examples/gcoap_dtls/Makefile, sys/net/application_layer/gcoap/forward_proxy.c
The gcoap example should better accept an URI as input instead of a host and path.
This avoids some module dependent port selection and prepares the example to deal with different kinds of coap proxies.
The client should be able to specify any scheme independent of modules as dealing with `coaps` or maybe even `http` or `quic` is the job of the proxy.
As described in #20454.
To get the `/.well-known/core` payload from the libcoap server you still nedd to increase  `CONFIG_GCOAP_PDU_BUF_SIZE`.
Client: `examples/gcoap`
```
main(): This is RIOT! (Version: 2024.04-devel-619-g920b4-pr/examples/gcoap_input_URI_and_proxy_fixes)
gcoap example app
> ifconfig
ifconfig
Iface  6  HWaddr: 5E:B0:EA:2B:C8:53 
L2-PDU:1500  MTU:1500  HL:64  Source address length: 6
Link type: …
```
=> examples/gcoap: take full URI as input

cpu/nrf5x_common/clock.c
@BOZHENG001 encountered the issue where all NimBLE-based examples would fail to establish connection while advertising works normally on `feather-nrf52840-sense`, while they work properly on `nrf52840dk`. As suggested by @andrzej-kaczmarek in https://github.com/apache/mynewt-nimble/issues/1777#issuecomment-2109931363, this is an issue with the internal RC low-frequency clock which needs to be calibrated.
While RIOT already tries to do so, it currently ignores the fact that the high-frequency clock needs to be manually started for the calibration to succeed. This is documented for nRF51 [here on page 53](https://docs.nordicsemi.com/bundle/nRF51-Series/resource/nRF51_RM_v3.0.1.pdf) and for nRF52-series for example [here for nRF52832](https://docs.nordicsemi.com/bundle/ps_nrf52832/page/clock. …
=> cpu/nrf5x_common: properly calibrate RC-based low-frequency clock

boards/nucleo-f722ze/doc.txt
This PR adds some improvements to the board documentation page for Nucleo-f722ze:
- addition of MCU table,
- addition of section concerning RIOT shell access (see PR #17453)
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f722ze.html 
```
PR #17453
=> boards/nucleo-f722ze: doc update

sys/include/shell.h, sys/include/vfs.h, sys/include/vfs_util.h, sys/shell/shell.c, sys/vfs/vfs.c, sys/vfs_util/vfs_util.c, tests/sys/shell_scripting/Makefile, tests/sys/shell_scripting/Makefile.ci, tests/sys/shell_scripting/main.c, tests/sys/shell_scripting/tests/01-run.py
This was requested for easier integration testing: It allows to provide a fixed (`native`) binary that is able to execute shell commands provided by a file and terminate when it finished executing the commands (with an error code indicating success).
A simple test application is provided in `tests/sys/shell_scripting`.
=> sys/shell: add support for running a batch of commands from a file

examples/psa_crypto/example_ecdsa_p256.c, sys/include/psa_crypto/psa/crypto_sizes.h, sys/psa_crypto/psa_crypto.c, tests/sys/psa_crypto_ecdsa/example_ecdsa_p256.c, tests/sys/psa_crypto_se_ecdsa/example_ecdsa_p256.c
The `key_bits` that are part of the `psa_key_attributes_t` are restricted to certain values in the PSA specification. An example is [PSA_ECC_FAMILY_SECP_R1](https://arm-software.github.io/psa-api/crypto/1.1/api/keys/types.html#c.PSA_ECC_FAMILY_SECP_R1), which allows for `key_bits = 256`, among others.
However, in https://github.com/RIOT-OS/RIOT/blob/master/examples/psa_crypto/example_ecdsa_p256.c#L91, `key_bits` was set to the size of the exported key, which at least for PSA_ECC_FAMILY_SECP_R1 doesn't match the expected `key_bits` (as it is defined [here](https://arm-software.github.io/psa-api/crypto/1.1/api/keys/management.html#key-formats) to be `1+2*key_bits`).
Fixing this revealed a unnecessary computation of the `curve_bits`, which actually match the `key_bits` according to the …
=> sys/psa_crypto: correct use of (ECDSA) key_bits

sys/include/psa_crypto/psa/crypto_sizes.h, sys/psa_crypto/Kconfig.keys
There were some left-overs from Kconfig dependency modeling (#20438) in the PSA crypto implementation, namely the determination of the maximum key size. This PR removes that and now also unconditionally sets the maximum key size in the C header file.
Look at the changes, CI should do.
Noted thanks to a discussion with @darthdrannel
=> sys/psa_crypto: remove keysize determination from Kconfig files

drivers/aip31068/aip31068.c, drivers/pca9633/pca9633.c, drivers/sdp3x/sdp3x.c
This is already called by `periph_init()`
found in https://github.com/RIOT-OS/RIOT/pull/20668#discussion_r1603247384
=> drivers: don't call i2c_init()

boards/nucleo-l452re/doc.txt, doc/doxygen/src/pinouts/nucleo-l452re.svg
This PR adds missing pinout diagram from board manual mb1136 for nucleo-l452re board.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l452re.html
```
None
=> boards/nucleo-l452re: add pinout to doc page

examples/nanocoap_server/Makefile, examples/nanocoap_server/coap_handler.c, sys/Makefile.dep, sys/include/event/timeout.h, sys/include/net/nanocoap.h, sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/nanocoap.c, sys/net/application_layer/nanocoap/sock.c, sys/net/gnrc/sock/udp/gnrc_sock_udp.c
This adds the capability to `nanocoap_server` to send separate response, that is a delayed response outside the CoAP handler.
The CoAP handler will first send an empty ACK (if the request was conformable), then some other function can send the actual response at a later time, using `nanocoap_sock_send_separate()` with the request context information serialized into `nanocoap_sock_response_ctx_t`.
A `/separate` endpoint was added to `examples/nanocoap_server`:
```
$ aiocoap-client coap://[fe80::748f:e6ff:fed7:426d%tapbr0]/separate
This is a delayed response.
```
```
2024-01-16 19:47:29,617 # main(): This is RIOT! (Version: 2024.01-devel-601-gbd62d-nanocoap_reply_separate)
2024-01-16 19:47:29,618 # RIOT nanocoap example application
2024-01-16 19:47:29,618 # Waiting for address …
```
=> nanocoap_sock: implement separate response

tests/periph/uart/Makefile, tests/periph/uart/main.c
This updates the test app to use the XFA shell interface and ztimer. In addition, a shell command to power off the UART interface is added to e.g. confirm that power consumption indeed goes down.
The test should work as before, except for one shell command to power down the UART being added.
None
=> tests/periph/uart: clean up and add power off cmd

pkg/wamr/Makefile
This PR updates WAMR to its 1.3.3 version referenced by this commit hash : 3f5e2bd23bcb8eb3767c8e17789c6a2e3e912a08.
I'd like some opinions about whether the `PKG_BLEEDING` condition (and variable) should be kept because this variable is not used somewhere else. Also the `main` tag does not exist and anyway tag names are not supported there, only commits hashes are.
Use various boards to see if the example/wamr still work.
I tested it with this example and another homemade one and the behavior was the same as the old version. The tests were made using an arduino nano 33 ble (and sense) and a dwm1001. 
Please note that the text+data values are slightly larger but the bss (ram) new use is not significant from what I saw.
N/A
=> pkg/wamr: updated package to WAMR 1.3.3

boards/arduino-nano-33-ble-sense/Kconfig, boards/arduino-nano-33-ble-sense/Makefile, boards/arduino-nano-33-ble-sense/Makefile.dep, boards/arduino-nano-33-ble-sense/Makefile.features, boards/arduino-nano-33-ble-sense/Makefile.include, boards/arduino-nano-33-ble-sense/board.c, boards/arduino-nano-33-ble-sense/doc.txt, boards/arduino-nano-33-ble-sense/include/board.h, boards/arduino-nano-33-ble-sense/include/gpio_params.h, boards/arduino-nano-33-ble-sense/include/periph_conf.h, boards/arduino-nano-33-ble-sense/reset.c
This PR adds support for arduino-nano-33-ble-sense. Please note that it provides all the configuration to use the internal sensors and actuators but not all of them since they are not currently supported by RIOT (or only the older versions are supported such as LSM6DSXX).
This code is based on the code of the arduino-nano-33-ble as they share the same base (the sense version mostly provides sensors and actuators in addition).
1.  Check the generated doc
2.  Run a few test examples
=> boards/arduino-nano-33-ble-sense: add support for arduino-nano-33-ble-sense

cpu/samd5x/include/candev_samd5x.h, cpu/samd5x/periph/can.c, tests/drivers/candev/main.c
This PR adds the handling of the CAN errors related interrupts.
The CAN errors are coded in this way:
You can generate a CAN error by trying to send a CAN frame from the CAN controller (Board used is same54-xpro) without terminating the bus (i.e not connecting the CANH and CANL pins of the same54-xpro). An ACK error will be generated then and handled.
=> cpu/samd5x: handle CAN errors

cpu/stm32/cpu_common.c, cpu/stm32/include/periph/cpu_common.h
This patch consolidates mutliple conditional compile blocks. This is done to simplify adding new STM32 CPU's and ease maintenance of existing ports. This PR is also part of my on-going effort to port RIOT to the STM32H7 family.
Also, note that this PR makes functions that I re-wrote thread safe. I do not believe that the previous implementation was.
Run the script below:
``` sh
#! /bin/sh -e
#boards=`make info-boards`
boards=""
boards="$boards `ls -1 boards/ | grep stm32`"
boards="$boards `ls -1 boards/ | grep nucleo`"
for board in $boards
do
make -C examples/blinky BOARD=$board
done
```
This is an alternate approach to my first attempt (PR  #20532) at cleaning up this part of the codebase.
=> cpu/stm32: de-duplicate ifdefs

boards/nucleo-f767zi/doc.txt, boards/nucleo-l552ze-q/doc.txt, boards/nucleo-u575zi-q/doc.txt
During review of PR #20671 @dylad spot in document page issue with row name in MCU table - was `I2cs` -> should be `I2Cs` [review](https://github.com/RIOT-OS/RIOT/pull/20671#pullrequestreview-2057095940). 
This PR fix this issue in other nucleo boards - f767, l552 and u575.
Generate doc and read the page.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f767zi.html
xdg-open doc/doxygen/html/group__boards__nucleo-l552ze-q.html
xdg-open doc/doxygen/html/group__boards__nucleo-u575zi-q.html
```
See also #20671
=> boards/nucleo144: fix I2Cs row name in MCU tables

sys/ztimer64/ztimer64.c
After upgrading to Ubuntu 24.04, ztimer64 would fail to build:
```
/home/benpicco/dev/RIOT/sys/ztimer64/ztimer64.c: In function 'ztimer64_clock_print':
/home/benpicco/dev/RIOT/sys/ztimer64/ztimer64.c:306:36: error: expected ')' before 'PRIu64'
306 |         printf("0x%08" PRIxPTR ":%" PRIu64 "\n", (uintptr_t)entry, entry->target);
|               ~                    ^~~~~~~
|                                    )
/home/benpicco/dev/RIOT/sys/ztimer64/ztimer64.c:35:1: note: 'PRIu64' is defined in header '<inttypes.h>'; did you forget to '#include <inttypes.h>'?
34 | #include "debug.h"
+++ |+#include <inttypes.h>
35 | 
/home/benpicco/dev/RIOT/sys/ztimer64/ztimer64.c:306:16: error: format '%x' expects a matching 'unsigned int' argument [-Werror=format=]
306 |         printf("0x%08" PRIxPTR …
```
=> sys/ztimer64: fix build when PRIu64 is not defined

dist/tools/pkg_version_check/README.md, dist/tools/pkg_version_check/version_check.py
This provides a script that will read the Makefile of third party packages in the `pkg/` directory and compare the `PKG_VERSION` hash with the latest upstream release hash or commit hash and check if the package is outdated or not.
The script requires a GitHub API token to run. 
Running the script and inputing a GitHub API token should print out a list of outdated packages.
Fixes #13911
=> pkg: Add script to check third party package version

boards/native/common_features.inc.mk, boards/nucleo-f207zg/Makefile.features, boards/nucleo-f429zi/Makefile.features, boards/nucleo-f439zi/Makefile.features, boards/nucleo-f767zi/Makefile.features, boards/same54-xpro/Makefile.features, boards/stm32f746g-disco/features-shared.mk, features.yaml, makefiles/features_existing.inc.mk
This renames the `ethernet` feature into `netif_ethernet`. The goal is to eventually have a number of `netif_<type>` features that would allow filtering boards by the time of connectivity the have.
The `ethernet` feature has not yet been used, so renaming it should not cause any issue. The CI will test this, though.
None
=> build system: rename ethernet feature into netif_ethernet

examples/nanocoap_server/coap_handler.c, sys/net/application_layer/nanocoap/sock.c
The `nanocoap_sock_request_cb()` function does a synchronous CoAP request.
This PR fixes that further retransmissions are done, even though a matching empty ACK was received.
The behavior is mandatory for CoAP and should also be done when no response callback is set, because the ACK is not the actual response.
Run `examples/nanocoap_server` and `tests/net/nanocoap_cli` and increase the timeout for the `/separate` resource.
Without this fix, the client keeps retransmitting even after the empty ACK.
Test when I set the server separate response delay to 10 seconds.
```
client get fe80::4d3:11ff:fe35:6a43 5683 /well-known/core
client get fe80::4d3:11ff:fe35:6a43 5683 /well-known/core
nanocli: sending msg ID 1, 22 bytes
nanocli: msg send failed: -6
> client get fe80::4d3:11ff:fe35:6a43 5683 …
```
=> nanocoap sock: stop retransmissions after empty ACK

sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/sock.c
Just like `nanocoap_get_blockwise_url_to_buf()`, but with a socket instead of a URL.
=> nanocoap_sock: add nanocoap_get_blockwise_to_buf()

core/lib/assert.c, core/lib/include/assert.h
This PR
- makes the output of `assert()` without `DEBUG_ASSERT_VERBOSE` consistent with the documentation (adding the prefix) and with the output of `assert()` with `DEBUG_ASSERT_VERBOSE` (changing to `=>`).
- provides a documentation cleanup of the `assert`-related functions and macros
Apply the following diff: 
```diff
diff --git a/examples/hello-world/Makefile b/examples/hello-world/Makefile
index 258d8e9baf..17ca69df87 100644
--- a/examples/hello-world/Makefile
+++ b/examples/hello-world/Makefile
@@ -7,6 +7,8 @@ BOARD ?= native
+# CFLAGS += -DDEBUG_ASSERT_VERBOSE
+
diff --git a/examples/hello-world/main.c b/examples/hello-world/main.c
index 213128ac64..e3d79db42d 100644
--- a/examples/hello-world/main.c
+++ b/examples/hello-world/main.c
@@ -21,6 +21,8 @@ …
```
=> core/lib/assert: consistify output and cleanup documentation

drivers/at/at.c, drivers/include/at.h, tests/drivers/at_unit/tests-at.c
Some static functions in the AT driver are meanwhile enough logically self-contained that they make sense to be exposed.
No logic was touched. Nevertheless, tested with `./tests/drivers/at_unit/test_all_configs.sh`.
=> drivers/at: expose some internal API

sys/include/event.h
I added a type cast to the custom_event pointer because event_post only accepts a pointer to the built-in event_t. 
Look at the generated documentation of sys/event.h.
=> sys/event.h: Fixed documentation error by adding a type cast.

sys/include/event.h
C is not a particularly safe language, but let's at least encourage best practices so that the few safety features C have are effectively used.
The example code should compile and not contain casts where not needed.
https://github.com/RIOT-OS/RIOT/pull/20704
=> sys/event: change example in doc to be type safe

boards/nucleo-l496zg/doc.txt, boards/nucleo-l4r5zi/doc.txt, doc/doxygen/src/pinouts/nucleo-l496zg.svg, doc/doxygen/src/pinouts/nucleo-l4r5zi.svg
This PR adds pinout diagrams from MB1312 for RIOT supported boards:
- nucleo-l4r5zi,
- nucleo-l496zg.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l4r5zi.html
xdg-open doc/doxygen/html/group__boards__nucleo-l496zg.html
```
None
=> boards/nucleo-l4r5zi and l496zg: add pinout to documentation page

cpu/saml1x/cpu.c, cpu/saml1x/periph/pm.c
This PR replaces all calls of `foo->bar.bit.xyz = ABCD` to `foo->bar.reg &= ABCD` for all SAML10/SAML11 MCUs
This should not have much impact on the code.
A careful review.
CI should catch most of the failure but feel free to run some tests on hardware.
see #20457
=> cpu/saml1x: avoid the use of bitfield in register calls

cpu/cortexm_common/vectors_cortexm.c
This might give a hint as to which thread caused the corruption.
=> cpu/cortexm_common: print last active thread on stack corruption

dist/tools/tapsetup/tapsetup
`doas` doesn't set `SUDO_USER`, but `DOAS_USER`. This populates `SUDO_USER` with `DOAS_USER` if it is empty, so the script works with both doas and sudo.
`sudo dist/tools/tapsetup/tapsetup` should still work on systems where `sudo` is not the [`doas-sudo-shim`](https://github.com/jirutka/doas-sudo-shim) but in fact the real legacy sudo tool.
None
=> dist/tools/tapsetup: make compatible with doas

cpu/saml21/cpu.c, cpu/saml21/periph/pm.c
This PR replaces all calls of `foo->bar.bit.xyz = ABCD` to `foo->bar.reg &= ABCD` for instance.
This should not have much impact on the code.
This is the first step of a long serie in order to support new Microchip vendor files.
I plan to do the same to all SAM0-based CPU and boards. 
A careful review.
CI should catch most of the failure but feel free to run some tests on hardware.
see #20457
=> cpu/saml21: avoid the use of bitfield in register call

.murdock
The last working `esp32-wroom-32` is not responsive. Let's disable them to un-break nightlies.
=> ci: disable esp32-wroom-32 tests

Makefile.include
place `compile_commands.json` by rule target
`make compile-commands` should result in the current `compile_commands.json` placement:
RIOTBASE if the app if in a subdirectory of that  or APPDIR if not
`make <somewhere>/compile_commands.json` should place it `<somewhere>`
as i often have separate app an riot but they share a common path its usually 
`make ../../compile_commands.json` or something like that 
or 
`<somewhere>$ make -D <whatever to build> ./compile_commands.json`
#19869
=> Makefile.include: place compile_commands.json by rule target

core/include/thread.h, core/thread.c, cpu/esp_common/freertos/task.c, cpu/esp_common/thread_arch.c, cpu/native/Makefile.include, cpu/native/include/native_internal.h, cpu/native/irq_cpu.c, cpu/native/native_cpu.c, cpu/native/startup.c, cpu/native/syscalls.c, examples/rust-gcoap/Cargo.lock, examples/rust-hello-world/Cargo.lock, sys/ps/ps.c, sys/rust_riotmodules_standalone/Cargo.lock, sys/test_utils/print_stack_usage/print_stack_usage.c, tests/rust_minimal/Cargo.lock
This changes a bunch of things that allows building with `BOARD=native` on 32-bit arches with the musl C lib, provided that `libucontext-dev` and `pkg-config` is installed.
Note that installing libucontext makes absolutely zero sense on C libs that do natively provide this deprecated System V API, such as glibc. Hence, it no sane glibc setup is expected to ever have libucontext installed.
```
make BOARD=native -C examples/default
```
On a 32 bit system with musl as C lib and `pkg-config` as well as `libucontext-dev` installed should now succeed. The generated binary on glibc based 32 bit or multiarch systems should not change compared to `master`.
Fixes https://github.com/RIOT-OS/RIOT/issues/18937
=> cpu/native: fix build with musl

cpu/samd21/cpu.c
This PR replaces all calls of `foo->bar.bit.xyz = ABCD` to `foo->bar.reg &= ABCD` for all SAMDxx MCUs
This should not have much impact on the code.
A careful review.
CI should catch most of the failure but feel free to run some tests on hardware.
see #20457
=> cpu/samd21: avoid the use of bitfield

boards/sodaq-sara-sff/board.c, boards/sodaq-sara-sff/include/board.h
This adds a pin definition for SARA_STATUS on the sodaq-sara-sff board.
Testing is only possible with this specific board, of course. Here is a code snippet to see it in operation.
```
printf("SARA_STATUS: %d\n", gpio_read(SARA_STATUS_PIN));
/* switch on the SARA Ublox */
SARA_ENABLE_ON;
SARA_TX_ENABLE_ON;
/* Switch the PWR_ON pin to output */
gpio_init(SARA_R4XX_PWR_ON_PIN, GPIO_OUT);
SARA_R4XX_PWR_ON_OFF;
xtimer_usleep(2000U * US_PER_MS);
SARA_R4XX_PWR_ON_ON;
/* Switch the PWR_ON pin back to input */
gpio_init(SARA_R4XX_PWR_ON_PIN, GPIO_IN);
printf("SARA_STATUS: %d\n", gpio_read(SARA_STATUS_PIN));
```
The output should then be:
```
SARA_STATUS: 0
SARA_STATUS: 1
```
=> boards/sodaq-sara-sff: add status pin for SARA

cpu/esp_common/syscalls.c, pkg/esp32_sdk/patches/0034-components-efuse-fix-incorrect-forward-declaration.patch, pkg/esp32_sdk/patches/0035-components-wpa_supplicant-add-missing-include.patch, pkg/esp32_sdk/patches/0036-components-fix-calls-to-calloc.patch
This fixes a number of issues when compiling with modern versions of GCC and more recent versions of Espressif's newlib fork. There are still issues during initialization with the newer versions of Espressif's newlib fork. Fixing those is left as follow up; this PR should be trivial to review.
I think that this should not change binaries, other than `calloc` called with correct arguments in the SDK.
None
=> cpu/esp*: fix compilation with GCC 14.1.0

sys/include/random.h, sys/random/shaxprng.c, tests/sys/prng_sha1prng/main.c
This PR fixes the SHAxPRNG `random_init_by_array` interface. Parameter `key_length` should contain the number of elements, not the number of bytes.
`make -C tests/sys/prng_sha1prng/ all test`
`make -C tests/sys/prng_sha256prng/ all test`
None
=> sys/random: fix SHAxPRNG init_by_array

Makefile.features, boards/esp32-ethernet-kit-v1_0/Makefile.features, boards/esp32-olimex-evb/Makefile.features, boards/native/common_features.inc.mk, boards/nucleo-f207zg/Makefile.features, boards/nucleo-f429zi/Makefile.features, boards/nucleo-f439zi/Makefile.features, boards/nucleo-f767zi/Makefile.features, boards/same54-xpro/Makefile.features, boards/stm32f746g-disco/features-shared.mk, cpu/esp32/Makefile.dep, dist/tools/buildsystem_sanity_check/check.sh, features.yaml, makefiles/features_existing.inc.mk
- If any `netif_%` (currently only `netif_ethernet`, but more are to come) is provided, the `netif` feature is implicitly provided
- The explicit addition of the `netif` feature from boards that already provide `netif_ethernet` is dropped, consequently
- Boards that previously provided `esp_eth` now instead provide `periph_eth` for consistancy
- Boards that provided `periph_eth` no longer need to provide `netif_ethernet`
- boards that have an external Ethernet MAC (such es `w5100`, `w5500`, `enc28j60`, `encx24j600`, etc.) would still need to provide `netif_ethernet` by hand
- from all other boards, `FEATURES_PROVIDED += netif_ethernet` is dropped, relying on it being added implicitly
This should not change any generated binaries.
Follow up to https://github.com/RIOT-OS/RIOT/issues/20694
=> build system: clean up netif features

cpu/native/startup.c
The first argument to `calloc()` is the number of members, the second the member size. This fixes an instance where the arguments where switched.
Compilation with GCC 14.1 for `native` should work again.
Offending code merged in https://github.com/RIOT-OS/RIOT/pull/18942
=> cpu/native: fix compilation with GCC 14.1

core/thread.c, tests/core/thread_stack_alignment/tests/01-run.py
The end-of stack alignment causes the function to fail measuring the stack size.
A new test was added to verify the stack measurement. 
`ps` also shows the stack usage again
```
2024-06-04 16:56:22,086 # ps
2024-06-04 16:56:22,089 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2024-06-04 16:56:22,091 # 	  - | isr_stack            | -        - |   - |   8192 (   -1) ( 8193) |  0x8085880 |  0x8085880
2024-06-04 16:56:22,093 # 	  1 | idle                 | pending  Q |  15 |   8192 (  436) ( 7756) |  0x8080180 |  0x8081fdc 
2024-06-04 16:56:22,095 # 	  2 | main                 | running  Q |   7 |  12288 ( 2792) ( 9496) |  0x8082180 |  0x8084fdc 
2024-06-04 16:56:22,097 # 	  3 | pktdump              | bl rx    _ |   6 |  12224 (  896) …
```
=> measure_stack_free_internal(): don't try to align end of stack

core/thread.c
The dark magic used used in thread_measure_stack_free() is frowned upon by valgrind. E.g. valgrind may deduce (by monitoring the stack pointer) that a specific value was at some point allocated on the stack, but has gone out of scope. When that value is now read again to estimate stack
usage, it does look a lot like someone passed a pointer to a stack allocated value, and that pointer is referenced after that value has gone out of scope.
This is "fixed" by temporarily disabling valgrind error reporting while iterating over the stack.
With this PR:
```
make BOARD=native64 all-valgrind -C tests/core/thread_basic && valgrind tests/core/thread_basic/bin/native64/tests_thread_basic.elf
[...]
==2283== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
With …
=> core/thread: "fix" valgrind erros in thread_measure_stack_free() 

drivers/ws281x/ws281x_saul.c
This fixes a few nits around the ws281x driver, which impact the Rust tutorial experience (because the Rust wrappers do check more strictly for whether the SAUL API is upheld)
* `$ make -C examples/saul BOARD=feather-nrf52840-sense all flash term`
* patch sys/shell/cmds/saul_reg.c to report dim in line 149, confirm with [saul_reg_write docs](https://doc.riot-os.org/group__sys__saul__reg.html#ga6ca94b517c5c162187b656fcee03ae26) that it needs to return the number of elements written (which the CLI generally ignores, as do many users)
* `> saul write 15 1 0 0`
=> drivers/ws281x: Fix SAUL writes

boards/b-l072z-lrwan1/Makefile.features, boards/b-l072z-lrwan1/include/periph_conf.h
This pull request adds the missing ADC feature for the b-l072z-lrwan1 board.
I took a boards/b-l072z-lrwan1 board and added USEMODULE += periph_adc to the Makefile.
I connected an analog sensor to the A0, A2, and PA5 ports (ADCIN_0, ADCIN_4 and ADCIN_5) and checked if I could read values correctly.
ADCIN_2 and ADCIN_3 are used by ST-Link, but I can still read values from them.
```c
#include <string.h>
#include "periph/adc.h"
#define NUM_LINES 5
int main(void)
{
adc_t lines[NUM_LINES];
int sample;
for (int i = 0; i < NUM_LINES; i++)
lines[i] = ADC_LINE(i);
while (1)
{
for (int i = 0; i < NUM_LINES; i++) {
sample = adc_sample(lines[i], ADC_RES_12BIT);
printf("Sample (%i): %i\n", i, sample);
}
}
return 0;
}
```
Output:
```
2024-06-06 02:02:08,260 # Sample (0): 2374 …
```
=> boards/b-l072z-lrwan1: add missing adc feature

sys/hashes/sha2xx_common.c
This PR changes the SHA2 PAD type to a const type, saving 64 bytes of RAM.
```
cd tests/unittests
make tests-hashes
make term
```
None
=> sys/hashes: change SHA2 PAD type to const

boards/stm32l476g-disco/Makefile.include, boards/stm32l476g-disco/doc.txt, boards/stm32l476g-disco/include/board.h
This PR enables `cpy2remed` programmer for `stm32l476g-disco` board. Moreover, it adds documentation page for this boards.
Go to `blinky` program and flash boards using command:
```
make BOARD=stm32l476g-disco PROGRAMMER=cpy2remed flash
```
```
make doc
xdg-open doc/doxygen/html/group__boards__stm32l476g-disco.html
```
None
=> boards/stm32l476g-disco: enable cpy2remed

sys/include/xtimer.h
This include what you use (IWYU) pragmas so that clang based linters (such as clangd) treat the use of `xtimer_...()` functions as a use of the `xtimer.h` header, even if the implementation of those functions come from a compatibility wrapper.
Open e.g. tests/net/gnrc_sock_ip/main.c in an LSP enabled editor (e.g. (neo)vim + ALE, vs codeium, ...) and a recent enough version of clangd, after you ran `make -C tests/net/gnrc_sock_ip compile-commands`. In master, it will complain that both `<assert.h>` and `"xtimer.h"` are unused includes (even though `xtimer_...()` functions are, in fact, used). In this PR, only the include of `<assert.h>` should be considered unused (which is correct).
None
=> sys/xtimer: add IWYU pragmas

sys/net/application_layer/nanocoap/sock.c
I encountered a situation in `nanocoap_sock_request_cb()` where the message ID did not match and an
`assert(ctx == NULL)` fired.
This introduces the state `STATE_WAIT_RESPONSE` after every (re)transmission.
The function is still hard to read. I added a label at the end to make sure the context is deleted in all cases.
I must have introduced this with #20697
=> nanocoap/sock: fix state handling for mismatching message ID in `nanocoap_sock_request_cb()`

dist/tools/buildsystem_sanity_check/check.sh
The build system sanity check test script currently does not pass shellcheck, preventing PRs improving it from getting merged.
This commit fixes the issues pointed out by shellcheck and should not have any functional changes, except for the github annotation teardown now being reached after the call to `main`.
The test script should work as before.
None
=> dist/tools/buildsystem_sanity_check: make shellcheck happy

dist/tools/buildsystem_sanity_check/check.sh, dist/tools/buildsystem_sanity_check/get_dockerhub_digests.py, makefiles/docker.inc.mk
We had a number of issues being reported that in the end were caused by building with a version of riotbuild incompatible with the source.
This commits adds a check that the used image is in the listed of known to work versions, unless `DOCKER_IMAGE` is not the default. Users overwriting `DOCKER_IMAGE` are expected to know what they are doing.
This also changes behavior in case no docker image is present: It will error and tell the use to use docker pull to get the image (and how to get it). **This is a change in behavior.**
I believe the new behavior of not downloading the image when not present is more consistent. E.g. users are otherwise mislead to the assumption that the image is kept in sync automatically, which never was the case. 
Compile an app with `BUILD_IN_DOCKER=1`. It should …
=> makefiles/docker.inc.mk: Pin riotbuild version with BUILD_IN_DOCKER=1

cpu/nrf5x_common/periph/gpio.c
Removing an extraneous bitwise assignment operation for NRF5X_common gpio.c
I've been running this on my micro-bit v2 with this fix for a couple of days with no ill effects.  However, it is not expected that the changed the behaviour of the code at all.
On my code base, it saves a whole 16 bytes of code :-).
Fixes #20736
=> Remove extraneous bitwise assignment operation on NRF5X_common gpio.c

sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c, sys/net/gnrc/network_layer/ipv6/nib/nib.c, tests/net/gnrc_ipv6_nib/main.c
I still had some fixes for NIB lying around.
I remember they were necessary during my thesis.
The fixes are old and probably would need some confirmation, but I think they are still valid.
I will try to show their necessity by adding something to our tests.
=> nib: some fixes when a router or a prefix is deleted

tests/periph/flashpage/main.c
Given the name of the command `write_raw` in `tests/periph/flashpage`, it should accept raw bytes instead of a string.
This enables more possible test input.
`BOARD=same54-xpro make -C tests/periph/flashpage flash term`
```
2023-12-13 12:52:07,847 # write_raw 0xFE000 11223344556677889
2023-12-13 12:52:07,852 # error: data must have an even length and must be <= 128
write_raw 0xFE000 112233445566778899
2023-12-13 12:52:14,145 # write_raw 0xFE000 112233445566778899
2023-12-13 12:52:14,150 # wrote local data to flash address 0xfe000 of len 9
read 127
2023-12-13 12:52:20,552 # read 127
2023-12-13 12:52:20,556 # Read flash page 127 into local page buffer
2023-12-13 12:52:20,557 # Local page buffer:
2023-12-13 12:52:20,566 # 00000000  11  22  33  44  55  66  77  88  99  FF  FF  FF  FF  FF  FF …
```
=> tests/periph/flashpage: make mtd_raw command write bytes instead of ASCII

README.md
take the introductory sentence from our doc
read
=> /README.md: match doc

.github/workflows/release-test.yml
For some reason, enabling matrix notifications for release test results does not seem to work: Last example is [here](https://github.com/RIOT-OS/RIOT/actions/runs/9425685944/job/25967687520#step:16:3683).
As discussed with @miri64, this removes the matrix notifications until we find a working setup again.
Compare changes to reverted commits (below). Merge and wait for next scheduled release test.
This reverts commit aafb9abb8bc7f332f6b2e8cb7a17771c0cf8c621 and 7e6a46465d63f15eb7ca0d741deecdf98bd6c85e from #20424.
=> release-tests.yaml: remove (always failing) matrix notification

.editorconfig
This adds an [EditorConfig][homepage] file in the root of the repo. Most editors support it [natively][native-support] or via a [plugin][plugin-support].
This is particularly useful for occasional contributors, who with this no longer need to configure the editor to properly show and format source code.
[homepage]: https://editorconfig.org/
[native-support]: https://editorconfig.org/#pre-installed
[plugin-support]: https://editorconfig.org/#download
Open/edit a source file in the PR branch with one of the supported editors. The format should match the coding convention out of the box.
None
=> .editorconfig: add EditorConfig

sys/crypto/modes/ocb.c, tests/sys/crypto/tests-crypto-modes-ocb.c
This PR fixes the Offset_0 calculation in OCB mode. There was a failed attempt to discard the upper two bits of `nonce_padded[15]`. The tests did not catch this because all nonces have zeros in those positions.
Perhaps we should just remove OCB mode, as it has apparently never been used by anyone (including its authors) since it was merged 5 years ago.
`make -C tests/sys/crypto all test`
None
=> sys/crypto: fix OCB mode

tests/drivers/pn532/main.c
`pn532_init()` contains no logic to actually test the proper connection to the device, and the driver test ignores initialization failures and does not show comprehensive errors. This PR changes the test to abort on errors during initialization or fw-version retrieval.
Look through the code changes. This does not impact the test execution in case of no errors.
=> tests/drivers/pn532: fix init error handling and increase verbosity

makefiles/boot/riotboot.mk
When using the auxiliary flash slot, the image slot size shrinks.
This must be known to the firmware image AND the bootloader.
Else slot 1 will not be booted after a SUIT update.
This PR adds the `SLOT_AUX_LEN` variable to the build environment of the bootloader
Without this fix, check the `riotbuild.h` in the `bin` folder of an application with `SLOT_AUX_LEN = 0x10000` and in `bootloaders/riotboot/bin`. You will see that for example `SLOT0_LEN` is different.
=> makefiles: add OPENOCD_DEBUG_ADAPTER and SLOT_AUX_LEN to riotboot build environment

core/include/native_sched.h, cpu/native/include/c11_atomics_compat_cpu.hpp, drivers/at25xxx/at25xxx.c, examples/dtls-wolfssl/Makefile.ci, sys/posix/include/sys/select.h
With this, almost all apps build for `native64` on musl.
I abused the insufficient memory tool using
```
./dist/tools/insufficient_memory/update_insufficient_memory_board.sh --no-docker native64
```
on Alpine. I guess `./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py` would have been the more canonical tool, but the insufficient memory tool has so fancy colors in the output :)
With this, almost all apps build fine.
None
=> tree wide: compilation fixes for `native64` on musl systems

boards/nucleo-l476rg/doc.txt, boards/stm32l476g-disco/doc.txt
During investigation for issue #20748 I found some mistakes in the documentation MCU tables for STM32 L476 MCU.
This PR fixes them.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l476rg.html 
xdg-open doc/doxygen/html/group__boards__stm32l476g-disco.html
```
See also Issue #20748.
=> boards/nucleo-l476rg & stm32l476g-disco: fix MCU table

Makefile.include, pkg/pkg.mk
The cached dir, only build for now, are not created by default so I added a small default target that will create the build dir and the CACHEDIR whenever a make command is called.
Both commands should have the same behavior now. Previously pkg-prepare was not creating `build/CACHEDIR.TAG` and was creating the `build/` directory through `pkg/pkg.mk`.
```bash
make pkg-prepare
```
```bash
make
```
N/A
=> Makefile.include: creation of CACHEDIR.TAG as a dependency of pkg-prepare

drivers/periph_common/init.c
When `WDT_HAS_INIT` is non-zero (which it is for all but two supported CPUs). The watchdog timer was not automatically started on boot when the `periph_wdt_auto_start` module was enabled. This patch fixes this.
I would like to add a test to prevent future breakage, but lack the time and python experience to do so. Perhaps somebody else could contribute this?
I manually tested by hand by inserting an infinite loop in the main thread to starve the watchdog thread. The CPU hangs without this patch and resets with this patch applied.
- non known
=> drivers/periph_wdt: fix auto starting of watchdog timer

boards/nucleo-f103rb/Makefile.features, boards/nucleo-f103rb/doc.txt, boards/nucleo-f103rb/include/periph_conf.h
This adds the ADC configuration and feature for the `nucleo-f103rb` board.
- Run the `tests/periph/adc` application (make sure to set the resolution to 12 bits).
None
=> boards/nucleo-f103rb: add ADC configuration

tests/sys/psa_crypto_ecdsa/Makefile, tests/sys/psa_crypto_ecdsa/Makefile.ci
We tried to specify the stacksize according to the used backend in `tests/sys/psa_crypto_ecdsa` but failed to do so, if the backend is auto-selected.
This PR moves the stacksize determination to after the default-makefile include.
```
make -C tests/sys/psa_crypto_ecdsa BOARD=nrf52840dk flash test
```
Without this patch, the application crashes.
Introduced in #20545
=> tests/sys/psa_crypto_ecdsa: fix stacksize determination

tests/sys/progress_bar/tests/01-run.py
`tests/sys/progress_bar` is apparently flaky on `samr21-xpro` and lets our nightlies fail :(
this PR adds a printout that may help debug the problem by seeing whether it always fails at the same progress value
Wait for the next couple of nightlies
See https://ci.riot-os.org/details/762147886d354ad5ad6308e93898d046/tests for a failed and https://ci.riot-os.org/details/fa7f9c6149fc4e5ba9e3db1627e611a3/tests/tests:sys:progress_bar for the last successful run.
=> test/sys/progress_bar: temporary printout to debug flaky test

cpu/sam0_common/include/periph_cpu_common.h, cpu/sam0_common/periph/adc.c, cpu/sam0_common/periph/dac.c, cpu/sam0_common/periph/dma.c, cpu/sam0_common/periph/eth.c, cpu/sam0_common/periph/flashpage.c, cpu/sam0_common/periph/gpio.c, cpu/sam0_common/periph/gpio_ll.c, cpu/sam0_common/periph/gpio_ll_irq.c, cpu/sam0_common/periph/hwrng.c, cpu/sam0_common/periph/i2c.c, cpu/sam0_common/periph/pwm.c, cpu/sam0_common/periph/rtc_rtt.c, cpu/sam0_common/periph/spi.c, cpu/sam0_common/periph/timer.c, cpu/sam0_common/periph/uart.c, cpu/sam0_common/periph/usbdev.c, cpu/sam0_common/periph/wdt.c, cpu/sam0_common/sam0_sdhc/sdhc.c
This PR removes all bitfields usage from `cpu/sam0_common/` folder.
I decided to go with a commit per file to allow an easy revert in case something got terribly wrong. Nevertheless, CI should catch most of the issues early. However, I might get sleepy here and there so please, take a careful eyes at this.
/!\ **Breakages are highly probable here** /!\
Triple careful review and CI should save us hopefully.
#20457
=> cpu/sam0_common: avoid bitfield usage

boards/stm32l0538-disco/Makefile.include, boards/stm32l0538-disco/doc.txt
This PR enables `cpy2remed` programmer for `stm32l0538-disco` board. Moreover, it update documentation page for this boards, concerning flashing using added programmer.
Go to `blinky` program and flash boards using command:
```
make BOARD=stm32l0538-disco PROGRAMMER=cpy2remed flash
```
```
make doc
xdg-open doc/doxygen/html/group__boards__stm32l0538-disco.html
```
None
=> boards/stm32l0538-disco: enable cpy2remed

cpu/samd5x/cpu.c, cpu/samd5x/periph/can.c, cpu/samd5x/periph/pm.c
This PR replaces all calls of `foo->bar.bit.xyz = ABCD` to `foo->bar.reg &= ABCD` for all SAMD5x MCUs
This should not have much impact on the code but it would be good to test the CAN driver implementation as I might have break something.
A careful review especially on the CAN driver is needed?
CI should catch most of the failure but feel free to run some tests on hardware.
see #20457
=> cpu/samd5x: avoid the use of bitfields

tests/sys/progress_bar/tests/01-run.py
Remove the temporary printout for debugging purposes after the test has been fixed.
Compare with the PRs that introduces the debug print, merge and wait for green nightly.
Initially introduced in #20763 and bugfix merged with #20764. See successful nightly here: https://ci.riot-os.org/details/4d090795a6a648419641ba286ad8f5a8/tests/tests:sys:progress_bar
=> tests/sys/progress_bar: remove debug print

boards/stm32l0538-disco/doc.txt
This PR adds MCU table to `stm32l0538-disco` board documentation page.
```
make doc
xdg-open doc/doxygen/html/group__boards__stm32l0538-disco.html 
```
None
=> boards/stm32l0538-disco: doc improvements

sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c, sys/net/gnrc/network_layer/ipv6/nib/nib_pl.c
Avoid overflows when subtracting current time from point in time that is assumed to be in the future, which however sometimes is not the case. For the changed lines of this PR, such an overflow has been encountered. There may still be more cases.
Have a 6LN in a state where it has a deprecated prefix (i.e. preferred lifetime = 0) in its prefix list.
- Observe "nib prefix" printing an overflown value for the preferred lifetime, when it should print 0.
- If the 6LN is a 6LR or 6LBR, it sends a Router Advertisement with a Prefix Information Option with an overflown value for the preferred lifetime, when it should be 0.
=> gnrc/ipv6: Check for overflow

cpu/stm32/periph/adc_l4.c
This PR fixes ADC initialization for `nucleo-l4xxx` boards (more details in issue #20748).
I tested this PR using `nucleo-l476rg`, `nucleo-l496zg` and `nucleo-l4r5zi`.
Flash mentioned boards (or maybe other from L4xxx family) using `tests/periph/adc` and observe console.
With this PR you should see new measurements each 100 ms:
```
main(): This is RIOT! (Version: 2021.07-devel-10832-g0ebb6-nucleo-l4xxx-fix-ADC)
RIOT ADC peripheral driver test
This test will sample all available ADC lines once every 100ms with
a 10-bit resolution and print the sampled results to STDIO
Successfully initialized ADC_LINE(0)
Successfully initialized ADC_LINE(1)
Successfully initialized ADC_LINE(2)
Successfully initialized ADC_LINE(3)
Successfully initialized ADC_LINE(4)
Successfully initialized ADC_LINE(5) …
```
=> cpu/stm32-L4: fix ADC initialization

examples/gcoap/client.c, sys/include/net/gcoap.h, sys/include/net/gcoap/forward_proxy.h, sys/include/net/nanocoap.h, sys/net/application_layer/cord/ep/cord_ep.c, sys/net/application_layer/cord/epsim/cord_epsim.c, sys/net/application_layer/cord/lc/cord_lc.c, sys/net/application_layer/gcoap/dns.c, sys/net/application_layer/gcoap/forward_proxy.c, sys/net/application_layer/gcoap/gcoap.c, sys/net/application_layer/gcoap/include/forward_proxy_internal.h, sys/net/application_layer/nanocoap/nanocoap.c
The gcoap forward proxy must respond to the client from the same address and port where it has received the request.
The address towards the server can be different.
For that the usual information in `sock_udp_aux_tx_t` are propated to where they are needed in `gcoap_req_send()` and `_handle_req()` in `gcoap.c`
Another fix is included by setting the correct payload size in the forwarded PDU right after it is copied.
Use this branch to run a client and proxy with `examples/gcoap`
`./dist/tools/tapsetup`
Client:
`CFLAGS+=-DCONFIG_GCOAP_PDU_BUF_SIZE=512 make flash term`
Proxy:
Add another link local address **only** to the proxy by adding the following to `examples/gcoap/Makefile`:
```diff
+# Uncomment the following 2 lines to specify static link lokal IPv6 address
+# this might be useful …
```
=> gcoap: propagate local tx aux to gcoap_req_send() and in _handler_req()

boards/nucleo-l452re/Makefile.features, boards/nucleo-l452re/include/periph_conf.h
This PR adds to the Nucleo-l452re ADC configuration.
Solution was successfully tested by @crasbe - more details [PR #20756](https://github.com/RIOT-OS/RIOT/pull/20756#issuecomment-2205897390). 
PR #20756
=> boards/nucleo-l452re: add ADC

makefiles/tools/jlink.inc.mk
Most details of this PR are detailed in #20775. tl;dr: In the `makefiles/tools/jlink.inc.mk` file, a `%` wildcard is used for the flash targets that includes all variants of `flash...` but not `flash` itself. Therefore important environment variables are not exported as they should be and others  like `JLINK_PRE_FLASH` and `JLINK_POST_FLASH` do not work.
Additionally, the `JLINK` and `JLINK_POST_FLASH` variables were not exported at all. The former did not have an effect because the `JLINK` variable has a backup in `dist/tools/jlink/jlink.sh`. However it _is_ defined in multiple places, for example in `boards/common/nrf52/Makefile.include`, so it would be good to actually use the defined value and not the fallback value.
The latter is not currently used by any boards, so it did not have …
=> makesfiles/jlink: fix exports for flashing

dist/tools/dhcpv6-pd_ia/kea.py
Adjust prefix delegation config for Kea 2.6.0
https://github.com/isc-projects/kea/blob/master/ChangeLog:
```
Kea 2.6.0 (stable) released on May 29, 2024
[...]
2232.	[func]*		fdupont
Auto-generated subnet identifiers are no longer supported.
Configurations that contain subnets without explicit subnet
identifiers (i.e. without an "id" entry) will now be rejected.
(Gitlab #2961)
```
(for reproducability: `sudo killall kea-dhcp6`)
`cd examples/gnrc_border_router/`
`sudo PREFIX_CONF=dhcpv6 IPV6_PREFIX=2001:db8::/64 make all term`
While the application is running, observe that no kea actually runs: `ps -aux | grep kea`
Kea throws an error that the "id" entry is missing and exits. The error is however silenced by the python script.
Having no DHCP server, the `gnrc_border_router` (6LBR) …
=> tools/dhcpv6-pd_ia: fix: Add explicit subnet id

pkg/cryptoauthlib/include/atecc608a_config.h, sys/shell/cmds/cryptoauthlib.c
The cryptoauthlib shell command was broken due to API changes.
I updated the calls.
Additionally I made the output a bit prettier.
It is also possible to select a specific device, in case there's more than one.
Update 2024-05-17:
Now also compatible with ATECC608A config zone.
Connect an ATECC508 (or 608), and run an application with the shell and the cryptoauthlib package. 
The output should look like this (values differ depending on configuration, of course):
```
2024-05-16 08:54:07,871 # atca
2024-05-16 08:54:07,886 # * set_dev <number> - set and initialize an atca device (defaults to index 0)
2024-05-16 08:54:07,891 # * read - read Microchip CryptoAuth device's config zone
2024-05-16 08:54:07,896 # * read_bin - read config zone and print binary data
2024-05-16 08:54:07,904 # * lock_c …
```
=> sys/shell: Update cryptoauthlib shell commands

dist/tools/pyterm/pyterm, makefiles/tools/serial.inc.mk
`pyterm` loggs all terminal output but the feature is very under-utilized.
Especially when multiple terminals are opened, this is very unreliable as all output goes to the default log file, so it is rather random which output gets logged.
Instead, create a session name based on the current time, the application and the board.
This helps recovering output later on.
Run `make term` as usual, but now you will find multiple log files in `~/.pyterm`:
```
/home/benpicco/.pyterm/T430s:
2023-11-29_20.13.51-gnrc_networking-same54-xpro.log
2023-11-29_20.17.53-hello-world-saml21-xpro.log
````
=> makefiles/tools/serial.inc.mk: make use of pyterm session names

examples/rust-gcoap/Cargo.lock, examples/rust-hello-world/Cargo.lock, sys/rust_riotmodules_standalone/Cargo.lock, tests/rust_minimal/Cargo.lock
Changes generated with `find -name Cargo.toml -exec cargo update --manifest-path "{}" --package riot-wrappers --package riot-sys ";"` on RIOT master
both `rust-riot-sys` and `rust-riot-wrappers` only bumped the version number with no functional changes
CI should suffice.
=> rust: bump rust-riot-{sys,wrappers} version

dist/tools/cosy/patches/0003-take-BUILD_DIR-environment-variable-into-account.patch
Symbols coming from packages are not properly recognized as soon as the `BUILD_DIR` environment variable is used. This PR changes that.
Configure `BUILD_DIR` as per [the documentation](https://doc.riot-os.org/advanced-build-system-tricks.html#out-of-tree-cache-dir).
Start cosy on any app that uses a third-party package, e.g., `dtls-echo`:
```
make -C examples/dtls-echo cosy
```
On master, this shows
> Warning: 893 symbols could not be matched to a path
With this PR, it reduces to
> Warning: 527 symbols could not be matched to a path
and the `tinydtls` symbols are correctly matched.
=> dist/tools/cosy: take BUILD_DIR into account

core/lib/panic.c, cpu/cortexm_common/panic.c
The LOG_ functions can be overwritten to log e.g. to network or file system.
Calling them in the panic handler will just lead to another panic, obfuscating the original source of the panic.
=> core/panic: don't use LOG_ functions in panic handler

pkg/wamr/Makefile
A while ago I added the glue in WAMR to make RIOT works with its most recent version. Since the code is now implemented in the latest release I thought it could be good to update the version RIOT was using. I tested the example and had no particular problem on a DWM1001. 
From what I saw the wamr package is for now only used in the example so that should not cause any extra problem. Feel free to test the example on any other board but be aware that if you are using your own program it may have been broken because of the slight API changes that occurred in wamr between v1.3.3 and v2.1.1 (calling a wasm function does not require the signature anymore if you are not using the iwasm API).
The only thing that was edited is the pkg/wamr/Makefile with the commit hash.
Ref : …
=> pkg/wamr : updated wamr version to v2.1.1

boards/stm32l476g-disco/Makefile.features, boards/stm32l476g-disco/include/periph_conf.h, cpu/stm32/include/periph/l4/periph_cpu.h
This PR adds to the stm32l476g-disco ADC support.
Flash the board using `tests/periph_adc` program. Check if measured values changes when A0-A4 pins are
None
=> boards/stm32l476g-disco: add ADC support

examples/leds_shell/Makefile
In current version of the `leds_shell` when user uses `gpio set` or `gpio clear` command in the `native` program ends with **_segmentation fault_** error. This PR solves this problem by adding `periph_gpio_mock` module. Now, when user in `native` uses these commands program works without crach - of course as this is mockup - nothing really happens. I tested this PR in few real boards and everything works fine.
Output from `examples/leds_shell` for `native` without this PR:
```
main(): This is RIOT! (Version: 2021.07-devel-10924-g4612c)
This board has 2 LEDs
> gpio set 0 0
gpio set 0 0
Set HIGH to PORT 0, PIN 0
Segmentation fault
```
and with this PR:
```
main(): This is RIOT! (Version: 2021.07-devel-10924-g4612c-examples-leds_shell-fix-segfault)
This board has 2 LEDs
> gpio set 0 0
gpio …
```
=> examples/leds_shell: use periph_gpio_mock on native

sys/net/gnrc/network_layer/ipv6/nib/nib.c, tests/net/gnrc_ipv6_nib/main.c
In GNRC's architecture, lifetimes are associated with prefixes (and not to any addresses themselves). The prefixes from a PIO are stored in the prefix list. Even if a prefix is not on-link, it needs to be stored in the prefix list if the A flag (SLAAC) is set, so that auto configured addresses in the prefix have their lifetimes managed. Otherwise these addresses would remain configured possibly longer than what the prefix lifetimes were set for.
This PR stores the prefix in the prefix list as soon as / whenever the A flag is set. The test is modified accordingly.
Background: Generally, by RFC definition (https://datatracker.ietf.org/doc/html/rfc4861#section-5.1) the prefix list only contains on-link prefixes, but in GNRC, this is determined for a prefix list entry by the `_PFX_ON_LINK` …
=> gnrc/ipv6: Store all SLAAC prefixes

sys/include/net/gcoap.h
The guards were wrong, leading to compilation issues with the modules enabled.
=> net/gcoap: fix guards around defines

release-notes.txt
Dear RIOTers!
The next release is getting closer with having [almost all release tests passed](https://github.com/RIOT-OS/Release-Specs/issues/311). :tada: 
The release notes are automatically created by the `riot-release-manager` tool and still lack the selected highlights and a release name. If you have suggestions for either, please post them below!
=> release-notes.txt: add 2024.07 release notes

sys/net/application_layer/dhcpv6/client.c
Hello 🐌
This enhances the handling of the option parsing.
CI should be enough + a good review. Maybe @miri64?
=> net/dhcpv6: Improve option handling in dhcpv6 advertise

boards/weact-g030f6/Makefile.include
Running
USEMODULE=stdio_rtt make BOARD=weact-g030f6 -C ... flash term
failed due the programmer not being specified by the time the serial is configured:
makefiles/tools/serial.inc.mk:44: "Warning: No RIOT_TERMINAL set,
but using stdio_rtt: The default terminal is likely not to work."
This reorders the setup of the board to first configure the programmer and then the serial, so that using stdio_rtt now works out of the box.
USEMODULE=stdio_rtt make BOARD=weact-g030f6 -C examples/default flash term
should now work
None
=> boards/weact-g030f6: fix use with stdio_rtt

boards/nucleo-l053r8/doc.txt
This PR adds MCU table to the `nucleo-l053r8` board doc page.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l053r8.html 
```
None
=> boards/nucleo-l053r8: MCU table addition to doc page

boards/stm32l476g-disco/Makefile.features, boards/stm32l476g-disco/include/periph_conf.h
This PR adds PWM configuration for `stm32l476g-disco`.
Flash the board using `tests/periph/pwm` program. Check if you could, for example, change LED
intensity using PWM.
None
=> boards/stm32l476g-disco: add PWM support

cpu/stm32/Makefile.features, cpu/stm32/include/gpio_ll_arch.h, cpu/stm32/include/periph/cpu_gpio_ll.h, cpu/stm32/periph/gpio_ll.c, drivers/include/periph/gpio_ll.h, features.yaml, tests/periph/gpio_ll/main.c
This changes the API of the `periph_gpio_ll_switch_dir` feature, so that `gpio_ll_switch_dir_output()` and `gpio_ll_switch_dir_input()` no longer directly take a bitmask indicating with GPIO pins to switch, but the output of `gpio_ll_prepare_switch_dir()` that takes this bitmask.
The reason for this change is that on STM32 (except for F1) the GPIO periphal has no direction register (with one bit per pin), but a mode register (with two bits per pin). This required some non-trivial bit operation to prepare the bitmask to write to the mode register from the bitmask specifying the pins to change. Splitting out the preparation allows to cache the result and switch directions fast anyway.
An implementation for STM32F1 is not provided yet.
A default implementation for …
=> cpu/stm32: implement `periph_gpio_ll_switch_dir`

cpu/riscv_common/irq_arch.c
The read_csr macro [returns the CSR value as a `unsigned long`](https://github.com/RIOT-OS/RIOT/blob/2024.07/cpu/riscv_common/include/vendor/riscv_csr.h#L195). However, the format specifier presently treats it as a `uint32_t`. This causes a `-Wformat` compilation error to be emitted by Clang 18:
cpu/riscv_common/irq_arch.c:149:49: error: format specifies type 'unsigned int'
but the argument has type 'unsigned long' [-Werror,-Wformat]
149 |             printf("  mepc:   0x%" PRIx32 "\n", read_csr(mepc));
```
$ make TOOLCHAIN=llvm BOARD=hifive1 -C examples/hello-world/
```
None.
=> riscv_common: Use unsiged long format specifier for printing CSR values

boards/nucleo-f439zi/Makefile.features, boards/nucleo-f439zi/include/periph_conf.h, cpu/stm32/include/periph/f4/periph_cpu.h
This PR adds to the nucleo-f439zi ADC support.
Flash the board using `tests/periph/adc` program. Check if measured values changes when A0-A5 pins are
connected to the 3,3V, GND or to the potentiometer.
None
=> boards/nucleo-f439zi: add ADC support

cpu/native/Makefile.include
This (hopefully) fixes https://github.com/RIOT-OS/RIOT/pull/20009#issuecomment-2294803168
E.g. `make BOARD=native64 -C tests/periph/timer` should now work on Debian 11.
https://github.com/RIOT-OS/RIOT/pull/20009#issuecomment-2294803168
=> cpu/native/periph_timer: add missing -lrt to linker flags

cpu/native/Makefile.include
This (hopefully) fixes https://github.com/RIOT-OS/RIOT/pull/20009#issuecomment-2294803168
E.g. `make BOARD=native64 -C tests/periph/timer` should now work on Debian 11.
https://github.com/RIOT-OS/RIOT/pull/20009#issuecomment-2294803168
=> cpu/native/periph_timer: add missing -lrt to linker flags [backport 2024.07]

cpu/native/periph/timer.c
Adds two lines of documentation so point towards -lrt to solve linker issues with timer_create(2)/timer_settime(2) are missing.
cd examples/gcoap-rust && make BOARD=native all
close #20815
=> doc: note that timer_settime() comes from librt on some systems

examples/rust-gcoap/Cargo.lock
This updates the use of two deprecated items to the latest idioms in riot-wrappers 0.8.
Green CI should suffice.
This unblocks testing of https://github.com/RIOT-OS/rust-riot-wrappers/pull/90: riot-wrappers 0.9 is developed and tested as 0.8.999, because its claim is that if all deprecation warnings of latest 0.8 are resolved, and you don't do something weird[^1], all can still run.
[^1]: Such as assigning the error from a known can-not-err result to a `!` type rather than to `Infallible` – that is a breaking API change, but practical breakage is not expected, and at worst fixed by implementing some conversion to do the same when going from `!` as for `Infallible`.
=> examples/rust: Update CoAP example modules

drivers/include/sx127x.h
Browsing through the RIOT documentation, I've noticed a link on the [Semtech SX1272 and SX1276 radios driver](https://doc.riot-os.org/group__drivers__sx127x.html) whose formatting is a bit broken:
This simple PR fixes the problem by slightly rearranging the documentation.
1. Run `make doc`.
2. Open the file `doc/doxygen/html/group__drivers__sx127x.html` with a web browser.
The link should now look like this:
–
=> drivers/sx127x: fix link formatting in documentation

boards/nucleo-g070rb/doc.txt
PR adds MCU table to the `nucleo-g070rb` board doc page.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-g070rb.html 
```
None
=> boards/nucleo-g070rb: add MCU table to doc page

boards/nucleo-g071rb/doc.txt
PR adds MCU table to the `nucleo-g071rb` board doc page.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-g071rb.html 
```
None
=> boards/nucleo-g071rb: add MCU table to doc page

makefiles/cargo-settings.inc.mk, makefiles/cargo-targets.inc.mk, makefiles/info.inc.mk
Users who want to do more than just use cargo to build their RIOT application (say, run the linter `cargo check` with the right settings, run `cargo fix`, the advanced linter `clippy`, or build documentation) previously had to extract the relevant environment variables and command line extras from `make info-rust`.
In particular, that was hard to integrate in CI – for example, to run the linter in strict mode on your application.
The newly introduced `make cargo-command CARGO_COMMAND="cargo clippy"` family (where the content for CARGO_COMMAND is run with all the right setup) closes this gap.
* CI still passes
* `make -C examples/rust-gcoap cargo-command CARGO_COMMAND="cargo check --release"` may show warnings, but completes successfully.
This may also contribute to …
=> Rust: Add `make cargo-command` and refactoring around it

drivers/lsm303agr/Cargo.toml, examples/rust-gcoap/Cargo.lock, examples/rust-gcoap/Cargo.toml, examples/rust-gcoap/Makefile.ci, examples/rust-gcoap/src/lib.rs, examples/rust-hello-world/Cargo.lock, examples/rust-hello-world/Cargo.toml, sys/rust_riotmodules_standalone/Cargo.lock, sys/rust_riotmodules_standalone/Cargo.toml, sys/shell/democommands/Cargo.toml, tests/rust_minimal/Cargo.lock, tests/rust_minimal/Cargo.toml
This updates riot-wrappers from the 0.8 series to 0.9. The [change log](https://github.com/RIOT-OS/rust-riot-wrappers/blob/main/NEWS.md) lists what happened: Most are changes that were in the pipeline for quite some time and waited for a critical mass to do a breaking change. Being breaking, this also required changes both to the provided examples and to the example modules that are referenced -- this update rolls them all into one PR.
Automated tests should suffice. Run `make -C examples/rust-gcoap` for good measure.
Some related PRs are listed at https://github.com/RIOT-OS/rust-riot-wrappers/issues?q=label%3Await-for-breaking-0.9; the big 0.9 transition is also described in https://github.com/RIOT-OS/rust-riot-wrappers/pull/109
=> Rust: Update to riot-wrappers 0.9

boards/ek-lm4f120xl/include/board.h, examples/rust-gcoap/Makefile, examples/rust-hello-world/Makefile, tests/rust_libs/Makefile, tests/rust_minimal/Makefile
boards/ek-lm4f120x: Change internal LED macro for C2Rust compatibility
C preprocessor defines in non-function form are assumed by C2Rust to be
constant if they are an expression and not a statement; the LED_PORT was
the only place in the code where that was wrong, and led to compiler
errors due to the value not being constant.
Altering the internal macro to use function form sidesteps that issue.
The generally preferred alternative of using a `const` is unavailable in
this case because the dereferencing operator is already part of the
vendor header file cpu/stellaris_common/include/vendor/cortex-m4-def.h.
The changed macro is documented as required by doccheck. The doccheck
rule that grandfathered in the LED_PORT macro as allowed undocumented is
not removed because it is also used in …
=> boards/ek-lm4f120x: Change internal LED macro for C2Rust compatibility

boards/common/particle-mesh/include/board.h, drivers/periph_common/init_leds.c
On the particle-xenon and similar boards, once SAUL is active, LED[012]_ON will not do anything, even though LED[012]_IS_PROVIDED is set. This may not surprise users of LEDn_ON (because it's the established behavior of those to no-op), but when explicitly inspecting LEDn_IS_PROVIDED (like Rust users [<del>will</del> do](https://github.com/RIOT-OS/rust-riot-wrappers/pull/113)), this behavior is confusing.
The cause of this is that SAUL's use of the LED pins is through PWM, and (at least on that family) that completely overrides GPIO input.
The change is two-fold:
* On the particle-mesh family, the condition for when something else grabs the LED pins is written out as `!(IS_ACTIVE(SAUL_AUTO_INIT) && IS_ACTIVE(SAUL_PWM))`. If that is the case, LED0_ON is not defined, and consequently, led.h …
=> drivers/led: Allow LEDn_ON to be disabled by other modules

sys/include/net/gnrc/ipv6.h, sys/net/gnrc/network_layer/ipv6/nib/nib.c
UPDATED ON: 2024-08-14, 2024-08-15
Setting static link local addresses is supported in nib.c.
This contribution adds options for applying static link local addresses only on specific interfaces.
Setting the static  link local address can be selected by either netdev driver type or by interface number.
Compile `examples/gnrc_networking` for board `native`, uncommenting the Makefile lines
```Makefile
IPV6_STATIC_LLADDR ?= '"fe80::cafe:cafe:cafe:1"'
CFLAGS += -DCONFIG_GNRC_IPV6_STATIC_LLADDR=$(IPV6_STATIC_LLADDR)
```
A static link local address will show up in `ifconfig`:
```text
Iface  6  HWaddr: 56:CB:2C:67:4D:F3
...
inet6 addr: fe80::cafe:cafe:cafe:7  scope: link  VAL
...
```
You can now play with the include options. Either
```Makefile
CFLAGS += …
```
=> nib.c: add interface selection rules for static link local address assignment

examples/cord_lc/Makefile.ci, examples/gcoap/Makefile, examples/gcoap/Makefile.ci, examples/gcoap/client.c, examples/gcoap/server.c, sys/include/net/gcoap.h, sys/include/net/nanocoap.h, sys/net/application_layer/gcoap/gcoap.c, sys/net/application_layer/nanocoap/nanocoap.c
When a CONfirmable CoAP request with an Observe option is sent, the sending client has to store the CoAP token to match multiple responses from the server sending Observe notifications.
The `gcoap` memo is not cleared when the 2.xx response for the client registration contains an Observe option.
https://github.com/RIOT-OS/RIOT/blob/3f41494e59dc915fe17f67ba3b40d0827b9b3a36/sys/net/application_layer/gcoap/gcoap.c#L521-L531
For a confirmable request with a token length >0, the problem happens right before, where the resend buffer is released by actually overwriting the first byte of the request header in `pdu_buf` with 0. The first byte contains the token length which is required to match in:
https://github.com/RIOT-OS/RIOT/blob/3f41494e59dc915fe17f67ba3b40d0827b9b3a36/sys/net/application_lay …
=> sys/net/application_layer/gcoap: fix Observe notifications correlation

sys/net/application_layer/gcoap/gcoap.c
Naming the `gcoap` thread `gcoap` makes it easier to tell where the thread comes from.
```
2024-08-26 15:43:52,704 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2024-08-26 15:43:52,705 # 	  - | isr_stack            | -        - |   - |   8192 (   -1) ( 8193) |  0x8081ee0 |  0x8081ee0
2024-08-26 15:43:52,706 # 	  1 | idle                 | pending  Q |  15 |   8192 (  436) ( 7756) |  0x807c7e0 |  0x807e63c 
2024-08-26 15:43:52,708 # 	  2 | main                 | running  Q |   7 |  12288 ( 2792) ( 9496) |  0x807e7e0 |  0x808163c 
2024-08-26 15:43:52,709 # 	  3 | ipv6                 | bl rx    _ |   4 |   8128 ( 1864) ( 6264) |  0x8086640 |  0x808845c 
2024-08-26 15:43:52,710 # 	  4 | udp                  | bl rx    _ |   5 |   4032 ( …
```
=> gcoap: the name of the gcoap thread should be gcoap

doc/doxygen/src/using-rust.md
This is a simple doc update to point users in the right direction when they see something like:
```
-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
-- Configuring incomplete, errors occurred!
--- stderr
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
CMake Error at /usr/lib/llvm-14/lib/cmake/clang/ClangTargets.cmake:756 (message):
The imported target "clangBasic" references the file
"/usr/lib/llvm-14/lib/libclangBasic.a"
but this file does …
```
=> doc: Point out common problem installing c2rust

cpu/sam0_common/periph/rtc_rtt.c
This PR fixes the issue with rtt reset after a node hibernation
You may notice an issue when using the **rtt_rtc** module in any RIOT OS example. Specifically, if you use the rtc_gettime() function to get the current time, then set an alarm, put the node into hibernation, and finally retrieve the time again after the node wakes up, you will find that the time is incorrect after hibernation.
I encountered this issue while working with the gcoap example on the same54-xpro board. After adding the rtt_rtc module, I followed the steps mentioned above and observed that the time returned by rtc_gettime() after waking up from hibernation did not match the expected value.
The output before the fix, you can notice the time after hibernation is wrong
```
rtc gettime
2024-08-28 17:48:10,774 # rtc …
```
=> cpu/sam0_common/periph: fix rtt reset after hibernation

pkg/lvgl/include/lv_conf.h, tests/pkg/lvgl/Makefile, tests/pkg/lvgl_touch/Makefile
Now that we have the `libsdl2-dev:amd64` package in the CI image (RIOT-OS/riotdocker#241), we can remove `native64` from the blacklist and build the lvgl tests in the CI.
The CI doesn't run the GUI program, but if we run the executable directly, we can see that the lvgl heap size chosen for RIOT is too small for a 64-bit system, since lvgl allocates a lot of space for pointers and the current limits seem to be as small as possible to make the examples run on 32-bit platforms.
I changed the default lvgl heap sizes in `pkg/lvgl/include/lv_conf.h` for 64-bit systems so that the examples can run.
The correct heap size is very application and platform specific. Simply extending the header to include a variety of different default heap sizes to run the examples may not be the most elegant way …
=> pkg/lvgl: Increase default LV_MEM_SIZE for 64 bit and enable tests for native64

boards/nucleo-g431rb/doc.txt
This PR adds MCU table for `nucleo-g431rb` board. Moreover, accordingly to comments from PR #20832 detailed source of pinout is added.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-g431rb.html
```
pinout source issue PR #20832
=> boards/nucleo-g431rb: add MCU table to documentation

sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c, tests/unittests/tests-gnrc_ipv6_nib/tests-gnrc_ipv6_nib-internal.c
Reserve unspecified address in NCEs for on-link prefixes, to have
`_PFX_ON_LINK => ipv6_addr_is_unspecified(dst->next_hop)` be true
In nib_[onl|offl]_entry_t,
a next_hop of NULL (as used by prefix list)
shouldn't be interpreted as "don't care"
but as an explicit "none, not applicable",
because the next_hop value is used for association with a router at
https://github.com/RIOT-OS/RIOT/blob/270aa7012fab0ceadeb0b82546ea06dbfe9c0902/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L1469
The code intends to delete all off-link prefixes where next hop is the specified router [1], but (without this PR) it actually also deletes on-link prefixes on the same interface [2] because they falsely use the same next hop. (And are only distinguished as on-link through `_PFX_ON_LINK` flag, which however is not …
=> gnrc_ipv6_nib: Force unspecified next hop addresses

boards/nucleo-g474re/doc.txt
This PR adds MCU table for `nucleo-g474re` board. Moreover, accordingly to comments from PR #20832 detailed source of pinout is added.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-g474re.html
```
PR #20832
=> boards/nucleo-g474re: add MCU table

tests/net/gnrc_ipv6_nib/main.c
This PR only provides a test to verify that `_handle_rtr_timeout` does not have any effect on any RA options:
> The Router Lifetime applies only to
the router's usefulness as a default router; **it
does not apply to information contained in other
message fields or options**.  Options that need time
limits for their information include their own
lifetime fields.
- https://datatracker.ietf.org/doc/html/rfc4861
Emphasis added to highlight what part exactly this test covers. (In particular, it does not cover testing that the "Router Lifetime" has any effect to "the router's usefulness as a default router".)
Test is implemented as part of the "base test function", causing 4 tests to fail if not providing an implementation.
Test is fulfilled by #20329 and #20371 (alone each, but they are also …
=> tests/gnrc_ipv6_nib: rtr_ltime test

cpu/nrf52/radio/nrf802154/nrf802154_radio.c
As detailed in #20803, The calculation of RSSI based on the hardware-provided LQI value on `master` is wrong. The [documentation](https://docs.nordicsemi.com/bundle/ps_nrf52840/page/radio.html#ariaid-title20) states that
> When receiving a frame the RSSI (reported as negative dB) will be measured at three points during the reception. These three values will be sorted and the middle one selected (median 3) for then to be remapped within the LQI range.
without further detailing the applied mapping.
Reusing the [RSSI measurement functionality](https://docs.nordicsemi.com/bundle/ps_nrf52840/page/radio.html#ariaid-title9), I was able to find out the (reverse) mapping with the diff below.
Apply the following diff enabling automatic RSSI measurement during packet reception:
```diff
diff --git …
```
=> cpu/nrf52: fix RSSI calculation in nrf802154_radio

sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/sock.c, tests/net/nanocoap_cli/main.c, tests/net/nanocoap_cli/nanocli_client.c
We have NON-Confirmable versions for PUT, POST, and FETCH, but non for GET so far.
This PR adds it in a straight forward manner.
`tapsetup`
Two `native` instances of `tests/net/nanocoap_cli`.
One starts the server:
```
2024-09-05 15:48:28,576 # server start
2024-09-05 15:48:28,576 # starting server on port 5683
```
The other one GETs a resource:
```
> get_non coap://[fe80::a0ae:a2ff:fe2f:af16]/value
2024-09-05 15:48:32,316 # get_non coap://[fe80::a0ae:a2ff:fe2f:af16]/value
2024-09-05 15:48:32,318 # 00000000  30
```
=> sys/net/application_layer/nanocoap: add `nanocoap_sock_get_non()`

doc/doxygen/src/using-rust.md, makefiles/docker.inc.mk
The docker image now uses c2rust 0.19 and Rust 1.81.
Initially, this only contains the documentation update. That first commit will serve to ask CI to give me the right hashes that'll go in a follow-up commit.
CI should suffice.
https://github.com/RIOT-OS/riotdocker/pull/252
=> Update docker image (and document the process)

boards/nucleo-f207zg/doc.txt, boards/nucleo-f303ze/doc.txt, boards/nucleo-f412zg/doc.txt, boards/nucleo-f413zh/doc.txt, boards/nucleo-f429zi/doc.txt, boards/nucleo-f439zi/doc.txt, boards/nucleo-f446ze/doc.txt, boards/nucleo-f722ze/doc.txt, boards/nucleo-f767zi/doc.txt, boards/nucleo-l496zg/doc.txt, boards/nucleo-l4r5zi/doc.txt
This PR adds detailed pinout source (UM number, link and page) to all pinouts for nucleo-144 boards. 
The issue was mentioned in the comments for PR #20832.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f207zg.html
. . .
```
PR #20832
=> boards/nucleo144: add pinout source

sys/net/application_layer/nanocoap/nanocoap.c
The CoAP block option gets written twice:
First a 'dummy' value is written by `coap_opt_add_block2()`, later this gets overwritten by the real option value by `coap_block2_finish()`.
The problem arises when the size of the option changes. If the option ends up smaller than the dummy, we have garbage bytes after the real option value, corrupting the packet.
To mitigate this, always write at least one option byte (which will be a 0 byte) to ensure the dummy data is overwritten.
- run `examples/gcoap_fileserver`:
make -C examples/gcoap_fileserver PORT=tap1 all term
- create a dummy file
echo "Hello World!" > examples/gcoap_fileserver/native/me
- Try to access the file via e.g. `ncget` with a 16 byte block size
CFLAGS=-DCONFIG_NANOCOAP_BLOCKSIZE_DEFAULT=COAP_BLOCKSIZE_16 make -C …
=> nanocoap: always write at least 1 byte in coap_block2_finish()

cpu/samd5x/cpu.c
This formats the code to improve readability and apply the coding convention. This is a whitespace only change that will not change generated binaries.
Confirm that only white space is changed. (I did sneak in dropping an unused header. But other than that.)
None
=> cpu/samd5x/cpu.c: reformat code

CODING_CONVENTIONS.md
This explicitly spells out what informally has been the coding convention for some time on preprocessor directives, making it more transparent and easier to find.
This is particularly useful as the code base has at least three different styles. Deducing what actually is the current policy would require a details look at how the style has changed over time, rather than being obvious from a quick `grep` over the code base.
Check that the wording is clear and easy to understand and that the policy matches what we actually do. (E.g. look at ztimer, as this is a rather new component that has received lots of reviewing.)
https://github.com/RIOT-OS/RIOT/pull/20864#discussion_r1764795474
=> CODING_CONVENTIONS.md: Add preprocessor directive formatting

sys/include/net/gnrc/ipv6/nib/ft.h, sys/net/gnrc/network_layer/ipv6/nib/nib_ft.c
An off-link prefix with SLAAC (i.e. RA PIO: L flag = 0, A flag = 1):
- is listed in `nib prefix`. Listing it here only means it’s a "managed" prefix (for SLAAC lifetimes), no indication about whether it’s on-link.
- `nib route`
❌ Currently **falsely displays it as on-link** (e.g. `2001:db8::/32 dev #6`)
Should not list it, to reflect the actually used routing logic [1]
https://github.com/RIOT-OS/RIOT/blob/0e7636a463894c177a2982fd08f7e02cef83aa89/sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c#L653
This PR removes it from the `nib route` output.
[1] which is correct ("forward the packet to a default router" - https://datatracker.ietf.org/doc/html/rfc4861#section-6.3.4)
<details>
<summary>Expand</summary>
`sudo dist/tools/tapsetup/tapsetup`
In any directory:
Set file content of …
=> gnrc/ipv6: `nib route`: hide off-link PLEs

sys/event/timeout_ztimer.c
Currently, the following can result in `event_B` being executed before `event_A`:
```c
event_timeout_set(event_A, 0);
event_post(event_queue, event_B);
```
I think this is unexpected behavior. Queuing an event with timeout zero should schedule the event for immediate execution. I therefore added a check in `event_timeout_set()` to immediately queue if the timeout is zero.
I briefly tested this on native in the application I'm currently working on.
=> event/timeout: event_timeout_set() enqueues immediately if timeout is zero

drivers/include/periph/cpuid.h
Pulling in prior art around https://github.com/future-proof-iot/RIOT-rs/pull/444, I hurt myself in confusion.
Look the built docs, they now have a note to prevent that confusion.
=> doc: Clarify that our CPU ID is not ARM's CPUID

sys/net/gnrc/Makefile.dep
6lowpan fragmentation is broken on `at86rf215` since #20672. The driver no longer tries to block when a transfer is ongoing, but reports `-EBUSY` to the upper layer when a send is triggered while the previous frame is still being sent.
For this to work (and not drop the 2nd fragment), we need `gnrc_netif_pktq`.
6lo fragmented packets are working again
```
2024-09-30 12:00:50,928 # > ping -s 512 fe80::6419:e83f:8e6b:4ce7%7
2024-09-30 12:00:51,042 # 520 bytes from fe80::6419:e83f:8e6b:4ce7%7: icmp_seq=0 ttl=64 rssi=-40 dBm time=108.982 ms
2024-09-30 12:00:52,050 # 520 bytes from fe80::6419:e83f:8e6b:4ce7%7: icmp_seq=1 ttl=64 rssi=-40 dBm time=108.986 ms
2024-09-30 12:00:53,044 # 520 bytes from fe80::6419:e83f:8e6b:4ce7%7: icmp_seq=2 ttl=64 rssi=-39 dBm time=108.983 ms
2024-09-30 …
```
=> gnrc_sixlowpan_frag: enable `gnrc_netif_pktq` if `netdev_new_api` is used

makefiles/suit.inc.mk
Specifying the password of the SUIT private key on the command line and thereby committing it to shell history is a security issue.
Instead ask for the password interactively when an encrypted private key is used.
```
$ make -C examples/suit_update SUIT_KEY=supersecret 
make: Entering directory '/home/benpicco/dev/RIOT/examples/suit_update'
Building application "suit_update" for "samr21-xpro" with CPU "samd21".
suit: generating key in /home/benpicco/.local/share/RIOT/keys
0) none
1) aes-256-cbc
Choose encryption for key file /home/benpicco/.local/share/RIOT/keys/supersecret.pem: 1
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
```
```
$ make -C examples/suit_update SUIT_KEY=supersecret suit/publish
make: Entering directory '/home/benpicco/dev/RIOT/examples/suit_update' …
```
=> makefiles/suit: make use of `SUIT_SEC_PASSWORD` optional 

makefiles/arch/native.inc.mk
We don't enable this on any other architecture.
`-pedantic` doesn't give us any more beneficial warnings, only warns about language extensions that are implemented by both GCC and Clang anyway.
Since those are the only compilers we are targeting, we can just make use of them to make our lives easier.
Code should still compile as before.
We can likely drop all those
```C
typedef int dont_be_pedantic;
```
as a follow-up.
=> makefiles/arch/native: don't be pedantic

dist/tools/bootterm/Makefile
Update the tool to the latest upstream version
`make RIOT_TERMINAL=bootterm term` is still working
```
Trying port /dev/ttyACM0... Connected to /dev/ttyACM0 at 115200 bps.
Escape character is 'Ctrl-]'. Use escape followed by '?' for help.
> ps
pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
- | isr_stack            | -        - |   - |    512 (  172) (  340) | 0x20000000 | 0x200001c8
1 | main                 | running  Q |   7 |   1536 (  708) (  828) | 0x200002c0 | 0x200007ac 
2 | pktdump              | bl rx    _ |   6 |   1472 (  172) ( 1300) | 0x20001048 | 0x2000155c 
3 | sam0_eth             | bl anyfl _ |   2 |    896 (  276) (  620) | 0x20000a5c | 0x20000d1c 
| SUM                  |            |     |   4416 ( 1328) ( 3088)
> 
```
=> dist/tools/bootterm: bump to 0.5

examples/lorawan/main.c
We cannot just decrement the reference counter of power modes without any coordination. First, this will trigger an `assert()`ion on non STM32 MCUs that have power modes that are not used (the ref count would be decremented below zero). Second, there hopefully is a reason a certain power mode is blocked, e.g. because a periph driver needs a certain clock to function.
Likely the `periph_uart` driver on STM32 boards keeps power modes blocked after TX is completed even when no RX callback is present, which is the waste of power this hack tries to address. But that should be addressed there.
With `master` on `wemos-zero` we get:
```
2024-10-01 15:34:30,055 # main(): This is RIOT! (Version: 2024.10-devel-217-g61df1)
2024-10-01 15:34:30,056 # LoRaWAN Class A low-power application
2024-10-01 …
```
=> examples/lorawan: drop crazy STM32 hack

boards/common/arduino-zero/include/arduino_iomap.h, boards/common/arduino-zero/include/periph_conf.h
The Arduino Zero based boards already provided the feature `arduino_spi`, but were missing the corresponding mapping. This fixes the issue by adding the SPI bus numbers for the ISP SPI bus and the D11D12D13 SPI bus.
(And in order to actually add the D11D12D13 SPI bus, the `periph_conf.h` was extended to provide an SPI configuration for it.)
Add an Arduino Ethernet Shield (the classic one with the W5100 chip) on top of an Arduino Zero board (either original or one of the compatible clones) and run:
```
USEMODULE=shield_w5100 make BOARD=wemos-zero -C examples/gnrc_networking flash term
```
This will fail to compile on `master` (due to the missing SPI defines), but succeed with this PR.
Sadly, this will only test the SPI bus already present in the `periph_conf.h`, not the one added.
None
=> boards/common/arduino-zero: Add Arudino SPI mapping

examples/rust-gcoap/Cargo.lock, examples/rust-gcoap/Cargo.toml, examples/rust-gcoap/Makefile, examples/rust-gcoap/Makefile.ci, examples/rust-gcoap/README.md, examples/rust-gcoap/src/lib.rs
The riot-coap-handler-demos has a few ready-made components that were not shown off in examples/rust-gcoap before. I think they are useful to have, as they point users to more example code and to things they can explore with safe Rust bindings. The added resources don't make the example's source code more complex (effectively they're all just adding a line), but obviously they increase code size.
Concretely, this exposes any board LEDs as individual resources (PUT CBOR values false or true, or POST (see maturity)), and also exposes /netif which roughly contains data from `ifconfig` (only MAC address and IP addresses so far).
Two non-src/lib.rs changes are an added note in the README on security (none is there, thus we only expose harmless things), updating various riot-wrappers related …
=> examples/gcoap-rust: Expose more functionality

sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mcps.c
Hello 🦛
This adds missing bounds checks.
Honestly, I am just hoping for CI 🫤
=> gnrc_lorawan: Ensure minimal packet length

drivers/Makefile.dep, drivers/doc.txt, drivers/sx126x/include/sx126x_params.h, makefiles/pseudomodules.inc.mk
This implements the `shield_llcc68` module that allows using the LLCC68 LoRa shield on Arduino UNO compatible boards (with Arduino IO mappings provided by the board) by just selecting the module.
```
USEMODULE="shield_llcc68" make BOARD=wemos-zero PROGRAMMER=openocd OPENOCD_DEBUG_ADAPTER=jlink VERBOSE_ASSERT=1 -C examples/gnrc_networking term
```
```
2024-10-01 18:34:49,475 # ifconfig
2024-10-01 18:34:49,477 # Iface  6  Frequency: 868300000Hz  RSSI: -128  BW: 125kHz  SF: 7  CR: 4/5 
2024-10-01 18:34:49,477 #            State: STANDBY 
2024-10-01 18:34:49,479 #           MTU:65535  HL:64  RTR  
2024-10-01 18:34:49,479 #           RTR_ADV  
2024-10-01 18:34:49,480 #           Link type: wireless
2024-10-01 18:34:49,480 #           inet6 group: ff02::2
2024-10-01 18:34:49,480 # …
```
=> drivers: Add shield_llcc68 module

makefiles/docker.inc.mk
This acknowledges the changes after [254], which moved the Rust installation into the static tools.
[254]: https://github.com/RIOT-OS/riotdocker/pull/254
CI self-tests this.
=> makefiles/docker: Update docker image

sys/net/application_layer/dhcpv6/client.c
Hello 🐿️
This adds missed size checks for the type conversions.
Please note that `dhcpv6_opt_ia_pd_t` and `dhcpv6_opt_ia_na_t` make use of flexible array member - so I am not super sure if the check is enough.
A good review by @miri64
=> net/dhcpv6: Improve option parsing in dhcpv6 advertise

sys/net/ble/bluetil/bluetil_ad/bluetil_ad.c
Hey 🦪
this fixes an erroneous advertisement parsing, in which the length of the adv. was inherently trusted.
Good review should be sufficient.
=> bluetil: Ensure advertisement length does not exceed pkt len

dist/tools/cargo-checks/check.sh, dist/tools/ci/static_tests.sh, drivers/lsm303agr/src/lib.rs, examples/rust-async/src/lib.rs, examples/rust-gcoap/src/lib.rs, examples/rust-hello-world/src/lib.rs, sys/shell/democommands/src/lib.rs, tests/rust_minimal/src/lib.rs
It is common for projects with Rust code to just enforce the code style suggested by Rust.
This adds a check to the static tests, and a second commits changes all the Rust sources to actually follow the code style (that is automated, `cargo fmt` does it).
This PR should fail with a sensible message on the first run, and be green when I push the second commit fixing all the formatting errors (through the provided command).
Thanks @Teufelchen1 for spotting the formatting errors.
This is a do-over of https://github.com/RIOT-OS/RIOT/pull/20886 which [GitHub killed](https://github.com/RIOT-OS/RIOT/pull/20886#issuecomment-2389576195).
=> static_tests: Add test for Rust code formatting rules

core/mutex.c
Using `sched_switch()` in `mutex_unlock()` can result in crashes when `mutex_unlock()` is called from IRQ context. This however is a common pattern in RIOT to wake up a thread from IRQ. The reason for the crash is that `sched_switch()` assumes `thread_get_active()` to always return a non-`NULL` value. But when thread-less idle is used, no thread may be active after the last runnable thread exited. Using `thread_yield_higher()` instead solves the issue, as `thread_yield_higher()` is safe to call from IRQ context without an active thread.
As described in https://github.com/RIOT-OS/RIOT/issues/20812 (also add the `assert(active_thread != NULL);` to `sched_switch()` to not rely on undefined behavior triggering the crash, but to crash reliably on invalid state).
In addition to fixing the …
=> core/mutex: use thread_yield_higher() in mutex_unlock()

boards/nucleo-l432kc/Makefile.features, cpu/stm32/include/can_params.h
This PR adds CAN support to the `nucleo-l432kc`board (see issue #20837) .
The testing procedure requires one Nucleo L432KC board, one Nucleo board having CAN interface (F446RE for instance) and 2 CAN drivers (such as [ST L9616](https://www.st.com/en/automotive-analog-and-power/l9616.html)).
```bash
cd tests/sys/conn_can
make BOARD=nucleo-l432kc flash term
```
Nucleo 1 (receiver)
```
init 0
set_mode 0 0
test_can recv 1 0 10000000 100 500
```
Nucleo 2 (sender)
```
init 0
set_mode 0 0
test_can send 0 100 01 02
```
fixes #20837.
=> boards/nucleo-l432kc: enable CAN support

core/include/thread.h, sys/net/application_layer/gcoap/forward_proxy_thread.c, tests/sys/shell/main.c
Those were missed in #20450
No functional changes.
follow-up to #20450
=> treewide: clean up remnants of THREAD_CREATE_STACKTEST

Makefile
With #20187, running `make` or `make all` in the RIOT base directory prints the welcome message including a list of available targets to be called from there. However, when the user enters an unknown target such as `make unknown`, Make only outputs a generic error.
This PR fixes this and shows the welcome message instead.
on `master`:
```
$ make unknown
make: *** No rule to make target 'unknown'.  Stop.
```
with this PR:
```
$ make unknown         
*** ERROR: unrecognized target "unknown"
Welcome to RIOT - The friendly OS for IoT!
You executed 'make' from the base directory.
Usually, you should run 'make' in your application's directory instead.
Please see our Quick Start Guide at:
https://doc.riot-os.org/getting-started.html
You can ask questions or discuss with other users on our forum: …
```
=> Makefile: add .DEFAULT target to further guide new users

doc/doxygen/Makefile
It can be confusing for new users where to find the HTML documentation generated with `make doc`. This PR prints the link to the `index.html` after successful generation.
`make doc`
also, CI should not be confused with these changes
=> doc/doxygen: print link to generated documentation

cpu/samd5x/include/periph_cpu.h
There were some bogus chars in a comment. Let's drop them.
Only whitespace changes, so this should not change the generated binaries.
None
=> cpu/samd5x/periph_cph.h: drop non-UTF-8 chars

boards/spark-core/doc.txt, cpu/esp32/doc.txt, dist/tools/codespell/ignored_words.txt, dist/tools/zep_dispatch/main.c, drivers/at86rf2xx/include/at86rf2xx_internal.h, drivers/atwinc15x0/doc.txt, drivers/include/enc28j60.h, drivers/include/ltc4150.h, drivers/sdmmc/sdmmc_sdhc.c, pkg/tlsf/contrib/native.c, pkg/uwb-core/include/dpl/dpl_eventq.h, release-notes.txt, sys/include/shell.h, sys/net/gnrc/transport_layer/tcp/include/gnrc_tcp_fsm.h
The static tests have been failing on `master` for some time due to codespell findings: https://github.com/RIOT-OS/RIOT/actions/workflows/static-test.yml
That happened probably after some update to the `riot/riotbuild` docker image, which presumably lead to a version bump of codespell.
This PR adds some new false positives to the ignored-words list and fixes several found true positives throughout the codebase.
Review typo corrections and newly added false positives.
Static tests in this PR will probably run through anyway as for all the other recent PRs. I'm wondering if the static-test workflow somehow uses a cached version of `riot/static-test-tools:latest`, since pulling that and executing the codespell check locally there also fails.
=> CI: fix true and false positives by newer codespell version

cpu/sam0_common/periph/dma.c
Match the signature of the implementation of the dma_prepare() with the declaration to fix:
/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/cpu/sam0_common/periph/dma.c:172:6: error: conflicting types for 'dma_prepare' due to enum/integer mismatch; have 'void(dma_t,  uint8_t,  const void *, void *, size_t,  uint8_t)' {aka 'void(unsigned int,  unsigned char,  const void *, void *, unsigned int,  unsigned char)'} [-Werror=enum-int-mismatch]
172 | void dma_prepare(dma_t dma, uint8_t width, const void *src, void *dst,
|      ^~~~~~~~~~~
In file included from /home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/cpu/samd5x/include/periph_cpu.h:26,
from /home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/cpu/sam0_common/periph/dma.c:21: …
=> cpu/sam0_common/periph_dma: Fix API mismatch

pkg/driver_bme680/Makefile
The upstream repo has gone, so let's use a mirror for now to avoid build failures.
`make -C tests/drivers/bme680` will now succeed. (Note: You may need to remove the `$(BUILD_DIR)/pkg/driver_bme680` folder first to clear the local cache, otherwise the build system will never check the upstream.)
None
=> pkg/driver_bme680: use mirror of git repo

boards/adafruit-grand-central-m4-express/Makefile.features, boards/adafruit-grand-central-m4-express/include/arduino_iomap.h, boards/adafruit-grand-central-m4-express/include/periph_conf.h
The board is compatible with Arduino UNO and Arduino MEGA shields and has an ISP connector, so this adds the corresponding features.
This adds the Arduino I/O-mapping for the ISP SPI and provides the corresponding feature.
It appears that the SPI on D11/D12/D13 cannot be provided by a SERCOM, this is under clarification at [1]. For now, no I/O mapping for that SPI bus is provided.
[1]: https://forums.adafruit.com/viewtopic.php?t=214093
An Arduino Shield that uses the ISP SPI bus (the older ones targeting the AVR based Arduinos still do that) should now work out of the box.
E.g.
```
USEMODULE=shield_w5100 make -C examples/gnrc_networking BOARD=adafruit-grand-central-m4-express flash term
[...]
2024-10-10 10:28:28,746 # ifconfig
2024-10-10 10:28:28,747 # Iface  6  HWaddr: A6:45:6B:D7:7E:41 …
```
=> boards/adafruit-grand-central-m4-express: provide arduino features

makefiles/vars.inc.mk
This patch exports the make macro `DEVELHELP`. Without this patch, use of the macro in the following files does not work when the macro is set in a makefile (such as in Makefile.local or an application's makefile as demonstrated in dist/Makefile). Inside these files `DEVELHELP` is not defined under these conditions.
- pkg/littlefs/Makefile
- pkg/littlefs2/Makefile
- sys/stdio_null/Makefile
Note that use of the macro does work in these files when the macro is set from the command line, without the patch. For example:
``` sh
$make DEVELHELP=1 all
```
1. run: `make -C examples/hello-world/ USEMODULE+=stdio_null`
2. observe the warning `Makefile:2: STDIO disabled via stdio_null, but DEVELHELP enabled` is seen with this patch, and is not seen without the patch. The warning is being emmited …
=> make: export DEVELHELP

sys/event/periodic.c, sys/include/event/periodic.h, sys/include/ztimer/periodic.h, sys/ztimer/periodic.c, tests/sys/event_ztimer/main.c
Depending on what you want, a periodic event could happen the first time after the first interval, or without initial delay.
Only the first variant is implemented in RIOT so far. This adds an API to start it without delay.
Currently I am misusing the timed events for that. I initialize them with 0 delay and in their callback I re-initialize and add them again with actual delay. The reinit is an invitation for race conditions if the event could also be added from another thread as the event thread.  
I added a call to the new API in `tests/sys/event_ztimer`.
```
s
START
main(): This is RIOT! (Version: 2024.10-devel-292-gb6d800-pr/event_periodic_no_delay)
posting periodic timed callback with timeout 1sec
waiting for periodic callback to be …
```
=> sys/event: add API to start periodic event without initial delay

.clang-format
This adds a clang-format configuration based on the Linux Kernel configuration and modified to better match RIOT's coding convention.
Automatic formatting using clang-format should now match RIOT's coding convention relatively closely. Aligning bitmasks is still a pain point, though. I think this is not yet possible to configure, but something that we don't have too often. E.g. the following would still not work
```C
/* good */
FOO_REG = FOO_REG_VAL1
| FOO_REG_VAL2
| FOO_REG_VAL3;
/* bad (but sadly currently generated by clang-format) */
FOO_REG = FOO_REG_VAL1 |
FOO_REG_VAL2 | FOO_REG_VAL3;
```
None
=> .clang-format: Add default clang-format configuration

cpu/cortexm_common/Makefile.features, cpu/esp32/Makefile.features, cpu/esp32/Makefile.include
This PR improves the error messages of the esp32 common makefiles when adding new esp32 based boards/cpu. 
The previous error messages did not make it clear which part was still missing when adding a new esp32 based board/cpu variant, thus making it needlessly complicated to pinpoint the problem (and also had a minor spelling mistake).
This also fixes the same spelling mistake for the cortexm error message.
I tested the hello_world on both `native`and `esp32c3-devkit` and also while adding a new variant to the `esp32` family. In all three cases everything worked as expected and it helped me to locate issues while adding a new variant.
=> cpu/esp32: Improve error descriptions

pkg/littlefs/Makefile, pkg/littlefs/lfs_log.h, pkg/littlefs/patches/0001-remove-pkg-supplied-logging-macros.patch, pkg/littlefs2/Makefile, pkg/littlefs2/lfs_log.h, tests/pkg/littlefs/Makefile, tests/pkg/littlefs2/Makefile
This patch replaces littlefs's logging with RIOT's own logging module.
``` sh
make -C tests/pkg/littlefs all term
make -C tests/pkg/littlefs2 all term
```
Some log messages in the tests needed to be silenced due to this patch also fixing broken support of logging in the package. See #20889.
=> pkg/littlefs: make use of RIOT's log module instead of pkg provided macros

sys/include/net/nanocoap.h, sys/net/application_layer/nanocoap/nanocoap.c
Some calls to `coap_build_hdr()` were done with the target buffer for the header and the source buffer for the token overlapping: They reuse the buffer that held the request to assemble the response in. We cannot use `memcpy()` in this case to copy the token into the target buffer, as source and destination would (fully) overlap.
This commit makes reusing the request buffer for the response a special case: `memcpy()` is only used to copy the token if source and destination address of the token differ.
An alternative fix would have been to use `memmove()` unconditionally. But `memmove()` does not make any assumption about the layout of target and source buffer, while we know that the token either will already be at the right position (when reusing the request buffer for the response) or be …
=> sys/net/nanocoap: fix UB when building hdr

boards/common/saml1x/include/board.h
Both `saml10-xpro` and `saml11-xpro` come with the ATECC508A chuip, so don't guard it for one board.
I ran `tests/pkg/cryptoauthlib_compare_sha256` on `saml10-xpro`
```
2024-10-16 15:36:28,700 # main(): This is RIOT! (Version: 2024.10-devel-303-g79dc90-boards/saml10-xpro_cryptoauthlib)
2024-10-16 15:36:28,703 # RIOT SHA256: Success
2024-10-16 15:36:28,728 # ATCA SHA256: Success
```
=> boards/saml10-xpro: enable ATECC508A

sys/include/net/nanocoap.h, sys/net/application_layer/gcoap/gcoap.c, sys/net/application_layer/nanocoap/fileserver.c
This adds a small convenience function to set the CoAP code of a packet and converts users of coap_hdr_set_code() where applicable.
No regressions should be introduced (the CI will tell).
Relevant to https://github.com/RIOT-OS/rust-riot-wrappers/pull/130
=> sys/nanocoap: add coap_pkt_set_code()

makefiles/docker.inc.mk
riotbuild has been rebuilt yesterday evening, which pulls in the latest version of Rust.
(Now that there is just one hash, I took it from dockerhub – let's see if this works with just one Actions run).
CI passes.
=> makefiles: Update docker image

examples/rust-async/Cargo.lock, examples/rust-gcoap/Cargo.lock, examples/rust-hello-world/Cargo.lock, sys/rust_riotmodules_standalone/Cargo.lock, tests/rust_minimal/Cargo.lock
All our Rust packages are locked to a particular version, even though the dependencies are also expressed as version requirements.
This updates all of them.
Noteworthy changes:
* shlex is updated. This is run on the host at build time. IIRC that had security issues – doesn't really affect us (whoever can get input in there already owns the Makefile), but it's good to set off fewer alarms.
* critical-section is updated fixing a soundness hole. Hard to tell whether it affected us, but again, no harm in updating.
* coap-message-demos are updated to not show `/time` when it produces no sensible output anyway
* riot-wrappers is future-proofed by including https://github.com/RIOT-OS/rust-riot-wrappers/pull/130
* riot-sys and riot-wrappers are updated in all places across versions that have …
=> treewide: Update Rust dependencies

boards/nucleo-f722ze/doc.txt
This PR fix typo in `nucleo-f722ze` documentation page. 
Currently there is "STM ser manual" should be "STM user manual".
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f722ze.html
```
None.
=> boards/nucleo-f722: fix typo in documentation

sys/ztimer/core.c
If the timer at the head of a ztimer clock's timer list is re-scheduled (`ztimer_set()` called on an already set timer) and the timer is no longer at the head after being re-scheduled, `clock-ops->set()` is never called from inside `ztimer_set()`, and the underlying timer is left with an ISR scheduled to expire at the timer's old time. The intended behavior is that the clock's lower level timer should always be set to expire at the time of the clocks head timer.
This patch changes `ztimer_set()` to call `_ztimer_update()`, which sets the lower level timer according to the current list of timers, rather than setting the timer directly inside of `ztimer_set()`.
This is a fix we might consider back porting. As far as I can tell this bug has always existed in `ztimer`.
- apply patch to create …
=> sys/ztimer: fix re-scheduling of timers

sys/event/event.c, sys/include/event.h, tests/sys/events/main.c
In some cases it's useful to ensure forward progress in the event queue before continuing. This PR adds `event_sync()`, which blocks until the last event on the queue at the moment of calling this (if any) will have been processed, e.g.
```c
event_post(queue, my_event);
// When event_sync() returns, my_event will have been processed.
event_sync();
```
The unit test was updated accordingly.
=> sys/event: add event_sync()

drivers/dht/dht.c, drivers/include/dht.h, tests/drivers/dht/main.c
The SAUL interface exposes two sensors for humidity and temperature, while the internal `dht` driver exposes a single `dht_read` function with two pointers to store humidity and temperature results. The SAUL wrappers pass NULL for the value they're not interested in, but `dht_read` does not check for that and tries to store both values all the time, causing a segfault.
The initial bug and its fix have been observed with a DHT11 on a Wemos D1 Mini with the `saul` shell command.
N/A
=> drivers/dht: fix null deref with saul

boards/nucleo-c031c6/doc.txt, boards/nucleo-f030r8/doc.txt, boards/nucleo-f070rb/doc.txt, boards/nucleo-f072rb/doc.txt, boards/nucleo-f091rc/doc.txt, boards/nucleo-f103rb/doc.txt, boards/nucleo-f302r8/doc.txt, boards/nucleo-f303re/doc.txt, boards/nucleo-f334r8/doc.txt, boards/nucleo-f401re/doc.txt, boards/nucleo-f410rb/doc.txt, boards/nucleo-f411re/doc.txt, boards/nucleo-f446re/doc.txt, boards/nucleo-g070rb/doc.txt, boards/nucleo-g071rb/doc.txt, boards/nucleo-l053r8/doc.txt, boards/nucleo-l073rz/doc.txt, boards/nucleo-l152re/doc.txt, boards/nucleo-l452re/doc.txt, boards/nucleo-l476rg/doc.txt
This PR adds detailed pinout source (UM number, link and page) to all pinouts for nucleo-64 boards.
The issue was mentioned in the comments for PR https://github.com/RIOT-OS/RIOT/pull/20832.
Generate doc and check if everything in the doc page is correct.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-c031c6.html
.   .   .
```
PR #20832, #20859
=> boards/nucleo64: add pinout source

boards/adafruit-grand-central-m4-express/include/periph_conf.h, boards/adafruit-itsybitsy-m4/include/periph_conf.h, boards/adafruit-pybadge/include/periph_conf.h, boards/same54-xpro/include/periph_conf.h
When not otherwise specified, the ADC will be clocked by GCLK_MAIN which in case of SAM D5x/E5x is configured to run at 120 MHz.
This exceeds the maximum allowed input GCLK frequency.
We could use `DIV4` here as well, but as long as we don't have the sample length calculation in, better run the ADC at a more conservative pace.
`tests/periph/adc` still works
```
2024-10-22 13:24:57,458 # main(): This is RIOT! (Version: 2024.10-devel-340-gdf7e3-boards/samd5x-adc_freq)
2024-10-22 13:24:57,458 # 
2024-10-22 13:24:57,461 # RIOT ADC peripheral driver test
2024-10-22 13:24:57,461 # 
2024-10-22 13:24:57,467 # This test will sample all available ADC lines once every 100ms with
2024-10-22 13:24:57,472 # a 10-bit resolution and print the sampled results to STDIO
2024-10-22 13:24:57,472 # 
2024-10-22 …
```
=> boards/samd5x: GCLK source for ADC must not exceed 100 MHz

cpu/atmega_common/periph/gpio.c, cpu/atxmega/periph/gpio.c, cpu/cc2538/periph/gpio.c, cpu/cc26xx_cc13xx/periph/gpio.c, cpu/efm32/periph/gpio.c, cpu/esp32/periph/gpio.c, cpu/esp8266/periph/gpio.c, cpu/fe310/periph/gpio.c, cpu/gd32v/periph/gpio.c, cpu/kinetis/periph/gpio.c, cpu/lm4f120/periph/gpio.c, cpu/lpc1768/periph/gpio.c, cpu/lpc23xx/periph/gpio.c, cpu/msp430/periph/gpio.c, cpu/native/periph/gpio_linux.c, cpu/native/periph/gpio_mock.c, cpu/nrf5x_common/periph/gpio.c, cpu/qn908x/periph/gpio.c, cpu/rpx0xx/periph/gpio.c, cpu/sam0_common/periph/gpio.c, cpu/sam3/periph/gpio.c, cpu/stm32/periph/gpio_all.c, cpu/stm32/periph/gpio_f1.c, drivers/include/periph/gpio.h
There is no reason for `gpio_write()` to take an `int` when a GPIO can only be either on or off.
To avoid confusion, switch to `bool`
Since a `bool` is usually just an `int` in disguise, there should be no code or semantic changes.
=> drivers/periph/gpio: make `gpio_write()` take a bool

sys/net/application_layer/gcoap/forward_proxy.c, sys/net/application_layer/gcoap/gcoap.c
Handle when the CoAP forward proxy is not getting a response from the remote server, by sending a RST message to the client, so it will not wait further for a response.
We used nanocoap client and the proxy without uplink connection. So the request will timeout and the client will get a RST. 
#20910
=> gcoap/forward_proxy: handle timeout case

sys/net/application_layer/gcoap/gcoap.c
The debug output breaks the build when compiled with IPv4 support. 
`make -C examples/gcoap LWIP_IPV4=1` should work again.
=> gcoap: fix build with IPv4

examples/cord_ep/README.md, examples/cord_epsim/README.md, examples/cord_lc/README.md, sys/include/net/cord/ep.h, sys/include/net/cord/lc.h, sys/net/application_layer/cord/doc.txt
This PR updates the doc file of the `CORD` module and examples in RIOT. Updates:
- Update of the references to **RFC 9176**.
- Removal of the label **Not Yet Implemented** in the doc file of the `CORD` module, since it is obsolete.
- The **draft-ietf-core-resource-directory-27** was compared with the **RFC 9176** and no necessary changes in the implementation were found.
- An experimental Lookup Client was built, to test if the functions from the `cord_lc` of the `CORD` module in RIOT were implemented. Lookup requests were sent to an `aiocoap` Resource Directory implementation. All the functions in the `cord_lc` returned the expected results.
- [Comparison draft-ietf-core-resource-directory-27 vs RFC 9176](https://author-tools.ietf.org/iddiff?url1=draft-ietf-core-resource-directory-27&url2 …
=> sys/net/app/cord: update doc

examples/twr_aloha/control.c, sys/event/event.c, sys/include/event/callback.h, sys/include/event/periodic_callback.h, sys/net/application_layer/gcoap/gcoap.c
When an uninitialized event is added, we will dereference a NULL pointer.
It can then be a bit tricky to find out which event caused this - so add an assertion when queuing the event that a callback is set.
=> sys/event: add assertion that event has a handler

sys/posix/pthread/include/pthread_threading_attr.h, sys/posix/pthread/pthread_attr.c
This adds the missing `pthread_attr_setstack` and `pthread_attr_getstack` functions to the `posix-pthread wrappers`.
'pthread_attr_setstackaddr' and `pthread_attr_getstackaddr` are deprecated and it is recommended to use use `pthread_attr_getstack` and `pthread_attr_setstack` instead.
=> sys/posix/pthread: Add pthread_attr_getstack and pthread_attr_setstack

sys/include/net/nanocoap.h, tests/unittests/tests-nanocoap/tests-nanocoap.c
Before `coap_get_total_hdr_len()` did not take the extended TKL field (RFC 8974) into account. This fixes the issue.
```
$ make BOARD=native -C tests/unittests all test
[...]
main(): This is RIOT! (Version: 2024.10-devel-370-g00e25)
READY
s
START
.......................==83870==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
.....................................................................................................................................................................................................................==83870==WARNING: ASan is ignoring requested __asan_handle_no_return: stack type: default top: 0xffcd4000; bottom 0xedf02000; size: …
```
=> sys/net/nanocoap: fix coap_get_total_hdr_len()

CODING_CONVENTIONS.md
This makes an implicit agreement that code should include the headers is uses, no more and no less, explicit.
It also recommends using tooling (such as clangd) and adding IWUY pragma comments to aid those tools in common cases they otherwise would provide false positives.
Read the changed coding conventions and confirm that this is what we want to do.
None
=> CODING_CONVENTIONS.md: Add IWYU policy

examples/nanocoap_server/coap_handler.c, sys/include/net/nanocoap.h, sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/nanocoap.c
Before, handlers writing blockwise transfer assumed that the response header length will match the request header length. This is true for UDP, but not for TCP: The CoAP over TCP header contains a Len field, that gets extended for larger messages. Since the reply often is indeed larger than the request, this is indeed often the case for CoAP over TCP.
> [!NOTE]
> Right now, no CoAP over TCP implementation is upstream. However, getting rid of incorrect assumptions now will make life easier later on.
This will not change generated binaries, as right now the implementation just calls the same function that was used before. After all, for CoAP over UDP the assumption that request and response header match in size is valid.
Relevant for https://github.com/RIOT-OS/RIOT/pull/20900
=> sys/net/nanocoap: add and use coap_get_response_hdr_len()

sys/net/application_layer/nanocoap/sock.c
Our go-coap server sometimes responds with block 0 to a block2 request. This breaks SUIT updates.
An easy fix is to just try again when an unexpected block was received, we then get the expected block.
```
2024-11-05 17:26:32,695 # nanocoap: fetching block 29
2024-11-05 17:26:32,696 # nanocoap: send 20 bytes (4 tries left)
2024-11-05 17:26:32,712 # nanocoap: waiting for response (timeout: 1283696 µs)
2024-11-05 17:26:32,776 # nanocoap: response code=203
2024-11-05 17:26:32,777 # nanocoap got block 29 (offset 29696)
2024-11-05 17:26:32,777 # nanocoap: fetching block 30
2024-11-05 17:26:32,792 # nanocoap: send 20 bytes (4 tries left)
2024-11-05 17:26:32,795 # nanocoap: waiting for response (timeout: 1466309 µs)
2024-11-05 17:26:34,263 # nanocoap: timeout waiting for response
2024-11-05 …
```
=> nanocoap/sock: re-try if wrong block was received

pkg/u8g2/doc.txt
This simply adds the `u8g2` package to the displays doc group.
The pkg should show up in these two locations:
- [website drivers page](https://www.riot-os.org/drivers.html) (under the "Display Device Drivers" menu)
- [doxygen "Display Device Drivers" page](https://doc.riot-os.org/group__drivers__display.html)
- none known
=> pkg/u8g2: add to the displays doc group

core/include/mutex.h
Same as `mutex_init()` and complements `MUTEX_INIT` / `MUTEX_INIT_LOCKED` - I was surprised we did not have this yet.
=> core/mutex: add `mutex_init_locked()`

tests/sys/shell_lock/main.c, tests/sys/shell_lock/tests/01-run.py
Before the test used the `help` command to verify that access to the shell is present. While this does have the benefit of not requiring a custom command, it does have some robustness issues:
- When new default commands get added, this test will fail
- When the help message of a command gets reworded, the test will fail
- When the order of commands in the test will change, the test will fail
- Note that with the XFA based `SHELL_COMMAND()` macro, we do not guarantee any particular order. Specifically, the order can change with implementation details.
The test should pass.
https://github.com/RIOT-OS/RIOT/pull/20958 has shown that changing implementation details of `SHELL_COMMAND()` does affect the order of commands in the `help` list.
=> tests/sys/shell_lock: increase robustness of the test

tests/build_system/xfa/main.c, tests/build_system/xfa/tests/01-run.py, tests/build_system/xfa/xfatest.h, tests/build_system/xfa/xfatest1.c, tests/build_system/xfa/xfatest2.c
This increases the test coverage for XFA:
- Multiple entries are added from a single file
- Priorities are assigned to enforce a given order
- The size of the `struct` to add is changed to no longer be a power of 2
The test is automated and should pass in the CI. It will fail on `native64`, though.
None
=> tests/build_system/xfa: improve test coverage

.clang-format
This disables adding/removing line breaks by `clang-format`, as this could very well introduce regressions in code formatting in terms of our coding convention: If a long array was matching the soft limit of 80 chars per line, `clang-format` would reflow it to match the hard limit of 100 chars.
One can selectively disable `clang-format` with magic comments. But at this point, I'd say we should rather disable this feature until we can configure it in a way to match our coding convention better (without having to add magic comments).
With this PR, `clang-format` should not increase the column with above 80 chars anymore.
None
=> .clang-format: Set ColumnLimit to 0

cpu/cc2538/radio/cc2538_rf_radio_ops.c
Instead of using the length byte from a received packet (that might be corrupted), use the number of bytes in the RX FIFO to determine the location of the CRC OK bit.
Flashed this change on two CC2538s, started ping while under heavy Wi-Fi interference. In the case where the old `pkt_len` was not equal to the new `crc_loc`, the error from #20955 did not appear. Also, the reported `pkt_len` in this case is always `crc_loc + 128`, indicating that the receiver actually only uses the 7 LSBs from the length byte.
Fixes #20955.
=> cpu/cc2538: use RX FIFO count to determine CRC OK location

sys/include/net/nanocoap.h, sys/net/application_layer/gcoap/gcoap.c
gcoap contains a hack where a `coap_pkt_t` is pulled out of thin air, parts of the members are left uninitialized and a function is called on that mostly uninitialized data while crossing fingers hard that the result will be correct. (With the current implementation of the used function this hack does actually work.)
Estimated level of insanity: 😱😱😱😱😱
This adds to insane functions to get the length of a token and the length of a header of a CoAP packet while crossing fingers hard that the packet is valid and that the functions do not overread.
Estimated level of insanity: 😱😱😱
The newly introduced insane functions are used to replace the old insane hack, resulting in an estimated reduction of insanity of 😱😱.
> [!NOTE]
> This actually does fix a bug, as the old code did not take into …
=> sys/net/gcoap: reduce insanity of hack

boards/common/nrf52/Makefile.include, dist/tools/openocd/openocd.sh, makefiles/tools/openocd.inc.mk
With nRF52 silicon revision Fxx and newer, the behavior of the APPROTECT flash protection was changed. Previously it had to be activated manually and as long as it was not activated, the flash could be read from and written to without issues.
After the revision, the device is in a protected state after the first power cycle, making it impossible to read/write/modify the flash memory with an external debugger.
Furthermore, the device has to be unlocked (or in Nordic terms "recovered") explicitly. Unlike the term "recover" might suggest, the flash is erased during that "recovery".
The Segger J-Link does that recovery process implicitly, while OpenOCD has a dedicated `nrf52_recover` command for it which has to be called after the `init` command and before any other command.
This necessitated …
=> cpu/nRF52: Always recover Device before Flashing

boards/openmote-b/include/board.h
The board had the problem that the AT86RF215 radio would not come up, especially from cold boot.
Increasing the reset delay to 50ms appears to fix this issue for good.
Unplug the device, after plugging it in verify that the interface has come up:
```
2024-11-08 16:11:57,032 # Iface  6  HWaddr: 19:C4  Channel: 0  NID: 0x23  PHY: MR-O-QPSK 
2024-11-08 16:11:57,034 #            chip rate: 1000  rate mode: 2 
2024-11-08 16:11:57,036 #           Long HWaddr: AE:8D:FE:E1:60:ED:99:C4 
2024-11-08 16:11:57,048 #            TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
2024-11-08 16:11:57,052 #           AUTOACK  ACK_REQ  CSMA  L2-PDU:2022  MTU:1280  HL:64  6LO  
2024-11-08 16:11:57,054 #           Source address length: 8
2024-11-08 16:11:57,055 #           Link type: wireless …
```
=> boards/openmote-b: set at86rf215 reset pulse width to 50ms

sys/net/gnrc/netif/gnrc_netif.c
Return early to prevent freeing the same packet again.
=> gnrc_netif: fix double free with netdev_new_api & gnrc_netif_pktq

drivers/slipdev/slipdev.c
This appears to be required with `gnrc_netif_pktq` - it does not fix the memory leak though :confused: 
The `NETOPT_TX_END_IRQ not implemented by driver` warning is no longer being printed.
=> drivers/slipdev: implement NETDEV_EVENT_TX_COMPLETE event

makefiles/pseudomodules.inc.mk, sys/include/shell.h, sys/shell/shell.c, tests/rust_libs/Makefile, tests/rust_libs/tests/01-run.py
This adds the `cmds_json` builtin command that does the same as `help`, but provides a machine readable JSON rather than a human readable table. It is only provided when the (pseudo-)module `shell_json` is used.
This in turn is used in a second commit in `tests/rust_libs`. It would otherwise depend on the order in which shell commands are printed, which at least for XFA shell commands (as provided by rust) is not the case.
Green CI: The new builtin command is tested implicitly in `tests/rust_libs`.
Needed to get https://github.com/RIOT-OS/RIOT/pull/20958 passed.
=> sys/shell: cmds_json builtin command

sys/net/gnrc/netif/gnrc_netif.c
Return early to prevent freeing the same packet again.
=> gnrc_netif: fix double free with netdev_new_api & gnrc_netif_pktq [backport 2024.10]

sys/include/endian.h
picolibc defines those now, so add a guard to prevent conflicts. 
Build with
```
USEMODULE += picolibc
FEATURES_REQUIRED += picolibc
```
should work again.
=> sys/endian: fix build with picolibc

sys/usb/usbus/cdc/acm/cdc_acm_stdio.c
There seems to be some problem the implementation of stdio over usbus_cdc_acm where printing an empty string _sometimes_ leads to the next character being missed in the printout. I've managed to pin the problem down to the call to `usbus_cdc_acm_flush(&cdcacm);` in `sys/usb/usbus/cdc/acm/cdc_acm_stdio.c` and, more specifically, to `_ep_xmit` in `cpu/nrf5x_common/periph/usbdev.c`, but since I have no non-nRF hardware at hand, I cannot tell whether it is a nRF specific issue.
In any case, skipping the flushing (and submitting) in the first place seems to fix the issue for now. If anyone has an idea how to investigate this further and maybe fix the root cause somewhere deeper in the usb driver, please tell me, I'm happy to test more.
1. apply the following diff:
```diff
diff --git …
```
=> sys/usb_cdc_acm_stdio: only submit and flush for non-empty buffer

core/sched.c, tests/drivers/xbee/Makefile.ci
`_runqueue_pop()` calls `clist_lpop()`, which pops the leftmost entry in the thread's priority runqueue, but not necessarily the one passed as argument. 
I understand the original logic behind this: if a thread is to be removed, then it is so because it is about to block on something or exit. And a thread can only block or exit if it's currently running. As a result, it must be the leftmost entry on the runqueue. But this isn't always true. Consider `sched_change_priority()`, which does the following:
```c
if (thread_is_active(thread)) { 
_runqueue_pop(thread);
_runqueue_push(thread, priority);
}
```
`thread_is_active()` returns true if a thread is either running or queued to be running. So the `_runqueue_pop()` might retrieve any thread. Let's extend `_runqueue_pop()` with the following …
=> core/sched.c: fix _runqueue_pop() removing wrong thread

README.md
This PR replaces the section called 'Forum' with a more generic section on 'asking for help'. I couldn't find something similar at first glance in our documentation so it is likely helpful for newcomers to explicitly add this.
Read the update to the readme and check whether all the links added work.
None
=> README: Rephrase forum into more generic help

tests/sys/shell/Makefile
Boards using highlevel_stdio disconnect on reboot, thereby failing the automatic python tests. The functionality to disable reboot was already there. This PR just disables it automatically when the board has the `highlevel_stdio` FEATURE.
`make -C tests/sys/shell BOARD=feather-nrf52840-sense flash test`
fails on master, passes with this PR
Encountered while working on #20980
=> tests/sys/shell: skip reboot for boards using highlevel_stdio

tests/cpu/mpu_noexec_ram/Makefile, tests/cpu/mpu_stack_guard/Makefile
Boards using highlevel_stdio do no print on crash, but the two mpu tests check for this printout. This PR blacklists the feature for those tests.
`make -C tests/cpu/mpu_noexec_ram BOARD=feather-nrf52840-sense flash test`
and
`make -C tests/cpu/mpu_stack_guard BOARD=feather-nrf52840-sense flash test`
are now refused to be run
Encountered while working on #20980
=> tests/cpu/mpu*: exclude boards using highlevel_stdio

drivers/at86rf215/at86rf215_netdev.c, sys/net/gnrc/netif/gnrc_netif.c, sys/net/gnrc/netif/gnrc_netif_raw.c
With `netdev_new_api` packets are not released on send anymore.
`gnrc_netif_pktq` adds a hold on a packet to not release it on send.
Even though 1 + 1 - 1 - 1 should be 0, we are leaking packets on send.
Run a driver that makes use of both `netdev_new_api` and `gnrc_netif_pktq` (e.g. `at86rf215`):
```
2024-11-13 13:49:00,444 # ping -c 10 -s 1024 ff02::23%6
2024-11-13 13:49:08,446 # error: packet buffer full
2024-11-13 13:49:09,446 # error: packet buffer full
2024-11-13 13:49:10,443 # 
2024-11-13 13:49:10,446 # --- ff02::23%6 PING statistics ---
2024-11-13 13:49:10,452 # 10 packets transmitted, 0 packets received, 100% packet loss
```
<details><summary>pktbuf stats</summary>
```
2024-11-13 13:49:37,227 # packet buffer: first byte: 0x20001c28, last byte: 0x20002c28 (size: 4096)
2024-11-13 …
```
=> gnrc_netif: fix packet leak with gnrc_netif_pktq & netdev_new_api

cpu/sam0_common/sam0_eth/eth-netdev.c, drivers/include/net/netdev.h
- Missing l2 ACK should be `EHOSTUNREACH`
- Collision should be `EBUSY`
- stm32 eth already uses `ENETDOWN` for no link / sleep, document that
=> drivers/netdev: revise return values of `.confirm_send()`

sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
The basic idea is: all free data is filled with `CANARY` bytes, once data is allocated this is overwritten with `~CANARY`.
When data is freed we now check if the chunk is only set to `CANARY` - if this happens, it was already freed.
Set `CONFIG_GNRC_PKTBUF_CHECK_USE_AFTER_FREE` to `1`.
=> sys/net/gnrc_pktbuf_static: add double free detection

drivers/at86rf215/at86rf215_netdev.c, drivers/include/net/netdev.h, sys/net/gnrc/netif/gnrc_netif.c, sys/test_utils/netdev_ieee802154_minimal/netdev_ieee802154_minimal.c
- `netdev_new_api` implies a TX_COMPLETE event, so no need to check for it
- hide the legacy `TX_COMPLETE` events behind a `MODULE_NETDEV_LEGACY_API` check so they are not used by accident when porting a driver to the new API.
`NETOPT_TX_END_IRQ not implemented by driver` should go away with `netdev_new_api` once and for all - the TX_COMPLETE event is now mandated.
=> gnrc_netif: netdev_new_api implies TX end irq, no need to check it

drivers/at86rf215/at86rf215_netdev.c, sys/net/gnrc/netif/gnrc_netif.c, sys/net/gnrc/netif/gnrc_netif_raw.c
With `netdev_new_api` packets are not released on send anymore.
`gnrc_netif_pktq` adds a hold on a packet to not release it on send.
Even though 1 + 1 - 1 - 1 should be 0, we are leaking packets on send.
Run a driver that makes use of both `netdev_new_api` and `gnrc_netif_pktq` (e.g. `at86rf215`):
```
2024-11-13 13:49:00,444 # ping -c 10 -s 1024 ff02::23%6
2024-11-13 13:49:08,446 # error: packet buffer full
2024-11-13 13:49:09,446 # error: packet buffer full
2024-11-13 13:49:10,443 # 
2024-11-13 13:49:10,446 # --- ff02::23%6 PING statistics ---
2024-11-13 13:49:10,452 # 10 packets transmitted, 0 packets received, 100% packet loss
```
<details><summary>pktbuf stats</summary>
```
2024-11-13 13:49:37,227 # packet buffer: first byte: 0x20001c28, last byte: 0x20002c28 (size: 4096)
2024-11-13 …
```
=> gnrc_netif: fix packet leak with gnrc_netif_pktq & netdev_new_api [backport 2024.10]

cpu/sam0_common/periph/adc.c
This adds a delay between enabling the ADC and starting to sample on the SAMD5x MCUs when the internal bandgap reference is used.
Before, `adc_sample()` on one of the SAMD5x MCUs I have at hands got stuck when the internal bandgap reference was used by never leaving this loop:
```
0x00001660 in _sample (line=line@entry=0)
at /home/marian.buschsieweke@ml-pa.loc/Repos/software/ML-PA-RIOT/cpu/sam0_common/periph/adc.c:489
489     while (!(dev->INTFLAG.reg & ADC_INTFLAG_RESRDY)) {}
```
Now, it works also on the "special" MCU that got stuck before:
```
> saul read 0
2024-11-14 22:14:45,179 # saul read 0
2024-11-14 22:14:45,180 # Reading from #0 (vol|SENSE_ANALOG)
2024-11-14 22:14:45,180 # Data:	          2122 
> saul read 1
2024-11-14 22:14:47,434 # saul read 1
2024-11-14 22:14:47,451 # Reading …
```
=> cpu/sam0_common/periph_adc: add work around for errata 2.1.6

sys/include/net/gnrc/pkt.h, sys/net/gnrc/netapi/gnrc_netapi.c, sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c, sys/net/gnrc/pktbuf_malloc/gnrc_pktbuf_malloc.c, sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c, tests/unittests/tests-pktbuf/tests-pktbuf.c, tests/unittests/tests-pktqueue/tests-pktqueue.c, tests/unittests/tests-priority_pktqueue/tests-priority_pktqueue.c
It's very unlikely that a pkt snip will have more than 255 users. Use a `uint8_t` here to save 4 bytes per snip as this now fits into the unused struct padding. 
`sizeof(gnrc_pktsnip_t) == 20`
`sizeof(gnrc_pktsnip_t) == 12`
=> sys/net/gnrc/pkt: use `uint8_t` for user count

cpu/cc2538/include/cc2538_rf.h, cpu/cc2538/radio/cc2538_rf_radio_ops.c
This is a follow-up for #20956.
I found that the solution applied there wasn’t robust, because when receiving short packets quickly after each other the RX FIFO might be filling up with a new packet while handling the IRQ. Then, the number of bytes in the FIFO will be bigger than the packet length of the first packet. Even though the second packet will be dropped anyway, the length of the first packet can still be correctly obtained from the length byte in the packet.
Namely, from section 23.9.5.1 of the CC2538 User’s Guide it follows that indeed the radio will mask out bit 7 of the length byte:
Then, it continues to fill the RX FIFO with this number of bytes as follows from section 23.9.3:
This means that with this approach, always the correct byte is used for checking the CRC result. …
=> cpu/cc2538: mask length byte before checking CRC

sys/usb/usbus/cdc/acm/cdc_acm_stdio.c
There seems to be some problem the implementation of stdio over usbus_cdc_acm where printing an empty string _sometimes_ leads to the next character being missed in the printout. I've managed to pin the problem down to the call to `usbus_cdc_acm_flush(&cdcacm);` in `sys/usb/usbus/cdc/acm/cdc_acm_stdio.c` and, more specifically, to `_ep_xmit` in `cpu/nrf5x_common/periph/usbdev.c`, but since I have no non-nRF hardware at hand, I cannot tell whether it is a nRF specific issue.
In any case, skipping the flushing (and submitting) in the first place seems to fix the issue for now. If anyone has an idea how to investigate this further and maybe fix the root cause somewhere deeper in the usb driver, please tell me, I'm happy to test more.
1. apply the following diff:
```diff
diff --git …
```
=> sys/usb_cdc_acm_stdio: only submit and flush for non-empty buffer [backport 2024.10]

cpu/sam0_common/include/gpio_ll_arch.h, cpu/sam0_common/periph/gpio_ll.c
It turns out that the legacy GPIO API and GPIO LL may disagree on what the GPIO base address is: GPIO LL will use the IOBUS as base address no matter what, the legacy GPIO API will use the APB as base address unless `periph_gpio_fast_read` is used.
If the APIs disagree, we need to do impedance matching.
For the other MCUs, we take the input register state instead of the output register state when the pin is configured as input. Let's do the same here, as this is a lot more useful and intuitive.
`gpio_query_conf(gpio_get_port(GPIO_PIN(PA, 1)), gpio_get_pin_num(GPIO_PIN(PA, 1));` should no longer run into a blown assertion.
None
=> cpu/sam0_common/periph_gpio_ll: fix gpio_get_port() and gpio_ll_query_conf()

cpu/sam0_common/periph/adc.c
This adds a delay between enabling the ADC and starting to sample on the SAMD5x MCUs when the internal bandgap reference is used.
Before, `adc_sample()` on one of the SAMD5x MCUs I have at hands got stuck when the internal bandgap reference was used by never leaving this loop:
```
0x00001660 in _sample (line=line@entry=0)
at /home/marian.buschsieweke@ml-pa.loc/Repos/software/ML-PA-RIOT/cpu/sam0_common/periph/adc.c:489
489     while (!(dev->INTFLAG.reg & ADC_INTFLAG_RESRDY)) {}
```
Now, it works also on the "special" MCU that got stuck before:
```
> saul read 0
2024-11-14 22:14:45,179 # saul read 0
2024-11-14 22:14:45,180 # Reading from #0 (vol|SENSE_ANALOG)
2024-11-14 22:14:45,180 # Data:	          2122 
> saul read 1
2024-11-14 22:14:47,434 # saul read 1
2024-11-14 22:14:47,451 # Reading …
```
=> cpu/sam0_common/periph_adc: add work around for errata 2.1.6 [backport 2024.10]

cpu/sam0_common/include/gpio_ll_arch.h, cpu/sam0_common/periph/gpio_ll.c
It turns out that the legacy GPIO API and GPIO LL may disagree on what the GPIO base address is: GPIO LL will use the IOBUS as base address no matter what, the legacy GPIO API will use the APB as base address unless `periph_gpio_fast_read` is used.
If the APIs disagree, we need to do impedance matching.
For the other MCUs, we take the input register state instead of the output register state when the pin is configured as input. Let's do the same here, as this is a lot more useful and intuitive.
`gpio_query_conf(gpio_get_port(GPIO_PIN(PA, 1)), gpio_get_pin_num(GPIO_PIN(PA, 1));` should no longer run into a blown assertion.
None
=> cpu/sam0_common/periph_gpio_ll: fix gpio_get_port() and gpio_ll_query_conf() [backport 2024.10]

boards/common/arduino-zero/include/arduino_iomap.h, boards/wemos-zero/doc.txt
Two pins were incorrectly mapped: D2 and D4 are swapped compared to the official Arduino Zero. In addition the is slightly extended.
None
=> boards/wemos-zero: fix Arduio I/O Map

sys/include/net/gnrc/pktbuf.h, sys/net/gnrc/pktbuf/gnrc_pktbuf.c, sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
When debugging #20983 this was quite useful to find the issue where a pointer to a pktsnip that was already freed was being held.
For the `!CONFIG_GNRC_PKTBUF_CHECK_USE_AFTER_FREE` this is already caught by the `assert(pkt->users > 0)`, so if we turn on more extensive leak detection, don't degrade this case.
=> sys/net/gnrc_pktbuf: detect use after free if canary is in metadata

tests/periph/uart/main.c
The UART self-test using a TX-RX-loop fails on `master`. Luckily it's not a bug in the UART driver, but just a timing issue between `uart_write` returning and the HW triggering the RX callback. This PR fixes the test by adding a 1ms delay between TX and RX buffer check.
While at it, I also improved the error handling and reporting in the test.
`make -C tests/periph/uart BOARD=nrf52840dk flash term`, then `test 1` fails on `master` and succeeds with these changes.
Encountered while testing for #20980
=> tests/periph/uart: minor improvements

cpu/stm32/periph/timer.c
This patch hardens the STM32 timer driver against some possible causes of spurious IRQs.
I did not actually observe spurious IRQs happening, but this PR comes as the result of a deep dive into the timer code to solve the bug in #20924. This PR is a defensive measure only.
Timers should continue to work.
- #20924
- #20925
=> cpu/stm32/periph/timer: prevent spurious IRQs

boards/stm32f429i-disc1/include/board.h
This patch fixes a missmatch between the LCD and touch drivers' coordinate systems.
Build and flash with `make -C tests/pkg/lvgl_touch/ flash`, and observe the test works as intended with this patch, but not without it.
none known
=> boards/stm32f429i-disc1: fix touch screen axis

cpu/sam0_common/periph/eth.c, cpu/sam0_common/sam0_eth/eth-netdev.c, drivers/include/net/netdev.h, pkg/lwip/contrib/netdev/lwip_netdev.c, sys/net/gnrc/netif/gnrc_netif.c
The new netdev API makes implementing drivers where `.send` is inherently synchronous (slip, dose, ethos) kind of awkward. They need to memorize the frame size, generate an event, and return the frame size in `.confirm_send` to signal completion.
However, the new netdev API does not use `.send` return values that are > 0. We can use those to signal that send is complete already and no further action is needed.
This makes writing and understanding synchronos drivers much easier, the code changes to support this in GNRC and LWIP are minimal. 
You can test with SLIP with is now trivial to convert:
<details><summary>slip.patch</summary>
```patch
--- a/drivers/slipdev/Makefile.dep
+++ b/drivers/slipdev/Makefile.dep
@@ -1,6 +1,6 @@
USEMODULE += chunked_ringbuffer
USEMODULE += eui_provider …
```
=> netdev_new_api: allow `.send()` to return > 0 to signal synchronos send

tests/periph/selftest_shield/Makefile, tests/periph/selftest_shield/main.c
Calling `timer_init()` with unsupported frequencies on some MCUs just selects the closest possible frequency. But e.g. on SAM0, using an unsupported frequency will cause `timer_init()` to fail; which probably is the better option.
However, a failing calling to `timer_init()` results in a test failure. This is now worked around by using timer_query_freq() to select a suitable timer frequency that is supported.
The GPIO IRQ tests had a side-effect that IRQs remained configured after the test case was complete. This caused stray IRQs to trigger on SAM0 MCUs and they consequently (and incorrectly) failed the test.
On e.g. `wemos-zero` or `arduino-zero` the test should now run to completion and - with the exception of the ADC tests - pass.
In `master` GPIO IRQ tests will fail and the test will …
=> tests/periph/selftest_shield: fix invalid calls to timer_init() + GPIO IRQ tests

drivers/dose/Makefile.dep, drivers/dose/dose.c
As we already implement `NETDEV_EVENT_TX_COMPLETE` we only need to provide `.confirm_send` 
*This is still untested*
=> drivers/dose: port to netdev_new_api

boards/stm32f429i-disc1/include/board.h
This patch fixes a missmatch between the LCD and touch drivers' coordinate systems.
Build and flash with `make -C tests/pkg/lvgl_touch/ flash`, and observe the test works as intended with this patch, but not without it.
none known
=> boards/stm32f429i-disc1: fix touch screen axis [backport 2024.10]

drivers/slipdev/Makefile.dep, drivers/slipdev/slipdev.c
Not sure how much sense this makes, since send is still blocking.
I mainly did this to reduce the number of code paths with `at86rf215` in the border router use case.
=> drivers/slipdev: port to netdev_new_api

drivers/ethos/Makefile.dep, drivers/ethos/ethos.c
The driver already does everything required by `netdev_new_api`, we only need to provide a dummy `confirm_send` to signal that it's conformant.
=> drivers/ethos: port to netdev_new_api

boards/adafruit-grand-central-m4-express/Makefile.include
With `MOST_RECENT_PORT=1`, detect the board correctly also when running the default bootloader and not a RIOT app flashed on it.
Double-tap the reset button to enter bootloader mode. Then run
```
make BOARD=adafruit-grand-central-m4-express -C examples/default flash term
```
It would fail in `master` due to no TTY being detected, but succeed with this PR.
None
=> boards/adafruit-grand-central-m4-express: improve TTY detection

boards/feather-nrf52840/Makefile.dep, boards/feather-nrf52840/include/board.h
Adds the NeoPixel LED config for the Adafruit nRF52840 Express (its the same as for the Sense).
Flash, e.g., the `examples/saul` app to a `feather-nrf52840`. The on-board RGB-LED should be controllable by the app.
Exposed while testing #20996.
=> feather-nrf52840: add config for NeoPixel LED

doc/doxygen/src/porting-boards.md, tests/sys/ztimer_overhead/README.md, tests/sys/ztimer_overhead/main.c
Since #17633, there is an alternative to configuring the ztimer overhead compensation in the board.h file. Mention this in the relevant places in the documentation and the test application.
While we are at it, also fixing a typo in the test application.
Check generated doc and changes to README.
Stumbled upon this while going through https://doc.riot-os.org/porting-boards.html#board-timer-configurations for #20980. Interesting enough that this configuration values are currently only set for a handful of boards :eyes:
=> sys/ztimer: mention ztimer_auto_adjust in relevant places

tests/periph/pm/main.c
That the PM mode just gets unblocked without any output is rather confusing. Add a small printout to the alarm to make it clear that we just woke up.
```
2024-11-21 14:55:08,216 # > unblock_rtc 2 5
2024-11-21 14:55:08,219 # Unblocking power mode 2 for 5 seconds.
2024-11-21 14:55:13,567 # RTC alarm
```
=> tests/periph/pm: print some output on alarm

drivers/periph_common/init.c
We want to initialize the watchdog early so it can detect a hang in later init functions.
I flashed `examples/gnrc_networking` with `periph_wdt_auto_start` on `same54-xpro`.
We still reach `main()` (and reset a bit after that because I didn't service the watchdog)
```
2024-11-21 16:34:40,149 # main(): This is RIOT! (Version: 2025.01-devel-150-g220d10-drivers/wdt-early_init)
2024-11-21 16:34:40,152 # RIOT network stack example application
2024-11-21 16:34:40,155 # All up, running the shell now
> 
```
=> drivers/periph_init: initialize watchdog first

drivers/atwinc15x0/Makefile.dep, drivers/atwinc15x0/atwinc15x0_netdev.c
While `atwinc15x0` is a real radio that would benefit from async send, the driver wraps a package that exposes a very high level synchronous send API.
This however makes porting the device to the `netdev_new_api` trivial.
=> drivers/atwinc15x0: port to `netdev_new_api`

sys/usb/usbus/Makefile.dep, sys/usb/usbus/cdc/ecm/cdc_ecm_netdev.c
The driver implements a blocking send interface, so the port is trivial. 
Ping still works
```
2024-11-21 19:13:46,298 # ping ff02::1
2024-11-21 19:13:46,305 # 12 bytes from fe80::eb2f:25e2:a25c:77d2%4: icmp_seq=0 ttl=64 time=0.522 ms
2024-11-21 19:13:47,305 # 12 bytes from fe80::eb2f:25e2:a25c:77d2%4: icmp_seq=1 ttl=64 time=0.615 ms
2024-11-21 19:13:48,305 # 12 bytes from fe80::eb2f:25e2:a25c:77d2%4: icmp_seq=2 ttl=64 time=0.737 ms
2024-11-21 19:13:48,306 # 
2024-11-21 19:13:48,308 # --- ff02::1 PING statistics ---
2024-11-21 19:13:48,313 # 3 packets transmitted, 3 packets received, 0% packet loss
2024-11-21 19:13:48,317 # round-trip min/avg/max = 0.522/0.624/0.737 ms
```
=> usbus/cdc_ecm: port to netdev_new_api

cpu/native/Makefile.dep, cpu/native/netdev_tap/netdev_tap.c
`netdev_tap` uses synchronous send, so we can trivially port it to the (relaxed) new netdev API.
depends on #21012
=> netdev_tap: port to `netdev_new_api`

examples/rust-async/Cargo.lock, examples/rust-gcoap/Cargo.lock, examples/rust-hello-world/Cargo.lock, sys/include/shell.h, sys/rust_riotmodules_standalone/Cargo.lock, sys/shell/shell.c, tests/rust_minimal/Cargo.lock
We do not need to add an array of pointers to the shell commands, just an array of shell commands is sufficient. This reduced the overhead of XFA by `sizeof(void *)` per command.
```
$ make BOARD=arduino-uno flash term -C examples/default
[...]
2024-11-06 18:27:11,666 # main(): This is RIOT! (Version: 2024.10-devel-388-gf4b2ef-sys/shell/xfa-reduce-overhead)
2024-11-06 18:27:11,686 # Welcome to RIOT!
help
2024-11-06 18:27:25,324 # help
2024-11-06 18:27:25,361 # Command              Description
2024-11-06 18:27:25,402 # ---------------------------------------
2024-11-06 18:27:25,459 # pm                   interact with layered PM subsystem
2024-11-06 18:27:25,525 # ps                   Prints information about running threads.
2024-11-06 18:27:25,594 # saul                 interact with …
```
=> sys/shell: reduce overhead of XFA shell commands

drivers/at86rf215/at86rf215.c, drivers/at86rf215/at86rf215_netdev.c, sys/net/gnrc/netif/gnrc_netif.c, tests/net/nanocoap_cli/nanocli_client.c
We would return EBUSY when the interface was in sleep, this caused the gnrc_netif to retry sending forever. Return ENETDOWN instead.
I added three additional minor fixes to this to not bother CI with those trivial changes:
- better error messages in `gnrc_netif` to tell apart the case where a pkt can't be queued and is dropped and where we try sending it instead
- wrong rx buffer size in the nanocoap_cli test
- overwriting `tx_frame_len` that has already been set in `at86rf215_tx_load()`
=> drivers/at86rf215: return ENETDOWN when interface is down

pkg/wakaama/contrib/lwm2m_client.c, pkg/wakaama/contrib/lwm2m_client_connection.c, pkg/wakaama/contrib/objects/ipso_sensor_base.c, pkg/wakaama/contrib/objects/light_control.c, pkg/wakaama/include/objects/common.h
#20930 updated the Wakaama package version. This version had some breaking changes. It seems that a change in `lwm2m_uri_t` slipped through. This fixes its usages throughout the contrib code.
EDIT:
I added a fix for a typo introduced in ISPO sensor base.
The best test would be an example that uses some of the IPSO objects, because there the URIs are manipulated. But there's currently no example with them. You can check the upstream type definitions:
https://github.com/eclipse-wakaama/wakaama/blob/d28bd1411413e7978269dcdb538f0cee3d3c82ec/include/liblwm2m.h#L329-L348
#20930
=> pkg/wakaama: Fix usages of `lwm2m_uri_t` and ISPO sensor

pkg/wakaama/contrib/lwm2m_client_connection.c
When a DTLS handshake fails, tinyDTLS keeps the session slot as used, and then it will fail on the next attempt unless the session is destroyed. This PR adds this behaviour to the lwm2m client.
With `examples/lwm2m`, you can test by starting the client before the server, making it fail the initial handshake attempt.
None
=> pkg/wakaama/client_connection: destroy unused DTLS sessions

sys/evtimer/evtimer.c
Evtimer function `_evtimer_handler`  comment updated to `ztimer` because `xtimer` is no longer used in evtimer.
=> sys/evtimer/evtimer.c: change comment from xtimer to ztimer

drivers/at86rf215/at86rf215.c, drivers/at86rf215/at86rf215_netdev.c, sys/net/gnrc/netif/gnrc_netif.c, tests/net/nanocoap_cli/nanocli_client.c
We would return EBUSY when the interface was in sleep, this caused the gnrc_netif to retry sending forever. Return ENETDOWN instead.
I added three additional minor fixes to this to not bother CI with those trivial changes:
- better error messages in `gnrc_netif` to tell apart the case where a pkt can't be queued and is dropped and where we try sending it instead
- wrong rx buffer size in the nanocoap_cli test
- overwriting `tx_frame_len` that has already been set in `at86rf215_tx_load()`
=> drivers/at86rf215: return ENETDOWN when interface is down [backport 2024.10]

cpu/cc2538/include/cc2538_rf.h, cpu/cc2538/radio/cc2538_rf_radio_ops.c
This is a follow-up for #20956.
I found that the solution applied there wasn’t robust, because when receiving short packets quickly after each other the RX FIFO might be filling up with a new packet while handling the IRQ. Then, the number of bytes in the FIFO will be bigger than the packet length of the first packet. Even though the second packet will be dropped anyway, the length of the first packet can still be correctly obtained from the length byte in the packet.
Namely, from section 23.9.5.1 of the CC2538 User’s Guide it follows that indeed the radio will mask out bit 7 of the length byte:
Then, it continues to fill the RX FIFO with this number of bytes as follows from section 23.9.3:
This means that with this approach, always the correct byte is used for checking the CRC result. …
=> cpu/cc2538: mask length byte before checking CRC [backport 2024.10]

tests/sys/events/main.c
This change edits the /sys/events/ test to test if `event_timeout_is_pending` returns false when `event_timeout_t ` is not completely  initialized. Meaning when `event_timeout_t ->queue`, `event_timeout_t ->clock` or `event_timeout_t ->event`  is NULL `event_timeout_is_pending` should return false.
This was previously not tested.
`BOARD=native make -C tests/sys/events flash test`
=> tests/sys/events: test if event_timeout_is_pending returns false

.vscode/settings.json, boards/nrf52840dk/include/arduino_iomap.h, examples/arduino_hello-world/Makefile, examples/arduino_hello-world/hello-world.sketch
Some minor fixes and enhancements for working with Arduino sketches in RIOT.
Check that diff makes sense, should be no code breaking changes.
Some feedback on the explicit `stdin` would be nice. The semantics of this pseudomodule do not seem to be defined anywhere explicitly. Maybe @benpicco has some insights?
Encountered while working on #20980
=> Arduino support layer: several fixes

tests/core/cond_order/main.c
Through test coverage, I noticed the test never tried the functions `cond_signal` and `cond_broadcast` without a thread waiting. This change helps to find problems with the functions when no thread is waiting.
`BOARD=native make -C tests/core/cond_order flash test`
check test coverage before and after (I used [simple coverage of thread communication](https://github.com/JulianHolzwarth/RIOT_coverage))
=> tests/core/cond_order/: calling cond signal and broadcast without waiting threads

sys/stdio/stdio.c
If I understand the purpose of the pseudomodule `stdin` correctly, it should describe the fact that the user wants to read from the stdio. If not selected, `stdio_available` (which returns the number of bytes available to be read) should thus always return zero.
Wait for @benpicco's take on this. Check for regressions via CI.
Encountered while working on #21039.
=> sys/stdio: stdio_available is always false with missing stdin module

tests/core/thread_msg/main.c
For some reason, the threads are (seemingly?) scheduled differently on `nrf52840dk` and `feather-nrf52840-sense`, at least the output order is not consistent. This PR changes the child threads to have a lower priority than the main thread so that "THREADS STARTED" is always printed first.
`make -C tests/core/thread_msg BOARD=feather-nrf52840-sense flash test`
fails on master, passes with this PR
Encountered while working on #20980
=> tests/core/thread_msg: lower thread priority for consistent output order

boards/adafruit-metro-m4-express/Makefile.features, boards/adafruit-metro-m4-express/Makefile.include, boards/adafruit-metro-m4-express/include/arduino_iomap.h
This PR contains two commits with one minor improvement each:
- The I2C and UART Arduino Mapping is provided
- The TTY detection now also can detect the board when the bootloader is running (which registers using the bootloader's USB vendor ID and model, rather than the RIOT variant)
Both already tested using https://github.com/RIOT-OS/RIOT/pull/21029
It would be possible to do so now by:
- Adding the peripheral self-test shield and run the corresponding test (but UART and SPI are mutually exclusive due to lack of time-sharing for SERCOMs)
- double pressing the reset button (to enter bootloader mode) and run `make BOARD=adafruit-metro-m4-express MOST_RECENT_PORT=1 -C examples/default flash`. This does now work, but fails in `master`
Split out of https://github.com/RIOT-OS/RIOT/pull/21029
=> boards/adafruit-metro-m4-express: Minor improvements

cpu/cortexm_common/include/cpu.h, cpu/esp32/periph/gpio_ll.c, cpu/gd32v/periph/gpio_ll.c, cpu/nrf5x_common/periph/gpio_ll.c, cpu/sam0_common/periph/gpio_ll.c, cpu/stm32/periph/gpio_ll.c, drivers/periph_common/gpio_ll.c, examples/pio_blink/main.c, pkg/openwsn/include/openwsn_log.h
1. drop `#include <stdio.h>` from `cpu.h`. This clearly should not belong here
- This causes some fallout, as some code relied on `cpu.h` including `<stdio.h>`. Those missing includes are added first to ease bisecting
2. Add IWYU pragma export to `cpu_conf.h`, as portable code is expected to not include `cpu_conf.h` directly (which does not exist across MCU families), but indirectly via `cpu.h`
Green CI
Split out of https://github.com/RIOT-OS/RIOT/pull/21029
=> cpu/cortexm_common: Make cpu.h IWYU clean

tests/sys/shell/Makefile, tests/sys/shell/tests/01-run.py
This changes the behavior of the test script for verifying the `help` command: It no longer assumes a specific order for the list of commands.
Making the test robust is a bit tricky, as the module `shell_cmds_default` that is used here may add commands specific to a set of board. We use `help_json` to get the list of commands actually provided, so that we know how many rows the command table printed by `help` need to be parsed.
A minimum set of commands that *must* be present for all boards is hard-coded in the test script and the actually provided commands are tested against this. Otherwise e.g. an empty list of commands presented by `help` and `help_json` would also pass.
<details><summary><code>make BOARD=samr21-xpro -C tests/sys/shell flash test</code></summary>
```
make: Entering …
```
=> tests/sys/shell: make test script more robust

sys/include/stdio_base.h, sys/stdio/stdio.c
This PR introduces a new pseudomodule. It is currently only implemented for `stdio_uart`.
The use case is to clear the input buffer so we can throw away the remaining input (like `\n` for example) after a call of `scanf` for the next call of `scanf`.
Have an application with multiple calls of `scanf` and use `stdio_flush_rx` at some places and don't use it on others.
=> sys/stdio_uart: add stdio_clear_stdin

core/include/msg.h, core/msg.c, tests/core/msg_queue_print/Makefile, tests/core/msg_queue_print/main.c, tests/core/msg_queue_print/tests/01-run.py
highlevel_stdio such as usb-cdc-acm seems to require IRQs to be enabled for printing, but `msg_queue_print()` currently prints with IRQs disabled. This PR fixes that by copying the message queue information to the stack before re-enabling IRQs.
`make -C tests/core/msg_queue_print BOARD=feather-nrf52840-sense flash test`
hangs on `master`, passes with this PR
Changes tested on  `native` and `seeedstudio-xiao-nrf52840`.
Encountered while testing for #20980.
=> core/msg: re-enable IRQs before printing for highlevel_stdio

boards/common/particle-mesh/Makefile.dep, boards/common/particle-mesh/Makefile.features, boards/common/particle-mesh/bat_voltage.c, boards/common/particle-mesh/include/bat_voltage_params.h, boards/feather-nrf52840-sense/Makefile.dep, boards/feather-nrf52840-sense/Makefile.features, boards/feather-nrf52840-sense/bat_voltage.c, boards/feather-nrf52840-sense/include/bat_voltage_params.h, boards/feather-nrf52840/Makefile.dep, boards/feather-nrf52840/Makefile.features, boards/feather-nrf52840/bat_voltage.c, boards/feather-nrf52840/include/bat_voltage_params.h, boards/particle-argon/doc.txt, boards/particle-boron/doc.txt, dist/tools/features_yaml2mx/features_yaml2mx.py, drivers/Makefile.dep, drivers/include/saul/bat_voltage.h, drivers/saul/Makefile, drivers/saul/bat_voltage_saul.c, drivers/saul/init_devs/auto_init_saul_bat_voltage.c, drivers/saul/init_devs/init.c, features.yaml, makefiles/features_existing.inc.mk, makefiles/pseudomodules.inc.mk
This exposes the battery measuring capabilities for feather-like boards (see, e.g., https://learn.adafruit.com/introducing-the-adafruit-nrf52840-feather/power-management-2#measuring-battery-3122383) into SAUL so that the output value is the voltage and provides support for ~~4~~ 7 boards:
- feather-nrf52840-sense ( :white_check_mark: tested )
- feather-nrf52840 ( :white_check_mark: tested )
- particle-xenon ( :white_check_mark: tested )
- particle-argon ( :red_square: not tested, don't own the board )
- ~~feather-m0, as well as its derivates, `feather-m0-lora` and `feather-m0-wifi`, ( :yellow_square: tested, but not working as expected[^1] )~~, see https://github.com/RIOT-OS/RIOT/pull/21018#issuecomment-2491210025
[^1]: not sure if the board I used for testing is broken. It used to work 5 …
=> saul: initial import of saul_bat_voltage module

Makefile.dep, makefiles/defaultmodules_deps.inc.mk, tests/build_system/external_module_dirs/README.md, tests/build_system/external_module_dirs/external_modules/external_module/Makefile.dep, tests/build_system/external_module_dirs/external_modules/transitive/Makefile, tests/build_system/external_module_dirs/external_modules/transitive/Makefile.dep
The PRNG is supposed to be set only if there is none selected at the end of the recursive dependency resolution. However, this is currently not the case: a transitive dependency setting the PRNG (encountered with `psa_crypto` which selects `prng_sha256prng`) will lead to a user-facing dependency clash.
The first commit extends `tests/build_system/external_module` to showcase the issue and the second one fixes it by moving the automatic prng selection to `defaultmodules_deps.inc.mk`.
Disclaimer: I'm not sure if this is the right approach to follow, but it seems to work. Any suggestions from people with more insights on the build system are welcome.
with only the first commit:
```
$ make -C tests/build_system/external_module_dirs info-modules
make: Entering directory …
```
=> makefiles: select default prng _after_ recursive dependency resolution

README.md
Add related projects, advertise Ariel OS
=> README.md: add refrences to related projects

tests/sys/shell/Makefile
`tests/sys/shell` currently per default uses `socat` as terminal, according to the comment to avoid having extra characters put into the IO by the terminal program. But that's exactly what `make cleanterm` is for, which is already used per default by the python testrunner.
I encountered issues with `socat` for this test (newlines not properly matched against) on boards that use `usb_cdc_acm` as stdio, while the approach with `cleanterm` works as expected.
Run the test with some boards using `make -C tests/sys/shell BOARD=xxx flash test`. Successfully tested with `native`, `nrf52840dk` and `feather-nrf52840-sense`.
The commit https://github.com/RIOT-OS/RIOT/pull/11004/commits/cdfece682f5c38d399ba44b8ee162b67f80bcdd8 that introduced the change was merged one and a half months before the …
=> tests/sys/shell: use default terminal instead of socat

README.md
In the related projects, one project name was formatted as bold, while the others were not. This removes the bold formatting from "Ariel OS", so that it matches the formatting of the other project names.
The README.md should now be consistent.
Inconsistent formatting introduced in: https://github.com/RIOT-OS/RIOT/pull/21052
=> README.md: Fix inconsistent formatting

doc/doxygen/src/release-cycle.md, doc/guides/managing-a-release/README.md
This moves the “Managing a Release” guide from the wiki into master.
Read https://github.com/RIOT-OS/RIOT/blob/6ada8b4f6a61dcf5b9875066a3e4696d2da7900c/doc/guides/managing-a-release/README.md
None
=> doc: move "managing a release" from wiki

cpu/stm32/include/periph/cpu_eth.h
This PR fixes and improves some ETH defines from [cpu_eth.h](https://github.com/RIOT-OS/RIOT/blob/master/cpu/stm32/include/periph/cpu_eth.h):
- RX_DESC_STAT_ES  (line 99) - wrong bit number - see reference manual, page 1812,
- TX_DESC_STAT_CIC... (line 143) - some improvements from @maribu, [see PR #19952](https://github.com/RIOT-OS/RIOT/pull/19952#issuecomment-1738733909).
I tested this change in `nucleo-f439zi` and `nucleo-f207zg` - and after change they works.
Check once again reference manual and used bits.
PR #19952
=> cpu/stm32/eth: fix and improve ETH defines

drivers/sx126x/include/sx126x_params.h
To be able to use multiple sx126x connected to one mcu.
=> drivers/sx126x: add #ifndef for SX126X_PARAMS

sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/sock.c
When module `nanocoap_server_separate` is not used, the functions to send separate responses are still provided, just in a broken version: They will send the separate replies from a different endpoint than the request was received at (even on machines with only one IP address, as also the source port is randomized).
This changes the behavior to only provide the functions for separate response when the do work, so that others will detect an invalid configuration at compile time rather than at run time.
The documentation is duly updated.
```
$ make BOARD=same54-xpro flash term -C examples/nanocoap_server
[...]
2024-12-12 10:30:46,488 # {"IPv6 addresses": ["fe80::fec2:3dff:fe0b:cf49"]}
2024-12-12 10:30:49,421 # _separate_handler(): send ACK, schedule response
2024-12-12 10:30:50,425 # …
```
=> sys/net/nanocoap: Fix sending bogus separate responses

drivers/ws281x/esp32.c
Minor change to the `WS281x` driver, specifically the `esp32` side.
The `ws281x` driver for the `esp32` uses a hardware module called the `RMT`, which generates the data signal that the `ws281x`s expect. The `RMT` module is supplied with the information about how to generate this signal; for a `1` symbol, how long should the signal be held high, how long should it be low, so on. These `1` and `0` symbol high/low times are recalculated at every `RMT` write. 
This PR does the calculation once at init. Marginal speed up (~10us on my 80 neopixel strip).
If there was a reason for doing it at every write, it was not obvious to me. Please let me know if so.
=> drivers/ws281x: esp32 neopixel driver to set the rmt symbol high/low lengths at init instead of every write

README.md
This PR removes the Subsection Related Projects in favor of adding the Subsection Collaboration in the Section Community.  The content of the new subsection conveys a more generic message. It gives an example by referring to Ariel.
This PR is the outcome of discussions in PR #21063.
=> README.md: add Section Collaboration

drivers/dose/dose.c
If there's no state transition within the driver, powering off (STANDBY, SLEEP) a DOSE interface might result in a deadlock. Specifically, `wait_for_state()` will block forever.
Note, there is (and always was) a race condition here, i.e. even if we observed the state IDLE, this might transition to RECEIVE at any time. However, this case is covered by improvements in the chunked buffer implementation (see depencencies below).
Tested this on a SAME54 board.
=> drivers/dose: fix poweroff

sys/include/chunked_ringbuffer.h, tests/unittests/tests-chunked_ringbuffer/tests-chunked_ringbuffer.c
If there is a non-finished chunk in the ringbuffer when a new one is started, discard the stale chunk first. 
The unit test is expanded to cover this case.
=> sys/chunked_ringbuffer: discard stale chunk when starting a new one

examples/nanocoap_server/coap_handler.c, sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/sock.c, tests/net/nanocoap_cli/Makefile, tests/net/nanocoap_cli/nanocli_client.c
When RFC 8974 support (module `nanocoap_token_ext`) is in use, the request token may be longer than the buffer in the separate response context is large. This adds a check to not overflow the buffer.
Sadly, this is an API change: Preparing the separate response context can actually fail, so we need to report this with a return value.
The example application has been adapted to only proceed if the separate reply context could have been prepared, and rather directly emit a reset message if the token exceeds the static buffer.
This requires a client from `master`, as extending the test to allow specifying the token is not backported.
```
$  sudo ./dist/tools/tapsetup/tapsetup 
```
This should be done with `2024.10-branch` and this PR
```
$ USEMODULE=nanocoap_token_ext make BOARD=native64 -C …
```
=> sys/net/nanocoap: fix buffer overflow in separate response handling [backport 2024.10]

cpu/sam0_common/periph/flashpage.c
From errata 2.14.1:
> NVM reads could be corrupted when mixing NVM reads with Page Buffer writes.
> #### Workaround
> Disable cache lines before writing to the Page Buffer when executing from NVM or reading
data from NVM while writing to the Page Buffer. Cache lines are disabled by writing a one to
`CTRLA.CACHEDIS0` and `CTRLA.CACHEDIS1`.
I ran `examples/suit_update` on `same54-xpro`.
This would previously crash when *not* disabling the interrupts.
I also tested this on `samr34-xpro` to ensure no regressions on `saml21`.
`samd21` never needed the disabled interrupts in the first place.
=> cpu/sam0_common: flashpage: disable cache while writing

doc/doxygen/Makefile
While rebasing #21067 I noticed that I forgot to add the `coc.md` dependency to the `latex` and `clean` targets in #21071.
`make latex` should work again and `make clean` should now remove the generated `src/coc.md` as well. 
Follow-up fix for #21071.
=> doxygen/Makefile: fix `make latex` and `make clean`

pkg/lwip/contrib/netdev/lwip_netdev.c
Since https://github.com/RIOT-OS/RIOT/pull/21012 a netdev in the new API can return > 0 directly in netdev_driver_t::send() to indicate the driver is naturally synchronous and has already completed the transmission.
The adaption of lwIP to that API change contained a bug: It handled the case after the thread is already blocked waiting for the signal that is never going to arrive. This is now fixed.
```
$ make BOARD=native64 -C tests/pkg/lwip -j && tests/pkg/lwip/bin/native64/tests_lwip.elf tap1
[...]
main(): This is RIOT! (Version: 2025.01-devel-318-g4044c8)
RIOT lwip test application
> ifconfig
ifconfig
Iface ET0 HWaddr: 26:de:d0:85:bd:b2 Link: up State: up
Link type: …
```
=> pkg/lwip: fix adaption to API change of netdev_new_api

drivers/at24cxxx/at24cxxx.c
If `len` is 0, `check` will be uniinitialized.
`_write()` already handles this correctly.
=> drivers/at24cxxx: fix uninitialized return value in `_set()`

sys/include/rtc_utils.h, sys/rtc_utils/rtc_utils.c
The function does not modify it, so make the time struct `const`
=> sys/rtc_utils: make parameter to `rtc_mktime()` const

cpu/atxmega/include/cpu_conf.h, sys/include/string_utils.h, sys/libc/string.c, tests/pkg/relic/Makefile, tests/unittests/tests-libc/tests-libc.c
Assembling a string through multiple writes if often open-coded like this
```C
char buffer[64];
size_t len = 0;
for (unsigned i = 0; i < ARRAY_SIZE(names); ++i) {
len += snprintf(&buffer[len], sizeof(buffer) - len, "%u: %s\n", i, names[i]);
}
```
This is error prone (the above example foregoes any error handling) and ugly.
This introduces a small helper function to achieve the same in a much more convenient fasion:
```C
char buffer[64];
string_writer_t sw;
string_writer_init(&sw, buffer, sizeof(buffer));
for (unsigned i = 0; i < ARRAY_SIZE(names); ++i) {
swprintf(&sw, "%u: %s\n", i, names[i]);
}
```
A new unit test has been added.
=> sys/string_utils: add string_writer helper

boards/nucleo-l073rz/doc.txt
This PR adds MCU table for `nucleo-l073rz` board.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-l073rz.html
```
None
=> boards/nucleo-l073rz: add MCU table to doc page

sys/shell/Makefile.dep
The LWIP netif shell commands make use of POSIX functions like inet_pton(). Hence, the module needs to be a dependency.
Without this dependency the build will fail on certain machines (e.g., Arch Linux) when building for certain platforms (e.g., esp32).
Build the paho-mqtt example for LWIP with IPv4 for an esp32 board on Arch Linux.
=> sys: shell: posix_inet as dependency for LWIP

tests/sys/shell/tests/01-run.py
This improves the test automation by changing the matching to not eagerly match a shell commands description across a line break.
This hopefully is the issue that causes nightly failures in test runs on tests/sys/shell on samr21-xpro.
None
=> tests/sys/shell: improve test automation

sys/include/net/sock/dns.h
Replaces Google's name servers with the ~[OpenNIC](https://opennic.org/)~ [Quad9](https://quad9.net/) ones. This is better aligned with RIOT's spirit I belive.
Build, for instance, `gnrc_networking` with `auto_init_sock_dns` and `sock_dns` enabled and try to ping riot-os.org.
=> sys: net: dns: use Quad9 resolver

Makefile.base, examples/subfolders/Makefile, examples/subfolders/folder/subfolder/c.c, examples/subfolders/main.c
Fixes a tiny `make` warning when a subfolder has multiple source files.
> RIOT/Makefile.base:120: target 'RIOT/examples/subfolders/bin/native/application_subfolders/folder/subfolder/' given more than once in the same rule
Compile `examples/subfolders` without the fix now and you will get the warning.
=> buildsystem: keep subfolders of sources unique

cpu/esp32/doc.txt, cpu/esp8266/doc.txt, dist/tools/esptools/export.sh, dist/tools/esptools/install.sh
`esptools` provide a handy way to quickly install the toolchain needed for the various ESP32 family members.
Installing the toolchain for the venerable esp8266 always requires looking up the right wiki page since it uses a custom toolchain that does not follow the same format.
To streamline this, add a special case for esp8266 to the `install.sh` script so the same script can be used to get all the Espressif toolchains.
Simply run 
./dist/tools/esptools/install.sh esp8266
and 
./dist/tools/esptools/export.sh esp8266
=> dist/tools/esptools: add support for installing esp8266 toolchain

CODING_CONVENTIONS.md
Raising the minimum version is only a formality. Several features, such as f-strings are already used in the code base.
In addition, the CI builds use a Docker image based on Ubuntu 22.04. Ubuntu 22.04 ships with Python 3.10.
While at it, I also improved the spelling a bit.
Not applicable.
None
=> CODING_CONVENTIONS.md: bump minimum Python version

sys/include/ztimer.h, sys/net/gnrc/sock/gnrc_sock.c, sys/ztimer/util.c, tests/sys/ztimer_mbox_get_timeout/Makefile, tests/sys/ztimer_mbox_get_timeout/Makefile.ci, tests/sys/ztimer_mbox_get_timeout/main.c, tests/sys/ztimer_mbox_get_timeout/tests/01-run.py
This implements `ztimer_mbox_get_timeout()` and salvages the test app from https://github.com/RIOT-OS/RIOT/pull/18977 with minor tweaking.
On top of `ztimer_mbox_get_timeout()`, the timeout of `gnrc_sock_recv()` is now implemented race-free. 
Run the provided test app. (Maybe also set `ENABLE_DEBUG` to `1` in `sys/ztimer/utils.c` to ensure that the race when a message was received just in time but the timeout was not cancelled in time is indeed triggered by the test app.)
Also do some testing with GNRC's SOCK implementation and proper timeout handling.
Better alternative to https://github.com/RIOT-OS/RIOT/pull/18977
=> sys/ztimer: implement ztimer_mbox_get_timeout() and use it to fix race in gnrc_sock_recv()

dist/tools/bmp/README.md, dist/tools/bmp/bmp.py, dist/tools/bmp/requirements.txt
The Black Magic Probe is a great debugger. Current implementation does not work with more modern firmware versions, because some commands have been renamed. Further more, Python 3.12 deprecated the `distutils` package (removed in 3.13), so this tool did not work on my machine.
Compatibility with older firmware versions has been maintained (or at least, I tried). I first wanted to implement auto--detection of the firmware version, but that does not work with debug mode in the current state.
I also cleaned up the code a tiny bit, and made things a bit more logical (IMHO).
Before, port detection would always throw an exception if no debugger was found, even if `--port` was provided. I relaxed this check, which gives me the possibility to provide any port. In my particular use-case, I run the …
=> dist/tools/bmp: improve compatibility

tests/sys/ztimer_mbox_get_timeout/main.c
On `native` when build with LLVM, time seems to not monotonically increase, causing a test to be flaky.
This disables the part that is flaky on native on native.
```
make BOARD=native TOOLCHAIN=llvm -C tests/sys/ztimer_mbox_get_timeout && for i in {1..100}; do tests/sys/ztimer_mbox_get_timeout/bin/native/tests_ztimer_mbox_get_timeout.elf || break; done
```
This should run in this PR, but fails in master.
Flaky test introduced in https://github.com/RIOT-OS/RIOT/pull/21113
=> tests/sys/ztimer_mbox_get_timeout: Fix flakyness

dist/tools/esptools/export.sh, dist/tools/esptools/install.sh
This PR fixes the `all` parameter in `dist/tools/esptool/intall.sh` and `dist/tools/esptool/export.sh`.
With PR #21094, the installation of the ESP8266 toolchain was added to the tools by overriding the `ESP32_GCC_RELEASE` variable with the `ESP8266_GCC_RELEASE` variable. This leads to wrong settings when iterating over all architectures if the tools are called with parameter `all`.
`dist/tools/esptool/install.sh all`
`. dist/tools/esptool/export.sh all`
Without the patch, the installation only works for the ESP8266 toolchain.
Fixes PR #21094
=> dist/tools/esptool: fix the all target

core/lib/include/cib.h
Just add some `const`  in `cib_peek_*`.
CI
=> core/cib: add const to cib_peek()

sys/include/net/nanocoap.h, sys/net/application_layer/gcoap/gcoap.c
Calling `coap_get_token()` and `coap_get_token_length()` on an (mostly) uninitialized `coap_pkt_t` did work so far due to implementation details matching the expectations, but this is not backed up by any API contract.
This fixes the API abuse by introducing and using a new API that does read a token and token length from a CoAP over UDP packet out of a buffer. This now provides the behavior expected by the caller and commits to it via API contract.
No change in behavior when using GCoAP.
Not abusing the API by calling an (mostly) unitialized `coap_pkt_t` is useful for adding other CoAP formats (e.g. as used for CoAP over TCP and CoAP over WebSocket), as `coap_get_token()` will look into a different location depending on the format: For that, adding information needed to deduce the CoAP …
=> sys/net/gcoap: get rid of API abuse

pkg/relic/Makefile, pkg/relic/patches/0001-use-modul-random-for-seeding.patch, pkg/relic/patches/0002-add-RIOT-random-support-to-cmake-and-relic_conf.h.patch, pkg/relic/patches/0003-fix-Wformat-nonliteral-by-using-printf-directly.patch, tests/pkg/relic/Makefile.ci, tests/pkg/relic/main.c
Update `pkg/relic` to [version 0.7.0](https://github.com/relic-toolkit/relic/releases/tag/0.7.0). I had to rewrite the patches since the last one could not apply anymore, but the actual changes stayed the same. Also needed one adaption in the respective test due to a function being gone.
`make -C tests/pkg/relic all tests`
=> pkg/relic: bump version to 0.7.0

cpu/stm32/periph/adc_l0.c, cpu/stm32/periph/adc_l1.c
Most of this PR is already described in #20780.
The STM32L0 was enabled before the resolution bits were set, but any access to configuration registers is prohibited (and seemingly ignored by the microcontroller). Therefore, the resolution set in `adc_sample` was not actually applied and the resolution was always 12-bit.
The same issue was present in the STM32L1, however this ADC hardware implementation does not seem to ignore configuration register calls (even though they are prohibited when the ADC is on). However, the resolution bits were not masked in the configuration register before setting the new resolution, leading to the resolution being stuck at 6-bit (0b11). The resolution was only OR-ed to the register.
For convenience you can change the test application (`tests/periph/adc`) …
=> cpu/stm32l0,l1: Fix ADC initialization order

sys/include/net/gnrc/netif.h, sys/net/gnrc/netif/gnrc_netif.c
The timeout value in `gnrc_netif_ipv6_wait_for_global_address()` would overflow for large timeouts, leading to an immediate return.
Instead of doing arithmetic, set a proper timer - or don't if the timeout is `UINT32_MAX`.
=> gnrc_netif: fix timeout in `gnrc_netif_ipv6_wait_for_global_address()`

cpu/esp32/Makefile.include, cpu/esp32/include/sys/features.h, cpu/esp32/syscalls.c
This PR provides a cleanup to reduce the number of linker scripts used for the ESP32x ROMs and thus the symbols used from the ESP32x ROMs. It works with both gcc 12.2 and gcc 14.2. The latter gcc version is a prerequisite for ESP-IDF v5.2 and higher version and thus a prerequisite for starting the work on the RIOT-OS port for the latest version of ESP-IDF. Thin in turn is a prerequisite to use newer ESP32x SoCs like ESP32-H2, ESP32-C2 and ESP32-C6 as well as the future ESP32-P4.
Compilation has to succeed.
The PR was tested with gcc 12.2 as well as gcc 14.2 for WiFi and BLE (the most complex usage of ESP32 SoCs) for all supported ESP32x variants.
=> cpu/esp32: Cleanup of used ESP32x ROM linker scripts

.github/workflows/release-test.yml
The new upload artifact does not support multiple artifacts uploaded with the same name, this fixes this by adding matrix info in.
[Here is the current error](https://github.com/RIOT-OS/RIOT/actions/runs/12840297187/job/35808765235)
Check the CI output.
=>  .github/workflows/release-test.yml: Fix upload-artifact

boards/nucleo-f412zg/doc.txt
This PR adds MCU table for `nucleo-f412zg` board.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f412zg.html
```
None
=> boards/nucleo-f412zg: add MCU table to doc page

bootloaders/riotboot/Makefile, cpu/cortexm_common/vectors_cortexm.c, cpu/doc.txt
A reoccurring issue is that some board sets way too much pin state in `board_init()` and this carries over to `riotboot` where it is then frozen forever.
But riotboot has no business to set any hw state, it just needs to compare two values in flash and jump to an address - we don't need to touch any hardware registers for that.
An app that makes use of riotboot, e.g. `examples/suit_update` still boots as before.
This was verified on `same54-xpro`.
=> bootloaders/riotboot: don't change CPU/pin state

tests/drivers/candev/Makefile, tests/drivers/candev/Makefile.board.dep
This changes the app config to prefer periph_can whenever that feature is provided, and fall back to mcp2515 as default if not.
```
$ for board in same54-xpro native native64 samr21-xpro hifive1b; do printf "%s: " "$board"; make -C tests/drivers/candev BOARD=$board info-modules | grep 'periph_can\|mcp2515'; done
same54-xpro: periph_can
native: periph_can
native64: periph_can
samr21-xpro: mcp2515
hifive1b: mcp2515
```
None
=> tests/drivers/candev: prefer periph_can when available

.github/workflows/release-test.yml
Needed for https://github.com/RIOT-OS/Release-Specs/pull/315
https://github.com/miri64/RIOT/actions/runs/12887946735/job/35931726186
https://github.com/RIOT-OS/Release-Specs/pull/315
=> release-test.yml: also fetch host key from grenoble

LOSTANDFOUND.md
In Pull Request #18562, the removal of MIPS support was documented and the headline had the right Commit ID, however the URL was not added to the link section below.
In Pull Request #21146, a `:` was added after the headline, leading to Doxygen not recognizing the link and therefore not applying it.
Unfortunately while this PR was open, I didn't see it in time, so now it has to be fixed afterwards.
I think both PRs are from @MrKevinWeiss, but I don't want to blame him. I fought for hours with the `LOSTANDFOUND.md` to find the bug described in #21106, so I know how easy it is to get Markdown angry :D
The documentation should still build and now show the links (they are still broken because of #21106, BUT there should now be `<a href=...` in the headlines.
Corrects the regressions …
=> LOSTANDFOUND.md: add missing URL, fix Markdown typo

sys/include/net/gnrc/ipv6.h
Adding the pseudo-random PID to a static link-local prefix is not very useful when we want predictable addresses.
Previously there was an attempt to remove the entire `CONFIG_GNRC_IPV6_STATIC_LLADDR` feature (https://github.com/RIOT-OS/RIOT/pull/13075), but with `CONFIG_GNRC_IPV6_STATIC_LLADDR_IS_FIXED` set it's actually useful.
So make `CONFIG_GNRC_IPV6_STATIC_LLADDR_IS_FIXED` the default as that's what people would expect from that feature and deprecate it's alternative (original) behavior.
If no use-case can be found for adding the PID to the link-local address, we should just drop it and always consider a static address static.
=> gnrc/ipv6/nib: make `CONFIG_GNRC_IPV6_STATIC_LLADDR_IS_FIXED` the default & deprecate it

examples/nanocoap_server/Makefile, examples/nanocoap_server/coap_handler.c, examples/nanocoap_server/main.c, sys/Makefile.dep, sys/include/net/coap.h, sys/include/net/nanocoap.h, sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/nanocoap.c, sys/net/application_layer/nanocoap/sock.c
- Clean up and extend the separate response feature of nanocoap
- Add a bit of glue to use the separate response feature to implement observe
```
$ sudo ip tuntap add tap0 mode tap user $(whoami)
$ sudo ip link set tap0 up
$ make BOARD=native64 -C examples/nanocoap_server -j flash term
```
```
$ coap-client-notls -s 60 -m get 'coap://[fe80::9826:30ff:feb8:31f4%tap0]/time'
8326
9000
10001
11000
12001
13000
14000
15001
16000
17001
18000
19000
20001
21000
22000
[...]
```
None
=> sys/net/nanocoap: Implement Observe (Server-Side)

sys/tiny_strerror/tiny_strerror.c
The picolibc shipped in Ubuntu does not provided non-POSIX errnos by default. If the errno codes are not provided, we can also not provide corresponding strings.
This guards the effected strings corresponding to non-POSIX errnos behind `#ifdef`, so that they are only provided when the corresponding errno is.
```
$ FEATURES_REQUIRED=picolibc make BOARD=nucleo-f767zi -C tests/periph/selftest_shield
```
<details><summary>on Ubuntu with <code>master</code> gives:</summary>
```
/home/marian.buschsieweke@ml-pa.loc/Repos/software/RIOT/master/sys/tiny_strerror/tiny_strerror.c:146:6: error: 'EHOSTDOWN' undeclared here (not in a function); did you mean 'ENETDOWN'?
146 |     [EHOSTDOWN]         = _ehostdown,
|      ^~~~~~~~~
|      ENETDOWN …
```
=> sys/tiny_strerror: fix compilation with picolibc on Ubuntu

tests/unittests/tests-rtc/tests-rtc.c
adds a test for unixtime conversion to our rtc function tests.
```
make -C tests/unittests/tests-rtc/ tests-rtc test
```
#20023
=> tests/test-rtc: test retrieval of unix-time

sys/net/application_layer/nanocoap/nanocoap.c
- Do not reply with a reset message to a reset or an ACK message
- Reply with a reset message when not able to process a CON/NON message (not even a suitable error reply)
```
$ sudo ip tuntap add tap0 mode tap user $(whoami)
$ sudo ip link set tap0 up
$ make BOARD=native64 -C examples/nanocoap_server -j flash term
```
```
$ cat test.py                     
import socket, aiocoap
m = aiocoap.Message()
m.code = 0
m.mid = 0
m.mtype = aiocoap.RST
s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
s.connect(('fe80::9826:30ff:feb8:31f4', 5683, 0, socket.if_nametoindex('tap0')))
s.send(m.encode())
s.recv(1024)
$ python3 test.py
```
```
$ tshark -i tap0 -Y "coap"
Capturing on 'tap0'
3 0.000397706 fe80::9826:30ff:feb8:31f3 56273 5683 fe80::9826:30ff:feb8:31f4 CoAP 66 RST, MID:0, Empty Message
4 …
```
=> sys/net/nanocoap: align request handling with spec

sys/net/application_layer/nanocoap/nanocoap.c
--------
- Do not reply with a reset message to a reset or an ACK message
- Reply with a reset message when not able to process a CON/NON message (not even a suitable error reply)
```
$ sudo ip tuntap add tap0 mode tap user $(whoami)
$ sudo ip link set tap0 up
$ make BOARD=native64 -C examples/nanocoap_server -j flash term
```
```
$ cat test.py                     
import socket, aiocoap
m = aiocoap.Message()
m.code = 0
m.mid = 0
m.mtype = aiocoap.RST
s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
s.connect(('fe80::9826:30ff:feb8:31f4', 5683, 0, socket.if_nametoindex('tap0')))
s.send(m.encode())
s.recv(1024)
$ python3 test.py
```
```
$ tshark -i tap0 -Y "coap"
Capturing on 'tap0'
3 0.000397706 fe80::9826:30ff:feb8:31f3 56273 5683 fe80::9826:30ff:feb8:31f4 CoAP 66 RST, MID:0, Empty …
```
=> [BACKPORT] sys/net/nanocoap: align request handling with spec

cpu/nrf52/radio/nrf802154/nrf802154_radio.c, tests/drivers/nrf802154/README.md, tests/drivers/nrf802154/main.c
The nrf802154_radio.c file implements a frame filter on the MAC sublayer as mentioned in IEEE 802.15.4-2020 in Section 6.7.2 Reception and rejection. For beacon frames (section e), it should check if source PAN ID matches the PAN ID of the device. This is currently not the case and beacon frames get filtered out.
This PR implements the PAN ID check, while also confirming that source PAN ID is present in the first place.
Tests provided in the first commit. (requires two nrf52 devices)
=> cpu/nrf52/radio/nrf802154: fix beacon acceptance

examples/gnrc_border_router/Makefile
For convenience, it would be nice to have DNS resolution enabled by default in the examples. Hence, this patch configures a default DNS resolver on the 6lbr example and propagates its via RDNSS option in RAs to the nodes.
Once again the tradeoff is some increased ROM and RAM usage.
1. Setup a border router (for instance on the nrf52840dongle), for instance, via `BOARD=nrf52840dongle make -C examples/gnrc_border_router clean all flash ULINK=cdc-ecm`.
2. Setup a second 6lowpan capable device with, for instance, `gnrc_networking` while enabling `USEMODULE += sock_dns` and `USEMODULE += gnrc_ipv6_nib_dns`.
3. Check if pinging a hostname works, e.g., `ping riot-os.org`.
Can be tested with #21116.
=> Configure default DNS resolver in 6lbr example

sys/chunked_ringbuffer/chunked_ringbuffer.c, sys/include/chunked_ringbuffer.h
It can be handy to know the size of the chunk that we just stored. Since we already have that information, it's very cheap to return that instead of `true`.
Technically an API change, but now we already returned 0 in the error case and 1 on success, so changing bool -> int won't need any code changes.
=> sys/chunked_ringbuffer: let `crb_end_chunk()` return size of the chunk

sys/net/application_layer/cord/doc.txt
This PR updates the **doc** file of the `CORD` module in RIOT. Updates:
- Update of additional references to **RFC 9176**.
- The **draft-ietf-core-resource-directory-27** was compared in the previous update with the **RFC 9176** and no extensions in the implementation were found. However, the Section References in the description of the `cord_ep` and `cord_epsim` submodules seemed not to be correct, not only for the **RFC 9176**, but also for the **draft-ietf-core-resource-directory-27**. Consequently, since the **draft-ietf-core-resource-directory-15** was the original version used before the reference update to the **draft-ietf-core-resource-directory-27**, it was compared with it and was found out that the references are valid for **draft-ietf-core-resource-directory-15** . During the …
=> sys/cord/doc.txt: Update additional references to RFC 9176

cpu/sam0_common/periph/eth.c
On boards with a broken PHY the init will hang indefinitely.
This is not very nice and makes it hard to tell what's wrong - instead, bail out early if the PHY does not become IDLE at all.
=> cpu/sam0_eth: fix hang with broken PHY

cpu/sam3/periph/hwrng.c
This PR fixes the access of PMC enable/disable clock for `hwrng` peripheral.
It looks like I missed this one while doing #21168 
While at it, I also fixes the accesses of `CR` register.
Read-modify-write is useless for this register as there is no other bits available for this register.
In addition, the previous way to disable the hwrng through `CR` register was also broken.
Only the ENABLE bit must be set to 0, not the KEY mask. If the KEY mask written is incorrect, the write access will be ignored by the MCU.
For the record here is the log of `tests/periph/hwrng` on `arduino-due` board with this PR:
```
2025-01-30 20:54:14,475 # Help: Press s to start test, r to print it is ready
s
2025-01-30 20:54:21,283 # START
2025-01-30 20:54:21,287 # main(): This is RIOT! (Version: …
```
=> cpu/sam3: fix hwrng peripheral register access

cpu/samd5x/periph/can.c
CAN required CLK_CANx_APB and CLK_CANx_APB to be running and will not request any clock by itself. We can ensure both clocks to be running by preventing the MCU from entering IDLE state.
The SAMD5x/SAME5x Family Data Sheet says in Section "39.6.9 Sleep Mode Operation" says:
> The CAN can be configured to operate in any idle sleep mode. The CAN
> cannot operate in Standby sleep mode.
>
> [...]
>
> To leave low power mode, CLK_CANx_APB and GCLK_CANx must be active
> before writing CCCR.CSR to '0'. The CAN will acknowledge this by
> resetting CCCR.CSA = 0. Afterwards, the application can restart CAN
> communication by resetting bit CCCR.INIT.
tl;dr: At most SAM0_PM_IDLE is allowed while not shutting down the CAN controller, but even that will pause communication (including RX).
Apparently, …
=> cpu/samd5x/periph_can: fix RX

dist/tools/tapsetup/tapsetup
"Become a daemon immediately (nowait) rather than waiting until an IP address has been acquired." Otherwise tapsetup may hang for a long time in the absence of a DHCP server.
Run `tapsetup -u <UPSTREAM-INTERFACE>` without a DHCP server ready on that link.
=> dist: tools: avoid hanging tapsetup in the absence of a DHCP server 

dist/tools/bmp/README.md, dist/tools/bmp/bmp.py
This extends the auto-detection logic by parsing the firmware version number from the device descriptor as returned by PySerial. For stable releases, this should return a proper version number, and restores out-of-the-box compatibility with older firmware versions.
```
found following Black Magic GDB servers:
[/dev/cu.usbmodem81C986981] Serial: 81C98698 Firmware: 2.0.0 <- default 
connecting to [/dev/cu.usbmodem81C986981]...
auto-detected firmware version 2.0.0
GDB EXECUTABLE NOT FOUND! FALLING BACK TO /opt/homebrew/bin/arm-none-eabi-gdb
connecting successful.
```
The second improvements is to detect unsupported targets. The former message was a bit misleading. At least in v1.10.2 and v2.0.0 of the BMP, unsupported targets are prefixed with ***:
```
(gdb) mon swd_scan
Target voltage: 3.3V …
```
=> dist/tools/bmp: additional improvements to auto-detection

cpu/samd5x/periph/can.c
CAN required CLK_CANx_APB and CLK_CANx_APB to be running and will not request any clock by itself. We can ensure both clocks to be running by preventing the MCU from entering IDLE state.
The SAMD5x/SAME5x Family Data Sheet says in Section "39.6.9 Sleep Mode Operation" says:
> The CAN can be configured to operate in any idle sleep mode. The CAN
> cannot operate in Standby sleep mode.
>
> [...]
>
> To leave low power mode, CLK_CANx_APB and GCLK_CANx must be active
> before writing CCCR.CSR to '0'. The CAN will acknowledge this by
> resetting CCCR.CSA = 0. Afterwards, the application can restart CAN
> communication by resetting bit CCCR.INIT.
tl;dr: At most SAM0_PM_IDLE is allowed while not shutting down the CAN controller, but even that will pause communication (including RX).
Apparently, …
=> cpu/samd5x/periph_can: fix RX [backport 2025.01]

cpu/esp_common/Makefile.include
The generated `partitions.csv` needs to state the size of the flash file. This so far used `ls -l | awk '{print $5}'` to achieve that, but that is not robust, as the columns of `ls -l` depend on the tool and system configuration used.
This commit replaces the call with `wc -c | cut -f 1 -d " "`, which should be more robust.
Building any app for any ESP8266/ESP32 should still work without regressions. In addition, it should now work on Ubuntu 24.04.1 LTS machines that are connected into some cooperate identity management stuff (I believe the last part adding a column to `ls -l` on my system).
None
=> cpu/esp_common: create partitions.csv more robustly

examples/gnrc_border_router/Makefile
Additionally to requesting a delegated prefix via DHCPv6 this also enables to ask for a temporary (non-permanent) address on the 6lbr. If the upstream DHCP server provides one, this can be used to establish end-to-end connectivity from the 6lbr towards an Internet host directly.
1. Bridge the upstream interface of the border router to your upstream router (assuming that it does DHCPv6) or configure a local DHCPv6 server, for instance [KEA](https://www.isc.org/kea/) with a configuration like [this](https://github.com/user-attachments/files/18290754/kea-dhcp6.txt)
2. Run the border router and check if you can ping Internet hosts directly.
=> Request temporary address (IA_NA) for the 6lbr example

examples/default/main.c
Fixes an issue reported to the RIOT matrix chat, where the user wanted to have a network interface but not the packet dump for the `default` example.
Comment out the `gnrc_pktdump` module in `examples/default/Makefile.board.dep`
```diff
diff --git a/examples/default/Makefile.board.dep b/examples/default/Makefile.board.dep
index ca5f03cba7..ee0f1c5e1f 100644
--- a/examples/default/Makefile.board.dep
+++ b/examples/default/Makefile.board.dep
@@ -9,7 +9,7 @@ ifneq (,$(filter netif,$(FEATURES_USED)))
USEMODULE += gnrc_txtsnd
-  USEMODULE += gnrc_pktdump
+  # USEMODULE += gnrc_pktdump
```
The example should still compile, sending packets should also still be possible, but the example will not provide any output when it receives a packet.
None
=> examples/default: fix dependency modeling

sys/include/net/nanocoap.h, sys/include/suit/transport/worker.h, tests/unittests/Makefile
There is an `typdef void sock_udp_ep_t` hack in `nanocoap.h` that tries allow using parts of nanocoap without a RIOT network stack.
There is a similar hack to allow it to be used without RIOT at all. This has been used in the early days during development on Linux directly. This however has not been tested and left bit rotting.
Both hacks are remove and nanocoap now just depends on sock/udp.h.
In a future cleanup, the CoAP packet parsing and building code of nanocoap can be separated from the part that does the transmission and reception of UDP packets. That way, using nanocoap's packet parsing and building will again be available without using a network stack.
Until then, let's drop the hacks and just depend on a network stack.
```
$ make BOARD=native64 -C tests/unittests/ tests-nanocoap …
```
=> sys/net/nanocoap: drop typedef hack [v2]

cpu/sam3/periph/gpio.c
This PR makes use of `bitarithm_test_and_clear` to process gpio ISR instead of looping through every bits inside the register.
It will use `CLZ` ARM instruction to catch the position of all bits set and clear them one by one which is faster than checking every bits every time.
Tested on `arduino-due` with `tests/buttons` (I've wired up 4 external buttons with a breadboard for this).
None
=> cpu/sam3: optimize gpio ISR processing

pkg/lwip/Makefile
lwIP v2.2.1 [came out this morning](https://savannah.nongnu.org/news/?id=10724), so let's bump our package for it.
I ran the same old loops for lwIP testing:
```bash
for ipv4 in 0 1; do
for ipv6 in 0 1; do
for board in native samr21-xpro; do
for app in lwip_sock_ip lwip_sock_tcp lwip_sock_udp; do
if [ $ipv4 == 0 ] && [ $ipv6 == 0 ]; then
continue;
fi;
BOARD=$board LWIP_IPV4=$ipv4 LWIP_IPV6=$ipv6 make -C tests/pkg/${app} -j flash test
done;
done;
done;
done
```
I also ran the `tests/pkg/lwip` test for native and tested the IP/UDP/TCP functionality on a 6LoWPAN-capable board (`samr21-xpro`), so after this (and scrolling through the changes since v2.2.0 a little bit) I am confident, that this does not break things.
=> lwip: bump to v2.2.1

drivers/at/at.c
Fixes a tiny bug in the `at` driver that causes a return of `-ENOBUFS` although the received response fits in the buffer.
It happens when the end-of-line sequence is at the last position before `\0`.
https://github.com/RIOT-OS/RIOT/blob/c20ce6996739f33243847f0d85bc19036091a547/drivers/at/at.c#L518-L528
When the `while` loop is exited because '\n' was received at the last position before the last `\0`, the `len` variable was already decremented. So the  `-ENOBUFS` condition triggers.
https://github.com/RIOT-OS/RIOT/blob/c20ce6996739f33243847f0d85bc19036091a547/drivers/at/at.c#L538-L540
Configure a URC and send a sequence over the UART via `pyterm` to the microcontroller.
For example "012345678901234567890123456789\n\0" for  `rp_buf_size` = 32.
=> drivers/at: at_readline_stop_at_str fix remaining buffer length

boards/esp32-ethernet-kit-v1_0/doc.txt, boards/esp32-ethernet-kit-v1_1/doc.txt, boards/esp32-ethernet-kit-v1_2/doc.txt, boards/esp32-heltec-lora32-v2/doc.txt, boards/esp32c3-devkit/doc.txt, boards/esp32s2-devkit/doc.txt, boards/esp32s3-devkit/doc.txt, boards/esp32s3-usb-otg/doc.txt
This PR fixes some links to board images an pinouts in the documentation of some ESP32x boards.
Without this PR, the following board documentation has some broken links to board images and pinouts:
https://doc.riot-os.org/group__boards__esp32__esp-ethernet-kit-v1__0.html
https://doc.riot-os.org/group__boards__esp32__esp-ethernet-kit-v1__1.html
https://doc.riot-os.org/group__boards__esp32__esp-ethernet-kit-v1__2.html
https://doc.riot-os.org/group__boards__esp32__heltec-lora32-v2.html
https://doc.riot-os.org/group__boards__esp32c3__devkit.html
https://doc.riot-os.org/group__boards__esp32s2__devkit.html
https://doc.riot-os.org/group__boards__esp32s3__devkit.html
https://doc.riot-os.org/group__boards__esp32s3__usb__otg.html
With the PR, the images and pinouts are shown correctly.
=> doc: fix image references for ESP32x boards

sys/include/ztimer.h
This PR fix small typo in doxygen documentation for `ztimer_acquire` and `ztimer_release` functions - in description appears 'the the' phrase.
Generate doc and see if everything is ok.
```
make doc
xdg-open doc/doxygen/html/group__sys__ztimer.html
```
None
=> sys/ztimer: fix small typo in doc

sys/include/net/gnrc/netif/flags.h
Both `GNRC_NETIF_FLAGS_6LO_HC` and `GNRC_NETIF_FLAGS_TX_FROM_PKTQUEUE` were using the same flag.
This meant that IPHC was always unset after a queued send (because `GNRC_NETIF_FLAGS_TX_FROM_PKTQUEUE` gets set/unset then).
=> sys/net/gnrc/netif: pktqueue: don't clash with `GNRC_NETIF_FLAGS_6LO_HC`

boards/rpi-pico-w/doc.txt, boards/rpi-pico/doc.txt, boards/rpi-pico/include/board.h, boards/rpi-pico/include/gpio_params.h, boards/rpi-pico/include/periph_conf.h
The Raspberry Pi Pico documentation was outdated, OpenOCD supports the RP2040 since version 1.12.0 that was released two years ago.
Furthermore I fixed the Raspberry Pi Pico image and changed the Pico-W image to the one from the documentation with a transparent background.
Doxygen has a ~~bug~~ intended behavior that `***Beware:***` is not rendered as bold-italic but instead it prints `Beware:***` in the output. As far as I can tell, this has been present since at least Doxygen 1.8.13 when the documentation was originally added: https://web.archive.org/web/20210921211645/https://doc.riot-os.org/group__boards__rpi__pico.html
~~I filed a bug report with Doxygen about this, but for the time being I replaced it with the HTML tags that work: https://github.com/doxygen/doxygen/issues/11420~~ …
=> boards/rpi-pico*: Update and fix documentation and image

boards/common/esp8266/include/board_modules.h, boards/ikea-tradfri/doc.txt, boards/spark-core/doc.txt, boards/stm32l496g-disco/include/periph_conf.h, cpu/cortexm_common/include/cpu_conf_common.h, cpu/esp32/doc.txt, cpu/esp32/esp-eth/esp_eth_netdev.c, cpu/esp_common/esp-wifi/esp_wifi_netdev.c, cpu/kinetis/include/bme.h, cpu/kinetis/include/cpu_conf_kinetis_k.h, drivers/atwinc15x0/atwinc15x0_netdev.c, drivers/include/hmc5883l.h, drivers/include/periph/gpio.h, examples/advanced_examples/suit_update/README.hardware.md, pkg/opendsme/include/opendsme/opendsme.h, sys/include/congure/test.h, sys/include/crypto/aes.h, sys/include/net/gnrc/netif/6lo.h, sys/include/net/gnrc/rpl/dodag.h, sys/include/net/gnrc/sixlowpan/frag/rb.h, sys/include/phydat.h, sys/include/sys/bus.h, sys/picolibc_syscalls_default/syscalls.c, sys/psa_crypto/doc.txt, tests/drivers/hmc5883l/README.md, tests/drivers/hmc5883l/main.c
In PR #21208 I fix double the - `the the` small typo in ztimer documentation. I checked the whole RIOT project and find much more appearance of this typo. This PR should fix all that small typos.
Looking at the changes with the successful generation of documentation and Murdock test pass should be enough - as I only touch doxygen and comments.
PR #21208
=> treewide: fix double the in doc and comments

cpu/sam0_common/sam0_sdhc/mtd_sdhc.c, drivers/mtd/mtd.c
The MTD `work_area` could be allocated multiple times when MTD is reinitialized.
A check for not `NULL` is added.
Custom board with an eMMC. I can craete a fatfs filesystem on it with:
```Makefile
ifneq (,$(filter mtd,$(USEMODULE)))
USEMODULE += mtd_write_page
USEMODULE += mtd_sdmmc_default
USEMODULE += sdmmc_mmc
endif
ifneq (,$(filter vfs_default,$(USEMODULE)))
USEMODULE += fatfs_vfs
USEMODULE += mtd
endif
```
=> {cpu/sam0_common/sam0_sdhc,drivers/mtd}: do not allocate `work_area` twice

tests/periph/adc/README.md, tests/periph/adc/main.c
During my work on the STM32 ADC, I struggled with the original `tests/periph/adc` test, since it only samples at 10 bit and has to be recompiled for different resolutions.
The changes were already discussed in #20780.
Get your favorite devboard with an ADC (some STM32s like F0,G0,C0 might show weird values due to #21222) and run the test with `BOARD=nucleo-l073rz make -C tests/periph/adc flash term`.
You should see the new output from the test with all resolutions. Keep a jumper wire at hand to set the analog inputs to ground and VCC to see that they are at the appropriate values.
This is the new output with this PR:
```
main(): This is RIOT! (Version: 2024.04-devel-2100-g1cb67-pr/adc_test)<\n>
<\n>
RIOT ADC peripheral driver test<\n>
<\n>
This test will sample all available ADC lines …
```
=> tests/adc: always test all resolutions

drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c, sys/include/net/ieee802154.h, sys/include/net/ieee802154/radio.h, sys/include/net/ieee802154/submac.h, sys/net/link_layer/ieee802154/submac.c, tests/net/ieee802154_submac/main.c
This moves the ACK timeout/CSMA backoff period calculation from the `at86rf215` driver to the radio HAL so it can be re-used by other IEEE 802.15.4g drivers.
To do so the `ieee802154_phy_conf_t` structure is extended depending on the used modulation. This allows to add alternative modulations with different properties (e.g. #19172).
Currently there is no driver that makes use of this.
alternative to #19198
=> ieee802154/submac: calculate symbol time on demand

boards/nucleo-f722ze/Makefile.features, boards/nucleo-f722ze/include/periph_conf.h
This PR adds ADC support for `nucleo-f722ze`.
Flash the board using `tests/periph/adc` program. Check if measured values changes when A0-A5 pins are
connected to the 3,3V, GND or to the potentiometer.
Unfortunately I don't have access to this board and cannot check if everything is working.
@crasbe - you mentioned in the PR #20971 that you have this board but it lacks configuration. Could you test it?
PR #20971
=> boards/nucleo-f722ze: add ADC support

doc/doxygen/src/using-rust.md
A newer version of a library broke c2rust (https://github.com/dtolnay/proc-macro2/issues/475 is the proc-macro issue, https://github.com/immunant/c2rust/pull/1197 is how c2rust fixed it, but they don't have a new release yet). Until then, using `--locked` is a viable path.
* Reinstall c2rust
* Any Rust example can still (or, if you recently installed c2rust, now) be built.
Closes: https://github.com/RIOT-OS/RIOT/issues/21079
=> docs/rust: Install c2rust with --locked

sys/include/net/nanocoap.h, sys/net/application_layer/nanocoap/nanocoap.c
For in-band signalling that a content format is not valid / present, the magic number `COAP_FORMAT_NONE` was introduced and the type `uint16_t` was used. Some APIs however used different in-band signalling values and types:
- coap_reply_simple(): No signal available, `unsigned int`
- coap_build_reply_header(): negative values, `int` (Using `int` would prevent using larger content format numbers on 8-bit and 16-bit archs, where `int` and `int16_t` have the same range.)
This changes the behavior to consistently use `COAP_FORMAT_NONE` as "no content format" signal and `uint16_t` as type.
- Using `coap_reply_simple()` with `COAP_FORMAT_NONE` should now allow using no content format in the reply
None
=> sys/net/nanocoap: fix API inconsistency

pkg/doc.txt
Currently the pkg documentation @ https://doc.riot-os.org/group__pkg.html has a link that is supposed to point to https://doc.riot-os.org/creating-modules.html#modules-outside-of-riotbase but on the Doxygen Output it simply creates a dead (and confusing) link to https://doc.riot-os.org/src/creating-modules.html#modules-outside-of-riotbase.
Simply replacing it with the full link should cover both people using the doxygen documentation and people checking out the doc.txt itself.
=> docs: Switch out pkg reference link

cpu/nrf52/Makefile.dep, cpu/nrf52/Makefile.nrf802154.dep, cpu/nrf5x_common/Makefile.features
RIOT does not support multiplexing the nrf radio between BLE and 802.15.4 modes. Currently, if `nrfble` was selected, `netdev_default` would still select `nrf802154` and the feature conflict would not be noted.
1. `USEMODULE="netdev_default nrfble" make -C examples/basic/hello-world BOARD=nrf52840dk all`
2. `USEMODULE="nrf52840 nrfble" make -C examples/basic/hello-world BOARD=nrf52840dk all`
On `master` both just report linker issues.
With this PR, 1 will build successfully without automatically selecting `nrf802154` and 2 will report the feature conflict.
Noticed while testing #20996
=> cpu/nrf5*: mark and resolve radio conflict

sys/include/event/deferred_callback.h, tests/sys/event_periodic_callback/main.c, tests/sys/event_periodic_callback/tests/01-run.py
Often there is a need to execute an event once after a delay.
This adds a convenience helper function for it.
A test for the new function has been added to `tests/sys/event_periodic_callback`
cleaner alternative to #20861
=> sys/event: add `event_deferred_callback_post()` helper

makefiles/docker.inc.mk
After https://github.com/RIOT-OS/riotdocker/pull/257 as requested by CI in https://github.com/RIOT-OS/RIOT/actions/runs/13591031011
static tests should succeed
=> makefiles: bump riotdocker

cpu/esp32/periph/sdmmc.c
This PR removes a small leftover found when migrating the code to ESP-IDF v5.4 which was used for debugging during the development of `cpu/esp32/periph/sdmmc`. It fixes the setting of the bus width which was hardcoded down to 1 bit by this left over.
Compilation has to succeed.
The fix has been tested successfully with `tests/driver/sdmmc` for:
- esp32-wrover-kit
- esp32s3-usb-otg
=> cpu/esp32: fix bus_width in periph_sdmmc

cpu/esp32/Makefile, cpu/esp32/stdatomic.c, pkg/jerryscript/Makefile, pkg/utensor/Makefile.include
This PR provides some small fixes of compile problems with the latest Espressif toolchain (GCC v14.2).
Compilation with used Espressif toolchain (GCC v12.2) should still work in CI.
=> cpu/esp32: Fixes of compile problems with GCC 14.2

boards/stm32f469i-disco/doc.md, boards/stm32l496g-disco/doc.md, dist/tools/doccheck/check.sh, doc/doxygen/riot.doxyfile
rename doc.txt to doc.md to get rid c comment stuff
TODO: rework this description
more nice github rendering
https://github.com/RIOT-OS/RIOT/blob/master/boards/stm32f469i-disco/doc.txt
https://github.com/kfessel/RIOT/blob/p-doc-md/boards/stm32f469i-disco/doc.md
https://ci.riot-os.org/results/ecabf730e9c34bff9b65eafa3097837b/doc-preview/group__boards__stm32f469i-disco.html
#21218
=> doc: doc.txt -> doc.md

boards/nucleo-f413zh/doc.md
This PR adds MCU table for `nucleo-f413zh` board. Moreover, it moves documentations from `doc.txt` do `doc.md` accordingly to the PR #21255.
Generate doc and check if everything looks good.
```
make doc
xdg-open ./doc/doxygen/html/group__boards__nucleo-f413zh.html 
```
PR #21255
=> boards/nucleo-f413zh: add MCU table, move to doc.md

Makefile, Makefile.include, doc/doxygen/Makefile
Doxygen receives a lot of updates (and lately some updates that fixed issues found when generating the RIOT documentation) and releases happen more recently than a couple of years ago.
Unfortunately some (*cough* debian based) distributions don't update it. Ubuntu 22.04 LTS for example will probably be forever stuck at version 1.9.1 from 2021.
To avoid issues with malformatted documentation due to an outdated Doxygen version, this PR adds a warning if the Doxygen version is too old. The warning is delibrately put at the end of the Make process due to the wall of warnings generated by Doxygen.
Request for comments: I don't think the solution with `awk` is super pretty, but doing stuff like that with Make is quite annoying. Another option would be to have a dedicated `check_version.sh`.
It …
=> doc, buildsystem: Add a Version Check for Doxygen, Fix doc* Target Execution

boards/feather-m0-lora/doc.md, boards/feather-m0-wifi/doc.md, boards/feather-m0/Makefile.include, boards/feather-m0/doc.md, boards/feather-m0/doc.txt
Around 2018, Adafruit changed the default bootloader from BOSSA to UF2. While the UF2 bootloader is backwards compatible to the BOSSA protocol, the Double Tap Magic Number has to be changed. In RIOT this can be done with the `BOOTLOADER_UF2` flag.
I wrote everything about this in great detail in #17722.
The note got extended to notify users about the change in case they have a very old board.
Furthermore I used the opportunity to change the `doc.txt` files to Markdown format as discussed in #21220.
Check the documentation.
Make sure the flashing works now for an application of your choice.
```
~/riot-feather/RIOT/tests/sys/shell$ BOARD=feather-m0 make flash -j12
Building application "tests_shell" for "feather-m0" with CPU "samd21".
stty -F /dev/ttyACM0 raw ispeed 1200 ospeed 1200 cs8 …
```
=> boards/feather-m0*: Update Default Bootloader to UF2

boards/nucleo-wl55jc/Makefile.features, boards/nucleo-wl55jc/include/periph_conf.h
This PR adds ADC support for `nucleo-wl55jc`.
Flash the board using `tests/periph/adc` program. Check if measured values changes when A0-A5 pins are
connected to the 3,3V, GND or to the potentiometer.
@crasbe - could you be so kind and test ADC config once again ;) 
PR https://github.com/RIOT-OS/RIOT/pull/20971
=> boards/nucleo-wl55jc: add ADC configuration

doc/doxygen/footer.html
Apparently Doxygen changed the default file type from PNG to SVG at some point and the footer was never updated, leading to the ugly "image not found" symbol in the footer.
The SVG file is already present and accessible on the webserver ( https://doc.riot-os.org/doxygen.svg ) but not in the `footer.html`.
Current state:
With this PR:
~~Check that the generated documentation contains the logo in the footer.~~
Apparently the old doxygen version (1.9.1) in the CI container has some issues displaying the SVG, because there is no size specification:
In newer Doxygen versions (1.12.0), the CSS settings for the footer were extended:
So you have test it locally, wait for the CI container to be updated or just trust me :D
None.
=> doc: Use the correct Doxygen Logo File Type in the Footer

tests/sys/suit_manifest/Makefile, tests/sys/suit_manifest/native_flashpage/native/Makefile, tests/sys/suit_manifest/native_flashpage/native/Makefile.dep, tests/sys/suit_manifest/native_flashpage/native/Makefile.features, tests/sys/suit_manifest/native_flashpage/native/Makefile.include
`tests/sys/suit_manifest` uses a custom `native` board with `periph_flashpage`. Both our native boards support this feature in tree since #15935. We can thus drop the custom board.
Building and running the test on both `native` and `native64` should still succeed:
`make -C tests/sys/suit_manifest BOARD=native clean all test`
`make -C tests/sys/suit_manifest BOARD=native64 clean all test`
Noticed while working on #21242
=> tests/sys/suit_manifest: remove unnecessary custom native board

boards/seeedstudio-xiao-nrf52840/Kconfig, boards/seeedstudio-xiao-nrf52840/Makefile, boards/seeedstudio-xiao-nrf52840/Makefile.dep, boards/seeedstudio-xiao-nrf52840/Makefile.features, boards/seeedstudio-xiao-nrf52840/Makefile.include, boards/seeedstudio-xiao-nrf52840/doc.md, boards/seeedstudio-xiao-nrf52840/include/arduino_iomap.h, boards/seeedstudio-xiao-nrf52840/include/board.h, boards/seeedstudio-xiao-nrf52840/include/gpio_params.h, boards/seeedstudio-xiao-nrf52840/include/periph_conf.h, boards/seeedstudio-xiao-nrf52840/mtd.c, boards/seeedstudio-xiao-nrf52840/reset.c, dist/tools/doccheck/exclude_patterns, doc/doxygen/src/io-mapping-and-shields.md, features.yaml, makefiles/features_existing.inc.mk
Initial board support for the tiny [Seed Studio XIAO nRF52840](https://wiki.seeedstudio.com/XIAO_BLE/). It uses the same bootloader as the Adafruit nrf52840 Feather (Sense) boards.
- I'm still in the process of running `BUILD_IN_DOCKER=1 dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . seeedstudio-xiao-nrf52840` locally and will report back with the result later.
- Look through the header and configuration files. I've mostly followed the example from `feather-nrf52840-sense` and `nrf52840dk` (for the external flash).
- Check generated documentation for the board.
=> boards/seeedstudio-xiao-nrf52840: initial board support

sys/include/net/coap.h, sys/include/net/nanocoap.h, sys/net/application_layer/nanocoap/nanocoap.c
- The responsibility for handling matching CoAP No-Response Options has been split:
- `coap_build_reply()` only needs to report this and return `-ECANCLED`
- `coap_handle_req()` does generate the empty ACK is needed.
==> As a result, writing CoAP request handlers correctly becomes a lost easier. Correct error handling to be present is now sufficient for correct handling of No-Response options.
==> This change is backward compatible with existing code.
- The API doc has been cleaned up and straightened
- CoAP reply handlers that behaved correctly before should still behave correctly now
- CoAP reply handlers that did not behave correctly before in presence of No-Response options should now behave correctly, if they had correct error handling
(CoAP reply handlers that did not get error …
=> sys/net/nanocoap: improve `coap_build_reply()`

boards/same54-xpro/include/board.h, boards/same54-xpro/include/periph_conf.h, cpu/samd5x/include/candev_samd5x.h, cpu/samd5x/periph/can.c, tests/drivers/candev/main.c
This adds an enable pin to the SAMD5x CAN configuration and adds automatic power management to the CAN driver. For the SAME54-XPRO the enable pin configuration has been added and an ugly per-app hack has been dropped.
CAN communication on the SAME54-XPRO should still work:
```
make BOARD=same54-xpro -C tests/drivers/candev
```
Then use the shell to send and receive CAN frames. A [canable](https://canable.io/) or similar connected to the CAN bus of the SAME54-XPRO should be able to receive the frames send, and send frames that should be received by the shell app.
Supersedes https://github.com/RIOT-OS/RIOT/pull/21203 with a better approach.
=> cpu/samd5x: add enable pin to CAN configuration

pkg/uwb-dw1000/doc.md, pkg/uwb-dw1000/doc.txt
This PR applies the migration from `doc.txt` to `doc.md` discussed in #21220.
Also it fixes the include, which showed the included `README.md` as a text/code block instead of properly parsing the Markdown.
Current master:
With this PR:
Build the documentation and check that it looks alright.
NOTE: The Workflow CI still uses Doxygen 1.9.1, which does not handle the `includedoc` command properly, so the Markdown file is still not recognized.
The include was corrected in #20440 (my second PR in RIOT actually :D ), but it still used the wrong include type (and Doxygen version < 1.10.0 did not successfully include Markdown files anyway).
=> pkg/uwb-dw1000: Move `doc.txt` to `doc.md`, use the correct include type

boards/seeedstudio-xiao-esp32c3/Kconfig, boards/seeedstudio-xiao-esp32c3/Makefile, boards/seeedstudio-xiao-esp32c3/Makefile.dep, boards/seeedstudio-xiao-esp32c3/Makefile.features, boards/seeedstudio-xiao-esp32c3/Makefile.include, boards/seeedstudio-xiao-esp32c3/doc.md, boards/seeedstudio-xiao-esp32c3/include/arduino_iomap.h, boards/seeedstudio-xiao-esp32c3/include/board.h, boards/seeedstudio-xiao-esp32c3/include/gpio_params.h, boards/seeedstudio-xiao-esp32c3/include/periph_conf.h
Add support for Seeed Studio ESP32C3 Xiao. See issue #21266.
Tested with the following examples:
- blinky
- gnrc_networking (Wi-Fi)
- nimble_gatt (Bluetooth)
=> Add support for Seeed Studio ESP32C3 Xiao

core/include/thread.h, core/thread.c
Errors in thread.c corrected:
- in thread_wakeup() the status of the function to be woken up is incorrectly set to TASK_RUNNING. Instead the task should be set to STATUS_PENDING here, as only sched_run() is allowed to set a task to TASK_RUNNING.
- in thread_create() it is checked whether the stack is large enough, but instead of aborting the function if the stack is too small and thus preventing a buffer overflow, only a debug output is made. Return statement added
- in thread_state_to_string() it is not checked whether state is within the valid range, so that in the event of an error an invalid memory address is returned, which in turn leads to further invalid memory accesses when the string is output. thread_state_to_string() is used in particular by ps(). In the case of a corrupt …
=> core/thread: error in thread.c corrected

sys/malloc_monitor/doc.txt
In the description the compiler switch -D is missing for setting the corresponding macro
Only documentation, no test necessary
No Issue available
=> sys/malloc_monitor: Fix documentation

tests/pkg/relic/main.c
This PR adds two tests to Relic library, concerning Paillier encryption:
- generation of Paillier public key pair and simple encryption and decryption,
- generation of Paillier public key pair, data encryption and addition of encrypted data.
Unfortunately, currently only 512 bit Paillier encryption works - in following weeks I try to figure out why longer keys leads to 
stack smashing. I tested native with 256 MiB of memory and stack smashing error appears. 
Run `tests/pkg/relic` and check if all tests are successful.
None
=> tests/pkg/relic: add Paillier encryption tests

drivers/mtd_sdmmc/mtd_sdmmc.c, drivers/sdmmc/sdmmc.c
Do not rely on `init_done` of `sdmmc_dev_t` because it could have been repowered (properly or improperly).
=> drivers/{mtd_sdmmc,sdmmc}: reinit card

pkg/lwip/contrib/sock/ip/lwip_sock_ip.c, pkg/lwip/contrib/sock/tcp/lwip_sock_tcp.c, pkg/lwip/contrib/sock/udp/lwip_sock_udp.c, pkg/openwsn/sock/openwsn_sock_udp.c, pkg/tinydtls/contrib/sock_dtls.c, sys/include/net/sock/async/event.h, sys/net/gnrc/sock/ip/gnrc_sock_ip.c, sys/net/gnrc/sock/udp/gnrc_sock_udp.c, sys/net/sock/async/event/sock_async_event.c
There's nothing preventing an async callback event from **any type of socket** to be enqueued and called after `sock_*_close()` is called. 
~This PR is **just a fix idea**. It only fixes it for UDP, but the problem is there for all kind of sockets. The principle should stay the same everywhere, but I don't know how to integrate it best to avoid code duplication.~
I added a call to `sock_event_close()` for all sockets that implement the async API.
~Also, this fix is probably racy if `sock_udp_close()` is not called from the same event queue, as the event is canceled after the sock is de-initialized. The sock is, however, at least still in scope.~
If I understand correctly, the RIOT socket API is not thread-safe. By this assumption, a socket used in async context **can only be safely closed …
=> net_sock_async_event: cancel async event on sock_*_close()

cpu/native/include/socket_zep.h, cpu/native/socket_zep/socket_zep.c, sys/include/net/ieee802154.h, tests/net/gnrc_sixlowpan_frag_sfr_congure_impl/tests/01-run.py
The radio HAL implementation of `socket_zep` was a bit off.
- `IEEE802154_RADIO_INDICATION_RX_DONE` must only be sent *after* the ACK was sent (if the frame contained an ACK request)
- there is now a 192µs delay between receiving a frame and sending the ACK. During this period received frames are discarded.
- read the frame into the RX buffer directly in `_socket_isr()` instead of fumbling around with `MSG_PEEK | MSG_TRUNC`
- delay sending frames for how long it would take to send the frame on 2.4 GHz O-QPSK
Build and run `examples/gnrc_networking` with `USE_ZEP=1`
Start the ZEP dispatcher with 80% transmission success probability:
```
echo "A B 0.8" | dist/tools/zep_dispatch/bin/zep_dispatch -t - :: 17754
```
`socket_zep` should now behave more like a real radio.
```
ping ff02::1
12 …
```
=> socket_zep: properly implement the radio HAL

dist/tools/pyterm/pyterm
Upon terminating pyterm any potentially spawned process (such as RIOT native) should be terminated as well. This could be done via sending a `SIGINT` to these processes.
Run any arbitrary RIOT application for RIOT native via `make term` and terminate `pyterm` (via `/exit` or `^C`).
Check if all RIOT native processes have been terminated.
Fixes #21307
=> pyterm: send SIGINT to the subprocess' child

Makefile.dep, boards/common/esp32s3/stdio_esp32s3_default.dep.mk, boards/common/makefiles/stdio_cdc_acm.dep.mk, boards/common/makefiles/stdio_tinyusb_cdc_acm.dep.mk, boards/esp32c3-wemos-mini/Makefile.dep, boards/esp32s3-box/Makefile.dep, boards/esp32s3-pros3/Makefile.dep, boards/esp32s3-usb-otg/Makefile.dep, boards/esp32s3-wt32-sc01-plus/Makefile.dep, boards/hamilton/Makefile.dep, boards/hip-badge/Makefile.dep, boards/pinetime/Makefile.dep, boards/ruuvitag/Makefile.dep, boards/thingy52/Makefile.dep, cpu/arm7tdmi_gba/Makefile, cpu/arm7tdmi_gba/Makefile.dep, cpu/native/Makefile.dep, examples/networking/misc/telnet_server/Makefile, examples/networking/misc/telnet_server/main.c, makefiles/pseudomodules.inc.mk, makefiles/stdio.inc.mk
Much like `netdev_default` or `vfs_default`, this adds a pseudo-module `stdio_default` with which boards can define their preferred method of doing stdio.
`examples/networking/misc/telnet_server` is updated to select the telnet stdio method in addition to the default stdio method.
=> boards: introduce `stdio_default`

boards/nucleo-f746zg/doc.md, boards/nucleo-f746zg/doc.txt
This PR updates `nucleo-f746zg` board doc page, by:
- adding board pinout,
- adding MCU table,
- renaming doc.txt to doc.md accordingly to the PR #21255.
Generate doc and check if everything looks good:
```
make doc
xdg-open ./doc/doxygen/html/group__boards__nucleo-f746zg.html 
```
PR #21255
=> boards/nucleo-f746zg: board doc update

cpu/native/include/async_read.h
`pid_t` is provided e.g. by `<sys/types.h>`. It seems that on glibc, `<stdlib.h>` will also provide `pid_t`. But this way it should work on both musl and glibc.
- Building now succeeds on musl (maribu tested this and pinky promises it did)
- Building still succeeds on glibc (Murdock will check this for us)
None
=> cpu/native: add missing include

boards/nucleo-f207zg/doc.md, boards/nucleo-f303ze/doc.md, boards/nucleo-f412zg/doc.md, boards/nucleo-f429zi/doc.md, boards/nucleo-f439zi/doc.md, boards/nucleo-f446ze/doc.md, boards/nucleo-f722ze/doc.md, boards/nucleo-f767zi/doc.md, boards/nucleo-l496zg/doc.md, boards/nucleo-l4r5zi/doc.md, boards/nucleo-l552ze-q/doc.md, boards/nucleo-u575zi-q/doc.md
This PR renames remaining `doc.txt` files to `doc.md` for Nucleo-144 boards accordingly to the PR #21255. 
Generate doc and check if everything is OK.
```
make doc
xdg-open ./doc/doxygen/html/group__boards__nucleo-f207zg.html 
xdg-open ./doc/doxygen/html/group__boards__nucleo-f303ze.html 
etc ...
```
PR #21255
=> boards/nucleo-144: rename doc.txt to doc.md

pkg/nimble/Makefile, pkg/nimble/patches/0001-port-npl-riot-add-svc_bas-config.patch
`pkg/nimble/Makefile.include` includes logic for the module, however the corresponding Make target is missing.
This produces the following error:
```
make[3]: *** No rule to make target 'nimble_svc_bas', needed by 'all'.  Stop.
```
=> pkg/nimble: Fix compilation with `USEMODULE += nimble_svc_bas`

pkg/fido2_tests/Makefile, pkg/fido2_tests/patches/0001-Adaptions-for-RIOT-FIDO2-CTAP.patch, sys/fido2/ctap/ctap.c, sys/fido2/ctap/ctap_utils.c, sys/include/fido2/ctap/ctap_utils.h, tests/sys/fido2_ctap/Makefile, tests/sys/fido2_ctap_hid/Makefile, tests/sys/fido2_ctap_hid/README.md
Update the fido2 test package to the latest version. Also fix a small bug in the GetAssertion & GetNextAssertion behavior which became apparent because a new test failed.
I ran all tests using the nrf5284dk and reached 100% with the ctap fix.
+ `/sys/sys/fido2_ctap`
=> Fido2 update tests

makefiles/docker.inc.mk
After https://github.com/RIOT-OS/riotdocker/pull/257 as requested by CI in https://github.com/RIOT-OS/RIOT/actions/runs/13591031011
static tests should succeed
=> makefiles: bump riotdocker [backport 2025.01]

Makefile.features, makefiles/dependency_resolution.inc.mk
During the development of #21332 I noticed that the `boards/Makefile.features` I introduced in #21327 does not work and unfortunately it is unlikely to ever work, because it suffers from the classic hen-and-egg problem.
The `$(RIOTBASE)/Makefile.features` (which includes $(RIOTBASE)/boards/Makefile.features) is included before the `$(RIOTBASE)/Makefile.dep` is included in the dependency check and before the dependencies are resolved, the Make system will check that there are not feature conflicts or errors.
https://github.com/RIOT-OS/RIOT/blob/e85269a830af1fb181db047964b4ce1b9198f1fa/Makefile.include#L407-L408
https://github.com/RIOT-OS/RIOT/blob/e85269a830af1fb181db047964b4ce1b9198f1fa/Makefile.include#L428-L429
https://github.com/RIOT-OS/RIOT/blob/e85269a830af1fb181db047964b4ce1b9198f1fa …
=> buildsystem: Fix `boards/Makefile.features` Inclusion

sys/include/net/nanocoap/link_format.h, sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/fs.c, sys/net/application_layer/nanocoap/link_format.c, sys/net/application_layer/nanocoap/sock.c, sys/shell/cmds/nanocoap_vfs.c, tests/net/gcoap_fileserver/Makefile.ci, tests/net/nanocoap_cli/Makefile.ci
How often have you been looking for a bug, and it felt like chasing a ghost because memory was messed up?
How often was it a buffer you have unsuspectingly increased in size, which was not `static`?
(The right answer is: Yes 😄) 
That's why non-`static` `uint8_t buffer[CONFIG_INCREASE_ON_DEMAND]` is likely a footgun. 
Most importantly, this PR makes that a response buffer for `nanocoap_link_format_get()` has to be user allocated.
I could have just made it `static`, but this would bring up a concurrency issue.
Secondly,  a buffer `[CONFIG_NANOCOAP_BLOCK_HEADER_MAX]` is added to `nanocoap_sock_t`.
This was before allocated in various `nanocoap` functions. I moved it to the socket because this is likely allocated in a user thread. Therefore the stack size of that user's thread is no longer …
=> nanocoap: avoid non `static` buffers of configurable size 

makefiles/cargo-targets.inc.mk
On some systems, `$(shell mkdir -p ~/.cargo/registry)` ended up not replacing `~` with the home directory, but rather created a directory named `~`.
The new approach should be a bit more robust.
The `~/.cargo` folder should now be created correctly across systems.
None
=> build system: create cargo folders more robustly

examples/networking/coap/nanocoap_server/Makefile, examples/networking/coap/nanocoap_server/README.md, examples/networking/coap/nanocoap_server/main.c
This PR enables LWIP IPv4 in `nanocoap_server`, as we have IPv4 enable in `tests/nanocoap_cli` (see PR #21314).
Enable LWIP IPv4 in `Makefile` by setting `LWIP_IPV4 ?= 1`, compile and execute example:
```
make all
./bin/native/nanocoap_server.elf tap0
main(): This is RIOT! (Version: 2024.04-devel-2305-g5f08f5-examples-nanocoap-lwip)
RIOT nanocoap example application
Waiting for address autoconfiguration...
{"IPv4 addresses": ["192.168.100.150"]}
```
Test if example responds to coap messages, for example:
```
$ coap-client-notls -m GET coap://192.168.100.150/riot/board
native
$ coap-client-notls -m GET coap://192.168.100.150/riot/ver
This is RIOT (Version: …
```
=> examples/nanocoap_server: enable LWIP IPv4 

core/include/stdio.h, cpu/avr8_common/avr_libc_extra/posix_unistd.c, cpu/native/syscalls.c, dist/tools/headerguards/headerguards.py, pkg/jerryscript/Makefile
So far `stdio_null` would just drop the stdio backend, all the expensive stdio formatting functions were still included.
This PR replaces all calls to `printf()` and friends with a no-op.
Build e.g. `tests/minimal` which uses `stdio_null`:
```
9256	    108	   1312	  10676	   29b4	/home/benpicco/dev/RIOT-2/tests/minimal/bin/same54-xpro/tests_minimal.elf
```
```
5140	    108	   1312	   6560	   19a0	/home/benpicco/dev/RIOT/tests/minimal/bin/same54-xpro/tests_minimal.elf
```
=> core: add stdio.h to replace stdout functions with stdio_null

doc.txt
Alternative to #21320. Quoting from there:
> #21170 added documentation about RIOT_FILE_RELATIVE and RIOT_FILE_NOPATH which were already considered obsolete in #18936.
@miri64 insisted on going through the normal deprecation process even for such previously non-publicly documented macros, so lets do that instead.
There are replacements for both macros as compiler built-ins from gcc 8/12 and clang 10/9.
Read the CI generated docs. Also check list of deprecated features.
#4053, #21320, #21170, #18936
=> doc: deprecate RIOT_FILE_* macros

cpu/stm32/periph/adc_f0_g0_c0.c
Most of the issue was described in #21222.
tl;dr: The initialization sequence was not entirely correct and at least for the STM32C0, changing the resolution did not work.
I rewrote the calibration and initialization sequence to follow the guides outlined in the reference manuals more closely.
It should be noted here that the reference manuals involve more steps and checks the newer the devices gets. The sequence for the F0 is very simple [1], for the G0 more complicated [2] and quite involved for the C0 [3].
~~Currently I don't have a STM32G0 nucleo, so the changes are untested for that family. Soon(ish) I'll buy one though.~~
It arrived and everything works as it should :)
Tested with:
Additional Tests:
~~I recommend to apply #21223 as well to check all resolutions at once.~~ The updated …
=> cpu/stm32{f0,g0,c0}: fix ADC initialization sequence

drivers/include/periph/timer.h, drivers/periph_common/timer.c, tests/periph/timer/main.c
This provides a helper function that builds upon the `periph_timer_query_freqs` feature to find the frequency supported by a given timer that is closest to a given target frequency.
This functionality isn't as straight forward to implement, as a naive implementation iterating over all supported pre-scalers will be prohibitively expensive when the pre-scaler register is 16 bit or even 32 bit wide.
Instead, a binary search is performed plus some corner case handling in case the target frequency cannot exactly be met, in which it is checked if the highest frequency below the target or the smallest above the target is closer.
The test app was extended:
```
git:(timer_get_closest_freq) ~/Repos/software/RIOT/master/tests/periph/timer ➜ make BOARD=nucleo-f429zi flash test
Building application …
```
=> drivers/periph_timer: add `timer_get_closest_freq()`

cpu/stm32/Makefile.dep, cpu/stm32/periph/adc_f3.c, cpu/stm32/periph/adc_l4_wb.c, cpu/stm32/periph/adc_wl.c
This PR fixes some issues with the ADC of the STM32WL55 and the ADC of the STM32F3, L4 and WB series.
1) All: The ADC initialization routine used `ztimer` for an uncritical delay, which caused issues (a crash) when it was called from the early reset vector to check the battery status. I explained it here in greater detail: https://github.com/RIOT-OS/RIOT/pull/21235#issuecomment-2675469788
Using ztimer for an uncritical delay is not really necessary, especially since the intended delay is 20µs and if only `ZTIMER_MSEC` was available instead of `ZTIMER_USEC`, the delay was extended to 1ms.
I replaced it with busy_wait and added a factor of 2, because busy_wait is not really accurate. We can wait longer, but we shouldn't push our luck by waiting shorter.
This was present in the F3, L4, WB …
=> cpu/stm32{f3,l4,wb,wl}: Replace ztimer with busy_wait, fix VBat sampling time and {wl only} fix initialization sequence

cpu/stm32/periph/adc_f2.c
During the testing of #20971 I noticed that the sampling time for reading VBat is insufficient. This happened on other platforms as well, apparently I did not test the F2 yet...
To test this PR, #20971 has to be applied as well, otherwise the sampling will freeze after the zero-th to second sampling due to incorrect resolution settings (I guess?).
With current `master`:
```
cbuec@W11nMate:~/RIOTstuff/riot-stm32adc/RIOT$ BOARD=nucleo-f207zg USEMODULE+=periph_vbat  make -C tests/periph/vbat flash term -j12
make: Entering directory '/home/cbuec/RIOTstuff/riot-stm32adc/RIOT/tests/periph/vbat'
Building application "tests_vbat" for "nucleo-f207zg" with CPU "stm32".
"make" -C /home/cbuec/RIOTstuff/riot-stm32adc/RIOT/pkg/cmsis/
"make" -C /home/cbuec/RIOTstuff/riot-stm32adc/RIOT/boards
"make" -C …
```
=> cpu/stm32f2: Fix Sampling Time for VBat

cpu/stm32/include/periph/c0/periph_cpu.h, cpu/stm32/include/periph/f0/periph_cpu.h, cpu/stm32/include/periph/f2/periph_cpu.h, cpu/stm32/include/periph/f3/periph_cpu.h, cpu/stm32/include/periph/f4/periph_cpu.h, cpu/stm32/include/periph/f7/periph_cpu.h, cpu/stm32/include/periph/g0/periph_cpu.h, cpu/stm32/include/periph/l0/periph_cpu.h, cpu/stm32/include/periph/l1/periph_cpu.h, cpu/stm32/include/periph/l4/periph_cpu.h, cpu/stm32/include/periph/wb/periph_cpu.h, cpu/stm32/include/periph/wl/periph_cpu.h, cpu/stm32/periph/adc_f0_g0_c0.c, cpu/stm32/periph/adc_f2.c, cpu/stm32/periph/adc_f3.c, cpu/stm32/periph/adc_f4_f7.c, cpu/stm32/periph/adc_l0.c, cpu/stm32/periph/adc_l1.c, cpu/stm32/periph/adc_l4_wb.c, cpu/stm32/periph/adc_wl.c
This PR is based on #20780.
The different implementations for the STM32 ADCs had wildly different styles of defining (in `cpu/stm32/include/periph/xx/periph_cpu.h`) and checking the resolution flags (in `cpu/stm32/periph/adc_xxx.c` ).
The c0 and g0 did not define the `adc_res_t` structure at all, so the generic fallback from `drivers/include/periph/adc.h` was used. However it appears that this did not set the right flags, because for example the value for 6-bit resolution from the generic structure is `00` whereas it should be `(0x3 << 3)`. Even worse, for higher resolutions, the DMA bits would be set instead of the resolution bits.
I did not check it yet, but it seems like the c0 and g0 STM32s were always stuck in 12-bit mode with the current code.
This PR makes all `adc_res_t` structure …
=> cpu/stm32: Make ADC Resolution Definition uniform

tests/unittests/README.md
This patch updates the example given to conform to the recomended placement of include guards.
This document is not yet part of the Doxygen output, and therefore does not show up in the doc preview. Testing can be done by viewing the document in Github's file viewer [here](https://github.com/Enoch247/RIOT/blob/fix-unittests-example/tests/unittests/README.md).
See issue #21335
=> tests/unittests: if include guards in doc example

sys/bcd/Makefile, sys/bcd/bcd.c, sys/include/bcd.h, sys/include/string_utils.h, sys/libc/string.c, tests/unittests/tests-bcd/Makefile.include, tests/unittests/tests-bcd/tests-bcd.c, tests/unittests/tests-libc/tests-libc.c
This adds two helper functions to the `string_utils` library:
- a `reverse_buf()` that inverts the order of bytes in an array
- a `bcd_buf_from_u32()` that takes a number `a` and calculates a number `a'` so that the hex string representation of `a'` is the same as the decimal string representation of `a`. e.g. ` bcd_buf_from_u32(123)` would produce `0x123`.  
This can be used to to generate pretty MAC / IP addresses from decimal serial numbers:
```C
static inline int _get_eui64(uint8_t index, eui64_t *addr)
{
memset(addr, 0, sizeof(*addr));
int res = bcd_buf_from_u32(device_get_serial(), addr, sizeof(*addr));
if (res < 0) {
return res;
}
addr->uint8[res] = index;
reverse_buf(addr, sizeof(*addr));
eui64_set_local(addr);
return 0;
}
```
```
2025-03-20 10:43:11,323 # Iface  8  HWaddr: 17:12 …
```
=> sys/bcd: add bcd_buf_from_u32()

.github/labeler.yml
As per the title.
Look at the change, see that it's good.
Noticed at https://github.com/RIOT-OS/RIOT/pull/20023#event-17112144771
Fixup after #21242
=> .github/labeler: recognize boards/common/native as native

sys/Makefile.dep, sys/include/event.h
This adds a pseudo-module that prints execution times of event handlers.
This can be useful to find out which event handler is hogging the event thread. 
Enable the `event_loop_debug` module
```
2025-04-03 11:45:49,355 # main(): This is RIOT! (Version: 2024.10-devel-138-gf3a9392-event_loop_debug)
2025-04-03 11:45:49,361 # event: executing 0x8059dfc->0x804cc0a
2025-04-03 11:45:49,362 # event 0
2025-04-03 11:45:49,362 # event: 0x8059dfc took 6 µs
2025-04-03 11:45:49,864 # event: executing 0x8059e3c->0x804cc0a
2025-04-03 11:45:49,864 # event A
2025-04-03 11:45:49,865 # event: 0x8059e3c took 6 µs
2025-04-03 11:45:50,363 # event: executing 0x8059e7c->0x804cc0a
2025-04-03 11:45:50,364 # event B
2025-04-03 11:45:50,365 # event: 0x8059e7c took 5 µs
2025-04-03 11:45:50,366 # event: executing …
```
=> sys/event: add `event_loop_debug` pseudo-module

boards/telosb/Makefile.include, boards/telosb/doc.txt
The stdio UART symbol rate is configured to 9600 Bd, and not to 115200 Bd. This updates `make term` and the doc to match what is implemented.
```
make BOARD=telosb flash term
```
Should now work again
Regression introduced in b51ea4ca2422ac0f024fb4c22b662459d34fa7cc
=> boards/telosb: fix stdio_uart symbol rate

Makefile.include
@maribu described a bug in #20948 that `native` will experience a race condition when compiling with multiple threads and directly calling the terminal, causing the terminal to execute an old file or other weird behavior.
The reason for that is that `term` does not have any `$(TERMDEPS)` in `native`, because `native` does not have to be flashed.
Therefore Make wants to "build" the `term` goal parallel to the `all` goal, which leads to the described race condition.
Some information about `.NOTPARALLEL`: https://www.gnu.org/software/make/manual/html_node/Parallel-Disable.html
(How could anyone work with `native` with that bug? That's annoying AF and I thought I was crazy when working on the isrpipe PR 🤣 )
1) Compile a program of your liking with multiple threads: `make -C tests/sys/shell …
=> buildsystem: Set `term` Goal to NOTPARALLEL

sys/include/net/ipv6/addr.h
This makes the header a lot more readable and `clang -Wdocumentation` happy, which does not like HTML tags (`<a href="...">...</a>`) to contain random line breaks.
The Doxygen output should still contain the same links as before.
(I tested this with Doxygen `1.14.0 (75f8cf7020304421786ec3ab3aaea99de7c49354)` locally, where it worked. But let's see if the one in the CI also likes this.)
None
=> sys/net/ipv6: use markdown links in doc

makefiles/cflags.inc.mk, makefiles/toolchain/gnu.inc.mk
This enables warnings for incorrect Doxygen comments when build with LLVM. To my experience, LLVM provides a low false positive rate (e.g. it does not complain about undocumented internal macros) and has very helpful output.
This disable `-Wdocumentation-deprecated-sync` for now, as we do not deprecate code with attributes yet.
The warnings are not set as errors, so that we can enable this without breaking builds.
```
make TOOLCHAIN=llvm BOARD=<SOME_BOARD> -C <path/to/some/app>
```
Should now warn about broken doc
None
=> buildsystem: Enable -Wdocumentation for LLVM

makefiles/info.inc.mk
@mguetschow documented in #21019 that the `info-build` target does not show the all the boards that are *actually* supported, depending on the board that is set on the command line.
The reason for this is that the Make system creates a lot of environment variables and hands them down to the next instance. In this case, the `FEATURES_REQUIRED` variable was set and had some requirements that not all of the supported boards could fulfill, therefore they were (errorneously) sorted out.
Therefore this PR starts the submake in a clean environment, so that Make is not influenced by what's set by the parent.
With `master`:
```
$ BOARD=feather-nrf52840-sense make -C tests/drivers/nrf802154 info-build 
...
supported boards:
adafruit-clue adafruit-itsybitsy-nrf52 arduino-nano-33-ble …
```
=> buildsystem: Fix Supported Board List in `info-build`

examples/networking/coap/nanocoap_server/coap_handler.c, sys/Makefile.dep, sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/sock.c, tests/net/nanocoap_cli/Makefile, tests/net/nanocoap_cli/nanocli_client.c
A new `observe` command was added to `tests/net/nanocoap_cli`:
```
> observe coap://[fe80::d07c:7cff:fe6d:9441]/time
2025-01-23 16:25:24,793 # 00000000  32  37  36  32  30  0A
2025-01-23 16:25:25,175 # 00000000  32  38  30  30  32  0A
2025-01-23 16:25:26,174 # 00000000  32  39  30  30  31  0A
2025-01-23 16:25:27,175 # 00000000  33  30  30  30  31  0A
2025-01-23 16:25:28,175 # 00000000  33  31  30  30  32  0A
2025-01-23 16:25:29,173 # 00000000  33  32  30  30  31  0A
2025-01-23 16:25:30,173 # 00000000  33  33  30  30  31  0A
2025-01-23 16:25:31,175 # 00000000  33  34  30  30  31  0A
2025-01-23 16:25:32,175 # 00000000  33  35  30  30  32  0A
2025-01-23 16:25:33,175 # 00000000  33  36  30  30  32  0A
2025-01-23 16:25:34,173 # 00000000  33  37  30  30  31  0A
2025-01-23 16:25:35,173 # …
```
=> nanocoap_sock: implement observe (Client-Side)

pkg/lwip/contrib/sock/udp/lwip_sock_udp.c, sys/net/gnrc/sock/udp/gnrc_sock_udp.c
`sock_udp_create()` leaves some fields (e.g. `reg.async_ctx`) uninitialized.
This blows up when accessing the field later as introduced by #21180
Just bring the whole `sock` struct to a sane state on init to avoid this. 
fixes issue described in https://github.com/RIOT-OS/RIOT/pull/21180#discussion_r2027268460
=> gnrc_sock/udp: zero-init sock struct on create

cpu/samd5x/periph/can.c
This makes the can initialization for the samd5x more stable 
- init: just write values not change them from an unknown state 
- setup clock: follow the Peripheral Channel Control setup method described in 14.6.3.3 of the SAM D5x/E5x Family datasheet.
find a Board that uses this cpu but has sight problems of getting the can bus up reliably 
find its more reliable with this Patch
[SAM D5x/E5x Family datasheet](https://ww1.microchip.com/downloads/aemDocuments/documents/MCU32/ProductDocuments/DataSheets/SAM-D5x-E5x-Family-Data-Sheet-DS60001507.pdf) page 144 (DS60001507M) 14.6.3.3
=> cpu/samd5x: improve can-initialization

Makefile, dist/tools/doxygen/.gitignore, dist/tools/doxygen/Makefile, doc/doxygen/Makefile
This is an alternative approach for #21295. Instead of trying to handle Doxygen inside of the Docker container, we just add Doxygen as a package in RIOT. Therefore it can be managed inside the RIOT repository.
The changes to the CI script(s) are minimal, only the target has to be changed from `make doc` to `make doc-ci` and Doxygen does not have to be installed as a package anymore (but it could be so that all dependencies are there).
~~TODO: It would probably be a good idea to pass the `DOXYGEN_MIN_VERSION` from `doc/doxygen/Makefile` to `dist/tools/doxygen/Makefile`, so that we really truly only have one single spot where the Doxygen version is maintained.~~ Done.
RFC: Would it be better to build Doxygen instead of downloading the binaries? IMO that would add a lot of unncessary compile …
=> dist/tools: Add Doxygen as a Tool for CI

drivers/include/lis2dh12.h, drivers/lis2dh12/lis2dh12.c, tests/drivers/lis2dh12/main.c
The return value of `lis2dh12_wait_event` is a 24-bit mask.
An `int` is not necessarily 32 bits.
If it really would have been an issue in practice, I think the compiler should have thrown a warning for any architecture.
=> drivers/lis2dh12: int32_t lis2dh12_wait_event()

dist/tools/headerguards/headerguards.py
The headerguards static check currently does not know anything about `#pragma once`. However in #21335, the consensus was reached to use `#pragma once`, the static test should not fail for it.
1) Add a `#pragma once` to a header of your choice that already has the classic include guards (without removing them): the static test `./dist/tools/headerguard/check.sh` should fail.
2) Remove the classic include guards, the static test `./dist/tools/headerguard/check.sh` should not fail.
=> dist/tools: add `#pragma once` to headerguard check

CODING_CONVENTIONS.md
As discussed in the previous to last VMA and last weekly, let's allow and promote `#pragma once` usage instead of header guards. Also see #21335
Read the coding convention.
#21367
=> CODING_CONVENTION.md: migrate to `#pragma once`

cpu/esp32/Makefile, cpu/esp32/stdatomic.c, pkg/jerryscript/Makefile, pkg/utensor/Makefile.include
This PR provides some small fixes of compile problems with the latest Espressif toolchain (GCC v14.2).
Compilation with used Espressif toolchain (GCC v12.2) should still work in CI.
=> cpu/esp32: Fixes of compile problems with GCC 14.2 [backport 2025.01]

drivers/include/periph/adc.h, drivers/sdmmc/sdmmc.c, drivers/sdmmc/sdmmc_sdhc.c, pkg/fatfs/fatfs_diskio/mtd/mtd_diskio.c, sys/ecc/hamming256.c, sys/hashes/md5.c, sys/include/bloom.h, sys/include/net/nanocoap_sock.h, sys/include/senml.h, sys/net/gnrc/netif/gnrc_netif.c, sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h, sys/newlib_syscalls_default/syscalls.c, tests/unittests/tests-ztimer64/tests-ztimer64-core.c
This fixes a number of documentation issues that LLVM/clang would flag with `-Wdocumentation`.
Compile e.g. `tests/unittests` with `TOOLCHAIN=llvm`. In `master`, lots of warnings will be produced. With this applied, the number of warnings should reduce (down to zero on latest Ubuntu LTS, but newer LLVM versions may find more issues not addressed here).
None
=> tree-wide: mixed back of documentation fixes

makefiles/docker.inc.mk
This updates the tagged container due to the merge of https://github.com/RIOT-OS/riotdocker/pull/255
Green CI
https://github.com/RIOT-OS/riotdocker/pull/255
=> makefiles/docker.inc.mk: bump tagged container [backport 2025.01]

makefiles/pseudomodules.inc.mk, sys/malloc_thread_safe/malloc_wrappers.c
use module `malloc_monitor` with verbose configuration instead
CI should catch errors
Deprecated and scheduled for removal after 2024.07 in https://github.com/RIOT-OS/RIOT/pull/20363
=> sys/malloc_tracing: remove deprecated module

drivers/include/mtd_default.h, pkg/flashdb/include/fal_cfg.h, sys/fido2/ctap/ctap_mem.c
use `mtd_dev_get()` instead
CI should catch errors.
deprecated more than a year ago in https://github.com/RIOT-OS/RIOT/pull/20078
=> drivers/mtd_default: remove deprecated `mtd_default_get_dev()`

sys/include/vfs.h, sys/vfs/vfs.c
use `vfs_iterate_mount_dirs()` instead
CI should catch problems.
deprecated in https://github.com/RIOT-OS/RIOT/pull/17660
=> sys/vfs: remove deprecated `vfs_iterate_mounts()`

sys/include/net/gcoap.h
Use alias `gcoap_req_send()` instead
CI should catch if there are still any remaining in-tree users.
Deprecated in https://github.com/RIOT-OS/RIOT/pull/20514
=> sys/net/gcoap: remove deprecated gcoap_req_send_tl()

examples/lang_support/official/rust-async/Cargo.lock, examples/lang_support/official/rust-gcoap/Cargo.lock, examples/lang_support/official/rust-hello-world/Cargo.lock, sys/rust_riotmodules_standalone/Cargo.lock, tests/rust_minimal/Cargo.lock
diff generated with `find -name Cargo.toml -exec cargo update --manifest-path "{}" --package riot-wrappers --package riot-sys ";"` according to https://github.com/RIOT-OS/RIOT/blob/master/doc/guides/managing-a-release/README.md?plain=1#L31
see what CI says
upcoming release version bump similar to https://github.com/RIOT-OS/RIOT/pull/21133
=> treewide: update riot-wrappers and riot-sys

cpu/native/Makefile.include, pkg/libsocketcan/Makefile, sys/Makefile.dep, sys/can/Makefile.dep
This fixes two related compilation issues when using the `can` module under native:
1. `can/can.h` from the `can` module includes `libsocketcan.h` from the `libsocketcan` package on `native%`, but does not depend on it. The missing dep is added
2. The `libsocketcan` package does not compile with the `posix_headers` package is used, as it really needs to include the host headers. The `INCLUDES` variable is stripped of the posix headers include path locally within the package's `Makefile` (so with no side-effect on other packages and modules).
```
$ USEMODULE=posix_headers BOARD=native64 RIOT_CI_BUILD=1 make -C tests/drivers/candev
```
Will fail spectacularly on `master`, but work fine with this PR.
None
=> sys/can: fix compilation issues under native

sys/include/ztimer/config.h
This patch adds a hint to users for how to set `CONFIG_ZTIMER_USEC_ADJUST_SLEEP`. The doc for `CONFIG_ZTIMER_USEC_ADJUST_SET` already contained a similar hint.
no code change
non known
=> sys/ztimer: add hint for setting static sleep adjustment

sys/include/isrpipe.h, sys/include/isrpipe/read_timeout.h, sys/include/tsrb.h, sys/isrpipe/isrpipe.c, tests/unittests/tests-isrpipe/Makefile, tests/unittests/tests-isrpipe/Makefile.include, tests/unittests/tests-isrpipe/tests-isrpipe-read_timeout.c, tests/unittests/tests-isrpipe/tests-isrpipe.c, tests/unittests/tests-isrpipe/tests-isrpipe.h
This PR originally started out as a fix to isrpipe's init of it's mutex, but it grew into adding unit tests and improving its doc as well. I also improved some doc for `tsrb`. I can break that into a separate PR if you desire.
``` bash
make -C tests/unittests/ tests-isrpipe test
```
None known
=> sys/isrpipe: unit tests, doc, and fix init

sys/psa_crypto/include/psa_ciphers.h, sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h, sys/psa_crypto/include/psa_crypto_location_dispatch.h, sys/psa_crypto/include/psa_ecc.h, sys/psa_crypto/include/psa_hashes.h
This drops a lot of "no-op" Doxygen statements, such as `@param foo <description>` where `<description>` is the empty string.
This now also provides no documentation, but a lot more compact.
The generated documentation should not contain any documentation about the parameters, but the headers should be a lot shorter.
None
=> sys/psa_crypto: drop no-op Doxygen statements

sys/fmt/fmt.c, sys/include/fmt.h, tests/periph/rtc/Makefile, tests/periph/rtc/main.c, tests/unittests/tests-fmt/tests-fmt.c
Because I have already copied the code to print a `struct tm` too often, I now added it to the `fmt` module.
`make -C tests/unittests tests-fmt flash term`
```
2025-04-08 18:20:25,437 # RIOT native interrupts/signals initialized.
2025-04-08 18:20:25,438 # RIOT native64 board initialized.
2025-04-08 18:20:25,438 # RIOT native hardware initialization complete.
2025-04-08 18:20:25,438 # 
2025-04-08 18:20:25,438 # main(): This is RIOT! (Version: 2025.04-devel-449-g3c6492-pr/fmt_time)
2025-04-08 18:20:25,438 # .................................
2025-04-08 18:20:25,438 # OK (33 tests)
2025-04-08 18:20:25,438 # 
2025-04-08 18:20:25,438 # native: exiting
2025-04-08 18:24:17,364 # Exiting Pyterm
```
#21343
=> sys/fmt: add {fmt,scn}_time_tm_iso8601

examples/networking/coap/nanocoap_server/Makefile, examples/networking/coap/nanocoap_server/main.c
This PR fix small typo in the LWIP interface - in the current code is `ET0aa` should be `ET0`.
Run `nanocoap_server` for LWIP IPv4 (set `LWIP_IPV4 ?= 1`in `Makefile`) and check if printed IPv4 address received from DHCP server is correct.
Without this PR some strange/random addresses are shown.
PR #21333 - added fixed code
=> examples/nanocoap_server: fix typo in LWIP interface name

doc/doxygen/src/getting-started.md
This patch adds the missing required `psutil` package to the getting started guide. This requirement was introduced in commit 0de3b8a7d8ad68371669ac769810ba7bd0a2ee0c.
Check that psutil is now mentioned in the [Getting Started Guide](https://doc.riot-os.org/getting-started.html) once this PR is merged.
`psutil` was added as a requirement for `pyterm` in #21309
=> doc: add psutil requirement to  Getting Started

boards/common/native/board_init.c, boards/common/native/doc.md
board/native: set env TZ to UTC by default
also fix the failing minema test - that assumend to be run in Berlin/Paris/Hamburg/Rom/Wien
most (all) embedded libc do not care for TZ and time functions don't do timezone conversion,
making native  use UTC for time.h functions does the same
you can still force localtime timezone  
- `TZ=":/etc/localtime" <elf_file>` or  
- `TZ=":/etc/localtime" make term or test` or 
- `export TZ=":/etc/localtime"` or 
or another timezone 
- `export TZ="LEET+1:33:7"`  (timezone name and offset from UTC optional DST
-  see man timezone for TZ specifier (not all of it is supported  by new/picolib(c)
run the minema test in Berlin and see that the time stamp is now UTC
#20018 #20005
=> board/native: set TZ to UTC by default

tests/bench/runtime_coreapis/Makefile, tests/bench/runtime_coreapis/Makefile.ci, tests/bench/runtime_coreapis/main.c, tests/bench/runtime_coreapis/tests/01-run.py
This adds a benchmark for clist_sort() and calls that on three different list sizes.
Run the benchmark and check whether the run times are plausible.
None
=> tests/bench/runtime_coreapis: add clist_sort() benchmark

pkg/esp32_sdk/patches/0037-driver-rtc_io-correct-declaration-of-renamed-functio.patch, pkg/esp32_sdk/patches/0038-newlib-avoid-sys-uio.h-inclusion-outside-of-RIOT.patch
This PR includes two `esp32_sdk` patches to ensure that the RIOT-bundled ESP-IDF remains compatible when used independently of the RIOT environment.
These changes are minimal and isolated, and they make the RIOT-patched ESP-IDF usable when ESP-IDF is used directly.
**1. [driver/rtc_io] Fixes an incorrect function declaration in ESP-IDF `components/driver/include/driver/rtc_io.h`.**
The implementation was renamed in [0022-driver-gpio-fix-undefined-reference-to-rtc_gpio_forc.patch](https://github.com/RIOT-OS/RIOT/blob/master/pkg/esp32_sdk/patches/0022-driver-gpio-fix-undefined-reference-to-rtc_gpio_forc.patch) as follows:
* From: `rtc_gpio_force_hold_all()`
* To: `rtc_gpio_force_hold_en_all()`
However, the declaration in the header file was not updated accordingly.
This patch corrects the …
=> pkg/esp32_sdk: Fix broken `rtc_io.h` declaration and prevent `sys/uio.h` inclusion outside RIOT

core/lib/include/cib.h
Users of CIB may easily be mislead to believing that it is generally thread safe, or at least thread safe as long as there is a single consumer and producer. Neither is the case, which now is clearly communicated in the API doc.
The generated API should now make it clear that CIB is not thread safe. It should especially be clear that thread safety cannot even be assumed in special cases (such as single consumer, single producer, inherently atomic access to `unsigned int`), but requires the caller to ensure exclusive access to `cib_t` under any circumstances.
See e.g. https://github.com/RIOT-OS/RIOT/pull/21400 for an example where the calling side got their feet shot.
=> core/cib: Add a prominent warning about thread safety

core/include/msg.h, core/msg.c
This now ensures race-free access to the CIB tracking the number of messages queued in the ringbuffer for a given thread.
In addition, `msg_avail_thread()` now checks if the provided pid refers to a thread that is currently existing.
- Tests of `msg_avail()` should still pass
- `msg_avail_thread()` and `msg_avail()` should no longer be racy
None
=> core/msg: fix `msg_avail_thread()` and `msg_avail()`

cpu/samd5x/include/candev_samd5x.h, cpu/samd5x/periph/can.c
This expose a few more configuration knobs, namely:
- automatic retransmission of failed CAN frames
- transmit pause
- monitoring mode
Run `tests/drivers/candev` after playing with can config and confirm that the new configuration is applied
None
=> cpu/samd5x/periph_can: Expose more CAN controller configs

core/include/msg.h, core/msg.c
Rather than using an `assert()` on `thread_get()`, check for the thread to exist and return a capacity of `0` if it does not.
This fixes compilation with `-fanalyzer` with `NDEBUG` defined, is more consistent with other core APIs, and makes the API usable for threads with a dynamic life cycle.
> [!NOTE]
> I marked this both as API change and as minor, as the API does not change for any user that did not run into a blowing assertion (or a `NULL` dereference with `NDEBUG`) before. The API is changed in that those cases previously being forbidden are now are allowed.
Green CI
None
=> core/msg: handle error in msg_queue_capacity()

Makefile, dist/tools/benchmark_udp/Makefile, dist/tools/cc2538-bsl/Makefile, dist/tools/cosy/Makefile, dist/tools/dose/Makefile, dist/tools/ethos/Makefile, dist/tools/fixdep/Makefile, dist/tools/kconfiglib/Makefile, dist/tools/lpc2k_pgm/Makefile, dist/tools/pioasm/Makefile, dist/tools/riotboot_gen_hdr/Makefile, dist/tools/riotboot_serial/Makefile, dist/tools/sliptty/Makefile, dist/tools/teensy-loader-cli/Makefile, dist/tools/tunslip/Makefile, dist/tools/uf2/Makefile, dist/tools/uhcpd/Makefile, dist/tools/zep_dispatch/Makefile, makefiles/app_dirs.inc.mk
@mguetschow noticed that `make distclean` does not clean `dist/tools`. The cause is described in #21409.
Make sure that the `clean` and `distclean` actually enter the `dist/tools` subdirectory. This can take quite a while.
```
cbuec@W11nMate:~/RIOTstuff/riot-canfix/RIOT$ time make clean --print-directory 2>/dev/null | grep -i dist/to
ols
make[1]: Entering directory '/home/cbuec/RIOTstuff/riot-canfix/RIOT/dist/tools/benchmark_udp'
make[1]: Leaving directory '/home/cbuec/RIOTstuff/riot-canfix/RIOT/dist/tools/benchmark_udp'
make[1]: Entering directory '/home/cbuec/RIOTstuff/riot-canfix/RIOT/dist/tools/bootterm'
rm -f /home/cbuec/RIOTstuff/riot-canfix/RIOT/dist/tools/bootterm/bt
make[1]: Leaving directory '/home/cbuec/RIOTstuff/riot-canfix/RIOT/dist/tools/bootterm'
make[1]: Entering directory …
```
=> buildsystem: clean `dist/tools` with `(dist)clean` as well, parallel cleaning!

core/include/thread.h, tests/net/gnrc_netif/main.c
This fixes compilation with `-fanalyzer`. We use `assume()` to signal GCC that `thread` must not be null in `NDEBUG` mode, and `assert()` it in with enabled assertions.
This also drops the `volatile` qualifier from the function argument and changes the return value to `bool`.
> [!NOTE]
> I've marked this as an API change because it technically is. But calling sides from C that did use the API correctly will just continue to compile and work as before.
- Calling sides from C code should not be affect. If rust code uses this, the CI will spot it
- Compiling with `-fanalyzer` of `tests/sys/entropy_source` should now almost work
None
=> core/thread: fix thread_has_msg_queue()

sys/include/embUnit.h, sys/include/embUnit/embUnit.h
This will fix false positives for unused includes in the unit tests with clangd.
Run
```
make -C tests/unittests compile-commands
```
Then open a unit test such as `tests/unittests/tests-core/tests-core-clist.c` in an editor that uses `clangd` as language server. In `master`, this will complain about `#include "embUnit.h"` in line 12 being unused, with this PR it will not.
This is adds comments only, it will not affect any machine code.
None
=> sys/embUnit: add IWYU pragmas

sys/include/suit/transport/worker.h, sys/suit/transport/worker.c
`suit_worker_trigger()` might be triggered from e.g. a CoAP endpoint or an event thread were we do not want to block for an extended period of time.
Replace the `mutex_lock()` with a `mutex_trylock()` to return immediately if a worker thread is already running.
=> sys/suit: don't block in suit_worker_trigger()

examples/advanced/suit_update/Makefile
@benpicco discovered a regression introduced by #21242 that the `examples/advanced/suit_update` example does not compile when the BOARD is set to `native`. It does work with `native64` though.
See: https://github.com/RIOT-OS/RIOT/pull/21242#issuecomment-2822327207
The reason is that the Makefiles for the example use the `BOARD` variable before the alias is applied to create a path, which becomes invalid once the alias is applied by `makefiles/board_alias.inc.mk`.
This PR swaps the includes of the global `Makefile.include` with the local makefile that uses the `BOARD` variable to make sure the alias is applied before using the `BOARD` variable.
Current `master` with `native`:
```
cbuec@W11nMate:~/RIOTstuff/riot-suit/RIOT$ BOARD=native make -C examples/advanced/suit_update
make: Entering …
```
=> examples/suit_update: fix compilation for `native`

sys/shell/cmds/vfs.c
Permission flags of `0` lead to a file that can't be read by anyone. 
Run `tests/sys/vfs_default`. In master a `vfs w /nvm0/test.txt ascii o data` would produce
```
---------- 1 benpicco benpicco    2 Apr 23 16:06 test.txt
```
With this patch we get
```
-rw-r--r-- 1 benpicco benpicco    4 Apr 23 16:25 test2.txt
```
=> shell/vfs: set proper file permissions

tests/unittests/tests-core/tests-core-clist.c
- Iterate of different lengths of unsorted data to also cover corner case one-item list
- Actually check that the list is sorted afterwards (and not just that the maximum got sorted in last)
- Actually check that the list was stable-sorted (as the API doc promises a stable sort)
- The unit tests should pass
- Mess with the sorting algorithm, check that the test stops passing
None
=> tests/unittests/tests-core-clist: improve unit test

dist/tools/headerguards/headerguards.py
When adding the #pragma once after a comment block, many editors will remain at the previous indentation level, adding a leading whitespace to the #pragma once. This is invalid, but causes the headerguards check to fail. Since it is a common issue, it warrants a separate check with a proposed solution, just like for other headerguard issues that are checked.
This came up in #21429 (here: https://github.com/RIOT-OS/RIOT/pull/21429#discussion_r2056845089 ) and previous Pull Requests while working on #21335.
Add a leading whitespace to the `#pragma once` of a header file of your liking (in this case I chose `core/include/msg.h`) and run the static test.
Current `master` (not very helpful):
```
cbuec@W11nMate:~/RIOTstuff/riot-suit/RIOT$ ./dist/tools/headerguards/check.sh
core/include/msg.h: …
```
=> dist/tools: add a leading whitespace check for `#pragma once` in the `headerguards` static test

examples/advanced/suit_update/Makefile
@benpicco discovered a regression introduced by #21242 that the `examples/advanced/suit_update` example does not compile when the BOARD is set to `native`. It does work with `native64` though.
See: https://github.com/RIOT-OS/RIOT/pull/21242#issuecomment-2822327207
The reason is that the Makefiles for the example use the `BOARD` variable before the alias is applied to create a path, which becomes invalid once the alias is applied by `makefiles/board_alias.inc.mk`.
This PR swaps the includes of the global `Makefile.include` with the local makefile that uses the `BOARD` variable to make sure the alias is applied before using the `BOARD` variable.
Current `master` with `native`:
```
cbuec@W11nMate:~/RIOTstuff/riot-suit/RIOT$ BOARD=native make -C examples/advanced/suit_update
make: Entering …
```
=> examples/suit_update: fix compilation for `native` [backport 2025.04]

.clang-tidy, .gitignore
This adds a default .clang-tidy configuration for additional linitng pleasure when using an editor with LSP support and clangd as language server.
A LSP enabled editor that uses clangd should now provide extra liniting pleasure, after `make compile-commands -C path/to/app` is used to create a `compile_commands.json`.
None
=> tools: add default .clang-tidy configuration

sys/include/atomic_utils.h
So far, the atomic utils only support known width integer types. This adds `unsigned int` to the supported list by mapping it to the corresponding fixed width integer type.
This also sneaks in a few minor style fixes that clang-tidy frowned upon.
This does not really add new functionality, but exposes the existing functionality under an alias that e.g. maps `atomic_store_unsigned()` to either `atomic_store_u64()`, `atomic_store_u32()`, or `atomic_store_u16` depending on the native width of `unsigned int`.
The code change is trivial, and easy to follow.
Could by used by https://github.com/RIOT-OS/RIOT/pull/21254 to simplify the code a bit and reducing the preprocessor use by just using `unsgined` for the flags, rather than `uint16_t` or `uint32_t` depending on the word size of the target …
=> sys/atomic_utils: add helpers for unsigned int

pkg/mpaland-printf/Makefile, pkg/mpaland-printf/Makefile.dep, pkg/mpaland-printf/Makefile.include, pkg/mpaland-printf/doc.md, pkg/mpaland-printf/mpaland-printf.mk, pkg/mpaland-printf/patches/0001-RIOT-integration.patch, pkg/mpaland-printf/patches/0002-Wrapper-targets-Add-endpoints-for-Wl-wrap.patch, pkg/mpaland-printf/patches/0003-RIOT-integration-Enable-floating-support-based-on-mo.patch, pkg/mpaland-printf/patches/0004-Fix-parsing-of-int8_t.patch, tests/sys/snprintf/Makefile, tests/sys/snprintf/Makefile.board.dep, tests/sys/snprintf/README.md, tests/sys/snprintf/main.c, tests/sys/snprintf/tests/01-run.py
This packs the stdio implementation from https://github.com/mpaland/printf as alternative to what the used standard C lib provides with the intent to provide a thread-safe, smaller, and more feature-complete alternative on newlib targets.
Compared to `newlib_nano` this reduces `.text` by a bit more than 200 B while adding support for standard format specifiers such as `RPIu8`, `PRIu16`, `PRIu64`, `%z`, and `%t`.
Note that `newlib_nano`'s stdio can be thread-safe in reentrant mode at the cost of RAM (per thread) and latency. Especially the increase in latency can be prohibitive when real time requirements need to be met.
[1]: https://github.com/mpaland/printf
A test application has been added in `tests/sys/snprintf`. This will use the package if `newlib` is used. It should pass, but …
=> pkg/mpaland-printf: Add alternative stdio as package

sys/include/string_utils.h
Currently the documentation only lists the [internal helper function](https://doc.riot-os.org/group__sys__string__utils.html#gadbe2d9857cb1488db63972bbd427fbce), not the actual `swprintf()` function.
Now the `swprintf` function gets properly documented:
=> sys/string_utils: make `swprintf()` appear in doc

pkg/micropython/Makefile
Fix the MicroPyhton pkg by casting an unused parameter.
The bug is revealed when using the MicroPython pkg and a header using pystack.h (E.g. `#include ‘py/runtime.h’`).
MicroPython code:
```c
#define m_renew(type, ptr, old_num, new_num) ((type*)(m_realloc((ptr), sizeof(type) * (new_num))))
static inline void *mp_nonlocal_realloc(void *ptr, size_t old_n_bytes, size_t new_n_bytes) {
return m_renew(uint8_t, ptr, old_n_bytes, new_n_bytes);
}
```
Error:
```bash
/home/test/RIOT/examples/micropython/bin/arduino-nano-33-ble/pkg/micropython/py/pystack.h:88:59: error: unused parameter 'old_n_bytes' [-Werror=unused-parameter]
/home/test/RIOT/examples/micropython/bin/arduino-nano-33-ble/pkg/micropython/py/pystack.h: In function 'mp_nonlocal_realloc':
88 | static inline void *mp_nonlocal_realloc(void …
```
=> pkg/micropython: bump version

drivers/Makefile.dep, drivers/doc.txt, drivers/sx126x/include/sx126x_params.h, makefiles/pseudomodules.inc.mk
Adds `shield_sx1262` analog to `shield_llcc68`.
=> drivers/sx126x: add `shield_sx1262`

sys/bcd/bcd.c, sys/include/bcd.h, tests/unittests/tests-bcd/tests-bcd.c
Add functions to 
- convert a BCD buffer to a `uint32_t`/`uint64_t`
- parse a string as BCD buffer
Unit-tests have been added for the new functions.
=> sys/bcd: add `bcd_buf_to_u32()` and `bcd_buf_from_str()`

cpu/nrf5x_common/periph/uart.c
Previously, uart_poweroff() and uart_poweron() were no-ops. This replaces them with the logic to indeed power on and power off the UART device.
- ideally, power consumption should be less after a call to `uart_poweroff()`
- beware: this is untested. however, at least a call to `uart_write()` while powered off would get stuck if not for the special handling, while before the UART remained fully operational when "powered off"
- regular operation should resume after again calling `uart_poweron()`
- this is tested
None
=> cpu/nrf5x_common: fix uart_poweroff()

release-notes.txt
Dear RIOTers!
The next release is officially due today, and already fully tested with https://github.com/RIOT-OS/Release-Specs/issues/322 🎉 Would be great to get this out by tomorrow :)
Please have a look at the automatically created release notes, and feel free to suggest rephrasings, reorderings, and further release highlights.
Thanks!
=> release-notes.txt: add 2025.04 release notes

dist/tools/uf2/nrf52_softdevice_check.sh
The current tooling cannot distinguish which one is the correct one to flash.
1. Connect two or more boards with Adafruit nrf52 bootloaders to your host.
2. Switch both of them to bootloader mode.
3. Try flashing one of them with `make -C examples/basic/hello-world BOARD=adafruit-feather-nrf52840-sense flash`
On `master`, this will actually give the bogus error message "No INFO_FILE.TXT found in UF2 Mass Storage Device!". Now, it should fail with a clearer error message.
Fixup for f8c9df35add38292b7705f7b7e678f17cb381bf5
=> tools/uf2/nrf52_softdevice_check: abort when several bootloaders present

dist/tools/uf2/nrf52_softdevice_check.sh
The current tooling cannot distinguish which one is the correct one to flash.
1. Connect two or more boards with Adafruit nrf52 bootloaders to your host.
2. Switch both of them to bootloader mode.
3. Try flashing one of them with `make -C examples/basic/hello-world BOARD=adafruit-feather-nrf52840-sense flash`
On `master`, this will actually give the bogus error message "No INFO_FILE.TXT found in UF2 Mass Storage Device!". Now, it should fail with a clearer error message.
Fixup for f8c9df35add38292b7705f7b7e678f17cb381bf5
=> tools/uf2/nrf52_softdevice_check: abort when several bootloaders present [backport 2025.04]

release-notes.txt
Dear RIOTers!
The next release is officially due today, and already fully tested with https://github.com/RIOT-OS/Release-Specs/issues/322 🎉 Would be great to get this out by tomorrow :)
Please have a look at the automatically created release notes, and feel free to suggest rephrasings, reorderings, and further release highlights.
Thanks!
=> release-notes.txt: add 2025.04 release notes [backport 2025.04]

makefiles/tools/riotgen.inc.mk
Recently I noticed that when you call `make generate-Makefile.ci` from the base directory, it would try to call `riotgen Makefile.ci`, which obviously fails. Likewise with any other `generate-*` target. Also, the colors for the warnings did not work for the warning when `riotgen` is not installed:
With this PR, the unrecognized target will be called out by the `Welcome Message` and the colors work for the warning. Also I made the warning a bit nicer.
Run `make generate-bogus` and `make generate-Makefile.ci` in the base directory and observe that the correct warning is displayed.
Uninstall `riotgen` and see that the warning is colored.
Install `riotgen` again and see that `make generate-test` will still call `riotgen` and ask you for the application name.
=> makefiles/riotgen: fix colors and behavior for undefined `generate-*` targets

doc/guides/general/structure.mdx
This PR fixes a small oversight that was made with the structure guide. When it was merged it still had some references via doxygens `@ref` system left. This should simply swap them out with working links.
I decided to always use full links so the guide is completely usable/clickable on github or in the IDE whenever developers read through it.
This has no testable changes.
Follow-up on #21404
=> doc/guides/general: switch out @ref usage

makefiles/pseudomodules.inc.mk, sys/include/stdio_base.h, sys/stdio/doc.md
This changes the documentation of how to configure stdio, especially with regard on how to configure the stdio frontends with `printf_float`, `printf_long_long`, and `stdin`.
The CI will provide a doc preview.
None
=> sys/stdio: better document configuration

sys/include/net/sock/util.h, sys/net/sock/sock_util.c
This allows using and compiling the URL handling functions of `sock_util` without a network stack used.
Specifically, the URL splitting function can be useful even without having a network stack in use, e.g. for exotic CoAP transports (say, CoAP over SMS or CoAP over UART).
The generated binaries should not change. But including `sock/util.h` without a network stack should now work without compilation failures.
Split out of https://github.com/RIOT-OS/RIOT/pull/21048
=> sys/net/sock_util: Do not depend on network stack

makefiles/cargo-targets.inc.mk, makefiles/docker.inc.mk
Do not create the cargo folder unconditionally, but only before running docker and only when they do not exist.
```
make BUILD_IN_DOCKER=1 BOARD=samr21-xpro -C examples/lang_support/official/rust-hello-world/
```
without `.cargo/git` and `.cargo/registry` should create those folders before running docker, so that they are not created as root.
None
=> build system: improve cargo/docker interaction

sys/include/net/sock/util.h
`sock_tcp_ep_t` may not be defined if sock_tcp is not used.
`make -C examples/networking/coap/gcoap LWIP_IPV4=1` works again 
fixes #21419
=> sys/net/sockutil: Do not use undefined structs

sys/embunit/TextUIRunner.c
When using `OUTPUT=COLORTEST` the return value of the unit test's `main()` on failure was `0`, while it should be `1`. As a result, running the unit tests from a script using
$ OUTPUT=COLORTEXT make BOARD=native64 RIOT_TERMINAL=native -j32 flash term -C tests/unittests
would not catch a test failure.
This commit changes the behavior so that `0` is returned on success and `1` on failure for both regular and colored text output.
Run
```
$ TZ=Europe/Berlin OUTPUT=COLORTEXT make BOARD=native64 RIOT_TERMINAL=native -j32 flash term -C tests/unittests
```
and
```
$ TZ=UTC OUTPUT=COLORTEXT make BOARD=native64 RIOT_TERMINAL=native -j32 flash term -C tests/unittests
```
The former will fail, the latter succeed. But both will have an exit code of `0` (`echo $?`) in `master`, while ommitting the …
=> sys/embunit: fix return value on failure

sys/shell/cmds/gnrc_netif.c
The helptext of the `ifconfig` shell command has a typo; instead of "Maximum transmission unit" it was "Maximum transition unit". not a super big deal. but this PR fixes it.
run `ifconfig help` and look at the line about "mtu"
=> sys/shell/cmd: typo in ifconfig helptext, \'transition\' fixed as \'transmission\'

doc/doxygen/src/getting-started.md, doc/guides/getting-started/installing.mdx
During our seminar, we discovered some issues with various distributions (especially Fedora and Arch Linux, for the latter I added a commit in #21395).
Also, the Getting Started guide is outdated and said that it is not possible to pass through USB devices, which is not correct (anymore).
Furthermore, #21436 introduced a regression. The link to the WSL guide in the Getting Started page was dead.
All in all, I used the opportunity to clean the Getting Started documentation up a bit, even though it'll be eventually replaced by the Starlight documentation.
Generate the documentation and see that everything still looks fine.
Fix regression from #21436.
=> doc/getting-started: Fix links, minor cleanup

examples/basic/subfolders/Makefile
At least on the samr21-xpro used for hardware in the loop testing, the terminal did not attach in time after the reset to capture all of the output.
This adds the `test_utils_interactive_sync` module to wait for an `s` to be received via `stdio` before starting to print to sync with the test scripting.
Test in the CI should pass now.
None
=> examples/basic/subfolders: fix test

drivers/include/net/netdev.h, drivers/include/net/netdev/ieee802154_submac.h, drivers/netdev_ieee802154_submac/Makefile.dep, drivers/netdev_ieee802154_submac/netdev_ieee802154_submac.c, pkg/openthread/contrib/netdev/openthread_netdev.c, pkg/openthread/contrib/platform_radio.c, sys/Makefile.dep
We only have `NETDEV_EVENT_TX_COMPLETE` now, store error codes in device struct.
*only lightly tested*
=> drivers/netdev_ieee802154_submac: port to netdev_new_api

pkg/lwip/Makefile.dep, pkg/lwip/contrib/netdev/lwip_netdev.c
While working on PR #21333, when I by mistake enable LWIP IPv4, Murdock detected some compilation errors
associated with dependencies (see https://github.com/RIOT-OS/RIOT/pull/21333#issuecomment-2761543019, older versions of this automatic reply). 
```
In file included from acd.c:71:
../../include/lwip/acd.h:97:48: error: 'struct etharp_hdr' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
97 | void acd_arp_reply(struct netif *netif, struct etharp_hdr *hdr);
|                                                ^~~~~~~~~~
acd.c: In function 'acd_tmr':
acd.c:264:13: error: implicit declaration of function 'etharp_acd_probe' [-Werror=implicit-function-declaration]
264 |             etharp_acd_probe(netif, &acd->ipaddr);
| …
```
=> pkg/lwip: fix dependencies when LWIP IPv4 is used

sys/arduino/include/arduino_board.h, tests/sys/arduino_blinky/BlinkWithoutDelay.sketch, tests/sys/arduino_blinky/Makefile, tests/sys/arduino_blinky/Makefile.ci
This PR defines `LED_BUILTIN` by using `ARDUINO_LED` as defined by a board for compatibility reasons with the Arduino IDE to make it easier to use Arduino sketches as they are.
While completing the Arduino I/O mapping for ESP32x in PR #21484 I was wondering why we define `ARDUINO_LED` while Arduino sketches mostly use `LED_BUILTIN`. In Arduino IDE, `LED_BUILTIN` ist usually defined for a board an is therefore frequently used to control the on-board LED. The most common example `BlinkWithoutDelay` also uses `LED_BUILTIN`.
The PR includes `tests/sys/arduino_blinky` which is just the orginal `BlinkWithoutDelay` example without any changes which works in RIOT-OS out of the box with this PR.
Use any board with enabled Arduino features and flash the test app:
```
BOARD=arduino-uno make -j4 -C …
```
=> sys/arduino: define LED_BUILTIN as frequently used by Arduino sketches

cpu/cc2538/include/periph_cpu.h, cpu/cc2538/periph/gpio.c
The CC2538 does not support "Open Drain" or "Open Drain with Pullup" outputs. However problems can arrise from setting both macros to the same value. This commit sets them to separate values which are both invalid to avoid conflicts with other applications.
The value of `0xf0` was chosen arbitrarily, but it is still very far away from the valid values:
https://github.com/RIOT-OS/RIOT/blob/04a169867e530e0a1113540c3db321c1b8d95002/cpu/cc2538/include/cc2538_gpio.h#L304-L313
Unfortunately I don't have the hardware to test this, but the changes should be fairly obvious.
Prerequisite for #10688.
=> cpu/cc2538: Distinguish between GPIO_OD and GPIO_OD_PU

dist/tools/headerguards/headerguards.py
The headerguard check did not catch the case when a `#pragma once` is present in the file followed by classic header guards.
Apparently I did not anticipate this corner case in #21367...
This commit also improves the error messages to give a better reason why the test failed.
Remove the header guards from a header of your liking, for example `boards/feather-m0/include/board.h`
Current Master:
```
cbuec@W11nMate:~/RIOTstuff/riot-gettingstarted/RIOT$ ./dist/tools/headerguards/check.sh
boards/feather-m0/include/board.h: no / broken header guard
```
This PR:
```
cbuec@W11nMate:~/RIOTstuff/riot-gettingstarted/RIOT$ git diff boards/feather-m0/include/board.h
diff --git a/boards/feather-m0/include/board.h b/boards/feather-m0/include/board.h
index bd410fdfb2..2ff00cf26b 100644
--- …
```
=> dist/tools: Improve Headerguard Check

doc/doxygen/src/css/riot.css, doc/doxygen/src/css/riot.less
The RIOT CSS for the Doxygen documentation explicitly enables `overflow: visible` for the code blocks, which leads to overlaps of the code blocks and the table of contents.
As Doxygen calculates the appropriate size for the code blocks beforehand, I don't really see the necessity of this explicit statement.
Even if you make a line über-long, the formatting still does not fail and it will insert line breaks:
<hr/>
Current master:
With this PR:
Look at the documentation output.
=> doc/doxygen: Avoid Overlapping of Code Blocks with Table of Contents

boards/esp32-wemos-d1-r32/Kconfig, boards/esp32-wemos-d1-r32/Makefile, boards/esp32-wemos-d1-r32/Makefile.dep, boards/esp32-wemos-d1-r32/Makefile.features, boards/esp32-wemos-d1-r32/Makefile.include, boards/esp32-wemos-d1-r32/doc.md, boards/esp32-wemos-d1-r32/include/arduino_iomap.h, boards/esp32-wemos-d1-r32/include/board.h, boards/esp32-wemos-d1-r32/include/gpio_params.h, boards/esp32-wemos-d1-r32/include/periph_conf.h, boards/esp32-wroom-32/doc.txt
This PR adds the board definition for the Wemos D1 R32 also known as ESPDuino-32, the only  only Arduino-sized ESP32 board with Arduino Uno compatible headers.
Compilation in CI should succeed.
=> boards: add Wemos D1 R32 (aka ESPDuino-32) board definition

doc/doxygen/src/creating-an-application.md
The existance of the `Makefile.board.dep` files in application directories was previously undocumented, but used throughout the RIOT example applications.
The possibility to create a board-specific `Makefile.dep` in the application folder was introduced in #12755, but no further documentation about it was added.
This is unfortunate, because it's used throughout RIOT already and a very useful feature, since that file (unlike the application Makefile) will be called throughout the dependency resolution phase and therefore have the latest and updated `FEATURES_USED`, `USEMODULE`, ... variables.
Look at the generated Doxygen documentation.
The feature was introduced in #12755.
The lack of documentation came up in #21442.
=> doc/creating-an-application: Add Section about Makefile.board.dep

doc/doxygen/src/creating-an-application.md
As requested by @miri64 in #21475.
Doxygen shouldn't throw any errors and the CI should be happy. Also the documentation should be even more clearer :)
Fixup for #21475.
=> doc/creating-an-app: clarify wording about Makefile.board.dep

cpu/native/irq.c
In the cleanup PR for native (#21283) (90a3f3ffcc3ae25f07ba5ac9fe2d1444cf7c26ea) the ISR stack variable got renamed from __isr_stack to _isr_stack but the valgrind configuration hasn't been updated.
Build any application for native with `make all-valgrind`.
Fixes a leftover issue from #21283
=> cpu/native: use correct isr_stack for valgrind

makefiles/defaultmodules_deps.inc.mk, makefiles/defaultmodules_no_recursive_deps.inc.mk, makefiles/defaultmodules_regular.inc.mk
This PR is a small correction of the comments in `makefiles/defaultmodules*.inc` which were a bit confusing, especially in `makefiles/defaultmodules_no_recursive_deps.inc.mk`.
Review of the comments.
=> makefiles/defaultmodules*.mk: fix the description in comments

boards/seeedstudio-xiao-esp32c3/Makefile.dep, boards/seeedstudio-xiao-esp32c3/Makefile.features, boards/seeedstudio-xiao-esp32c3/doc.md, boards/seeedstudio-xiao-esp32c3/include/arduino_iomap.h, boards/seeedstudio-xiao-esp32c3/include/board.h, boards/seeedstudio-xiao-esp32c3/include/gpio_params.h, boards/seeedstudio-xiao-esp32c3/include/periph_conf.h, makefiles/defaultmodules_no_recursive_deps.inc.mk
Add guard around macro definition to allow the user to redefine it to use the SPI module
- Disable BUTTON0 if SPI is used because this pin conflicts with the SPI MISO line.
- Don't define GPIO5 as a PWM line any more since it is used as chip select in the default SPI configuration.
Fixes #21462
=> boards/seeedstudio-xiao-esp32c3: fix pin conflict

drivers/atwinc15x0/Makefile.dep, drivers/atwinc15x0/atwinc15x0_bus.c, pkg/driver_atwinc15x0/Makefile, pkg/driver_atwinc15x0/Makefile.dep, pkg/driver_atwinc15x0/patches/0012-nmdrv-don-t-call-spi_enable_flash-0.patch
The PR removes the compilation of the SPI Flash driver part of the package. This allows also to use the ATWINC15x0 for ESPs.
The SPI flash integrated in the ATWINC15x0 chip is not used in RIOT. It is therefore not necessary to compile the SPI flash driver part of the package. The only function of this part that is called by other parts of the driver package is `spi_enable_flash(0)` to disable the SPI flash during the driver deinitialization for power consumption reasons. Since we are not deinitializing the driver, the function is not called and can be commented out to be able to compile the package without the SPI flash driver part.
A networking application should still work for any board with a ATWINC15x0 WiFi module that uses the ATWINC15x0 driver package, for example:
```python …
```
=> pkg/driver_atwinc15x0: remove the compilation of the SPI Flash driver part

boards/esp32-wrover-kit/Makefile.dep, tests/pkg/fatfs/Makefile, tests/pkg/fatfs/Makefile.board.dep, tests/pkg/fatfs/README.md, tests/pkg/fatfs_vfs/Makefile, tests/pkg/fatfs_vfs/Makefile.board.dep, tests/pkg/fatfs_vfs/README.md
To prevent `mtd_sdcard` from being used by default for boards that use a different default MTD, which can lead to module conflicts, `mtd_sdcard` is now only enabled in `tests/pkg/fatfs` and `tests/pkg/fatfs_vfat` if no other MTD is enabled by default with the corresponding `mtd_*_default` module.
With this PR, MTD dependencies for `esp32-wrover-kit` could be fixed.
Compilation in CI should succeed.
Use any board definition with SDMMC as SD Card interface und try the following command with and w/o this PR:
```
BOARD=stm32f746g-disco make -C tests/pkg/fatfs info-modules | grep mtd
```
Without the PR, the list of MTD modules is:
```
mtd
mtd_sdcard
mtd_sdmmc
mtd_sdmmc_default
```
With the PR the command should give:
```
mtd
mtd_sdmmc
mtd_sdmmc_default
```
Prerequisite for PR #21471
=> tests/pkg/fatfs*: cleanup MTD default dependencies

boards/esp32s3-usb-otg/Makefile.dep, boards/esp32s3-usb-otg/Makefile.features, boards/esp32s3-usb-otg/doc.txt, boards/esp32s3-usb-otg/include/periph_conf.h
This PR enables the `periph_sdmmc` feature for the `esp32s3-usb-otg` board to use the SDMMC Host to access the SD Card instead of using the SD Card in SPI mode.
```python
BOARD=esp32s3-usb-otg make -j4 -C tests/sys/vfs_default/ flash term
```
should still work.
Depends on PR #21478
=> boards/esp32s3-usb-otg: enable SDMMC peripheral

sys/include/shell.h, sys/shell/shell.c, sys/shell_lock/shell_lock.c
For interactive shell commands, `readline()` is very useful as it provides robust line fetching from the console and is already externally linked. This PR just declares it in `shell.h`
Nothing to be tested.
=> sys/shell: expose readline()

boards/feather-m0/include/periph_conf.h
The current ADC settings set the reference to the internal 1V reference with a x1 gain. This means that the maximum voltage that can be measured with any analog input is 1V, which is usually not sufficient for most applications.
Therefore the default value is changed to use the external VDDA input, which is 3.3V (internally divided by 2) and the gain to x1/2. This allows to measure voltages up to VDDA on any analog input.
You can run the `tests/periph/adc` example with an external voltage source connected. You should see that with `master`, the ADC values max out at about 1V (or 2V for the battery input).
I connected a 0.8V voltage to the BAT input, which has a 1/2 resistor divider.
`master` : The values should be 0.8/1.0 * 0.5 * {256, 1024, 4096, 65536} = {102, 410, 1638, 26214} on …
=> boards/feather-m0: Correct ADC Settings

sys/include/shell.h, sys/shell/cmds/udptty.c, sys/shell/shell.c, sys/shell_lock/shell_lock.c
Hello 🦫,
the recent PR #21505 exposed the shell readline function. This PR adjust its name as proposed by @mguetschow
=> sys/shell: rename shell_readline()

boards/adafruit-feather-nrf52840-express/Makefile.features, boards/adafruit-feather-nrf52840-sense/Makefile.features, boards/feather-m0/Makefile.features, doc/doxygen/src/io-mapping-and-shields.md, features.yaml, makefiles/features_existing.inc.mk
Same as `xiao_shield` for all Feather boards supported by RIOT. Not used yet as no extension boards for Feather's are currently defined (and I'm not sure how we would even model them right now in our build system).
Briefly skim over the changes, CI should be green.
=> features.yaml: add feather_shield feature

examples/networking/coap/gcoap_dtls/client.c, examples/networking/coap/gcoap_dtls/gcoap_example.h, examples/networking/coap/gcoap_dtls/main.c, tests/build_system/test_tools/main.c, tests/cpu/cortexm_address_check/main.c, tests/sys/atomic_utils/main.c, tests/sys/congure_abe/main.c, tests/sys/congure_quic/main.c, tests/sys/congure_reno/main.c, tests/sys/congure_test/main.c, tests/sys/heap_cmd/main.c, tests/sys/rng/main.c, tests/sys/struct_tm_utility/main.c, tests/sys/struct_tm_utility/tests/01-run.py, tests/sys/usbus_cdc_acm_stdio/main.c, tests/sys/usbus_msc/main.c, tests/sys/xtimer_mutex_lock_timeout/main.c, tests/sys/xtimer_rmutex_lock_timeout/main.c, tests/sys/ztimer_rmutex_lock_timeout/main.c
Migrate some more applications to using the XFA SHELL_COMMAND instead of the statically allocated list (often with `extern` function declarations) in `main.c`.
CI should find build regressions.
Follow-up of https://github.com/RIOT-OS/RIOT/pull/21171
=> treewide: migrate to XFA SHELL_COMMAND

drivers/sdmmc/sdmmc_sdhc.c
I witnessed situations where the sdmmc driver stalls while waiting for an IRQ.
It might be hardware though ...
However even if it is hardware, it keeps going with this changes in this PR.
Internal app where data is written to an eMMC and I keep pressing ENTER to continuously execute `vfs ls`.
```
> 2025-04-24 10:31:28,805 # vfs ls /sd0/data
2025-04-24 10:31:28,821 # RPOS.TXT	4 B
2025-04-24 10:31:28,821 # 0.CNK	5559 B
2025-04-24 10:31:28,821 # 1.CNK	4181 B
2025-04-24 10:31:28,821 # 2.CNK	696 B
2025-04-24 10:31:28,821 # total 4 files
> 2025-04-24 10:31:28,837 # vfs ls /sd0/data
2025-04-24 10:31:30,853 # [ERROR] [sdmmc] Card not present
2025-04-24 10:31:30,853 # vfs_opendir error: -EIO
> 2025-04-24 10:31:30,853 # vfs ls /sd0/data
2025-04-24 10:31:30,853 # vfs_opendir error: -EIO
> 2025-04-24 …
```
=> drivers/sdmmc_sdhc: add timeout to wait for ISR mutex unlock

examples/lang_support/official/rust-gcoap/Makefile, makefiles/docker.inc.mk
This ensures that `make BUILD_IN_DOCKER=1` will use the same container that was used in the CI (Murdock).
Green CI
None
=> build-system: pin new docker image

sys/shell/cmds/gnrc_netif.c
`flags` is unused if `MODULE_GNRC_IPV6` is unused.
split out from #21202
=> sys/shell/cmds/gnrc_netif: fix compilation without IPv6

dist/tools/compile_test/compile_like_murdock.py
This PR changes `dist/tools/compile_test/compile_like_murdock.py` to
1. allow specifying the used toolchain (hardcoded to `gnu` (backwards-compatible default) and `llvm`)
2. return an error code on exit if any of the builds failed (this is a breaking change as it was before always returning success)
Let's hope no other tool was relying on the exit code being always zero, hopefully CI would catch that.
You can test the script locally with
```
dist/tools/compile_test/compile_like_murdock.py -a tests/pkg/fff tests/sys/shell -b native32 -t gnu
dist/tools/compile_test/compile_like_murdock.py -a tests/pkg/fff tests/sys/shell -b native32 -t llvm
```
The first should succeed, the latter fail.
This is needed for https://github.com/RIOT-OS/riotdocker/pull/256 and transitively to unblock the failing …
=> dist/tools/compile_test: specify toolchain and exit code

dist/tools/compile_test/compile_like_murdock.py
This PR changes `dist/tools/compile_test/compile_like_murdock.py` to
1. allow specifying the used toolchain (hardcoded to `gnu` (backwards-compatible default) and `llvm`)
2. return an error code on exit if any of the builds failed (this is a breaking change as it was before always returning success)
Let's hope no other tool was relying on the exit code being always zero, hopefully CI would catch that.
You can test the script locally with
```
dist/tools/compile_test/compile_like_murdock.py -a tests/pkg/fff tests/sys/shell -b native32 -t gnu
dist/tools/compile_test/compile_like_murdock.py -a tests/pkg/fff tests/sys/shell -b native32 -t llvm
```
The first should succeed, the latter fail.
This is needed for https://github.com/RIOT-OS/riotdocker/pull/256 and transitively to unblock the failing …
=> dist/tools/compile_test: specify toolchain and exit code [backport 2025.04]

examples/lang_support/official/rust-gcoap/Makefile, makefiles/docker.inc.mk
This ensures that `make BUILD_IN_DOCKER=1` will use the same container that was used in the CI (Murdock).
Green CI
None
=> build-system: pin new docker image [backport 2025.04]

dist/tools/bmp/bmp.py, dist/tools/bmp/requirements.txt
[PEP 723](https://peps.python.org/pep-0723/) is an accepted proposal to in-line script metadata. One such use cases is to list script dependencies inside the script, which makes the `requirements.txt` redundant.
With the correct shebang, it becomes even possible to run the script directly, without creating a virtual environment and installing dependencies in advance. Combining both makes the execution of single-file scripts within RIOT much easier and friendlier.
PEP 723 metadata can be used by [`pipx`](https://github.com/pypa/pipx) and can be easily installed when `pip` is available. It is maintained by the PyPA, just like `pip`. 
I chose this file to start with, but there are at least five more scripts with `requirements.txt` that could benefit from the same change. Because `pip …
=> dist/tools/bmp: in-line dependencies using PEP 723

tests/drivers/ili9341/main.c, tests/drivers/st77xx/main.c
The lcd_fill() argument x2 (y2) must be less than dev.params->lines (dev.params->rgb_channels) to not draw to invalid LCD coordinates.
Tested on a Xiao nRF52840 with a ST7735 attached.
This is my first contribution to RIOT and to be honest I did not completely read the Linux kernel coding style guide, but I wrapped the long lines according to https://docs.kernel.org/process/coding-style.html#breaking-long-lines-and-strings.
=> tests/drivers/{st77xx,ili9341}: fix coordinates in lcd_fill()

dist/tools/riotboot_gen_hdr/genhdr.c, dist/tools/riotboot_gen_hdr/main.c
For parsing the output of the `genhdr` command, a JSON mode will make things easier.
```
$ genhdr show --json slot0.1748336784.bin 
{
"version": 1748336786,
"address": 4352,
"valid": true
}
```
```
$ genhdr show slot0.1748336784.bin        
version: 1748336786
address: 0x1100
checksum: valid
```
=> dist/tools/riotboot_gen_hdr: add JSON mode

sys/ztimer/init.c
I'm working on a port for [a custom chip](https://www.crystalfree.org/) in which the peripheral timer runs at 500kHz. I applied this patch to make ztimer work correctly over it.
Maybe there's a better way, e.g with less code duplication.
Run `tests/sys/ztimer_msg` on the custom chip:
<details><summary>With this PR</summary>
```
$ BUILD_IN_DOCKER=1 make BOARD=scum-devkit -C tests/sys/ztimer_msg/ --no-print-directory flash test
Launching build container using image "docker.io/riot/riotbuild@sha256:21c416fbbb94a99c3d9c76341baf5a9740608b1d1af89967127c7a171248fd7b".
docker run --rm --tty --user $(id -u) --platform linux/amd64 -v '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro' -v '/work/riot/RIOT:/data/riotbuild/riotbase:delegated' -v …
```
=> sys/ztimer: add support for timers running at a 500kHz frequency

sys/include/event/deferred_callback.h
Remove the event from the timer queue before modifying it's contents.
=> sys/event/deferred_callback: disable timer before modifying event

sys/event/thread.c, sys/include/event.h
`event_wait_multi()` always returns an event, so the `event_loop_multi()` can be rewritten s.t. it explicitly never returns. The compiler will optimize away any prologue/epilogue, saving stack and code space. 
Ran the `sys/event_thread` app on native64.
=> sys/event/thread: optimize stack usage

doc/guides/getting-started/install-wsl.mdx
The link in the box on https://guide.riot-os.org/getting-started/install-wsl/ is broken.
Check the guides preview (do we have that?).
Also, I'm a bit surprised to find the WSL installation guide above the general "Setup Development Environment" in the navigation tree, is that intentional @AnnsAnns ?
=> guides: use absolute path to fix url

boards/nucleo-l412kb/Makefile.features, boards/nucleo-l412kb/include/periph_conf.h, cpu/stm32/Makefile.features, cpu/stm32/include/periph/l4/periph_cpu.h, cpu/stm32/periph/adc_l4_wb.c
This PR enables ADC for `nucleo-l412kb` board.
I don't have access to this boards, but because ADC pinout is the same as for `nucleo-l432kc` (see board manual tables 15 and 16) code should works fine. I compile code without any warnings.
Flash the board using `tests/periph/adc` and `tests/periph/vbat` programs.
The outputs should be similar to the ones presented in https://github.com/RIOT-OS/RIOT/pull/21238#issuecomment-2694298250
None.
=> boards/nucleo-l412kb: enable ADC

pkg/esptool/Makefile
It seems that Espressif recently released version 5.0.0 of `esptool.py` and uploaded the corresponding Python package. This version throws a number of depcrecation warnings when compiling applications for any ESP board:
```
Warning: DEPRECATED: 'esptool.py' is deprecated. Please use 'esptool' instead. The '.py' suffix will be removed in a future major release.
Warning: Deprecated: Option '--flash_mode' is deprecated. Use '--flash-mode' instead.
Warning: Deprecated: Option '--flash_size' is deprecated. Use '--flash-size' instead.
Warning: Deprecated: Option '--flash_freq' is deprecated. Use '--flash-freq' instead.
```
This PR pins the installation of the `esptool.py` Python package to version 4.9.0 so that compilation works without these deprecation warnings.
Compile any application for …
=> pkg/esptool: force installation of version 4.9.0

core/Makefile, core/include/thread_flags_group.h, core/thread_flags_group.c, tests/core/thread_flags_group/Makefile, tests/core/thread_flags_group/Makefile.ci, tests/core/thread_flags_group/main.c, tests/core/thread_flags_group/tests/01-run.py
Adds thread flags group overlay.
From `core/include/thread_flags_group.h`:   
A thread flags group allows setting thread flags for an arbitrary number of
threads (called waiters) at the same time. The waiters can join and leave
the group at any time. An additional advantage is that the signaler (the
"flags setter") is de-coupled from the list of waiters, i.e. it does not
need to know which specific thread must be signaled.
Example (waiter):
```c
static tfg_t group = THREAD_FLAGS_GROUP_INIT;
// ...
tfg_entry_t entry;
thread_flags_group_join(&group, &entry);
while (!some_condition_is_met()) {
thread_flags_wait_any(SOME_FLAG);
}
thread_flags_group_leave(&group, &entry);
``` 
Example (signaler):
```c
fulfill_some_condition();
thread_flags_group_set(&group, SOME_FLAG);
```
Run the test …
=> core/thread_flags: add thread flags group

dist/tools/uf2/Makefile
In the current master, the setup of `uf2conv` tends to fail with weird errors. The reason for that is that `make` executes multiple targets parallel, one of which tries to access the file that has not been copied yet (or sometimes it has, race condition).
It works on the second try.
Perhaps it's caused by using multiple threads.
Also, during `make distclean`, the `dist/tools/uf2` folder is not cleaned up.
Current `master` (note there is no actual board connected):
```
cbuec@W11nMate:~/RIOTstuff/riot-security/RIOT$ BOARD=seeedstudio-xiao-nrf52840 make -C tests/minimal flash -j
make: Entering directory '/home/cbuec/RIOTstuff/riot-security/RIOT/tests/minimal'
Building application "tests_minimal" for "seeedstudio-xiao-nrf52840" with CPU "nrf52".
"make" -C …
```
=> dist/tools: include UF2 folder in `distclean` and fix setup

boards/arduino-mega2560/doc.md, boards/arduino-nano/doc.md, boards/arduino-uno/doc.md, boards/atmega1284p/doc.md, boards/atmega328p-xplained-mini/doc.md, boards/atmega328p/doc.md
During the review of #21573 the AVaRICE debugger came up and our documentation is a bit out of date.
While the development of AVaRICE is still slow, it is not stopped (anymore) and there was a release in 2020. When the documentation was written, there hasn't been a release for nearly a decade, so I decided to remove the remarks about AVaRICE's ancient code base.
RFC: It would be possible to add a remark that AVaRICE should probably still be built from code instead of using the release version, as half a decade is also quite old already...
While touching the files, I moved them to Markdown format as discussed in #21220.
It would be nice to have a single documentation for AVaRICE, because currently it's a bit redundant with varying levels of completeness, but I didn't feel like diving into …
=> boards/*avr*: Update the link to the AVaRICE documentation

tests/unittests/tests-sock_util/Makefile.include
Hello 🦋,
this fixes an issue where the unit test `tests-sock_util` could not be compiled as types were left undefined.
`make -C tests/unittests/ tests-sock_util flash-only test`
Possibly introduced by either "pragma once" breaking (fixing) a header include or by #21419 which guards transitive header explicitly.
=> tests/unittests: Add missing module dependency to enable UDP

sys/include/net/l2filter.h, sys/net/link_layer/l2filter/l2filter.c
Hey 🐫,
this fixes a ineffective length check.
It is very unlikely to be exploitable in the wild. It is an internal, developer oriented API that usually will not be used in an untrustworthy context.
CI + Build will be sufficient.
GHSA-7972-w7f9-3j9m / CVE-2025-53888
=> net/l2filter: fix incorrect length check

cpu/esp32/Makefile, cpu/esp32/Makefile.dep, cpu/esp32/Makefile.features, cpu/esp32/Makefile.include, cpu/esp32/esp-idf/Makefile, cpu/esp32/esp-idf/common/Makefile, cpu/esp32/esp-idf/ieee802154/Makefile, cpu/esp32/esp-ieee802154/Makefile, cpu/esp32/esp-ieee802154/esp_ieee802154_hal.c, cpu/esp32/esp-ieee802154/esp_ieee802154_hal.h, cpu/esp32/include/irq_arch.h, cpu/esp32/include/periph_cpu.h, cpu/esp32/include/sdkconfig.h, cpu/esp32/irq_arch.c, cpu/esp_common/Makefile.dep, drivers/include/net/netdev.h, features.yaml, makefiles/features_existing.inc.mk, pkg/esp32_sdk/patches/0034-ieee802154-driver-fix-misssing-include.patch, sys/net/gnrc/netif/init_devs/auto_init_esp_ieee802154.c, sys/net/gnrc/netif/init_devs/init.c, tests/net/ieee802154_hal/init_devs.c, tests/net/ieee802154_hal/main.c, tests/net/ieee802154_hal/test_common.h, tests/net/ieee802154_submac/main.c
This PR provides the support for the IEEE 802.15.4 interface for the ESP32-H2.
Flash the test application `examples/networking/gnrc/gnrc_networking`
```
BOARD=esp32h2-devkit make -C examples/networking/gnrc/gnrc_networking flash term
```
which uses the IEEE 802.15.4 interface as `netdev_default`. It should be possible to ping other IEEE 802.15.4 nodes.
IEEE 802.15.4 for ESP32-H2 has been tested with an `esp32h2-devkit` board together with a `waveshare-nrf52840-eval-kit` board:
```
main(): This is RIOT! (Version: 2025.07-devel-513-g0af92-cpu/esp32/add_esp32h2_ieee802154)
RIOT network stack example application
> ifconfig
Iface  8  HWaddr: 5B:72  Channel: 26  NID: 0x23  PHY: O-QPSK 
Long HWaddr: EE:DD:84:74:AB:D8:DB:72 
TX-Power: 0dBm  State: IDLE 
ACK_REQ …
```
=> cpu/esp32: add IEEE 802.15.4 support for ESP32-H2

makefiles/tools/esptool.inc.mk
This PR pins the installation of the `esptool.py` Python package to version 4.9.0 also for flashing.
A couple of days ago, Espressif released version 5.0.0 of `esptool.py` and uploaded the corresponding Python package. While `esptool.py` installation was pinned to version `v4.9.0` for compilation by PR #21588, `esptool.py` version `v5.0.0` is still used for flashing. As a result, `esptools.py` is installed again and again alternating between `v4.9.0` and `v5.0.0`. 
This PR fixes this problem.
Try to compile an flash any application for any ESP32 board, for example:
```
BOARD=esp32-wroom-32 make -C tests/sys/shell flash
```
Without the PR, `epstool.py` is installed again and again and the `flash` target throws a number of deprecation warnings. With the PR `esptool.py` is installed only …
=> makefiles/tools/esptool: force installation of version 4.9.0

examples/advanced/suit_update/README.hardware.md, examples/networking/coap/gcoap/README-slip.md, examples/networking/misc/lwm2m/README.md
Carefully look at the diff :eyes:
=> examples: fix typos in refs to gnrc_border_router

boards/lora-e5-dev/dist/openocd.cfg
This patch fixes an issue in the OpenOCD STM32WLX target config (`target/stm32wlx.cfg`) where the `_TARGETNAME` variable is not defined after creating the CPU target. 
Board configs relying on `_TARGETNAME` fail with `can't read "_TARGETNAME": no such variable` during flashing or debugging.
Per the [OpenOCD Config File Guidelines](https://openocd.org/doc/html/Config-File-Guidelines.html), `_TARGETNAME` should be set in the target config, but it was removed in a previous commit ([diff](https://review.openocd.org/c/openocd/+/6050/8/tcl/target/stm32wlx.cfg#b44)).
This patch sets `_TARGETNAME` explicitly in the `openocd.cfg` for `lora-e5-dev` to point to the main CPU target (`$_CHIPNAME.cpu0`), restoring expected behavior.
With this fix, flashing the `examples/basic/hello-world` example now …
=> boards/lora-e5-dev: set OpenOCD _TARGETNAME variable to fix flashing

sys/include/net/netstats/neighbor.h, sys/net/gnrc/netif/gnrc_netif.c
These were only updated with in the old TX_COMPLETE events that no longer exist with the new API.
tbd
=> gnrc_netif: fix neighbor statistics with netdev_new_api

sys/include/net/nanocoap.h, sys/net/application_layer/nanocoap/nanocoap.c, tests/unittests/tests-nanocoap/tests-nanocoap.c
This adds a convenience function to iterate over a packets's URI query options.
Options have the format `key=value`, but options that only consist of a key may also exist.
For consistency, in this case the value is set to `"1"`.
I extended the `tests-nanocoap` unit test with the new function.
=> nanocoap: add coap_iterate_uri_query()

cpu/esp32/doc.md, dist/tools/esptools/export.sh, dist/tools/esptools/install.sh
The esptools/export.sh script has to be sourced, otherwise the exported variables are not persistent in the environment, rendering the script useless. The commit adds a check to the script that it runs in the correct environment and enhances the documentation to make it clearer that the "source" prefix command is important.
The documentation mentioned that, but I did not understand what "sourcing a script" means and I did not pay attention to the dot in front of the script. Sorry @gschorcht for not reading the documentation well enough 👀 
***Open for discussion:*** Should the script terminate before doing anything (as it does now) or should it print out the warning instead of the `Extending PATH by ...` message?
Pre: Make sure your PATH variable does not contain the latest ESP SDK version …
=> dist/tools: improve the `esptools`, enhance documentation

pkg/driver_cryptocell_310/psa_cryptocell_310/hmac.c, sys/hashes/psa_riot_hashes/hmac_sha256.c, sys/include/psa_crypto/psa/mac/types.h, sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h, sys/psa_crypto/include/psa_crypto_location_dispatch.h, sys/psa_crypto/include/psa_mac.h, sys/psa_crypto/psa_crypto.c, sys/psa_crypto/psa_crypto_algorithm_dispatch.c, sys/psa_crypto/psa_crypto_location_dispatch.c
Currently PSA mac backends can only implement psa_mac_compute() from the PSA crypto API, but not psa_mac_verify() and the associated multi-part functions.
Extend the location and algorithm dispatchers to connect the above PSA API functions to suitable backends. Also extend the MAC backend API to allow backends to implement those additional functions. Due to a design issue with the SE backend API (context size is dynamic, thus requiring a memory allocation) only psa_mac_verify() can be accelerated by SE backends.
Currently no backend implements the additional functions, but this will change in the future.
I successfully compiled and executed the PSA-related tests.
Prerequisite for #20758.
=> sys/psa_crypto: Extend mac API

dist/tools/picosdk/.gitignore, dist/tools/picotool/Makefile, dist/tools/picotool/picotool.sh, pkg/picosdk/Makefile, pkg/picosdk/Makefile.include
The `picosdk` is required for the RP2350 support #21545 and it would be convenient to use it through the `USEPKG` mechanism.
~~TODO: I think I removed too much from the `picotool` Makefile. The `picotool` has to be built for the RP2040 as well, but that does not use the `picosdk`.~~
Fixed.
Ping @AnnsAnns :)
I decided it would be easier if I create a separate PR (I'll send you a modified patch later for your PR), see the TODO...
Make sure `BOARD=rpi-pico make -C tests/minimal flash` still works.
Requirement for #21545.
=> dist/tools: Move `picosdk` to `pkg` folder, improve `picotool.sh` script

dist/tools/suit/suit-manifest-generator/suit_tool/clidriver.py
I would like to build the `suit-tool` as a self-contained binary. E.g. like this:
```console
$ cd dist/tools/suit/suit-manifest-generator
$ pyinstaller --onefile --name suit-tool suit_tool/clidriver.py
```
However, the `main()` function was not called.
This code change fixes this by:
* Execute the `main()` function when the script is run directly
* Please the Flake8 linter according to your coding convention
Now the binary can be created as stated above.
The binary can print its version:
```console
$ file ./dist/suit-tool 
./dist/suit-tool: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=eb586756c39e4efd29c393a8b324b3af04fd9a90, stripped
$  ./dist/suit-tool --version
0.0.2
```
Also the …
=> Allow for building the `suit-tool` as a self-contained binary

CODING_CONVENTIONS.md
This PR adds initial information concerning SPDX format to the coding conventions as @crasbe mentioned in [post](https://github.com/RIOT-OS/RIOT/issues/21515#issuecomment-3129227342).
Any comments welcome.
Review [CODING_CONVENTIONS.md](https://github.com/krzysztof-cabaj/RIOT/blob/84b16e927cdd5856865fa6e6e4655b52497e9d8a/CODING_CONVENTIONS.md) file sections `Documentation` and `SPDX`, introduced by this PR.
#21515 - track for SPDX transition for RIOT OS
=> doc: add SPDX information to coding convenstions

cpu/samd5x/cpu.c
current samd5 initialization is strange and might fail ( hardware dependant) while initializing this fixes that.
The failure is know a POR issue.
- valid clock XOSC32 startup time 
- avoid gclk roundtrip for FDPLL when XOSC32 is used
read and compare to documentation
=> cpu/samd5: improve clock initialisation XOSC32 and FDPLL

sys/include/suit/storage.h, sys/suit/handlers_command_seq.c
Currently, `_cond_comp_offset()` only prints the offset that was read from then manifest, it does not indicate whether the offset is correct or not.
This leads to the SUIT proccess failing with just a 
```
[INF] suit_worker: suit_parse() failed. res=-4
```
with no indication what went wrong.
A manifest with wrong offsets will now produce a much more clear error
```
2025-07-30 09:32:39,884 # [INF] suit_worker: started.
2025-07-30 09:32:39,895 # [INF] suit_worker: downloading "coap://[fdea:dbee:f::1]/fw/1/m/DCs?hwr=0&fwt=22&fwr=3000001"
2025-07-30 09:32:39,901 # [INF] suit_worker: got manifest with size 489
2025-07-30 09:32:39,907 # [INF] suit: verifying manifest signature
2025-07-30 09:32:41,037 # [INF] Unable to validate signature: -2
2025-07-30 09:32:41,049 # [INF] suit: verifying …
```
=> sys/suit: print warning if offset does not match

boards/arduino-nano-esp32/Kconfig, boards/arduino-nano-esp32/Makefile, boards/arduino-nano-esp32/Makefile.dep, boards/arduino-nano-esp32/Makefile.features, boards/arduino-nano-esp32/Makefile.include, boards/arduino-nano-esp32/doc.md, boards/arduino-nano-esp32/include/arduino_iomap.h, boards/arduino-nano-esp32/include/board.h, boards/arduino-nano-esp32/include/gpio_params.h, boards/arduino-nano-esp32/include/periph_conf.h
This PR adds the board definition for the [Arduino Nano ESP32](https://docs.arduino.cc/hardware/nano-esp32) board, an ESP32-S3 board in Arduino Nano format.
Basic tests for the board should work. The following tests have already been executed:
<details><summary>Shell</summary>
```
main(): This is RIOT! (Version: 2025.10-devel-111-g12a65-boards/arduino-nano-esp32)
test_shell.
> help
Command              Description
---------------------------------------
bufsize              Get the shell's buffer size
start_test           starts a test
end_test             ends a test
echo                 prints the input command
empty                print nothing on command
periodic             periodically print command
xfa_test1            xfa test command 1
xfa_test2            xfa test command 2 …
```
=> boards: add Arduino Nano ESP32 board

sys/include/suit.h, sys/suit/handlers_envelope.c
It can be handy to know which public keys are accepted by SUIT.
This adds a simple helper function `suit_get_public_key()` that gives access to the internal `public_key` array.
=> sys/suit: add suit_get_public_key()

doc/guides/getting-started/installing.mdx
Application of https://github.com/RIOT-OS/RIOT/pull/21399 to the new guides site which apparently got overlooked while migrating. @AnnsAnns 
Check diff, double-check package names.
Previously fixed with https://github.com/RIOT-OS/RIOT/pull/21399, but apparently not carried over with https://github.com/RIOT-OS/RIOT/pull/21573
=> guides/installing: add psutil requirement for pyterm

dist/tools/picotool/Makefile, pkg/picosdk/Makefile
This mostly only adds support for the new revision of the pico2 (Technically it already worked but looked weird in picotool). All other changes, at most, affect advanced pico 2 related stuff when using picosdk, which we currently don't do.
Flash a project with `PROGRAMMER=picotool` to the pico 1 or pico 2. Note that I only tested it working on the pico 2 as I currently have no pico 1 here, though considering that the flashing process is nearly 1:1 between them it should work identically.
=> picotool/picosdk: Bump version

boards/common/nucleo144/Makefile.features, boards/common/nucleo144/include/arduino_iomap.h
This PR includes some fixes of Arduino pin configurations for Nucleo144 boards with L4, L5 and U5 and completes the Arduino configuration for I2C, SPI, and UART devices of Nucleo144 boards.
In detail:
1. On Nucleo144 boards for L4, L5 and U5, Arduino connector pins D0/D1 have a different configuration. According to the user manuals for
- [L4 boards]( https://www.st.com/resource/en/user_manual/um2179-stm32-nucleo144-boards-mb1312-stmicroelectronics.pdf), D0/D1 are GPIOs PD9/PD8
- [L5 boards](https://www.st.com/resource/en/user_manual/um2581-stm32l5-nucleo144-board-mb1361-stmicroelectronics.pdf), D0/D1 are GPIOs PD9/PD8
- [U5 boards](https://www.st.com/resource/en/user_manual/um2861-stm32u5-nucleo144-board-mb1549-stmicroelectronics.pdf), D0/D1 are GPIOs PG8/PG7
2. According to the user …
=> boards/common/nucleo144: fix and complete Arduino configuration

sys/Makefile.dep, sys/include/net/ntp_packet.h, sys/include/net/sntp.h, sys/net/application_layer/sntp/sntp.c
The `sntp` module still uses the deprecated `xtimer`. This PR migrates it to `ztimer64`.
Testing is a bit non-trivial because RIOT can't access internet-based NTP servers (I think?) and systemd has an integrated NTP client, which does not act as an NTP server itself.
Therefore you have to install the good old `ntpd` and run it as `sudo`. Also a tap-network has to be setup of course.
The output should look something like this. In the build log, you should see `ztimer64` instead of `xtimer` and the output of `ntpdate` should be pretty much the same.
```
cbuec@W11nMate:~/RIOTstuff/riot-crc8/RIOT$ PORT=tap0 make -C tests/net/sntp all term -j
make: Entering directory '/home/cbuec/RIOTstuff/riot-crc8/RIOT/tests/net/sntp'
using BOARD="native64" as "native" on a 64-bit system
Building application …
```
=> sys/net/sntp: migrate from xtimer to ztimer

pkg/mpaland-printf/patches/0005-Change-p-formatting-to-match-glibc.patch
newlib and picolibc already implicitly add the `0x` prefix for `%p` just as glibc does, and some of our tests scripts depend on this.
(And subjectively, this looks better.)
This adds https://github.com/mpaland/printf/pull/90 on top of our patches.
Combined with
```diff
diff --git a/tests/core/msg_queue_print/tests/01-run.py b/tests/core/msg_queue_print/tests/01-run.py
index a03118d268..f78b50870e 100755
--- a/tests/core/msg_queue_print/tests/01-run.py
+++ b/tests/core/msg_queue_print/tests/01-run.py
@@ -41,12 +41,12 @@ def expect_some(child, size, avail, range_start):
def expect_content(child, counter):
if counter == 0:
-        if os.environ.get('BOARD') in ['native', 'native32', 'native64']:
-            child.expect_exact('type: 0x0000, content: 0 ((nil))')
-        else:
- …
```
=> pkg/mpaland-printf: format points like glibc

tests/pkg/emlearn/README.md
The model is actually generated in the model.h not sonar.h. I think that filename was used (hard coded?) in the very early versions of that example.
A second commit is added to drop the last sentence that states the header file is automatically generated which is not true anymore.
Just read. The model header file is generated using the `generate_model.py` script. The `main.c` file doesn't include `sonar.h`
None
=> tests/pkg/emlearn: fix wrong model header file name in README

drivers/include/sx126x.h, drivers/sx126x/Makefile.include, drivers/sx126x/include/sx126x_params.h, drivers/sx126x/sx126x.c
The dio2 and dio3 pins of `sx126x` are optional. They can be used as IRQ pins. dio2 can be used as RF switch pin and dio3 can be used to feed 32MHz to a Temperature-Compensated Crystal Oscillator (TCXO). Those are special hardware configurations.
Read:
[dio2](https://www.mouser.com/datasheet/2/761/DS_SX1261-2_V1.1-1307803.pdf#%5B%7B%22num%22%3A240%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C54%2C463%2Cnull%5D)
[dio3](https://www.mouser.com/datasheet/2/761/DS_SX1261-2_V1.1-1307803.pdf#%5B%7B%22num%22%3A240%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C95%2C217%2Cnull%5D)
By default if the modules `sx126x_dio2` and `sx126x_dio3` are used, the pins are assumed to be interrupt pins.
You can use the dio2 RF switch like this:
```C
#define SX126X_DIO2_MODE …
```
=> drivers/sx126x: add support for Dio2 and Dio3

sys/include/net/nanocoap_sock.h, sys/net/application_layer/nanocoap/nanocoap.c, sys/net/application_layer/nanocoap/sock.c
Requests larger than `CONFIG_NANOCOAP_SERVER_BUF_SIZE` were previously silently ignored.
But we can do better: With `sock_udp_recv_buf_aux()` we don't need to copy the request into a separate buffer but can just use the buffer allocated by the network stack.
We still need `CONFIG_NANOCOAP_SERVER_BUF_SIZE` for the response as otherwise the size of the request packet would be the limit for the response packet. But this is now both in control of the server, a good server implementation can only use this for the header and keep the payload in a separate buffer.
The only problem is that several CoAP handler functions (e.g. [`_sha256_handler()`](https://github.com/RIOT-OS/RIOT/blob/master/examples/networking/coap/nanocoap_server/coap_handler.c#L116)) expect `pkt->hdr` to point to the response …
=> nanocoap_server: use zero-copy network buffer for parsing request

sys/suit/handlers_command_seq.c
The firmware URL is actually interesting if something goes wrong, increase the log level from DEBUG to INFO.
=> sys/suit: print firmware URL if download fails

drivers/sx126x/sx126x.c
Fail `init()` when no `sx126x` driver is connected.
Else this https://github.com/RIOT-OS/RIOT/blob/3eee3687d80fc5a365d8dece7be6df26d30b7fb3/sys/net/gnrc/netif/gnrc_netif.c#L1636 assert() triggers for the driver.
Run `DEVELHELP=1 VERBOSE_ASSERT=1 BOARD=adafruit-metro-m4-express USEMODULE+="shell_cmd_ps shield_sx1262" make -C examples/networking/gnrc/gnrc_lorawan flash term PORT=/dev/ttyACM0` with and without a connected device.
=> drivers/sx126x: fail on init if no device is connected

README.md
Inspired by comments in #21052  especially https://github.com/RIOT-OS/RIOT/pull/21052#discussion_r1863848019 this tries to improve Riots Feature List 
read [kfessel:p-improve-feature-list](https://github.com/kfessel/RIOT/tree/p-improve-feature-list)
read [kfessel:p-improve-feature-list:README.md](https://github.com/kfessel/RIOT/tree/p-improve-feature-list/README.md)
#21052
at the same time ( for future reference)
#21061
#21063
=> README.md: improve feature list

drivers/include/sx126x.h, drivers/sx126x/sx126x.c, drivers/sx126x/sx126x_netdev.c
Makes it possible to use different transmission powers on sx126x.
I did not necessarily add a field to save the Tx power because this would come in with the radio HAL adaptation.
`DEVELHELP=1 VERBOSE_ASSERT=1 BOARD=adafruit-metro-m4-express USEMODULE+="shell_cmd_ps shield_sx1262" make -C examples/networking/gnrc/gnrc_lorawan flash term PORT=/dev/ttyACM0`
Split out from #21675
=> drivers/sx126x: bind PA config to output power

makefiles/tools/openocd-adapters/stlink.inc.mk, makefiles/tools/openocd.inc.mk
When `OPENOCD_DEBUG_ADAPTER` was set to `stlink`, no `openocd.cfg` was needed for most STM32 boards. (But one could still be provided if special handling was needed.) However, for any other debug adapter this was not the case.
This moves the handling for when no custom `openocd.cfg` is provided from the `stlink.inc.mk` to `openocd.inc.mk`, so that most boards now work out of the box with other debuggers.
Tested with `OPENOCD_DEBUG_ADAPTER=jlink` with a yet to be upstreamed STM32 board. B
Fixes one of the issues we ran into on the RIOT summit Hackathon when adding the Olimexino-STM32F3 board definition
=> makefiles/tools/openocd: Do not require openocd.cfg for STM32 boards

doc/starlight/astro.config.mjs
I renamed the title tag of the RIOT guides website to write `RIOT` instead of `Riot`.
We always write RIOT's name as `RIOT` and not as `Riot` in all places I checked.
E.g.:
- https://www.riot-os.org/
- https://doc.riot-os.org/
- main readme.md
=> doc/starlight: rename guides title from Riot to RIOT

doc/starlight/astro.config.mjs
The guides page was already providing links (at the top right) to GitHub, Matrix and Mastodon, but not to the forum.
So I added a simple link to the RIOT discourse :)
=> doc/starlight: Add link to RIOT forum

doc/guides/rust_tutorials/create_project.mdx
This should reduce potential errors as happened in #21733 and make it easier to understand when/how to build stuff within our docker container. 
`make doc-starlight`
This closes #21733
=> doc/guides/rust_tutorials: mention BUILD_IN_DOCKER more verbosely

pkg/lvgl/contrib/lvgl.c, pkg/lvgl/include/lv_conf.h, sys/auto_init/screen/auto_init_lvgl.c
This enables using monochrome displays via the [Display Device Generic API](https://doc.riot-os.org/group__drivers__disp__dev.html) and the [u8g2](https://github.com/olikraus/u8g2/) package.
I've tested this on two displays with the 1306 driver. In the examples below there's a random counter that updates a label and a line plot on the left.
[i2c.webm](https://github.com/user-attachments/assets/3b90795c-55be-4122-8eaa-ae02923a5085)
(ignore PCB marking, connection is a 4-wire SPI :)
[spi.webm](https://github.com/user-attachments/assets/6c13c2f9-2b62-4ef4-802a-2b239c54aec1)
The test application `tests/pkg/lvgl` should work after adapting it to the correct resolution.
Depends on #21725
=> pkg/lvgl: support monochrome displays via u8g2

makefiles/docker.inc.mk, makefiles/tests/tests.inc.mk
When building for native with `BUILD_IN_DOCKER=1`, the created elf file may not be compatible with the host system if:
- The container used is using glibc and the host system is using another C lib
- Both container and host are using glibc, but the container is using a more recent one than the host
To avoid these issues, this commit changes behavior to just run the `test` goal inside the docker image as well when the board is `native%`.
Run the following commands:
1. `make -C tests/sys/fmt_print all test BOARD=native64 BUILD_IN_DOCKER=1`
- Build should be run in docker
- Test should be run in docker
2. `make -C tests/sys/fmt_print all test BOARD=native BUILD_IN_DOCKER=1`
- Build should be run in docker
- Test should be run in docker
3. `make -C tests/sys/fmt_print all test BOARD=native64` …
=> build system: Allow running tests in docker

cpu/samd5x/periph/can.c
ISR on cortex_m shall end with `cortexm_isr_end();` to ensure the scheduler is run 
read
=> cpu/samd5x/can: add missing cortexm_isr_end

cpu/kinetis/include/bme.h, drivers/kw41zrf/kw41zrf.c, drivers/kw41zrf/kw41zrf_getset.c, drivers/kw41zrf/kw41zrf_netdev.c
The kinetis bme implementation currently doesn't work proberly, see https://github.com/RIOT-OS/RIOT/pull/21705#discussion_r2389433571.
This PR temporarily sets `BITBAND_FUNCTIONS_PROVIDED` to false so that the default `sys/bit` implementation for bit manipulation is used instead. 
Came up while extending the `bme` implementation in #21705.  
Unblocks #21577.
=> kinetis/bme: temp disable `BITBAND_FUNCTIONS_PROVIDED`

dist/tools/ci/print_toolchain_versions.sh
Currently the print-version script used for debugging does not include information about the Rust and Frontend environment. While at it I thought it might also make sense to include information about the exact state the RIOT repository is in, esp. to debug cases where the RIOT repository might simply be outdated.
```
[ann@computer RIOT]$ make print-versions 
Operating System Environment
----------------------------
Operating System: "EndeavourOS" 
Kernel: Linux 6.16.5-arch1-1 x86_64 unknown
System shell: GNU bash, version 5.3.3(1)-release (x86_64-pc-linux-gnu)
make's shell: GNU bash, version 5.3.3(1)-release (x86_64-pc-linux-gnu)
Installed compiler toolchains
-----------------------------
native gcc: gcc (GCC) 15.2.1 20250813
arm-none-eabi-gcc: missing
avr-gcc: missing
msp430-elf-gcc: …
```
=> dist/tools/ci: include rust, node and git commit in print-version

examples/networking/gnrc/gnrc_border_router/Makefile, sys/Makefile, sys/include/net/dns.h, sys/include/net/hosts.h, sys/include/net/ipv4/addr.h, sys/net/application_layer/hosts/Makefile, sys/net/application_layer/hosts/hosts.c, sys/net/netutils/util.c, sys/net/sock/sock_util.c
Operating with hostnames instead of raw IP addresses can be more convenient in applications.
On Linux we have `/etc/hosts` where we can statically define hostname -> IP mappings.
This module adds something similar to RIOT.
Enable the `hosts` module. The XFA is by default populated with a `localhost` entry:
```
2025-04-11 17:49:05,409 # > ping localhost
2025-04-11 17:49:05,414 # 12 bytes from ::1: icmp_seq=0 ttl=64 time=0.202 ms
2025-04-11 17:49:06,414 # 12 bytes from ::1: icmp_seq=1 ttl=64 time=0.202 ms
2025-04-11 17:49:07,414 # 12 bytes from ::1: icmp_seq=2 ttl=64 time=0.202 ms
2025-04-11 17:49:07,415 # 
2025-04-11 17:49:07,417 # --- localhost PING statistics ---
2025-04-11 17:49:07,422 # 3 packets transmitted, 3 packets received, 0% packet loss
2025-04-11 17:49:07,426 # round-trip …
```
=> net/hosts: add module for static hostname definitions

CODEOWNERS
Hello! 🐸
This removes @PeterKietzmann as code owner. I asked him out of band, he was a bit hesitant which I interpreted as "I would like to remain a maintainer" but okay with the code owner cleanup.
In addition, I add myself to the unittests. Unittests have always been one of my favorite topics.
=> codeowner: Remove PeterKietzmann and add Teufelchen

doc/guides/advanced_tutorials/porting_boards.md
As "discovered" in #21745, the common code process introduced in #21327 was not sufficiently documented yet.
Also in #21708, the documentation added in #21327 was removed for some reason, therefore I re-added it here.
Lastly, one of the `Further Reference` links was broken, that also got fixed.
Run `make doc-starlight` and look at the documentation.
Better document the new proecss introduced in #21327.
Re-add documentation errorneously removed in #21708.
=> doc/guides: Add Section about Creating a Common Board Directory

sys/include/bit.h, tests/unittests/tests-bit/Makefile, tests/unittests/tests-bit/tests-bit.c, tests/unittests/tests-bit/tests-bit.h
This adds unit tests for the functions from `bit.h`
Just run `make -C tests/unittests tests-bit`
depends on #21705
=> tests/unittests: add test for bit.h

cpu/stm32/dist/kconfig/Kconfig.lines.j2, cpu/stm32/dist/kconfig/Kconfig.models.j2, cpu/stm32/dist/kconfig/gen_kconfig.py
In https://github.com/RIOT-OS/RIOT/pull/21758#discussion_r2405762997 @crasbe spotted that in `cpu/stm32/dist/kconfig` directory there is a little utility tool `genkconfig` which generates Kconfig files with old style licenses. This PR fix this issue, plus move license of the script to SPDX, too.
Review changed files.
Track https://github.com/RIOT-OS/RIOT/issues/21515
=> cpu/stm32/genkconfig: move script licence and templates to SPDX
