Makefile.include
=> make: escape unknown version string

cpu/native/include/nativenet.h
=> native: increase buffer size, set defaults conditionally

cpu/stm32f0/periph/uart.c
Optimized the UART driver for less memory usage. See numbers for `tests/periph_uart_int`:
before:
```
text	   data	    bss	    dec	    hex
19464	    116	   5548	  25128	   6228
```
and after:
```
text    data     bss     dec     hex
18544     116    5548   24208    5e90
```
=> cpu/stm32f0: optimizations to UART driver

sys/base64/Makefile, sys/base64/base64.c, sys/include/base64.h, tests/unittests/tests-base64/Makefile, tests/unittests/tests-base64/Makefile.include, tests/unittests/tests-base64/tests-base64.c, tests/unittests/tests-base64/tests-base64.h
This module provides encoding and decoding of base64 strings.
=> base64 encoding/decoding module

sys/net/transport_layer/udp/udp.h
added doxygen and removed two redundant function definitions.
=> net/udp: cleaned up header and documentation

examples/default/main.c, examples/rpl_udp/helper.c, sys/net/network_layer/sixlowpan/mac.c, sys/net/routing/etx_beaconing.c, tests/nativenet/main.c
Started working on fixing #2346
=> Removing (some) common globals

boards/samr21-xpro/Makefile.include, boards/samr21-xpro/dist/debug.sh, boards/samr21-xpro/dist/gdb.conf
=> Samr21: autostart gdb when running make debug

sys/chardev_thread.c, sys/include/timex.h, sys/timex/timex.c, sys/vtimer/vtimer.c
I enabled debug output in all files to poke around
and there were some errors (seemingly) due to code
changes that were not tested with debug enabled. This
commits tries to fix these issues.
=> Fix misc errors that occur with ENABLE_DEBUG

boards/stm32f0discovery/Makefile.include, boards/stm32f0discovery/dist/debug.sh, boards/stm32f0discovery/dist/flash.sh, boards/stm32f0discovery/dist/gdb.cfg, boards/stm32f0discovery/dist/gdb.conf, boards/stm32f0discovery/dist/reset.sh
switched flashing and debug scripts to use OpenOCD
=> board/stm32f0discovery: switched to OpenOCD

examples/rpl_udp/rpl.c
The radio channel is set unconditionally on initialization of a node, it is set to `RADIO_CHANNEL` which is out of range e.g. for the AT86RF23 on the iot-lab_M3.
Also it overrides the setting if the channel has been set previously, i.e. using the `chan` command before invoking `init (r|n|h)`.
This PR changes the `init` procedure to use the set or default channel provided by the `TRANSCEIVER` and only tries to set it to `RADIO_CHANNEL` if the transceiver cannot use the set channel.
On failing setting the channel the `init` procedure aborts.
=> examples/rpl_udp: Fix unconditional setting of a radio channel on initialization

sys/include/embUnit.h, sys/shell/commands/sc_net_if.c, tests/unittests/main.c, tests/unittests/tests-core/tests-core-atomic.c, tests/unittests/tests-core/tests-core-bitarithm.c, tests/unittests/tests-core/tests-core-cib.c, tests/unittests/tests-core/tests-core-clist.c, tests/unittests/tests-core/tests-core-lifo.c, tests/unittests/tests-core/tests-core-priority-queue.c, tests/unittests/tests-core/tests-core.c, tests/unittests/tests-core/tests-core.h, tests/unittests/tests-netdev_dummy/tests-netdev_dummy.c, tests/unittests/tests-netdev_dummy/tests-netdev_dummy.h, tests/unittests/tests-nomac/tests-nomac.c, tests/unittests/tests-nomac/tests-nomac.h, tests/unittests/tests-pkt/tests-pkt.h, tests/unittests/tests-pktbuf/tests-pktbuf.h, tests/unittests/tests-pktqueue/tests-pktqueue.c, tests/unittests/tests-pktqueue/tests-pktqueue.h
Addresses https://github.com/RIOT-OS/RIOT/pull/2409#discussion_r24300529
=> doc: Add mail address where it is missing

sys/Makefile, sys/include/net/ng_netapi.h, sys/net/crosslayer/ng_netapi/Makefile, sys/net/crosslayer/ng_netapi/ng_netapi.c
as promised the simplified version of `netapi`, cut down to a very nice manageable size of ~50 lines of code...
=> ng_net: add new version of NETAPI

sys/Makefile, sys/include/net/ng_netif.h, sys/net/crosslayer/ng_netif/Makefile, sys/net/crosslayer/ng_netif/ng_netif.c, tests/unittests/tests-netif/Makefile, tests/unittests/tests-netif/Makefile.include, tests/unittests/tests-netif/tests-netif.c, tests/unittests/tests-netif/tests-netif.h
~~Depends on #2397~~ It does not
=> netif: Initial import of ng_* version

cpu/native/include/native_internal.h, cpu/native/startup.c, cpu/native/syscalls.c
- detach from working directory
- detach from process group
- set umask
- add required syscall wrappers
Should make daemonzied processes more well-behaved in dynamic environments.
=> native: enhance daemonization

.travis.yml, dist/tools/travis-scripts/build_and_test.sh, dist/tools/travis-scripts/get-pkg-list.py
=> travis: add static tests as a matrix build target

sys/net/crosslayer/ng_netapi/ng_netapi.c
- renamed opt variable in _get_set
- fixed msg type MACRO names
sometimes you wonder what slips through...
=> net/ng_netapi: fixed implementation

sys/net/link_layer/net_if/net_if.c, sys/net/network_layer/sixlowpan/ip.c, sys/net/network_layer/sixlowpan/lowpan.c, sys/net/network_layer/sixlowpan/mac.c
=> sixlowpan: Handle short hardware addresses correctly

tests/driver_lis3dh/main.c
Trivial error in lis3dh test application.
=> tests/lis3dh: Fix SPI_CONF #define

core/include/msg.h
=> core: document msg_reply_int()

core/include/msg.h
Sometimes two ACKs are not enough... (#2539)
=> core: added missing semicolon in header

cpu/kinetis_common/uart.c
This enables the RX and TX FIFOs in the Kinetis UART hardware module.
Tested on K60, improves RX alot when using high baud rates, I used to lose bytes because of a full RX buffer without this.
This change may affect the timing/latency of TX since we can now queue sizeof(TXFIFO) bytes before blocking when writing to the UART, instead of only writing one byte non-blocking.
Disabled for CPUs without KINETIS_UART_ADVANCED (KW0x etc)
=> kinetis: Enable UART hardware FIFO buffers.

examples/ccn-lite-client/HOWTO, sys/include/fd.h, sys/posix/fd.c, sys/posix/pnet/sys_socket.c, sys/posix/unistd.c
-Fixes  #1759 
-Also fixed a minor typo in previous description
=> Changed description for fd_t::fd in sys/include/fd.h

sys/include/net/ng_ethernet.h, sys/include/net/ng_ethernet/hdr.h, sys/include/net/ng_ethertype.h
Does what it says on the tin ;-)
=> net: initial import of ethertypes and the ethernet header

sys/Makefile
Otherwise apps are not happy ;-)
=> ng_nomac: add to sys/Makefile

boards/stm32f0discovery/include/periph_conf.h, cpu/stm32f0/periph/timer.c
Now the timer definition for the F0 is the same as for the F1, F3 and F4...
=> cpu/stm32f0: cleanup for timer IRQ macro

boards/stm32f0discovery/include/periph_conf.h, cpu/stm32f0/periph/gpio.c
- guarded calls in case no interrupt is defined
- eneabled detection of multiple, simoultaneous events
=> cpu/stm32f0: fixed gpio interrupt routines

boards/arduino-due/Makefile.include, boards/arduino-due/dist/flash.sh, boards/spark-core/Makefile.include
#2480 broke the flashing for the arduino-due and the spark core (-> see also issue #2615)
This PR fixes #2615 and also the spark-core...
=> boards: fix flashing of arduino-due and spark-core

Makefile.dep, sys/shell/commands/Makefile, sys/shell/commands/sc_netif.c, sys/shell/commands/shell_commands.c
~~Depends on #2580~~ (merged). Will port IPv6 support as follow-up to #2437 (see #2582).
This merges the functionality of #2525 with this of the original `ifconfig` command
=> shell: port ifconfig for ng_netif

boards/nucleo-f091/Makefile, boards/nucleo-f091/Makefile.features, boards/nucleo-f091/Makefile.include, boards/nucleo-f091/board.c, boards/nucleo-f091/dist/openocd.cfg, boards/nucleo-f091/include/board.h, boards/nucleo-f091/include/periph_conf.h, cpu/stm32f0/include/cpu-conf.h, cpu/stm32f0/include/stm32f091xc.h, cpu/stm32f0/startup.c, cpu/stm32f0/stm32f091rc_linkerscript.ld
~~rebased on #2593~~
Needed a board for testing the xbee driver and this was only one I had laying around... So here is the port :-)
=> boards: added support for ST nucleo-f091

Makefile.dep
seems like some spaces slipped into the `Makefile.dep` which contains only tabs for indention otherwise...
=> make: made consistent use of spaces in Makefile.dep

boards/nucleo-f334/dist/openocd.cfg
minor fix to adjust to latest OpenOCD changes...
=> boards/nucleo-f334: adjusted openocd config

Makefile.dep, sys/Makefile, sys/include/net/ng_ipv6.h, sys/include/net/ng_ipv6/netif.h, sys/net/crosslayer/ng_netif/ng_netif.c, sys/net/network_layer/ng_ipv6/netif/Makefile, sys/net/network_layer/ng_ipv6/netif/ng_ipv6_netif.c, tests/unittests/Makefile, tests/unittests/tests-ipv6_netif/Makefile, tests/unittests/tests-ipv6_netif/Makefile.include, tests/unittests/tests-ipv6_netif/tests-ipv6_netif.c, tests/unittests/tests-ipv6_netif/tests-ipv6_netif.h
~~Depends on #2433.~~ (merged)
~~Depends on #2546 for debug output~~ (merged)
=> ng_ipv6: provide support for ng_netif

sys/include/net/ng_netbase.h
=> net/ng_netbase: added include of ng_netif/hdr.h

cpu/atmega2560/periph/timer.c, cpu/cc430/periph/rtc.c, cpu/lpc2387/lpc23xx-iap.c, cpu/samd21/periph/i2c.c, cpu/samd21/periph/spi.c, sys/net/ccn_lite/ccnl-core.c, sys/net/routing/etx_beaconing.c, sys/net/routing/rpl/rpl_dodag.c, sys/shell/commands/sc_sht11.c
Some functions had no blank lines to separate them from their
neighborhood.
=> *: add missing blank lines

tests/unittests/netdev_dummy/include/netdev_dummy.h
=> unittests/netdev_dummy: fixed header file include guard

tests/unittests/tests-pktbuf/tests-pktbuf.h
=> unittests/tests-pktbuf: fixed header file include guard

tests/unittests/tests-pktqueue/tests-pktqueue.h
=> unittests/tests-pktqueue: fixed header file include guard

tests/unittests/tests-timex/tests-timex.h
=> unittests/tests-timex: fixed header file include guard

tests/unittests/tests-base64/tests-base64.h
=> unittests/tests-base64: fixed header file include guard

tests/unittests/tests-crypto/tests-crypto.h
=> unittests/tests-crypto: fixed header file include guard

tests/unittests/tests-netdev_dummy/tests-netdev_dummy.h
=> unittests/tests-netdev_dummy: fixed header file include guard

tests/unittests/tests-netif/tests-netif.h
=> unittests/tests-netif: fixed header file include guard

tests/unittests/tests-netreg/tests-netreg.h
=> unittests/tests-netreg: fixed header file include guard

tests/unittests/tests-pkt/tests-pkt.h
=> unittests/tests-pkt: fixed header file include guard

boards/airfy-beacon/Makefile.features, boards/arduino-due/Makefile.features, boards/avsextrem/Makefile.features, boards/cc2538dk/Makefile.features, boards/chronos/Makefile.features, boards/fox/Makefile.features, boards/iot-lab_M3/Makefile.features, boards/msba2/Makefile.features, boards/msbiot/Makefile.features, boards/native/Makefile.features, boards/nucleo-f091/Makefile.features, boards/nucleo-l1/Makefile.features, boards/openmote/Makefile.features, boards/pca10000/Makefile.features, boards/pca10005/Makefile.features, boards/samr21-xpro/Makefile.features, boards/stm32f0discovery/Makefile.features, boards/stm32f3discovery/Makefile.features, boards/stm32f4discovery/Makefile.features, boards/udoo/Makefile.features, boards/wsn430-v1_3b/Makefile.features, boards/wsn430-v1_4/Makefile.features, boards/yunjia-nrf51822/Makefile.features
Boards list their features one per row compared to all their features on one or two rows. This fixes #2611.
=> boards/Makefile.features: one feature per row

core/clist.c, core/lifo.c
=> core: remove lagacy tests from clist and lifo

sys/net/routing/rpl/rpl_dodag.c
=> rpl: edit debug message for instance == NULL

cpu/cortex-m4_common/thread_arch.c
Clang 3.6 is stricter than GCC and previous releases of Clang regarding
naked functions and now only allows inline asm inside naked functions (i.e. no C code).
This is a refactoring of the functions isr_pendsv, isr_svc,
context_save, context_restore to still be naked functions but allow
building with Clang 3.6
Building the current C/asm mixed naked function with Clang 3.6 results in:
.../RIOT/cpu/cortex-m4_common/thread_arch.c:145:5: error: non-ASM statement in naked function is not supported
enableIRQ();
^
.../RIOT/core/include/arch/irq_arch.h:40:25: note: expanded from macro 'enableIRQ'
#define enableIRQ       irq_arch_enable
^
.../RIOT/cpu/cortex-m4_common/thread_arch.c:142:16: note: attribute is here
__attribute__((naked)) void NORETURN thread_arch_start_threading(void)
^ …
=> cortex-m4_common: Refactor context save/restore

boards/stm32f3discovery/Makefile.features
the STM32F3 is build on top of a Cortex-M4 :-)
=> boards/stmf3discovery: fixed MCU GROUP

core/include/cib.h
=> core: limit message queue size

core/include/cib.h
Reverts RIOT-OS/RIOT#2674
PR was merged without proper review and without ACKs
=> Revert "core: limit message queue size"

sys/net/link_layer/ng_nomac/ng_nomac.c
=> net/ng_nomac: added missing return in event cb

sys/shell/commands/shell_commands.c
I don't like the line break in the description - and if one needs help with the usage, just call the command to get that information. Also this saves some byte of flash :-)
=> sys/shell: shortened description of netif shell cmd

sys/shell/commands/Makefile
stumbled upon another one, see #2626 for explanation.
=> sys/shell_commands: Makefile: converted tabs to spaces

sys/include/net/ng_nettype.h
Got an extra letter in ICMP somehow :-D
=> nettype: fix typo

tests/unittests/README.md, tests/unittests/common/unittests-constants.h, tests/unittests/tests-core/tests-core.h, tests/unittests/tests-ipv6_nc/tests-ipv6_nc.h
Refering to the issue #2623. Have modified the module tests  include guards . Please review .
=> tests: Updated include guards to remove leading underscores

core/include/arch/atomic_arch.h, core/include/arch/irq_arch.h, core/include/arch/lpm_arch.h, core/include/arch/reboot_arch.h, core/include/arch/thread_arch.h, core/include/cib.h, core/include/clist.h, core/include/crash.h, core/include/debug.h, core/include/hwtimer.h, core/include/lifo.h, core/include/msg.h, core/include/mutex.h, core/include/priority_queue.h, core/include/ringbuffer.h, core/include/thread.h
Refering to the issue #2623. Have modified the module cores include guards . Please review.
=> core: Updated include guards to remove leading underscores

drivers/include/isl29020.h, drivers/include/l3g4200d.h, drivers/include/ltc4150_arch.h, drivers/isl29020/include/isl29020-internal.h
Refering to the issue #2623. Have modified the driver modules include guards . Please review.
=> drivers : Update include guards to remove leading underscores

examples/ccn-lite-client/main.c, sys/shell/commands/sc_lps331ap.c, sys/shell/commands/sc_rtc.c
@kushalsingh007's #2602 introduced some tabs. This removes them.
=> style: replace tabs with spaces in source

core/include/debug.h
=> Revert "debug.h: check stacksize fixed"

cpu/x86/x86_threading.c
The ucontext->x86_fxsave is initialize as 512 bytes of zeros, but it
is not a valid value to be set onto FPU registers, causing a General
Protection Fault:
Interrupt 0x0d (General Protection Fault) while handling 0x07 (Device not available)
EAX=0012f4c0  ECX=001336e4  EDX=001334ac  EBX=001336e0
ESP=00123784  EBP=001237c8  ESI=00000200  EDI=00000000
Error code=00000000
CR0=80010031  CR2=00000000  CR3=0012d000  CR4=000001e0
EIP=0000:80010031  EFLAGS=0012d000
<stack trace>
00000000
???
</stack trace>
Halting.
So lets copy the initial state of FPU registers before FPU is used
and set it as the initial state of FPU to new threads(coroutine).
=> Fix x86 FPU lazy swap

tests/unittests/tests-hash_string/tests-hash_string.c, tests/unittests/tests-hash_string/tests-hash_string.h
- Created unittests for hash_string module present in sys/hash_string
- Fixes a part of #1131
- Created a new PR because of some problems in my previous branch for #2698
=> Tests: Creating unittests for the hash_string module

sys/include/net/ng_pktbuf.h
Adds the convenience function discussed in #2794.
=> pktbuf: add helper function to remove snips from packet

sys/shell/commands/sc_fib.c
=> sys/shell: added missing return values for FIB command handler

drivers/xbee/xbee.c
seems like I forgot some `static` declarations...
=> drivers/xbee: declared private functions as static

Makefile.dep, sys/net/crosslayer/ng_pktdump/ng_pktdump.c
Depends on #2697 and ~~#2731~~ (merged).
=> pktdump: add IPv6 header dump

sys/include/net/ng_pktbuf.h
=> pktbuf: fix snip-was-head case for pktbuf_remove_snip

sys/include/ps.h, sys/ps/ps.c, sys/shell/commands/sc_ps.c
Better ideas for the function name are welcome.
=> ps: fix module prefix and documentation plus minor cleanup

sys/net/crosslayer/ng_pktdump/ng_pktdump.c
=> pktdump: fix formatting of snips and false illegal version warning

sys/posix/pthread/include/pthread_cond.h
=> Add fix for clockid_t on OS X

doc/doxygen/riot.doxyfile
=> doxygen: generate graphs for includes

sys/shell/commands/sc_netif.c
It works exactly as the [POSIX](http://www.freebsd.org/cgi/man.cgi?ifconfig%288%29) [ifconfig](http://linux.die.net/man/8/ifconfig)
=> shell: sc_netif: add set/unset for flags

sys/include/net/ng_pktbuf.h
=> pktbuf: clarify doc of pktbuf_add()

sys/shell/commands/sc_netif.c
If we have return values, we should utilize them :-)
=> shell: fix netif command for return values

doc/doxygen/riot.doxyfile
=> doc: order modules alphabetically

sys/shell/commands/sc_netif.c
~~Depends on #2614 and #2778 (and all their dependencies).~~ (merged)
=> shell: add support for (un-)setting 6LoWPAN support on an interface

drivers/xbee/xbee.c, tests/driver_xbee/main.c
- added getters for some netconf options (ADDR_LEN, SRC_LEN), needed by 6LoWPAN and IPv6
- optimized address generation
- added output for initialization ok in the xbee test application
=> drivers/xbee: misc enhancements

dist/tools/travis-scripts/build_and_test.sh
I somehow forgot to set an essential parameter ^^"
=> travis: Actually use the build-skip feature

sys/shell/commands/sc_netif.c
edit:
~~now rebased on #2778 and #2845~~
=> sys/shell: added RAWMODE option to netif sc

Makefile.dep, sys/Makefile, sys/auto_init/auto_init.c, sys/include/net/ng_udp.h, sys/net/crosslayer/ng_netreg/ng_netreg.c, sys/net/transport_layer/ng_udp/Makefile, sys/net/transport_layer/ng_udp/ng_udp.c
this PR depends on many other `ng_` PRs, will detail them out once this PR gets in a state of being testable/reviewable. I will try to provide a first approach for a socket implementation to make this code better understandable.
While writing this code, I came across some issues we should think about:
~~1. how do we handle the checksum calculation when sending data and the src address is still unknown?~~
~~2. where do we get the source port from, if not using sockets but talking directly to UDP via NETAPI?~~
UPDATE: This implementation is now ready for testing
~~UPDATE 2: rebased on #2801~~
=> net: added ng_udp implementation

.travis.yml
The bytesatwork mirror is currently down...
=> Travis: change emdebian mirror

drivers/ng_at86rf2xx/ng_at86rf2xx_getset.c
=> drivers/ng_at86rf2xx: disable debug

sys/net/network_layer/ng_sixlowpan/frag/rbuf.c, sys/net/network_layer/ng_sixlowpan/frag/rbuf.h, sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c
=> ng_sixlowpan: fixes

sys/net/network_layer/ng_ipv6/ng_ipv6.c
Forgot to use this function after it was introduced.
=> ng_ipv6: use netapi_receive()

drivers/ng_at86rf2xx/ng_at86rf2xx_getset.c, drivers/ng_at86rf2xx/ng_at86rf2xx_netdev.c, sys/include/net/ng_netconf.h
ARM once nominated me as RIOT cleaner, I should justify this reputation.
=> at86rf231: minor cleanup

sys/net/network_layer/ng_sixlowpan/frag/rbuf.c
Another day, another bug me and @PeterKietzmann found.
=> sixlowpan_frag: another bugfix for reassembly

sys/net/network_layer/ng_ipv6/ng_ipv6.c
If no interface is given for a multicast, but the node has only one, it must be set.
=> ng_ipv6: set interface for multicast

sys/net/network_layer/ng_ipv6/ng_ipv6.c
=> ng_ipv6: fix debug output

sys/net/network_layer/ng_ipv6/ng_ipv6.c
=> ng_ipv6: fix for API change in #2908

.drone.yml, dist/tools/drone-scripts/build_and_test.sh
This PR adds support for running buildtests in Drone.
Drone is a continuous integration server that can be installed locally.
The included Drone configuration mimics the Travis build scripts except for the build matrix feature, all targets are built sequentially by the `dist/tools/drone-scripts/build_and_test.sh` script instead of in
separate instances.
See: https://github.com/drone/drone
I am still experimenting with Drone and learning about it so this may not be the cleanest configuration file possible.
Short guide for running Drone inside a Docker instance
-----
install Docker:
```sh
sudo apt-get install lxc-docker
```
Pull the Drone image:
```sh
docker pull drone/drone:latest
```
Create the configuration in `~/drone/drone.toml`
```
[database]
driver="sqlite3" …
```
=> drone: added Drone file

drivers/include/isl29125.h
For consistency and identification.
=> drivers/isl29125: fix group description

cpu/nrf51822/periph/random.c
My goal is to drive one NRF51 controller via CR2032 cell for an minimum of three years with radio network. This needs to reduce average current to 7.5uA.  This is one small step to reach this goal.
This PR has some effects:
1. PAN #21 fix for better RNG quality
2. random_read doesn't hang when random is powered off
3. auto powerdown RNG to save 16uA current
4. reduce code size for RNG power handling
5. fix hanging random after poweroff() and poweron()
=> cpu/nrf51822/periph/random Power optimization

Makefile.dep, Makefile.pseudomodules, core/hwtimer.c, core/include/log.h, core/kernel_init.c, core/lifo.c, core/sched.c, sys/Makefile, sys/Makefile.include, sys/log/Makefile, sys/log/Makefile.include, sys/log/log_printfnoformat/log_module.h
introduce logging API.
(includes log_printnoformat by @LudwigOrtmann)
=> core: introduce logging API

drivers/include/xbee.h, drivers/ng_at86rf2xx/ng_at86rf2xx.c, drivers/xbee/xbee.c, sys/include/net/ng_ieee802154.h
=> at86rf2xx: fix EUI64 computation

boards/mulle/Makefile.features
It was missing... (like kw2x in #3010)
=> mulle: Add FEATURES_MCU_GROUP=cortex_m4

boards/pba-d-01-kw2x/dist/mkw22d512.cfg, boards/pba-d-01-kw2x/dist/pll_freq.m, boards/pba-d-01-kw2x/include/board.h, boards/pttu/tools/openocd-pttu.sh, boards/redbee-econotag/tools/mc1322x-load.pl, cpu/stm32f0/include/stm32f091xc.h, doc/doxygen/src/riot-footer.html, examples/rpl_udp/README.md, tests/malloc/main.c, tests/pkg_micro-ecc/main.c
=> Tab indentation fixes

Makefile.dep, Makefile.pseudomodules
Only applies if ng_ipv6 also was included.
=> ng_net: add 6LoWPAN as dependency for IEEE 802.15.4 devices

sys/net/network_layer/ng_ipv6/netif/ng_ipv6_netif.c, tests/unittests/tests-ipv6_netif/tests-ipv6_netif.c
This PR resolves https://github.com/RIOT-OS/RIOT/issues/2965 for  ``ipv6_ifs ``and ``ipv6_ifs[i].addrs`` in  ``ng_ipv6_netif.c`` and adds tests for this situation.
=> ng_ipv6_netif: no more duplicates if empty entries are found before

sys/net/crosslayer/ng_netif/ng_netif.c
prevent ng_netif_add() from adding duplicates as described in https://github.com/RIOT-OS/RIOT/issues/2965
=> ng_netif: don't add duplicates

dist/tools/pyterm/pyterm
=> Pyterm newline

cpu/saml21/include/cpu_conf.h, cpu/saml21/startup.c
=> cpu/saml21: fixed and cleaned up startup.c

sys/net/network_layer/sixlowpan/ip.c
This introduces a compatibility "option" to enable FIB in the ip part of the  good ol' network stack .
Rationale: 
To enable using the FIB in the old stack requires to change the `get_next_hop()` calls in `ip.c`.
Contrary to the prior registered functions of the routing protocols, the `fib_get_next_hop()` function must be called.
Just switching to the FIB functions would break (routing protocol) implementations using the old approach. 
So this PR introduces a compatibility "option" that enables to switch between the FIB and the former direct routing protocol next-hop request handling.
=> ip: added a define to enable a FIB compatibility mode replacing `get_next_hop()`

dist/tools/ng_sniffer/ng_sniffer.py
- now working with the samr21 through removed uart flow control calls
- removed unused code
- move and added some comments
=> dist: some fixes to the ng_sniffer script

boards/saml21-xpro/Makefile.features, boards/saml21-xpro/include/periph_conf.h, cpu/saml21/periph/rtt.c
=> saml21: add periph rtt support

sys/net/crosslayer/ng_pktbuf/ng_pktbuf.c
Fixes #3088 and also some weird artifacts I discovered when writing #3089.
=> ng_pktbuf: Some fixes

sys/net/crosslayer/ng_pktbuf/ng_pktbuf.c
Adds some debug lines to the packet buffer module.
=> ng_pktbuf: add DEBUG output

boards/native/Makefile.dep, boards/native/Makefile.include, sys/auto_init/auto_init.c, sys/auto_init/netif/auto_init_kw2xrf.c, sys/auto_init/netif/auto_init_ng_at86rf2xx.c, sys/auto_init/netif/auto_init_ng_netdev_eth.c, sys/auto_init/netif/auto_init_slip.c, sys/auto_init/netif/auto_init_xbee.c, tests/driver_netdev_eth/Makefile, tests/driver_netdev_eth/main.c
This PR fixes some other minor issues. I can split if you insist.
Fixes #3093
=> ng_nativenet: auto initialization and improvements

sys/include/net/ng_sixlowpan.h, sys/net/crosslayer/ng_pktdump/ng_pktdump.c, sys/net/network_layer/ng_sixlowpan/ng_sixlowpan_print.c
~~Depends on #2614~~ (merged)
~~Depends on #2833~~ (merged)
=> pktdump: add 6LoWPAN dump

sys/net/network_layer/ng_ndp/ng_ndp.c
The setting of the states and reset of the retransmission timers is broken in the current implementation. This patch fixes that behavior and simplifies the code a little.
You can test, by using `tests/driver_netdev_eth` with `USEMODULE += ng_icmpv6_echo ng_ipv6_default` or just using `examples/ng_networking` from #2895.
Start-up 2 native nodes and ping one of them from the other. The pinging node should then send a neighbor solicitation to the solicited-nodes multicast address of the pinged node (`ff02::1:XXXX:XXXX` for IPv6 address `xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:XXXX:XXXX`) and the pinged node answers with a unicast neighbor advertisement. Then 3 pings are send and answered. If you check the neighbor cache on the pinged node now with `ncache` the state should be `DELAY`, since there were …
=> ng_ndp: fix neighbor advertisement handling

sys/include/net/ng_ipv6/nc.h, sys/net/network_layer/ng_ndp/ng_ndp.c
Just some clarification for possible future optimizations
=> ng_ndp: expand documentation on ng_ipv6_nc_t::nbr_adv_timer

Makefile.dep, boards/iot-lab_M3/Makefile.dep, boards/native/Makefile.dep, boards/samr21-xpro/Makefile.dep
=> boards: make use of ng_netif_default pseudomodule

examples/ng_networking/Makefile, examples/ng_networking/main.c, examples/ng_networking/udp.c
This PR supersedes #2720.
~~Rebased on #2891.~~
Markes as WIP because it is not quite working yet (at least I am not able to transfer UDP data from one node to another). Also the README.md is still missing (as I am not quite sure what needs to be done before you can send data).
So any feedback and testing is welcome!
=> examples: added 6LoWPAN UDP example application

sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c
Fixes some issues with the network stack, but not all. Carry on searching.
=> ng_sixlowpan: write protect pkt

sys/net/network_layer/ng_ndp/ng_ndp.c
Calling `vtimer_set_msg()` multiple times may result in live locks, if the `vtimer` did not fire before it is set again. Removing the `vtimer` before setting it again should be more stable.
Without this fix, `ng_ndp` hangs for me and has a cpu usage of 100%
=> ng_ndp: remove vtimer before setting it again

sys/Makefile
=> gnrc: remove duplicate nomac from Makefile

examples/ng_networking/Makefile, sys/shell/commands/sc_icmpv6_echo.c
=> ng_icmpv6_echo: fix time output on shell command

sys/net/link_layer/ping/ping.c, sys/net/routing/aodvv2/aodv.c, tests/vtimer_msg/main.c, tests/vtimer_msg_diff/main.c
This series is done to close the just openned #3269.
It will hopefully fix a couple of crashes and erratic behavior.
=> 3269 fix msg init queue calls

sys/net/network_layer/ng_ndp/ng_ndp.c
Some code restructuring to be in line with other code of similar format.
=> ng_ndp: code restructuring

sys/net/network_layer/ng_ndp/ng_ndp.c
=> ng_ndp: fix ng_ndp_get_next_hop() for FIB fix in #3250

dist/tools/drone-scripts/build_and_test.sh
This integrates the github label check into the drone build script.
=> dist: add github label check to drone build script

sys/net/link_layer/ng_nomac/ng_nomac.c
=> ng_nomac: use dispatch function

sys/include/net/ng_udp.h, sys/net/transport_layer/ng_udp/ng_udp.c
Fixes and clarifies some documentation and also fixes the code to actually behave like documented.
=> ng_udp: fix documentation

Makefile.dep, sys/include/net/ng_nettest.h, sys/net/crosslayer/ng_nettest/ng_nettest.c
Some bugs where overlooked on merging #3098.
=> ng_nettest: some fixes

sys/include/net/ng_sixlowpan.h
=> ng_sixlowpan: clarify documentation

cpu/cortexm_common/vectors_cortexm.c
Alternative to #3328 
@daniel-k: can you test if this works on your device with -O0?
=> cpu/cortexm_common: Overwrite stack up until the current stack pointer only

sys/net/crosslayer/ng_pktbuf/ng_pktbuf.c
=> ng_pktbuf: fix possible packet corruption in case of internal error

sys/net/network_layer/ng_ndp/ng_ndp.c
Might resolve our issue with 6LoWPAN.
I ran `ng_networking` on two samr21-xpro to test and did not see any further random cleansing of the neighbor cache for 10 min.
=> ng_ndp: only check NS retransmission in correct state

sys/net/crosslayer/ng_pktbuf/ng_pktbuf.c
Fixes an issue mentioned in https://github.com/RIOT-OS/RIOT/pull/3367#issuecomment-120917530.
=> ng_pktbuf: handle size == pkt->size case for ng_pktbuf_add()

sys/net/network_layer/ng_ndp/ng_ndp.c
Helped me a lot when doing #3385.
=> ng_ndp: enhance debug output

boards/pca10000/board.c, boards/pca10000/include/board.h
- fixed some doxygen style issues
- fixed some newline issues
- compacted the board initialization code
=> boards/pca10000: some cleanup

sys/net/network_layer/ng_ndp/ng_ndp.c
#3388 made IPv6 use the EUI-64 for 6LoWPAN nodes. The neighbor discovery was however buggy for those kinds of addresses. This fixes that.
=> ng_ndp: fix _get_l2src

dist/tools/ng_sniffer/ng_sniffer.py
=> dist: make ng_sniffer.py more pythonic

sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c
=> ng_sixlowpan: fix IPHC dispatch check

sys/net/network_layer/fib/fib.c
most fib DEBUGs were missing newlines, so I added them for better readability :)
=> fib: add newlines to DEBUG output.

Makefile.include
Some convenience functionality.
=> make: auto-include testbed support for IoT-LAB

sys/include/random.h
Provides a function to generate a random value in an arbitrary range.
=> random: provide range functionality

boards/avsextrem/board_init.c, boards/msba2-common/board_common_init.c, boards/pttu/board_init.c, cpu/arm7_common/arm_cpu.c, cpu/arm7_common/bootloader.c, cpu/arm7_common/include/VIC.h, cpu/arm7_common/include/arm7_common.h, cpu/arm7_common/panic.c, cpu/arm7_common/syscalls.c, cpu/lpc2387/doc/lpc2387.doc, cpu/lpc2387/include/lpc2387.h, cpu/lpc2387/periph/pwm.c, cpu/msp430-common/include/assert.h, cpu/msp430-common/include/cpu.h, cpu/msp430-common/include/hwtimer_cpu.h, cpu/msp430-common/panic.c
Cleaning up some Doxygen groups in cpu/
=> doxygen: Clean up groups for msp430 and arm7

Makefile, doc/doxygen/Makefile, doc/doxygen/riot.doxyfile
=> doxygen: add make targets to build man and latex

sys/net/network_layer/fib/universal_address.c, sys/net/network_layer/ng_ndp/ng_ndp.c
Detected by Clang static analyzer.
=> ng_ndp, fib: Two small code style fixes

.astylerc
Ends my whitespace terror and also might obsolete the need for `keyword-space.sed`.
=> astyle: fix config

pkg/libfixmath/Makefile, pkg/libfixmath/checkout.sh, pkg/libfixmath/perform-svn-checkout.sh, tests/libfixmath_unittests/Makefile, tests/libfixmath_unittests/main.c
Should fix problems on Travis with failing checkouts.
=> pkg/libfixmath: Protect svn checkout with a lock

cpu/native/periph/random.c, sys/net/link_layer/ng_netdev_eth/ng_netdev_eth.c, sys/net/network_layer/ng_icmpv6/ng_icmpv6.c, sys/net/network_layer/ng_ipv6/ng_ipv6.c, sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c, sys/net/transport_layer/ng_udp/ng_udp.c
Fix some findings by clang-analyzer (see also #3468).
=> Fix some clang analyzer findings

Makefile.dep
=> make: add 6LoWPAN IPHC as default module for 6LoWPAN

cpu/native/include/nativenet.h, cpu/native/native_cpu.c, sys/net/link_layer/ng_netdev_eth/ng_netdev_eth.c
Fixes warnings on FreeBSD which became errors in #3319.
=> native: fix warning errors freebsd

sys/shell/commands/sc_netif.c
Provides a new flag for the `ifconfig` command:
```
ifconfig <if> [-]iphc
```
It allows to (de-)activate IPHC for testing etc.
needs #3494 to work properly on device initialization (as soon as you send one packet it works as expected).
=> shell: ifconfig: add capability to (un)set IPHC

sys/net/network_layer/ng_ipv6/ng_ipv6.c
For sending the try to duplicate of the IPv6 header for write protection happens currently before it is checked if the first header is the IPv6 header, resulting in the netif header being duplicated instead. While this is also needed (for the removal of the header in `_send_unicast`) it leaves the IPv6 header unprotected. This fixes this issue.
=> ng_ipv6: fix write protect

boards/nrf51dongle/Makefile, boards/nrf51dongle/Makefile.features, boards/nrf51dongle/Makefile.include, boards/nrf51dongle/board.c, boards/nrf51dongle/dist/debug.sh, boards/nrf51dongle/dist/flash.sh, boards/nrf51dongle/dist/reset.sh, boards/nrf51dongle/include/board.h, boards/nrf51dongle/include/periph_conf.h, examples/ng_networking/Makefile, tests/pthread_rwlock/Makefile, tests/thread_cooperation/Makefile, tests/unittests/Makefile
rebased on #3207
As @PeterKietzmann was so nice to send me one of this dongles, I could just not go without porting it...
NOTE: For flashing I had to update my version of the [Segger `JLinkExe` tool](https://www.segger.com/jlink-software.html), I am now using version 
```
SEGGER J-Link Commander V5.00c ('?' for help)
Compiled Jun 11 2015 11:42:46
DLL version V5.00c, compiled Jun 11 2015 11:42:43
```
My old version (4.8x something) did not work with this board...
=> boards: added support for the Nordic nRF51 Dongle

cpu/cortexm_common/cortexm_init.c
Replaces #3450 - in order to get this thing merged today.
(Had to be rebased.)
=> cpu: cortexm_common: set pendSV to default priority

Makefile.include
=> make: remove scan-build folder in clean

sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c
Fixes bugs introduced in the review phase of #3494.
=> ng_sixlowpan: fix the kaputt-reviewed fixes

cpu/native/include/hwtimer_cpu.h, cpu/native/include/periph_conf.h, cpu/native/periph/timer.c, tests/hwtimer_spin/main.c, tests/hwtimer_wait/main.c
…tion
This keeps the test/hwtimer_wait test duration correct.
=> native: timer: synchronize HWTIMER_SPIN_BARRIER with timer min resolu

sys/shell/commands/Makefile
somebody broke the indention in this Makefile...
=> sys/shell_commands: fixed formatting in Makefile

sys/auto_init/netif/auto_init_kw2xrf.c, sys/auto_init/netif/auto_init_ng_at86rf2xx.c, sys/auto_init/netif/auto_init_ng_netdev_eth.c, sys/auto_init/netif/auto_init_slip.c, sys/auto_init/netif/auto_init_xbee.c
=> auto_init: make MAC priorities higher than IPv6's

sys/Makefile, sys/universal_address/Makefile
=> sys/universal_address: Makefile cleanup

cpu/lm4f120/include/periph_cpu.h, cpu/lpc1768/include/periph_cpu.h, drivers/include/periph/dev_enums.h, drivers/include/periph/timer.h
I think we should also touch this interface once more and change some of the return values to void in accordance to the proposed changes to the GPIO, UART and SPI driver, but I did not feel like touching all the CPUs...
=> drivers/periph: updated the timer interface a bit

boards/avsextrem/drivers/avsextrem-ssp0.c, boards/ek-lm4f120xl/include/board.h, sys/crypto/3des.c, sys/crypto/twofish.c
Removed some printfs and the like that would cause warnings (errors) because of the use non ISO C compliant macros.
=> debug cleanup

examples/ng_networking/Makefile
No reason to not include the fib here.
=> examples: added fib to ng_networking

sys/net/network_layer/fib/fib.c
This modification to the print function makes ipv6 addresses more readable when inspecting the fib table.
=> ng_fib: prettyprint ipv6 addresses

sys/shell/commands/sc_fib.c
1. The first commit refactors the code to add an entry into a separate function
2. The second commit adds the option to add entries without specifying a device, **IF:**
* `MODULE_NG_NETIF` exists
* only one interface is configured
With this PR it is possible to shorten
`fibroute add 2001:db8::1 via fe80::1 dev 7`
`fibroute add 2001:db8::2 via fe80::2 dev 7 lifetime 6000`
to
`fibroute add 2001:db8::1 via fe80::1`
`fibroute add 2001:db8::2 via fe80::2 lifetime 6000`
if only one interface is configured (output of `ifconfig`) and if the `ng_netif` module is used
=> sys/shell: make dev parameter optional for fibroute

pkg/libcoap/0001-Add-RIOT-Makefile.patch, pkg/libcoap/0002-Add-config.h.patch, pkg/libcoap/0003-Remove-two-example-programs-in-root.patch, pkg/libcoap/0004-Eliminate-some-compiler-warnings-and-errors.patch, pkg/libcoap/0005-fix-old-style-function-declarations.patch, pkg/libcoap/0006-debug-do-not-misuse-NDEBUG.patch, pkg/libcoap/0007-fix-option-parsing-with-debug-enabled.patch, pkg/libcoap/0008-fix-debug-out-in-PDU-parsing.patch
Will also try to get them upstream.
=> libcoap: some fixes for debugging enabled

tests/unittests/tests-ipv6_netif/Makefile.include
=> tests: fix ipv6_netif tests

sys/include/net/fib.h
Fixes documentation issue revealed in #3568
=> fib: doc fix

Makefile.dep, Makefile.include, sys/Makefile, sys/include/net/fib.h, sys/include/net/ng_ipv6/netif.h, sys/include/net/ng_ndp.h, sys/include/net/ng_ndp/internal.h, sys/include/net/ng_ndp/node.h, sys/net/network_layer/ng_ipv6/ng_ipv6.c, sys/net/network_layer/ng_ndp/internal/Makefile, sys/net/network_layer/ng_ndp/internal/ng_ndp_internal.c, sys/net/network_layer/ng_ndp/ng_ndp.c, sys/net/network_layer/ng_ndp/node/Makefile, sys/net/network_layer/ng_ndp/node/ng_ndp_node.c
Reorganizes NDP for multiple implementations support
=> ng_ndp: prepare for parallel NDP implementations

tests/hwtimer/main.c
=> Test hwtimer wo sleep

sys/net/network_layer/ng_ndp/node/ng_ndp_node.c
Groundhog day: #3487 
Fixes https://github.com/RIOT-OS/RIOT/issues/3597#issuecomment-130268007
=> ndp: missing initialization

boards/fox/include/periph_conf.h, boards/iot-lab_M3/include/periph_conf.h, boards/spark-core/include/periph_conf.h, cpu/stm32f1/periph/i2c.c, cpu/stm32f1/periph/spi.c, cpu/stm32f1/periph/uart.c
=> cpu/stm32f1: simplified pin initialization in periph drivers

dist/tools/sniffer/sniffer.py
fixes a leftover comment in #3151 (https://github.com/RIOT-OS/RIOT/pull/3151#discussion_r33745111)
=> dist/tools/sniffer: Fix usec calculation

pkg/wakaama/0001-changing-header-location.patch, pkg/wakaama/0002-defined-endianness.patch, pkg/wakaama/0003-fixed-warnings-in-er-coap-13.c.patch, pkg/wakaama/0004-fixed-warnings-in-packet.c.patch, pkg/wakaama/0005-fixed-warnings-in-tlv.c.patch, pkg/wakaama/0006-fixed-warnings-in-utils.c.patch, pkg/wakaama/Makefile, pkg/wakaama/Makefile.include
This is just the first step for the LWM2M protocol integration. 
At the moment it can't be used in its current state.
=> adding wakaama pkg

Makefile.dep, sys/Makefile, sys/include/net/ng_udp.h, sys/include/net/udp.h, sys/net/crosslayer/ng_pktdump/ng_pktdump.c, sys/net/transport_layer/ng_udp/ng_udp.c, sys/net/transport_layer/udp/Makefile, sys/net/transport_layer/udp/udp_hdr_print.c
Moves UDP header and its print function to `sys/include/net/udp.h`
=> udp: put UDP header in its own module

sys/include/net/ng_sixlowpan/frag.h, sys/include/net/ng_sixlowpan/iphc.h, sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c, sys/net/network_layer/ng_sixlowpan/frag/rbuf.c, sys/net/network_layer/ng_sixlowpan/frag/rbuf.h, sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c, sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c
=> ng_sixlowpan: fix #3588

cpu/cortexm_common/vectors_cortexm.c
Should fix #3664.
Please test this, as I have no hardware at hand atm.
=> cortexm_common: don't compare with r13/sp in assembly, fix #3664

sys/auto_init/auto_init.c, sys/include/net/fib.h, sys/include/net/gnrc/ipv6.h, sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c, sys/net/gnrc/network_layer/ndp/node/gnrc_ndp_node.c, sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c, sys/net/gnrc/routing/rpl/gnrc_rpl_dodag.c, sys/net/network_layer/fib/fib.c, sys/shell/commands/sc_fib.c, tests/unittests/tests-fib/tests-fib.c
@authmillenon, @cgundogan, you might be interested, too.
IMO this is a) the cleaner way to go and b) required if we want to support dual stack applications (e.g. IPv6 and CCN or IPv6 and IPv4).
=> fib: allow for multiple instances of FIB

drivers/include/net/netdev2.h
@haukepetersen and I tried to find a generally usable but maximally minimized "network device interface".
This is our work in progress. Please comment.
=> sys: add improved network device API

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
In the current implementation option parsing was done for all incoming DIOs. This PR limits this only for incoming DIOs that belong to the pref. parent.
=> rpl: parse DIO and options only for DIOs from pref. parent

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
Reseting the trickle timer when receiving an `INFINITE_RANK` DIO from a child that is doing a local repair e.g., ensures that this child can quickly join the dodag again.
=> rpl: reset trickle if INFINITE_RANK DIO from child recvd

sys/include/net/gnrc/rpl.h, sys/net/gnrc/routing/rpl/gnrc_rpl.c, sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
This PR adds some validity checking for control messages and (currently a subset of) their options.
~~Depends on #3659~~
=> rpl: control message validity checks

dist/tools/openocd/openocd.sh
Hopefully fixes #3427.
Please test this on as many system as possible, especially on Mac OS. The problem seemed to be, that openocd stays in the same process group when forking it (`openocd .... &`). Now in GDB when you press Ctrl+c the `SIGINT` signal will be sent to the parent shell, that redirects it to GDB as well as to openocd.
Solution: detach openocd from process group.
The script also used the wrong environment variable to grab the openocd PID accroding to [this](http://www.tldp.org/LDP/abs/html/exit-status.html#EXSREF).
=> debugging: fix openocd closing when pressing Ctrl+C in GDB, fix #3427

sys/include/net/fib.h, sys/include/net/fib/table.h, sys/include/net/gnrc/ipv6.h, sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c, sys/net/gnrc/network_layer/ndp/node/gnrc_ndp_node.c, sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c, sys/net/gnrc/routing/rpl/gnrc_rpl_dodag.c, sys/net/network_layer/fib/fib.c, sys/shell/commands/sc_fib.c, tests/unittests/tests-fib/tests-fib.c
In order to properly make use of different FIB tables, a size parameter is required.
=> fib: add size parameter

examples/gnrc_networking/udp.c
This allows for sending UDP packets repeatedly with a configured delay.
=> gnrc_networking example: add capability to send UDP packets repeatedly

Makefile.include, boards/native/Makefile.include, cpu/native/dev_eth_tap/dev_eth_tap.c, cpu/native/include/dev_eth_tap.h, cpu/native/periph/timer.c, sys/net/gnrc/link_layer/netdev_eth/gnrc_netdev_eth.c, sys/net/gnrc/network_layer/ndp/node/gnrc_ndp_node.c, sys/od/od.c, sys/shell/commands/sc_netif.c
rebased upon ~~#3290~~ and #3390 to build again after merge of #3319.
@emmanuelsearch can you verify?
=> native: fix warning error OS X

dist/testbed-support/Makefile.iotlab
IoT-LAB expects different file formats for different architectures.
=> dist: chose binary format for IoT-LAB Makefile

Makefile.dep, drivers/include/srf02.h, drivers/srf02/srf02.c, tests/driver_srf02/Makefile, tests/driver_srf02/main.c
- switched to use xtimer
- simplified interface slightly
- optimized reading of results
- some style cleanups
- updated the documentation
=> drivers/srf02: some optimizations

sys/include/net/gnrc/ipv6/netif.h
Addresses https://github.com/RIOT-OS/RIOT/pull/3771#discussion_r38850979
=> gnrc: ipv6: netif: obey naming conventions

cpu/stm32f3/periph/gpio.c
=> cpu/stm32f3: disable debug in GPIO driver

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
`Section 6.7.2 - RFC 6550:`
The Pad1 option is used to insert a single octet of padding into the message to enable options alignment. If more than one octet of padding is required, the PadN option should be used rather than multiple Pad1 options.
=> rpl: RFC6550 states that you should use PadN instead of multiple Pad1 bytes

sys/shell/commands/sc_gnrc_rpl.c
=> rpl: RPL Instance ID 0 must be allowed

cpu/msp430-common/lpm_cpu.c
Found this while analyzing #3567
=> msp430: use assert instead of printf

sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c
=> gnrc_ndp: fix setting of addresses by PIO

sys/shell/commands/sc_netif.c
This file had some growing pains and now the output looks all weird on native. This PR fixes that.
=> shell: fix output for ifconfig

Makefile.dep, sys/Makefile, sys/include/net/ipv4.h, sys/include/net/ipv4/addr.h, sys/net/network_layer/ipv4/addr/Makefile, sys/net/network_layer/ipv4/addr/ipv4_addr_from_str.c, sys/net/network_layer/ipv4/addr/ipv4_addr_to_str.c, sys/net/network_layer/ipv6/addr/ipv6_addr_from_str.c, sys/net/network_layer/ipv6/addr/ipv6_addr_to_str.c, tests/unittests/tests-ipv4_addr/Makefile, tests/unittests/tests-ipv4_addr/Makefile.include, tests/unittests/tests-ipv4_addr/tests-ipv4_addr.c, tests/unittests/tests-ipv4_addr/tests-ipv4_addr.h
This provides just the type and string conversion functions.
=> ipv4_addr: initial import

sys/net/gnrc/network_layer/sixlowpan/nd/gnrc_sixlowpan_nd.c
IMO this order is more sensible.
=> 6lowpan nd: check for link-local first

core/include/assert.h, core/include/debug.h, core/include/panic.h, core/lifo.c, core/msg.c, core/panic.c, cpu/arm7_common/panic.c, cpu/atmega_common/include/cpu.h, cpu/cortexm_common/include/cpu.h, cpu/cortexm_common/panic.c, cpu/lpc2387/include/cpu.h, cpu/lpc2387/periph/gpio.c, cpu/msp430-common/include/cpu.h, cpu/msp430-common/panic.c, cpu/native/include/cpu.h, cpu/native/irq_cpu.c, cpu/native/panic.c, cpu/stm32f3/periph/i2c.c, cpu/x86/include/cpu.h, cpu/x86/panic.c, drivers/kw2xrf/kw2xrf.c, sys/cpp11-compat/cppsupport.cpp
Replaces #3722 after I screwed things up in git.
=> core: RIOT's own assert macro

Makefile.dep, sys/include/net/gnrc/ipv6/netif.h, sys/net/gnrc/network_layer/ipv6/netif/gnrc_ipv6_netif.c
Please check thoroughly if I got that right.
=> gnrc: 6lowpan-nd: some broken router dependencies

sys/net/gnrc/link_layer/netdev2/gnrc_netdev2_eth.c, sys/shell/commands/sc_ipv6_nc.c, sys/shell/commands/sc_netif.c
Some minor fixes for issues detected with make scan-build.
=> gnrc: scan build fixes

sys/include/net/gnrc/sixlowpan/nd/router.h, sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c, sys/net/gnrc/network_layer/sixlowpan/nd/gnrc_sixlowpan_nd.c
A 6LR has to join the all routers multicast group, too.
=> 6lowpan nd: router fixes

sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c
This PR includes a check if a prefix has been processed already for PIO generation (see #3827)
=> ndp: pio - check if prefix has been processed before

boards/arduino-due/include/board.h, boards/arduino-mega2560/include/board.h, boards/avsextrem/include/board.h, boards/cc2538dk/include/board.h, boards/ek-lm4f120xl/include/board.h, boards/f4vi1/include/board.h, boards/fox/include/board.h, boards/limifrog-v1/include/board.h, boards/mbed_lpc1768/include/board.h, boards/msbiot/include/board.h, boards/mulle/board.c, boards/mulle/include/board.h, boards/nrf51dongle/include/board.h, boards/nrf6310/include/board.h, boards/nucleo-f091/include/board.h, boards/nucleo-f303/include/board.h, boards/nucleo-f334/include/board.h, boards/nucleo-l1/include/board.h, boards/openmote/include/board.h, boards/pttu/include/board.h, boards/remote/include/board.h, boards/saml21-xpro/include/board.h, boards/spark-core/include/board.h, boards/stm32f0discovery/include/board.h, boards/stm32f3discovery/include/board.h, boards/udoo/include/board.h, core/include/kernel.h
Now that the hwtimer was removed, these defines are not needed/used anymore...
=> boards/core: removed some hwtimer leftovers

Makefile.dep, Makefile.pseudomodules, drivers/Makefile, examples/default/Makefile, examples/default/README.md, examples/default/main.c
=> examples: networking support for default example

sys/net/gnrc/network_layer/ndp/gnrc_ndp.c, sys/net/gnrc/network_layer/sixlowpan/nd/gnrc_sixlowpan_nd.c
=> gnrc_sixlowpan_nd: activate NC state machine

sys/net/gnrc/network_layer/ipv6/netif/gnrc_ipv6_netif.c, sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
Not only a 6LBR should send router advertisements.
=> 6lowpan nd: send router advertisements on 6LR

cpu/atmega_common/panic.c, examples/gnrc_border_router/Makefile, examples/gnrc_networking/Makefile
should fix https://github.com/RIOT-OS/RIOT/pull/3886#issuecomment-141789316
=> atmega: added panic function

Makefile.dep, Makefile.pseudomodules, sys/include/net/conn.h, sys/include/net/conn/ip.h, sys/include/net/conn/tcp.h, sys/include/net/conn/udp.h, sys/include/net/gnrc/conn.h, sys/net/gnrc/Makefile, sys/net/gnrc/conn/Makefile, sys/net/gnrc/conn/gnrc_conn.c, sys/net/gnrc/conn/ip/Makefile, sys/net/gnrc/conn/ip/gnrc_conn_ip.c, sys/net/gnrc/conn/udp/Makefile, sys/net/gnrc/conn/udp/gnrc_conn_udp.c, tests/conn_ip/Makefile, tests/conn_ip/ip.c, tests/conn_ip/main.c
Leight-weight, but stack agnostic. I tried to keep it as close to the socket API as possible to write very simple wrappers for that in the posix module.
~~Depends on #3608.~~
=> conn: Initial import of a light-weight network application API

sys/base64/base64.c, sys/bloom/bloom.c, sys/crypto/modes/ccm.c, sys/embunit/stdImpl.c, sys/ubjson/ubjson-read.c, tests/unittests/tests-cbor/tests-cbor.c
=> clean up: Some scan build warnings

drivers/kw2xrf/kw2xrf.c
Without this gnrc IPv6 won't work on the Phytec board.
=> kw2xrf: short address getter and iid option

boards/limifrog-v1/include/periph_conf.h, boards/nucleo-l1/include/board.h, boards/nucleo-l1/include/periph_conf.h, cpu/stm32l1/include/periph_cpu.h, cpu/stm32l1/include/stm32l1xx.h, cpu/stm32l1/periph/timer.c
saves ~600 byte ROM and looks nicer :-)
also #3525 works nicely with this.
=> cpu/stm32l1: optimized and fixed timer driver

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
I don't know why #3913 broke, but this PR replaces it.
=> rpl: fix src addr of outgoing control messages

sys/net/gnrc/network_layer/ipv6/nc/gnrc_ipv6_nc.c
=> IPv6 nc: missing debug parameter

sys/net/gnrc/link_layer/slip/gnrc_slip.c
Should fix #3933 at least partly.
=> gnrc_slip: reorder received packet correctly

cpu/lpc2387/periph/spi.c
=> cpu: lpc2387: add spi_conf_pins()

sys/net/gnrc/network_layer/ipv6/netif/gnrc_ipv6_netif.c, sys/net/gnrc/network_layer/sixlowpan/nd/router/gnrc_sixlowpan_nd_router.c
These fixes are required to get SLAAC working.
=> 6lowpan nd: PIO fixes

sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
All the option values that determine the time for the next router solicitation can be 0 (for invalidate this option now). That's bad if you are searching for the minimum and assume in the [rescheduling function](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/sixlowpan/nd/gnrc_sixlowpan_nd.c#L227) that this time can't be 0. If the value is 0 it can thus be ignored, as is already [done for the router lifetime](https://github.com/RIOT-OS/RIOT/pull/3964/files#diff-c668f2091e40b20cfc8d5c4b5aeca3e1R516).
=> gnrc_ndp: lifetimes might be 0 in RA options

sys/include/xtimer.h, sys/xtimer/xtimer.c, sys/xtimer/xtimer_core.c
Some small fixes I found while working on other parts of the xtimer subsystem.
=> sys/xtimer: Small fixes

cpu/stm32f3/periph/uart.c
and one more....
`hello-world` for `stm32f3discovery`:
```
BEFORE:
9128	    112	   2664	  11904	   2e80
AFTER:
7816	    112	   2664	  10592	   2960
```
Savings: ~1,5K...
=> cpu/stm32f3: optimized baudrate calculation

cpu/stm32f4/periph/uart.c
The F4 does is also happy to save some ROM...
`hello-world` for `stm32f4discovery`:
```
BEFORE:
9212	    116	   2652	  11980	   2ecc
AFTER:
7900	    116	   2652	  10668	   29ac
```
Oh happy day :-)
=> cpu/stm32f4: optimized baudrate calculation

sys/cbor/cbor.c, sys/include/ubjson.h, tests/unittests/tests-fib/tests-fib.c
=> unittests: native: fixes for OS X

examples/gnrc_border_router/main.c, examples/gnrc_networking/main.c, sys/shell/commands/sc_icmpv6_echo.c
=> shell: fix multicast pings

sys/net/gnrc/netapi/gnrc_netapi.c
=> gnrc netapi: switch to non-blocking IPC calls

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c, sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c
=> pktbuf: release correct snip in error case

sys/shell/commands/sc_icmpv6_echo.c
=> shell ping: improved duplicate dropping

sys/shell/commands/sc_netif.c
=> shell: ifconfig: fixes (release version)

cpu/native/syscalls.c
g++ 5.2.0 apparently requires malloc before startup is run.
@authmillenon 
Please check if a change to Makefile.include like 8a33a629144374b03d97a4265f7948ee7d54a0df is required.
=> native: dynamically load malloc

release-notes.txt
I guess this needs just a pro-forma ACK.
=> 2015.09: added release notes

tests/xtimer_hang/Makefile, tests/xtimer_hang/main.c
Test case for #4060, fixed on samr21-xpro by #4061.
=> tests: add xtimer_hang

boards/weio/Makefile.features, boards/weio/include/periph_conf.h, cpu/lpc11u34/periph/pwm.c
This pull request add PWM capabilities to ```cpu/lpc11u34```.
It also add the configuration to use it in the ```board/weio```
=> cpu/lpc11u34 : Peripheral addition : PWM

sys/xtimer/xtimer_core.c
Release branch version of #4061.
=> sys: xtimer: add another safeguard against setting a timer in the past

boards/nucleo-l1/include/periph_conf.h, cpu/stm32l1/include/periph_cpu.h, cpu/stm32l1/periph/uart.c
Supersedes #3854. Rebased on current master.
=> cpu/stm32l1: cleaned up UART pin configuration slightly

boards/weio/Makefile.features, boards/weio/include/periph_conf.h, cpu/lpc11u34/periph/adc.c
This pull request adds the ADC support fo LPC11U34
=> cpu/lpc11u34 : Added ADC support for LPC11U34

boards/weio/Makefile.features, boards/weio/include/periph_conf.h, cpu/lpc11u34/Makefile.include, cpu/lpc11u34/include/periph_cpu.h, cpu/lpc11u34/periph/spi.c, tests/driver_at86rf2xx/Makefile, tests/driver_kw2xrf/Makefile
This pull request adds the support for SPI to the LPC11U34 chip.
=> cpu/lpc11u34 : Added SPI for NXP LPC11U34 (SPI_0 and SPI_1)

drivers/servo/servo.c
'dev' is an output. The pwm to initialize must be read from arg 2
=> servo ctor fix

Makefile.dep, drivers/Makefile.dep
I got tired of rebasing #3420, so I decided to split it up a little bit more...
For testing: it should be fine when Travis is green, as this implies that all dependencies are still pulled correctly...
=> make: moved driver deps to drivers/Makefile.dep

cpu/atmega2560/periph/timer.c, cpu/cc2538/periph/timer.c, cpu/cc430/periph/timer.c, cpu/kinetis_common/timer.c, cpu/lm4f120/periph/timer.c, cpu/lpc11u34/periph/timer.c, cpu/lpc1768/periph/timer.c, cpu/lpc2387/periph/timer.c, cpu/msp430fxyz/periph/timer.c, cpu/native/periph/timer.c, cpu/nrf51/periph/timer.c, cpu/sam3/periph/timer.c, cpu/samd21/periph/timer.c, cpu/saml21/periph/timer.c, cpu/stm32f0/periph/timer.c, cpu/stm32f1/periph/timer.c, cpu/stm32f3/periph/timer.c, cpu/stm32f4/periph/timer.c, cpu/stm32l1/periph/timer.c, drivers/include/periph/timer.h
=> periph/timer: Drop timer_reset

sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c
hotfix for Release-2015.09. see #4150
=> ndp/internal: assert and dst for anycast

sys/include/net/gnrc/ipv6/nc.h, sys/net/gnrc/network_layer/ipv6/nc/gnrc_ipv6_nc.c, sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
release and vtimer version of #4172
=> ndp: use separate timer of nc_entry in rtr_sol_handle

sys/net/gnrc/link_layer/slip/gnrc_slip.c
=> gnrc_slip: set NETOPT_IS_WIRED

sys/include/xtimer.h, sys/xtimer/xtimer_core.c, tests/xtimer_shift_on_compare/main.c
This PR is only a clean up of xtimer code, no added functionality or bugs fixed. This clean up is necessary to make future xtimer PRs more readable and easier to follow.
=> xtimer: small cleanups

Makefile.include, boards/samr21-xpro/Makefile.include
Set-up for #2724, making things a little easier to use and spot when something goes wrong.
=> Minor usability improvements prior to adding documentation 

drivers/at86rf2xx/at86rf2xx_netdev.c
=> at86rf2xx: added protocol setter

sys/shell/commands/sc_netif.c
Required for, e.g. the plugtests
=> shell netif: support setting the IPv6 hop limit

sys/shell/commands/sc_netif.c
This is the 2015.09 version of #4223.
=> shell netif: set correct MTU

uncrustify-riot.cfg
Added a configuration file for Uncrustify (http://uncrustify.sourceforge.net/) code beautifier based on the Linux configuration for this tool (http://uncrustify.sourceforge.net/linux.cfg.txt).
Thanks to @LudwigKnuepfer for the hint.
=> style: added uncrustify config

sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c
RAs aren't currently send if there is no global unicast address set. This is because the function that builds the PIOs both assumes NULL for the error case and an empty PIO list, resulting in the RA send function to drop the packet altogether.
=> gnrc_ndp_internal: send RAs even when there are no PIOs

doc/doxygen/riot.doxyfile, doc/doxygen/src/getting-started.md, doc/doxygen/src/mainpage.md
Re-adds getting started section as its own page.
=> doc: add 'Getting started' page

doc/doxygen/src/mainpage.md
=> doc: fixed typo in doc mainpage.md

sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c
Iterate directly the fib entries instead of copying entries from the fib and also mark routes that
were not added by RPL DAOs (but e.g. by the fibroute shell command) as external in DAOs.
External routes won't have the RPL flag set in the `fibroute` command.
Also, saves ~76 bytes of ROM.
=> rpl: directly iterate fib entries for DAO and mark external routes

sys/newlib/syscalls.c
Minor doc fix in `newlib/syscalls.c`
=> newlib/syscalls: minor doc fix

tests/nhdp/Makefile
see https://github.com/RIOT-OS/RIOT/pull/4337#issuecomment-159530403
=> nhdp: blacklist chronos

sys/shell/commands/sc_netif.c
Allows to set the `RTR_ADV` flag manually and also shows it + the `RTR` flag in the gnrc_netif shell command.
=> shell: sc_netif: show and manipulate router related flags

dist/testbed-support/Makefile.iotlab
Otherwise make will always call experiment-cli.
=> iotlab: set DEBUG_NODE correctly

sys/xtimer/xtimer.c, tests/xtimer_msg_receive_timeout/Makefile, tests/xtimer_msg_receive_timeout/main.c, tests/xtimer_msg_receive_timeout/tests/01-run.py
=> xtimer: implement missing msg receive timeout

core/include/msg.h
=> core: msg: remove pointless warning in doxygen

boards/arduino-mega2560/dist/debug.sh, boards/arduino-mega2560/dist/debug_srv.sh, boards/msba2-common/tools/flashutil.sh, boards/pttu/tools/openocd-pttu.sh, boards/x86-multiboot-common/dist/link, dist/tools/drone-scripts/build_and_test.sh, dist/tools/eclipsesym/cmdline2xml.sh, dist/tools/pr_check/check_labels.sh, dist/tools/pr_check/pr_check.sh, dist/tools/testsuite/build_and_generate_html.sh, dist/tools/testsuite/generate_html.sh, dist/tools/testsuite/parse_buildlog.sh, dist/tools/testsuite/run_tests.sh, dist/tools/toolchains/build_gnuarm.sh, dist/tools/toolchains/build_gnuarm_naked.sh, dist/tools/toolchains/build_x86.sh, dist/tools/travis-scripts/build_and_test.sh, dist/tools/usb-serial/find-tty.sh, pkg/libfixmath/checkout.sh, pkg/libfixmath/perform-svn-checkout.sh
For host systems like FreeBSD, bash binary is found in a different path.
=> tools: remove hardcoding of bash hashbang

dist/tools/licenses/patterns/3c-BSD-atmel4, sys/Makefile, sys/ecc/doc.txt, sys/ecc/hamming256/Makefile, sys/ecc/hamming256/hamming256.c, sys/include/ecc/hamming256.h, tests/unittests/tests-ecc/Makefile, tests/unittests/tests-ecc/Makefile.include, tests/unittests/tests-ecc/tests-ecc.c
I'll need this for the lower layer of the file system thingy I'm building :smile: Found the code [here](https://code.google.com/p/android-source-browsing/source/browse/MakefileBasedBuild/Atmel/sam3x/sam3x-ek/libraries/libboard_sam3x-ek/source/hamming.c?repo=device--google--accessory--adk2012&r=e0f114ab1d645caeac2c30273d0b693d72063f54), seems license compatible with what we have, right?
=> Add 256 byte block hamming code implementation

sys/include/phydat.h
typos were discovered after #3538 was merged...
=> sys/phydat: fixed typos in documentation

core/include/atomic.h
ridiculous PR - but this is for getting doxygen warning free...
=> core/atomic.h: fix doxygen to get rid of warning

boards/frdm-k64f/include/board.h, boards/frdm-k64f/include/periph_conf.h, boards/nrf51dongle/include/periph_conf.h, boards/nrf6310/include/board.h, boards/nrf6310/include/periph_conf.h, boards/saml21-xpro/include/board.h, boards/saml21-xpro/include/periph_conf.h
=> boards: fixed include guards

sys/include/net/conn.h, sys/include/net/gnrc/ipv6/netif.h, sys/net/gnrc/conn/gnrc_conn.c, sys/posix/sockets/posix_sockets.c
=> POSIX socket: source addr selection

drivers/include/pcd8544.h
this was the only driver not complying to #2623...
=> drivers/pcd8544: fixed include guard

.gitattributes
Thanks for the proposal, @kaspar030!
=> git: handle patch files as binary

sys/arduino/doc.txt
=> arduino: minor doc fix

core/include/flags.h, core/include/log.h, core/include/native_sched.h, core/include/sched.h
=> core: fixed include guards a minor style/doxygen

.travis.yml, dist/tools/travis-scripts/build_and_test.sh
Fixes the travis bug that was discussed in https://github.com/RIOT-OS/RIOT/pull/4386#issuecomment-162347903
=> travis: fix git complaining about 'ambiguous argument'

drivers/kw2xrf/kw2xrf.c
BUG: the pktbuf was released at the wrong place and
return value of _assemble_tx_buf was not verified.
=> drivers/kw2xrf/kw2xrf.c: fix bug and cleanup in _assemble_tx_buf

drivers/at86rf2xx/at86rf2xx.c, drivers/at86rf2xx/at86rf2xx_getset.c, drivers/at86rf2xx/at86rf2xx_internal.c, drivers/at86rf2xx/at86rf2xx_netdev.c, drivers/at86rf2xx/include/at86rf2xx_internal.h, drivers/include/at86rf2xx.h
Followup PR for @gebart 's page and channel selection (#4191) since he's traveling and it would be nice to see this in the next release. :)
Also includes #4411 to making Travis happy with this PR.
=> at86rf2xx: Add support for channel page

boards/f4vi1/include/board.h, boards/f4vi1/include/periph_conf.h, boards/msbiot/include/board.h, boards/msbiot/include/periph_conf.h, boards/nucleo-f401/include/board.h, boards/nucleo-f401/include/periph_conf.h, boards/stm32f4discovery/include/board.h, boards/stm32f4discovery/include/periph_conf.h, cpu/stm32f4/include/periph_cpu.h, cpu/stm32f4/include/stm32f401xe.h, cpu/stm32f4/include/stm32f407xx.h, cpu/stm32f4/include/stm32f415xx.h, cpu/stm32f4/periph/uart.c
based on #4114
This driver is now utilizing DMA for transmitting data. This is possible through the changes in the UART driver interface and should save quite some energy as the CPU will now be able to sleep while sending data...
=> cpu/stm32f4: optimized UART driver

sys/posix/sockets/posix_sockets.c
According to http://pubs.opengroup.org/onlinepubs/009695399/functions/connect.html for a "socket [that] has not already been bound to a local address, connect() shall bind it to an address which, unless the socket's address family is AF_UNIX, is an unused local address."
~~Depends on #4385.~~
=> POSIX sockets: implicit bind for connect()

doc/doxygen/src/mainpage.md, doc/doxygen/src/riot-gnrc.svg, sys/include/net/gnrc.h
This PR includes a preliminary version of gnrc's documentation. However, much more info can be added to that. @authmillenon can you add more info where you think it's necessary?
=> gnrc: enhance documentation

doc/doxygen/src/mainpage.md, doc/doxygen/src/riot-gnrc.svg, sys/include/net/gnrc.h
=> doxygen: gnrc: backport of doc enhancements

cpu/stm32f4/periph/pwm.c
=> cpu/stm32f4discovery: fixed freq return in pwm_init

sys/net/gnrc/conn/udp/gnrc_conn_udp.c, sys/posix/sockets/posix_sockets.c
=> posix_sockets: fix overflowing fd in close()

boards/arduino-due/Makefile.features, boards/udoo/Makefile.features, cpu/sam3/include/cpu_conf.h, cpu/sam3/periph/cpuid.c
Adding cpu id for sam3 cpu, inspiring from https://github.com/RIOT-OS/RIOT/issues/1511.
=> Sam3 cpuid

boards/nucleo-f103/Makefile, boards/nucleo-f103/Makefile.features, boards/nucleo-f103/Makefile.include, boards/nucleo-f103/board.c, boards/nucleo-f103/dist/openocd.cfg, boards/nucleo-f103/include/board.h, boards/nucleo-f103/include/periph_conf.h, cpu/stm32f1/ldscripts/stm32f103rb.ld, cpu/stm32f1/periph/spi.c, examples/gnrc_border_router/Makefile, examples/gnrc_networking/Makefile, examples/gnrc_tftp/Makefile, tests/pkg_cmsis-dsp/Makefile, tests/thread_cooperation/Makefile, tests/unittests/Makefile
Initial support for the board ST Nucleo f103
=> Board nucleo f103

cpu/x86/x86_startup.c, examples/ccn-lite-relay/Makefile, examples/ccn-lite-relay/main.c, pkg/tlsf/patch.txt
Fixes #4451 by re-introducing the init function and updates using functions accordingly.
=> pkg tlsf: make it compile with -pedantic

doc/doxygen/riot.doxyfile, doc/doxygen/src/creating-an-application.md, doc/doxygen/src/mainpage.md
Another one in #4309 bites the dust ;-)
=> doc: add page about creating an application

core/include/msg.h
Merges IPC section of old doxygen mainpage and detailed description and enhances it with some introductory text and examples.
Since I have uncrustify run as a pre-commit hook I included some style fixes too in an extra commit.
=> core: msg: update detail section on IPC

cpu/x86/x86_startup.c, examples/ccn-lite-relay/Makefile, examples/ccn-lite-relay/main.c, pkg/tlsf/patch.txt
=> pkg tlsf: make it compile with -pedantic (release)

core/include/msg.h
=> core: msg: update detail section on IPC (2015.12 version)

doc/doxygen/riot.doxyfile, doc/doxygen/src/creating-an-application.md, doc/doxygen/src/mainpage.md
Release version of https://github.com/RIOT-OS/RIOT/pull/4477
=> doc: add page about creating an application (2015.12 version)

tests/unittests/Makefile
=> Revert "unittests: deactivate relic tests for all but native"

Makefile.dep
=> ipv6_hdr: add ipv6_addr as dependency

tests/unittests/Makefile
=> unittests: deactivate relic tests for all but native

doc/doxygen/riot.doxyfile, doc/doxygen/src/creating-modules.md, doc/doxygen/src/mainpage.md
=> doc: add page about creating modules

doc/doxygen/riot.doxyfile, doc/doxygen/src/creating-modules.md, doc/doxygen/src/mainpage.md
Release version of https://github.com/RIOT-OS/RIOT/pull/4480
=> doc: add page about creating modules (2015.12 version)

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c
One more PR that aims to fix #4462 (might need #4485 to fully fix the issue). With NHC activated the highest layer payload isn't directly adjacent to IPv6 anymore nor is the IPv6 header necessarily the first or second snip in a received `pkt` as it was before, since UDP (and later probably some extension headers or GHC supported headers) will be inserted between them. These assumptions are completely removed by this PR and the IPv6 header is searched as in any other layer + the pktsnip list is completely reversed for forwarding.
=> gnrc_ipv6: make no pre-assumption about any marked headers

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c
=> gnrc_ipv6: make no pre-assumption about any marked headers (2015.12 version)

sys/include/net/gnrc/sixlowpan/iphc.h, sys/net/gnrc/network_layer/sixlowpan/frag/rbuf.c, sys/net/gnrc/network_layer/sixlowpan/gnrc_sixlowpan.c, sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c, sys/net/gnrc/transport_layer/udp/gnrc_udp.c
=> gnrc_sixlowpan: Fix IPHC/NHC packet order problem (backport)

Makefile.dep
=> sys: net: disable NHC

drivers/include/periph/uart.h
I guess the title is speaking. Please give feedback about the depth of the description as well as missing informations!
=> periph/uart: extend uart API doc

drivers/include/periph/gpio.h
I guess the title is speaking. Please give feedback about the depth of the description as well as missing informations!
=> periph/gpio: extend gpio API doc

tests/unittests/tests-fib_sr/tests-fib_sr.c
=> unittests: some fixes to fib_sr tests (2015.12 version)

drivers/include/periph/uart.h
=> periph/uart: extend uart API doc (release version)

drivers/include/periph/gpio.h
=> periph/gpio: extend gpio API doc (release version)

examples/gnrc_tftp/tftp_client.c, examples/gnrc_tftp/tftp_server.c, sys/net/gnrc/application_layer/tftp/gnrc_tftp.c
=> tftp: fix formating warnings/errors

sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c
=> gnrc_ndp: fixed ND Option handling for 6LoWPAN

sys/shell/commands/sc_icmpv6_echo.c, sys/shell/commands/sc_netif.c
=> shell: commands: fix selective outputs for nano specs (2015.12 version)

cpu/native/include/periph_conf.h, cpu/native/periph/timer.c, tests/xtimer_now64_continuity/Makefile, tests/xtimer_now64_continuity/README.md, tests/xtimer_now64_continuity/main.c
=> cpu: native: fix native_timer_absolute() (release version)

.travis.yml, dist/tools/travis-scripts/build_and_test.sh
Testing whether this change to travis does not break anything for other branches than master
EDIT: release version of #4615
=> travis: pass the proper branch to compile_test.py

release-notes.txt
=> 2015.12: added release notes

pkg/oonf_api/Makefile
This PR refactors the Makefile of the `oonf_api` `pkg` to look more like the other `pkg`'s Makefiles
=> oonf_api: adjust Makefile

examples/gnrc_networking/README.md
=> examples: fix tiny typo in gnrc_networking README

sys/include/net/conn.h, sys/net/gnrc/conn/udp/gnrc_conn_udp.c
First attempt at trying to explain the relationship between conn, applications and network stacks a bit better. This is very much WIP and currently mainly exists for @authmillenon to shout at :)
=> conn: add more detailed documentation (WIP)

uncrustify-riot.cfg
See https://github.com/RIOT-OS/RIOT/pull/4475#discussion_r47655743
=> uncrustify: ignore parens on return

sys/sema/sema.c
Work-around to prevent weird errors from happening due to #4372.
=> sema: pre-set timeout-timer for sema_wait_timed_msg()

sys/include/sema.h, sys/sema/sema.c
* fixes (and documents properly) return values of `sema_post()`
* introduces static initializer for semaphores
* some style fixes.
=> sema: some API fixes

sys/net/network_layer/fib/fib.c
Checking the lifetime of a newly created source route seems pointless to me.
This PR furthermore removes the `now` parameter for the check lifetime function since this function get call `xtimer_now()` itself.
~~Fixes #4513.~~
=> FIB: remove superfluous things

tests/unittests/tests/01-run.py
Fixes python 3 bug introduced in #3309.
=> unittests: fix for python3

dist/testbed-support/Makefile.iotlab
Some minor things have been overlooked during the heat of the H&A night.
=> iotlab makefiles: minor cleanups

dist/testbed-support/Makefile.iotlab
That was still not working as intended.
=> iotlab: fix IOTLAB_SITE for term, flash etc

sys/auto_init/netif/auto_init_netdev2_tap.c
=> auto_init: disable DEBUG

cpu/atmega2560/periph/gpio.c, cpu/cc2538/periph/gpio.c, cpu/ezr32wg/periph/gpio.c, cpu/lpc11u34/periph/gpio.c, cpu/lpc2387/periph/gpio.c, cpu/msp430fxyz/periph/gpio.c, cpu/nrf51/periph/gpio.c, cpu/sam3/periph/gpio.c, cpu/samd21/periph/gpio.c, cpu/saml21/periph/gpio.c, cpu/stm32f0/periph/gpio.c, cpu/stm32f1/periph/gpio.c, cpu/stm32f3/periph/gpio.c, cpu/stm32f4/periph/gpio.c, cpu/stm32l1/periph/gpio.c, drivers/include/periph/gpio.h
cleaning up a little more of the GPIO driver code...
=> drivers/gpio: added default ISR context struct

boards/samr21-xpro/include/gpio_params.h
~~depends on #4740 and #4741~~
=> saul: add user button for samr21-xpro

doc/doxygen/src/mainpage.md
Fixes minor typo bug in the documentation
=> doc: fix link to devel mailman

sys/shell/commands/sc_icmpv6_echo.c
This PR changes the ping6 shell command to accept (and if needed, require) an interface specifier.
```
> ping6 fe80::1%6
```
If destination address is link local and only one interface present, use that interface.
If destination address is link local and multiple interfaces present, require interface specifier.
Otherwise, use specifier if present.
It also adds, if an interface specifier is present, the necessary netif header.
*edit* depends on #4753.
=> sys: shell: ping6: allow specification of target interface

sys/hashes/sha256.c, sys/include/hashes/sha256.h, tests/unittests/tests-hashes/tests-hashes-sha256.c
added initial version of `hmac-sha256` computation function.
=> hashes/sha256: initial commit for hmac-sha256 computation

sys/net/gnrc/network_layer/sixlowpan/frag/rbuf.c
https://tools.ietf.org/html/rfc4944#section-5.3 says:
> If a link fragment that overlaps another fragment is received, as
> identified above, and differs in either the size or datagram_offset
> of the overlapped fragment, the fragment(s) already accumulated in
> the reassembly buffer SHALL be discarded.  A fresh reassembly may be
> commenced with the most recently received link fragment.
XBee retransmit frames automatically until it receives ACK, results in duplicated fragments. We must just ignore duplicated fragments to reduce packet losses.
Related: #4547.
=> rbuf: drop overlapped fragment only if offset or size differs from previous one

cpu/kinetis_common/gpio.c, cpu/kinetis_common/random_rnga.c, cpu/kinetis_common/random_rngb.c, cpu/sam3/periph/gpio.c, cpu/stm32f0/periph/gpio.c, cpu/stm32f0/periph/spi.c, cpu/stm32f1/periph/gpio.c, cpu/stm32f3/periph/pwm.c, cpu/stm32f4/periph/gpio.c, cpu/stm32f4/periph/pwm.c, cpu/stm32f4/periph/random.c, cpu/stm32l1/periph/spi.c
I don't know why, but somehow some of my old email address entries survived...
=> cpu: use Hauke's correct email address

cpu/lm4f120/periph/uart.c, drivers/kw2xrf/kw2xrf.c, drivers/srf08/srf08.c, sys/net/gnrc/application_layer/zep/gnrc_zep.c, tests/driver_mpu9150/main.c, tests/driver_pir/main.c, tests/irq/main.c, tests/unittests/tests-cbor/tests-cbor.c, tests/xtimer_shift_on_compare/main.c
Removes some dead code and unused variables and set static on definitions of compilation-unit local globals.
=> misc: small cleanups

cpu/stm32f0/include/periph_cpu.h, cpu/stm32f0/periph/gpio.c, cpu/stm32f0/vectors.c
~~based on #4697~~
Needed so I can proceed with #4430
=> cpu/stm32f0: fixes + gpio_init_analog() adde

drivers/cc110x/cc110x-netdev2.c, drivers/include/cc110x.h
Instead of hardcoding the protocol.
=> cc110x: make protocol configurable

boards/pba-d-01-kw2x/include/board.h
added button (S1 for revision 1 and S2 for revision 2)
=> board/pba-d-01-kw2x: user button added

drivers/include/mma8652.h, drivers/mma8652/mma8652.c, tests/driver_mma8652/main.c
1. commit fixes a bug: it is not possible to write to the configuration registers without being in the `STANDBY` mode
2. convert the raw data to milli g, so that a user does not need to look into the data sheets.
=> drivers/mma8652: enhancements

boards/samr21-xpro/include/periph_conf.h, cpu/samd21/include/periph_cpu.h, cpu/samd21/periph/pwm.c
3rd channel neeed to tinker with rgb-led stipes...
and sorry for the formatting fixes that slipped in :-)
=> boards/samr21-xpro: added third channel for PWM1

cpu/native/netdev2_tap/netdev2_tap.c, drivers/cc110x/cc110x-netdev2.c, drivers/enc28j60/enc28j60.c, drivers/encx24j600/encx24j600.c, drivers/ethos/ethos.c
=> drivers: net: fix isr_arg for encx24j600 and ethos

boards/nrf51dongle/include/board.h
without this configuration the xtimer is not working on this board...
=> boards/nrf51dongle: add xtimer configuration

boards/airfy-beacon/board.c, boards/airfy-beacon/include/board.h, boards/nrf51dongle/board.c, boards/nrf51dongle/include/board.h, boards/nrf52dk/include/board.h, boards/nrf6310/board.c, boards/nrf6310/include/board.h, boards/pca10000/board.c, boards/pca10000/include/board.h, boards/pca10005/board.c, boards/pca10005/include/board.h, boards/yunjia-nrf51822/board.c, boards/yunjia-nrf51822/include/board.h
=> boards: cleaned up LED handling for NRF5x based boards

boards/ek-lm4f120xl/Makefile.features, cpu/lm4f120/include/periph_cpu.h, cpu/lm4f120/periph/gpio.c, cpu/stellaris_common/include/cortex-m4-def.h
This PR add support for the GPIO API for the lm4f120 cpu
=> cpu/lm4f120: GPIO support

Makefile.dep, sys/posix/sockets/posix_sockets.c
=> libcoap: fix missing dependencies and includes

sys/xtimer/xtimer_core.c
As discussed on the mailing list
https://lists.riot-os.org/pipermail/devel/2016-February/003508.html
wbr
malo
=> xtimer: Malo xtimer fixes

drivers/ethos/ethos.c
=> drivers: ethos: fix _recv signature

boards/mbed_lpc1768/system.c
=> boards/mbed_lpc1768/system.c: C comment style

sys/shell/commands/sc_netif.c
Revisited this bit of code when discussing a separate issue with @OlegHahm. Might be of interest to look at for @haukepetersen since it is his original code.
=> sc_netif: check for NULL pointers on send

drivers/include/nrf24l01p.h, drivers/nrf24l01p/nrf24l01p.c
- The title is speaking I guess
- Not tested yet 
- I think the whole driver needs some love and hopefully adoptions to netdev at one time.
=> drivers/nrf24l01p: unify return values

dist/tools/compile_test/compile_test.py
=> dist: tools: compile_test: fix unassigned variable

sys/include/saul_reg.h, sys/saul_reg/saul_reg.c, sys/shell/commands/sc_saul_reg.c
=> sys/saul_reg: made registry a global variable

dist/tools/goodfet/goodfet.bsl
At least on my Python (2.7.11) and pyserial (3.0.1) version, the current script is not working.
=> tools: goodfet fix

sys/auto_init/netif/auto_init_at86rf2xx.c, sys/auto_init/netif/auto_init_kw2xrf.c
DEBUG was printing the wrong number.
=> auto_init: Print correct SPI bus in DEBUG output

tests/saul/Makefile, tests/saul/README.md, tests/saul/main.c
=> tests: added SAUL test application

boards/nucleo-f401/Makefile.features, boards/nucleo-f401/include/periph_conf.h
Added I2C pin configuration for the board "Nucleo-F401"
=> boards: I2C Feature for nucleo-f401

tests/unittests/tests-sixlowpan/Makefile, tests/unittests/tests-sixlowpan/Makefile.include, tests/unittests/tests-sixlowpan/tests-sixlowpan.c, tests/unittests/tests-sixlowpan/tests-sixlowpan.h
Some tests are failing - not sure, why.
=> unittests: initial import of 6LoWPAN tests

boards/chronos/include/board.h, boards/msb-430/include/board.h, boards/msb-430h/include/board.h, tests/leds/Makefile, tests/leds/README.md, tests/leds/main.c
when doing #4828, I found it useful to have an application that just let's the on-board LEDs blink, so here it is...
~~Travis will fail right now, so waiting for #4828.~~
=> tests: added test for on-board LED macros

sys/net/gnrc/link_layer/netdev2/gnrc_netdev2_eth.c
In case the packet buffer is full `gnrc_netdev2_eth` might crash currenlty.
(See also https://github.com/RIOT-OS/RIOT/pull/4646#discussion_r52534904)
=> gnrc_netdev_eth: handle error on iovec initialization.

Makefile.include
=> make: check if APPLICATION is set

boards/saml21-xpro/Makefile.features, boards/saml21-xpro/include/periph_conf.h, cpu/saml21/periph/rtc.c
FWX did a port of RTC from the SAMR21 to the SAML21. 
TODO: Need to be tested
=> Driver RTC for the board SAML21 by FWX

examples/default/README.md, examples/posix_sockets/README.md, sys/shell/commands/sc_netif.c, sys/shell/commands/shell_commands.c
=> shell: improved online documentation for txtsnd

boards/nucleo-f091/include/board.h, boards/nucleo-f103/include/board.h, boards/nucleo-f303/include/board.h, boards/nucleo-f334/include/board.h, boards/nucleo-f401/include/board.h, boards/nucleo-l1/include/board.h, boards/saml21-xpro/include/board.h, boards/stm32f0discovery/include/board.h, boards/stm32f3discovery/include/board.h, boards/stm32f4discovery/include/board.h
Useful for testing of if one ones to use the on-board button(s) in an application.
=> boards: added pin defines for user buttons

boards/arduino-mega2560/Makefile.include
A wiki page with the procedure should be created (I can create it)
=> boards/arduino-mega2560: add support to flash it on mac osx

core/include/cib.h
Adopted #4086 from @IldarValiev
=> core: added documentation and assert to cib

Makefile.dep, sys/net/routing/nhdp/iib_table.c, sys/net/routing/nhdp/nhdp.c, sys/net/routing/nhdp/nhdp.h, sys/net/routing/nhdp/nhdp_reader.c, sys/net/routing/nhdp/nib_table.c
Splitted first part of PR #4660
=> sys/net/routing/nhdp: get rid of vtimer

sys/include/net/fib.h
extend the `FIB_MSG_RP_SIGNAL_` documentation to make the signals intentions a bit more clear :)
=> fib: extend FIB_MSG_RP_SIGNAL documentation

cpu/cc2538/periph/i2c.c, cpu/stm32f1/periph/i2c.c
Minor follow up to #4943 for two drivers that were left out.
=> cpu/periph: Fix some more empty body warnings

boards/ek-lm4f120xl/Makefile.features, boards/ek-lm4f120xl/include/periph_conf.h, cpu/lm4f120/periph/adc.c
Only ADC_0 and no precision support.
=> cpu/lm4f120: ADC support

core/include/lpm.h, cpu/nrf5x_common/doc.txt
Stumbled across these when I was looking for something else.
=> Small Doxygen fixes

boards/fox/include/periph_conf.h, boards/iotlab-m3/include/periph_conf.h, boards/nucleo-f103/include/periph_conf.h, boards/spark-core/include/periph_conf.h, cpu/stm32f1/include/periph_cpu.h, cpu/stm32f1/periph/adc.c, cpu/stm32f1/periph/gpio.c
The ADC peripheral implementation for the STM32F1xx series.
=> cpu/stm32f1/periph/adc: ADC implementation for STM32F1

Makefile.include, cpu/Makefile.include.cortexm_common
=> make: always include toolchain dependent Makefile

sys/color/color.c, sys/include/color.h, tests/unittests/tests-color/tests-color.c
I've added to the color library the inversion of a given rgb color as the calculation of the complementary color of a given rgb color
=> RGB color inversion and complementary color calculation added

core/thread.c
Current version doesn't check if pid is valid and can damage innocent data.
=> Added thread existence check at thread_wakeup

Makefile.vars, boards/msba2-common/Makefile.include, cpu/Makefile.include.cortexm_common, cpu/Makefile.include.llvm, sys/newlib/Makefile.include
Rename TARGET_TRIPLE to TARGET_ARCH as discussed in #5088
=> make: Rename TARGET_TRIPLE -> TARGET_ARCH

boards/mulle/include/periph_conf.h
Added some more pins to the default configuration.
=> boards/mulle: Add more ADC lines to default configuration

cpu/stm32f1/include/periph_cpu.h, cpu/stm32f1/periph/gpio.c
fix for bug introduced with #4862
=> cpu/stm32f1: fixed pull selection in GPIO driver

sys/shell/commands/Makefile
=> shell: fix condition for ping command

Makefile.pseudomodules, cpu/Makefile.include.cortexm_common, sys/Makefile.include, tests/printf_float/Makefile, tests/printf_float/main.c
Addressing one of the comment from #5078.
=> newlib: enabling floating point printf for cortex-m cpus

drivers/dht/dht.c, drivers/dht/dht_saul.c, drivers/dht/include/dht_params.h, drivers/include/dht.h, drivers/include/saul.h, drivers/saul/Makefile, drivers/saul/saul.c
~~based on #4664~~
This PR adds SAUL support for DHTxx devices.
The interesting part here is the synchronization of values for the temperature and humidity endpoints.
=> drivers/dht: added support for SAUL

sys/include/net/gnrc/rpl.h, sys/net/gnrc/routing/rpl/gnrc_rpl.c, sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c, sys/net/gnrc/routing/rpl/gnrc_rpl_dodag.c, sys/shell/commands/sc_gnrc_rpl.c
Minor fixes/enhancements like formatting, removing superfluous initializations, etc.
No functionality changes.
=> gnrc_rpl: minor enhancements

tests/xtimer_drift/main.c
- drift is the total difference from the expected time
- jitter is the difference only since the last printout
=> tests/xtimer_drift: Compute drift and jitter

dist/tools/travis-scripts/get-pkg-list.py
=> dist: travis: add gdb to travis

Makefile.include, pkg/ccn-lite/Makefile.include, pkg/cmsis-dsp/Makefile.include, pkg/libcoap/Makefile.include, pkg/micro-ecc/Makefile.include, pkg/microcoap/Makefile.include, pkg/oonf_api/Makefile.include, pkg/pkg.mk, pkg/relic/Makefile.include, pkg/tlsf/Makefile, pkg/tlsf/Makefile.include
=> pkg: (git): move pkgdir to $BINDIRBASE/pkg/$BOARD/$PKG_NAME, do proper clean

cpu/native/include/netdev2_tap.h, cpu/native/netdev2_tap/netdev2_tap.c, cpu/native/startup.c, drivers/at86rf2xx/at86rf2xx.c, drivers/at86rf2xx/at86rf2xx_getset.c, drivers/at86rf2xx/at86rf2xx_internal.c, drivers/at86rf2xx/at86rf2xx_netdev.c, drivers/encx24j600/encx24j600.c, drivers/ethos/ethos.c, drivers/include/at86rf2xx.h, drivers/include/encx24j600.h, drivers/include/ethos.h, drivers/include/xbee.h, drivers/xbee/xbee.c, sys/auto_init/netif/auto_init_at86rf2xx.c, sys/auto_init/netif/auto_init_xbee.c, tests/driver_at86rf2xx/main.c, tests/driver_xbee/xbee_params.h
For consistency and simplification reasons.
=> netdev2: use params parameter for setup

boards/cc2538dk/Makefile.features, boards/cc2538dk/include/periph_conf.h, boards/openmote-cc2538/Makefile.features, boards/openmote-cc2538/include/periph_conf.h, boards/remote/Makefile.features, boards/remote/include/periph_conf.h, cpu/cc2538/Makefile.include, cpu/cc2538/include/cc2538_ssi.h, cpu/cc2538/include/periph_cpu.h, cpu/cc2538/periph/spi.c
=> cpu/cc2538: add periph/spi driver

dist/tools/compile_test/compile_test.py
See https://github.com/RIOT-OS/RIOT/pull/5180#issuecomment-201913008
=> dist: CI: remove application skipping

drivers/cc110x/cc110x.c
=> cc110x: fix typo

boards/fox/include/periph_conf.h, boards/iotlab-m3/include/periph_conf.h, boards/limifrog-v1/include/periph_conf.h, boards/nucleo-f091/include/periph_conf.h, boards/nucleo-f103/include/periph_conf.h, boards/nucleo-f303/include/periph_conf.h, boards/nucleo-f334/include/periph_conf.h, boards/nucleo-l1/include/periph_conf.h, boards/spark-core/include/periph_conf.h, boards/stm32f0discovery/include/periph_conf.h, boards/stm32f3discovery/Makefile.features, boards/stm32f3discovery/include/periph_conf.h, boards/stm32f4discovery/include/periph_conf.h, cpu/stm32_common/include/periph_cpu_common.h, cpu/stm32_common/periph/dac.c, cpu/stm32f0/include/periph_cpu.h, cpu/stm32f1/include/periph_cpu.h, cpu/stm32f3/include/periph_cpu.h, cpu/stm32f3/periph/gpio.c, cpu/stm32f4/include/periph_cpu.h, cpu/stm32l1/include/periph_cpu.h, cpu/stm32l1/periph/gpio.c
The DAC peripheral implementation for the STM32F1xx series.
=> cpu/stm32f1/periph/dac: DAC implementation for STM32F1

cpu/stm32f4/cpu.c
One more with #3703 in mind.
Propose to configure the STM32F4 PLL clock source with the CLOCK_HSE or CLOCK_HSI define in the includes\periph_conf.h from the BSP
Can't test HSI and HSE implementation, although nothing for HSE isn't changed. HSI should also work since the clock tree is the same for HSI and HSE selection.
=> cpu: Add clock source selection based on CLOCK_HSE or CLOCK_HSI for STM32F4 family

Makefile.pseudomodules, cpu/native/netdev2_tap/netdev2_tap.c, drivers/at86rf2xx/at86rf2xx.c, drivers/at86rf2xx/at86rf2xx_netdev.c, drivers/enc28j60/enc28j60.c, drivers/include/net/netdev2.h, drivers/netdev2_eth/netdev2_eth.c, drivers/netdev2_ieee802154/netdev2_ieee802154.c, sys/net/gnrc/link_layer/netdev2/gnrc_netdev2.c, sys/net/gnrc/link_layer/netdev2/gnrc_netdev2_eth.c, sys/net/gnrc/link_layer/netdev2/gnrc_netdev2_ieee802154.c, sys/shell/commands/sc_netif.c
A first step towards addressing https://github.com/RIOT-OS/RIOT/issues/1297.
~~Depends on #4645.~~
Waits for #5176, but is not yet rebased on it.
=> netstats: introduce L2 netstats

cpu/lpc2387/asmfunc.s, cpu/lpc2387/mci/lpc2387-mci.c, drivers/include/diskio.h, sys/auto_init/auto_init.c, sys/shell/commands/sc_disk.c
Just another minor step towards #2137.
=> doc diskio: RIOTized style and added doxygen

dist/tools/ethos/ethos.c
=> dist: ethos: fix usage string

pkg/pkg.mk
=> make: pkg: remove pkg source dir before checkout

doc/doxygen/src/getting-started.md
Found this while referring it to a user.
=> doc: fix typo

sys/include/net/netopt.h
=> netopt: fix typo in documentation

drivers/include/net/netdev2.h
=> netdev2: fix event_callback references

pkg/openwsn/Makefile
=> pkg/openwsn: prevent build loop (backport)

sys/saul_reg/saul_reg.c, tests/unittests/tests-saul_reg/Makefile, tests/unittests/tests-saul_reg/Makefile.include, tests/unittests/tests-saul_reg/tests-saul_reg.c, tests/unittests/tests-saul_reg/tests-saul_reg.h
=> test: added unittests for the SAUL registry

sys/saul_reg/saul_reg.c, tests/unittests/tests-saul_reg/Makefile, tests/unittests/tests-saul_reg/Makefile.include, tests/unittests/tests-saul_reg/tests-saul_reg.c, tests/unittests/tests-saul_reg/tests-saul_reg.h
=> test: added unittests for the SAUL registry (Backport of #5323)

drivers/Makefile.dep
=> drivers/Makefile.dep: fixed FEATURE_REQ assignments (backport of #5308)

drivers/include/periph/adc.h, drivers/include/periph/i2c.h, drivers/include/periph/pwm.h, drivers/include/periph/timer.h, drivers/include/periph/uart.h, tests/periph_uart/main.c
=> drivers/periph: fixed UNDEF values to UINT_MAX (backport)

boards/x86-multiboot-common/include/multiboot.h
=> boards/multiboot: close doxy group (backport)

sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c
=> gnrc_sixlowpan_iphc.c: handle forwarded GNRC_NETTYPE_IPV6 packet (backport)

sys/include/net/gnrc/ipv6.h, sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c
Backport to https://github.com/RIOT-OS/RIOT/pull/5326
=> gnrc_ipv6: Revert #5179 (backport)

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c
=> gnrc_ndp: don't let addresses timeout (backport)

dist/tools/ethos/start_network.sh
=> tools: ethos: allow `start_network.sh` script to run from anywhere (backport)

core/mutex.c
=> core: allow DEBUG in mutex.c to run without DEVELHELP (backport)

drivers/at86rf2xx/at86rf2xx_netdev.c, drivers/netdev2_ieee802154/netdev2_ieee802154.c
=> at86rf2xx: fix option setting (backport)

Makefile.dep
Reverting #5044
EDIT: https://github.com/RIOT-OS/Release-Specs/issues/19#issuecomment-212917673
=> make: disable NHC

Makefile.dep
=> make: disable NHC (backport of #5385)

boards/pba-d-01-kw2x/board.c
This PR fixes leds default state (off).
=> boards/pba-d-01-kw2x/board.c: fix leds default state

cpu/nrf51/ldscripts/nrf51x22xxac.ld
nRF51 AC variant with 256K of ROM and 32K of RAM
=> Added nrf51 ac variant

boards/airfy-beacon/include/board.h, boards/arduino-mega2560/include/board.h, boards/chronos/include/board.h, boards/msb-430-common/include/board_common.h, boards/nrf51dongle/include/board.h, boards/pca10000/include/board.h, boards/pca10005/include/board.h, boards/telosb/include/board.h, boards/wsn430-common/include/board_common.h, boards/yunjia-nrf51822/include/board.h, boards/z1/include/board.h, sys/include/xtimer.h
=> sys/xtimer: eliminate XTIMER_SHIFT_ON_COMPARE (backport)

Makefile.dep
=> make: enable NHC by default (backport)

Makefile.dep
=> make: enable NHC by default

drivers/netdev2_ieee802154/netdev2_ieee802154.c
Follow-up to https://github.com/RIOT-OS/RIOT/pull/5227#discussion_r59983170.
=> netdev2_ieee802154: replace overflow checks with asserts

Makefile.dep, sys/trickle/trickle.c
A little refactoring of our `trickle` module to use the proper `random` functions, and some minor things.
How to test: Run `gnrc_networking`, start a rpl root node and look at the `rpl` output `TR(...)`.
```
text    data    bss     dec     BOARD/BINDIRBASE
-144    0       0       -144    arduino-due
58284   292     17456   76032   master-bin
58140   292     17456   75888   trickle-bin
-310    -4      0       -314    arduino-mega2560
83100   11802   11260   106162  master-bin
82790   11798   11260   105848  trickle-bin
-228    0       0       -228    avsextrem
86316   228     98069   184613  master-bin
86088   228     98069   184385  trickle-bin
-144    0       0       -144    cc2538dk
58452   228     17408   76088   master-bin
58308   228     17408   75944   trickle-bin
-144    0       0 …
```
=> trickle: uses random.h and includes some enhancements

drivers/bmp180/bmp180.c, drivers/bmp180/bmp180_saul.c, drivers/bmp180/include/bmp180_params.h, drivers/include/bmp180.h, sys/auto_init/auto_init.c
Not tested yet but it should work.
=> drivers/bmp180: add saul adaptation

dist/tools/git/git-cache
Tags need also be downloaded. See https://github.com/RIOT-OS/RIOT/pull/5400#issuecomment-223071249.
=> git-cache: also fetch tags

pkg/pkg.mk
The purpose of this PR is twofold:
1. Providing an alternative to #5393 by solving the potential concurrency issues caused in "Apple" make ( @kYc0o, @emmanuelsearch, @thomaseichinger please check!)
2. Re-separating the patching and downloading step. This way a package needs not to be re-downloaded, when one just changes the patch files. In the same stroke I made the patch operation dependent both on the patch files and the Makefile of the package (for possible URL or version change) i.e. changes to them cause a re-patch.
=> pkg: split patch and download rule

sys/include/net/gnrc/rpl.h, sys/include/net/gnrc/rpl/p2p.h, sys/include/net/gnrc/rpl/srh.h
=> gnrc_rpl: doc fix

sys/include/phydat.h, sys/phydat/phydat_str.c
I'll arrive soon with a PR implementing a driver for [a luminosity sensor](https://cdn-shop.adafruit.com/datasheets/TSL2561.pdf) but I need this first to integrate it in saul.
=> sys/phydat: adding luminosity unit (Lux)

cpu/native/include/clang_compat.h, cpu/nrf51/include/cpu_conf.h, cpu/nrf51/include/nrf51_bitfields.h, cpu/nrf52/include/nrf52_bitfields.h, cpu/sam3/include/cpu_conf.h, cpu/samd21/include/cpu_conf.h, cpu/stellaris_common/include/cortex-m4-def.h, cpu/stellaris_common/include/hw_adc.h, cpu/stellaris_common/include/hw_gpio.h, cpu/stellaris_common/include/hw_hibernate.h, cpu/stellaris_common/include/hw_i2c.h, cpu/stellaris_common/include/hw_ints.h, cpu/stellaris_common/include/hw_memmap.h, cpu/stellaris_common/include/hw_nvic.h, cpu/stellaris_common/include/hw_pwm.h, cpu/stellaris_common/include/hw_ssi.h, cpu/stellaris_common/include/hw_sysctl.h, cpu/stellaris_common/include/hw_sysexc.h, cpu/stellaris_common/include/hw_timer.h, cpu/stellaris_common/include/hw_types.h, cpu/stellaris_common/include/hw_uart.h, cpu/stellaris_common/include/hw_watchdog.h, cpu/stellaris_common/include/stellaris_periph/adc.h, cpu/stellaris_common/include/stellaris_periph/comp.h, cpu/stellaris_common/include/stellaris_periph/cpu.h, cpu/stellaris_common/include/stellaris_periph/fpu.h, cpu/stellaris_common/include/stellaris_periph/gpio.h, cpu/stellaris_common/include/stellaris_periph/hibernate.h
Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#)
=> CPU：Fix header include guards

tests/thread_exit/README.md, tests/thread_exit/main.c
=> tests/thread_exti: add small README

cpu/stellaris_common/include/stellaris_periph/i2c.h, cpu/stellaris_common/include/stellaris_periph/interrupt.h, cpu/stellaris_common/include/stellaris_periph/pin_map.h, cpu/stellaris_common/include/stellaris_periph/pwm.h, cpu/stellaris_common/include/stellaris_periph/rom.h, cpu/stellaris_common/include/stellaris_periph/rom_map.h, cpu/stellaris_common/include/stellaris_periph/ssi.h, cpu/stellaris_common/include/stellaris_periph/sysctl.h, cpu/stellaris_common/include/stellaris_periph/sysexc.h, cpu/stellaris_common/include/stellaris_periph/systick.h, cpu/stellaris_common/include/stellaris_periph/timer.h, cpu/stellaris_common/include/stellaris_periph/uart.h, cpu/stellaris_common/include/stellaris_periph/watchdog.h
Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#)
=> cpu/stellaris: fix header include guards.

cpu/samd21/include/samd21.h
=> samd21: do not redefine LITTLE_ENDIAN

dist/tools/travis-scripts/build_and_test.sh
This PR should fix murdock for non-master branches.
=> dist: build_and_test.sh: don't hard-code base branch

dist/tools/ethos/ethos.c, dist/tools/ethos/start_network.sh, examples/gnrc_border_router/Makefile
=> dist/tools: ethos baudrate configuration

pkg/lwip/contrib/netdev2/lwip_netdev2.c, pkg/lwip/include/lwipopts.h
This fixes some guard comments and removes a duplicated line.
=> pkt/lwip: minor fixes

core/include/cib.h, tests/unittests/tests-core/tests-core-cib.c
I needed that on a project I was working on...
=> core/cib: add peek capabilities

drivers/l3g4200d/l3g4200d_saul.c
Came across this tiny copy-paste mistake :-)
=> drivers: l3g4200d: fix saul doxygen group

tests/driver_bh1750/Makefile
Found another small copy-paste mistake.
=> tests: driver_bh1750: fix application name

cpu/cortexm_common/vectors_cortexm.c
This PR reorders the DEVELHELP hardfault handler to show as much informations as possible also when the stack has been corrupted.
When the stack has been corrupted it will still be possible to read the extended fault status registers since they are hardware registers not located in RAM.
Also moved the BKPT instruction at the end to outside the condition so that the debugger halts regardless of the state of the stack.
=> cortexm: Hard fault: Try to output as much as possible even with corrupt stack

cpu/msp430fxyz/periph/gpio.c
As proposed in  #5302 
~~(currently untested)~~
=> cpu/msp430: initialize gpio as input OR output

cpu/samd21/periph/i2c.c
The i2c_poweroff did not disable.
=> cpu/samd21/periph/i2c: power off did enable instead of disable

dist/tools/ethos/ethos.c
Add ethos support to use a tcp socket instead of a TTY.
Use 'tcp:hostname[:port]' as serial argument.
Default port is 20000 which is used in on IoT-LAB.
Known issue: hostname cannot be an ipv6 address, because of the ':'.
=> dist: ethos: add tcp socket support

cpu/stm32f4/include/periph_cpu.h
Simple code style changes. 
(extracted from #5643)
=> cpu/stm32f4: uncrustify periph_cpu

pkg/lwip/contrib/netdev2/lwip_netdev2.c
lwIP does some weird byte-swapping in netif_create_ip6_linklocal_address()
with non-ethernet-addresses, so I rather initialize it like in GNRC, so it is
compatible to both GNRC and emb6.
Backport to #5718
=> lwip: initialize link-local address correctly

cpu/kinetis_common/periph/i2c.c
I had to debug a misbehaving i2c device without access to the JTAG port, only UART, so I added some `DEBUG` messages to the periph/i2c driver for Kinetis. Modify `ENABLE_DEBUG` at the top of the file to 1 just like any other RIOT file to use.
There are two commented-out debug lines as well for printing each byte as they are transferred, but that is only useful in rare circumstances so I left them commented out.
=> cpu/kinetis_common: Add debugging messages to i2c driver

pkg/tiny-asn1/Makefile, pkg/tiny-asn1/Makefile.include, pkg/tiny-asn1/doc.txt, pkg/tiny-asn1/patches/0001-Added-RIOT-Makefile.patch, tests/pkg_tiny-asn1/Makefile, tests/pkg_tiny-asn1/README.md, tests/pkg_tiny-asn1/main.c, tests/pkg_tiny-asn1/tests/01-run.py
This is an early heads-up and very much work in progress.
I have just released the first alpha version of [tiny-asn1](https://gitlab.com/matthegap/tiny-asn1), a lightweight asn.1/der decoder for embedded devices. It is still a bit rough around the edges and has virtually no documentation, but once it is usable I would like to include it into RIOT as a package.
I have some questions which will help me to finish this:
* I am using CMAKE as a build system for tiny-asn1. Is it ok to require that for the build, or do I have to create a seperate Makefile?
* Where should I place documentation about a new package?
And of course, any feedback on the code is very welcome.
=> Include tiny-asn1 as a package

sys/embunit/ColorTextColors.h, sys/include/embUnit.h, sys/include/embUnit/AssertImpl.h, sys/include/embUnit/ColorOutputter.h, sys/include/embUnit/ColorTextOutputter.h, sys/include/embUnit/CompilerOutputter.h, sys/include/embUnit/HelperMacro.h, sys/include/embUnit/Outputter.h, sys/include/embUnit/RepeatedTest.h, sys/include/embUnit/Test.h, sys/include/embUnit/TestCaller.h, sys/include/embUnit/TestCase.h, sys/include/embUnit/TestListener.h, sys/include/embUnit/TestResult.h, sys/include/embUnit/TestRunner.h, sys/include/embUnit/TestSuite.h, sys/include/embUnit/TextOutputter.h, sys/include/embUnit/TextUIRunner.h, sys/include/embUnit/XMLOutputter.h, sys/include/embUnit/embUnit.h, sys/include/embUnit/embUnit_config.h, sys/include/embUnit/stdImpl.h
Fix sys/embunit header include guards.
Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#).
=> Fix sys/embunit header include guards.

sys/include/crypto/ciphers.h, sys/include/crypto/helper.h, sys/include/crypto/modes/cbc.h, sys/include/crypto/modes/ccm.h, sys/include/crypto/modes/ctr.h, sys/include/crypto/modes/ecb.h
Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#).
=> fix sys/crypto header include guards.

drivers/at86rf2xx/include/at86rf2xx_internal.h
Documents concerns stated in https://github.com/RIOT-OS/RIOT/pull/4925#issuecomment-190735863
=> at86rf2xx: document operation mode concerns for

pkg/u8g2/Makefile, pkg/u8g2/patches/0001-u8g2-add-riot-os-makefiles.patch, pkg/u8g2/patches/0002-u8g2-add-riot-os-interface.patch, tests/pkg_u8g2/Makefile, tests/pkg_u8g2/README.md, tests/pkg_u8g2/main.c
Just a few bug fixes and improvements due to [new developments](https://github.com/olikraus/u8g2/pull/37) that should simplify a few things. I also simplified the test application.
Mark it as WIP, because I still have to test one display, which I don't have acces to. In the mean time, maybe @aabadie wants to check out the improvements?
=> pkg: u8g2: improvements and bugfixes

Makefile.include
=> make: include RIOT_VERSION in CFLAGS for riotbuild

Makefile.dep, pkg/lwip/contrib/sys_arch.c, pkg/lwip/include/arch/sys_arch.h
Ports lwip sys_mbox wrappers to RIOTs native mboxes.
=> lwip: port mboxes to core_mbox

examples/ccn-lite-relay/main.c
=> examples: ccn-lite-relay: minor doc fix

cpu/atmega1281/include/cpu_conf.h, cpu/atmega_common/avr-libc-extra/errno.h
Pull request created as per the issue  [#2623](https://github.com/RIOT-OS/RIOT/issues/2623#).
=> fix cpu/atmega header include guardes.

boards/native/Makefile.include
longer discussion here #5787, corrects some changes introduces in #5742 for OSX
=> correcting linker LTO flags on OSX

cpu/samd21/periph/i2c.c
There are several places in the i2c driver for the samd21 where the pattern
```
register & busstate_value 
```
is used. This works for single bits, but it does not work as expected here where the bus state is two bits. I discovered this because for back to back i2c writes, it was not properly waiting for the stop condition to finish, so it would fail in the next start condition, but there are other less common code paths where I think the check is incorrect in the current code.
I will add line comments for each one to further explain the logic.
=> samd21: i2c: check all busstate bits

tests/driver_at86rf2xx/recv.c
=> tests/driver_at86rf2xx: corrects flag compare

sys/include/net/gnrc/rpl.h
- expose configurable default parameters
- adapt some default values, e.g. to RFC values
=> gnrc_rpl: adapt default parameters and expose to Makefile 

tests/unittests/README.md
For the sake of completeness, point out that you can debug your tests using gdb :) (thanks to @x3ro for telling me that this is possible :D)
=> unittests: document make debug

cpu/lpc2387/lpc2387-lpm.c, cpu/native/netdev2_tap/netdev2_tap.c, drivers/ethos/ethos.c, drivers/lsm303dlhc/lsm303dlhc.c, drivers/pir/pir.c, drivers/srf08/srf08.c, pkg/nordic_softdevice_ble/src/ble-core.c, pkg/nordic_softdevice_ble/src/ble-mac.c, pkg/openwsn/patches/0002-Add-RIOT-adaption.patch, sys/auto_init/netif/auto_init_cc110x.c, sys/auto_init/netif/auto_init_kw2xrf.c, sys/auto_init/netif/auto_init_xbee.c, sys/cbor/cbor.c, sys/crypto/modes/ccm.c, sys/net/gnrc/application_layer/tftp/gnrc_tftp.c, sys/net/gnrc/link_layer/netdev2/gnrc_netdev2_eth.c, sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c, sys/net/gnrc/network_layer/ipv6/netif/gnrc_ipv6_netif.c, sys/net/gnrc/routing/rpl/gnrc_rpl_dodag.c
=> debug: add missing line breaks

pkg/lwip/contrib/netdev2/lwip_netdev2.c, pkg/lwip/contrib/sys_arch.c
During hacking for #5802 I found some minor bugs in lwIP. This PR fixes those.
=> pkg: lwip: some fixes

Makefile.dep, sys/include/rtt_stdio.h, sys/rtt_stdio/Makefile, sys/rtt_stdio/README.md, sys/rtt_stdio/rtt_stdio.c
This is a rebase / reclean of #4720 which I accidentally nuked while cleaning stuff up.
@thomaseichinger I addressed the concerns you had on the previous PR. Would you mind taking a look and seeing if I missed anything?
I'd like to get this into the upcoming release, what can I do to increase the odds of that happening?
=> sys/rtt_stdio: Support SEGGER RTT for stdin/stdout

sys/include/net/sock/ip.h, sys/include/net/sock/udp.h
Another round of doc fixes (mostly typos).
=> sock: doc fixes

sys/shell/commands/sc_ipv6_nc.c
As it says in the title: fixes #5930
=> shell: ncache: Fix #5930

sys/include/net/sock/ip.h, sys/include/net/sock/udp.h
=> sock: Some formatting fixes

dist/tools/vagrant/README.md
=> Vagrant adapt readme

sys/include/net/gnrc.h
Add basic pktbuf usage to the tutorial in `gnrc.h` to draw attention to the fact that this should be done. Since the rest of the file doesn't mention the packet buffer, I think that it's important to point out its existence, since it could easily be overlooked otherwise.
Additionally, in some instances, I've found the text I read a bit hard to understand, so I've clarified the language.
Disclaimer: I've just written down what I think is correct from the code I've read, so I'm not 100% confident I got it right ;)
=> gnrc.h: extend documentation

core/include/thread.h
Rearrange existing documentation and add a small tutorial to thread.h in response to https://github.com/RIOT-OS/RIOT/issues/1837. I'm sure there's a lot more to be said about threads, but I thought this might be a start.
=> thread.h: rearrange docs, add small tutorial

cpu/cortexm_common/vectors_cortexm.c
Release branch version of #5727.
=> cpu: cortexm_common: fix compile warning

Makefile, Makefile.tests, dist/tools/static-tests.sh, dist/tools/travis-scripts/build_and_test.sh
Allow execution of static tests with the `make static-tests`
command and improve its output for the human reader
=> Improve execution of static-tests

boards/nucleo-f030/Makefile, boards/nucleo-f030/Makefile.features, boards/nucleo-f030/Makefile.include, boards/nucleo-f030/board.c, boards/nucleo-f030/dist/openocd.cfg, boards/nucleo-f030/include/board.h, boards/nucleo-f030/include/periph_conf.h, cpu/stm32f0/include/cpu_conf.h, cpu/stm32f0/include/stm32f030x8.h, cpu/stm32f0/ldscripts/stm32f030r8.ld, examples/gnrc_border_router/Makefile, examples/gnrc_networking/Makefile, examples/gnrc_tftp/Makefile, examples/microcoap_server/Makefile, examples/posix_sockets/Makefile, tests/coap/Makefile, tests/conn_ip/Makefile, tests/driver_xbee/Makefile, tests/gnrc_ipv6_ext/Makefile, tests/gnrc_sixlowpan/Makefile, tests/lwip/Makefile, tests/mutex_order/Makefile, tests/nhdp/Makefile, tests/posix_semaphore/Makefile, tests/pthread_rwlock/Makefile, tests/slip/Makefile, tests/thread_cooperation/Makefile, tests/unittests/Makefile
Yet another PR for adding very basic support to the nucleo f030 board. I only tested a few examples and had failing xtimer tests.
I need some help from someone more knowledgeable with ARM timers.
=> boards: initial support for Nucleo f030 board

tests/unittests/tests-checksum/tests-checksum-fletcher16.c, tests/unittests/tests-checksum/tests-checksum-fletcher32.c
=> tests: unittests: add tests for longer input vectors

sys/include/color.h, sys/include/od.h, sys/include/pipe.h, sys/include/ps.h, sys/include/shell.h, sys/include/shell_commands.h, sys/include/timex.h, sys/include/tm.h, sys/log/log_printfnoformat/log_module.h, sys/oneway-malloc/include/malloc.h, sys/posix/pthread/include/pthread.h, sys/posix/pthread/include/pthread_barrier.h, sys/posix/pthread/include/pthread_cancellation.h, sys/posix/pthread/include/pthread_cleanup.h, sys/posix/pthread/include/pthread_cond.h, sys/posix/pthread/include/pthread_mutex.h, sys/posix/pthread/include/pthread_mutex_attr.h, sys/posix/pthread/include/pthread_once.h, sys/posix/pthread/include/pthread_rwlock.h, sys/posix/pthread/include/pthread_rwlock_attr.h, sys/posix/pthread/include/pthread_scheduling.h, sys/posix/pthread/include/pthread_threading.h, sys/posix/pthread/include/pthread_threading_attr.h, sys/posix/pthread/include/pthread_tls.h
a bit of cleanup for issue #2623
=> sys: fix include headers guards

Makefile.dep, sys/Makefile, sys/include/net/ntp_packet.h, sys/include/net/sntp.h, sys/net/application_layer/sntp/Makefile, sys/net/application_layer/sntp/sntp.c, sys/shell/commands/Makefile, sys/shell/commands/sc_sntp.c, sys/shell/commands/shell_commands.c
Initial implementation for SNTP done during Ladies that Foss event. Currently missing tests, that will be added at a later point.
=> sntp: initial import

pkg/micro-ecc/Makefile.dep, tests/pkg_micro-ecc/Makefile
=> micro-ecc: require hardware RNG

examples/default/Makefile, examples/gnrc_border_router/Makefile, examples/gnrc_minimal/Makefile, examples/gnrc_networking/Makefile, examples/microcoap_server/Makefile, examples/nanocoap_server/Makefile
Backport from #6039 to 2016.10.
=> examples: fix custom channel definition [2016.10-backport]

boards/cc2538dk/include/board.h, boards/cc2538dk/include/periph_conf.h, boards/openmote-cc2538/include/board.h, boards/openmote-cc2538/include/periph_conf.h, boards/remote-common/include/board_common.h, boards/remote-common/include/periph_common.h, cpu/cc2538/include/periph_cpu.h, cpu/cc2538/periph/timer.c
=> CC2538 periph/timer overhaul [2016.10-backport]

sys/include/net/ppp/hdr.h, sys/include/net/ppptype.h
Hi.
I'm writing a PPP stack for RIOT (for usage with mobile communications, etc).
This is a PR of PPP header definition and running tests.
Best regards
=> [GNRC PPP] PPP header definition and helpers

examples/dtls-echo/dtls-client.c, examples/dtls-echo/dtls-server.c
Backport to https://github.com/RIOT-OS/RIOT/pull/6046
=> examples: fix off-by-one error in TinyDTLS example [2016.10-backport]

tests/mutex_order/Makefile, tests/mutex_order/README.md, tests/mutex_order/main.c, tests/mutex_order/tests/01-run.py
=> BACKPORT: tests: mutex_order: updated test and fixed README 

drivers/cc2420/cc2420.c, drivers/include/cc2420.h
=> drivers/cc2420: calculate CRC and check CRC_OK bit on packet reception [2016.10-backport]

sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c
=> gnrc_sixlowpan_nhc: fix forwarding case [2016.10-backport]

dist/tools/uhcpd/uhcpd.c
Adds '--bind-to-device' option to binds uhcpd listening socket to a device.
It allows running multiple uhcpd and so multiple border router on the same
computer.
This is used for IoT-LAB.
This option requires 'root' permissions as I currently didn't find an
alternative.
=> dist/tools/uhcpd: add an option to bind to device

boards/microbit/microbit/microbit.c
Amateur... 
(saves 76 byte ROM)
=> boards/microbit: optimized microbit_matrix_init()

sys/net/network_layer/ipv6/hdr/ipv6_hdr_print.c, sys/net/network_layer/sixlowpan/sixlowpan_print.c
This helps with some tests ;-).
=> net: fix header dumps for nanospec newlib

pkg/relic/Makefile, pkg/relic/fix-old-style-definitions.sh, pkg/relic/fix-util_print_wo_args.sh, pkg/relic/os_util.sh
=> [backport] pkg/relic: fix for macOS

pkg/nanocoap/Makefile
=> [backport] pkg/nanocoap: update pkg version

sys/include/net/sock/ip.h, sys/include/net/sock/tcp.h, sys/include/net/sock/udp.h, sys/net/gnrc/sock/include/sock_types.h, tests/gnrc_sock_ip/main.c, tests/gnrc_sock_udp/main.c
See https://github.com/RIOT-OS/RIOT/pull/6137#issuecomment-261506878
=> gnrc_sock: move net/af.h include to sock_types.h

drivers/bh1750fvi/bh1750fvi.c, drivers/include/bh1750fvi.h, tests/driver_bh1750/main.c
=> drivers/bh1750fvi: added names to return values

boards/native/Makefile.include, core/include/assert.h, doc/doxygen/riot.doxyfile
See https://github.com/RIOT-OS/RIOT/pull/5881#discussion_r81025522
=> native: always assert() verbosely

cpu/nrf5x_common/periph/uart.c
Fixes #5954  Move the clearing of TXRDY flag before writing the data to avoid
an infinite loop in case of multiple thread accessing the UART(very
possible when using the DEBUG/stdio over UART).
=> nRF5x uart_write : avoid infinite loop

sys/include/timex.h
Small time-related precursor to the new neighbor discovery ;-).
=> timex: more conversion macros

boards/avsextrem/drivers/avsextrem-smb380.c
same issue as in #6206, different location...
=> boards/avsextrem: fix u_int type in smb380 driver

sys/shell/commands/sc_gnrc_6ctx.c
=> shell: fix strtok_r compile error

dist/tools/git/git-cache
=> git-cache: consider if git_cache dir is present

cpu/stm32_common/periph/timer.c
=> cpu/stm32: fix timer speed for STM32F1 and F2

tests/periph_uart/main.c
Terminating the used strings with a `\0` character made UART ports a little harder to test with external usb-uart-converters. Changing the termination character to Unix endline (`\n`) should be more straight forward and easier to apply.
=> tests/periph_uart: terminate strings with \n

boards/limifrog-v1/include/periph_conf.h, boards/nucleo-f103/include/periph_conf.h
=> boards/stm32f1-based: fixed timer configuration

cpu/nrf5x_common/include/nrfmin.h
=> doc: correct doxygen group for nrfmin

sys/include/net/ppp/hdr.h, sys/include/net/ppptype.h
=> doc: fix doxygen groups for PPP

boards/frdm-k64f/include/periph_conf.h, boards/mulle/include/periph_conf.h, boards/pba-d-01-kw2x/include/periph_conf.h, cpu/kinetis_common/include/periph_cpu.h, cpu/kinetis_common/periph/pwm.c
Some simplification and 'modern' style for the Kinetis PWM driver.
EDIT:
~~So far untested (hence WIP) and only adapted for the phyNODE and the mulle.~~
Confirmed working for the `pba-d-01-kw2x` (phyNODE)
=> cpu/kinetis: reworked PWM driver implementation

core/include/list.h, pkg/oonf_api/patches/0012-isolate-oonf-list-implementation-of-riot-s-implement.patch
this adds a method to remove elements from a list
Required by: #6158
=> core/list: add remove method

drivers/bmp180/bmp180_saul.c
This just remove useless function in the saul adaptation.
=> drivers/bmp180: saul driver cleanup

Jenkinsfile
Rationale: I am currently evaluating the performance of Jenkins and for this a `Jenkinsfile` is necessary.
Jenkins is able to detect PRs and branches when a `Jenkinsfile` is included in the root directory.
Such a `Jenkinsfile` orchestrates a build's operation (much like `.travis.yml` for Travis).
This PR is WIP and feedback is very welcome.
=> jenkins: add initial config

boards/arduino-common/Makefile.dep, boards/arduino-common/Makefile.include, boards/arduino-common/include/gpio_params.h
expose on-board led to saul interface.
=> boards/arduino-common: export led via saul

cpu/cortexm_common/cortexm_init.c, cpu/cortexm_common/mpu.c, cpu/kinetis_common/periph/gpio.c, drivers/at86rf2xx/at86rf2xx.c, drivers/at86rf2xx/at86rf2xx_netdev.c, sys/auto_init/saul/auto_init_adc.c, sys/auto_init/saul/auto_init_gpio.c, sys/auto_init/saul/auto_init_isl29020.c, sys/auto_init/saul/auto_init_l3g4200d.c, sys/auto_init/saul/auto_init_lis3dh.c, sys/auto_init/saul/auto_init_lps331ap.c, sys/auto_init/saul/auto_init_lsm303dlhc.c, sys/auto_init/saul/auto_init_mma8652.c
Fixes some of the warnings enabled by -Wextra
References #1121
=> sys+cpu: Some warning fixes

boards/pba-d-01-kw2x/Makefile.dep, drivers/Makefile.dep, drivers/Makefile.include, drivers/hdc1000/hdc1000.c, drivers/hdc1000/hdc1000_saul.c, drivers/hdc1000/include/hdc1000_params.h, drivers/hdc1000/include/hdc1000_regs.h, drivers/include/hdc1000.h, sys/auto_init/auto_init.c, sys/auto_init/saul/auto_init_hdc1000.c, tests/driver_hdc1000/Makefile, tests/driver_hdc1000/README.md, tests/driver_hdc1000/main.c
This PR implements the SAUL interface for the HDC1000 sensor and adds means for auto-initializing it.
=> drivers/hdc1000: remodeled driver + SAUL integration

boards/stm32f4discovery/include/periph_conf.h
#6393 was merged slightly too fast, I forgot to un-comment a block that I commented out for debugging...
=> boards/stm32f4discovery: fix PWM configuration

boards/stm32f4discovery/Makefile.dep, boards/stm32f4discovery/include/gpio_params.h
Similar to #6324 except that the LEDs are not as nice.
=> boards/stm32f4discovery: export user LEDs and button to SAUL

boards/stm32f0discovery/Makefile.dep, boards/stm32f0discovery/include/gpio_params.h
=> boards/stm32f0discovery: export user LEDs and button to SAUL

Jenkinsfile
Execute the static-tests on a slave instead of a master. See [1].
[1] https://github.com/RIOT-OS/RIOT/pull/6390#issuecomment-273187329
=> jenkins: exec static-tests on slave instead of master

sys/xtimer/xtimer_core.c
=> xtimer: fix formatter for xtimer_now in DEBUG

boards/nucleo-f070/Makefile.features, boards/nucleo-f070/include/periph_conf.h
Same as #6375 but for nucleo-f070.
=> boards/nucleo-f070: configure some PWM pins, add extra UART, fix ADC

Jenkinsfile
No need for the second commit status notification anymore.
=> jenkins: remove extra githubNotify

boards/nucleo-f401/Makefile.features, boards/nucleo-f401/include/periph_conf.h
=> boards/nucleo-f401: configure PWM on 7 pins

cpu/lpc11u34/periph/gpio.c
Toggle function is LPC_GPIO->NOT and not LPC_GPIO->CLR
=> cpu/lpc11u34: Bug with toggle function

boards/weio/include/periph_conf.h, cpu/lpc11u34/include/periph_cpu.h, cpu/lpc11u34/periph/pwm.c
last step towards cleaning up the PWM implemenations. Needed for #6231
=> cpu/lpc11u34: remodeled PWM driver

drivers/Makefile.dep, drivers/Makefile.include, drivers/bme280/Makefile, drivers/bme280/bme280.c, drivers/bme280/bme280_saul.c, drivers/bme280/include/bme280_internals.h, drivers/bme280/include/bme280_params.h, drivers/include/bme280.h, sys/auto_init/auto_init.c, sys/auto_init/saul/auto_init_bme280.c, tests/driver_bme280/Makefile, tests/driver_bme280/Readme.md, tests/driver_bme280/main.c
The subject says it all.
It was inspired by the driver for BMP180, and the public Github code from Bosch.
=> drivers: Add driver for BME280

Makefile.dep, examples/gnrc_tcp_cli/Makefile, examples/gnrc_tcp_cli/main.c, examples/gnrc_tcp_srv/Makefile, examples/gnrc_tcp_srv/main.c, sys/auto_init/auto_init.c, sys/include/net/gnrc/tcp.h, sys/include/net/gnrc/tcp/config.h, sys/include/net/gnrc/tcp/fsm.h, sys/include/net/gnrc/tcp/hdr.h, sys/include/net/gnrc/tcp/tcb.h, sys/net/gnrc/Makefile, sys/net/gnrc/netreg/gnrc_netreg.c, sys/net/gnrc/transport_layer/tcp/Makefile, sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c, sys/net/gnrc/transport_layer/tcp/gnrc_tcp_eventloop.c, sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c, sys/net/gnrc/transport_layer/tcp/gnrc_tcp_option.c, sys/net/gnrc/transport_layer/tcp/gnrc_tcp_pkt.c, sys/net/gnrc/transport_layer/tcp/gnrc_tcp_rcvbuf.c, sys/net/gnrc/transport_layer/tcp/internal/eventloop.h, sys/net/gnrc/transport_layer/tcp/internal/fsm.h, sys/net/gnrc/transport_layer/tcp/internal/helper.h, sys/net/gnrc/transport_layer/tcp/internal/option.h, sys/net/gnrc/transport_layer/tcp/internal/pkt.h, sys/net/gnrc/transport_layer/tcp/internal/rcvbuf.h
TCP implementation for gnrc. 
There are still a lot do, so this pull request is for referential purposes. 
Current todo list:
1. ~~Zero Window Probing~~
2. ~~Adaptive Transamission Times (Retransmission time is currently a constant)~~
3. ~~Sequence Number Overflow detection~~
4. ~~Piggybagging pending data on acknowledgements~~ (Not part of initial release)
5. ~~Implementation of conn interface~~ (Not part of initial release)
6. ~~Final overhaul (Doc and Code)~~
7. ~~Testing (native and hardware)~~
=> gnrc_tcp: initial implementation

cpu/lpc11u34/include/cpu_conf.h, drivers/include/periph/flashpage.h, tests/unittests/tests-flashpage/Makefile, tests/unittests/tests-flashpage/tests-flashpage.c, tests/unittests/tests-flashpage/tests-flashpage.h
Continuation of #5365 ~(on which this is also rebased).~
Added also some unittests for result validation.
=> drivers/flashrom: added addr-to-page function

Jenkinsfile
=> jenkins: move retry+timeout out of groovy into shell

boards/nucleo-l1/include/periph_conf.h
Small doxygen fix in nucleo-l1 periph_conf.
=> boards/nucleo-l1: fix non closed doxygen block

examples/iotivity_examples/client_switch/client_switch.c
As requested in:
https://github.com/RIOT-OS/RIOT/pull/6075#discussion_r96491505
Bug: https://github.com/RIOT-OS/RIOT/issues/6241
Change-Id: I6b2af5ab6b8bf20e848dcd30d580990006c950e7
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
=> pkg: iotivity: Hide put_light function if not needed

cpu/cortexm_common/cortexm_init.c, cpu/cortexm_common/include/vectors_cortexm.h, cpu/samd21/periph/gpio.c, cpu/samd21/periph/spi.c, cpu/samd21/vectors.c
This PR makes SAM R21 unittests compile with -pedantic.
=> cpu: samd21: misc compile fixes

drivers/pn532/pn532.c, tests/driver_pn532/Makefile, tests/driver_pn532/main.c, tests/driver_pn532/pn532_params.h
missed in #4780: driver needed adaption to SPI interface changes for its SPI mode.
=> drivers/pn532: adapted to SPI interface changes

drivers/pn532/pn532.c, tests/driver_pn532/Makefile, tests/driver_pn532/main.c, tests/driver_pn532/pn532_params.h
(not sure about labels / milestones regarding backports)
=> Backport #6478

cpu/cortexm_common/include/cpu.h
=> backport: cpu/cortexm: fixed cortexm_sleep()

drivers/include/periph/spi.h
2 typos found when reading SPI doc.
=> spi: doc typo

Makefile.dep, sys/Makefile, sys/include/net/icmpv6.h, sys/net/gnrc/pktdump/gnrc_pktdump.c, sys/net/network_layer/icmpv6/Makefile, sys/net/network_layer/icmpv6/icmpv6_hdr_print.c
print basic ICMPv6 header in packet dump
=> pktdump: add icmpv6 print

core/sched.c
=> core: fix osx compile issue

drivers/include/isl29125.h, drivers/isl29125/isl29125.c, tests/driver_isl29125/Makefile, tests/driver_isl29125/main.c
Adopted from #6118 because of inactivity.
=> isl29125: added interrupt

tests/pkg_libcoap/main.c
Seems I pushed the wrong file in #6536, so now the real change.
=> tests/pkg_libcoap: exchange printf with puts

sys/fmt/fmt.c, sys/include/fmt.h
=> fmt: add print_byte_hex() helper

tests/gnrc_ipv6_ext/README.md, tests/gnrc_ipv6_ext/tests/01-run.py
Debug output seems to be changed. This PR updates the README and the test script.
Fixes #6538.
=> tests/gnrc_ipv6_ext: update README.md

drivers/dht/dht.c, drivers/dht/include/dht_params.h, drivers/include/dht.h, sys/auto_init/auto_init.c, sys/auto_init/saul/auto_init_dht.c, tests/driver_dht/Makefile, tests/driver_dht/main.c
- unified auto-init to use same style as other SAUl devices
- make use of named return values
- added some asserts
Tested with DHT11 on a `stm32f3discovery`
=> drivers/dht: updated auto-init + some enhancements

Makefile.dep, sys/Makefile, sys/include/net/tcp.h, sys/net/gnrc/pktdump/gnrc_pktdump.c, sys/net/transport_layer/tcp/Makefile, sys/net/transport_layer/tcp/tcp_hdr_print.c
print basic TCP header in packet dump
=> sys: net: gnrc: pktdump: add tcp_hdr_print

tests/saul/main.c
the changes should speak for themselves :-)
=> tests/saul: added some more descriptive output

boards/msba2-common/tools/src/download.c, boards/msba2-common/tools/src/ihex.c, core/assert.c, cpu/lm4f120/periph/gpio.c, cpu/lpc2387/mci/lpc2387-mci.c, dist/tools/cppcheck/check.sh, sys/arduino/include/serialport.hpp
This PR adds .hpp to the list of file name patterns and fixes a few of the cppcheck warnings in master.
=> cppcheck fixes 1

sys/posix/sockets/posix_sockets.c
Apparently this was never built.
=> posix: missing closing parenthesis

drivers/cc110x/include/cc110x-netdev2.h, sys/auto_init/netif/auto_init_cc110x.c, sys/auto_init/netif/auto_init_netdev2_tap.c, sys/include/net/gnrc/conn.h, sys/include/net/gnrc/ipv6/netif.h
Unbelievable but true there are still some remnants from the early days of the NSTF.
=> net: cleanup ng_ remnants

sys/include/fmt.h
Adds some information to the API docs from the discussion at #6544
=> sys/fmt: Improve API documentation summary

doc/doxygen/riot.doxyfile, drivers/nrf24l01p/include/nrf24l01p_settings.h
- de-blacklisted nrf24l01p_settings.h from doxygen excludes
- fixed doc for that file
=> drivers/nrf24l01: removed doxgen warnings

drivers/include/saul.h, drivers/include/veml6070.h, drivers/veml6070/veml6070_saul.c, tests/driver_veml6070/Readme.md, tests/driver_veml6070/main.c
Since #6665 has already been merged, I open this to address the comments from @smlng.
=> drivers/veml6070: cleanup and improvements

sys/posix/sockets/posix_sockets.c
As reported on the [devel Mailinglist](https://lists.riot-os.org/pipermail/devel/2017-March/005047.html).
=> posix_sockets: fix assertion on close

drivers/Makefile.dep, drivers/Makefile.include, drivers/adxl345/Makefile, drivers/adxl345/adxl345.c, drivers/adxl345/adxl345_saul.c, drivers/adxl345/include/adxl345_params.h, drivers/adxl345/include/adxl345_regs.h, drivers/include/adxl345.h, sys/auto_init/auto_init.c, sys/auto_init/saul/auto_init_adxl345.c, tests/driver_adxl345/Makefile, tests/driver_adxl345/README.md, tests/driver_adxl345/main.c
Initial support for [ADXL345](http://www.analog.com/media/en/technical-documentation/data-sheets/ADXL345.pdf) accelerometer (I2C support only) + SAUL
=> drivers/adxl345: Initial support + saul

tests/xtimer_now64_continuity/Makefile, tests/xtimer_now64_continuity/README.md, tests/xtimer_now64_continuity/main.c
- adapt code to use public, typesafe API calls
- add some statistical output
- minor code enhancements and doc corrections
=> tests: enhance xtimer_now64_continuity

drivers/Makefile.dep, drivers/Makefile.include, drivers/feetech/Makefile, drivers/feetech/feetech.c, drivers/feetech/include/feetech_protocol.h, drivers/feetech/include/feetech_reader.h, drivers/feetech/include/feetech_writer.h, drivers/feetech/reader.c, drivers/feetech/writer.c, drivers/include/feetech.h, drivers/uart_half_duplex/Makefile, drivers/uart_half_duplex/include/uart_half_duplex.h, drivers/uart_half_duplex/uart_half_duplex.c, tests/driver_feetech/Makefile, tests/driver_feetech/README.md, tests/driver_feetech/main.c
Hello !
I'm adding a driver for feetech's scs15 servomotors.
I'm basing my work on [my previous C++ library](https://github.com/AversivePlusPlus/feetech).
This is currently a work in progress.
EDIT : 
[Here is](http://www.feetechrc.com/product/digital-servo/feetech-scservo-multi-purpose-uart-bus-robot-servo-for-arduino-diy/) the best source of information I can find on the motors .
=> drivers/feetech : initial support

drivers/include/mtd.h, sys/fs/constfs/constfs.c, sys/fs/devfs/devfs.c, sys/fs/doc.txt, sys/include/fs/constfs.h, sys/include/fs/devfs.h
There were some recent changes to the doxygen, that messed up the doc tree a little bit.
=> doc: fix doc hierarchy

cpu/native/include/mtd_native.h, cpu/native/mtd/mtd_native.c
=> doc: fix grouping of mtd_native

drivers/at86rf2xx/at86rf2xx_netdev.c, drivers/netdev_ieee802154/netdev_ieee802154.c
Found using Clang static analyzer (make scan-build) with examples/gnrc_networking on mulle.
=> net: Fix two minor return value issues

cpu/sam0_common/include/periph_cpu_common.h
Fix SAML SPI issue described in #6686
=> SAML: Fix SPI SERCOM ID calculation 

cpu/k60/Makefile.include, cpu/k64f/Makefile.include, cpu/kw2x/Makefile.include
These are already provided by cortexm_common
=> kinetis: Remove duplicate CPU_MODEL CFLAGS definition

boards/nucleo-l1/Makefile.features, boards/nucleo-l1/include/periph_conf.h, cpu/stm32l1/include/periph_cpu.h, cpu/stm32l1/periph/adc.c, tests/unittests/Makefile
This PR contains the split required by @kYc0o in #6081.
I just want to make things to go faster.
=> stm32l1: add adc & dac support, update configuration for nucleo-l1

cpu/native/startup.c
The startup function is a constructor, which means that it will be called somewhere among any other constructors in the application. This includes the constructor calls for C++ global objects. But because startup actually calls the main application code, any constructor listed after startup in the initalization order will never be called.
This PR adds a loop for iterating over the remaining constructors before calling native_cpu_init. This location is similar to where C++ global constructors are called on Cortex-M. This also means that constructors are called before there is any threading, IPC, or other system facilities, so don't put application logic in global constructors! This is just C++ common sense/best practice, but it is worth mentioning anyway.
This fixes an issue discovered in …
=> native: Finish iterating constructor calls before moving on to native_cpu_init

drivers/adxl345/adxl345.c, drivers/adxl345/include/adxl345_params.h, drivers/include/adxl345.h, tests/driver_adxl345/main.c
@haukepetersen If you have some time, could you take a look at it please ?
I need some advises about the set state functions. I have to add a clear_state function for each mode. But I don't know how could I put it into one clear and efficient function.
=> drivers/adxl345: cleanup/enhancements

doc/doxygen/.gitignore, doc/doxygen/Makefile, doc/doxygen/src/css/riot.css, doc/doxygen/src/css/riot.less
See https://github.com/RIOT-OS/RIOT/pull/6878#issuecomment-293859915
=> doc: add build capacities for LESS

sys/net/gnrc/network_layer/icmpv6/gnrc_icmpv6.c
=> net, icmpv6: correct debug output

sys/posix/sockets/posix_sockets.c
=> [backport] sys, posix: fix cppcheck warnings and errors in posix_socket

cpu/mips_pic32_common/periph/gpio.c, sys/posix/sockets/posix_sockets.c, sys/xtimer/xtimer_core.c
Patches created by badzero.cocci. (See #6946)
=> some (ptr == 0) -> (ptr == NULL) fixes (found by coccinelle)

doc/doxygen/src/css/riot.css, doc/doxygen/src/css/riot.less
=> doc: fix spacing in parameter description

boards/remote-reva/include/board.h, boards/remote-revb/include/board.h
=> [backport] boards/remote: fix led macro

sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c
some enhancements to TCP FSM and its handling of the TCB list
=> gnrc_tcp: optimize and cleanup operations on TCB list

Makefile.dep, sys/net/routing/nhdp/nhdp.c
Still one dependency left for `conn`.
=> nhdp: port to sock

tests/unittests/tests-mtd/tests-mtd.c
This is the port of #6990 for 2017.04
=> unittests/tests-mtd: disable AND flash test with dummy flash (2017.04 port)

cpu/cortexm_common/include/cpu.h, cpu/nrf5x_common/periph/hwrng.c
quick one: the changed name for this function is better in line with the main sleep function...
=> cpu/cortexm: s/cpu_sleep_until_.../cortexm_sle.../

release-notes.txt
PR updates release notes for 2017.04.
=> RELEASE 2017.04

boards/mulle/include/board.h
No need to perform read-modify-write cycles through bitbanding on the GPIO set/clear/toggle registers.
=> mulle: Streamline LED macros

dist/tools/ci/build_and_test.sh, dist/tools/ci/changed_files.sh, dist/tools/cppcheck/check.sh, dist/tools/externc/check.sh, dist/tools/licenses/check.sh
There was a lot of hacky, duplicated shell code. This PR removes the duplication by sourcing common a common file.
=> dist: tools: factor out changed files collection in check scripts

tests/msg_avail/Makefile, tests/msg_avail/main.c, tests/msg_avail/tests/01-run.py
- rename `thread_msg_avail` to `msg_avail`, does not require threads
- minor code enhancements and corrections
=> tests: enhance msg_avail

dist/tools/toolchains/build_gnuarm.sh
some md5 command line is different into some OS
=> use MD5 as environment variable

boards/calliope-mini/Makefile.include, boards/microbit/Makefile.include
this makes these two boards consistent with all other boards supporting multiple flash tools...
=> boards: s/FLASHTOOL/PROGRAMMER/

sys/posix/sockets/posix_sockets.c
This fixes Issue #7054.
@immesys
=> posix_sockets: Fix use of fd_new

boards/arduino-zero/Makefile.include, boards/samd21-xpro/Makefile.include, boards/saml21-xpro/Makefile.include, boards/samr21-xpro/Makefile.include, boards/sodaq-autonomo/Makefile.include, makefiles/boards/sam0.inc.mk
This PR removes ~20 duplicated lines across 4 boards.
Please help testing:
=> boards: sam0: deduplicate sam0 board makefiles

sys/shell/commands/sc_vfs.c
Calls to vfs_closedir were missing at the end of _ls_handler causing umount
ro return an error.
=> sc_vfs: fix _ls_handler

sys/include/net/gcoap.h, sys/net/application_layer/coap/gcoap.c
the title should speak for itself...
=> net/gcoap: make input parameters const

sys/shell/commands/sc_ccnl.c
improves on #7022 and fixes a possible undefined  behavior: `buf` is declared within the `if` statement but used outside through `body = buf`. Further, using `pos` instead of `buf_prt` is more intuitive when working with char array anyway.
=> shell: fix _ccnl_content command

dist/tools/coccinelle/README.md
This PR adds a README.md explaining some aspects of the CI's Coccinelle integration.
=> dist: tools: coccinelle: add documentation

tests/xtimer_msg_receive_timeout/README.md, tests/xtimer_msg_receive_timeout/main.c, tests/xtimer_msg_receive_timeout/tests/01-run.py
- correct test period from 100ms to 1000ms, to match description
- moved description to separate README.md
- changed timer message type from 44 to 42, for nerdiness
- minor code enhancements
=> tests: enhance xtimer_msg_receive_timeout

Makefile.dep, drivers/at86rf2xx/at86rf2xx_netdev.c, drivers/include/net/netdev.h, makefiles/pseudomodules.inc.mk, pkg/openthread/Makefile, pkg/openthread/Makefile.include, pkg/openthread/contrib/Makefile, pkg/openthread/contrib/netdev/Makefile, pkg/openthread/contrib/netdev/openthread_netdev.c, pkg/openthread/contrib/openthread.c, pkg/openthread/contrib/platform_alarm.c, pkg/openthread/contrib/platform_diag.c, pkg/openthread/contrib/platform_functions_wrapper.c, pkg/openthread/contrib/platform_logging.c, pkg/openthread/contrib/platform_misc.c, pkg/openthread/contrib/platform_radio.c, pkg/openthread/contrib/platform_random.c, pkg/openthread/contrib/platform_settings.c, pkg/openthread/contrib/platform_uart.c, pkg/openthread/include/ot.h, sys/auto_init/auto_init.c, tests/openthread/Makefile, tests/openthread/README.md, tests/openthread/main.c
This is the OpenThread core from #5552 . I'm spliting #5552 into multiple PR for an easier review.
After merging this one, I can push the sock adoption.
Cheers!
=> pkg/openthread:  core and tests

boards/pic32-clicker/clicker.c, boards/pic32-clicker/include/board.h
Signed-off-by: Francois Berder <fberder@outlook.fr>
=> boards: pic32-clicker: Add LEDs support

boards/pic32-wifire/include/board.h, boards/pic32-wifire/wifire.c
Signed-off-by: Francois Berder <fberder@outlook.fr>
=> boards: pic32-wifire: Add LEDs support

boards/samd21-xpro/Makefile.features, boards/saml21-xpro/Makefile.features, boards/samr21-xpro/Makefile.features, cpu/sam0_common/include/cpu_conf.h, cpu/sam0_common/periph/flashpage.c
~~rebased on #5365~~
for some reason I did not get it to work on the `samr21-xpro`, so marked it as WIP...
=> cpu/samd21: added flashpage driver implementation

cpu/sam0_common/periph/adc.c
Fix add resolution assert.  See issue [#7100](https://github.com/RIOT-OS/RIOT/issues/7100)
=> sam0/adc: assert resolution check fix

sys/include/net/gnrc/rpl.h, sys/include/trickle.h, sys/net/gnrc/routing/rpl/gnrc_rpl.c, sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c, sys/shell/commands/sc_gnrc_rpl.c, sys/trickle/trickle.c, tests/trickle/Makefile, tests/trickle/main.c
This PR enhances our trickle module by removing one of the two timers / messages. Furthermore, RPL is adjusted to the trickle enhancements and a test application for trickle is provided.
=> trickle: enhancements

sys/xtimer/xtimer_core.c
=> xtimer: Use {} for empty while loops

drivers/at86rf2xx/at86rf2xx_getset.c, drivers/at86rf2xx/at86rf2xx_internal.c, drivers/cc110x/cc110x-rxtx.c, drivers/dht/dht.c, drivers/enc28j60/enc28j60.c, drivers/encx24j600/encx24j600.c
flollow up on #7169, fixing all while loops `drivers/*`
=> drivers: coding style, use {} for empty while loops

sys/include/net/gnrc/ipv6/nib/conf.h, sys/include/net/gnrc/ipv6/nib/nc.h
Looks like we missed the renaming of the NIB in one or two places.
=> doc: nib: neighbor information base everywhere you look

drivers/bmp180/Makefile, drivers/bmp180/bmp180.c, drivers/bmp180/bmp180_saul.c, drivers/bmp180/include/bmp180_params.h, drivers/include/bmp180.h, sys/auto_init/saul/auto_init_bmp180.c, tests/driver_bmp180/Makefile, tests/driver_bmp180/main.c
This PR does some cleanup and refactoring in bmp180 driver implementation and saul support.
=> drivers/bmp180: implementation refactoring and cleanup

boards/pba-d-01-kw2x/Makefile.dep, drivers/Makefile.include, drivers/include/tmp006.h, drivers/tmp006/include/tmp006_params.h, drivers/tmp006/include/tmp006_regs.h, drivers/tmp006/tmp006.c, drivers/tmp006/tmp006_saul.c, sys/auto_init/auto_init.c, sys/auto_init/saul/auto_init_tmp006.c, tests/driver_tmp006/Makefile, tests/driver_tmp006/main.c
- rework general implementation of tmp006
- adapt driver test accordingly
- add support for saul
this concludes the effort of full SAUL support for board `pba-d-01-kw2x` see #7152
=> driver: tmp006 rework

Makefile.dep, sys/evtimer/Makefile, sys/evtimer/evtimer.c, sys/include/div.h, sys/include/evtimer.h, sys/include/evtimer_msg.h, tests/evtimer_msg/Makefile, tests/evtimer_msg/main.c, tests/evtimer_msg/tests/01-run.py, tests/evtimer_underflow/Makefile, tests/evtimer_underflow/main.c, tests/evtimer_underflow/tests/01-run.py
Extends #5999 by doc, some helpers for message-based events and a test. Also rebases it to current master.
=> evtimer: initial import

cpu/sam0_common/periph/i2c.c, cpu/samd21/periph/rtc.c, cpu/saml21/periph/rtc.c
Change my email address:
<baptiste.clenet@xsoen.com>
to
<bapclenet@gmail.com>
=> Change my email address - biboc

sys/include/net/gnrc/mac/internal.h, sys/include/net/gnrc/mac/types.h, sys/net/gnrc/link_layer/gnrc_mac/internal.c
This PR intends to update/correct the coding style of `gnrc_mac` module
=> gnrc_mac: update coding style.

sys/include/net/gnrc/priority_pktqueue.h, sys/net/gnrc/priority_pktqueue/priority_pktqueue.c
This PR intends to update/correct the coding style of the `gnrc_priority_pktqueue` module
=> gnrc_priority_pktqueue: updated coding style.

boards/nz32-sc151/Makefile, boards/nz32-sc151/Makefile.dep, boards/nz32-sc151/Makefile.features, boards/nz32-sc151/Makefile.include, boards/nz32-sc151/board.c, boards/nz32-sc151/include/board.h, boards/nz32-sc151/include/gpio_params.h, boards/nz32-sc151/include/periph_conf.h, tests/unittests/Makefile
This PR supersedes #6081 and is based on ~~#6819~~ (merged).
=> boards/nz32-sc151: add initial support

boards/arduino-due/include/periph_conf.h
unified the look of the file...
=> boards/arduino-due: style cleanup in periph_conf.h

tests/gnrc_udp/Makefile, tests/gnrc_udp/README.md, tests/gnrc_udp/main.c, tests/gnrc_udp/udp.c
This PR adds a test to allow for testing of [release specs 6](https://github.com/RIOT-OS/Release-Specs/blob/master/06-single-hop-udp/06-single-hop-udp.md)
=> tests: add application for release specs 6

drivers/adcxx1c/adcxx1c_saul.c, drivers/adxl345/adxl345_saul.c, drivers/bmp180/bmp180_saul.c, drivers/bmx280/bmx280_saul.c, drivers/dht/dht_saul.c, drivers/hdc1000/hdc1000_saul.c, drivers/include/saul.h, drivers/io1_xplained/io1_xplained_saul.c, drivers/isl29020/isl29020_saul.c, drivers/jc42/jc42_saul.c, drivers/l3g4200d/l3g4200d_saul.c, drivers/lis3dh/lis3dh_saul.c, drivers/lps331ap/lps331ap_saul.c, drivers/lsm303dlhc/lsm303dlhc_saul.c, drivers/lsm6dsl/lsm6dsl_saul.c, drivers/mag3110/mag3110_saul.c, drivers/mma8x5x/mma8x5x_saul.c, drivers/saul/adc_saul.c, drivers/saul/gpio_saul.c, drivers/saul/saul.c, drivers/saul/saul_str.c, drivers/si70xx/si70xx_saul.c, drivers/tcs37727/tcs37727_saul.c, drivers/tmp006/tmp006_saul.c, drivers/tsl2561/tsl2561_saul.c, drivers/veml6070/veml6070_saul.c
follow up on #7213, #7243, and #7244
=> saul: use const for device parameter

drivers/dht/include/dht_params.h, drivers/include/dht.h, sys/auto_init/saul/auto_init_dht.c
Cleanup in DHT implementation and saul adaption (as discussed in #7257)
=> drivers/dht: some cleanup

boards/pba-d-01-kw2x/Makefile.dep, drivers/include/mpl3115a2.h, drivers/mpl3115a2/include/mpl3115a2_params.h, drivers/mpl3115a2/mpl3115a2.c, drivers/mpl3115a2/mpl3115a2_saul.c, sys/auto_init/auto_init.c, sys/auto_init/saul/auto_init_mpl3115a2.c, tests/driver_mpl3115a2/Makefile, tests/driver_mpl3115a2/README.md, tests/driver_mpl3115a2/main.c
- rework driver interface
- adapt test
- add saul support -> i.e., for pba-d-01-kw2x
=> drivers/mpl3115a2: rework

examples/saul/Makefile
Application name was copy-pasta'd for this application
=> examples: fix name of saul application

drivers/bmp180/include/bmp180_internals.h
Another doxygen issue with sensor drivers...
=> drivers/bmp180: fix doxygen brief documentation

drivers/include/adcxx1c.h, drivers/include/bmp180.h, drivers/include/bmx280.h, drivers/include/cc110x.h, drivers/include/cc2420.h, drivers/include/io1_xplained.h, drivers/include/led.h, drivers/include/mpu9150.h, drivers/include/sht11.h, drivers/include/si70xx.h, drivers/include/srf02.h, drivers/include/sx127x.h, drivers/include/tsl2561.h, drivers/include/veml6070.h, drivers/include/w5100.h, drivers/io1_xplained/include/io1_xplained_internals.h
This PR is another very small step toward fully documented drivers.
At least, it gives consistent brief description in the drivers modules page. I also added more detailed doc with the sensor I know best.
It will be a lot of work if we want to reach a good level of documentation there...
=> drivers: doxygen documentation improvement

dist/tools/edbg/Makefile
=> [backport] tools, edbg: fix compiler issue on macos

drivers/xbee/xbee.c
=> xbee: provide NETOPT_PROTO [2017.07 backport]

release-notes.txt
This is the Release 2017.07: backport from 2017.07-branch.
=> RELEASE 2017.07 [Backport]

release-notes.txt
This is the official release 2017.07.
=> RELEASE 2017.07

boards/frdm-k64f/include/periph_conf.h, boards/mulle/include/periph_conf.h, boards/pba-d-01-kw2x/include/periph_conf.h
Just a cosmetic change to unify the board configurations a little bit and make things look nicer.
=> boards/kinetis-based: beautify ADC configuration

.gitignore
I'm using Visual Studio Code editor and it creates a .vscode directory with user settings. This PR make this directory ignored from git status.
=> ignore vscode user settings from git status

cpu/k22f/include/cpu_conf.h, cpu/k60/include/cpu_conf.h, cpu/k64f/include/cpu_conf.h, cpu/kinetis_common/include/cpu_conf_kinetis.h, cpu/kw2xd/include/cpu_conf.h
Another code deduplication PR.
This PR merges the settings which are common for all currently supported Kinetis CPUs into a single cpu_conf_kinetis.h file.
Based on #7395
=> kinetis: Merge cpu_conf settings into kinetis_common

cpu/atmega_common/periph/timer.c, cpu/cc2538/periph/timer.c, cpu/cc26x0/periph/timer.c, cpu/cc430/periph/timer.c, cpu/ezr32wg/periph/timer.c, cpu/kinetis_common/include/periph_cpu.h, cpu/lm4f120/periph/timer.c, cpu/lpc11u34/periph/timer.c, cpu/lpc1768/periph/timer.c, cpu/lpc2387/periph/timer.c, cpu/mips_pic32_common/include/periph_cpu_common.h, cpu/msp430fxyz/periph/timer.c, cpu/native/include/periph_cpu.h, cpu/nrf5x_common/periph/timer.c, cpu/sam3/periph/timer.c, cpu/samd21/periph/timer.c, cpu/saml21/periph/timer.c, cpu/stm32_common/periph/timer.c, drivers/periph_common/timer.c
how about a little less code duplication?! here we go.
=> cpu: add and use shared code for timer_set()

cpu/stm32f1/periph/rtt.c
This code is currently even compiling for some optimization flags.
=> stm32f1: rtt: declare functions static

boards/frdm-k22f/include/periph_conf.h, boards/frdm-k64f/include/periph_conf.h, boards/mulle/include/periph_conf.h, boards/pba-d-01-kw2x/include/periph_conf.h, cpu/kinetis_common/doc.txt
Some left overs after a driver refactor.
=> kinetis: Remove unused configuration items

core/kernel_init.c, core/msg.c, core/mutex.c
PR removes duplicate includes...
=> core: remove redundant includes

drivers/at86rf2xx/at86rf2xx.c, drivers/at86rf2xx/at86rf2xx_getset.c, drivers/at86rf2xx/at86rf2xx_internal.c, drivers/at86rf2xx/at86rf2xx_netdev.c, drivers/at86rf2xx/include/at86rf2xx_internal.h, drivers/include/at86rf2xx.h
This PR reorganizes #5971 that I did with @immesys.  
I think it was about to be merged and the reviewer was @OlegHahm. 
The following figure may be useful for review
=> at86rf2xx: reliable radio state change

pkg/minmea/Makefile
description: see title 😉 
@kaspar030 should resolve issues discussed via mail.
=> pkg, minmea: update URL and version

dist/tools/ethos/ethos.c
Significantly improves throughput and latency on FRDM-KW41Z.
Ping against fe80::2 (ethos interface link local address) with a packet of size 100 yields a 30 ms roundtrip with this patch, 177 ms without. Size 1000 ping before: 1160 ms, after: 188 ms
=> dist/tools/ethos: Build escaped packet in buffer before writing to UART

boards/cc2650stk/include/periph_conf.h, cpu/cc26x0/include/periph_cpu.h
see discussion in #7335
Updates timer configuration documentation for CC26x0 and copy-pasta to the boards timer config.
=> docu: enhance timer config docu for cc26x0

boards/airfy-beacon/include/board.h, boards/b-l072z-lrwan1/include/board.h, boards/calliope-mini/include/board.h, boards/chronos/include/board.h, boards/microbit/include/board.h, boards/msb-430-common/include/board_common.h, boards/nrf51dongle/include/board.h, boards/nucleo-f401/include/board.h, boards/nucleo-f410/include/board.h, boards/nucleo-f411/include/board.h, boards/nucleo-f446/include/board.h, boards/nucleo-l053/include/board.h, boards/nucleo-l073/include/board.h, boards/nucleo-l152/include/board.h, boards/nucleo144-f303/include/board.h, boards/nucleo144-f412/include/board.h, boards/nucleo144-f413/include/board.h, boards/nucleo144-f429/include/board.h, boards/nucleo144-f446/include/board.h, boards/pca10000/include/board.h, boards/pca10005/include/board.h, boards/stm32f4discovery/include/board.h, boards/telosb/include/board.h, boards/wsn430-common/include/board_common.h, boards/yunjia-nrf51822/include/board.h, boards/z1/include/board.h
=> boards: use default value for XTIMER_DEV and _CHAN

boards/nrf52840dk/include/periph_conf.h, boards/nrf52dk/include/periph_conf.h, cpu/nrf52/include/periph_cpu.h
=> cpu/nrf52: share const CLOCK_CORECLOCK

sys/shell/commands/sc_vfs.c
Add write command to vfs shell commands.
It can write an ascii string or a hex string to a file.
=> sc_vfs: add write command

cpu/sam0_common/periph/uart.c
fixes #7546
The driver is still some steps for ideal, but for now the UARTs should work again. Will do more cleanup once I have access to my saml21-xpro...
Verified working on the `samr21-xpro`.
=> cpu/sam0_common: fixed UART for samd21

cpu/mips32r2_common/include/cpu.h, cpu/mips32r2_common/include/cpu_conf.h, cpu/mips32r2_common/include/eic_irq.h, cpu/mips_pic32_common/doc.txt, cpu/mips_pic32_common/include/periph_cpu_common.h, cpu/mips_pic32mx/include/cpu.h, cpu/mips_pic32mx/include/cpu_conf.h, cpu/mips_pic32mz/include/cpu.h, cpu/mips_pic32mz/include/cpu_conf.h, cpu/msp430_common/include/cpu.h, cpu/msp430_common/include/cpu_conf.h, cpu/msp430_common/include/msp430_types.h, cpu/msp430_common/include/stdio.h, cpu/msp430_common/include/stdlib.h, cpu/msp430_common/include/sys/stat.h, cpu/msp430_common/include/unistd.h
Another pass of cleanup of doxygen documentation grouping in the cpu modules:
* remaining issue with MIPS
* msp430
=> cpu: doxygen cleanup

cpu/atmega328p/include/periph_cpu.h, cpu/atmega_common/thread_arch.c
=> Atmega fix typo and empty space

drivers/Makefile.dep, drivers/Makefile.include, drivers/apa102/Makefile, drivers/apa102/apa102.c, drivers/apa102/include/apa102_params.h, drivers/include/apa102.h, sys/include/color.h, tests/driver_apa102/Makefile, tests/driver_apa102/README.md, tests/driver_apa102/main.c
Did not work when tested this morning, will look into this when back in the office...
=> drivers: add driver for apa102 RGB LEDs

boards/cc2538dk/Makefile.dep, boards/native/Makefile.dep, boards/openmote-cc2538/Makefile.dep, boards/remote-common/Makefile.dep, drivers/Makefile.include, pkg/jerryscript/Makefile.dep, pkg/libcoap/Makefile.dep, sys/Makefile.include, sys/log/Makefile.include
=> make: fix indentation to 2 spaces in several places

boards/arduino-atmega-common/include/periph_conf.h, boards/waspmote-pro/include/periph_conf.h, cpu/atmega1281/include/periph_cpu.h, cpu/atmega2560/include/periph_cpu.h, cpu/atmega328p/include/periph_cpu.h, cpu/atmega_common/include/atmega_regs_common.h, cpu/atmega_common/periph/i2c.c, cpu/atmega_common/periph/spi.c
=> cpu/atmega: use power.h defines instead of direct register access

pkg/lwip/Makefile
See http://savannah.nongnu.org/forum/forum.php?forum_id=8953
Tests fail, but this seems to be the case in master as well. If I find the time I'll look into it and rebase this PR on top of the fix.
=> lwip: Update to v2.0.3

sys/fmt/fmt.c
=> fmt: Remove unused pwr function

boards/arduino-mkr-common/include/periph_conf.h, boards/arduino-zero/include/periph_conf.h, boards/samd21-xpro/include/periph_conf.h, boards/saml21-xpro/include/periph_conf.h, boards/samr21-xpro/include/periph_conf.h, boards/sodaq-autonomo/include/periph_conf.h, cpu/sam0_common/include/periph_cpu_common.h, cpu/sam0_common/periph/uart.c
Adding option for USART to wake from sleep.
=> cpu/sam0/periph/uart - wake from sleep on receive line

core/include/sched.h, core/sched.c, sys/ps/ps.c, tests/ps_schedstatistics/main.c
=> schedstats: revert to 32Bit, and enhance output of schedstats

core/include/arch/thread_arch.h
=> correct print_stack macro

tests/unittests/tests-gnrc_ipv6_nib/tests-gnrc_ipv6_nib-pl.c
We missed a spot, #6988 was already merged before #7222.
=> tests: unittests: actually do TODO in NIB-PL tests

cpu/stm32f4/vectors.c
=> cpu/stm32f4: optimized isr vector definitions

cpu/stm32f7/vectors.c
=> cpu/stm32f7: optimized isr vector definitions

cpu/stm32f0/vectors.c
=> cpu/stm32f0: optimized isr vector definitions

sys/random/xorshift.c
~~Waiting for #7544.~~
See https://en.wikipedia.org/wiki/Xorshift.
=> sys: random: add xorshift prng

sys/auto_init/netif/auto_init_netdev_tap.c, sys/shell/commands/Makefile, sys/shell/commands/sc_gnrc_netif2.c, sys/shell/commands/shell_commands.c
Does what it says on the bin (+ port auto_init_netdev_tap non-intrusively for testing).
~~Depends on #7370.~~
This PR is part of the network layer remodelling effort:
=> shell_commands: port ifconfig command for gnrc_netif2

cpu/nrf5x_common/radio/nrfmin/nrfmin_gnrc.c, sys/include/net/gnrc/netif2.h, sys/include/net/gnrc/netif2/ethernet.h, sys/net/gnrc/netif2/gnrc_netif2.c, tests/gnrc_netif2/main.c
Wishes made offline by @kaspar030 to #7410.
=> gnrc_netif2: make gnrc_netif2_create idempotent and crash on error

cpu/stm32l0/vectors.c
=> cpu/stm32l0: optimized isr vector definitions

cpu/stm32f1/vectors.c
=> cpu/stm32f1: optimized isr vector definitions

LOSTANDFOUND.md
=> lostandfound: fix some typos / wording

boards/msba2-common/board_common_init.c, boards/msba2-common/tools/src/pseudoterm.c, boards/msba2/board_init.c, cpu/arm7_common/arm_cpu.c, cpu/cc2538/periph/pm.c, cpu/cortexm_common/ldscripts/multislot.ld, cpu/cortexm_common/periph/pm.c, examples/default/main.c, sys/include/auto_init.h, sys/include/shell_commands.h, tests/lwmac/main.c
This PR fixes some occurences of my copyright or authorship.
=> all: fix my email address

cpu/cc26x0/include/periph_cpu.h, cpu/cc26x0/periph/pm.c
=> [backport] cpu, cc26x0: fix pm, don't go into cortexm_sleep(0)

tests/bitarithm_timings/Makefile, tests/bitarithm_timings/tests/01-run.py, tests/bloom_bytes/Makefile, tests/bloom_bytes/tests/01-run.py, tests/buttons/Makefile, tests/buttons/tests/01-run.py, tests/cpp11_condition_variable/Makefile, tests/cpp11_condition_variable/tests/01-run.py, tests/cpp11_mutex/Makefile, tests/cpp11_mutex/tests/01-run.py, tests/cpp11_thread/Makefile, tests/cpp11_thread/tests/01-run.py
=> [backport] tests: added some more pexpect scripts

drivers/ds1307/ds1307.c, tests/driver_ds1307/tests/01-run.py
It hints at to an unconnected devices ;-)
=>  ds1307: return error when nothing is read or written on initialization

makefiles/tools/serial.inc.mk
backport of #7758 and it's fix #7789
=> [backport] add var for selecting terminal prog

drivers/ds1307/ds1307.c, tests/driver_ds1307/tests/01-run.py
=> ds1307: return error when nothing is read or written on initialization [2017.10 backport]

pkg/fatfs/fatfs_diskio/native/native_diskio.c
Fixes #7795.
To verify run the following from tests/pkg_fatfs:
```
dd if=/dev/zero of=riot_fatfs_disk.img bs=1M count=128
make && make term
mkfs 0 fat
mount 0
touch testfile
ls
<various combinations of read and write if you like>
```
Keep in mind the exfat option of mkfs wont work if not enabled explicitly at compile time.
What the fix actually does: there was a missing include, that lead to `#if (_USE_MKFS == 1)` never beeing true. Also I added some debug messages that would have helped to find the error.
=> pkg/fatfs: fix mkfs on native

pkg/fatfs/fatfs_diskio/native/native_diskio.c
Backport for already merged *pkg/fatfs: fix mkfs on native #7797*
=> pkg/fatfs: fix missing includes and disk_ioctl function in native diskio [2017.10 backport]

tests/xtimer_hang/Makefile, tests/xtimer_hang/tests/01-run.py, tests/xtimer_now64_continuity/Makefile, tests/xtimer_now64_continuity/tests/01-run.py, tests/xtimer_periodic_wakeup/Makefile, tests/xtimer_periodic_wakeup/tests/01-run.py, tests/xtimer_remove/Makefile, tests/xtimer_remove/tests/01-run.py, tests/xtimer_reset/Makefile, tests/xtimer_reset/tests/01-run.py
=> [backport] tests/xtimer_x: added pexpect scripts

tests/float/Makefile, tests/float/README.md, tests/float/main.c, tests/float/tests/01-run.py
=> tests/float: automated test and added pexpect script

tests/float/Makefile, tests/float/README.md, tests/float/main.c, tests/float/tests/01-run.py
=> [backport] tests/float: automated test and added pexpect script

tests/xtimer_hang/tests/01-run.py
=> test/xtimer_hang: accept 10% timing deviations

tests/thread_flood/Makefile, tests/thread_flood/main.c, tests/thread_flood/tests/01-run.py, tests/thread_flood/tests/test_thread.py
=> [backport] tests/thread_flood: improve test output

tests/unittests/tests/01-run.py
=> [backport] test/unittests: set pexpect timeout to 60s

sys/trickle/trickle.c
=> trickle: correctly reset t [2017.10 backport]

release-notes.txt
Backport of the release notes + some end-of-line-space-char fixes.
=> [backport] Release notes of 2017.10

boards/mulle/include/periph_conf.h
=> mulle: Update RTT config to match other Kinetis boards

Makefile.dep, sys/auto_init/netif/auto_init_at86rf2xx.c, sys/include/net/gnrc/lwmac/hdr.h, sys/include/net/gnrc/lwmac/lwmac.h, sys/include/net/gnrc/lwmac/timeout.h, sys/include/net/gnrc/lwmac/types.h, sys/include/net/gnrc/mac/internal.h, sys/include/net/gnrc/netif2/mac.h, sys/net/gnrc/link_layer/lwmac/include/lwmac_internal.h, sys/net/gnrc/link_layer/lwmac/include/rx_state_machine.h, sys/net/gnrc/link_layer/lwmac/include/tx_state_machine.h, sys/net/gnrc/link_layer/lwmac/lwmac.c, sys/net/gnrc/link_layer/lwmac/lwmac_internal.c, sys/net/gnrc/link_layer/lwmac/rx_state_machine.c, sys/net/gnrc/link_layer/lwmac/timeout.c, sys/net/gnrc/link_layer/lwmac/tx_state_machine.c, sys/net/gnrc/netif2/gnrc_netif2_ieee802154.c
Port LwMAC protocol to netif2.
=> gnrc_lwmac: port to gnrc_netif2

pkg/umorse/Makefile, pkg/umorse/Makefile.include, pkg/umorse/Makefile.umorse, pkg/umorse/doc.txt, tests/pkg_umorse/Makefile, tests/pkg_umorse/README.md, tests/pkg_umorse/main.c, tests/pkg_umorse/tests/01-run.py
this PR adds a package for Morse encoding and output.
It contains the initial package support, plus a test application which also shows main uMorse features. It also provides a script for test automation.
=> pkg: add uMorse

drivers/Makefile.dep, drivers/Makefile.include, drivers/include/si70xx.h, drivers/si70xx/Makefile, drivers/si70xx/include/si70xx_internals.h, drivers/si70xx/include/si70xx_params.h, drivers/si70xx/si70xx.c, makefiles/pseudomodules.inc.mk, sys/auto_init/saul/auto_init_si70xx.c, tests/driver_si70xx/Makefile, tests/driver_si70xx/README.md, tests/driver_si70xx/main.c
While working on the drivers documentation improvements (#7295), I noticed that this one could be cleaned up.
=> drivers/si70xx: cleanup and use pseudomodules

pkg/openthread/contrib/platform_radio.c
I really appreciate the openthread port #7082, which is @jia200x's job. 
I'm building on #7082 now and this PR deals with one of some issues in #7082 . 
OpenThread uses RSSI [dBm] as the link quality indicator, but the current OpenThread port does not provide a correct RSSI value. This PR provides RSSI for openthread and it supports SAMR21.
=> [OpenThread] report RSSI for openthread

cpu/sam0_common/periph/adc.c, cpu/sam0_common/periph/i2c.c, cpu/sam0_common/periph/uart.c, cpu/sam3/periph/pwm.c, cpu/samd21/periph/pwm.c, cpu/samd21/periph/rtc.c, cpu/samd21/periph/rtt.c, cpu/saml21/periph/rtc.c
=> cpu/samX: remove guards from periph drivers

examples/javascript/Makefile
Reverts RIOT-OS/RIOT#7953.
The problem that caused that PR is resolved.
=> Revert "examples: only whitelist a few essential boards (dirty hack)"

LOSTANDFOUND.md
finishing up #7979
EDIT
~~Needs adaption with correct commit hashes after #7979 was merged.~~
=> lostandfound: added pca10000 and pca10005

sys/include/net/ipv6/hdr.h
=> net/ipv6/hdr: fix issue #5944

tests/thread_cooperation/Makefile, tests/thread_cooperation/main.c, tests/thread_cooperation/tests/01-run.py
PR updates thread_cooperation test output, fixed list of boards with insufficient memory and adapts parameter for boards if possible.
Further it adds a testrunner script for test automation.
=> tests: enhance thread cooperation

tests/irq/Makefile, tests/irq/main.c, tests/irq/tests/01-run.py
=> tests/irq: migrate to testrunner

dist/tools/testrunner/testrunner.py
Always having to activate `traceback=True` to debug a test sucks and having the traceback always printed sucks as well so I came up with this. Now the testrunner prints the line information just about the failed expect (but traceback can still be added in case that info is not enough).
I basically just get the last frame that isn't in the `pexpect` module from the traceback and print its information (with some path magic to get a path relative to `RIOTPATH`).
=> testrunner: show information about failed line (even without traceback)

tests/periph_timer/main.c
In my timer driver implementation I forgot to pass `arg` to `timer_isr_ctx_t`. I noticed this when experimenting with #7919.
This PR modifies the `periph_timer` test to actually check if the argument is passed-on. I use an unique combination of cookie value + timer number + channel number to actually make sure that the right timer and channel fired (the cookie should prevent comparing to (un)initialized memory).
=> test: periph_timer: check if argument is passed.

LOSTANDFOUND.md
Documenting #8042
Waiting for #8042 to be merged so the correct commit hashes can be added.
=> lostandfound: add x86 and qemu-i386

sys/net/gnrc/link_layer/lwmac/lwmac.c, sys/net/gnrc/link_layer/lwmac/tx_state_machine.c
Another issue that popped up in #7925.
(See [this travis](https://travis-ci.org/RIOT-OS/RIOT/builds/303031686?utm_source=github_status&utm_medium=notification) build for reference)
=> gnrc_lwmac: fix issues reported by cppcheck

drivers/Makefile.dep, drivers/Makefile.include, drivers/hts221/Makefile, drivers/hts221/hts221.c, drivers/hts221/hts221_saul.c, drivers/hts221/include/hts221_params.h, drivers/hts221/include/hts221_regs.h, drivers/include/hts221.h, sys/auto_init/auto_init.c, sys/auto_init/saul/auto_init_hts221.c, tests/driver_hts221/Makefile, tests/driver_hts221/main.c
initial driver implementation, this module can be found on X-NUCLEO extension shield IKS01A2.
Currently WIP, most functions are implemented including support for one-shot and continuous measurements. However, somethings currently wrong with the humidity reading, temperature seems to work but sometimes the values are weird.
=> drivers: hts221 humidity and temperature sensor

cpu/stm32l4/vectors.c
=> cpu/stm32l4: optmized isr vector definitions

drivers/cc110x/cc110x-netdev.c
=> cc110x-netdev.c: add NETOPT_ADDR_LEN.

tests/evtimer_msg/tests/01-run.py, tests/evtimer_underflow/tests/01-run.py, tests/gnrc_sock_ip/tests/01-run.py, tests/gnrc_sock_udp/tests/01-run.py, tests/lwip_sock_ip/tests/01-run.py, tests/lwip_sock_tcp/tests/01-run.py, tests/lwip_sock_udp/tests/01-run.py, tests/pipe/tests/01-run.py, tests/pkg_jsmn/tests/01-run.py, tests/pkg_libcoap/tests/01-run.py, tests/pkg_micro-ecc-with-hwrng/tests/01-run.py, tests/pkg_micro-ecc/tests/01-run.py, tests/pkg_minmea/tests/01-run.py, tests/sched_testing/tests/01-run.py
Partially addresses #8141.
Fix style issue ' module imported but unused'
=> tests: fix python style 'F401 module imported but unused'

sys/net/gnrc/link_layer/lwmac/lwmac.c
just some minor code enhancement, which bothered me while fixing issues for #7919
=> net, lwmac: cleanup, restructured code

examples/arduino_hello-world/Makefile, examples/bindist/Makefile, examples/ccn-lite-relay/Makefile, examples/default/Makefile, examples/dtls-echo/Makefile, examples/emcute/Makefile, examples/gcoap/Makefile, examples/gnrc_border_router/Makefile, examples/gnrc_minimal/Makefile, examples/gnrc_networking/Makefile, examples/gnrc_networking_mac/Makefile, examples/gnrc_tftp/Makefile, examples/hello-world/Makefile, examples/ipc_pingpong/Makefile, examples/javascript/Makefile, examples/nanocoap_server/Makefile, examples/posix_sockets/Makefile, examples/riot_and_cpp/Makefile, examples/saul/Makefile, examples/timer_periodic_wakeup/Makefile
factored out from #8029, disable develhelp for all examples
=> make: adapt develhelp for all examples

boards/bluepill/include/board.h, boards/bluepill/include/gpio_params.h
=> boards: bluepill: invert LED state

dist/tools/testrunner/testrunner.py
I am not the python expert here, but seems to me like the code for the testrunner can be slighly simplified, is that right?
=> tools/testrunner: minor code beautification

tests/lwip/tests/01-run.py
Partially addresses #8141 
Here is a [SO answer](https://stackoverflow.com/a/14247383) that explains why we should use 'is' when testing if something is not None.
=> tests/lwip: fix python E711 comparison to None should be 'if cond is not None:'

CODE_OF_CONDUCT.md
This PR provides a first draft for our future code of conduct. I think it's about high time we get one (though I also am convinced that we already followed this rules to our best abilities for the most part up to this) ;-).
=> github: add Code of Conduct

tests/unittests/tests-priority_pktqueue/tests-priority_pktqueue.c
Failed assertion due to wrong usage in unittest, was discovered in #8080 
fixes a failed assertion in gnrc_packet_buf caused by the priority_pktqueue unites. The assertion fails because the tests calls flush on the queue which removes all nodes and associated packet_snips assuming these snips are in the packet but which they weren't for the test case.
=> unittests: fix failed assertion caused by priority_pktqueue

sys/include/net/gnrc/lwmac/lwmac.h
This PR revises the brief description doc of LWMAC to be a brief one-liner.
=> gnrc_lwmac: revise brief description.

.travis.yml, dist/tools/testrunner/testrunner.py
This PR make the testrunner script compliant with RIOT's [Python coding conventions](https://github.com/RIOT-OS/RIOT/wiki/Coding-conventions#python-coding-convention).
None
=> dist/tools/testrunner: fix flake8 remaining issues

tests/thread_priority_inversion/Makefile, tests/thread_priority_inversion/README.md, tests/thread_priority_inversion/main.c
added simple test program for priority inversion problem as discussed in #7365
=> added test program for priority inversion problem

boards/acd52832/include/periph_conf.h, boards/common/nrf52xxxdk/Makefile.features, boards/common/nrf52xxxdk/include/periph_conf.h, cpu/nrf52/include/periph_cpu.h, cpu/nrf52/periph/i2c.c
This PR adds a peripheral I2C driver for nrf52 MCUs.
Continuation of #7557
=> cpu/nrf52: add i2c driver and configs

Makefile.dep, pkg/littlefs/Makefile, pkg/littlefs/Makefile.include, pkg/littlefs/Makefile.littlefs, pkg/littlefs/doc.txt, pkg/littlefs/fs/Makefile, pkg/littlefs/fs/littlefs_fs.c, sys/include/fs/littlefs_fs.h, tests/unittests/tests-littlefs/Makefile, tests/unittests/tests-littlefs/Makefile.include, tests/unittests/tests-littlefs/tests-littlefs.c, tests/unittests/tests-littlefs/tests-littlefs.h
Just to avoid duplicate work, I'm pushing this. I started to work on littlefs package integration. I wanted to test it and see the performances.
I still have some issues and I don't know when I'll have time to continue working on it.
Fix #8204
=> fs: add littlefs as a package

dist/tools/flake8/check.sh, dist/tools/pyterm/pyterm, dist/tools/pyterm/pytermcontroller/pytermcontroller.py, dist/tools/pyterm/testbeds/testbeds.py
This PR makes the pyterm scripts compliant with flake8 checks. I didn't look at the tool implementation details.
None
=> dist/tools/pyterm: fix flake8 issues

core/sched.c, sys/net/gnrc/netif/gnrc_netif.c, sys/net/gnrc/network_layer/sixlowpan/gnrc_sixlowpan.c, sys/shell/commands/sc_sntp.c, sys/vfs/vfs.c
followup on #5166 which changed handling of debug output. This PR fixes several issues that popped up when compiling for native on macOS.
#5166
=> macOS: fix debug output

pkg/libcoap/patches/0001-Add-RIOT-Makefile.patch, pkg/libcoap/patches/0002-Add-config.h.patch, pkg/libcoap/patches/0003-Remove-two-example-programs-in-root.patch, pkg/libcoap/patches/0004-Eliminate-some-compiler-warnings-and-errors.patch, pkg/libcoap/patches/0005-fix-old-style-function-declarations.patch, pkg/libcoap/patches/0006-debug-do-not-misuse-NDEBUG.patch, pkg/libcoap/patches/0007-fix-option-parsing-with-debug-enabled.patch, pkg/libcoap/patches/0008-fix-debug-out-in-PDU-parsing.patch, pkg/libcoap/patches/0009-delete-unused-function-check_opt_size.patch
=> [backport] pkg/libcoap: update patches for git >=2.15.x

cpu/native/include/socket_zep.h
=> [backport] socket_zep: remove unnecessary include

core/sched.c, sys/net/gnrc/netif/gnrc_netif.c, sys/net/gnrc/network_layer/sixlowpan/gnrc_sixlowpan.c, sys/shell/commands/sc_sntp.c, sys/vfs/vfs.c
=> [backport] macOS: fix debug output

Makefile.dep, cpu/nrf5x_common/radio/nrfmin/nrfmin.c, sys/net/gnrc/netif/gnrc_netif.c, sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c
Backport to #8380.
Backport to #8380.
=> gnrc_netif: set-up 6Lo for NRFmin [2018.01 backport]

examples/gnrc_tftp/tftp_server.c
=> [backport] examples/gnrc_tftp: fix implicit fallthrough error

tests/unittests/tests-littlefs/tests-littlefs.c
=> unittests/littlefs: fix unittests [2018.01]

dist/tools/ethos/ethos.c
Forked off from #8376 to ease review/merge.
Add a specific case of EOF on stdin to avoid situations where the message `error reading from stdio. res=0` is repeated forever if stdin is not a terminal.
When EOF is received on stdin and stdin is a TTY (terminal), then ethos will close gracefully. EOF on stdin is sent when the user presses CTRL+D in the terminal on Linux, MacOS, or CTRL+Z on Windows.
If stdin is not a terminal (for example using `</dev/null` on the command line), then stdin will be closed if EOF is reached, but the ethos process will continue tunneling traffic.
#8376
=> ethos: handle EOF on stdin

sys/net/gnrc/network_layer/ipv6/nib/nib.c
This fixes the behavior for the NIB in case of errors. For some error cases in the forwarding look-up the packet wasn't released. This is fixed with that
Fixes #8457 (at least the test).
=> gnrc_ipv6_nib: release packages for forwarding error cases

sys/net/gnrc/network_layer/ipv6/nib/nib.c
=> gnrc_ipv6_nib: release packages for forwarding error cases [2018.01 backport]

boards/native/board_init.c
back port of #8466
fixes #8443
=> board/native: add periph_hwrng and init

cpu/native/include/socket_zep.h, sys/include/net/zep.h
This PR adds a missing doxygen brief description to the net_zep group
None
=> sys/net/zep: add missing doxygen brief description

sys/net/gnrc/netif/gnrc_netif.c, sys/net/gnrc/network_layer/ipv6/nib/_nib-6ln.c, sys/net/gnrc/network_layer/ipv6/nib/_nib-arsm.c
Fixes for auto-address generation some issues @kYc0o had during the release tests.
none
=> gnrc: fix link-layer/IPv6 address conversion for XBee

pkg/littlefs/fs/littlefs_fs.c
=> pkg_littlefs: call mtd_write with size == prog_size  [2018.01 backport]

release-notes.txt
update release notes for 2018.01
=> release-notes: add 2018.01

sys/pm_layered/pm.c
Trivial code style adjustment in pm_layered
=> pm_layered: Use {} for empty while loops

boards/common/msb-430/board_init.c, boards/common/msba2/board_common_init.c, boards/msba2/board_init.c, core/bitarithm.c, cpu/arm7_common/include/iap.h, cpu/atmega_common/periph/uart.c, cpu/atmega_common/thread_arch.c, cpu/cc430/include/cc430-rtc.h, cpu/lpc2387/cpu.c, cpu/lpc2387/include/cpu.h, cpu/lpc2387/lpc23xx-iap.c, cpu/msp430_common/cpu.c, cpu/native/include/native_internal.h, cpu/native/periph/pm.c, drivers/hd44780/hd44780.c, drivers/sdcard_spi/sdcard_spi.c, sys/crypto/aes.c, sys/shell/commands/sc_gnrc_netif.c, tests/driver_sdcard_spi/main.c, tests/pkg_microcoap/coap.c, tests/unittests/tests-ecc/tests-ecc.c
This PR moves cpp style comments found in the code base to C-style comments.
None
=> *: use c-style comments instead of ccp style comments

cpu/efm32/periph/adc.c, cpu/efm32/periph/rtc_series0.c
When @kYc0o was testing #8520, two small bugs were identified. This PR fixes them.
Required for #8520.
=> cpu: efm32: fix ADC and RTC

sys/net/application_layer/gcoap/gcoap.c
During the review for #7337, I found that gcoap assumed the return type for gcoap_udp_send() was of type `size_t`, but really it is of type `ssize_t`. This PR fixes that error. I also added a debug statement to show the error code from an invocation of gcoap_udp_send().
[Discussion](https://github.com/RIOT-OS/RIOT/pull/7337#issuecomment-357868126) in the earlier PR.
=> net/gcoap: fix sock send return type

dist/tools/edbg/Makefile
This PR fixes a minor typo in a comment. Should be straight-forward to review.
None
=> dist/tools/edbg: fix typo in comment

drivers/include/hts221.h, tests/driver_hts221/main.c
This PR fixes typos found in the HTS221 driver documentation and cleans up a bit the related test application.
None
=> drivers/hts221: minor fixes

sys/include/crypto/modes/cbc.h
Add documentation for return values of `cipher_encrypt_cbc` and `cipher_decrypt_cbc`
none
=> crypto/cbc: add return values to documentation

doc/doxygen/src/riot-gnrc.svg
Seems like we forgot to remove a long-gone interface at one place ;-): The graphic on [this page](http://doc.riot-os.org/group__net__gnrc.html).
None
=> doc: replace conn with sock in GNRC architecture overview

sys/rtt_stdio/rtt_stdio.c
The uart_stdio module binds to file descriptors 0, 1, and 2 when VFS is enabled. This modifies rtt_stdio to do the same. Without this pull request, stdio does not work as expected when rtt_stdio and VFS are used simultaneously.
Fixes the second half of #8309. The first half of #8309 was fixed by #8552. See also Pull Request #8310.
=> sys/rtt_stdio: reserve file descriptors for stdin, stdout, and stderr

pkg/semtech-loramac/doc.txt
This PR fixes a broken link in the semtech-loramac package documentation and improves slightly one of the code snippet by adding a return statement if the join procedure failed.
None
=> pkg/semtech-loramac: small fixes

doc/doxygen/riot.doxyfile, pkg/semtech-loramac/include/semtech_loramac.h
This PR fixes the doxygen documentation of the Semtech Loramac package.
Related to #8664 and based on #8665
=> pkg/semtech-loramac: fix doxygen documentation

cpu/kinetis/periph/uart.c
Small alignment cleanup 
Split from #6995
=> kinetis: Align defines in uart.c

drivers/include/periph/qdec.h
Signed-off-by: Yannick Gicquel <ygicquel@gmail.com>
fixup of documentation from #8482
=> drivers/qdec: doxygen rendering fixes
