RIOT-OS/RIOT

dist/tools/ci/print_toolchain_versions.sh

this PR enhances the tool script to print versions of installed compilers, devel libs and tools:
- add generic command version printer
- add cmake version
- enhance output structure
None

tools/ci: enhance print_toolchain script

---

pkg/littlefs/Makefile
pkg/littlefs/Makefile.include
pkg/littlefs/fs/littlefs_fs.c

Update package to a tagged version (v1.3).
Also add license field and clean up Makefile
None

pkg: update littlefs pkg to v1.3

---

README.md

This PR provides a small cleanup of the TAP setup section in the main README.
None

README: cleanup in tap network section

---

dist/tools/ci/build_and_test.sh

show output for headerguards check on failure
fixes #8737

tools: show diff for headerguards check on failure

---

pkg/ccn-lite/Makefile
sys/shell/commands/sc_ccnl.c

Minor changes to the pkg integration of CCN-lite are necessary in order to be able to use the latest CCN-lite features.
I don't like version bumping the CCN-lite package every week. But these changes are necessary to use the latest CCN-lite master.
fixes https://github.com/cn-uofbasel/ccn-lite/issues/208

pkg: ccn-lite: minor changes to integrate latest ccn-lite features

---

doc/doxygen/riot.doxyfile
pkg/openthread/include/ot.h

This PR fixes some issues in openthread package documentation
Related to #8664 and based on ~#8665~

pkg/openthread: fix issues in doxygen documentation

---

drivers/jc42/include/jc42_params.h
sys/auto_init/saul/auto_init_jc42.c

This PR update the params definitions scheme for the jc42 device driver.

drivers/jc42: apply unified params definition scheme

---

drivers/sdcard_spi/include/sdcard_spi_params.h

This PR update the params definitions scheme for this device driver.

drivers/sdcard_spi: use new driver params scheme

---

drivers/sx127x/include/sx127x_params.h

This PR update the params definitions scheme for this device driver.

drivers/sx127x: use new driver params scheme

---

drivers/mrf24j40/include/mrf24j40_params.h

This PR updates the params definitions scheme of this device driver

drivers/mrf24j40: apply unified driver params scheme

---

drivers/soft_spi/include/soft_spi_params.h

This PR update the params definitions scheme for this device driver.

drivers/soft_spi: use new driver params scheme

---

drivers/dht/include/dht_params.h
sys/auto_init/saul/auto_init_dht.c

This PR update the params definitions scheme for the dht device driver.

drivers/dht: apply unified params definition scheme 

---

drivers/Makefile.dep
drivers/Makefile.include
drivers/include/si114x.h
drivers/si114x/Makefile
drivers/si114x/include/si114x_internals.h
drivers/si114x/include/si114x_params.h
drivers/si114x/si114x.c
drivers/si114x/si114x_saul.c
makefiles/pseudomodules.inc.mk
sys/auto_init/auto_init.c
sys/auto_init/saul/auto_init_si114x.c
tests/driver_si114x/Makefile
tests/driver_si114x/README.md
tests/driver_si114x/main.c

Had this one in a pending branch. The proximity sensor is not implemented yet (well it still doesn't work) and I'm not sure about the UV, IR and visible light retrieved values.

drivers/si1145: initial implementation

---

drivers/io1_xplained/include/io1_xplained_params.h
sys/auto_init/saul/auto_init_io1_xplained.c

Missed that one last week. I just discovered it while doing some cleanup in my branches.

drivers/io1_xplained: apply unified params definition scheme

---

tests/unittests/tests-tweetnacl/tests-tweetnacl.c

This PR adds a simple sign/verify test to tweetnacl's unittest, testing whether tweetnacl can verify it's own signature, and whether naive tempering makes the verification fail.

tests/unittests: add tweetnacl sign/verify test

---

pkg/tweetnacl/Makefile.dep
pkg/tweetnacl/src/randombytes.c
sys/random/Makefile
sys/random/random.c
sys/random/tinymt32.c

This PR unifies tinymt32 and tweetnacl random_bytes().

sys/random: add random_bytes()

---

Makefile
Makefile.base
Makefile.include
boards/common/arduino-mkr/Makefile.include
boards/common/msba2/tools/Makefile
boards/native/Makefile.include
doc/doxygen/Makefile
drivers/Makefile
makefiles/buildtests.inc.mk
makefiles/cflags.inc.mk
makefiles/docker.inc.mk
makefiles/info-global.inc.mk
makefiles/info-nproc.inc.mk
makefiles/info.inc.mk
makefiles/mcuboot.mk
sys/Makefile
sys/crypto/Makefile
sys/log/Makefile
tests/driver_dsp0401/Makefile
tests/driver_sx127x/Makefile

This PR is a follow-up of #8815 but applied to all Makefiles. Then the use of `$(variable)` is consistent across all makefiles (instead of mixing it with `${variable}`).
Maybe @cladmi is interested ?

make: replace curly braces with parenthesis

---

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c

If the payload length is zero and the next header field is not set to
NONXT, GNRC will interpret the current header as the payload because the
first snip is always interpreted as the payload. This can lead to loops
and or crashes.
My steps to reproduce such a crash:
- `sudo ip tuntap add tap0 mode tap user $USER`
- `sudo ip link set tap0 address 26:d5:e9:75:d0:e0 && sudo ip link set dev tap0 up`
- start the gnrc_networking example and set the ipv6 address as follows
- `ifconfig 6 del fe80::24d5:e9ff:fe75:d0e1`
- `ifconfig 6 add fe80::dcad:beff:feef:cafe`
- use a packet injection tool like bittwist to inject a bad packet from the supplied pcap files
- `sudo bittwist -i tap0 id_0000017.pcap`
- the example should crash
[riot-crash-pcap.tar.gz](https://github.com/RIOT-OS/RIOT/files/1872456/rio …

gnrc_ipv6: discard non-NONXT packets with 0 payload length

---

cpu/stm32l0/periph/i2c.c

A timeout has been added to get out of busy waiting loop. I have already face issues where my cpu was blocked in this kind of loop.
Signed-off-by: Aurelien Fillau <aurelien.fillau@gmail.com>

cpu/stm32l0 : timeout added on waiting loop

---

pkg/tweetnacl/src/randombytes.c
tests/unittests/tests-tweetnacl/tests-tweetnacl.c
tests/unittests/tests-tweetnacl/tests-tweetnacl.h

As the subject says, small cleanup in the tweetnacl package
None

pkg/tweetnacl: Remove unused headers and function declarations

---

sys/evtimer/evtimer.c

Minor changes to optimize adding an event timer.
Removes variable  `delta_sum` and three calculations.

evtimer: optimized adding

---

sys/include/net/nanocoap.h

This response code from RFC 7252 was not yet included
None

nanocoap: add request entity incomplete response code

---

sys/include/matstat.h
sys/matstat/Makefile
sys/matstat/matstat.c
tests/unittests/tests-matstat/Makefile
tests/unittests/tests-matstat/Makefile.include
tests/unittests/tests-matstat/tests-matstat.c
tests/unittests/tests-matstat/tests-matstat.h

Introduce a new library for estimating parameters of sampled random distributions. The library uses only integer operations and the algorithms only require a single pass over the input data, which reduces the memory usage to O(1).
Includes unit tests of all library functions and for some basic verification of the accuracy of the computed values.
Required by #8531

matstat: Integer mathematical statistics library

---

drivers/include/pulse_counter.h

http://api.riot-os.org/group__drivers__pulse__counter.html
The documentation page for this sensor was named "extra sensor" in the list of modules. This PR updates the docs to better match the other documentation.
Introduced in #7883

pulse_counter: Editorial changes to docs

---

pkg/qDSA/Makefile.dep
pkg/qDSA/Makefile.include

pkg/qDSA: disble arm asm version for cortexm > 0plus [BACKPORT]

---

release-notes.txt

add 2018.04 release notes [BACKPORT]

---

release-notes.txt

PR adds 2018.04 release notes.

add 2018.04 release notes

---

release-notes.txt

release notes 2018.04 typo fix

---

tests/isr_yield_higher/Makefile
tests/libfixmath_unittests/Makefile
tests/pipe/Makefile
tests/pkg_cayenne-lpp/Makefile
tests/posix_semaphore/Makefile
tests/rmutex/Makefile
tests/thread_cooperation/Makefile
tests/thread_exit/Makefile
tests/thread_flags/Makefile
tests/trace/Makefile
tests/xtimer_hang/Makefile
tests/xtimer_usleep/Makefile

This PR adds more automated tests on the CI. I tested them on OS X and some failed,
but it's maybe related to my configuration. If it shows that there's a problem there, I'll
remove them from the list.
#8801

tests: add more hardware in the loop tests

---

sys/include/net/gcoap.h
sys/net/application_layer/gcoap/gcoap.c

Some cleanup and enhancements, namely:
- make path attribute const
- add asserts, to verify path, i.e., must start with `/`
None

gcoap: enhance gcoap_req_init

---

drivers/include/periph/i2c.h
drivers/periph_common/init.c

This PR defines the new I2C API of RIOT.
We will update the CPU and devices drivers step by step in this dedicated branch.
Rebased of #6576 
Progress is tracked with #6577

I2C: introduce new API

---

cpu/cortexm_common/vectors_cortexm.c

(very) minor indention fix I stumble upon

cpu/cortex_common: fix indention in vector table

---

drivers/include/periph/i2c.h

periph/i2c: fix doc typo

---

boards/cc2538dk/Makefile.include
boards/common/remote/Makefile.include
boards/mulle/Makefile.include
boards/openmote-cc2538/Makefile.include
boards/pba-d-01-kw2x/Makefile.include
boards/ruuvitag/Makefile.include
boards/teensy31/Makefile.include
boards/telosb/Makefile.include
boards/thingy52/Makefile.include
boards/z1/Makefile.include

Use RIOTTOOLS variable for boards.
Follow up to #9067 and part of #8821

boards: use RIOTTOOLS variable

---

makefiles/tools/bossa.inc.mk
makefiles/tools/edbg.inc.mk
makefiles/tools/jlink.inc.mk
makefiles/tools/openocd.inc.mk
makefiles/tools/renode.inc.mk
makefiles/tools/serial.inc.mk
makefiles/tools/targets.inc.mk

Use RIOTTOOLS variable for flashers and tools.
Follow up to #9067 and part of #8821

makefiles/tools: use RIOTTOOLS variable

---

drivers/include/periph/i2c.h

Small formatting fixes for i2c.h

periph/i2c: Editorial changes to i2c.h

---

boards/arduino-zero/include/periph_conf.h
boards/common/arduino-mkr/include/periph_conf.h
boards/feather-m0/include/periph_conf.h
boards/samd21-xpro/include/periph_conf.h
boards/saml21-xpro/include/periph_conf.h
boards/samr21-xpro/include/periph_conf.h
boards/sodaq-autonomo/include/periph_conf.h
boards/sodaq-explorer/include/periph_conf.h
cpu/sam0_common/include/periph_cpu_common.h
cpu/sam0_common/periph/i2c.c

This PR updates the I2C driver from sam0 families CPU and also update their periph_conf.h file to fit the new driver.
tested with #9193 #9195 and ADXL345
#6577

cpu/sam0: update I2C driver to new API

---

Makefile.dep
examples/ccn-lite-relay/Makefile
pkg/ccn-lite/Makefile
pkg/ccn-lite/Makefile.dep
sys/shell/commands/sc_ccnl.c

This PR changes the CCN-lite shell command to use the recently introduced method for adding contents in CCN-lite thread context. A version bump of the package will follow soon.
CCN-lite [#256](https://github.com/cn-uofbasel/ccn-lite/pull/256)

shell/ccnl: use new CS add method

---

makefiles/vars.inc.mk

Align comment indentation
None

makefiles/vars.inc.mk: fixup indentation

---

sys/embunit/TestCaller.c
sys/embunit/TestCase.c
sys/include/embUnit/TestCaller.h
sys/include/embUnit/TestCase.h

There is no reason to let embunit think test case names are writable. Fixes `-Wwrite-strings`

embunit: Const test case names

---

tests/bench_msg_pingpong/Makefile
tests/bench_msg_pingpong/README.md
tests/bench_msg_pingpong/main.c
tests/bench_msg_pingpong/tests/01-run.py
tests/bench_mutex_pingpong/Makefile
tests/bench_mutex_pingpong/README.md
tests/bench_mutex_pingpong/main.c
tests/bench_mutex_pingpong/tests/01-run.py
tests/bench_sched_nop/Makefile
tests/bench_sched_nop/README.md
tests/bench_sched_nop/main.c
tests/bench_sched_nop/tests/01-run.py
tests/bench_thread_flags_pingpong/Makefile
tests/bench_thread_flags_pingpong/README.md
tests/bench_thread_flags_pingpong/main.c
tests/bench_thread_flags_pingpong/tests/01-run.py
tests/bench_thread_yield_pingpong/Makefile
tests/bench_thread_yield_pingpong/README.md
tests/bench_thread_yield_pingpong/main.c
tests/bench_thread_yield_pingpong/tests/01-run.py

This PR adds some benchmark applications that I've been using for benchmarking RIOT's IPC performance.

tests: add some benchmarks

---

cpu/stm32l1/periph/adc.c

This PR takes over #8463 and fixes the whitespace errors.
#8463

cpu/stm32l1: fix ADC clock

---

boards/samr21-xpro/board.c
boards/samr21-xpro/include/board.h

This is the continuation of #8348. Basically I took @gvz's commit and addressed @haukepetersen's comment (as far as I could).
#8348

boards/samr21-xpro: add function to configure antenna switch

---

examples/lorawan/README.md

This PR provides 2 fixes in the README of the LoRaWAN example application:
- fix a typo
- reword slightly one sentence
I was surprised (and happy) to see this application was merged recently :)

examples/lorawan: minor fixes in application README

---

core/include/thread_flags.h

Trivial cleanup
Split from #9284

core: uncrustify thread_flags.h

---

drivers/include/srf02.h
drivers/srf02/srf02.c
tests/driver_srf02/main.c

Update the srf02 sensor driver to the new I2C API.
#6577

drivers/srf02: Update to new i2c API

---

cpu/kinetis/periph/spi.c

Fixes a problem with hardware CS when using slow SPI speeds, mentioned in https://github.com/RIOT-OS/RIOT/issues/6437#issuecomment-283114795
The problem was identified as the module was being disabled before the CS line has been deasserted when using fast core clocks in combination with slow SPI speeds. By setting the HALT bit and waiting for the TXRXS status flag to become unset we allow the hardware to acknowledge that the transfer is completely finished and we can finally disable the module clocks.
#6437

kinetis: Clean up SPI module power handling

---

drivers/include/lis3dh.h
drivers/lis3dh/include/lis3dh_params.h
drivers/lis3dh/lis3dh.c
sys/auto_init/saul/auto_init_lis3dh.c

This PR update the params definitions scheme and makes some cleanup in the driver implementation.

drivers/lis3dh: apply unified driver params scheme + cleanup

---

drivers/ina220/ina220.c
tests/driver_ina220/main.c

Adapt drivers/ina220 to new I2C api
#6577

drivers/ina220: adapt to new I2C api

---

drivers/hdc1000/hdc1000.c

HDC1000 driver adaptation for i2c refactoring.
#6577

drivers/hdc1000: adapt to new i2c API

---

drivers/mpl3115a2/mpl3115a2.c

Adapt mpl3115a2 driver to new I2C api.
#6577

drivers/mpl3115a2: adapt to new i2c API

---

drivers/mma8x5x/mma8x5x.c

Adapt mma8x5x to new i2c API.
#6577

drivers/mma8x5x: adapt to new i2c API

---

boards/frdm-k22f/include/periph_conf.h
boards/frdm-k64f/include/periph_conf.h
boards/frdm-kw41z/include/periph_conf.h
boards/mulle/include/periph_conf.h
boards/pba-d-01-kw2x/include/periph_conf.h
boards/teensy31/Makefile.features
core/include/thread_flags.h
cpu/kinetis/Makefile.dep
cpu/kinetis/doc.txt
cpu/kinetis/include/cpu_conf_kinetis.h
cpu/kinetis/include/periph_cpu.h
cpu/kinetis/periph/i2c.c
cpu/kinetis/periph/rtt.c
cpu/kinetis/periph/timer.c

Update the Kinetis I2C driver for the new API
Needs some more testing
#6577

kinetis: Update i2c driver to new API

---

drivers/pn532/pn532.c

clone of #9432 - with all the changes addressed. Accidentally dleted the old branch and wasn't able to reopen the PR.
#6577

drivers/pn532: adapt to new i2c API (recreated)

---

drivers/mpu9150/mpu9150.c

Adapt mpu9150 driver to new I2C api
#6577

drivers/mpu9150: adapt to new I2C api

---

drivers/mag3110/include/mag3110_params.h
drivers/mag3110/mag3110.c
sys/auto_init/saul/auto_init_mag3110.c

This PR update the params definitions scheme for this device driver.
Also forgot this one last week.

drivers/mag3110: apply unified params definition scheme

---

tests/pkg_monocypher/Makefile

As should have been done in the initial commit. Stack space set to the
amount described in the doc
Obsoletes #9486

tests/monocypher: Increase stack space

---

drivers/bmx055/bmx055.c

captain obvious to the rescue, i.e. see title
#6577

drivers/bmx055: adapt to new i2c api

---

dist/tools/mosquitto_rsmb/config.cnf

This helped me a lot while testing #9464 to interact with the broker
using the mosquitto shell command clients.
Useful for testing stuff like #9464

mosquitto_rsmb: add MQTT listener to config

---

drivers/lis3mdl/lis3mdl.c

Adapt lis2mdl driver to new I2C api
#6577

drivers/lis3mdl: adapt to new i2c API

---

drivers/include/isl29020.h
drivers/isl29020/include/isl29020_params.h
drivers/isl29020/isl29020.c
sys/auto_init/saul/auto_init_isl29020.c
tests/driver_isl29020/Makefile
tests/driver_isl29020/main.c

This PR cleans up the isl29020 implementation to make more inline with other drivers.
#6577

drivers/isl29020: apply unified params definition scheme

---

sys/net/gnrc/netif/gnrc_netif.c

gnrc_netif expects NETOPT_RX_END_IRQ to be enabled by default, or else no packets will be received. All current netdev drivers enable some of these flags by default, but it seems hacky to depend on flag default values. With this change, the device drivers can be simplified and the preprocessor conditional on MODULE_NETSTATS_L2 for NETOPT_TX_END_IRQ can be removed from the device drivers as well.
Not sure how the other network stacks may be affected so there are no changes to the netdev device drivers in this PR.

gnrc_netif: Enable RX and TX complete events after netdev init

---

drivers/bmp180/bmp180.c
drivers/include/bmp180.h
tests/driver_bmp180/main.c

This PR adapt the BMP180 driver to the new I2C api.
#6577

drivers/bmp180: adapt to new I2C api

---

.github/ISSUE_TEMPLATE/bug_report.md

Makes the bug report template selectable.

github: Update issue templates for front-end

---

boards/arduino-zero/include/periph_conf.h
boards/common/arduino-mkr/include/periph_conf.h
boards/nucleo-f103/Makefile.features

Fix C++ related issues for some boards, ie. struct attributes need to be init in order.

Arduino: fix several boards with C++ issues due to new I2C params

---

boards/ublox-c030-u201/Makefile
boards/ublox-c030-u201/Makefile.dep
boards/ublox-c030-u201/Makefile.features
boards/ublox-c030-u201/Makefile.include
boards/ublox-c030-u201/board.c
boards/ublox-c030-u201/dist/openocd.cfg
boards/ublox-c030-u201/include/arduino_pinmap.h
boards/ublox-c030-u201/include/board.h
boards/ublox-c030-u201/include/gpio_params.h
boards/ublox-c030-u201/include/periph_conf.h

backport commit to new_i2c_if because of embargo breach.
#8769

boards: add ublox c030-u201 [backport]

---

drivers/mrf24j40/mrf24j40_netdev.c

The mrf24j40 driver should return the frame length when both buf is NULL
and len is zero and drop the packet when len is nonzero and buf is NULL.
This PR fixes that behaviour
None

mrf24j40: Fix netdev recv implementation

---

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c

This change is a gnrc_ipv6_nib/gnrc_netif(2)-based rework of #7210.
Packet duplication
==================
Its main optimization is that it restructures `gnrc_ipv6` handling of
sent packets so that duplication for write-protection happens at the
latest possible step:
* potential `gnrc_netif` headers added by upper layers are
write-protected before their removal
* This unifies the duplication of the IPv6 header directly after
that
* Extension headers in-between the IPv6 header and the payload header
are duplicated just before the check sum is duplicated
Especially the last point allows for only handing a single packet snip
to all lower functions instead of an already searched IPv6 header
(which now is always the first until it is handed to the interface) +
payload header.
Further clean-ups …

 gnrc_ipv6: clean-up and simplify send handling

---

boards/acd52832/include/periph_conf.h
boards/feather-m0/include/periph_conf.h
boards/samd21-xpro/include/periph_conf.h
boards/saml21-xpro/include/periph_conf.h
boards/samr21-xpro/include/periph_conf.h
boards/sodaq-autonomo/include/periph_conf.h
boards/sodaq-explorer/include/periph_conf.h
boards/yunjia-nrf51822/include/periph_conf.h
cpu/stm32_common/include/periph_cpu_common.h

This PR should fix all CPP issues for new_i2c_if feature branch, I cherry-picked some commits from @smlng and #9571. I also include the required changes from @aabadie (see #9571 discussion)
Once this PR get merged, I'll rebase new_i2c_if3 to see if Murdock is happy.
This way it should ease comparison between original new_i2c_if branch and new_i2c_if3 which will be rebased onto master.
#9571

i2c: cpp check fixes

---

cpu/stm32_common/stm32_mem_lengths.mk
examples/gcoap/Makefile
examples/nanocoap_server/Makefile
examples/posix_sockets/Makefile
examples/rdcli_simple/Makefile
tests/driver_enc28j60/Makefile
tests/gnrc_ipv6_ext/Makefile
tests/gnrc_sixlowpan/Makefile
tests/gnrc_sock_dns/Makefile
tests/lwip/Makefile
tests/lwip_sock_ip/Makefile
tests/lwip_sock_tcp/Makefile
tests/lwip_sock_udp/Makefile
tests/nhdp/Makefile
tests/pkg_libcoap/Makefile
tests/pkg_microcoap/Makefile
tests/posix_semaphore/Makefile
tests/pthread_rwlock/Makefile
tests/slip/Makefile
tests/sntp/Makefile
tests/thread_cooperation/Makefile

On some MCUs the ram sizes specified in stm32_mem_lengths.mk are based on the sum of available ram, while it is physically not mapped to a contiguous ram region. This will make the linker place data/code in unmapped address space if enough ram is used. See #9534 for details.
This PR fixes the problem by decreasing the ram sizes to the size of the "primary" ram region.
For testing the following snippet may be helpful:
```c
extern uint32_t _sram;
extern uint32_t _eram;
int main(void)
{
printf("ram start @0x%p\n", &_sram);
printf("ram end   @0x%p\n", &_eram);
printf("last value in ram @0x%p: 0x%08lX\n", &_eram - 1, *(&_eram - 1));
return 0;
}
```
On stm32-l476rg without the fix the above code crashes:
```
ram start @0x0x20000000
ram end   @0x0x20020000
Context before hardfault:
r0: …
```

stm32_common: fix ram length for MCUs with non-contiguous ram regions

---

drivers/w5100/w5100.c

When testing with an W5100 ethernet shield I came across an error where the system freezed when receiving packets. While debugging, I noticed that the `ir` variable holding the interrupt register was never updated (read again from the device) which led the loop to run forever and thus freezing my system. With this fix, receiving packets works fine.

w5100: fixed RX interrupt handling 

---

tests/mpu_stack_guard/Makefile

One of the many errors #9398 revealed. I don't intend to fix all of them, but this one was a simple one to snipe ;-)
None

tests: ignore infinite recursion for mpu_stack_test with clang

---

sys/net/gnrc/link_layer/gomach/gomach.c
sys/net/gnrc/link_layer/lwmac/lwmac.c
sys/net/gnrc/link_layer/lwmac/tx_state_machine.c

As reported by `llvm`. (see #9398)
Fixes issue reported due to #9398.

gnrc: mac: fix types according to print formatting

---

drivers/at86rf2xx/at86rf2xx.c
drivers/cc2420/cc2420.c
drivers/kw2xrf/kw2xrf.c
drivers/mrf24j40/mrf24j40.c
sys/net/gnrc/netif/gnrc_netif.c

Please see description of the referenced PRs.
#9601 #9606

gnrc_netif & radios: event reporting flags  [backport 2018.07] for #9601 #9606

---

boards/openmote-b/Makefile
boards/openmote-b/Makefile.dep
boards/openmote-b/Makefile.features
boards/openmote-b/Makefile.include
boards/openmote-b/board.c
boards/openmote-b/include/board.h
boards/openmote-b/include/periph_conf.h
examples/lua_REPL/Makefile
tests/unittests/Makefile

Add the basic board files based off the original openmote board.

boards/openmoteb-cc2538: Initial support

---

boards/cc2538dk/include/periph_conf.h
boards/openmote-b/include/periph_conf.h
boards/openmote-cc2538/include/periph_conf.h
boards/remote-pa/include/periph_conf.h
boards/remote-reva/include/periph_conf.h
boards/remote-revb/include/periph_conf.h
cpu/cc2538/include/cc2538_ssi.h
cpu/cc2538/include/periph_cpu.h
cpu/cc2538/periph/gpio.c
cpu/cc2538/periph/spi.c

Adapt the periph SPI implementation to make use of vendor header defines and also utilise proper
GPIO API functions instead of manually configure through registers.

cpu/cc2538: refine periph/spi implementation

---

boards/arduino-due/doc.txt
boards/common/doc.txt
boards/frdm-kw41z/doc.txt
boards/frdm-kw41z/include/board.h
boards/jiminy-mega256rfr2/doc.txt
boards/jiminy-mega256rfr2/include/board.h
boards/native/doc.txt
boards/udoo/doc.txt

#8516 was merged and there are some inconsistencies in the [boards module page](http://doc.riot-os.org/group__boards.html):
- For some board, a copyright is displayed instead of the brief description
- For native, a link to the "Family:native" wiki page is displayed instead of the  brief description
- For some other boards, the brief description is not consistent with other (it should start with "Support for ...")
Can be considered as a small follow-up of #8516

boards*: documentation cleanup

---

release-notes.txt

This is the draft PR for the 2018.07 release note.
I invite maintainers to push directly to my branch to document major changes that are not yet listed.
Developers can comment here to add their work.
As a reference, I tried to list all merged PRs in master and closed issues for this release in https://github.com/RIOT-OS/RIOT/milestone/23?closed=1.
It will be again updated with time.
The upcoming release

Release notes for 2018.07

---

tests/lwip_sock_ip/stack.c
tests/lwip_sock_udp/stack.c

tests/lwip_sock_*: fix compilation error

---

boards/sensebox_samd21/doc.txt

Just a fix on the sensebox_samd21 board's documentation.

boards/sensebox_samd21: Fix documentation

---

cpu/native/netdev_tap/netdev_tap.c

As the title indicates
should fix the ram increase from #9832

netdev_tap: declare netdev_driver struct as const

---

dist/tools/pyterm/pyterm

This PR fixes deprecation warnings for warn and SafeConfigParser as mentioned in issue #9827

tools:pyterm fix deprecation warnings

---

boards/slstk3402a/doc.txt
boards/slstk3402a/include/board.h

Now that #8516 is merged, I can merge the documentation for the SLSTK3402a. I don't include the images, since there is no place to store them.
If this PR gets merged, I will open similar PR's for the other boards.
#8516

boards: slstk3402a: add docs

---

sys/checksum/doc.txt
sys/hashes/doc.txt
sys/include/hashes.h
sys/include/hashes/cmac.h
sys/include/hashes/md5.h
sys/include/hashes/sha1.h
sys/include/hashes/sha256.h
sys/include/hashes/sha3.h

Following #9842, this PR groups all hashes into the `hashes` group. I also define/modify some other groups in order to create the categories Checksums, Keyed cryptographic hash functions, Unkeyed cryptographic hash functions and Non cryptographic hash functions (all of them under `sys_hashes` group).
This PR does the following:
- Checksums moved from `sys`group to `sys_hashes` group
- Define groups for `sha256` and `sha3`
- Add CMAC to `sys_hashes_keyed`
- Add MD5, SHA1, SHA256 and SHA3 to `sys_hashes_unkeyed`
- Add all hashes from `hashes.h` files to `sys_hashes_non_crypto`
I also deprecated the section based documentation from the `doc.txt`, because it was outdated and it had the same information as the Doxygen group list.
`make doc`. Go to `System>Hashes` in the generated documentation …

 doc: refactor `hashes` group

---

dist/tools/compile_test/compile_test.py

This PR fixes flake8 issues in `compile_test.py` script that were raised in #9867.
Run `make static-test`, it should return no flake8 errors.
#9867

dist/tools/compile_test: fix flake8 issues

---

boards/sltb001a/doc.txt

This PR adds docs for the SLTB001a.
#9791

boards: sltb001a: add docs

---

README.md

This PR updates the main README to list support of ESP8266.
Not applicable.
Not applicable.

README: update listing support of ESP8266

---

pkg/doc.txt

@silkeh noticed that the patch documentation for packages was outdated. This PR updates it to better reflect the current state
Check whether the documentation matches the current situation.
None

pkg: update patch documentation

---

cpu/sam0_common/periph/gpio.c

cpu/sam0_common/gpio: use gpio_irq feature

---

dist/tools/ci/print_toolchain_versions.sh

This PR adds some more tool version to be printed by the helper script. 
I think we might also want to make this output mandatory if someone reports an issue.
run `./dist/tools/ci/print_toolchain_versions.sh`

dist/tools: extend the print_toolchain_version script

---

dist/tests/if_lib/README.md
dist/tests/if_lib/base_device.py
tests/periph_i2c/tests/README.md
tests/periph_uart/tests/README.md

Add deprecation warnings for cleanup of hardware testing tools to README.md files and in the lib_if that is to be removed.

doc: Add deprecation warnings for new repos

---

cpu/kinetis/periph/gpio.c

cpu/kinetis/gpio: use gpio_irq feature

---

.github/ISSUE_TEMPLATE/feature_request.md

This PR adds a GitHub feature request issue template to our repository.
This needs to be merged before one can test it.
extends #9504

.github: add feature request template

---

README.md

This PR is updating the main README by just removing the "Experimental" status of the LoRaWAN feature. With #8864 now merged and providing real improvements, I consider this much more stable.
And after #9524 will be merged, the support will be very close from full LoRaWAN compliance.
Read the readme
related to #8864

README: remove LoRaWAN experimental status 

---

MAINTAINING.md

This PR includes several changes which clarify certain points, following feedback.

MAINTAINING.md: Several changes for clarity

---

pkg/openthread/include/ot.h

This PR fixes a small typo in the OpenThread pkg documentation.

pkg/openthread: fix typo in documentation

---

cpu/cc2538/periph/gpio.c

cpu/cc2538/gpio: use gpio_irq feature

---

cpu/nrf5x_common/periph/gpio.c

cpu/nrf5x/gpio: use periph_gpio_irq feature

---

cpu/stm32f1/periph/gpio.c

cpu/stm32f1/gpio: use gpio_irq feature

---

cpu/efm32/periph/gpio.c

cpu/efm32/gpio: use gpio_irq feature

---

CONTRIBUTING.md
README.md

This PR proposes a full rewrite of our existing [CONTRIBUTING.md](https://github.com/RIOT-OS/RIOT/blob/master/CONTRIBUTING.md) document.
RIOT has now a very well detailed and organized MAINTAINING.md (with a good review process) but it's still not the case (personal opinion) for the contributing file, which is IMHO, the most important file.
In this PR, I try to give good rules for opening a feature request, a bug report, a pull request and give some information on the doxygen documentation.
I took a lot of inspiration from the [Rust contributing.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) file.
I know the document proposed is not perfect, maybe too technical sometimes. All comments are welcome.
Read the file
based on #10028

CONTRIBUTING: rewrite the existing document

---

pkg/tiny-asn1/Makefile
pkg/tiny-asn1/doc.txt
tests/pkg_tiny-asn1/README.md

Update the tiny-asn1 package.
The update fixes a possible buffer overflow.
run `make test` in `tests/pkg_tiny-asn1`

tiny-asn1: update package version

---

cpu/stm32_common/periph/gpio.c

cpu/stm32_common/gpio: use gpio_irq feature

---

cpu/lpc1768/periph/gpio.c

cpu/lpc1768/gpio: use gpio_irq feature

---

cpu/atmega_common/periph/gpio.c

cpu/atmega/gpio: use gpio_irq feature

---

cpu/lm4f120/periph/gpio.c

cpu/lm4f120/gpio: use gpio_irq feature

---

cpu/sam3/periph/gpio.c

cpu/sam3/gpio: use gpio_irq feature

---

cpu/esp8266/periph/gpio.c

cpu/esp8266/gpio: use gpio_irq feature

---

sys/include/net/nanocoap.h

Adds high-level module documentation for nanocoap. This provides an outline for implementing a client or server, and pointers to the important API functions. It also clarifies how to use the minimal and struct-based APIs for options. The documentation is structured like the gcoap module documentation.
Also capitalized "Nanocoap" in the @defgroup doxygen tag, so it's in order in the Networking section of the documentation.
N/A, just documentation

net/nanocoap: add module documentation

---

drivers/Makefile.dep
drivers/Makefile.include
drivers/include/saul.h
drivers/include/vcnl40x0.h
drivers/saul/saul_str.c
drivers/vcnl40x0/Makefile
drivers/vcnl40x0/include/vcnl40x0_internals.h
drivers/vcnl40x0/include/vcnl40x0_params.h
drivers/vcnl40x0/vcnl40x0.c
drivers/vcnl40x0/vcnl40x0_saul.c
makefiles/pseudomodules.inc.mk
sys/auto_init/auto_init.c
sys/auto_init/saul/auto_init_vcnl40x0.c
sys/include/phydat.h
sys/phydat/phydat_str.c
tests/driver_vcnl40x0/Makefile
tests/driver_vcnl40x0/README.md
tests/driver_vcnl40x0/main.c

This PR adds basic support to the [VCNL4010](http://www.vishay.com/docs/83462/vcnl4010.pdf) proximity and ambient light sensor.
Only the on-demand mode is implemented, I added the saul adapation as well.

drivers/vcnl4010: initial implementation

---

boards/slstk3401a/doc.txt
boards/slstk3401a/include/board.h

This PR adds docs for the SLSTK3401a.
#9791

boards: slstk3401a: add docs

---

boards/common/nrf52xxxdk/include/board_common.h
boards/nrf52840dk/include/board.h
boards/nrf52dk/include/board.h
boards/ruuvitag/include/board.h
boards/thingy52/include/board.h

Obvious typo fixed in copyright comment.
All similar typos should be fixed by this PR since git grep was used to track them.
None
None

boards/*: fix typo Feie => Freie

---

tests/pkg_cmsis-dsp/Makefile
tests/pkg_cmsis-dsp/tests/01-run.py

Provides a test script for `tests/pkg_cmsis-dsp`
None

tests/pkg_cmsis-dsp: provide testscript

---

sys/net/gnrc/netif/gnrc_netif_ieee802154.c

Useful in sniffer situations to see the signal strength of a received packet. Also avoids the crash described in https://github.com/RIOT-OS/applications/pull/54
Run the sniffer application (RIOT-OS/applications), see that there is a non-zero and non-garbage LQI displayed with the packet dump.
Without this PR and without RIOT-OS/applications#54, samr21-xpro shows LQI 0C on all packets in my tests, this is a garbage value read from somewhere unpredictable and is likely different in other builds. With only RIOT-OS/applications#54 applied, LQI is stuck at 00 (because of missing information from the network interface)
different side of the same problem: RIOT-OS/applications#54

gnrc_netif_ieee802154: Provide LQI, RSSI in raw mode via netif_hdr

---

cpu/stm32_common/periph/i2c_1.c

Errors flags could not clear making the i2c unusable after error.
This fix removes the error check in start so the error flags can clear and does proper checking for status bits before _bus_check.
Run periph_i2c on any STM32 F0, F3, F7, L0 and L4 family.  I connect a PHiLIP but any i2c sensor can be used.
`BOARD=nucleo-l476rg make flash term -C tests/periph_i2c`
```
i2c_read_regs 0 85 152 10 0    
2018-10-26 09:45:14,539 - INFO # i2c_read_regs 0 85 152 10 0
2018-10-26 09:45:14,545 - INFO # Command: i2c_read_regs(0, 0x55, 0x98, 10, 0x00)
2018-10-26 09:45:14,557 - INFO # Success: i2c_0 read 10 byte(s) from reg 0x98 : [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09]
i2c_read_regs 0 84 152 10 0    
2018-10-26 09:46:33,204 - INFO #  i2c_read_regs 0 84 152 10 0
2018-10-26 …
```

cpu/stm32_common/i2c: Fix error handling in i2c_1.c

---

boards/jiminy-mega256rfr2/doc.txt

Added that a brown-out happens when 1.8V is set at the DC/DC.
Added explanation for fuse settings.

Update Jiminy doc.txt

---

release-notes.txt

This is the draft PR for the 2018.10 release note (follow up of @cladmi's idea to do it in a PR :)
I invite maintainers to push directly to my branch to document major changes that are not yet listed.
Developers can comment here to add their work.
As a reference, I tried to list all merged PRs in master and closed issues for this release in https://github.com/RIOT-OS/RIOT/milestone/24?closed=1.
It will be again updated with time.
Release 2018.10

release-notes.txt: Add Release 2018.10 notes [backport 2018.10]

---

sys/include/net/gnrc/netif/hdr.h

Another one of those ;-). I need it to make #10521 compilable.
`tests/gnrc_netif` should still pass.
None

gnrc_netif_hdr: make input parameters constant

---

core/cond.c
core/include/cond.h
core/include/thread.h
tests/cond_order/Makefile
tests/cond_order/README.md
tests/cond_order/main.c
tests/cond_order/tests/01-run.py

This is a simple condition variable implementation. I have found it useful in my programming, so I thought I should contribute it upstream.
None at this time.

core: condition variable implementation

---

boards/nrf51dk/Makefile
boards/nrf51dk/Makefile.dep
boards/nrf51dk/Makefile.features
boards/nrf51dk/Makefile.include
boards/nrf51dk/board.c
boards/nrf51dk/doc.txt
boards/nrf51dk/include/board.h
boards/nrf51dk/include/gpio_params.h
boards/nrf51dk/include/periph_conf.h
cpu/nrf51/include/cpu_conf.h
examples/asymcute_mqttsn/Makefile
examples/default/Makefile
examples/dtls-echo/Makefile
examples/gnrc_border_router/Makefile
examples/gnrc_tftp/Makefile
examples/javascript/Makefile
examples/lua_REPL/Makefile
examples/lua_basic/Makefile
examples/posix_sockets/Makefile
tests/gnrc_netif/Makefile
tests/gnrc_tcp_client/Makefile
tests/gnrc_tcp_server/Makefile
tests/netstats_l2/Makefile
tests/unittests/Makefile

This PR adds an initial support for the [nrf51dk](https://www.nordicsemi.com/eng/Products/nRF51-DK) board.
Note for reviewers: this PR is based on #10243  and #10277.
Timer and i2c based applications have been tested with success. The rest is the same as other nrf51 boards.
An important point with this port is the way to flash the board: I couldn't make it fully work using the jlink  software (or using openocd with jlink adapter). The shell wasn't working correctly, the firmware is not responding to incoming data but data are received from the firmware.
I tried to update the flasher chip using a DAPLink firmware, provided by mbed. And with this, it works very well. The procedure is described in the board documentation.
1. update the flash chip as described in the board documentation
2. …

boards/nrf51dk: add initial support

---

dist/testbed-support/makefile.iotlab.single.inc.mk

This PR adds the `firefly` board in the list of architectures provided by IoT-LAB.
1. Book a `firefly` on IoT-LAB:
```
$ iotlab-experiment submit -n pr_firefly -d 20 -l 1,archi=firefly+site=lille
$ iotlab-experiment wait
```
2. Build, flash, term it with any application using the RIOT build system:
```
$ make BOARD=firefly IOTLAB_NODE=auto-ssh -C examples/default/ flash term
```
None

dist/testbed-support: add firefly in IoT-LAB archis

---

sys/net/gnrc/network_layer/ipv6/ext/gnrc_ipv6_ext.c

Though this change might seem more complicated, it has the benefit, that
after #9484 we don't have to assume that a received packet within IPv6's
receive function can be handed to the function pre-parsed, making that
function far less complicated (will be provided in a future PR).
Also this might give the forwarding via routing header a little
performance boost, as we now don't *receive* the packet first only to
forward it later-on.
From https://github.com/RIOT-OS/RIOT/pull/10229#issuecomment-439611720 (corrected one inconsistency though):
> 1. Compile `examples/gnrc_networking` with `USEMODULE += gnrc_rpl_srh` for `native`
> 2. Start two native instances connected via a bridge `tapbr0`
> 3. `native` instance 1 (`native1`):
>     ```
>     ifconfig 6 add 2001:db8::1
>     udp server start …
```

gnrc_ipv6_ext: use send for forwarding with RH

---

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c

While testing some IPv6 functionality I noticed, that hop-limit 0 is just accepted, worse even, it is forwarded, since the router just checks `(--hl > 0)` and thus overflows. This fixes that case.
0. (create two TAP interfaces connected via a TAP bridge `tapbr0`):
```
dist/tools/tapsetup/tapsetup
```
1. Start two native instances of `gnrc_networking` (`native0` and `native1`).
2. On `native0` add a global address:
```
ifconfig 6 add 2001:db8::1
```
3. On `native1` add a route to `native0`:
```
nib route add 6 2001:db8::/64 <link-local address of native0>
```
4. On Linux host add a route to `native1` via bridge:
```sh
sudo ip route add 2001:db8::/64 via "<link-local address of native1>" dev tapbr0
```
6. Ping `2001:db8::1` from Linux with hop-limit 1 (should fail in any case):
```sh
ping6 …
```

gnrc_ipv6: fix hop-limit == 0 case

---

doc.txt

This PR adds the `@configurations` tag to Doxygen. This label is intended to group all configurations (macros) in a single Doxygen entry (as seen on #10566 )
Run `make doc`. You should see no errors.
Also check if the name and description of the tag make sense.
#10566

doc: add configurations Doxygen group

---

sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c

With `gnrc_pktbuf_merge()` introduced in #10447 we can remove some code duplication when it comes to looping back a packet.
Pinging an address of the node (or the loopback address `::1`) should still work as before.
Follow-up on #10447.

gnrc_ipv6: use gnrc_pktbuf_merge() to loopback packet

---

sys/net/gnrc/network_layer/sixlowpan/gnrc_sixlowpan.c

When using the `sixlowpan` module without `IPv6`, then
the compiler stumbles across some dependencies that are not met.
remove `gnrc_ipv6` from the `Makefile.dep` for `gnrc_sixlowpan` should suffice. Alternatively, I completely removed the `gnrc_sixlowpan` dependency entry from `Makefile.dep` and added `gnrc_sixlowpan_frag` to the `ccn-lite-relay` example for testing purposes.
–

sixlowpan: minor fixes for non-ipv6 usage

---

cpu/esp_common/esp-now/doc.txt
cpu/esp_common/esp-now/esp_now_netdev.c
cpu/esp_common/esp-now/esp_now_netdev.h
cpu/esp_common/esp-now/esp_now_params.h

Minor doc clean-up after #10663.
Follow-up to #10663.

esp_now: fix doxygen groups

---

dist/tools/ci/print_toolchain_versions.sh

Adds the xtensa toolchains to the toolchain version print tool.
See #10674
Fixes #10674

 print_toolchain_versions.sh: add xtensa toolchains

---

sys/include/net/gnrc/ipv6.h
sys/include/net/gnrc/sixlowpan.h

This is a follow-up to #10583 and follows the suggestion made in https://github.com/RIOT-OS/RIOT/pull/10583#discussion_r241743314
None, just a wording update in the doc.
Follow-up to #10583.

gnrc: make titles of NETAPI command documentation more specific

---

drivers/ccs811/ccs811_saul.c

Not much to add, the casts were totally unnecessary

drivers/ccs811: remove unnecessary casts

---

sys/net/gnrc/network_layer/sixlowpan/frag/rbuf.c

Found this while working on #10679 and #10680. It is however independent.
While the recursion in `gnrc_sixlowpan_frag` shouldn't be infinite we
still should avoid using recursions in general (also to be able to
statically analyze stack usage). This unrolls the recursion.
`ping6` with fragmented packets between two 6Lo capable nodes should still be possible.
None

gnrc_sixlowpan_frag: unroll recursion

---

core/mbox.c
core/msg.c

There is nothing more to say about it.

core: remove redundant casts

---

makefiles/arch/cortexm.inc.mk

arm-gcc version from ubuntu bionic repository is not supported in RIOT.
Both when building with `gnu` and `llvm`.
arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:6.3.1+svn253039-1build1) 6.3.1 20170620
So detect this version and print an error if found.
The check is done on the building machine and not on the host when building in
docker.
The error can be disabled when building with WERROR=0.
Try compiling anything for `samr21-xpro` with your working setup, it should produce no error at compilation
Try building with ubuntu bionic GCC version (change your PATH) to see the error is detected, and also other "working" gcc versions:
```
RIOT_CI_BUILD=1 BOARD=samr21-xpro make --no-print-directory -C examples/default/ 
/home/harter/work/git/RIOT/makefiles/arch/cortexm.inc.mk:61: …
```

cortexm.inc.mk: detect 'arm-none-eabi-gcc' from ubuntu bionic

---

doc/memos/rdm0000.md

This PR attempts to clarify the difference between a change that can be addressed by minor revision and one that must be addressed by deprecation.
Read!

doc/rdm: clarification to revision process

---

sys/include/net/gnrc/sixlowpan.h

As a consequence of #8511 I reworked the submodules of `gnrc_sixlowpan` in [this project](https://github.com/RIOT-OS/RIOT/projects/18) but never actually documented the new behavior anywhere except in the issue. This PR fixes that.
`make doc` should produce nicely rendered output ;-).
Documents behavior outlined in #8511.

gnrc_sixlowpan: document submodules according to #8511

---

cpu/native/socket_zep/socket_zep.c

When I tested #10782 with `gnrc_networking` on `native` I found this issue in `socket_zep`
Replace `gnrc_netdev_default` with `socket_zep` in `examples/gnrc_networking/Makefile`:
```diff
diff --git a/examples/gnrc_networking/Makefile b/examples/gnrc_networking/Makefile
index 628b9c9..99ac370 100644
--- a/examples/gnrc_networking/Makefile
+++ b/examples/gnrc_networking/Makefile
@@ -19,7 +19,7 @@ BOARD_INSUFFICIENT_MEMORY := arduino-duemilanove arduino-mega2560 arduino-uno \
-USEMODULE += gnrc_netdev_default
+USEMODULE += socket_zep
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_icmpv6_error
```
Compile with ubsan support:
```sh
UBSAN_ENABLE=1 UBSAN_MODE=msg_exit make -C examples/gnrc_networking
```
And start a native instance:
```sh
TERMFLAGS="-z [::]:17755,[::1]:17754" make -C …
```

socket_zep: fix undefined timestamp conversion behavior

---

doc/doxygen/src/mainpage.md

This adds a reference to the newest [RIOT paper](https://riot-os.org/docs/riot-ieeeiotjournal-2018.pdf) to documentation.
`make doc` and open `doc/doxygen/html/index.html`. The amended text should now appear.
None

doc: add reference to RIOT paper

---

dist/tests/if_lib/philip_if.py
tests/periph_i2c/tests/periph_i2c_if.py
tests/periph_i2c/tests/test.py
tests/periph_uart/tests/periph_uart_if.py
tests/periph_uart/tests/test.py
tests/puf_sram/tests/example_test.py
tests/puf_sram/tests/puf_sram_if.py

HAW was missing from the copywrites in some files, I just want to make sure the credit is correct.
Read it

doc: Update copywrites it include HAW

---

.github/ISSUE_TEMPLATE/security_bug.md

The [doc on issue templates](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/) is somewhat confusing about `name`/`title`. Turns out: `title` is what's used to generate the title for a new issue and `name` is required for it to show up in the "new issue" listing. This fixes that. See [templates edit page](https://github.com/RIOT-OS/RIOT/issues/templates/edit) for more information.
Sadly this needs to be merged to see the changes in effect :-/.
Follow-up to #10756

github: fix security bug template

---

release-notes.txt

This PR adds the (sub) Release 2018.10.1 notes.
It contains the list of merged PRs and commits in `2018.10-branch` between `2018.10-devel` tag and the #10285  
Read
None so far

release-notes.txt: Add Release 2018.10.1 notes

---

release-notes.txt

release-notes.txt: Add Release 2018.10.1 notes [Backport 2018.10]

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

Currently the constructed NA for a delayed NA case is neither used nor released nor does it get an IPv6 header to be used properly. This fixes that case.
Since this is currently an edge-case we shouldn't really enter ATM, I fear you have to read and understand the code ... But the test case proposed by @aabadie proposed in https://github.com/RIOT-OS/Release-Specs/issues/98#issuecomment-461587132 might be one to test if together with #10978 this reduces (or even eliminates) the leaks in the packet buffer.
I'm still not sure this fixes all leaks (this code shouldn't even be entered since we do not use anycasts addresses at least in the test case these leaks were found), but definitely closes more leaks together with #10978.

gnrc_ipv6_nib: fix preparation of delayed NA [backport 2019.01]

---

sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c
sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c

backport: gnrc_tcp: syn_rcvd pkt loss fix

---

release-notes.txt

This PR adds the (sub) Release 2018.10.1 notes.
It contains the list of merged PRs and commits in `2018.10-branch` between `2018.10-devel` tag and the #10285  
Read
None so far

release-notes.txt: Add Release 2018.10.1 notes [backport 2019.01]

---

release-notes.txt

This PR is the initial draft for the 2019.01 release notes.
Every maintainer is invited to update this PR by either opening PRs against my fork or by directly pushing into my branch.
You can get the complete list of closed issues and PRs tagged for this release in https://github.com/RIOT-OS/RIOT/milestone/25?closed=1.

Release 2019.01 notes [backport 2019.01]

---

cpu/nrf5x_common/periph/uart.c

When testing https://github.com/RIOT-OS/RIOT/pull/11096, we discovered a bug in the `nrf5240`s uart implementation: Nordic's `EasyDMA` is only capable of transferring data from RAM, but not from ROM. So whenever passing a ROM location to the UART driver (e.g. some `const char *`), the UART would only transfer `0x00` bytes. This made e.g. `tests/fmt_print` fail for all targets using the `nrf5280` cpu.
This PR fixes this issue by chunk-wise copying the TX data into RAM before sending it in case the data is coming from ROM.
Run e.g. the `tests/fmt_print` test on the `nrf52840dk` or the `reel` or similar. Without this PR the test will fail, with this PR it will succeed.
issue found in #11096

cpu/nrf52840: fix UART DMA when data is in ROM

---

cpu/saml1x/cpu.c

According to datasheet, SAML1X should be set in PL2 with 1 WaitState if it runs at 16MHz (which is currently the default speed supported).
See Chap 46.12 from the [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAM-L10-L11-Family-Data-Sheet-DS60001513C.pdf)
run any tests you want on SAML10-XPRO or SAML11-XPRO
@emmanuelsearch could you check that your PR works with this one ?

cpu/saml1x: set wait state according to datasheet

---

boards/arduino-zero/Makefile.features
boards/arduino-zero/include/periph_conf.h
boards/samr21-xpro/Makefile.features
boards/samr21-xpro/include/periph_conf.h
cpu/sam0_common/include/periph_cpu_common.h
cpu/sam0_common/include/sam_usb.h
cpu/sam0_common/periph/usbdev.c
drivers/include/periph/usbdev.h

This PR adds a USB peripheral driver for the sam0 device class. The driver is much WIP as some details still have to be thought out.
Nothing yet, a follow-up is required to actually initialize the usb device.
depends on #9830

sam0_common: Add USB peripheral driver

---

tests/lwip_sock_udp/main.c

This provides the same test I provided for the GNRC implementation in #9453 for both lwIP's IPv4 and IPv6 implementation
Same test for GNRC introduced in #9453.

tests: provide tests for reception on sock with port 0

---

sys/include/net/ndp.h
sys/net/gnrc/network_layer/ipv6/nib/nib.c
sys/net/gnrc/network_layer/ndp/gnrc_ndp.c
tests/gnrc_ipv6_nib/main.c
tests/gnrc_ipv6_nib_6ln/main.c

As promised in https://github.com/RIOT-OS/RIOT/pull/10985#discussion_r256117858 here are some documented defines for the hop-limit value for NDP messages.
`gnrc_networking` should still compile.
Follow-up to https://github.com/RIOT-OS/RIOT/pull/10985.

ndp: provide define for common hop-limit

---

cpu/stm32_common/periph/rtt.c

According to stm32 manual ARR and CMP registers may have unpredictable results if ARROK and CMPOK flags are not checked:
```
The ARROK flag and the CMPOK flag in the LPTIM_ISR register indicate when the write
operation is completed to respectively the LPTIM_ARR register and the LPTIM_CMP
register.
After a write to the LPTIM_ARR register or the LPTIM_CMP register, a new write operation
to the same register can only be performed when the previous write operation is completed.
Any successive write before respectively the ARROK flag or the CMPOK flag be set, will
lead to unpredictable results.
```
In the same vein, CNT register should be read twice to ensure the value is correct:
```
It should be noted that for a reliable LPTIM_CNT register read access, two consecutive read
accesses must be …
```

cpu/stm32_common: fix rtt registers access

---

drivers/mrf24j40/mrf24j40_netdev.c

mrf24j40 version of the `iol->iol_len==0` issue described in #11163
See #11163
#11163

mrf24j40: don't load data if iol->iol_len == 0

---

pkg/ubasic/Makefile
pkg/ubasic/Makefile.include
pkg/ubasic/doc.txt
pkg/ubasic/ubasic.mk
pkg/ubasic/ubasic_tests.mk
tests/pkg_ubasic/Makefile
tests/pkg_ubasic/tests/01-run.py

As we all know supporting more programming language is important and BASIC is an important programming language. So here is a port for it.
Run
```sh
make -C tests/pkg_ubasic all test
```
on a board of your liking. The tests were provided by the package itself.
None

pkg: Initial introduction of ubasic package

---

examples/nimble_scanner/README.md

This PR fixes an obvious typo in the `examples/nimble_scanner` application README.
Just compare the README with the [puts code](https://github.com/RIOT-OS/RIOT/blob/master/examples/nimble_scanner/main.c#L52) of the application.
Found while looking at #11372

examples/nimble_scanner: fix typo in README

---

cpu/atmega_common/thread_arch.c

This PR make the remaining RAM of AVR MCUs available as heap for `malloc/free` functions of `avr-libc`.
`__malloc_heap_end` is set to 0 by default. Therefore, `malloc` checks `__brkval` against the SP instead of `__malloc_heap_end`.
```c
cp = __malloc_heap_end;
if (cp == 0)
cp = STACK_POINTER() - __malloc_margin;
if (cp <= __brkval)
```
In thread mode, however, the SP is is always in `.data` section below `__bss_end` and thus below `__malloc_heap_start`. Since `__brkval` points at least to `__malloc_heap_start`, the check always fails.
This PR sets `__malloc_heap_end` to the current SP before switching to thread mode. Thus, `malloc` checks `__brkval` against `__malloc_heap_end`.
Use `tests/malloc` to check `malloc/free` functions of `avr-libc`, for example:
```
make -C tests/malloc …
```

cpu/atmega_common: make remaining RAM available as heap

---

sys/net/gnrc/netif/ieee802154/gnrc_netif_ieee802154.c

Fixes https://github.com/RIOT-OS/RIOT/issues/11398
With the descriptions given in https://github.com/RIOT-OS/RIOT/issues/11398, read the code ;-).
(I'll provide a test case soon-ish)
Fixes https://github.com/RIOT-OS/RIOT/issues/11398

gnrc_netif_ieee802154: check if mhr_len is lesser than nread

---

pkg/semtech-loramac/doc.txt

This PR is improving the code snippet provided in the Loramac-node package documentation by showing that the send function return code should be checked before calling the receive function.
It also fixes a broken link (well no link in fact) to the upstream package in github + adds a missing newline at the end of the file.
Just read the generated documentation.
None

pkg/semtech-loramac: improve and cleanup doxygen doc

---

release-notes.txt

Release notes for 2019.04 release
Please read through, and check that, for the area of the OS which you're familiar with, that the existing information is correct, and there are no omissions.

Update release notes with 2019.04 notes [backport 2019.04]

---

boards/pyboard/board.c
core/clist.c
core/include/clist.h
sys/event/callback.c
sys/event/event.c
sys/event/timeout.c
sys/include/event.h
sys/include/event/callback.h
sys/include/event/timeout.h
sys/include/iolist.h
sys/include/net/nanocoap.h
sys/include/net/nanocoap_sock.h
sys/include/riotboot/flashwrite.h
sys/include/riotboot/hdr.h
sys/include/riotboot/slot.h
sys/iolist/iolist.c
sys/net/application_layer/nanocoap/nanocoap.c
sys/net/application_layer/nanocoap/sock.c
sys/random/xorshift.c
sys/riotboot/flashwrite.c
sys/riotboot/hdr.c
sys/riotboot/slot.c

Over the last years, most of my RIOT work was done as part of the IOTPUSH project, a joint project between Inria and Freie Universität Berlin.
This PR updates some copyright statements accordingly, adding both Freie Universität Berlin and Inria.

add copyrights from IOTPUSH project

---

dist/tools/buildsystem_sanity_check/check.sh

Check that some variables are not exported in the build system.
This should track variables that managed to not be exported anymore so
that they do not reappear in a BSP.
It is not a whitelist but just a way to keep things cleaned in the
future.
No error when running the script as will CI check in `static-tests`.
No error when running `shellcheck` on the script.
Applying this diff will report a lot of errors as they are still exported.
```
diff --git a/dist/tools/buildsystem_sanity_check/check.sh b/dist/tools/buildsystem_sanity_check/check.sh
index e18ca6776..bd4071fd8 100755
--- a/dist/tools/buildsystem_sanity_check/check.sh
+++ b/dist/tools/buildsystem_sanity_check/check.sh
@@ -50,6 +50,8 @@ check_not_parsing_features() {
UNEXPORTED_VARIABLES=()
UNEXPORTED_VARIABLES+=('FLASHFILE') …
```

dist/tools/buildsystem_sanity_check: add an export variable check

---

examples/emcute_mqttsn/README.md

A complete newcomer to the application might not know, that they have to
run `make term` first.
Read
Noticed while helping out with https://github.com/RIOT-OS/RIOT/issues/11494

examples/emcute_mqttsn: make into native application more obvious

---

dist/tools/openocd/openocd.sh

tools/openocd.sh: try to probe the board for real flash address
> ### Note, this only for 'bin' flashing
> All this handling is only done when flashing binaries, so currently only with `riotboot` and not for elf or hex files. This code is not executed in the normal flashing.
Some boards have a configuration of the flash bank with an address of 0
when it actually starts as 0x08000000 but openocd relies on probing
the hardware at runtime.
This now allows to first probe the board to get the actual value.
If probing fail for any reason, return the value from the configuration.
This can happen when the board is unreachable so at least give a valid
output instead of an error.
This will allow correct flash detection on for example the `stm32f3` and
`stm32l4` which have a configured address of 0. …

tools/openocd.sh: try to probe the board for real flash address

---

bootloaders/riotboot/README.md

Fixes bootloader README typos and error in  command description.
CI checks should be enough.

bootloader/README: fix typos

---

sys/include/net/sock/util.h

Adapts #11558  in accordance to #10566.
When reviewing the PR I didn't take care in enforcing #10566. I'm pushing this PR to fix that overlook on my side.
Run CI
#11558

sock: expose configuration file

---

cpu/sam0_common/periph/timer.c

- The frequency parameter is unused now, so don't check it.
- The hardware provides dedicated SET/CLR registers to do away with read-modify-write cycles, so don' t do read-modify-write on them, just write them.
- Workaround a possible hardware bug on SAMD5x where the `TC_SYNCBUSY_CTRLB` bit is not immediately set after writing `TC_CTRLBSET_CMD_READSYNC` - loop until the bit is really set.
- replace magic value by constant define.

sam0/timer: various fixes

---

cpu/samd5x/cpu.c

There is still a bug with the samd5x code:
I first sourced the DPLL0 from XOSC32K where it doesn't need a reference clock, so I deleted the reference clock configuration.
Then I wanted to have more flexibility, e.g. running the system entirely from the ULPOSC32K without the need for an external oscillator, so I sourced the DPLL0 from the 32kHz GCLK1 but forgot to add back the reference clock setup (this can be GCLK1 too).
Now for some reason this worked fine until I flashed an image with riotboot. A colleague noted that this used to work before, so I began searching as to what changed in the meantime. I could narrow it down to the dpll setup and indeed with this patch applied, riotboot can load an image again.

cpu/samd5x: CPU init fixes

---

cpu/nrf52/periph/usbdev.c

This PR adds USB suspend/resume state detection to the nrf52840 usbdev peripheral. This is essential for detecting when the host side suspends bus activity and thus when not to expect any periodic transfer to be serviced
1. Enable debug in `sys/usb/usbus/usbus.c` to print USB suspend/resume info.
2. flash on one of the nrf52840 based boards
3. Plug the device usb port in a Linux based host (needed for next steps)
4. Find out which usb port is used, `dmesg` usually shows this info, should be something along the lines of `3-9.4`, depends on the usb bus, hub and port it is plugged into.
5. use:
```
echo "0" > "/sys/bus/usb/devices/$PORT/power/autosuspend"
echo "auto" > "/sys/bus/usb/devices/$PORT/power/level"
```
to force the port in suspend mode.
6. Verify that the device prints `usbus: USB …

nrf52: Add suspend/resume detection to usbdev

---

tests/driver_sx127x/main.c

This PR uncrustifies the `main.c` file of the sx127x test.
Check that changes make sense

drivers/sx127x: uncrustify main file

---

boards/msbiot/doc.txt

- Updated outdated information
- Fixed Markdown to generate desired output
- Replaced references to source code by references to their documentation
- Correct use of units (b = bit, B = byte, Ki = 1024, K = 1000, ...)
- Check if CI detects any issues with Doxygen
- All remaining MSB-IoT Boards are now owned by our work group, so no one is really affected by this change except of us
- As long as nothing unrelated sneaked into this PR, I think little to no review/testing is required, as basically only our work group is affected.
None

boards/msbiot: Updated/fixed documentation

---

.gitignore

Since I'm using mypy to lint python files, it's cache directory shows up in "git status".
This PR adds that folder to .gitignore.

.gitignore: add .mypy_cache/

---

sys/net/gnrc/application_layer/tftp/gnrc_tftp.c

`gnrc_tftp` performs an out-of-bounds memory access when comparing defined TFTP modes (`netascii`, `octet`, or `mail`) with the one in the received TFTP packet. This is due to the fact that the code currently doesn't check whether the mode string used for comparison is longer than the  amount of remaining bytes in the packet. This PR introduces such a check.

gnrc_tftp: Fix out-of-bounds memory access when comparing modes

---

pkg/nanocbor/Makefile
pkg/nanocbor/Makefile.include
pkg/nanocbor/Makefile.nanocbor
pkg/nanocbor/doc.txt
pkg/nanocbor/include/nanocbor/config.h
tests/pkg_nanocbor/Makefile
tests/pkg_nanocbor/main.c
tests/pkg_nanocbor/tests/01-run.py

Nanocbor is a small CBOR encoder and parser aiming to provide almost full CBOR spec support with minimal flash footprint
execute the test application.
To be completely honest, I was too lazy to write a decoder example and assumed the upstream package is tested well enough to guarantee a functioning package :laughing: 
None

nanocbor: Initial support for the nanocbor package

---

sys/net/gnrc/application_layer/tftp/gnrc_tftp.c

gnrc_tftp: Add minimum packet length check [backport 2019.07]

---

sys/net/application_layer/nanocoap/nanocoap.c

Adds internal documentation for a couple of functions related to option handling. I found myself needing to understand the inputs and output in detail, and this documentation means we don't have to figure it out each time. ;-)
N/A, just documentation
N/A

net/nanocoap: document internal option functions

---

release-notes.txt

Release notes for 2019.07 release
Please read through, and check that, for the area of the OS which you're familiar with, that the existing information is correct, and there are no omissions.

release-notes.txt: add notes for 2019.07 release

---

release-notes.txt

Release notes for 2019.07 release
Please read through, and check that, for the area of the OS which you're familiar with, that the existing information is correct, and there are no omissions.

release-notes.txt: add notes for 2019.07 release [backport 2019.07]

---

drivers/include/ccs811.h
sys/include/hashes/sha256.h
sys/include/hashes/sha3.h

fix common typo usefull to correct useful.
just documentation change.
Read.
None.

fix typo: usefull -> useful

---

sys/include/net/tcp.h

just documentation change.
Read.
None.

sys/net: fix typos in docu

---

sys/posix/sockets/posix_sockets.c

See https://github.com/RIOT-OS/RIOT/pull/10308#issuecomment-526712394
¯\\_(ツ)\_/¯
Discovered in but independent of https://github.com/RIOT-OS/RIOT/pull/10308

posix_socket: set sock for returned socket on accept()

---

cpu/kinetis/periph/timer.c

Spinning for the correct time has the side effect that it may cause
infinite recursion if the callback function calls timer_set.
timer_set->callback->...->timer_set->callback->...->timer_set-> infinity
In theory, the drawback is that the callback for very short timeouts
(<2 lptmr ticks) may be delayed up to 2 lptmr ticks (61 µs)
In practice however, tests performed using tests/bench_timers shows that
this change only affects the accuracy of the timer target when timer_set
is called with a timeout of 0, which results in a delay of 30 µs.
Run the test in #10019 on a kinetis board with an LPTMR configuration (e.g. any of the frdm boards, for k64f, see #9930) with this PR applied.
Regression test for this bug #10019 
LPTMR configuration for frdm-k64f: #9930

kinetis: lptmr reload instead of spinning

---

sys/net/gnrc/transport_layer/tcp/gnrc_tcp_pkt.c

From my understanding of the `gnrc_pktbuf_add` documentation the size parameter should specify the length of the given data not the desired length of the requested pktbuf. It seems to me that if the packet should have a certain size `gnrc_pktbuf_realloc` must be used.
None, read the code. Just noticed this while reading the source, I might be entirely wrong about this.

gnrc_tcp: Fix invocation of gnrc_pktbuf_add

---

sys/net/gnrc/transport_layer/tcp/gnrc_tcp_option.c

gnrc_tcp: abort on unknown option

---

sys/net/gnrc/netif/ethernet/gnrc_netif_ethernet.c

#12248 ## Contribution description
A received packet is outputted in DEBUG _after_ it was already parsed, but with a reference to the already parsed header. The result is that there can be some garbage in the output and the packet is not dumped in total. As without parsing we do not have access to the header yet, we
use the `gnrc_netif_addr_to_str()` helper function instead of parsing the destination address by hand.
Compile `examples/gnrc_networking` for `native` with `ENABLE_DEBUG=1` in `sys/net/gnrc/netif/ethernet/gnrc_netif_ethernet.c`. Send some packets to the application e.g. using `ping6`. You will get something like
```
gnrc_netif_ethernet: received packet from 02:ca:6d:11:65:c4 of length 78
00000000  02  58  97  2A  A6  2D  02  CA  6D  11  65  C4  86  DD  60  00
00000010  00  00 …
```

gnrc_netif_ethernet: fix debug output for received packet

---

boards/p-l496g-cell02/Makefile
boards/p-l496g-cell02/Makefile.dep
boards/p-l496g-cell02/Makefile.features
boards/p-l496g-cell02/Makefile.include
boards/p-l496g-cell02/board.c
boards/p-l496g-cell02/doc.txt
boards/p-l496g-cell02/include/board.h
boards/p-l496g-cell02/include/gpio_params.h
boards/p-l496g-cell02/include/periph_conf.h
cpu/stm32l4/include/cpu_conf.h
cpu/stm32l4/include/periph_cpu.h

This PR adds support for the [P-L496G-CELL02](https://www.st.com/en/evaluation-tools/p-l496g-cell02.html) board which comes with an LTE-M radio extension. The board also provides an Arduino pinout.
All available UARTs are configured and have been tested with success. The I2C is also configured and tested. The SPI available on Arduino pinout is also available and tested.
- Run `./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . p-l496g-cell02` and you should get the following result:
```
ERROR:p-l496g-cell02:Tests failed: 5
Failures during test:
- [tests/driver_grove_ledbar](tests/driver_grove_ledbar/test.failed)
- [tests/driver_my9221](tests/driver_my9221/test.failed)
- [tests/gnrc_ipv6_ext](tests/gnrc_ipv6_ext/test.failed)
- …
```

boards/p-l496g-cell02: add support

---

cpu/nrf52/periph/usbdev.c

When writing the usbdev driver for the nrf52840, I forgot to implement code for the optional data stage of control write transfers. This PR adds the necessary code for handling the data from the data stage.
Probably best tested with the STDIO test from #11085. Without this PR the STDIO should fail to set up or take a long time to initialize. With this PR it should work again.
None

nrfusb: Fix data stage handling of control writes

---

tests/pkg_ubasic/Makefile

The test code prints runtimes using floats, but it is built without specifying printf float support. This PR adds the corresponding dependency.
Output on master:
```
main(): This is RIOT! (Version: 2019.10-devel-1163-g1663c)                                                                         
Running test #1... done. Run time:  s                                                                                              
Running test #2... done. Run time:  s                                                                                              
Running test #3... done. Run time:  s                                                                                              
Running test #4... done. Run time:  s …
```

tests/pkg_ubasic: add print_float dependency

---

sys/net/gnrc/transport_layer/tcp/gnrc_tcp.c

This PR fixes debugging message strings.

gnrc_tcp-fix debug message

---

sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c

This PR contains an optimization for gnrc_tcp: 
Normally gnrc_tcp reopened its receive window if there is enough space available to store a payload of negotiated MSS size. This is done by sending a packet with the ACK - Flag set.
With this PR this mechanism is optimized by not sending a window reopening packet if the peer has sent a packet with the FIN-Bit set before. It prohibits window reopening in a case then there is no data to receive anyway.

gnrc_tcp: do not reopen recv window on closed connection

---

tests/gnrc_tcp/README.md
tests/gnrc_tcp/tests/05-garbage-pkts.py
tests/gnrc_tcp/tests/shared_func.py

This provides regression tests for some issues that were found in the past. The respective issues are quoted in the comments. I actually already found a regression when implementing these (see #12368).
```sh
BOARD="<pick one>" make -C tests/gnrc_tcp flash
sudo make -C tests/gnrc_tcp test
```
Require #12368 to work.

tests/gnrc_tcp: provide regression tests for fixed issues

---

pkg/cayenne-lpp/Makefile

This version contains a fix with barometric pressure values
See https://github.com/aabadie/cayenne-lpp/pull/8 for details
- Test on native: 
```
make -C tests/pkg_cayenne-lpp all test
```
- Test on a board:
```
make BOARD=b-l072z-lrwan1 -C tests/pkg_cayenne-lpp all test
```
None in RIOT.

pkg/cayenne-lpp: bump version to 0.1.1

---

drivers/sx127x/sx127x.c

This PR is an attempt to fix #11913: the sx127x driver reset sequence fails if the reset pin is undefined but some board don't provide it.
As initially proposed in #11913, it just don't return an error if the reset pin is not undefined but just skip the reset sequence.
Note that I moved the block initializing TX/RX switch pins before the reset sequence. I'm not sure what consequence this could have.
- Reset sequence should still work for board providing the reset pin
- The driver should work for not providing the reset pin
fixes #11913

drivers/sx127x: skip reset sequence if pin is undefined

---

tests/gnrc_udp/Makefile

This is a PR in preparation (and anticipation :wink:) of RIOT-OS/Release-Specs#137. While adding IPv6 fragmentation to the test shouldn't really harm, we should wait for the discussion there, before we add unnecessary code to the test.
Should still compile, the proposed release specs (TBD), resulting from RIOT-OS/Release-Specs#137 should pass.
RIOT-OS/Release-Specs#137

tests: prepare for RIOT-OS/Release-Specs#137

---

tests/ssp/Makefile

Ensure `make info-boards-supported` outputs the same with/without this PR.
Based on #9081.

tests/ssp: make use of architecture features

---

sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c

While 485dbd1fdac9c965c1f734b1dda711b35bb4ac1a (from #12175) was right in assuming that the for most ICMPv6 error messages the originating packet's destination address must not be a multicast, this is not the case for _all_ ICMPv6 error messages (see [RFC 4443], section 2.4(e.3)). Additionally, 485dbd1fdac9c965c1f734b1dda711b35bb4ac1a removed the check for the source address ([RFC 4443], section 2.4(e.6)), which this PR re-adds.
[RFC 4443]: https://tools.ietf.org/html/rfc4443#section-2.4
- Read the RFC and confirm, that the rules are applied correctly now.
- [Release specifications for ICMPv6 errors should still pass](https://github.com/RIOT-OS/Release-Specs/blob/master/10-icmpv6-error/10-icmpv6-error.md).
Accompanying #12440, but not necessary to fix the problem there

gnrc_icmpv6_error: consider originator's destination address correctly

---

sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c

While 485dbd1fdac9c965c1f734b1dda711b35bb4ac1a (from #12175) was right in assuming that the for most ICMPv6 error messages the originating packet's destination address must not be a multicast, this is not the case for _all_ ICMPv6 error messages (see [RFC 4443], section 2.4(e.3)). Additionally, 485dbd1fdac9c965c1f734b1dda711b35bb4ac1a removed the check for the source address ([RFC 4443], section 2.4(e.6)), which this PR re-adds.
[RFC 4443]: https://tools.ietf.org/html/rfc4443#section-2.4
- Read the RFC and confirm, that the rules are applied correctly now.
- [Release specifications for ICMPv6 errors should still pass](https://github.com/RIOT-OS/Release-Specs/blob/master/10-icmpv6-error/10-icmpv6-error.md).
Accompanying #12440, but not necessary to fix the problem there

gnrc_icmpv6_error: consider originator's destination address correctly [backport 2019.10]

---

sys/usb/usbus/cdc/acm/cdc_acm.c

This adds an interface association descriptor to the USBUS CDC ACM code. This should enable the Windows operating system (at least version 10) to correctly enumerate, detect and use the CDC ACM functionality in RIOT.
Currently RIOT describes itself as a composite device to host computers. When this is used, WIndows uses interface association descriptors to detect logical interface collections on the device[1].
Flash the `tests/usbus_cdc_acm_stdio` test on a board, Windows should correctly detect the COM device and allow usage of said COM device.
More extensive test (as already done by @chrysn) would be to add the CDC ECM in different configurations and test that Windows does not enable the CDC ECM functionality, but does offer the COM functionality of the device.
(Linux and MacOS should …

CDCACM: Add interface association descriptor before CDC ACM control interface descriptor

---

sys/include/event.h

sys/event: fix typo: imlementation -> implementation

---

pkg/doc.txt

remove reference to old removed file in documentation
read
none

pkg: docu: remove old pkg/Makefile.svn

---

core/sched.c

core/sched: remove duplicate include of irq.h

---

release-notes.txt

Release notes for 2019.10 release
Please review the sections you are familiar with and markup any omissions or mistakes. Thanks!

release-notes.txt: add notes for 2019.10 release [backport 2019.10]

---

sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c

When decoding IPHC in a fragmented datagram, relying on the size of the allocated space for the decoded packet is wrong when fragments are forwarded and decoded on an intermediate node (for which the reassembly buffer's space is used): Using the full datagram size for allocation in this case would be wasteful, so the allocated space is only marginally larger than the fragment's compressed form. This in turn results in the wrong UDP payload size being chosen and even worse being forwarded to the subsequent nodes.
This change uses the (virtual) reassembly buffer's `datagram_size` instead of relying on the allocated space for the encoded datagram/fragment.
Send a fragmented, IPHC+NHC-compressed UDP packet from one host to another. The packet should still be received.
- UDP Client: …

gnrc_sixlowpan_iphc_nhc: determine UDP hdr length from RB

---

cpu/sam0_common/periph/spi.c

Currently, [`spi_acquire()`](https://github.com/RIOT-OS/RIOT/blob/307faa460a03841101159469777f69a073a429e7/cpu/sam0_common/periph/spi.c#L114) will always re-configure the SPI bus.
If the configuration did not change, this is entirely unnecessary and makes SPI operations take longer than needed.
Instead, save the current configuration and skip the initialization if it didn't change since the last call.
All SPI operations should still continue to work as before.
A simple ping test with an spi-connected radio should already show the improvement:
**before:**
```
2019-10-08 13:56:30,361 #  ping6 fe80::d0ae:c1b:2054:58f%7
2019-10-08 13:56:30,373 # 12 bytes from fe80::d0ae:c1b:2054:58f: icmp_seq=0 ttl=64 rssi=-21 dBm time=5.664 ms
2019-10-08 13:56:31,645 # 12 bytes from fe80::d0ae:c1b:2054:58f: …
```

sam0/spi: Don't re-configure SPI device when not needed

---

pkg/ccn-lite/Makefile.dep
pkg/gecko_sdk/Makefile.dep
pkg/gecko_sdk/Makefile.include
pkg/jerryscript/Makefile.dep
pkg/libcoap/Makefile.dep
pkg/ndn-riot/Makefile.dep
pkg/ndn-riot/Makefile.include
pkg/openthread/Makefile.dep
pkg/tinydtls/Makefile.dep
pkg/umorse/Makefile.dep

While recently working on blacklisting some architecture at package level, I noticed that dependency handling in some packages was not fully inline with the current standard in RIOT.
This PR is cleaning up what I found problematic:
- there's no need to protect the module dependencies in an if block that checks if the module itself is loaded. This is done already and automatically in the global Makefile.dep:
https://github.com/RIOT-OS/RIOT/blob/be39169bd41f50e48c26f0b63312fe372b81147f/Makefile.dep#L982
- dependencies of a package should be provided in a dedicated `Makefile.dep` and not in their `Makefile.include`
- in `openthread` and `tinydtls`, some conditional addition where always true when the package is loaded, the checks are simply removed, as they are useless.
A green Murdock …

pkg: cleanup management of dependencies

---

CONTRIBUTING.md

Hint to also search closed PRs when looking for previous work before contributing.
E.g., #12740 was opened without considering a previous closed PR. Author claims to have searched only for open ones (as that's the default).

CONTRIBUTING.md: hint to also search closed PRs for previous work

---

CONTRIBUTING.md

General fixes throughout documentation. Made sentence in bug reports section easier to understand.
Changed "Once you have verified that they haven't," to "Once you have verified that the bug you have found hasn't been reported," 
This was done to make it more clear what hasn't been reported.

Minor readability fixes to CONTRIBUTING.md

---

boards/nucleo-f207zg/Makefile.dep
boards/nucleo-f207zg/Makefile.features
boards/nucleo-f207zg/include/periph_conf.h
examples/default/Makefile

Added Ethernet support for the Nucleo-f207zg

boards/nucleo-f207zg: add ethernet configuration

---

doc/doxygen/riot.doxyfile
doc/doxygen/src/build-system-basics.md

I've tried to resume some of the advice I've seen @cladmi @jcarrano and other give on `Makefile` variable declaration/evaluation. 
- Have I made a technical mistake int he description?
- Does naming make sense?
- Does the placing make sense?
Part of #8420

doc/doxygen: add build-system-basics.md

---

examples/javascript/Makefile
examples/javascript/main.c

This PR makes examples/javascript make use of the newly merged blob utility makefile.
Test if the example still works, and if the header and main.c get rebuild when changing main.js.
#11870

examples/javascript: make use of blob.inc.mk

---

doc/doxygen/src/mainpage.md

Rearranged sentence so that only one 'and' is used in the sentence. Did the same for line 
114.

Minor text fix for mainpage.md

---

pkg/lwip/contrib/lwip.c

Add glue code to initialize Ethernet and add netif for stm32 in lwip_bootstrap. 
LWIP now supports STM32. 
**Before:**
tests/lwip --> send_ip() --> fails, because there is no available netif
**After:**
tests/lwip --> send_ip() --> works

pkg/lwip: add STM32 support

---

pkg/pkg.mk

Remove git command output while building packages. 
Run make in RIOT app which uses packages.

pkg: make build output quiet

---

drivers/Makefile.dep
drivers/Makefile.include
drivers/include/shtc1.h
drivers/shtc1/Makefile
drivers/shtc1/include/shtc1_params.h
drivers/shtc1/include/shtc1_regs.h
drivers/shtc1/shtc1.c
drivers/shtc1/shtc1_saul.c
sys/auto_init/auto_init.c
sys/auto_init/saul/auto_init_shtc1.c
tests/driver_shtc1/Makefile
tests/driver_shtc1/README.md
tests/driver_shtc1/main.c

- SAUL integration added to this driver.
- Codefixes.
Testboard: SAMR21-xpro
Depends on PR #7866.

drivers/shtc1: Initial support for the SHTC1 temperature and humidity sensor

---

pkg/Makefile.git
pkg/Makefile.http
pkg/heatshrink/Makefile
pkg/openthread/Makefile
pkg/pkg.mk

A few improvements w.r.t. package (metadata) handling. I cherry picked most of them from #11553 by @cladmi , but that PR is stalled at the moment.
Murdock should be happy when building the tests for the packages.
#11553

pkg: minor improvements to metadata handling

---

sys/shell/commands/sc_nimble_netif.c

Currently, there is no way to get information on BLE connection timings using the `ble` shell command. However, for e.g. automated experiments etc this would be very useful.
This PR adds outputting information on BLE connection timing to the `ble info` shell command. In particular, it will now output the i) connection interval in ms, ii) the supervision timeout in ms, as well as iii) the slave latency for each open connection.
E.g. using the `gnrc_networking` example with any board supporting `nimble_netif` (e.g. nrf52dk, nrf52840dk, ...):
- connect two boards (calling `ble adv a` on the first, calling `ble connect a` on the second)
- call `ble info` on each node -> you should see the timing information for the open connection
- call `ble update 0 90 1000` on any of the two nodes
- call …

shell/sc_nimble_netif: add timing info to ble info

---

boards/sltb001a/doc.txt

This updates the documentation for the SLTB001a.
- Updated links
- Updated specifications
- Enforced line length
Documentation should build and show the page.
#13099

boards/sltb001a: update documentation

---

boards/slstk3401a/doc.txt

This updates the documentation for the SLSTK3401a.
- Updated links
- Updated specifications
- Enforced line length
Documentation should build and show the page.
#13099

boards/slstk3401a: update documentation

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

This feature was removed without replacment in [71a7dbf91856d](https://github.com/RIOT-OS/RIOT/commit/71a7dbf91856dc221a5615e29587c6b8309b08d2#diff-f9bf85cb337616822921e4230ede1572L857-L869), but it can
still be useful.
Uncomment the definition for `GNRC_IPV6_STATIC_LLADDR` in `examples/gnrc_networking/Makefile`
```diff
diff --git a/examples/gnrc_networking/Makefile b/examples/gnrc_networking/Makefile
index 0ae56343f9..6628e113ff 100644
--- a/examples/gnrc_networking/Makefile
+++ b/examples/gnrc_networking/Makefile
@@ -39,8 +39,8 @@ DEVELHELP ?= 1
-#IPV6_STATIC_LLADDR ?= '"fe80::cafe:cafe:cafe:1"'
-#CFLAGS += -DGNRC_IPV6_STATIC_LLADDR=$(IPV6_STATIC_LLADDR)
+IPV6_STATIC_LLADDR ?= '"fe80::cafe:cafe:cafe:1"'
+CFLAGS += -DGNRC_IPV6_STATIC_LLADDR=$(IPV6_STATIC_LLADDR)
```
Compile and flash to …

gnrc_ipv6_nib: allow for configuration of static link-local addresses

---

examples/suit_update/README.md

This PR extends the doc to show how to perform `suit_updates` over ble. Two cases are added:
- RIOT ble border router + ble suit-device
- Linux ble host + ble-device
We are using `autoconn` so the setup is minimal and no changes to the code are necessary.
NOTE: I had some issues with my local driver for BLE, I ended up using a 4.0 bluetooth usb dongle and it worked straight away.
- 0e3097a is the main commit to review
- 7a911dc might be included in #12361
- eb6522a will be PR'd separately.
Testing here should mean following the doc and being able to perform suit-updates in both scenarios. 
I would recommend rebasing on #11553 so the compilation of the pkg's isn't triggered for every `flash`, `publish`.
Depends on ~#11818~ and #12361

examples/suit_update: add ble documentation in README

---

pkg/tensorflow-lite/Makefile.include

As reported in https://github.com/RIOT-OS/RIOT/issues/13133#issuecomment-575141102 (I had @fjmolinas'd agreement IRL) this PR blacklists the LLVM toolchain on Cortex-M CPUs.
Since I have no idea of the origin of the problem (where it's a problem with the fully connected operator, a misuse of TensorFlow quantization or anything I can't think of), I opened an issue on TensorFlow with the hope that they have an idea and could give some advice.
Check that LLVM is blacklisted for Cortex-M:
<details>
```
TOOLCHAIN=llvm  make BOARD=stm32f723e-disco -C tests/pkg_tensorflow-lite flash term
make: Entering directory '/work/riot/RIOT/tests/pkg_tensorflow-lite'
The selected TOOLCHAIN=llvm is blacklisted: llvm
/work/riot/RIOT/tests/pkg_tensorflow-lite/../../Makefile.include:843: *** You can let the …
```

pkg/tensorflow-lite: blacklist LLVM for cortexm cpu arch

---

pkg/tensorflow-lite/Makefile.include

As reported in https://github.com/RIOT-OS/RIOT/issues/13133#issuecomment-575141102 (I had @fjmolinas'd agreement IRL) this PR blacklists the LLVM toolchain on Cortex-M CPUs.
Since I have no idea of the origin of the problem (where it's a problem with the fully connected operator, a misuse of TensorFlow quantization or anything I can't think of), I opened an issue on TensorFlow with the hope that they have an idea and could give some advice.
Check that LLVM is blacklisted for Cortex-M:
<details>
```
TOOLCHAIN=llvm  make BOARD=stm32f723e-disco -C tests/pkg_tensorflow-lite flash term
make: Entering directory '/work/riot/RIOT/tests/pkg_tensorflow-lite'
The selected TOOLCHAIN=llvm is blacklisted: llvm
/work/riot/RIOT/tests/pkg_tensorflow-lite/../../Makefile.include:843: *** You can let the …
```

pkg/tensorflow-lite: blacklist LLVM for cortexm cpu arch [backport 2020.01]

---

cpu/nrf52/include/nrf802154.h
cpu/nrf52/radio/nrf802154/Kconfig
cpu/nrf52/radio/nrf802154/nrf802154.c
drivers/Kconfig.net

This PR adds Clear Channel Assessment support for the nRF802154 radios using CCA Mode 1 (Energy above threshold).
I implemented the following NETOPTs:
- NETOPT_IS_CHANNEL_CLR: Perform CCA and return NETOPT_ENABLE if the channel is clear.
- NETOPT_CCA_THRESHOLD: Set the CCA ED threshold in dBm.
I'm also introducing a `CONFIG_NRF802154_CCA_THRESH_DEFAULT` for setting the default CCA threshold.
- With the help of a jammer (or ping command with a very short ms interval) check the results of `dev->driver->get(dev, NETOPT_IS_CHANNEL_CLR , &clear_channel, sizeof(clear_channel)`. While jamming you should see several "busy" responses (NETOPT_DISABLED)
- Try changing the value of NRF802154_CCA_THRESH_DEFAULT using Kconfig (`Drivers > Configure nRF802154 > Default CCA threshold`. Smaller values tend …

nRF802154: implement CCA

---

boards/hifive1/Makefile.include
boards/hifive1b/Makefile.include

This PR removes the useless include if the stdio_uart module in the hifive1* boards. This module is already pulled-in by default by the main Makefile.dep file, so there's no need to include it again at board level.
Simply build, flash and run an example with a shell and check that stdio works:
<details>
```
$ make BOARD=hifive1b -C examples/saul flash term
make: Entering directory '/work/riot/RIOT/examples/saul'
Building application "saul_example" for "hifive1b" with MCU "fe310".
"make" -C /work/riot/RIOT/boards/hifive1b
"make" -C /work/riot/RIOT/cpu/fe310
"make" -C /work/riot/RIOT/cpu/fe310/nano
"make" -C /work/riot/RIOT/cpu/fe310/periph
"make" -C /work/riot/RIOT/cpu/fe310/vendor
"make" -C /work/riot/RIOT/drivers
"make" -C …
```

boards/hifive1*: remove useless stdio_uart include

---

tests/periph_rtc/main.c

This PR fixes a system lock that occurs when the `newlib` with real locking functionality is used instead of the `newlib_nano`.
`tests/periph` calls the functions `rtc_get_alarm` and `rtc_set_alarm` from an ISR. Depending on the implementation of `periph_rtc`, these functions may use `newlib` functions such as `localtime` and `mktime`, which in turn call the `newlib` lock function `__tz_lock`. This can lead to a system lock if the `newlib` with real lock functionality is used instead of the `newlib_nano`.
This PR moves the call of the `rtc_get_alarm` and `rtc_set_alarm` functions from interrupt context to the thread context of the main thread. The ISR just sends a message to the main thread to inform the about the interrupt. The interrupt is then handled in thread context.
The problem was …

tests/periph_rtc: fix system locks in ISR

---

drivers/ds18/ds18.c
tests/driver_ds18/Makefile

Fix `ds18` temperature conversion for issue #13287
I tested PR on my hardware (Arduino Nano ATmega328p and DS18B20 sensor). Also I tests for different input values to cover boundary values, negative and positive values and [related issues](https://github.com/RIOT-OS/RIOT/commit/1783b3da55902431198a295560cc4a473aa711ad).
Fixes #13287

Fix ds18 temperature conversion

---

drivers/doc.txt
drivers/include/dsp0401.h
drivers/include/hd44780.h
drivers/include/ili9341.h
drivers/include/pcd8544.h

This PR adds a display group to the drivers group in doxygen and moves the current set of display devices to the group
Read the new docs :)
None

drivers: Add display device doxygen group

---

boards/mbed_lpc1768/doc.txt

This commit improves the documentation for the mbed lpc1768 board.
None
None

boards: mbed_lpc1768: Improve documentation

---

drivers/mtd_spi_nor/mtd_spi_nor.c

When playing with #8316, I noticed that performances were a lot below theoretical expectations.
I tried changing the sleep time used when polling the 'write completed' status bit and found that simply yielding lead to the best performance.
It might lead to a lot of context switches if the erase time is really long, but in my benchmark, performances are 20 times better than before...
#8316

mtd_spi_nor: remove sleep when waiting for write completed

---

dist/tools/ci/print_toolchain_versions.sh

This PR removes an extra `-` under the "Operating System versions" title printed with `make print-versions`.
In master, you get this:
```
Operating System Environment
-----------------------------
Operating System: "Ubuntu" "19.10 (Eoan Ermine)"
Kernel: Linux 5.3.0-29-generic x86_64 x86_64
System shell: /usr/bin/dash (probably dash)
make's shell: /usr/bin/dash (probably dash)
```
With this PR, you get this:
```
Operating System Environment
----------------------------
Operating System: "Ubuntu" "19.10 (Eoan Ermine)"
Kernel: Linux 5.3.0-29-generic x86_64 x86_64
System shell: /usr/bin/dash (probably dash)
make's shell: /usr/bin/dash (probably dash)
[...]
```
It's subtle :)
Check the underlying `-` are now right aligned with the title.
Found when I wrote #13358

tools/toolchain_version: remove extra underlying -

---

sys/shell/commands/sc_gnrc_icmpv6_echo.c

I often find myself wondering on what interface I've received a reply with `ping6` if there is more than one.
So if there is more than one interface, print the id of the receiving interface for convenience.
```
> ping6 ff02::1
2020-02-20 18:19:38,644 # 12 bytes from fe80::d0ae:c1b:2054:58e%7: icmp_seq=0 ttl=64 rssi=-45 dBm time=4.801 ms
2020-02-20 18:19:38,652 # 12 bytes from fe80::d0ae:c1b:2054:58c%8: icmp_seq=0 ttl=64 rssi=-63 dBm time=13.422 ms (DUP!)
2020-02-20 18:19:38,661 # 12 bytes from fe80::c78:16d9:8aca:ba9a%8: icmp_seq=0 ttl=64 rssi=-44 dBm time=21.819 ms (DUP!)
2020-02-20 18:19:39,648 # 12 bytes from fe80::d0ae:c1b:2054:58e%7: icmp_seq=1 ttl=64 rssi=-44 dBm time=4.797 ms
2020-02-20 18:19:39,657 # 12 bytes from fe80::d0ae:c1b:2054:58c%8: icmp_seq=1 ttl=64 rssi=-61 dBm …
```

shell/gnrc_icmpv6_echo: print interface id in reply

---

CODEOWNERS

I don't need to be informed on every test there is. I'm happy to just review the tests for "my" network stacks, the unittests and any test script added.
Read I guess...
None

CODEOWNERS: reduce my scope on tests

---

boards/cc1312-launchpad/doc.txt

First attempt to document the `cc1312-launchpad` board.
#13205

cc1312-launchpad: add board documentation

---

tests/driver_srf08/main.c

The issue is reported by cppcheck when modifying this file
This PR fixes a CppCheck issue reported in #13431 (see details [on Travis CI](https://travis-ci.org/RIOT-OS/RIOT/builds/653407588#L208)).
- Static tests are green
- The test still works (if it does already).
Required by #13431

tests/driver_srf08: reduce scope of range_array

---

drivers/bmx280/include/bmx280_internals.h
pkg/openthread/Makefile
tests/unittests/Makefile

The ARM toolchain upgrade (https://github.com/RIOT-OS/riotdocker/pull/78) slipped through some new compiler warnings (which turn into errors now).
This PR tries to fix them.
Fixes #13434.

cpu/arm: fixes necessary for toolchain upgrade

---

drivers/bmx280/include/bmx280_internals.h

See https://github.com/RIOT-OS/RIOT/pull/13456#discussion_r383261579 for discussion.

drivers/bmx280: provide correct CALIB_T_P_LEN

---

CODEOWNERS

Hopefully this helps a bit with the mass requests...
Remove from all tests.
Add openmote board ownership.
Add to periphs for cpu, drivers, and tests.
Merge and see???

CODEOWNERS: fine tune @MrKevinWeiss code ownership

---

cpu/cortexm_common/ldscripts/cortexm_base.ld
cpu/lpc2387/include/cpu_conf.h
cpu/lpc2387/ldscripts/lpc2387.ld
cpu/sam0_common/include/cpu_conf.h
sys/newlib_syscalls_default/syscalls.c

Several MCUs have discontinuous memory regions. Unless memory is explicitly marked to go into those sections, this memory is currently unused by RIOT.
For lpc2387 this adds 16k of USB, 16k of Ethernet and 2k of Backup memory to the heap.
same54 (and saml21) has an additional 4k of backup memory that can be used for the same purpose.
Run `tests/malloc`.
<details><summary>lpc2387 before</summary>
<p>
```
2019-12-12 00:23:50,319 # main(): This is RIOT! (Version: 2020.01-devel-1355-ge8a85-mcb2388-multiheap)
2019-12-12 00:23:50,323 # CHUNK_SIZE: 512
2019-12-12 00:23:50,323 # NUMBER_OF_TESTS: 3
…
2019-12-12 00:23:51,965 # Allocated 512 Bytes at 0x0x4000fd28, total 512
2019-12-12 00:23:51,966 # Allocated 512 Bytes at 0x0x4000fb10, total 1032
2019-12-12 00:23:51,967 # Allocated 512 Bytes at …
```

sys/newlib: enable multiple heaps in _sbrk_r()

---

dist/tools/ethos/start_network.sh

As we now also support DHCPv6 we might want to use the setup-routine of start_networking.sh but not start the UHCP server.
Run the script (with an `ethos`-supporting app on a node, e.g. `gnrc_border_router`) with and without the `-e`/`--ethos-only` flag)
```sh
sudo ./dist/tools/ethos/start_network.sh --ethos-only /dev/ttyACM0 tap0 2001:db8::/64
^C
sudo ./dist/tools/ethos/start_network.sh -e /dev/ttyACM0 tap0 2001:db8::/64
^C
sudo ./dist/tools/ethos/start_network.sh /dev/ttyACM0 tap0 2001:db8::/64
^C
```
Follow-up on #13424

start_networking.sh: add capability to not start uhcpd

---

doc/doxygen/src/creating-modules.md

I implemented a pseudomodule and was very confused by the documentation. I would suggest to update this entry. 
Or did I missed something?

doc/creating-modules: update Pseudomodules entry

---

pkg/nimble/netif/include/nimble_netif.h

Minor doc improvement...
none really needed.
none

pkg/nimble/netif: minor API doc improvement

---

sys/net/gnrc/application_layer/uhcpc/gnrc_uhcpc.c

See https://github.com/RIOT-OS/RIOT/pull/13485#issuecomment-591826207
See testing procedure in https://github.com/RIOT-OS/RIOT/pull/8576
Follow-up on https://github.com/RIOT-OS/RIOT/pull/8576, discovered in #13485

gnrc_uhcpc: fix NULL pointer dereference

---

cpu/stm32f1/periph/rtc.c

This converts the stm32f1 RTC implementations to use the new `rtc_mktime()` & `rtc_localtime()` functions.
This allows the RTC to operate for another 118 years.
Run `tests/periph_rtc` on e.g. a `bluepill` board.
depends on #13284
addresses #13277

cpu/stm32f1: make RTC Y2038 safe

---

pkg/tinydtls/contrib/sock_dtls.c

As discussed in #12907: the indirection of the buffer pointer via the `sock`'s `mbox` for receive really is not necessary. This gets rid of it, so asynchronous receive is implementable. As a bonus it also safes a few byte of ROM.
`examples/dtls-sock` should still work as well as it does on master.
See discussions in #12907.

tinydtls: remove receive buffer indirection via mbox

---

sys/net/gnrc/application_layer/uhcpc/gnrc_uhcpc.c

Otherwise the border router has no way to disseminate the context throughout the network.
Context and ABR should only be configured if the border router has an interface to a 6Lo-ND enabled network (check with `6ctx` and `nib abr`.
See https://github.com/RIOT-OS/RIOT/pull/13561#issuecomment-595304412

gnrc_uhcpc: only configure 6Lo-ND features if wireless-interface is 6LN

---

sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mcps.c

This PR fixes the handling of downlink frames without payload.
According to the [LoRAWAN Specification](https://lora-alliance.org/sites/default/files/2018-07/lorawan1.0.3.pdf), section 4.3.2 _Port field (FPort)_, line 545, the port field must be present if the payload is not empty.
This means that the port field is not available for downlink frames without payload. The following logic does not cover this case correctly: https://github.com/RIOT-OS/RIOT/blob/5e9733645f1671189db577beeafbfec6e5b503f7/sys/net/gnrc/link_layer/lorawan/gnrc_lorawan_mcps.c#L89-L94 If the downlink frame has no payload, `pkt->size` is already 0 and the error condition doesn't match. The subsequent `assert` leads to a crash since `fport` is `NULL` in that case. Even if the application is compiled with `NDEBUG`, the …

gnrc/lorawan: fixes the handling of downlink frames without payload

---

pkg/qcbor/Makefile
pkg/qcbor/Makefile.dep
pkg/qcbor/Makefile.include
pkg/qcbor/Makefile.qcbor
pkg/qcbor/doc.txt
tests/pkg_qcbor/Makefile
tests/pkg_qcbor/Makefile.ci
tests/pkg_qcbor/main.c
tests/pkg_qcbor/tests/01-run.py

pkg/qcbor: Add QCBOR package

---

tests/lwip/tests/01-run.py

While running this test script, I encountered the problem, that the process for the previous test was not finished, not allowing the next test to use its TAP interface. This small timer should fix that.
```sh
BOARD=native make -C tests/lwip all test
```
passes.
None

tests/lwip: stabalize test script

---

drivers/cc110x/cc110x_netdev.c

When an IRQ is lost during cc110x_send(), the driver will remain locked until another IRQ is triggered. This PR changes the behavior to wait for at most an reasonable upper bound, which is chosen to not only allow the driver to recover but also (at least in theory) complete the transmission correctly.
There should be no regressions for existing boards.
Fixes https://github.com/RIOT-OS/RIOT/issues/13587

drivers/cc110x: Handle lost IRQs more gracefully

---

pkg/lvgl/Makefile
pkg/lvgl/Makefile.dep
pkg/lvgl/Makefile.include
pkg/lvgl/Makefile.lvgl
pkg/lvgl/Makefile.lvgl_module
pkg/lvgl/contrib/Makefile
pkg/lvgl/contrib/lvgl.c
pkg/lvgl/doc.txt
pkg/lvgl/include/lv_conf.h
pkg/lvgl/include/lvgl_riot.h
tests/pkg_lvgl/Makefile
tests/pkg_lvgl/Makefile.ci
tests/pkg_lvgl/README.md
tests/pkg_lvgl/main.c

This PR adds support to the [LittlevGL](https://github.com/littlevgl/lvgl) package to RIOT. I've been looking to it for quite some time and now that the ili9341 driver is in, I think it's time to move forward with this.
This PR also introduces a generic (and still basic) API for display devices, it follows the same scheme as netdev.
There's also a test application that display a system monitor on a screen. It was tested on the stm32f429i-disc1 board.
I know other people in the community (@bergzand, @fjmolinas) have already done some work with this package and maybe they can provide some good advice here so we can move forward faster.
Ideas for future improvements:
- improve package configuration macros: maybe even in this PR (I think it's the weakest point of this PR)
- provide a driver …

pkg/lvgl: add initial support for LittlevGL to RIOT

---

core/thread.c

Before calling `thread_yield_higher();` allways enable interrupts.
Will only make a difference when calling  `thread_zombify()` with interrupts disabled.
Prevents warning: `"thread_yield_higher: interrupts are disabled - this should not be"` on native.
`make -C tests/thread_zombie/ flash test`
output:
```
Number of threads before the test = 2
Creating first thread (sleeping)
Creating second thread (sleeping)
Creating third thread (sleeping)
Current number of threads = 5
OK
Waking up first thread
Thread: 1 is starting
Thread: 1 calls zombify
Current number of threads = 5
OK
Waking up second thread
Thread: 2 is starting
Thread: 2 calls zombify
Current number of threads = 5
OK
Kill first thread
Current number of threads = 4
OK
Waking up third thread
Thread: 3 is starting
Thread: 3 calls …
```

core/thread.c: thread_zombify small fix

---

cpu/cc2538/periph/gpio.c

If only one bit it is set in `state` (one GPIO pin caused an interrupt), don't loop over all 8 bits.
Use `clz` to get the position of the first interrupt bit and clear it, looping only as many times as there are actual interrupts.
<details>
<summary>All 8 interrupt pins/port should still work.</summary>
```C
#include <stdint.h>
static void handle_isr(uint32_t state) {
while (state) {
int pin = 8 * sizeof(state) - __builtin_clz(state) - 1;
state &= ~(1 << pin);
printf("Interrupt on pin %d\n", pin);
}
}
int main(int argc, char **argv) {
uint32_t state = 1;
for (int i = 0; i < 8; ++i) {
printf("%d:\n", i);
handle_isr(state);
state <<= 1;
if (state & 0x4) {
state |= 1;
}
}
}
```
</details>
I tested this on the `openmote-b` and both the user button and the interrupts …

cpu/cc2538: gpio: save a few cycles in handle_isr()

---

sys/net/gnrc/application_layer/uhcpc/gnrc_uhcpc.c

This makes the UHCP client to use the actually advertised prefix length instead of assuming statically `/64`.
Set environment variable `IPV6_PREFIX` to something else than a 64-bit prefix e.g.
```sh
IPV6_PREFIX=2001:db8::/62 make -C examples/gnrc_border_router/ flash term
```
On master the configured prefix will be a 64-bit prefix no matter what. With this change, it will be configured as expected:
```
uhcp_client(): sending REQ...
got packet from fe80::e0bc:7dff:fecb:f54f port 57685
uhcp: push from fe80::e0bc:7dff:fecb:f54f:57685 prefix=2001:db8::/62
gnrc_uhcpc: uhcp_handle_prefix(): got same prefix again
gnrc_uhcpc: uhcp_handle_prefix(): add compression context 0 for prefix 2001:db8::840c:77ec:2333:6278/62
nib prefix
nib prefix
2001:db8::/62 dev #6
```
None (used to debug …

gnrc_uhcp: use actually advertised prefix length

---

.gitignore

Similar to what we have for `vim`, now for `emacs`..
Open a file with emacs, change and save a file .. the rest is not so difficult (:
--

.gitignore: add emacs backup files

---

drivers/at86rf215/at86rf215_internal.c

When the radio is in DEEP SLEEP, reading the state register will return 0.
This makes the reset routine abort early even though the device is connected and still waking up.
Instead, just add a timeout to the polling of the WAKEUP IRQ bit.
In practice it has shown that the loop will be taken two times on 'normal' reset and four times when the radio was in DEEP SLEEP.
Polling 255 times sure does not hurt.
To reproduce the issue, put both interfaces into SLEEP mode,
then reboot the module:
ifconfig 7 set state sleep
ifconfig 8 set state sleep
reboot
On master, the radio will fail to initialize.
With this patch the radio initializes properly.

drivers/at86rf215: fix reset after deep sleep

---

examples/gnrc_border_router/Makefile

Fixes https://github.com/RIOT-OS/RIOT/pull/13609#discussion_r404765346
See https://github.com/RIOT-OS/RIOT/pull/13609#discussion_r404765346.
See https://github.com/RIOT-OS/RIOT/pull/13609#discussion_r404765346

examples/gnrc_border_router: use 64-bit prefix with UHCP

---

tests/gnrc_rpl_srh/tests/01-run.py

The sniffer in `tests/gnrc_rpl_srh` always had stability issues, since it uses some badly synchronized threading of mine. Since v2.4.3 scapy has its own [asynchronous sniffer] (which is already used in
`tests/gnrc_dhcpv6_client_6lbr`), so I ported my sniffer implementation to use that instead.
[asynchronous sniffer]: https://scapy.readthedocs.io/en/latest/usage.html#asynchronous-sniffing
`tests/gnrc_rpl_srh` should now be much more stable in passing.
None.

gnrc_rpl_srh: use AsyncSniffer for sniffing

---

sys/include/tm.h

had this commit flying around, saw it wasn't fixed upstream, so....

tm.h: fix typo

---

boards/cc1312-launchpad/include/periph_conf.h
cpu/cc26x2_cc13x2/include/cc26x2_cc13x2_prcm.h
cpu/cc26xx_cc13xx/include/cc26xx_cc13xx_uart.h
cpu/cc26xx_cc13xx/periph/uart.c

Fixes UART1 initialization (didn't work before).
- Add UART1 to `periph_conf.h` for your CC13x2/CC26x2 board.
- Tell `stdio` to use `UART_DEV(1)`
<details>
<summary>Example configuration</summary>
```patch
From 083d64aea63ff374654e5410f04322dcd7ff7af3 Mon Sep 17 00:00:00 2001
From: Jean Pierre Dudey <jeandudey@hotmail.com>
Date: Wed, 8 Apr 2020 12:18:17 -0500
Subject: [PATCH] cc1312-launchpad: use UART1
Signed-off-by: Jean Pierre Dudey <jeandudey@hotmail.com>
---
boards/cc1312-launchpad/include/periph_conf.h | 10 ++++++++++
examples/hello-world/Makefile                 |  2 ++
2 files changed, 12 insertions(+)
diff --git a/boards/cc1312-launchpad/include/periph_conf.h b/boards/cc1312-launchpad/include/periph_conf.h
index 0bd76b1da..5e9621ecd 100644
--- …
```

cc26xx_cc13xx: fix UART1 initialization

---

tests/emcute/tests/01-run.py

On `samr21-xpro` not all UDP packets were received, leading to the testing automaton to get into an invalid state and failing. This small delay between `sendto()` fixes that issue.
Run the test on `samr21-xpro`. Without this fix it should not work reliably, with it it does.
```
BOARD=samr21-xpro make -C tests/emcute/ flash -j16
for i in $(seq 30); do
sudo BOARD=samr21-xpro \
make -C tests/emcute/ --no-print-directory test || break;
done
```
**This test is not run by the CI!**
Addresses first half of https://github.com/RIOT-OS/Release-Specs/issues/152#issuecomment-614659443.

tests/emcute: add small inter-packet gap between server replies

---

tests/emcute/tests/01-run.py

On `samr21-xpro` not all UDP packets were received, leading to the testing automaton to get into an invalid state and failing. This small delay between `sendto()` fixes that issue.
Run the test on `samr21-xpro`. Without this fix it should not work reliably, with it it does.
```
BOARD=samr21-xpro make -C tests/emcute/ flash -j16
for i in $(seq 30); do
sudo BOARD=samr21-xpro \
make -C tests/emcute/ --no-print-directory test || break;
done
```
**This test is not run by the CI!**
Addresses first half of https://github.com/RIOT-OS/Release-Specs/issues/152#issuecomment-614659443.

tests/emcute: add small inter-packet gap between server replies [backport 2020.04]

---

doc/doxygen/src/creating-modules.md

This PR extends and corrects some inaccuracies of  `PSEUDMODULES` documentation.
Read the docs, correct the typos, check if I'm also being inaccurate.
#10970

doc/creating-modules.md: correct PSEUDOMODULES documentation

---

tests/conn_can/README.md
tests/conn_can/main.c

Add command to send a can frame with the RTR (remote request) flag on.

test: conn_can: add remote request test

---

cpu/sam0_common/periph/timer.c

Now that we can query the GCLK frequency at run-time, there is no need to implicitely hard-code the timer frequency in the config struct anymore.
This is needed to allow timers that run at a frequency other than 1 MHz.
`scale` should end up the same as the previously hard-coded value in the board definition.
`tests/periph_timer` and `tests/xtimer_*` should still work.
The `prescaler` field in the `tc32_conf_t` struct is now obsolete and will be removed.

cpu/sam0_common: timer: don't ignore frequency in timer_init()

---

makefiles/docker.inc.mk

Split from #12419 this PR adds a generic `docker_run_make` function to run make commands in docker.
- `DOCKER_MAKE_ARGS` is now empty since `DOCKER_MAKECMDGOALS` is passed individually yo the function and `DOCKER_OVERRIDE_CMDLINE` is allays passed.
- `BUILD_DIR` creation is removed since it is provided globally.
The function 3rd argument is currently unused, but I use it in #12419 to set `flags` specific to some docker targets, notably `flash` and `term`.
- Run docker targets and verify it builds in docker
- compile with and without `DOCKER_MAKE_ARGS="-j"`
- any ideas on what else to test?
Split from #12419

makefiles/docker.inc.mk: add and use generic docker_run_make

---

sys/include/ztimer.h

sys/ztimer: Fixed typo in doc

---

Makefile
makefiles/tools/riotgen.inc.mk

This PR adds 3 new code bootstrap targets (bootstrap-{example,board,test}) in the build system. The feature relies on [riotgen](https://github.com/aabadie/riot-generator), a small Python tool I wrote to generate empty RIOT code projects.
The idea is to use these targets when one wants to start a new example application, test application or board support: all copyright headers are correctly setup, with main.c files, README, etc. This should simplify initial boring work and improve contribution quality of newcomers.
Just call them using `make` and answer a few questions:
```
$ make bootstrap-example
Example application name (no space): new-example
Example application brief description []: This is a new example application
Target board [native]: 
Required modules (comma separated) []: …
```

makefiles: add code generator targets

---

cpu/nrf52/periph/i2c.c

This commit enhances the I2C code of the nRF52 family to block on a
mutex while the I2C transfer is busy. The mutex is unlocked in the ISR
when it is trigger by either a stop condition or an error condition.
While the current code already allows the MCU to sleep during the transfer, this enhancement allows the RIOT scheduler to schedule other (lower priority) threads during the transfer.
I2C operations should still work, any connected peripheral such as an BME280 must still function as before. 
@MrKevinWeiss Do you have the time and hardware to give this a shot with RIOT-HIL?
None

nrf52/i2c: Use mutex and IRQ for blocking

---

doc/doxygen/src/kconfig/kconfig.md

Update documentation to add "Appendix D: A few key aspects while exposing a macro to Kconfig"
`make doc`
Doxygen build works fine.
@leandrolanzieri

doc/kconfig.md : Update documentation

---

pkg/lwip/contrib/lwip.c

This PR adds the support for `netdev_tap` to pkg/lwip the same way as PR #12895 and #12950 already did for other Ethernet devices.
I only was able to compile test this, but there was no traffic visible in Wireshark.
None, but came up during the review of #13701.

lwip: add IPv4 support for `netdev_tap`

---

sys/include/net/netif.h
sys/net/gnrc/netif/_netif.c
sys/net/netif/netif.c

This is a proof-of-concept implementation for a stack-independent interface identifiers.
None yet, but will add some if we agree on the concept.
A proposed solution for #12680.

netif: add functions to get and get by identifier 

---

pkg/nimble/netif/nimble_netif.c

This is simply a small cleanup: the GNRC netif struct for the NimBLE netif device is allocated statically inside the `nimble_netif` module. For no good reason, I somehow added an additional pointer pointing towards this struct, initialize that pointer in `_netif_init()` and use that pointer in the rest of the code. This makes actually no sense, as we can simply reference the original struct directly... 
This PR removes that redundant pointer, saves some byte of RAM/ROM :-)
E.g. 
- run `examples/gnrc_networking` on two `nrf52dk` boards
- open a BLE connection between them (use the `ble` shell command)
- make sure the nodes can ping each other
none

pkg/nimble/netif: remove redundant netif ptr

---

cpu/sam0_common/include/periph_cpu_common.h
cpu/sam0_common/periph/dma.c

I noticed some shortcomings in the documentation of the new DMA peripheral on the sam0 devices
Read the fabulous docs
follow up to #14260

sam0_common: Add additional documentation on DMA usage

---

pkg/wolfssl/Makefile
pkg/wolfssl/Makefile.include
pkg/wolfssl/Makefile.wolfcrypt
pkg/wolfssl/Makefile.wolfssl

This PR is improving the situation with the integration of the wolfssl package in the build system. The goal is mainly to avoid to alter the package sources during the build.
- Verify wolfssl related applications are still functional and code size remains unchanged
None

pkg/wolfssl: improve build system integration

---

cpu/sam0_common/periph/uart.c

Allow to only configure the RX pin of the UART so that the TX pin can be used as a GPIO instead.
Replace the `.tx_pin` definition of any board with `GPIO_UNDEF`
```patch
--- a/include/periph_conf.h
+++ b/include/periph_conf.h
@@ -81,7 +81,7 @@ static const uart_conf_t uart_config[] = {
{    /* EXT1 */
.dev      = &SERCOM1->USART,
.rx_pin   = GPIO_PIN(PA, 9),
-        .tx_pin   = GPIO_PIN(PA, 8),
+        .tx_pin   = GPIO_UNDEF,
#ifdef MODULE_PERIPH_UART_HW_FC
.rts_pin  = GPIO_UNDEF,
.cts_pin  = GPIO_UNDEF,
```
When using `tests/periph_uart` and connecting another UART adapter, you should be able to receive on that UART, but not transmit.

cpu/sam0_common: UART: allow RX only configuration

---

core/include/cib.h

MAXINT is not a defined value and since the types are unsigned also misleading.
Read.
None

core/cib: fix documented maximum size restrictions

---

core/include/sched.h

This PR adds some documentation for the sched_cb module.
Read the docs :)
None

sched_cb: Add function documentation

---

sys/include/stdio_uart.h

Add a warning that RIOT does not officially support STDIO over UART from interrupt context. Some reasons are given below.
Read the documentation.

sys/stdio_uart: Add warning about use in ISR

---

sys/net/application_layer/dhcpv6/client.c

The DHCPv6 server might send reposes [multiple times](https://github.com/RIOT-OS/RIOT/files/4449928/DHCPv6_multiple_replies.pcapng.zip).
The DHCPv6 client will only handle the first response, if additional responses are comming in they are left in the RX queue.
That results in the client always reading the response of a previous transaction on any subsequent transactions.
In this case the client will try again, creating a new transaction - that will again only read the previous response.
This essential creates a life-lock with the client not reacting to any input anymore as it is spending all it's time on sending DHCP requests. 
To fix this, discard previous responses by flushing the RX queue before sending a new message to the DHCPv6 server.
make -C examples/gnrc_border_router …

sys/net/dhcpv6: discard stale replies

---

boards/native/Makefile.include
cpu/esp32/Makefile.include
cpu/esp8266/Makefile.include
cpu/esp_common/Makefile.include
cpu/mips32r2_common/Makefile.include
makefiles/arch/cortexm.inc.mk

This PR followups to  #14351 and cleanups some modified conditional that had been used as a workaround.
Same testing procedure as in #14351
~~Depends on #14351~~

Makefile: use normal conditionals

---

doc/doxygen/src/kconfig/kconfig.md

This extends the documentation of Kconfig with a guide to model provided features, CPUs and boards in Kconfig during migration. Also updates the name of the generated `.config` file.
- `make doc` and check the documentation
Useful for the process tracked in #14148
Suggested by @fjmolinas in #14176 and by @maribu in #13404

doc/kconfig: Add guide to model features, CPUs and boards

---

sys/net/gnrc/transport_layer/tcp/gnrc_tcp_fsm.c

Hi fellow RIOTers,
This PR moves the allocation and release of a connections receive buffer from the internal FSM to the gnrc_tcp functions related to open and close.
Just like #14222, this is a preparation for an API change in gnrc_tcp (implements a listen/accept scheme) to simplify sock_tcp integration.  I have tested this PR on native.
This PR does not introduce new features, testing by executing the test scripts in "tests/gnrc_tcp" should be sufficient.

gnrc_tcp: rewrite recv buffer allocation/returning

---

doc/doxygen/src/driver-guide.md

Update documentation to include exposure of parameter to doxygen groups.
`make doc`
Doxygen build works fine.
@leandrolanzieri

doc/driver-guide.md : Update for compile-time configuration 

---

dist/pythonlibs/riotctrl_shell/tests/test_gnrc.py

This slipped through the review in #11406.
Tests still pass:
```sh
cd dist/pythonlibs/riotctrl_shell/; tox
```
Follow-up on #11406.

riotctrl_shell: remove unneeded variables and imports

---

.github/workflows/tools-buildtest.yml
.github/workflows/tools-test.yml
dist/pythonlibs/riotctrl_shell/requirements.txt

Sorry this was not intended to be proposed now, I wanted to try on my own fork... but well, now that it's here...
This PR is a POC for setting up Github Actions for some of our tests: static-test, some standalone builds for tools (flatc and mosquitto_rsmb) and also for running tests on some of our tools, like compile_and_test_for_board.py, backport_pr.py and riotctrl_shell scripts (all come with a full test environment based on tox).
In the end, I think GH actions could a good replacement to Travis, which had some failures during the last weeks (some jobs were not showing up in PRs).
For running the static-test and the standalone builds for tools, I created a dedicated [riot-action project](https://github.com/aabadie/riot-action) which is based on a simple (and small) Docker image. I …

ci: setup github actions

---

dist/pythonlibs/riotctrl_shell/gnrc.py
dist/pythonlibs/riotctrl_shell/tests/test_gnrc.py

Another shell interaction and parsers for `riotctrl_shell`, this time for the `nib` command.
I provided tests, so `tox`/`tools-test` should pass.
None

riotctrl_shell.gnrc: provide ipv6_nib interactions and parsers

---

examples/emcute_mqttsn/README.md

I worked with the emcute example and had the added problems (messages send by RSMB don't arrive and topics change ids). I found the solutions in the notes section of the asymcute readme and I think they are needed here too, to be easily accessible for beginners. Especially the the problem with the link local addresses was hard to debug for a RIOT-OS/MQTT-SN beginner.
none / Manual proofreading
none

emcute example: Added more FAQ entries to readme

---

LOSTANDFOUND.md

This PR add a note in LOSTANDFOUND.md about the removal of the wsn430 boards.
Just read the note and verify that the commits points to the merge commit of the PR that removed these boards
wait for #14491

LOSTANDFOUND.md: add note about wsn430 boards

---

CODING_CONVENTIONS.md

Floating point math should be avoided in the embedded space.
Most of our targets do not have a FPU, so we want to avoid including several kB of soft-float libs when most of the time calculations can be done just as well and and better accuracy when using integer math. 
Read.

CODING_CONVENTIONS.md: add a note about float

---

cpu/stm32/periph/gpio_all.c
cpu/stm32/periph/gpio_f1.c
cpu/stm32/periph/uart.c

- Do not set an intermediate mode, prepare correct mode settings in a temporary variable
- Consistently enabled the GPIO periph in gpio_init_af()
- Previously, STM32 F1 did not require a separate call to gpio_init() prior to a call of gpio_init_af(), but other STM32 families did
- Now, gpio_init_af() can be used without gpio_init() consistently
- STM32 F1: Do not touch ODR for non input pins
- For input pins, this enables / disabled pull up resistors. For outputs, this register should remain untouched (according to API doc)
- Make use of the fact that gpio_init_af() does not need prior call to gpio_init() for all STM32 families anymore and drop call to gpio_init()
- Initialize the UART periph first, before initializing the pins
- While uninitialized, the UART periph will send signal LOW …

cpu/stm32: Fix garbage on UART init [backport 2020.07] #14426

---

.github/workflows/tools-buildtest.yml
.github/workflows/tools-test.yml

This also runs the Github workflows for the release branches. The syntax [is the same](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) as for the [branch protection rules](https://github.com/RIOT-OS/RIOT/settings/branches).
Not sure they will run without merging.
See https://github.com/RIOT-OS/RIOT/pull/14522#issuecomment-658841365

gh-actions: run for PRs against release branches [backport 2020.07]

---

sys/include/net/someip.h

This PR introduces the SOME/IP header to RIOT. 
Scalable service-Oriented MiddlewarE over IP (SOME/IP) is a new application layer communication protocol from the field of Automotive Ethernet (https://www.autosar.org/fileadmin/user_upload/standards/foundation/19-11/AUTOSAR_PRS_SOMEIPProtocol.pdf). 
None.
None.

sys/include/net: Add SOME/IP header

---

dist/tools/usb-cdc-ecm/start_network.sh
examples/gnrc_border_router/Makefile
examples/gnrc_border_router/Makefile.cdc-ecm.conf

Add USB ethernet (CDC-ECM) support as an uplink to the `grnc_border_router` example. This allows using the usb ethernet drivers as an alternative to SLIP or ethos, which compared to ethos reduces latency over the link.
Flash the example to a board with USB support, for example `samr21-xpro`.
`sudo make UPLINK=usb-cdc-ecm all flash`
You will then need to attach the usb port to your computer, which should automatically detect and bring up the interface with link-locals on most distributions. Bear in mind that this may be a different USB port to the one that you used to flash the board.
I have successfully plugged in my `samr21-xpro` with two micro usb cables, one into the device port, and one into the edbg port for testing. This allows access to the serial terminal over the EDBG serial, …

Add USB Ethernet support to GNRC Border Router example

---

tests/malloc/main.c

Otherwise, the test fails on z1 (with no allocations).
CI test run should be sufficient.
Needed for #12457.

tests/malloc: reduce chunk size to 128b

---

release-notes.txt

This are the release notes for the upcoming 2020.07 release. Please read and ensure that your of the past 3 months work is addressed.
Read.

release-notes.txt: add 2020.07 release notes

---

release-notes.txt

This are the release notes for the upcoming 2020.07 release. Please read and ensure that your of the past 3 months work is addressed.
Read.

release-notes.txt: add 2020.07 release notes [backport 2020.07]

---

core/include/sched.h
core/sched.c

RIOT support has been merged in OpenOCD. 
OpenOCD makes assumptions about some symbol names / array entries so add a note that we need to keep those synchronized as a comment.
Read the updated documentation.
http://openocd.zylin.com/#/c/4256/

core: add comments to symbols used by OpenOCD

---

.github/workflows/test-on-iotlab.yml

This PR adds a github action workflow that launch `compile_and_test_for_board` on a list of boards provided by the IoT-LAB testbed.
For each board, an experiment is launched, then the compile_and_test script starts. Once it completes, the experiment is stopped and build artifacts are stored. These 2 steps are always performed, regardless of the compile and test status.
For each board, jobs are run in parallel and a job takes ~2h30 to complete. Only 6 boards are added for the moment but more could be added (samr30-xpro, frdm-kw41z, nrf52dk, nrf52840dk, etc).
Since it takes a lot of time to complete, it's not ~possible~ acceptable to perform this check on PR basis, so the action is configured to be run on a weekly basis on master and for each RC tag pushed.
This action uses a specific …

.github/workflows: add CI on IoT-LAB

---

makefiles/kconfig.mk

This PR refactors some dependencies in `kconfig.mk` to avoid duplicate calls to some targets like `merge_config` and `genconfig`. It also makes the dependency of `GENERATED_DIR` to `CLEAN` conditional, so it only occurs once and not on every restart of Make. This last part seems to be needed for #14654.
- Compile `tests/kconfig`. With this PR you should see the following message only once:
```
Merged configuration 'RIOT/tests/kconfig/app.config'
Configuration saved to 'RIOT/tests/kconfig/bin/native/generated/merged.config'
```
On master this happens twice.
- The following should still work:
- Running `make menuconfig`, compiling and cleaning the configuration
- Change `app.config` should change the configuration on the application, except when `menuconfig` has already been used.
Needed …

makefiles/kconfig.mk: remove duplicate calls to merge_config and cleanups

---

sys/event/event.c
sys/include/event.h
tests/events/main.c

Added `event_t *event_wait_prio(event_queue_t *queues, size_t n_queues)`, that
- in the case `queues` contains only one item (`n_queues == 1`) behaves identical to `event_wait()`
- in case of multiple queues waits until any queue has an event
- in case multiple queues have an event, priorities queues with an lower index in the array over those with a higher index
The idea is that this can (under certain conditions) allow reducing the number of event handler threads that are used to implement priorities. But as a high priority event will with this no longer preempt the handling of low priority events, handling both real-time and non-real-time events by the same thread requires special care, as handling of the longest to handle low priority event might have just started when a high priority …

sys/event: implement waiting on multiple queues

---

LOSTANDFOUND.md

Rebasing seems to have changed it.
Search for previous hash in git log, it is not there. Search for updated, confirm it points to the removal commit.
Introduced in https://github.com/RIOT-OS/RIOT/pull/12457.

LOSTANDFOUND.md: fix chronos board removal commit hash

---

sys/Makefile

Sorted `sys/Makefile` alphabetically by module name.
1. Murdock
2. Number of lines should be identical (except for the added screaming comment)
None

sys: Sort Makefile

---

cpu/stm32/periph/gpio_all.c

Use the new helper function to iterate over all set bits in the stm32 GPIO driver.
GPIO interrupts should still work
depends on #14556

cpu/stm32: GPIO: use bitarithm_test_and_clear()

---

cpu/cc2538/periph/timer.c

I found this bug while testing #10493 since I would see the application getting stuck for 32bit timers. This commit fixes it.
The interval load value was only set to 0xffff regardless of the counter
mode used which mad the 32bit timer apparently stop after 0xffff (it
would never reach values >0xffff).
When a GPTM is configured to one of the 32-bit modes, TAILR appears as a
32-bit register (the upper 16-bits correspond to the contents of the
GPTM Timer B Interval Load (TBILR) register). In a 16-bit mode, the
upper 16 bits of this register read as 0s and have no effect on the
state of TBILR.
Therefore the LOAD_VALUE can be set to 0xffffffff instead of 0xffff
since the higher bits will be ignored in 16bit mode.
Can be tested with #10493 `BOARD=openmote-b make -C tests/periph_timer_diff/ …

cpu/cc2538/timer: fix 32 bit timer reload value

---

cpu/lpc23xx/periph/rtc.c

- reduce indentation
- sanitize logic in rtc_set_alarm()
- [ILR register](https://www.nxp.com/docs/en/user-guide/UM10211.pdf#page=587) is clear-on-write, writing 0 has no effect
`tests/periph_rtc` should still work.

cpu/lpc23xx: RTC: cleanup

---

dist/tools/buildsystem_sanity_check/save_all_dependencies_resolution_variables.sh
dist/tools/compile_test/compile_test.py
dist/tools/esptool/gen_esp32part.py
dist/tools/pyterm/setup.py

This replaces the last invocations on Python2 with Python3.
Make sure the affected scripts still run.

Convert remaining Python2 users to Python3

---

cpu/stm32/periph/dma.c
cpu/stm32/periph/spi.c

Add support for STM32F3.
Only tested on STM32F334r8.
Moved from #14734.

cpu/stm32/periph/dma: add support for STM32F3

---

.github/workflows/release-test.yml

This was forgotten in #14740. See https://github.com/RIOT-OS/RIOT/actions/runs/209426259.
Should be obvious...
Follow-up on #14740

gh-actions: rename release test artifacts (part 2)

---

makefiles/libc/picolibc.mk
sys/picolibc_syscalls_default/syscalls.c

We can simply re-use the same code from newlib.
Run `tests/malloc` on a board with multiple memory regions.
e.g. `same54-xpro`
<details><summary>125 allocations</summary>
```
2020-08-24 20:42:30,423 # CHUNK_SIZE: 2048
2020-08-24 20:42:30,425 # NUMBER_OF_TESTS: 3
2020-08-24 20:42:30,437 # Allocated 2048 Bytes at 0x0x200009d8, total 2048
2020-08-24 20:42:30,441 # Allocated 2048 Bytes at 0x0x200011f0, total 4104
2020-08-24 20:42:30,445 # Allocated 2048 Bytes at 0x0x20001a08, total 6160
2020-08-24 20:42:30,446 # Allocated 2048 Bytes at 0x0x20002220, total 8216
2020-08-24 20:42:30,447 # Allocated 2048 Bytes at 0x0x20002a38, total 10272
2020-08-24 20:42:30,448 # Allocated 2048 Bytes at 0x0x20003250, total 12328
2020-08-24 20:42:30,452 # Allocated 2048 Bytes at 0x0x20003a68, total 14384 …
```

picolibc: enable multiple heaps

---

pkg/wolfssl/Makefile

Update to the latest upstream release
https://www.wolfssl.com/docs/wolfssl-changelog/
`tests/pkg_wolfssl` and `tests/pkg_wolfcrypt-ed25519-verify` still work on `native`.

pkg/wolfssl: bump version to 4.5.0

---

tests/conn_can/README.md

This PR adds information back to the `README` that was previously removed.
None.
#12769
#13624

tests/conn_can: Add to README

---

dist/tools/tapsetup/tapsetup

Just a minor typo in `echo`.
Should not be necessary

dist/tools/tapsetup: fix minor typo

---

release-notes.txt

This provides the release notes for the 2020.07.1 point release.
Read. Check if everything is right ;-).
The release was tested on the current version of `2020.07-branch` ~~e24586db0d~~  f415d935f640ef276b6af56c84803f4f5434a8a0. @fjmolinas ran [spec99 of the release-specs](https://github.com/RIOT-OS/Release-Specs/tree/master/99-compile-and-test-one-board) [on his machine](https://ci.inria.fr/ci-riot-tribe/job/build-pipeline.jk/162/artifact/) and I ran spec99 as the [`test-on-iotlab` GitHub workflow](https://github.com/RIOT-OS/RIOT/actions/runs/218388740). All results can be found [here](https://github.com/miri64/RIOT-2020.07-results/tree/master/2020.07.1-RC1-e24586db0d).
Additionally, I [ran the automated specs](https://github.com/RIOT-OS/RIOT/actions/runs/218665502).
This should cover …

release-notes: add 2020.07.1 release notes

---

.github/workflows/test-on-iotlab.yml

Now that https://github.com/RIOT-OS/RIOT/pull/14851 we can activate this feature for the weekly tests.
I'll trigger a run. It then should contain a report.xml in each artifact directory.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/14851.

gh-actions: test-on-iotlab: additionally report as XML

---

cpu/fe310/periph/gpio.c

The rv32imac supports the A (atomic) extensions containing
read-modify-store operations. This commit modifies the GPIO code to use
these for all bitwise operations. The atomic operations are emitted with
relaxed ordering as they do not require multiprocessor synchronization.
This decreases the duration of the gpio operations from 59 ns to 50 ns
per call. depending a bit on the type of operation.
On master the assembly generated for `gpio_set` is:
```
Disassembly of section .text.gpio_set:
00000000 <gpio_set>:
0:   10012737                lui     a4,0x10012
4:   4754                    lw      a3,12(a4)
6:   4785                    li      a5,1
8:   00a79533                sll     a0,a5,a0
c:   8d55                    or      a0,a0,a3
e:   c748                    sw      a0,12(a4)
10: …
```

fe310: Use read-modify-store instruction for GPIO bitwise operations

---

core/panic.c

Add a weak function callback that an app can implement if it wants to store/log when a panic occurs.

core/panic: callback app during panic

---

tests/pkg_wolfcrypt-ed25519-verify/Makefile
tests/pkg_wolfcrypt-ed25519-verify/main.c
tests/pkg_wolfcrypt-ed25519-verify/tests/01-run.py
tests/pkg_wolfssl/Makefile
tests/pkg_wolfssl/main.c
tests/pkg_wolfssl/tests/01-run.py

While testing #14814 I realized these test had no automatic test script, this PR adds one as well as some simple cleanups.
Only tested on native, maybe it will need some whitelisting or increasing the timeout...
- murdock should test
- run tests on local hardware

tests/pkg_wolf*: add test scripts and cleanup

---

drivers/mtd/mtd.c

If the underlying driver implements 'plain' read/write/erase functions, don't convert them to pagewise functions and back.
Just use the old direct functions.

mtd: allow to use non-pagewise functions

---

pkg/ccn-lite/Makefile

Green murdock.
Needed for https://github.com/RIOT-OS/RIOT/pull/14702

pkg/ccn-lite: bump version

---

README.md

Correctly hyperlink and indent the mailing list section.
Read [the new README](https://github.com/silkeh/RIOT/blob/pr/fix-mailing-lists/README.md#mailing-lists) and see that it is now correctly formatted and hyperlinked.
none

README: improve formatting of mailing lists.

---

LOSTANDFOUND.md

- Add link references to the bottom of LOSTANDFOUND to make it easy to find the relevant commits/PRs/releases that features/modules where removed.
- Change several commit hashes to the ones that actually appear on master.
Open all links in [LOSTANDFOUND.md](https://github.com/silkeh/RIOT/blob/pr/hyperlink-lost-found/LOSTANDFOUND.md) and see that they work and are present on master.
none

LOSTANDFOUND: add/fix commit hyperlinks

---

boards/nucleo-f303k8/Kconfig
boards/nucleo-f303k8/Makefile.features
boards/nucleo-f303k8/include/periph_conf.h

Add ADC feature.
Untested.
Depends on PR #14860.

boards/nucleo-f303k8: add ADC feature

---

cpu/saml1x/cpu.c

During the review of #14416, I noticed a bug regarding the RTT module.
This module will get stuck during its init process if the RTC was running from a previous boot.
The RTC module is only reset at power on reset so when you flash tests/periph_rtc then tests/periph_rtt, the RTC module will still be running. This PR fixes the clock management of the RTC module to prevent disabling this clock if the RTC was running as the IP doesn't like this. I also add a workaround to early disable the RTC if it was running only if RTC or RTT is in used in the code.
Test the following with master
make BOARD=saml11-xpro -C tests/periph_rtc flash
make BOARD=saml11-xpro -C tests/periph_rtt flash
the RTC output should be good but the RTT should be stuck in the init.
There is no way to recover unless you …

cpu/saml1x: fix RTT issue in init process

---

drivers/include/periph/timer.h

The function needs the `periph_timer_periodic` feature.
Add a `@note` about that to the documentation.

drivers/periph/timer: amend documentation for timer_set_periodic()

---

cpu/stm32/periph/eth.c

Using the `TER` bit in the TX descriptors when only using a single descriptor for sending triggered a hardware bug. Thus, stop using the TER bit and store the currently active TX descriptor in RAM instead.
See https://github.com/RIOT-OS/RIOT/pull/14594#issuecomment-681696715
Bug introduced by https://github.com/RIOT-OS/RIOT/pull/14594

cpu/stm32/periph/eth: Fix transmission bug

---

sys/usb/usbus/cdc/ecm/cdc_ecm_netdev.c

Previously, the function would always return the max_len parameter.
This poses two issues:
1. the API requires to return the actual packet size
2. the API requires that if the packet is larger than max_len, the
packet is flushed and -ENOBUFS is returned
3. this basically bypasses the packet flushing, consequtive _recv()
would return the last packet again
These are fixed by this PR.
This passed the tests before, so maybe ensure that those still pass. Otherwise, double-check API requirements and take a good look at the code.

sys/usb/usbus/cdc_ecm_netdev: fix _recv() return values

---

sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c

The buffer _pktbuf was previously only aligned to a 1 byte boundary. This could result in run time issues. This PR makes sure the buffer is aligned as required and silences warnings generated by `-Wcast-align` where correct alignment is indeed ensured.
Hopefully, this doesn't change any binaries. At least the `.text` section should remain unchanged.

sys/net/gnrc/pktbuf_static: Fix alignment

---

makefiles/kconfig.mk

`Kconfig.dep` depends on `FORCE`, so it is always generated when compiling with Kconfig under normal conditions. When TEST_KCONFIG=1 is set, this file is no longer a dependency for `out.config`. So when cleaning the 'bin' directory, out.config has no direct dependencies that force its rebuilding (the generated directory is order only). This causes the file not to be produced when calling `TEST_KCONFIG=1 make clean all`.
This PR changes the dependency on the 'generated' directory to a direct dependency when `CLEAN` is set and leaves it as order-only when not. This allows to generate out.config only when needed by not depending on `FORCE`.
Calling multiple times `TEST_KCONFIG=1 BOARD=samr21-xpro make -C examples/hello-world clean all` should work.
Reported by @fjmolinas in …

makefiles/kconfig: fix dependencies for out.config target

---

sys/net/gnrc/network_layer/ipv6/nib/_nib-6lr.c

In accordance with [RFC 6775, section 5.2](https://tools.ietf.org/html/rfc6775#section-5.2) an NCE should be set STALE
when an ARO renews the address registration for the address:
> ```
> The routers SHOULD NOT garbage-collect Registered NCEs (see
> Section 3.4), since they need to retain them until the Registration
> Lifetime expires.  Similarly, if NUD on the router determines that
> the host is UNREACHABLE (based on the logic in [RFC4861]), the NCE
> SHOULD NOT be deleted but rather retained until the Registration
> Lifetime expires.  A renewed ARO should mark the cache entry as
> STALE.  Thus, for 6LoWPAN routers, the Neighbor Cache doesn't behave
> like a cache.  Instead, it behaves as a registry of all the host
> addresses that are attached to the router.
> ```
See …

gnrc_ipv6_nib: set NCE stale on incoming ARO

---

boards/mcb2388/doc.txt

Document the implementation status of the MCUs peripherals.

boards/mcb2388: enhance documentation

---

sys/shell/commands/sc_gnrc_icmpv6_echo.c

Fix unaligned memory access in `ping6` shell command
Run `examples/gnrc_networking` and `ping6` should stll work

sys/shell/commands/gnrc_icmpv6_echo: Fix alignment

---

doc/doxygen/src/advanced-build-system-tricks.md

This extends the 'Advanced build system tricks' section with a make
script to select the board debugger and serial based on the USB serial
number as reported by the device. This solution is different from the
udev-rule solution as it doesn't require administrative permissions.
Read the docs :)
None

doc: Extend tricks with Make-only board selector

---

boards/nucleo-f302r8/Kconfig
boards/nucleo-f302r8/Makefile.features
boards/nucleo-f302r8/include/periph_conf.h
cpu/stm32/periph/adc_f3.c

Add ADC feature.
Untested.
Depends on PR #14860.

boards/nucleo-f302r8: add ADC feature

---

boards/nucleo-f303ze/Kconfig
boards/nucleo-f303ze/Makefile.features
boards/nucleo-f303ze/include/periph_conf.h

Add ADC feature.
Untested.
Depends on PR #15119.

boards/nucleo-f303ze: add ADC feature

---

boards/nucleo-f303re/Kconfig
boards/nucleo-f303re/Makefile.features
boards/nucleo-f303re/include/periph_conf.h

Add ADC feature.
Untested.
Depends on PR #15119.

boards/nucleo-f303re: add ADC feature

---

sys/include/net/gnrc/rpl.h

This copies the information from #3662 to the documentation.
Makes it more discoverable and let's people manage their expectations.
Read the documentation.
Did I miss to mention everything?
I noticed routes downward in the tree don't work for all nodes. Should this be documented?
#3662

gnrc/rpl: document implementation status

---

sys/net/gnrc/netif/gnrc_netif_raw.c

... to give upper layer a hint on the interface the packet came from.
`examples/gnrc_minimal` should not run into an assertion:
<details>
```diff
diff --git a/examples/gnrc_minimal/Makefile b/examples/gnrc_minimal/Makefile
index cb657e60b4..f7e72d658e 100644
--- a/examples/gnrc_minimal/Makefile
+++ b/examples/gnrc_minimal/Makefile
@@ -14,7 +14,8 @@ DEVELHELP ?= 0
-USEMODULE += gnrc_netdev_default
+USEMODULE += slipdev_stdio
+CFLAGS += -DGNRC_IPV6_STATIC_LLADDR='"fe80::2"'
USEMODULE += auto_init_gnrc_netif
```
```sh
BOARD=samr21-xpro make -C examples/gnrc_minimal/ -j flash term
```
Let run for a minute or two
</details>
(also see https://github.com/RIOT-OS/RIOT/issues/15171)
`examples/gnrc_border_router` should work as before
<details>
(requires two nodes)
```sh
BOARD=samr21-xpro …
```

gnrc_netif_raw: add NETIF header on receive

---

cpu/stm32/periph/eth.c

The link status was previously not returned via the `value` parameter, as required by the netdev_driver_t API. As a result, e.g. the `ifconfig` shell command showed garbage.
1. Run `examples/gnrc_networking` on the Nucleo-F767ZI (or one of the other two STM32 board with peripheral Ethernet support).
2. Check if the shell command `ifconfig` correctly reports that the link is up or down
Note: In about 1 out of 3 tries, the Ethernet chip does not correctly connect... An issue is open for that.
~~Depends on and includes: https://github.com/RIOT-OS/RIOT/pull/15163~~

cpu/stm32: Fix periph_eth link status [backport 2020.10]

---

pkg/tinycrypt/Makefile

Bump the snapshot of TinyCrypt that we are using.
`tests/pkg_tinycrypt` still works.

pkg/tinycrypt: bump version

---

.gitignore

Prevent firmware files from accidentally being commited.
#15247

.gitignore: ignore .elf

---

sys/net/gnrc/routing/rpl/gnrc_rpl.c

When gnrc_rpl_init was called from a thread with higher priority than
the RPL thread, the initializer's call to gnrc_netreg_register would be
executed before the event loop even had a chance to set up its message
queue.
Rather than introducing full synchronization, this provides the minimum
mitigation by adding an assertion on compatible priorities, and
documentation inside the code. The added thread_yield allows things to
pass even when when priorities are the same, as is the case if the
dhcpv6-client thread calls it with current default priorities.
[edit: filled in the remaining setup after miri was as nice as to remind me that there were ... gaps]
* Run a DHCPv6 server with delegatable prefixes on the upstream module. (I'm using an OpenWRT router whose usb0 interface is part of the LAN …

gnrc_rpl: Check for race against initializer thread

---

boards/microbit/doc.txt

There were some random `bash` strings inside the code examples that are just confusing.
Also we need to specify the board not only for emulation but for normal flashing too.

boards/microbit: fix documentation

---

boards/native/doc.txt

After fiddling around a second time just to find out that I need to install the `gcc-multilib` package in order to build `native` on a modern version of Ubuntu, add that to the `native` documentation.
Also document the native GPIO feature that is missing from the list of features.
alternative to #15283

boards/native: Improve Documentation

---

sys/include/ztimer.h

This PR adds some documentation on the tradeofs of the chosen data structure.

sys/ztimer: add some doc on the data structure choice

---

doc.txt

This elaborates on the brief "additional code parts" line by listing kinds of changes made by DEVELHELP and giving some examples.
(On indentation: The current version built as an indented preformatted block in my doxygen version, so I unindented to make it testable for me).
There's two stages to make this more comprehensive:
* Comprehensively list all *kinds* of things that depend on DEVELHELP. The list here may already do this, but I didn't go through every single DEVELHELP mention in the code base to verify that. New kinds of changes would need documenting then.
Actually, this is what I'd prefer to do, so I'm marking the PR as a draft until I've done a full pass over `git grep DEVELHELP`.
* List every single change (possibly grouped by the above) -- this seems to be overkill. If doxygen …

doc: Give examples of what DEVELHELP does

---

sys/xtimer/xtimer.c

Place a verbatim copy of `_mutex_lock()` as `static` in `xtimer`, so internal mutex function can be optimized one step at a time without breaking `xtimer`.
- `make BOARD=<some_board> -C tests/xtimer_mutex_lock_timeout flash test`
- `make BOARD=<some_board> -C tests/xtimer_rmutex_lock_timeout flash test`
Needed to split https://github.com/RIOT-OS/RIOT/pull/15052, as requested

sys/xtimer: untangle from core/mutex

---

LOSTANDFOUND.md

Follow-up of #15326: add a reference of the removal of nordic_softdevice_ble package in LOSTANDFOUND.md.
I tried to reference the authors as listed in the removed code.
Read and verify the reference points to the right merge commit.
Follow-up of #15326

LOSTANDFOUND.md: add nordic_softdevice_ble package removal

---

drivers/sdp3x/sdp3x.c

Updated improper comments for internal functions of Sensirion sdp3x driver
Nothing to be tested
\-

drivers/sdp3x: Corrected improper comments for internal functions

---

dist/tools/insufficient_memory/add_insufficient_memory_board.sh

It's useful being able to run this script without having Docker installed.
Introduce the `--no-docker` parameter to run the script without docker.
`add_insufficient_memory_board.sh --no-docker` compiles all apps for a board without the use of Docker.

tools/insufficient_memory: restore build with no docker

---

release-notes.txt

This are the release notes for the upcoming 2020.10 release. Please read and ensure that your of the past 3 months work is mentioned.
Read, read, read…
None

release-notes.txt: add 2020.10 release notes

---

release-notes.txt

This are the release notes for the upcoming 2020.10 release. Please read and ensure that your of the past 3 months work is mentioned.
Read, read, read…
None

release-notes.txt: add 2020.10 release notes [backport 2020.10]

---

cpu/stm32/stmclk/stmclk_f0f1f3.c

This PR extends the STM32F0/F1/F3 clock config/initialization with support for MCO (microcontroller clock output). This feature allows to output one clock source among HSE, HSI, PLLCLK / 2 or SYSCLK to a GPIO pin (PA8 with AF0).
On F0 and F3, MCO prescaler can be configured (among 1, 2, 4, 8, 16, the default is 1). No prescaler is available on F1.
LSE/LSE input clocks are not configurable although they could on F0 and F3. This can be done in a follow-up PR.
Using one of the MCO clock source will automatically enable the corresponding underlying clock (HSE, HSI or PLL). So for example, it's possible to use HSI as system clock while using the PLLCLK / 2 as input clock for MCO.
To test this PR, one needs a logic analyzer or a scope to verify the clock output on PA8 when MCO is enabled. I'm …

cpu/stm32f0f1f3: add MCO configuration and initialization

---

core/include/mutex.h

```
make doc && firefox doc/doxygen/html/index.html
```
Need for better documentation become apparent in https://github.com/RIOT-OS/RIOT/pull/15327

core/mutex: improve documentation

---

sys/include/net/uhcp.h

This is the result of [some discussion on the devel mailing list](https://lists.riot-os.org/pipermail/devel/2020-November/006622.html). As proposed by @OlegHahm I added parts of the discussion as a paragraph to the main documentation of UHCP. I also added a half-sentence on which functions are supposed to be implemented by the network stack.
Reading and a happy Murdock and Circle CI.
None

uhcp: improve documentation

---

core/include/msg_bus.h

When reading the documentation, I noticed this doxygen error:
While fixing it, I also took the opportunity to expand on the documentation.
Just read.

core/msg_bus: enhace documentation

---

dist/tools/usb-cdc-ecm/start_network.sh

More Shellcheck fixes. The script uses a few bashisms (`echo -n`) so it is converted to a bash script.
This should be tested with the gnrc_border_router example and a board using USB CDC ECM.
None

usb-cdc-ecm: resolve shellcheck issues

---

sys/net/link_layer/ieee802154/submac.c

This PR fixes a non valid Radio HAL API access from `ieee802154_submac`.
The SubMAC tries to go to its idle state on reception (either RX_ON or TRX_OFF). The problem is, the event is indicated first and right after the function returns the SubMAC tries to set the transceiver state.
If the upper layer wanted to send data (e.g `gnrc_netif_pktq` trying to dequeue a packet on RX_DONE), the SubMAC might call the `ieee802154_radio_set_trx_state` while the transmission is ongoing. This breaks the Radio HAL API.
Try the following patch in master:
```diff --git a/sys/net/link_layer/ieee802154/submac.c b/sys/net/link_layer/ieee802154/submac.c
index 23653b58c4..5cb1e9f2b6 100644
--- a/sys/net/link_layer/ieee802154/submac.c
+++ b/sys/net/link_layer/ieee802154/submac.c
@@ -27,6 +27,8 @@
#define …
```

ieee802154_submac: set TRX state only if SubMAC is idle

---

core/include/mutex.h
core/mutex.c

- Use static inline function for `mutex_try_lock()`
- The implementation is trivial enough with the `inline`-able IRQ API to just always be `inline`-ed
- Rename `_mutex_lock()` to `mutex_lock()` and drop the blocking parameter
- This was possible to the stand-alone `mutex_try_lock()` implementation
- This yields a measurable performance bump
- Tests `tests/mutex_order` and `tests/mutex_unlock_and_sleep` should still pass
- Benchmark `tests/bench_mutex_pingpong` should be faster
Split out of https://github.com/RIOT-OS/RIOT/pull/15052

core/mutex: Cleanup

---

drivers/mtd_mapper/mtd_mapper.c
tests/mtd_mapper/main.c

Implement functions to use the pagewise MTD API.
This way we don't have to fall back to non-pagewise access if the underlying storage implements the pagewise functions.
`tests/mtd_mapper` should still work.

mtd_mapper: implement pagewise functions

---

makefiles/arch/riscv.inc.mk

This improves the target triple detection logic to include all possible target triples of compilers that might be able to generate our binaries.
`make BOARD=hifive1 -C exampes/default` should work if you have a GCC cross compiler able of generating RISC-V binaries for embedded systems, no matter what variant of the target triple you chose.
Suggested by @nmeum in https://github.com/RIOT-OS/RIOT/pull/15176

makefiles/arch/riscv.inc.mk: Detect target triple

---

pkg/jsmn/Makefile

Only fixes for typos and warnings, but good to keep up to date.
`tests/pkg_jsmn` still passes.

pkg/jsmn: bump version

---

core/include/thread.h
core/thread.c
sys/ps/ps.c

This PR untangles core and ps a bit, by turning some of ps' direct accesses to thread_t fields to core API calls.
There are some left (mostly regarding stack defines), will do those in a later PR.
I consider this a minor refactor, so IMO no need for two ACKs.
ps output is widely tested on CI, so a successful run should suffice.

core: refactor thread info 

---

doc/doxygen/src/porting-boards.md

This PR updates the boards porting documentation after #15477 and #15475 were merged since now it's not necessary to include `<programmer>.inc.mk` and `serial.inc.mk` at the board level.
Read the documentation
Doc needs an update after #15477 and #15475 are merged. Depends on #15477

doc: update board porting documentation page

---

cpu/cortexm_common/thread_arch.c

Split `isr_pendsv()`, with the aim of increasing readability.
Shouldn't change binaries, maybe confirm that, for Cortex-M0 and M3+.
Preparation for fixing https://github.com/RIOT-OS/RIOT/issues/15538.

cpu/cortexm_common: split isr_pendsv()

---

CODEOWNERS

Being worked on by me and @bergzand lately.

CODEOWNERS: update for cpu/cortexm_common/

---

.murdock

llvm update broke many builds. Disable for CI until fixed.
https://github.com/RIOT-OS/RIOT/pull/15595

CI: temporarily disable llvm builds

---

sys/xtimer/xtimer.c

Use `mutex_lock_cancelable()` and `mutex_cancel()` to implement `xtimer_mutex_lock_timeout()`.
- `make -C tests/xtimer_rmutex_lock_timeout`
- `make -C tests/xtimer_mutex_lock_timeout`
But both should be run by the CI anyway.
Split out of https://github.com/RIOT-OS/RIOT/pull/15052

sys/xtimer: clean up xtimer_mutex_lock_timeout

---

examples/gnrc_networking/Makefile

Copy the needed DNS modules from `gnrc_border_router` to `gnrc_networking` as well.
This makes it easier to enable DNS when needed.

examples/gnrc_networking: add option to enable DNS

---

boards/mulle/board.c

add error checks of devfs_register()

---

.github/ISSUE_TEMPLATE/bug_report.md
CONTRIBUTING.md
Makefile
README.md
doc/doxygen/src/mainpage.md

We have a forum now. We should advertise that everywhere where we also mention mailing lists.
Read.
None

doc: advertise forum.riot-os.org

---

SECURITY.md

Fixes the mailto link as suggested in https://github.com/RIOT-OS/RIOT/pull/15516#discussion_r540105575
Link should open your configured MUA now.
Follow-up on https://github.com/RIOT-OS/RIOT/pull/15516

SECURITY.md: fix mailto link

---

sys/net/application_layer/cord/ep/cord_ep.c

sys/net/application_layer/cord/ep/cord_ep.c: add error check to cord_ep_register()
Addresses parts of #15524

add error check of cord_common_add_qstring()

---

sys/net/application_layer/uhcp/uhcp.c

Fixes https://github.com/RIOT-OS/RIOT/issues/15574.
See https://github.com/RIOT-OS/RIOT/issues/15574 for steps to reproduce and confirm that with this fix the issue is fixed.
Fixes https://github.com/RIOT-OS/RIOT/issues/15574.

uhcp: check maximum for prefix length

---

cpu/cortexm_common/thread_arch.c

Previously, isr_pendsv() was relying on r12 not being clobbered by sched_run() which is not correct.
This PR fixes the issue by saving and restoring the scratch register used to save the previous sched_active_thread value, in the partial thumb (Cortex-M0 and related) case.
Some juggling of the r4 (thread content) register is required to make this work.
Testing on the samr21-xpro, for some reason bench_sched_nop is a cycle faster with this change. bench_mutex_pingpong is unaffected.
scheduler benchmark tests must still work, for example bench_sched_nop and bench_mutex_pingpong.
Fixes #15538 for the cortex-m0 and m23.

cpu/cortexm_common: fix r12 clobber in pendsv for Cortex-M0

---

sys/net/application_layer/asymcute/asymcute.c

As pointed out in many other PRs, explicit casts should be avoided wherever possible. This PR fixes `asymcute` with that regard, should be  straight forward...
Buildtest should suffice.
none

net/asymcute: rm explicit casts where applicable

---

dist/pythonlibs/testrunner/spawn.py
dist/tools/bmp/bmp.py
tests/pbkdf2/tests/test_base.py

This PR fixes the flake8 issues found by static tests when run on master ([see this static test job ran on master](https://github.com/RIOT-OS/RIOT/actions/runs/467209330)).
The changes are pretty obvious (and IMHO help for code readability). Maybe reviewers will have better suggestions for the variable names though.
Just run `./dist/tools/flake8/check.sh` from RIOTBASE:
- This PR (empty output):
```
./dist/tools/flake8/check.sh 
```
- master:
```
./dist/tools/flake8/check.sh 
There are style issues in the following Python scripts:
dist/pythonlibs/testrunner/spawn.py:59:16: E741 ambiguous variable name 'l'
dist/tools/bmp/bmp.py:76:24: E741 ambiguous variable name 'l'
tests/cond_order/tests/01-run.py:10:1: F401 'os' imported but unused
tests/pbkdf2/tests/test_base.py:9:1: F401 'os' imported …
```

ci/flake8: fix some issues found by static-tests ran on master

---

doc/doxygen/generate-changelog.py

Currently, the output of the [release-notes in the documentation](https://doc.riot-os.org/changelog.html) is broken. This should fix it.
Circle CI should pass and the changelog.html should look correct; point releases are listed in the Table of Contents.
None

doc: generate-changelog: add support for point releases

---

dist/tools/buildsystem_sanity_check/check.sh
dist/tools/pr_check/check.sh

This check really belongs with the static tests. moreover with the buildsystem sanity checks.
The `REMOVE ME` commit should trigger a reaction for `pkg/lwip`.
None

dist/tools: move check for PKG_SOURCE_LOCAL to buildsystem_sanity_check 

---

drivers/w5100/w5100.c

drivers/w5100/w5100.c, when the ringbuffer of w5100 comes to end, the pointer goes back to the start of the buffer, but in 
the wrong positon, this fix correct it.
test/driver_w5100
Fixes https://github.com/RIOT-OS/RIOT/issues/15447

drivers/w5100/w5100.c: correct the pointer position when w5100's buf is full 

---

sys/usb/usbus/usbus.c

Replaces the two critical sections in the usbus thread code with calls from atomic_utils.
`tests/usbus` and hooking up one of the other test applications on a board to a host is enough here.
None

usbus: Use atomic_utils for endpoint flag operations

---

dist/tools/commit-msg/check.sh

Another one of those PRs adding annotations for a check.
The bogus commits attached should generate annotations
None

dist/tools/commit-msg: annotate errors in Github Action

---

dist/tools/headerguards/check.sh

This provides Github annotation support for the `headerguard` check.
None

dist/tools/headerguards: annotate errors in Github Action

---

dist/tools/coccinelle/check.sh

This provides Github annotation support for the `coccinelle` check.
None, but the check-script adaptation is similar to #15746 as both generate patches.

dist/tools/coccinelle: annotate errors in Github Action

---

dist/tools/cppcheck/check.sh

This provides the `cppcheck` with Github annotation support.
~~Depends on #15640~~

dist/tools/cppcheck: annotate errors in Github Action

---

cpu/sam0_common/periph/rtc_rtt.c

Tamper events are used to wake the CPU from Deep Sleep. On enabling, a spurious tamper event is generated, so we block on a mutex that gets unlocked by the tamper event callback before we enter sleep in this case.
Errata 2.17.4 says:
> Upon enabling the RTC tamper detection feature, a false tamper detection *can* be reported by the RTC.
It turns out that this spurious event is not always generated.
If RTC alarm is used and the CPU was previously woken from hibernate by RTC, it *can* happen that the false tamper event is *not* generated.
In this case, we will block indefinitely on the mutex.
To solve this, add a timeout to the event.
Also poll the event instead of using a mutex, as we have already set `PM->SLEEPCFG.bit.SLEEPMODE` at this point.
This has proven difficult / non …

cpu/samd5x: RTC: add timeout to spurious tamper event

---

dist/tools/vera++/check.sh

This provides Github annotation support for the `vera++` check.
None

dist/tools/vera++: annotate errors in Github Action

---

dist/tools/buildsystem_sanity_check/check.sh

This provides Github annotation support for the `buildsystem_sanity_check` check.
None

dist/tools/buildsystem_sanity_check: minor fixes and annotate errors in Github Action

---

dist/tools/codespell/check.sh

This provides Github annotation support for the `codespell` check.
None

dist/tools/codespell: annotate errors in Github Action

---

.github/workflows/release-test.yml

See https://github.com/RIOT-OS/RIOT/pull/15774#issuecomment-760499737

gh/workflows/release-tests: add LoRaWAN parameters as env variables

---

cpu/fe310/clock.c
cpu/fe310/context_frame.c
cpu/fe310/cpu.c
cpu/fe310/include/clk_conf.h
cpu/fe310/include/irq_arch.h
cpu/fe310/include/periph_cpu.h
cpu/fe310/irq_arch.c
cpu/fe310/periph/cpucycle.c
cpu/fe310/periph/gpio.c
cpu/fe310/periph/i2c.c
cpu/fe310/periph/plic.c
cpu/fe310/periph/pm.c
cpu/fe310/periph/rtt.c
cpu/fe310/periph/spi.c
cpu/fe310/periph/timer.c
cpu/fe310/periph/uart.c
cpu/fe310/periph/wdt.c
cpu/fe310/thread_arch.c

Simple uncrustify of the `cpu/fe310` code.
CI should be enough here
None

cpu/fe310: Uncrustify code

---

sys/include/memarray.h
sys/memarray/memarray.c
tests/memarray/Makefile.ci
tests/memarray/main.c
tests/memarray/tests/01-run.py

This PR adds two functions two manage memarray pools. The `memarray_extend` allows for adding new pool areas to an existing memarray pool. the `memarray_reduce` function can remove (partial) areas from the pool.
I've also added an `memarray_available()` to aid tests.
The memarray test application has been extended.
None

memarray: Add functions to extend and reduce the pool with new memory areas

---

dist/tools/ci/static_tests.sh

Using the [`::group` command](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter), the output of the static tests can be made a bit easier to scroll through and find issues, especially for runs that run on a base branch and not on a PR.
See https://github.com/miri64/RIOT/runs/1729102188 for an example run.
None

static-tests: group tests

---

cpu/sam0_common/periph/flashpage.c
tests/periph_flashpage/main.c

- add test of unaligned write to tests/periph_flashpage (sam0 only section regarding user page)
- fix unaligned write for sam0_common/periph/flashpage implementation
The previous implementation did not allow data sizes of < 3 bytes to be written (edit: under all alignment conditions).
The casts within the code could also lead to unaligned `uint32_t` pointers.
An underflow of the `len` variable was previously possible.
The first commit which modifies the test in tests/periph_flashpage should break the test "test_config_page" which is available on sam0 devices with a user page only. The test should hardfault at cpu/sam0_common/periph/flashpage.c:234.
The test will run successfully after applying the second commit.
None

sam0_common/periph/flashpage: fix unaligned write

---

.github/workflows/static-test.yml

Fixes output such as [this](https://github.com/RIOT-OS/RIOT/runs/1728749196#step:5:17).
See https://github.com/miri64/RIOT/runs/1728867466
None

static-tests: increase git diff renameLimit for branch runs

---

tests/gnrc_ipv6_ext_frag/tests-as-root/01-run.py

Currently the test script for `tests/gnrc_ipv6_ext_frag` assumes a certain order and interface ID for the underlying application which provides one for a mocked transfer and one ethos interface to interact with the host-side scripting. However, ever since eb73515e2cfdf5e42c84dfd53489c0e63dc6f00b got merged (and probably others) got merged, that order and numbering is not true anymore, making the test fail at the moment.
This fixes the test to fetch the interface identifiers based on the Ethernet address of the interface (for ethos and assume the other to be the mock interface) and uses those identifiers throughout the script instead of the constant once.
```sh
BOARD=samr21-xpro make -C tests/gnrc_ipv6_ext_frag/ -j flash test-as-root
```
currently fails on master and in release branches …

tests/gnrc_ipv6_ext_frag: fetch Interface IDs dynamically

---

tests/gnrc_ipv6_ext_frag/tests/01-run.py

Currently the test script for `tests/gnrc_ipv6_ext_frag` assumes a certain order and interface ID for the underlying application which provides one for a mocked transfer and one ethos interface to interact with the host-side scripting. However, ever since eb73515e2cfdf5e42c84dfd53489c0e63dc6f00b got merged (and probably others) got merged, that order and numbering is not true anymore, making the test fail at the moment.
This fixes the test to fetch the interface identifiers based on the Ethernet address of the interface (for ethos and assume the other to be the mock interface) and uses those identifiers throughout the script instead of the constant once.
```sh
BOARD=samr21-xpro make -C tests/gnrc_ipv6_ext_frag/ -j flash
sudo BOARD=samr21-xpro make -C tests/gnrc_ipv6_ext_frag/ test
``` …

tests/gnrc_ipv6_ext_frag: fetch Interface IDs dynamically [backport 2021.01]

---

cpu/samd21/doc.txt

SAMD10, SAMD20, SAMD21, SAMR21 all belong to the same family/generation of Atmel MCUs, they are all supported by `cpu/samd21`.

cpu/samd21: update doc.txt with supported MCUs

---

boards/same54-xpro/doc.txt

The table has not been touched since initial support for the board was added.

boards/same54-xpro: update implementation status

---

core/atomic_c11.c
core/include/cib.h
core/include/macros/units.h
core/include/msg_bus.h
core/init.c
core/mbox.c
core/msg.c
core/mutex.c
core/panic.c
core/thread.c
core/thread_flags.c
dist/tools/uncrustify/blacklist.txt
dist/tools/uncrustify/whitelist.txt
sys/include/ztimer.h
sys/include/ztimer/xtimer_compat.h
sys/ztimer/convert_frac.c
sys/ztimer/core.c
sys/ztimer/periph_rtc.c
sys/ztimer/periph_timer.c
sys/ztimer/util.c

Newer versions of `uncrustify` provide more patch suggestions then the once applied in https://github.com/RIOT-OS/RIOT/pull/10867 and https://github.com/RIOT-OS/RIOT/pull/13975. I also applied the discussed fixes from https://github.com/RIOT-OS/RIOT/pull/15778#issuecomment-760936289 (I hope I understood @bergzand correctly :sweat_smile:)
`uncrustify` should pass in the `static-tests` action. The binaries should not change.
None

treewide: re-uncrustify whitelisted files

---

release-notes.txt

This are the release notes for the 2021.01 Release. Please give it a look and make sure that your work in the last 3 months is present here.
Read :)

release-notes.txt: add 2021.01 release notes

---

release-notes.txt

This are the release notes for the 2021.01 Release. Please give it a look and make sure that your work in the last 3 months is present here.
Read :)

release-notes.txt: add 2021.01 release notes [backport 2021.01]

---

pkg/lwip/contrib/lwip.c

Allows activating both Ethernet and WiFi interfaces at the same time using lwIP on ESP boards.
Run ifconfig shell command to list interfaces while running lwIP on an ESP board with
both Ethernet and WiFi active (like ESP32-Ethernet-Kit or Olimex ESP32-EVB).
ifconfig for lwIP is being added in PR #15992.
This is split from PR #15992

lwip/esp: Support adding both netifs (eth+wifi)

---

boards/common/nrf52/Makefile.dep
boards/common/nrf52/include/cfg_clock_32_0.h
boards/microbit-v2/Kconfig
boards/microbit-v2/Makefile
boards/microbit-v2/Makefile.dep
boards/microbit-v2/Makefile.features
boards/microbit-v2/Makefile.include
boards/microbit-v2/board.c
boards/microbit-v2/doc.txt
boards/microbit-v2/include/board.h
boards/microbit-v2/include/gpio_params.h
boards/microbit-v2/include/microbit.h
boards/microbit-v2/include/periph_conf.h
boards/microbit-v2/microbit/Makefile
boards/microbit-v2/microbit/microbit.c
cpu/nrf52/Makefile.features
cpu/nrf5x_common/include/periph_cpu_common.h
cpu/nrf5x_common/periph/gpio.c
cpu/nrf5x_common/periph/uart.c
examples/default/Makefile
tests/board_microbit/Makefile

This PR adds support for the [v2 version of the microbit](https://microbit.org/new-microbit/). It embeds an nrf52833 MCU and to make it fully work, I had to fix a couple of issues in the cpu support.
The LED matrix is adapted (well copy-pasted) from v1 and it works. I can eventually try to put it in common in a follow-up PR.
Every configured features were tested except I2C and SPI. Main remaining problems are:
- access the FXOS8700 accelerometer via internal I2C is not working
- RTT is not working and this explains the failing tests
I can test #15618 with the speaker.
Run compile_and_test_for_board:
```
$ ./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . microbit-v2 --with-test-only --jobs=6 --incremental
[...]
ERROR:microbit-v2:Tests failed: 4
Failures during test: …
```

boards: add support for microbit v2

---

cpu/stm32/periph/gpio_f1.c

Don't iterate over all set bits, only iterate as many times as there are bits set.
The `auto_test` command of `tests/periph_gpio` should still work with two connected GPIOs
#14564

cpu/stm32: GPIO/f1: use bitarithm_test_and_clear()

---

sys/riotboot/flashwrite.c

sys/riotboot/flashwrite.c: add message to static assert 

---

boards/microbit/doc.txt

PR fixes wrong variable name in the otherwise outstanding microbit documentation.

boards/microbit: doc: FLASHTOOL -> PROGRAMMER

---

CODEOWNERS

I'd say this can go in untested.

CODEOWNERS: add @maribu for some more files

---

CODEOWNERS

I have gotten used to ignoring everything that doesn't mention me, lets fix that.
None

CODEOWNERS: reduce the noise

---

cpu/sam0_common/periph/spi.c

On a custom board, commit 31bf0c5257308b39bdb2346262d4c4f6f3418820 broke the `at86rf215` driver.
It is now stuck in a loop
```
2021-02-22 19:44:45,146 # gnrc_netif: possibly lost interrupt.
2021-02-22 19:44:45,149 # gnrc_netif: possibly lost interrupt.
2021-02-22 19:44:45,152 # gnrc_netif: possibly lost interrupt.
2021-02-22 19:44:45,155 # gnrc_netif: possibly lost interrupt.
2021-02-22 19:44:45,158 # gnrc_netif: possibly lost interrupt.
2021-02-22 19:44:45,163 # gnrc_netif: possibly lost interrupt.
```
on init. 
A `git bisect` pointed to 31bf0c5257308b39bdb2346262d4c4f6f3418820 as the culprit and indeed a revert solves the issue.
`tests/driver_at86rf215` should work again.
But there must be something board specific about this bug, it is not exhibited when using REB215-XPRO on …

Revert "cpu/sam0_common: SPI: only mux MISO on spi_acquire()"

---

cpu/esp32/esp-eth/esp_eth_netdev.c

If there is an event to be handled by `_esp_eth_isr()`, don't
overwrite it if a new packet has been received.
In my testing, all `SYSTEM_EVENT_ETH_CONNECTED` events except the first
are immediately followed by at least one `SYSTEM_EVENT_ETH_RX_DONE` event.
This causes the `SYSTEM_EVENT_ETH_CONNECTED` to not get handled, and the
IP stack will not be notified of the new link state.
Protect the other events by dropping the packet instead. If an earlier
unhandled `SYSTEM_EVENT_ETH_RX_DONE` event exists, overwrite it with the
newer packet.
I only saw this happen with lwIP and not with GNRC - I am not sure why.
But it still is a race waiting to happen. The nice long term solution
is probably to have a queue of unhandled events, allowing them all to
be processed once there is time.
Flash an …

esp32/eth: Don't overwrite queued event with RX packet

---

drivers/include/periph/spi.h

- Use negative errno as error codes, rather than home-grown enums
- Update the home-grown enum with negative errno codes for backward compatibility and mark it deprecated
- This brings the API back to current coding practices in RIOT, e.g. as documented in the driver guide
- Update API doc to use negative errno codes
- Fix various style issues in Doxygen doc
- Use `@retval` to document specific return values instead of abusing `@return` for this
- Align parameters to proper indent level
As this change is fully backward compatible, there should not be any issues. But marking previous behavior (using e.g. `SPI_OK`) as deprecated IMO qualifies this as an API change.
- Generated binaries should be *almost* identical. (Using different constants in return values will change binaries, obviously) …

drivers/periph/spi: clean up error codes and doc

---

tests/gnrc_tcp/README.md

This PR corrects the README.md for the gnrc_tcp tests. 
Nothing to test, its updates only the given documentation.

gnrc_tcp: Update test documentation

---

cpu/native/netdev_tap/netdev_tap.c

Both functions are declared as `static inline`, so these changes should not break anything.

cpu/native: rename _get_promiscous/_set_promiscous

---

drivers/include/lis2dh12.h
drivers/lis2dh12/include/lis2dh12_params.h
drivers/lis2dh12/include/lis2dh12_registers.h
drivers/lis2dh12/lis2dh12.c
drivers/lis2dh12/lis2dh12_internal.h
tests/driver_lis2dh12/Makefile
tests/driver_lis2dh12/Makefile.ci
tests/driver_lis2dh12/app.config.test
tests/driver_lis2dh12/main.c

drivers/lis2dh12 are updated with module specific functionality
- added definition for all registers in `lis2dh12_register.h`
- enables change of power mode and data rate
- enables FIFO functionality
- enables use of high pass filter
- enables click detection
- updated test for additional functionality, with user input
- tested with an own board
- old functionality is not touched

driver_lis2dh12: functionality extension

---

sys/include/event.h

No code changed.
Came up in https://github.com/RIOT-OS/RIOT/pull/16144

sys/event: add missing precondition to doc

---

sys/include/phydat.h

Clarify how the `phydat_t::scale` is used in `phydat_fit`.
Render the documenation:
None.

sys/phydat: clarify use of phydat::scale in phydat_fit

---

CODING_CONVENTIONS.md

returning void is allowed changed Any to Every and clarify the message
read
none

doc/Coding_Convention: clarify: void return is allowed

---

tests/cpu_cortexm_address_check/main.c
tests/cpu_efm32_features/main.c
tests/fault_handler/main.c

Ran across these mistakes when I was looking around in test code.

tests: Fix some pedantic mistakes

---

cpu/stm32/periph/eth.c

Fix compilation with module `stm32_eth_link_up` when `stm32_eth_auto`
is not used.
Compilation of `tests/lwip` with https://github.com/RIOT-OS/RIOT/pull/16229 for the Nucleo-F767ZI (or any other STM32 board with Peripheral Ethernet) should now work when compiled with IPv4 support.
Noticed while testing https://github.com/RIOT-OS/RIOT/pull/16229

cpu/stm32/periph_eth: bugfix

---

dist/tools/goodfet/goodfet.bsl

Since python2 is now obsolete we should update the scripts in RIOT to python3.
After a quick search I couldn't find and easy replacement so I did the following:
Apply `2to3` for scripted python 2 to 3 update.
Fix encoding and decoding of serial write and read.
Fix `chr` and `ord` to `to_bytes` and `bytearray`.
Flash boards that use the `goodfet` flasher.
I only tested on the `z1` board.

dist/tools/goodfet: Update goodfet flasher to python3

---

sys/include/random.h

Enable the documentation generation for random floats (e.g. `random_real`), currently missing (see http://api.riot-os.org/group__sys__random.html#ga27cf0bd7f3f0328b7bc4f40acf9a6262 ).
I ran `make doc` on the modified tree.

sys/include/random: generate documentation for random double generation

---

sys/Makefile.dep

Should not contain any semantic changes in the dependency resolution.
Split out of https://github.com/RIOT-OS/RIOT/pull/16268

sys/Makefile.dep: clean up

---

cpu/sam0_common/include/periph_cpu_common.h

This PR fixes a few issues that I spotted earlier today.
Review the documentation.
None.

cpu/sam0: correct periph_cpu_common.h documentation

---

drivers/sht1x/sht1x.c
drivers/sht1x/sht1x_saul.c
sys/shell/commands/sc_sht1x.c

Generated binaries shouldn't differ compared to `master`.
None

drivers/sht1x: fix code style issues

---

dist/tools/tapsetup/tapsetup

tapsetup: fix typo in usage text

tapsetup: fix typo in usage text

---

examples/gnrc_border_router/Makefile
examples/suit_update/Makefile
examples/suit_update/README.md

This fixes a few small errors in the documentation and adds the option to use 1024 byte blocks in `examples/suit_update`
`examples/suit_update` still works with `LARGE_BLOCKS=1`

examples: small fixes

---

drivers/include/soft_uart.h
drivers/soft_uart/include/soft_uart_params.h
drivers/soft_uart/soft_uart.c

Somehow an extra letter has sneaked into the mail and was copy & pasted around.
Read.

drivers/soft_uart: fix typo in eMail address

---

cpu/stm32/include/cpu_conf.h
cpu/stm32/periph/flashpage.c
drivers/include/periph/flashpage.h
drivers/periph_common/flashpage.c

`flashpage_addr()` is a generic function that can be used by other implementations as well.
No code changes, everything should still compile.

drivers/periph: flashpage: add common helper functions

---

makefiles/tools/programmer.inc.mk
makefiles/vars.inc.mk

Documentation change was missed in #16371. This PR is fixing that.
Just read and verify that the comment is in sync with the new behavior.
https://github.com/RIOT-OS/RIOT/blob/0493292ef37534732e9504333d8fd08c0e895b17/makefiles/tools/programmer.inc.mk#L8-L9
#16371

makefiles/vars.inc.mk: update USE_PROGRAMMER_WRAPPER_SCRIPT comment

---

pkg/nanopb/Makefile

Update to nanopb 0.4.5: [Changelog](https://github.com/nanopb/nanopb/blob/master/CHANGELOG.txt)
`tests/pkg_nanopb` still works.

pkg/nanopb: bump version to 0.4.5

---

pkg/doc.txt

longer short description, more details than brief but less that howto build for packages
read 
ci/circleci: doc-build artifact https://9285-7370241-gh.circle-artifacts.com/0/doc/group__pkg.html
Matrix questions about what are packges

doc/pkg: provide a longer short description

---

cpu/esp_common/periph/i2c_sw.c

In I2C, clock stretching occurs when the controller stops driving SCL
down but the peripheral continues to drive SCL down until the value of
SDA that is expected to be set by the peripheral is ready. This allows a
peripheral to communicate at a high speed but introduce a delay in the
response (like an ACK or read) in some specific situations. Not all I2C
peripherals require I2C stretching, and in many cases SCL is only an
input to these peripherals.
Clock stretching is the only situation where a peripheral may drive down
SCL, which technically makes SCL an open-drain with a pull-up like SDA.
However, if clock stretching is not needed, SCL can be configured as an
output removing the need for a pull-up and specially, allowing to use
as SCL GPIO pins that otherwise have a pull-down …

cpu/esp_common: Support disabling I2C clock stretching in ESP8266

---

dist/pythonlibs/riotctrl_shell/loramac.py
dist/pythonlibs/riotctrl_shell/tests/test_loramac.py

This PR adds a loramac shell, to be used in the Release tests.
- green ci
- used in https://github.com/RIOT-OS/Release-Specs/pull/218

dist/pythonlibs/riotctrl_shell: add loramac shell

---

README.md

It seems that with the new website the link to the documentation is gone. This updates the URL in the `Getting started` block of the README to https://doc.riot-os.org.
Read carefully.

README: Update url of documentation

---

cpu/saml21/cpu.c

Microchip SAML21 CPU allows a few slow clock modes which are useful on low power devices, to save energy.
This PR adds support for the PL0 power level modes to the CPU initialization.

SAML21 CPU: support 4MHz, 8MHz, 12MHz CORE_CORECLOCK choices

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

When two threads use `gnrc_ipv6_nib_get_next_hop_l2addr()` to determine a next hop (e.g. when there is both an IPv6 sender and a 6LoWPAN fragment forwarder), a race condition may happen, where one thread acquires the NIB and the other acquires the network interface resulting in a deadlock. By releasing the NIB (if acquired) before trying to acquire the network interface and re-acquiring the NIB after the network interface is acquired, this is fixed.
An example for how the race condition might come to pass is that first, the IPv6 thread, acquires both the `netif` and the NIB for a look-up of an off-link (global) address:
https://github.com/RIOT-OS/RIOT/blob/6e4434a76049356d5c24be606084cd38abc6d432/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L198-L199
and then continues to …

gnrc_ipv6_nib: fix acquire race on gnrc_ipv6_nib_get_next_hop_l2addr()

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

When two threads use `gnrc_ipv6_nib_get_next_hop_l2addr()` to determine a next hop (e.g. when there is both an IPv6 sender and a 6LoWPAN fragment forwarder), a race condition may happen, where one thread acquires the NIB and the other acquires the network interface resulting in a deadlock. By releasing the NIB (if acquired) before trying to acquire the network interface and re-acquiring the NIB after the network interface is acquired, this is fixed.
An example for how the race condition might come to pass is that first, the IPv6 thread, acquires both the `netif` and the NIB for a look-up of an off-link (global) address:
https://github.com/RIOT-OS/RIOT/blob/6e4434a76049356d5c24be606084cd38abc6d432/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L198-L199
and then continues to …

gnrc_ipv6_nib: fix acquire race on gnrc_ipv6_nib_get_next_hop_l2addr() [backport 2021.04]

---

release-notes.txt

Here are the preliminary release notes. Please rearrange/fix/proofread as deemed necessary!

release-notes.txt: add 2021.04 release notes

---

release-notes.txt

Here are the preliminary release notes. Please rearrange/fix/proofread as deemed necessary!

release-notes.txt: add 2021.04 release notes [backport 2021.04]

---

CODEOWNERS

Make sure I don't depend on @maribu to get pinged when CoAP stuff comes in.

CODEOWNERS: Notify @chrysn on CoAP changes

---

cpu/stm32/periph/adc_f3.c

As I no longer work at the laas, I updated my email address.

cpu/stm32/periph/adc_f3.c: e-mail update

---

sys/ps/ps.c

I found no way to display the actual time in a thread. The only way is to display the percentage of every thread. So if you only have the percentage you can not distinguish between very inactive threads, because the percentage gets to zero.
I created a new entry for the `schedstatistics` module. The `ps` command is extended by the `runtime_usec` entry.
The time spend in each thread are calculated from the `xtimer` ticks and are displayed in micro seconds.
For testing you can use `examples/gnrc_networking` with `USEMODULE=schedstatistics make -j` to enable the `schedstatistics` module and see the new entry (`runtime_usec`) after the `ps` command.
I used the `samd20-xpro` for testing, but it should not matter which board is used.

sys/ps: enable runtime_usec output for the ps command

---

core/msg.c
tests/msg_queue_print/Makefile
tests/msg_queue_print/main.c
tests/msg_queue_print/tests/01-run.py

This PR fixes `msg_queue_print`. When the msg_queue is full the  `msg_queue_print` does not print out the messages.
change main in msg_avail to :
```
int main(void)
{
msg_t msges[MSG_QUEUE_LENGTH];
msg_init_queue(msg_queue, MSG_QUEUE_LENGTH);
puts("[START]");
/* add message to own queue */
for (int idx = 0; idx < MSG_QUEUE_LENGTH; ++idx) {
msges[idx].type = idx;
msg_send_to_self(msges + idx);
LOG_INFO("+ add msg: %d\n", idx);
if (msg_avail() != (idx) + 1) {
puts("[FAILED]");
return 1;
}
}
msg_queue_print();
/* receive available messages in queue */
for (int idx = msg_avail(); idx > 0; --idx) {
msg_t msg;
msg_receive(&msg);
LOG_INFO("- got msg: %d\n", (MSG_QUEUE_LENGTH - idx));
if ((int)msg.type != (MSG_QUEUE_LENGTH - idx)
|| msg_avail() != idx - 1) {
puts("[FAILED]");
return 1;
}
} …
```

core/msg.c: fixed msg_queue_print()

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

Consider the following configuration:
nib prefix
2001:16b8:4569:88fc::/62 dev #7  expires 7081 sec deprecates 3481 sec
2001:16b8:4569:88fe::/63 dev #6
If `_on_link()` stops at the first match, a packet received from #7 with a destination in the downstream subnet in #6 would always be sent back via #7 if this happens to be the first entry in the list.
Instead, consider all prefixes and return the one that is the closest match.
I have three boards connected using SLIP (using #16530 and #16531).
The first board also has an Ethernet uplink from which it received a /62 prefix via DHCPv6 for the downstream SLIP interface and a /64 prefix on it's upstream Ethernet interface.
<details><summary>first node</summary>
```
2021-06-07 13:07:02,520 # Iface  6 
2021-06-07 13:07:02,524 #           Long …
```

gnrc_ipv6_nib: consider all prefixes when deciding on-link next hop

---

.github/workflows/release-test.yml

This exposes the `QUIETER` environment variable introduced in https://github.com/RIOT-OS/RIOT/pull/16513 and deployed in https://github.com/RIOT-OS/Release-Specs/pull/224 to the docker container in the release tests.
In [this run](https://github.com/miri64/RIOT/runs/2894603593) the build steps are now a lot [quieter](https://github.com/miri64/RIOT/runs/2894603593?check_suite_focus=true#step:12:83) ;-).
Follow-up on https://github.com/RIOT-OS/RIOT/pull/16513 and https://github.com/RIOT-OS/Release-Specs/pull/224.
Replaces https://github.com/RIOT-OS/Release-Specs/pull/225

gh-actions/release-tests: export QUIETER to docker

---

tests/gnrc_dhcpv6_client_6lbr/tests-as-root/01-run.py

#15508 added support for the Manufacturer Usage Description (MUD, RFC 8520) option to RIOT's DHCPv6 client. As `scapy`, a library that is used for testing the client, did not support this option directly yet, a workaround with an alias based on the generic `DHCP6OptUnknown` was introduced to the `gnrc_dhcpv6_client_6lbr` test.
As a new version (2.4.5) of `scapy` has been released in the meantime, this PR updates the test file while maintaining backwards compability with older `scapy` versions. When using a `scapy` version >= 2.4.5 the newly integrated MUD option is used directly without a workaround. Otherwise, the old solution is used.
To test this PR run the updated test with an older and the current version of `scapy`. It should succeed in both cases. When changing one of the tested …

tests/gnrc_dhcpv6_client_6lbr: Update test for DHCPv6 MUD option

---

boards/6lowpan-clicker/include/periph_conf.h
boards/pic32-wifire/include/periph_conf.h

What the title says.
By datasheet / documentation:
- https://reference.digilentinc.com/_media/reference/microprocessor/wi-fire/wi-fire_rm_revd.pdf
- https://www.mikroe.com/clicker-6lowpan
Required to get https://github.com/RIOT-OS/RIOT/pull/16582 pass

boards/{pic32-wifire,6lowpan-clicker}: Add CLOCK_CORECLOCK

---

cpu/kinetis/Makefile.include

cpu/kinetis: fix RAM_LEN calculation

---

drivers/sx126x/sx126x_netdev.c

Backport of #16570
From #16570

drivers/sx126x: fix netdev send and recv function [backport 2021.07]

---

sys/net/gnrc/netif/lorawan/gnrc_netif_lorawan.c

gnrc_lorawan: fix gnrc_pktbuf_release_error (introduced by #16080) [backport 2021.07]

---

makefiles/kconfig.mk

This PR forces SHOULD_RUN_KCONFIG whenever a previous configuration file is present.
As it is on master, running `make menuconfig` on applications that set `SHOULD_RUN_KCONFIG` to blank (e.g `gnrc_lorawan`) will silently fail because the keys are not set.
It's fine to skip calling Kconfig if an `app.config` file is set and `SHOULD_RUN_KCONFIG` not, but if the user explicitly called `make menuconfig` Kconfig should not be skipped.
This commit also adds a warning when the config file is present and `SHOULD_RUN_KCONFIG` is not.
Thanks @leandrolanzieri for the proposed fix!
```
make clean
SHOULD_RUN_KCONFIG= make
make menuconfig
SHOULD_RUN_KCONFIG= make
```
None so far

makefiles/kconfig.mk: force SHOULD_USE_KCONFIG if config file is present

---

release-notes.txt

Here are the preliminary release notes. Please rearrange/fix/proofread as deemed necessary!

release-notes.txt: add 2021.07 release notes

---

release-notes.txt

Backport of the release notes from #16651

release-notes.txt: add 2021.07 release notes [backport 2021.07]

---

cpu/stm32/periph/rtc_all.c

Added `periph/rtc` support for `CPU_FAM_STM32L5` through adding the required register settings in `cpu/stm32/periph/rtc_all.c` file. 
Run `tests/periph_rtc` with succesful outputs.
```
main(): This is RIOT! (Version: 2021.10-devel-169-g916dc-periph_rtc_l5)
RIOT RTC low-level driver test
This test will display 'Alarm!' every 2 seconds for 4 times
Setting clock to   2020-02-28 23:59:57
Clock value is now   2020-02-28 23:59:57
Setting alarm to   2020-02-28 23:59:59
Alarm is set to   2020-02-28 23:59:59
Alarm cleared at   2020-02-28 23:59:57
No alarm at   2020-02-28 23:59:59
Setting alarm to   2020-02-29 00:00:01
Alarm!
Alarm!
Alarm!
Alarm!
```
DPB protection blocks the bit that clears RTC interrupt (has to be unlocked when clearing the CALRAF bit on RTC_SCR register), this wasn't adviced …

Update cpu/stm32/periph/rtc_all.c for CPU_FAM_STM32L5 support.

---

boards/rpi-pico/doc.txt

- Add note about the OpenOCD version to be used
- Make use of proper Doxygen commands
`make doc; xdg-open doc/doxygen/html/index.html`
Misleading doc found in https://github.com/RIOT-OS/RIOT/pull/16655

boards/rpi-pico: improve doc

---

drivers/include/periph/uart.h

Some terminology issues are fixed. (The speed of an UART interface is
the symbol rate. The unit it is measured in is baud, which is symbols
per second. There is no such thing as baudrate or even baud/s.)
The return codes are changed to use negative errno constants on error
to match the driver design rules. For backward compatibility, the
enum was updated to match the error codes. Unless an application
depends on the exact numerical value (which would be insane), this is
not breaking any code.
Except for the numerical values of the error return codes, this should not change the generated machine code.
None

periph/uart: Fix doc, use errno for return values

---

cpu/sam0_common/periph/eth.c
cpu/sam0_common/sam0_eth/eth-netdev.c

This PR provides a better resilience for the SAM0 ethernet driver in case of heavy traffic in the network.
In some case interrupts fire faster than the netdev thread can process them and we run out of buffers quickly. With this PR, we now check if we don't have buffers available, so we can flush everything and restart reception properly even if we did drop a few in the operation.
See #16451 
Fixes #16451

cpu/sam0: improve ethernet driver resilience

---

cpu/nrf52/periph/i2c.c

Hello everyone.
This PR is related to issue: https://github.com/RIOT-OS/RIOT/issues/16680
It adds i2C 16-bits register addressing support to the NRF52 CPUs. I guess this mainly add compatibility for EEPROM ICs. 
Tested with a NRF52840, a AT24C256C EEPROM, and the according RIOT test script: tests/driver_at24cxxx.
With the "erase flag" set I've got the following output: 
> 2021-08-05 11:00:35,074 # main(): This is RIOT! (Version: 2021.10-devel-293-g1b015-cpu/nrf52/periph/i2c)
2021-08-05 11:00:35,075 # Starting tests for module at24cxxx
2021-08-05 11:00:35,077 # EEPROM size: 32768 byte
2021-08-05 11:00:35,078 # Page size  : 64 byte
2021-08-05 11:00:35,079 # [SUCCESS] at24cxxx_init
2021-08-05 11:00:41,159 # [SUCCESS] at24cxxx_erase
2021-08-05 11:00:41,159 # [SUCCESS] at24cxxx_write_byte …

cpu/nrf52: i2c: add support for 16-bit register addresses 

---

sys/net/gnrc/network_layer/ipv6/nib/nib.c

If the fib contains a route to a subnet via another host, it can not be on-link.
Consider fib entries when deciding whether an address is on-link.
If a route via another host is a stronger match than an on-link prefix, the address must be off-link.
see https://github.com/RIOT-OS/RIOT/pull/8823#discussion_r651841766
this required manually adding a routing entry for the next hop via `nib route add 5 2001:16b8:45b5:9afa::/63 fe80::5884:3bff:fe4f:a903` (~~is it possible to use NDP for this?~~ yes, see #16568)
```
2021-06-15 19:01:41,048 # 2001:16b8:45b5:9afa::/63 via fe80::5884:3bff:fe4f:a903 dev #5
2021-06-15 19:01:41,051 # 2001:16b8:45b5:9af8::/62 dev #5
2021-06-15 19:01:41,054 # 2001:16b8:45b5:9a00::/64 dev #6
2021-06-15 19:01:41,058 # default via fe80::de39:6fff:fe6a:6980 dev #6
```
Here …

gnrc_ipv6_nib: consider largest prefix match when deciding if host on-link

---

sys/include/net/sock/tcp.h

The example has two errors:
- `sock_tcp_accept()` expects a timeout parameter
- `sock_tcp_stop_listen()` expects a pointer
with these fixed, the example actually compiles.
Unfortunately this is not a runable example, so only read and compare with the sock_tcp API. 
Alternatively use this `Makefile` to build it:
```make
APPLICATION = tcp_echo
BOARD ?= native
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_sock_tcp
```

sock: tcp: fix Echo Server example

---

.gitignore

The output of my `git status` has become quite messy. Let's ignore remnants of failed patches so the output is a bit cleaner.

.gitignore: add *.rej and *.save 

---

cpu/native/periph/spidev_linux.c
cpu/stm32/periph/spi.c

Remove duplicated includes introduced in #15902

---

pkg/nimble/README.ipv6-over-ble.md
tests/rng/README.md

cleanup some minor spelling error found by codespell
they caused a notification after i pushed the green button
read the diff

doc: cleanup some minor spelling error found by codespell

---

examples/benchmark_udp/Makefile
examples/gnrc_networking_subnets/Makefile
tests/nimble_rpble_gnrc/Makefile

Those were merged in the meantime, update the Makefiles as well.
Binaries should not change
follow-up to #16744

examples, tests: replace gnrc_netdev_default with netdev_default

---

pkg/nanocbor/Makefile

Include the latest NanoCBOR fix
`tests/pkg_nanocbor` still works
https://github.com/bergzand/NanoCBOR/pull/55

pkg/nanocbor: bump version

---

sys/net/gnrc/netif/pktq/gnrc_netif_pktq.c

This PR schedules dequeues in `gnrc_netif_pktq` immediately if `CONFIG_GNRC_NETIF_PKTQ_TIMER_US` is equal to zero.
This avoids an extra context switch.
This PR also sets the default timer to zero in order to schedule a packet immediately if the lower layer (either network device or dedicated MAC layer) is busy. This reduces the RTT considerably when using MAC layers that might return -EBUSY if the transmit function is called inside the RX function (e.g SubMAC and hopefully soon [OpenDSME](https://opendsme.org))
This was tested using the reworked version of the SubMAC, but it could be tested with current master as well. Make sure pinging large packets (e.g 1024) works as expected using GNRC_NETIF_PKTQ.
None so far

gnrc_netif_pktq: schedule immediately if timer us is equal to zero

---

README.md

This keeps the ASCII-Art logo but adds a ~~PNG~~ SVG graphic to be displayed in the web version. 
Read the new README (in rendered and unrendered version)
Alternative to #15282

README.md: add graphical logo

---

pkg/nimble/autoadv/nimble_autoadv.c

Fixes
```
/home/kaspar/src/riot.rs/pkg/nimble/autoadv/nimble_autoadv.c:163:46: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
if (IS_ACTIVE(NIMBLE_AUTOADV_FLAG_FIELD) && BLUETIL_AD_FLAGS_DEFAULT) {
^  ~~~~~~~~~~~~~~~~~~~~~~~~
/home/kaspar/src/riot.rs/pkg/nimble/autoadv/nimble_autoadv.c:163:46: note: use '&' for a bitwise operation
if (IS_ACTIVE(NIMBLE_AUTOADV_FLAG_FIELD) && BLUETIL_AD_FLAGS_DEFAULT) {
^~
&
/home/kaspar/src/riot.rs/pkg/nimble/autoadv/nimble_autoadv.c:163:46: note: remove constant to silence this warning
if (IS_ACTIVE(NIMBLE_AUTOADV_FLAG_FIELD) && BLUETIL_AD_FLAGS_DEFAULT) {
~^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

pkg/nimble: fix `if(IS_ACTIVE(..) && CONSTANT)` with llvm

---

sys/Makefile.dep
sys/include/ut_process.h
sys/ut_process/Makefile
sys/ut_process/ut_process.c
tests/unittests/tests-ut_process/Makefile
tests/unittests/tests-ut_process/Makefile.include
tests/unittests/tests-ut_process/tests-ut_process.c
tests/unittests/tests-ut_process/tests-ut_process.h

This provides a simple checker and processor for URI templates up to level 3 in accordance with [RFC 6570](https://datatracker.ietf.org/doc/html/rfc6570).
Unittests are provided, they orient themselves on the examples provided in the RFC. Just run
```sh
make -C tests/unittests tests-ut_process test
```
for a board of your choice.
None.

ut_process: initial import of a URI template processor

---

tests/bench_msg_pingpong/main.c

Fixes a bunch of these:
```
In file included from /home/kaspar/src/riot/tests/bench_msg_pingpong/main.c:21:                                                                    
/usr/arm-none-eabi/include/stdatomic.h:201:17: error: unknown type name 'int_least8_t'; did you mean '__int_least8_t'?
typedef _Atomic(int_least8_t)           atomic_int_least8_t;                                                                                       
^                                                                                                                                  
/usr/arm-none-eabi/include/machine/_default_types.h:134:29: note: '__int_least8_t' declared here                                                   
typedef __INT_LEAST8_TYPE__ __int_least8_t; …
```

tests/bench_msg_pingpong: add stdint.h include (for clang & stdatomic.h)

---

Makefile.include

Add a compile-time convenience variable to enable verbose asserts.
alternative to #16864

build system: add VERBOSE_ASSERT flag

---

makefiles/vars.inc.mk

Read the doc...
https://github.com/RIOT-OS/RIOT/pull/16884#issuecomment-927108855

makefiles/vars.inc.mk: Document DEVELHELP and VERBOSE_ASSERT

---

drivers/include/rtt_rtc.h

`epoch` in this context refers to `RIOT_EPOCH`, not Unix Epoch.
Clarify the documentation to avoid confusion.

rtt_rtc: clarify documentation about epoch

---

pkg/tiny-asn1/Makefile
sys/net/credman/credman.c
tests/pkg_tiny-asn1/main.c

Update the tiny-asn1 package to the newest version.
Only minor changes (const pointers are used where possible)
No changes to the unit tests have been made.
https://gitlab.com/mtausig/tiny-asn1/-/merge_requests/3

Update tiny-asn1 package

---

pkg/qr-code-generator/Makefile

Bumps the QR code generator package to the [1.7.0 version](https://github.com/nayuki/QR-Code-generator/releases/tag/v1.7.0). Nothing special to mention.
- Green CI
- Works on native:
<details>
```
$ BUILD_IN_DOCKER=1 RIOT_CI_BUILD=1 make -C tests/pkg_qr-code-generator/ all test --no-print-directory  …
```

pkg/qr-code-generator: bump to 1.7.0

---

sys/auto_init/auto_init.c

sys/auto_init: fix indention

---

dist/tools/uhcpd/project.py

This should never have made it into the repo, it's a build file for an
experimental build system I built years ago.

dist/tools/uhcpd: remove project.py

---

CODING_CONVENTIONS_C++.md

CODING_CONVENTIONS_C++.md: Change space after negation

---

dist/tools/mcuboot/imgtool.md
dist/tools/packer/scripts/riot.sh
dist/tools/vagrant/freebsd/Vagrantfile
tests/mcuboot/README.md

`pycrypto` is unmaintained [[1]] since v2.6.1 (released October 2013). This version, however, has some severe vulnerabilities [[2]] [[3]].
The recommendation is to use the API-compatible `pycryptodome` library.
As FreeBSD appears not to support python 3.7 anymore, I also updated a python 3.8 update (which is the current default python 3 version in FreeBSD 12) as a piggy-back commit.
[1]: https://github.com/pycrypto/pycrypto/issues/173
[2]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-7459
[3]: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-6594
Someone knowledgeable with `mcuboot` (@kYc0o, @kaspar030?) should test, if `mcuboot` still works with `pycryptodome`. 
I tested, if the installation of `pycryptodome` in BSD still works (which led to the piggy-backed `py38` …

pycrypto: use pycryptodome instead

---

pkg/openwsn/doc.txt

This PR updates OpenWSN documentation which was quite out of sync.
Read the docs.

pkg/openwsn: update doc

---

drivers/at30tse75x/Kconfig
drivers/at30tse75x/Makefile.dep
drivers/at30tse75x/at30tse75x.c

port at30tse75x-driver to ztimer_usec
build and run tests/at30tse75x-driver
#17111

driver/at30tse75x: port to ztimer_usec

---

sys/fido2/ctap/ctap_cbor.c

The TinyCBOR library takes a `size_t *` length argument in many functions which at function call contains the length of a buffer, and at exit the actual size of the data. The FIDO-2 code however uses `uint8_t` fields in `struct`s to store the data. Previously, a pointer to that `uint8_t` filed was just casted to `size_t *`, resulting in three neighboring bytes also being interpreted as being part of the buffer size - which could result in undetected buffer overflows. Similar, upon exit of the function not only the `uint8_t` sized length `struct` member but also three neighboring bytes were written to.
I didn't care to investigate, but this really looks like crafted CBOR payloads send to the FIDO2 implementation could result in arbitrary code execution on the device.
Normal operation …

sys/fido2: fix CBOR parsing

---

dist/tools/doccheck/create_pattern.sh

This adds a script to create the patterns from doxygen warnings, with the logic taken from #16779 (comment).

dist/tools/doccheck: add create_pattern.sh

---

sys/fido2/ctap/ctap_cbor.c

The TinyCBOR library takes a `size_t *` length argument in many functions which at function call contains the length of a buffer, and at exit the actual size of the data. The FIDO-2 code however uses `uint8_t` fields in `struct`s to store the data. Previously, a pointer to that `uint8_t` filed was just casted to `size_t *`, resulting in three neighboring bytes also being interpreted as being part of the buffer size - which could result in undetected buffer overflows. Similar, upon exit of the function not only the `uint8_t` sized length `struct` member but also three neighboring bytes were written to.
I didn't care to investigate, but this really looks like crafted CBOR payloads send to the FIDO2 implementation could result in arbitrary code execution on the device.
Normal operation …

sys/fido2: fix CBOR parsing [backport 2021.10]

---

cpu/sam0_common/periph/uart.c

In Asynchronous Fractional baud rate mode, the baud rate can not be greater than the source frequency divided by the oversampling (8, 16).
Currently we are always using 16x oversampling.
This makes it impossible to e.g. set a 2 MHz UART baud rate on the 16 MHz `saml10-xpro`.
With this change, the oversampling is automatically reduced to 8x which allows us to set 16 MHz / 8 -> 2 MHz baud rate.
Run `tests/periph_uart` and try to set a UART baud rate that is greater than the UART GCLK frequency / 16.
On master this will always fail with Asynchronous Fractional Baud rate mode enabled. Writes to the UART will get the system stuck.

cpu/sam0_common: uart: set oversampling based on baud rate

---

SECURITY.md

Adding the new security@riot-os.org key id.

SECURITY.md: add gpg key information

---

cpu/cortexm_common/vectors_cortexm.c

See title
CI runs `static-tests`
none

cpu/cortexm_common: make CI happy

---

cpu/arm7_common/arm7_init.c

The CI runs the `static-tests`
None

cpu/arm7_common: suppress false positives of cppcheck

---

core/include/bitarithm.h

The CI will run `static-tests`
None

core/bitarthm: suppress false positives

---

boards/lora-e5-dev/doc.txt

Had to extend the documentation for a course, better do it in the tree...
Circle ci.

boards/lora-e5-dev: extended documentation

---

dist/tools/radvd/radvd.sh

`radvd` can be started on any interface, not just tap devices.
The help text is confusing.

tools/radvd: fix help text

---

tests/unittests/tests-checksum/tests-checksum-fletcher32.c

Murdock will do so on `native`, but one could also run
```
$ make -C tests/unittests/ BOARD=<board> tests-checksum flash test
```
to confirm no breakage on bare-metal targets.
~~This contains the same commit to enable C11 for MIPS as https://github.com/RIOT-OS/RIOT/pull/17152 - so if one of the two gets in first the other should be rebased on `master`.~~

tests/unittests: fix unaligned access

---

cpu/cortexm_common/thread_arch.c
cpu/esp8266/startup.c
cpu/esp_common/syscalls.c
cpu/esp_common/thread_arch.c
cpu/riscv_common/thread_arch.c
tests/fault_handler/main.c
tests/malloc/main.c

Fix or suppress some cppcheck errors. Mostly pointer comparison when getting stack sizes or similar.
No code change, only comments. The mentioned errors should no longer show in cppcheck run.

Fix some cppcheck errors

---

sys/include/tsrb.h
sys/tsrb/tsrb.c
tests/unittests/tests-tsrb/tests-tsrb.c

This PR adds peek functions to `tsrb`.
Unit tests provided.

sys/tsrb: add peek functions

---

boards/stm32f746g-disco/doc.txt

As requested by @chrysn in https://github.com/RIOT-OS/RIOT/pull/17198#discussion_r750114398, this PR extends a bit the documentation of the stm32f746g-disco that was added in #17198.
Just read and the generated documentation should be ok (see circleci output)
Follow-up of #17198

boards/stm32f746g-disco: extend documentation

---

sys/include/tsrb.h
tests/unittests/tests-tsrb/tests-tsrb.c

Add a function to reset the buffer to its initial state.
A test case was added. Run `make tests-tsrb term`

sys/tsrb: add tsrb_clear

---

dist/tools/zep_dispatch/README.md
dist/tools/zep_dispatch/topology.c

I noticed that the latest addition from #16879 was only documented in the PR description, not the README of the tool itself.
[Read](https://github.com/RIOT-OS/RIOT/blob/49b0cbddd80617b952c9bfcb181195ece3b797c3/dist/tools/zep_dispatch/README.md) (and try following the instructions to see if they make sense).
follow up on #16879

tools/zep_dispatch: document foren6 usage

---

sys/include/ztimer.h

Adds some hints on ztimer usage.

sys/ztimer: add some best practices

---

cpu/nrf5x_common/periph/temperature.c

Modify the periph_temperature implementation to expose the full resolution of the temperature sensor. The accuracy of the sensor will likely be less than 0.25 °C, but typically temperature sensors have a precision in the order of their resolution. Exposing the full resolution can therefore be useful to monitor relative temperature changes.
<details><summary>Output of <code>make BOARD=nrf52840dk PROGRAMMER=openocd flash term -C examples/saul</code></summary>
```
[...]
saul
2021-12-14 22:43:17,122 # saul
2021-12-14 22:43:17,124 # ID	Class		Name
2021-12-14 22:43:17,128 # #0	ACT_SWITCH	LED 1
2021-12-14 22:43:17,128 # #1	ACT_SWITCH	LED 2
2021-12-14 22:43:17,129 # #2	ACT_SWITCH	LED 3
2021-12-14 22:43:17,131 # #3	ACT_SWITCH	LED 4
2021-12-14 22:43:17,132 # #4	SENSE_BTN	Button 1
2021-12-14 …
```

cpu/nrf5x_common/periph_temperature: Increase resolution

---

dist/tools/ci/can_fast_ci_run.py

This runs each changed header or c source file through `gcc -fpreprocessed -dD -E -P -` to strip all comments, for both the base revision and the tested revision. if the hashes match, the file is not added to the changeset.

tools: can_fast_ci_run.py: ignore comment changes for `\.[ch]$`

---

SECURITY.md

Adds a link to download the key to the SECURITY.md
- Read
- Check if Markdown is rendered correctly
- Check if link works
Follow-up on #17189

SECURITY.md: Add key link

---

examples/suit_update/README.hardware.md

To run the test, the README tells to run `make -C examples/suit_update test` although it should be `make -C examples/suit_update tes-with-config`. This is because the automated test script is located under the `test-with-config| directory and needs a custom network setup.
Follow the test procedure in the README:
```
$ BOARD=samr34-xpro make -C examples/suit_update test-with-config
make: Entering directory '/work/riot/RIOT/examples/suit_update'
make -C benchmark_udp
make[2]: Nothing to be done for 'all'.
make -C ethos
make[2]: Nothing to be done for 'all'.
make -C uhcpd
make[2]: Nothing to be done for 'all'.
make -C sliptty
make[2]: Nothing to be done for 'all'.
make -C zep_dispatch
make[2]: Nothing to be done for 'all'.
/usr/bin/make -C benchmark_udp …
```

examples/suit_update: fix test instructions in README

---

sys/include/usb/usbus/hid.h

Another unimplemented function declaration I missed. Same as in #17452 . Sorry for the inconvenience.

usbus/hid: Remove unimplemented function declaration

---

core/include/irq.h
cpu/arm7_common/include/irq_arch.h
cpu/avr8_common/include/irq_arch.h
cpu/cortexm_common/include/irq_arch.h
cpu/esp_common/irq_arch.c
cpu/mips32r2_common/irq_arch.c
cpu/msp430_common/include/irq_arch.h
cpu/native/irq_cpu.c
cpu/riscv_common/include/irq_arch.h

This only cleans up the API, no change in behavior or users of the API is expected.
This is mostly a cosmetic change, if everything still compiles we are good.

core: change return type of irq_is_in(), irq_is_enabled() to bool

---

pkg/fatfs/fatfs_diskio/mtd/mtd_diskio.c
tests/pkg_fatfs/Makefile
tests/pkg_fatfs/Makefile.ci
tests/pkg_fatfs_vfs/Makefile
tests/pkg_fatfs_vfs/Makefile.ci
tests/pkg_fatfs_vfs/main.c

We have the `FEATURES_REQUIRED` now, no need to whitelist boards with SPI and GPIOs.

tests/pkg_fatfs{_vfs}: drop whitelist

---

tests/pkg_edhoc_c/initiator.c
tests/pkg_edhoc_c/tests/01-run.py

While looking at `ryot` results output I saw that EDHOC test was failing on `openmote-b` it was because since it has multiple interfaces the auto-test was failing. This PR changes the test to handle those cases.
`BOARD=openmote-b make -C tests/pkg_edhoc_c/ flash test -j`
```
ifconfig
Iface  6  HWaddr: 4A:8B  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
Long HWaddr: AE:8D:FE:E1:60:C7:CA:8B 
TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
AUTOACK  ACK_REQ  CSMA  L2-PDU:102  MTU:1280  HL:64  RTR  
6LO  IPHC  
inet6 addr: fe80::ac8d:fee1:60c7:ca8b  scope: link  VAL
init handshake fe80::ac8d:fee1:60c7:ca8b%6 5683
inet6 group: ff02::1:ffc7:ca8b
Iface  5  HWaddr: 4A:8A  Channel: 0  Page: 2 …
```

tests/pkg_edhoc: handle multiple interfaces

---

drivers/include/dose.h

I forgot to add documentation for the `dose_watchdog` pseudo-module in #17180, so add it now. 
follow-up on #17180

drivers/dose: add documentation for dose_watchdog

---

tests/pkg_edhoc_c/initiator.c
tests/pkg_edhoc_c/tests/01-run.py

While looking at `ryot` results output I saw that EDHOC test was failing on `openmote-b` it was because since it has multiple interfaces the auto-test was failing. This PR changes the test to handle those cases.
`BOARD=openmote-b make -C tests/pkg_edhoc_c/ flash test -j`
```
ifconfig
Iface  6  HWaddr: 4A:8B  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
Long HWaddr: AE:8D:FE:E1:60:C7:CA:8B 
TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
AUTOACK  ACK_REQ  CSMA  L2-PDU:102  MTU:1280  HL:64  RTR  
6LO  IPHC  
inet6 addr: fe80::ac8d:fee1:60c7:ca8b  scope: link  VAL
init handshake fe80::ac8d:fee1:60c7:ca8b%6 5683
inet6 group: ff02::1:ffc7:ca8b
Iface  5  HWaddr: 4A:8A  Channel: 0  Page: 2 …
```

tests/pkg_edhoc: handle multiple interfaces [backport 2022.01]

---

.github/workflows/test-on-iotlab.yml

Add the `dwm1001`.
Run the workflow, `examples/twr_aloha` should be run and pass for this BOARD.

.github/workflows/test-on-iotlab: add dwm1001

---

cpu/native/native_cpu.c

Building `fuzzing/gcoap` with afl-gcc 11.2 gives
```
/home/benpicco/dev/RIOT/cpu/native/native_cpu.c: In function ‘thread_stack_init’:
/home/benpicco/dev/RIOT/cpu/native/native_cpu.c:120:11: error: variable ‘stk’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
120 |     char *stk = NULL;
|           ^~~
/home/benpicco/dev/RIOT/cpu/native/native_cpu.c:118:72: error: argument ‘stack_start’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
118 | char *thread_stack_init(thread_task_func_t task_func, void *arg, void *stack_start, int stacksize)
|
```
We can re-write the function to not use this temporary variable and the error goes away.
Any `native` application should still run.
You can also build the fuzzing examples on a recent distribution again.

cpu/native: fix build with afl-gcc 11.2

---

release-notes.txt

These are the release notes for the 2022.01 release. Please give it a look!
Make sure that your work in the last 3 months is present in the list ;)
See notes ;)

release-notes.txt: add 2022.01 release notes

---

release-notes.txt

These are the release notes for the 2022.01 release. Please give it a look!
Make sure that your work in the last 3 months is present in the list ;)
See notes ;)

release-notes.txt: add 2022.01 release notes [backport 2022.01]

---

tests/pkg_edhoc_c/Makefile

This test fails rather regularly on CI, so disable it.
```
socat - open:/dev/ttyUSB0,b115200,echo=0,raw
File "/tmp/dwq.0.5480675865160537/2c1d3acc7a86753de0db3a13fc04973d/tests/pkg_edhoc_c/tests/01-run.py", line 101, in <module>
sys.exit(run(testfunc))
File "/tmp/dwq.0.5480675865160537/2c1d3acc7a86753de0db3a13fc04973d/dist/pythonlibs/testrunner/__init__.py", line 28, in run
logfile=sys.stdout if echo else None)
File "/tmp/dwq.0.5480675865160537/2c1d3acc7a86753de0db3a13fc04973d/dist/pythonlibs/testrunner/spawn.py", line 88, in setup_child
sync_child(child, env)
File "/tmp/dwq.0.5480675865160537/2c1d3acc7a86753de0db3a13fc04973d/dist/pythonlibs/testrunner/spawn.py", line 123, in sync_child
TEST_INTERACTIVE_DELAY)
File …
```

tests/pkg_edhoc_c: blacklist esp32-wroom-32

---

dist/tools/zep_dispatch/README.md
dist/tools/zep_dispatch/topogen.sh

This adds some description to the usage of `topogen`
Try to follow the instructions to see if they make sense.

tools/zep_dispatch: document topogen usage

---

tests/driver_lc709203f/README.md

The documentation is incorrect, see https://forum.riot-os.org/t/lc709203f-test-code-giving-hardfault/3509

tests/driver_lc709203f: fix documentation

---

pkg/tinycbor/Makefile

Bump version to 0.6.0
`tests/pkg_tinycbor` still works

pkg/tinycbor: bump version

---

pkg/fatfs/fatfs_vfs/fatfs_vfs.c

This hooks up the statvfs() function to query file system properties.
Cluster size is 64 sectors, sector size is 512 bytes. So 242560 32k clusters adds up for a 8 GB SD card.
```
2022-02-10 15:44:32,919 # vfs df /
2022-02-10 15:44:32,925 # Mountpoint              Total         Used    Available     Capacity
2022-02-10 15:44:32,930 # /                      242560          491       242069       0%
2022-02-10 15:45:05,382 # ls /test
2022-02-10 15:45:05,394 # 0.CNK	4194510 B
2022-02-10 15:45:05,403 # 1.CNK	4195975 B
2022-02-10 15:45:05,411 # 2.CNK	4197915 B
2022-02-10 15:45:05,420 # 3.CNK	2178228 B
2022-02-10 15:45:05,421 # total 4 files
```
491 clusters (15712 kB) are allocated for 4 files totaling 14420k.

pkg/fatfs: implement statvfs()

---

sys/include/net/dhcpv6/client.h

I always keep forgetting which option to tweak when I want multiple downstream networks.

sys/net/dhcpv6: enhance doc of CONFIG_DHCPV6_CLIENT_PFX_LEASE_MAX

---

cpu/sam0_common/periph/gpio.c

On SAM L21 only 8 EXTWAKE pins can wake the CPU from Backup sleep.
Handle this analogous to the RTC tamper pins on SAM D5x/E5x where configuring them as an interrupt will also cause them to wake the device from Deep Sleep.
Flash the `tests/periph_gpio` on e.g. `saml21-xpro`. The user button is connected to PA02 which can be used as an EXTWAKE source.
```
init_int 0 2 0 
…
pm set 0
```
If you press the button again, the CPU should wake up from sleep.
~~*still untested as I currently don't have access to the hardware*~~

cpu/sam0_common: implement EXTWAKE for SAM L21

---

.github/workflows/tools-test.yml

apt-get should run an update before trying to install packages
see tools-test (python-tests) not failing (hope it takes this one and no master)

workflow/tool-test:  update prior install

---

pkg/lwip/contrib/sock/lwip_sock.c

Move includes where they belong.

pkg/lwip: move includes to the top of the file

---

examples/emcute_mqttsn/Makefile

 Make example/emcute_mqtt honor radio settings 

---

examples/suit_update/README.hardware.md

I had the mistake of creating `coaproot` inside the application directory, add a few words to prevent that mistake in the future.
Follow the instructions.

examples/suit_update: clarify README.hardware.md

---

.github/workflows/tools-buildtest.yml
dist/tools/benchmark_udp/Makefile

The location of `list.h` did change
follow-up to #17652

tools/benchmark_udp: fix build

---

pkg/littlefs2/Makefile

Update to the new release: https://github.com/littlefs-project/littlefs/releases/tag/v2.4.2

pkg/littlefs2: bump version to 2.4.2

---

drivers/mtd_sdcard/mtd_sdcard.c
drivers/sdcard_spi/sdcard_spi.c

Only print errors when debug is enabled.

drivers/mtd_sdcard: drop printf()

---

tests/pbkdf2/Makefile
tests/periph_flashpage_unittest/main.c
tests/periph_timer_periodic/tests/01-run.py
tests/pkg_micro-ecc/Makefile
tests/ps_schedstatistics/Makefile
tests/ps_schedstatistics/main.c
tests/sys_sched_round_robin/Makefile
tests/sys_sema_inv/main.c

With #17721 I ran tests on multiple platforms and discovered failing tests that were unrelated to that PR. This PR fixes them. The affected platforms are `avr` and `z1`, running the affected tests on those platforms should be enough.
- I'll post run-results

tests: multiple fixes

---

cpu/sam0_common/periph/eth.c
cpu/sam0_common/sam0_eth/eth-netdev.c

Implement SLEEP mode by disabling the clock. This reduces the current consumption by ~3 mA.
```
2022-03-30 13:55:43,297 # > ping 2600::
2022-03-30 13:55:43,426 # 12 bytes from 2600::: icmp_seq=0 ttl=52 time=123.890 ms
2022-03-30 13:55:44,425 # 12 bytes from 2600::: icmp_seq=1 ttl=52 time=123.211 ms
2022-03-30 13:55:45,425 # 12 bytes from 2600::: icmp_seq=2 ttl=52 time=123.191 ms
2022-03-30 13:55:45,426 # 
2022-03-30 13:55:45,428 # --- 2600:: PING statistics ---
2022-03-30 13:55:45,433 # 3 packets transmitted, 3 packets received, 0% packet loss
2022-03-30 13:55:45,438 # round-trip min/avg/max = 123.191/123.430/123.890 ms
2022-03-30 13:55:52,658 # > ifconfig 5 set state sleep
2022-03-30 13:55:52,662 # success: set state of interface 5 to SLEEP
2022-03-30 13:55:54,297 # > ping 2600:: …
```

cpu/sam0_eth: implement SLEEP state

---

sys/net/gnrc/network_layer/ndp/gnrc_ndp.c

I believe, the override flag in `gnrc_ndp_nbr_adv_send()` is not set correctly, due to a forgotten `!`.
It is set, if a TL2A option is supplied and if the target address is an anycast address.
From RFC4861:
> If the Target Address is either an anycast address or a unicast
> address for which the node is providing proxy service, or the Target
> Link-Layer Address option is not included, the Override flag SHOULD
> be set to zero.  Otherwise, the Override flag SHOULD be set to one.
So it should be set, if `target is not anycast && we are not a proxy for target && TL2A is supplied`.
I am also not sure if `pkt != NULL` is equivalent to `TL2A supplied`, because if `supply_tl2a` is false, `pkt` is whatever `ext_opts` is.

gnrc/ndp: bugfix set O-flag if target is not anycast

---

.murdock

Enabling this causes too many false negatives. So, disable for now, and sort out later.

CI: disable microbit testing

---

.murdock

Enabling this causes too many false negatives. So, disable for now, and sort out later.

CI: disable microbit testing [backport 2022.04]

---

examples/wasm/.gitignore

This PR is just a cleanup to add a .gitignore to the`example/wasm` application directory to ignore the generated `hello.wasm` file.
Maybe this PR is not relevant, I admit I haven't checked in detail how the `examples/wasm` build is supposed to work (and it doesn't seem trivial)
- Build `examples/wasm` and check that git doesn't list `hello.wasm` as untracked file.
Discovered while running the `compile_and_test_for_board.py` script in #17954

examples/wasm: ignore generated hello.wasm

---

drivers/sdcard_spi/sdcard_spi.c

Both _sw_spi_rxtx_byte and _hw_spi_rxtx_byte return always 1, so
having a return value and checking for it does not make sense,
instead, return void and remove the checks
`tests/sdcard_spi` still works.
```shell
2022-04-20 14:59:46,195 # init
2022-04-20 14:59:46,214 # Initializing SD-card at SPI_0...[OK]
> 2022-04-20 14:59:52,743 # main(): This is RIOT! (Version: 2022.07-devel-125-g02ce1-pr_scard_spi_cleanup)
2022-04-20 14:59:52,746 # SD-card spi driver test application
2022-04-20 14:59:52,752 # insert SD-card and use 'init' command to set card to spi mode
2022-04-20 14:59:52,759 # WARNING: using 'write' or 'copy' commands WILL overwrite data on your sd-card and
2022-04-20 14:59:52,765 # almost for sure corrupt existing filesystems, partitions and contained data!
> init
2022-04-20 …
```

drivers/scard_spi: _dyn_spi_rxtx_byte return void

---

sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/nanocoap.c
sys/net/application_layer/nanocoap/sock.c

This splits off some minor fixes from #17950

nanocoap: follow-up fixes (uncontroversial parts)

---

pkg/pkg.mk

Add git quiet when cloning.
Silenced clone logs.
Cleanup from  #16316

pkg/pkg: add GIT_QUIET

---

pkg/hacl/doc.txt

replace doc.txt link by something not 404
these links may not be the best option but a certainly better that 404
read

pkg/hacl: documentation link update

---

CODEOWNERS

Since @cgundogan seems to not be super interested in kconfig anymore and I guess am...
None

CODEOWNERS: replace cgundogan->MrKevinWeiss for kconfig

---

sys/suit/storage/flashwrite.c

Just reduce the log level.
Murdock? Sad to do a full run for this though....

sys/suit/storage: change log to LOG_DEBUG

---

sys/include/time_units.h

Added all sensible conversion factors up to days to `time_units.h` and ordered them.
Just checking the numbers should IMO be enough.
None

sys/include/time_units.h: add more constants

---

sys/include/net/nanocoap.h
sys/net/application_layer/nanocoap/sock.c

- we must not immediately return when receiving a RESET packet as this would leak the RX buffer
- The return values of `coap_blockwise_cb_t` don't have to be as strict as the documentation suggests, adopt documentation to better match reality.

nanocoap: minor fixes

---

release-notes.txt

These are the release notes for the 2022.04 release. Please note that this initial version contains mostly the automated output from release-manager tool. There's probably still a lot of room for improvement.
@chrysn, what were the most important improvements regarding RUST support?
@kaspar030, what was the major step regarding ztimer in this release?
Everyone, please check whether I missed to explicitly list a highlight.
Read it!
n/a

Pr/release notes 2022.04

---

sys/vfs/vfs.c

`vfs_sysop_stat_from_fstat()` is a fallback implementation of `stat()` based on `fstat()`.
It will open a file and call `fstat()`.
This fails if the target is not a file but a directory, which means that directories are not recognized as such.
To fix this, try to open the path as a directory if opening it as a file fails. If this succeeds, set the `S_IFDIR` flag.
Just list the files on a FAT filesystem:
```
2022-05-03 16:48:46,950 # > ls /sd0
2022-05-03 16:48:46,951 # SYSTEM~1
2022-05-03 16:48:46,952 # TEST
2022-05-03 16:48:46,952 # ICT
2022-05-03 16:48:46,953 # RANGE
2022-05-03 16:48:46,953 # FW
2022-05-03 16:48:46,954 # TRASH-~1
2022-05-03 16:48:46,955 # FW.BIN	64 B
2022-05-03 16:48:46,957 # IMAGE.BIN	93032 B
2022-05-03 16:48:46,958 # total 2 files
```
```
2022-05-03 16:47:46,423 # > ls …
```

vfs: fix dir detection in vfs_sysop_stat_from_fstat()

---

makefiles/libc/picolibc.mk

See title
Changes a message printed only, no testing required
None

makefiles/libc/picolibc.mk: Fix typo

---

pkg/nanopb/Makefile

New bugfix release, see [changes](https://github.com/nanopb/nanopb/blob/master/CHANGELOG.txt).
```
main(): This is RIOT! (Version: 2022.07-devel-573-gb94dd6)
Your lucky number was 13!
{ "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 436 }]}
{ "threads": [{ "name": "main", "stack_size": 12288, "stack_used": 2628 }]}
```

pkg/nanopb: bump version to 0.4.6

---

dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
dist/tools/compile_and_test_for_board/setup.cfg

As PR title.
Green static checks

dist/tools/compile_and_test_for_board: fix lint

---

sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c

In a881af8b08f39 we would return early if the subnet did not change, but we must still send the router advertisement with the route information option to the upstream network, otherwise hosts in that network will not consider the downstream subnet off-link.
`nib route` (or `ip -6 route` on Linux) should now again look like this
```
2022-06-09 16:58:16,681 - INFO # fd11::/16 dev #5
2022-06-09 16:58:16,683 - INFO # fd11:4000::/18 dev #7
2022-06-09 16:58:16,684 - INFO # fd11:8000::/18 dev #6
2022-06-09 16:58:16,689 - INFO # fd11:a000::/20 via fe80::b84c:f01d:6e42:57bb dev #6
2022-06-09 16:58:16,694 - INFO # fd11:9000::/20 via fe80::b84c:f01d:6e42:57bb dev #6
2022-06-09 16:58:16,697 - INFO # default via fe80::2943:95f9:56d9:b77 dev #5
```
for a downstream router with 3 subnets and downstream …

gnrc/ipv6_auto_subnets: always send RIO to upstream network

---

sys/shell/commands/sc_lwip_netif.c

Add information about the address state (e.g. if it is valid, preferred, tentative, how many probes have been sent if it is still tentative). This is helpful for debugging an issue with IPv6 when netifs require some time to establish a link (e.g. the STM32 Ethernet driver only reports the link to be up once the auto-negotation is completed if the `stm32_eth_auto` is used).
Type `ifconfig` in an app that uses the shell, `shell_commands`, `lwip_netif` and IPv6. 
None

sys/shell/commands/sc_lwip_netif.c: add address state

---

drivers/include/mtd.h
drivers/mtd/mtd.c

The function allows for offsets greater than the page size.

dirvers/mtd: fix documentation of mtd_write_page_raw() and mtd_read_page()

---

cpu/esp32/doc.txt

This PR includes a number of very small doc fixes for ESP32.
Green CI
Split off from PR #17841

cpu/esp32: small doc fixes

---

sys/net/application_layer/dns/cache.c

In https://github.com/RIOT-OS/RIOT/pull/18329#discussion_r924622627, @benpicco realized, that synchronization of cache access is missing for `dns_cache`. This adds the missing synchronization.
`tests/unittests` should still pass.
Follow-up on #18318.

dns_cache: synchronize access with mutex

---

cpu/esp32/periph/adc_arch_esp32.c
cpu/esp32/periph/gpio.c
cpu/esp32/periph/i2c_hw.c
cpu/esp32/periph/pwm.c
cpu/esp32/periph/spi.c

This PR is a split-off from #17842, providing some sanity checks.
Green CI
Split-off from #17842

cpu/esp32: add some sanity checks in peripheral drivers

---

sys/include/random.h
sys/random/random.c

Get rid of the need for casting.
No logic changes, green CI should suffice.

random: use void * in random_bytes()

---

sys/net/application_layer/asymcute/asymcute.c

As per Section 5.2.1 of the MQTT-SN specification, the MQTT-SN length header is either 1- or 3-octet long. If it is 3-octet long then the first octet is `0x01`. The asymcute implementation currently only checks that the incoming packet is at least 2-octet long before attempting to parse it (`MIN_PKT_LE`N):
https://github.com/RIOT-OS/RIOT/blob/4dcb8edcc8f985ba25f83cccf0a7c8d2ceee74f2/sys/net/application_layer/asymcute/asymcute.c#L578
However, if the first octet is `0x01` the packet must be more than 3 octet long in order to be valid. Since asymcute does not check this it reads one octet beyond the packet data (via `byteorder_bebuftohs` which reads a `uint16_t` in `_len_get`) for a 2-octet packet where the first octet has the value `0x01`. This commit fixes this issue by adding an …

asymcute: fix one byte out-of-bounds access in _len_get

---

dist/tools/suit/password_protect_key.py

-  This file provides encryption to an existing key. It won't generate any key but the idea is that you 
- already have a key, and you need to encrypt it. 
- In order to test it, just provide an existing key you have, the default.pem would be great, then 
-execute the file along with the password you want to use and the path to the .pem file.

dist/tools/suit: encrypt an existing key

---

cpu/esp32/ld/esp32s2/memory.ld
cpu/esp32/ld/esp32s2/sections.ld

This PR is a split-off from #18235. It adds the linker script for ESP32-S2.
Green CI.

cpu/esp32: add linker scripts for ESP32-S2

---

cpu/sam0_common/periph/spi.c

The SPI clock can’t be higher than the source GCLK, so clamp it to that.
This is useful when using the same configuration across multiple boards with different frequencies or when enabling the `USE_XOSC_ONLY` option on same54-xpro

cpu/sam0_common: spi: limit clock to source clock

---

sys/Makefile.dep
sys/shell/commands/sc_nanocoap_vfs.c

- make use if `vfs_is_dir()` so users don't have to type the `/` at the end of the destination directory
- allow to set the default download directory via CFLAGS

sys/shell: ncget: convenience improvements

---

pkg/libhydrogen/Makefile

Just bump to the latest master

pkg/libhydrogen: bump version

---

tests/thread_priority_inversion/main.c

As trivial as the title says.
Run `tests/thread_priority_inversion`.
```
READY
s
START
main(): This is RIOT! (Version: 2022.10-devel-596-gdfcd2)
low priority thread has started
low priority thread started to work on its task
high priority thread has started
low priority thread is done
high priority thread started to work on its task
high priority thread is done
{ "threads": [{ "name": "high, "stack_size": 512, "stack_used": 228}]}
mid priority thread has started
mid priority thread started to work on its task
... this ...
... takes ...
... bloody ...
... ages ...
... to ...
... complete ...
mid priority thread is done
{ "threads": [{ "name": "mid, "stack_size": 512, "stack_used": 220}]}
{ "threads": [{ "name": "low, "stack_size": 512, "stack_used": 228}]}
TEST PASSED
```
```
READY
s
START …
```

tests/thread_priority_inversion: improve output for debugging

---

.murdock

We've seen the "makefile_error" weirdness... This PR tries to provide some more insight into what's actually faililng.

CI: improve makefile broken handling

---

core/lib/include/macros/xtstr.h
cpu/atmega_common/periph/uart.c
cpu/atxmega/include/cpu_ebi.h
cpu/cc26x0_cc13x0/include/cc26x0_cc13x0_aux.h
cpu/cc26x0_cc13x0/include/cc26x0_cc13x0_prcm.h
cpu/cc26xx_cc13xx/doc.txt
cpu/esp8266/periph/timer.c
cpu/gd32v/periph/gpio.c
cpu/stm32/periph/gpio_f1.c
dist/tools/codespell/ignored_words.txt

Static tests started complaining about those on master, so let's fix them.

treewide: fix typos

---

drivers/include/net/netdev.h
sys/usb/usbus/cdc/ecm/cdc_ecm_netdev.c

This one was missed previously.

USBUS/cdc_ecm: register with netdev

---

.murdock.yml

This PR introduces some per repo configuration for the coming and under test [Murdock instance](https://ci-staging.riot-os.org).
The configurations provided should enable:
- comment on PRs with a link to the job and eventually some failing builds/tests, plus some stats
- skipping a job if the comment of the commit to build contains some keywords
- a downloadable result.json.gz file with a link on the Murdock UI of the job
- Green Murdock (both :) )
- Comments should be reported in this PR by riot-ci user
- Not sure but if some builds are triggered there should be a link to result.json.gz on the Murdock job page.
None

.murdock.yml: add new Murdock configuration

---

.murdock.yml

"staging" and "testing" were added to be prepared vor [bors](https://bors.tech).
But according to https://bors.tech/documentation/getting-started/, actually it's "trying" instead of "testing".

murdock: fix bors branch name (testing -> trying)

---

.github/labeler.yml

ci: teach github-labeler about .murdock.yml

---

pkg/lwip/contrib/sock/ip/lwip_sock_ip.c
pkg/lwip/contrib/sock/lwip_sock.c
pkg/lwip/contrib/sock/tcp/lwip_sock_tcp.c
pkg/lwip/contrib/sock/udp/lwip_sock_udp.c

When I was working on the MSG_PEEK flag I had a hard time understanding the lwip code. This PR aims to improve readability of the code.
Dependency for and split out from #16850

pkg/lwip: refactor code

---

sys/include/checksum/crc16_ccitt.h

The documentation was not updated when non-lookup table versions of the CRC-16 algorithms were added.
Also, it should read `crc16_fast`, not `crc32_fast`
follow-up to #18701

sys/checksum: update CRC-16 documentation

---

cpu/arm7_common/arm_cpu.c
tests/thread_stack_alignment/Makefile
tests/thread_stack_alignment/Makefile.ci
tests/thread_stack_alignment/README.md
tests/thread_stack_alignment/main.c
tests/thread_stack_alignment/tests/01-run.py

`thread_stack_init()` didn't correctly set up the stack alignment. This fixes the issue and brings the function closer to the Cortex M version, laying the groundwork for future code duplication.
```
$ make BOARD=msba2 tests-printf_float -C tests/unittests flash test
```
In `master`, this fails. With this PR, it succeeds.
The new test application `tests/thread_stack_alignment` provides a bit more insight in the actual issue.
```
make BOARD=msba2 flash test -C tests/thread_stack_alignment
```
The test fails for four out of eight possible alignments.
<details><summary>Full log output</summary>
```
READY
s
START
main(): This is RIOT! (Version: 2022.10-devel-880-g3a9f3-tmp)
Testing with a stack sized 1664 and an alignment up to 128
Testing …
```

cpu/arm7_common: align stacks correctly

---

pkg/lvgl/Makefile

This is just a bug fix release so no changes required on the RIOT side. Only tested using the native port and works as expected.
`tests/pkg_lvgl` and `tests/pkg_lvgl_touch` are still working (tested on native with SDL)
None

pkg/lvgl: bump to 8.3.3

---

pkg/arduino_sdi_12/Makefile
pkg/arduino_sdi_12/patches/0001-Use-RIOT-s-gpio-to-handle-pin-change-interrupts.patch
pkg/arduino_sdi_12/patches/0002-Integration-with-RIOT-to-support-other-boards.patch
pkg/arduino_sdi_12/patches/0003-RIOT-Fix-for-SAMD-boards.patch

Mostly doc changes since the last commit hash, patches now apply without the 3-way merge.

pkg/arduino_sdi_12: bump version, fix patches [backport 2022.10]

---

examples/nanocoap_server/coap_handler.c
tests/riotboot_flashwrite/coap_handler.c

`coap_build_reply()` may return negative values on error or 0 in the no-response case.
Don't use it to calculate a payload offset without checking first.

examples: check return value of coap_build_reply()

---

tests/pkg_tinyvcdiff/main.c

Move some variables from stack to `.bss` / `.data` to avoid stack overflows, which are detected by the MPU stack guard (e.g. on the Nucleo-F767ZI that I used) and results in the test failing.
```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
```
```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-307-g19021)
..*** RIOT kernel panic:
MEM MANAGE HANDLER
*** halted.
Inside isr -12
```
```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-308-g038e3-tests/pkg_tinyvcdiff)
..
OK (2 tests)
```

tests/pkg_tinyvcdiff: fix stack overflow

---

tests/pkg_tinyvcdiff/main.c

Move some variables from stack to `.bss` / `.data` to avoid stack overflows, which are detected by the MPU stack guard (e.g. on the Nucleo-F767ZI that I used) and results in the test failing.
```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
```
```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-307-g19021)
..*** RIOT kernel panic:
MEM MANAGE HANDLER
*** halted.
Inside isr -12
```
```
$ make BOARD=nucleo-f767zi -C tests/pkg_tinyvcdiff flash test
[...]
READY
s
START
main(): This is RIOT! (Version: 2023.01-devel-308-g038e3-tests/pkg_tinyvcdiff)
..
OK (2 tests)
```

tests/pkg_tinyvcdiff: fix stack overflow [backport 2022.10]

---

boards/samd21-xpro/include/periph_conf.h
boards/same54-xpro/include/periph_conf.h
boards/saml21-xpro/include/periph_conf.h
boards/samr21-xpro/include/periph_conf.h

Anonymous initializes are hard to read and always a bit magic, get rid of that and spell out the struct members.
Also fix the indentation for conform to the coding style.
Only style changes

boards/sam*-xpro: fix style of PWM config

---

pkg/tinyusb/contrib/tinyusb.c
pkg/tinyusb/hw/hw_stm32_fsdev.c

This PR provides a small fix for STM32 boards that do not have internal D+ pullups or a dedicated GPIO on the board to simulate a USB disconnect. For such boards, the D+ GPIO must be temporarily configured as an output and pushed down to simulate a disconnect/connect cycle to allow the host to recognize the device. This is done correctly in `cpu/stm32/periph/usbdev_fs.c`, but not in the tinyUSB STM32 hardware driver. That means pressing the RESET button does not reset the USB connection.
Since `ztimer_msec` is used for the reset, the initialization of the hardware which has been done before the creation of the tinyUSB thread had to be moved to the tinyUSB thread implementation.
Use a blxxxpill board and flash `tests/pkg_tinyusb_cdc_msc`:
```
FEATURES_PROVIDED=tinyusb_device BOARD=bluepill …
```

pkg/tinyusb: fix the reset of the USB connection for STM32 boards without internal D+ pullup

---

release-notes.txt

This contains the current state of the release notes for discussion. Note that the release is not yet ready and backports will still be made. However, only bug fixes will be backported, hence the release notes will only receive minor additions.
Proof reading ...
None

release-notes.txt: add 2022.10 release notes

---

bors.toml

This PR configures bors to not include the whole PR description in its merge messages.
See https://github.com/RIOT-OS/RIOT/pull/18910#issuecomment-1342759338.

CI: bors.toml: set cut_body_after

---

.murdock

This PR implements "quick builds" (subset builds).
The logic is as following (checkmark for what was tested):
TBD: actual list of QUICKBUILD_BOARDS
bors tracking issue: https://github.com/RIOT-OS/RIOT/issues/18911

CI: implement quick build logic [backport 2022.10]

---

drivers/soft_spi/include/soft_spi_params.h
drivers/soft_spi/soft_spi.c

This PR contains some small bug and spelling fixes I noticed while reading the soft_spi code while using it as an example for writing my own driver. See the commit comments for details of each change.
I compiled, but did not run, tests/driver_soft_spi. The change is minor and verifiable by simply looking at the code.
- None

Fix soft spi bugs

---

pkg/lvgl/Makefile

Tested with success on native and stm32f429i-disc1
None

pkg/lvgl: bump to 8.3.4

---

pkg/minmea/Makefile

Only minor fixes since last time.

pkg/minmea: bump version

---

release-notes.txt

Here are the auto-generated release-notes. Please take a look!

release-notes.txt: add 2023.01 release notes

---

pkg/lvgl/Makefile

This PR bumps lvgl to [the latest release 8.3.5](https://github.com/lvgl/lvgl/releases/tag/v8.3.5), which is a minor release.
Tested related applications on native and noticed no regression:
```
BOARD=native make -C tests/pkg_lvgl clean all term 
BOARD=native make -C tests/pkg_lvgl_touch clean all term 
```
None

pkg/lvgl: bump to 8.3.5

---

drivers/mtd/mtd.c

If we overwrite a whole sector, don't perform a read-modify-write cycle.

mtd: add fast path to mtd_write_page()

---

pkg/u8g2/Makefile
pkg/u8g2/Makefile.include

The pkg hasn't been updated in 3 years.
Code still compiles, but I don't have a board to test / know which boards are supported. 
pending upstream fix https://github.com/olikraus/u8g2/pull/2101

pkg/u8g2: bump version

---

dist/tools/insufficient_memory/add_insufficient_memory_board.sh

- drop all bash specifics and use generic sh
- fix all shellcheck warnings
- use nproc instead of hard-coded `-j4`
- print output on (real) compilation error
Script should still work
None

dist/tools/insufficient_memory: Improve and clean up script

---

sys/include/net/fib.h

There are no known users outside unit tests.
Read
Alternative to #19300.

fib: document unused state

---

bors.toml

Reactivates the `check_labels` action (on `review`) and adds to block on "Process: missing approvals".
Let's add the >1 ACK label for testing once #19160 was merged.
Requires https://github.com/RIOT-OS/RIOT/pull/19160

bors.yaml: re-activate labels check + add block_labels

---

SUBSYSTEMS.md

We have this list now, but it's been sitting empty so I'll add myself to get the ball rolling.
For this list to have any value there needs to be some commitment behind it, so only add yourself. You can't make other people commit to things on their behalf.
I'm looking forward for more PRs to this list!

SUBSYSTEMS.md: add myself to the list

---

SUBSYSTEMS.md

Adding myself to the relevant parts of `SUBSYSTEMS.md` (also moving 6LoWPAN into GNRC... not sure why this was its own subsystem)
Read! ;-)

SUBSYSTEMS.md: Adding myself to the relevant parts

---

pkg/heatshrink/doc.txt
pkg/lz4/doc.txt
pkg/uzlib/doc.txt
sys/doc.txt

This adds a doxygen group to group together the different compression libraries we provide.
Read the generated doc:

sys/doc.txt: add sys_compression doxygen group

---

MAINTAINING.md

Add some tips & tricks for the quirks & features of Bors.
Read the document.

MAINTAINING.md: add some notes on Bors

---

SUBSYSTEMS.md

Adding myself to the SAM0 families and USB support.
None.
None.

SUBSYSTEMS.md: add myself to relevant parts

---

dist/tools/edbg/Makefile

Adds some more device IDs, always handy.
Flashing still works.

dist/tools/edbg: bump edbg version

---

doc/doxygen/src/mainpage.md

Shortcuts a referral on the wiki
Check the url in the doxygen main page
None

doxygen: Point to contributing.md document

---

sys/Makefile.dep
sys/net/application_layer/cord/ep/cord_ep_standalone.c

As the subject describes
The `examples/cord_ep` example should work as before.
None

cord: convert to ztimer

---

cpu/esp_common/esp-wifi/esp_wifi_netdev.c

There have been new disconnect reasons added in recent SDK revisions. Currently they cause a crash due to invalid memory access. This PR fixes those and also accounts for future extensions of the list by providing an easy way of adding new codes/gaps aswell as returning "UNKNOWN" for not yet known reasons to prevent crashes.
The new function has been tested by iterating over all possible 255 return codes. Also it has been verified that an ESP that previously crashed after being disconnected from a WPA2 Enterprise secured network no longer crashes.

cpu/esp_common: Add missing disconnect reasons

---

dist/tools/openocd/openocd.sh

This PR fixes the problem that OpenOCD v0.12 can't be used to flash application images for `riotboot`. Found when using OpenOCD v0.12 for GD32V and `riotboot`.
If `riotboot` is used, application images including their riotboot headers are flashed as binaries where the flash address has to be sepcified in `openocd` command. To determine the flash address, OpenOCD command `flash list` is used which returns a list of flash banks. With OpenOCD version v0.12, the format of the command output has been changed.
Until version OpenOCD version v0.11, command `flash list` returned something like (**without newlines**):
```
{name nrf51 base 0 size 0 bus_width 1 chip_width 1}
{name nrf51 base 268439552 size 0 bus_width 1 chip_width 1}
```
It was hard-coded in function `_flash_addr` to extract the 4th …

dist/tools/openocd: fix problems with riotboot caused by _flash_addr function for OpenOCD v0.12 

---

drivers/servo/timer.c

Not needed; code review will confirm that this is a comment only change.
None

drivers/servo: Fix typo in comment

---

pkg/lvgl/Makefile

This is a straight forward change. [lvgl 8.3.6](https://github.com/lvgl/lvgl/releases/tag/v8.3.6) was released today and is mainly a bug fix release.
I tested `tests/pkg_lvgl` and `tests/pkg_lvgl_touch` on native and both applications are working.
None

pkg/lvgl: bump to v8.3.6

---

pkg/qcbor/Makefile
pkg/qcbor/Makefile.include
pkg/qcbor/doc.txt

The current version of this package a master commit from 2020 while version 1.2 was release in January 2023. This PR bumps to this version and extend a bit the documentation with some notes on how to disable some features to shave some code. By default, the new version adds ~400B of ROM but when disabling some features it can be less than the version in master.
- Green CI
None

pkg/qcbor: bump to v1.2

---

release-notes.txt

This are the release notes for the 2023.04 Release. Please give it a look and make sure that your work in the last 3 months is present here.
- Read the document

release-notes.txt: add 2023.04 release notes [backport 2023.04]

---

pkg/lvgl/Makefile

This [version was released today](https://github.com/lvgl/lvgl/releases/tag/v8.3.7) and is a bug fix release.
Tested `tests/pkg_lvgl` and `tests/pkg_lvgl_touch` on native and it works as expected.
None

pkg/lvgl: bump to 8.3.7

---

makefiles/pseudomodules.inc.mk
sys/shell/Makefile.dep
sys/shell/cmds/Kconfig
sys/shell/cmds/gnrc_netif.c

This PR is a follow-up of #19466 and should address https://github.com/RIOT-OS/RIOT/pull/19466#issuecomment-1508700618
Untested yet.
The testing procedure in #19466 should be the same.
#19466

sys/shell/gnrc_netif: don't always build lora options with ifconfig

---

tests/README.md

This adds a small overview of the different subdirectories now in the tests directory
- Read the new documentation
- Check the links
- Check whether I missed any new subdirectory in the list.
Related to the excellent cleanup work started by @Teufelchen1 and @aabadie

tests/README.md: Add directory overview

---

doc/doxygen/src/mainpage.md

While looking at the documentation page, I noticed that the link to "supported hardware" was pointing to a largely outdated table in the wiki. The sentence right also looks weird and I fix that's just because of the use of `.` instead of `,`.
The link to the supported boards now points the main website where the list can be easily synced. I hesitated a bit with the board group page in the doxygen but I found it less nice for newcomers.
Just read
None

doc/mainpage: minor improvements

---

drivers/lpsxxx/lpsxxx.c

Perform computation directly in centi-degree-celsius to avoid floating point arithmetics. In addition, use scientific rounding in the division.
Beware: Code is untested. This should change results (much).
Fixes https://github.com/RIOT-OS/RIOT/issues/17486

drivers/lpsxxx: avoid float arithmetics

---

tests/drivers/epd_bw_spi_disp_dev/main.c

Code review should be sufficient
None

tests/drivers/epd_bw_spi_disp_dev: fix accidental use of FPU

---

tests/sys/bloom_bytes/main.c
tests/unittests/tests-bloom/tests-bloom.c

tests: remove unnecessary use of floating point

---

sys/shell/cmds/rtc.c

There is no need for the shell command to duplicate functionality that already exists in common code.
follow-up to https://github.com/RIOT-OS/RIOT/pull/19141

shell/rtc: use rtc_tm_normalize() to sanitize input

---

SUBSYSTEMS.md

SUBSYSTEMD.md: add @kaspar030 to core, Rust, build system, CI & timers

---

SUBSYSTEMS.md

I added myself to the subsystems I feel responsible for, as well as to C++. I'm not really a C++ developer or advocate, but I strongly believe that better C++ APIs that do take advantage of modern C++ features were sensible would benefit RIOT. So I thought I keep the seat warm until a real C++ nerd steps up and try to at least feel responsible to review PRs that improve C++ support.
Doesn't apply.
None.

SUBSYSTEMS.md: add @maribu

---

cpu/avr8_common/include/flash_utils_arch.h

See title.
Review the comment now makes more sense than before.
None

cpu/avr8_common: fix typo in a comment

---

cpu/atmega8/Kconfig
cpu/atmega8/Makefile
cpu/atmega8/Makefile.dep
cpu/atmega8/Makefile.features
cpu/atmega8/Makefile.include
cpu/atmega8/doc.txt
cpu/atmega8/include/cpu_conf.h
cpu/atmega8/include/default_timer_config.h
cpu/atmega8/include/periph_cpu.h

Splitted from:
- #19740
Tested on atmega8 with:
- #19755
Dependencies:
- #19752
- #19751

cpu/atmega8: new cpu

---

sys/od/od.c

This PR fixes a weird bug I've encountered when playing with `tests/periph/flashpage` on nRF53.
I wrote a string in the beginning of the last flash page  and read back its content:
```
2023-07-06 11:31:02,011 # main(): This is RIOT! (Version: 2023.07-devel-760-gf0dc0-cpu/nrf53/add_flashpage_support)
2023-07-06 11:31:02,013 # ROM flash read write test
2023-07-06 11:31:02,014 # 
2023-07-06 11:31:02,018 # Please refer to the README.md for further information
2023-07-06 11:31:02,018 # 
2023-07-06 11:31:02,021 # Flash start addr:             0x00000000
2023-07-06 11:31:02,023 # Page size:                    4096
2023-07-06 11:31:02,028 # Number of pages:              256
2023-07-06 11:31:02,028 # Number of first free page:    7 
2023-07-06 11:31:02,030 # Number of last free page:     255 
read …
```

sys/od: increase the size of str_pos variable

---

boards/esp32s3-devkit/doc.txt
boards/esp32s3-devkit/include/board.h
cpu/esp32/doc_esp32.txt
cpu/esp32/doc_esp32c3.txt
cpu/esp32/doc_esp32s2.txt
cpu/esp32/doc_esp32s3.txt

This PR fixes some documentation issues for ESP32x boards.
Green CI

boards/esp32: small documentation fixes

---

pkg/littlefs2/Makefile

This is a small release to add some features that help with the previous on-disk minor-version bump
https://github.com/littlefs-project/littlefs/releases/tag/v2.7.0

pkg/littlefs2: bump version to 2.7

---

tests/drivers/shtcx/main.c

On `master` we would simply repeat the previous string if an error occured
```
2023-08-02 15:33:55,171 - INFO #   Humidity [%rH]: 46.75
2023-08-02 15:33:57,186 - INFO # Temperature [°C]: 32.71
2023-08-02 15:33:57,186 - INFO #   Humidity [%rH]: 46.75
2023-08-02 15:33:59,201 - INFO # Temperature [°C]: 32.71
2023-08-02 15:33:59,202 - INFO #   Humidity [%rH]: 46.75
2023-08-02 15:34:01,201 - INFO # Temperature [°C]: 32.71
2023-08-02 15:34:01,201 - INFO #   Humidity [%rH]: 46.75
2023-08-02 15:34:03,217 - INFO # Temperature [°C]: 32.71
2023-08-02 15:34:03,218 - INFO #   Humidity [%rH]: 46.75
2023-08-02 15:34:05,233 - INFO # Temperature [°C]: 32.71
2023-08-02 15:34:05,234 - INFO #   Humidity [%rH]: 46.75
2023-08-02 15:34:07,233 - INFO # Temperature [°C]: 32.71
2023-08-02 15:34:07,233 - INFO # …
```

tests/drivers/shtcx: don't repeat last string on error

---

release-notes.txt

This are the release notes for the 2023.07 Release. Please give it a look and make sure that your work in the last 3 months is present here.
- Read the document

release-notes.txt: add 2023.07 release notes

---

tests/pkg/relic/Makefile

`tests/pkg/relic` is constantly failing in nightlies tests on samr21-xpro and llvm toolchain. It works on native though. So this PR is just skipping the test on that platform until a better solution is found.
Green CI
None

tests/pkg/relic: skip CI testing with samr21-xpro and llvm toolchain

---

pkg/lvgl/Makefile

As the title says. This is still a patch version so it only contains bug fixes. See details [here](https://github.com/lvgl/lvgl/blob/v8.3.9/docs/CHANGELOG.md).
Tested `tests/pkg/lvgl*` applications on stm32f428i-disc1 and native and both are still working.

pkg/lvgl: bump to v8.3.9

---

makefiles/pseudomodules.inc.mk
sys/shell/Makefile.dep
sys/shell/cmds/gnrc_netif.c
sys/shell/cmds/gnrc_txtsnd.c

Make gnrc_netif slightly smaller.
Build an application with `USEMODULE+=gnrc_txtsnd` and the command is still there and works.

sys/shell/gnrc_txtsnd: Move to separate module

---

dist/tools/backport_pr/backport_pr.py

More of a quick-and-dirty hack than an actual fix, but it should give us some time to properly fix it (I set the per_page to 100, currently there are 36 returned with that ;-))
Try backporting a PR with it ;-).
https://github.com/RIOT-OS/RIOT/pull/19984 was created using this fix.

backport_pr.py: increase entries per page for branches GET

---

tests/core/thread_cooperation/main.c

- add `static` qualifiers where sensible
- drop `volatile` qualifier that was incorrectly used
- add a comment on use of shared memory for inter-thread communication
<details><summary><code>make BOARD=nrf52840dk -j -C tests/core/thread_cooperation flash test</code></summary>
```
make: Entering directory '/home/maribu/Repos/software/RIOT/master/tests/core/thread_cooperation'
Building application "tests_thread_cooperation" for "nrf52840dk" with MCU "nrf52".
"make" -C /home/maribu/Repos/software/RIOT/master/pkg/cmsis/ 
"make" -C /home/maribu/Repos/software/RIOT/master/boards/nrf52840dk
"make" -C /home/maribu/Repos/software/RIOT/master/core
"make" -C /home/maribu/Repos/software/RIOT/master/core/lib
"make" -C …
```

tests/core/thread_cooperation: clean up test

---

cpu/cortexm_common/thread_arch.c

This should have been dropped in 06f0c14460a3260b076d12d393bfda3ab7d739d2
#6630

cortexm_common: drop TODO about Cortex-M4F FPU

---

drivers/include/mtd.h

see the title its no more no less
read doc

driver/mtd: mtd_init add documentation for return value

---

pkg/littlefs2/Makefile

Minor version number bump.
- Check if I copied the correct commit hash.
- Run the tests.
None

pkg/littlefs2: bump to v2.8.1

---

.murdock

Test change from bors to Github Merge Queues
I am too tired to think

.murdock: Switch to github merge queue

---

.murdock

ci: temporarily force full builds for merge queues

---

release-notes.txt

That time again, please check it out!

release-notes.txt: add 2023.10 release notes

---

release-notes.txt

That time again, please check it out!

release-notes.txt: add 2023.10 release notes [backport 2023.10]

---

drivers/lpsxxx/lpsxxx.c

Temperature values below zero should now be correct.
Fixes https://github.com/RIOT-OS/RIOT/issues/20093

drivers/lpsxxx: add missing sign extension

---

.gitignore

I try to keep my system nice an clean with venvs... More than once I added my venv so maybe it would be nice to add this in.
NONE :open_mouth:

.gitignore: Add venv

---

doc/doxygen/src/roadmap.md

Check the markdown and the gerenated doc
None

roadmap: extend peripheral drivers section

---

.mailmap

In `master`:
```
git log 3da3280930f74bc7c2b0df8b7f74974ccb59141c
commit 3da3280930f74bc7c2b0df8b7f74974ccb59141c
Author: Marian Buschsieweke <marian.buschsieweke@ovgu.de>
Date:   Wed Sep 4 13:15:15 2019 +0200
driver/cc110x: Fixed indent/alignment in doc
The Doxygen documentation blocks have not been correctly aligned. This commit
fixes this.
```
with this PR:
```
git log 3da3280930f74bc7c2b0df8b7f74974ccb59141c
commit 3da3280930f74bc7c2b0df8b7f74974ccb59141c
Author: Marian Buschsieweke <marian.buschsieweke@posteo.net>
Date:   Wed Sep 4 13:15:15 2019 +0200
driver/cc110x: Fixed indent/alignment in doc
The Doxygen documentation blocks have not been correctly aligned. This commit
fixes this.
```
None

.mailmap: map my old email to my new email address

---

cpu/sam0_common/include/periph_cpu_common.h
cpu/sam0_common/periph/gpio_ll.c

Fix some copy-paste bugs in the doc.
Check the generated doc / check the (trivial) diff
Pointed out by @dylad on Matrix

cpu/sam0_common/periph_gpio_ll: fix doc

---

.github/workflows/check-commits.yml
.github/workflows/tools-buildtest.yml

Fixes https://github.com/RIOT-OS/RIOT/issues/20287 and a similar issue for the "tools-build succeeded" ci job.

ci: ensure "xxx succeeded" properly fail

---

sys/net/application_layer/nanocoap/sock.c

Just make the output a bit more consistent.

nanocoap_sock: improve debug output

---

sys/include/event/periodic_callback.h

Accessing those struct internals is not very nice, so add getter methods for better ergonomics and future proofing.

event_periodic_callback: add getter for interval & count

---

cpu/stm32/Makefile.features
cpu/stm32/include/periph/cpu_spi.h
cpu/stm32/periph/spi.c

The test in `tests/periph/spi` should help here.
Fixes https://github.com/RIOT-OS/RIOT/issues/20227

cpu/stm32: implement periph_spi_reconfigure

---

core/lib/init.c

Don't disable interrupts just to enable them again.
Also, this makes the code a bit easier to understand.

core/init: clean up !core_thread init path

---

examples/rust-hello-world/Cargo.toml

This is a simple spelling error in a comment in the Cargo.toml

exmple > example in Cargo.toml comment

---

sys/newlib_syscalls_default/syscalls.c

This eagerly calls `__sinit()` instead of lazy initialization upon the first call to stdio (e.g. `puts()`, `printf()`). The issue is that without locking (as is currently the case for all RIOT platforms but ESP) two concurrent "first calls" may result in concurrent initialization of the same structure and data corruption.
Have two threads concurrently use stdio and the boot message disabled. This may result in data corruptions and crashes.
See https://github.com/RIOT-OS/RIOT/issues/20067 for details on a reproducible crashing app.
Fixes https://github.com/RIOT-OS/RIOT/issues/20067

sys/newlib_syscalls_default: fix race condition in __sinit()

---

README.md

This changes the full caps section titles to regular capitalization.
Read the readme

README: Change from all caps to regular

---

sys/net/gnrc/routing/ipv6_auto_subnets/gnrc_ipv6_auto_subnets.c

The wording was a bit confusing, clarify which subnets are meant.

gnrc/ipv6_auto_subnets: clarify documentation

---

examples/default/main.c

As trivial as the title says.
Green CI
None

examples/default: drop unused #include

---

doc/doxygen/riot.doxyfile
doc/doxygen/src/community-processes.md

Everything is in the title ;)
Docs should build fine!

doxygen: added community processes (import from Wiki)

---

sys/net/application_layer/gcoap/forward_proxy.c

Introduce an _cep_set_req_etag() helper function and drop the _cep_set_req_etag_len() helper to avoid use of preprocessor conditionals in the code.
The gcoap forward proxy should still work as before.
None

sys/net/gcoap/forward_proxy: clean up code

---

pkg/littlefs2/Makefile

Bump to the latest release, only minor changes: https://github.com/littlefs-project/littlefs/releases/tag/v2.9.2

pkg/littlefs2: bump to v2.9.2

---

CONTRIBUTING.md

Very simple modifications to sentence structure

doc: fix spelling in CONTRIBUTING.md

---

sys/include/net/l2filter.h
sys/include/net/netopt.h

This was the conclusion of https://github.com/RIOT-OS/RIOT/security/advisories/GHSA-4x44-qf4f-gp3v.
Read the docs for the module and the options ;-)

l2filter: mark module and related netopt options as experimental

---

boards/samd10-xmini/doc.txt
boards/samd20-xpro/doc.txt
boards/samd21-xpro/doc.txt
boards/same54-xpro/doc.txt
boards/saml10-xpro/doc.txt
boards/saml11-xpro/doc.txt
boards/saml21-xpro/doc.txt
boards/samr21-xpro/doc.txt

This PR updates some sam0-based boards documentation as some of them were quite outdated.
If you want me to add specific information, feel free to speak up.
Look at the rendered documentation by CI.
None.

boards: Update SAM0-based documentation

---

pkg/tflite-micro/Makefile

Recent PR #20683 introduced a race condition that can sometimes cause builds to fail. This is due to missing flatc options. This PR aims to provide those
See that build failures hopefully stop happening

pkg/tflite-micro: add proper options to flatc

---

boards/nucleo-f303ze/doc.txt
doc/doxygen/src/pinouts/nucleo-f303ze.svg

This PR add missing pinout from UM1947 for nucleo-f303ze.
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-f303ze.html
```
None

boards/nucleo-f303ze: add pinout 

---

sys/include/net/gnrc.h

While https://github.com/RIOT-OS/riot-os.org/pull/131 provided the files, the links were never re-assigned here.
The links should now work in the built documentation.
Follow-up on https://github.com/RIOT-OS/riot-os.org/pull/131

doc: fix links to GNRC master thesis

---

.mailmap

Does what it says on the label ;-).
My latest merge commits (e.g. aef06f4ed27a1e31e844c4) should be associated to me as all others with `git log`

mailmap: add my TU Dresden e-mail address

---

pkg/nanocbor/Makefile

A small PR to upgrade NanoCBOR package to the lastest version.
`make tests/pkg/nanocbor term` said _OK (1 tests)_
none

pkg/nanocbor - upgrade to last version

---

boards/nucleo-g070rb/doc.txt
boards/nucleo-g071rb/doc.txt
doc/doxygen/src/pinouts/nucleo-g070rb-and-g071rb.svg

This PR adds pinouts to the documentation pages for:
- `nucleo-g070rb`
- `nucleo-g071rb`
```
make doc
xdg-open doc/doxygen/html/group__boards__nucleo-g070rb.html
xdg-open doc/doxygen/html/group__boards__nucleo-g071rb.html
```
None

boards/nucleo-g070rb & g071rb: add pinouts to documentation

---

.github/workflows/release-test.yml
.github/workflows/test-on-iotlab.yml

See https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Should make the release tests run again once merged
None

gh-actions: bump upload-artifact to v4

---

.github/workflows/release-test.yml
.github/workflows/test-on-iotlab.yml
.github/workflows/tools-test.yml

See https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/ and also latest [release-tests run](https://github.com/RIOT-OS/RIOT/actions/runs/11189902402).
Confirm the new versions exist:
- https://github.com/webfactory/ssh-agent/releases
- https://github.com/actions/setup-python/releases
... and review. We can also start the worflows in question, if the reviewer thinks it is needed.
None.

gh-actions: bump deprecated packages 

---

drivers/include/periph/timer.h

The code examples in the doc contained an obvious bug that this PR fixes.
The bug should be obvious.
None

drivers/periph_timer: fix timer_query_freqs() doc

---

boards/samr34-xpro/dist/openocd.cfg

The file is needed for `make debug` to work with OpenOCD
`make BOARD=samr34-xpro flash debug` works
```
Open On-Chip Debugger 0.12.0
Reading symbols from /home/benpicco/dev/RIOT/examples/gnrc_networking/bin/samr34-xpro/gnrc_networking.elf...
Remote debugging using localhost:3333
sam0_cortexm_sleep (deep=0)
at /home/benpicco/dev/RIOT/cpu/sam0_common/include/periph_cpu_common.h:645
645	    cpu_pm_cb_leave(deep);
(gdb) 
(gdb) info threads
[New Thread 2]
[New Thread 3]
[New Thread 4]
[New Thread 5]
[New Thread 6]
Id   Target Id                                           Frame 
* 1    Thread 1 "main" (Name: main, Blocked mutex)         sam0_cortexm_sleep (deep=0)
at …
```

boards/samr34-xpro: add openocd.cfg

---

release-notes.txt

This adds the release notes for the 2024.10 release.
Please read and see if something is missing.

release-notes.txt: add 2024.10 release notes

---

release-notes.txt

This adds the release notes for the 2024.10 release.
Please read and see if something is missing.

release-notes.txt: add 2024.10 release notes [backport 2024.10]

---

pkg/littlefs2/Makefile

Bump version to [v2.10.1](https://github.com/littlefs-project/littlefs/releases/tag/v2.10.1)
`tests/pkg/littlefs2` still runs successful

pkg/littlefs2: bump version to v2.10.1

---

.mailmap

This maps all current and former email addresses to my primary contact.
Code review should be sufficient.
None

.mailmap: Add more e-mail addresses of maribu

---

doc.txt
doc/doxygen/riot.doxyfile

@mguetschow pointed out, and rightly so, that `RIOT_FILE_RELATIVE` is not documented. This fixes that.
`RIOT_FILE_RELATIVE` should show up in the rendered doc now.

doc: add documentation on RIOT_FILE_RELATIVE

---

release-notes.txt

Just updating the release notes that was in the 2025.01 release.
Should be simple...

release-notes.txt: add 2025.01 release notes

---

boards/arduino-due/doc.txt

This PR creates a proper board documentation for Arduino Due.
I might have forgotten stuff so feel free to add your nitpicks there.
A look at CI doc preview should do it.
None.

boards/arduino-due: update doc.txt

---

examples/networking/dtls/dtls-sock/README.md

Small PR - Commit 55fa531e02f9b386993d1e5e10a633c29d4d48be moved the `dtls-echo` example. This PR adjusts sources to changes

examples: update `dtls-echo` source

---

examples/networking/misc/sniffer/tools/README.md

The changes should be pretty self-explanatory.
Read the diff.
Found while reviewing #21244

examples/sniffer: update README

---

doc/doxygen/src/porting-boards.md

As proposed by kfessel in #21220, the best approach to update the `doc.txt` files with and without broken comment blocks is to convert them to Markdown files to eliminate the code blocks.
This PR updates the documentation in the `Porting Boards` tutorial and adds a small remark about the change to avoid confusion why existing confusion has a different format.
Also I added the syntax highlighting option, which Doxygen does not seem to render but GitHub does. `markdown` is not recognized by Doxygen either.
Current State:
With this PR in Doxygen:
With this PR in GitHub:
Generate the documentation and check that everything looks as it should.
This replaces #21252 and depends on #21255.

doc/porting-boards: Change example doc.txt to doc.md

---

MAINTAINING.md
README.md

Those lists are long gone (I think).

doc: remove and replace deprecated mailing lists

---

cpu/esp32/periph/gpio.c
cpu/qn908x/periph/i2c.c
dist/tools/codespell/ignored_words.txt
drivers/lis2dh12/include/lis2dh12_registers.h
drivers/pcf857x/pcf857x.c
examples/advanced/twr_aloha/README.md
pkg/uwb-core/include/dpl_syscfg/syscfg_uwb_rng.h
sys/include/net/sock/dtls.h
sys/include/net/sock/udp.h
sys/net/gnrc/network_layer/sixlowpan/frag/rb/gnrc_sixlowpan_frag_rb.c
tests/README.md

It looks like there are some spelling issues in master...
Here is the fix.
Green CI or run `./dist/tools/codespell/check.sh`

Fix spelling found by codespell

---

sys/include/psa_crypto/psa/crypto_sizes.h
sys/malloc_monitor/doc.txt
sys/psa_crypto/include/psa_ecc.h
sys/psa_crypto/psa_crypto.c
sys/psa_crypto/psa_crypto_algorithm_dispatch.c
sys/psa_crypto/psa_crypto_location_dispatch.c
sys/psa_crypto/psa_key_slot_mgmt/psa_crypto_slot_management.c

This should be a do-nothing, change nothing PR that just shortens long lines so that the static tests do not spuriously complain.
Compiled and ran the tests/sys/psa_crypto_hashes test case.
The complaints showed up in PR #21297.

psa_crypto: fold some long lines

---

tests/net/nanocoap_cli/Makefile
tests/net/nanocoap_cli/main.c
tests/net/nanocoap_cli/nanocli_client.c

Allow to build the nanoCoAP test with lwIP to run it on IPv4-only networks.
Run the test with `LWIP_IPV4=1`
```
2025-03-22 10:06:21,011 # > ifconfig
2025-03-22 10:06:21,016 # Iface ET0 HWaddr: f8:f0:05:a9:ec:19 Link: up State: up
2025-03-22 10:06:21,019 #         Link type: wireless
2025-03-22 10:06:21,024 #         inet addr: 10.53.12.146 mask: 255.255.0.0 gw: 10.53.0.1
2025-03-22 10:06:21,029 # Iface ET1 HWaddr: fc:c2:3d:22:12:3b Link: down State: up
2025-03-22 10:06:21,031 #         Link type: wired
2025-03-22 10:06:21,036 #         inet addr: 0.0.0.0 mask: 0.0.0.0 gw: 0.0.0.0
2025-03-22 10:06:23,855 # > ncget coap://coap.me/
2025-03-22 10:06:24,973 # /test
2025-03-22 10:06:24,974 # /validate
2025-03-22 10:06:25,007 # /hello
2025-03-22 10:06:25,035 # /blåbærsyltetøy
2025-03-22 …
```

tests/nanocoap_cli: allow to build with lwIP

---

doc/guides/managing-a-release/README.md

Just mention the release tests and that the release manager should look out for them in the weeks running up to the release.
Read

doc/managing-a-release: add looking out for release tests to preps

---

makefiles/docker.inc.mk

This updates the tagged container due to the merge of https://github.com/RIOT-OS/riotdocker/pull/255
Green CI
https://github.com/RIOT-OS/riotdocker/pull/255

makefiles/docker.inc.mk: bump tagged container

---

drivers/include/sen5x.h
drivers/sen5x/include/sen5x_constants.h
drivers/sen5x/include/sen5x_params.h
tests/drivers/sen5x/app.config.test

Since we did not want to bother @dprigoshij with further suggestions after the already very long PR in #19955, I created this PR to do some final touches and apply the `#pragma once` that we have settled on while the PR was being reviewed and remove the Kconfig for the tests, as this has become obsolete since the original PR was created.
Make sure that `drivers/sen5x` still compiles and the static-tests still run.
Applies #21335.

driver/sen5x: Small Fixups

---

tests/sys/shell/Makefile

Now that #19002 has been merged, the test is also working on `native`.
Run `tests/sys/shell` on `native` (CI will take care of this).

tests/shell: enable the test on native

---

pkg/lwip/contrib/sock/tcp/lwip_sock_tcp.c

As the title says. This may aid finding bugs both in lwIP or code using lwIP.
Flash and run application using lwIP (such as the lwIP tests apps, or the nanocoap examples) with `DEBUG_ENABLE` in the modified file set to `1`. There should now be debug output. Setting it back to `0` and the application should perform exactly as in `master`.
Split out of https://github.com/RIOT-OS/RIOT/pull/21048

pkg/lwip: Add DEBUG output to lwip_sock_tcp()

---

sys/include/atomic_utils.h

Add atomic bit set/clear for `unsigned int`.
These are just very simple mappings from `unsigned` to the fixed size counterparts. ~No type casting is involved~ With the exception  `atomic_bit_unsigned()`, there is no type casting s.t. everything can be checked by the compiler.
Completes #21429.

sys/atomic_utils: add bit set/clear helpers for unsigned int

---

cpu/sam0_common/include/cpu_conf.h
cpu/sam0_common/include/exti_config.h
cpu/sam0_common/include/gpio_ll_arch.h
cpu/sam0_common/include/mtd_sam0_sdhc.h
cpu/sam0_common/include/periph_cpu_common.h
cpu/sam0_common/include/sam_usb.h
cpu/sam0_common/include/sdhc.h
cpu/sam0_common/include/timer_config.h
cpu/sam3/include/periph_cpu.h
cpu/sam4s/include/periph_cpu.h
cpu/samd21/include/periph_cpu.h
cpu/samd5x/include/can_params.h
cpu/samd5x/include/candev_samd5x.h
cpu/samd5x/include/periph_cpu.h
cpu/saml1x/include/periph_cpu.h
cpu/saml21/include/periph_cpu.h

- Use `#pragma once`
- Indent preprocessor directives inside conditional compilation
- Drop unused `#include`s
The changes not influence the generated binaries in any way
None

cpu/sam*: update style to coding convention

---

.github/workflows/test_docs.yml

With the #21404 we included a CI build and deploy script, however, something that wasn't in the scope of that PR but should greatly enhance the CI is a simple build test.
The new workflow will be executed whenever changes are made to `doc/guides` or `doc/starlight` to catch any mistakes ahead of time.
I have included a negative and positive example commit within the PR to see this in action.
Since Github will not execute workflows added in PRs (for good reason). These are only viewable through my fork:
- Negative: https://github.com/AnnsAnns/RIOT/commit/e5d4f55aca1f7ef7c8271fa5515f130c1751e2c7
- Action run: https://github.com/AnnsAnns/RIOT/actions/runs/14757885078/job/41430797143 
- Positive: https://github.com/AnnsAnns/RIOT/commit/4d669410b809e6ba3875f5d89f88631ff75ab582
- Action run: …

.github/workflows: Guide Site Build Test

---

pkg/littlefs2/Makefile

Minor bugfix release, see changelog upstream: https://github.com/littlefs-project/littlefs/releases/tag/v2.11.0
CI will take care of it.

pkg/littlefs2: bump version to v2.11.0

---

examples/networking/gnrc/gnrc_lorawan/Makefile

I struggled a bit to figure out what to set and what to enable for `examples/networking/gnrc/gnrc_lorawan`.
I would consider this a tiny clean up. Maybe you agree.
split out from #21202

examples/gnrc_lorawan: simplyfy configuration a bit

---

doc/starlight/package-lock.json

Dependabot is currently tracking three potential security issues created by the Starlight dependencies:
I ran `npm audit fix` to update the `package-lock.json` file and apparently nothing broke.
Ping @AnnsAnns :)
Make sure `make doc-starlight` still works and does not show any errors:
With current `master`:
```
cbuec@W11nMate:~/RIOTstuff/riot-security/RIOT$ make doc-starlight
"make" -C doc/starlight dev
make[1]: Entering directory '/home/cbuec/RIOTstuff/riot-security/RIOT/doc/starlight'
Installing starlight...
changed 5 packages, and audited 477 packages in 872ms
224 packages are looking for funding
run `npm fund` for details
2 vulnerabilities (1 moderate, 1 high)
To address all issues, run:
npm audit fix
Run `npm audit` for details.
Starlight installed successfully.
Starting starlight …
```

doc/starlight: update `package-lock.json` to fix (potential) security issues

---

examples/lang_support/official/rust-async/Cargo.lock
examples/lang_support/official/rust-gcoap/Cargo.lock
examples/lang_support/official/rust-hello-world/Cargo.lock
sys/rust_riotmodules_standalone/Cargo.lock
tests/rust_minimal/Cargo.lock

Hello 🦄,
diff generated with `find -name Cargo.toml -exec cargo update --manifest-path "{}" --package riot-wrappers --package riot-sys ";"` according to https://github.com/RIOT-OS/RIOT/blob/master/doc/guides/managing-a-release/README.md?plain=1#L36
see what CI says
Natural followup for #21383

treewide: Update Rust dependencies

---

release-notes.txt

Hey hey 🦂,
please take a look at the notes and discuss if they are adequate.

release-notes.txt: add 2025.07 release notes

---

cpu/esp32/periph/i2c_hw.c
cpu/rpx0xx/periph/pwm.c
drivers/cst816s/cst816s_touch_dev.c
drivers/soft_spi/soft_spi.c
drivers/ws281x/esp32.c
pkg/cifra/psa_cifra/aes_ccm.c
pkg/driver_cryptocell_310/psa_cryptocell_310/aes_ccm.c
pkg/tinyvcdiff/contrib/tinyvcdiff_mtd/mtd.c
pkg/uwb-core/Makefile
pkg/uwb-dw1000/Makefile
sys/test_utils/netdev_eth_minimal/shell_commands.c
tests/drivers/dose/main.c
tests/drivers/enc28j60/main.c
tests/drivers/encx24j600/main.c
tests/drivers/esp_eth/main.c
tests/drivers/ethos/main.c
tests/drivers/sam0_eth/main.c
tests/drivers/stm32_eth/main.c
tests/drivers/w5100/main.c
tests/drivers/w5500/main.c
tests/net/gnrc_sixlowpan_frag_sfr_congure/mockup_netif.c
tests/net/gnrc_tx_sync/main.c
tests/net/ieee802154_hal/main.c
tests/periph/flashpage/main.c
tests/sys/usbus_msc/main.c
tests/sys/vfs_iterate_mount/main.c

This PR fixes compilation problems when NDEBUG is defined that were identified by PR #13266.
Compilation in CI should succeed.
Fixes problems found with PR #13266

tests: fix compilation problems with NDEBUG

---

doc/guides/index.md

As the title says. Just saw it while glancing over the guide site.
Have a close look at the diff :eyes:

guides/index: fix minor typo

---

sys/net/gnrc/netif/gnrc_netif.c
sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h
sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c
sys/net/gnrc/network_layer/ipv6/nib/nib.c

No functional changes, just clean up the code & debug output a bit.

gnrc/ipv6/nib: improve debug output, declutter code

---

doc/starlight/Makefile
doc/starlight/astro.config.mjs
doc/starlight/package-lock.json
doc/starlight/package.json

This (re-adds) the original image zoom that used to also be on https://riotguide.annsann.eu
While moving the documentation to the RIOT repository this was (accidentally) not included. The work of the plugins author is even used by Starlight itself in their own documentation https://github.com/withastro/starlight/blob/main/docs/astro.config.mjs#L4
This also fixes a minor prints mistake in the makefile that we didnt catch before in #21730

doc/starlight: Update dependencies, add image zoom, fix wrong prints

---

CODEOWNERS

Since I touched every file to some degree in doc I might as well feel responsible for it :sweat_smile:

CODEOWNERS: Add AnnsAnn to doc & rp2350
